#!/bin/bash
name="$1"
set -e
pdflatex -output-directory out "$name"
if [ -z "$quick" ]; then
    (cd out && BIBINPUTS=.. bibtex "$name")
    (cd out && makeindex "$name")
    pdflatex -output-directory out "$name"
    pdflatex -output-directory out "$name"
fi
