#!/bin/bash

: <<DOC

Usage:

    SCRIPT <input-file> ...

where:
- SCRIPT is the path to this script file
- Each <input-file> is something that Pandoc can read.

DOC

set -o errexit
set -o nounset
set -o pipefail

cd ~/work/edom.github.io

make -f _pandoc/Makefile env=dev org_files=$1 install
