#!/bin/bash
# Insecure legacy code
openssl enc -d -bf -md md5 -in keyring.e -out keyring \
    && vim keyring \
    && openssl enc -bf -md md5 -in keyring -out keyring.e \
    && shred keyring \
    && sync \
    && rm keyring
