#!/bin/bash
LINE="$(openssl enc -d -bf -in keyring.e | grep "$1" | grep "$2")"
SITE="$(echo "$LINE" | cut -f1 '-d ')"
USER="$(echo "$LINE" | cut -f2 '-d ')"
PASS="$(echo "$LINE" | cut -f3 '-d ')"
echo "$SITE : $USER"
echo -n "$PASS" | xclip -in -sel clipboard
