#!/bin/bash

# This rebuilds the site and overwrites edom.github.io.
# You should be careful not to publish unpublished content.

set -o errexit
set -o nounset
set -o pipefail

# We specify --destination so that we don't clash with a running "jekyll serve".
# However, you should make sure that no "jekyll serve" is running.

JEKYLL_DIR=_site_publish

jekyll() {
    bundle exec jekyll "$@"
}

export JEKYLL_ENV=production

cd ~/work/edom.github.io
jekyll clean --destination "./${JEKYLL_DIR}"
jekyll build --destination "./${JEKYLL_DIR}"
make -j4 -f _pandoc/Makefile env=prod html_dir=_pandoc_out/prod jekyll_dir=_site_publish install

# Spawn a subshell to confine the GIT_* exports.

(
    set -o errexit
    set -o nounset
    set -o pipefail

    cd ~/work

    export GIT_DIR=tmp/edom.github.io.git
    mkdir -p "$GIT_DIR"
    git init --bare
    git config user.name 'Erik Dominikus'
    git config user.email 'software@spacetimecat.com'

    # https://stackoverflow.com/questions/25172470/git-error-fatal-git-work-tree-or-work-tree-directory-not-allowed-without
    export GIT_WORK_TREE="edom.github.io/${JEKYLL_DIR}"
    git add --all .
    git commit -m "$(date -Iseconds)" || true
    git push -f git@github.com:edom/edom.github.io.git master

)
