#+TITLE: Towards the abduction of the simplest theory that explains paranormal evidence
#+DATE: 2019-09-07 00:00:00 +0700
#+PERMALINK: /anomaly-theory.html
* Meta-research directions
** About this document
We /have/ enough evidences of anomalies; it's time to /explain/ them with a testable theory.

This document discusses souls and the phenomenons associated with them,
such as anomalous cognition, reincarnation, afterlife,
out-of-body experience, near-death experience,
subjective experience (first-person point of view), and so on.
** Directions
Whenever we feel lost in our paranormal research, answering these meta-questions will give us some directions:
- How does evidence /constrain/ (narrow down) the space of hypotheses that attempt to explain paranormal phenomenons?
- What /key/ question should we ask next in order to formulate a /crucial/ experiment
  whose result would most strongly constrain the hypothesis space?
- How can /mathematics/ help, if it can help at all?

We research souls /indirectly/ as we research stars,
because it is difficult to experiment with souls as it is with stars.
Thus we mostly /observe/ and /theorize/.

#+BEGIN_QUOTE
Astronomers cannot hold stars in their hands and geologists cannot go back in time,
but both scientists can learn a great deal about the universe through observation and comparison.
 [fn::<2019-09-11> https://evolution.berkeley.edu/evolibrary/misconceptions_faq.php#e1]
#+END_QUOTE

We also research souls as we do /chemistry/.
The object of study is complex and we do not know what it actually is;
we only know some of its properties and some phenomenons associated with it.
Our current knowledge of /souls/ is similar to our past knowledge of /phlogistons/.
We need a psychic "Lavoisier" to discover the psychic "oxygen" and replace the psychic "phlogiston combustion" theory with psychic "oxygen combustion" theory.
We do not know what a soul is as we did not know what a phlogiston is.
We merely /posit/ their existence and assume that they cause the phenomenons that interest us,
and then we set out to find their properties.

The primary method of reasoning in this research is /abductive/:
Find the simplest theory that explains all known evidence.

We should consider /non-American/ parapsychologists, such as Russian and Japanese ones.
In 2015, Edwin C. May said that Russia was more open to parapsychology than America is.[fn::7:30 <2019-09-10> An Interview with Edwin C May, Ph.D. https://www.youtube.com/watch?v=ZZwZKpsgMow]

https://www.parapsych.org/blogs/jmishlove/entry/1285/2019/6/parapsychology_in_russia_with_loyd.aspx

https://www.newdawnmagazine.com/articles/the-changing-face-of-russian-psi-research

Targ's 2012 book \cite{targ2012reality}

It seems Targ has an "ESP Trainer" mobile app[fn::http://www.espresearch.com/iphone/],
but it seems to be iPhone-only.
* My experiments and drafts?
** On the word "energy"
If energy is the ability to do work, then psychic energy is the ability to do psychic work.

Psychic energy gradient?

Psychic energy conservation?
** Materials
Targ 2012 book \cite{targ2012reality}.

Conscientology and projectiology[fn::<2019-09-08> https://www.iacworld.org/what-is-conscientiology-projectiology/]

Carl Sagan thinks that there is considerable preliminary evidence for some paranormal phenomenons.[fn::<2019-09-08> https://www.iacworld.org/top-3-psychic-anomalies-according-to-carl-sagan/]

CIA collection of news articles of police testimonies for psychics
 [fn::<2019-09-13> https://www.cia.gov/library/readingroom/document/cia-rdp96-00788r002000240037-5]

35% of reincarnated children has birth marks that correspond to the mode of death
 [fn::<2019-09-15> Video Nugget: A Neuroscientist Looks at Reincarnation with Marjorie Woollacott https://www.youtube.com/watch?v=nB_KdB-zzSE]

The gold leaf lady.[fn::https://psi-encyclopedia.spr.ac.uk/articles/gold-leaf-lady]
 [fn::<2019-09-15> Video Nugget: A Most Unusual Psychic Gift with Stephen E. Braude https://www.youtube.com/watch?v=HLt7F00WOk8]
It seems that people with difficult marriages or emotional disturbances experience more psychokinetic phenomenons.

James Randi's reputation is not perfect.[fn::<2019-09-15> https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Jaime_Licauco.html]

The difference between apport and materialization is that apport is the anomalous movement of existing object whereas materialization is the creation of a new object.
 [fn::<2019-09-15> https://psi-encyclopedia.spr.ac.uk/articles/gold-leaf-lady]

Why does a grounded Faraday cage enhances ESP if ESP is not an electromagnetic phenomenon?
 [fn::<2019-09-19> Video Nugget: A Faraday Cage for Amplifying ESP with Charles Tart https://www.youtube.com/watch?v=3kJuUtPJsqI]
Where is the paper?
* Grouping evidence for hypothesis formation
An /anomaly/ is a strangeness, an unexpected phenomenon, something that goes against common sense.

Anomalies lead to truth.
Anomalies enable us to revise our belief.

What evidence do we have,
what hypothesis does it raise,
and what question should we ask to test that hypothesis?

By this grouping, I hope to formulate the next /crucial experiments/.

The theory must parsimoniously /explain/ all evidence in the previous section, namely:
past-life carry over, anomalous cognition.

We should not be too eager to invoke quantum physics.
Parapsychology itself already makes people think we're lunatics.
Invoking quantum physics will make people think we're deranged lunatics.

Perhaps everyone is psychic but their conscious mind /blocks/ their subconscious mind.
** On the /ontology/ of paranormal things
Bernardo Kastrup proposes a solution to the mind-body problem.
He proposes an ontology that is "more parsimonious and empirically rigorous" than mainstream ontologies are.
 [fn::<2019-09-13> https://www.freewiki.eu/en/index.php?title=Bernardo_Kastrup]
 [fn::<2019-09-13> What Can We Learn From Bizarre Phenomena? with Bernardo Kastrup https://www.youtube.com/watch?v=tWpKB7n4dRs]
 [fn::<2019-09-13> https://www.bernardokastrup.com/p/papers.html]
The key is the brain activity of people with /dissociative identity disorder/.
 [fn::<2019-09-13> https://blogs.scientificamerican.com/observations/could-multiple-personality-disorder-explain-life-the-universe-and-everything/]

Its simplicity is genius?

It has deep implications.
If it becomes mainstream, we will witness a paradigm shift.

It explains all paranormal phenomenons: reincarnation, anomalous cognition, psychokinesis, and so on.

Perhaps it also answers Brian D. Josephson[fn::http://www.tcm.phy.cam.ac.uk/~bdj10/]'s "mind-matter unification project".

The difference between Kastrup and other philosophers is that his theory is based on /empirical evidence/,
whereas other theories are based on thought experiments.
Thus, I think we can just read Kastrup directly, skip Chalmers 2018 \cite{chalmers2018meta},
and skip the Part IV of a 2001 thick book \cite{moreira2011exploring}.
Or perhaps I'm just in a honeymoon with a shiny new thing.

What is it like, the subjective experience of the cosmic consciousness?

Telepathy, Clairvoyance, and Precognition are instances of Psychic Ability.

Anomalous Perception is my synonym for Extra-Sensory Perception,
because Perception is the act of /interpreting/ sensory inputs,
and thus perception implies sensors, by definition;
it is just that we don't know the sensor,
in the same way we can use the skin to feel pressure without knowing how the skin transduces pressure into sensory inputs for the brain.

Sensing is the transduction of a phenomenon into a signal.

Ghost is a subclass of Spirit.

Poltergeist is an instance of Paranormal Phenomenon.

Kruth[fn::<2019-09-07> https://tunsasays.wordpress.com/about-this-site/]: "Parapsychology is the scientific study of five specific phenomena."

https://rsbakker.wordpress.com/2014/03/18/the-ontology-of-ghosts/

Materialism is false? What are these trying to say?
2016 article "Why Materialism Is False, and Why It Has Nothing To Do with the Mind"
 [fn::https://www.cambridge.org/core/journals/philosophy/article/why-materialism-is-false-and-why-it-has-nothing-to-do-with-the-mind/5DC675B901E2F68E82643B88EE468EAE]

Are materialism and subjective experience compatible?
Problem of other minds?

Evidence of survival after bodily death:
Apparently dead people can play chess and answer questions.[fn::<2019-09-14> The Chess Game from Beyond the Grave https://www.youtube.com/watch?v=g1S6y1-Pz_w]

Applied precognition research in 2016[fn::<2019-09-14> The Practical Applications of Precognition, Part Two: Ongoing Research, with Marty Rosenblatt https://www.youtube.com/watch?v=YszAl5_il4c]

There are several remote viewing /protocols/.

Anomalous cognitive information transfer is not limited by the speed of light.
The remote viewing of the moons of Jupiter by Edwin C. May et al.
 [fn::<2019-09-14> 10:19 in Researching Anomalous Cognition with Edwin C. May https://www.youtube.com/watch?v=-ybMdxvMSbI]
He also knows a remote-viewing /disbeliever/ who does remote viewing well.
 [fn::<2019-09-14> 21:54 in the same video]

Evidence of macropsychokinetic physiology, materialization, apports, "permanent paranormal object"
 [fn::<2019-09-14> The Apports of Amyr Amiden with Stanley Krippner https://www.youtube.com/watch?v=RUTzjK_GvdA]
 [fn::<2019-09-14> https://psi-encyclopedia.spr.ac.uk/articles/amyr-amiden]

Reincarnation:
Stevenson seems to be quite rigorous.[fn::<2019-09-14> How Researchers Approach Reincarnation with James G. Matlock https://www.youtube.com/watch?v=Ds10X_vVEpI]

Joseph Gallenberger used Las Vegas casinos as his parapsychology laboratory.[fn::<2019-09-14> Cultivating Psychokinesis, Part One: A Personal Journey, with Joseph Gallenberger https://www.youtube.com/watch?v=Tx3nCQMKHfM]

Can we get better at remote viewing by exercise/training, or is it special talent by birth?

"Remote viewing" is a misnomer; "remote perception" is more appropriate.
"Remote sensing" has already been used to mean something else.
** On multi-location and teleportation
bi-location/multi-location (being at several places simultaneously)

Body doubles (look-alikes) are not psychic.

An Indonesian bus got into the middle of a jungle without leaving any trails (such as tire marks or broken woods)?
** On things related to /afterlife/
Keywords:
afterlife, super-survival, near-death experience, reincarnation, xenoglossy, past-life memory, past-life carry-over,
instrumental transcommunication, mediumship, possession, thanatology.

I define "afterlife" as all subjective experience after bodily death.

Apparently, bodily death is not eternal oblivion.

There are several studies and accounts of /near-death experience/ (NDE).

There are studies[fn::http://www.nderf.org/]:
Pim van Lommel's study of consciousness after clinical death
 [fn::<2019-09-12> https://en.wikipedia.org/wiki/Pim_van_Lommel]
 [fn::<2019-09-12> https://en.wikipedia.org/wiki/Near-death_experience],
Sam Parnia's AWARE study \cite{parnia2014aware}
 [fn::<2019-09-12> https://en.wikipedia.org/wiki/Sam_Parnia]
 [fn::<2019-09-12> AWARE study initial results are published! https://iands.org/news/news/front-page-news/1060-aware-study-initial-results-are-published.html].

There are individual accounts:
Elizabeth Krohn
 [fn::<2019-09-12> The Power of the Near-Death Experience, Part 1 with Elizabeth Krohn https://www.youtube.com/watch?v=S_Yomwcod3E]
 [fn::<2019-09-12> The Power of the Near-Death Experience, Part 2 with Jeffrey Kripal https://www.youtube.com/watch?v=-qsLltCUetc].

Dying, near-death experiences, thanatology:
- <2019-09-12> From life to death, beyond and back - Thomas Fleischmann - TEDxTUHHSalon https://www.youtube.com/watch?v=mMYhgTgE6MU

Can we explain these phenomenons without resorting to souls?
Reincarnation (past-life carry-over),
super-survival (life after clinical death),
instrumental transcommunication (telephone calls from the dead, etc.).

/Xenoglossy/ is the anomalous acquisition of language.

Semkiw
 [fn::<2019-09-13> https://reincarnationresearch.com/walter-semkiw/]
 [fn::<2019-09-13> Reincarnation, Part Two: Cases of Xenoglossy, with Walter Semkiw https://www.youtube.com/watch?v=h2mmEYEzwjo]

Here I sloppily use "soul" and "spirit" as synonyms, and I use them to mean the non-material part of living beings.
Our biggest problem is not this sloppiness, but our not knowing what souls are.
 [fn::https://www.etymonline.com/word/soul#etymonline_v_23918]
 [fn::https://www.etymonline.com/word/spirit#etymonline_v_24031]

I define "reincarnation" as any phenomenon that a layman would likely suspect to be past-life carry-over.
It is not Buddhist reincarnation.
My definition is more general than Buddhist reincarnation.
My definition does not imply souls.

TODO Mishlove's interviewing Semkiw (at least four parts).

I want to test the /locality/ and /non-linearity/ of reincarnation.

It would be nice if we could extract the testable parts out of
Tan Kheng Khoo's speculations about Buddhist reincarnation.[fn::<2019-09-11> http://www.kktanhp.com/reincarnation_htm.htm]

Afterlife experiments?
 [fn::https://listverse.com/2009/01/29/top-10-bizarre-afterlife-experiments/]
 [fn::http://www.theoccultmuseum.com/5-chilling-experiments-attempted-prove-existence-afterlife/]
The Future Life Institute proposes an experiment purported to prove reincarnation by 2050.
 [fn::<2019-09-08> http://www.futurelifeinstitute.org/2013/psd/Experiment-Web.pdf]

Stafford Betty's instrumental transcommunication.

Reincarnation patterns[fn::<2019-09-19> Patterns Found in Reincarnation Cases with James G. Matlock https://www.youtube.com/watch?v=mKBgiuqzj04]
*** On its /non-linearity/
A reincarnation (past-life carry-over) is either /single/ or /multiple/.

A multiple reincarnation is either /overlapping/ or /non-overlapping/.

Is there evidence for /multiple/ reincarnation?

Is there evidence for /multiple-and-overlapping/ reincarnation?

Is there evidence for /non-linear reincarnation/?

http://nhne-pulse.org/past-life-research/

Anyone can corroborate this Mira Kelley's client John?[fn::https://mirakelley.com/meet-mira/praise/mira-kelleys-beyond-past-lives/]
*** On its /locality/
The /reincarnation locality hypothesis/ states that a person is born /near/ where he died in his previous life.
 [fn::Tongren Yuye 2008 calls this the "principle of the locality of the soul" in the English translation; <2019-09-08> https://www.fyears.org/2010/06/how-to-prove-reincarnation-with-statistical-experiment.html]
 [fn::original in Mandarin Chinese <2019-09-08> https://www.geekonomics10000.com/178]

It can be tested with the records of Stevenson & Tucker.

I have not verified the records myself; I am presuming their honesty.

Perhaps there is a /spacetime distance limit/
between the birthplace of a person and the deathplace of his previous life.
By "birthplace", we mean the point in spacetime, not only the spatial aspect of the point.

Soul theory explanation:
Perhaps souls conserve energy and thus tries to stay still unless there is a reason to move, just like humans.

The most compelling /evidence/ of memory of past life is the thousands of records meticulously collected, verified, and corroborated by Ian Stevenson and Jim Tucker.
Some children can tell some /facts/ about a specific deceased person that,
according to our common sense, can only be known by the deceased person alone
because he has never told those facts to anyone else.
By "facts", we mean assertions whose truth can be corroborated with historical records or living relatives.
The facts are so specific that an impostor is astronomically unlikely to guess them correctly.
The facts are also not written, recorded, or told, so it does not use known communication channels.
There is a lot of evidence of memory of past lives.
 [fn::<2019-09-08> https://upliftconnect.com/past-lives/]
 [fn::<2019-09-08> https://www.gaia.com/article/incredible-evidence-for-remembering-past-lives]
 [fn::<2019-09-08> https://www.consciouslifestylemag.com/reincarnation-stories-proof-past-life/]
 [fn::<2019-09-08> https://www.rd.com/true-stories/chilling-reincarnation-stories/]
 [fn::<2019-09-08> https://www.google.com/amp/s/www.psychologytoday.com/us/blog/feeling-too-much/201412/children-who-seemingly-remember-past-lives%3famp]
 [fn::<2019-09-08> https://uvamagazine.org/articles/the_science_of_reincarnation]

Past-life memory seems to fade as one grows into adulthood. \cite{haraldsson2012persistence}

By "memory of past life", I mean memory of /subjective experience/ of past life.

Thus it should also be possible to experience life from other people's point of view;
it should be possible to experience other people's qualia (subjective experience);
it should be possible to /swap souls/, be it temporary or permanent.

That evidence shows that /our common sense is wrong/,
that our understanding of life and death is wrong,
and that, when a man dies, he does not go to heaven, but neither does he disappear into oblivion.

Come to think of it, our common sense (Western rationality common sense) is not so common,
and is rather exceptional than common.

Can one soul reincarnate into two bodies?
Can two people have memory of one deceased person?
If yes, then soul is ideal (software) because it can be copied but not moved.
If no, then soul is material (hardware) because it can be moved but not copied.
I propose that we search for two people who recall the same deceased person.
I hypothesize that we will not find any such pair.

Is it important to ask why the subjects are mostly children between 2 and 5 years old?
Adults may censor themselves to conform to social norms.

A dying soul may be like a dying star:
They explode, reverberating through spacetime.

Now that we have established the existence of the phenomenon,
we ask: /How do they remember their past lives?/
How does it work?
What is the mechanism?

Why does the old soul get diluted as the new person grows into adulthood?

Does the old person has to be willing to reincarnate?

Hypothesis:
Past-life regression may happen due to a /mixing of souls/.
Memory may exist without soul.
Memory may infect souls as prions infect cow brains.

Memory can persist outside brains.
For example, a hard disk has memory.
A capacitor has memory.
Every stateful system has memory.

Souls may broadcast signals that reverberate in the Universe,
and the reverberation may later be picked up by another soul?

Something else?

More interestingly, Stevenson found some /patterns/ in reincarnation.
 [fn::<2019-09-08> https://psi-encyclopedia.spr.ac.uk/articles/patterns-reincarnation-cases]
*** On super-survival
/Super-survival/ is mental survival of bodily death.

Keywords: life after death, afterlife.

Elisabeth Targ (daughter of Russell Targ)[fn::<2019-09-12> The Life, Death, and Afterlife of Elisabeth Targ with Russell Targ https://www.youtube.com/watch?v=q_c-V472wl0]

What happens after we die?

Compare:
- https://tunsasays.wordpress.com/2015/04/23/the-survival-hypothesis-a-very-brief-discussion/
*** On mental property transference in organ donations
There are some claims and disclaims that some mental properties are transferred from organ donors to recipients.
Lowth 2016:
Positive https://listverse.com/2016/05/14/10-organ-recipients-who-took-on-the-traits-of-their-donors/
Bunzel et al. 1992: Negative or inconclusive.
Does changing the heart mean changing personality? A retrospective inquiry on 47 heart transplant patients.
https://www.ncbi.nlm.nih.gov/pubmed/1299456
** On /psychic abilities/
Especially on its nature-versus-nurture issue.
*** On its /inheritance/
Why is Stevenson's psychic children mostly male, but adult psychics are mostly female?
I hypothesize that it is because our society expects men to be rational and materialistic,
because our society forces men to numb their feelings.
I call this "arrogant Western rationality".
It includes gender binarism.

We need to combine Western thinking and Eastern feeling.
The most rational solution is to kill every human.

If psychic ability is the phenotype, what is the underlying genotype?

Where is Radin & Wahbeh's results?[fn::https://noetic.org/research/genetics-of-psychic-ability/]
Is it inherited via the father or the mother or both?
What is the ratio of psychic offsprings to non-psychic offsprings?
Is the inheritance Mendelian?

It seems that the children with past-life memory in Stevenson's records have parents /without/ psychic abilities.

Is there a /genetic/ basis of psychic ability?
Is it inherited via normal genetics?

What?
 [fn::http://www.globalpsychics.com/family-genetics-and-being-psychic/]
 [fn::https://noetic.org/blog/the-genetics-of-psychic-ability-take-our-newest-survey/]
 [fn::https://psychicelements.com/blog/are-psychic-abilities-hereditary/]

On the genetic basis of psychic abilities?

It seems that psychic abilities run in families.
 [fn::https://psychicelements.com/blog/are-psychic-abilities-hereditary/]
 [fn::https://www.anthonstmaarten.com/blog/psychic-dna-nature-or-nurture]

Does it have genetic basis?
Hereditary?
Inherited trait?

https://noetic.org/research/genetics-of-psychic-ability/

If psychic abilities are inherited, then they may have genetic basis.
If there does not seem to be any genetic basis,
then dualism may be true and there may be mental genetics we don't yet know.

Is the non-psychic person doomed?
Is being non-psychic like being a lactose-intolerant,
in the sense that you /just can't/ produce the enzyme because you were born without the necessary machinery
(unless you underwent some gene therapy perhaps)?
*** On its prevalence in people with /unusual brains/
Is psychic ability more prevalent in people with unusual brains such as those with synesthesia, autism, epilepsy, and so on?

Head trauma, autism, psychic
http://content.time.com/time/health/article/0,8599,1868287,00.html

Edwin C. May hypothesizes that people with /synesthesia/ are more likely to have precognition ability,
and that there is a /psychic organ/ or a /psychic sensor/ (he uses the analogy "psychic retina").
 [fn::<2019-09-09> How Precognition Works with Edwin C. May https://www.youtube.com/watch?v=37tPK3iwcZ4]

But this seems to conflict with super-survival.
If psychic ability does not require a brain (some dead people have psychic ability),
why is psychic more prevalent in people with unusual brains?
*** On the learnability of psychic abilities
Can one learn to be psychic?
Conflicting opinions:
- Angela Moore: "Psychic ability can not be learned. You're either born with the gift or you aren't"[fn::https://www.psychicreviewonline.com]
- Carpenter 2004 psi theory/model

It disheartens me to hear people say that psychics are born and not made.
*** On the effects of the mother's emotional state while conceiving her baby
It seems that stressing the pregnant mother may affect the epigenetics of the unborn baby.

Dutch famine experiment.

What if the mother is physically unstressed but mentally stressed?
That is, what if we give the mother the perfect nutrition, but we mentally torture the mother?
What will happen to the unborn baby?
What will the baby become?

https://www.jashow.org/articles/hereditary-coherence-and-other-forms-of-transference/

*** On using babies and animals as sensors
If babies are more sensitive to paranormal phenomenons, then we can use babies as paranormal sensors!
*** On psi-favorable and psi-antagonistic conditions
Terms: /psi-favorable/ and /psi-antagonistic/. \cite{braud2002psi}
Also: /psi-conducive/.

Hypothesis: Strong emotions promote psychokinesis.
Anger?
Fear?
** On the mainstream aspects of /anomalous cognition/
From physics and neuroscience point of view.

Related topics: presentiment.

There are reports of /anomalous cognition/
in which some people see dead people and know some details about those dead people.
For example, Brian Weiss had a patient named Catherine who anomalously told him details about his dead relatives
 [fn::Dr. Brian Weiss: Past-Life Skeptic to Past-Life Expert | SuperSoul Sunday | Oprah Winfrey Network https://www.youtube.com/watch?v=qQAgiP8zQ6M].

The "precognition" subreddit[fn::https://www.reddit.com/r/precognition/].

Does precognition imply retrocausation?

I hypothesize that all forms of anomalous cognition is caused by /the same mechanism/.
Anomalous cognition includes recalling past-life memory, telepathy, precognition, possession, and mediumship.

To know whether it is really cognition (that is, whether the subject actually knows something),
we select the subject's anomalous claims that we are sure the subject could not have known conventionally, and then we verify them.

/Presentiment/ is an anomalous cognition.
People reacts to a scary stimulus /before/ they get the stimulus itself.

"sweaty palm detector"[fn::<2019-09-10> Correlates of Anomalous Cognition with Edwin C. May https://www.youtube.com/watch?v=Y5X4_DXGX60]

Edwin C. May[fn::<2019-09-10> Correlates of Anomalous Cognition with Edwin C. May https://www.youtube.com/watch?v=Y5X4_DXGX60]

What is implied by the absence of a stable correlation between neural activity pattern and anomalous cognition?
Does it mean that anomalous cognition does not require the brain?
Or does it mean that there is a non-material part of brain that we don't know?
Or does it mean that our understanding of materialism is incomplete?
For example, we know the existence of dark energy and dark matter,
but we don't know what they actually are.

On remote viewing's working better with large /entropy/ changes

From Edwin C. May.
 [fn::6:08 <2019-09-10> An Interview with Edwin C May, Ph.D. https://www.youtube.com/watch?v=ZZwZKpsgMow]
 [fn::<2019-09-11> Entropy and the Nature of Time with Edwin C. May https://www.youtube.com/watch?v=yC9EPkeEwvY]

It is easier to remote-view events in which there is a large entropy change, such as nuclear bomb detonation.

"Entropy gradient".

"Entropy bombs" are analogous to flashlights.
Senses are better at sensing /changes/ in input than sensing constant input.
Perhaps psi-sensor senses entropy.

On the /decision augmentation theory/ of May, Utts, & Spottiswoode.

What does the theory predict?
How do we test it?

Does anomalous cognition require a /sensor/ in the brain?
Does it have /neural correlate/?

We usually assume that, in order for a man to ken something,
he has to perceive an image of it with his senses.
** On verifying premonitions
A /central premonitions registry/ enables us to verify premonitions.
- 1968, http://www.weirduniverse.net/blog/comments/central_premonitions_registry
- 2017, https://scry.cloud/ (no longer open)
** On magnetism
Spottiswoode's sidereal correlation research;
presence of magnetite in the brain;
human magnetoreception?
We know pigeons do.[fn::<2019-09-10> Correlates of Anomalous Cognition with Edwin C. May https://www.youtube.com/watch?v=Y5X4_DXGX60]

It may sound crazy, but it seems that the effect strength of psi depends on the position of the Earth relative to the stars.
** On poltergeists, psychokinesis, mediumship, healing, seances, and materialization
Anomalous actuation.

Anomalous sensor and anomalous motor/actuator.

Brains have sensors and actuators.

Keywords: psychokinesis, telekinesis, mind-over-matter.

PK Man (Ted Owens)'s predictions and claims.
 [fn::<2019-09-12> The Case of the PK Man with Stephen E. Braude https://www.youtube.com/watch?v=1ZXNccfg6uc]
 [fn::<2019-09-12> Reflections on The PK Man with Debra Lynne Katz https://www.youtube.com/watch?v=Kv6ARS5Hl9U]
 [fn::<2019-09-12> "Most of the information in this article is drawn from a biography of Owens by Jeffrey Mishlove: 'The PK Man: A True Story of Mind Over Matter'." https://psi-encyclopedia.spr.ac.uk/articles/ted-owens]

If Ted Owens's goal was to spread his knowledge, why didn't he use his powers to get rich first to make it easier?

Dani Caputi has a psychokinetic weather manipulation experiment
 [fn::<2019-09-12> Psychokinetic Weather Influence with Dani Caputi https://www.youtube.com/watch?v=rYinq45nS4g]
 [fn::<2019-09-13> https://deltaaware.org/weather/].

Apparently psychokinesis /lingers/.
It's called the linger effect.

what aspects of poltergeists should we scrutinize next?

Lyn Buchanan could drop a rock through a thin metal plate without making a hole in the plate.[fn::<2019-09-11> The Poltergeist Experience with Lyn Buchanan https://www.youtube.com/watch?v=52AqGmw_TYY]

Besides remote viewing, there is also /remote influencing/.

/Materialization/ is a very big claim.
There are some questionable reports.
Leslie Kean's account[fn::https://goop.com/wellness/spirituality/surviving-death-overview-evidence-support-afterlife/].
Stewart Alexander?
Franek Kluski's reputation was not perfect.[fn::<2019-09-11> https://en.wikipedia.org/wiki/Franek_Kluski]
Gustav Geley's reputation was not perfect.
Eusapia Palladino's reputation was not perfect.
 [fn::opinions damning her <2019-09-11> https://en.wikipedia.org/wiki/Eusapia_Palladino]
 [fn::opinions defending her <2019-09-12> http://davidpratt.info/psychic.htm]
Charles Richet and Gustav Geley's research of Franek Kluski?
However, everyone was holding each other's hands.[fn::https://www.metapsychique.org/the-kluski-hands-moulds/]

Uri Geller[fn::opinions defending him <2019-09-12> http://davidpratt.info/psychic.htm]?

https://en.wikipedia.org/wiki/Charles_Richet
* Haunting vs poltergeist
This is taken from Stephen E. Braude[fn::<2019-09-16> Poltergeist Phenomena with Stephen E. Braude https://www.youtube.com/watch?v=-nwG7p9MJ0U],
who studies macropsychokinetic phenomenons.

Both haunting and poltergeist are macropsychokinetic phenomenons.
However, haunting is centered on a place, whereas poltergeist is centered on a person.

Examples of poltergeists: Eleonore Zugun[fn::<2019-09-16> https://parapsychologie.info/zugun.htm],
Enfield poltergeist,
Matthew Manning[fn::<2019-09-16> https://psi-encyclopedia.spr.ac.uk/articles/matthew-manning].

It seems that the detail of the poltergeist reflects the underlying psychological explanation of the subject's problem.

It also seems that apporting objects heat them up: Apparently bigger apported objects feel warmer.

A "schlimazel" is a consistently unlucky person, more unlucky than a "schlemiel".
* Questions that may be elaborated into experiments
This section aims to sharpen some questions into experiment candidates.

Ideally, this section is empty.
** Questions on souls or spirits
On the movement of spirits

How do spirits move?
Do they require energy to move?
Where do they get that energy from?
How do we measure it?

Do ghosts prefer to haunt some places?
What kind of places do ghosts prefer to haunt?
Why?

Questions on souls that fight each other

Are there instances of souls fighting each other to control a body?

Questions on the creation of souls

How are souls created?
How are souls destroyed?
Is the number of souls constant over time?
** On experiencing the subjective experience of others
https://www.reddit.com/r/precognition/comments/bhbxzb/seeing_through_the_eyes_of_another_person/
** Hypotheses about the properties of souls
What is the /weight/ of a soul?
Has anyone repeated Duncan MacDougall's soul-weighing experiment more rigorously?
It would be the parapsychology analog of the Michelson--Morley experiment?
I think some of the weight difference is because some air leaves the lungs and intestines as muscles relax.
Each liter of air weighs 1.23 gram at room condition.[fn::<2019-09-08> https://en.wikipedia.org/wiki/Density_of_air]
A weight difference of 21 grams would mean that a man expels 17 liters of air when he dies.
I don't think there is that much air in the body.
Even an adult man's pair of lungs only contains 6 liters of air,
and not all of it is expelled when his muscles relax completely.
I don't think anyone can fart 11 liters of air at once;
otherwise coroners would routinely see dead people's bellies implode.

Gasser 2014 says what?
 [fn::http://www.pandualism.com/d/reincarnation.html]
How do we test his "psychon theory"?

https://www.neuroquantology.com/index.php/journal/article/view/389

https://www.lionsroar.com/do-you-only-live-once/
https://www.lionsroar.com/reincarnation-research-buddhism/
https://reincarnationafterdeath.com/theory/

2 people 1 soul?
https://www.quora.com/Can-two-people-share-the-same-soul-1
https://www.reddit.com/r/spirituality/comments/9qbzla/one_soul_in_two_bodies_or_two_souls_in_one_does/
???
http://weeklyworldnews.com/headlines/15170/how-to-tell-if-youre-double-souled/

Are souls /recycled/ in the same way nutrients are recycled in the biogeochemical cycle?

What happens in a /mass death/, such as in the 2004 Aceh tsunami that killed more than 100,000 people?[fn::<2019-09-08> https://en.wikipedia.org/wiki/2004_Indian_Ocean_earthquake_and_tsunami]
Where do all those souls go?
** Pastward future signal theory
Future objects may emit signals pastwards (towards the past).

If the signal is a wave, what reflects it, what diffracts it?
** On spirits, ghosts, possessions, and mediums
What places do ghosts prefer to haunt, and why?
How do ghosts decide what places to haunt?

The folk theory is that spirits can possess bodies.

Auerbach 2018 claims that ghosts cannot physically harm people.[fn::<2019-09-07> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e61agrg/]
** On near-death experiences and impossible recovery from brain damage
not cold reading
https://goop.com/wellness/mindfulness/a-research-scientist-on-what-happens-to-the-brains-of-mediums-when-they-talk-to-the-other-side/

https://goop.com/wellness/spirituality/the-other-side/

https://goop.com/wellness/spirituality/dr-eben-alexander-near-death-experience-hes-learned-consciousness/

"The best clinical examples are terminal lucidity, acquired savant syndromes, and hallucinogenic substance studies."
But this conflicts with /functional areas/?
** On embodied consciousness or possessed body?
Is each of us a consciousness that gets trapped in a body, or a body that gets possessed by a consciousness?

Are we mostly ideal/mental or mostly material/physical?

Is poltergeist a body that gets possessed by a consciousness?

Hypothesis:
Both a human and a poltergeist are a combination of mind and body.
But a human is more body than mental whereas a poltergeist is more mental than body.
** Where should we look next?
Exorcists in stigmatized property market, especially in Japan?
Or people just looking for cheap properties?

Tanishi Matsubara is trying to live in stigmatized properties for his comedy material.[fn::<2019-09-12> https://www.youtube.com/watch?v=hd_m2RevjPA]
I guess he won't be sharing it with us.
Even if he does, I guess it won't be in English.
* Claims that require corroboration before they are admissible as evidence
** Claims that may be practical enough to test
Joseph McMoneagle's remote viewing of Mars can be tested.
I think we'll begin exploring Mars in the 21st century.

Joseph (Joe) McMoneagle got a Legion of Merit[fn::https://en.wikipedia.org/wiki/Legion_of_Merit][fn::Joe McMoneagle; <2019-09-07> https://en.wikipedia.org/wiki/Recipients_of_the_Legion_of_Merit].

Joe McMoneagle claims that the best remote viewers have about 50%--60% accuracy;
he also suggests that it is unrealistic to expect more than that.
 [fn::<2019-09-10> Guidelines for Future Remote Viewing with Joseph McMoneagle https://www.youtube.com/watch?v=W2-iGRkW9AU]

Lyn Buchanan has remote viewing /exercises/.[fn::<2019-09-11> Exercises to Cultivate Remote Viewing with Lyn Buchanan https://www.youtube.com/watch?v=wDO8CdJV_kc].
First: Every time you change room, notice the /change/ in ambiance.
Second: Learn vocabulary to describe what you feel.

Ingo Swann[fn::https://en.wikipedia.org/wiki/Ingo_Swann]

Joe McMoneagle remote-viewed Japan for a six-year archeology project from his dining room in Central Virginia.
 [fn::<2019-09-11> https://www.youtube.com/watch?v=F-8puX-83o4]
His sponsors were looking for artifacts related to Empress Himiko.[fn::https://en.wikipedia.org/wiki/Himiko]
If it can be used for archeology, then perhaps it can also be used for geology, and for prospecting, for finding resources?

Joe McMoneagle found two missing people in Japan.
 [fn::<2019-09-11> http://web.archive.org/web/20061215094642/http://www.rense.com/general20/joemcmoneagle.htm]
 [fn::<2019-09-11> https://www.reddit.com/r/remoteviewing/comments/7kp8un/request_jo_mcmoneagle_finding_people_on_tv/]
** Claims that may be hard to test
Immanuel Kant's account of Emanuel Swedenborg, 18th century.

Evidence captured by 21st century equipments.

Witnesses are often reliable.

Most evidence was anecdotal until J.B. Rhine began using statistics.[fn::Remote Viewing and the Reality of Psychic Phenomena | Waking Cosmos | Garret Moddel Ph.D. https://www.youtube.com/watch?v=IC1kTVe61yc]

We assume that the records are not manipulated?

EVP?

Camera?

Are these experiments trustworthy?
https://www.consciouslifestylemag.com/mind-over-matter-experiments/

Most convincing unexplained recordings for me:
- From https://www.reddit.com/r/AskReddit/comments/1sv39b/serious_what_in_your_opinion_is_the_most/
  - "Ghost scares dogs on camera"[fn::https://www.youtube.com/watch?v=DL_bIhVJi-k]
    - text summary[fn::https://www.reddit.com/r/AskReddit/comments/1sv39b/serious_what_in_your_opinion_is_the_most/ce25ska/]
      - there is also a debunking
  - "My Ghost Story Haunted Lab"[fn::https://www.youtube.com/watch?v=92jFdzNC228&t=2m28s];
    dubious, a reality show?
    - Andy Coppock?
  - https://www.quora.com/What-are-the-most-convincing-paranormal-cases

Are there double-blind parapsychological experiments?

What does the oil industry say about dowsers?
How much money are they betting on it?
If it were big, there had to be something?
https://www.quora.com/What-are-some-practical-applications-of-parapsychology

Oil dowsing: Either it does not work or it is a heavily guarded secret.

What do the archeologists say about psychics?
** What does the police have to say about the best remote viewers?
What does the police have to say about their collaboration with Joe McMoneagle?
What does the police have to say about his statistics?

Joe McMoneagle is the number one American remote viewer.

Elena Klimova is the number one Russian remote viewer.
 [fn::<2019-09-10> http://davidpratt.info/psi.htm]
Edwin C. May claims that he once worked with her and she was a very good remote viewer.
 [fn::<2019-09-10> 17:33, Edwin C. May https://www.youtube.com/watch?v=L811nO601sg]

What do Russians call a remote viewer?
Some related Russian terms according to Google Translate on <2019-09-10>:
военного применения экстрасенсорики (voyennogo primeneniya ekstrasensoriki) = military use of extrasensory perception
** Questions on psychokinesis
If psychokinesis is real and moving objects requires energy,
where does the energy come from?
The body's energy storage?
Any point in the Universe where there is abundant energy?
Then, how does that amount of energy move?

We should measure the psychic's body mass or /energy storage content/ (the count of ATP molecules in his body)
while he is psychokinetizing.
That is, we should research the physiology of psychokinesis.

But what about changing the weather as Ted Owens claimed?
How much energy is required to change the weather?

Of course it is possible that energy is not conserved,
that the law of conservation of energy is wrong;
indeed it is wrong in time scale;
Heisenberg uncertainty principle;
virtual particles popping into and out of existence;
but this violation is only likely to happen in /extremely short time span/.
** How do we know whether our ancestor spirits enjoy our offerings?
** Oil dowsing
From Ault 2014[fn::https://jimmyjoeault.wixsite.com/adventures/single-post/2014/06/19/Dowsing-For-Oil]:
"The petroleum industry has used dowsing to locate oil wells."

https://canadiandowsers.org/military-government-and-big-business-use-dowsing/
#+BEGIN_QUOTE
One of the most successful dowsers was Paul Clement Brown of California, an MIT graduate and electrical engineer,
who used dowsing to successfully dowse oil wells for Standard Oil, Signal Oil, Getty Oil, Mobil Oil, and others.
For years, he advised one of America’s most successful petroleum “wildcatters,”
J.K. Wadley, on whether or not his proposed oil-drilling sites would be productive and how deep the oil would lie.
His ability to dowse for oil was tested by an initially skeptical senior petroleum engineer.
Chet Davis, on 35 proposed well sites. “He was right on all 35 wells,” says Davis.
“I don’t think anyone in the oil business would believe it if they didn’t see it. I wouldn’t have.”
#+END_QUOTE
** China's psychic children
CIA Project Stargate archive "China's psychic children"[fn::https://www.cia.gov/library/readingroom/document/cia-rdp96-00792r000300420017-1]
** On interviewing people with skin in the game
Anecdotes not from psychics themselves, but from the people who have benefited from psychics.

First, seek for-profit industries that have put their money in psychics.
They have their skin in the game.
Oil, water, drilling, etc.
Dowsing, pendulum.

Cops.
* Apparently dead ends
** What we perceive is not the object itself
I think philosophers have known this for a long time.

What we see is not the object itself, but an /image/ of the object.
We see the light that is reflected or emitted by the object.

What I think I am is only my perception of me and not what I actually am,
in the same way that, when I see a tree, I am seeing the image of the tree, the light that reaches my eyes, not the tree itself.
By "I see a tree", I mean that the light reflected by the tree has arrived at my eyes.
** On testing folk theories and folk hypotheses
We need a falsifiable theory that makes some testable predictions.

The theory has to be to explain paranormal phenomenons such as precognition, spiritual possession, poltergeist, and haunting.

Utts 2001 \cite{utts2001assessment}[fn::Also on CIA website https://www.cia.gov/library/readingroom/document/cia-rdp96-00791r000200070001-9]
claims that "Using the standards applied to any other area of science, it is concluded that psychic functioning has been well established."
Ray Hyman was a co-researcher but did not share the conclusion.

"Senders do not appear to be necessary at all; feedback of the correct answer may or may not be necessary.
Distance in time and space do not seem to be an impediment." \cite{utts2001assessment}:

https://tunsasays.wordpress.com/

Kruth 2015[fn::<2019-09-06> https://tunsasays.wordpress.com/2015/05/04/the-nature-of-psi-the-first-sight-model-and-theory-of-psi/] proposed a theory of psi.
- Carpenter 2004 "First Sight Model and Theory of Psi".
  OK, it explains, but what does it /predict/?
- From <2019-09-06> https://www.rhine.org/who-we-are/9-uncategorised/192-peg-slide.html
- From <2019-09-06> gsearch psychic experiencers group
- From <2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/?sort=confidence

Angela Moore started Psychic Review Online[fn::https://www.psychicreviewonline.com]
to keep track of real and fake psychics.
Interesting: A company named "Psychic Source" has skin in the game with money-back guarantee.

Can we corroborate with Debra Chalmers's previous employer?
https://www.psychicreviewonline.com/blog/in-the-news/725/

https://www.researchgate.net/publication/317784136_What_is_Psi_From_Anti-Parapsychology_to_Psi_as_a_Next_Scientific_Revolution_Theoretical_Reviews_and_Hypothesized_Vision

BDJ https://www.researchgate.net/publication/328968105_The_Physics_of_Mind_and_Thought

https://www.researchgate.net/publication/328968105_The_Physics_of_Mind_and_Thought
** On testing psychic abilities
Briggs 2006 \cite{briggs2006so} is a 200-page book of /tests/ for some psychic abilities,
with a healthy dose of true skepticism.

Bob Olsen won't let people scrutinize his "15-point test"[fn::"famous, although secret, 15-point test" https://bestpsychicdirectory.com/Tested-Legitimate-List],
so I don't trust him.
** Astral travel, remote viewing, out-of-body experience?
What is non-local consciousness?
Are these legit or kook?
- https://allaboutheaven.org/observations/1122/127/swann-ingo-out-of-body-to-mercury-003207
- https://www.quora.com/Is-astral-projection-true-If-so-has-anyone-done-it-Is-there-a-standard-procedure
- [[https://www.youtube.com/watch?v=bjQxwm9vuiE]["Experiments Proving Astral Projection is Real"]]
** On spontaneous remission
I would not be surprised if someday we found a purely biological explanation for /spontaneous remission/[fn::https://en.wikipedia.org/wiki/Spontaneous_remission]
(the unexpected disappearance of cancer from a person)
because biology is complex:
We don't even understand the biology of mundane things like acnes and dandruffs.
* Bibliography
