#+TITLE: On hindrances to anomaly research
#+DATE: 2019-09-02 00:00:00 +0700
#+PERMALINK: /anomaly-hindrance.html
* Fraud
/Fraud/ is rife in /both/ the psychics camp and the skeptics camp,
so the possibility of fraud must be ruled out before any claim or counter-claim is admitted as evidence or counter-evidence.

The reports that interest us are buried among lots of frauds and unreliable anecdotes.

There are two sides: psychics and skeptics.
Both sides have their own share of charlatans: cold-readers and pseudo-skeptics.
Cold readers are not paranormal.
Pseudo-skeptics are religious zealots who refuse to consider any evidence.

One big problem is /survivorship bias/: only the successes get reported, and the failures are forgotten.
* The Internet
Google doesn't help much, because its search result for "psychic" is polluted by cold-readers
 [fn::https://www.reddit.com/r/AskReddit/comments/29041r/serious_psychics_of_reddit_do_you_knowingly_scam/]
 [fn::https://blogs.scientificamerican.com/illusion-chasers/two-neuroscientists-walk-into-a-psychic-fair/]
and pseudo-skeptics.
They taint the term "psychic" and encumber my Google search.
But /you can help:/
Stop calling cold-readers "psychics", and use "psychics" only for real psychics.
Call people what they are, not what they claim to be.
A "psychic" who asks too many questions is a cold-reader, not a psychic,
who is supposed to give you statements, not questions.

Google search result for psychic-related terms is full of these shit:
- cold-readers trying to sell you shit,
- pseudo-skeptics shoving their shit on you,
- "researchers" selling their books.

Wikipedia is infested with pseudo-skeptics.

Another problem is /self-censorship/ due to living in a society of closed-minded people.

Some things are not paranormal.
Cold reading is not psychic.
Forer effect[fn::https://en.wikipedia.org/wiki/Barnum_effect] (making vague predictions that are almost always true) is not psychic.
