#+TITLE: On anomalies
#+DATE: 2019-09-02 00:00:00 +0700
#+PERMALINK: /anomaly.html
* On the language we use for anomalies and unexplained phenomenons
The field of study of anomalies is called /anomalistics/[fn::https://en.wikipedia.org/wiki/Anomalistics].
See also ASSAP[fn::https://en.wikipedia.org/wiki/Association_for_the_Scientific_Study_of_Anomalous_Phenomena].

There is also /parapsychology/.

Paranormal[fn::https://www.etymonline.com/search?q=paranormal]

The "para-" prefix means "beyond" or "beside".[fn::https://www.etymonline.com/word/para-]

https://www.google.com/amp/s/amp.reddit.com/r/Paranormal/comments/48bwox/exskeptics_what_event_convinced_you_of_the/

https://abcnews.go.com/GMA/Weekend/psychic-reveals-tricks-trade/story?id=10590096

https://www.cia.gov/library/readingroom/document/cia-rdp96-00788r000100340001-4

Extra-sensory perception is also called "second sight".[fn::https://psychicelements.com/blog/are-psychic-abilities-hereditary/]

Did Carl Sagan say this?
https://www.iacworld.org/top-3-psychic-anomalies-according-to-carl-sagan/
* On beginning anomaly research
Where should we begin?
We can begin from these:
- corroborated report by an independent third party (not a self-report by the psychic himself),
- evidence in which its authors have no motive to falsify the record,
- accounts of skeptical ghost hunters.

Jeffrey Mishlove's "New Thinking Allowed"[fn::<2019-09-12> https://www.youtube.com/playlist?list=PLDclhMCOIszQqH61Hy712_G-1v_2O3aN1]
is indispensable.
It is very suitable for beginners.
He asks great questions to experts, producing lots of high-quality starting points.

Reddit is a better starting point than Google for anomaly research.
Example: The "Psychic" subreddit[fn::https://www.reddit.com/r/Psychic/].

Choose a class of phenomenon (two example classes are precognition and psychokinesis).
Focus one day on finding evidences of it.

For corroborated reports, we can begin from
the document "Newspaper articles re psychics"[fn::https://www.cia.gov/library/readingroom/docs/CIA-RDP96-00788R002000240037-5.pdf],
which is part of the Stargate project of the CIA.

Either all those people are insane, or there is something we don't know.
If there is one or two reports, the reporter may be hallucinating.
If there are thousands of reports, there may be something going on.

Not enough details in this report[fn::https://www.huffpost.com/entry/psychic-mediums_n_5acf4961e4b08337adca0b62]

Has any skeptic changed his belief?[fn::inconclusive https://www.reddit.com/r/AskReddit/comments/vx51d/reddit_has_anyone_been_to_a_psychicmedium_as_a/]
* My work queue
** Reddit
There are /lots/ of pointers in Loyd Auerbach's Reddit interview[fn::<2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/]:
links to research organizations,
phenomenons corroborated by multiple witnesses[fn::<2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e6163hs/],
phone calls from the dead[fn::<2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e615rz4/],
communicating with the dead[fn::https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e619ma3/],
visualizations and psychic shields[fn::<2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e616u9x/],
and so on.

According to Auerbach 2018[fn::<2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e618myt/],
Joseph W. McMoneagle was CIA Project Star Gate's number-one remote viewer.

CIA document "an assessment of the evidence for psychic functioning"

From USA government "sensemaking"[fn::https://time.com/4721715/phenomena-annie-jacobsen/], to corroborate:
- 'In 2014, the Office of Naval Research embarked on a four-year, $3.85 million research program to explore the phenomena it calls premonition and intuition, or “Spidey sense,” for sailors and Marines.'
- "a 2006 incident in Iraq, when Staff Sergeant Martin Richburg, using intuition, prevented carnage in an IED, or improvised explosive device, incident"
- "Fifty years ago in Vietnam, Joe McMoneagle used his sixth sense to avoid stepping on booby traps, falling into punji pits, and walking into Viet Cong ambushes.
  His ability to sense danger was not lost on his fellow soldiers, and the power of his intuitive capabilities spread throughout his military unit."

On CIA Project STARGATE
https://www.reddit.com/r/ProjectSTARGATE/

On remote viewing
https://www.reddit.com/r/remoteviewing/

Reddit psionics

Paranormal

Past lives
https://www.reddit.com/r/Paranormal/comments/cyjipx/my_aunts_friends_son_is_living_his_last_life/

Mass hysteria
* On testing alleged mind-body interactions
** On the legitimacy of psychic claims
Psychic claims are /falsifiable/, but unfortunately most are frauds.
We should test those which are not frauds, as seriously as we test scientific theories.

It seems to me that, in the "psychic" world, fame and legitimacy are inversely correlated.

Cold reading is not psychic.

Where do we find the real psychics, if they exist at all?
We should begin not from famous "psychics",
but we should begin from "proven" psychics,
those who have solved police cases /several/ times.

Can we trust these people?
- Bob Olson claims to have a methodology[fn::https://bestpsychicmediums.com/testedaslegitimate]
  for his "Genuine & Legitimate Psychic Mediums List"[fn::https://bestpsychicmediums.com/thelist.htm],
  but he puts a disclaimer[fn::https://bestpsychicmediums.com/disclaimer.htm],
  so is he saying anything at all?
- "Troy Griffin claims he's worked on more than 100 missing persons cases."[fn::https://www.vice.com/en_us/article/9k33av/a-psychic-detective-tells-us-how-he-solves-murders]

It is not about 100% accuracy;
it is about /much better than chance/.

If police knows psychics, then there will be no cold cases?
Does the existence of cold cases prove that psychics do not exist?

It is easy to test psychic mediums, telepaths, clairvoyants, and other kinds of psychics.
However, it is difficult to /replicate/ the test, because, if it works, it works only with a particular psychic,
so it is hard for different researchers at different places to replicate the experiment at different times.

If we can prove that psychic mediums are reliable, can we infer the existence of /disembodied minds/?
** On Russell Targ's claim of remote viewing
How do we test it?

Banned TEDTalk about Psychic Abilities | Russell Targ | suespeaks.org https://www.youtube.com/watch?v=hBl0cwyn5GY
** On police cases allegedly solved by psychics
Psychic detective[fn::https://en.wikipedia.org/wiki/Psychic_detective]

We need a psychic who has solved /several/ cases and is corroborated by an independent third party
(such as the police; the case must not be self-reported by the psychic himself).
He is probably not famous.
He probably does not call himself "psychic" because that word has been tainted by fraudsters.

From a 2000 article by CIA[fn::https://www.cia.gov/library/readingroom/docs/CIA-RDP96-00788R000100280009-3.pdf], I infer:
- Police uses psychics, but rarely, and mostly as last resort.
- Most psychics are unreliable, although some have unexplainedly high accuracy.

Is there any people who unexplainedly solve /several/ police cases?
 [fn::10 Real Psychics Who Helped Solve Mysteries https://www.youtube.com/watch?v=4nCaiJbKdFw]
 [fn::https://patch.com/michigan/northville/michigan-medium-solves-cold-cases--spotlighted-in-investigation-discoverys-newest-series-restless-souls]
 [fn::https://www.reddit.com/r/UnresolvedMysteries/comments/6d4e41/request_any_cases_that_were_actually_helped_by_a/]

How do we verify those claims?
We can ask the police directly.
I think we can assume that the police are honest.
** On possessions, out-of-body experiences (OBEs), and near-death experiences (NDEs)
Sam Parnia, AWARE II study

Pim van Lommel

How do we verify, test, explain possessions and out-of-body experiences?
** Wanted: replicable magick experiments
- Notes?

  - The presence of the experimenter affects the result?
  - The experiments may need to be repeated many times?

- Experiment ideas, ordered from the easiest to repeat:

  - Extrasensory perception

    - Astral projection

      1. Get a person (A) who can astral-project.
      2. Generate a bit X.
      3. Ask A about X.

    - Dream precognition

      - Telepathy

        1. Get two telepathic people A and B. (If you are telepathic yourself, you can be any one of them.)
        2. Generate a bit X (0 or 1) that only you and A know.
        3. Let A telepathically tell X to B. (Take care to isolate each of you to avoid sensory leakage.)
        4. Ask B about X.

    - Spirit possession

      - Procedure:

        1. Get two mediums A and B. (If you are a medium yourself, you can be A.)
        2. Get A to summon a spirit S.
        3. Generate a bit X (0 or 1) that only you and A know.
        4. Let A tell X to S.
        5. Get S into B. (This needs more detail.)
        6. Ask the S-possessed B about X.
           If he/she consistently knows, we may have a support for dualism.
        7. Get S out of B.

      - If the experiment result is promising,
        we can test the spirit's working memory capacity
        by replacing the bit X with a string, a number, a sentence, or whatever longer.
        The only important constraint is that you need to pick an X
        that is easy to remember but hard to guess.
      - Problems:

        1. Mediation may be tiring? (Can get another medium?)
        2. Spirits may refuse to cooperate? (Can get another spirit?)

  - Joint micropsychokinesis

    - What if many people try to influence a RNG at once?
      So far experiments one person influences a RNG at a time.
      Does the effect add up?

      - Is there even any effect at all?

- We might dismiss one person for hallucinating.
  Two unrelated honest people corroborating each other are less likely to be hallucinating.
  The more people say the same thing, the more serious the claim is.
  Not necessarily more true, but surely more serious.
  Most people are not pathological liars.

  - The facts may be correct, but the explanation may be unjustified.
  - https://www.lesswrong.com/posts/CJxSgaqG6y7z6Rbij/are-mass-hallucinations-a-real-thing


- From the ghost's point of view, it is we who are haunting them, not they who are haunting us.
  Or is it not that simple?
- aggregators

  - [[https://www.reddit.com/r/Paranormal/comments/7nh31e/creating_a_google_map_of_haunted_locations/][Creating a Google map of haunted locations]]

- some ghost pictures are due to crappy camera https://www.reddit.com/r/Paranormal/comments/6jdy18/question_why_does_every_ghost_picture_seem_to_be/
- scientific?

  - https://www.reddit.com/r/Paranormal/comments/w2b04/hello_rparanormal_i_am_a_physicist_and_i_have_an/
  - http://liparanormalinvestigators.com/

    - They claim [[http://liparanormalinvestigators.com/evidence-gallery/][high standard of evidence]].

- 2018-08-13

  - I was too scared to view some materials at night. I did these:

    - Play "Yakety Sax" in the background.
    - Surf the Internet with my sister.
** Obtaining magickal powers?
- Which ones are not charlatans, fraudsters, quacks?
- We may dismiss the explanation, but we must not dismiss the fact (the phenomenon, the observation).
- Are there tutorials?

  - Related search terms (Indonesian, Javanese, Sundanese, English):

    - ajian, clairaudiance, clairvoyance, extrasensory perception, gaib (occult), gendam, ilmu, jangjawokan, kanuragan, kinasihan, linuwih, magick, medium, poltergeist, premonition, psychokinesis, reiki, remote viewing, rukyah, ruwat, sakti, santet, sihir, telekinesis, telepathy, teluh, tenaga dalam, tenung

- [[https://www.youtube.com/watch?v=hBl0cwyn5GY][Banned TEDTalk about Psychic Abilities | Russell Targ | suespeaks.org]]
- To be tested: theories, hypotheses, assertions, sometimes contradicting each other

  - Gaia: "A Unified Theory Of The Paranormal", [[https://www.youtube.com/watch?v=QinS6-0O2_Q][youtube]]

    - John A. Keel, The Mothman Propecies, The Eighth Tower

      - electromagnetic events are often associated with paranormal events
      - Santet has negative electric charge. Sleeping on the floor blocks santet. https://areknerut.wordpress.com/2012/11/15/hukum-fisika-sebagai-cara-untuk-menangkal-santet/
      - Sleeping on the floor worsens santet. (7th item in the list) https://www.brilio.net/serem/7-cara-menangkal-santet-menurut-pendekar-silat-a-masruri-170924x.html

    - Stephen Greer, CE-5 UFO summoning protocol

- Gaia: Remembering Past Lives, [[https://www.youtube.com/watch?v=X4LuRJWzPEA][youtube]]
- [[https://www.youtube.com/watch?v=n8yhaFd_GpM][YT:TED:A scientific approach to the paranormal | Carrie Poppy]]

- Undigested information

  - These are unknown, but these give us a procedure we can try, if it's clear at all.

    - A simple remote viewing protocol everyone can try: http://www.irva.org/remote-viewing/howto.html
    - Farsight institute for remote viewing
      has instructions for "scientific remote viewing".
    - Paul H. Smith's remote viewing
      has procedures we can follow.
    - Other people's scientific experiments

      - Articles to read.

        - https://www.quora.com/What-are-some-trippy-thought-experiments-2
        - http://listverse.com/2013/10/21/10-mind-boggling-thought-experiments/
        - http://rationallyspeaking.blogspot.co.id/2013/09/three-and-half-thought-experiments-in.html

    - Robert Monroe's out-of-body-experience how-to http://weird-people.com/astral-projection-how-to/

  - Is it science?

    - Chinese psychic kids
    - Dream research

      - Is dream research our best bet at consciousness research?
      - Lucid dreams
      - the sense of time in dream? http://www.susanblackmore.co.uk/Articles/si91ld.html
      - http://www.sawka.com/spiritwatch/dream.htm
      - http://www.spiritwatch.ca/
      - http://serendip.brynmawr.edu/bb/neuro/neuro99/web2/Plotnick.html
      - http://www.abichal.com/html/dreams/lucid_dreams/lucid_dreamers/alan_worsley.htm
      - http://www.lucidity.com/
      - http://www.lucidity.com/slbbs/

    - [[http://www.magickofthought.com/][Mike Sententia old blog]]

      - http://www.magickofthought.com/tag/science/
      - http://www.magickofthought.com/tag/testing/

    - Popular writings

      - http://listverse.com/2009/01/29/top-10-bizarre-afterlife-experiments/
      - http://www.therichest.com/rich-list/most-shocking/6-paranormal-experiments-conducted-by-the-government/?view=all
      - http://io9.com/5721855/25-of-the-scariest-science-experiments-ever-conducted

    - Carl Jung's parapsychological research
    - Haunting

      - Institutional experiments

        - Major research approaches.
        - Major psi experiments.
        - Koestler Parapsychology Unit
          recent studies
          and
          research overview.
          It sells online courses and Caroline Watt's book (An introduction to parapsychology).
          PA student members get discount.
        - James E. Kennedy's
          research,
          other papers,
          experimenter effects PDF,
          misconduct,
          and
          why psi is elusive.
        - Dean Radin's
          of experiments.
        - Wiseman's dream precognition
        -
          13 University-Sanctioned Paranormal Research Projects
        - An Introduction to Parapsychology - Harvey J. Irwin and Caroline A. Watt
        - Basic research in parapsychology
        - Global consciousness project correlates shocking world events and significant RNG perturbations.
        - 2012 [[http://media.noetic.org/uploads/files/PhysicsEssays-Radin-DoubleSlit-2012.pdf][correlating concentrated attention and double-slit experiment
          outcome]].
          PDF. Needs lab equipment.
        - 2011 retrocausal experiments (draft).
          I think this paper has been retracted by the author himself. PDF. Journal of Personality and Social Psychology 100, 407--425.
          An APA journal.
          Daryl Bem.
          Wiseman replication failed.
          Replication is important.
        - PEAR experiments
        - Modern experiments in telepathy
          http://psycnet.apa.org/psycinfo/1955-03428-000
        - Dream telepathy: Experiments in nocturnal ESP
          http://psycnet.apa.org/psycinfo/1975-02219-000
        - Automated Tests for Telephone Telepathy Using Mobile Phones
          http://www.explorejournal.com/article/S1550-8307(15)00062-2/abstract

      - Old papers

        - 1989
          Evidence for consciousness-related anomalies in random physical systems.
          Foundations of Physics vol 19 no 12.
        - 1989
          intention influences random events.
          PDF.
          Journal of Scientific Exploration.

    - Military-related

      - p-teleport. PDF.
      - https://en.wikipedia.org/wiki/Stargate_Project
      - Document too long: [[https://www.reddit.com/r/occult/comments/6rue4m/magick_explained_scientifically_in_cia_doc/][Reddit 6rue4m: Magick explained scientifically in CIA doc]].

    - Other experiments I have not seen into

      - http://www.thescoleexperiment.com/
      - http://www.iisis.net/index.php?page=semkiw-reincarnation-communication-with-dead
      - http://www.nbcbayarea.com/news/tech/Brain-Scanner-Records-Dreams-on-Video-130497213.html
      - http://www.reddit.com/r/Paranormal/comments/1qgo0w/ama_i_have_have_a_phd_in_parapsychology/
      - http://www.dailygrail.com/Fresh-Science/2014/1/Scientists-Call-Open-Informed-Study-Psi-Effects-and-Consciousness

    - J. B. Rhine

      - http://archived.parapsych.org/members/jb_rhine.html
      - http://www.rhine.org/what-we-do/current-research.html
      - http://dukemagazine.duke.edu/issues/111209/depqa.html
      - Study J. B. Rhine http://www.williamjames.com/Science/ESP.htm

  - How do we verify this?

    - John Chang, the magus of java, youtube video

      - http://www.gestaltreality.com/2012/02/07/mo-pai-nei-kung-john-chang/

    - Nina Kulagina http://www.mysteriouspeople.com/Nina_Kulagina.htm

      - [[https://www.cicap.org/new/articolo.php?id=101003][Massimo Polidoro's Secrets of a Russian Psychic]]

    - Matthew Manning
    - https://en.wikipedia.org/wiki/Quantum_cognition
    - "The afterlife experiments" book
    - What is "dimensional jumping"? Is it legit? How do we do it? [[https://np.reddit.com/r/DimensionalJumping/][/r/DimensionalJumping]]

      - [[https://www.reddit.com/r/DimensionalJumping/comments/2ax00o/dimensional_jumping_for_dummies_revamped/][Reddit 2ax00o]]
        has a procedure everyone can try.
      - [[https://www.reddit.com/r/DimensionalJumping/comments/38c3yk/how_to_jump_between_dimensions/][Reddit 38c3yk]]
        offers 6 procedures everyone can try.

    - Somewhat promising sources, but still, forum, need much corroboration

      - user 'darkbreed'

        - http://www.unexplained-mysteries.com/forum/topic/120420-scientific-research-on-psychic-metaphysical/
        - http://www.unexplained-mysteries.com/forum/topic/124456-offering-a-helping-hand-and-deeper-insights/

      - http://moebius.psy.ed.ac.uk/~info/ResearchCentres.php3
      - http://www.espresearch.com
      - http://en.wikipedia.org/wiki/SRI_International

    - after-death communication http://www.after-death.com/links/research.htm
    - http://www.collective-evolution.com/2014/03/08/10-scientific-studies-that-prove-consciousness-can-alter-our-physical-material-world/
    - https://www.reddit.com/r/metaphysical/top/
    - Are these serious?

      - http://metaphysicsuniversity.com/
      - http://www.umsonline.org/

    - demonic possession

      - https://www.mirror.co.uk/news/weird-news/devil-father-amorth-exorcist-film-11137254.amp
      - http://www.theweek.co.uk/87467/exorcism-industry-booming-in-france-italy-and-uk

        - Does demonic possession happen only in Italy? Does demonic possession also happen in other countries?
        - Does it only happen to Catholics?
        - Is the frequency of demonic possession inversely proportional to the distance from Vatican?

    - Reddit

      - http://www.reddit.com/r/parapsychology/
      - http://www.reddit.com/r/ParanormalScience/search?q=experiment&sort=relevance&restrict_sr=on&t=all
      - http://www.reddit.com/r/Paranormal/search?q=experiment&sort=relevance&restrict_sr=on&t=all
      - http://www.reddit.com/r/Psychic/search?q=experiment&sort=relevance&restrict_sr=on&t=all
      - maybe not so helpful
        http://www.reddit.com/r/occult/search?q=experiment&sort=relevance&restrict_sr=on&t=all

    - Uri Geller
    - autistic savants
    - brain injury cause superpower?
    - parapsychology
    - psychotronics
    - psychokinesis
    - PEAR (Princeton Engineering Anomalies Research)
    - SRI (Stanford Research Institute)
    - Write a protocol http://www2.lv.psu.edu/jxm57/irp/prot.htm
    - http://www.spr.ac.uk/
    - Is this for real? http://www.spiritualresearchfoundation.org/spiritual-problems/demonic-possession/ghost-spirit-symptoms/
    - voodoo: vance vanders?
    - anomalous cognition in hypnagogic condition
    - Isaac Newton's study of the occult?
    - premonition
    - Body swap/brain swap

      - Let there be two people, A, wearing red shirt, and B, wearing green shirt; they are looking at their respective shirts;
        I assume that
        everybody knows first-hand the concept of self.
        A' sees A's body,
        B' sees B's body.

    - https://www.kaskus.co.id/forum/23/supranatural
    - poltergeist proof? journal articles?
    - http://psionguild.org/education/articles/mental-abilities/telepathy-manual/#IVB

  - What is the difference between magick, occult, mysticism?
    What are their etymologies?

    - https://en.wikipedia.org/wiki/Magick_(Thelema)
    - https://en.wikipedia.org/wiki/Occult
    - https://en.wikipedia.org/wiki/Mysticism
    - https://en.wikipedia.org/wiki/Natural_magic

  - Websites that I have glanced and I deem to have no content

    - Problems

      - unclear proposition for the reader in a hurry
      - doesn't make any prediction or explanation
      - doesn't even bother to understand existing science

    - from Google search "scientific method occult"

      - http://occultsciences.org/
      - https://www.occultphysics.com/

        - selling a book

- aggregators

  - https://www.reddit.com/r/Paranormal/comments/3ep2f1/my_huge_collection_of_paranormalthemed_askreddit/
  - https://www.reddit.com/r/Paranormal/comments/6l40lg/some_lesser_known_askreddit_paranormal_etc_threads/
  - https://www.reddit.com/r/Thetruthishere/top/
  - things that convince some people

    - https://www.reddit.com/r/AskReddit/comments/6prmsk/serious_redditors_who_use_to_not_believe_in_the/
    - https://www.reddit.com/r/AskReddit/comments/6ryogk/serious_redditors_who_believe_in_the_paranormal/
    - https://www.reddit.com/r/Thetruthishere/comments/5bq8fj/what_is_the_most_convincing_paranormal_evidence/

- Parapsychology.
  Some interesting anecdotes.
  Still looking for replicable experiment.

  - [[https://koestlerunit.wordpress.com/][Koestler parapsychology unit of University of Edinburgh]]

- [[https://en.wikipedia.org/wiki/Dream_telepathy][WP:Dream telepathy]]
- [[https://www.reddit.com/r/AskReddit/comments/1sv39b/serious_what_in_your_opinion_is_the_most/][[Serious] What, in your opinion, is the most convincing photo captured of something supernatural? : AskReddit]]

  - https://www.reddit.com/r/Paranormal/comments/1b0k5d/i_aint_afraid_of_no_ghost/
* English-Indonesian term concordance
| English        | Indonesian               |
|----------------+--------------------------|
| psychic        | cenayang, "orang pintar" |
| occult         | gaib                     |
| shaman         | dukun                    |
| roaming spirit | arwah gentayangan        |
| ghost          | hantu                    |
* Bibliography
