#+TITLE: On hindrances to anomaly research
#+DATE: 2019-09-02 00:00:00 +0700
#+PERMALINK: /anomaly-hindrance.html
* This page is deprecated
I think, instead of telling people what to avoid (what not to do), we should tell people what to do.
* Fraud from both sides
/Fraud/ is rife in /both/ the psychics camp and the skeptics camp,
so the possibility of fraud must be ruled out before any claim or counter-claim is admitted as evidence or counter-evidence.

The reports that interest us are buried among lots of frauds and unreliable anecdotes.

There are two sides: psychics and skeptics.
Both sides have their own share of charlatans: cold-readers and pseudo-skeptics.
Cold readers are not paranormal.
Pseudo-skeptics are religious zealots who refuse to consider any evidence.
* Google
Google must be used very cautiously, because its search result for "psychic" is polluted by cold-readers
 [fn::https://www.reddit.com/r/AskReddit/comments/29041r/serious_psychics_of_reddit_do_you_knowingly_scam/]
 [fn::https://blogs.scientificamerican.com/illusion-chasers/two-neuroscientists-walk-into-a-psychic-fair/],
pseudo-skeptics, and snake-oil sellers.
They taint the term "psychic" and encumber my Google search.

But /you can help:/
Stop calling cold-readers "psychics", and use "psychics" only for real psychics.
Call people what they are, not what they claim to be.

It could be that some of them are legitimate?
* Wikipedia
Wikipedia itself says that it is not a reliable source.[fn::<2019-11-04> https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_is_not_a_reliable_source]

Also, the job of Wikipedia administrators is to enforce policy, not to find out the truth.
* Self-censorship
Another problem is /self-censorship/ due to living in a society of closed-minded people.
* Mistakes
Some things are not paranormal.
Cold reading is not psychic.
Forer effect[fn::https://en.wikipedia.org/wiki/Barnum_effect] (making vague predictions that are almost always true) is not psychic.

There may be some /survivorship bias/: only the successes get reported, and the failures are forgotten.
* On poorly chosen words
ESP (Extra-Sensory Perception) is oxymoron:
If you can perceive it, you have a sensor for it; you just don't know what the sensor is.
Perhaps ESP should be renamed to EOP ("/Extra-Ordinary/ Perception").
But the term has stuck, and words mean whatever we choose them to mean, so let's stick with ESP?

The word "supernatural" is absurd:
If it exists, then it is natural, because Nature is defined to be everything that exists.
"Extraordinary" is a better choice.

How do we define "artificial"?
Everything is natural, because everything comes from Nature;
even the humans who create artificial things come from Nature.

Why do we assume that some things will not come into existence if there are no humans to create it?
The probability is non-zero.

Is it possible that somewhere out there in the vast outer space,
there is a jet aircraft formed spontaneously by natural processes such as explosion of stars?

Is it possible that there is a teapot-shaped space rock formed by natural processes?

Why are most objects in outer space relatively simple compared to artificial objects?
Or are things not as simple as they seem?
