#+TITLE: Towards the abduction of the simplest theory that explains paranormal evidence
#+DATE: 2019-09-07 00:00:00 +0700
#+PERMALINK: /anomaly-theory.html
* About this document
This document discusses souls and the phenomenons associated with them,
such as anomalous cognition, reincarnation, afterlife,
out-of-body experience, near-death experience,
subjective experience (first-person point of view), and so on.
* Meta-research directions
Whenever we feel lost in our paranormal research, answering these meta-questions will give us some directions:
- How does evidence /constrain/ (narrow down) the space of hypotheses that attempt to explain paranormal phenomenons?
- What /key/ question should we ask next in order to formulate a /crucial/ experiment
  whose result would most strongly constrain the hypothesis space?
- How can /mathematics/ help, if it can help at all?

There is always the "fraud explanation",
so before a report is admitted as evidence, the possibility of fraud has to be ruled out.

We research souls /indirectly/ as we research stars,
because it is difficult to experiment with souls as it is with stars.
Thus we mostly /observe/ and /theorize/.

We also research souls as we do /chemistry/.
The object of study is complex and we do not know what it actually is;
we only know some of its properties and some phenomenons associated with it.
Our current knowledge of /souls/ is similar to our past knowledge of /phlogistons/.
We need a psychic "Lavoisier" to discover the psychic "oxygen" and replace the psychic "phlogiston combustion" theory with "oxygen combustion" theory.
We do not know what a soul is as we did not know what a phlogiston is.
We merely /posit/ their existence and assume that they cause the phenomenons that interest us,
and then we set out to find their properties.

The primary method of reasoning in this research is /abductive/:
Find the simplest theory that explains all known evidence.

There are /experiments/ about afterlife and reincarnation.
Afterlife experiments?
 [fn::https://listverse.com/2009/01/29/top-10-bizarre-afterlife-experiments/]
 [fn::http://www.theoccultmuseum.com/5-chilling-experiments-attempted-prove-existence-afterlife/]
The Future Life Institute proposes an experiment purported to prove reincarnation by 2050.
 [fn::<2019-09-08> http://www.futurelifeinstitute.org/2013/psd/Experiment-Web.pdf]

We are trying to craft experiments that test /dualism/.

Here I sloppily use "soul" and "spirit" as synonyms, and I use them to mean the non-material part of living beings.
I don't think this will be a problem, because we don't know what they are anyway.
 [fn::https://www.etymonline.com/word/soul#etymonline_v_23918]
 [fn::https://www.etymonline.com/word/spirit#etymonline_v_24031]
* Theoretical implications of some evidence
What evidence do we have, and how does it constrain our hypothesis space?
** On past-life memories
The most compelling /evidence/ of memory of past life is the thousands of records meticulously collected, verified, and corroborated by Ian Stevenson and Jim Tucker.
Some children can tell some /facts/ about a specific deceased person that,
according to our common sense, can only be known by the deceased person alone
because he has never told those facts to anyone else.
By "facts", we mean assertions whose truth can be corroborated with historical records or living relatives.
The facts are so specific that an impostor is astronomically unlikely to guess them correctly.
The facts are also not written, recorded, or told, so it does not use known communication channels.
There is a lot of evidence of memory of past lives.
 [fn::<2019-09-08> https://upliftconnect.com/past-lives/]
 [fn::<2019-09-08> https://www.gaia.com/article/incredible-evidence-for-remembering-past-lives]
 [fn::<2019-09-08> https://www.consciouslifestylemag.com/reincarnation-stories-proof-past-life/]
 [fn::<2019-09-08> https://www.rd.com/true-stories/chilling-reincarnation-stories/]
 [fn::<2019-09-08> https://www.google.com/amp/s/www.psychologytoday.com/us/blog/feeling-too-much/201412/children-who-seemingly-remember-past-lives%3famp]
 [fn::<2019-09-08> https://uvamagazine.org/articles/the_science_of_reincarnation]

Past-life memory seems to fade as one grows into adulthood. \cite{haraldsson2012persistence}

Edwin C. May hypothesizes that people with /synesthesia/ are more likely to have precognition ability,
and that there is a /psychic organ/ or a /psychic sensor/ (he uses the analogy "psychic retina").
 [fn::<2019-09-09> How Precognition Works with Edwin C. May https://www.youtube.com/watch?v=37tPK3iwcZ4]

By "memory of past life", I mean memory of /subjective experience/ of past life.

Thus it should also be possible to experience life from other people's point of view;
it should be possible to experience other people's qualia (subjective experience);
it should be possible to /swap souls/, be it temporary or permanent.

That evidence shows that /our common sense is wrong/,
that our understanding of life and death is wrong,
and that, when a man dies, he does not go to heaven, but neither does he disappear into oblivion.

Come to think of it, our common sense (Western rationality common sense) is not so common,
and is rather exceptional than common.

Can one soul reincarnate into two bodies?
Can two people have memory of one deceased person?
If yes, then soul is ideal (software) because it can be copied but not moved.
If no, then soul is material (hardware) because it can be moved but not copied.
I propose that we search for two people who recall the same deceased person.
I hypothesize that we will not find any such pair.

Is it important to ask why the subjects are mostly children between 2 and 5 years old?
Adults may censor themselves to conform to social norms.

A dying soul may be like a dying star:
They explode, reverberating through spacetime.

Now that we have established the existence of the phenomenon,
we ask: /How do they remember their past lives?/
How does it work?
What is the mechanism?

Why does the old soul get diluted as the new person grows into adulthood?

Does the old person has to be willing to reincarnate?

Hypothesis:
Past-life regression may happen due to a /mixing of souls/.
Memory may exist without soul.
Memory may infect souls as prions infect cow brains.

Memory can persist outside brains.
For example, a hard disk has memory.
A capacitor has memory.
Every stateful system has memory.

Souls may broadcast signals that reverberate in the Universe,
and the reverberation may later be picked up by another soul?

Something else?

Perhaps there is a limit to the maximum spacetime distance
between the birthplace of a person and the deathplace of his previous life.
Tongren Yuye 2008
 [fn::translation <2019-09-08> https://www.fyears.org/2010/06/how-to-prove-reincarnation-with-statistical-experiment.html]
 [fn::original in Mandarin Chinese <2019-09-08> https://www.geekonomics10000.com/178]
calls this "the principle of locality of the soul",
in which "a baby's previous body" should die "near the baby's birth place".

We can test the principle of locality of the soul with the records of Stevenson & Tucker.

More interestingly, Stevenson found some /patterns/ in reincarnation.
 [fn::<2019-09-08> https://psi-encyclopedia.spr.ac.uk/articles/patterns-reincarnation-cases]
** Questions on the movement of spirits
How do spirits move?
Do they require energy to move?
Where do they get that energy from?
How do we measure it?

Do ghosts prefer to haunt some places?
What kind of places do ghosts prefer to haunt?
Why?
** Hypotheses on anomalous cognition
I hypothesize that all forms of anomalous cognition is caused by /the same mechanism/.
Anomalous cognition includes recalling past-life memory, telepathy, precognition, possession, and mediumship.

To know whether it is really cognition (that is, whether the subject actually knows something),
we select the subject's anomalous claims that we are sure the subject could not have known conventionally, and then we verify them.
** On mental property transference in organ donations
There are some claims and disclaims that some mental properties are transferred from organ donors to recipients.
Lowth 2016:
Positive https://listverse.com/2016/05/14/10-organ-recipients-who-took-on-the-traits-of-their-donors/
Bunzel et al. 1992: Negative or inconclusive.
Does changing the heart mean changing personality? A retrospective inquiry on 47 heart transplant patients.
https://www.ncbi.nlm.nih.gov/pubmed/1299456
** On anomalous cognition
There are reports of /anomalous cognition/
in which some people see dead people and know some details about those dead people.
For example, Brian Weiss had a patient named Catherine who anomalously told him details about his dead relatives
 [fn::Dr. Brian Weiss: Past-Life Skeptic to Past-Life Expert | SuperSoul Sunday | Oprah Winfrey Network https://www.youtube.com/watch?v=qQAgiP8zQ6M].

The "precognition" subreddit[fn::https://www.reddit.com/r/precognition/].

Does precognition imply retrocausation?
** On experiencing the subjective experience of others
https://www.reddit.com/r/precognition/comments/bhbxzb/seeing_through_the_eyes_of_another_person/
** Questions on souls that fight each other
Are there instances of souls fighting each other to control a body?
** Hypotheses about the properties of souls
What is the /weight/ of a soul?
Has anyone repeated Duncan MacDougall's soul-weighing experiment more rigorously?
It would be the parapsychology analog of the Michelson--Morley experiment?
I think some of the weight difference is because some air leaves the lungs and intestines as muscles relax.
Each liter of air weighs 1.23 gram at room condition.[fn::<2019-09-08> https://en.wikipedia.org/wiki/Density_of_air]
A weight difference of 21 grams would mean that a man expels 17 liters of air when he dies.
I don't think there is that much air in the body.
Even an adult man's pair of lungs only contains 6 liters of air,
and not all of it is expelled when his muscles relax completely.
I don't think anyone can fart 11 liters of air at once;
otherwise coroners would routinely see dead people's bellies implode.

Gasser 2014 says what?
 [fn::http://www.pandualism.com/d/reincarnation.html]
How do we test his "psychon theory"?

https://www.neuroquantology.com/index.php/journal/article/view/389

https://www.lionsroar.com/do-you-only-live-once/
https://www.lionsroar.com/reincarnation-research-buddhism/
https://reincarnationafterdeath.com/theory/

2 people 1 soul?
https://www.quora.com/Can-two-people-share-the-same-soul-1
https://www.reddit.com/r/spirituality/comments/9qbzla/one_soul_in_two_bodies_or_two_souls_in_one_does/
???
http://weeklyworldnews.com/headlines/15170/how-to-tell-if-youre-double-souled/

Are souls /recycled/ in the same way nutrients are recycled in the biogeochemical cycle?

What happens in a /mass death/, such as in the 2004 Aceh tsunami that killed more than 100,000 people?[fn::<2019-09-08> https://en.wikipedia.org/wiki/2004_Indian_Ocean_earthquake_and_tsunami]
Where do all those souls go?
* Claims that require corroboration before they are admissible as evidence
** Claims that may be practical enough to test
Joseph McMoneagle's remote viewing of Mars can be tested.
I think we'll begin exploring Mars in the 21st century.

Joseph (Joe) McMoneagle got a Legion of Merit[fn::https://en.wikipedia.org/wiki/Legion_of_Merit][fn::Joe McMoneagle; <2019-09-07> https://en.wikipedia.org/wiki/Recipients_of_the_Legion_of_Merit].

Ingo Swann[fn::https://en.wikipedia.org/wiki/Ingo_Swann]
** Claims that may be hard to test
Immanuel Kant's account of Emanuel Swedenborg, 18th century.

Evidence captured by 21st century equipments.

Witnesses are often reliable.

Most evidence was anecdotal until J.B. Rhine began using statistics.[fn::Remote Viewing and the Reality of Psychic Phenomena | Waking Cosmos | Garret Moddel Ph.D. https://www.youtube.com/watch?v=IC1kTVe61yc]

We assume that the records are not manipulated?

EVP?

Camera?

Are these experiments trustworthy?
https://www.consciouslifestylemag.com/mind-over-matter-experiments/

Most convincing unexplained recordings for me:
- From https://www.reddit.com/r/AskReddit/comments/1sv39b/serious_what_in_your_opinion_is_the_most/
  - "Ghost scares dogs on camera"[fn::https://www.youtube.com/watch?v=DL_bIhVJi-k]
    - text summary[fn::https://www.reddit.com/r/AskReddit/comments/1sv39b/serious_what_in_your_opinion_is_the_most/ce25ska/]
      - there is also a debunking
  - "My Ghost Story Haunted Lab"[fn::https://www.youtube.com/watch?v=92jFdzNC228&t=2m28s];
    dubious, a reality show?
    - Andy Coppock?
  - https://www.quora.com/What-are-the-most-convincing-paranormal-cases

Are there double-blind parapsychological experiments?

What does the oil industry say about dowsers?
How much money are they betting on it?
If it were big, there had to be something?
https://www.quora.com/What-are-some-practical-applications-of-parapsychology

Oil dowsing: Either it does not work or it is a heavily guarded secret.

What do the archeologists say about psychics?
** Questions on psychokinesis
If psychokinesis is real and moving objects requires energy, where does the energy comes from in psychokinesis?
* My experiments?
** A mind-silencing/mind-idling/mind-parking experiment
I tried to silence my mind, or, perhaps more accurately, /idle/ my mind, or, /park/ my mind, by not thinking anything,
or, by focusing on the null thought (nothingness).
It seemed to dislike silence; it fought back by generating random thoughts.

I tried to pretend that I did not have any senses.

From[fn::https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e61agrg/],
emphasis mine:
#+BEGIN_QUOTE
I've learned from [...]
that the majority of humans seem to walk about oblivious to anything/everything of a psychic nature because
our cultural and other programming has built up our own /psychic shields/, shored up quite by belief (and disbelief).
True disbelievers are rarely, if ever, bothered by or even experience anything psychic. Their shields are strong.

[...]

I know I won't be harmed because a) /ghosts can't physically harm people/ and
b) my "psychic shield" is strong [...] and
c) I have knowledge of the first two which mitigates any negative emotional impact I might feel.
#+END_QUOTE

I tried to silence my mind, with the hope of receiving something, but I received nothing,
as if I were a radio receiver with no nearby radio stations broadcasting any radio waves.
** Filter theory of consciousness? Meditation: focusing or unfocusing?
An attention is a subset of all sensory inputs?

Is meditation about focusing or unfocusing (unfocused awareness)?

* Other
** On the ontology of paranormal things
Telepathy, Clairvoyance, and Precognition are instances of Psychic Ability.

Anomalous Perception is my synonym for Extra-Sensory Perception,
because Perception is the act of /interpreting/ sensory inputs,
and thus perception implies sensors, by definition;
it is just that we don't know the sensor,
in the same way we can use the skin to feel pressure without knowing how the skin transduces pressure into sensory inputs for the brain.

Sensing is the transduction of a phenomenon into a signal.

Ghost is a subclass of Spirit.

Poltergeist is an instance of Paranormal Phenomenon.

Kruth[fn::<2019-09-07> https://tunsasays.wordpress.com/about-this-site/]: "Parapsychology is the scientific study of five specific phenomena."

https://rsbakker.wordpress.com/2014/03/18/the-ontology-of-ghosts/
** What we perceive is not the object itself
I think philosophers have known this for a long time.

What we see is not the object itself, but an /image/ of the object.
We see the light that is reflected or emitted by the object.

What I think I am is only my perception of me and not what I actually am,
in the same way that, when I see a tree, I am seeing the image of the tree, the light that reaches my eyes, not the tree itself.
By "I see a tree", I mean that the light reflected by the tree has arrived at my eyes.
** On anomalous cognition
We assume that, in order for a man to ken something,
he has to perceive an image of it with his senses.
** On testing folk theories and folk hypotheses
We need a falsifiable theory that makes some testable predictions.

The theory has to be to explain paranormal phenomenons such as precognition, spiritual possession, poltergeist, and haunting.

Utts 2001 \cite{utts2001assessment}[fn::Also on CIA website https://www.cia.gov/library/readingroom/document/cia-rdp96-00791r000200070001-9]
claims that "Using the standards applied to any other area of science, it is concluded that psychic functioning has been well established."
Ray Hyman was a co-researcher but did not share the conclusion.

"Senders do not appear to be necessary at all; feedback of the correct answer may or may not be necessary.
Distance in time and space do not seem to be an impediment." \cite{utts2001assessment}:

https://tunsasays.wordpress.com/

Kruth 2015[fn::<2019-09-06> https://tunsasays.wordpress.com/2015/05/04/the-nature-of-psi-the-first-sight-model-and-theory-of-psi/] proposed a theory of psi.
- Carpenter 2004 "First Sight Model and Theory of Psi".
  OK, it explains, but what does it /predict/?
- From <2019-09-06> https://www.rhine.org/who-we-are/9-uncategorised/192-peg-slide.html
- From <2019-09-06> gsearch psychic experiencers group
- From <2019-09-06> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/?sort=confidence

Brian D. Josephson[fn::http://www.tcm.phy.cam.ac.uk/~bdj10/] has a "mind-matter unification project".
He also has spoken out against pseudo-skeptics.

Angela Moore started Psychic Review Online[fn::https://www.psychicreviewonline.com]
to keep track of real and fake psychics.
Interesting: A company named "Psychic Source" has skin in the game with money-back guarantee.

Can we corroborate with Debra Chalmers's previous employer?
https://www.psychicreviewonline.com/blog/in-the-news/725/

https://www.researchgate.net/publication/317784136_What_is_Psi_From_Anti-Parapsychology_to_Psi_as_a_Next_Scientific_Revolution_Theoretical_Reviews_and_Hypothesized_Vision

BDJ https://www.researchgate.net/publication/328968105_The_Physics_of_Mind_and_Thought

https://www.researchgate.net/publication/328968105_The_Physics_of_Mind_and_Thought
** Materialism is false? What are these trying to say?
- 2016 article "Why Materialism Is False, and Why It Has Nothing To Do with the Mind"
  https://www.cambridge.org/core/journals/philosophy/article/why-materialism-is-false-and-why-it-has-nothing-to-do-with-the-mind/5DC675B901E2F68E82643B88EE468EAE
*** Are materialism and subjective experience compatible?
- Problem of other minds.
*** What is non-local consciousness? Are these legit or kook?
**** Pim van Lommel, cardiologist, consciousness after clinical death
- [[https://en.wikipedia.org/wiki/Pim_van_Lommel][WP:Pim van Lommel]]
  - [[https://en.wikipedia.org/wiki/Near-death_experience][WP:Near-death experience]]
**** Sam Parnia's AWARE study
- https://en.wikipedia.org/wiki/Sam_Parnia
**** Dying, near-death experiences, thanatology
- http://www.nderf.org/
- [[https://iands.org/news/news/front-page-news/1060-aware-study-initial-results-are-published.html][AWARE study initial results are published!]]
- https://www.resuscitationjournal.com/article/S0300-9572%2814%2900739-4/pdf
- [[https://www.youtube.com/watch?v=mMYhgTgE6MU][YT:From life to death, beyond and back - Thomas Fleischmann - TEDxTUHHSalon]]
**** Central premonitions registry
- 1968, http://www.weirduniverse.net/blog/comments/central_premonitions_registry
- 2017, https://scry.cloud/
**** Astral travel, remote viewing, out-of-body experience?
- https://allaboutheaven.org/observations/1122/127/swann-ingo-out-of-body-to-mercury-003207
- https://www.quora.com/Is-astral-projection-true-If-so-has-anyone-done-it-Is-there-a-standard-procedure
- [[https://www.youtube.com/watch?v=bjQxwm9vuiE]["Experiments Proving Astral Projection is Real"]]
** On spirits, ghosts, possessions, and mediums
What places do ghosts prefer to haunt, and why?
How do ghosts decide what places to haunt?

The folk theory is that spirits can possess bodies.

Auerbach 2018 claims that ghosts cannot physically harm people.[fn::<2019-09-07> https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e61agrg/]
*** What happens after we die?
Compare:
- https://tunsasays.wordpress.com/2015/04/23/the-survival-hypothesis-a-very-brief-discussion/
** On the nature-versus-nurture of psychic abilities
*** On the learnability of psychic abilities
Can one learn to be psychic?
Conflicting opinions:
- Angela Moore: "Psychic ability can not be learned. You're either born with the gift or you aren't"[fn::https://www.psychicreviewonline.com]
- Carpenter 2004 psi theory/model

It disheartens me to hear people say that psychics are born and not made.
*** On the genetic basis of psychic abilities?
It seems that psychic abilities run in families.
 [fn::https://psychicelements.com/blog/are-psychic-abilities-hereditary/]
 [fn::https://www.anthonstmaarten.com/blog/psychic-dna-nature-or-nurture]

Does it have genetic basis?
Hereditary?
Inherited trait?

https://noetic.org/research/genetics-of-psychic-ability/

If psychic abilities are inherited, then they may have genetic basis.
If there does not seem to be any genetic basis,
then dualism may be true and there may be mental genetics we don't yet know.

Is the non-psychic person doomed?
Is being non-psychic like being a lactose-intolerant,
in the sense that you /just can't/ produce the enzyme because you were born without the necessary machinery
(unless you underwent some gene therapy perhaps)?
*** On the effects of the mother's emotional state while conceiving her baby
It seems that stressing the pregnant mother may affect the epigenetics of the unborn baby.

Dutch famine experiment.

What if the mother is physically unstressed but mentally stressed?
That is, what if we give the mother the perfect nutrition, but we mentally torture the mother?
What will happen to the unborn baby?
What will the baby become?

https://www.jashow.org/articles/hereditary-coherence-and-other-forms-of-transference/

*** On using babies and animals as sensors
If babies are more sensitive to paranormal phenomenons, then we can use babies as paranormal sensors!
** On embodied consciousness or possessed body?
Is each of us a consciousness that gets trapped in a body, or a body that gets possessed by a consciousness?

Are we mostly ideal/mental or mostly material/physical?

Is poltergeist a body that gets possessed by a consciousness?

Hypothesis:
Both a human and a poltergeist are a combination of mind and body.
But a human is more body than mental whereas a poltergeist is more mental than body.
** On the care that has to be taken before invoking quantum physics
Parapsychology itself already makes people think you're a lunatic.
Invoking quantum physics will make people think you're a deranged lunatic.
* Bibliography
