#+TITLE: The root cause of Boeing 737 MAX fiasco: existentially-threatening competitions?
#+DATE: 2019-07-07 00:00:00 +0700
#+PERMALINK: /boeing.html
The Boeing 737 MAX fiasco is not a mere software accident,
because the software is working as intended,
that is as a crutch to work around bad hardware design due to cost-cutting.
That plane is a pile of workarounds:
that software is a workaround for bad hardware which is a workaround for bad business decisions.
They are making planes as game companies make games:
They think they can just release crashing planes and patch the planes later,
but planes kill people when they crash, whereas games don't.
That fiasco is a case of prioritizing profits before engineering,
but unfortunately, Nature, the judge,
will always grant victory to physics, when physics and profits disagree.

However, can we blame companies for seeking profit,
because profit is necessary for their survival?
Does it mean that airplanes should be made by non-profits?
But who is going to do anything at all, if not for profit?
But why can't we just gather the people who are good at building airplanes,
and give them money and tools to build airplanes?

A possible solution is to make organizations in which people just build planes they would themselves love to ride.
They may compete a bit, but they must not compete to survive.
Competition may exist, but must not be an existential threat.
Non-profits would be even more efficient if there were no competition.
But even non-profits need money, and that money has to come from somewhere,
and no one is going to suddenly donate some billion dollars and start a non-profit organization that makes airplanes.
Or is anyone going to do that?
The richest people can do that several times over, but will they?

The root cause of the Boeing 737 MAX crashes is that competition presents an existential threat to companies.
If I had to design a plane while facing an existential threat,
such as being held at a gunpoint,
then my plane would probably crash too, as I cut corners to save my life.
So the question is, how do we remove the gun,
so that I can design planes in peace,
while also ensuring that my design makes sense physically and economically?

Competition has given us big companies that produce all luxuries that our ancestors could only imagine but we take for granted.
But the future is cooperative, not competitive.

Competition is wasteful.
Boeing and Airbus are full of smart people reinventing each other's wheels.
It would be better if those smart people cooperate to make the best airplanes.
