#+TITLE: Summary of some books
#+DATE: 2019-09-28 00:00:00 +0700
#+PERMALINK: /book.html
* About
What I am interested in: theories (testable theories, not conspiracy theories), hypotheses, corroboratable facts, experiments, reports, observations.

Usually I prefer engineers and scientists who have experienced anomalies themselves.

Perhaps a more appropriate title is "Review of some authors".
* Planned
** "Psychic Development [...]", William W. Hewitt
"Psychic Development for Beginners"
** "Astral Travel [...]", Richard Webster
"Astral Travel for Beginners: Transcend Time and Space with Out-of-Body Experiences"
* "The Magus of Java: [...]", Kosta Danaos
"The Magus of Java: Teachings of an Authentic Taoist Immortal"

This book is Kosta Danaos's account of John Chang,
a level-4-of-72 neigong master at the time that book was written.

Kostas and John did some experiments and had some hypotheses about yin and yang.
* "Proof of Heaven [...]", Eben Alexander
"Proof of Heaven: A Neurosurgeon's Journey into the Afterlife"

This book is Eben Alexander's account of his near-death experience.

He considered how some materialistic hypotheses fail to explain the experience he had when his neocortex was not functioning.
* "The Reality of ESP: [...]", Russell Targ
"The Reality of ESP: A Physicist's Proof of Psychic Abilities"
* "Kundalini: [...] Guide [...]", Kimberly Moon
"Kundalini: The Ultimate Guide to Awakening Your Chakras Through Kundalini Yoga and Meditation and to Experiencing Higher Consciousness, Clairvoyance, Astral Travel, Chakra Energy, and Psychic Visions"

What a long title.

The book is relatively short for its very long title.

I feel that this book is a mere aggregation of information found by googling lots of sites.
I feel it contains little original thought, commentary, opinion, or insight.
It feels like a bunch of generic wellness advices.
It feels like a mere repetition of what others say.
It feels like a mere echo in the giant echo chamber that is the Internet.

I feel this book is optimized for search-engine.
The title is full of gratuitous keywords.
Lots of list-titled chapters (like 123 ways you can do XYZ).

Did she try anything she wrote?
Did she have any experience about it?
What worked for her, and what did not?
What are her experiments and hypotheses?
Why did she not write about such things?

Nevertheless, it is a guide, as its title claims, but not the ultimate guide.
It is a guide in the sense that it provides some procedures you can try.
* "Mind Trek [...]", Joseph McMoneagle
"Mind Trek: Exploring Consciousness, Time & Space through Remote Viewing"

Interesting: His out-of-body experience interferes with his remote viewing.
* "Remote Viewing: [...]", Ingo Swann
"Remote Viewing: The Real Story, An Autobiographical Memoir"
* Need to background-research the authors
Books whose title contains "secret" or "hidden" are suspect.

The title of these books arouses my suspicion.
I demand a background check on the authors before I read these books.

David Wilcock's "The Hidden Science of Lost Civilisations: The Source Field Investigations"
has some facts, but?
