#+TITLE: On spirituality and business
#+DATE: 2020-01-11 00:00 +0700
* We don't have to choose between BSD and GPL
We can choose /both/.

Why not all of them?

We can say "The project is licensed under these licenses, at your choice: BSD/MIT/X11/ISC/MPL/Apache2/GPL/LGPL/AGPL"

BSD does not forbid adding restrictions.

I choose BSD/MIT/Apache2 because I want humans to flourish, not companies to suffer.

I choose the licenses that are based on love, not on hatred.

People choose GPL because they hate capitalism first, and they want humankind to benefit second.
I used to hate capitalism, but now I see that it is neutral, and the problem is humans, not systems.
If a company freeloads on an open-source project, people can choose to not buy from the company.
* Taxation
Spirit of corporate taxation laws:
- Personal expenses are not corporate expenses.
* What
Why does the company retain most of its profits?
To create buffer.
Reinvest?

I want a company without employees.
Everyone is paid according to their impact?
Everyone bids?

If money should not be given to those who do not know what to do with it,
then either employees should be paid less or nobody should be employees (everybody should be one-person businesses instead).

If profit is theft, then loss is also theft.
If a profiting employer is fleecing its employees,
then a losing employer is being fleeced by its employees.

We are not customer-driven because customers can be immoral.

We are self-driven.

We want to be God-driven, but we don't know how to be sure that it's God.

Employers trust God more than employees do?

Adam Smith's theorem?
Voluntary trade improves everyone's satisfaction / satisfied wants.
But what about drug users?
Do they voluntarily trade their hard-earned money for harmful drugs?

Business = intrinsic motivation * distribution channel?

What
https://wanderingaimfully.com/start-a-business/

Write principles, start my own businesses. Trust God. A businessperson trusts God more than an employee does. In risk is God.

Avoid looking down on old-school capitalists.
Do not feel holier than others.

No employment. No command. No power asymmetry.

Employment is immoral, but most people prefer certain income, stability, and low risk appetite, only want to master a narrow range of things.
Or it's just that sometimes employment is necessary because control?

Nature provides more than a social safety net can ever provide:
A fertile land to live on forever.

Accounting should be truthful.
If truth is not possible, then it should be pessimistic.
Debts and expenses are certain.
Assets and incomes are uncertain.
* Ethical advertising
We inform, not manipulate.

No discounts. No promotions.
* Computational complexity and intellectual property
The intended definition of intellectual property is something hard enough to compute/create/come up with.

Patents, copyrights, and intellectual properties hamper progress.

If ideas are planted in our minds by spirits, then nobody has the right to claim authorship?

An insurance company can only profit by making the average person lose.
It's cheap when you're young and you don't need it.
It's too expensive when you're old and you need it.

The insurance company makes the book so it has house advantage.
Search "actuarial tables".

Appeal to fear.

#+BEGIN_VERSE
God is my insurance.
Illness is God's calling me home.
#+END_VERSE
* Inspiring Internet onion seller
Inspiring Internet onion seller[fn::https://www.deepsouthventures.com/i-sell-onions-on-the-internet/]:
It's /stupidly simple/, but it's /real money/.
It's /good business/.

https://www.bradford-delong.com/2017/07/how-to-think-like-an-economist-if-that-is-you-wish-to.html
https://hackernoon.com/how-to-make-more-money-as-a-software-developer-da9fc13944e4
https://en.wikipedia.org/wiki/Economic_system
https://en.wikipedia.org/wiki/Circular_economy

https://en.wikipedia.org/wiki/Productivity_model
https://en.wikipedia.org/wiki/Productive_forces
https://en.wikipedia.org/wiki/Production_(economics)
* <2019-08-17> Economics: anti-cafe
In anti-cafe, one pays for time, not for food.[fn::https://en.wikipedia.org/wiki/Anti-café]
* Open source?
https://github.com/tycrek/degoogle/blob/master/README.md
* Business vs company
Business is essence/activity/spirit/idea.
Company is form/detail/execution/body.

Business : company = spirit : body.
* Old contents
- [[file:rich.html]] was written when I was a materialist before I was into spirituality
