#+TITLE: Cara memilih pejabat dalam sebuah demokrasi
#+DATE: 2019-08-21 00:00:00 +0700
#+PERMALINK: /cara-memilih-pejabat.html
/Pertama/, Anda harus bertanya "/Apa untungnya buat saya/ kalau saya pilih dia?"

Contoh alasan yang masuk akal:
- Saya pilih dia karena dia janji akan mengurangi pajak saya.
- Saya pilih dia karena dia janji akan mempermudah perizinan gereja/wihara/kuil/klenteng/dll.
- Saya pilih dia karena dia janji akan mengatasi banjir di rumah saya /dengan cara yang masuk akal/.
- Saya pilih dia karena dia janji akan mengatasi macet dan mengurangi polusi /dengan cara yang masuk akal/.
- Saya pilih dia karena program kerja dia memperbaiki kehidupan banyak orang /dengan cara yang masuk akal/.
- Saya pilih dia karena dia sepaham dengan pejabat-pejabat lain yang saya pilih dan dia akan membantu program kerja mereka.

Contoh alasan yang /bodoh/ dan merusak negara:
- Saya pilih dia karena dia ganteng/cantik/baik/pintar/sopan/dll. (Apa untungnya buat Anda?)
- Saya pilih dia karena dia satu agama/suku/kampung dengan saya. (Apa untungnya buat Anda?)
- Saya pilih dia karena baliho dia paling besar. (Apa untungnya buat Anda?)

/Kedua/, Anda harus bertanya
"Bagaimana orang ini akan mewujudkan janji tersebut /dengan cara yang masuk akal/?"
Ini untuk mencari tahu apakah orang ini memang bisa memenuhi janjinya.
Kalau dia tidak bisa beri jawaban yang masuk akal, dia cuma asal janji.

Jangan tanya "Anda bisa?", tapi tanya "Bagaimana caranya?"
Kalau jawabannya tidak masuk akal, berarti sama saja dengan dia tidak berjanji apa-apa.
Kalau dia jawab "Tidak tahu", dia orang /jujur meskipun bodoh/.
Kalau jawabannya tidak masuk akal, berarti dia /sudah bodoh penipu pula/.
Tentu lebih baik bodoh dan /jujur/ daripada bodoh dan /penipu/.

/Ketiga/, Anda harus bertanya "Apa ada janjinya yang saling bertentangan?"
Misalnya, dia berjanji ke rakyat /menaikkan/ pajak pengusaha,
tapi dia berjanji ke pengusaha /menurunkan/ atau tidak mengubah pajak pengusaha (hal yang sama).
Kalau ada janjinya yang demikian, niatnya naik pangkat, bukan melayani rakyat;
catatlah buktinya, dan perlihatkan dustanya ke orang-orang.

Politisi /boleh saja mengubah pendapatnya/, tetapi harus /dengan alasan yang masuk akal/,
misalnya karena dia baru menemukan suatu penelitian ilmiah yang bertentangan dengan pendapat lamanya.

Seandainya memang tidak ada calon yang becus, kita bisa /golongan putih/ atau bahkan /rombak negara/,
tapi biasanya sih selalu ada minimal satu calon yang becus.

Kalau Anda memilih politisi tanpa pikir panjang, Anda sendiri yang rugi.
Contohnya, lihat orang-orang yang dulu memilih Anies Baswedan dan Sandiaga Uno
tapi kemudian
/demo/[fn::2019-07-16: Didemo Nelayan, Anies Baswedan Dinilai Ingkar Janji Soal Reklamasi https://tirto.id/didemo-nelayan-anies-baswedan-dinilai-ingkar-janji-soal-reklamasi-eeoB],
/kecewa/
 [fn::2018-08-14: Anies Coret Anggaran Selter, Warga Bukit Duri Kecewa https://www.cnnindonesia.com/nasional/20180814185837-20-322267/anies-coret-anggaran-selter-warga-bukit-duri-kecewa]
 [fn::2019-06-24: Soal Reklamasi, Pendukung Termakan Janji Manis Anies https://www.wartaekonomi.co.id/read233318/kecewa-pendukung-anies-kecewa-janji-manis-anies.html]
 [fn::2019-06-27: Masyarakat Nelayan Kecewa Anies Terbitkan IMB Reklamasi https://nasional.republika.co.id/berita/nasional/jabodetabek-nasional/ptpkas409/masyarakat-nelayan-kecewa-anies-terbitkan-imb-reklamasi]
 [fn::2019-08-18: Nelayan Angke Kecewa Kepada Anies Karena Lakukan Upacara Di Pulau Reklamasi http://indonews.id/artikel/23130/Nelayan-Angke-Kecewa-Kepada-Anies-Karena-Lakukan-Upacara-Di-Pulau-Reklamasi/],
/menyesal/[fn::2017-11-03: UMP 2018 Rp3,6 Juta, Serikat Buruh Menyesal Pilih Anies-Sandi https://www.cnnindonesia.com/nasional/20171103153223-20-253275/ump-2018-rp36-juta-serikat-buruh-menyesal-pilih-anies-sandi],
dan /merasa dikhianati/[fn::2019-06-25: Nelayan Teluk Jakarta Merasa Dikhianati Anies https://nasional.republika.co.id/berita/nasional/jabodetabek-nasional/ptm4k1330/nelayan-teluk-jakarta-merasa-dikhianati-anies] oleh pilihan mereka sendiri.
Itu kata /pemilih mereka sendiri/ lho, bukan karangan saya.
Tentu mereka bukan politisi pertama yang mengecewakan pemilih mereka sendiri,
tapi mereka yang paling terkenal, berkat kerusuhan Pilkada Gubernur Jakarta 2017.

Jadi, setiap kali ada pemilihan, Anda cukup bertanya:
1. /Apa untungnya buat saya/ kalau saya pilih dia?
2. Bagaimana dia akan mewujudkan janjinya /dengan cara yang masuk akal/?
3. Apa ada janjinya yang saling /bertentangan/?

Tapi saya khawatir, jangan-jangan pola pikir "apa untungnya buat saya"
bisa perlahan mengubah negara jadi plutokrasi seperti di Amerika:
pemilik perusahaan besar mendukung politisi yang menguntungkan mereka, tidak peduli merugikan orang banyak.
