#+TITLE: On the evolution of the ontology of chemistry
#+DATE: 2019-08-17 00:00 +0700
#+PERMALINK: /chemistry-ontology.html
#+MATHJAX: yes
#+OPTIONS: toc:nil
* Abstract
Here we discuss the evolution of the ontology of chemistry between the 1st century and the 21st century?

An example of mereology: molecules = atoms + bonds.

Forces from strong to weak: nuclear force, chemical bond, intermolecular force, electrostatic force?
* The ontology of chemistry, before molecules
What can be inferred from reason and unaided observation?

An atom is an indivisible thing.
This is defined a-priori.
This is declared by fiat.

TODO
WP:democritus ref no 32
* The ontology of chemistry, after molecules
* The ontology of chemistry, after subatomic particles
* Ontology of chemistry before molecules
What is a mixture?

Mixing salt and water produces salt water,
which can be separated by distillation,
but mixing wood and oil of vitriol does not produce woody oil of vitriol.

When a homogenous mixture is divided into two equal parts, both parts have the same properties.

How did Democritus arrive at his idea,
at such a long time before electrochemistry was discovered?

From https://en.wikipedia.org/wiki/Democritus#Atomic_hypothesis <2019-08-09>

#+BEGIN_QUOTE
Democritus, along with Leucippus and Epicurus, proposed the earliest views on the shapes and connectivity of atoms.
They reasoned that the solidness of the material corresponded to the shape of the atoms involved.
Thus, iron atoms are solid and strong with hooks that lock them into a solid; water atoms are smooth and slippery;
salt atoms, because of their taste, are sharp and pointed; and air atoms are light and whirling, pervading all other materials.[32]
Using analogies from humans' sense experiences,
he gave a picture or an image of an atom that distinguished them from each other by their shape,
their size, and the arrangement of their parts. Moreover,
connections were explained by material links in which single atoms were supplied with attachments:
some with hooks and eyes others with balls and sockets.[33]
The Democritean atom is an inert solid (merely excluding other bodies from its volume) that interacts with other atoms mechanically.
In contrast, modern, quantum-mechanical atoms interact via electric and magnetic force fields and are far from inert.
#+END_QUOTE

See also the book:
Pfeffer, Jeremy, I.; Nir, Shlomo (2001). Modern Physics: An Introduction Text. World Scientific Publishing Company. p. 183. ISBN 1-86094-250-4.

#+BEGIN_QUOTE
However, Lucretius, describing atomism in his De rerum natura, gives very clear and compelling empirical arguments for the original atomist theory.
He observes that any material is subject to irreversible decay.
Through time, even hard rocks are slowly worn down by drops of water.
Things have the tendency to get mixed up: Mix water with soil and mud will result, seldom disintegrating by itself.
Wood decays.
However, there are mechanisms in nature and technology to recreate "pure" materials like water, air, and metals.[citation needed]
The seed of an oak will grow out into an oak tree, made of similar wood as historical oak trees, the wood of which has already decayed.
The conclusion is that many properties of materials must derive from something inside, that will itself never decay,
something that stores for eternity the same inherent, indivisible properties.
The basic question is: Why has everything in the world not yet decayed,
and how can exactly some of the same materials, plants,
and animals be recreated again and again?
One obvious solution to explain how indivisible properties can be conveyed in a way not easily visible to human senses,
is to hypothesize the existence of "atoms".
These classical "atoms" are nearer to humans' modern concept of "molecule" than to the atoms of modern science.
The other central point of classical atomism is that there must be considerable open space between these "atoms":
the void. Lucretius gives reasonable arguments[citation needed]
that the void is absolutely necessary to explain how gasses and liquids can flow and change shape,
while metals can be molded without their basic material properties changing.
#+END_QUOTE
* Ontology of chemistry after molecules
Molecules, elements, compounds
* Digression: Language, naming
First some people saw a lion before we had a name for it,
and then they named it "lion",
and then we began to use the word "lion" to mean it.

But it is the reverse with atoms.

First we define the word "atom" to mean "a body which cannot be cut in two"[fn::Maxwell, 1873, "Molecules"],
and then we look for it in Nature.

A name enables us to know that we do not know,
and to communicate our ignorance,
and to find ways to know about that name.

Thus, atoms were defined a-priori by fiat.
* TODO Pure compound?
<2019-07-17> https://cnx.org/contents/f8zJz5tx@7.1:PJxH0gb1@6/2-1-Early-Ideas-in-Atomic-Theory

#+BEGIN_QUOTE
Dalton knew of the experiments of French chemist Joseph Proust, who demonstrated that /all samples of a pure compound contain the same elements in the same proportion by mass/.
This statement is known as the /law of definite proportions/ or the /law of constant composition/.
#+END_QUOTE

What is a /pure compound/?
* Molecules, ancient
<2019-07-16> https://en.wikipedia.org/wiki/Molecule#History_and_etymology

#+BEGIN_QUOTE
The definition of the molecule has evolved as knowledge of the structure of molecules has increased.
Earlier definitions were less precise, defining molecules as the smallest particles of pure chemical substances that still retain their composition and chemical properties.
#+END_QUOTE
* Basic chemical ontology
https://education.jlab.org/qa/

What is the difference between atoms and elements?
https://education.jlab.org/qa/atoms_and_elements.html

What is the simplest way of explaining what atoms, elements, compounds and mixtures are?
https://education.jlab.org/qa/atom_02.html

What is a mixture?
https://education.jlab.org/qa/mixture.html

On the Epistemological and Ontological Status of Chemical Relations
http://www.hyle.org/journal/issues/16-2/bernal.pdf

SUBSTANCES: THE ONTOLOGY OF CHEMISTRY
https://core.ac.uk/download/pdf/34432791.pdf

"Substance" is a synonym of "thing".

"Oil of vitriol" can be obtained by following a recipe for making "oil of vitriol".

"Ammonia" is the smelly thing near the Temple of Ammon.

If we have an unidentified substance that smells like ammonia, how do we know that it is indeed ammonia?

- First, we name a thing (such as "ammonia").
- Then, we identify its properties (such as a certain odor).
- Then, we reuse the name to mean all things that have the same properties.

"Sulfur" did not always mean the atom with 16 protons.

https://www.johnastewart.org/networked-narratives/a-brief-history-of-alchemy/

#+BEGIN_QUOTE
Jabir ibn Hayyan developed a theory that said that all metals and minerals were composed of two more fundamental elements: sulphur and mercury. [...]
The more sulphureous elements were thought to be more brittle. [...] Metals and minerals with more mercury were more malleable and shiny.
#+END_QUOTE

Mixture vs compound
https://education.jlab.org/qa/atom_02.html

Example:
In hydrogen gas.
Each hydrogen-gas /molecule/ consists of two hydrogen /atoms/ bound to each other.

A molecule is a bunch of bound atoms.
* Standardization of chemical notations
1860
https://en.wikipedia.org/wiki/Karlsruhe_Congress
* Atoms and the absence of actual infinities
Democritus's atomic theory follows from the hypothesis that actual infinites do not exist.
It is the hypothesis that Nature, although vast, is finite.

How do we know that Nature is finite?

How do we know that it is not a limitation of our instruments?
* How do we know that gases diffuse?
Maxwell 1873 "Molecules"[fn::https://web.archive.org/web/20070209001003/http://www.thecore.nus.edu.sg/landow/victorian/science/science_texts/molecules.html]:

#+BEGIN_QUOTE
As most gases are invisible, I shall exhibit gaseous diffusion to you by means of two gases, ammonia and hydrochloric acid, which, when they meet, form a solid product.
#+END_QUOTE
* Molecules: How do we know?
<2019-07-15>
What is a molecule?
"An atom is a body which cannot be cut in two;
a molecule is the smallest possible portion of a particular substance."
 [fn::Maxwell 1873 <2019-07-15> https://en.wikipedia.org/wiki/History_of_molecular_theory]
 [fn::Maxwell 1873 "Molecules" https://web.archive.org/web/20070209001003/http://www.thecore.nus.edu.sg/landow/victorian/science/science_texts/molecules.html]

https://en.wikipedia.org/wiki/History_of_molecular_theory

#+BEGIN_QUOTE
the composition of water [that water consists of two hydrogen atoms and one oxygen atom] was not known before Avogadro (c. 1811).

In 1738, Swiss physicist and mathematician Daniel Bernoulli published Hydrodynamica, which laid the basis for the kinetic theory of gases.
In this work, Bernoulli positioned the argument, still used to this day, that gases consist of great numbers of molecules moving in all directions,
that their impact on a surface causes the gas pressure that we feel, and that what we experience as heat is simply the kinetic energy of their motion.
The theory was not immediately accepted, in part because conservation of energy had not yet been established,
and it was not obvious to physicists how the collisions between molecules could be perfectly elastic.

Amedeo Avogadro created the word "molecule".[8] His 1811 paper "Essay on Determining the Relative Masses of the Elementary Molecules of Bodies",
he essentially states, i.e. according to Partington's A Short History of Chemistry, that:[9]
[...]

Avogadro developed this hypothesis in order to reconcile Joseph Louis Gay-Lussac's 1808 law on volumes and combining gases with Dalton's 1803 atomic theory.
The greatest difficulty Avogadro had to resolve was the huge confusion at that time regarding atoms and molecules—one of the most important contributions of Avogadro's work was clearly distinguishing one from the other, admitting that simple particles too could be composed of molecules, and that these are composed of atoms.
Dalton, by contrast, did not consider this possibility. Curiously, Avogadro considers only molecules containing even numbers of atoms; he does not say why odd numbers are left out.

The year 1873, by many accounts, was a seminal point in the history of the development of the concept of the "molecule".
In this year, the renowned Scottish physicist James Clerk Maxwell published his famous thirteen page article 'Molecules' in the September issue of Nature.[15]
In the opening section to this article, Maxwell clearly states:
#+BEGIN_QUOTE
An atom is a body which cannot be cut in two; a molecule is the smallest possible portion of a particular substance.
#+END_QUOTE
#+END_QUOTE

Mole: What is it?[fn::<2019-07-15> https://en.wikipedia.org/wiki/Mole_(unit)]

Dalton defined the relative mass of hydrogen gas to be 1.
* Atoms: How we know they exist
An atom is supposed to be an indivisible matter.
But how do we know that it is really indivisible?

What are the properties of an atom?
Indivisibility, supposedly.

How do we know that atoms exist?
By dividing objects until we cannot.
But what is the reason of our inability:
Is it a limitation of our technology, or is it a limitation of Nature?

How do we infer that atoms exist?

We have it easy: School teachers shove atomic theory down our throat.
Our ancestors had to figure it out the hard way:
They have to hypothesize, experiment, fail, and even die, many times.
We arrived at 21st century chemistry through a lot of experiments and reasoning.
We don't see the toil of our ancestors, the thousands of hypotheses falsified by experiments.

How do we know atoms exist?[fn::http://www.bbc.com/earth/story/20151120-how-do-we-know-that-things-are-really-made-of-atoms]
Brownian motion?
Dalton's ratios?
 [fn::http://chemed.chem.purdue.edu/genchem/history/dalton.html]
 [fn::Dalton's disputed nitric oxide experiments and the origins of his atomic theory. https://www.ncbi.nlm.nih.gov/pubmed/18175369]

What is the details of Dalton's experiment?
What gases did he use?
What did he do?

Electron microscopes?
But there was no such thing back then.
How do we know atoms exist without electron microscopes?

Most knowledge about atoms is inferred, not directly perceived.
Indeed knowledge about atoms is inferred abductively, not deductively.

It seems that we can only study minuscule things abductively and not deductively,
because we lack the senses to perceive them directly.

- Require: Chemical element
- [[https://en.wikipedia.org/wiki/Atom#First_evidence-based_theory][WP:Atom, first evidence-based theory]]
  - John Dalton (1766--1844)
  - [[https://en.wikipedia.org/wiki/Law_of_multiple_proportions][WP:Law of multiple proportions]]
    - [[https://en.wikipedia.org/wiki/Stoichiometry][WP:Stoichiometry]]
      - [[http://chemed.chem.purdue.edu/genchem/history/stoichiometry.html][The origins of stoichiometry]]
      - [[https://en.wikipedia.org/wiki/Jeremias_Benjamin_Richter][WP:Jeremias Benjamin Richter]] (1762--1807)
      - Observe:
        - Burning wood produces /ash/.
        - Burning /more/ wood produces /more/ ash.
        - The amount of ash produced is /proportional/ to the amount of wood burned:
          - If burning \( x \) amount of wood produces \( y \) amount grams of ash,
            then burning \( a \cdot x \) amount grams of wood produces \( a \cdot y \) amount of ash.
    - Require: A chemical reaction that is available to prehistoric humans, and whose reactants and products are easy to weigh.
      - [[https://en.wikipedia.org/wiki/Chemical_reaction#History][WP:Chemical reaction, history]]
        - "combustion in fire, fermentation and the reduction of ores to metals were known since antiquity"
      - Chemical reaction notation example: wood + air + fire -> ash
  - Observe: [[https://en.wikipedia.org/wiki/Conservation_of_mass][WP:Conservation of mass]]
    - Burn up a piece of wood in a sealed container.
    - Observe: The mass of the container is unchanged.
- What was Democritus's justification?
  - http://people.wku.edu/jan.garrett/democ.htm
  - Is it in Roberto Torretti's 1999 book "The philosophy of physics"?
- Section: Compound, bond, molecule, ion
  - [[https://en.wikipedia.org/wiki/Molecule][WP:Molecule]]
    - Define: Something is either a /molecule/ or an /ion/.
* Atomic masses?
How do we know that H 1 amu, He 2 amu, Li 3 amu, etc.

How do we weigh atoms?
Spectroscopy.
"What about before the days of mass spectrometers, when chemists were fuzzy about what an atom even was?
Then, they primarily measured the weights of the atoms that composed various elements in terms of their relative masses, rather than their actual masses."
 [fn::https://www.livescience.com/20581-weigh-atom.html]
* Nucleus: How do we know?
Geiger--Marsden experiment?
* Atomizers do not split things into atoms
An atomizer is a spray with very small nozzle.
 [fn::https://en.wikipedia.org/wiki/Atomizer_nozzle]
  [fn::https://en.wikipedia.org/wiki/Atomization]
It emits very small particles, but they are still much larger than atoms.[fn::https://www.nyu.edu/classes/tuckerman/adv.chem/lectures/lecture_3/node1.html]
* The evolution of chemical ontology
People interpreted words differently.
* Atoms, redefined: Another language issue
At first, we defined "atoms" to be something unsplittable.
Then, after several millenniums of research,
we finally found some things that we could not split, so we named them "atoms".
Then, a few decades later, with improved instruments, we found that such atoms could indeed be split into electrons, protons, neutrons.
Alas, in the meantime, hundreds of textbooks had been written, and the name had stuck.
Thus, we redefined "atom" to mean a neutral bunch of protons, neutrons, and electrons,
so that we did not have to rewrite all those textbooks.
After all, words do not carry their meanings themselves; it is we who interpret words into meanings.

How do we know whether something is a limitation of Nature or a limitation of our technology?
* Bonds: What are they?
Nick Lucid
 [fn::https://www.youtube.com/watch?v=mFKCW_D2oE4]
 [fn::https://www.youtube.com/watch?v=g39nwNm0Xfw]
