#+TITLE: Computation
#+DATE: 2017-06-29 22:40 +0700
#+PERMALINK: /compute.html
#+MATHJAX: yes
- What is the theory of computation?

  - What is it concerned with?
  - What are its important results?

- Where should we begin?

  - Should we begin by defining a function, a machine,
    computation, complexity, or a problem class?
  - Suppose we have a function $f : A \to B$.
  - Given an input function $\alpha : A \to S$,
    an output function $\beta : S \to B$,
    and a transition function $m : S \to S$,
    the computation is $f = \beta \circ m^\infty \circ \alpha$.
  - The space of all functions from $A$ to $B$: $F~A~B$.
  - We know that a function is a kind of relation.
    A relation composes.
    $(S, \circ)$ where $\circ$ is associative.
    There is identity relation.
    There is inverse relation.
    Therefore the relation space forms a group.
    The function space forms a semigroup.

- ontology?
  - (moved to file:philo.org)
  - computable
    - [[https://en.wikipedia.org/wiki/Computable_function][WP:Computable function]]
  - computation
  - problem
    - [[https://en.wikipedia.org/wiki/Computational_problem][WP:Computational problem]]
    - [[https://en.wikipedia.org/wiki/Decision_problem][WP:Decision problem]]
  - computation graph
    - ? $M$ /simulates/ $N$ iff a subgraph of $M$ is isomorphic to $N$.
      - $T$ is the type of terms.
      - $M$ is the semantic function.
    - Shortcut
      - The /shortcut/ of $A$ is $B$ where
        $$
          B(x,y) = \text{\\(x\\) is initial, \\(y\\) is terminal, and \\(x\\) reaches \\(y\\).}
          $$
        - $A$ should be acyclic.
      - Alternative names for shortcut:
        [[https://en.wikipedia.org/wiki/Disintermediation][WP:Disintermediation]],
        immediation,
        curtailment,
        shortening,
        abridgement.
      - Shortcutting is idempotent:
        the shortcut of the shortcut is the shortcut itself.
- Do not confuse a /problem/ and an /algorithm/ that solves that problem.
  - Example:
    Consider $p(x)$ that
    wastes $2^{|x|}$ steps,
    and then returns the leftmost bit of $x$.
    Thus $p \in \ExpTime$,
    but $\Search(p) \in \Time(O(1))$,
    because every string that begins with $1$ satisfies $p$,
    and we can just hardcode any of those strings in the solution of $\Search(p)$.

- rewriting system

  - What does it mean that a rewriting system /computes/ a function?
  - Given more time, a rewriting system can compute more functions.
  - A Turing machine is a rewriting system.
  - What is the difference between a rewriting system and a formal system?
  - What is the difference between a formal system and a formal language?

- Computation graph?

  - What should we name this sequence?

    - The sequence: $x, f(x), f(f(x)), \ldots, f^n(x), \ldots$

      - $x$ is the initial state.
      - $f$ is the next-state function.

    - Trace? History? Path? Computation path?
    - [[https://en.wikipedia.org/wiki/Iterated_function][WP:Iterated function]]
    - [[https://en.wikipedia.org/wiki/Iteration][WP:Iteration]]

- Function $f$ is /computable/ by formal system $S$ iff $S$ has a finite description of $f$.
- Are there one-way functions?
- Mess: next-state relation

  - The /next-state relation/ $N$ is obtained from $T$
    by making a loop for each isolated vertex.
    For each $x$ in the domain of $T$, $N(x,y) = T(x,y)$.
    For each outside $x$, $N(x,x)$.
  - The computed relation of $T$ is $N^\infty = N^\infty \circ N$.
  - The problem computed by the graph is the infinite self-composition of the graph's next-state function.
    Such problem is the smallest $X$ that satisfies $N \circ X = X$.
    It is the least fixed point of $F$ where $F(X) = N \circ X$.
    The nth self-composition of $N$ is $N^n = E \circ N^{n-1}$.
  - An /infinite composition/ $N^\infty$ is a relation satisfying $N^\infty \circ N = N^\infty$.
    The empty relation satisfies this.
    The other one is nontrivial.

- Problem computed by a graph

  - A graph G /computes/ the problem
    $P(G) = \{ (x,y) ~|~ \text{\\(y\\) is the nearest terminal vertex reachable from \\(x\\)} \}$.
    Because the graph is loopless, there is no path from a vertex to itself, a vertex is not reachable from itself.

#+BEGIN_EXAMPLE
    terminal(x) = not exists y : E(x,y)
    reach(x,y) = E(x,y) vee exists m ( reach(x,m) wedge reach(m,y) )
    adist(x,y,1) = E(x,y)
    adist(x,y,n) = exists m exists k : dist(x,m,k) wedge dist(m,y,n-k)
    dist(x,y,n) = adist(x,y,n) wedge neg exists m < n : adist(x,y,m)
#+END_EXAMPLE

- Configuration graph as formal system?

  - Configuration /is/ well-formed formula.
  - $E(a,b)$ /is/ iff $a' \vdash b'$.
  - Initial state /is/ axiom.
  - $F \models P$

*** Related articles
    :PROPERTIES:
    :CUSTOM_ID: related-articles
    :END:

- related Wikipedia articles

  - [[https://en.wikipedia.org/wiki/Logic_of_graphs][WP:Logic of graphs]] (related to finite model theory)
  - [[https://en.wikipedia.org/wiki/Disjoint_union][WP:Disjoint union]]

- Introductory materials

  - Universal algebra (precursor to model theory)

    - [[http://mathcs.chapman.edu/~jipsen/talks/BLAST2009/JipsenUAtutorial1pp.pdf][Peter Jipsen's "tutorial on universal algebra"]]
      presumes you know some abstract algebra.
    - [[http://www.math.hawaii.edu/~ralph/Classes/619/UA-Valeriote.pdf][Matt Valeriote's "Lectures on universal algebra"]]
    - Not so introductory?

      - [[http://www.uni-log.org/joana.pdf][Joanna Grygiel's "universal algebra for logics"]] (is this introductory?)
      - [[http://www.math.hawaii.edu/~ralph/Classes/619/willard-ua.pdf][An overview of modern universal algebra]]
      - [[http://www.dsi.unive.it/~salibra/mainfinale.pdf][Applying Universal Algebra to Lambda Calculus]]

  - Model theory

    - [[http://www.math.toronto.edu/weiss/model_theory.pdf]["Fundamentals of model theory"]]

  - Finite model theory

    - [[https://dtai.cs.kuleuven.be/krr/files/seminars/IntroToFMT-janvdbussche.pdf][Jan Van den Bussche's "Introduction to finite model theory"]]
      seems approachable

  - Hodge theory

    - [[https://arxiv.org/abs/0807.4991][Vladimir G. Ivancevic and Tijana T. Ivancevic's "undergraduate lecture notes in de Rham--Hodge theory"]]

- People and activities

  - [[https://logic.rwth-aachen.de/~graedel/][Erich Grädel]]

    - "Finite model theory studies the relationship between logical definability and computational complexity on finite structures."
    - [[https://logic.rwth-aachen.de/Research/AlMoTh/][Algorithmic model theory]]
    - [[https://logic.rwth-aachen.de/pub/graedel/AbuzaidDawGraPak17.pdf]["Definability of summation problems for abelian groups and semigroups"]].
      "Our interest in the Abelian Semigroup Summation Problem
      is due to the observation that it illustrates, in a mathematically
      very pure way, the basic differences between logics and algorithms,
      or between definability and complexity, that underly
      some of the most fundamental and exciting problems of logic
      in computer science."
    - [[https://logic.rwth-aachen.de/pub/graedel/GrPaPa17.pdf]["The model-theoretic expressiveness of propositional proof systems"]]

  - Ronald Fagin
  - Neil Immerman
  - many others?

- http://www.math.ucla.edu/~chernikov/teaching/17W-MATH285D/FiniteModelTheoryNotes.pdf
- external resources

  - online text books?

    - http://theoryofcomputing.org/articles/main/index.html
    - http://oajse.com/subjects/computer_science.html

  - journals?

    - https://www.hindawi.com/journals/ase/contents/

- Predicate Computation and Search Problem

  - Isomorphism:

    - Language ~ predicate.
    - Predicate ~ set.

      - (A predicate is a unary relation.)

  - Insight?

    - Every predicate $p$
      gives rise to at least two problems:

      - $\Compute(p) = \text{given \\(x\\), compute \\(p(x)\\)}$, and
      - $\Search(p) = \text{find any \\(x\\) such that \\(p(x)\\) is true}$.

    - https://en.wikipedia.org/wiki/Search_problem

  - There are $p$ with slow $\Compute(p)$ but fast $\Search(p)$?
  - There are $p$ with fast $\Compute(p)$ but slow $\Search(p)$?
  - Conjecture:
    For every complexity class $C$,
    there exists $p$ such that $\Compute(p) \in C$.
  - Conjecture:
    For every predicate $p$,
    there exists complexity class $C$ such that $\Compute(p) \in C$.
  - Conjecture:
    For every complexity classes $C \subset D$,
    there exists $p$ such that $\Compute(p) \in D-C$.
  - Conjecture:
    For every complexity class $C$,
    there exists $p$ such that $\Compute(p) \in C$ and $\Search(p) \not\in C$.
  - Conjecture:
    For every predicate $p$,
    there exists complexity class $C$ such that $\Compute(p) \in C$ and $\Search(p) \not\in C$.
  - Problem formation conjecture:
    For every complexity class $C$,
    there exists $p,P,Q$ such that $P(p) \in C$ and $Q(p) \not\in C$.
  - Conjecture of arbitrary pessimization:
    For all complexity classes $F$ and $S$ where $F \subset S$,
    there exists $p$ such that $\Compute(p) \in S$ and $\Search(p) \in F$.
    The letters $F$ and $S$ are mnemonics for "fast" and "slow".

- Lemma: There exists fast $p$ having slow $S(p)$.
- Conjecture:
  For every complexity classes $C$,
  there exists $p \in C$ such that $S(p) \not\in C$.
- Conjecture:
  For every complexity classes $C$ and $D$,
  there exists $p \in C$ such that $S(p) \in D$.
- Formal languages and describable problems

  - Consider the formal language $L$
    with alphabet $\{ z,s \}$
    and formation rules

  1) $z \in L$ and
  2) $\alpha \in L \rightarrow s \alpha \in L$.
     It should be obvious that $L$ describes the set $\{ z, sz, ssz, \ldots \}$.
     This language solves the problem of adding a natural number by one.

- First-order logic

  - Example of terms in first-order logic:

    - $x$
    - $R(x,y)$
    - $R(x) \wedge S(y)$
