#+TITLE: On the word "conscious"
#+DATE: 2018-11-04 00:00:00 +0700
#+PERMALINK: /conscious.html
* To ken and to wit
I have to talk about this because I will define "conscious" in terms of "ken".

In the rest of this document, when I use "know", I usually mean "ken" only and not to mean "wit".

German has "kennen" and "wissen".
English has "ken" and "wit".

To ken something is to have experienced something.

To wit something is to remember or infer something.

- https://en.wiktionary.org/wiki/kennen#Usage_notes
- https://yourdailygerman.com/what-is-the-difference-wissen-and-kennen/

"I know that water is H2O" means "I /trust/ the book that says water is H2O".

"I know how beef tastes" means "I /have experienced/ the taste of beef, and I believe that all beef tastes that way".

"I don't know what 2 times 1234567 is" means "I know how to compute the result but I /don't bother/ to".

"I don't know whether the Riemann hypothesis is true" means I don't know.

"I know the Pythagorean theorem"

"I know a proof of the Pythagorean theorem"

"I know a person who can do that"

In all cases, knowledge implies /memory/.
* Consciousness is the ability to ken
/Consciousness/ is the ability to ken, that is, to experience, but not necessarily to wit.

On the etymology of the word "conscious",
Wiktionary[fn::<2019-10-27> https://en.wiktionary.org/wiki/conscious]
says that it comes from Latin "con-" (together) and "scire" (to know).

Something is /conscious/ iff it /can know/.

But that is trivial: If it knows, then it can know.
I think we take it for granted as an axiom in alethic modal logic:
If X is true, then X is possible.

Therefore, we are interested is whether something /can/ know, not whether something knows.

While I'm sleeping, I'm /unconscious/ (I have /low consciousness/), because I can only know very little while I'm sleeping.

I have /more consciousness/ when I'm awake than when I'm asleep,
because I /can know more/ when I'm awake than when I'm asleep.
But is that true?
What if I can know in my sleep, but I just don't remember it?

Why are we so sure that a rock doesn't know anything?
* On separating the double meaning of "consciousness"
Confusingly, we use the word "consciousness" for the subjective experience itself,
besides for the /ability/ to have such subjective experience.

We need two words for those two senses.
What are good words?

We use the word "quale" ("qualia") for subjective experience.

We use "consciousness" for the ability to have qualia.

"X can Y" is true iff there is something X can do to make "X does Y" true.

"X can Y by Z" is true iff X's doing Z makes "X does Y" true.

"X can Y" is true iff there exists Z such that "X can Y by Z" is true.

Example:
Power is the ability to unleash harm, but is not harm itself.
Indeed, when you unleash harm, your power is temporarily reduced,
because you have to recharge your power for unleashing the next harm.

That makes me think.

A conscious being can unleash quale, in the same way a powerful being can unleash harm.

A conscious being can experience, in the same way a powerful being can harm.

How do we increase power?
By weapons (harm multipliers), increasing our physical strength, and so on.

How do we increase consciousness?
What are the consciousness multipliers?
Meditation?
* Consciousness and epistemology
In Kantian parlance, perhaps consciousness is the ability to have synthetic a-posteriori knowledge.

Defining consciousness as "the ability to know" raises two questions:
What does it mean to /know/ something?
What does it mean to be /able/ to do something?
Those questions are the questions that epistemology aims to answer.
Thus defining consciousness requires epistemology.
* Hypothesis: Consciousness requires sense, memory, and feedback.
This hypothesis assumes materialism.
This will be false if it turns out that consciousness is fundamental in Nature.

- Imagine something.
- Imagine that you are imagining something.
- Imagine that the imagined you are in turn imagining something else.
  Is this even possible?
- To manipulate your consciousness,
  you must consciously intend to manipulate your consciousness.
  Can you consciously manipulate your consciousness?
- Consciousness needs sensory input.
- Consciousness needs feedback.
- Self concept needs feedback.
- If there is not a feedback, a system cannot distinguish itself from its environment.
  The self concept will never arise.
- If a brain can immediately control a thing,
  then that thing is part of the brain's self concept.
  If the brain can't, it's not.
- If a brain often gets certain input shortly after it produces certain output,
  it will associate the output with its self concept.
- The self is the thing under conscious control.
- It seems that:
  - Consciousness requires sense.
  - Consciousness requires memory.
  - Consciousness requires feedback.
- It seems that consciousness is (itself, or is caused by?)
  the feedback of information from the immediate past.
** Memory is necessary but not sufficient for consciousness.
- If I don't have memory, I can't bunch my past self and my present self into the same identity.
** Identity?
- Cutting off the legs of a person does not change the identity of that person.
  All of his memories are intact.
  Veterans who lost their legs in war retains their pre-war memories.
- Some brain damage changes the identity of the person.
** Prerequisites of consciousness?
- What is /necessary/ for consciousness?
  - Thought experiment: If someone is born without any senses, it cannot be conscious?
  - Thought experiment: Of an average adult, if all motor nerves are cut, and all sensor nerves are intact,
    then he is conscious intensionally but not extensionally?
    - If we cut all efferent nerve connections,
      the person will behave the same as the one in vegetative coma.
      If we remove the prefrontal cortex,
      the person will still show vital signs, but will be vegetative.
  - Infer: Consciousness has something to do with the brain. (What is it?)
    - Observe: A brain-damaged person does not exhibit conscious behavior.
    - Assume: Philosophical zombie does not exist.
    - Assume: Trapped consciousness does not exist.
    - [[https://www.quora.com/Can-consciousness-exist-without-sensory-inputs][Quora: Can consciousness exist without sensory inputs?]]
      - dissociative anesthesia? ketamine? sensory deprivation tank?
  - Assume: There is no experiment that can decide between these two things:
    the absence of consciousness, and the absence of efferent nerves?
  - Assume: My consciousness is tied to my body.
  - Assume: When I sleep, my consciousness pauses.
- What is /sufficient/ for consciousness?
- Unread
  - http://about.elsevier.com/media/Chaos/p2_Allegrini.pdf
  - https://www.researchgate.net/publication/283345070_Necessary_and_sufficient_conditions_for_consciousness_Extended_Dual-Aspect_Monism_framework
  - http://www.terapiacognitiva.eu/cpc/dwl/embodied/Prinz.pdf
  - [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3501646/][2012, "Neuronal function is necessary but not sufficient for consciousness: consciousness is necessary for will"]]
** How does consciousness arise? How are these different things of the same person related? Which requires which?
- His brain.
- His mind / thought / soul / spirit.
- His behavior. (His externally visible behavior.)
- His memory.
- His identity.

The questions:
- Which can exist without which?
- Which requires which?
  Which suffices which?
  Which is necessary but not sufficient for which?
  Which is sufficient for which?

https://www.quora.com/How-does-consciousness-arise-from-an-electrochemical-system-like-the-human-brain-What-is-the-expectation-that-artificial-intelligence-will-achieve-consciousness

https://www.iflscience.com/brain/long-term-memories-may-not-be-stored-synapses-afterall/

https://www.scientificamerican.com/article/consciousness-does-not-reside-here/

http://science.sciencemag.org/content/210/4475/1232

What we know: Altering the brain alters the behavior of the body that contains the brain.
Machine analog: Physically altering the machine without altering the software alters the output of the machine. Example: Firing electrons at a transistor.
* Brain? Biology? Materialism?
- [[https://www.youtube.com/watch?v=lyu7v7nWzfo][TED: Your brain hallucinates your conscious reality | Anil Seth]]
- [[https://www.youtube.com/watch?v=SgOTaXhbqPQ][TED: What hallucination reveals about our minds | Oliver Sacks]]
- same video, different narrator
  - [[https://www.youtube.com/watch?v=X_tYrnv_o6A][Veritasium: Your Amazing Molecular Machines]]
  - [[https://www.youtube.com/watch?v=WFCvkkDSfIU][Drew Berry: Animations of unseeable biology]]
* Knowledge
This chapter discusses knowledge, epistemology, and consciousness.
** Properties/behaviors of knowledge, propagation
We don't know what "knowledge" is.
But, for this section, assume that we know.

We think we can share or transfer some knowledge.

We can /transfer/ some knowledge by /simulation/.
Simulator-trained pilots /know/ how to fly planes:
If they can fly the planes in the simulator, they can fly the planes in reality.

We can /transfer/ some knowledge by /teaching/.
School teachers /transfer/ knowledge to their students.

Language enables some knowledge transfer.

We don't know how to transfer other knowledge.
The taste of salt.
The hue of green.

Perhaps someday technology will enable transferring all knowledge.
** Knowledge, software, copy, and move
We can /copy/ knowledge, but not /move/ knowledge.
This is similar to software: it can be copied but not moved.
By move I mean: when you move your car from place A to place B, the car is now at B, and is no longer at A.
But we don't /move/ software from hardware A to hardware B;
we /copy/ it from A to B, and then /delete/ the copy at A.
The same with knowledge:
We don't move it from person A to person B;
we /copy/ it; we spread it; and we don't know how to /delete/ knowledge from a person.

Books are not knowledge.
Books contain /text/, not knowledge.
Destroying a book is like destroying a computer disk that contains a program.
** <2018-11-05> Attention is the direction of consciousness?
** TODO What is knowledge?
*** Plato JTB theory: Knowledge is Justified True Belief.
Gettier problem / epistemic luck?
Can we believe something right for the wrong reason?

Justifying justifications?
*** How do we know? Ways of obtaining and justifying knowledge
- Through our senses.
- By logic?
- By divine revelation?
- Telepathy?
- Mind upload?

*** TODO What does it mean to know something?
Example sentences:
- "I know the taste of salt."
- "I know you did it."
- "We know that the decimal expansion of pi begins with 3.141659..."
  - We know that pi is an irrational number.
  - We know that the decimal expansion of an irrational number doesn't end.
  - We know that we will never know all digits of pi.
  - But we know how to compute each digit of pi.
- "I know John."
- "John knows a lot about philosophy."
- "I know where you hide the money."
- "I know how to boil eggs."
- "I don't know how eggs boil."
- "I didn't know you were there."
- "I didn't know you could do that." (Now I know.)
- "I used to know his phone number." (I no longer know.)

Reading queue:
- https://philosophy.stackexchange.com/questions/33348/what-does-it-mean-to-know-something
- https://www.quora.com/What-does-it-mean-to-know-something
**** Language issues
***** If we place a blind between a camera and a person, does the camera become unaware of the person?
*** TODO Knowledge justification dilemma
Knowledge without justification is "dumb luck": https://english.stackexchange.com/questions/384314/is-there-a-word-for-an-unjustified-true-belief

Thus, a true belief isn't always a knowledge.

Knowledge with justification suffers the Gettier problem.

- https://en.wikipedia.org/wiki/Gettier_problem#Knowledge_as_justified_true_belief_(JTB)
- https://en.wikipedia.org/wiki/Epistemology#Defining_knowledge
*** TODO What is the difference between knowledge and belief?
**** Knowledge is a /subset/ of belief?
Every knowledge is a belief.
There are beliefs that are not knowledge.

My knowledge of the taste of salt is a belief.

Language is not necessary for belief.
For example, I can falsely believe that I have a shirt with this color that I can see in my mind but I can't describe to you.
**** Wrong: /Knowledge/ is /belief/ that agrees with /reality/.
"We know S" means "we believe S, and S is true".

When we say "S is true", we mean that S is true in objective reality.
**** Belief is not binary
"If an acquaintance suddenly contacts you after a long time of silence, he is trying to sell you insurance."

"If the cloud looks gray, it's going to rain."
**** Distinguishing the absence of belief and the belief of absence
There is a difference between "S does not believe P" and "S believes that P is false".
**** Beliefs that go against reality
False negative: S is true but I believe that S is false.

False positive: S is false but I believe that S is true.
**** Unread
- https://en.wikipedia.org/wiki/Doxastic_logic
- https://en.wikipedia.org/wiki/Modal_logic#Doxastic_logic
**** Beliefs about conditionals and probabilities
Example belief: Car crashes kill drivers.
*** TODO We can imagine some things we have never experienced.
*** TODO Can we imagine a color we have never seen?
*** TODO What do we /believe/ about our /imagination/?
*** Knowledge argument, Mary's room: Argument against physicalism
- https://en.wikipedia.org/wiki/Knowledge_argument
- https://plato.stanford.edu/entries/qualia-knowledge/#3.1
