#+TITLE: Jakarta Consciousness Research Group
#+DATE: 2019-11-24 00:00:00 +0700
* Overview
Jakarta Consciousness Research Group (JCRG) is a /group/ of people,
a community, forum, perhimpunan, paguyuban, perkumpulan, persatuan, union, organisasi, kelompok, institution, institute, association?

We are located in /Jakarta/.

The research topic is /consciousness/, psychic, paranormal, supernormal, science.
* Desires
- Find researchers, physicists, psychologists.
- Find psychic subjects, people with psychic abilities.
- Formulate an introspective psychological theory that explains and predicts psychic abilities.
  - Formulate psychological experiments.
- Formulate a physical theory that explains and predicts psychic abilities.
  - Formulate physical experiments.
- Formulate a procedure for everyone to efficiently and reliably develop psychic abilities.
- Reach enlightenment? Prevent reincarnation?
  But how the hell are we going to reach enlightenment if we don't even know what it is?
  Perhaps we do not want to reach enlightenment, but we want to undo endarkenment?
  - Determine whether Siddharta Gautama was right; test his instructions.
  - Determine whether Patanjali was right; test Raja Yoga (Patanjali Yoga Sutra) for several years.
  - Formulate a procedure for attaining enlightenment in the most efficient manner.
- Find sponsors, rich people interested in this topic (after finding out what to do, and having a plan/program/mission).
- Unidirectional: precognition, remote viewing, clear-perception (clairvoyance etc.), matter affecting mind
- Bidirectional: healing, telekinesis, mind affecting matter, telepathy
- Buddhist/Hindu/Indian epistemology: How do we know whether we have achieved samyama?
- Analyze some books
* Other resources
Please keep your expectations low.

Lists:
- https://www.meetup.com/topics/consciousness/id/
- https://www.meetup.com/topics/yoga/id/jakarta/
- https://www.meetup.com/topics/spiritual-healing/id/jakarta/

Trying:
- https://www.meetup.com/Yayasan-Penelitian-Sains-Spiritual-Jakarta-Meetup/
- https://www.meetup.com/Jakarta-NonDuality-Meetup/
- https://www.meetup.com/Jakarta-Meditation-Group/

Unvetted sources:
- https://www.facebook.com/indigo.indonesia/
- Komunitas Indigo https://www.komunitasindigo.com/
- Kaskus
