#+TITLE: On the word "conscious"
#+DATE: 2018-11-04 00:00:00 +0700
#+PERMALINK: /conscious.html
* Consciousness is the ability to ken
/Consciousness/ is the ability to ken, that is, to experience, but not necessarily to wit.
Compare German /kennen/ and /wissen/.

In the rest of this document, when I use "know", I usually mean "ken" only and not to mean "wit".

On the etymology of the word "conscious",
Wiktionary[fn::<2019-10-27> https://en.wiktionary.org/wiki/conscious]
says that it comes from Latin "con-" (together) and "scire" (to know).

Something is /conscious/ iff it /can know/.

But that is trivial: If it knows, then it can know.
I think we take it for granted as an axiom in alethic modal logic:
If X is true, then X is possible.

Therefore, we are interested is whether something /can/ know, not whether something knows.

While I'm sleeping, I'm /unconscious/ (I have /low consciousness/), because I can only know very little while I'm sleeping.

I have /more consciousness/ when I'm awake than when I'm asleep,
because I /can know more/ when I'm awake than when I'm asleep.
But is that true?
What if I can know in my sleep, but I just don't remember it?

Why are we so sure that a rock doesn't know anything?
* On separating the double meaning of "consciousness"
Confusingly, we use the word "consciousness" for the subjective experience itself,
besides for the /ability/ to have such subjective experience.

We need two words for those two senses.
What are good words?

We use the word "quale" ("qualia") for subjective experience.

We use "consciousness" for the ability to have qualia.

"X can Y" is true iff there is something X can do to make "X does Y" true.

"X can Y by Z" is true iff X's doing Z makes "X does Y" true.

"X can Y" is true iff there exists Z such that "X can Y by Z" is true.

Example:
Power is the ability to unleash harm, but is not harm itself.
Indeed, when you unleash harm, your power is temporarily reduced,
because you have to recharge your power for unleashing the next harm.

That makes me think.

A conscious being can unleash quale, in the same way a powerful being can unleash harm.

A conscious being can experience, in the same way a powerful being can harm.

How do we increase power?
By weapons (harm multipliers), increasing our physical strength, and so on.

How do we increase consciousness?
What are the consciousness multipliers?
Meditation?
* Consciousness and epistemology
In Kantian parlance, perhaps consciousness is the ability to have synthetic a-posteriori knowledge.

Defining consciousness as "the ability to know" raises two questions:
What does it mean to /know/ something?
What does it mean to be /able/ to do something?
Those questions are the questions that epistemology aims to answer.
Thus defining consciousness requires epistemology.
* How do we measure consciousness (ability to know)?
How do we measure whether X has more consciousness than Y?
* Hypothesis: Consciousness requires sense, memory, and feedback.
This hypothesis assumes materialism.
This will be false if it turns out that consciousness is fundamental in Nature.

- Imagine something.
- Imagine that you are imagining something.
- Imagine that the imagined you are in turn imagining something else.
  Is this even possible?
- To manipulate your consciousness,
  you must consciously intend to manipulate your consciousness.
  Can you consciously manipulate your consciousness?
- Consciousness needs sensory input.
- Consciousness needs feedback.
- Self concept needs feedback.
- If there is not a feedback, a system cannot distinguish itself from its environment.
  The self concept will never arise.
- If a brain can immediately control a thing,
  then that thing is part of the brain's self concept.
  If the brain can't, it's not.
- If a brain often gets certain input shortly after it produces certain output,
  it will associate the output with its self concept.
- The self is the thing under conscious control.
- It seems that:
  - Consciousness requires sense.
  - Consciousness requires memory.
  - Consciousness requires feedback.
- It seems that consciousness is (itself, or is caused by?)
  the feedback of information from the immediate past.
** Memory is necessary but not sufficient for consciousness.
- If I don't have memory, I can't bunch my past self and my present self into the same identity.
** Identity?
- Cutting off the legs of a person does not change the identity of that person.
  All of his memories are intact.
  Veterans who lost their legs in war retains their pre-war memories.
- Some brain damage changes the identity of the person.
** Prerequisites of consciousness?
- What is /necessary/ for consciousness?
  - Thought experiment: If someone is born without any senses, it cannot be conscious?
  - Thought experiment: Of an average adult, if all motor nerves are cut, and all sensor nerves are intact,
    then he is conscious intensionally but not extensionally?
    - If we cut all efferent nerve connections,
      the person will behave the same as the one in vegetative coma.
      If we remove the prefrontal cortex,
      the person will still show vital signs, but will be vegetative.
  - Infer: Consciousness has something to do with the brain. (What is it?)
    - Observe: A brain-damaged person does not exhibit conscious behavior.
    - Assume: Philosophical zombie does not exist.
    - Assume: Trapped consciousness does not exist.
    - [[https://www.quora.com/Can-consciousness-exist-without-sensory-inputs][Quora: Can consciousness exist without sensory inputs?]]
      - dissociative anesthesia? ketamine? sensory deprivation tank?
  - Assume: There is no experiment that can decide between these two things:
    the absence of consciousness, and the absence of efferent nerves?
  - Assume: My consciousness is tied to my body.
  - Assume: When I sleep, my consciousness pauses.
- What is /sufficient/ for consciousness?
- Unread
  - http://about.elsevier.com/media/Chaos/p2_Allegrini.pdf
  - https://www.researchgate.net/publication/283345070_Necessary_and_sufficient_conditions_for_consciousness_Extended_Dual-Aspect_Monism_framework
  - http://www.terapiacognitiva.eu/cpc/dwl/embodied/Prinz.pdf
  - [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3501646/][2012, "Neuronal function is necessary but not sufficient for consciousness: consciousness is necessary for will"]]
** How does consciousness arise? How are these different things of the same person related? Which requires which?
- His brain.
- His mind / thought / soul / spirit.
- His behavior. (His externally visible behavior.)
- His memory.
- His identity.

The questions:
- Which can exist without which?
- Which requires which?
  Which suffices which?
  Which is necessary but not sufficient for which?
  Which is sufficient for which?

https://www.quora.com/How-does-consciousness-arise-from-an-electrochemical-system-like-the-human-brain-What-is-the-expectation-that-artificial-intelligence-will-achieve-consciousness

https://www.iflscience.com/brain/long-term-memories-may-not-be-stored-synapses-afterall/

https://www.scientificamerican.com/article/consciousness-does-not-reside-here/

http://science.sciencemag.org/content/210/4475/1232

What we know: Altering the brain alters the behavior of the body that contains the brain.
Machine analog: Physically altering the machine without altering the software alters the output of the machine. Example: Firing electrons at a transistor.
* What do others say about consciousness?
TODO summarize:
- Vsauce video "What is consciousness?"[fn::https://www.youtube.com/watch?v=qjfaoe847qQ]
- 2009, "How to define consciousness—and how not to define consciousness", [[http://cogprints.org/6453/1/How_to_define_consciousness.pdf][pdf]]

* Brain? Biology? Materialism?
- Does everyone have a fusiform gyrus? A prefrontal cortex?
- [[https://www.youtube.com/watch?v=lyu7v7nWzfo][TED: Your brain hallucinates your conscious reality | Anil Seth]]
- [[https://www.youtube.com/watch?v=SgOTaXhbqPQ][TED: What hallucination reveals about our minds | Oliver Sacks]]
- same video, different narrator
  - [[https://www.youtube.com/watch?v=X_tYrnv_o6A][Veritasium: Your Amazing Molecular Machines]]
  - [[https://www.youtube.com/watch?v=WFCvkkDSfIU][Drew Berry: Animations of unseeable biology]]
