#+TITLE: Topics in consciousness research
#+DATE: 2019-11-28 00:00:00 +0700
* My current research focus
<2019-11-27>

(On Desda Zuckerman's 2012 book "Your Sacred Anatomy: An Owner's Guide To The Human Energy Structure".)
Is "spiritual anatomy"[fn::<2019-11-27> Spiritual Anatomy with Desda Zuckerman https://www.youtube.com/watch?v=e4xuBYfI0n4] a theory of psychic functioning?
It looks scientific: she did some tests, standardizations, and replications.
It started from her observations.
How good is its explanatory/predictive power?
The book is dauntingly thick; perhaps we should watch some videos instead?

Grout 2013 experiments.
 [fn::<2019-11-27> https://www.jodichapman.com/2015/03/04/a-spiritual-science-experiment/]

I feel that SSRF[fn::<2019-11-27> https://www.spiritualresearchfoundation.org/] is a bit off.
Despite its name, I don't see any science in its website; no theories, no explanations, no experiments, only instructions and claims.
Some people even think that SSRF is brainwashing.[fn::<2019-11-27> https://www.quora.com/Is-Spiritual-Science-Research-Foundation-SSRF-brainwashing-people-with-their-so-called-spiritual-research]

Farsight Institute sometimes makes some big claims
 [fn::<2019-11-27> https://farsight.org/FarsightPress/Moses_Beyond_Exodus_Farsight_Project_main_page.html]
 [fn::<2019-11-27> http://farsightpresentations.com/RV_Projects/CrucifixionRuse.html].
I don't know the truth, but those claims are a bit too kooky for my taste.

Horgan 2017[fn::<2019-11-27> https://blogs.scientificamerican.com/cross-check/what-does-it-feel-like-to-be-enlightened/]:
#+BEGIN_EXAMPLE
And if you really experience nothing, how can you remember the experience? How do you emerge from this state of oblivion back into ordinary consciousness?
#+END_EXAMPLE

Possibly enlightenment?[fn::<2019-11-28> Enlightened Beings Share Their Awakening, Mystical Experiences https://www.youtube.com/watch?v=f54jAzYawZk]
Note that the subjects themselves do not label the experience as "enlightenment",
but apparently all of them at least experience temporary ego death.

Sometimes I imagine something so fun that I lost sense of time (1--2 hours had passed, whereas I think it was only 15--30 minutes).
Is that ego death?
But I don't feel extreme bliss.

Enlightenment?[fn::<2019-11-28> How Do You Recognize An Enlightened Being? - Sadhguru https://www.youtube.com/watch?v=VQrhl7KJ0m4]

People "who are congenitally blind for organic reasons and have never been able to see anything in their entire lives
can perceive the environment when their non-local consciousness detaches from their bodies during various life-threatening situations."
 [fn::<2019-11-27> https://www.consciouslifestylemag.com/non-local-consciousness-and-the-brain/]
If blind people can do that, then myopia should be a trivial obstacle.
Seeing without eyes is not crazy if you already know remote viewing.
Also see Katharina Friedrich's "seeing without eyes"
 [fn::<2019-11-27> https://seeingwithouteyes.com.au/dr-katharina-friedrich/]
 [fn::<2019-11-27> https://seeingwithouteyes.com.au/]
("Sehen ohne Augen").
Are there English videos?
What are her experiments and theories?

Remote viewing is similar to automatic writing/drawing in that both of them use the subconscious.
How do we distinguish these cases?
1. The viewer's consciousness goes to the target.
2. The viewer and the target communicate by telepathy.
3. The viewer reads some Akashic records about the target.
4. The viewer is let know by a spirit/disembodied consciousness.

What is the evidence for auras?
What does Kirlian photography actually capture?
Biofield evidence?[fn::<2019-11-27> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4654779/]

What is the evidence for chakras?

/Why does all psychic development book boil down to deep meditation and visualization/?
If they work, how do they work?

Are "super psychic kids"[fn::<2019-11-27> Super Psychic Kids With Abilities That You Wont Believe Until You See https://www.youtube.com/watch?v=E3MQ3-CAV4Y] real?

I am reading David DeBold's "Miracle mastery" book?

What are Paramahansa Yogananda's "scientific techniques for attaining direct personal experience of God"[fn::<2019-11-08> https://en.wikipedia.org/wiki/Paramahansa_Yogananda]?

Is the goal of null-domain meditation (empty-mind meditation) ego death?

Does an enlightened man know that he is enlightened?
To be enlightened is to know reality directly without the material senses?

If an enlightened person cannot be disturbed[fn::<2019-11-27> Sri Avinash's opinion https://www.youtube.com/watch?v=KxUPSRgLIGE],
then what is the difference between enlightenment and apathy?

Some of the quickly visible effects of meditation are reduced stress and increased ability to maintain focus.

Is meditation about focus, about relaxation, or about quieting the mind?

Read Quora psychics-related topic, and perhaps Reddit, but Quora is more structured (question-answer).

Is Patanjali[fn::<2019-11-27> http://www.rainbowbody.net/HeartMind/Yogasut_plain.htm] right? Did he know what he was talking about?

Does myopia hamper aura-seeing?
Do we use eyes to see aura?
If not, then myopia should not hamper aura-seeing.

(On telekinesis and the conservation of energy.)
Where does the energy come from? Does the practitioner become tired? Is energy conserved?

A plan of the table of contents:
- [[file:conscious-basic.html][Basic concepts in consciousness research]].
  Definition of common terms such as consciousness, mind, cognition, etc.
- Mind-brain relationship: Gage, Sperry, Libet, corpus callostomy, "thalamic bridge", etc.
- Evolution of the brain.
  What questions about the brain can evolution answer?
  Why do brain parts specialize into functional areas?
  Speculations on the non-uniformity of the brain.
  Encephalization quotient?
  Why have humans built more variety of tools than elephants have?
- Dissociative identity disorder.
  Kastrup's hypothesis of individual consciousness as dissociation of cosmic consciousness.
  Is there an identity dissociation that is not a disorder?
- Disembodied consciousness, mediumship, life after death, out-of-body experiences, near-death experiences, shared death experiences, anomalous cognition.
- Remote viewing, energy works, psychic abilities/functioning, paranormal phenomena, poltergeist vs haunting.
  - [[file:remote-viewing.html][On remote viewing]]
- What can cybernetics tell us about the brain? Good regulator theorem?
  - Anapoiesis reconstructs knowledge "from long-term memory to working memory"?
    <2019-11-05> https://arxiv.org/ftp/arxiv/papers/1402/1402.5332.pdf
- Psi research around the world: USA, USSR, China, etc.? [[file:question.html]]
- Memory. Hypothesis: Temporal ordering enhances recall. Perception of time. [[file:question.html]]
- [[file:physics-21.html][A crash course on 21st century physics, with emphasis on modeling]].
  Quantum mechanics.
  Relativity.
- Borderline crackpot territory.
  - Quantum-physical hypotheses of the workings of the brain, consciousness, whatever.
  - Religion as technology for communicating with God.
    Jesus as a democratization of the access to God (from select shamans then to everyone now)?

- I have some [[file:question.html][unanswered questions]].
- Minds and brains [[file:mind-brain.html][interact]],
  but we [[file:mind.html][don't really know how]].
- [[file:energy.html][Energy]] is the ability to do work. Power is the rate of energy transfer.
  (If you wish to detour to politics, see [[file:power.html][On political power]].)
- There is enough paranormal [[file:paranormal-evidence.html][evidence]].
  We need a [[file:anomaly-theory.html][theory]].
- Everyone should [[file:psychic.html][develop]] psychic abilities?
  - [[file:book.html][Summary of some books]] (deprecated)
- [[file:anomaly.html][On anomalies]]
- Philosophy should use [[file:philo.html][simple language]].
- [[file:religion.html][Religion]] is a technology for communicating with God?
- Deprecated pages
  - Avoid [[file:anomaly-hindrance.html][hindrances]] to anomaly research.

What?

Precognition indicates consciousness?
Animals precognize.
Human consciousness can interfere in consciousness experiments.
 [fn::<2019-09-28> Machine Consciousness: Experimental Evidence | Garret Moddel https://www.youtube.com/watch?v=4H5GDQ7u_iE]

Perhaps we prayed because it will rain; perhaps the future affects the past.

I declare <2019-11-25> as my day one of consciousness experiments.
By then I had been meditating lightly for a few days.
* <2019-11-27> Idea: Measuring the depth of meditation
The depth of meditation can be subjectively measured by the /rate of internal distraction/ (number of internal distractions per unit time).
For example, a newbie meditator may be distracted 20 times per minute,
and an expert meditator may be distracted 1 time per 15 minutes.
One internal distraction is one time realizing that one has been distracted.
External distraction does not always translate to internal distraction.
For example, when someone talks to me while I am reading an article, I may fail to respond to the other person.

The depth of meditation can be objectively measured by frequency analysis of brain waves?
* <2019-11-27> Calling all scientists and engineers with personal psychic experiences
Who are engineers/scientists who have personal psychic experiences?
 [fn::<2019-11-27> https://noetic.org/blog/engineers-scientists-report-psychic-experiences/]
Some of them are
Russell Targ (he has witnessed some psychic phenomena;
his website[fn::<2019-09-17> http://www.espresearch.com/] has some links[fn::<2019-09-17> http://www.espresearch.com/links.shtml])
and Alan Hugenot (where did he learn mediumship?).

Among those engineers/scientists, who have theories and experiments?

Gathering the engineers/scientists may speed up the next scientific revolution.

The theory does not have to be stated in terms of mainstream physics.
The theory simply has to explain/predict some psychic aspects of reality,
and we can marry the theory and mainstream physics later.

Consciousness research is long overdue, but I think it is at least speeding up.
* <2019-11-27> On funding psychic research, and on working around the brokenness of how we do science
While we wait for the old guards to die,
we can ask the crowd to fund our psychic/paranormal research.
It would be even better if we could force those old guards to retire early
as they have become the very thing they sought to destroy in their youth.
It seems that the way we do science in the 21st century
corrupts open-minded youths into close-minded old guards.
There is something wrong with the system.
"Publish or perish" make people game citations.
Proposals take too much effort to write and, even worse,
the grants are awarded to "safe-bet" researches that have slim chance of discovering anything important.

Our way of doing science is systematically broken:
old guards have too much power,
grants are not allocated to enough varieties,
people are too attached to theories,
and the majority is too risk-averse.
For faster progress, science should be anarchistic.

"Shut up and calculate" leads to a dead end.
Theoretical physicists should also identify and relax the simplifying assumptions, not just tinker with mathematics.
Theoretical physics is not a branch of mathematics.
Theoretical physics is a combination of philosophy and mathematics.
* <2019-11-27> Some physics questions
If matter is congealed energy, and a wave is a disturbance that moves energy without moving matter, then what?

Let not-you be everything else in the Universe except you.

Moving yourself with velocity v is the same as moving not-you by -v.
That is, our ability to move ourselves is the same ability to move the entire Universe.
Your gaining kinetic energy mv2 is equivalent to not-you gaining kinetic energy Mv2 where m is your mass and M is the mass of not-you.

But why, accelerating you by a is not the same as accelerating not-you by -a?
That is, we can tell who is accelerating by finding out who feels a force.

We cannot tell who is moving, but we can tell who is accelerating.
Why is that?

That is, I know a way to move all stars in the sky, but I know no way to move only some stars without moving everything else.

Acceleration is the rate of change of velocity.

Accelerometer measures force, not acceleration.

Or should we redefine acceleration as whatever measured by an accelerometer?
* <2019-11-27> Comparing classical mechanics and quantum mechanics
In Newton-style mechanics, an n-body system is modeled as (x1,ldots,xn) where xk R to R3.
The interpretation is "At time t, body 1 is at x1(t) and ... and body n is at xn(t)"

In Schrödinger-style mechanics, an n-body system is modeled as psi(x1,ldots,xn) where xk in R3.
The interpretation is "At time t, there is a probability density of sqr abs psi(x1,ldots,xn,t) that body 1 is at x1 and ... and body n is at xn"

https://en.wikipedia.org/wiki/Wave_function
* <2019-11-27> Is motion continuous?
A /movement/ is a change in position.

A /motion/ is a /continuous/ movement (a continuous change in position). But is it appropriate to model continuous movement with continuous functions (continuous in the sense of real analysis)? Is spacetime infinitely divisible?

Classical mechanics makes the ontological commitment that spacetime is infinitely divisible.

A simplifying assumption may be an ontological commitment.

Quantum mechanics has more ontological parsimony than classical mechanics.
* <2019-11-27> On unifying quantum mechanics and relativity, and linguistic issues
Perhaps the key to unifying quantum mechanics and relativity is to determine a more correct concept of spacetime.

The key issue is language: the same word "time" is used to mean different things in those theories.

Quantum mechanics still assumes Newtonian absolute spacetime.
Relativity assumes locality but experiments show that reality is non-local.
Perhaps we must relax both of those assumptions.
We need a theory that explains both quantum entanglement and spacetime curvature.

We know that something is in the past because we remember it or because we believe someone else who remembers it.
But our memory of the past is not what the past actually is.

The way we use a word implies our mental model of its meaning.

How we use a word implies what we think of it.

The usage of a word implies its meaning (how we interpret the word, how we ascribe meaning to the word).

The meaning of a word is determined by the circumstances in which it is used, not by the word itself.
* <2019-11-27> On the epistemology and ontology of spacetime
What does our usage of English imply about how we think of spacetime?

We say:
- Time passes, time flies
- The first time, the second time
- One time, two times
- What time is it

There are several meanings.

Space is the separation between matter, and time is the separation between events?

Which one is right:
- Matter occupies space (space contains matter)
- Space separates matter
- Neither of them

Space is the ability to contain, and time is the ability to endure?

What does it mean to bend spacetime?
How do we know?

It seems that our minds expect the entropy of the system it observes to always increase.

A gas expands to fill its container. The arrow of time is the direction of time in which the gas seems to expand. The arrow of time is the direction in which entropy increases.

We seem to perceive time to be moving in one direction.
Why is that?

We know the speed of the passage of time by looking at the rate of change of things around us.

We define space by the size of an object?
The amount of space occupied by an object

But what is time itself?
* <2019-11-27> On refusing reincarnation
bhagavad gita
https://asitis.com/15

Krishna meditation, 6:13-14, dhyana yoga
https://vedabase.io/en/library/bg/6/

The light at the end of the tunnel is the birth canal?
What theory is this?
https://www.quora.com/What-if-you-dont-want-to-be-reincarnated

Is life a gift, a trap, a prison, a test, or what?
Is it what you make of it?

https://www.reddit.com/r/spirituality/top/?t=all
* <2019-11-27> On alternative societies
Gather the people tired of the rat race.

There is no point in working beyond what is necessary for sustenance.

* <2019-08-14> Electromagnetic wave
In Maxwell's theory, an electric charge instantaneously affects all of space,
and an electromagnetic wave is not something emitted by an electric charge.
* <2019-11-28> Is psychology science?
There are psychological experiments and theories that try to explain those experiments, but do those theories predict anything?

Is psychology falsifiable?

There are some interesting experiments and applications.
Asch conformity experiment,
Stanford prison experiment.
Using stories to change minds.
Hostage negotiation techniques.
Pavlovian conditioning, Skinnerian conditioning.
Rat heaven experiment.
Monkey mother experiment.
/But what is the underlying science?/
Biology, genetics, hormones, epigenetics, neuroscience, and so on.

Psychology can be thought of as applied biology.

Everyone capable of some empathy has an intuitive understanding of basic psychology.
* On living on Earth
** On living sanely, peacefully, and sustainably
- [[file:groom.html][Grooming]]
- [[file:subsist.html][On living sanely]]
** A clean eating protocol
Combine /nutrition science/ and /psychology/.

For two weeks.

Pay attention to gut microbiome.

No sugar; no condiments bought from supermarket because they all have sugar.
No flour.
No carb.
No food that is processed more than one step from its original form.
No refined foods.
No extracts.
Sugar is not OK because it is concentrated sugarcane plant extract.
Cooked meat is very OK, but sausage is not.
White rice is not OK.
Green vegetables OK.

Anytime you're hungry, just eat; there is no time restriction;
the only restriction is that you eat real fat/protein.

Everytime you eat, you must send a photograph of what you eat to me.
It is not for approval, but for commentary, and for /psychology/, for accountability,
so that you feel that you are doing it for me, so that you don't prematurely abandon your effort.

You can drink anything as long it has no sugar in it.
Just drink plain water.
Drinks from the supermarket are not OK; they all have sugar.
** <2019-08-20> ? On skin-wrapping for skin-tightening, occlusion cuff training, and blood flow restriction training
Do they work? How do they work? What is the science?
** Why do I wear long hair?
- To repel close-minded people.
- To know when I have lost in life, when I can no longer do things as I wish,
  be it due to biological, political, or economical reasons.
** The importance of monuments and folklores, especially at disaster sites
To pass on the knowledge to future generations, so that we do not forget, so that we do not waste lives.
 [fn::https://99percentinvisible.org/article/tsunami-stones-ancient-japanese-markers-warn-builders-high-water/]

Monuments, folklores, and histories are trans-generational memory.
It is what enables the human race to advance: Because humans can build on their predecessors' work
and do not repeat everything that their predecessors did.
** <2019-10-28> Urban planning should include nutrient cycle.
** A rather dystopian prophecy
In the future, society will split into three groups:

1. The masters: The people who program the system (tell the system what to do).
   Governments, computer programmers, wealthy people.
2. The slaves: The people who are programmed by the system (are told to do what to do by the system).
   Citizens, online taxi drivers, workers.
3. The outcasts: The people who refuse to participate in the system.

The system consists of people, computers, other machines, and weapons.

** <2019-07-06> Friendship is fluid and circumstantial
At 10 years old, we are friends because we are in the same class, and we don't have better things to do.
Simple physical proximity.
But we stop being friends as soon as we graduate out of school.

At 20 years old, we are friends because we are in the same company.
We stop being friends as soon as we resign.

At 30 years, we are friends because we share a goal or hobby or problem, because we care about a common thing.
We stop being friends as soon as our problem is solved.

** <2019-07-06> Two approaches to living: here-first and there-first
There are two approaches to living:
- There-first: Start with what you want, and find what you should have:
  Find what things have to exist in order to satisfy the goal.
- Here-first: Start with what you have, and find what you should want:
  Find what can be done with what already exists.

* Nature
- [[file:nature.html][A physics book draft]] (should be split into articles instead)
- [[file:chemistry-ontology.html][On the evolution of the ontology of chemistry]]
- [[file:save.html][On my plan to save myself and perhaps some people]]

Are black holes the key to unifying general relativity and quantum field theory?

"Realistic Simulation: Inside a Black Hole - New Universe through White Hole?"[fn::https://www.youtube.com/watch?v=iUr8Obv_DeA]
** <2019-08-17> On myopia
I hypothesize that myopia has lower prevalency in the population of drivers because drivers refocus their eyes a lot.

black-on-white promotes myopia, white-on-black inhibits myopia?
https://www.nature.com/articles/s41598-018-28904-x

https://biology.stackexchange.com/questions/24589/how-does-the-eye-know-whether-to-focus-further-out-or-nearer-in-order-to-bring-a

https://photo.stackexchange.com/questions/105433/can-you-tell-from-a-blurry-photo-if-focus-was-too-close-or-too-far

Hypothesis:
The brain uses the chromatic aberration of the eye lens in order to detect whether the focus is too near or too far.
Green fringing means that the focus is too ???
Purple fringing means that the focus is too ???
https://photographylife.com/what-is-chromatic-aberration
https://en.m.wikipedia.org/wiki/Circle_of_confusion
** Appeal-to-evolution weakens the theory that irregular eating causes gastritis
<2019-08-17>

The /appeal-to-evolution/ is this argument:
/If a trait would hamper the survival of a species, then that species would not have evolved that trait./

It is a heuristic.
It is not always correct.
For example, it cannot explain peacock tails.
However, it seems reasonable in absence of other information.

The appeal-to-evolution weakens the theory that irregular eating causes gastritis as follows.

Perhaps the very early hunter-gatherer humans ate irregularly;
they were always a few days away from starvation,
they did not have a secure food supply,
they depend very much on their surroundings.
/Having gastritis due to irregular eating would hamper their survival./
Therefore they probably evolved such that irregular eating does not cause gastritis.
** Others' articles about gastritis
"Coadaptation of /Helicobacter pylori/ and humans: ancient history, modern implications"[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2735910/]

"The Iceman had a tummy bug"[fn::https://www.sciencemag.org/news/2016/01/iceman-had-tummy-bug]

1998 "Helicobacter pylori in vivo causes structural changes in the adherent gastric mucus layer but barrier thickness is not compromised"[fn::https://gut.bmj.com/content/43/4/470]
** On atherosclerosis
Atherosclerosis or arteriosclerosis?
https://amp.theguardian.com/science/2019/jun/11/mystery-arteries-harden-cracked-scientists-calcium-deposits
** On gut microbiome?
https://www.prebiotin.com/prebiotin-academy/what-are-prebiotics/dietary-fiber/

https://medium.com/boosted/intermittent-fasting-your-thyroid-and-your-immune-system-ec8f5f02d997
https://www.sciencedirect.com/science/article/pii/S0924224414002386
https://mennohenselmans.com/protein-is-not-more-satiating-than-carbs-and-fats/
https://www.ncbi.nlm.nih.gov/pubmed/8695595/
https://www.shape.com/latest-news-trends/go-veggie-gain-weight-heres-why-it-can-happen
https://www.livestrong.com/article/1011649-6-reasons-people-gain-weight-after-going-vegetarian/
https://www.healthline.com/health/food-nutrition/becoming-vegetarian-tips
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4564526/
https://selfhacked.com/blog/how-your-gut-microbiota-can-make-you-fat-or-thin/
https://www.ncbi.nlm.nih.gov/pubmed/30336163
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6036887/
** On the science of diets
Conservation of mass.

Body mass is gained by food and drinks, and lost by exhalation and excretion.

The question is the /composition/ of those mass.

If I weigh 70 kg and both my legs weigh 20 kg, then a squat consumes at least 50 kg * 10 m/s2 * 0.5 m = 200 J = 0.0478 kcal.
That's a tiny amount relative to the calories in the food we eat!
We can easily eat 300 kcal in one meal.
Thus, if the human body were 100% efficient, I would have to squat /6,276 times/ to burn that one meal!

Thus the biggest energy consumer is the basal metabolic processes.

The proximal cause is the combination of nutrition and hormones.
Hormones are affected by nutrition, activity, and genetics.
** On the discreteness of length and the isotropy of space
If length is discrete, than space cannot be both isotropic and Euclidean, because not all angles are possible.
But what if space is discrete and everything is a field/wave?
Space would look isotropic?

What about this?

"Is Space-Time Discrete or Continuous? An Empirical Question", Peter Forrest, Synthese, Vol. 103, No. 3 (Jun., 1995), pp. 327-354.

* <2018-10-03> Brain-to-brain interface?
https://www.sciencealert.com/brain-to-brain-mind-connection-lets-three-people-share-thoughts
* Using analytic philosophy to clarify and navigate social relationships
** Friendship
*** What is a friend?
Your friends are those who sacrifice for you.
The greater the sacrifice,
the greater the friendship.
How do we measure a sacrifice?
*** How do we measure friendship?
In theory, we define $F(A,B)$ (the /friendship measure from A to B/)
as how much sacrifice that A is willing to make for B.

(Is the direction correct? Is that backwards?)

Thus measuring friendship boils down to valuating sacrifices.

$F(A,B)$ can be approximated by an equivalent amount of money.

How do we measure friendship in practice?

Foot-in-the-door:
let A ask B to make bigger and bigger sacrifices until B refuses.
Then we have found $F(A,B)$.

Door-in-the-face:
let A ask B to make a sacrifice so big that B refuses,
and then let A ask B to make smaller and smaller sacrifices until B accepts.
Then we have found $F(A,B)$.

Those results may differ, but $F(A,B)$ should lie somewhere between those two points.
We can also average them, take the maximum, take the minimum,
use interval arithmetics,
or describe the result using a statistical distribution, for example.
*** Properties of friendship
Friendship is circumstantial:
$F(A,B)$ changes over time.

Friendship is usually asymmetric:
$F(A,B) \neq F(B,A)$.
*** Questions
What is self-friendship?
What is $F(A,A)$?
How much is one willing to sacrifice for oneself?
Does this question even make sense?
*** Links
- [[http://www.abc.net.au/news/2015-10-29/friendship-theory-developed-by-sydneysider-goes-viral/6897402#theory][Mobinah Ahmad's 6-level relationship categorization]]
- [[https://kenanddot.wordpress.com/2007/03/21/the-asymmetry-of-friendship/]["Ken writes: Isn't it strange that although friendships are obviously asymmetrical this isn't unambiguously reflected in language?"]]
** Defining "boss"
- What is a boss?

  1. X is a /boss/ of Y iff X can affect Y's salary, even if X does it indirectly.
  2. X is a /strong boss/ of Y iff X has the authority to change Y's salary.
  3. X is a /weak boss/ of Y iff X is a boss, but not a strong boss, of Y.

- Example:

  - Everyone who can fire you is your strong boss.
  - Everyone who can get you fired (complain to someone who can fire you) is your weak boss.

- The stronger a boss is, the more seriously you should treat him/her.
- Don't bite the hand that feeds you.
*** Another definition, based on fear: X is a boss of Y if Y fears X.
** Happiness
Happiness = Reality - Expectation.

To be more happy, raise reality, lower expectation, or do both.

Pain also reduces happiness.

Money cannot buy happiness,
but it can buys things that will make you happier.

Money helps, but after you have enough to make your life comfortable,
adding money doesn't add happiness.
* What?
** Why are we so angry?
- https://www.nhs.uk/conditions/stress-anxiety-depression/about-anger/
  - "being treated unfairly and feeling powerless to do anything about it"
    - Is it really unfairness that bothers me, or do I have the wrong sense of fairness?
      Does fairness even exist?
- https://psychcentral.com/blog/angry-all-the-time-for-no-reason-this-might-be-why/
  - 'Anger also “stems from wanting to control what is outside of us,” said Michelle Farris, LMFT, a psychotherapist in San Jose, Calif.'
** What psychology?
- [[https://en.wikipedia.org/wiki/Psychology_of_collecting][WP:Psychology of collecting]]

  - [[https://en.wikipedia.org/wiki/Compulsive_hoarding][WP:Compulsive hoarding]]
  - [[https://en.wikipedia.org/wiki/Digital_hoarding][WP:Digital hoarding]]

- Undigested

  - [[http://www.apa.org/monitor/nov02/gomad.aspx][2002, Jennifer Daw, Why and how normal people go mad]]
  - advertising, propaganda

    - [[https://www.youtube.com/watch?v=nj_UWbifM2U][How One Man Manipulated All of America]], 12 minutes, too long, about [[https://en.wikipedia.org/wiki/Edward_Bernays][WP: Edward Bernays]]

  - Persuasion, changing minds

    - [[https://viaconflict.wordpress.com/2014/10/26/the-behavioral-change-stairway-model/][The Behavioral Change Stairway Model]],
      can be used for hostage negotiation, suicide prevention, terrorist deradicalization
    - changingminds.org

      - http://changingminds.org/techniques/general/overall/overall.htm
      - http://changingminds.org/techniques/general/cialdini/cialdini.htm
      - http://changingminds.org/techniques/general/kellerman/kellerman.htm
      - http://changingminds.org/techniques/general/being_right/being_right.htm
      - http://changingminds.org/techniques/general/ingratiation/ingratiation.htm
      - http://changingminds.org/techniques/how_to/trust_me/trust_me.htm

    - The key to persuasion is *think as the target*.
      Think what he/she wants and hates.

      - Application to politics:

        - [[https://qz.com/525132/the-smartest-most-effective-way-to-win-any-political-argument/][Frame your persuasion in the target's morality]].
        - [[https://www.nytimes.com/2015/11/15/opinion/sunday/the-key-to-political-persuasion.html][Same]].

  - A /market/ is where things are bought and sold.
  - To /market/ something is to try to sell that thing.
  - Marketing is about inducing people to buy something?
  - Sometimes being agreeable is more important than being correct.

    - Other people's feelings are more important than the truth?

  - https://qz.com/881289/a-new-study-linking-profanity-to-honesty-shows-people-who-curse-are-more-authentic/

- How the Nazis might have made the German people accept Nazism

  - https://en.wikipedia.org/wiki/The_Wave_%282008_film%29
  - https://en.wikipedia.org/wiki/The_Third_Wave_(experiment)

- Why do people kill?

  - Anger? Envy? Hatred?

- Why do people rape?

  - Is it about beauty?

    - No?

      - There are ugly people who get raped.
      - There are beautiful people who don't get raped.

  - Is it about getting satisfaction from unconsenting victim?
  - Is rape a power trip?
  - Is there any relationship between grandiosity and rape?

- Why do people commit crimes?

  - Do they know the penalties?

    - If yes, why do they still commit crimes?

- [[https://www.beeminder.com/home][beeminder.com: use loss aversion to trick yourself to accomplishing goals]]
- [[https://www.youtube.com/watch?v=WEvqMN75sCI][Does your job match your personality? | Jordan Peterson]]

  - axis: complexity

    - high complexity requires high cognitive function level

  - axis: creative/entrepreneurial vs managerial/administrative

    - big five personality trait

      - C/E requires "openness to experience"
      - M/A requires conscientiousness

- [[https://www.youtube.com/watch?v=-moW9jvvMr4][A simple way to break a bad habit | Judson Brewer]]: by being curiously aware
- [[https://www.youtube.com/watch?v=xp0O2vi8DX4][How to motivate yourself to change your behavior | Tali Sharot | TEDxCambridge]]
- https://www.washingtonpost.com/news/storyline/wp/2014/12/04/people-around-you-control-your-mind-the-latest-evidence/?utm_term=.40265b80e149

  - https://news.ycombinator.com/item?id=12698204

- [[https://www.youtube.com/watch?v=kyioZODhKbE][Facts Don't Win Fights: Here's How to Cut Through Confirmation Bias - Tali Sharot - YouTube]]

  - To polarize someone is to make him more confident (about a belief).
  - Confirmation bias: People hear what they want to hear.

    - People filter incoming information.
    - People bend incoming information to conform with their preexisting beliefs.
    - Agreements polarize people, but disagreements don't depolarize people.
    - Information agreeing with preexisting belief polarize the believer.
    - Information disagreeing with preexisting belief is filtered out and doesn't depolarize the believer.

  - Key insight: We can change people's behavior without changing their beliefs.

- [[https://www.youtube.com/watch?v=WAL7Pz1i1jU][How to Persuade Others with the Right Questions: Jedi Mind Tricks from Daniel H. Pink]]

  - how to get your daughter to clean her room

    - the comment section is pessimistic

- 2018-08-29 What I learned today.

  - To temporarily defuse your enemy's hatred of you, find another enemy that is common to both of you.

    - These happens in quick succession:
      Coworker A offended me.
      Then coworker B came and offended A in front of me.
      Then I offend coworker B in front of A.
      Then I can feel some agreement with coworker A.

  - The perception of having a common enemy unites people, even if the enemy is fake.

- [[https://www.youtube.com/watch?v=nknYtlOvaQ0][Why obvious lies make great propaganda - YouTube]]

  - [[https://www.rand.org/pubs/perspectives/PE198.html][The Russian "Firehose of Falsehood" Propaganda Model: Why It Might Work and Options to Counter It | RAND]]

    - This has a concrete recommendations for countering the firehose of falsehood.

  - Trump and Putin use "firehose of falsehood" to assert power, in the same way school bullies do.
  - The only way to take power from them is to dismiss them.
    Media should stop giving them a platform.
    We should refuse to hear them.
    We should not fact-check, because by fact-checking we affirm that they have power.
    We should simply dismiss everything they say.
    Their competitors should counter-flood the media with their own firehoses.
  - I'm sure Trump and Putin are not the only people using that technique.
    I suspect that PKS may be using that technique in mosques in West Java.
  - Can [[https://en.wikipedia.org/wiki/Gaslighting][WP:Gaslighting]] be used to unplant false beliefs?
** Fear explains everything?
There are only two ways to make people do something:
- Make them want it.
- Make them fear the consequences of not doing it.

https://en.wikipedia.org/wiki/Fear_appeal
*** Explaining love/attachment as fear of loss...
*** Intrinsic motivation to do X is fear of the consequences of not doing X.
*** To want X is to fear not getting X.
*** We eat because we fear death. We eat because we fear regretting not tasting the delicious-looking food.
*** It is the terrorists/extremists who are afraid of us, in the same way a cornered rat biting us is afraid of us?
** <2019-11-28> Why does darkness inconvenience us?
Street lights went out.
I feel somewhat uneasy; I had to consciously calm myself, although there is nothing unusual.
Why does darkness inconvenience us?
