#+TITLE: Basic concepts in consciousness research
#+DATE: 2019-11-05 00:00:00 +0700
* Overview of basic concepts and their relationships
/Minds/ contain thoughts.

/Brains/ contain brain matter.

/Consciousness/ is the ability to ken.
For more explanation, see [[file:conscious.html]].

Is there any meaningful difference between subconscious and unconscious?

If
Consciousness = ability to know (introspectability?)
then
Subconsciousness = /reduced/ ability to know,
and
Unconsciousness = inability to know, lack of ability to know.

Cognition and recognition

cogito comes from from con- (from cum-, with) and agito (agere, to do) <2019-11-05> https://en.wiktionary.org/wiki/cogito#Latin

Cognizance, cogitate

Cogito = I think

X recognizes Y iff X cognizes that X cognizes Y.

For example, we see a photo of a distant acquaintance that we last met 40 years ago.
We immediately /cognize/ this person, in the sense that we immediately feel that we know this person (we have seen this person somewhere before);
but for a moment we strive to think who this person is and where we met this person: it takes us some time to /recognize/ this person.

"Spirit" means breath.[fn::<2019-10-29> https://www.etymonline.com/word/spirit]
"Spirit" may also mean idea, essence, intention, or meaning, such as in "spirit of the law",
as opposed to "letter of the law", which is the mere appearance.
* An analogy of consciousness: a person in a stream full of fish
My consciousness, my awareness,
my perception of what I think is the present, my existence,
is like trying to catch as many fish as possible in a rapid stream of water full of fish swimming along in the current.
There are so many fish that my conscious mind does not see.
When I silence my mind, it is as if I let the fish swim, not catch them, not interfere with their natural trajectories.

The fish in my hand is my conscious mind.

The fish I glimpse in my peripheral vision is my subconscious mind.

The fish swimming under the water is my unconscious mind.
* What do others say about consciousness?
TODO summarize:
- Vsauce video "What is consciousness?"[fn::https://www.youtube.com/watch?v=qjfaoe847qQ]
- 2009, "How to define consciousness—and how not to define consciousness", [[http://cogprints.org/6453/1/How_to_define_consciousness.pdf][pdf]]
* Understanding is reasonably accurate modeling
To /understand/ something is to have a reasonably accurate /model/ of it.

X /understands/ Y iff X has a reasonably accurate model of Y.
