#+TITLE: Understand basic economics
#+DATE: 2019-04-24 00:00 +0700
#+PERMALINK: /economics.html
#+OPTIONS: ^:nil toc:nil
Here we study economics shallowly,
only as far as necessary to start a small business and begin centralizing power.
* Understand money
** Money as seed and human as soil
We can think of money as seed and human as soil.
Some humans are fertile soils for money to grow.
A poor person who wins a lottery soon loses all of it.
A rich person who wins a lottery keeps getting richer.
A fool and his money are soon parted.
However, this way of thinking puts money first and human second.

We can think of how fast money flows through a person.
** Money as people's way of voting for what they want
Money is a way for people to vote for what they want.
People vote with their money.

Money is the consumer's vote for what producers should do.

Money is the people's vote for what companies should do.
** Money as fluid
** Money as blood
Economic actors are the organs, and money is the blood.
** Money is valuable due to higher-order belief
People believe that money is valuable because they believe
that others also believe that money is valuable.

The value of money depends on whether there are people nearby willing to accept it.

Money has no inherent value.
We attach value to money.

It's the same:
Words do not have inherent meaning,
We attach meaning to words.

It's all convention that enables us to exchange.
Language enables the exchange of ideas.
Money enables the exchange of goods.

Related: Keynesian beauty contest[[fn::https://en.wikipedia.org/wiki/Keynesian_beauty_contest]]
* Understand the causal chain of profit
The direct cause of profit is the ability to sell something at a price higher than its production cost.

Why is that?

Why is a working car more valuable than a broken car?

From neuroscientific point of view, people buy because of dopamine?

Patrick Anderson has an interesting idea:
"the origin of profit is the consumer's lack of ownership in the means of production"
 [fn::http://postgrowth.org/how-on-earth-flourishing-in-a-not-for-profit-economy-by-2050/].
* Understand value
"Create value"?

Value does not exist.
What exists is /want/.

To "create value" is to satisfy desire, to satisfy want.
* Understand wealth
/Wealth/ is the sum of satisfied wants.
* Understand ownership
To /own/ something is to have exclusive access to that thing.
* Price, pay, ownership, exchange, transaction
- /Exchange/ and /transaction/ are synonyms.
- An /exchange/ is an agreement
  - between two parties A and B where
    - A gives X to B,
    - B gives Y to A.
  - If X is money and Y is not money, then:
    - X is the price.
      - /Price/ is the amount agreed for exchange.
      - /Price/ is something sacrificed to get something else.

    - A is the buyer.
    - B is the seller.
    - The buyer /pays/ the price to the seller.
* negotiation, price-taker, price-maker
    - Negotiating parties often have asymmetrical bargaining power.
    - The price-taker is the weaker one.
    - The price-maker is the stronger one.
* money and currency
    - Money has /currency/ and /amount/ (/magnitude/).
    - Money can be /exchanged/ with many other things.
* debt, interest, and price
    - The price of debt is the /interest/
      (the amount of money that will be exchanged for obtaining the loan now).

      - An X market is a market where X is traded.

        - A money market is a market where money is traded.

          - How do you buy money with money?
* Assumptions
  - Every human:

    - Has wants.
    - Has priorities? Utility function?

      - Non-constructive? It exists, but we don't know what it is?

    - Acts to satisfy those wants.
* Counterexamples? Where the theory breaks down?
  - Thiefs want something more than freedom?
    - But both of the stolen thing and the freedom will be taken away?
  - Smokers and junk food eaters don't want health?
    - Everybody wants health?
      - But doesn't behave consistent with wants?
        - Cognitive dissonance?
          - Want health later or health now?
          - Addiction?
            - Physical changes to the brain?
* Fundamentals of economics?
  - Everybody wants something.
  - How do we satisfy more people using less resources?

* Land > Labor > Capital
  - The [[https://en.wikipedia.org/wiki/Factors_of_production][factors of production]]
    in classical economics are:
    - land (all other things that exist in nature),
    - labor (human),
    - capital (tools).

Land creates labor.

Labor creates capital.

If capital is destroyed, labor can rebuild it.

If labor is destroyed, capital cannot rebuild it.

Labor without capital is inefficient.

Capital without labor is /nothing/.

However, without land, nothing would exist at all.

Therefore, land is more important than labor, and labor is more important than capital,

But it seems here that capital is revered, labor is disdained, and land is forgotten.

Money is not capital, but it can be used to buy capital, but this quote is related:
#+BEGIN_QUOTE
When the last tree is cut, the last fish is caught, and the last river is polluted;
when to breathe the air is sickening, you will realize, too late,
that wealth is not in bank accounts and that you can't eat money.

Alanis Obomsawin (b. 1932)[fn::http://quoteinvestigator.com/2011/10/20/last-tree-cut/]
#+END_QUOTE
* Tax
It suffices beginner businesspeople to know that tax is a large-scale protection racket:
If we don't pay the racketeers, they will ruin us.
* Finance
- Economics vs finance
  - Economics is about value?
  - Finance is about money?

"Finance is a field that deals with the study of investments."
 [fn::https://en.wiktionary.org/wiki/finance]
 [fn::https://en.wikipedia.org/wiki/Finance]

- Loan-related jargon

  - A lender lends (gives) a loan to a borrower.
  - A borrower borrows (takes) a loan from a lender.
  - Loan is the amount.
  - Borrower (one who borrows) is the debtor (one who has debt).
  - Lender (one who lends) is the creditor (one who gives credit).
  - Lease vs rent?

    - Lease is more formal and long-term than rent.

      - [[http://www.businessdictionary.com/article/1063/lease-vs-rent-d1412/][businessdictionary.com]]
      - [[https://www.nolo.com/legal-encyclopedia/leases-rental-agreements-faq.html][nolo.com]]

- Currency-related jargon

  - The /price/ is the amount paid by the buyer to the seller.
  - What is currency?
  - What is money?
  - What is the difference between currency and money?

    - https://www.weusecoins.com/hidden-secrets-of-money-currency-versus-money/

      - "Currency is a medium of exchange, a unit of account."
      - "Money is [currency] plus a store of value over a long period of time."

  - What is legal tender?
  - What is cryptocurrency?
  - Is there such thing as "cryptomoney"?

- Securities

  - A [[https://en.wikipedia.org/wiki/Security_(finance)][security]] is a /claim/ to something.
  - An /exchange/ was a place (is a computer system) where things are traded (bought and sold).

    - The exchange requires /brokers/ because it was invented before computers.

      - Impractical: 1 million people on the trading floor shouting for a match.

        - But a computer can match 1 million trades in a second.

      - Nobody bothers making a new stock exchange.

        - Because of [[https://en.wikipedia.org/wiki/Network_effect#Financial_exchanges][network effect]].
        - But [[https://robinhood.com/][Robinhood]] is doing that,

          - but it's a broker, not a stock exchange,

            - but I hope they make buying stock as easy as ordering pizza online,

              - because if everyone uses the same broker,
                then the broker /is/ the exchange.

          - [[https://support.robinhood.com/hc/en-us/articles/202853769-How-Robinhood-Makes-Money][How Robinhood makes money]]

            - No trading fee.
            - $6 per month per person who uses Robinhood Gold; otherwise none.
            - In 2017, Robinhood had 2 million users ([[https://techcrunch.com/2017/04/26/robincorn/][techcrunch.com]]).

              - How many of them use Robinhood Gold?

                - How many people have margin account compared to regular account?

                  - I guess 1:100.

              - How many employees do Robinhood have?

                - 30 ([[https://www.owler.com/company/robinhood][owler.com]])

              - Does that make sense?

                - My estimate:

                  - Their revenue:

                    - $60,000 per month = $720,000 per year.

                  - Their expenses:

                    - $300,000 per year for employees.
                    - ? for stock exchange chairs.
                    - ? for building leases.

                - Yes, it makes sense.
                - Are customers "mercy-buying" because they think Robinhood is too cheap (compared to old-school brokerages)?

                  - [[https://www.stockbrokers.com/guides/features-fees][stockbrokers.com: 21 Most Common Online Broker Features & Fees]]
                  - Comparison: In Indonesia, stock trading cost is about 0.02% of trade value.

    - A stock exchange starts out trading stocks,
      but after some time it begins trading other securities,
      but the name has stuck.

  - A /bond/ is a securitized loan?
  - Every asset can be securitized?
  - Stock

    - /Stock/ is company ownership.
    - A /share/ is a fraction of stock.
    - Buying share means buying partial company ownership.

- Undigested information

  - [[http://noahpinionblog.blogspot.co.id/2013/01/how-much-value-does-finance-industry.html][Noahpinion: How much value does the finance industry create?]]
  - Investing, speculating, or gambling?

    - Slap some "math" on gambling masquerading as "investing", and suddenly it looks legit.
    - "Modern investing: gambling in disguise", David Schneider

* Defining investing, trading, gambling, betting, wagering, insurance
** Defining gambling
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/
** How do we know something is not gambling?
*** If it's possible to be skillful, then it's not gambling.
** What
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?" https://www.bbc.com/news/business-38905963
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
* Use the economic/financial system to centralize power?
What are we trying to do?
- Understand how to make the system works for us instead of making us work for the system.

Sam Altman puts it concisely: "You get rich by owning things."[fn::http://blog.samaltman.com/how-to-be-successful]

Why do we get rich by owning things?

Because we can ask the police to violate whomever violates our ownership
(unless the perpetrator is the government itself).

Respecting private property enables the accumulation of wealth and the ensuing economic inequality.

Inequality is not poverty.[fn::https://fee.org/articles/stop-conflating-inequality-with-poverty/]

Poverty, not inequality, is the problem.

We have several choices to reduce inequality:
- Embrace capitalism:
  Make everyone own properties and educate everyone to spend money wisely.
- Oppose capitalism:
  Steal from the rich, give to the poor, although this incentivizes poverty.
  Abolish private ownership.
  But isn't this envy-based politics?

But why should we reduce inequality?
It is poverty that we should reduce, not inequality.

Of course some poverty is due to bad luck,
and we should help people who fall into poverty due to bad luck.
But too many entitlement programs are trapping people in poverty.

It is up to us whether we want to find ways to own properties.
** What is a company?
A company is a /legal fiction/ for concentrating wealth (economic power) to its shareholders.
Such economic power often translates to other forms of power such as political power.

A company is rife with /principal-agent problems/ and /conflicts of interest/.
There is one principal-agent problem between the shareholders and the directors.
There is another principal-agent problem between the directors and the employees.
There is one principal-agent problem for each layer of management.

It is a physically impossible to build or hurt a company.
A company cannot do anything.
People do things.

A company is an abstract object with concrete consequences.
The legal fiction is unreal.
The environmental effects are real.
** What is "economy"?
What is "economy"?
What is "economy" in "economic meltdown"?

Exchange?
Trade?

Satisfy maximum wants using minimum resources.
There are two solutions:
- Reduce wants.
- Use more resources.

Economics is easy to explain but hard to predict.
Economics is too interconnected.

Demand/consumption is easy; supply/production is hard.

/Demand is easy./
We can want anything.
Changing our minds is free.

/Supply is hard./
We have to work to satisfy our demands.

Consumption is easy.
Production is hard.
Destruction is easy.
Creation is hard.
Second law of thermodynamics: The entropy of the Universe never decreases.
In nature, entropy never decreases.
Disorder arises naturally.
The second law of thermodynamics explains why consumption is easier than production.

The nature of economics is that demand is free, but supply is costly..
Changing demand is cheap: you just change your mind.
Changing supply is costly: all the infrastructure that has been built won't simply turn back into cash.

Demand first or supply first?
Human nature is the root cause of economic demands.
There will always be demand for food and shelter.
There is always demand to make life easier and less boring.

However, in the case of iPhone, we have two views:
- Steve Jobs's presentation causes people to want iPhones. Supply creates demand.
- People always want an easier way to live. Steve Jobs's iPhone just happens to make people's lives easier.

For example:
We want an easier way to live.
People don't want iPhones for iPhones's sake.
People want iPhones because people believe iPhones make people's lives easier.

If demand surges, it will collapse later.
Example: tulip mania.
** Economic recession
Economic recession is the reduction of money flow velocity.

How do we predict recession?
How do we measure and monitor money flow velocity?
- people savings balance
- mass layoffs
- mass price hikes for vital goods (oil?)
- company profit/loss statements
- money accumulates at few economic actors

Technology introduction, demand shift among substitute goods:

A demand shift is a demand collapse and a demand surge.

Cheaper robotic workers (or increasing minimum wages) causes demand for human workers to collapse and demand for robotic workers to surge.

Demand shifts among substitute goods.
** Fluid dynamics explains economic recessions
Economic recession happens because money flow slows down.

Money is a fluid.
A fluid flows.
Fluid flow velocity depends on pressure at the source and resistances in the path.

If we want to maintain flow velocity despite increasing resistance, we have to increase pressure at the source of the fluid flow.
But do we want this?

Money flow slows down because people spend less.

People spend less because they have less discretionary income.

People have less discretionary income because they are fired, or governments raise taxes, or important things get more expensive, etc.

Assumption:
A person's behavior changes slowly, if it changes at all.
A person who has never cared about the environment will not suddenly care about the environment.

A recession has two possible direct causes: /demand collapse/ or /supply collapse/.

Examples of supply collapse:
- Mine collapse, oil rig explosion, etc.
- Disasters: fire, earthquake, tsunami, flood, volcanic eruption, etc..
- Lots of people going out of workforce at once (into pension, dying in war, etc.).
- Lots of people suddenly becoming conscious (Google workers demonstrating for transparency, etc.).

Examples of demand collapse:
- Bitcoin ran out of fools (greater fool theory).
- Renewable energy sources reduce oil demand.
- Young people adopt a minimalist lifestyle after realizing that consumerism is unsustainable.
- Government increases minimum wage big enough to make switching to robots looks cheap.
  Lots of companies introduce robot workers at the same time, making human workers redundant.

Supply collapse is caused by physical destruction.
Demand collapse is self-inflicted human condition.

Consumers supply demands to producers.
Consumers demand supplies from producers.
Take and give.
To demand is to take, to consume, to destroy.
To supply is to give, to produce, to create.

What does inverted yield curve has to do with recession?
What does time preference have to do with economic recession?
What is an economic recession?

CAGR = compound annualized growth rate.

What is the yield of a bond?
A bond's yield is the CAGR of the bond price.

What is the yield curve?
The yield curve is the curve in a plot with two axes: the horizontal axis is tenor (duration to maturity), and the vertical axis is yield.

An inverted yield curve indicates that buyers are pessimistic about the bond's future?
** Currency? Free banking? Digital fiat currencies?
Piggyback nascent fintech/e-cash/e-money startups?
BTPN Jenius?

https://openbazaar.org/blog/trust-is-risk-a-decentralized-trust-system/
Currency requires trust.
Debt requires trust.
Transaction requires trust.
Business requires trust.
What is trust?

A trustworthy person refrains from exploiting vulnerabilities.
Trust is the assumption that the other party refrains from exploitation.
Trust is the assumption of the absence of betrayal.
Betrayal is the exploitation of trust.
(Problem: Circular definition.)
** Economic crisis is discontent due to reduction of purchasing power.
A /crisis/ is a mass discontent.

An /economic crisis/ is a mass discontent due to mass reduction of purchasing power.

"A financial crisis is any of a broad variety of situations in which some financial assets suddenly lose a large part of their nominal value."
 [fn::https://en.wikipedia.org/wiki/Financial_crisis]

- High firing rate, high unemployment, unemployed people having genuine difficulty finding jobs, employers not willing to employ
- Greatly reduced demand (discretionary spending)
- Reduced purchasing power
** Economics of open-source
https://en.wikipedia.org/wiki/Open-source_economics

Where do we draw the line between open core and crippleware?
- https://en.wikipedia.org/wiki/Open-core_model
- https://en.wikipedia.org/wiki/Crippleware

Is "open core" just an euphemism of "crippleware"?

If the open core is actually useful, then it isn't crippleware.
http://blogs.collab.net/subversion/enough-of-this-open-core-confusion

Marginal cost is the change in opportunity cost due to increasing production quantity by one.
https://en.wikipedia.org/wiki/Marginal_cost
** Understand how capitalism centralizes power
Capitalism is:[fn::https://en.wikipedia.org/wiki/Capitalism]
1. the /private ownership/ of means of production,
2. the operation of such means /for profit/.

What?
- http://www.visualcapitalist.com/
- Capital is everything that is not labor?
- Capitalism is capital above labor? Communism is labor above capital?
- Example of low-capital high-labor:
  - small and medium enterprises (SMEs)
    - food stalls
    - home bakeries
    - art freelancing
  - research in pure mathematics
** Companies must extract value to survive
- A profitable company must extract more value
  from its employees than it pays its employees.
  - People create value. People in a company create value. Human labor creates value.
    Companies aren't human. Companies can't work. It's the employees who work.
  - But if the employees weren't in the company, they might create less value.
    The company might be a place where the employees can create more value for society.
** "Investing"
What Bitcoin "investing" is:
- You buy a certificate of environmental destruction from someone, probably a "miner".
- You expect a greater fool to buy that certificate from you at a higher price.
  There are millions of other people who are looking for someone else more stupid than them.

Bitcoin is massive wealth transfer from late buyers to early buyers.
All financial investing is massive "realistic-return" Ponzi scheme.
Exactly fits the definition.
Newcomers pay oldtimers.
Late buyers pay early buyers.

Bitcoin is not necessary at all. It is pure want.
Inflation target disincentivizes currency hoarding.
A deflating currency encourages currency hoarding and discourages real spending.
https://www.cmegroup.com/education/featured-reports/an-in-depth-look-at-the-economics-of-bitcoin.html

https://www.theguardian.com/technology/2018/nov/05/energy-cost-of-mining-bitcoin-more-than-twice-that-of-copper-or-gold
** Economics, price, quality
Price is not important in itself.
It is the quality-price trade-off that is important.
People don't buy shit even if it's cheap, even if you pay them to buy it.

For an increment of quality, people are willing to pay an increment of price.
But there is a "good enough" point where people are satisfied and they just look at the lowest price.

Negative price means willingness to pay to get rid of something.
Example: rotten vegetables has negative price to most people, but positive price to farmers.
** Economics?
We should measure debt-to-income ratio instead of debt-to-GDP ratio?

Consumptive debt sacrifices future for the present.

Productive debt is good.

Example of productive debt:

Suppose that you want to buy a land to farm on it. These are the scenarios:
- You work for 20 years. Then you buy the land with cash. But the land price has risen.
- You take a loan, buy the land now, and repay the loan over 10 years. In the second year, your land starts producing.

If a person takes too much consumptive debt, he goes bankrupt.

If a government takes too much consumptive debt nominated in its own currency, it can print money to repay the debt, but such printing devalues the currency.

If the US continues to take loans mindlessly, it will have to choose:
- Default (refuse to repay).
- Suffer severe inflation (rising prices), if the creditors spend the printed money.

Does the USA think it can get away by refusing to repay its debts? It will trigger a huge power shift, maybe to China. Will China sacrifice itself to clean up America's mess? Will China buy up all US debts, and use the default as a reason to start a war?

https://deviantinvestor.com/9778/sacrificing-future-spending/

https://en.wikipedia.org/wiki/Unearned_income

Everything comes from nature.
We are not creating or destroying anything.
We are merely transforming things.
At least as seen from physics.

The number of atoms in Earth doesn't change.
(But what about solar wind? It does change a bit?)

Urban toilet harms humans and the Earth.
- We should poo squatting, not sitting.
- Urine and feces should be composted, not flushed down the drain.
- Compost bins should replace septic tanks.

https://www.vice.com/amp/en_us/article/zm95ka/republicans-are-outraged-about-the-deficit-they-caused

https://en.wikipedia.org/wiki/Unrestricted_Warfare
** There are only two ways to get rich: earn or steal
There are only two ways to get rich: /earn/ wealth or /steal/ wealth.

Earn wealth: convince people to give you money, by selling them things that improve their lives.
Use the money to develop your wealth even more.

Or steal wealth: An investor steals a little wealth from each person who does not invest.

After you obtain enough wealth, develop it, but don't lose all of them.
