#+TITLE: On economics
#+DATE: 2019-04-24 00:00 +0700
#+PERMALINK: /economics.html
#+OPTIONS: ^:nil toc:nil
* What is this?
This is economics with some politics, history, and philosophy.
* The natural moral system assumed in this document
** Good = promoting survival
I pick natural morality for this document,
because it is the moral system that I think most people agree with.

"Something is /good/" means that it promotes the survival of the human race as a whole in the long term.
"As a whole" means that it is the survival of the species, not of particular individuals.
I do not mean to put humans above other beings;
it is just that we need a working definition of "good" in order to advance the discourse,
and natural morality is what I think most people agree with.
Nevertheless, it is in the human race's own best interests to avoid mindlessly killing other animals.

What we think is good is not always actually good, because we are bad at predicting the future unintended consequences.
For example, eradicating a parasite may trigger a cascade of events that collapses the food chain.

Moral systems often suffer from quandaries, and so does natural morality.
For example:
Suppose that mankind is facing an existential crisis,
and there is only one person who can save mankind, but doing so requires keeping him alive.
Then natural morality prescribes that he should be kept alive at all costs,
even if it means killing one billion people.
** Deserving (desert)
X /deserves/ Y = X /should/ get Y = It is /good/ that X get Y.

Thus desert is simply a special case of morality,
and it depends on the moral system we subscribe to.
Picking a moral system enables us to answer questions like "Does X deserve Y?"
** Do rich people deserve to be rich?
What does that question really mean, besides some implied envy?

Each necessary cause deserves a part of the consequence that it contributes to.
The question is thus:
How much should be attributed to which causal factor?

Does anyone deserve to be rich?
Does anyone deserve to be poor?
What is to deserve?

Does anyone deserve inheritance?

Do wealthy people deserve their wealth?
What does "deserve" mean?
The only way to be a millionaire is by exploiting people?

If you create a product bought by 1 million people, you deserve to be a millionaire.
Problem: you did not create it; your employees did.

Is there anything that everyone deserves, such as basic courtesy?
If so, what is the cause?

One deserves to be treated the way he treats others?
** Fairness, justice?
What is fairness?

To divide something fairly is to divide it such that no recipient is disadvantaged.

Feeling disadvantaged vs actually disadvantaged?

What is justice?
** The next interesting questions after we define "good"
Is capitalism good?
Is communism good?
Is it good to have states?
** Economics should maximize goodness, not wealth
Economics should maximize goodness (survival of the human race),
not maximize wealth (the sum of satisfied human wants).
* Definitions of economic concepts, and the consequences
** What is economics?
Economics is the "art of managing a household", the "science of wealth".[fn::https://www.etymonline.com/search?q=economics]

Is economics science?
Is economics falsifiable?
What is the object of study in economics?

https://en.wikiversity.org/wiki/10_Principles_of_Economics

/Economy/ is the stewardship of households.[fn::https://www.etymonline.com/word/economy]

/Economics/ studies how we should satisfy our wants.

We live in /economic systems/[fn::https://en.wikipedia.org/wiki/Economic_system].

These concepts are fundamental:
utility, want, value, wealth, moneyfulness/pecuniosity.

A thing is /useful/ iff it satisfies a /want/.

A thing's /value/ is its ability to satisfy wants.

useful = valuable

/Wealth/ is the sum of satisfied wants.

A farmer is /wealthy/, because he satisfies most of his wants;
but he is /impecunious/ (moneyless).
The opposite, a person too busy working for a consulting firm, is /pecunious/ (moneyful) but /unwealthy/,
because, despite having a lot of money, he is hardly satisfied;
he has enough money to eat delicious foods every day,
but he does not have the time.

/Do not conflate price and value./

/Price/ is the amount of money paid for value.

To /own/ something is to be able to defend the exclusive access to that thing.
What is owned is defined by the owner's ability to defend his possessions.
If the owner is incapable of violence, directly or indirectly, then he is incapable of ownership.

Price, pay, ownership, exchange, transaction:
- /Exchange/ and /transaction/ are synonyms.
- An /exchange/ is an agreement
  between two parties A and B in which
  - A gives X to B,
  - B gives Y to A.
  - If X is money and Y is not money, then:
    - X is the price.
      - /Price/ is the amount agreed for exchange.
      - /Price/ is something sacrificed to get something else.
    - A is the buyer.
    - B is the seller.
    - The buyer /pays/ the price to the seller.
** money and currency
- Money has /currency/ and /amount/ (/magnitude/).
- Money can be /exchanged/ with many other things.
** debt, interest, and price
- The price of debt is the /interest/
  (the amount of money that will be exchanged for obtaining the loan now).
  - An X market is a market where X is traded.
    - A money market is a market where money is traded.
      - How do you buy money with money?
** The factors of production: Land > Labor > Capital
The factors of production, from the most important: land, labor, capital.
WIthout land, labor (human) would not exist, let alone capital.

The factors of production, from the most protected by law: capital, labor, land.

When human laws go against the laws of Nature, life becomes shit.

The /factors of production/[fn::https://en.wikipedia.org/wiki/Factors_of_production]
in classical economics are:
- land (everything that exists in the Universe, except labor and capital),
- labor (human),
- capital (tools).

Land creates labor.

Labor creates capital.

If capital is destroyed, labor can rebuild it.

If labor is destroyed, capital cannot rebuild it.

Labor without capital is inefficient.

Capital without labor is /nothing/.

However, without land, nothing would exist at all.
Therefore, land is more important than labor, and labor is more important than capital,
But it seems here that capital is revered, labor is disdained, and land is forgotten.
** Wealth
Wealth is the sum of satisfied wants.

One's satisfaction is the ratio of his satisfied wants to all his wants.

It is not always good to satisfy human wants.
For example, it does not promote survival,
to satisfy the wants of a human who wants to kill all humans.
** Wealth and money should not be confused
#+BEGIN_QUOTE
When the last tree is cut, the last fish is caught, and the last river is polluted;
when to breathe the air is sickening, you will realize, too late,
that wealth is not in bank accounts and that you can't eat money.

Alanis Obomsawin (b. 1932)[fn::http://quoteinvestigator.com/2011/10/20/last-tree-cut/]
#+END_QUOTE

All wealth comes from Nature.
Humans come from Nature.
Human labor comes from Nature.
The food we eat in order for us to be able to labor comes from Nature.
Everything comes from Nature.
** Value
** Labor
** Money
** Capital
From Latin "caput" (head)

referring to the heads of cattle

cattle as tools / means of production?

(source?)

Why is cattle categorized as "capital" but human categorized as "labor"?
Aren't both animals working?
** Money vs capital
Money is not capital, but it may be used to buy capital.
** Ownership
Exclusive access.

Defended by power.

Power is the ability to harm.
** value vs price vs cost
** Industry
industry = diligence https://www.etymonline.com/word/industry
** Assumptions on human behavior
How do we know?
We only need to look into ourselves:
What if there are 7 billion people like us?

Humans constantly try to minimize their energy expenditure (the work they directly do with their bodies).

If humans are not paid,
then they will do what they most want to do.
*** Human wants
What do humans want?

The /root want/ of humans,
hardwired into them by evolution,
is to /survive and have fun/.
From that root want come all other wants,
such as to survive longer, in more environments, with less effort;
to eat;
to move;
to belong to a community;
to have a place to rest;
to have companions and offsprings;
to understand nature;
and so on.

A problem with such theory of root want is the failure to explain /suicide/, the antithesis of survival.
But this problem is solved,
if it is the human /species/ that wants to survive, and not the human /individual/.
Thus, perhaps the species benefits from having some suicidal individuals.
But what evolutionary advantage does a suicidal individual confer upon the species?
 [fn::http://nautil.us/issue/45/power/does-depression-have-an-evolutionary-purpose]
Why do some people commit suicide?
Don't they want to survive?

Another problem with such theory of root want is to explain wants that detriment survival, such as cigarette-smoking.
But this problem is solved,
if humans only need to survive until their children can live independently,
assuming that humans begin having kids at 20.
Thus, if something is harmful, but fun, and takes more than 40 years to kill a human,
then there will be someone stupid enough to do it, such as cigarette-smoking,
because, before 20th century healthcare, perhaps humans rarely lived past 40,
which is perhaps why evolution did not care about the fertility of women after 40[fn::https://en.wikipedia.org/wiki/Age_and_female_fertility].

Such theory of root want also has to explain /crimes/.
Crime in the 21st century endangers the criminal's survival,
but before states and police were invented,
crime such as stealing food and murdering others does indeed improve the criminal's survival.

Every human has a /preference/ shaped by his genetics, history, and circumstances.
But sometimes this preference seems nonsensical.
For example, do thieves want the stolen thing more than they want freedom from jail?
Do smokers and junk food eaters want the taste of cigarette and food more than they want health?

A satisfied man soon gets bored and begins wanting more.
Why did we evolve boredom?
What is the evolutionary advantage of boredom?

Boredom drives the desire of newer and better ways to do things.

/Boredom drives technological innovation./

Boredom, curiosity, and fear improve survival.

Cautious curiosity improves survival.

Natural sciences and social sciences need not be divided,
because all social sciences are about human nature,
which can be partially explained by the theory of /evolution/,
which is studied in /biology/.
For an example of relationship between biology and economy,
it would not be unreasonable to posit that hormones affect buying decisions.
What complicates social sciences is that the chain of causes is not a simple line as in natural sciences,
but is a complex graph of necessary causes that must happen together in order to cause the effect.
However, the objects of study of social sciences are nevertheless parts of nature,
and thus ultimately follow the laws of nature.
*** Under what conditions are people willing to do things for free?
And, is it really for free?

Are city-dwellers more calculating than villagers?
*** Imperfections, irrationality, laziness, satisficing, "good enough"
Recurrent buying, search cost, switching cost, and "satisficing"[fn::https://en.wikipedia.org/wiki/Satisficing]

People do not look for "best"; they merely look for "good enough".
* What does a capitalist do?
* Why should anyone be entitled to any ownership at all?
Why does one who owns a cow expect to own all descendants of that cow?

Why do we let anyone own anything at all?

We take ownership for granted, but ownership is a recent phenomenon
that did not exist in ancient prehistoric times.

Is ownership (exclusive access) good?
Does it promote the survival of the human species?
Does respecting ownership promote the survival of the human species?
* Why should anyone be paid at all?
Why should everyone be paid the same?
Why should everyone be paid differently?
One can argue for both, so the actual question is:
Why should anyone be paid at all?

In a gift economy, no one is paid?
* Ownership vs possession?
* Capital is tool, a productivity multiplier
Examples of capitals: machines, hammers, computer programs, processes.

As "capital" means "tool",
the phrase "human capital" implies that humans are tools.
Toolmakers create tools with a specific purpose in mind.
What are the purpose of humans?
To execute business logic.
Humans are selfish/egoistical biological robots with high maintenance cost.

Capital = tool = productivity multiplier = technology = self-extension?

If people are capital, then people are tools.
To a capitalist, the maintenance of humans is no different than the maintenance of machines:
It is simply an irreducible cost that has to be paid in order to gain a bigger profit.

If people are tools, what are they for?
Execution of business processes.
Logic.
Control.
Program.
Like computers.
Humans are unreliable computers.
Computers never refuse to run a program.
Humans are finicky.

A hammer is a tool for driving nails into walls.

A human is a tool for what?

A human is a tool for delegation, for doing what you have to do but would rather not do.

A human is a tool for duplicating the tool user.
One can teach humans to do simple things.
One can program humans in a very high-level ambiguous programming languages,
unlike classical computer programming ("hard computing" as opposed to "soft computing")
that require exact definitions of everything down to the smallest details.

A lathe is a tool for making tools?
* How capital is accumulated and inequality is created
One who owns cows will own even more cows without any effort, because cows breed.

One who owns corn plants will own even more corn plants without any effort, because corn plants grow.

To get more capitals,
own a capital and everything produced by that capital,
including all descendant capitals produced by that initial capital.

Why should anyone be granted ownership (exclusive access) to cows (or land, or anything at all)?

Expropriation of nature?
* An abridged history of the world from economics point of view
Humans started out as hunters and gatherers.

Then they began making tools for killing preys to make hunting easier.
Less work, more leisure.

Then they began farming and domesticating plants and animals.

One theme is common:
Humans always try to reduce the effort necessary to survive.

State[fn::https://en.wikipedia.org/w/index.php?title=State_(polity)&oldid=904019453]:
#+BEGIN_QUOTE
The earliest forms of the state emerged whenever it became possible to centralize power in a durable way.
Agriculture and writing are almost everywhere associated with this process:
agriculture because it allowed for the emergence of a social class of people who did not have to spend most of their time providing for their own subsistence,
and writing (or an equivalent of writing, like Inca quipus) because it made possible the centralization of vital information.
#+END_QUOTE

Leisure.
Boredom.
Creativity.
Technology.
Laziness.

Surplus.
Trade/exchange.

Labor is the currency of Nature.
Nature pays everyone who works:
Foragers get to eat berries,
hunters get to eat meat, and
farmers get to eat vegetables.

Money as medium of exchange goes back to at least ...[fn::https://en.wikipedia.org/wiki/History_of_money]

Lending and usury goes back to at least ...

Tribalism ...

Monarchy ...

Feudalism ...

Tulip bubble ...

Imperialism, colonialism, expansionism, the worship of growth

VOC, the biggest corporation ever

Engines, machines

States, centralization of power, USSR, USA ...

Computers, automation

The confusion between money and wealth ...
** Evolution of economic systems
*** Pure-labor economy in hunting tribes
All labor, no capital, no money.

Resources are allocated according to kinship:
- The hunters get to eat first.
- The families of the hunters get to eat next.
- Other people in the tribe get to eat whatever that remains.
*** Sedentary agricultural societies
*** Physical machines and the Industrial Revolution
*** Mental machines and the Information Age
* Productivity, and its measurement
** Productivity, output, production
Productivity is /output per input/.

Economically, /output/ is something satisfying a want.
For example, a machine produces goods, but it also produces heat, pollution, and waste,
but only the goods is useful to humans, and thus the goods is the output.

Production is a process of transforming /less useful/ things into /more useful/ things.
What is useful is determined by human nature, which is ultimately shaped by evolution.

Thus, productivity is the /efficiency/ of production.

Thus, productivity is the rate of addition of value.

An examples of false productivity that feels good but only wastes time is
checking off lots of unimportant things from a to-do list.
Another example is sorting files and folders that we rarely use.
Those are examples of being /unproductively busy/.

In manufacturing, a defective product does not satisfy wants,
and thus defective products reduce productivity.
However, an overzealous quality control for zero defect rate also reduces productivity.
** Not important: the etymology of "productivity"
Where does the word "productivity" come from?
- productivity[fn::https://en.wiktionary.org/wiki/productivity] ← productive + -ity[fn::https://en.wiktionary.org/wiki/-ity]
- productive[fn::https://en.wiktionary.org/wiki/productive] ← prōductīvus
- prōductīvus[fn::https://en.wiktionary.org/wiki/productivus] ← prōdūcō + -īvus[fn::https://en.wiktionary.org/wiki/-ivus]
- prōdūcō[fn::https://en.wiktionary.org/wiki/produco] ← prō-[fn::https://en.wiktionary.org/wiki/pro-] + dūcō[fn::https://en.wiktionary.org/wiki/duco]

In 2019, "to produce"[fn::https://en.wiktionary.org/wiki/produce][fn::https://www.etymonline.com/word/produce]
means "to make".

"Productive" means:
- /related/ to producing
- /tending/ (having a tendency) to produce[fn::https://en.wiktionary.org/wiki/-ive]

"Productivity" means:
- the /state/ of being productive[fn::https://en.wiktionary.org/wiki/-ity]
- a /measure/ of someone's ability to produce
  (this definition parallels the definition of
  conductivity[fn::<2019-05-07> "Measure of a material's ability to conduct an electric current"
  https://en.wikipedia.org/wiki/List_of_physical_quantities] in physics
  [fn::http://www.thefreedictionary.com/words-that-end-in-ivity]
  [fn::https://en.wikipedia.org/wiki/Sensitivity_and_specificity])
- In economics, productivity is output per unit of labor.
  [fn::http://www.thefreedictionary.com/productivity]
- "Productivity describes various measures of the efficiency of production.
  A productivity measure is expressed as the /ratio of output to inputs/ used in a production process, i.e. output per unit of input."
  [fn::<2019-05-07> https://en.wikipedia.org/wiki/Productivity]
  (emphasis mine)
** Why should we care about productivity and not only profit?
Productivity increases /wealth/.
Profit increases /pecuniosity/ (/moneyfulness/).

Productivity is /real/.
Profit is /nominal/.

Productivity is about /value/.
Profit is about /price/.

Productivity does not always mean profitability.
For example, a farmer may produce a lot of oranges, but when the demand for oranges is low,
he may not be able to sell his excess production for profit.
** What should be produced?
We should produce /goods/, which is what is /good/,
which depends on the /moral system/ we subscribe to.

A /utilitarian/ produces what maximizes the /total satisfaction of the population/.
However, he has no qualms killing 1,000 people to save 1,000,000 people.

A /hedonist/ produces what brings him the most joy when he produces it.
But what good is production for its own sake?
** Production, consumption, and satisfaction
People consume to satisfy their wants.

Consumption is the dual of production.

Satisfaction is the dual of quality.

Consumption is the dual of production?
But production is not exactly the opposite of consumption:
/Consumption produces/ satisfaction, and /production consumes/ input.
But for something to be consumed, it must first be produced.

We can think of a chain of boxes; each box consumes its inputs and produces its outputs;
the outputs of a box are the inputs of another box, and so on.
The end goal is to produce /satisfaction/.
** Measure productivity?
*** Is it practical to measure productivity?
What does it mean to measure productivity?

It is impractical to trace all the causal chains.

It is easy to compare factory worker productivity between such workers because:
- The causal chain is very simple and short.
- The interaction between factory workers do not affect each worker's productivity.
- The environmental factors (machines, lighting, etc.) are constant and identical for all workers.

A knowledge worker's productivity is affected by peer interaction.

In order to measure a programmer's productivity, he must first be isolated from everyone else.
But this isolation affects his productivity?

If both A and B are necessary causes of C,
then A or B alone is not sufficient to cause C.
Each of A and B is a causal factor (necessary but not sufficient).
The cause of C cannot be reduced to either A or B.
Both of them are necessary to cause C.
For example, in the fire triangle, all of fuel, oxygen, and heat are necessary to cause fire.
The cause of fire cannot be reduced to any strict sub-combination of those three factors.

Measuring producitivity requires understanding causality.

It is not as simple as blaming the proximate (the nearest) cause.
For example, suppose a smoker in a gas station causes an explosion.
The blame is /largely/, but not /entirely/ on the smoker,
because the smoker alone is not enough to cause the explosion:
the explosion requires gasoline vapor,
which is caused by the existence of the gas station,
which is caused by the demand for gas,
which is caused by other car owners,
and so on.
In the end, all of humanity shares a little blame, although negligible.
*** When is line of code a valid measure?
Lines-of-code (LOC) can be a valid measure if they are /normalized/ first,
like purchasing-power-parity adjustment in currency exchange rates.

LOC should only be compared for the same /language/ and /style/.

Some possible conventions:
One atomic statement per line.

1 LOC of normal-style C is not equal to 1 LOC of normal-style Java,
in the same way we cannot equate 1 kilogram and 1 pound.
*** Complexity points? Story points? Function points?
- What the hell are we trying to measure?
- What should we care about?
  We only care about /how long it takes to make/.
*** What does a software engineer do?
- Find out what the user really wants.
- Formalize user requirements.
*** How do we compare programmers/code?
- correctness of the system
- maintainability of the system
- efficiency of the system
- time taken to implement the system
*** How do we measure developer productivity?
- 2004 article "Defining and measuring the productivity of programming languages" [[https://pdfs.semanticscholar.org/1852/9ff58460b6238f5095af073d8505d79d3264.pdf][pdf]]:
  - It defines these metrics:
    - "the time and effort required to write, debug, and tune the code"
    - "the performance of the code that results"
  - power-efficiency graph (human efficiency and machine efficiency)
  - what else?
- 2008 https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/Web/Planning/productivity.html
  - https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/
- 1992 article https://www.andrews.edu/~vyhmeisr/papers/progprod.html
- 2012 article http://www.drdobbs.com/jvm/the-comparative-productivity-of-programm/240005881
  - "A database comparing 6,000 projects shows that the choice of programming language has a significant impact on project schedule."

State of the art[fn::https://en.wikipedia.org/wiki/Programming_productivity]?

\cite{karimi2016links}
*** What?
- 2015, PhD thesis, Bergersen, "Measuring Programming Skill: Construction and Validation of an Instrument for Evaluating Java Developers"
  - [[http://folk.uio.no/gunnab/publications/Bergersen2015_PhD_thesis.pdf][pdf]]
  - It's a collection of 4 articles.
  - https://www.duo.uio.no/handle/10852/48583
*** Ideas?
*** Quantity-quality output model
Output should be a function of /quantity/ and /quality/,
but perhaps not a simple multiplication.
If quality is too low, quantity does not matter, because no buyer wants it.
If quality is too high, it does not matter, because no buyer can perceive the quality difference.

What is /quality/?

The ability to produce, or the ability to /satisfy consumers/?
Producers don't produce for the sake of production.
Producers keeps producing because there is unsatisfied demand.

Aren't we putting too much emphasis on consumption?

Quality is an arbitrary number?
Subjective?

100 oranges at quality 20 vs 50 oranges at quality 40?

100 room-cleaning at quality 50 vs 50 room-cleaning at quality 100?

The output of a machine is defined by the machine's designer.

The output of a system is defined by the system's designer.

People always desire speed, easiness, simplicity, laziness, less effort, more joy, more fun, more chance of survival
*** How do we measure the productivity of services producers?
The same way we measure the productivity of goods producers?
* Technology, and its valuation
** Technology as productivity multiplier
Economically, a technology, including software,
no matter how sophisticated, can be thought of as just a /productivity multiplier/,
that /helps/ satisfy wants by improving the productivity in producing existing goods and services.
The word "help" is emphasized, because technology is the means, not the end,
which is the satisfaction of human wants.
At the end of all sophisticated technologies is the satisfaction of human wants,
one of which is to survive with less effort,
which drives the development of many technologies,
such as self-driving cars, artificial intelligence, planetary defense, and so on.

One does not want hardware only or software only.
One wants a /system/, sometimes a machine, a combination of hardware and software, that satisfies some wants.

Software is limited by hardware.
Hardware is limited by reality.
But few people are going to buy hardware that cannot run existing software.
** Productivity and unit economics
Unit economics is the /nominalization/ of productivity.
Unit economics is obtained by converting the factors in productivity into monetary amounts,
using prices obtainable by the agent in consideration.
** Comparing productivity
An over-simplified imaginary example of comparing the productivity of two productions:
- Process 1: A human takes 0.1 kg of rice and 8 hours of labor, and gives 10 clothes per day.
- Process 2: A machine takes 0.1 kg of fuel and 1 hour of labor, and gives 100 clothes per day.

Assumptions:
- Both processes produce outputs of the same quality.
- Labor hours have been adjusted for skill.

\begin{align*}
\text{relative productivity} &= \frac{\text{productivity 2}}{\text{productivity 1}}
\\ &= \frac{\text{output 2} / \text{input 2}}{\text{output 1} / \text{input 1}}
\\ &= \frac{\text{100 clothes} / (\text{0.1 kg fuel} + \text{1 hour labor})}{\text{10 clothes} / (\text{0.1 kg rice} + \text{8 hours labor})}
\\ &= \frac{10 \cdot (\text{0.1 kg rice} + \text{8 hours labor})}{\text{0.1 kg fuel} + \text{1 hour labor}}
\\ &= \frac{\text{10 kg rice} + \text{800 hours labor}}{\text{1 kg fuel} + \text{10 hour labor}}
\end{align*}

That fraction cannot be simplified further without more simplifying assumptions.

The relative productivity can be /nominalized/ with price assumptions.
For example, with the assumption that rice is $0.86/kg, labor is $3/hour, and fuel is $1/kg, similar to Indonesian prices in 2019,
we can compare the productivity of process 1 and process 2:
\begin{align*}
\frac{\$8.6 + \$2,400}{\$1 + \$30} &= \frac{\$2,408.6}{\$31}
\\ &\approx 77.7
\end{align*}

Thus, process 2 is /nominally/ 77.7 times as productive as process 1, under the above assumptions.

The nominal relative productivity changes with price changes.

Only /scarce resources/ need to be considered economically.
What is scarce depends on the situation.
For example, on a typical day on Earth in the 21st century,
oxygen is abundant;
but in a spaceship, oxygen is scarce.

The input is material and energy.
The output is material and energy.
** Economic production processes
Processes can be composed.
If process P transforms X to Y with productivity p,
and process Q transforms Y to Z with productivity q,
then process PQ transforms X to Z with productivity pq.
** Valuation of technologies
If the /new process/ takes $1 to produce a cloth,
and the /common process/ takes $10 to produce a cloth,
then the /advantage/ of the new process over the common process is $9 per cloth.

The following pricing example will make us understand.
If I am the only one who can produce clothes at $1 each,
and the best everybody else can produce clothes at is $10 each,
then I can extract a maximum profit of $9 per cloth,
/until/ someone else catches up with my technology,
until he independently reinvents my technology or something better,
until my technology becomes /common/ or obsolete.
If I can expect to sell 1,000 clothes before my technology becomes common,
then I can expect a profit of $9,000 from this technology,
and thus the price of my technology should be $9,000
minus the discount for time preference.

Therefore,
the price of a new technology depends on:
- its /advantage/ against the common technology, and
- its /difficulty/, that is, how hard it is to independently reinvent.

Higher difficulty gives more time to profit from the technology,
if trade secrets are protected,
and if nobody else has been developing a similar technology.

The /no-arbitrage price/ of a new technology is the /expected profit/
brought about by using that new technology against the current technology.
This price is relative to how far the agent can exploit the new technology.

What should be the price of a technology?

What should be the price of something?

What should be the price of a machine?
** Technology and society in the 21st century
The introduction of a technology obsoletes another technology,
and thus reduces the demand for labor skilled in the old technology.

In the 21st century, technology development is speeding up,
and new technologies are obsoleting skills faster than the obsolete-skilled humans can die naturally.
This may create a huge unemployment and a huge population of poor old people.
** Where does software operation and maintenance fit in the big picture of productivity?
Once created, software has to be operated.
Software operation has costs.
** What are the inputs of software production process?
- man-hour
- machine-hour
- electricity
** Not too important?
*** What is technology?
/Technology/ is the Greek-English of /the study of arts/[fn::https://www.etymonline.com/word/technology],
where /art/ means skill or craft, not the narrow meaning of paintings, sculpture, music, etc.[fn::https://www.etymonline.com/word/art].

Humans seek better ways to do things.

Humans do not want technology in and of itself,
but humans want the increase of survival that is enabled by the technology.

Technology is the fruit of human ingenuity.

How does technology improve productivity?

Technology enables a person to control more things.
With bare hands, a person can control 10 kg.
With power tools, a person can control 100 kg.

Technology is subject to the laws of nature.

Wikipedia has historical examples of productivity-improving technologies.
 [fn::https://en.wikipedia.org/wiki/Productivity_improving_technologies]
*** Laziness is the mother of technology
Technology is born out of human laziness, that is,
the human desire to minimize work,
to minimize unpleasant things,
to conserve energy,
to minimize energy expenditure.
* Economics for business people
** Taxation
It suffices us to know that /taxation is protection racket/:
If we don't pay the racketeers, they will ruin us.
** Investing, trading, gambling, and insurance
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/

How do we know something is not gambling?
If it's possible to be skillful, then it's not gambling.

What?
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?"[fn::https://www.bbc.com/news/business-38905963]
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
** Finance
What is the difference between /economics/ and /finance/?
- Economics is about value?
- Finance is about money?

"Finance is a field that deals with the study of investments."
 [fn::https://en.wiktionary.org/wiki/finance]
 [fn::https://en.wikipedia.org/wiki/Finance]

- Loan-related jargon

  - A lender lends (gives) a loan to a borrower.
  - A borrower borrows (takes) a loan from a lender.
  - Loan is the amount.
  - Borrower (one who borrows) is the debtor (one who has debt).
  - Lender (one who lends) is the creditor (one who gives credit).
  - Lease vs rent?

    - Lease is more formal and long-term than rent.

      - [[http://www.businessdictionary.com/article/1063/lease-vs-rent-d1412/][businessdictionary.com]]
      - [[https://www.nolo.com/legal-encyclopedia/leases-rental-agreements-faq.html][nolo.com]]

- Currency-related jargon

  - The /price/ is the amount paid by the buyer to the seller.
  - What is currency?
  - What is money?
  - What is the difference between currency and money?

    - https://www.weusecoins.com/hidden-secrets-of-money-currency-versus-money/

      - "Currency is a medium of exchange, a unit of account."
      - "Money is [currency] plus a store of value over a long period of time."

  - What is legal tender?
  - What is cryptocurrency?
  - Is there such thing as "cryptomoney"?

- Securities

  - A [[https://en.wikipedia.org/wiki/Security_(finance)][security]] is a /claim/ to something.
  - An /exchange/ was a place (is a computer system) where things are traded (bought and sold).

    - The exchange requires /brokers/ because it was invented before computers.

      - Impractical: 1 million people on the trading floor shouting for a match.

        - But a computer can match 1 million trades in a second.

      - Nobody bothers making a new stock exchange.

        - Because of [[https://en.wikipedia.org/wiki/Network_effect#Financial_exchanges][network effect]].
        - But [[https://robinhood.com/][Robinhood]] is doing that,

          - but it's a broker, not a stock exchange,

            - but I hope they make buying stock as easy as ordering pizza online,

              - because if everyone uses the same broker,
                then the broker /is/ the exchange.

          - [[https://support.robinhood.com/hc/en-us/articles/202853769-How-Robinhood-Makes-Money][How Robinhood makes money]]

            - No trading fee.
            - $6 per month per person who uses Robinhood Gold; otherwise none.
            - In 2017, Robinhood had 2 million users ([[https://techcrunch.com/2017/04/26/robincorn/][techcrunch.com]]).

              - How many of them use Robinhood Gold?

                - How many people have margin account compared to regular account?

                  - I guess 1:100.

              - How many employees do Robinhood have?

                - 30 ([[https://www.owler.com/company/robinhood][owler.com]])

              - Does that make sense?

                - My estimate:

                  - Their revenue:

                    - $60,000 per month = $720,000 per year.

                  - Their expenses:

                    - $300,000 per year for employees.
                    - ? for stock exchange chairs.
                    - ? for building leases.

                - Yes, it makes sense.
                - Are customers "mercy-buying" because they think Robinhood is too cheap (compared to old-school brokerages)?

                  - [[https://www.stockbrokers.com/guides/features-fees][stockbrokers.com: 21 Most Common Online Broker Features & Fees]]
                  - Comparison: In Indonesia, stock trading cost is about 0.02% of trade value.

    - A stock exchange starts out trading stocks,
      but after some time it begins trading other securities,
      but the name has stuck.

  - A /bond/ is a securitized loan?
  - Every asset can be securitized?
  - Stock

    - /Stock/ is company ownership.
    - A /share/ is a fraction of stock.
    - Buying share means buying partial company ownership.

- Undigested information

  - [[http://noahpinionblog.blogspot.co.id/2013/01/how-much-value-does-finance-industry.html][Noahpinion: How much value does the finance industry create?]]
  - Investing, speculating, or gambling?

    - Slap some "math" on gambling masquerading as "investing", and suddenly it looks legit.
    - "Modern investing: gambling in disguise", David Schneider
** Use the economic/financial system to centralize power?
What are we trying to do?
- Understand how to make the system works for us instead of making us work for the system.

Sam Altman puts it concisely: "You get rich by owning things."[fn::http://blog.samaltman.com/how-to-be-successful]

Why do we get rich by owning things?

Because we can ask the police to violate whomever violates our ownership
(unless the perpetrator is the government itself).

Respecting private property enables the accumulation of wealth and the ensuing economic inequality.

Inequality is not poverty.[fn::https://fee.org/articles/stop-conflating-inequality-with-poverty/]

Poverty, not inequality, is the problem.

We have several choices to reduce inequality:
- Embrace capitalism:
  Make everyone own properties and educate everyone to spend money wisely.
- Oppose capitalism:
  Steal from the rich, give to the poor, although this incentivizes poverty.
  Abolish private ownership.
  But isn't this envy-based politics?

But why should we reduce inequality?
It is poverty that we should reduce, not inequality.

Of course some poverty is due to bad luck,
and we should help people who fall into poverty due to bad luck.
But too many entitlement programs are trapping people in poverty.

It is up to us whether we want to find ways to own properties.
*** What is a company?
A company is a /legal fiction/ for concentrating wealth (economic power) to its shareholders.
Such economic power often translates to other forms of power such as political power.

A company is rife with /principal-agent problems/ and /conflicts of interest/.
There is one principal-agent problem between the shareholders and the directors.
There is another principal-agent problem between the directors and the employees.
There is one principal-agent problem for each layer of management.

It is a physically impossible to build or hurt a company.
A company cannot do anything.
People do things.

A company is an abstract object with concrete consequences.
The legal fiction is unreal.
The environmental effects are real.
*** What is "economy"?
What is "economy"?
What is "economy" in "economic meltdown"?

Exchange?
Trade?

Satisfy maximum wants using minimum resources.
There are two solutions:
- Reduce wants.
- Use more resources.

Economics is easy to explain but hard to predict.
Economics is too interconnected.

Demand/consumption is easy; supply/production is hard.

/Demand is easy./
We can want anything.
Changing our minds is free.

/Supply is hard./
We have to work to satisfy our demands.

Consumption is easy.
Production is hard.
Destruction is easy.
Creation is hard.
Second law of thermodynamics: The entropy of the Universe never decreases.
In nature, entropy never decreases.
Disorder arises naturally.
The second law of thermodynamics explains why consumption is easier than production.

The nature of economics is that demand is free, but supply is costly..
Changing demand is cheap: you just change your mind.
Changing supply is costly: all the infrastructure that has been built won't simply turn back into cash.

Demand first or supply first?
Human nature is the root cause of economic demands.
There will always be demand for food and shelter.
There is always demand to make life easier and less boring.

However, in the case of iPhone, we have two views:
- Steve Jobs's presentation causes people to want iPhones. Supply creates demand.
- People always want an easier way to live. Steve Jobs's iPhone just happens to make people's lives easier.

For example:
We want an easier way to live.
People don't want iPhones for iPhones's sake.
People want iPhones because people believe iPhones make people's lives easier.

If demand surges, it will collapse later.
Example: tulip mania.
*** Economic recession
Economic recession is the reduction of money flow velocity.

How do we predict recession?
How do we measure and monitor money flow velocity?
- people savings balance
- mass layoffs
- mass price hikes for vital goods (oil?)
- company profit/loss statements
- money accumulates at few economic actors

Technology introduction, demand shift among substitute goods:

A demand shift is a demand collapse and a demand surge.

Cheaper robotic workers (or increasing minimum wages) causes demand for human workers to collapse and demand for robotic workers to surge.

Demand shifts among substitute goods.
*** Fluid dynamics explains economic recessions
Economic recession happens because money flow slows down.

Money is a fluid.
A fluid flows.
Fluid flow velocity depends on pressure at the source and resistances in the path.

If we want to maintain flow velocity despite increasing resistance, we have to increase pressure at the source of the fluid flow.
But do we want this?

Money flow slows down because people spend less.

People spend less because they have less discretionary income.

People have less discretionary income because they are fired, or governments raise taxes, or important things get more expensive, etc.

Assumption:
A person's behavior changes slowly, if it changes at all.
A person who has never cared about the environment will not suddenly care about the environment.

A recession has two possible direct causes: /demand collapse/ or /supply collapse/.

Examples of supply collapse:
- Mine collapse, oil rig explosion, etc.
- Disasters: fire, earthquake, tsunami, flood, volcanic eruption, etc..
- Lots of people going out of workforce at once (into pension, dying in war, etc.).
- Lots of people suddenly becoming conscious (Google workers demonstrating for transparency, etc.).

Examples of demand collapse:
- The 17th-century tulip mania[fn::https://en.wikipedia.org/wiki/Tulip_mania] ran out of fools (greater fool theory).
- Renewable energy sources reduce oil demand.
- Young people adopt a minimalist lifestyle after realizing that consumerism is unsustainable.
- Government increases minimum wage big enough to make switching to robots looks cheap.
  Lots of companies introduce robot workers at the same time, making human workers redundant.

Supply collapse is caused by physical destruction.
Demand collapse is self-inflicted human condition.

Consumers supply demands to producers.
Consumers demand supplies from producers.
Take and give.
To demand is to take, to consume, to destroy.
To supply is to give, to produce, to create.

What does inverted yield curve has to do with recession?
What does time preference have to do with economic recession?
What is an economic recession?

CAGR = compound annualized growth rate.

What is the yield of a bond?
A bond's yield is the CAGR of the bond price.

What is the yield curve?
The yield curve is the curve in a plot with two axes: the horizontal axis is tenor (duration to maturity), and the vertical axis is yield.

An inverted yield curve indicates that buyers are pessimistic about the bond's future?
*** Currency? Free banking? Digital fiat currencies?
Piggyback nascent fintech/e-cash/e-money startups?
BTPN Jenius?

https://openbazaar.org/blog/trust-is-risk-a-decentralized-trust-system/
Currency requires trust.
Debt requires trust.
Transaction requires trust.
Business requires trust.
What is trust?

A trustworthy person refrains from exploiting vulnerabilities.
Trust is the assumption that the other party refrains from exploitation.
Trust is the assumption of the absence of betrayal.
Betrayal is the exploitation of trust.
(Problem: Circular definition.)
*** Economics of open-source
https://en.wikipedia.org/wiki/Open-source_economics

Where do we draw the line between open core and crippleware?
- https://en.wikipedia.org/wiki/Open-core_model
- https://en.wikipedia.org/wiki/Crippleware

Is "open core" just an euphemism of "crippleware"?

If the open core is actually useful, then it isn't crippleware.
http://blogs.collab.net/subversion/enough-of-this-open-core-confusion

Marginal cost is the change in opportunity cost due to increasing production quantity by one.
https://en.wikipedia.org/wiki/Marginal_cost
*** Understand how capitalism centralizes power
Capitalism is:[fn::https://en.wikipedia.org/wiki/Capitalism]
1. the /private ownership/ of means of production,
2. the operation of such means /for profit/.

What?
- http://www.visualcapitalist.com/
- Capital is everything that is not labor?
- Capitalism is capital above labor? Communism is labor above capital?
- Example of low-capital high-labor:
  - small and medium enterprises (SMEs)
    - food stalls
    - home bakeries
    - art freelancing
  - research in pure mathematics
*** Companies must extract value to survive
- A profitable company must extract more value
  from its employees than it pays its employees.
  - People create value. People in a company create value. Human labor creates value.
    Companies aren't human. Companies can't work. It's the employees who work.
  - But if the employees weren't in the company, they might create less value.
    The company might be a place where the employees can create more value for society.
*** "Investing"
What Bitcoin "investing" is:
- You buy a certificate of environmental destruction from someone, probably a "miner".
- You expect a greater fool to buy that certificate from you at a higher price.
  There are millions of other people who are looking for someone else more stupid than them.

Bitcoin is massive wealth transfer from late buyers to early buyers.
All financial investing is massive "realistic-return" Ponzi scheme.
Exactly fits the definition.
Newcomers pay oldtimers.
Late buyers pay early buyers.

Bitcoin is not necessary at all. It is pure want.
Inflation target disincentivizes currency hoarding.
A deflating currency encourages currency hoarding and discourages real spending.
https://www.cmegroup.com/education/featured-reports/an-in-depth-look-at-the-economics-of-bitcoin.html

https://www.theguardian.com/technology/2018/nov/05/energy-cost-of-mining-bitcoin-more-than-twice-that-of-copper-or-gold
*** Economics, price, quality
Price is not important in itself.
It is the quality-price trade-off that is important.
People don't buy shit even if it's cheap, even if you pay them to buy it.

For an increment of quality, people are willing to pay an increment of price.
But there is a "good enough" point where people are satisfied and they just look at the lowest price.

Negative price means willingness to pay to get rid of something.
Example: rotten vegetables has negative price to most people, but positive price to farmers.
*** Economics?
We should measure debt-to-income ratio instead of debt-to-GDP ratio?

Consumptive debt sacrifices future for the present.

Productive debt is good.

Example of productive debt:

Suppose that you want to buy a land to farm on it. These are the scenarios:
- You work for 20 years. Then you buy the land with cash. But the land price has risen.
- You take a loan, buy the land now, and repay the loan over 10 years. In the second year, your land starts producing.

If a person takes too much consumptive debt, he goes bankrupt.

If a government takes too much consumptive debt nominated in its own currency, it can print money to repay the debt, but such printing devalues the currency.

If the US continues to take loans mindlessly, it will have to choose:
- Default (refuse to repay).
- Suffer severe inflation (rising prices), if the creditors spend the printed money.

Does the USA think it can get away by refusing to repay its debts? It will trigger a huge power shift, maybe to China. Will China sacrifice itself to clean up America's mess? Will China buy up all US debts, and use the default as a reason to start a war?

https://deviantinvestor.com/9778/sacrificing-future-spending/

https://en.wikipedia.org/wiki/Unearned_income

Everything comes from nature.
We are not creating or destroying anything.
We are merely transforming things.
At least as seen from physics.

The number of atoms in Earth doesn't change.
(But what about solar wind? It does change a bit?)

Urban toilet harms humans and the Earth.
- We should poo squatting, not sitting.
- Urine and feces should be composted, not flushed down the drain.
- Compost bins should replace septic tanks.

https://www.vice.com/amp/en_us/article/zm95ka/republicans-are-outraged-about-the-deficit-they-caused

https://en.wikipedia.org/wiki/Unrestricted_Warfare
*** There are only two ways to get rich: earn or steal
There are only two ways to get rich: /earn/ wealth or /steal/ wealth.

Earn wealth: convince people to give you money, by selling them things that improve their lives.
Use the money to develop your wealth even more.

Or steal wealth: An investor steals a little wealth from each person who does not invest.

After you obtain enough wealth, develop it, but don't lose all of them.
** Understand the causal chain of profit
The direct cause of profit is the ability to sell something at a price higher than its production cost.

Why is that?

Why is a working car more valuable than a broken car?

From neuroscientific point of view, people buy because of dopamine?

Patrick Anderson has an interesting idea:
"the origin of profit is the consumer's lack of ownership in the means of production"
 [fn::http://postgrowth.org/how-on-earth-flourishing-in-a-not-for-profit-economy-by-2050/].
** negotiation, price-taker, price-maker, BATNA
- Negotiating parties often have asymmetrical bargaining power.
- The price-taker is the weaker one.
- The price-maker is the stronger one.
- When negotiating, we want to know the BATNA[fn::https://en.wikipedia.org/wiki/Best_alternative_to_a_negotiated_agreement] of each party
** Understand money
/Money and human/ can be thought of as /seed and soil/.
Some humans are fertile soils for money to grow.
A poor person who wins a lottery soon loses all of it.
A rich person who wins a lottery keeps getting richer.
A fool and his money are soon parted.
However, this way of thinking puts money first and human second.
We can think of how fast money flows through a person,
similar to how we think of how fast crops grow in a soil.
The person's business ability is akin to the soil's fertility.

Money is also a way for people to /vote/ for what they want.
People vote with their money.
Money is the consumer's vote for what producers should do.
Money is the people's vote for what companies should do.
Indeed the voice of the people is the voice of God[fn::https://en.wikipedia.org/wiki/Vox_Populi,_Vox_Dei],
in politics, and more so in economics, no matter how perverse.
/The consumers are the masters of the companies,/
because the consumers are who feed the companies money.
Whoever feeds a company is its master.
Surprisingly companies are very much like dogs; but companies eat money whereas dogs eat meat.
But /the consumers collectively have the power to teach[fn::https://en.wikipedia.org/wiki/Operant_conditioning] the companies/,
that is, to reward wanted behavior and punish unwanted behavior.
The key word is /collectively/: an individual consumer is powerless,
but all those consumers together are the master of the companies,
and it is the average behavior of all consumers that is sensed by the companies.
Thus a negligent master will produce an untrained dog that litters anywhere it wants and destroys anything it wants.
Unfortunately the consumers are divided; they would be strong if they united.[fn::https://en.wikipedia.org/wiki/Consumer_activism]

/Can we use cognitive behavioral therapy on companies?/
Can we use the same techniques we use to fix misbehaving dogs?
We treat a company as an indivisible psychological entity.

Sometimes, pervertedly, the master depends on the dog,
although it is the dog that should depend on the master.
This perversion happens in monopolies.

The 21st century environmental destruction has been voted for by the consumers.
Companies are merely obeying the wishes of their masters, the consumers.
Consumers want quick and cheap.
Consumers do not care about how something was made or where something came from.

If consumers cannot or will not care,
then the government has to step in to internalize the negative externalities back into the offending firms,
and prevent the extinction of those short-sighted consumers.
*** Money as fluid
*** Money as blood
Economic actors are the organs, and money is the blood.
*** Money is valuable due to higher-order belief
People believe that money is valuable because they believe
that others also believe that money is valuable.

The value of money depends on whether there are people nearby willing to accept it.

Money has no inherent value.
We attach value to money.

It's the same:
Words do not have inherent meaning,
We attach meaning to words.

It's all convention that enables us to exchange.
Language enables the exchange of ideas.
Money enables the exchange of goods.

Related: Keynesian beauty contest[fn::https://en.wikipedia.org/wiki/Keynesian_beauty_contest]
** Sell what we would buy?
One thing is almost certain:
If I want something, there is very likely someone else who also want it among all 7 billion people on Earth.
Thus, /we should sell what we would buy/ because:
- We understand what we buy and why we buy it, so we can explain it.
- Our buying demonstrates that the market exists.
- We know how to sell that thing,
  because the buyers are similar to ourselves.
** Job market, salary
*** Why do some markets such as job markets don't show prices?
A supermarket shows its prices prominently.

Why doesn't a job market show its prices?

[[https://www.flexjobs.com/blog/post/why-isnt-salary-always-listed-on-a-postin/][Why Isn't Salary Always Listed on a Job Posting? - FlexJobs]]

- Adam Ruins Everything - Why You Should Tell Coworkers Your Salary https://www.youtube.com/watch?v=7xH7eGFuSYI

Adam Ruins Everything - Why You Should Tell Coworkers Your Salary
https://www.youtube.com/watch?v=7xH7eGFuSYI

Adam Ruins Everything - Work 40 Hours a Week
https://www.youtube.com/watch?v=rHpYQ8rYSrI
*** Would it be better if they do?
- https://www.elitedaily.com/money/about-sharing-salaries/1171642
*** How much should you be paid?
https://www.forbes.com/sites/jacquelynsmith/2012/11/27/how-to-figure-out-what-you-really-should-be-paid/#333beba75402
*** Handle employee salary questions
What to do when an employee asks us about why his salary is what it is?

We must not pretend that we know the answer.

The correct answer is /more questions/, a coaching activity:
- What do you mean by that question?

Does he simply envy a coworker?

Is he simply a rational person who wants to maximize his salary-to-effort ratio?

Fairness does not exist.
What exists is the /feeling/ of being treated unfairly.

Why am I paid a different salary to do the same thing?
But what is /same/?

Salary is /price/, not value.

Do not conflate /price/ and /value/.

In order for a business to profit, it must pay employees salary lower than their value.
It must buy labor at a lower cost than it sells its products.
** Economic crises
A /crisis/ is a mass discontent.

An /economic crisis/ is a mass discontent due to mass reduction of purchasing power.

"A financial crisis is any of a broad variety of situations in which some financial assets suddenly lose a large part of their nominal value."
 [fn::https://en.wikipedia.org/wiki/Financial_crisis]

- High firing rate, high unemployment, unemployed people having genuine difficulty finding jobs, employers not willing to employ
- Greatly reduced demand (discretionary spending)
- Reduced purchasing power

Why do economic crises happen?

/Some/ economic crises such as the Great Depression might have been /self-fulfilling prophecies/.

- People believe that there is a crisis, whereas there is actually none.
- People reduce spending, and save more, believing that hard times lie ahead.
- Companies profit go down.
- Companies lay off workers.
- There is now an actual crisis.

Similarly, some economic booms might also be self-fulfilling prophecies.

- People believe that the economy is doing good, whereas it is actually what it has always been.
- People increase spending, and save less, believing that good times lie ahead.
- Companies profit go up.
- Companies hire more workers.
- There is now an actual boom.

The government and mass media must maintain public opinion about the economic outlook;
we want people to be moderate, cautious, not too pessimistic, not too optimistic.

Some economic crises are due to /mismanagement/.
For example, Venezuela failed to diversify its economy;
its government depended too much on its oil exports.
Then oil price crashed in 2014, and the Venezuelan economy went down with it,
spurring a social crisis in 2018 and the mass exodus of millions of people.
Their people have to learn the hard way that there is no free lunch.

<2019-05-18>
Another brewing crisis is the excessive property speculation in China, Indonesia, and other Asian countries.
The governments must brake property ownership and steer the public opinion away
from the widespread false belief that real estate is a safe-and-sure investment.
Otherwise, the higher the price goes, the more it hurts when it crashes.
Increasing real estate price is not real economic growth.
The governments must encourage real economic growth,
and discourage "financial growth", which is just a fancy term for shuffling wealth around.

Nothing is free.
If you get something for free,
then either someone else has paid for it,
or you are the product being sold.
** Selling abstract-ideal things
*** The abstract-ideal nature of software
Software can be thought of as both goods and services.

In the goods view, an engineer /produces/ software in the same way a chicken lays eggs.

In the services view, an engineer is a slave-driver
that /translates/ human wants into programs that force the machine to satisfy the wants.

But the goods view is somewhat strange:
Software can be /copied/ but not /moved/,
unlike physical goods which can be /moved/ but not /copied/.

Hardware is concrete and material.
Software is abstract and ideal.

Software does not get consumed.
Food gets consumed.
When you eat food, the food is gone.
When you use software, the software is still there.
Software does not wear out.
*** The economics of abstract-ideal things
The non-materiality of software affects how we can sell it.
In economic parlance, the marginal cost[fn::https://en.wikipedia.org/wiki/Marginal_cost] of production of software is zero.

How do we profit from software without going against the abstract-ideal nature of software?
The key is to sell an /embodiment/ of the software, not the software itself.
One way is to embody the software in hardware, and sell that hardware, such as calculators and Tamagotchis.
Another way is the /software-as-a-service/ (SaaS)[fn::https://en.wikipedia.org/wiki/Software_as_a_service] model,
in which the software is usually presented as a website,
typically embodied in hardware in a cloud,
and what is sold is the /license/ to use the software.
A SaaS is like an amusement park: one pays for access to get in.
The difference is that your experience of the amusement park belongs to you,
but your data is usually locked into the SaaS vendor.

To make money from software without necessarily selling the software or an embodiment of it,
also without going against the abstract-ideal nature of software,
one can resort to /subscription/ or /advertising/.
But advertising destroys the Internet.[fn::http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html]

An example of something that goes against the abstract-ideal nature of software is DRM (Digital Rights Management).
It is fundamentally impossible; it is absurd; it is self-defeating; it goes against nature.
Bruce Schneier sums it up in an eloquent analogy: "Digital files cannot be made uncopyable, any more than water can be made not wet."
 [fn::https://superuser.com/questions/14224/how-can-i-explain-why-drm-cannot-work]
 [fn::https://www.schneier.com/crypto-gram/archives/2001/0515.html#3]
Anything that goes against nature is bound to encounter much hardship, if not immediate failure.

Another abstract-ideal thing is ideas.
How do we sell ideas?
How do we sell mathematics?
How do we sell knowledge?
* Economics in the 20th and 21st centuries
** What is it like to live in the 21st century?
In the 21st century, the effort required by a rich person to survive is practically zero.
Food is nutritious and cheap.
Healthcare is good, but expensive, but rich people can still afford it.
The only thing a rich person needs to do to survive is to avoid doing stupid things with all that money.

The life of poor people has pretty much always been the same.
However, the most unfortunate are the poor who live in cities.
More fortunate than them are the poor people who live at fertile lands,
because they can work to eat,
because nature always buys everyone's labor and sells food to everyone who works.
Nature feeds everyone who works.
But city dwellers are not willing to buy the poor people's labor, because city dwellers have no use of them.

The 21st century is the age of /irrelevant abundance/:
There are so many things in this world that we do not want or do not care about.
Contrast this to the first days of human existence,
when everyone cares about one thing, and one thing only: survival.
** Economic systems are converging
Economically, the Cold War can be thought of as a world-wide experiment to find out
which is better between market economy and command economy.
The result is clear: market economy is better than command economy, although not the best.

America began with too much individual freedom.
Russia began with too little individual freedom.
Both have a problem distributing wealth:
America, despite being the most wealthy nation on Earth, has unexpectedly many poor people;
meanwhile, Russia's statistical distribution of wealth is too skewed toward the poor side.
But they are converging toward the center,
where wealth distribution is more balanced but individual freedom is not too much sacrificed.
Note that we do /not/ want to /flatten/ the statistical distribution;
we merely want to /nudge/ the leftmost part of the distribution toward the right,
in order to improve the lives of the poorest people,
without stealing from the rich.

It seems that the sweet spot is a market economy,
mostly free market,
with some regulation,
with low flat tax rate of about 10--20%
 [fn::https://ndsmcobserver.com/2018/04/arthur-laffer-tax-economic-growth/]
 [fn::https://octavianreport.com/article/arthur-laffer-on-taxes-prosperity-and-freedom/],
with some social safety net.
** The next tenfold-increase technologies in the 21st century?
In agriculture, /vertical farming/ promises tenfold increase (just build a ten-story farm),
which is easy from the 21st century point of view,
but what about the cost-benefit ratio?

What about other fields?

Quantum computers?

Nuclear power?

Wikipedia has a page on emerging technologies.[fn::https://en.wikipedia.org/wiki/Emerging_technologies]
** What is the best economic system?
What is the economic system that satisfies the most wants?

Gift economy?
Tribalism?

Capitalism is utilitarian?

Overproduction is waste.
When the production exceeds wants.
People are saturated.
It may be wasteful if everyone produces the same thing,
because there would be an overproduction.
** Measure the economic success of a country
We should measure the /statistical distribution/ of the living standard, not the GDP (gross domestic product).
We do not want to /flatten/ the distribution.
We want to /shift/ the distribution toward higher living standard.
We want to improve the poorest people without stealing from the rich.
** A new economic system is necessary if humans are to survive the next millennium
* Discontents, problems, and solutions
** Inequality
Is inequality really a problem, or just a symptom of a more fundamental problem?

Why is there inequality?

There are two reasons.

First, people are inherently unequal, as all animals are inherently unequal.
They are born unequal.
They have different genes and environments.

Second, laws enable private property, which enables capitalists to skim value from laborers and to centralize economic power.

Inequality is the direct cause of private property,
which is in turn sanctioned by the very law that we uphold so high.

Massive private property can only exist with protection from the state.

Why should risk-taking be compensated?
** Poverty, breeding, and vicious circle
Poor people are poor because their parents are poor.
Therefore, poverty can be greatly reduced by preventing poor people from breeding.
But what are the unintended consequences?
** The solution to overpopulation is mass murder
Either we do it ourselves, or Nature will do it for us.

Only a natural disaster that kills at least half of all people can fix Jakarta traffic problem.

But a mass murder only delays the problem; humans will breed and recover.
The only solution that addresses the root cause of the problem is to kill all humans.
** Post-scarcity?
Suppose that scarcity does not exist: Everyone has everything they want, and nobody has to work anymore.

Who will do the unpleasant jobs?
Who will clean up accident scenes?
Who will pick up the trash?
Who will clean up melted-down nuclear fission power plants?

If nobody gets paid,

What is the value/price of a stick in Robinson Crusoe economics?
Coconut.
Stick.
** Capitalism is sustainable if there is no negative externality
Negative externality is the problem:
The polluters do not bear the cost themselves.

If we want to keep capitalism,
but we do not want kill all of us,
then we have to have an environmental-damage tax.

The solution is simple in principle:
Carbon tax.

But the solution is not simple in practice:
All countries have to agree on the same carbon tax.
If a country does not have a carbon tax, then the polluters will move there.
How do we measure someone's carbon dioxide emission?

The solution is technology/engineering, not politics.
Mass planting of plants.
Mass murder of humans.
Carbon sequestration.
Politics is part of the problem;
politics slows down engineers and scientists.
** It is not simple to replace capitalism
We must make workers not want to work at corporates,
but how will those workers get money then?

We must provide a way for them to directly convert their labor into wealth, in the same way Nature provides them.

Nature provides a way for converting labor directly into wealth.
** Economics and morality
If economics is "to maximize the sum of wealth with respect to scarcity constraints",
then, is economics inherently utilitarian?

Is it possible to have an economic system that is morally neutral (does not impose any implicit morality)?
** Inheritance?
If inheritance is limited, how do we ensure that the government is a better steward of wealth than those heirs?
The government is not designed to be a good steward of wealth?
* Money
** How much money should be in circulation?
* What?
** <2018-09-24> Competition is wasteful
Suppose that Company A and Company B both make System S.
They duplicate each other's efforts.
Then Company B loses.
Thus everything B (and all other losers) did is /wasted/.

- If a company doesn't have any competitors, it has little incentive to improve.
  (We assume that companies only improve when they are existentially threatened.)
- How do we make sure that something improves even without competition?
  /Guilds/.
  An organization that /intrinsically/ wants to improve (while still profiting),
  not an organization that intrinsically wants to maximize profit at all costs.

[[https://academic.oup.com/antitrust/article/1/1/162/274807][Is competition always good? | Journal of Antitrust Enforcement | Oxford Academic]]

Duplicated Effort vs. Partnership from Christianity perspective
http://www.lausanneworldpulse.com/perspectives-php/1234/01-2010
** Better than capitalism and communism?
If there is no compensation,
then who will do all the unpleasant tasks, such as picking up trash?
** Scaled island economics?
Can we scale the economics of a family to one country?

Can we scale the economics of an island to one country?

Money is one way of scaling economy.

https://en.wikipedia.org/wiki/Robinson_Crusoe_economy
** Understand poverty
*** Money, wealth, and poverty: traversing the causal chain from the proximate cause to the ultimate cause
These are two /different/ questions:
- Why does someone become rich or poor?
- Why is someone rich or poor?

A person becomes rich due to sustained surplus.
A person becomes poor due to sustained deficit.
A surplus enriches a person.
A deficit impoverishes a person.
If his expenses consistently exceeds his income, he will become poor.

Is his expenses too high?
Is his income too low?
**** Mutual causes, vicious circles; poverty, homelessness
TLDR:
Poverty causes homelessness.
Homelessness exacerbates poverty.

Which causes which, between poverty and homelessness?
To find out, answer both "How does a poor person become homeless?" and "How does a homeless person become poor?".

If the poor can increase his income, he will be able to buy a home.
But to increase his income, he need to have a home (a mailing address) first.
It's catch-22.

If the poor can get a home but not increase his income, he will lose the home, and he will be homeless again.

A homeless person doesn't have a mailing address.
Thus he can't create a bank account.
Thus he can't apply for a job.
Thus he has no income.
Thus he becomes poor.

A poor person has a house.
Thus he needs money to buy food.
Thus he sells his house.
Thus he becomes homeless.
Thus he ends up even poorer.

** Political economics
Political economics is economics with some political tinge.

Political ideals cannot escape economic reality.
Politicians cannot give everyone free lunch just by making it a law.

We tend to waste free things?

** Profit?
"An ethical justification of profit maximization"[fn::https://www.emeraldinsight.com/doi/abs/10.1108/17465681011079491?mobileUi=0&journalCode=sbr]?
What about environmental destruction?

How do we design a scalable incentive system that solves the tragedy of the commons?

If we require every business to restore the part of nature that they exploit, then no business can be profitable?

The problem of the tragedy of the commons is that the feedback is delayed.

Consider cattle farmers and a common grassland.

Traffic jams are also a tragedy of the commons.
Everyone exploits the road because it's free.

The same solution can be used to solve overfishing, pollution, climate change, etc..

What is the solution?
"Sometimes the best governmental solution may be to do nothing."
"locals have often come up with solutions to the commons problem themselves"
https://en.wikipedia.org/wiki/Tragedy_of_the_commons#Solutions

Profit maximization or hassle minimization?
Profit is the food a company eats to survive.
** Scrutinizing the law of supply and demand
The law of supply and demand can be derived from microeconomics with the assumption of rational actors.

Why does price rise when demand rises faster than supply does?
There are several possibilities:
- The supplier is psychologically overwhelmed and wants to reduce demand.
- The supplier is greedy.

Microeconomics gives rise to the law of supply and demand[fn::https://www.youtube.com/watch?v=PNtKXWNKGN8]
** Economic ecology
There is an intuitive connection between economy and ecology.

The idea of business ecology goes back to Moore 1996.[fn::https://en.wikipedia.org/wiki/Business_ecosystem]

Companies in an economy are like organisms in an ecology:
some companies consume the output of other companies, and produce another output that is consumed by other companies.
The economic development[fn::https://en.wikipedia.org/wiki/Rostow%27s_stages_of_growth] from agricultural to manufacturing to service
parallels the ecological succession[fn::https://en.wikipedia.org/wiki/Ecological_succession] from desert to grassland to forest.
The recovery of an economy after devastation parallels the recovery of an ecology after forest fire[fn::https://en.wikipedia.org/wiki/Fire_ecology].
There are pioneer companies, parallel to pioneer species[fn::https://en.wikipedia.org/wiki/Pioneer_species].

Which is more likely?
- Consumers feed companies money, in the same way masters feed dogs meat.
- Companies eat customers, in the same way fishes eat planktons.

The parallels:
- Organisms eat food to survive.
  Companies eat money to survive.
- pioneer species in biology ~ pioneer species in economics?
- ecosystem recovery after wildfire ~ economy recovery after war/disaster?
- fire ecology ~ war/disaster ecology?
- How does a community rebuild itself?

These help a species to thrive: lots of food, little competition, little predation.

Companies can fill niches, in the same way species occupy niches.
** How to be unbeatable: Have zero cost
If my cost is zero, no competition can beat me.

It is possible to have zero monetary cost and pure labor.
For example, farming.
** How did we arrive at such a shitty world?
Each individual has one billionth of the power, and everyone shares one billionth of the blame.
No single person is to blame, which means that no single person will fix it.
We're doomed.
* Prosperity without growth?
https://en.wikipedia.org/wiki/Prosperity_Without_Growth

https://en.wikipedia.org/wiki/Steady-state_economy

https://timjackson.org.uk/ecological-economics/pwg/
* Non-privately-owned capital?
Heads of bulls, cows, horses, pigs, chickens.

Capital multiplies labor efficiency.
Working a land with your hands vs working a land with N cattle.

Some examples of capital are tools.
* Work-leisure ratio
A man's time can be divided into two categories: leisure and non-leisure.
Leisure is everything that one would rather do.

Whether sleep is work or leisure depends on whether the person wants to sleep or not.
* Necessary energy expenditure as measure of poverty
By "necessary", I mean the absolute minimum required to sustain life.

I propose to measure one's poverty as /the amount of energy he expends to sustain his life/ (such as looking for food and performing vital activities).
The higher that energy is, the poorer he is.
Poor people spend more energy to sustain their lives than rich people do.

But effort is not energy.
One can be tormented and motionless, not spending significant energy, but exerting a lot of effort, for example when one has no money to buy food for tomorrow.
It seems that thinking harder does not consume significantly more energy although it may consume more psychological willpower.
* Bibliography
