#+TITLE: Understand economics
#+DATE: 2019-04-24 00:00 +0700
#+PERMALINK: /economics.html
#+OPTIONS: ^:nil toc:nil
* Human wants
** What do humans want?
The /root want/ of humans,
hardwired into them by evolution,
is to /survive and have fun/.
From that root want come all other wants,
such as to speed up things,
to do things with less effort,
and so on.

But this theory fails to explain /suicide/ and /crime/.
Suicide is the antithesis of survival.
Crime endangers the criminal's survival.

- Every human:
  - Has wants.
  - Has priorities? Utility function?
    - Non-constructive? It exists, but we don't know what it is?
  - Acts to satisfy those wants.

Counterexamples? Where the theory breaks down?

- Thiefs want something more than freedom?
  - But both of the stolen thing and the freedom will be taken away?
- Smokers and junk food eaters don't want health?
  - Everybody wants health?
    - But doesn't behave consistent with wants?
      - Cognitive dissonance?
        - Want health later or health now?
        - Addiction?
          - Physical changes to the brain?
** Why did we evolve boredom?
What is the evolutionary advantage of boredom?

Boredom drives the desire of newer and better ways to do things.

Boredom, curiosity, and fear improve survival.

Cautious curiosity improves survival.
* Basic economics
** What is economics?
/Economy/ is household stewardship.[fn::https://www.etymonline.com/word/economy]

/Economics/ studies how we should satisfy our wants.

Economic system[fn::https://en.wikipedia.org/wiki/Economic_system]?
** Utility, want, value, wealth, moneyfulness/pecuniosity
A thing is /useful/ iff it satisfies a /want/.

A thing's /value/ is its ability to satisfy wants.

useful = valuable

/Wealth/ is the sum of satisfied wants.

A farmer is /wealthy/, because he satisfies most of his wants;
but he is /impecunious/ (moneyless).

A person too busy working for a consulting firm is /pecunious/ (moneyful) but /unwealthy/,
because, despite having a lot of money, he is hardly satisfied.
He has enough money to eat delicious foods every day,
but he does not have the time.
** Price and value
/Price/ is the amount of money paid for value.

Do not conflate price and value.
** Price, pay, ownership, exchange, transaction
To /own/ something is to have exclusive access to that thing.

- /Exchange/ and /transaction/ are synonyms.
- An /exchange/ is an agreement
  - between two parties A and B in which
    - A gives X to B,
    - B gives Y to A.
  - If X is money and Y is not money, then:
    - X is the price.
      - /Price/ is the amount agreed for exchange.
      - /Price/ is something sacrificed to get something else.
    - A is the buyer.
    - B is the seller.
    - The buyer /pays/ the price to the seller.
** money and currency
- Money has /currency/ and /amount/ (/magnitude/).
- Money can be /exchanged/ with many other things.
** debt, interest, and price
- The price of debt is the /interest/
  (the amount of money that will be exchanged for obtaining the loan now).
  - An X market is a market where X is traded.
    - A money market is a market where money is traded.
      - How do you buy money with money?
** Land > Labor > Capital
- The /factors of production/[fn::https://en.wikipedia.org/wiki/Factors_of_production]
  in classical economics are:
  - land (everything that exists in the Universe, except labor and capital),
  - labor (human),
  - capital (tools).

Land creates labor.

Labor creates capital.

If capital is destroyed, labor can rebuild it.

If labor is destroyed, capital cannot rebuild it.

Labor without capital is inefficient.

Capital without labor is /nothing/.

However, without land, nothing would exist at all.

Therefore, land is more important than labor, and labor is more important than capital,

But it seems here that capital is revered, labor is disdained, and land is forgotten.

Money is not capital, but it can be used to buy capital, but this quote is related:
#+BEGIN_QUOTE
When the last tree is cut, the last fish is caught, and the last river is polluted;
when to breathe the air is sickening, you will realize, too late,
that wealth is not in bank accounts and that you can't eat money.

Alanis Obomsawin (b. 1932)[fn::http://quoteinvestigator.com/2011/10/20/last-tree-cut/]
#+END_QUOTE
* Productivity
** Productivity, output, production
Productivity is /output per input/.

Economically, /output/ is something satisfying a want.
For example, a machine produces goods, but it also produces heat, pollution, and waste,
but only the goods is useful to humans, and thus the goods is the output.

Production is a process of transforming /less useful/ things into /more useful/ things.
What is useful is determined by human nature, which is ultimately shaped by evolution.

Thus, productivity is the /efficiency/ of production.

Thus, productivity is the rate of addition of value.
** Where does the word "productivity" come from?
- productivity[fn::https://en.wiktionary.org/wiki/productivity] ← productive + -ity[fn::https://en.wiktionary.org/wiki/-ity]
- productive[fn::https://en.wiktionary.org/wiki/productive] ← prōductīvus
- prōductīvus[fn::https://en.wiktionary.org/wiki/productivus] ← prōdūcō + -īvus[fn::https://en.wiktionary.org/wiki/-ivus]
- prōdūcō[fn::https://en.wiktionary.org/wiki/produco] ← prō-[fn::https://en.wiktionary.org/wiki/pro-] + dūcō[fn::https://en.wiktionary.org/wiki/duco]

In 2019, "to produce"[fn::https://en.wiktionary.org/wiki/produce][fn::https://www.etymonline.com/word/produce]
means "to make".

"Productive" means:
- /related/ to producing
- /tending/ (having a tendency) to produce[fn::https://en.wiktionary.org/wiki/-ive]

"Productivity" means:
- the /state/ of being productive[fn::https://en.wiktionary.org/wiki/-ity]
- a /measure/ of someone's ability to produce
  (this definition parallels the definition of
  conductivity[fn::<2019-05-07> "Measure of a material's ability to conduct an electric current"
  https://en.wikipedia.org/wiki/List_of_physical_quantities] in physics)
  - http://www.thefreedictionary.com/words-that-end-in-ivity
  - https://en.wikipedia.org/wiki/Sensitivity_and_specificity
- In economics, productivity is output per unit of labor.
  [fn::http://www.thefreedictionary.com/productivity]
- "Productivity describes various measures of the efficiency of production.
  A productivity measure is expressed as the /ratio of output to inputs/ used in a production process, i.e. output per unit of input."
  [fn::<2019-05-07> https://en.wikipedia.org/wiki/Productivity]
  (emphasis mine)
** Why should we care about productivity and not only profit?
Productivity increases /wealth/.
Profit increases /pecuniosity/ (/moneyfulness/).

Productivity is /real/.
Profit is /nominal/.

Productivity is about /value/.
Profit is about /price/.

Productivity does not always mean profitability.
For example, a farmer may produce a lot of oranges, but when the demand for oranges is low,
he may not be able to sell his excess production for profit.
** What should be produced?
We should produce /goods/.
What is /good/ depends on which /moral system/ we subscribe to.

If we subscribe to /utilitarian/ ethics,
we should produce what maximizes the /total satisfaction of the population/.
However, an utilitarian is okay with killing 1,000 people to save 1,000,000 people.

Profit maximization is utilitarian?

If we subscribe to /hedonist/ ethics,
we should produce what brings us the most joy when we produce it.
** Examples of false or unwanted productivity
Examples of false productivity that feels good but only wastes time:
- Checking off lots of unimportant things from a to-do list.
- Sorting files and folders that we rarely use.

Productivity is about long-term profit.
Forced labor is productive only in the very short term.

Examples of unwanted productivity:
- Manufacturing as much hardware as possible with unacceptable defect rate.
- Writing as much software as possible with unacceptable unmaintainability.
** Consumption and satisfaction
People consume to satisfy themselves.

Consumption is the dual of production.

Satisfaction is the dual of quality.
*** Consumption is everywhere
Production is not exactly the opposite of consumption.
Production itself consumes some input to produce some output.
* Technology and productivity
** Software and wants
Interesting questions:
- What wants are satisfied by software?
- How does software satisfy wants?

Directly or indirectly.
- indirectly, by improving the productivity of an existing process
- directly, such as having fun, such as games
Game.
** What are the inputs of software production process?
- man-hour
- machine-hour
- electricity
** Software as goods and software as services
Software can be thought of as both goods and services.

In the goods view, an engineer produces software.

The goods view is somewhat strange:
Software can be /copied/ but not /moved/,
unlike physical goods which can be /moved/ but not /copied/.

In the services view, an engineer is a slave driver.
An engineer creates value by translating user wants into machine configuration.

** Where does software operation and maintenance fit in the big picture of productivity?
Once created, software has to be operated.
Software operation has costs.
** How does technology improve productivity?
Technology enables a person to control more things.
With bare hands, a person can control 10 kg.
With power tools, a person can control 100 kg.

- https://en.wikipedia.org/wiki/Productivity_improving_technologies

* Measure productivity?
** Is it practical to measure productivity?
What does it mean to measure productivity?

It is impractical to trace all the causal chains.

It is easy to compare factory worker productivity between such workers because:
- The causal chain is very simple and short.
- The interaction between factory workers do not affect each worker's productivity.
- The environmental factors (machines, lighting, etc.) are constant and identical for all workers.

A knowledge worker's productivity is affected by peer interaction.

In order to measure a programmer's productivity, he must first be isolated from everyone else.
But this isolation affects his productivity?

If both A and B are necessary causes of C,
then A or B alone is not sufficient to cause C.
Each of A and B is a causal factor (necessary but not sufficient).
The cause of C cannot be reduced to either A or B.
Both of them are necessary to cause C.
For example, in the fire triangle, all of fuel, oxygen, and heat are necessary to cause fire.
The cause of fire cannot be reduced to any strict sub-combination of those three factors.

Measuring producitivity requires understanding causality.

It is not as simple as blaming the proximate (the nearest) cause.
For example, suppose a smoker in a gas station causes an explosion.
The blame is /largely/, but not /entirely/ on the smoker,
because the smoker alone is not enough to cause the explosion:
the explosion requires gasoline vapor,
which is caused by the existence of the gas station,
which is caused by the demand for gas,
which is caused by other car owners,
and so on.
In the end, all of humanity shares a little blame, although negligible.
** When is line of code a valid measure?
Line of code (LOC) can be a valid measure if they are /normalized/ first,
like purchasing-power-parity adjustment in currency exchange rates.

One atomic statement per line.

LOC is valid for the same language with the same coding style.

1 LOC of C cannot be equated with 1 LOC of Java, in the same way we cannot equate 1 kilogram and 1 pound.
** Complexity points? Story points? Function points?
- What the hell are we trying to measure?
- What should we care about?
  We only care about /how long it takes to make/.
** What does a software engineer do?
- Find out what the user really wants.
- Formalize user requirements.
** How do we compare programmers/code?
- correctness of the system
- maintainability of the system
- efficiency of the system
- time taken to implement the system
** How do we measure developer productivity?
- 2004 article "Defining and measuring the productivity of programming languages" [[https://pdfs.semanticscholar.org/1852/9ff58460b6238f5095af073d8505d79d3264.pdf][pdf]]:
  - It defines these metrics:
    - "the time and effort required to write, debug, and tune the code"
    - "the performance of the code that results"
  - power-efficiency graph (human efficiency and machine efficiency)
  - what else?
- 2008 https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/Web/Planning/productivity.html
  - https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/
- 1992 article https://www.andrews.edu/~vyhmeisr/papers/progprod.html
- 2012 article http://www.drdobbs.com/jvm/the-comparative-productivity-of-programm/240005881
  - "A database comparing 6,000 projects shows that the choice of programming language has a significant impact on project schedule."

State of the art[fn::https://en.wikipedia.org/wiki/Programming_productivity]?

\cite{karimi2016links}
** What?
- 2015, PhD thesis, Bergersen, "Measuring Programming Skill: Construction and Validation of an Instrument for Evaluating Java Developers"
  - [[http://folk.uio.no/gunnab/publications/Bergersen2015_PhD_thesis.pdf][pdf]]
  - It's a collection of 4 articles.
  - https://www.duo.uio.no/handle/10852/48583
** Ideas?
** Quantity-quality output model
Output should be a function of /quantity/ and /quality/,
but perhaps not a simple multiplication.
If quality is too low, quantity does not matter, because no buyer wants it.
If quality is too high, it does not matter, because no buyer can perceive the quality difference.

What is /quality/?

The ability to produce, or the ability to /satisfy consumers/?
Producers don't produce for the sake of production.
Producers keeps producing because there is unsatisfied demand.

Aren't we putting too much emphasis on consumption?

Quality is an arbitrary number?
Subjective?

100 oranges at quality 20 vs 50 oranges at quality 40?

100 room-cleaning at quality 50 vs 50 room-cleaning at quality 100?

The output of a machine is defined by the machine's designer.

The output of a system is defined by the system's designer.

People always desire speed, easiness, simplicity, laziness, less effort, more joy, more fun, more chance of survival
** How do we measure the productivity of services producers?
The same way we measure the productivity of goods producers?
* Economics for business people
** Taxation
It suffices us to know that /taxation is protection racket/:
If we don't pay the racketeers, they will ruin us.
** Defining investing, trading, gambling, betting, wagering, insurance
*** Defining gambling
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/
*** How do we know something is not gambling?
**** If it's possible to be skillful, then it's not gambling.
*** What
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?" https://www.bbc.com/news/business-38905963
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
** Finance
- Economics vs finance
  - Economics is about value?
  - Finance is about money?

"Finance is a field that deals with the study of investments."
 [fn::https://en.wiktionary.org/wiki/finance]
 [fn::https://en.wikipedia.org/wiki/Finance]

- Loan-related jargon

  - A lender lends (gives) a loan to a borrower.
  - A borrower borrows (takes) a loan from a lender.
  - Loan is the amount.
  - Borrower (one who borrows) is the debtor (one who has debt).
  - Lender (one who lends) is the creditor (one who gives credit).
  - Lease vs rent?

    - Lease is more formal and long-term than rent.

      - [[http://www.businessdictionary.com/article/1063/lease-vs-rent-d1412/][businessdictionary.com]]
      - [[https://www.nolo.com/legal-encyclopedia/leases-rental-agreements-faq.html][nolo.com]]

- Currency-related jargon

  - The /price/ is the amount paid by the buyer to the seller.
  - What is currency?
  - What is money?
  - What is the difference between currency and money?

    - https://www.weusecoins.com/hidden-secrets-of-money-currency-versus-money/

      - "Currency is a medium of exchange, a unit of account."
      - "Money is [currency] plus a store of value over a long period of time."

  - What is legal tender?
  - What is cryptocurrency?
  - Is there such thing as "cryptomoney"?

- Securities

  - A [[https://en.wikipedia.org/wiki/Security_(finance)][security]] is a /claim/ to something.
  - An /exchange/ was a place (is a computer system) where things are traded (bought and sold).

    - The exchange requires /brokers/ because it was invented before computers.

      - Impractical: 1 million people on the trading floor shouting for a match.

        - But a computer can match 1 million trades in a second.

      - Nobody bothers making a new stock exchange.

        - Because of [[https://en.wikipedia.org/wiki/Network_effect#Financial_exchanges][network effect]].
        - But [[https://robinhood.com/][Robinhood]] is doing that,

          - but it's a broker, not a stock exchange,

            - but I hope they make buying stock as easy as ordering pizza online,

              - because if everyone uses the same broker,
                then the broker /is/ the exchange.

          - [[https://support.robinhood.com/hc/en-us/articles/202853769-How-Robinhood-Makes-Money][How Robinhood makes money]]

            - No trading fee.
            - $6 per month per person who uses Robinhood Gold; otherwise none.
            - In 2017, Robinhood had 2 million users ([[https://techcrunch.com/2017/04/26/robincorn/][techcrunch.com]]).

              - How many of them use Robinhood Gold?

                - How many people have margin account compared to regular account?

                  - I guess 1:100.

              - How many employees do Robinhood have?

                - 30 ([[https://www.owler.com/company/robinhood][owler.com]])

              - Does that make sense?

                - My estimate:

                  - Their revenue:

                    - $60,000 per month = $720,000 per year.

                  - Their expenses:

                    - $300,000 per year for employees.
                    - ? for stock exchange chairs.
                    - ? for building leases.

                - Yes, it makes sense.
                - Are customers "mercy-buying" because they think Robinhood is too cheap (compared to old-school brokerages)?

                  - [[https://www.stockbrokers.com/guides/features-fees][stockbrokers.com: 21 Most Common Online Broker Features & Fees]]
                  - Comparison: In Indonesia, stock trading cost is about 0.02% of trade value.

    - A stock exchange starts out trading stocks,
      but after some time it begins trading other securities,
      but the name has stuck.

  - A /bond/ is a securitized loan?
  - Every asset can be securitized?
  - Stock

    - /Stock/ is company ownership.
    - A /share/ is a fraction of stock.
    - Buying share means buying partial company ownership.

- Undigested information

  - [[http://noahpinionblog.blogspot.co.id/2013/01/how-much-value-does-finance-industry.html][Noahpinion: How much value does the finance industry create?]]
  - Investing, speculating, or gambling?

    - Slap some "math" on gambling masquerading as "investing", and suddenly it looks legit.
    - "Modern investing: gambling in disguise", David Schneider
** Use the economic/financial system to centralize power?
What are we trying to do?
- Understand how to make the system works for us instead of making us work for the system.

Sam Altman puts it concisely: "You get rich by owning things."[fn::http://blog.samaltman.com/how-to-be-successful]

Why do we get rich by owning things?

Because we can ask the police to violate whomever violates our ownership
(unless the perpetrator is the government itself).

Respecting private property enables the accumulation of wealth and the ensuing economic inequality.

Inequality is not poverty.[fn::https://fee.org/articles/stop-conflating-inequality-with-poverty/]

Poverty, not inequality, is the problem.

We have several choices to reduce inequality:
- Embrace capitalism:
  Make everyone own properties and educate everyone to spend money wisely.
- Oppose capitalism:
  Steal from the rich, give to the poor, although this incentivizes poverty.
  Abolish private ownership.
  But isn't this envy-based politics?

But why should we reduce inequality?
It is poverty that we should reduce, not inequality.

Of course some poverty is due to bad luck,
and we should help people who fall into poverty due to bad luck.
But too many entitlement programs are trapping people in poverty.

It is up to us whether we want to find ways to own properties.
*** What is a company?
A company is a /legal fiction/ for concentrating wealth (economic power) to its shareholders.
Such economic power often translates to other forms of power such as political power.

A company is rife with /principal-agent problems/ and /conflicts of interest/.
There is one principal-agent problem between the shareholders and the directors.
There is another principal-agent problem between the directors and the employees.
There is one principal-agent problem for each layer of management.

It is a physically impossible to build or hurt a company.
A company cannot do anything.
People do things.

A company is an abstract object with concrete consequences.
The legal fiction is unreal.
The environmental effects are real.
*** What is "economy"?
What is "economy"?
What is "economy" in "economic meltdown"?

Exchange?
Trade?

Satisfy maximum wants using minimum resources.
There are two solutions:
- Reduce wants.
- Use more resources.

Economics is easy to explain but hard to predict.
Economics is too interconnected.

Demand/consumption is easy; supply/production is hard.

/Demand is easy./
We can want anything.
Changing our minds is free.

/Supply is hard./
We have to work to satisfy our demands.

Consumption is easy.
Production is hard.
Destruction is easy.
Creation is hard.
Second law of thermodynamics: The entropy of the Universe never decreases.
In nature, entropy never decreases.
Disorder arises naturally.
The second law of thermodynamics explains why consumption is easier than production.

The nature of economics is that demand is free, but supply is costly..
Changing demand is cheap: you just change your mind.
Changing supply is costly: all the infrastructure that has been built won't simply turn back into cash.

Demand first or supply first?
Human nature is the root cause of economic demands.
There will always be demand for food and shelter.
There is always demand to make life easier and less boring.

However, in the case of iPhone, we have two views:
- Steve Jobs's presentation causes people to want iPhones. Supply creates demand.
- People always want an easier way to live. Steve Jobs's iPhone just happens to make people's lives easier.

For example:
We want an easier way to live.
People don't want iPhones for iPhones's sake.
People want iPhones because people believe iPhones make people's lives easier.

If demand surges, it will collapse later.
Example: tulip mania.
*** Economic recession
Economic recession is the reduction of money flow velocity.

How do we predict recession?
How do we measure and monitor money flow velocity?
- people savings balance
- mass layoffs
- mass price hikes for vital goods (oil?)
- company profit/loss statements
- money accumulates at few economic actors

Technology introduction, demand shift among substitute goods:

A demand shift is a demand collapse and a demand surge.

Cheaper robotic workers (or increasing minimum wages) causes demand for human workers to collapse and demand for robotic workers to surge.

Demand shifts among substitute goods.
*** Fluid dynamics explains economic recessions
Economic recession happens because money flow slows down.

Money is a fluid.
A fluid flows.
Fluid flow velocity depends on pressure at the source and resistances in the path.

If we want to maintain flow velocity despite increasing resistance, we have to increase pressure at the source of the fluid flow.
But do we want this?

Money flow slows down because people spend less.

People spend less because they have less discretionary income.

People have less discretionary income because they are fired, or governments raise taxes, or important things get more expensive, etc.

Assumption:
A person's behavior changes slowly, if it changes at all.
A person who has never cared about the environment will not suddenly care about the environment.

A recession has two possible direct causes: /demand collapse/ or /supply collapse/.

Examples of supply collapse:
- Mine collapse, oil rig explosion, etc.
- Disasters: fire, earthquake, tsunami, flood, volcanic eruption, etc..
- Lots of people going out of workforce at once (into pension, dying in war, etc.).
- Lots of people suddenly becoming conscious (Google workers demonstrating for transparency, etc.).

Examples of demand collapse:
- Bitcoin ran out of fools (greater fool theory).
- Renewable energy sources reduce oil demand.
- Young people adopt a minimalist lifestyle after realizing that consumerism is unsustainable.
- Government increases minimum wage big enough to make switching to robots looks cheap.
  Lots of companies introduce robot workers at the same time, making human workers redundant.

Supply collapse is caused by physical destruction.
Demand collapse is self-inflicted human condition.

Consumers supply demands to producers.
Consumers demand supplies from producers.
Take and give.
To demand is to take, to consume, to destroy.
To supply is to give, to produce, to create.

What does inverted yield curve has to do with recession?
What does time preference have to do with economic recession?
What is an economic recession?

CAGR = compound annualized growth rate.

What is the yield of a bond?
A bond's yield is the CAGR of the bond price.

What is the yield curve?
The yield curve is the curve in a plot with two axes: the horizontal axis is tenor (duration to maturity), and the vertical axis is yield.

An inverted yield curve indicates that buyers are pessimistic about the bond's future?
*** Currency? Free banking? Digital fiat currencies?
Piggyback nascent fintech/e-cash/e-money startups?
BTPN Jenius?

https://openbazaar.org/blog/trust-is-risk-a-decentralized-trust-system/
Currency requires trust.
Debt requires trust.
Transaction requires trust.
Business requires trust.
What is trust?

A trustworthy person refrains from exploiting vulnerabilities.
Trust is the assumption that the other party refrains from exploitation.
Trust is the assumption of the absence of betrayal.
Betrayal is the exploitation of trust.
(Problem: Circular definition.)
*** Economic crisis is discontent due to reduction of purchasing power.
A /crisis/ is a mass discontent.

An /economic crisis/ is a mass discontent due to mass reduction of purchasing power.

"A financial crisis is any of a broad variety of situations in which some financial assets suddenly lose a large part of their nominal value."
 [fn::https://en.wikipedia.org/wiki/Financial_crisis]

- High firing rate, high unemployment, unemployed people having genuine difficulty finding jobs, employers not willing to employ
- Greatly reduced demand (discretionary spending)
- Reduced purchasing power
*** Economics of open-source
https://en.wikipedia.org/wiki/Open-source_economics

Where do we draw the line between open core and crippleware?
- https://en.wikipedia.org/wiki/Open-core_model
- https://en.wikipedia.org/wiki/Crippleware

Is "open core" just an euphemism of "crippleware"?

If the open core is actually useful, then it isn't crippleware.
http://blogs.collab.net/subversion/enough-of-this-open-core-confusion

Marginal cost is the change in opportunity cost due to increasing production quantity by one.
https://en.wikipedia.org/wiki/Marginal_cost
*** Understand how capitalism centralizes power
Capitalism is:[fn::https://en.wikipedia.org/wiki/Capitalism]
1. the /private ownership/ of means of production,
2. the operation of such means /for profit/.

What?
- http://www.visualcapitalist.com/
- Capital is everything that is not labor?
- Capitalism is capital above labor? Communism is labor above capital?
- Example of low-capital high-labor:
  - small and medium enterprises (SMEs)
    - food stalls
    - home bakeries
    - art freelancing
  - research in pure mathematics
*** Companies must extract value to survive
- A profitable company must extract more value
  from its employees than it pays its employees.
  - People create value. People in a company create value. Human labor creates value.
    Companies aren't human. Companies can't work. It's the employees who work.
  - But if the employees weren't in the company, they might create less value.
    The company might be a place where the employees can create more value for society.
*** "Investing"
What Bitcoin "investing" is:
- You buy a certificate of environmental destruction from someone, probably a "miner".
- You expect a greater fool to buy that certificate from you at a higher price.
  There are millions of other people who are looking for someone else more stupid than them.

Bitcoin is massive wealth transfer from late buyers to early buyers.
All financial investing is massive "realistic-return" Ponzi scheme.
Exactly fits the definition.
Newcomers pay oldtimers.
Late buyers pay early buyers.

Bitcoin is not necessary at all. It is pure want.
Inflation target disincentivizes currency hoarding.
A deflating currency encourages currency hoarding and discourages real spending.
https://www.cmegroup.com/education/featured-reports/an-in-depth-look-at-the-economics-of-bitcoin.html

https://www.theguardian.com/technology/2018/nov/05/energy-cost-of-mining-bitcoin-more-than-twice-that-of-copper-or-gold
*** Economics, price, quality
Price is not important in itself.
It is the quality-price trade-off that is important.
People don't buy shit even if it's cheap, even if you pay them to buy it.

For an increment of quality, people are willing to pay an increment of price.
But there is a "good enough" point where people are satisfied and they just look at the lowest price.

Negative price means willingness to pay to get rid of something.
Example: rotten vegetables has negative price to most people, but positive price to farmers.
*** Economics?
We should measure debt-to-income ratio instead of debt-to-GDP ratio?

Consumptive debt sacrifices future for the present.

Productive debt is good.

Example of productive debt:

Suppose that you want to buy a land to farm on it. These are the scenarios:
- You work for 20 years. Then you buy the land with cash. But the land price has risen.
- You take a loan, buy the land now, and repay the loan over 10 years. In the second year, your land starts producing.

If a person takes too much consumptive debt, he goes bankrupt.

If a government takes too much consumptive debt nominated in its own currency, it can print money to repay the debt, but such printing devalues the currency.

If the US continues to take loans mindlessly, it will have to choose:
- Default (refuse to repay).
- Suffer severe inflation (rising prices), if the creditors spend the printed money.

Does the USA think it can get away by refusing to repay its debts? It will trigger a huge power shift, maybe to China. Will China sacrifice itself to clean up America's mess? Will China buy up all US debts, and use the default as a reason to start a war?

https://deviantinvestor.com/9778/sacrificing-future-spending/

https://en.wikipedia.org/wiki/Unearned_income

Everything comes from nature.
We are not creating or destroying anything.
We are merely transforming things.
At least as seen from physics.

The number of atoms in Earth doesn't change.
(But what about solar wind? It does change a bit?)

Urban toilet harms humans and the Earth.
- We should poo squatting, not sitting.
- Urine and feces should be composted, not flushed down the drain.
- Compost bins should replace septic tanks.

https://www.vice.com/amp/en_us/article/zm95ka/republicans-are-outraged-about-the-deficit-they-caused

https://en.wikipedia.org/wiki/Unrestricted_Warfare
*** There are only two ways to get rich: earn or steal
There are only two ways to get rich: /earn/ wealth or /steal/ wealth.

Earn wealth: convince people to give you money, by selling them things that improve their lives.
Use the money to develop your wealth even more.

Or steal wealth: An investor steals a little wealth from each person who does not invest.

After you obtain enough wealth, develop it, but don't lose all of them.
** Understand the causal chain of profit
The direct cause of profit is the ability to sell something at a price higher than its production cost.

Why is that?

Why is a working car more valuable than a broken car?

From neuroscientific point of view, people buy because of dopamine?

Patrick Anderson has an interesting idea:
"the origin of profit is the consumer's lack of ownership in the means of production"
 [fn::http://postgrowth.org/how-on-earth-flourishing-in-a-not-for-profit-economy-by-2050/].
** negotiation, price-taker, price-maker, BATNA
- Negotiating parties often have asymmetrical bargaining power.
- The price-taker is the weaker one.
- The price-maker is the stronger one.
- When negotiating, we want to know the BATNA[fn::https://en.wikipedia.org/wiki/Best_alternative_to_a_negotiated_agreement] of each party
** Understand money
*** Money as seed and human as soil
We can think of money as seed and human as soil.
Some humans are fertile soils for money to grow.
A poor person who wins a lottery soon loses all of it.
A rich person who wins a lottery keeps getting richer.
A fool and his money are soon parted.
However, this way of thinking puts money first and human second.

We can think of how fast money flows through a person.
*** Money as people's way of voting for what they want
Money is a way for people to vote for what they want.
People vote with their money.

Money is the consumer's vote for what producers should do.

Money is the people's vote for what companies should do.
*** Money as fluid
*** Money as blood
Economic actors are the organs, and money is the blood.
*** Money is valuable due to higher-order belief
People believe that money is valuable because they believe
that others also believe that money is valuable.

The value of money depends on whether there are people nearby willing to accept it.

Money has no inherent value.
We attach value to money.

It's the same:
Words do not have inherent meaning,
We attach meaning to words.

It's all convention that enables us to exchange.
Language enables the exchange of ideas.
Money enables the exchange of goods.

Related: Keynesian beauty contest[fn::https://en.wikipedia.org/wiki/Keynesian_beauty_contest]
** Sell what we would buy?
One thing is almost certain:
If I want something, there is very likely someone else who also want it among all 7 billion people on Earth.
Thus, /we should sell what we would buy/ because:
- We understand what we buy and why we buy it, so we can explain it.
- Our buying demonstrates that the market exists.
- We know how to sell that thing,
  because the buyers are similar to ourselves.
* What?
** What is the best economic system?
What is the economic system that satisfies the most wants?

Gift economy?
Tribalism?

Capitalism is utilitarian?

Overproduction is waste.
When the production exceeds wants.
People are saturated.
It may be wasteful if everyone produces the same thing,
because there would be an overproduction.
** How much money should be in circulation?
** Measure the economic success of a country
We should measure the /statistical distribution/ of the living standard, not the GDP (gross domestic product).
We do not want to /flatten/ the distribution.
We want to /shift/ the distribution toward higher living standard.
We want to improve the poorest people without stealing from the rich.
** Evolution of economic systems
*** Pure-labor economy in hunting tribes
All labor, no capital, no money.

Resources are allocated according to kinship:
- The hunters get to eat first.
- The families of the hunters get to eat next.
- Other people in the tribe get to eat whatever that remains.
*** Sedentary agricultural societies
*** Physical machines and the Industrial Revolution
*** Mental machines and the Information Age
** Irrelevant abundance in the 21st century
There are so many things in this world that we do not want or do not care about.
We are living in an age of /irrelevant abundance/.
* Bibliography
