#+TITLE: On energy, work, and power
#+DATE: 2018-04-11 04:00 +0700
#+PERMALINK: /energy.html
* Energy, work, and power, in physics
Energy is the ability to do work.
 [fn::<2019-10-28> https://home.uni-leipzig.de/energy/energy-fundamentals/01.htm]

/Work/ was defined as weight lifted through a height,
by Coriolis in 1826 \cite{coriolis1829calcul}[fn::<2019-10-28> https://en.wikipedia.org/wiki/Work_(physics)],
when it was common to use steam engines to pump water out of flooded mines.

When were the modern notions of work and energy created?
 [fn::https://hsm.stackexchange.com/questions/414/when-were-the-modern-notions-of-work-and-energy-created]
Helmholtz 1847?
Coriolis 1826?

There is a proportional relation between
the amount of work that such engine can do and the amount of fuel supplied to the engine.
Thus we say that fuel contains energy,
and we say that an engine converts such energy into work.

Energy density is of interest to vehicle designers,
especially when designing fuel and batteries.
Higher energy density means easier storage and transport,
but it can also mean bigger explosions in case of accidents.
* Energy?
/Energy/ is the amount of work that /could/ (potentially) be done,
whereas work is what /is/ (actually) done.[fn::Nick Lucid's "What the HECK is Energy?" https://www.youtube.com/watch?v=snj1wBtn6I8]

That makes me think: Why is some of that potential not actualized?

Energy is relative to observers?

Energy is a mathematical concept and not a physical reality?
Can a mathematical quantity be a physical reality?
Is Platonism true?[fn::https://en.wikipedia.org/wiki/Max_Tegmark]

For example of a conversion from potential energy to kinetic energy, observe a stone that is rolling downhill.

"Work" readily generalizes from only weights to every /force/, because weight is just a gravitational force.

What if the force and the displacement make an angle?

Mathematically, we say that the amount of work \( F \cdot h \) is done by lifting a weight \(F\) so that its height increases by \(h\).
 [fn::https://en.wikipedia.org/wiki/Work_(physics)]

/Energy/ is the ability to do work.

History of energy?[fn::https://en.wikipedia.org/wiki/History_of_energy]

/Power/ is work done per unit time: \( P = W / t \).[fn::https://en.wikipedia.org/wiki/Power_(physics)]
This means that a steam engine with twice the power
will clean the same mine in half the time.
* Generalization
Work can be generalized to mean any result we desire, and energy can be generalized accordingly;
the only constraint is that they are measured in the same unit.
* Power in physics and politics
** Political power as a special case of physical power
Political power is ultimately the ability to harm.

Physical power is also the ability to harm.
For example, you can give a man one gigajoule in any form, but his fate depends on your /power/, that is,
your rate of energy transfer, how fast you give him that much energy.
If the rate is one milliwatt and the transfer is unfocused, he will be fine for a long time.
If the rate is one gigawatt, he will soon perish, regardless of the form of energy;
one gigajoule in any form will annihilate a man if transferred instantly.[fn::<2019-10-28> https://en.wikipedia.org/wiki/Orders_of_magnitude_(energy)]

Indeed political power only exists as far as it is backed by physical power.

Therefore, political power is a special case of physical power.
** Measuring political power in units of physical power
In the previous section, we have shown that political power is a special case of physical power.
That means we should be able to /measure political power in watts/, or any other unit of physical power.

Perhaps it takes the same amount of time for both a bullet and a punch to transfer their kinetic energy,
but the bullet has more energy to begin with, and thus more power (higher transfer rate of energy).

Here is a comparison.
A bullet's kinetic energy as it leaves the gun muzzle is about a few thousands of joules.[fn::<2019-10-28> https://en.wikipedia.org/wiki/Table_of_handgun_and_rifle_cartridges].
One kilogram of TNT releases about 4 million joules when it explodes.[fn::<2019-10-28> https://en.wikipedia.org/wiki/TNT_equivalent]
* Bibliography
