#+TITLE: A simple solution to the English singular gender-neutral pronoun problem
#+DATE: 2019-08-14 00:00:00 +0700
#+PERMALINK: /english-gender.html
I propose one tiny change to the way we interpret English:
We declare that "it" can refer to everything, including humans,
and we should use "it" instead of "he" and "she",
unless when knowing genders is useful.
After all, we have been using "he" and "she" for all sorts of moving things like
cats, dogs, hamsters, horses, cows, pigs, cars, boats, and who knows what else.

The problem with English is not only gender prejudice, but also /anthropocentric prejudice/,
because it reflects the society that created it,
the society of England in the middle ages.
In the 21st century, we should not even assume that English is used only by humans,
because English is also used by machines.

My solution requires only changing our attitude, not inventing any new words, so it should not offend anyone's taste.
However, although the change is minimal, it may be painful for some people,
because they are under the delusion that humans are special,
although it may benefit them to know that the Universe does not give a damn about humans;
it might someday hurl a giant space rock at humans, and it could not care less if everyone died.

Anyway, it takes only one generation, about twenty years, for the change to feel normal.
It may feel strange to us, but it will feel normal to our kids.

My proposal is easy; humanity has made much harder changes.
The French people changed their measurement system from imperial to metric.
The mainland Chinese people changed their writing system from traditional to simplified.
If humanity could do things that hard,
then surely humanity could do something much easier.
