#+TITLE: Toward a curriculum for esoteric science
#+DATE: 2019-11-28 00:00:00 +0700
This page was last updated on <2020-01-21>.

This is mostly a list of phenomena whose explanation would advance science.
* Terminology
- SPM = Single-Pointed Meditation
- UAP = Unidentified Aerial Phenomenon
- CE = Contact Experience / Close Encounter
* Summary
** Observations to be explained
- Schild et al. 2018 \cite{schild2018beyond}: comprehensive contactee surveys
- Medhus & Medhus 2015 \cite{medhus2015my}: properties of spirits
- SPM and CE /distort/ the experiencer's time perception in the /opposite/ way.
  - After SPM, one is surprised that /much/ time has passed.
  - After CE, one is surprised that /little/ time has passed.
- Most meditators and contactees become less egoistical and more loving.
- Spirits can emit /photons/.
  - Why are they seen in photos but unseen by the naked eye?
    Is the eye not more sensitive than the camera?
    Or is it about the frequency?
  - What is the frequency of the photons?
  - What is the intensity of the light?
- Anomalous perception
  - Channelers (mediums) say things they supposedly cannot know.
  - Precognition
  - Telepathy (thought transference)
- Non-local perceptions
  - Remote viewing
** Hypothesized explanations
- (Insufficient observations?)
- Concepts:
  - perceived speed of time
  - aperture of focus
  - amount of consciousness
  - big aperture = low focus = low consciousness?
- Hypothesis: The perceived speed of time is /inversely related/ to the amount of consciousness.
  - Predictions:
    - We feel time passing faster when we sleep.
    - We feel time passing slower when we are hyperfocused (e.g. on pain).
    - The perceived speed of time is inversely proportional to the amount of new information?
    - Null-meditation (/not/ focusing on anything) /decreases/ consciousness?
    - Single-pointedness meditation (/focusing/ on something) /increases/ consciousness?
    - In both cases of meditation, one becomes unaware of his body.
    - UAP encounter increases consciousness (makes one hyperaware).
    - Consciousness is the speed of time?
- Hypothesis: The material body /interferes/ with consciousness.
  - The material body does not generate consciousness.
  - Explains: Perception without material senses.
- Hypothesis: Poltergeists are the victim's own unconscious psychokinesis; ghosts are earthbound human spirits?
  - Poltergeists haunt people; ghosts haunt places?
    - Poltergeists follow people; ghosts stay at places?
    - A poltergeist doesn't change victim?
* Details of observations
** Distorted time perception, meditation, and aliens
- SPM: Sadhguru did not realize that he had been sitting for some days.
  (But what type of meditation did Sadhguru do?)
- CE: Some people felt that they spent days in "matrix" reality,
  but when they came back, their friends said that only a few minutes had passed.
  (But how the hell do they know how many days they spent in "matrix" reality, if there are no watch and no sunrise/sunset?)
- missing time and missing distance[fn::<2020-01-21> https://mysteriousuniverse.org/2013/05/strange-cases-of-missing-time/]
- Mainstream neuroscience observations
  - <2020-01-21> https://www.huffpost.com/entry/slow-down-time_n_3567218
    - "By paying attention and actively noticing new things, we can slow time down."
    - <2020-01-21> [[https://www.eagleman.com/blog/brain-time][David Eagleman]]
      - "different types of sensory information (auditory, tactile, visual, etc.) are processed at different speeds by different neural architectures"[fn::<2020-01-21> https://en.wikipedia.org/wiki/Time_perception]
    - Burkhard Bilger? "Time can warp when our brain receives much more or less input than usual in a three-second span.
      (For example, time slows down when you are about to crash your car, but you can easily lose a whole day watching things on YouTube.)"
    - Habituation promotes ignorance, automates processing, and decreases consciousness? Surprise/error minimization? Energy-based learning?
  - <2020-01-21> https://buffer.com/resources/the-science-of-time-perception-how-to-make-your-days-longer
    - "When familiar information is processed, this doesn’t take much time at all. New information, however, is a bit slower and makes time feel elongated."
  - Information/sensory overload in Asperger/autistic people?
** Perception without material senses
- People born blind can see during near-death experiences.
  - People can see without brains/eyes.
    - People born blind can see during NDE.[fn::<2020-01-23> https://www.near-death.com/science/evidence/people-born-blind-can-see-during-nde.html]
      - If so, then /it should apply to all senses/.
        People born deaf should be able to hear after they die.
      - Grof & Grof [[https://www.consciouslifestylemag.com/non-local-consciousness-and-the-brain/][excerpt]].[fn::<2019-11-27>]
      - If blind people can do that, then myopia should be a trivial obstacle.
      - Seeing without eyes is not crazy if you already know remote viewing.
      - Also see Katharina Friedrich's "seeing without eyes"
        [fn::<2019-11-27> https://seeingwithouteyes.com.au/dr-katharina-friedrich/]
        [fn::<2019-11-27> https://seeingwithouteyes.com.au/]
        ("Sehen ohne Augen").
        Are there English videos?
        What are her experiments and theories?
      - Google search: blind people can see after they die.
- Veridical OBEs (out-of-body experiences).
** Properties of spirits
- Understand main sources
  - Instrumental Trans-Communication (ITC)
  - Accounts of discarnates via translator mediums
- Medhus 2013
- Infer the properties of spirits from Medhus & Medhus 2015 \cite{medhus2015my}.
  - Spirits can go/be anywhere in a blink just by thinking/willing.
  - Spirits can increase their probability of being perceived by changing their appearance to one that resonates with the recipient.
    - Spirits do everything, including changing their form, by willing/thinking/wanting.
  - A spirit has identity and a sense of self, a boundary, very much as an incarnate knows what is part of his body and what is not.
    It's just harder for spirits to manipulate materials.
  - He "could split off and be in multiple places at the same time, and it happened naturally, like breathing when I was alive". (p. 55)
  - "The weird thing is that if there were twenty people talking about me, those twenty conversations came right to me all at once,
    even if they were talking about me to somebody else. Not only did I hear everyone’s inner thoughts but I also /felt/ their emotions"
  - It seems that we can "connect to" or "touch" (send a message to) a spirit just by thinking about it.
    How does the other direction work?
    It seems spirit induce/plant thoughts/feelings when our mind is quiet?
- Spiritual photonics
  - Spirits can show themselves as orbs in camera photos. \cite{medhus2015my}
  - Spirits can increase photon detection rate in a photomultiplier (sensitive apparatus that can detect single photons). (Schwartz)
- We have misunderstood death.
  We should call it "shedding" instead.
  It is not the end.
  Dead people simply /shed/ their bodies.
  They still exist, but our brains/bodies interfere with communication.
- Schwartz 2016 \cite{schwartz2016nature}
- photomultiplier \cite{schwartz2011sacred} \cite{schwartz2010possible}
- experiments \cite{schwartz2012consciousness}
- He coined the term "postmaterial person".
- The SoulPhone, devices for spirit communication: Gary E. Schwartz et al. at [[https://www.thesoulphonefoundation.org/][The SoulPhone Foundation]]
- The [[https://www.thesoulphonefoundation.org/][SoulPhone]]: "An Evidence-Based Technology for 'Spirit' Communication"
- Sonia Rinaldi; more than 30 years of research, as of 2019; ITC, electronic voice phenomenon (EVP), etc.
  - Why does ITC seem to be particularly big in Brazil?
- via [[https://www.youtube.com/watch?v=54ikzd8SQGI][Affirmations, New Thought, and Beyond with Darryl Robert Schoon]]
  - Is "A course in miracles" a curriculum?
  - "Right use of will"?
- Julie Beischel (Windbridge)
- Dean Radin & Helané Wahbeh (IONS), etc.
- Windbridge Institute and Windbridge Research Center are two different things.
* High-strangeness events while meditating
- https://www.wildmind.org/mindfulness/three/odd-experiences-in-meditation
- How to meditate? https://www.lamayeshe.com/article/developing-single-pointed-concentration
- How to meditate?
  - Most of the time, we direct our attention outwards: we direct it at something we are seeing.
  - Try to direct our attention inwards.
  - How can we see something while directing our attention inwards?
    - Can we turn our eyes 180 degrees back?
    - But we can feel our heart beat?
- Absorbed inwards or expanding outwards?
  - If separation is an illusion, then being absorbed inwards and expanding outwards are the same?
- What exactly do we intend to achieve in meditation? https://www.swami-krishnananda.org/disc/disc_336.html
* Need elaboration
** FREE, contact modalities, quantum hologram hypothesis, Mitchell et al.
- video: [[https://www.youtube.com/watch?v=5Ckk8xO_wbE][Contact Modalities with Reinerio Hernandez]]
- book: "Beyond UFOS. The Science of Consciousness. Volume 1" \cite{schild2018beyond}
- https://www.consciousnessandcontact.org/
** CE-5 protocol for summoning aliens?
- Hynek CE-n close encounter classification https://alien-ufo-research.com/ufo-sighting-classification/
- https://www.ce5texas.com/ce5-contact-protocols.php
- https://www.ce5texas.com/meditation-primer.php
- https://www.reddit.com/r/UFOs/comments/8v8ia5/are_the_csetice5_protocols_a_legitimate_way_to/
- http://www.ufowatchdog.com/steven_greer.htm
* Mediumship? Channeling?
- Understand that mediumship is learnable.
  - Alan Hugenot.
* Abilities?
- Patanjali's yoga sutras, siddhis.
- Meditate; see [[file:meditate.html][meditate.html]]?
- Remote-view something.
- Do not run away from uncomfortable emotions, but /meditate on them/, and you will find their root cause.
  For example: sometimes envy, lust, and sloth arise in me.
  Note the language: "I envy" vs "envy arises in me".
  - In meditation, we ask the question, and then we quiet our mind and wait for the answer.
    The answers do not have to come in a language.
    Some memories may arise.
- Thoughts and feeling are the language of spirits?
  But the brain interferes with its habits, its programming, its memories?
  - Spiritual signals are much weaker than material signals; we must be very quiet and sensitive.
    - Why do spirits seem so weak? Or are they actually strong?
      Because E = mc2: a piece of matter is /a lot/ of congealed energy?
      If spirits gain more energy, they congeal into matter?
* Gary Schwartz and spirit communication technologies
[[https://www.drgaryschwartz.com/][Gary Schwartz]] has done lots of experiments about spirits, afterlife, and healing.

The papers are on his website.

Plant leaves emit photons? \cite{creath2005biophoton}

Gary wrote/co-wrote some books such as
and the 2014 book "Afterlife Communication: 16 Proven Methods, 85 True Accounts",
Schwartz 2011 \cite{schwartz2011sacred},
Schwartz & Simon 2002 \cite{schwartz2002afterlife},
and Schwartz 2007 \cite{schwartz2007god}.

There are also some videos of him on YouTube.

(via [[https://www.soulproof.com/soulphone-want-call/][soulproof.com]] on <2019-12-11>)

Discarnate scientists/researchers, and cooperating with discarnate beings in scientific experiments:

Interesting:
Google search result for "discarnate scientist" and "discarnate scientists" (both with quotes, for exact match).

We have found that the afterlife exists.
Now it is time to find out how to communicate with discarnate beings more efficiently.

Channelers can cooperate with people (spirits) in the afterlife for scientific research.

/We can ask discarnate beings to do some experiments and report the results to us./
Is it linguistically correct to say that a discarnate being is the /living remnant/ of a dead people?

If life does not require a body, what is life?

But first we have to know how to communicate with discarnate beings.

Perhaps "death" should be redefined to "disembodiment".
Instead of saying "he died", we say "he shed his body".
* Idea: Measuring the depth of meditation
The depth of meditation can be subjectively measured by the /rate of internal distraction/ (number of internal distractions per unit time).
For example, a newbie meditator may be distracted 20 times per minute,
and an expert meditator may be distracted 1 time per 15 minutes.
One internal distraction is one time realizing that one has been distracted.
External distraction does not always translate to internal distraction.
For example, when someone talks to me while I am reading an article, I may fail to respond to the other person.

The depth of meditation can be objectively measured by frequency analysis of brain waves?
* Hypothesis: Determining meditation correctness
We know we are focused at a single point if we become aware that it is all we are aware of,
and we become unaware of everything else, including our own internal bodily sensations.
* Other interesting current research topics
** Donald Hoffman's book "The case against reality"
Most of it \cite{hoffman2019case} (except the math) is obvious to me because I have already believed what the book tries to accomplish.

Where is the details of the mathematics of "conscious agent theory"?

(via [[https://www.youtube.com/watch?v=dd6CQCbk2ro][ZDoggMD]] on <2019-12-11>)
** Meditation, and advanced meditation?
Set a timer for 20 seconds.
Count how many times you realize that you lost focus.

Repeat.

Increase the timer to 30 seconds.

Increase to a minute.

And so on.

We can test: autonomous breathing rate below 9 per minute
(6 2/3 second per autonomous breath; a breath is an inhalation-exhalation pair),
[[https://www.youtube.com/watch?v=wKWt6FPXyxI][Sadhguru: If your breath drops down, you'll evolve into perceiving higher things!]]
Shinzen Young once told a story about Master Wuguang whose pulse is so weak that his doctor said "You're not alive!" \cite{young2016science}.

Cyclist idle breathing rate?
They don't experience psychic because they are not silent?

Toward enlightenment:

[[https://zenawakened.com/padmasambhavas-pointing-instructions/][Padmasambhava's pointing-out instructions]]

Ramana Maharshi's teaching is mostly in silence.
You sit near him, you let yourself be absolutely still, and you get something?
How does that work, and why?
*** Enligtenment language trap
If you read a lot, you will not be enlightened; you will only be an expert at speaking like an enlightened person.
The text is to guide a /practice/, not to be read, not to be intellectualized.
The language is a limitation; language cannot transmit experience.

I fell to the trap of intellectualizing enlightenment;
I tried to understand it, that is to create a mental model of it, not to know it, that is to directly experience it.
I was just feeding my monkey mind with words.
That realization enlightened me about enlightenment, but it did not enlighten me.

To learn to emote without language, watch silent movies.
But aren't body languages language?

To enlighten is to shine light upon, to dispel darkness, to dispel ignorance, to make someone see.
To be enlightened is to know.
To know what?
Everything.
*** To be enlightened is to be able to consciously leave the body (to bodily die just by will)
Conflicting details about Ramakrishna Paramahansa:
- [[https://www.youtube.com/watch?v=43Vt2dHdkCg][Sadhguru - enlightenment means you have broken the barriers of the physical]]
- https://groups.google.com/forum/#!topic/holy_trinity/97JlUmIQSnE
- https://en.wikipedia.org/wiki/Ramakrishna#Last_days

Which one is correct? None of them?
** Urge surfing
I got this via [[https://www.youtube.com/watch?v=m-OomGSciTY][Nir Eyal on Video Advice]],
but you should not watch that information-sparse clickbait-titled overlong video;
you should read [[https://med.dartmouth-hitchcock.org/documents/Urge-Surfing.pdf][Dartmouth--Hitchcock 3-page document]] instead.

It's interesting, although nothing new to Buddhists,
because urge surfing is a special case of mindfulness.
** Systems not goals
- [[https://jamesclear.com/goals-systems][Forget About Setting Goals. Focus on This Instead.]]: focus on systems/processes instead of goals.
** Other people's esoteric sciences
Rudolf Steiner's book "An outline of esoteric science"?

esoteric science? occult experiments?
http://www.kheper.net/essays/Esoteric_Science.html

Should all scientists meditate, so that they directly know?

Desda Zuckerman published her 2012 book "Your Sacred Anatomy: An Owner's Guide To The Human Energy Structure".
Is "spiritual anatomy"[fn::<2019-11-27> Spiritual Anatomy with Desda Zuckerman https://www.youtube.com/watch?v=e4xuBYfI0n4] a theory of psychic functioning?
It looks scientific: she did some tests, standardizations, and replications.
It started from her observations.

Its thickness is quite intimidating;
it took her decades to write, but I think it can be slimmed down,
or perhaps split into a few books, each with narrower focus.

She uses the scientific method: observe, hypothesize, experiment.
But the subject is her inner experience; how do we directly experience the inner experience of others?
* Basic definitions
"Esoteric" [[https://www.etymonline.com/word/esoteric][means]] "inner".

"Exoteric" [[https://www.etymonline.com/word/exoteric][means]] "outer".

They have nothing to do with secrecy or obfuscation.

/Esoteric science/ is the study of the mind.
Of course one can experiment with one's own mind using the scientific method.
The problem is everyone's mind is different,
so there are as many theories as there are people.

/Exoteric science/ is what most people mean when they say "science" in 2019.

"Normal" [[https://www.etymonline.com/word/normal][means]] "common".

"Paranormal" [[https://www.etymonline.com/word/paranormal][means]] "beside normal".
It means happenings not yet explainable by our common mental model.
What we call "paranormal" is normal to people who experience it daily.
Thus normality is relative.

The prefix "para-" [[https://en.wiktionary.org/wiki/παρά][means]] "beside", such as in
[[https://en.wikipedia.org/wiki/Arene_substitution_pattern][chemistry]],
the word [[https://www.etymonline.com/word/paragraph]["paragraph"]] ("beside-writing"),
and the word [[https://www.etymonline.com/word/parallel]["parallel"]] ("beside one another").

"Occult" [[https://www.etymonline.com/word/occult][means]] "hidden".
Or does it mean "concealed (intentionally hidden)"?

TODO: Define.

mystic, mysticism

magic (magick)

[[https://heterodoxology.com/2016/02/24/the-scholastic-imagination/][catapathic vs apophatic]]

An /entity/ is something that has an identity.
** Understanding is reasonably accurate modeling
To /understand/ something is to have a reasonably accurate /model/ of it.

X /understands/ Y iff X has a reasonably accurate model of Y.
* Overview of mind, brain, self, soul, spirit, consciousness
/Minds/ contain thoughts and feelings, as implied by our saying "What is in your mind?"
Synonyms: Latin [[https://en.wiktionary.org/wiki/mens#Latin][mens]], [[https://en.wiktionary.org/wiki/νόος][Greek]] [[https://en.wiktionary.org/wiki/nous][nous]].
"Mental" is the adjective that means "related to the mind".

/Brains/ contain brain matter.

/Soul/.
Greek psyche.

/Consciousness/ is the ability to ken.
For more explanation, see [[file:conscious.html]].

"Spirit" [[https://www.etymonline.com/word/spirit][means]] breath.
"Spirit" may also mean idea, essence, intention, or meaning, such as in "spirit of the law",
as opposed to "letter of the law", which is the mere appearance.
Greek pneuma.

* On minds and thoughts
What is the relationship between mind and thought?
Which are correct?

- Thoughts appear in minds?
- Thoughts enters minds?
- Minds create/generate thoughts?
- Minds receive/transmit thoughts?

My mind thinks. I do not think. So what do I do then? I merely exist.
How do I know I exist? Thought is not required.
But how can I know I exist if I cannot feel anything?
Without language, I can still know I exist; I will merely be unable to tell others.

Attention.
Focus.

Intention.

Expectation.
** Our surface experience of our minds
/Mind/ is what contains thoughts.
Mind is what thinks thoughts?

The /meaning/ of X for an agent A is A's mind's interpretation of X.

The meaning of X for us is our mind's interpretation of X.

Undefined terms: to /feel/, to /think/, to /experience/, to /remember/, to /recall/.

A /feeling/ is what is felt.

A /thought/ is what is thought.

To /infer/ is to reason according to a [[https://en.wikipedia.org/wiki/Formal_system][formal system]].
Inference is formal/syntactic manipulation, a strict adherence to some inference rules.
It does not involve semantics/meaning.

There are at least two kinds of thinking:
- thinking without language, such as imagining the a visual object or a sound; imagining something
- thinking with language, commentary, labeling, inference

Imagination.

To infer is not to assume.

Memory.

Undefined terms: time, past, present, future?

When a thought is bothering you, you can't erase it by trying not to think it;
you can only bury it with another thought or by not trying to thinking anything.
** Knowing our minds more deeply
[[file:meditate.html]]
** Enligtenment? Ego death?
Horgan 2017[fn::<2019-11-27> https://blogs.scientificamerican.com/cross-check/what-does-it-feel-like-to-be-enlightened/]:
#+BEGIN_QUOTE
And if you really experience nothing, how can you remember the experience? How do you emerge from this state of oblivion back into ordinary consciousness?
#+END_QUOTE

Does this [[https://hackspirit.com/ego-death-7-stages-to-the-obliteration-of-the-self/][ego-death attainment procedure]] work?
(From Google search "how to ego death without drugs".)

Possibly enlightenment?[fn::<2019-11-28> Enlightened Beings Share Their Awakening, Mystical Experiences https://www.youtube.com/watch?v=f54jAzYawZk]
Note that the subjects themselves do not label the experience as "enlightenment",
but apparently all of them at least experience temporary ego death.

Sometimes I imagine something so fun that I lost sense of time (1--2 hours had passed, whereas I think it was only 15--30 minutes).
Is that ego death?
But I don't feel extreme bliss.

Enlightenment?[fn::<2019-11-28> How Do You Recognize An Enlightened Being? - Sadhguru https://www.youtube.com/watch?v=VQrhl7KJ0m4]

Remote viewing is similar to automatic writing/drawing in that both of them use the subconscious.
How do we distinguish these cases?
1. The viewer's consciousness goes to the target.
2. The viewer and the target communicate by telepathy.
3. The viewer reads some Akashic records about the target.
4. The viewer is let know by a spirit/disembodied consciousness.

What is the evidence for auras?
What does Kirlian photography actually capture?
Biofield evidence?[fn::<2019-11-27> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4654779/]

What is the evidence for chakras?

/Why does all psychic development book boil down to deep meditation and visualization/?
If they work, how do they work?

I am reading David DeBold's "Miracle mastery" book?
There seem to be [[https://healingtaousa.com/topic/miracle-mastery-by-david-debold-has-anyone-read-this-text/][other readers]] too.

What are Paramahansa Yogananda's "scientific techniques for attaining direct personal experience of God"[fn::<2019-11-08> https://en.wikipedia.org/wiki/Paramahansa_Yogananda]?

Is the goal of null-domain meditation (empty-mind meditation) ego death?

Does an enlightened man know that he is enlightened?
To be enlightened is to know reality directly without the material senses?

If an enlightened person cannot be disturbed[fn::<2019-11-27> Sri Avinash's opinion https://www.youtube.com/watch?v=KxUPSRgLIGE],
then what is the difference between enlightenment and apathy?

Some of the quickly visible effects of meditation are reduced stress and increased ability to maintain focus.

Is meditation about focus, about relaxation, or about quieting the mind?

Read Quora psychics-related topic, and perhaps Reddit, but Quora is more structured (question-answer).

Is [[http://www.rainbowbody.net/HeartMind/Yogasut_plain.htm][Patanjali]] right? Did he know what he was talking about?

Does myopia hamper aura-seeing?
Do we use eyes to see aura?
If not, then myopia should not hamper aura-seeing.

(On telekinesis and the conservation of energy.)
Where does the energy come from? Does the practitioner become tired? Is energy conserved?

A plan of the table of contents:
- Evolution of the brain.
  What questions about the brain can evolution answer?
  Why do brain parts specialize into functional areas?
  Speculations on the non-uniformity of the brain.
  Encephalization quotient?
  Why have humans built more variety of tools than elephants have?
- Dissociative identity disorder.
  Kastrup's hypothesis of individual consciousness as dissociation of cosmic consciousness.
  Is there an identity dissociation that is not a disorder?
- Disembodied consciousness, mediumship, life after death, out-of-body experiences, near-death experiences, shared death experiences, anomalous cognition.
- Remote viewing, energy works, psychic abilities/functioning, paranormal phenomena, poltergeist vs haunting.
  - [[file:remote-viewing.html][On remote viewing]]
- What can cybernetics tell us about the brain? Good regulator theorem?
  - Anapoiesis reconstructs knowledge "from long-term memory to working memory"?
    <2019-11-05> https://arxiv.org/ftp/arxiv/papers/1402/1402.5332.pdf
- Psi research around the world: USA, USSR, China, etc.? [[file:question.html]]
- Memory. Hypothesis: Temporal ordering enhances recall. Perception of time. [[file:question.html]]
- Borderline crackpot territory.
  - Quantum-physical hypotheses of the workings of the brain, consciousness, whatever.
  - Religion as technology for communicating with God.
    Jesus as a democratization of the access to God (from select shamans then to everyone now)?
- I have some [[file:question.html][unanswered questions]].
- [[file:energy.html][Energy]] is the ability to do work. Power is the rate of energy transfer.
  (If you wish to detour to politics, see [[file:power.html][On political power]].)
- Everyone should develop psychic abilities?
  - [[file:book.html][Summary of some books]] (deprecated)
- Philosophy should use [[file:philo.html][simple language]].
- [[file:religion.html][Religion]] is a technology for communicating with God?
- [[file:anomaly.html][On anomalies]]
- There is enough paranormal evidence.
  We need a [[file:anomaly-theory.html][theory]].

What?

Precognition indicates consciousness?
Animals precognize.
Human consciousness can interfere in consciousness experiments.
 [fn::<2019-09-28> Machine Consciousness: Experimental Evidence | Garret Moddel https://www.youtube.com/watch?v=4H5GDQ7u_iE]

Perhaps we prayed because it will rain; perhaps the future affects the past.

I declare <2019-11-25> as my day one of consciousness experiments.
By then I had been meditating lightly for a few days.
** My personal discoveries
I think these will apply to you too.
*** How to anger me
How to surprise me:
Violate my guesses.

How to anger me:
Violate my expectations.

How to arouse resentment in me:
Violate my expectations, and give me no control to change it.

<2019-11-28>

Especially good at angering me are shitty computer systems.
My shitty bank's shitty website.
Gojek's shitty behavior (giving drivers 2 km away).

When I'm angry, cussing helps diffuse the urge to destroy things.
*** How to scare me
How to make me fear: Put me in a dark outdoor place with no street lights.

Why is that?
How was I conditioned to fear that?
* Overview of consciousness
Is there any meaningful difference between subconscious and unconscious?

If
Consciousness = ability to know (introspectability?)
then
Subconsciousness = /reduced/ ability to know,
and
Unconsciousness = inability to know, lack of ability to know.

Cognition and recognition

cogito comes from from con- (from cum-, with) and agito (agere, to do) <2019-11-05> https://en.wiktionary.org/wiki/cogito#Latin

Cognizance, cogitate

Cogito = I think

X recognizes Y iff X cognizes that X cognizes Y.

For example, we see a photo of a distant acquaintance that we last met 40 years ago.
We immediately /cognize/ this person, in the sense that we immediately feel that we know this person (we have seen this person somewhere before);
but for a moment we strive to think who this person is and where we met this person: it takes us some time to /recognize/ this person.
** An analogy of consciousness: a person in a stream full of fish
How accurate is this analogy?

My consciousness, my awareness,
my perception of what I think is the present, my existence,
is like trying to catch as many fish as possible in a rapid stream of water full of fish swimming along in the current.
There are so many fish that my conscious mind does not see.
When I silence my mind, it is as if I let the fish swim, not catch them, not interfere with their natural trajectories.

The fish in my hand is my conscious mind.

The fish I glimpse in my peripheral vision is my subconscious mind.

The fish swimming under the water is my unconscious mind.
** What do others say about consciousness?
TODO summarize:
- Vsauce video "What is consciousness?"[fn::https://www.youtube.com/watch?v=qjfaoe847qQ]
- 2009, "How to define consciousness—and how not to define consciousness", [[http://cogprints.org/6453/1/How_to_define_consciousness.pdf][pdf]]
* Editor: Move these things somewhere else?
** Why are we so angry?
- https://www.nhs.uk/conditions/stress-anxiety-depression/about-anger/
  - "being treated unfairly and feeling powerless to do anything about it"
    - Is it really unfairness that bothers me, or do I have the wrong sense of fairness?
      Does fairness even exist?
- https://psychcentral.com/blog/angry-all-the-time-for-no-reason-this-might-be-why/
  - 'Anger also “stems from wanting to control what is outside of us,” said Michelle Farris, LMFT, a psychotherapist in San Jose, Calif.'
** What psychology?
- [[https://en.wikipedia.org/wiki/Psychology_of_collecting][WP:Psychology of collecting]]

  - [[https://en.wikipedia.org/wiki/Compulsive_hoarding][WP:Compulsive hoarding]]
  - [[https://en.wikipedia.org/wiki/Digital_hoarding][WP:Digital hoarding]]

- Undigested

  - [[http://www.apa.org/monitor/nov02/gomad.aspx][2002, Jennifer Daw, Why and how normal people go mad]]
  - advertising, propaganda

    - [[https://www.youtube.com/watch?v=nj_UWbifM2U][How One Man Manipulated All of America]], 12 minutes, too long, about [[https://en.wikipedia.org/wiki/Edward_Bernays][WP: Edward Bernays]]

  - Persuasion, changing minds

    - [[https://viaconflict.wordpress.com/2014/10/26/the-behavioral-change-stairway-model/][The Behavioral Change Stairway Model]],
      can be used for hostage negotiation, suicide prevention, terrorist deradicalization
    - changingminds.org

      - http://changingminds.org/techniques/general/overall/overall.htm
      - http://changingminds.org/techniques/general/cialdini/cialdini.htm
      - http://changingminds.org/techniques/general/kellerman/kellerman.htm
      - http://changingminds.org/techniques/general/being_right/being_right.htm
      - http://changingminds.org/techniques/general/ingratiation/ingratiation.htm
      - http://changingminds.org/techniques/how_to/trust_me/trust_me.htm

    - The key to persuasion is *think as the target*.
      Think what he/she wants and hates.

      - Application to politics:

        - [[https://qz.com/525132/the-smartest-most-effective-way-to-win-any-political-argument/][Frame your persuasion in the target's morality]].
        - [[https://www.nytimes.com/2015/11/15/opinion/sunday/the-key-to-political-persuasion.html][Same]].

  - A /market/ is where things are bought and sold.
  - To /market/ something is to try to sell that thing.
  - Marketing is about inducing people to buy something?
  - Sometimes being agreeable is more important than being correct.

    - Other people's feelings are more important than the truth?

  - https://qz.com/881289/a-new-study-linking-profanity-to-honesty-shows-people-who-curse-are-more-authentic/

- How the Nazis might have made the German people accept Nazism

  - https://en.wikipedia.org/wiki/The_Wave_%282008_film%29
  - https://en.wikipedia.org/wiki/The_Third_Wave_(experiment)

- Why do people kill?

  - Anger? Envy? Hatred?

- Why do people rape?

  - Is it about beauty?

    - No?

      - There are ugly people who get raped.
      - There are beautiful people who don't get raped.

  - Is it about getting satisfaction from unconsenting victim?
  - Is rape a power trip?
  - Is there any relationship between grandiosity and rape?

- Why do people commit crimes?

  - Do they know the penalties?

    - If yes, why do they still commit crimes?

- [[https://www.beeminder.com/home][beeminder.com: use loss aversion to trick yourself to accomplishing goals]]
- [[https://www.youtube.com/watch?v=WEvqMN75sCI][Does your job match your personality? | Jordan Peterson]]

  - axis: complexity

    - high complexity requires high cognitive function level

  - axis: creative/entrepreneurial vs managerial/administrative

    - big five personality trait

      - C/E requires "openness to experience"
      - M/A requires conscientiousness

- [[https://www.youtube.com/watch?v=-moW9jvvMr4][A simple way to break a bad habit | Judson Brewer]]: by being curiously aware
- [[https://www.youtube.com/watch?v=xp0O2vi8DX4][How to motivate yourself to change your behavior | Tali Sharot | TEDxCambridge]]
- https://www.washingtonpost.com/news/storyline/wp/2014/12/04/people-around-you-control-your-mind-the-latest-evidence/?utm_term=.40265b80e149

  - https://news.ycombinator.com/item?id=12698204

- [[https://www.youtube.com/watch?v=kyioZODhKbE][Facts Don't Win Fights: Here's How to Cut Through Confirmation Bias - Tali Sharot - YouTube]]

  - To polarize someone is to make him more confident (about a belief).
  - Confirmation bias: People hear what they want to hear.

    - People filter incoming information.
    - People bend incoming information to conform with their preexisting beliefs.
    - Agreements polarize people, but disagreements don't depolarize people.
    - Information agreeing with preexisting belief polarize the believer.
    - Information disagreeing with preexisting belief is filtered out and doesn't depolarize the believer.

  - Key insight: We can change people's behavior without changing their beliefs.

- [[https://www.youtube.com/watch?v=WAL7Pz1i1jU][How to Persuade Others with the Right Questions: Jedi Mind Tricks from Daniel H. Pink]]

  - how to get your daughter to clean her room

    - the comment section is pessimistic

- 2018-08-29 What I learned today.

  - To temporarily defuse your enemy's hatred of you, find another enemy that is common to both of you.

    - These happens in quick succession:
      Coworker A offended me.
      Then coworker B came and offended A in front of me.
      Then I offend coworker B in front of A.
      Then I can feel some agreement with coworker A.

  - The perception of having a common enemy unites people, even if the enemy is fake.

- [[https://www.youtube.com/watch?v=nknYtlOvaQ0][Why obvious lies make great propaganda - YouTube]]

  - [[https://www.rand.org/pubs/perspectives/PE198.html][The Russian "Firehose of Falsehood" Propaganda Model: Why It Might Work and Options to Counter It | RAND]]

    - This has a concrete recommendations for countering the firehose of falsehood.

  - Trump and Putin use "firehose of falsehood" to assert power, in the same way school bullies do.
  - The only way to take power from them is to dismiss them.
    Media should stop giving them a platform.
    We should refuse to hear them.
    We should not fact-check, because by fact-checking we affirm that they have power.
    We should simply dismiss everything they say.
    Their competitors should counter-flood the media with their own firehoses.
  - I'm sure Trump and Putin are not the only people using that technique.
    I suspect that PKS may be using that technique in mosques in West Java.
  - Can [[https://en.wikipedia.org/wiki/Gaslighting][WP:Gaslighting]] be used to unplant false beliefs?
** Fear explains everything?
There are only two ways to make people do something:
- Make them want it.
- Make them fear the consequences of not doing it.

https://en.wikipedia.org/wiki/Fear_appeal
*** Explaining love/attachment as fear of loss...
*** Intrinsic motivation to do X is fear of the consequences of not doing X.
*** To want X is to fear not getting X.
*** We eat because we fear death. We eat because we fear regretting not tasting the delicious-looking food.
*** It is the terrorists/extremists who are afraid of us, in the same way a cornered rat biting us is afraid of us?
*** Emotion hypothesis: Everything is fear
Attractive emotion.
Fear is a repulsive emotion.

Emotion axis: low/high energy, repulsive/attractive toward the cause

Hate is fear of proximity.

Desire is fear of loss.

Love is fear of loss.

Boredom is fear of repetition.

Indecisiveness is fear of regret.

Hunger and thirst are fear of death.

Joy is fear of fear.
** <2019-11-28> Why does darkness inconvenience us?
Street lights went out.
I feel somewhat uneasy; I had to consciously calm myself, although there is nothing unusual.
Why does darkness inconvenience us?
** Artificial?
We say that something is "artificial" iff it is highly unlikely to exist without being created by a human.
We say that something is "natural" iff it is not artificial.
But, if artificial urea and natural urea are exactly the same thing with the same properties, why do we bother?

Why do we assume that some things will not come into existence if there are no humans to create it?

Is it possible that somewhere out there in the vast outer space,
there is a jet aircraft formed spontaneously by natural processes such as explosion of stars?

Is it possible that there is a teapot-shaped space rock formed by natural processes?

Why are most objects in outer space relatively simple compared to artificial objects?
Or are things not as simple as they seem?
** On beginner resources for psychic power, spiritual journey, etc.
[[https://www.youtube.com/watch?v=bRYHmniQnA8][Robert Bruce advises astral travel beginners]]:
As one is about to leave the body, one must stay calm and focused, and not get excited.
** Esoteric science going mainstream?
Is [[https://www.sciencedirect.com/science/article/pii/S1550830718300685][Krippner et al. 2019]] a sign that remote viewing is going mainstream?
** <2019-11-27> On refusing reincarnation
bhagavad gita
https://asitis.com/15

Krishna meditation, 6:13-14, dhyana yoga
https://vedabase.io/en/library/bg/6/

The light at the end of the tunnel is the birth canal?
What theory is this?
https://www.quora.com/What-if-you-dont-want-to-be-reincarnated

Is life a gift, a trap, a prison, a test, or what?
Is it what you make of it?

https://www.reddit.com/r/spirituality/top/?t=all
** Using analytic philosophy to clarify and navigate social relationships
*** Friendship
**** What is a friend?
Your friends are those who sacrifice for you.
The greater the sacrifice,
the greater the friendship.
How do we measure a sacrifice?
**** How do we measure friendship?
In theory, we define $F(A,B)$ (the /friendship measure from A to B/)
as how much sacrifice that A is willing to make for B.

(Is the direction correct? Is that backwards?)

Thus measuring friendship boils down to valuating sacrifices.

$F(A,B)$ can be approximated by an equivalent amount of money.

How do we measure friendship in practice?

Foot-in-the-door:
let A ask B to make bigger and bigger sacrifices until B refuses.
Then we have found $F(A,B)$.

Door-in-the-face:
let A ask B to make a sacrifice so big that B refuses,
and then let A ask B to make smaller and smaller sacrifices until B accepts.
Then we have found $F(A,B)$.

Those results may differ, but $F(A,B)$ should lie somewhere between those two points.
We can also average them, take the maximum, take the minimum,
use interval arithmetics,
or describe the result using a statistical distribution, for example.
**** Properties of friendship
Friendship is circumstantial:
$F(A,B)$ changes over time.

Friendship is usually asymmetric:
$F(A,B) \neq F(B,A)$.
**** Questions
What is self-friendship?
What is $F(A,A)$?
How much is one willing to sacrifice for oneself?
Does this question even make sense?
**** Links
- [[http://www.abc.net.au/news/2015-10-29/friendship-theory-developed-by-sydneysider-goes-viral/6897402#theory][Mobinah Ahmad's 6-level relationship categorization]]
- [[https://kenanddot.wordpress.com/2007/03/21/the-asymmetry-of-friendship/]["Ken writes: Isn't it strange that although friendships are obviously asymmetrical this isn't unambiguously reflected in language?"]]
*** Defining "boss"
- What is a boss?

  1. X is a /boss/ of Y iff X can affect Y's salary, even if X does it indirectly.
  2. X is a /strong boss/ of Y iff X has the authority to change Y's salary.
  3. X is a /weak boss/ of Y iff X is a boss, but not a strong boss, of Y.

- Example:

  - Everyone who can fire you is your strong boss.
  - Everyone who can get you fired (complain to someone who can fire you) is your weak boss.

- The stronger a boss is, the more seriously you should treat him/her.
- Don't bite the hand that feeds you.
**** Another definition, based on fear: X is a boss of Y if Y fears X.
*** Happiness
Happiness = Reality - Expectation.

To be more happy, raise reality, lower expectation, or do both.

Pain also reduces happiness.

Money cannot buy happiness,
but it can buys things that will make you happier.

Money helps, but after you have enough to make your life comfortable,
adding money doesn't add happiness.
** Blog about biology, health, and beauty
*** <2019-08-17> On myopia
I hypothesize that myopia has lower prevalency in the population of drivers because drivers refocus their eyes a lot.

black-on-white promotes myopia, white-on-black inhibits myopia?
https://www.nature.com/articles/s41598-018-28904-x

https://biology.stackexchange.com/questions/24589/how-does-the-eye-know-whether-to-focus-further-out-or-nearer-in-order-to-bring-a

https://photo.stackexchange.com/questions/105433/can-you-tell-from-a-blurry-photo-if-focus-was-too-close-or-too-far

Hypothesis:
The brain uses the chromatic aberration of the eye lens in order to detect whether the focus is too near or too far.
Green fringing means that the focus is too ???
Purple fringing means that the focus is too ???
https://photographylife.com/what-is-chromatic-aberration
https://en.m.wikipedia.org/wiki/Circle_of_confusion
*** Appeal-to-evolution weakens the theory that irregular eating causes gastritis
<2019-08-17>

The /appeal-to-evolution/ is this argument:
/If a trait would hamper the survival of a species, then that species would not have evolved that trait./

It is a heuristic.
It is not always correct.
For example, it cannot explain peacock tails.
However, it seems reasonable in absence of other information.

The appeal-to-evolution weakens the theory that irregular eating causes gastritis as follows.

Perhaps the very early hunter-gatherer humans ate irregularly;
they were always a few days away from starvation,
they did not have a secure food supply,
they depend very much on their surroundings.
/Having gastritis due to irregular eating would hamper their survival./
Therefore they probably evolved such that irregular eating does not cause gastritis.
*** Others' articles about gastritis
"Coadaptation of /Helicobacter pylori/ and humans: ancient history, modern implications"[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2735910/]

"The Iceman had a tummy bug"[fn::https://www.sciencemag.org/news/2016/01/iceman-had-tummy-bug]

1998 "Helicobacter pylori in vivo causes structural changes in the adherent gastric mucus layer but barrier thickness is not compromised"[fn::https://gut.bmj.com/content/43/4/470]
*** On atherosclerosis
Atherosclerosis or arteriosclerosis?
https://amp.theguardian.com/science/2019/jun/11/mystery-arteries-harden-cracked-scientists-calcium-deposits
*** On gut microbiome?
https://www.prebiotin.com/prebiotin-academy/what-are-prebiotics/dietary-fiber/

https://medium.com/boosted/intermittent-fasting-your-thyroid-and-your-immune-system-ec8f5f02d997
https://www.sciencedirect.com/science/article/pii/S0924224414002386
https://mennohenselmans.com/protein-is-not-more-satiating-than-carbs-and-fats/
https://www.ncbi.nlm.nih.gov/pubmed/8695595/
https://www.shape.com/latest-news-trends/go-veggie-gain-weight-heres-why-it-can-happen
https://www.livestrong.com/article/1011649-6-reasons-people-gain-weight-after-going-vegetarian/
https://www.healthline.com/health/food-nutrition/becoming-vegetarian-tips
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4564526/
https://selfhacked.com/blog/how-your-gut-microbiota-can-make-you-fat-or-thin/
https://www.ncbi.nlm.nih.gov/pubmed/30336163
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6036887/
*** On the science of diets
Conservation of mass.

Body mass is gained by food and drinks, and lost by exhalation and excretion.

The question is the /composition/ of those mass.

If I weigh 70 kg and both my legs weigh 20 kg, then a squat consumes at least 50 kg * 10 m/s2 * 0.5 m = 200 J = 0.0478 kcal.
That's a tiny amount relative to the calories in the food we eat!
We can easily eat 300 kcal in one meal.
Thus, if the human body were 100% efficient, I would have to squat /6,276 times/ to burn that one meal!

Thus the biggest energy consumer is the basal metabolic processes.

The proximal cause is the combination of nutrition and hormones.
Hormones are affected by nutrition, activity, and genetics.

*** A clean eating protocol
Combine /nutrition science/ and /psychology/.

For two weeks.

Pay attention to gut microbiome.

No sugar; no condiments bought from supermarket because they all have sugar.
No flour.
No carb.
No food that is processed more than one step from its original form.
No refined foods.
No extracts.
Sugar is not OK because it is concentrated sugarcane plant extract.
Cooked meat is very OK, but sausage is not.
White rice is not OK.
Green vegetables OK.

Anytime you're hungry, just eat; there is no time restriction;
the only restriction is that you eat real fat/protein.

Everytime you eat, you must send a photograph of what you eat to me.
It is not for approval, but for commentary, and for /psychology/, for accountability,
so that you feel that you are doing it for me, so that you don't prematurely abandon your effort.

You can drink anything as long it has no sugar in it.
Just drink plain water.
Drinks from the supermarket are not OK; they all have sugar.
*** <2019-08-20> ? On skin-wrapping for skin-tightening, occlusion cuff training, and blood flow restriction training
Do they work? How do they work? What is the science?
*** <2019-10-28> Urban planning should include nutrient cycle.
** On living on Earth
*** On living sanely, peacefully, and sustainably
- [[file:groom.html][Grooming]]
*** Why do I wear long hair?
- To repel close-minded people.
- To know when I have lost in life, when I can no longer do things as I wish,
  be it due to biological, political, or economical reasons.
*** The importance of monuments and folklores, especially at disaster sites
To pass on the knowledge to future generations, so that we do not forget, so that we do not waste lives.
 [fn::https://99percentinvisible.org/article/tsunami-stones-ancient-japanese-markers-warn-builders-high-water/]

Monuments, folklores, and histories are trans-generational memory.
It is what enables the human race to advance: Because humans can build on their predecessors' work
and do not repeat everything that their predecessors did.
*** A rather dystopian prophecy: three groups of people
In the future, society will split into three groups:

1. The masters: The people who program the system (tell the system what to do).
   Governments, computer programmers, wealthy people.
2. The slaves: The people who are programmed by the system (are told to do what to do by the system).
   Citizens, online taxi drivers, workers.
3. The outcasts: The people who refuse to participate in the system.

The system consists of people, computers, other machines, and weapons.
*** <2019-07-06> Friendship is fluid and circumstantial
At 10 years old, we are friends because we are in the same class, and we don't have better things to do.
Simple physical proximity.
But we stop being friends as soon as we graduate out of school.

At 20 years old, we are friends because we are in the same company.
We stop being friends as soon as we resign.

At 30 years, we are friends because we share a goal or hobby or problem, because we care about a common thing.
We stop being friends as soon as our problem is solved.
*** <2019-07-06> Two approaches to living: here-first and there-first
There are two approaches to living:
- There-first: Start with what you want, and find what you should have:
  Find what things have to exist in order to satisfy the goal.
- Here-first: Start with what you have, and find what you should want:
  Find what can be done with what already exists.
*** <2019-11-27> On alternative societies
Gather the people tired of the rat race.

There is no point in working beyond what is necessary for sustenance.
* My life lessons
This lessons only apply to me.
This is my self-discovery.
** On procrastination
I had a habit of delaying important-but-unpleasant things.
I had a habit of avoiding them, running away from them.
I had an escapism problem.

A concrete example: I got a new phone,
but I was too lazy to port my old SIM card due to different form factors;
so I got a family member's unused SIM card.
Thus I used my old phone much less frequently.
Then I forget to pay the phone company which then killed my old number.
I had to tell my contacts that I changed my phone number.
I had to go to the bank to update my account.
Much hassle.

Some delayed problems begat bigger problems.
I never thought about that.

I hated the phone company, so I blamed the phone company.

I hated going to the bank.

But then I thought, perhaps it was the Universe's way of telling me that that habit was bad for me.

Perhaps I could meditate while waiting at the bank.

Perhaps it would be a good chance to learn equanimity.

The same habit also causes my browser to have hundreds of open tabs.
I thought that a link was pointing to an interesting document, so I clicked on it.
But I thought that it was unpleasant to actually read the document.
I liked imagination and hated reality;
I liked to imagine myself understanding the document,
but I hated to actually read it.

I know another friend of mine who has the same problem of too many open tabs.

My life would be much easier if I killed the problem while it was small.
* Toward a curriculum for spirituality
- Understand the difference between Jesus and Christ.
- Define "vibration" or "frequency".
  Number of repetitions per unit time?
- Define "synchronicity"?
- Understand ITC (instrumental trans-communication): Gary E. Schwartz, Sonia Rinaldi, etc.
- Understand cognitive-, affective-, and null-domain meditation.
- Overcome material desires.
- Overcome the desire to eat.
- Overcome the desire to drink.
- Overcome the desire to have sex.
- Overcome sexual thoughts.
- Overcome the desire to breathe.
* Mess
** Postmaterialism for the 21st century
- Understand the difference between science and Scientism.
  - Scientism is a religion like Christianity, Islam, etc.
    Dogmatic.
  - There are no fixed beliefs in science (except perhaps that we know that we do not know).
    On the other hand, Scientism adherents have fixed beliefs in mainstream science.
- Understand the difference between skeptics and pseudoskeptics.
- Understand that materialism has advanced us greatly but it can help us no further.

Science can and should be used to investigate afterlife, spirituality, religion, and paranormal phenomena.

We are doing science wrong.
Science should advance faster than one funeral at a time.
Funding should be more random.

Why do we strive to study things as far as the moon, if we have never even studied things as near as our own minds?

Esoteric and exoteric science should be merged into a more complete science.

/Practice/ is important.
Avoid getting so immersed in trying to read all esoteric literatures that you forget to practice anything.
Choose one that /resonates/ with you, and practice it.
For me, it's scientific esotericism.

** Algebra of thoughts and feelings
- If one can think \(x\) and one can think \(y\), then one can think \(x+y\) (both of them together).
- If one can feel \(x\) and one can feel \(y\), then one can feel \(x+y\) (both of them together).
- Thoughts can superpose. Waves can superpose. Forces can superpose.
** What is a body for?
A spirit can think and feel without body.
So what is a body for?
** Speculations
If alien implants are true, then Jesus might have been implanted into Mary's womb by aliens.
** God and us?
- If God and us are one, then it does not make sense for us to pray to God,
  in the same way it does not not make sense for us to tell ourselves about ourselves,
  because we already know ourselves.
** Vibrations?
- What is vibration, and /what/ is vibrating? Vibration of what?
- Molecular vibration is in the order of tens of THz, visible light frequency is in the order of hundreds of THz.
  What does this imply? Nothing?
- Unclear https://www.yourvibration.com/16560/how-to-measure-vibration-how-to-measure-consciousness-how-to-measure-your-vibrational-frequency/
- Hawkins scale unclear
- !!?? Tries to be clear? https://ascensionglossary.com/index.php/Law_of_Vibration
- How are "love" and "hate" vibrations?
  How the hell is "love" is "higher frequency" than "hate"?
** Affirmation slippery edge?
How do we think that we deserve wealth without being an affluenza person?

These are different: to think that we deserve wealth, and to think that we don't deserve poverty.

To me, "X deserves Y" means "It is good that X has Y", for whatever definition of "good" you subscribe to.

https://en.wikipedia.org/wiki/Desert_(philosophy)
** <2019-11-28> Is psychology science?
There are psychological experiments and theories that try to explain those experiments, but do those theories predict anything?

Is psychology falsifiable?

There are some interesting experiments and applications.
Asch conformity experiment,
Stanford prison experiment.
Using stories to change minds.
Hostage negotiation techniques.
Pavlovian conditioning, Skinnerian conditioning.
Rat heaven experiment.
Monkey mother experiment.

/But what is the underlying science?/
Biology, genetics, hormones, epigenetics, neuroscience, and so on.

Psychology can be thought of as applied biology.

Everyone capable of some empathy has an intuitive understanding of basic psychology.
** Mind and brain?
<2018-10-03> [[https://www.sciencealert.com/brain-to-brain-mind-connection-lets-three-people-share-thoughts][brain-to-brain interface?]]

Mind-brain relationship: Gage, Sperry, Libet, corpus callostomy, "thalamic bridge", etc.

Minds and brains [[file:mind-brain.html][interact]],
but we [[file:mind.html][don't really know how]].
** Editor's notes
Alternative titles:
- /introspection/
- mind/mental/introspection/personal-psychology /experiments/
- /unified/ esoteric-exoteric science
- inner /science/; science of the subjective experience
** Condemned resources?
Pam Grout's 2013 book ("[...] Nine Do-It-Yourself Energy Experiments [...]")
gives some spiritual experiments that everyone can do on their own.
But there are lots of [[https://www.amazon.com/product-reviews/1401938906/?filterByStar=critical&pageNumber=1][damning reviews]], so I did not read the book.
But there are some positive reviews too.
I should decide for myself.
** <2020-01-01> Idea: A system is an embodied intention
Establish an organization with an intention.
People with the same intentions resonate and contribute to the organization.
Example: Wikipedia is the embodiment of the intention of creating an encyclopedia (summary of mainstream materials).

To manifest an intention, /embody/ that intention: give that intention a body, create a body with that intention.
Establish an organization?
Establish a group?
Create a system?

Global intention is manifested by /resonance/ among like-minded people.

Two people /resonate/ iff they have the same intention.
** <2020-01-01> Questions on manifesting; lower mind vs higher mind
Why can't I just sit down and "will my way" to anything?
Why can't I just sit down, totally believe that I have a car, and make a car pop out of nowhere?

/Or can I?/

Perhaps, deep down, my subconscious disbelief is stronger than my conscious belief?
Or perhaps "I" am not what I think I am?
When I think "I am willing a car", it is my mind that is willing, not I that is willing.

Idea for some "enlightenment" via writing:

- I, me, my, myself = what I am; "higher mind"
- 'I', 'me', 'my', 'myself' = what my mind thinks I am; "lower mind"

I am manifesting, but from 'my' point of view, 'I' am not manifesting, because that is true: it is I, not 'I', who is manifesting.
So how can 'I' know myself and what I am thinking?
'I' is mired so deep in its illusion of what 'I' think I am.
'I' have brain, but I don't have brain, so how do I know, and how do I communicate with 'me'?
How come that I and 'I' are one but different?
** <2020-01-01> Imagination is real
Imagination is undoubtedly real, at least subjectively.
We do not doubt that our imagination exists.
It is just that we don't know how to mix our imagination and reality;
we don't know how to embody our imagination.

Effort is the progress of embodying an imagination?
We embody imagination by giving energy to it?

What is subjectively real?
Everything you "see" is, by definition, subjectively real.
This includes perception, hallucination, dream.
** <2020-01-01> On God and imagination
*** Hypothesis: We are God's imaginations
How do we test this hypothesis?

God is to us as we are to our imaginary friends.

Our imaginary friends are our imaginations as we are God's imaginations.

We imagine our imaginary friends into existence as God imagines us into existence.

Our imaginary friends believe that they are real, as we believe that we are real.

What is real to us is God's imagination.

What is it like, to see from God's point of view?
*** On nested imaginations
If we can imagine talking with our imaginary friends, then our imaginary friends can imagine talking with us.

We can imagine that our imaginary friends are imagining something.

God can imagine us imagining God.

Like a dream in a dream, like "Inception".
** On looking for aliens
- <2020-01-21>
  I think it is ironic that to find aliens we must go /inwards/, not outwards like the SETI project.
  Of course SETI finds nothing; it assumes that a 200-year old physical model is reality;
  its engineering may be new, but it ignores 200 years of recent science;
  it is looking at the wrong place, like looking for fish in in the sky!
  /The spiritual researchers have found the aliens/, and they do not use your 19th-century electromagnetic radiation; they manipulate spacetime!
  The SETI project is a misguided waste of effort and should be aborted right now,
  and all its funding should be given to spiritual/consciousness researchers, such as the FREE foundation!
  It's too late to have reservations about contacting aliens; /the aliens themselves are contacting us/!
** Essassani?
Darryl Anka's Bashar vs Andrew Bayuk's Elan?
https://www.inwardquest.com/questions/101857/what-happened-to-elan-chanelled-by-andrew-bayak
** Bertrand Russell
Bertrand Russell - Message To Future Generations
https://www.youtube.com/watch?v=ihaB8AFOhZo
* Bibliography
