#+TITLE: Ethics
#+DATE: 2018-09-15 23:22 +0700
#+PERMALINK: /ethics.html
* Abortion debates are futile communication failures
<2018-09-15>

TLDR: Before you debate abortion, make sure everyone has the same definition of the words you're going to use.
** The problem with abortion debates
Abortion debate is all emotion and no thinking.
Nothing will ever come out of it.
There is no real discussion.
The participants don't even agree on the meaning of the words they use (human, fetus, life, species, murder).
It is communication failure.
It is religious debate.

Everyone gives different meanings to the same word.
Everyone assumes everyone else has the same definitions.
There is only an illusion of communication.
There is no real progress.

New York Times has some [[https://opinionator.blogs.nytimes.com/2011/11/30/on-abortion-and-defining-a-person/][opinion]] about language in abortion debates.
** Abortion debate is battle between thinkers and feelers
After seeing [[https://abortion.procon.org/][Abortion ProCon.org]], I realize that the debate is just a battle between thinkers and feelers.
Generally, thinkers are pro-abortion and feelers are anti-abortion.

After browsing around, I realize that gun control, euthanasia, death penalty, and other moral issues are just a giant battle between thinkers and feelers.
** Ubiquitous problem: not defining what a human is
What is a human?
We think we know what a human is, but when we want to say it, we find out we can't.
Why?
Is our language limited?
Is "human" an ill-defined concept?

We don't know what a human is, we don't know what life is, but we dare to debate the sanctity of the life of a human?

People who debate abortion but can't define human are wasting time.
They don't know what they're talking about.
** Ubiquitous fallacy: binarizing the continuum
Concepts such as hot, tall, big are not binary.
They are continuums.

Life is not binary.
It is a continuum.
We are more alive when we wake up.
We are less alive when we sleep.
We are even less alive when we die.

Being human is a continuum.

Truth is a continuum.
We reason probabilistically.
** Why do we care what others do?
We care about what others do only as far as how they may harm us.

We don't care when someone harms himself.

We care when someone harms others, but only if he may harm us.

We care when someone kills people because we fear he may kill us next, not because we care about the people he killed.

We care when someone kills his children because we fear he may kill our children next, not because we care about the children he killed.

Why do we care when a pregnant woman aborts her fetus?

We care when a woman aborts her fetus because we want to impose our morality on others, not because we care about the fetus.
If we cared about the fetus, we would help the mother raise the fetus, help her give birth, and then adopt the baby.
** Nature-defying El Salvador abortion law
[[https://www.bbc.co.uk/news/magazine-24532694][El Salvador abortion law ignores nature]].
It imprisons people unnecessarily.
** Catching fallacies in action
*** Dennis Prager
Dennis Prager has a [[https://www.youtube.com/watch?v=AMwkQVpy98A][video about abortion]].

What he gets right:

- Right: "When challenged with this argument, people usually change the subject to the rights of the mother."
  - The right response is to ask the claimant to define the words human, species, life, fetus, etc.
    There is no need to digress to mother rights in order to point out the problems with the argument.

What he gets wrong:

- Mixing unrelated concepts in a loaded question: "Does the human fetus have any value and any rights?"
  - "Value" is a moral concept.
    "Rights" is a legal concept.
    The two don't always coincide.
    Also, he hadn't defined what a "human" is.
- Misuse of language: "A living being doesn't have to be a person in order to have intrinsic moral value and rights."
  - The term "intrinsic rights" is an oxymoron.
    Your rights are the things laws give you.
    They don't come with you.
- Wrong: "Either a human fetus has worth or it doesn't."
  - This is the fallacy of binarizing the continuum.
- Loaded question:
  "Why does one person, a mother, get to determine whether that being has any right to live?"
  - The question should have been: "Why does /anyone/ at all get to determine whether any being has any right to live?"
    - That question suggests antinatalism.
      Why do we force babies to come into being?
* Moral particularism
https://philosophynow.org/issues/60/Why_You_Shouldnt_Be_A_Person_Of_Principle

Is there a universal moral principle that coincides with the majority intuition about these issues?

- It is moral to kill fewer people to save more people?
- Is it moral to kill a serial killer to prevent 100 murders?
- Is it moral to kill a healthy innocent person and distribute his organs to save 5 people in need?
- Is it moral to annex a mismanaged country and improve it?
* Does intention matter?
How do we know others' intentions?
* Improbability of equality of outcome in doomsday spaceship scenario
Consider this "doomsday spaceship" scenario:
- A huge asteroid will hit the Earth 1 week from now. That will kill all 7 billion people.
- But we have one spaceship that can save 1000 people. That is the only way out of Earth.
Which people should we save?
Why?
There is no satisfactory answer to this; we should just use a truly random lottery.
But if we pick people randomly, the ship will be full of poor people, because the majority of the Earth is poor.
Should pregnant women be prioritized before non-pregnant women?
Should older women be prioritized before younger women?
Should women be prioritized before men?
Should children be prioritized before women?
Nobody should be prioritized.
If we don't pick people randomly, then we don't practice what we preach about equality.

With a lottery, all 7 billion people have a chance to board the spaceship,
but it is physically impossible for all 7 billion people to actually board the spaceship.
No amount of political correctness will change the laws of nature.

Of course, when the spaceship is big enough for 7 billion people, we can have equality of outcome.
The question is how we make a spaceship that big.
* Leaving Greenpeace
- [[https://www.youtube.com/watch?v=BpBnJq19R60][video]] of Patrick Moore's reasons for leaving Greenpeace
