#+TITLE: Failures
#+DATE: 2017-05-20 00:00:00 +0700
* Internet service providers
** Fastnet
Every time Fastnet goes down when
I want to connect to the Internet,
I'll write here.

2016-11-29 it went down.

2016-12-13 it went down due to someone else's fault.
Kabel kecangkul alat berat orang lain di depan BCA KCP Kepa Duri Jl Mangga.

2017-06-15 00:00 +0700 it went down.
04:00 I went to bed, and it was still down.
It went up again some time between 04:00 and 10:30.
The downtime was more than 4 hours.

2017-08-11 00:00 +0700 it went down.
2017-08-11 02:30 +0700 it went up.
The downtime was 2 hours 30 minutes.

2017-08-24 08:00 +0700 it went down.
2017-08-24 12:24 +0700 I left home for office; it was still down.
2017-08-25 02:00 +0700 I went home from office; it had gone up.
The downtime was less than 18 hours.
I forgot to ask the people at home how long it had been down.

2017-10-09 11:00 +0700 it went down.
They said it would go up on 2017-10-10 23:00 +0700 (24 hour downtime).
2017-10-10 03:23 +0700 it hadn't gone up.
It finally went up, but I didn't note when.

In 2018, we stopped using Fastnet.
We switched to CBN.
** CBN
<2019-10-30>
Update: CBN sudah tidak sering mati seperti dulu.
(Atau saya yang jarang di rumah?)

Plus:
CBN lebih murah daripada Fastnet.
CBN fiber upload lebih cepat daripada Fastnet ADSL.

Minus:
CBN lebih sering mati.
/CBN sangat sering mati./

2017-12-23 00:00 CBN mati sekitar 12 jam.

2018-05-22 04:27 CBN mati.
04:37 sudah nyala.

2018-07-17 22:32 CBN mati.

2018-09-07 11:30 - 13:30 CBN mati.

2018-09-26 02:04 - 12:11 CBN mati.

2018-11-16 00:16 CBN mati sebentar.

2018-11-26 16:45 - 17:30 CBN mati.
Hujan petir.

2018-11-29 16:00 CBN mati.

2018-11-30 00:30 CBN mati.

2018-12-17 04:00 CBN mati.
14:00 nyala.
* WhatsApp bullshit I have to put up with
<2018-12-13>
WhatsApp Web requires Chrome 36+ or newer?
I have Chromium 65.
* PLN electricity distribution
Zona waktu GMT+7.

Daerah Green Ville tahap 4, Jakarta Barat.

2017-10-05 13:42 PLN mati.

2017-12-20 00:17 PLN mati sekitar 15 menit.

2018-01-02 07:00 PLN mati.
Waktu kembali hidup tidak dicatat.

2018-04-03 22:00 brownout.
00:00 mati total.
07:20 nyala.

2018-??-??: Gardu PLN meledak.

("Sebentar" berarti "sekitar 10 detik".
Zona waktu UTC+7.)

PLN mati sebentar:
- 2018-05-10 02:50
- 2018-05-10 20:00
- 2018-08-08 23:28
- 2018-09-18 01:18
- 2018-09-19 02:55
- 2018-12-07 01:39
- 2018-12-07 23:00

2019-03-05 05:20 one-second brown-out.

2019-07-29 00:22 one-minute black-out.

2019-07-30 00:12 one-minute black-out.

Mengapa PLN suka mati sebentar?

- 2018-08-14 23:58 PLN mati sebentar.
  - This corrupts Chromium profile.
  - Chromium fails to restore tabs.
    - This is the second time it fails.
  - My response:
    - Discard tabs at the end of browsing.
      - Open Chromium with predefined tabs.
      - This also solves two other problems: tab hoarding and information overload.

I wish we have distributed electricity generation with solar panels and batteries.
Electric utility companies should die.

2019-08-04 11:00-21:00 pln mati se-jawa barat & jawa tengah
21:00 Nyala sebentar cuma 2 jam
23:14 mati lagi
06:00 nyala
10:00 mati lagi
15:30 nyala

2019-08-23 01:25 mati lampu beberapa detik

- 2020-01-16 18:51 pln mati
- 2020-01-17 04:03 pln mati
* <2018-09-22> Derita naik Gojek/Grabbike/Gocar/Grabcar
<2019-10-30>
Update: Hal-hal di bawah sudah tidak berlaku.
Pada tahun 2019, Grab lebih bagus daripada Gojek.
Akhirnya saya kembali pakai Grab.

<2018-09-22>

Saya sempat coba Grab dan Gojek.
Saya tidak pakai Grab karena saya benci kode promo.
Akhirnya berlabuh di Gojek.

- Gojek
  - Kadang pengemudi tidak bisa membaca.
    Tiap minggu ada saja pengemudi yang tidak baca catatan, lalu nyasar.
    Sangat buang waktu.
  - Kadang dapat motor Yamaha Aerox.
    - Motor ini tidak aman; pusat massa tinggi, mengurangi kestabilan.
    - Motor ini tidak nyaman; joknya keras, suspensinya keras, menyiksa pantat.
    - Contoh motor yang enak: Honda Scoopy.
      Tampilannya emang culun, tapi jok lebar dan empuk, dan suspensi juga lembut.
      Enak buat pantat.
    - (Saya tidak punya motor.
      Saya bukan fans Yamaha ataupun Honda.
      Saya cuma benci sakit pantat.)
  - Kadang ban kempes.
    Kadang motor bocor.
    Kadang ban bocor.
  - Pernah, jam 17:00, 30 menit gak ada yang ambil.
- Gocar
  - Kadang pengemudi mengantuk, merem melek.
    Mobil ngegas ngerem.
  - Posisi suka ngaco.
    Minta jemput di S Parman, supir di Mal Pondok Indah lah (12 km), di Pejompongan lah (6 km), di Tomang lah (4 km), di sisi jalan yang salah lah (4 km).
  - Kadang di-cancel 5 kali baru dapat.
  - Kadang mobil bau rokok.
- Grabbike
  - <2018-10-05> Grab jam 17 sangat shitty.
    Driver tidak bisa dihubungi.
    Dua kali berturut-turut.
- Grabcar
  - <2018-10-25> Saya ditinggal kabur supir grabcar, padahal saya tinggal 5 langkah dari mobil, dan dia belum ada 5 menit menunggu.
- Aplikasi Gojek vs Grab:
  - Grab lebih reliable.
  - Gojek lebih hemat baterai.
- Perasaan saya.
  - Teknologi keduanya shitty, tapi teknologi Grab less shitty daripada teknologi Gojek;
    Grabcar lebih bisa mencari supir yang dekat (500 m, 1 km); Gocar seringkali dapat supir (2 km, bahkan pernah 6 km).
  - Supir Gocar memperlakukan penumpang lebih baik daripada supir Grabcar memperlakukan penumpang.
    Mungkin karena Gojek lebih kejam ke supir.
* Gmail
- I know it's free and my life depends on it, but I need to rant.
  - Who says it's free? I paid it with my privacy!
** <2018-11-03> Plain text 78-character hard word wrap. It's 2018, and I open Gmail in a browser, in an almost 30-inch screen.
- Either the request fell on deaf ears, or the forum is not the right place for requests.
  https://productforums.google.com/forum/#!msg/gmail/rThTLh3KY7s/ACN9M300XYAJ
** <2016-04-01> Harmful miscommunication-inducing deal-breaking enemy-making April fools' day prank
April fools' day is harmful.

Pranks are harmful.

[[http://www.telegraph.co.uk/technology/2016/04/01/gmails-mic-drop-april-fool-backfires-costing-people-their-jobs/][Gmail mic drop April fools' day prank]]
is [[http://www.businessinsider.co.id/google-pulls-mic-drop-minions-april-fools-joke-due-to-complaints-job-losses-2016-4/#.Vv43px_I7Qo][a stupid idea]], and also a harmful one, it turns out.

I, among who knows how many of the other [[http://techcrunch.com/2016/02/01/gmail-now-has-more-than-1b-monthly-active-users/][1 billion users]],
was sending an email to a head recruiter for a job on the following Monday (2016-04-04)
when I accidentally pressed that damn button.

Pranks violate the [[https://en.wikipedia.org/wiki/Cooperative_principle][cooperative principle]].

The next time you're going to play pranks: just don't.
Better spend your time somewhere else.
* Jakarta
2020-01-01: Jakarta failed.
Worst flood in 30 years.
Water level was above my knee in my home.
On the streets, the water was deeper than my height.
We took refuge, and we were only able to come back home on the 5th,
and we were only able to sleep back at home on the 11th,
after much cleaning, although it would take longer to restore the house to pre-disaster conditions.

This city suffered from heavy rain,
citizens who were religious but godless and ungrateful,
and a governor who only cared about looking good.
This city was /cursed/.
It was /doomed/.

I saw the flood as a gift from God to hasten my spiritual progress.
The flood presented a perfect occasion to meditate.
* Mozilla Firefox
- Scrolling problems in 68.4.1esr (Debian 10)
  - <2020-01-20> Rich editors (such as those in Confluence and Wikipedia) are affected by this https://bugzilla.mozilla.org/show_bug.cgi?id=1577058
  - <2020-01-20> Defect: "overflow-y: scroll" disables scrolling with PageDown/PageUp; an example affected page is https://lispcookbook.github.io/cl-cookbook/process.html
