#+TITLE: Gaming
#+DATE: 2017-06-27 01:00 +0700
#+PERMALINK: /game.html
* What should a game be?
A game should be a playground for transfer learning by intelligent agents.

A game should teach [[https://en.wikipedia.org/wiki/Transferable_skill][transferable skill]] to the brain.

A game should be a virtual world for transfer learning.
A game should model at least some aspect of reality.

A game should be a fun education.

The game designer should want to teach something.

The game player should want to learn something.

Their wants should coincide.

A game should impart knowledge by narration.

A game should stimulate the body or the mind or both.

A game should be fun.

A game is basically a playable story.
There is role-play in every game.
You play as an agent (a being that can cause things).

"An /abstract strategy game/ is a strategy game in which the theme is not important to the experience of playing."
 [fn::https://en.wikipedia.org/wiki/Abstract_strategy_game]

Before having an immersive graphics, a game first should have something to teach the player.

A story should /emerge/ from the game mechanics, not be built-in.
* Replay value, fun, boredom
** How do we increase replay value?
The game with the biggest possible replay value is real life.
One hardly gets bored of real life.

Thus, if we integrate our game and real life,
then our game will have the biggest possible replay value.
** How long before a game gets boring?
My Steam data says that a game usually bores me after 20 hours.
** Why does a game get boring?
Why does anything get boring?

Why are we bored?

Is boredom the opposite of fun?
* Why play games?
Transfer learning.

It's fun.
* Why not play games?
- It wastes time.
- My older self just feels less fun from playing games.
* How do we make good games?
  - The best game isn't the one with the best graphics.
  - The challenge is how to get the player immersed with minimal resources.
  - All games eventually bore the player.
  - Hypothesis: The only reason a player stays is that the player
    resonates with the alternate identity built by the game.
  - Hypothesis: the games you pick reflect who you want to be.
  - Some games are even useful.

    - Serious games.
    - [[https://en.wikipedia.org/wiki/Human-based_computation_game][Wikipedia: Human-based computation game]], game with a purpose
* What do games teach you?
** Factorio
- The game is practically over when you have 50 laser turrets.
- I'm bored after 72 hours into the game.
  This is excellent.
  Usually I'm bored after about 20 hours.
** Go
What does Go teach me?

One who chases two rabbits catches neither.

Go is about compromise.
If you try too hard to defeat your enemy, you will defeat yourself.
** Freeciv
What does Freeciv teach me?
- Defense is easier than attack.
  This is even more true behind city walls.
- If A and B are at war with each other, then C can surpass both of them.
- It is better to expand to another untouched land
  than to try to recapture a city taken by the enemy.
  But I am consumed by my desire for revenge,
  to take back what was mine, and to revenge by inflicting greater misery than what was inflicted on me.
  I have a desire to own everything that I make.
- War takes a lot of resources and has a huge opportunity cost.
** Other
- SimCity 4
- City: Skylines
  - I uninstalled it to free disk space.
- Endless sky
  - The game is practically over when you can build 50 haulers;
    you can kill anything as long as your fleet gathers around you.
  - It's free and open-source.
- Prison architect
  - Get 200 low risk prisoners into a holding cell or dorm,
    build several parole rooms,
    and profit a lot.
- Battle of Wesnoth
- Freeciv, call to power
- Freecol, colonization
- Romance of the three kingdoms
- SimCity 4, LinCity NG
- Constructor, mob rule
- Red alert
- Sim Tower
- Axis and allies, TripleA
- Simutrans, transport tycoon
  - But I hate the GUI.
- Liquid war
- Grand theft auto: Vice city
- Board games
  - Abstract strategy board games
    - Chess
    - Wéiqí, go, baduk
    - No point playing abstract strategy board games anymore. AI has beaten humans. Find something else.
- Endgame: singularity
  - The game is pretty much over as soon as you have quantum computers.
** Other interesting games I don't play
- Metal gear solid
  - MGS 3 snake eater has the best stories
  - MGS 4 is more like a movie than a game
  - MGS 5 the phantom pain is that way because Konami understandably chooses money over Kojima
    - Konami is a company
      - Every company is for-profit, or dies
        - but they cut out 1 chapter from MGS 5
- The /Yakuza/ series
  - dark comedy, very good story writing
  - should ring a bell for Kitano Takeshi (Beat Takeshi) fans
- I was thinking about buying "Kerbal Space Program", but now I'm sure that I'm not buying it.
  - [[https://www.youtube.com/watch?v=WCLbUD_aubQ][New EULA Makes KSP Spyware? - Kerbal Space Program Terms of Service Steal Private Information]]
** Game design
  - "If everyone likes your game but no one loves it, it will fail." (Mark Rosewater)
    - https://www.reddit.com/r/DestinyTheGame/comments/7e6wqs/if_everyone_likes_your_game_but_no_one_loves_it/
  - Designing a game is hard.
  - Replay is an architecturally significant requirement.
  - It's more straightforward to develop an enterprise application than a game.
    - When developing an enterprise application,
      you have some idea about what you are going to make,
      the end result, the goal.
    - When developing a game, it's too free.
      The requirement is very abstract: "be fun".
** <2019-04-10> FreeOrion
Turn-based Space strategy (4X games)

https://www.freeorion.org/index.php/Space_Strategy_Games

Some terminology:
- http://askanastronomer.org/bhc/2015/10/05/hierarchy-of-the-universe/
- https://www.syfy.com/syfywire/there-is-a-hierarchy-to-the-universe

Two people don't like star lanes.[fn::http://www.spacesector.com/blog/2009/07/freeorion-a-free-open-source-4x-space-strategy-game/]
But without star lanes, there are no supply lines.
But we can replace supply lines with supply circles (radius).

Reason for star lanes: Hard to program the AI.[fn::https://www.freeorion.org/index.php/FAQ#Why_not.3F]

How about hexagonal tiles like Wesnoth?

"Micromanagement is not fun."[fn::https://www.spacesector.com/blog/2009/08/interview-with-freeorions-programming-lead-zach-laine/]
* What are some game ideas?
** Airflow simulator
- computational fluid dynamics
- input:
  - a room
  - airflow requirements
- output:
  - placement of fans
* Should we use hexagonal tiles in turn-based strategy games?
Why?
Why not?
(Unanswered.)
* Why are games fun?
Rimworld and Crusader Kings 2 are fun because wacky stories arise from gameplay.

"Crusader Kings II's community is hilarious when taken out of context"[fn::https://www.destructoid.com/crusader-kings-ii-s-community-is-hilarious-when-taken-out-of-context-514623.phtml]

Crusader Kings 2 brings out the dark side of humans.
* <2018-11-26> Fix male fighting game characters now!
Male fighting game characters are too big, too muscular, too unsightly, too monstrous, too unproportional, too unfappable.
Every male characters degrade into a generic steroid hunk.

Tekken 3 has better character proportions than Tekken 7.

Street Fighter has been offending this sensibility for even longer than Tekken has.

The men are proportional in Tekken 3.
They get a little bit more muscles in Tekken 4.
They get some more muscles in Tekken 5.
They begin to look like Street Fighter characters in Tekken 6.
They all use steroid in Tekken 7.

Compare Heihachi.
There is no fucking way an average Japanese martial-artist tycoon grandpa would get that ripped without steroids.

Compare Hwoarang.
There is no fucking way an average non-bodybuilding Korean taekwondoist would get that ripped without steroids.

The same goes on for Jin, Law, etc.

King is OK.
He's an American wrestler.
It makes sense for people that big to be a wrestler.
They stand 6 feet without even trying.
Genetics.
Watch WWE.
