#+TITLE: Toward a curriculum for geometry
#+DATE: 2020-01-26 00:00:00 +0700
* Syllabus
- Geometry /with drawing/.
  - Understand /two-dimensional Euclidean geometry/.
  - Understand /three-dimensional Euclidean geometry/.
- Geometry /without drawing/.
  - Generalize it to /more dimensions/.
  - ? symmetries
  - Do geometry with /real numbers/, functions, calculus, analysis.
  - Understand /coordinate systems/.
  - Understand /coordinate transformations/.
  - Generalize it to /non-Euclidean geometry/.
    - Rationale: This is after analytic geometry because coordinate systems facilitate discussing non-Euclidean geometry.
    - Generalize /straight lines/ to /geodesics/.
  - Describe /curved spaces/ with algebra.
  - Understand /metric tensors/.
* Two- and three-dimensional Euclidean geometry
** Spaces, metrics
- A [[https://en.wikipedia.org/wiki/Space_(mathematics)][space]] (a mathematical space) is a set of points.
- A /point/ is an element in a set.
- "[[https://en.wikipedia.org/wiki/Metric_(mathematics)][Metric]]" is another term for "distance".
  - We write \(d(x,y)\) to mean "the /distance/ between point \(x\) and point \(y\)".

| geometry | set theory |
|----------+------------|
| space    | set        |
| point    | element    |
** Circles, pi, angles, radian
- A /[[https://en.wikipedia.org/wiki/Circle][circle]] with center \(c\) and radius \(r\)/ is \( \SetBuilder{x}{d(c,x) = r} \)
  (the set of every point whose distance from \(c\) is \(r\)).
  - A [[https://en.wikipedia.org/wiki/Circular_sector][/sector/]] is ...
- [[https://en.wikipedia.org/wiki/Pi][\( \pi \)]] is the ratio of a circle's circumference to its diameter.
  - All circles have that ratio.
  - The first few digits of π are 3.141659...
  - π is sometimes approximated as 22/7.
- An [[https://en.wikipedia.org/wiki/Angle][/angle/]] is ...?
- An /angle/ may be thought of as one revolution, half revolution, quarter revolution, 3/4 revolution, etc.,
  but [[https://en.wikipedia.org/wiki/Radian][/radian/]] is the natural unit for angles.
  - 360 degrees = 2π radian = 1 revolution
- Understand [[https://en.wikipedia.org/wiki/Radian#Advantages_of_measuring_in_radians][why]][fn::<2020-01-26>] radian is the natural unit for angles.
- Circle, sector, angle, congruence
  - Consider a circle of radius \(r\).
  - Consider a sector of angle \(\alpha\) in that circle.
  - The circumference of that sector is \( r \cdot \alpha \).
- An angle is the radius-independent "size" of a sector.
- An angle is an equivalence relation between sectors.
** Basic shapes
- A [[https://en.wikipedia.org/wiki/Polygon][/polygon/]] (an \(n\)-gon) is a shape with \(n\) vertices / edges / internal angles.
  - A /vertex/ is a point.
  - An /edge/ is a straight line that connects two vertices.
  - An /internal angle/ is ...
- A [[https://en.wikipedia.org/wiki/Triangle][/triangle/]] is a shape with three vertices / three edges / three internal angles.
  - triangle = three-angle
  - quadrangle = four-angle, etc.
- A /circle/ is \( \SetBuilder{x}{d(c,x) = r} \) (see above).
** Basic solids
- A /sphere/ is \( \SetBuilder{x}{d(c,x) = r} \).
  - A [[https://en.wikipedia.org/wiki/Sphere][sphere]] is the surface of a ball.
** Right triangles and trigonometry
- A /right triangle/ is a triangle with one right angle.
  - The /hypothenuse/ is the side across the right angle.
- The [[https://en.wikipedia.org/wiki/Pythagorean_theorem][Pythagorean theorem]] relates the length of the sides of every right triangle.
- [[https://en.wikipedia.org/wiki/Trigonometry][Trigonometry]]
  - [[https://en.wikipedia.org/wiki/Trigonometric_functions][Trigonometric functions]]
    - ? sine of an angle, cosine of an angle, tangent of an angle, ...
** Euclidean vectors
- An /[[https://en.wikipedia.org/wiki/Euclidean_vector][Euclidean vector]]/ is something with magnitude and direction.
- Understand vector addition.
- Understand vector negation.
- Understand point--vector addition.

| operation   | left argument | right argument | result |
|-------------+---------------+----------------+--------|
| addition    | vector        | vector         | vector |
| addition    | point         | vector         | point  |
| subtraction | vector        | vector         | vector |
| subtraction | point         | point          | vector |

- Derive subtraction from addition and negation.
  - Subtraction can be derived from addition and negation: \(x-y = x+(-y)\).
  - Negation: \(-x\) is something such that \(x+(-x) = 0\).
  - If \(p+v=r\), then, subtract both sides by \(v\) to get \(p=r-v\).
* More dimensions
** Modeling physical space as a three-dimensional Euclidean space
There are two different meanings of "space".
Physical space is often thought of as the volume occupied by objects.

Most likely, you already understand a three-dimensional Euclidean space,
because it is your internal mental model of the space around you.

An [[https://en.wikipedia.org/wiki/Euclidean_space][Euclidean space]] is a set of points, not a set of coordinates.

We usually draw a point as a dot, but a point is a zero-dimensional geometric object that occupies no space at all.

[[https://commons.wikimedia.org/wiki/File:Coord_system_CA_0.svg#][This picture]] may help you visualize a three-dimensional real tuple space.
** Dimension
- The /number of dimensions/ of a space is the /maximum number of mutually orthogonal lines/ that can coexist in that space.
  - For example, we know no way to arrange more than three mutually orthogonal rulers in physical space.
    Therefore, we think our physical space has three dimensions.
- The number of dimensions of every /subset/ of \( \Real^n \) is \(n\).
  - Do not confuse embeddings and subsets.
    - \( \Real^m \) is not a /subset/ of \( \Real^n \) if \( m \neq n \).
  - We do not define \(\Real^0\).
  - We do not define the number of dimensions of the empty set.

How do we know how many /dimensions/ a space has?

We know that a space has dimension \(n\) if we cannot simultaneously place more than \(n\) mutually orthogonal lines in that space.
We infer that our space has three dimensions because we have not found how to arrange more than three mutually orthogonal lines in our space.
For example, if we pick three rulers, we can arrange them so that they are orthogonal to each other.
But, if we pick four rulers, we know no way to arrange them so that they are orthogonal to each other.
That is why we think that space is three-dimensional.
** Orthogonality, perpendicularity
How do we know that two lines are /orthogonal/?
By a protractor?

We know that two lines are orthogonal if all the four angles formed by their intersection are equal.

Other terms for "orthogonal" are "perpendicular" and "at a right angle".
** Relationship between spaces: embedding, projection, homeomorphism
- Understand /embedding/.
  - Example: A line may be embedded in a three-dimensional space.
- Understand [[https://en.wikipedia.org/wiki/Ambient_space][ambient spaces]].
- Understand /projection/.
  - Example: A cube may be projected onto a plane.
  - Understand that /shadows/ can be modeled by geometric projections.
- Understand /homeomorphism/.
** Vector spaces
- A /vector/ is an element of a [[https://en.wikipedia.org/wiki/Vector_space][vector space]].
- See also [[https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)][a brief history of vectors]].
** Hypersolids
- [[https://en.wikipedia.org/wiki/Polygon][polygon]] (many-corner)
  → [[https://en.wikipedia.org/wiki/Polyhedron][polyhedron]] (many-seat)
  → [[https://en.wikipedia.org/wiki/Polytope][polytope]] (many-place)
- shape → solid → hypersolid
- A /line/ is \( \SetBuilder{x}{x = a + tb, ~ t \in \Real} \).
- A /hyperplane/ is \( \SetBuilder{x}{a \cdot x = b} \).
* Geometry with coordinates
- Alternative titles:
  - Geometry with coordinates
  - Geometry with numbers and functions
  - Analytical geometry
** Real tuple spaces
- Conflate an /Euclidean space/ and its corresponding /real tuple space/.
** Cartesian coordinate systems
- See [[https://en.wikipedia.org/wiki/Cartesian_coordinate_system][Cartesian coordinate system]].
- The /Cartesian basis vectors/:
  - \(e_k\) is the zero vector /except/ the \(k\)th element is 1.
  - In two dimensions:
    \begin{align*}
    e_1 &= (1,0)
    \\ e_2 &= (0,1)
    \end{align*}
  - In three dimensions:
    \begin{align*}
    e_1 &= (1,0,0)
    \\ e_2 &= (0,1,0)
    \\ e_3 &= (0,0,1)
    \end{align*}
  - In \(n\) dimensions:
    \begin{align*}
    e_1 &= (1,0,\ldots,0,0)
    \\ e_2 &= (0,1,\ldots,0,0)
    \\ \vdots
    \\ e_n &= (0,0,\ldots,0,1)
    \end{align*}
- Visual interpretation:
  - Interpret a /basis vector/ as a /coordinate axis/.
  - The standard three-dimensional Cartesian coordinate system is [[https://en.wikipedia.org/wiki/Right-hand_rule][right-handed]].
    - With your right hand:
      - Form an L with the thumb and the index finger.
      - Form another L with the index and the middle finger.
      - Then see this table.

#+CAPTION: Standard directions
| direction | right hand finger | XYZ        |
|-----------+-------------------+------------|
| rightward | right thumb       | X positive |
| forward   | right index       | Y positive |
| leftward  |                   | X negative |
| backward  |                   | Y negative |
| upward    | right middle      | Z positive |
| downward  |                   | Z negative |

- Understand the /\(n\)-dimensional Euclidean metric in Cartesian coordinate systems/:
  \[ d(x,y) = \sqrt{\sum_{k=1}^n (x_k-y_k)^2} \]
** Dot product, orthogonality
- In \(n\) dimensions: \[ x \cdot y = \sum_{k=1}^n x_k \cdot y_k \]
- Two vectors \(x\) and \(y\) are /orthogonal/ iff \( x \cdot y = 0 \).
- What is the visual interpretation?
** Coordinate systems and transformations
- A /coordinate system/ is a scheme for naming points with tuples of real numbers.
  - We need to name /all/ points because we need to refer to all of them.
  - A coordinate system is a function whose domain is the set of real \(n\)-tuples and whose codomain is an \(n\)-dimensional space.
    - A coordinate system takes a coordinate tuple and gives a point.
    - The name of a point is a tuple of numbers.
    - A coordinate system over E describes how to /name/ each point in E, how to locate those points.
- See also [[https://en.wikipedia.org/wiki/Analytic_geometry][WP:analytic geometry]].
- Definitions for this section:
  - Let \(C\) be a set of coordinate tuples.
  - Let \(S\) be a space.
  - A /[[https://en.wikipedia.org/wiki/Coordinate_system][coordinate system]]/ for \(S\) is a surjective function \(C \to S\)
    where \(C \subseteq \Real^n\).
  - Let \(s : C \to S\) be a coordinate system.
  - Let \(s' : C' \to S\) be a coordinate system.
  - We may say:
    - $x$ /names/ \(s(x)\).
    - \(x\) /refers to/ \(s(x)\).
    - \(x\) /references/ \(s(x)\).
    - \(x\) is an /\(s\)-name/ of \(s(x)\).
    - \(x\) is a /\(C\)-name/ of \(s(x)\).
    - \(s(x)\) is the /referent/ of \(x\).
    - \(s(x)\) is the \(s\)-/referent/ of \(x\).
    - \(s(x)\) is the \(C\)-/referent/ of \(x\).
- "Coordinate system transformation" means "coordinate transformation".
- A /[[https://en.wikipedia.org/wiki/Coordinate_system#Transformations][coordinate transformation]]/ from \(s\) to \(s'\)
  is a function \(t : C \to C'\) such that \(s(c) = s'(c')\) where \(c' = t(c)\) for all \(c \in C\).
- A coordinate transformation changes the name but preserves the point.
  \begin{align*}
  s(c) &= s'(c') = s'(t(c))
  \\ s &= s' \circ t
  \\ (s')^{-1} \circ s &= t
  \end{align*}
- Linear coordinate systems and linear transformations
  - If \(s\) is linear, then there is a matrix \(E\) such that \(s(x) = Ex\).
  - If \(s'\) is linear, then there is a matrix \(F\) such that \(s'(x) = Fx\).
  - If \(s\) and \(s'\) are linear, then \(t\) is linear, and there is a matrix \(T\) such that \(t(x) = Tx\).
    - \( F^{-1} E = T \)
  - Understand /basis vectors/ (coordinate axes?).
  - Understand /span/.
  - Understand /collinearity/.
  - Understand /linear operators/?
- Do we need non-linear coordinate systems?
- ? covariance and contravariance with respect to what?
- ? curvilinear coordinate systems
- ? curved coordinate systems
** Matrices
- Relationship between matrices, bases (concatenation of basis vectors?), linear system of equations, linear transformations, and linear functions
  - Confusing names: [[https://en.wikipedia.org/wiki/Operator_(mathematics)#Linear_operators][linear operator]],
    [[https://en.wikipedia.org/wiki/Linear_map][linear map]],
    linear function
  - 'However, when using "linear operator" instead of "linear map", mathematicians often mean actions on vector spaces of functions, which also preserve other properties, such as continuity.'
    [fn::<2020-01-26> https://en.wikipedia.org/wiki/Operator_(mathematics)]
** Imagining a three-dimensional Euclidean real tuple space
- Pick three rulers (graduated straightedges), called X, Y, and Z.
- Arrange them so that they intersect at one point (called the "origin") and are at a right angle to each other.
- Extend each ruler infinitely in both directions.
- Then, assume that space is homogenous (is the same everywhere) and isotropic (is the same in all directions).
- To find a point named (x,y,z):
  go right x units in ruler X,
  and then go forward y units in ruler Y,
  and then go up z units in ruler Z.
  Observe that each point has a unique name.
** Euclidean spaces vs real tuple spaces
An Euclidean space is a set of /points/,
whereas a real tuple space is a set of /tuples of real numbers/.
We often conflate them, such as when we say "the point \((x,y,z)\)" to mean "the point /whose coordinates are/ \((x,y,z)\)".

An /Euclidean vector space/ is a set of vectors with Euclidean metric.
A metric is a function that maps each vector to its length.
An Euclidean metric is distance as we know it in everyday situation.

Euclidean distance can be derived from the [[https://en.wikipedia.org/wiki/Pythagorean_theorem][Pythagorean theorem]]
that relates the lengths of the sides of a right triangle.

The three-dimensional-Euclidean distance between a point \(A = (x,y,z)\) and another point \(B = (x',y',z')\) is
written \(\norm{AB}\) or \(d(A,B)\), is defined as:
\begin{align*}
\norm{AB} &= d(A,B)
\\ &= \sqrt{(AB)_1^2 + (AB)_2^2 + (AB)_3^2}
\\ &= d((x,y,z),(x',y',z'))
\\ &= \sqrt{(x'-x)^2 + (y'-y)^2 + (z'-z)^2}
\end{align*}
They are different ways of writing the same thing;
\(d(A,B)\) is "synthetic geometry" style, whereas \(d((x,y,z),(x',y',z'))\) is "analytic geometry" style.
However, without numbers, we cannot express \(d(A,B)\) as a square root, because square root is a numeric operation, not a geometric operation.
We have just witnessed the usefulness of analytic geometry.

The "synthetic geometry" style of computing \(d(A,B)\) is to use a ruler to measure the length.
** Intersection of two spaces
- Understand the intersection of two spaces.
  - Understand /systems of equations/ (/simultaneous equations/).
  - Understand /systems of linear equations/?
    - Understand /matrices/.
  - \( P \cap Q = \SetBuilder{x}{p(x) \wedge q(x)} \)
** Modeling position with coordinates
We pick a point called the /origin/, and pick three directions.
Then, each point in space can be described as a tuple \((x,y,z)\) of three numbers;
that tuple means "From the origin, go \(x\) steps east, \(y\) steps north, and \(z\) steps up."

A tuple is a bunch of numbers.

A coordinate system gives meaning to such tuples.

Cartesian coordinate systems?

A coordinate system is a method of naming every point.

Let \(E^n\) mean the \(n\)-dimensional Euclidean space.

A Cartesian coordinate system is a geometric interpretation of a real tuple space.
Such system uses
a tuple in \(\Real^n\) and three orthogonal axes
to describe a point in \(E^n\).
"Axes" here is plural of "axis", not of "axe".

For an example of a two-dimensional Cartesian coordinate system, see [[https://en.wikipedia.org/wiki/File:Cartesian-coordinate-system.svg?][picture]].
The positive x-axis points right.
The positive y-axis points up.

In three dimensions:
(A picture would be nice.)
** The rectangular coordinate system
\(R(x,y) = x e_1 + y e_2\).

\(R(x) = x_1 e_1 + x_2 e_2\).

In this system, the coordinates are the scalar coefficients in the linear combination of basis vectors.
The coordinates describe how the basis vectors should be linearly combined to form the described vector.

Let \(T : V^2 \to V^2\) be a linear transformation.
Then \(T(R(x)) = T(x_1 e_1 + x_2 e_2) = x_1 \cdot T(e_1) + x_2 \cdot T(e_2) = x_1 e_1' + x_2 e_2' = R'(x) \).
** The polar coordinate system
\(P(r,t) = r e_1 \text{ rotated } t \text{ radians counterclockwise}\).

\section{Locating the same point with different coordinate systems}

Example of coordinate transformation:
The same point in the same two-dimensional Euclidean space
is described by
both the polar coordinates \( (r,\theta) \)
and the rectangular coordinates \( (r \cos \theta, r \sin \theta) \).
The transformation is \( (r,\theta) \to (r \cos \theta, r \sin \theta) \).

What
 \footnote{\url{https://en.wikipedia.org/wiki/Real_coordinate_space}}
 \footnote{\url{https://en.wikipedia.org/wiki/Real_coordinate_space}}
 \footnote{\url{https://en.wikipedia.org/wiki/Mathematical_analysis}}

A \emph{coordinate system} $M : C \to S$ is a surjective mapping from
\emph{coordinate space} $C$ to \emph{target space} $S$.

A \emph{coordinate} is a point in \(C\).
The coordinate system tells us how to get to a point.

The \(n\)-dimensional real coordinate space is $\mathbb{R}^n$.
It is also called the real $n$-space.
A point in the real $n$-space is an $n$-tuple of real numbers $(x_1,\ldots,x_n)$.

$(x,y)$ is the tuple of coordinates,
$x$ is the x-coordinate, and $y$ is the y-coordinate.

Coordinate systems unify geometry and
mathematical analysis.
With coordinates,
we can solve geometric problems by
numbers, calculus, and algebra,
so that computers can
find the intersection of geometric objects
by solving the corresponding system of equations,
and find the size of a geometric object by solving the corresponding integral.
** An example basis?
Imagine a flat sheet of paper.

Draw a point \(A\).

Draw a vector named \(i\), from \(A\), \SI{1}{cm} long, pointing right.

Draw another vector named \(j\), also from \(A\), 1 cm long, but pointing up.

Thus, the vectors \(i\) and \(j\) are /orthogonal/.

Then, we declare the basis
\( e : \Real^2 \to E^2 \) as \( e(x,y) = xi + yj \).

A real tuple space on its own has no geometric meaning.
One way to visualize a real tuple space is a Cartesian coordinate system.
** Spherical coordinate systems
(Why do we bring this up?)
*** Mathematician's heading
To simplify the explanation of the coming spherical coordinate system,
we introduce "heading".

Our definition of heading begins with \ang{0} pointing east (positive x-axis),
and then goes counterclockwise,
so \ang{90} is north (positive y-axis), \ang{180} is west (negative x-axis),
and \ang{270} is south (negative y-axis).

Note that our heading differs from the navigator's heading,
which begins with \ang{0} pointing north and then goes clockwise.
 \footnote{\url{https://en.wikipedia.org/wiki/Cardinal_direction\#Additional_points}}
*** The spherical coordinate system
The spherical coordinates \((r,a,b)\) mean
"set heading to \(a\), set elevation to \(b\), and then go the distance \(r\)".

The spherical coordinate system adds another angle component to the polar coordinate system.

We now describe how to map the spherical coordinates \(S(r,a,b)\) to Cartesian coordinates \(C(x,y,z)\).
The slogan to remember is that \(S(r,a,b)\) means
\enquote{set heading to \(a\),
set elevation to \(b\),
and then go the distance \(r\)}.
Another slogan is \enquote{face east, turn your head left by angle \(a\),
turn your head up by angle \(b\), and then look at distance \(r\)}.

Let's read slower as we imagine the drawing.

Let \(O\) be the center of both the spherical coordinate system and the Cartesian coordinate system.
Let their centers coincide.

A negative angle \(-a\) means the angle \(a\) but in the reverse direction.

Draw the point \(D\) at \(C(r,0,0)\),
which means that \(D\) lies on the positive x-axis,
at distance \(r\) from \(O\).

With the positive z-axis as the axis of rotation,
rotate the vector \(OD\), by angle \(a\) toward the positive y-axis
(or toward the negative y-axis if \(a\) is negative).
Call the resulting vector \(OE\).
Thus, the point \(E\) is at \(C(r \cos a, r \sin a, 0)\),
which is still on the xy-plane.

Then, rotate the vector \(OE\), by angle \(b\),
out of the xy-plane, toward the positive z-axis
(or toward the negative z-axis if \(b\) is negative).
Call the resulting vector \(OF\).

Then \(F\) is the point described by \(S(r,a,b)\).
*** Relationship with Cartesian coordinate systems
Let's say that the point \(F\) is at \(S(r,a,b)\), which is equal to \(C(x,y,z)\).
By the definition of rotation and the congruence of triangles,
we can convert spherical coordinates to Cartesian coordinates as follows:
\begin{align}
    x &= r \cos a \cos b
    \\
    y &= r \sin a \cos b
    \\
    z &= r \sin b
\end{align}

We can convert Cartesian coordinates to spherical coordinates as follows:
\begin{align}
    r &= \sqrt{x^2 + y^2 + z^2}
    \\
    \tan a &= y/x
    \\
    \sin b &= z/r
\end{align}
but we have to pick the angles that make the signs correct.

Thus, we have just explained what is meant by the slogan
\enquote{set heading to \(a\),
set elevation to \(b\),
and then go the distance \(r\)}.
*** Which spherical coordinate system?
Note that our \(b\) is elevation, not azimuth.
The relationship between elevation and azimuth is
\[
    \text{azimuth} = \ang{90} - \text{elevation}.
\]

If the elevation is zero, then the spherical coordinate system reduces
to the polar coordinate system on the xy-plane.
That method embeds the polar coordinate system into the xy-plane.
Thus the angle \(a\) is called heading angle, polar angle, or longitude.
The angle \(b\) is called elevation angle or latitude.

Azimuth is angle from zenith.
In this case, zenith is the z-axis.

ISO standard?
Azimuth?
Elevation?

What\footnote{\url{https://en.wikipedia.org/wiki/Spherical_coordinate_system}}
** ? Converting polar coordinate tuples to rectangular coordinate tuples
Both the rectangular coordinate $(r\cos\theta, r\sin\theta)$ and the polar coordinate $(r,\theta)$
describe the same point in two-dimensional Euclidean space.
\[
R(r\cos\theta, r\sin\theta) = P(r,\theta)
\]

A point in a space can have different coordinates in different coordinate systems.
* Describing curved spaces
- Understand how to /algebraically/ describe a /curved space/.
  - Example:
    - Consider a circle with origin \(O = (0,0)\) and radius \(r\).
    - Its /analytic-algebraic/ description is \( \SetBuilder{(x,y)}{x^2+y^2=r^2} \).
    - Its /synthetic-algebraic/ description is \( \SetBuilder{x}{d(O,x) = r} \).
- Understand two-dimensional geometry: line, circle, square.
- Understand three-dimensional geometry: plane, sphere, cube.
- Understand higher-dimensional geometry: hyperplane, hypersphere, hypercube, "hyper-" + <the name of a three dimensional object>.
* Differential geometry and non-Euclidean geometry
- Understand that a /manifold/ is a /locally Euclidean space/.
- Understand /tangent spaces/.
- Understand /curvature/.
  - Understand /osculating circles/ (kissing circles).
- A /[[https://en.wikipedia.org/wiki/Manifold][manifold]]/ is a "space that locally resembles Euclidean space near each point".
- The /[[https://en.wikipedia.org/wiki/Tangent_space][tangent space]]/ of \(S\) at \(p\), written \(T_p S\),
  is the vector space of every vector that is tangent to \(S\) at \(p\).
** Manifold, chart, atlas, local coordinate system?
- A /[[https://en.wikipedia.org/wiki/Atlas_(topology)][chart]]/ (a /coordinate chart/) for \(S\)
  is a [[https://en.wikipedia.org/wiki/Homeomorphism][homeomorphism]] between a subspace of \(S\) and a subspace of an Euclidean space.
- An /atlas/ is a collection of charts.
- "There are ways of describing curves without coordinates [...]"[fn::<2020-01-26> https://en.wikipedia.org/wiki/Coordinate_system]
* Appreciating various approaches
** Appreciating synthetic geometry
- A circle, a sphere, a square, and a hypersphere have the /same description/ \( \SetBuilder{x}{d(c,x) = r} \) but /different metrics/:
  - A circle is a generalized circle in two-dimensional Euclidean metric space.
  - A sphere is a generalized circle in three-dimensional Euclidean metric space.
  - A hypersphere is a generalized circle in \(n\)-dimensional Euclidean metric space.
  - A square is a generalized circle in two-dimensional [[https://en.wikipedia.org/wiki/Taxicab_geometry][taxicab]] metric space.
** Appreciating analytic geometry
A coordinate system marries points and numbers,
so that we can refer to every point as easily as we manipulate numbers.
This enables computers to do geometry.
This enables geometry with calculator without drawing.
This speeds up computation.
This enables [[https://en.wikipedia.org/wiki/Analytic_geometry][analytic geometry]].
This enables the application of the mathematical technology named "differential calculus" to geometry.
This enables us to think more precisely about geometry.

Analytic geometry is the usage of coordinate systems for thinking about spaces?

Analytic geometry can be thought of doing geometry by manipulating numbers instead of by drawing shapes.

With analytic geometry, we can describe shapes using real numbers.

John L. Bell sums it up: "The power of analytic geometry derives very largely from the fact
that it permits the methods of the calculus, and, more generally, of
mathematical analysis, to be introduced into geometry."
 [fn::page 1 in "Two Approaches to Modelling the Universe: Synthetic Differential Geometry and Frame-Valued Sets" by John L. Bell
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.114.1930&amp;rep=rep1&amp;type=pdf]
* Motivating stress tensor
See [[https://en.wikipedia.org/wiki/Stress_(mechanics)][Wikipedia]].

Generalize
/uniaxial normal stress/ \( \sigma = F/A \)
and /simple shear stress/ \( \tau = F/A \)
to [[https://en.wikipedia.org/wiki/Cauchy_stress_tensor][Cauchy stress tensor]]
* Invariants
Let \(\phi : D \to C\) be a function.

Let \(T : D \to D\) be a function, usually called a "transformation".

We say
"\(\phi\) is /unaffected/ by \(T\)"
or "\( \phi \) is /\(T\)-invariant/"
or "\( T \) is an /invariant/ (a /symmetry/) of \( \phi \)"
iff, for all \(x \in D\):
\[ \phi(x) = \phi(T(x)) \]

Here are some examples of invariants.

Let \( Tx = x + c \) represent translation.

Example:
If \(\phi(x,o,r)\) means "\(x\) is a point on a circle with center \(o\) and radius \(r\)",
then \(\phi(x,o,r) = \phi(Tx,To,r)\).
(A predicate is a function whose codomain is the set of booleans.)

Example:
If \(V\) is a vector space, then \(\SetBuilder{Tv}{v \in V} = V\).
If we follow the "auto-lifting" convention, we can write the equation more prettily as \( TV = V \).

Example:
Even functions exhibit mirror symmetry.
(A function \( f \) is /even/ iff \( f(x) = f(-x) \) for all applicable \(x\).)

Example:
Periodicity is a special case of translation-invariance.
(A function \(f\) has /period/ \(p\) iff \(p\) is the smallest positive number such that \( f(x+p) = f(x) \) for all applicable \(x\).
A function is /periodic/ iff it has a period.)
* Symmetries
Example: let \(S\) be the set of points of an unlabeled square.

Let \(T\) be a rotation about the square's center by a right angle.

We write \(TS\) to mean "the result of rotating \(S\) about its center by a right angle".

We write \(TS = S\) to mean "rotating \(S\) about its center by a right angle produces \(S\) itself".
