#+TITLE: Toward a curriculum for geometry
#+DATE: 2020-01-26 00:00:00 +0700
\(
\newcommand\der{\operatorname{der}}
\newcommand\Der{\mathrm{D}}
\newcommand\dd{\operatorname{d}}
\newcommand\ang[1]{#1^\circ}
\newcommand\parenthesize[1]{\left(#1\right)}
\newcommand\dif{\mathrm{d}}
\newcommand\Dif{\Delta}
\)
* Syllabus
- [[file:geometry-1.html][Geometry 1: Axioms and drawings]]
  - Understand metric spaces and normed vector spaces.
    - Derive a /metric space/ from a /normed vector space/.
      - Understand that the /subtraction of two points/ produces a vector.
  - Understand /ambient spaces/.
  - Understand /two-dimensional Euclidean geometry/.
    - right triangles, Pythagorean theorem, trigonometry, trigonometric functions
  - Understand /three and more/ dimensions.
  - Understand /transformations/, /symmetries/, and /invariants/.
- [[file:geometry-2.html][Geometry 2: Coordinates]]
  - More real numbers, more algebra, less drawing.
  - Understand /coordinate systems/.
    - Understand the correspondence between /Cartesian coordinate systems/ and Euclidean spaces.
  - Find the intersection of two shapes in two different ways: /graphically/ and /algebraically/.
    - Understand that both ways have the same meaning and give the same result.
  - Understand non-Cartesian coordinate systems: polar, spherical.
  - Understand /coordinate transformations/.
  - See also [[https://en.wikipedia.org/wiki/Analytic_geometry][WP:analytic geometry]].
- [[file:geometry-3.html][Geometry 3: Curves]]
  - Describe these things synthetically, parametrically, and algebraically:
    - curves
    - hypersurfaces
    - curved spaces
- [[file:geometry-4.html][Geometry 4: Spheres]]
  - local differential geometry
  - local coordinate system
  - Navigate the Earth while formulating differential geometry.
  - spherical geometry for introducing non-Euclidean geometry
    - Generalize /straight lines/ to /geodesics/.
    - Understand /local differential geometry/.
  - Generalize spherical geometry to differential geometry on arbitrary manifolds.
    - It readily generalizes.
    - Use a sphere such as the idealized Earth as a manifold to concretely motivate differential geometry.
  - Motivate local metric
    - The length of a great circle
* Appreciating various approaches
** Appreciating synthetic geometry
- A circle, a sphere, a square, and a hypersphere have the /same description/ \( \SetBuilder{x}{d(c,x) = r} \) but /different metrics/:
  - A circle is a generalized circle in two-dimensional Euclidean metric space.
  - A sphere is a generalized circle in three-dimensional Euclidean metric space.
  - A hypersphere is a generalized circle in \(n\)-dimensional Euclidean metric space.
  - A square is a generalized circle in two-dimensional [[https://en.wikipedia.org/wiki/Taxicab_geometry][taxicab]] metric space.
** Appreciating analytic geometry
A coordinate system marries points and numbers,
so that we can refer to every point as easily as we manipulate numbers.
This enables computers to do geometry.
This enables geometry with calculator without drawing.
This speeds up computation.
This enables [[https://en.wikipedia.org/wiki/Analytic_geometry][analytic geometry]].
This enables the application of the mathematical technology named "differential calculus" to geometry.
This enables us to think more precisely about geometry.

Analytic geometry is the usage of coordinate systems for thinking about spaces?

Analytic geometry can be thought of doing geometry by manipulating numbers instead of by drawing shapes.

With analytic geometry, we can describe shapes using real numbers.

John L. Bell sums it up: "The power of analytic geometry derives very largely from the fact
that it permits the methods of the calculus, and, more generally, of
mathematical analysis, to be introduced into geometry."
 [fn::page 1 in "Two Approaches to Modelling the Universe: Synthetic Differential Geometry and Frame-Valued Sets" by John L. Bell
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.114.1930&amp;rep=rep1&amp;type=pdf]
* Motivating stress tensor
See [[https://en.wikipedia.org/wiki/Stress_(mechanics)][Wikipedia]].

Generalize
/uniaxial normal stress/ \( \sigma = F/A \)
and /simple shear stress/ \( \tau = F/A \)
to [[https://en.wikipedia.org/wiki/Cauchy_stress_tensor][Cauchy stress tensor]]
* Bibliography
