#+TITLE: Geometry 2: Coordinates
#+DATE: 2020-01-26 00:00:00 +0700
* Real tuple spaces
- Conflate an /Euclidean space/ and its corresponding /real tuple space/.
  - Difference:
    - An Euclidean space is a set of /points/.
    - A real tuple space is a set of /tuples of real numbers/.
* Coordinate systems
** Defining coordinate systems
- A /coordinate system/ is a scheme for naming points with tuples of real numbers.
  - We need to name /all/ points because we need to refer to all of them.
  - A coordinate system is a function whose domain is the set of real \(n\)-tuples and whose codomain is an \(n\)-dimensional space.
    - A coordinate system takes a coordinate tuple and gives a point.
    - The name of a point is a tuple of numbers.
    - A coordinate system over E describes how to /name/ each point in E, how to locate those points.
- Definitions:
  - Let \(C\) be a set of coordinate tuples.
  - Let \(S\) be a space.
  - A /[[https://en.wikipedia.org/wiki/Coordinate_system][coordinate system]]/ for \(S\) is a surjective function \(C \to S\)
    where \(C \subseteq \Real^n\).
  - We may say:
    - $x$ /names/ \(s(x)\).
    - \(x\) /refers to/ \(s(x)\).
    - \(x\) /references/ \(s(x)\).
    - \(x\) is an /\(s\)-name/ of \(s(x)\).
    - \(x\) is a /\(C\)-name/ of \(s(x)\).
    - \(s(x)\) is the /referent/ of \(x\).
    - \(s(x)\) is the \(s\)-/referent/ of \(x\).
    - \(s(x)\) is the \(C\)-/referent/ of \(x\).
** Conflating a name and its referent
- It is often convenient to conflate a point and its coordinates:
  we often say "the point \((x,y,z)\)" to mean "the point /whose coordinates are/ \((x,y,z)\)",
  in the same way we often say "John" to mean "the man whose name is 'John'".
** Cartesian coordinate systems
- See [[https://commons.wikimedia.org/wiki/File:Cartesian-coordinate-system.svg#][picture]].
- See also [[https://en.wikipedia.org/wiki/Cartesian_coordinate_system][Cartesian coordinate system]].
- The /Cartesian basis vectors/:
  - \(e_k\) is the zero vector /except/ the \(k\)th element is 1.
  - In two dimensions:
    \begin{align*}
    e_1 &= (1,0)
    \\ e_2 &= (0,1)
    \end{align*}
  - In three dimensions:
    \begin{align*}
    e_1 &= (1,0,0)
    \\ e_2 &= (0,1,0)
    \\ e_3 &= (0,0,1)
    \end{align*}
  - In \(n\) dimensions:
    \begin{align*}
    e_1 &= (1,0,\ldots,0,0)
    \\ e_2 &= (0,1,\ldots,0,0)
    \\ \vdots
    \\ e_n &= (0,0,\ldots,0,1)
    \end{align*}
- Visual interpretation:
  - Interpret a /basis vector/ as a /coordinate axis/.
  - Negative X-axis is the opposite direction to positive X-axis, and so on.
  - The standard two-dimensional Cartesian coordinate system:
    #+CAPTION: Standard two-dimensional directions
    | direction | XY         |
    |-----------+------------|
    | rightward | X positive |
    | upward    | Y positive |
  - The standard three-dimensional Cartesian coordinate system is [[https://en.wikipedia.org/wiki/Right-hand_rule][right-handed]].
    - With your right hand:
      - Form an L with the thumb and the index finger.
      - Form another L with the index and the middle finger.
      - Then see these table.
        #+CAPTION: Standard three-dimensional directions
        | direction | right hand finger | XYZ        |
        |-----------+-------------------+------------|
        | rightward | right thumb       | X positive |
        | forward   | right index       | Y positive |
        | upward    | right middle      | Z positive |
** Imagining the two-dimensional Cartesian coordinate system
- Pick two rulers (graduated straightedges), called X and Y.
- Arrange them so that they intersect at one point (called the "origin") and are at a right angle to each other.
- Extend each ruler infinitely in both directions.
- Then, assume that space is homogenous (is the same everywhere) and isotropic (is the same in all directions).
- To find a point named (x,y):
  go right x units in ruler X,
  and then go up y units in ruler Y.
  Observe that each point has a unique name.
** ? The rectangular coordinate system
\(R(x,y) = x e_1 + y e_2\).

\(R(x) = x_1 e_1 + x_2 e_2\).

In this system, the coordinates are the scalar coefficients in the linear combination of basis vectors.
The coordinates describe how the basis vectors should be linearly combined to form the described vector.

Let \(T : V^2 \to V^2\) be a linear transformation.
Then \(T(R(x)) = T(x_1 e_1 + x_2 e_2) = x_1 \cdot T(e_1) + x_2 \cdot T(e_2) = x_1 e_1' + x_2 e_2' = R'(x) \).
** ? The polar coordinate system
\(P(r,t) = r e_1 \text{ rotated } t \text{ radians counterclockwise}\).

\section{Locating the same point with different coordinate systems}

Example of coordinate transformation:
The same point in the same two-dimensional Euclidean space
is described by
both the polar coordinates \( (r,\theta) \)
and the rectangular coordinates \( (r \cos \theta, r \sin \theta) \).
The transformation is \( (r,\theta) \to (r \cos \theta, r \sin \theta) \).

What
 \footnote{\url{https://en.wikipedia.org/wiki/Real_coordinate_space}}
 \footnote{\url{https://en.wikipedia.org/wiki/Real_coordinate_space}}
 \footnote{\url{https://en.wikipedia.org/wiki/Mathematical_analysis}}

A \emph{coordinate system} $M : C \to S$ is a surjective mapping from
\emph{coordinate space} $C$ to \emph{target space} $S$.

A \emph{coordinate} is a point in \(C\).
The coordinate system tells us how to get to a point.

The \(n\)-dimensional real coordinate space is $\mathbb{R}^n$.
It is also called the real $n$-space.
A point in the real $n$-space is an $n$-tuple of real numbers $(x_1,\ldots,x_n)$.

$(x,y)$ is the tuple of coordinates,
$x$ is the x-coordinate, and $y$ is the y-coordinate.

Coordinate systems unify geometry and
mathematical analysis.
With coordinates,
we can solve geometric problems by
numbers, calculus, and algebra,
so that computers can
find the intersection of geometric objects
by solving the corresponding system of equations,
and find the size of a geometric object by solving the corresponding integral.
* Real vectors
- Now that we have Cartesian coordinate systems, we can use real numbers to describe vectors.
- A real vector is a tuple of real numbers.
- A real tuple space conflates points and vectors.
  - A point is a real tuple.
  - A vector is also a real tuple?
* Formulating Euclidean distances with Cartesian coordinate systems
- Understand the /\(n\)-dimensional Euclidean metric in Cartesian coordinate systems/:
  \[ d(x,y) = \sqrt{\sum_{k=1}^n (x_k-y_k)^2} \]

The three-dimensional-Euclidean distance between a point \(A = (x,y,z)\) and another point \(B = (x',y',z')\) is
written \(\norm{AB}\) or \(d(A,B)\), is defined as:
\begin{align*}
\norm{AB} &= d(A,B)
\\ &= \sqrt{(AB)_1^2 + (AB)_2^2 + (AB)_3^2}
\\ &= d((x,y,z),(x',y',z'))
\\ &= \sqrt{(x'-x)^2 + (y'-y)^2 + (z'-z)^2}
\end{align*}
They are different ways of writing the same thing;
\(d(A,B)\) is "synthetic geometry" style, whereas \(d((x,y,z),(x',y',z'))\) is "analytic geometry" style.
However, without numbers, we cannot express \(d(A,B)\) as a square root, because square root is a numeric operation, not a geometric operation.
We have just witnessed the usefulness of analytic geometry.

The "synthetic geometry" style of computing \(d(A,B)\) is to use a ruler to measure the length.
* Dot product, orthogonality
- In \(n\) dimensions: \[ x \cdot y = \sum_{k=1}^n x_k \cdot y_k \]
- Two vectors \(x\) and \(y\) are /orthogonal/ iff \( x \cdot y = 0 \).
- What is the visual interpretation?
* Coordinate transformations
- Definitions for this section:
  - Let \(C\) be a set of coordinate tuples.
  - Let \(S\) be a space.
  - A /[[https://en.wikipedia.org/wiki/Coordinate_system][coordinate system]]/ for \(S\) is a surjective function \(C \to S\)
    where \(C \subseteq \Real^n\).
  - Let \(s : C \to S\) be a coordinate system.
  - Let \(s' : C' \to S\) be a coordinate system.
- "Coordinate system transformation" means "coordinate transformation".
- A /[[https://en.wikipedia.org/wiki/Coordinate_system#Transformations][coordinate transformation]]/ from \(s\) to \(s'\)
  is a function \(t : C \to C'\) such that \(s(c) = s'(c')\) where \(c' = t(c)\) for all \(c \in C\).
- A coordinate transformation changes the name but preserves the point.
  \begin{align*}
  s(c) &= s'(c') = s'(t(c))
  \\ s &= s' \circ t
  \\ (s')^{-1} \circ s &= t
  \end{align*}
- Linear coordinate systems and linear transformations
  - If \(s\) is linear, then there is a matrix \(E\) such that \(s(x) = Ex\).
  - If \(s'\) is linear, then there is a matrix \(F\) such that \(s'(x) = Fx\).
  - If \(s\) and \(s'\) are linear, then \(t\) is linear, and there is a matrix \(T\) such that \(t(x) = Tx\).
    - \( F^{-1} E = T \)
  - Understand /basis vectors/ (coordinate axes?).
  - Understand /span/.
  - Understand /collinearity/.
  - Understand /linear operators/?
- Do we need non-linear coordinate systems?
- ? curvilinear coordinate systems
- ? curved coordinate systems
** ? Converting polar coordinate tuples to rectangular coordinate tuples
Both the rectangular coordinate $(r\cos\theta, r\sin\theta)$ and the polar coordinate $(r,\theta)$
describe the same point in two-dimensional Euclidean space.
\[
R(r\cos\theta, r\sin\theta) = P(r,\theta)
\]

A point in a space can have different coordinates in different coordinate systems.
* Matrices
- Relationship between matrices, bases (concatenation of basis vectors?), linear system of equations, linear transformations, and linear functions
  - Confusing names: [[https://en.wikipedia.org/wiki/Operator_(mathematics)#Linear_operators][linear operator]],
    [[https://en.wikipedia.org/wiki/Linear_map][linear map]],
    linear function
  - 'However, when using "linear operator" instead of "linear map", mathematicians often mean actions on vector spaces of functions, which also preserve other properties, such as continuity.'
    [fn::<2020-01-26> https://en.wikipedia.org/wiki/Operator_(mathematics)]
* Two ways of computing intersection
- There are two ways of computing the intersection of several geometric objects:
  - graphical: draw and see
  - algebraic: manipulate a system of simultaneous equations
- The algebraic way is easier to automate with electronic computers
  and works for all numbers of dimensions.
- Understand the intersection of two spaces.
  - Understand /systems of equations/ (/simultaneous equations/).
  - Understand /systems of linear equations/?
    - Understand /matrices/.
  - The intersection of two spaces contains every point that is common to both spaces:
    \( P \cap Q = \SetBuilder{x}{p(x) \wedge q(x)} \),
    where \(p(x)\) means "point \(x\) is in space \(P\)".
    - space intersection ~ set intersection ~ logical conjunction
** Example: Intersection of several lines
** Example: Intersection of a circle and a line
* Modeling position with coordinates
We pick a point called the /origin/, and pick three directions.
Then, each point in space can be described as a tuple \((x,y,z)\) of three numbers;
that tuple means "From the origin, go \(x\) steps east, \(y\) steps north, and \(z\) steps up."

A tuple is a bunch of numbers.

A coordinate system gives meaning to such tuples.

Cartesian coordinate systems?

A coordinate system is a method of naming every point.

Let \(E^n\) mean the \(n\)-dimensional Euclidean space.

A Cartesian coordinate system is a geometric interpretation of a real tuple space.
Such system uses
a tuple in \(\Real^n\) and three orthogonal axes
to describe a point in \(E^n\).
"Axes" here is plural of "axis", not of "axe".

For an example of a two-dimensional Cartesian coordinate system, see [[https://en.wikipedia.org/wiki/File:Cartesian-coordinate-system.svg?][picture]].
The positive x-axis points right.
The positive y-axis points up.

In three dimensions:
(A picture would be nice.)
* An example basis?
Imagine a flat sheet of paper.

Draw a point \(A\).

Draw a vector named \(i\), from \(A\), \SI{1}{cm} long, pointing right.

Draw another vector named \(j\), also from \(A\), 1 cm long, but pointing up.

Thus, the vectors \(i\) and \(j\) are /orthogonal/.

Then, we declare the basis
\( e : \Real^2 \to E^2 \) as \( e(x,y) = xi + yj \).

A real tuple space on its own has no geometric meaning.
One way to visualize a real tuple space is a Cartesian coordinate system.
