#+TITLE: Increase software engineer productivity?
#+DATE: 2018-04-11 00:00 +0700
#+OPTIONS: ^:nil toc:nil
#+PERMALINK: /increase.html
* Use Gallup StrengthsFinder (CliftonStrengths) to match people and roles?
Too complex?

- The subject pays $50.[fn::https://www.gallupstrengthscenter.com/store/en-us/]
- The subject makes 177 choices in the survey, which takes about an hour.[fn::https://www.gallupstrengthscenter.com/home/en-us/cliftonstrengths-how-it-works]
- The system creates a report that is an ordering of the 34 themes.[fn::https://www.gallupstrengthscenter.com/home/en-us/cliftonstrengths-themes-domains]
  There is a sample report.[fn::https://www.gallupstrengthscenter.com/home/en-us/get-file?fileName=All34Report_DonClifton.pdf&language=en-us]

<2019-05-05>
Ahmad Rizqi Meydiarso told me about Gallup StrengthsFinder.
* Higher-level programming language?
more powerful hardware -> higher-level software abstraction -> higher engineer productivity

There is a limit to productivity, because software has irreducible essential complexity.
But there is still some room to reduce the accidental complexity.
* Distraction room?
A distraction room is where blocked engineers gather and distract each other.
I explain "blocked" below.

When is distraction desirable?

Distraction is desirable when the distracted person encounters a mental block,
and undesirable when the person is in the flow.

A working software engineer can be thought to be in one of two states:
- In the flow: Turning an idea in the mind into reality
- Blocked: Confused, trying to come up with an idea in the mind

When he is in the flow, he should not be distracted.

When he is blocked, he should be distracted.
Sleeping also helps.

A programmer's block is the same as a writer's block:
They don't know what to do next.
In this state, random stimulation and context switching may be good.
* Others? Already done or unlikely?
** Remote work? Less commute?
For seniors?

<2019-05-05>
Sofian Hadiwijaya of Warung Pintar[fn::https://warungpintar.co.id/]
told me that remote working is not suitable for junior employees who need lots of guidance.
** Ergonomic equipments?
Desk, chair, keyboard, screen, etc.?

Comfortable temperature, etc.?
