#+TITLE: Increase software engineer productivity?
#+DATE: 2018-04-11 00:00 +0700
#+OPTIONS: ^:nil toc:nil
#+PERMALINK: /increase.html
* Personal development? Factors intrinsic to the people themselves?
** Use Gallup StrengthsFinder (CliftonStrengths) to match people and roles?
<2019-05-05>
Ahmad Rizqi Meydiarso told me about Gallup StrengthsFinder.
*** <2019-05-05> What is CliftonStrengths?
- The subject pays $50.[fn::https://www.gallupstrengthscenter.com/store/en-us/]
- The subject makes 177 choices in the survey, which takes about an hour.[fn::https://www.gallupstrengthscenter.com/home/en-us/cliftonstrengths-how-it-works]
- The system creates a report that is an ordering of the 34 themes.[fn::https://www.gallupstrengthscenter.com/home/en-us/cliftonstrengths-themes-domains]
  There is a sample report.[fn::https://www.gallupstrengthscenter.com/home/en-us/get-file?fileName=All34Report_DonClifton.pdf&language=en-us]
*** Is it too complex?
Can the 34 themes and 177 choices be reduced further?
This may be an interesting research topic for people in human resource departments and people in psychology majors.
However, "One major concern about considering people as assets or resources is that they will be commoditized, objectified and abused."
 [fn::<2019-05-07> https://en.wikipedia.org/wiki/Human_resources]

Example simplification:
Which would you rather do:
- think or do?
- plan or execute?
- create or operate?
- create or maintain?
- etc.

But we should not ask people about their future, because nobody knows what they will be in the future.
We should ask people about their past,
and extrapolate their past into the future.
** Teach new skills?
** Coach?
** Physical exercise?
Physical exercise increases blood flow to the brain.
* Higher-level programming language?
more powerful hardware -> higher-level software abstraction -> higher engineer productivity

There is a limit to productivity, because software has irreducible essential complexity.
But there is still some room to reduce the accidental complexity.
* Ergonomic equipments?
Desk, chair, keyboard, screen, etc.?

Comfortable temperature, etc.?

* Distraction room?
A distraction room is where blocked engineers gather and distract each other.
I explain "blocked" below.

When is distraction desirable?

Distraction is desirable when the distracted person encounters a mental block,
and undesirable when the person is in the flow.

A working software engineer can be thought to be in one of two states:
- In the flow: Turning an idea in the mind into reality
- Blocked: Confused, trying to come up with an idea in the mind

When he is in the flow, he should not be distracted.

When he is blocked, he should be distracted.
Sleeping also helps.

A programmer's block is the same as a writer's block:
They don't know what to do next.
In this state, random stimulation and context switching may be good.
* Remote work? Less commute?
For seniors?

<2019-05-05>
Sofian Hadiwijaya of Warung Pintar[fn::https://warungpintar.co.id/]
told me that remote working is not suitable for junior employees who need lots of guidance.

Remote work does not mean absence of interaction.

The remote employee must have a good microphone, a good headphone, a good Internet connection, and a rather quiet space.
