#+TITLE: Erik Dominikus's home page
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
* About the author and the website
My name is Erik Dominikus.
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
* Disclaimers
/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to my beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
* Research
Perhaps now you are wondering "What do you have for me?"
How do I answer that?
It depends on your interests.
You may wear multiple hats as I do.
But I wrote this website primarily for myself.
Thus the question becomes "What do I have for myself",
that is "What do I really want", that is, "What is important for me?"
If you have some common goals or interests, then get in touch, drop a comment.
We should join forces to reach our shared goals.
** Meta-research
I am [[file:research.html][looking for ways to research more efficiently]].
** Computing
I am trying to make machines work more for me.

I am [[file:proglang.html][looking for the best programming language]],
some of which may involve [[file:haskell.html][improving Haskell]].
I am [[file:prolog.html][using Prolog]].

I am [[file:publish.html][looking for a publishing system]].
I also write
[[file:emacs.html][Using Emacs and Org Mode]],
[[file:emacsvi.html][Emacs for vi users]],
[[file:writing.html][Writing]],
and [[file:markdown.html][Working around Markdown]].

I am [[file:parse.html][looking for parsing techniques]],
because parsing is the common thing between programming language and publishing system, and I am looking for both.
Meanwhile, I had to understand Brzozowski quotient and set division,
so I wrote [[file:division.html][Generalizing division]].

I am [[file:pnptry.html][trying to understand the P vs NP problem]],
which requires [[file:compute.html][computation]], [[file:model.html][model]], and [[file:logic.html][logic]].
I was motivated by the prize money[fn::one million US dollars http://www.claymath.org/millennium-problems/millennium-prize-problems], but I think my chances are slim.

I am looking for an AI that helps me process data into information.
Thus I write [[file:intelligence.html][Making intelligence]] and
[[file:endo.html][The endofunction model of worlds and agents, and its philosophical implications]].
But I think my chances are slim.

There are some interesting mathematical perspectives.

Boolean metric spaces merge logic and analysis?
How do we define a sensible approximation error?
How do we define the /distance/ between two formulas?

What are these papers?
 [fn::https://arxiv.org/abs/0903.2567]
 [fn::https://www.um.es/beca/papers/Aviles-Algebras.pdf]

The formula \( p \wedge q \) /approximates/ the formula \( p \wedge q \wedge r \).
What is the approximation /error/?
Can we merge approximation theory and propositional calculus?
** Philosophy
I am trying to understand what [[file:model.html][model]] is and what [[file:compute.html][computation]] is.

I am [[file:philo.html][trying to understand the relationship between mind and brain]].

I am [[file:nature.html][trying to understand physics]].

I am [[file:finite.html][looking for a philosophically sound foundation of mathematics]].
It may be finitism.

If people know some basic epistemology (that is, if they can tell apart what they know from what /they think/ they know), then there will be no wars.
Some epistemology should be taught in primary school.
We often assume a lot of things about others.
Most conflicts happen because we assume something wrong about someone else.
** Society
I am looking for a technology that empowers people and liberates people, a technology that makes oppression physically impossible.
I am trying to codify (that is, to express in English) our implicit morality, that is, the implicit moral system that we have evolved.
Thus I write [[file:social.html][Designing the ideal society]].
I thought I could change the world with politics, but now I think politics only wastes time,
and now I think technology is the only hope for making something in the physical-law layer to bypass the convoluted human-made-law layer.
I think law should be principle-based, and justice should be restorative.
I think the world needs only one law: Try not to harm others.
Nobody bothers to fix the broken political systems.
Nobody even bothers to think.
Political systems are too expensive to fix; it is much cheaper to scrap them.

I [[file:usecom.html][use computers]].
I [[file:phone.html][buy a smartphone]] when my old smartphone becomes unusable.
I usually watch YouTube at 2x-3x speed; we can speed it up to 16x[fn::https://www.quora.com/Is-there-a-way-of-watching-YouTube-videos-at-higher-than-2x-speed].

Why users don't use distributed systems:
Users don't care; they want software to just work.[fn::"Decentralized systems will continue to lose to centralized systems until
there's a driver requiring decentralization to deliver a clearly superior consumer experience."
http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html]

I find YaCy[fn::https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html] unusable:
its search result relevance is too far behind Google.
YaCy-related things
 [fn::https://loklak.org/ Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]
 [fn::https://chat.susi.ai/ SUSI.AI Chat - Open Source Artificial Intelligence]
seem to also suffer from usability issues.

We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
The pack might contain things like matrix.org, riot.im.
But why stop there?
Why not make free/libre distributed operating system[fn::https://en.wikipedia.org/wiki/Distributed_operating_system] with all those goodies preinstalled?

Example of federated/decentralized social networks:
Kari Nordmann's comment[fn::https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc]:
"Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo)"

What is a constitution?
Why should people in the 21st century agree with people in the 18th century?
Why should we agree with people born 300 years ago?
We don't even agree with our parents born 30 years ago!
** Software engineering
I am thinking about open-source.
I prefer cooperation to competition.
I write
[[file:opensrc.html][Making contributable open-source projects]],
[[file:community.html][Building online communities]].
I am thinking about maintaining open-source projects.

Sometimes I think about forward software engineering,
such as [[file:softeng.html][making lasting software sooner]].

Sometimes I think about [[file:reveng.html][reverse software engineering]],
such as[[file:ps1.html][Reverse-engineering PlayStation 1 3D games to control the camera]].

I wanted to automate stock trading with my broker which has a stock trading application written in Java 6.
Thus I wrote [[file:rejava.html][Reverse engineering the network protocol used by a Java desktop application]].
But now I think financial economy is just a big Ponzi scheme full of rent-seeking,
full of people who want to get a slice of the pie of real economy without growing the pie of real economy,
full of people who just want to extract value from society without creating value,
people who only take but don't give,
people who only shuffle money around.

I tried to think about [[file:engman.html][managing software engineers]].
I thought about [[file:salary.html][software engineer salary]].

Is software engineering engineering?
What is engineering?

I summarized the [[file:smf.html][Standard MIDI file format]].
I was thinking about making a digital audio workstation, but I changed my mind about music.

Here are some Java stuff.
I used Java back in the days when I lacked self-respect.
Now I recommend Prolog instead of Java.

<2018-08-29>
For Java enterprise/server programming, I recommend Maven instead of Gradle.

This is a command line for production.
Replace variables accordingly.
#+BEGIN_SRC bash
java \
    -Xms$heap_size \
    -Xmx$heap_size \
    -Xloggc:"$gc_log_file" \
    -XX:+PrintGCDetails \
    -classpath 'target/*:target/dependency/*' \
    "$java_main_class" \
    "$@"
#+END_SRC

The GC log is important.
When your application is unexplainably slow, first look at the GC log: does GC take too much time?
Look at the "real" time.

<2018-10-28> Systemd programmers are not competent enough for what they are doing.
 [fn::https://blog.erratasec.com/2018/10/systemd-is-bad-parsing-and-should-feel.html]
 [fn::https://www.reddit.com/r/programming/comments/9rtm1f/systemd_is_bad_parsing_and_should_feel_bad/]

Computers feel slow not because hardware sucks, but because programmers tell it to do stupid things.
Ever-stronger hardware lets more programmers get away with writing ever-shittier software.

If software is a pure art, then its construction shouldn't be time-limited.
A painter doesn't paint with deadlines.
A painting is finished when the painter feels it's finished.
However, a painter, when asked to paint a very specific painting, can estimate how many days it will take.
** Farming
I thought about [[file:subsist.html][starting a farm in the middle of Jakarta]],
but I put it on hold because I felt that the opportunity cost was too high.

The key to farming is to understand ecology, some botany (plant physiology and pathology), and nutrient cycle.

We should care more about phosphate run-off.
Phosphates are vital and non-renewable, like fossil fuel.
The bad news is that there is no cycle bringing back the phosphates from the sea to the land, unlike water with its hydrologic cycle.
** Best place to live?
According to "The Economist"[fn::"Where is the world's most liveable city?", The Economist https://www.youtube.com/watch?v=ylR21fezN7E],
in 2018, Vienna is the most livable city, and it was Melbourne.

The United States of America seems to be the most powerful country on Earth.
I thought America was liberal; it turns out to be socialist.
Also, America has too much frivolous lawsuits[fn::https://www.legalzoom.com/articles/top-ten-frivolous-lawsuits].

How do we measure, perhaps indirectly, the /rationality/ a country?
That is, how do we measure how likely its people think critically?
How do we know which people use their brains?

I am thinking about metrics that may correlate with the quality of life in a country.
Among those metrics are immigration hardness,
passport strength[fn::https://www.passportindex.org/byRank.php],
tax rate[fn::https://en.wikipedia.org/wiki/List_of_countries_by_tax_rates],
press freedom index[fn::https://en.wikipedia.org/wiki/Press_Freedom_Index] (journalist imprisonment rate?),
human freedom index (HFI)[fn::https://www.cato.org/human-freedom-index-new],
most liberal country ranking[fn::https://www.worldatlas.com/articles/the-10-most-liberal-countries-of-the-world.html].
I think tax rate correlates with government size, and smaller government is better,
but some high-tax-rate countries have good HFI.

New Zealand sounds promising.
It has good HFI.

It seems that America has never killed or imprisoned journalists for criticizing people in power.

I think that the country that is the hardest to immigrate into[fn::https://www.investopedia.com/articles/personal-finance/121114/5-hardest-countries-getting-citizenship.asp] may be the best country on Earth.
But I think those developed countries have their own problems.

A strong passport means that other countries believe that the issuer will not export bad people.

I think the solution to the refugee problem is not to take refugees, but to /fix the source country/,
which must have become so messy that millions of people would rather die at sea than stay at home.

Switzerland?

Making a house[fn::https://en.wikipedia.org/wiki/List_of_human_habitation_forms]

It's wise to avoid places with known disaster risks:
- US risky areas:
  - Florida, North Carolina: hurricanes
  - San Francisco, California: earthquakes and soil liquefaction
  - Tornado alley (where?)
- Japan, South Korea, Philippines: typhoons
- Palu earthquake and liquefaction
- Aceh tsunami
- Selat Sunda, Krakatau
- areas in the Ring of Fire[fn::https://en.wikipedia.org/wiki/Ring_of_Fire]
  [fn::South East Asia earthquake map https://cilisos.my/what-protects-malaysia-from-all-these-earthquakes-that-is-happening-in-indonesia/]
- There is much more.
** Journalism
*** Blacklisted untrustworthy news sources
According to https://www.vox.com/platform/amp/policy-and-politics/2018/10/1/17923178/washington-times-seth-rich-aaron-rich-trump-fox-news:
- Washington Times
- FOX News

But Vox isn't entirely trustworthy either.

VICE is questionable.
https://www.reddit.com/r/KotakuInAction/comments/898na9/vice_gets_patreon_to_remove_naomi_wu_who_blasted/

Wikipedia maintains a blacklist of untrustworthy news sources
 [fn::perennial sources with varying trustworthiness https://en.wikipedia.org/wiki/Wikipedia:Identifying_reliable_sources/Perennial_sources]
 [fn::https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2018-12-24/Discussion_report]
*** Some journalist brutal murder cases
Journalists have been brutally murdered in these areas:
- Malta: Daphne Caruana Galizia was car-bombed in 2017. https://en.wikipedia.org/wiki/Daphne_Caruana_Galizia
- Bulgaria: Viktoria Marinova was raped and murdered in 2018.
** Common
Every person should know these things.

Nearsightedness (myopia) is reversible, but it takes years, as it also takes years for the eye to take that much damage.
I think Todd Becker[fn::https://gettingstronger.org/tag/myopia/] writes more clearly than
about D1-D2-D3[fn::Myopia: A Modern Yet Reversible Disease — Todd Becker, M.S. (AHS14) https://www.youtube.com/watch?v=x5Efg42-Qn0]
Jake Steiner[fn::https://endmyopia.org/how-to-finding-active-focus/][fn::https://endmyopia.org/trouble-finding-active-focus-screen/] does,
although they seem to convey the same message.

Crooked teeth can be fixed with orthotropics[fn::https://orthotropics.com/], but it may take years, as orthodontics does anyway.
The problem is that the modern human's jaw does not grow enough due to two reasons:
(1) we don't chew soft modern foods as much as our ancestors chewed their hard foods, and
(2) we have improper tongue posture.
At first it is hard to understand what the tongue posture should be because
we normally don't pay attention to our tongues, but I finally understand it.
Orthotropics makes sense, but Mike Mew seems to have overstepped some boundaries unrelated to orthotropics.[fn::https://orthotropics.com/decision-dr-mike-mew-jonathan-sandler-british-orthodontic-society/]
I understand that it is frustrating when you see something that others don't[fn::https://en.wikipedia.org/w/index.php?title=Ignaz_Semmelweis&oldid=871726873],
but you have to be patient, play the long game, and collect evidence.

Avoid untimely death.
Don't swallow slugs[fn::https://www.dailymail.co.uk/news/article-6352629/amp/Sam-Ballard-dies-eight-years-swallowing-slug.html].
Don't swim in a warm lake[fn::https://en.wikipedia.org/wiki/Naegleria_fowleri].
** Other
*** Ungrouped
I collect [[file:entertain.html][entertainments found on the Internet]].

I [[file:groom.html][somewhat care about appearance]].

I am [[file:world.html][somewhat pessimistic about the 21st century]].

My inquiries often intersect.
[[file:philo.html]] and [[file:intelligence.html]] intersect in modeling, mind, consciousness.
[[file:intelligence.html]] and [[file:social.html]] intersect in trust.
Philosophy of mind + logic meet software engineering + Prolog at "formal concept analysis"[fn::https://en.wikipedia.org/wiki/Formal_concept_analysis].
Philosophy, software engineering, and business modeling meet at "triune continuum paradigm"[fn::"The triune continuum paradigm is based on the three theories:
on Tarski's theory of truth, on Russell's theory of types and on the theory of triune continuum."
https://en.wikipedia.org/wiki/Triune_continuum_paradigm].
I disclaim any understanding.

I was once fleetingly interested in these things:
[[file:art.html][Art]],
[[file:music.html][Music]],
[[file:game.html][Game]].

I occasionally played weiqi[fn::Weiqi is also known as go, igo, baduk. https://en.wikipedia.org/wiki/Go_(game)],
but after AlphaGo[fn::https://en.wikipedia.org/wiki/AlphaGo] beat[fn::https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol] Lee Sedol, I abandoned weiqi and never looked back.
I occasionally played chess, before Deep Blue beat Kasparov[fn::https://en.wikipedia.org/wiki/Deep_Blue_versus_Garry_Kasparov].
I occasionally played poker, before machines took over[fn::https://www.theguardian.com/technology/2017/jan/30/libratus-poker-artificial-intelligence-professional-human-players-competition].
Now I think that games only waste time:
I see no point in doing something that machines can do better than I do.

I am looking for an Indonesian etymology dictionary, which I think is necessary for philosophical analysis of Indonesian laws.
*** From the Internet
If you want to be an altruist, pick activities with high impact-to-effort ratio[fn::https://www.effectivealtruism.org/articles/introduction-to-effective-altruism/].
Find a high-social-impact job suitable for you.[fn::https://80000hours.org/career-quiz/#/]
 [fn::How to find the world's most pressing problems https://80000hours.org/career-guide/most-pressing-problems/]
 [fn::The evidence on how to find the right career for you https://80000hours.org/career-guide/personal-fit/]
 [fn::Evidence-based advice on how to be successful in any job https://80000hours.org/career-guide/how-to-be-successful/]
 [fn::What are the 10 most harmful jobs? https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/]
 [fn::https://hackernoon.com/where-are-the-programmers-who-give-a-shit-87f859f13f75]

Jordan Peterson: responsibility gives life meaning[fn::be competent and dangerous https://www.youtube.com/watch?v=ONK8pGAGT28].

Biohacking?[fn::https://www.theguardian.com/science/2018/sep/21/extreme-biohacking-tech-guru-who-spent-250000-trying-to-live-for-ever-serge-faguet]

Lyrebird can mimic sounds uncannily.
Laser guns, drills, hammers, camera shutters.

Genetics is the biggest factor in how far we can build our body.[fn::https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting]
*** Important vs urgent
Something is important if not doing it is fatal.
Breathing, eating, drinking water.
Having some in-demand high-paying skills.
Being useful.

Something is urgent if it urges you to do it, if you feel an urge (strong desire) to do it.
Eating sugar, fucking, shitting.
*** Senior, lead, manager, director
Etymology clears up the differences.

Senior = older.[fn::https://www.etymonline.com/word/senior]

Lead = to show the way.[fn::https://www.etymonline.com/word/lead#etymonline_v_6615]

Manage = handle or train a horse.[fn::https://www.etymonline.com/search?q=manage]

Handle = "touch with the hands, hold in the hands, fondle, pet"[fn::https://www.etymonline.com/word/handle]

A director /directs/.
Directors knows what they want.
*** Birth is not survival.
To survive is to keep/continue living.

Survival of the individual vs survival of the species?

Survivalism is compatible with antinatalism.
*** Flat Earth is a social issue, not a scientific issue
Flat-Earthers are merely looking for friends in this extremely power-unbalanced world.
They have trust issues with authorities.
I am also looking for friends who share my beliefs, and I also have trust issues with authorities,
but the difference between a Flat-Earther and me is that
I have trust issues with political authorities,
whereas a Flat-Earther has a trust issue with scientific authorities.
Thus, although I do not believe in Flat Earth,
a Flat-Earther and I have more commonalities than differences.
The same is true with Holocaust deniers and climate change deniers:
it is a trust issue with some authorities.

How did such trust issues arise?
Our parents, for good reason, taught us not to trust strangers.
Thus it is a logical consequence that we don't trust authorities: they are strangers!
We don't know who they are, and yet they suddenly come down telling us what is right and what is wrong.

How can two strangers be friends?
By physical closeness (being at nearby location and time) and by mental closeness (having similar ideas and beliefs).
How do we make sure that the people in power are not strangers?
It is not feasible for one person to meet millions of people.
Thus I have this corollary: /having power over more people always begets more trust issues/, simply because it is harder for the authority to not be strangers with its subjects.
Perhaps it's just that power today is too centralized.
But mass media enables centralization of power;
the authority uses mass media to make its subjects feel that the authority is familiar.
But mass communication is one-way communication.
How does one-way communication build trust?
In the same way an actor builds his fanbase of fans who trust him.
First, the would-be fans have to fall in love with him from afar, be it due to his handsomeness, his charisma, or any aspect of him that resonates with them.
But then this fanbase has to be maintained, and it is physically impossible for an actor with a million fans to be close to all of them.
Therefore what is required to maintain the fanbase is a /mass illusion/ of closeness:
the actor has to behave in such a way that makes his fans /perceive/ that he cares about /all/ of them,
whereas he can only /actually/ care about /few/ of them.
The mass media only has to show the actor's interacting with /a few/ of his fans, in order to make /all/ of his fans feel that they have been interacted with.
This is not because he is evil; he is just constrained by the laws of physics.
This technique is a double-edged sword:
it can be used to maintain political stability,
but it can also be used to lie to millions of people.
We need to teach people epistemology so that they can tell apart what they know and what they think they know.
Mass media does not give any knowledge; it only gives an illusion of knowledge.
Reading the news does not make us know anything; it only makes us think that we know.
How do I know there is a disaster somewhere?
I do not, because I can only know things near me, and it is not feasible for me to verify every claim in the news; I am merely assuming that the news is honest.
Epistemology is more important than ever in this age of falsehood.

There are some simple experiments that we can carry out to determine the curvature of the Earth.
Reality itself has told us through those experiments that the Earth is not flat; it is up to us to listen to reality or ignore it at our own peril.
We will make costly mistakes if we make antennas and satellites with Flat Earth theory.

The theory makes sense and is a fine scientific theory: it is falsifiable.
What does not make sense to me is the refusal to change one's beliefs despite being otherwise told by reality.
* Music
I played piano in the band [[file:nomads.html][The Nomads]] (an Indonesian band, not the Swedish band).
However, I quit being a performer on 2018-12-23, less than a year after joining the band, because I hate inhaling cigarette smoke in venues and I hate carrying pianos to venues.
I am no longer a pianist.
I am now a composer with an asset mindset.

I have a love-hate relationship with music.
Music wastes time, but as I distance myself from it, something always tempts me to come back.

Kids should learn art to stimulate the brain, but they should not grow up to be artists.
They should grow up to be mathematicians/scientists/engineers who know some art.
* Notes to self
I need to rewrite these pages:
[[file:compsci.html][Computer science]],
[[file:math.html][Mathematics]],
[[file:modeldata.html][Modeling all data]].
[[file:politik_masjid.html][Politik masjid]],
[[file:jakarta.html][Living in Jakarta]].

I need to rewrite [[file:other.html][Unimportant content]].
It badly needs massive reorganization.
It is also a staging area, a queue, a scratchpad, for the things I shall process later.

Learning computer science?
 [fn::https://en.wikipedia.org/wiki/Computer_science]
 [fn::Map of Computer Science https://www.youtube.com/watch?v=SzJ46YA_RaA]

I should merge [[file:goal.html][Goals]] and [[file:meta.html][Meta]] (my thoughts about this website itself) into this page.

<2017-05-25>:
Thanks to [[http://davidensinger.com/][David Ensinger]]'s
[[http://davidensinger.com/2013/11/building-a-better-sitemap-xml-with-jekyll/][code]],
Jekyll can generate sitemap.xml without plugins.

<2018-12-25>
Migrating from Jekyll to Pandoc broke some things.
The generated page [[file:all.html][All pages]] does not include Pandoc-generated pages.
Sitemap.xml is also broken in the same way.
* Notes for future AI recommender
Dear machine, please find me people whose interests are similar to mine.
These are some example of such people, mostly professors or ex-professors.
I have not met these people.
I have only seen publicly available information.

Why is there no professor search engine?
Why is there no Semantic Web ontology for research interests?
Idea: We can query[fn::https://query.wikidata.org/] Wikidata to find professors whose research interests intersect ours.
<2019-01-08>
I tried that, but Wikidata does not have much data relevant to that query.
** Intersecting in two topics
Prof. Sanjeev Arora[fn::https://www.cs.princeton.edu/~arora/] is a member of
Princeton theory-of-computation group[fn::http://theory.cs.princeton.edu/],
Princeton ML Theory Group[fn::http://mltheory.cs.princeton.edu/],
and Arora Research Group[fn::http://unsupervised.cs.princeton.edu/].

https://www.quora.com/How-good-is-Princeton-at-machine-learning

https://www.math.ias.edu/theoretical_machine_learning
** Intersecting in one topic
*** Computational complexity theory
Prof. Neil Immerman[fn::https://www.cics.umass.edu/faculty/directory/immerman_neil][fn::https://people.cs.umass.edu/~immerman/]
wrote the "Descriptive complexity" book[fn::www.cs.umass.edu/~immerman/book/descriptiveComplexity.html] published in 1999.
He is also a member of UMass CS Theory Group[fn::http://theory.cs.umass.edu/people.html] which has interesting theoretical researches.

https://www.quora.com/Which-professors-research-groups-are-working-on-mathematical-theoretical-understanding-of-deep-learning

Prof. Oded Goldreich[fn::http://www.wisdom.weizmann.ac.il/~/oded/]

Prof. Eric Allender[fn::https://www.cs.rutgers.edu/faculty/eric-allender]
*** Programming language theory
Prof. Philip Wadler[fn::http://homepages.inf.ed.ac.uk/wadler/]

Prof. Simon Peyton--Jones[fn::https://www.microsoft.com/en-us/research/people/simonpj/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fpeople%2Fsimonpj]
*** Artificial intelligence and machine learning
Prof. Jürgen Schmidhuber[fn::http://people.idsia.ch/~juergen/].

Prof. Elad Hazan[fn::https://www.cs.princeton.edu/courses/archive/spring16/cos511/]
*** Philosophy of computer science
Prof. William Rapaport[fn::http://www.buffalo.edu/cas/philosophy/faculty/emeriti/rapaport.html].

Prof. Brian Cantwell Smith[fn::https://ischool.utoronto.ca/profile/brian-cantwell-smith/].
* Contact
To ask questions, suggest corrections, or add something, do any of these:

- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue on GitHub]].
- Leave something at [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]].

If you know me personally, then you may send me a message at [[https://www.linkedin.com/in/erikdominikus/][Linkedin]].

If you are in Jakarta, we may meet in some meetups.

I think I should create a second email address.
