#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
* About the group and this website
** What is in this website?
This website contains questions that we think should be answered.

This page (the home page) can be thought as a table of contents.
** Who are the group members?
- Erik Dominikus
** Who is Erik Dominikus?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
** What are the group's goals?
See the sections describing the research subgroups in this page.
We are not confident that we can achieve those goals, but we think those goals are worthy of pursuit.
** Is the group for profit?
No.
We are for meaning, not for profit.
** Disclaimers
/We may err./
Read cautiously.
Compare with other independent sources.
Do not trust us without thinking for yourself.
Use your own judgement.

/We are not responsible for what other people write in their comments,/ but we can remove comments from our website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/We may change./
We are not attached to our beliefs.
Things we wrote in the past should not be solely used to judge our present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
* Research subgroups
** Computing Research Group
We aim to prescribe how computing should be done.

We are looking for the best technique for parsing and unparsing formal languages,
because parsing is the common thing between programming language and publishing system, and we are looking for both.

Intersecting topics: philosophy, mathematics, nature.

We dream of solving the P vs NP problem.

See [[file:compute.html]].
** Social Research Group
We aim to prescribe how humanity should proceed.
Intersecting topics: morality, ethics, anarchism, philosophy.

We dream of eliminating principal-agent problems.

See [[file:social.html]].
** Techno-Anarchy Research Group
We research physics and distributed computing, as far as techno-anarchy is concerned.

We dream of creating technologies that make power centralization physically impractical.

We dream of a self-sufficient global anarchistic society where people freely do what they really want without harming others, where power is distributed.
But this dream may change.
We are trying to understand what anarchy is, and we disagree with some anarchists.

We prefer peaceful means.
We dislike revolutions.
We don't want to be in a revolution.
We prefer to convince people by reason than by force.
*** How do we liberate people with technology?
I am looking for a technology that empowers people and liberates people, a technology that makes power centralization impractical.
I thought I could change the world with politics, but now I think politics only wastes time,
and now I think technology is the only hope for making something in the physical-law layer to bypass the convoluted human-made-law layer.
I think law should be principle-based, and justice should be restorative.
I think the world needs only one law: Try not to harm others.
Nobody bothers to fix the broken political systems.
Nobody even bothers to think.
Political systems are too expensive to fix; it is much cheaper to scrap them.
*** What?
I [[file:usecom.html][use computers]].
I [[file:phone.html][buy a smartphone]] when my old smartphone becomes unusable.
I usually watch YouTube at 2x-3x speed; we can speed it up to 16x[fn::https://www.quora.com/Is-there-a-way-of-watching-YouTube-videos-at-higher-than-2x-speed].
*** Why don't users use distributed systems?
Users don't care; they want software to just work.[fn::"Decentralized systems will continue to lose to centralized systems until
there's a driver requiring decentralization to deliver a clearly superior consumer experience."
http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html]

I find YaCy[fn::https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html] unusable:
its search result relevance is too far behind Google.
YaCy-related things
 [fn::https://loklak.org/ Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]
 [fn::https://chat.susi.ai/ SUSI.AI Chat - Open Source Artificial Intelligence]
seem to also suffer from usability issues.

We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
The pack might contain things like matrix.org, riot.im.
But why stop there?
Why not make free/libre distributed operating system[fn::https://en.wikipedia.org/wiki/Distributed_operating_system] with all those goodies preinstalled?

Example of federated/decentralized social networks:
Kari Nordmann's comment[fn::https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc]:
"Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo)"
*** What are WhatsApp alternative?
<2019-01-31>
Facebook is merging WhatsApp?
We need an alternative with better privacy?
*** How do we increase homemadeability?
Why do we want homemadeability?
Because homemadeability promotes equality, liberty, and anarchism.
/Everything/ should be homemadeable, including nuclear bombs.
Only when everyone can produce everything will we have equality and liberty.

Why is not everything homemadeable?

Does it make sense to use solar power (1000 W/m2) for nuclear transmutation?
#+BEGIN_EXAMPLE
E = mc2
9e16 J = 1 kg
1 J = 1.11e-17 kg
#+END_EXAMPLE

No.

How do we make nuclear transmutation homemadeable?
What prevents energy from turning into matter?
What prevents matter from turning into energy?
What prevents matter from breaking down?
Why is matter stable?
What is matter?
What is energy?
A mathematical quantity?
*** How should we farm in cities?
I thought about [[file:subsist.html][starting a farm in the middle of Jakarta]],
but I put it on hold because I felt that the opportunity cost was too high.

The key to farming is to understand ecology, some botany (plant physiology and pathology), and nutrient cycle.

We should care more about phosphate run-off.
Phosphates are vital and non-renewable, like fossil fuel.
The bad news is that there is no cycle bringing back the phosphates from the sea to the land, unlike water with its hydrologic cycle.
*** Biohacking?
Biohacking?[fn::https://www.theguardian.com/science/2018/sep/21/extreme-biohacking-tech-guru-who-spent-250000-trying-to-live-for-ever-serge-faguet]

Genetics is the biggest factor in how far we can build our body.[fn::https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting]
*** Theoretical physics, philosophy of physics
I am [[file:nature.html][trying to understand physics]].

Why is it hard to convert between matter and energy?
What does QFT say?
(Related: Why isn't everything homemadeable?)
** Meta-Research Group
We aim to make other research groups more efficient.
See [[file:meta.html]].

Topics: meta-research, writing, publishing.
** Music Research Group
We aim to prescribe how we should make and use music.
See [[file:music.html]].
* Other
You may find these uninteresting.
** What things are entertaining?
I collect [[file:entertain.html][entertainments found on the Internet]].

Why are lyrebirds entertaining?
Lyrebird can mimic sounds uncannily.
Laser guns, drills, hammers, camera shutters.
** Notes to self
I need to rewrite these pages:
[[file:compsci.html][Computer science]],
[[file:math.html][Mathematics]],
[[file:modeldata.html][Modeling all data]].
[[file:politik_masjid.html][Politik masjid]],
[[file:jakarta.html][Living in Jakarta]].

I need to rewrite [[file:other.html][Unimportant content]].
It badly needs massive reorganization.
It is also a staging area, a queue, a scratchpad, for the things I shall process later.

Learning computer science?
 [fn::https://en.wikipedia.org/wiki/Computer_science]
 [fn::Map of Computer Science https://www.youtube.com/watch?v=SzJ46YA_RaA]

I should merge [[file:goal.html][Goals]] and [[file:meta.html][Meta]] (my thoughts about this website itself) into this page.

<2017-05-25>:
Thanks to [[http://davidensinger.com/][David Ensinger]]'s
[[http://davidensinger.com/2013/11/building-a-better-sitemap-xml-with-jekyll/][code]],
Jekyll can generate sitemap.xml without plugins.

<2018-12-25>
Migrating from Jekyll to Pandoc broke some things.
The generated page [[file:all.html][All pages]] does not include Pandoc-generated pages.
Sitemap.xml is also broken in the same way.
** Notes for future AI recommender
Dear machine, please find me people whose interests are similar to mine.
These are some example of such people, mostly professors or ex-professors.
I have not met these people.
I have only seen publicly available information.

Why is there no professor search engine?
Why is there no Semantic Web ontology for research interests?
Idea: We can query[fn::https://query.wikidata.org/] Wikidata to find professors whose research interests intersect ours.
<2019-01-08>
I tried that, but Wikidata does not have much data relevant to that query.
*** Intersecting in two topics
Prof. Sanjeev Arora[fn::https://www.cs.princeton.edu/~arora/] is a member of
Princeton theory-of-computation group[fn::http://theory.cs.princeton.edu/],
Princeton ML Theory Group[fn::http://mltheory.cs.princeton.edu/],
and Arora Research Group[fn::http://unsupervised.cs.princeton.edu/].

https://www.quora.com/How-good-is-Princeton-at-machine-learning

https://www.math.ias.edu/theoretical_machine_learning
*** Intersecting in one topic
**** Computational complexity theory
Prof. Neil Immerman[fn::https://www.cics.umass.edu/faculty/directory/immerman_neil][fn::https://people.cs.umass.edu/~immerman/]
wrote the "Descriptive complexity" book[fn::www.cs.umass.edu/~immerman/book/descriptiveComplexity.html] published in 1999.
He is also a member of UMass CS Theory Group[fn::http://theory.cs.umass.edu/people.html] which has interesting theoretical researches.

https://www.quora.com/Which-professors-research-groups-are-working-on-mathematical-theoretical-understanding-of-deep-learning

Prof. Oded Goldreich[fn::http://www.wisdom.weizmann.ac.il/~/oded/]

Prof. Eric Allender[fn::https://www.cs.rutgers.edu/faculty/eric-allender]
**** Programming language theory
Prof. Philip Wadler[fn::http://homepages.inf.ed.ac.uk/wadler/]

Prof. Simon Peyton--Jones[fn::https://www.microsoft.com/en-us/research/people/simonpj/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fpeople%2Fsimonpj]
**** Artificial intelligence and machine learning
Prof. Jürgen Schmidhuber[fn::http://people.idsia.ch/~juergen/].

Prof. Elad Hazan[fn::https://www.cs.princeton.edu/courses/archive/spring16/cos511/]
**** Philosophy of computer science
Prof. William Rapaport[fn::http://www.buffalo.edu/cas/philosophy/faculty/emeriti/rapaport.html].

Prof. Brian Cantwell Smith[fn::https://ischool.utoronto.ca/profile/brian-cantwell-smith/].
** Which inquiries intersect?
My inquiries often intersect.
[[file:philo.html]] and [[file:intelligence.html]] intersect in modeling, mind, consciousness.
[[file:intelligence.html]] and [[file:social.html]] intersect in trust.
Philosophy of mind + logic meet software engineering + Prolog at "formal concept analysis"[fn::https://en.wikipedia.org/wiki/Formal_concept_analysis].
Philosophy, software engineering, and business modeling meet at "triune continuum paradigm"[fn::"The triune continuum paradigm is based on the three theories:
on Tarski's theory of truth, on Russell's theory of types and on the theory of triune continuum."
https://en.wikipedia.org/wiki/Triune_continuum_paradigm].
I disclaim any understanding.
** Self-research
PhD interview questions[fn::https://www.findaphd.com/advice/finding/phd-interview-questions.aspx][fn::https://academia.stackexchange.com/questions/101803/answering-the-why-do-you-want-to-do-a-phd-question]
*** What are my strengths?
I try to be rational.
I readily change my beliefs when I find conflicting evidences.
*** What are my weaknesses?
I have a bad relationship with time.
I have difficulty sleeping and waking up.
I disregard deadlines.
I'm slow.
I suck at races.

I don't act without reason.
I am prone to overthinking.
I am selfish and stubborn.
I see things from my point of view.
It takes a lot of effort to convince me.
I should not be put in a team that I do not believe in.
I will not do what I don't believe is important for my goal.
You will find me useless when you want me to do something that I don't believe is important for my goal, no matter how important it is to you;
in such situation I will be totally uncooperative.
I don't pretend to care.

I am non-conformist.
I put reason above norms, conventions, and authorities.
I hate ceremonies.
I risk making cultural mistakes.
My candid may offend people.

I'm bad at socializing, but I'm trying to change this.
I suck at caring.
I suck at pretending to care.
I'm learning to be the first to greet.

I hate crowds.
I'm afraid to be in crowds.
I'm paranoid and untrusting.

I am not loyal.

I have strong opinions on everything.
*** What am I no longer interested in?
I was once fleetingly interested in these things:
[[file:art.html][Art]],
[[file:game.html][Game]].

I occasionally played weiqi[fn::Weiqi is also known as go, igo, baduk. https://en.wikipedia.org/wiki/Go_(game)],
but after AlphaGo[fn::https://en.wikipedia.org/wiki/AlphaGo] beat[fn::https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol] Lee Sedol, I abandoned weiqi and never looked back.
I occasionally played chess, before Deep Blue beat Kasparov[fn::https://en.wikipedia.org/wiki/Deep_Blue_versus_Garry_Kasparov].
I occasionally played poker, before machines took over[fn::https://www.theguardian.com/technology/2017/jan/30/libratus-poker-artificial-intelligence-professional-human-players-competition].
Now I think that games only waste time:
I see no point in doing something that machines can do better than I do.
*** What musical instruments do I play?
I played piano in the band [[file:nomads.html][The Nomads]] (an Indonesian band, not the Swedish band).
However, I quit being a performer on 2018-12-23, less than a year after joining the band, because I hate inhaling cigarette smoke in venues and I hate carrying pianos to venues.
I am no longer a pianist.
I am now a composer with an asset mindset.
* Contact
To ask questions, suggest corrections, or add something, do any of these:

- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue on GitHub]].
- Leave something at [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]].

If you know me personally, then you may send me a message at [[https://www.linkedin.com/in/erikdominikus/][Linkedin]].

If you are in Jakarta, we may meet in some meetups.

I think I should create a second email address.
