#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
#+MATHJAX: true
#+OPTIONS: ^:nil
* About the group and this website
** What is in this website?
This website contains questions that we think should be answered.

This page (the home page) can be thought as a table of contents.
** Who are the group members?
- Erik Dominikus

We are not a formal organization.
We are just a bunch of people who think similarly,
and we don't know what to call ourselves.
The group may change name later.
** Who is Erik Dominikus?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
** What are the group's goals?
See the later sections describing the subgroups.
We are not confident that we can achieve those goals, but we think those goals are worthy of pursuit.
** Is the group for profit?
No.
We are for truth and meaning, not for profit.
** Disclaimers
/We may err./
Read cautiously.
Compare with other independent sources.
Do not trust us without thinking for yourself.
Use your own judgement.

/We are not responsible for what other people write in their comments,/ but we can remove comments from our website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/We may change./
We are not attached to our beliefs.
Things we wrote in the past should not be solely used to judge our present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
* Philosophy Research Group
The [[file:philo.html][Philosophy Research Group]] analyzes fundamental concepts to support other groups.

The [[file:language.html][Language Research Group]] defines "language" for the Programming System Research Group.
We care about linguistics only insofar as it concerns computing.

The [[file:parse.html][Parsing Research Group]] is looking for the best technique for specifying formal grammars, parsing formal languages, and unparsing formal languages.
Parsing is the common thing between programming language and publishing system, and we want both.
While studying parsing, we had to understand Brzozowski quotient and set division,
so we wrote [[file:division.html][Generalizing division]].

The [[file:moral.html][Morality Research Group]] analyzes our natural morality, that is our moral system as shaped by evolution.

The [[file:mind.html][Mind Research Group]] tries to define "mind".
It analyzes the relationship between mind and brain.
It compares mental phenomena such as fantasy, illusion, hallucination, etc.

The [[file:social.html][Social Research Group]] aims to prescribe how humanity should proceed.
We dream of eliminating principal-agent problems.
Our topics include morality, ethics, and anarchism.

The [[file:art.html][Art Research Group]] does what?

The [[file:music.html][Music Research Group]] aims to prescribe how we should make and use music.
We also research about music education and how to teach music.

The Aesthethics Research Group analyzes [[file:groom.html][grooming]], that is, how we should care for ourselves.

The Security Research Group is too small to have its own page,
so it lives as a section of the [[file:social.html][Social Research Group]].

The [[file:nature.html][Nature Research Group]] studies physics and the philosophy of physics.
* Computing Research Group
The [[file:compute.html][Computing Research Group]] aims to prescribe how computing should be done.
We craft the theoretical foundations of other subgroups.
We follow recent advances by occasionally checking Twitter and Semantic Scholar.

The [[file:pnptry.html][Complexity Research Group]] dreams of solving the P vs NP problem.
One goal of computational complexity theory is to separate the complexity classes.
Intersecting topics: philosophy, mathematics, nature.

The [[file:program.html][Programming Research Group]] dreams of creating the best programming system.
We think we should program directly in the language of the mind.
We think programming languages need to interoperate.
We dream of writing translating meta-programs to free programmers from design mistakes such as Java.
We are deep-diving into declarative programming.
We want a programming language with minimal accidental complexity.

The [[file:semantics.html][Semantics Research Group]] researches programming language semantics.

The [[file:softeng.html][Software Engineering Research Group]] researches forward software engineering.
How should we build software?
How can we make more lasting software sooner?
We also research some reverse software engineering.

The [[file:game.html][Gaming Research Group]] is interested in [[file:ps1.html][reverse-engineering PlayStation 1 3D games to control the camera]].
We are interested in reverse-engineering these (mostly PlayStation 1) games:
Street Fighter EX series (EX Plus Alpha, EX2, EX3), Fighting Layer, Fighting EX Layer,
Tekken series from Tekken 3, Virtual Hiryu No Ken, Dead or Alive series, Virtua Fighter series, Bloody Roar series.
* Techno-Anarchy Research Group
The [[file:tech.html][Techno-Anarchy Research Group]] peacefully, rationally, technologically, and undefeatably actualize the dreams of the Social Research Group.
We dream of precluding power centralization, or, at least, preventing or impeding it,
in a physical way such that natural laws go against human-made laws.
We research science and technology, mostly physics, cryptography, and distributed computing, but only insofar as they concern techno-anarchy.
* Internal Research Group
The [[file:meta.html][Internal Research Group]] aims to make other research groups more efficient.
We research meta-research, writing, publishing.
Where should we live?

The [[file:publish.html][Publishing Research Group]] aims to make a system for publishing this website.
* Contact
To ask questions, suggest corrections, or add something, do any of these:

- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue on GitHub]].
- Leave something at [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]].

If you know me personally, then you may send me a message at [[https://www.linkedin.com/in/erikdominikus/][Linkedin]].

If you are in Jakarta, we may meet in some meetups.

I think I should create a second email address.
* Bibliography
