#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
#+MATHJAX: true
#+OPTIONS: ^:nil
* What is your goal tree?
- Survive and have fun
  - [[file:live.html][Live forever]]
    - Live healthily
      - Eat healthy foods;
        know the food we eat;
        be self-sufficient;
        - Produce our own foods
          - [[file:subsist.html][Subsisting]]: urban farming; on hold due to opportunity cost
        - Compost excess foods
      - Sleep properly; eliminate circadian-rhythm disruptors
    - Preserve the environment
      - Have a closed personal nutrient cycle
  - [[file:plan.html][Be remembered forever]]
    - Be everywhere everytime
      - ???
        - Start a YouTube channel?
        - Start a Facebook page?
    - Say or write /contrarian/ things against prevailing opinions;
      be the devil's advocate;
      but it's bad to disagree for the sake of disagreement;
      one who /always/ disagrees is going to be /ostracized/
    - Make some /impacts/
      - Get the /resources/ required to make some impacts
        - Get /power/
          - [[file:power.html][Understand power]]
          - Get more physical power by exercising
          - [[file:rich.html][Get /rich/ quickly solving my problems without going to jail]]
            - <2019-04-22>
              I think the most feasible way for me to get power is to get rich.
            - Think entrepreneurially
            - Start a delivery-only healthy kitchen;
              I have difficulty finding affordable healthy food nearby
          - Gain /trust/ by Aristotelian rhetorics (ethos, logos, pathos)
            - Learn rhetorics, public speaking, and how to convince people
            - Settle controversial topics
              - Lead thoughts and opinions
              - Eliminate religious extremism, fanaticism, and narrow-mindedness
                - Understand religions historically, especially Islam
                  - Write a short article and share it on social media?
                  - Give a lecture/seminar?
                  - Answer these questions:
                    - Who threw the first stone in the war between Israel and Palestine?
                    - Why did the Crusades happen?
                    - Who threw the first stone in the first Crusade?
                    - How do Catholics rationalize their cognitive dissonance between papal infallibility and the unexemplary 10th century popes?
                      - Protestantism as a reaction to corrupt 10th century Catholicism
                - Understand the psychology of terrorism
                  - Why does someone become a terrorist?
                  - Why does someone become an ex-terrorist?
                  - Are there non-religious terrorists?
                - Measure religious fanaticism
          - Understand and predict world /politics/ and /economics/
    - Optimize biological aspects
      - [[file:groom.html][Grooming]]: aesthetics
  - Fix my problems first before fixing more interesting problems?

This goal tree often changes.

This /backward planning/ is explained somewhere in [[file:meta.html]].

Goal tree is similar to /work breakdown structure/[fn::https://en.wikipedia.org/wiki/Work_breakdown_structure]
and /product breakdown structure/[fn::https://en.wikipedia.org/wiki/Product_breakdown_structure].
- WBS = goal tree + 100% rule + mutual exclusivity + procedural.
- PBS = WBS - procedural + declarative.
* Why do you make this website?
Because I find thinking, writing, and planning fun.
This website contains questions that I think should be answered.

I think of myself as three different people:
- my past self
- my present self
- my future self

This website is a way for those three people to communicate.
* Who are you?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
* Should I trust you?
/No, you should not./
Anyone can put anything on the Internet.
Judge for yourself.
More disclaimers follow.

/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me without thinking for yourself.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to our beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
* How should I interact with you?
You can pick one of these:
- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue at GitHub]].

Expect long delay.
If you don't get a reply after waiting for a few days,
try resending your message.
It does get lost sometimes.

If you are in Jakarta, we may meet in some meetups.
* Where else are you?
I may also be found at these places, but I rarely check them:
- [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]]
- [[https://www.linkedin.com/in/erikdominikus/][Linkedin:erikdominikus]]
* Bibliography
