#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
#+MATHJAX: true
#+OPTIONS: ^:nil
* What are you working on?
** Computer-related
- [[file:softeng.html][Software engineering]]: forward engineering
  - [[file:prolog.html][Using the Prolog programming language]]
** Computer-related, utter mess
- [[file:reveng.html][Reverse software engineering]]
  - [[file:rejava.html][Reverse engineering the network protocol used by a Java desktop application]]
- [[file:opensrc.html][Making contributable open-source projects]]
- [[file:community.html][Building online communities]]
- [[file:game.html][Gaming]]
- [[file:publish.html][Publishing Research Group]]: making a system for publishing this website
- [[file:program.html][Programming Research Group]]: these should be merged?
  - [[file:proglang.html][programming language design]]
  - [[file:program-sketch.html][sketching a declarative programming language]]
- [[file:compute.html][Computing Research Group]]
  - [[file:language.html][Language Research Group]]
  - [[file:parse.html][Parsing Research Group]]
    - I am looking for the best technique for specifying formal grammars, parsing formal languages, and unparsing formal languages.
      Parsing is the common thing between programming language and publishing system, and I want both.
  - [[file:division.html][Generalizing division]]: Brzozowski quotient and set division
  - [[file:pnptry.html][Complexity Research Group]]: dreaming of solving the P vs NP problem
  - [[file:semantics.html][Semantics Research Group]] (of programming languages)
- [[file:ps1.html][Reverse-engineering PlayStation 1 3D games to control the camera]]
** Social
- [[file:social.html][Political power decentralization]]
  - [[file:moral.html][Morality]]: our natural morality shaped by evolution
** Philosophy
- [[file:philo.html][Philosophy]]: armchair philosophy
  - [[file:mind.html][Mind]]: philosophy of mind
  - [[file:groom.html][Grooming]]: aesthetics
- [[file:meta.html][Internal Research Group]]: meta-research, meta-thinking
- [[file:nature.html][Nature Research Group]]: physics and its philosophy
** Utter mess
- [[file:art.html][Art Research Group]]
- [[file:music.html][Music Research Group]]
- [[file:tech.html][Techno-Anarchy Research Group]]
- [[file:other.html][Unimportant content]]: utter mess
* Why do you make this website?
Because I am not satisfied with reality.
This is my attempt to change the world to what I want it to be.

I think of myself as three different people:
- my past self
- my present self
- my future self

This website is a way for those three people to communicate.

This website contains questions that I think should be answered.
* Who are you?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
* Should I trust you?
/No, you should not./
Anyone can put anything on the Internet.
Judge for yourself.

Some more disclaimers follow.

/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me without thinking for yourself.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to our beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
* How should I interact with you?
You can pick one of these:
- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue at GitHub]].

Expect long delay.
If you don't get a reply after waiting for a few days,
try resending your message.
It does get lost sometimes.

If you are in Jakarta, we may meet in some meetups.
* Where else are you?
I may also be found at these places, but I rarely check them:
- [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]]
- [[https://www.linkedin.com/in/erikdominikus/][Linkedin:erikdominikus]]
* Bibliography
