#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
#+MATHJAX: true
#+OPTIONS: ^:nil
* Consciousness research
- [[file:book.html][Summary of some books]]
- [[file:meditate.html][On meditation]]
- [[file:philo.html][On defining philosophical concepts according to everyday usage]]
- [[file:mind.html][On the mind-body problem]]
- [[file:anomaly.html][On anomalies]]
- [[file:remote-viewing.html][On remote viewing]]
- [[file:anomaly-theory.html][Towards the abduction of the simplest theory that explains paranormal evidence]]

<2019-09-30>
IAC claims that someone can obtain some very basic psychic abilities in /three hours/ with the /right technique/.
  [fn::<2019-09-30> https://uk.iacworld.org/how-long-does-it-take-to-develop-psychic-abilities/]
But what is the right technique?
I tried to download their ebook, but it requires me to subscribe, so I did that, and then the website experiences an internal error, after asking for my personal data.
How convenient.
At first it seems mostly legit with some questionable things and yellow flags.
It sells courses.
It assumes you're in Europe.
I'm in Indonesia.
Tough luck.

Haunting vs poltergeist[fn::<2019-09-16> Poltergeist Phenomena with Stephen E. Braude https://www.youtube.com/watch?v=-nwG7p9MJ0U]:
Both haunting and poltergeist are macropsychokinetic phenomenons.
However, haunting is centered on a place, whereas poltergeist is centered on a person.
Example cases: Eleonore Zugun[fn::<2019-09-16> https://parapsychologie.info/zugun.htm],
Enfield poltergeist,
Matthew Manning[fn::<2019-09-16> https://psi-encyclopedia.spr.ac.uk/articles/matthew-manning].
It also seems that apporting objects heat them up: Apparently bigger apported objects feel warmer.
It seems that the phenomenon reflects the underlying psychological explanation of the subject's problem.
A "schlemazel" is a consistently unlucky person.
Stephen E. Braude looks at macropsychokinetic phenomenons.

Russell Targ's website[fn::<2019-09-17> http://www.espresearch.com/] has some links[fn::<2019-09-17> http://www.espresearch.com/links.shtml].

There is always the possibility that the patients are faking their responses, but we suppose that they are honest.
But how do we know?

What journal is this?
Who are these people?
2008 article "Investigating paranormal phenomena: Functional brain imaging of telepathy"\cite{venkatasubramanian2008investigating}.

Precognition indicates consciousness?
Animals precognize.
Human consciousness can interfere in consciousness experiments.
 [fn::<2019-09-28> Machine Consciousness: Experimental Evidence | Garret Moddel https://www.youtube.com/watch?v=4H5GDQ7u_iE]
* Literacy research
** Literacy research articles
- [[file:literacy.html][On literacy]]
- [[file:dual-read-write.html][On the mathematical duality of reading and writing]]
- [[file:writing.html][On writing]]
** A simple solution to English singular gender-neutral pronoun problem
<2019-08-14>

I propose this one small painless change to the way we interpret English:
We declare that "he" is always gender-neutral and never implies maleness.
Thus, in the singular case, we now have a gender-neutral human pronoun "he",
a female human pronoun "she",
a non-human pronoun "it",
and /no male pronouns/.

My solution requires inventing no new words as it is already common to use "he" as a gender-neutral pronoun.
The change is minimal, undisruptive, and painless.

Now let us see how the new interpretation prevents hurt feelings.
Consider this conversation:

#+BEGIN_QUOTE
Alice: "You have a child? What is his occupation?"

Bob: "She is unemployed."
#+END_QUOTE

In the old interpretation, Bob is implicitly correcting Alice.
In the new interpretation, Bob is simply giving more information to Alice
without implying at all that Alice wrongly guessed the gender of his child.

It takes only one generation to teach this for this to feel normal.
It's just a matter of consensus.
** <2019-08-14> Writing is a non-linear process
From https://macademic.org/2011/03/15/writing-philosophy/:
- "Combining these different pieces of information does not happen in an orderly linear process."
- "Writer’s block often comes from being too closely linked to the linearity of a process and
  the inability to break out small pieces of text to work on and move with ideas."
** On English participles and gerunds
A participle is an /adjective/ formed from a verb.
A gerund is a /noun/ formed from a verb.[fn::<2019-09-29> https://www.cliffsnotes.com/study-guides/english/verb/verbals-gerunds-infinitives-and-participles]

What is the difference between "I don't like the /guy/ wearing the green pants" and "I don't like the /guy's/ wearing green pants"?

"I don't like the /guy/ wearing the green pants" means you don't like /the guy himself/.
You have a personal problem with the guy.

"I don't like the /guy's/ wearing green pants" means you don't like /what he does/: wearing green pants.
You don't have a personal problem with the guy, but you think he shouldn't wear green pants.
However, there is a better way to express this:
Ask him "What's the story behind these green pants?" instead; you get a chance to better understand him.
** On changing people's minds
One way to lower people's defense to change their opinions is "I used to ..., but then ..."

Bad title, provokes defense mechanism: "Abortion is wrong"

Bad title, sounds confrontational: "Why abortion is wrong"

Better title: "I used to be against abortion until I encounter the sorites paradox"

The most convincing argument is a story, not an argument.
* Meta-research
See [[file:meta.html]].
** <2019-07-07> Do not ask Google (or anyone else) questions that only you can answer
Like "If I am my own target audience, what should I write, for myself?"
** On personal knowledge bases
What is the most commonly used free-and-open-source one?
There are too many solutions?

If the graphical user interface cannot be standardized, at least the data format should be standardized.

I'm using Org Mode and Pandoc.

Wordpress?

TiddlyWiki?

I want free-and-open-source software because I want my data to be usable forever.

Evernote is not FOSS.

https://www.ubuntupit.com/13-best-evernote-alternative-note-taking-apps-linux/

https://opensource.com/article/17/12/joplin-open-source-evernote-alternative

One can convert a dynamic website to a static website with a /website downloader/.
You can point a website downloader to localhost.

Should we build it on Pollen[fn::https://docs.racket-lang.org/pollen/]?
It was made for making web-based books.
* On living on Earth
** On living sanely, peacefully, and sustainably
- [[file:groom.html][Grooming]]
- [[file:subsist.html][On living sanely]]
** On muscle, fat, and handsomeness
It's not the above-average muscles that make one look handsome;
it's the above-average fat that makes one look ugly.
** A clean eating protocol
Combine /nutrition science/ and /psychology/.

For two weeks.

Pay attention to gut microbiome.

No sugar; no condiments bought from supermarket because they all have sugar.
No flour.
No carb.
No food that is processed more than one step from its original form.
No refined foods.
No extracts.
Sugar is not OK because it is concentrated sugarcane plant extract.
Cooked meat is very OK, but sausage is not.
White rice is not OK.
Green vegetables OK.

Anytime you're hungry, just eat; there is no time restriction;
the only restriction is that you eat real fat/protein.

Everytime you eat, you must send a photograph of what you eat to me.
It is not for approval, but for commentary, and for /psychology/, for accountability,
so that you feel that you are doing it for me, so that you don't prematurely abandon your effort.

You can drink anything as long it has no sugar in it.
Just drink plain water.
Drinks from the supermarket are not OK; they all have sugar.
** On business and economics
Inspiring Internet onion seller[fn::https://www.deepsouthventures.com/i-sell-onions-on-the-internet/]:
It's /stupidly simple/, but it's /real money/.
It's /good business/.

https://www.bradford-delong.com/2017/07/how-to-think-like-an-economist-if-that-is-you-wish-to.html
https://hackernoon.com/how-to-make-more-money-as-a-software-developer-da9fc13944e4
https://en.wikipedia.org/wiki/Economic_system
https://en.wikipedia.org/wiki/Circular_economy

https://en.wikipedia.org/wiki/Productivity_model
https://en.wikipedia.org/wiki/Productive_forces
https://en.wikipedia.org/wiki/Production_(economics)
** <2019-08-20> ? On skin-wrapping for skin-tightening, occlusion cuff training, and blood flow restriction training
Do they work? How do they work? What is the science?
** Why do I wear long hair?
- To repel close-minded people.
- To know when I have lost in life, when I can no longer do things as I wish,
  be it due to biological or economical reasons.
* Software research
** Software research articles
- [[file:software.html][Towards a philosophy of software]]
- [[file:software-science.html][Towards software science]]
- [[file:softeng.html][Towards software engineering]]
- [[file:parse.html][On parsing formal languages]]
- [[file:intelligence.html][On intelligence]]
- [[file:software-system-model.html][Towards a comprehensive software system modeling language]]

On programming by examples.
Erik Meijer has an interesting presentation about machine learning, that is, programming computers by examples.
Can we create a programming language in which programming by examples is elegantly expressible?
** <2019-08-27> A direction for software engineering
Two things have to be addressed in software engineering:
the lack of /science/, and the lack of /tools/.

/Software engineering lacks an underlying branch of science/.
Remember that engineering is an application of science

/Software engineering lacks tools./
Building an enterprise application with Java is like building a 20-story building with only shovel.

One of those tools is a /whole-system programming language/
with support for /persistent states/ (that outlive one run of the application).
Every time the program starts, it has to /initialize/ all persistent states that are not already initialized.
A software system is not only the program, but also the database, the files, the documentation, etc.
Current programming languages focus too much on the application and not on the /whole system/.
We need a language that can also capture the persistent states.
** <2019-08-23> Software engineers need better tools
We are demanded to build a skyscraper, but all we have is a spade.

Java is too low level for programming business applications.
** "Computer science" should be renamed to "software science"?
<2019-08-11>

Our "computer science" label has misled people into thinking that we can fix their computers.

Although the first computer scientists did study computers,
computer scientists now don't study computers anymore because software has grown too big;
now computer scientists study mostly software,
and the hardware is supposed to be studied by /computer engineers/.

A honestly-named computer-science student should study both hardware and software
because a computer has a hardware part and a software part,
But, in fact, a computer-science student studies much more software than hardware,
and will often work with software while taking hardware for granted in their jobs.

Perhaps universities should also merge law departments and computer science departments into /software departments/.

On second thought, perhaps we should not call ourselves "software scientists"
because we don't even know what software is.
Perhaps we should just call ourselves "computer programmers".
** Software structural engineering
<2019-08-15>

Here we transplant /civil structural engineering/ to /software structural engineering/ by analogy.

Both civil structural engineers and software structural engineers do /capacity planning/ and /load testing/.

Civil structural engineers deal with the /strength of materials/, whereas software structural engineers deal with the /emptying rate of queues/.

The science of civil structural engineering is based on /continuum mechanics/,
whereas the science of software structural engineering is based on /queuing theory/.

Material breakage is analogous to /full queue/.

When a civil structure fails, the /building/ collapses.
When a software structure fails, the /system performance/ collapses: latency skyrockets and throughput drops.

Structural engineers design structures to /withstand probable adversities/ according to cost-benefit analysis.
Civil structural engineers design structures to withstand /heat, wind, earthquakes, etc./
Software structural engineers design systems to withstand /load spikes, network disruptions, disk failures, etc./
If we are building a skyscraper in an earthquake-prone region, we must seriously consider earthquakes.
If we are building a system for 1,000,000 concurrent users, we must seriously consider traffic spikes, network disruptions, and other adversities.
If we are merely building a system with 10,000 lines of code for 10 users,
and it will stay that way for 100 years, then it is a waste of resources to bake in a grandiose architecture.
If you need a shack, and it will satisfy you for 1,000 years, then perhaps don't build a skyscraper.
** <2019-08-17> On programs and software
Perhaps we should focus on /programs/ instead of software.
We can talk about computer programs without talking about software.
After all, Tukey 1958 intended "software" to mean computer programs.
** <2019-08-20> On writing numerical algorithms for humans, and on the semantic shift of the word "computer"
We can assume that humans implement these primitive operations:
addition, subtraction, multiplication, exponentiation, and division, for small numbers below ten, rounding, comparison.

Any average person could execute such an algorithm,
because it is /unambiguous/ and is built on common primitive operations.

All those primitive operations also happens to be implementable in electronic computers.
That is, electronic computers can do some human operations.
** <2019-09-04> On defining languages in other languages
There are two languages: the /host/ language and the /guest/ language.
In linguistics, they are called the /meta/-language[fn::https://en.wikipedia.org/wiki/Metalanguage] and the /object/ language, respectively.
For example, when we teach German to someone who only knows English,
we use English as the host language and German as the guest language.

We can borrow the host language's concrete syntax,
so that we can reuse `read-syntax`, but specify different semantics, with an interpretation function.

We can borrow the host language's semantics.
* Financial research
** Financial research articles
[[file:stock.html][On stocks, their prices, and their financial valuation]]

[[file:valuation.html][On financial valuation]]
** On valuation
Aswath Damodaran – Laws of Valuation: Revealing the Myths and Misconceptions (FULL PRESENTATION)
https://www.youtube.com/watch?v=c20_S-QgvsA
4:25 corporate life cycle: from birth to death
Valuation is a bridge between numbers and stories
In a young company, story matters more than numbers
In an old company, numbers matter more than story

https://www.youtube.com/watch?v=Z5chrxMuBoo
pricing (momentum, emotion) vs valuation (asset, growth, reinvestment, liability, risk, story)
51:32 investing is more luck than skill?
1:01:01
Interesting point of view:
"[...] Don't overreach.
You don't get /rich/ by investing.
You get rich by doing whatever you're doing, and investing is about /preserving/ what you made elsewhere and /growing/ it.
It's when you get greedy about trying to make that killing on your investment that you tend to overreach."
[emphasis mine]

Aswath Damodaran: "The Value of Stories in Business" | Talks at Google
https://www.youtube.com/watch?v=uH-ffKIgb38
12:50 the story should be possible, plausible, and probable

https://www.youtube.com/watch?v=VlcmHhbYeNY
Valuation is not pricing.
Venture capitalists do pricing not valuation.
* Natural research
- [[file:nature.html][A physics book draft]] (should be split into articles instead)
- [[file:chemistry-ontology.html][On the evolution of the ontology of chemistry]]
- [[file:save.html][On my plan to save myself and perhaps some people]]

Are black holes the key to unifying general relativity and quantum field theory?

"Realistic Simulation: Inside a Black Hole - New Universe through White Hole?"[fn::https://www.youtube.com/watch?v=iUr8Obv_DeA]
** <2019-08-17> On myopia
I hypothesize that myopia has lower prevalency in the population of drivers because drivers refocus their eyes a lot.

black-on-white promotes myopia, white-on-black inhibits myopia?
https://www.nature.com/articles/s41598-018-28904-x

https://biology.stackexchange.com/questions/24589/how-does-the-eye-know-whether-to-focus-further-out-or-nearer-in-order-to-bring-a

https://photo.stackexchange.com/questions/105433/can-you-tell-from-a-blurry-photo-if-focus-was-too-close-or-too-far

Hypothesis:
The brain uses the chromatic aberration of the eye lens in order to detect whether the focus is too near or too far.
Green fringing means that the focus is too ???
Purple fringing means that the focus is too ???
https://photographylife.com/what-is-chromatic-aberration
https://en.m.wikipedia.org/wiki/Circle_of_confusion
** Appeal-to-evolution weakens the theory that irregular eating causes gastritis
<2019-08-17>

The /appeal-to-evolution/ is this argument:
/If a trait would hamper the survival of a species, then that species would not have evolved that trait./

It is a heuristic.
It is not always correct.
For example, it cannot explain peacock tails.
However, it seems reasonable in absence of other information.

The appeal-to-evolution weakens the theory that irregular eating causes gastritis as follows.

Perhaps the very early hunter-gatherer humans ate irregularly;
they were always a few days away from starvation,
they did not have a secure food supply,
they depend very much on their surroundings.
/Having gastritis due to irregular eating would hamper their survival./
Therefore they probably evolved such that irregular eating does not cause gastritis.
** Others' articles about gastritis
"Coadaptation of /Helicobacter pylori/ and humans: ancient history, modern implications"[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2735910/]

"The Iceman had a tummy bug"[fn::https://www.sciencemag.org/news/2016/01/iceman-had-tummy-bug]

1998 "Helicobacter pylori in vivo causes structural changes in the adherent gastric mucus layer but barrier thickness is not compromised"[fn::https://gut.bmj.com/content/43/4/470]
** On atherosclerosis
Atherosclerosis or arteriosclerosis?
https://amp.theguardian.com/science/2019/jun/11/mystery-arteries-harden-cracked-scientists-calcium-deposits
** On gut microbiome?
https://www.prebiotin.com/prebiotin-academy/what-are-prebiotics/dietary-fiber/

https://medium.com/boosted/intermittent-fasting-your-thyroid-and-your-immune-system-ec8f5f02d997
https://www.sciencedirect.com/science/article/pii/S0924224414002386
https://mennohenselmans.com/protein-is-not-more-satiating-than-carbs-and-fats/
https://www.ncbi.nlm.nih.gov/pubmed/8695595/
https://www.shape.com/latest-news-trends/go-veggie-gain-weight-heres-why-it-can-happen
https://www.livestrong.com/article/1011649-6-reasons-people-gain-weight-after-going-vegetarian/
https://www.healthline.com/health/food-nutrition/becoming-vegetarian-tips
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4564526/
https://selfhacked.com/blog/how-your-gut-microbiota-can-make-you-fat-or-thin/
https://www.ncbi.nlm.nih.gov/pubmed/30336163
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6036887/
** On the science of diets
Conservation of mass.

Body mass is gained by food and drinks, and lost by exhalation and excretion.

The question is the /composition/ of those mass.

If I weigh 70 kg and both my legs weigh 20 kg, then a squat consumes at least 50 kg * 10 m/s2 * 0.5 m = 200 J = 0.0478 kcal.
That's a tiny amount relative to the calories in the food we eat!
We can easily eat 300 kcal in one meal.
Thus, if the human body were 100% efficient, I would have to squat /6,276 times/ to burn that one meal!

Thus the biggest energy consumer is the basal metabolic processes.

The proximal cause is the combination of nutrition and hormones.
Hormones are affected by nutrition, activity, and genetics.
* Politics and economics
[[file:cara-memilih-pejabat.html][Cara memilih pejabat dalam sebuah demokrasi]]
** <2019-08-20> Pengguna narkoba adalah korban, bukan penjahat
Pengguna narkoba harusnya ditolong, bukan dipenjara.

Korban memakai narkoba karena terisolasi secara sosial (merasa kesepian).

Penjara tidak menyelesaikan apapun.

Penjara adalah masalah, bukan solusi.

Untuk mengatasi narkoba, contohlah Portugis yang berhasil, dan jangan contoh Amerika yang gagal.
** <2019-08-21> Politics rule no 1: Avoid angering the majority
Avoid angering the majority.

If the majority are idiots, it is even more important to avoid angering them.

Even if you know the truth, avoid angering the majority.

(Isn't this common sense?)
** Autosegregation is rational
Every man thinks that it's much easier to move to where the "smart" people are than to fix the "idiots" around him.

For example, non-Muslim people would not want to live near mosques because mosques are noisy,
but Muslims would want to live near mosques because they go there very often.
Thus, those two groups have just automatically segregated themselves without anyone's help.
** The root cause of Boeing 737 MAX fiasco: existentially-threatening competitions?
<2019-07-07>

The Boeing 737 MAX fiasco is not a software accident,
because the software is working as intended,
that is as a crutch to work around bad hardware design due to cost-cutting.
That plane is a pile of workarounds:
that software is a workaround for bad hardware which is a workaround for bad business decisions.
They are making planes as game companies make games:
They think they can just release crashing planes and patch the planes later,
but planes kill people when they crash, whereas games don't.
That fiasco is a case of prioritizing profits before engineering,
but unfortunately, Nature, the judge,
will always grant victory to physics, when physics and profits disagree.
But can we blame companies for seeking profit,
because profit is necessary for their survival?
Does it mean that airplanes should be made by non-profits?
But who is going to do anything at all, if not for profit?
But why can't we just gather the people who are good at building airplanes,
and give them money and tools to build airplanes?
Software companies do this all the time.

My first solution attempt is to make organizations in which people just build the best planes they can.
They may compete, but they must not compete to survive.
Competition may exist, but must not be an existential threat.
Non-profits would be even more efficient if there were no competition.
But even non-profits need money, and that money has to come from somewhere,
and no one is going to suddenly donate some billion dollars and start a non-profit organization that makes airplanes.
Or is anyone going to do that?
The richest people can do that, but will they?

The root cause of the Boeing 737 MAX crashes is that competition presents an existential threat to companies.
If I had to design a plane while facing an existential threat,
such as being held at a gunpoint,
then my plane would probably crash too, as I cut corners to save my life.
So the question is, how do we remove the gun,
so that I can design planes in peace,
while also ensuring that my design makes sense physically and economically?

Competition has given us big companies that produce all luxuries that our ancestors could only imagine but we take for granted.
But the future is cooperative, not competitive.

** Gun rights is now about selling guns for profit, no longer about fighting tyrannical governments
<2019-08-15>

In 2019, anyone who thinks that guns can protect them from tyrannical governments is deluded.
Governments have better guns, soldiers, cops, bombs, planes, drones, tanks, nukes, and a monopoly on violence bigger than ever in history.
Nevertheless, guns can be used to terrorize government employees to discourage people from working for the government,
 [fn::https://www.bbc.com/news/amp/world-us-canada-49339903]
but I don't recommend that,
and I don't plan to discuss asymmetric warfare[fn::https://en.wikipedia.org/wiki/Asymmetric_warfare] and militant anarchism here.

Thus the only reason left for gun rights is to let people sell guns for profit.
** Constitutions are not holy books
<2019-08-16>

Changing constitutions is almost as hard as changing bibles.
Constitutions have become holy books, and political ideologies have become religions.
Blind beliefs are bad for progress.

Constitutions should be hard to change,
because it is the foundation of all other laws in a country.
A constitution that changes often will confuse everyone.
Unfortunately, this also means that a bad constitution will stay bad forever.
** Platforms and antitrust laws are inherently incompatible
A platform is only useful if everybody uses it, but if that is the case, then it has become a monopoly.
But monopolies are illegal?
Thus, are platforms illegal?

One can mitigate monopolies by requiring interoperability?
** Capitalism exploits individual selfishness to benefit everyone?
Everyone wants to maximize their own profit.
Everyone only cares about themselves.
Therefore, a system must be created, such that selfish people can only profit by benefiting others.

What does a system incentivize?
** Unions?
Who does a union benefit?
The incumbent workers?

Do laborers have less bargaining power than capitalists?

https://www.quora.com/Why-do-some-people-hate-labor-unions

https://en.wikipedia.org/wiki/Opposition_to_trade_unions
** How do inventors profit without patents?
Sell the invention as a service?

Are trade secrets protected?

Patents pros:
- incentivize innovation

Patents cons:
- encourage patent trolling and gaming the legal system for personal financial gain at the expense of others

https://en.wikipedia.org/wiki/Economics_and_patents
** <2019-07-06> Borders are lawless places
*** <2019-07-06> Use a new clean phone that is not logged into anything, when you go abroad
Customs are lawless.
Borders are lawless places.
Laws are not enforceable at borders.
Rights do not exist at borders.
China forces travelers to install malware.[fn::https://www.slashgear.com/china-forces-malware-on-tourist-phones-at-border-heres-what-they-want-02582568/]
USA customs harass.[fn::https://www.schneier.com/blog/archives/2019/04/former_mozilla_.html]

Finding Border Patrol secret Facebook group is like finding a roach nest,
and now the roaches are running around in panic to save themselves.[fn::https://theintercept.com/2019/07/05/border-patrol-facebook-group/]
But it is an insult to the roaches.

Customs officials can make their own laws because they face no consequences:
There is no practical way to hold them accountable for their actions.
Also, people don't care.
** <2019-07-06> Is freedom of speech important?
Examples of degrees of freedom of speech:
- In USA and Canada, you can talk shit about the government, as long as you don't make death threats, or the cops will get you.
- In Indonesia, you can disagree with the government, but you have to do it very politely, or you will be jailed.
- In China, if you disagree with the government, your will be encumbered, if not killed.
- In Saudi Arabia, if you disagree with the government, you will be killed.

But all government is more similar than different:
There is always centralization of power, and therefore abuse of power.

Without freedom of speech, life goes on pretty much normally in Indonesia.
Meanwhile, the USA, for all its free speech, still has problems like crony capitalism
and highest gun-related murder which is totally preventable
as shown by the Australians.

Why do you insist on owning a gun?
It does not protect you from a tyrannical government.
They have bombs, armies, nukes, soldiers, cops, gunboats, aircrafts, hackers, money, what else.
If you think your teeny-pistol militia can beat them, you're as deluded as Don Quixote;
but actually he has better chances than you do,
because windmills don't fight back, whereas governments do.
The freedom to bear arms is just a ceremonial distraction
from more important issues such as imperialism, privacy, and borders.
** <2019-07-06> Gerrymandering
Gerrymandering is a self-inflicted pain with a simple solution:
proportional representation[fn::https://www.fairvote.org/how_proportional_representation_would_finally]
 [fn::https://www.sightline.org/2019/05/03/the-secret-to-ending-gerrymandering-isnt-a-secret/].
Drawing district lines is like punching yourself in the face and wondering why it hurts.
The fix is simple: Just don't do it.

How does Alabama have a government that does not represent its constituents
 [fn::https://qz.com/1628427/saudi-arabias-abortion-laws-are-more-forgiving-than-alabamas/]
 [fn::https://www.motherjones.com/politics/2019/05/previously-unreleased-poll-shows-alabama-voters-disapprove-of-extreme-abortion-ban/]
 [fn::https://www.vox.com/policy-and-politics/2019/5/18/18630562/alabama-abortion-ban-voters-exemption-for-rape-incest]?
Gerrymandering?
** <2019-08-14> Elections should have an entrance fee
The amount is not important, but should be low, but not zero.
What is important is that an entrance fee /exists/.

When a surgeon fails, he injures one people.
When a car driver fails, he injures ten people.
When a lawmaker fails, he injures millions of people.
Then why do we insist on lower standards for our lawmakers than for our surgeons?
Why do we elect clueless clowns and self-enriching thiefs into the government?
/Because we pay for a surgery but not for an election/.
Paying for something increases our expectation.
We don't pay for an election, so we expect nothing.

But companies do pay for elections, through contributions and lobbyings.
Thus companies expect to gain from elections, while people don't.
** <2019-08-14> We need a World Government
These entities may have done things that would be considered atrocities by 2019 standards:
Muhammad
 [fn::https://wikiislam.net/wiki/List_of_Killings_Ordered_or_Supported_by_Muhammad]
 [fn::Why Did Carl Jung Compare Hitler To Muhammad? https://www.youtube.com/watch?v=BzlESr-2cZ4],
Suharto[fn::https://indonesiaatmelbourne.unimelb.edu.au/theres-now-clear-proof-that-soeharto-orchestrated-the-1965-killings/],
the United States of America[fn::https://en.wikipedia.org/wiki/United_States_war_crimes],
the British Empire[fn::https://www.independent.co.uk/news/uk/home-news/worst-atrocities-british-empire-amritsar-boer-war-concentration-camp-mau-mau-a6821756.html],
many imperialist European countries,
Mao[fn::https://en.wikipedia.org/wiki/Mass_killings_of_landlords_under_Mao_Zedong],
Stalin[fn::https://en.wikipedia.org/wiki/Excess_mortality_in_the_Soviet_Union_under_Joseph_Stalin],
Hitler[fn::https://en.wikipedia.org/wiki/The_Holocaust],
Genghis Khan,
and many more[fn::https://www.hawaii.edu/powerkills/NOTE1.HTM][fn::https://en.wikipedia.org/wiki/Democide],
if not everyone.

/But only Hitler lost the war./

Thus now Hitler is condemned, whereas the others are venerated.

It is a crime to murder one person.
It is not a crime to wage an unjust war /and win the war/
because the winner gets to define what "crime" is, and then he gets to write the history.
This is just human nature.
Even I myself suffer from that:
I often find myself imagining the killing of billions of people,
be it by my own hands or by a natural catastrophe,
and I imagine the peace that follows, the problems that disappear,
the overcrowding gone, the pollution gone, the noise-makers gone, the exorbitant land prices fall.

There is no government for countries,
and thus countries go to war against other countries.
At the level of citizens, there is a rule of law,
but at the level of countries, it is anarchy.
Thus it seems that there has to be a government for governments,
but this suffers from infinite regress:
second-level governments may go to war with each other,
and so on.
Thus, the only way to global peace is /to have exactly one government for all people/, one World Government,
because it is impossible to have a war if there is nobody else to wage a war against,
that is, if you are the only government in the world.
This is the only way to prevent wars.

This World Government should be filled with scientists and engineers
because they do politics better than politicians do;
see China[fn::https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers],
but it's changing in 2017.[fn::https://www.scmp.com/news/china/policies-politics/article/2117169/out-technocrats-chinas-new-breed-politicians]

But people are too chauvinistic, too egoistic, and too proud for a World Government.
All nationalism is chauvinism, because we are all citizens of the Earth.
As technology is heading toward a singularity,
human culture is also heading toward a singularity.

Having different governments also enables tax avoidance, money laundering, and wage slavery,
by enabling one to arbitrage different regulations in different countries.
** <2019-08-14> People, not beliefs, deserve respect
We can respectfully treat people who believe unjustifiable things such as religions, superstitions, but we should not respect their beliefs.
If we facilitate some people with stupid beliefs, it is not because we respect their beliefs, but because we respect their feelings.

But this is impractical.
People interpret attacks on their beliefs as attacks on their selves.

Not all opinions are equal:
- [[https://www.youtube.com/watch?v=pe4feBH0ABk][Richard Dawkins: No, Not All Opinions Are Equal---Elitism, Lies, and the Limits of Democracy - YouTube]]
  - If you have a surgery, you want an expert surgeon.
  - If you have a concert, you want an expert musicians.
  - Why then, when it comes to Brexit, do people suddently think they are expert politicians?
    - The people voting for Brexit might not even understand what the European Union is.
** <2019-08-14> Groups diffuse blame
A perverse situation may arise, in which the individual is praised for success, but the group is blamed for faults,
perhaps due to our desire to feel good and avoid conflicts.
An example of such perverse situation is the belief "If this country advances, it's due to the president; if this country regresses, it's due to the government",
or "If this company profits, it's due to the director; if the company loses, it's due to everyone".
** <2019-08-14> Why are corporations legal people?
Corporations are legal people so that they can be sued and brought into court.
 [fn::https://www.forbes.com/sites/timworstall/2012/11/17/ill-believe-corporations-are-people-when-texas-executes-one-what-is-this-foolishness-from-robert-reich/#78f1f29633f2]
** <2019-08-17> Entrepreneurial employee is exploitation
Work as hard as entrepreneurs, get paid as low as employees.
** <2019-08-17> British imperialism?
Opium wars?[fn::https://amp.cnn.com/cnn/2019/05/26/opinions/china-is-not-the-enemy-sachs/index.html]
** <2019-08-20> On the false assumptions of deterrence theory
What is the point of making a weapon so powerful that you would rather not use it?
What is the point of living under constant fear?

https://www.theguardian.com/world/2018/jan/14/nuclear-deterrence-myth-lethal-david-barash
** <2019-08-20> Common law is more agile than civil law
Civil law is always late, because we suck at foretelling.
In civil law, everything is legal until legislators make a law against it.

But common law requires higher standards for judges, whereas judges are fallible humans too, just like the rest of us.

Humans are not computers.
Humans excel at following the /spirit/ of the law.
Computers excel at following the /letter/ of the law.
Indeed humans who strictly follow the letter of the law may be malicious.

Lawmakers should make principles, not rules.
Lawmakers should explicitly state the spirit and intention of the law,
not just the letter of the law.
** <2019-08-20> What is natural economic growth?
As fast as /lives/ can grow: plants, bacteria, etc.
If you grow faster than natural, you are extracting some wealth?
** <2019-08-20> On workplace fairness
As an employer, it is very difficult to treat all employees fairly.
Fairness does not exist.
What exist are envy and jealousy.
Everyone has their own idea of fairness.
Thus, the problem is not to be fair, but to be /perceived/ as fair by /each/ employee.
But every person has a different idea of fairness.
** South Korea quits Windows cold turkey?
https://betanews.com/2019/05/18/korea-linux/

What about "Indonesia goes open source"?
** On the futility of abortion debates
The root problem of the abortion issue is the disagreement on the definition of "human".

The question "Should we allow abortion?" actually reads "What is a human?"

My suggestion is:
Before everyone agrees on the same definition of "human", avoid wasting time in abortion "debates".
No communication happens when people interpret words differently.

There is no reason in an abortion debate; it's just pure feeling and linguistic issues.
Anyone who doesn't know about the sorites paradox has no place in an abortion debate.

What is a human?
Nobody can satisfactorily define what a "human" is; they only "know it when they see it".
For every "definition" of human you come up with, I can point out a problem with it.
I have tried to define "human" a few times, and failed.

Outlawing abortion now causes increased crime rate 20 years later.

Outlawing abortion is condemning rape victims into economic hell.

Just because you don't like it doesn't mean it should be illegal.
** On the firehose of lies
“Don't try to fight the firehose of falsehood with the squirtgun of truth,” Paul said. “Try to put 'raincoats' on those who will be hit with the firehose.”
 [fn::https://www.rand.org/blog/2016/12/beyond-the-headlines-rands-christopher-paul-discusses.html]
 [fn::https://www.youtube.com/watch?v=i1pA1kpJosk]
** Bush's Iraq War
Bush attacked Iraq to reaffirm American hegemony.[fn::https://www.aljazeera.com/amp/indepth/opinion/bush-war-iraq-190318150236739.html]
That is, he did it just because he could.
** What is the problem with West Java?
Jawa Barat: sudah berpenduduk terbanyak[fn::https://ilmupengetahuanumum.com/jumlah-penduduk-indonesia/],
sarang ekstremis pula.[fn::https://www.jpnn.com/news/mms-sebut-jawa-barat-sarang-ekstrimis]
** Core beliefs
If a belief conflicts with reality, then the belief must change.

We define "good" as "promoting the survival of the human species".

/Nationalism is collective egoism./
There should be only one government on Earth, and it should be The Only World Government,
because otherwise governments will fight each other due to national egoism.

/Religion is a mental illness/, although it can help people establish order and find peace. We respect people, not beliefs.

We prefer to be /sober/ and savor every moment of our lives.
The only time we use consciousness-altering drugs is in great pain, such as in surgeries or in terminal illnesses.
We do not drink alcohol to the point of intoxication.

/We hate smoke/: cigarettes, vapes, you name it, we hate it.
We do not smoke.

/We hate perfumes./
We prefer no odor at all.
We prefer slight natural body odor to perfumes.

We think a little dandruff and a little body odor is normal.

We treat most bacteria as essential, not as things to be eradicated.
We only use antibiotics if it is the only way to save us from death.

We do not want to change the status quo for the sake of change without reason.
Disruption is not something to be proud of.
Every change has unintended consequences.

We prefer /sustainability/ to growth.

/Leisure/ is noble and there is nothing shameful about wanting leisure, seeking sustainability, and shunning gratuitous growth.

/Pension is robbing the young to pay the old./
It assumes that the population pyramid will always have a certain shape.
It is not sustainable.
** Science is a verifiable religion
It is simple to verify natural science; just run the experiments.
All scientists will find the same facts about Nature.

On the other hand, until we find a way to rewind time, we cannot verify religion and history;
we can only corroborate sources and reason by counterfactuals as to which explanation is most likely, given what we know.
If we don't know all the relevant facts, we will draw the wrong conclusion about the past.
** <2019-08-21> Hiring from trading point of view: buy low sell high
Everything is trading: Buy low, sell high.

Hiring is trading too.
Buy labor cheap, sell products high.

Labor has maintenance costs, just like machines.
Skimp on machine maintenance, they break down.
Skimp on labor maintenance, they resign, or worse, they riot, or even worse, they unionize.
** <2019-08-21> Capitalism and morality?
From https://evonomics.com/role-of-morality-in-a-capitalist-economy/
#+BEGIN_QUOTE
Now, what do you mean social good? In economics and evolution we have a well-defined concept of public goods.
Production of public goods is individually costly, while benefits are shared among all.
I think you see where I am going.
As we all know, selfish agents will never cooperate to produce costly public goods.
I think this mathematical result should have the status of “the fundamental theorem of social sciences.”
#+END_QUOTE
** Sejarah Islam Indonesia
https://www.nu.or.id/post/read/71691/awal-mula-masuknya-islam-di-indonesia-menurut-mbah-maimoen-
** FairTube, and renaming "advertising"
I hope FairTube wins, but the root cause of the problem is that today's "advertising" is about /making people buy/,
by psychological manipulation, by all means, at all costs;
whereas the original 15th century meaning of "to advertise" is to "give notice to others"[fn::https://www.etymonline.com/search?q=advertise].
There was no sense of persuasion in the 15th-century advertising.

In 2019, "advertising" is about manipulating people into buying things, by all means not forbidden by law.
Thus what we call "advertising" now, we should call "for-profit psychological manipulation".
** There is no such thing as "straight" or "gay"
Men have been putting their dicks wherever they want to since humans existed:
in their own hands, in other women, in other men, in goats, in horses, you name it, someone has put their dick in it.
** On modern monetary theory?
We should think of /taxes/ as a way for /incentivizing/ behaviors, /not/ for /funding/ government programs.
The government can just create money out of nothing, as long as the money creation rate does not exceed the real economic growth rate.
Indeed, right now, banks are creating money out of nothing, in the form of loans,
and these virtual numbers can have real effects on prices:
If, at the same time, one million people get loans and buy cars,
then there will be a short-term shortage of cars (demand surge),
and producers may decide to increase production or raise prices or both if the surge persists.

But what if the real economy is shrinking?
** Growing food is the best solution to poverty
Growing food is the only sane way to lift many people out of poverty, because /Nature pays everyone who works/.

It reduces unemployment, poverty, homelessness, crime.

Example[fn::https://www.bbc.com/indonesia/majalah-47052996]
** Seek wealth, not money
If one wants to be rich, then one should seek wealth, not money.
One should always know that money is only a proxy of wealth, and the conversion of money to wealth always depends on who is willing to accept that money.
** Examples of costly cost-cutting when management overrides engineers
I used to argue for nuclear fission power.
Now I argue against nuclear fission power, not because it is harmful, but because companies cannot be trusted.
I feel that companies are inherently incompatible with humanity; they centralize power to shareholders.

I trust engineers and scientists, but I don't trust companies.
If a nuclear power plant is run by a company, it is just a matter of time
before someone in management cuts costs for short-term profit,
skimps on something, dismisses the engineers, and causes an accident.
It has happened with airplanes (such as Boeing 737 MAX, they cut corners because they were competing with Airbus),
nuclear fission power plants (such as TEPCO Fukushima, they ignored an engineer's concern about the backup pump's vulnerability to giant tsunami).

When you ignore an engineer, a disaster will happen,
and you will bear a much higher cost than what would cost you if you just did what the engineer told you to do.
Disrespecting engineers and scientists is disrespecting Nature, and /Nature does not care about your profits./
** A scalable solution to poverty
1. Relocate poor people to fertile land that is unused but not too far from civilization; give each family 100 square meters.
2. Help them grow food; educate and train them. Pay attention to ecology, and close the nutrient cycle.
3. Help them sell their production.

This simultaneously solves hunger, poverty, homelessness, overcrowding, and crime.

This reduces agricultural failure risk:
More small farms distributed geographically means we have more backups to a regional catastrophe.

Indonesia will lose 20% corn production by 2050 due to climate change?
 [fn::https://medium.com/@jeremyerdman/we-produce-enough-food-to-feed-10-billion-people-so-why-does-hunger-still-exist-8086d2657539]
** An insightful clustering of America into 11 nations
https://www.npr.org/2013/11/11/244527860/forget-the-50-states-u-s-is-really-11-nations-says-author
** I'd rather have polices not work than have them incentivized to catch people
Incentivizing police to catch people is extremely dangerous;
I'd rather have police not work than have them eagerly incriminate people.

Police should not be rewarded for making arrests.
Police should not be rewarded for successful trials.
* Vital service failure log
** Internet service providers
*** Fastnet
Every time Fastnet goes down when
I want to connect to the Internet,
I'll write here.

2016-11-29 it went down.

2016-12-13 it went down due to someone else's fault.
Kabel kecangkul alat berat orang lain di depan BCA KCP Kepa Duri Jl Mangga.

2017-06-15 00:00 +0700 it went down.
04:00 I went to bed, and it was still down.
It went up again some time between 04:00 and 10:30.
The downtime was more than 4 hours.

2017-08-11 00:00 +0700 it went down.
2017-08-11 02:30 +0700 it went up.
The downtime was 2 hours 30 minutes.

2017-08-24 08:00 +0700 it went down.
2017-08-24 12:24 +0700 I left home for office; it was still down.
2017-08-25 02:00 +0700 I went home from office; it had gone up.
The downtime was less than 18 hours.
I forgot to ask the people at home how long it had been down.

2017-10-09 11:00 +0700 it went down.
They said it would go up on 2017-10-10 23:00 +0700 (24 hour downtime).
2017-10-10 03:23 +0700 it hadn't gone up.
It finally went up, but I didn't note when.

In 2018, we stopped using Fastnet.
We switched to CBN.
*** CBN
Plus:
CBN lebih murah daripada Fastnet.
CBN fiber upload lebih cepat daripada Fastnet ADSL.

Minus:
CBN lebih sering mati.
/CBN sangat sering mati./

2017-12-23 00:00 CBN mati sekitar 12 jam.

2018-05-22 04:27 CBN mati.
04:37 sudah nyala.

2018-07-17 22:32 CBN mati.

2018-09-07 11:30 - 13:30 CBN mati.

2018-09-26 02:04 - 12:11 CBN mati.

2018-11-16 00:16 CBN mati sebentar.

2018-11-26 16:45 - 17:30 CBN mati.
Hujan petir.

2018-11-29 16:00 CBN mati.

2018-11-30 00:30 CBN mati.

2018-12-17 04:00 CBN mati.
14:00 nyala.
** WhatsApp bullshit I have to put up with
<2018-12-13>
WhatsApp Web requires Chrome 36+ or newer?
I have Chromium 65.
** PLN electricity distribution
Zona waktu GMT+7.

Daerah Green Ville tahap 4, Jakarta Barat.

2017-10-05 13:42 PLN mati.

2017-12-20 00:17 PLN mati sekitar 15 menit.

2018-01-02 07:00 PLN mati.
Waktu kembali hidup tidak dicatat.

2018-04-03 22:00 brownout.
00:00 mati total.
07:20 nyala.

2018-??-??: Gardu PLN meledak.

("Sebentar" berarti "sekitar 10 detik".
Zona waktu UTC+7.)

PLN mati sebentar:
- 2018-05-10 02:50
- 2018-05-10 20:00
- 2018-08-08 23:28
- 2018-09-18 01:18
- 2018-09-19 02:55
- 2018-12-07 01:39
- 2018-12-07 23:00

2019-03-05 05:20 one-second brown-out.

2019-07-29 00:22 one-minute black-out.

2019-07-30 00:12 one-minute black-out.

Mengapa PLN suka mati sebentar?

- 2018-08-14 23:58 PLN mati sebentar.
  - This corrupts Chromium profile.
  - Chromium fails to restore tabs.
    - This is the second time it fails.
  - My response:
    - Discard tabs at the end of browsing.
      - Open Chromium with predefined tabs.
      - This also solves two other problems: tab hoarding and information overload.

I wish we have distributed electricity generation with solar panels and batteries.
Electric utility companies should die.

2019-08-04 11:00-21:00 pln mati se-jawa barat & jawa tengah
21:00 Nyala sebentar cuma 2 jam
23:14 mati lagi
06:00 nyala
10:00 mati lagi
15:30 nyala

2019-08-23 01:25 mati lampu beberapa detik

Semoga monopoli PLN dihapus.

Dalam pengalaman saya sebagai warga Jakarta,
PAM Jakarta jadi becus setelah diswastakan.
Saat PAM masih dipegang negara, airnya kecil, kotor, dan berlumpur.
** <2018-09-22> Derita naik Gojek/Gocar
Saya sempat coba Grab dan Gojek.
Saya tidak pakai Grab karena saya benci kode promo.
Akhirnya berlabuh di Gojek.

- Gojek
  - Kadang pengemudi tidak bisa membaca.
    Tiap minggu ada saja pengemudi yang tidak baca catatan, lalu nyasar.
    Sangat buang waktu.
  - Kadang dapat motor Yamaha Aerox.
    - Motor ini tidak aman; pusat massa tinggi, mengurangi kestabilan.
    - Motor ini tidak nyaman; joknya keras, suspensinya keras, menyiksa pantat.
    - Contoh motor yang enak: Honda Scoopy.
      Tampilannya emang culun, tapi jok lebar dan empuk, dan suspensi juga lembut.
      Enak buat pantat.
    - (Saya tidak punya motor.
      Saya bukan fans Yamaha ataupun Honda.
      Saya cuma benci sakit pantat.)
  - Kadang ban kempes.
    Kadang motor bocor.
    Kadang ban bocor.
  - Pernah, jam 17:00, 30 menit gak ada yang ambil.
- Gocar
  - Kadang pengemudi mengantuk, merem melek.
    Mobil ngegas ngerem.
  - Posisi suka ngaco.
    Minta jemput di S Parman, supir di Mal Pondok Indah lah (12 km), di Pejompongan lah (6 km), di Tomang lah (4 km), di sisi jalan yang salah lah (4 km).
  - Kadang di-cancel 5 kali baru dapat.
  - Kadang mobil bau rokok.
- Grabbike
  - <2018-10-05> Grab jam 17 sangat shitty.
    Driver tidak bisa dihubungi.
    Dua kali berturut-turut.
- Grabcar
  - <2018-10-25> Saya ditinggal kabur supir grabcar, padahal saya tinggal 5 langkah dari mobil, dan dia belum ada 5 menit menunggu.
- Aplikasi Gojek vs Grab:
  - Grab lebih reliable.
  - Gojek lebih hemat baterai.
- Perasaan saya.
  - Teknologi keduanya shitty, tapi teknologi Grab less shitty daripada teknologi Gojek;
    Grabcar lebih bisa mencari supir yang dekat (500 m, 1 km); Gocar seringkali dapat supir (2 km, bahkan pernah 6 km).
  - Supir Gocar memperlakukan penumpang lebih baik daripada supir Grabcar memperlakukan penumpang.
    Mungkin karena Gojek lebih kejam ke supir.
** Gmail
- I know it's free and my life depends on it, but I need to rant.
  - Who says it's free? I paid it with my privacy!
*** <2018-11-03> Plain text 78-character hard word wrap. It's 2018, and I open Gmail in a browser, in an almost 30-inch screen.
- Either the request fell on deaf ears, or the forum is not the right place for requests.
  https://productforums.google.com/forum/#!msg/gmail/rThTLh3KY7s/ACN9M300XYAJ
*** <2016-04-01> Harmful miscommunication-inducing deal-breaking enemy-making April fools' day prank
April fools' day is harmful.

Pranks are harmful.

[[http://www.telegraph.co.uk/technology/2016/04/01/gmails-mic-drop-april-fool-backfires-costing-people-their-jobs/][Gmail mic drop April fools' day prank]]
is [[http://www.businessinsider.co.id/google-pulls-mic-drop-minions-april-fools-joke-due-to-complaints-job-losses-2016-4/#.Vv43px_I7Qo][a stupid idea]], and also a harmful one, it turns out.

I, among who knows how many of the other [[http://techcrunch.com/2016/02/01/gmail-now-has-more-than-1b-monthly-active-users/][1 billion users]],
was sending an email to a head recruiter for a job on the following Monday (2016-04-04)
when I accidentally pressed that damn button.

Pranks violate the [[https://en.wikipedia.org/wiki/Cooperative_principle][cooperative principle]].

The next time you're going to play pranks: just don't.
Better spend your time somewhere else.
* Other article drafts
** <2019-07-06> AWS RDS automated backup doesn't always work
AWS RDS PostgreSQL point-in-time recovery (PITR) does not always work.

The error message is only the phrase "Incompatible-restore", and no more information.
What the hell?

Always routinely test the restorability of your backups.

In a company with 50 engineers,
there is one potentially business-ending accident per year,
like an accidental deletion of a production database.

A good system is not designed by wishing that people are smart.
Scripts have shitty user interfaces.
Smart people make mistakes.

Meanwhile, accidents do happen elsewhere in the cloud.
 [fn::GOTO 2017 • Debugging Under Fire: Keep your Head when Systems have Lost their Mind • Bryan Cantrill https://www.youtube.com/watch?v=30jNsCVLpAE]
Joyent, Heroku, AWS, Gitlab.
Accidental reboots.
Accidental table droppings.
Other costly software accidents are
Ariane-5[fn::https://iansommerville.com/software-engineering-book/case-studies/ariane5/]
and Therac-25[fn::https://en.wikipedia.org/wiki/Therac-25] (but is it really a software accident?).
It's just a matter time before there is a software accident as massive as Chernobyl.

I think most software accidents can be attributed to the hubris of some humans,
be it of managers, engineers, or operators, or a combination of them.
** <2019-07-06> Network Address Translation contributes to oppression
NAT is unholy: It contributes to the oppression of dissidents and journalists, because it hampers peer-to-peer technologies.
It precludes peer-to-peer truly distributed Web.
But P2P (peer-to-peer) over NAT may be possible with UDP/TCP/ICMP hole-punching.
Require an intermediary server only for initial handshake and then the connection is "handed over".

Really no 3rd party in this NAT traversal?[fn::https://github.com/samyk/pwnat]
** <2019-07-06> Best laughters
- lateralusmaster's laughing at mountain dew name votes https://www.youtube.com/watch?v=rxu3kZPlZx8
- shadowporker's laughing at "gluten-free lapdances" https://www.youtube.com/watch?v=beA-HMLVb9M
- Rabbit fall (kanin faldet) Big Brother DK https://www.youtube.com/watch?v=kGKMVXxyXXY&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=7
- Bradley Walsh cracks up at Fanny Chmelar https://www.youtube.com/watch?v=qfRwUKjJMxE&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=12
- news anchor reading the name "Chris P Bacon"
- Russian news anchor reading news about bears in marijuana plantation
- Man Struggles To Make It Up His Icy Driveway With Trash Can 2:41, 2:47 https://www.youtube.com/watch?v=xlrLFadODEA&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=22
- Meterstick Jim - The Sims 3: The funniest patch notes https://www.youtube.com/watch?v=4nxsCZ2SEcQ&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=23
** <2019-07-06> Two approaches to living: here-first and there-first
There are two approaches to living:
- There-first: Start with what you want, and find what you should have:
  Find what things have to exist in order to satisfy the goal.
- Here-first: Start with what you have, and find what you should want:
  Find what can be done with what already exists.
** <2019-07-06> Friendship is fluid and circumstantial
At 10 years old, we are friends because we are in the same class, and we don't have better things to do.
Simple physical proximity.
But we stop being friends as soon as we graduate out of school.

At 20 years old, we are friends because we are in the same company.
We stop being friends as soon as we resign.

At 30 years, we are friends because we share a goal or hobby or problem, because we care about a common thing.
We stop being friends as soon as our problem is solved.
** <2019-07-06> Knots
Knots are complex.
Seemingly dead knots in my shorts can suddenly untie when tugged some time after they were tied.
** <2019-07-06> Blinking Morse code as covert communication channel
Jeremiah Denton signals "torture" by blinking on TV while he was a war prisoner in Vietnam.
 [fn::https://qz.com/1625459/learning-morse-code-is-a-valuable-skill-even-in-the-21st-century/]
** <2019-07-07> Using government data?
Marc Dacosta: Adventures in the Dark Web of Government Data[fn::https://www.youtube.com/watch?v=SzkyuGeNDf8]:
joining multiple disparate data sources.
** <2019-08-14> Electromagnetic wave
In Maxwell's theory, an electric charge instantaneously affects all of space,
and an electromagnetic wave is not something emitted by an electric charge.
** <2019-08-17> Economics: anti-cafe
In anti-cafe, one pays for time, not for food.[fn::https://en.wikipedia.org/wiki/Anti-café]
** <2019-08-20> Howto: Send gmail as namesilo email
namesilo: "Please note that we do not offer a service for sending email."[fn::https://www.namesilo.com/Support/What-Email-Service-is-right-for-me%3F]
Follow these instructions to set up gmail[fn::https://www.namesilo.com/Support/Gmail-Instructions-for-Reply~to-Using-Custom-Domain].

There are two SMTP servers.
Receiving and sending use /different/ SMTP servers.
Receiving email uses Emailowl SMTP, /but/ sending email uses Gmail SMTP.
Set up Gmail "app password".
** <2019-08-20> Decentralized routing? Replacement to phone numbers?
How to keep in touch with public key cryptography without phone numbers:

Key idea: To use public key as mailbox address, and to use gossip to spread.

Everyone has a key pair.

Suppose Alice wants to send message M to Bob.

Alice encrypts M with Bob's public key, into E.

Alice broadcasts E to all her friends (a friend is a node she knows).

Her friends broadcast E to all their friends who have not yet received E.

(What?)

What about mesh networks?
How do we install routers at our neighbors' homes?
** <2019-08-20> A genius way to deal with scammers: "Reply all"
Bringing Scammers Together (Not Harmonious!) - Scambaiting By Reply-All
https://www.youtube.com/watch?v=py-cQ5PscsU
** <2019-08-21> Ideas that don't work: Cooling with ice bottles
Should we just buy a portable air conditioner, or a big fan with misting capability?

https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node118.html

https://www.reddit.com/r/askscience/comments/27yfbd/cooling_a_room_with_ice_and_a_fan_does_it_even/
https://www.quora.com/How-do-you-calculate-how-much-ice-you-need-to-cool-down-a-room-using-thermodynamics
https://burakkanber.com/blog/cooling-a-room-with-2-liters-of-ice-calculation/

Ignoring humidity, we want to cool 10x3x3 = 90 m3 of air from 33 deg C to 27 deg C using ice blocks.

Assume that the heat capacity of air is 0.001 J / cm3 / K = 1 MJ / m3 / K
https://en.wikipedia.org/wiki/Heat_capacity#Table_of_specific_heat_capacities

Thus we have to remove 90 m3 * 6 K * 1 MJ / m3 / K = 540 MJ of heat from the air in the room.

Some thermal conductivity parameters at 1 bar in watt per meter per kelvin
[fn::http://hyperphysics.phy-astr.gsu.edu/hbase/Tables/thrcn.html]:
- ice is 1.6
- air at 33 deg C is 0.02684[fn::https://www.engineeringtoolbox.com/air-properties-viscosity-conductivity-heat-capacity-d_1509.html]
- water between 0 and 33 deg C is about 0.58
- aluminum is 205.0
- 1 bar is approximately 1 atm

To feel comfortable while resting, we must constantly dissipate heat at a rate of about 90 watts.[fn::http://hyperphysics.phy-astr.gsu.edu/hbase/thermo/coobod.html]
** <2019-08-21> On Factorio
"SparenofIria" gives the strongest argument for left-hand drive, the argument that cannot be refuted without changing game mechanics:
 [fn::https://www.reddit.com/r/factorio/comments/9wxjxc/why_lefthand_drive_rail_is_more_efficient_for/e9p3mkd/]

#+BEGIN_QUOTE
Reason: You always exit trains to the left, and it's better to exit onto empty space than to exit onto another track or between tracks.
#+END_QUOTE
** <2019-08-24> How does the player know what kills Crash in Crash Bandicoot?
Although the game never explicitly instructs players about what things would kill Crash,
players seem to have an /instinct/ or /intuition/ about such things.
For example, animals, traps, fires, and falling would kill Crash.
Players seem to /just know/ how to play the game.
But that is only because the dangerous things in the game world /correspond/ to dangerous things in the real world;
thus players /already know/.
It seems that /most/ adult humans know /some/ ways of avoiding death:
If doing something kills you, then simply don't do it.

The polar opposite is Minecraft:
Even with instructions, players still take time to find out how to play the game.
** On Tesla autopilot crashes
The question is:
Where do they get their training data from?
What are their samples?
What does their training data represent?

My guess is that they have few scenarios involving trailers, if any, in their training data,
because it is rather rare to encounter trailers.
** My doomer music playlist
*** To sink into the ocean of doom
May these musical pieces be of some consolation to fellow doomers.

"Oblivion", by Astor Piazzolla.

"Can't say goodbye to yesterday", by Rika Muranaka, sung by Carla White.

These two songs are American songs with lush orchestral background.

"Yesterdays", sung by Ella Fitzgerald.

"My romance", Mel Tormé.
Mel's suave light voice and the lush orchestral background.

"Yesterday", The Beatles.

"Yesterday when I was young", sung by Matt Monro.

"Fragile", by Sting.

"Gabriel's Oboe", by Ennio Morricone.

"Lacrimosa", from "Requiem", by Wolfgang Amadeus Mozart.

"Seacht suáilcí na Maighdine Muire", Aoife Ní Fhearraigh.

"The best is yet to come", by Rika Muranaka, sung by Aoife Ní Fhearraigh.

"Sorry seems to be the hardest word", Blue featuring Elton John.

"God rest you merry gentlemen".
For this song, I prefer the Aeolian mode, some inverted chords, a tempo of about 60 bpm,
and a conservative solemn arrangement that does not try too hard to impress the listener.
There is also Annie Lennox's interesting arrangement, although I would prefer its harmony to be in Aeolian mode.

"My way", Elvis Presley.

"End of the world", Aphrodite's Child.
*** To float in the ocean of doom
These are a little upbeat.

But no matter how hard one tries, one eventually sinks into the ocean of doom,
into eternal oblivion, into the nothingness that he came from.

"The unsung war", Ace Combat 5.

"Liberation of Gracemeria", Ace Combat 6.
An interesting rhythmic invention; that syncopated ostinato is genius.
It still feels satisfying even after many replays.

"Follow me", Pat Metheny.

"Fairy tales", Anita Baker.

"Are you real?", Art Blakey & The Jazz Messengers.

"I'm Mr Jody", Marvin Sease.

"All rise", Blue.

"Asman", Gulnur Satylganova.

"Wakare no yokan", Teresa Teng.

"Toki wo kakeru shoujo", Harada Tomoyo.

The NAAFP (National Association for the Advancement of Fat People) anthem from Family Guy.
Beautiful harmony.
I love the IV-III7-vi progression (in the "god's man-boobs are flabby and they hurt when he jogs" part).

Movement 1 of BWV 1052 (Harpsichord concerto in D minor), Johann Sebastian Bach.

Russian national anthem.
** <2019-08-27> On the nuclear option
There have been several nuke-related ideas:
Nuke /subduction plates/ to prevent big earthquakes;
Nuke /hurricanes/ to stop them[fn::https://www.bbc.com/news/world-us-canada-49471093];
Nuke /asteroids/ to prevent them from crashing into Earth.
But they all suffer from one problem: The nuke we have in 2019 is too weak for those purposes.

<2019-08-19> Idea: Explode atomic bombs at subduction plates to prevent bigger earthquakes.
Won't work[fn::https://earthscience.stackexchange.com/questions/4825/will-a-nuclear-bomb-stop-an-earthquake-from-happening]

But isn't it just a matter of making bigger bombs?
It is possible in principle.
We can leave it to the engineers; it's just a matter of time before they build a bomb big enough to move subduction plates.

It reminds me of George Carlin's saying: "The planet is fine. The people are fucked."
** It is important to make monuments at disaster sites
To pass on the knowledge to future generations, so that we do not forget, so that we do not waste lives.
 [fn::https://99percentinvisible.org/article/tsunami-stones-ancient-japanese-markers-warn-builders-high-water/]
** Can psychology solve terrorism?
The thing common to all terrorists is /belief/ and /segregation/.

Why do many people harbor extreme thoughts but only few act them out?
* Notes to self
I need to rewrite these pages:
[[file:compsci.html][Computer science]],
[[file:math.html][Mathematics]],
[[file:modeldata.html][Modeling all data]].
[[file:politik_masjid.html][Politik masjid]],
[[file:jakarta.html][Living in Jakarta]].

 [fn::https://en.wikipedia.org/wiki/Computer_science]
 [fn::Map of Computer Science https://www.youtube.com/watch?v=SzJ46YA_RaA]

<2017-05-25>:
Thanks to [[http://davidensinger.com/][David Ensinger]]'s
[[http://davidensinger.com/2013/11/building-a-better-sitemap-xml-with-jekyll/][code]],
Jekyll can generate sitemap.xml without plugins.

<2018-12-25>
Migrating from Jekyll to Pandoc broke some things.
The generated page [[file:all.html][All pages]] does not include Pandoc-generated pages.
Sitemap.xml is also broken in the same way.
** Notes for future AI recommender
Dear machine, please find me people whose interests are similar to mine.
These are some example of such people, mostly professors or ex-professors.
I have not met these people.
I have only seen publicly available information.

Why is there no professor search engine?
Why is there no Semantic Web ontology for research interests?
Idea: We can query[fn::https://query.wikidata.org/] Wikidata to find professors whose research interests intersect ours.
<2019-01-08>
I tried that, but Wikidata does not have much data relevant to that query.
*** Intersecting in two topics
Prof. Sanjeev Arora[fn::https://www.cs.princeton.edu/~arora/] is a member of
Princeton theory-of-computation group[fn::http://theory.cs.princeton.edu/],
Princeton ML Theory Group[fn::http://mltheory.cs.princeton.edu/],
and Arora Research Group[fn::http://unsupervised.cs.princeton.edu/].

https://www.quora.com/How-good-is-Princeton-at-machine-learning

https://www.math.ias.edu/theoretical_machine_learning
*** Intersecting in one topic
**** Computational complexity theory
Prof. Neil Immerman[fn::https://www.cics.umass.edu/faculty/directory/immerman_neil][fn::https://people.cs.umass.edu/~immerman/]
wrote the "Descriptive complexity" book[fn::www.cs.umass.edu/~immerman/book/descriptiveComplexity.html] published in 1999.
He is also a member of UMass CS Theory Group[fn::http://theory.cs.umass.edu/people.html] which has interesting theoretical researches.

https://www.quora.com/Which-professors-research-groups-are-working-on-mathematical-theoretical-understanding-of-deep-learning

Prof. Oded Goldreich[fn::http://www.wisdom.weizmann.ac.il/~/oded/]

Prof. Eric Allender[fn::https://www.cs.rutgers.edu/faculty/eric-allender]
**** Programming language theory
Prof. Philip Wadler[fn::http://homepages.inf.ed.ac.uk/wadler/]

Prof. Simon Peyton--Jones[fn::https://www.microsoft.com/en-us/research/people/simonpj/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fpeople%2Fsimonpj]
**** Artificial intelligence and machine learning
Prof. Jürgen Schmidhuber[fn::http://people.idsia.ch/~juergen/].

Prof. Elad Hazan[fn::https://www.cs.princeton.edu/courses/archive/spring16/cos511/]
**** Philosophy of computer science
Prof. William Rapaport[fn::http://www.buffalo.edu/cas/philosophy/faculty/emeriti/rapaport.html].

Prof. Brian Cantwell Smith[fn::https://ischool.utoronto.ca/profile/brian-cantwell-smith/].
** Which inquiries intersect?
My inquiries often intersect.
[[file:philo.html]] and [[file:intelligence.html]] intersect in modeling, mind, consciousness.
[[file:intelligence.html]] and [[file:social.html]] intersect in trust.
Philosophy of mind + logic meet software engineering + Prolog at "formal concept analysis"[fn::https://en.wikipedia.org/wiki/Formal_concept_analysis].
Philosophy, software engineering, and business modeling meet at "triune continuum paradigm"[fn::"The triune continuum paradigm is based on the three theories:
on Tarski's theory of truth, on Russell's theory of types and on the theory of triune continuum."
https://en.wikipedia.org/wiki/Triune_continuum_paradigm].
I disclaim any understanding.

* Site map (was goal tree)
- Survive and have fun
  - [[file:live.html][Live forever]]
    - Live healthily
      - Eat healthy foods;
        know the food we eat;
        be self-sufficient;
        - Produce our own foods
        - Compost excess foods
      - Sleep properly; eliminate circadian-rhythm disruptors
    - Preserve the environment
      - Have a closed personal nutrient cycle
  - [[file:plan.html][Be remembered forever]]
    - Be everywhere everytime
      - ???
        - Start a YouTube channel?
        - Start a Facebook page?
    - Say or write /contrarian/ things against prevailing opinions;
      be the devil's advocate;
      but it's bad to disagree for the sake of disagreement;
      one who /always/ disagrees is going to be /ostracized/
    - Make some /impacts/
      - Get the /resources/ required to make some impacts
        - Get /power/
          - [[file:power.html][Understand power]]
          - Get more physical power by exercising
          - [[file:rich.html][Get /rich/ quickly solving my problems without going to jail]]
            - <2019-04-22>
              I think the most feasible way for me to get power is to get rich.
            - Think entrepreneurially
            - Start a delivery-only healthy kitchen;
              I have difficulty finding affordable healthy food nearby
          - Gain /trust/ by Aristotelian rhetorics (ethos, logos, pathos)
            - Learn rhetorics, public speaking, and how to convince people
            - Settle controversial topics
              - Lead thoughts and opinions
              - [[file:religion.html][Understand religion]]
          - Understand and predict world /politics/ and /economics/
  - Fix my problems first before fixing more interesting problems?

This goal tree often changes.

This /backward planning/ is explained somewhere in [[file:meta.html]].

Goal tree is similar to /work breakdown structure/[fn::https://en.wikipedia.org/wiki/Work_breakdown_structure]
and /product breakdown structure/[fn::https://en.wikipedia.org/wiki/Product_breakdown_structure].
- WBS = goal tree + 100% rule + mutual exclusivity + procedural.
- PBS = WBS - procedural + declarative.

<2019-07-06>
I am tired of planning and thinking top-down.
Now I'm trying to think bottom-up, reactive, improvisatory, opportunistic.
* Perhaps not too important
** Why do you make this website?
Because I find thinking, writing, and planning fun.
This website contains questions that I think should be answered.

I think of myself as three different people:
- my past self
- my present self
- my future self

This website is a way for those three people to communicate.
** Who are you?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
** Should I trust you?
/No, you should not./
Anyone can put anything on the Internet.
Judge for yourself.
More disclaimers follow.

/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me without thinking for yourself.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to our beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
URLs may change.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.
** How should I interact with you?
You can pick one of these:
- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue at GitHub]].

Expect long delay.
If you don't get a reply after waiting for a few days,
try resending your message.
It does get lost sometimes.

If you are in Jakarta, we may meet in some meetups.
** Where else are you?
I may also be found at these places, but I rarely check them:
- [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]]
- [[https://www.linkedin.com/in/erikdominikus/][Linkedin:erikdominikus]]
** What are some similar websites?
These are some websites similar to this website and their differences.

[[https://kevinbinz.com/][kevinbinz.com]] is more like a blog than a wiki.

[[https://en.wikipedia.org/][en.wikipedia.org]] does not want original content.
(Also, if [[https://www.quora.com/Will-it-be-feasible-to-move-Wikipedia-mediaWiki-from-PHP-to-some-modern-language-like-Golang][Kelly Kinkade's answer]] is true, then it's worrying that so much human knowledge is stored in such unparseable MediaWiki markup language.)

TheBrain: the idea is good, but the app is slower than static web.

[[https://www.brainpickings.org][brainpickings.org]]:
too social, too much content, too little navigation, too little structure;
pop science content is too much pop and too little science.

* Bibliography
