#+TITLE: Erik Dominikus Research Group
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
#+MATHJAX: true
#+OPTIONS: ^:nil
* Overview of contents
My current interests are:
- [[file:esoteric-science.html][Esoteric science]], consciousness, spirituality, physics, philosophy, psychics, psychology, parapsychology,
  paranormalism, metaphysics, religion, health, well-being, wellness, afterlife;
  especially experiments, evidence, hypotheses, and testing.
  - [[file:psychic.html][The truth about psychics]]: combating rampant disinformation.
  - If you live in Jakarta, please consider the [[file:conscious-jakarta.html][Jakarta Consciousness Research Group]].
- [[file:literacy-topic.html][Literacy]], meta-research, independent researchers,
   [fn::<2019-11-27> https://en.wikipedia.org/wiki/Independent_scientist]
   [fn::<2019-11-27> https://www.nature.com/articles/nj7647-747a]
  fringe science,
  crowdfunding of research[fn::<2019-11-27> https://researchwhisperer.org/2017/08/15/patreon/].
- [[file:program-topic.html][Programming]]; programming language design and implementation;
  sometimes mathematics, sometimes artificial intelligence, sometimes machine learning.
- [[file:politics-topic.html][Politics]], sometimes.
* My story
<2019-12-12>

I am torn between many unrelated desires lingering in my mind for too long.
I want to research consciousness.
I want to create a programming language.
I want to compose music.
And so on; I wrote down my desires, spanning several pages.

Why do I want those?
Why can't I just want one thing?
Do I really want those, or do I just want to be busy; do I just want to want, and not actually do what I want?
Even though I am not a materialist, I am no better than materialists;
Both of us are tormented by our own desires.

Materialism and capitalism have outlived their usefulness and overstayed their welcome.

I think nations hamper scientific research.
There should be either one world government, one currency, and one law; or there should be none at all.

I made a [[file:plan.html][plan]], but I didn't stick to it.
Aim for the moon, they say.
I enjoyed aiming too much and never took a shot.
I enjoy my imagination more than my reality.
I can stay at bed for hours just imagining pleasant things; why can't I live in my own imagination?
Am I not imagining things strong enough?

I don't think I ever have any strong urge to live.
I am interested in the afterlife.

I want to know the truth.
* Caution and disclaimers
Contents and URLs may change without notice.

Updates are irregular, but usually at least once a week.

If you have good eyesight, you may want to zoom out by pressing Control-minus.
The fonts may be too big.

/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me without thinking for yourself.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to our beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
* Spirituality
** Universal love is the only way out
<2019-12-20>

In a capitalist society, companies enslave workers.

In a communist society, the state enslaves workers.
 [fn::<2019-12-20> https://cs.stanford.edu/people/eroberts/cs201/projects/communism-computing-china/workethic.html]

In an anarchistic society, powerful people enslave workers.

Thus, in all societies of various ideologies and systems, the powerful entities enslave the powerless entities. All societies are suffering from centralization of power. On the other hand, if power is not centralized, then anyone can take matters into their own hands.

The only way out of slavery is that every human must see others as he sees himself. If he can see others as he sees himself, he will treat others as he treats himself, and he will love others as he loves himself. Nothing outside humans is going to erase slavery. No system is going to erase slavery. No law is going to erase slavery. Even after all work has been relegated to machines, slavery will continue to exist as long as a human does not see others as he sees himself.

If all humans have universal love, then anarchy is the best society: they will not do evil even if there are no laws.

If every human loves others as he loves himself, he will not hurt others as he will not hurt himself; he will not steal from others as he does not steal from himself; he will not kill others as he will not kill himself.

Universal love is required for anarchy to work.

If we have universal love, then anarchy is the best society.

The thing that we must fix is not countries or companies.

/We/ ourselves are what we must fix.
* Vital service failure log
** Internet service providers
*** Fastnet
Every time Fastnet goes down when
I want to connect to the Internet,
I'll write here.

2016-11-29 it went down.

2016-12-13 it went down due to someone else's fault.
Kabel kecangkul alat berat orang lain di depan BCA KCP Kepa Duri Jl Mangga.

2017-06-15 00:00 +0700 it went down.
04:00 I went to bed, and it was still down.
It went up again some time between 04:00 and 10:30.
The downtime was more than 4 hours.

2017-08-11 00:00 +0700 it went down.
2017-08-11 02:30 +0700 it went up.
The downtime was 2 hours 30 minutes.

2017-08-24 08:00 +0700 it went down.
2017-08-24 12:24 +0700 I left home for office; it was still down.
2017-08-25 02:00 +0700 I went home from office; it had gone up.
The downtime was less than 18 hours.
I forgot to ask the people at home how long it had been down.

2017-10-09 11:00 +0700 it went down.
They said it would go up on 2017-10-10 23:00 +0700 (24 hour downtime).
2017-10-10 03:23 +0700 it hadn't gone up.
It finally went up, but I didn't note when.

In 2018, we stopped using Fastnet.
We switched to CBN.
*** CBN
<2019-10-30>
Update: CBN sudah tidak sering mati seperti dulu.
(Atau saya yang jarang di rumah?)

Plus:
CBN lebih murah daripada Fastnet.
CBN fiber upload lebih cepat daripada Fastnet ADSL.

Minus:
CBN lebih sering mati.
/CBN sangat sering mati./

2017-12-23 00:00 CBN mati sekitar 12 jam.

2018-05-22 04:27 CBN mati.
04:37 sudah nyala.

2018-07-17 22:32 CBN mati.

2018-09-07 11:30 - 13:30 CBN mati.

2018-09-26 02:04 - 12:11 CBN mati.

2018-11-16 00:16 CBN mati sebentar.

2018-11-26 16:45 - 17:30 CBN mati.
Hujan petir.

2018-11-29 16:00 CBN mati.

2018-11-30 00:30 CBN mati.

2018-12-17 04:00 CBN mati.
14:00 nyala.
** WhatsApp bullshit I have to put up with
<2018-12-13>
WhatsApp Web requires Chrome 36+ or newer?
I have Chromium 65.
** PLN electricity distribution
Zona waktu GMT+7.

Daerah Green Ville tahap 4, Jakarta Barat.

2017-10-05 13:42 PLN mati.

2017-12-20 00:17 PLN mati sekitar 15 menit.

2018-01-02 07:00 PLN mati.
Waktu kembali hidup tidak dicatat.

2018-04-03 22:00 brownout.
00:00 mati total.
07:20 nyala.

2018-??-??: Gardu PLN meledak.

("Sebentar" berarti "sekitar 10 detik".
Zona waktu UTC+7.)

PLN mati sebentar:
- 2018-05-10 02:50
- 2018-05-10 20:00
- 2018-08-08 23:28
- 2018-09-18 01:18
- 2018-09-19 02:55
- 2018-12-07 01:39
- 2018-12-07 23:00

2019-03-05 05:20 one-second brown-out.

2019-07-29 00:22 one-minute black-out.

2019-07-30 00:12 one-minute black-out.

Mengapa PLN suka mati sebentar?

- 2018-08-14 23:58 PLN mati sebentar.
  - This corrupts Chromium profile.
  - Chromium fails to restore tabs.
    - This is the second time it fails.
  - My response:
    - Discard tabs at the end of browsing.
      - Open Chromium with predefined tabs.
      - This also solves two other problems: tab hoarding and information overload.

I wish we have distributed electricity generation with solar panels and batteries.
Electric utility companies should die.

2019-08-04 11:00-21:00 pln mati se-jawa barat & jawa tengah
21:00 Nyala sebentar cuma 2 jam
23:14 mati lagi
06:00 nyala
10:00 mati lagi
15:30 nyala

2019-08-23 01:25 mati lampu beberapa detik

Semoga monopoli PLN dihapus.

Dalam pengalaman saya sebagai warga Jakarta,
PAM Jakarta jadi becus setelah diswastakan.
Saat PAM masih dipegang negara, airnya kecil, kotor, dan berlumpur.
** <2018-09-22> Derita naik Gojek/Grabbike/Gocar/Grabcar
<2019-10-30>
Update: Hal-hal di bawah sudah tidak berlaku.
Pada tahun 2019, Grab lebih bagus daripada Gojek.
Akhirnya saya kembali pakai Grab.

<2018-09-22>

Saya sempat coba Grab dan Gojek.
Saya tidak pakai Grab karena saya benci kode promo.
Akhirnya berlabuh di Gojek.

- Gojek
  - Kadang pengemudi tidak bisa membaca.
    Tiap minggu ada saja pengemudi yang tidak baca catatan, lalu nyasar.
    Sangat buang waktu.
  - Kadang dapat motor Yamaha Aerox.
    - Motor ini tidak aman; pusat massa tinggi, mengurangi kestabilan.
    - Motor ini tidak nyaman; joknya keras, suspensinya keras, menyiksa pantat.
    - Contoh motor yang enak: Honda Scoopy.
      Tampilannya emang culun, tapi jok lebar dan empuk, dan suspensi juga lembut.
      Enak buat pantat.
    - (Saya tidak punya motor.
      Saya bukan fans Yamaha ataupun Honda.
      Saya cuma benci sakit pantat.)
  - Kadang ban kempes.
    Kadang motor bocor.
    Kadang ban bocor.
  - Pernah, jam 17:00, 30 menit gak ada yang ambil.
- Gocar
  - Kadang pengemudi mengantuk, merem melek.
    Mobil ngegas ngerem.
  - Posisi suka ngaco.
    Minta jemput di S Parman, supir di Mal Pondok Indah lah (12 km), di Pejompongan lah (6 km), di Tomang lah (4 km), di sisi jalan yang salah lah (4 km).
  - Kadang di-cancel 5 kali baru dapat.
  - Kadang mobil bau rokok.
- Grabbike
  - <2018-10-05> Grab jam 17 sangat shitty.
    Driver tidak bisa dihubungi.
    Dua kali berturut-turut.
- Grabcar
  - <2018-10-25> Saya ditinggal kabur supir grabcar, padahal saya tinggal 5 langkah dari mobil, dan dia belum ada 5 menit menunggu.
- Aplikasi Gojek vs Grab:
  - Grab lebih reliable.
  - Gojek lebih hemat baterai.
- Perasaan saya.
  - Teknologi keduanya shitty, tapi teknologi Grab less shitty daripada teknologi Gojek;
    Grabcar lebih bisa mencari supir yang dekat (500 m, 1 km); Gocar seringkali dapat supir (2 km, bahkan pernah 6 km).
  - Supir Gocar memperlakukan penumpang lebih baik daripada supir Grabcar memperlakukan penumpang.
    Mungkin karena Gojek lebih kejam ke supir.
** Gmail
- I know it's free and my life depends on it, but I need to rant.
  - Who says it's free? I paid it with my privacy!
*** <2018-11-03> Plain text 78-character hard word wrap. It's 2018, and I open Gmail in a browser, in an almost 30-inch screen.
- Either the request fell on deaf ears, or the forum is not the right place for requests.
  https://productforums.google.com/forum/#!msg/gmail/rThTLh3KY7s/ACN9M300XYAJ
*** <2016-04-01> Harmful miscommunication-inducing deal-breaking enemy-making April fools' day prank
April fools' day is harmful.

Pranks are harmful.

[[http://www.telegraph.co.uk/technology/2016/04/01/gmails-mic-drop-april-fool-backfires-costing-people-their-jobs/][Gmail mic drop April fools' day prank]]
is [[http://www.businessinsider.co.id/google-pulls-mic-drop-minions-april-fools-joke-due-to-complaints-job-losses-2016-4/#.Vv43px_I7Qo][a stupid idea]], and also a harmful one, it turns out.

I, among who knows how many of the other [[http://techcrunch.com/2016/02/01/gmail-now-has-more-than-1b-monthly-active-users/][1 billion users]],
was sending an email to a head recruiter for a job on the following Monday (2016-04-04)
when I accidentally pressed that damn button.

Pranks violate the [[https://en.wikipedia.org/wiki/Cooperative_principle][cooperative principle]].

The next time you're going to play pranks: just don't.
Better spend your time somewhere else.
* Elaborate, rewrite, or discard?
** What?
Rewrite?

- [[file:plan.html]]
- [[file:rich.html][Get /rich/ quickly solving my problems without going to jail]]

Discard?

- [[file:politik_masjid.html][Politik masjid]],
- [[file:jakarta.html][Living in Jakarta]].
- [[file:live.html][Live forever]]
- [[file:goal.html][Goals]]

what
 [fn::https://en.wikipedia.org/wiki/Computer_science]
 [fn::Map of Computer Science https://www.youtube.com/watch?v=SzJ46YA_RaA]

<2017-05-25>:
Thanks to [[http://davidensinger.com/][David Ensinger]]'s
[[http://davidensinger.com/2013/11/building-a-better-sitemap-xml-with-jekyll/][code]],
Jekyll can generate sitemap.xml without plugins.

<2018-12-25>
Migrating from Jekyll to Pandoc broke some things.
The generated page [[file:all.html][All pages]] does not include Pandoc-generated pages.
Sitemap.xml is also broken in the same way.
** Notes for future AI recommender
Dear machine, please find me people whose interests are similar to mine.
These are some example of such people, mostly professors or ex-professors.
I have not met these people.
I have only seen publicly available information.

Why is there no professor search engine?
Why is there no Semantic Web ontology for research interests?
Idea: We can query[fn::https://query.wikidata.org/] Wikidata to find professors whose research interests intersect ours.
<2019-01-08>
I tried that, but Wikidata does not have much data relevant to that query.
*** Intersecting in two topics
Prof. Sanjeev Arora[fn::https://www.cs.princeton.edu/~arora/] is a member of
Princeton theory-of-computation group[fn::http://theory.cs.princeton.edu/],
Princeton ML Theory Group[fn::http://mltheory.cs.princeton.edu/],
and Arora Research Group[fn::http://unsupervised.cs.princeton.edu/].

https://www.quora.com/How-good-is-Princeton-at-machine-learning

https://www.math.ias.edu/theoretical_machine_learning
*** Intersecting in one topic
**** Computational complexity theory
Prof. Neil Immerman[fn::https://www.cics.umass.edu/faculty/directory/immerman_neil][fn::https://people.cs.umass.edu/~immerman/]
wrote the "Descriptive complexity" book[fn::www.cs.umass.edu/~immerman/book/descriptiveComplexity.html] published in 1999.
He is also a member of UMass CS Theory Group[fn::http://theory.cs.umass.edu/people.html] which has interesting theoretical researches.

https://www.quora.com/Which-professors-research-groups-are-working-on-mathematical-theoretical-understanding-of-deep-learning

Prof. Oded Goldreich[fn::http://www.wisdom.weizmann.ac.il/~/oded/]

Prof. Eric Allender[fn::https://www.cs.rutgers.edu/faculty/eric-allender]
**** Programming language theory
Prof. Philip Wadler[fn::http://homepages.inf.ed.ac.uk/wadler/]

Prof. Simon Peyton--Jones[fn::https://www.microsoft.com/en-us/research/people/simonpj/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fpeople%2Fsimonpj]
**** Artificial intelligence and machine learning
Prof. Jürgen Schmidhuber[fn::http://people.idsia.ch/~juergen/].

Prof. Elad Hazan[fn::https://www.cs.princeton.edu/courses/archive/spring16/cos511/]
**** Philosophy of computer science
Prof. William Rapaport[fn::http://www.buffalo.edu/cas/philosophy/faculty/emeriti/rapaport.html].

Prof. Brian Cantwell Smith[fn::https://ischool.utoronto.ca/profile/brian-cantwell-smith/].
** Which inquiries intersect?
My inquiries often intersect.
[[file:philo.html]] and [[file:intelligence.html]] intersect in modeling, mind, consciousness.
[[file:intelligence.html]] and [[file:social.html]] intersect in trust.
Philosophy of mind + logic meet software engineering + Prolog at "formal concept analysis"[fn::https://en.wikipedia.org/wiki/Formal_concept_analysis].
Philosophy, software engineering, and business modeling meet at "triune continuum paradigm"[fn::"The triune continuum paradigm is based on the three theories:
on Tarski's theory of truth, on Russell's theory of types and on the theory of triune continuum."
https://en.wikipedia.org/wiki/Triune_continuum_paradigm].
I disclaim any understanding.

** Site map (was goal tree)
Goal tree is similar to /work breakdown structure/[fn::https://en.wikipedia.org/wiki/Work_breakdown_structure]
and /product breakdown structure/[fn::https://en.wikipedia.org/wiki/Product_breakdown_structure].
- WBS = goal tree + 100% rule + mutual exclusivity + procedural.
- PBS = WBS - procedural + declarative.

<2019-07-06>
I am tired of planning and thinking top-down.
Now I'm trying to think bottom-up, reactive, improvisatory, opportunistic.
** Ideas that don't work?
*** <2019-08-21> Cooling with ice bottles
Should we just buy a portable air conditioner, or a big fan with misting capability?

https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node118.html

https://www.reddit.com/r/askscience/comments/27yfbd/cooling_a_room_with_ice_and_a_fan_does_it_even/
https://www.quora.com/How-do-you-calculate-how-much-ice-you-need-to-cool-down-a-room-using-thermodynamics
https://burakkanber.com/blog/cooling-a-room-with-2-liters-of-ice-calculation/

Ignoring humidity, we want to cool 10x3x3 = 90 m3 of air from 33 deg C to 27 deg C using ice blocks.

Assume that the heat capacity of air is 0.001 J / cm3 / K = 1 MJ / m3 / K
https://en.wikipedia.org/wiki/Heat_capacity#Table_of_specific_heat_capacities

Thus we have to remove 90 m3 * 6 K * 1 MJ / m3 / K = 540 MJ of heat from the air in the room.

Some thermal conductivity parameters at 1 bar in watt per meter per kelvin
[fn::http://hyperphysics.phy-astr.gsu.edu/hbase/Tables/thrcn.html]:
- ice is 1.6
- air at 33 deg C is 0.02684[fn::https://www.engineeringtoolbox.com/air-properties-viscosity-conductivity-heat-capacity-d_1509.html]
- water between 0 and 33 deg C is about 0.58
- aluminum is 205.0
- 1 bar is approximately 1 atm

To feel comfortable while resting, we must constantly dissipate heat at a rate of about 90 watts.[fn::<2019-10-27> http://hyperphysics.phy-astr.gsu.edu/hbase/thermo/coobod.html]

Although the ice bottle project did not bear fruit, I learned something for building my next house.
*** <2019-08-27> On the nuclear option
There have been several nuke-related ideas:
Nuke /subduction plates/ to prevent big earthquakes;
Nuke /hurricanes/ to stop them[fn::https://www.bbc.com/news/world-us-canada-49471093];
Nuke /asteroids/ to prevent them from crashing into Earth.
But they all suffer from one problem: The nuke we have in 2019 is too weak for those purposes.

<2019-08-19> Idea: Explode atomic bombs at subduction plates to prevent bigger earthquakes.
Won't work[fn::https://earthscience.stackexchange.com/questions/4825/will-a-nuclear-bomb-stop-an-earthquake-from-happening]

But isn't it just a matter of making bigger bombs?
It is possible in principle.
We can leave it to the engineers; it's just a matter of time before they build a bomb big enough to move subduction plates.

It reminds me of George Carlin's saying: "The planet is fine. The people are fucked."
** <2019-07-06> Best laughters
- lateralusmaster's laughing at mountain dew name votes https://www.youtube.com/watch?v=rxu3kZPlZx8
- shadowporker's laughing at "gluten-free lapdances" https://www.youtube.com/watch?v=beA-HMLVb9M
- Rabbit fall (kanin faldet) Big Brother DK https://www.youtube.com/watch?v=kGKMVXxyXXY&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=7
- Bradley Walsh cracks up at Fanny Chmelar https://www.youtube.com/watch?v=qfRwUKjJMxE&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=12
- news anchor reading the name "Chris P Bacon"
- Russian news anchor reading news about bears in marijuana plantation
- Man Struggles To Make It Up His Icy Driveway With Trash Can 2:41, 2:47 https://www.youtube.com/watch?v=xlrLFadODEA&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=22
- Meterstick Jim - The Sims 3: The funniest patch notes https://www.youtube.com/watch?v=4nxsCZ2SEcQ&list=PLZrbXygxJiiu5zWE_EmpVrP7ZbYzbujoT&index=23
- Prank interview with Elijah Wood https://www.youtube.com/watch?v=IfhMILe8C84
** <2019-07-06> Knots
Knots are complex.
Seemingly dead knots in my shorts can suddenly untie when tugged some time after they were tied.
** My doomer music playlist
*** To sink into the ocean of doom
May these musical pieces be of some consolation to fellow doomers.

"Oblivion", by Astor Piazzolla.

"Can't say goodbye to yesterday", by Rika Muranaka, sung by Carla White.

These two songs are American songs with lush orchestral background.

"Yesterdays", sung by Ella Fitzgerald.

"My romance", Mel Tormé.
Mel's suave light voice and the lush orchestral background.

"Yesterday", The Beatles.

"Yesterday when I was young", sung by Matt Monro.

"Fragile", by Sting.

"Gabriel's Oboe", by Ennio Morricone.

"Lacrimosa", from "Requiem", by Wolfgang Amadeus Mozart.

"Seacht suáilcí na Maighdine Muire", Aoife Ní Fhearraigh.

"The best is yet to come", by Rika Muranaka, sung by Aoife Ní Fhearraigh.

"Sorry seems to be the hardest word", Blue featuring Elton John.

"God rest you merry gentlemen".
For this song, I prefer the Aeolian mode, some inverted chords, a tempo of about 60 bpm,
and a conservative solemn arrangement that does not try too hard to impress the listener.
There is also Annie Lennox's interesting arrangement, although I would prefer its harmony to be in Aeolian mode.

"My way", Elvis Presley.

"End of the world", Aphrodite's Child.
*** To float in the ocean of doom
These are a little upbeat.

But no matter how hard one tries, one eventually sinks into the ocean of doom,
into eternal oblivion, into the nothingness that he came from.

"The unsung war", Ace Combat 5.

"Liberation of Gracemeria", Ace Combat 6.
An interesting rhythmic invention; that syncopated ostinato is genius.
It still feels satisfying even after many replays.

"Follow me", Pat Metheny.

"Fairy tales", Anita Baker.

"Are you real?", Art Blakey & The Jazz Messengers.

"I'm Mr Jody", Marvin Sease.

"All rise", Blue.

"Asman", Gulnur Satylganova.

"Wakare no yokan", Teresa Teng.

"Toki wo kakeru shoujo", Harada Tomoyo.

The NAAFP (National Association for the Advancement of Fat People) anthem from Family Guy.
Beautiful harmony.
I love the IV-III7-vi progression (in the "god's man-boobs are flabby and they hurt when he jogs" part).

Movement 1 of BWV 1052 (Harpsichord concerto in D minor), Johann Sebastian Bach.

Russian national anthem.
* Games
** <2019-08-24> How does the player know what kills Crash in Crash Bandicoot?
Although the game never explicitly instructs players about what things would kill Crash,
players seem to have an /instinct/ or /intuition/ about such things.
For example, animals, traps, fires, and falling would kill Crash.
Players seem to /just know/ how to play the game.
But that is only because the dangerous things in the game world /correspond/ to dangerous things in the real world;
thus players /already know/.
It seems that /most/ adult humans know /some/ ways of avoiding death:
If doing something kills you, then simply don't do it.

The polar opposite is Minecraft:
Even with instructions, players still take time to find out how to play the game.

** <2019-08-21> On Factorio
"SparenofIria" gives the strongest argument for left-hand drive, the argument that cannot be refuted without changing game mechanics:
 [fn::https://www.reddit.com/r/factorio/comments/9wxjxc/why_lefthand_drive_rail_is_more_efficient_for/e9p3mkd/]

#+BEGIN_QUOTE
Reason: You always exit trains to the left, and it's better to exit onto empty space than to exit onto another track or between tracks.
#+END_QUOTE
* Finance
** Financial research articles
[[file:stock.html][On stocks, their prices, and their financial valuation]]

[[file:valuation.html][On financial valuation]]
** On valuation
Aswath Damodaran – Laws of Valuation: Revealing the Myths and Misconceptions (FULL PRESENTATION)
https://www.youtube.com/watch?v=c20_S-QgvsA
4:25 corporate life cycle: from birth to death
Valuation is a bridge between numbers and stories
In a young company, story matters more than numbers
In an old company, numbers matter more than story

https://www.youtube.com/watch?v=Z5chrxMuBoo
pricing (momentum, emotion) vs valuation (asset, growth, reinvestment, liability, risk, story)
51:32 investing is more luck than skill?
1:01:01
Interesting point of view:
"[...] Don't overreach.
You don't get /rich/ by investing.
You get rich by doing whatever you're doing, and investing is about /preserving/ what you made elsewhere and /growing/ it.
It's when you get greedy about trying to make that killing on your investment that you tend to overreach."
[emphasis mine]

Aswath Damodaran: "The Value of Stories in Business" | Talks at Google
https://www.youtube.com/watch?v=uH-ffKIgb38
12:50 the story should be possible, plausible, and probable

https://www.youtube.com/watch?v=VlcmHhbYeNY
Valuation is not pricing.
Venture capitalists do pricing not valuation.
* Business
** Inspiring Internet onion seller
Inspiring Internet onion seller[fn::https://www.deepsouthventures.com/i-sell-onions-on-the-internet/]:
It's /stupidly simple/, but it's /real money/.
It's /good business/.

https://www.bradford-delong.com/2017/07/how-to-think-like-an-economist-if-that-is-you-wish-to.html
https://hackernoon.com/how-to-make-more-money-as-a-software-developer-da9fc13944e4
https://en.wikipedia.org/wiki/Economic_system
https://en.wikipedia.org/wiki/Circular_economy

https://en.wikipedia.org/wiki/Productivity_model
https://en.wikipedia.org/wiki/Productive_forces
https://en.wikipedia.org/wiki/Production_(economics)
** <2019-08-17> Economics: anti-cafe
In anti-cafe, one pays for time, not for food.[fn::https://en.wikipedia.org/wiki/Anti-café]
* Other things
** Why do you make this website?
Because I find thinking, writing, and planning fun.
This website contains questions that I think should be answered.

I think of myself as three different people:
- my past self
- my present self
- my future self

This website is a way for those three people to communicate.
** Who are you?
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
** Should I trust you?
/No, you should not./
Anyone can put anything on the Internet.
Judge for yourself.
More disclaimers follow.
** How should I interact with you?
You can pick one of these:
- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue at GitHub]].

Expect long delay.
If you don't get a reply after waiting for a few days,
try resending your message.
It does get lost sometimes.

If you are in Jakarta, we may meet in some meetups.
** Where else are you?
I may also be found at these places, but I rarely check them:
- [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]]
- [[https://www.linkedin.com/in/erikdominikus/][Linkedin:erikdominikus]]
** What are some similar websites?
These are some websites similar to this website and their differences.

[[https://kevinbinz.com/][kevinbinz.com]] is more like a blog than a wiki.

[[https://en.wikipedia.org/][en.wikipedia.org]] does not want original content.
(Also, if [[https://www.quora.com/Will-it-be-feasible-to-move-Wikipedia-mediaWiki-from-PHP-to-some-modern-language-like-Golang][Kelly Kinkade's answer]] is true, then it's worrying that so much human knowledge is stored in such unparseable MediaWiki markup language.)

TheBrain: the idea is good, but the app is slower than static web.

[[https://www.brainpickings.org][brainpickings.org]]:
too social, too much content, too little navigation, too little structure;
pop science content is too much pop and too little science.

<2019-11-05>

[[https://glennelert.us/][Glenn Elert]] writes online [[https://hypertextbook.com/][hypertext books]] similar in spirit to this website.
* Bibliography
