#+TITLE: Erik Dominikus's home page
#+DATE: 2017-05-20 00:00:00 +0700
#+PERMALINK: /index.html
* About the author and the website
My name is Erik Dominikus.
I am an independent[fn::https://en.wikipedia.org/wiki/Independent_scientist] researcher from Indonesia,
with too many interests, mostly theoretical,
because theoretical research is low-cost and can be done at home[fn::https://en.wikipedia.org/wiki/Armchair_theorizing],
because I don't have the resources for experimental research.
Most of my writings involve applied analytic philosophy, mathematics, and computers.
(Applied analytic philosophy is the careful usage of words to discover the essence of things.)

My last formal education degree, if you care, is a Sarjana Ilmu Komputer[fn::https://en.wikipedia.org/wiki/Bachelor_of_Computer_Science] degree bestowed in 2011 by the
Fakultas Ilmu Komputer[fn::https://www.cs.ui.ac.id/] of Universitas Indonesia[fn::https://www.ui.ac.id/] for four years of undergraduate education.
* Disclaimers
/I may err./
Read cautiously.
Compare with other independent sources.
Do not trust me.
Use your own judgement.

/I am not responsible for what other people write in their comments,/ but I can remove comments from my website.
People are free to say whatever they want, and people are free to disagree with whatever others say,
as long as they do that in a civilized manner.

/I may change./
I am not attached to my beliefs.
Things I wrote in the past should not be solely used to judge my present self.

Most pages are messy drafts.
URLs may change.
* Research
Perhaps now you are asking "What do you have for me?"
How do I answer that?
It depends on your interests.
You may wear multiple hats as I do.
But I wrote this website primarily for myself.
Thus the question becomes "What do I have for myself",
that is "What do I really want", that is, "What is important for me?"
If you have some common goals or interests, then get in touch, drop a comment.
We should join forces to reach our shared goals.
** Meta-research
I am [[file:research.html][looking for ways to research more efficiently]].

If we are interested in article A authored by W published in journal J,
then which should we zoom into: author W or journal J?

An author has a long-term unchanging ambition.
An author has a deep interest in a narrow subfield.

A journal publishes similar articles.

There are too many journals for authors to compare.
Authors publish to where their friends publish.
Thus it is important that people with similar interests know each other.
** Computing
I am trying to make machines work more for me.

I am [[file:proglang.html][looking for the best programming language]],
some of which may involve [[file:haskell.html][improving Haskell]].
I am [[file:prolog.html][using Prolog]].

I am [[file:publish.html][looking for a publishing system]].
I also write
[[file:emacs.html][Using Emacs and Org Mode]],
[[file:emacsvi.html][Emacs for vi users]],
[[file:writing.html][Writing]],
and [[file:markdown.html][Working around Markdown]].

I am [[file:parse.html][looking for parsing techniques]],
because parsing is the common thing between programming language and publishing system, and I am looking for both.
Meanwhile, I had to understand Brzozowski quotient and set division,
so I wrote [[file:division.html][Generalizing division]].

I am [[file:pnptry.html][trying to understand the P vs NP problem]].
I was motivated by the prize money[fn::one million US dollars http://www.claymath.org/millennium-problems/millennium-prize-problems], but I think my chances are slim.

I am looking for an AI that helps me process data into information.
Thus I write [[file:intelligence.html][Making intelligence]] and
[[file:endo.html][The endofunction model of worlds and agents, and its philosophical implications]].
But I think my chances are slim.

Computer science[fn::https://en.wikipedia.org/w/index.php?title=Computer_science&oldid=875563283#Etymology]
is a branch of mathematics, not a branch of science,
which is the application of the scientific method to make falsifiable theories.
** Philosophy
I am [[file:philo.html][trying to understand the relationship between "mind" and "brain"]].

I am [[file:nature.html][trying to understand physics]].

I am [[file:finite.html][looking for a philosophically sound foundation of mathematics]].
It may be finitism.
** Society
I am looking for a technology that empowers people and liberates people, a technology that makes oppression physically impossible.
I am trying to codify (that is, to express in English) our implicit morality, that is, the implicit moral system that we have evolved.
Thus I write [[file:social.html][Designing the ideal society]].
I thought I could change the world with politics, but now I think politics only wastes time,
and now I think technology is the only hope for making something in the physical-law layer to bypass the convoluted human-made-law layer.
I think law should be principle-based, and justice should be restorative.
I think the world needs only one law: Try not to harm others.
Nobody bothers to fix the broken political systems.
Nobody even bothers to think.
Political systems are too expensive to fix; it is much cheaper to scrap them.

I [[file:usecom.html][use computers]].
I [[file:phone.html][buy a smartphone]] when my old smartphone becomes unusable.
** Software engineering
I am thinking about open-source.
I prefer cooperation to competition.
I write
[[file:opensrc.html][Making contributable open-source projects]],
[[file:community.html][Building online communities]].
I am thinking about maintaining open-source projects.

Sometimes I think about forward software engineering,
such as [[file:softeng.html][making lasting software sooner]].

Sometimes I think about [[file:reveng.html][reverse software engineering]],
such as[[file:ps1.html][Reverse-engineering PlayStation 1 3D games to control the camera]].

I wanted to automate stock trading with my broker which has a stock trading application written in Java 6.
Thus I wrote [[file:rejava.html][Reverse engineering the network protocol used by a Java desktop application]].
But now I think financial economy is just a big Ponzi scheme full of rent-seeking,
full of people who want to get a slice of the pie of real economy without growing the pie of real economy,
full of people who just want to extract value from society without creating value,
people who only take but don't give,
people who only shuffle money around.

I tried to think about [[file:engman.html][managing software engineers]].
I thought about [[file:salary.html][software engineer salary]].

Is software engineering engineering?
What is engineering?
** Farming
I thought about [[file:subsist.html][starting a farm in the middle of Jakarta]],
but I put it on hold because I felt that the opportunity cost was too high.

The key to farming is to understand ecology, some botany (plant physiology and pathology), and nutrient cycle.

We should care more about phosphate run-off.
Phosphates are vital and non-renewable, like fossil fuel.
The bad news is that there is no cycle bringing back the phosphates from the sea to the land, unlike water with its hydrologic cycle.
** Unimportant
I collect [[file:entertain.html][entertainments found on the Internet]].

I [[file:groom.html][somewhat care about appearance]].

I am [[file:world.html][somewhat pessimistic about the 21st century]].

My inquiries often intersect.
[[file:philo.html]] and [[file:intelligence.html]] intersect in modeling, mind, consciousness.
[[file:intelligence.html]] and [[file:social.html]] intersect in trust.

I occasionally played weiqi (also known as igo/baduk)[fn::https://en.wikipedia.org/wiki/Go_(game)],
but after AlphaGo[fn::https://en.wikipedia.org/wiki/AlphaGo] beat[fn::https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol] Lee Sedol, I abandoned weiqi and never looked back.
I see no point in doing something that machines can do better than I do.

I was once fleetingly interested in these things:
[[file:art.html][Art]],
[[file:music.html][Music]],
[[file:game.html][Game]].

Here are some unsolicited opinions.

I think Semantic Web is wrong.
It is backward Artificial Intelligence.
Humans should not dumb themselves down for the sake of machines.
Machines should smarten up and understand English.

I think Wikipedia translation is futile.
I think the right way is to write everything in English, and invent an AI that translates human languages better than human does.
* Music
I played piano in the band [[file:nomads.html][The Nomads]] (an Indonesian band, not the Swedish band).
However, I quit being a performer on 2018-12-23, less than a year after joining the band, because I hate inhaling cigarette smoke in venues and I hate carrying pianos to venues.
I am no longer a pianist.
I am now a composer with an asset mindset.
* Notes to self
[[file:goal.html][Goals]] should be merged into this page.

[[file:meta.html][Meta]] (my thoughts about this website itself) should be merged into this page.

Migrating from Jekyll to Pandoc broke some things.
The generated page [[file:all.html][All pages]] does not include Pandoc-generated pages.
Sitemap.xml is also broken in the same way.

These files are a mess.
I need to find a reason of their existence.
- [[file:math.html][Mathematics]]
- [[file:modeldata.html][Modeling all data]]: should be moved?
- Living in the 21st century
  - Hidup di Indonesia abad 21
    - [[file:politik_masjid.html][Politik masjid]]
    - [[file:jakarta.html][Living in Jakarta]]

[[file:other.html][Unimportant content]]:
this page badly needs massive reorganization.
This page is also a staging area, a queue, a scratchpad, for the things I shall process later.

- [[file:compsci.html][Computer science]]: page needs massive restructuring
  - Learning computer science
    - [[https://en.wikipedia.org/wiki/Computer_science][WP:Computer science]]
    - [[https://www.youtube.com/watch?v=SzJ46YA_RaA][YT:Map of Computer Science]]
  - [[file:compute.html][Computation]]

Perhaps I should delete these pages:
- [[file:smf.html][Standard MIDI file format]]
- Programming
  - Using Java
    - Building a Java project
      - 2018-08-29: For Java enterprise/server programming, I recommend Maven instead of Gradle.
      - 2019-01-01: I recommend using Prolog instead of Java.
- Searching
  - Where does this fit in the hierarchy?
  - [[https://en.wikipedia.org/wiki/Optimal_stopping][WP:Optimal stopping]]
* Contact
To ask questions, suggest corrections, or add something, do any of these:

- Leave a Disqus comment in the related page.
- [[https://github.com/edom/edom.github.io/issues][Open an issue on GitHub]].
- Leave something at [[https://twitter.com/ErikDominikus][Twitter:ErikDominikus]].

If you are in Jakarta, we may meet in some meetups.

I think I should create a second email address.
