#+TITLE: Language Research Group
#+DATE: 2019-02-05 00:00:00 +0700
#+PERMALINK: /language.html
#+OPTIONS: ^:nil
* Language
** A language is a convention
A /language/ is a convention of signs, meanings, and how to interpret those symbols into those meanings.
Thus a language has /syntax/ (how it looks) and /semantics/ (what it means).
A /sign/ may be visual, aural, tactile, or anything that a human can perceive.
Visual signs are seen, such as writings, sign languages, semaphores.
Aural signs are heard, such as speech.
Tactile signs are touched, such as Braille.

Sign or symbol?

Must a language have meaning?

In the 13th century, "language" means "words, what is said, conversation, talk".[fn::https://www.etymonline.com/word/language]
The Latin word "lingua" means "tongue".

We associate symbols with meanings.

A language is a means of communication.

A language is a set of mutually agreed symbols.

A language may contain logic.

Is being a language objective or subjective (teleological)?
A symbol does not have meaning on its own; someone has to interpret it.

Some animals may have languages.[fn::https://en.wikipedia.org/wiki/Animal_language].

A language constructs symbols by computable/finite means.

A language is a convention for encoding/decoding/representing meaning.

What is English? It depends on when.
Middle English was English.
What people in 1400 call "English" and what people in 2000 call "Middle English" is the same thing.
https://en.wikipedia.org/wiki/Middle_English
** Language preservation
*** How do we interpret old texts if languages shift?
In order to understand an old text, we have to interpret it as its writer did.
*** Preserving language for future generations
If we are to help future generations, we must resist changing our languages.
We must resist changing the meaning of existing words.
** What is communication?
We use language for communication.
What is communication?

"Communicable" means "spreadable".

what
 [fn::https://www.etymonline.com/word/communication]
 [fn::https://www.etymonline.com/word/communicate]
** Limitations of languages
*** A language enables transfer of wit but not of ken?
Language cannot be used to spread knowledge that has to be directly experienced by the senses.
It is impossible to describe with language what "red" or "hot" are; they have to be directly experienced.
No amount of talking will make someone who has never tasted wine knows what it tastes like.
** Meta-languages and second-language acquisition
A language may be rich enough for humans to use to describe the language itself.

We can describe English in English.

An erratum (a document about correcting another document) uses English as meta-language.
Such erratum contains meta-statements such as "in pages 123-234, replace each occurrence of 'Foo' with 'Bar'".

Second language acquisition is the usage of a language as a meta-language for describing the target language.
For example, an English speaker learning German uses English as a meta-language for describes German.

Should a language be rich enough for us to describe itself?

What about programming languages?
Reflection?

For example, we can use English+Java+math as a meta-language for teaching English-speaking Java programmers about Scheme/Haskell.
** Semantics, semiotics, linguistics, confusion
Jake Mitchell pointed out[fn::https://twitter.com/mekajfire/status/1090689517701349376]
that there are a lot of confusing pair of terms in philosophy:
sense and reference, signifier and signified, use-mention distinction, concept and object.

* Meaning
** What is a meaning?
What do we mean by "X means Y"?
If words do not have meaning, then what is the "meaning of a word"?
** Meaning arises from interpretation; words do not carry meaning
Words do not carry meaning; we interpret words.
If words carried meaning, then misunderstanding would be impossible, and people would not have to learn languages.

"Meaning of a word" is meaningless?
A word alone does not have meaning.
We interpret a word into a meaning depending on context/situation.
** How-do vs how-should questions, what are the meanings?
A how-do question is answered with a fact.

A how-should is answered with a justified belief.

How do we cook an egg?
Heat it by whatever means: fire, boiling, microwave, etc.

How should we cook an egg?
It depends: do we want to preserve nutrition, minimize carcinogens, or make delicacy?

"How should we do X" is "What is the best way for us to do X and why is that the best way".
* Grammar and syntax
** What is grammar and syntax?
"Grammar" comes from Greek "grammatike (tekhne)" that means "(art) of letters".[fn::https://www.etymonline.com/word/grammar]
In 1600, "syntax" is "a putting together or in order, arrangement, a grammatical construction".[fn::https://www.etymonline.com/word/syntax]

We limit our analysis to formal languages.

Grammar vs syntax
 [fn::https://linguistics.stackexchange.com/questions/3484/whats-the-difference-between-syntax-and-grammar]
 [fn::https://english.stackexchange.com/questions/29577/whats-the-difference-between-grammar-and-syntax].
** A grammar is a convention
A /grammar/ is a convention for representing meanings as symbols.
A meaning is /abstract/, ideal.
A symbol is /concrete/, material, tangible, transmissible, perceptible.
A symbol may be a character, a pictogram, a diagram, a syllable, etc.

An /ungrammar/ is a convention for interpreting symbols into meanings.

We represent meanings as shapes that others can perceive and interpret.
It just happens that we represent meanings as strings of characters in computers.

We can mathematically model a grammar as a relation between form and meaning: \(G \subseteq F \times M\).
In computers, \(F = C^*\) is the set of all character strings, and \(M\) is the set of all abstract-syntax-tree nodes.
Defining grammar as relation gives rise to a way of writing parsers as logic programs.
What is the literature on the logic of grammar/parsing?
DCG?
#+BEGIN_EXAMPLE
% grammar(?Form, ?Meaning).
#+END_EXAMPLE

The correspondence:
- one Chomskyan production rule ~ one Horn clause

A /grammar relation/ is a relation \(G \subseteq C^* \times T\).
The set \(C\) is the /alphabet/.
The set \(C^*\) is the /Kleene closure/ of \(C\).
The set \(T\) is the set of /syntax trees/.

Let \(G\) be a grammar.

We say that a string \(S\) is /grammatical/ with respect to \(G\) iff there exists a tree \(T\) such that \(G(S,T)\).
We may omit "with respect to \(G\)" if it is clear from context that there is only one grammar.

Iff the grammar relation is a function, then we say that the grammar is /unambiguous/.
** Must a grammar concern only strings and trees?
Trees are graphs.
Why stop at trees?
Why not graphs?

- [[https://en.wikipedia.org/wiki/Graph_rewriting][WP:Graph rewriting]]
- 2015 slides "Graph grammars" [[http://www.its.caltech.edu/~matilde/GraphGrammarsLing.pdf][pdf]]
- 1993 article "A Graph Parsing Algorithm and Implementation" [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.612.9698&rep=rep1&type=pdf][pdf]]
- 1990 article "A Graph Parsing Algorithm" [[https://dl.acm.org/citation.cfm?id=859753][paywall]]

What are graph grammars?
 [fn::https://en.wikipedia.org/wiki/Graph_rewriting]
 [fn::https://cstheory.stackexchange.com/questions/39393/what-are-graph-grammars]
** How do we model/specify grammar?
Wikipedia?
 [fn::https://en.wikipedia.org/wiki/Grammar]
 [fn::https://en.wikipedia.org/wiki/Formal_grammar]

There are several ways.

Recursive descent parsing?[fn::https://en.wikipedia.org/wiki/Recursive_descent_parser]

Chomsky 1956 \cite{chomsky1956three} phrase-structure grammar: non-terminals, terminals, and rules.
See also semi-Thue system, string rewriting system, Post rewriting system.

Backus-Naur Form "is a notation technique for context-free grammars"[fn::https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form].

Shieber 1995, parsing as deduction, logic programming\cite{shieber1995principles}.
** Does attribute grammar indeed specify the semantics of the language?
https://en.wikipedia.org/wiki/Attribute_grammar
** How should we specify grammars?
"How should I specify a grammar for a parser?"[fn::https://softwareengineering.stackexchange.com/questions/107266/how-should-i-specify-a-grammar-for-a-parser]
* Understanding
** What is understanding?
To understand X is to construct an internal predictive model of X?
** Hypothesis: an organ that understands causality will understand language
* Logic, truth
What is truth?
Truth is what is true.

What is true?
"True" is real, factual, in line with reality.

An /open formula/ is a formula that has one or more free variables.[fn::https://en.wikipedia.org/wiki/Open_formula]

The truth of an open formula /may/ depend on the substitution of the free variables.

Some formulas are true or false due to their form, even though they contain free variables. For example: in classical logic, \( p \wedge (p \to q) \to q \) is true regardless of what \(p\) and \(q\) are. Another example: in classical logic, then \( p \wedge \neg p \) is false regardless of what \(p\) is.

If a formula's truth can be proven by virtue of its form alone, then it is true in all interpretations?

Classical logic assumes two things: material implication and the law of excluded middle.
* Designing languages
** What can language pedagogy teach us about programming language design and pedagogy?
How do we learn languages?

How do we learn second languages?

Spaced repetition, constant usage, total immersion.

Gegg 1995 \cite{gegg1995representing} (emphasis ours):
"The key difference between experts and novices is not the size of their memory span, but rather their ability to /chunk/ information together into meaningful units.
Schemata provide a method of organizing meaningful information about complex domains.
Experts have more and better problem schemata than novices.
Novice programmers tend to categorize problems based on surface syntax-based features of the problem statement,
while experts categorized problems with respect to a more abstract hierarchical organization of algorithms [...]."

What can we learn from Loglan, Lojban, Esperanto, etc?
** What is a good language?
A good language is simple, consistent, predictable.
** Minimizing expected energy required to communicate
More-often-used words are shorter to minimize the expected energy required to communicate.

Often-used words are short.
Seldom-used words are long.

Likely words are short.
Unlikely words are long.

"Expected" means that the language evolves or is designed with certain use-cases in mind.
Hypothesis: Natural languages evolved to maximize human survival.
* History
** How did the first translator translate?
* References
