#+TITLE: Language Research Group
#+DATE: 2019-02-05 00:00:00 +0700
#+PERMALINK: /language.html
#+OPTIONS: ^:nil
* What is a language?
A /language/ is a convention of signs, meanings, and how to interpret those symbols into those meanings.
Thus a language has /syntax/ (how it looks) and /semantics/ (what it means).
A /sign/ may be visual, aural, tactile, or anything that a human can perceive.
Visual signs are seen, such as writings, sign languages, semaphores.
Aural signs are heard, such as speech.
Tactile signs are touched, such as Braille.

Language cannot be used to spread knowledge that has to be directly experienced by the senses.
It is impossible to describe with language what "red" or "hot" are; they have to be directly experienced.
No amount of talking will make someone who has never tasted wine knows what it tastes like.
Wine is basically rotten grape juice.

Sign or symbol?

A language may be rich enough for humans to use to describe the language itself.

Must a language have meaning?

In the 13th century, "language" means "words, what is said, conversation, talk".[fn::https://www.etymonline.com/word/language]
The Latin word "lingua" means "tongue".

We associate symbols with meanings.

A language is a means of communication.

A language is a set of mutually agreed symbols.

A language may contain logic.

Is being a language objective or subjective (teleological)?
A symbol does not have meaning on its own; someone has to interpret it.

Some animals may have languages.[fn::https://en.wikipedia.org/wiki/Animal_language].

A language constructs symbols by computable/finite means.

A language is a convention for encoding/decoding/representing meaning.

What is English? It depends on when.
Middle English was English.
What people in 1400 call "English" and what people in 2000 call "Middle English" is the same thing.
https://en.wikipedia.org/wiki/Middle_English

In order to understand an old text, we have to interpret it as its writer did.

If we are to help future generations, we must resist changing our languages.
We must resist adding or changing the definitions of words.

"Meaning of a word" is meaningless?
A word alone does not have meaning.
We interpret a word into a meaning depending on context/situation.

What do we mean by "X means Y"?
* What is a meaning?
* What is an understanding?
* What can language pedagogy teach us about programming language design and pedagogy?
How do we learn languages?

How do we learn second languages?

Spaced repetition, constant usage, total immersion.

Gegg 1995 \cite{gegg1995representing} (emphasis ours):
"The key difference between experts and novices is not the size of their memory span, but rather their ability to /chunk/ information together into meaningful units.
Schemata provide a method of organizing meaningful information about complex domains.
Experts have more and better problem schemata than novices.
Novice programmers tend to categorize problems based on surface syntax-based features of the problem statement,
while experts categorized problems with respect to a more abstract hierarchical organization of algorithms [...]."
* How-do vs how-should questions, what are the meanings?
A how-do question is answered with a fact.

A how-should is answered with a justified belief.

How do we cook an egg?
Heat it by whatever means: fire, boiling, microwave, etc.

How should we cook an egg?
It depends: do we want to preserve nutrition, minimize carcinogens, or make delicacy?

"How should we do X" is "What is the best way for us to do X and why is that the best way".
* Meta-languages?
** Should a language be rich enough for us to describe itself?
We can describe English in English.

What about programming languages?
Reflection?

An erratum (a document about correcting another document) uses English as meta-language.
Such erratum contains meta-statements such as "in pages 123-234, replace each occurrence of 'Foo' with 'Bar'".

Second language acquisition is the usage of a language as a meta-language for describing the target language.
For example, an English speaker learning German uses English as a meta-language for describes German.
* What is a good language?
A good language is simple, consistent, predictable.
** Why are more often-used words shorter?
To minimize the expected energy required to communicate.

Often-used words are short.
Seldom-used words are long.

Likely words are short.
Unlikely words are long.
* What?
** Hypothesis: an organ that understands causality will understand language
** Semantics, semiotics, linguistics, confusion
Jake Mitchell pointed out[fn::https://twitter.com/mekajfire/status/1090689517701349376]
that there are a lot of confusing pair of terms in philosophy:
sense and reference, signifier and signified, use-mention distinction, concept and object.
** How did the first translator translate?
** Logic, truth
What is truth?
Truth is what is true.

What is true?
"True" is real, factual, in line with reality.

An /open formula/ is a formula that has one or more free variables.[fn::https://en.wikipedia.org/wiki/Open_formula]

The truth of an open formula /may/ depend on the substitution of the free variables.

Some formulas are true or false due to their form, even though they contain free variables. For example: in classical logic, \( p \wedge (p \to q) \to q \) is true regardless of what \(p\) and \(q\) are. Another example: in classical logic, then \( p \wedge \neg p \) is false regardless of what \(p\) is.

If a formula's truth can be proven by virtue of its form alone, then it is true in all interpretations?

Classical logic assumes two things: material implication and the law of excluded middle.
* References
