#+TITLE: On literacy
#+DATE: 2019-08-17 00:00:00 +0700
#+PERMALINK: /literacy.html
#+MATHJAX: true
* Communication
** Communication basics
Writing and speaking are /transmission/, the conversion of thought to symbols.

Reading and listening are /reception/, the conversion of symbols to thought.

To /communicate/, the transmitter and the receiver must share the necessary /background knowledge/ and /language/.

A /language/ is a system that relates utterances and meanings.

The /background knowledge/ is a set of beliefs.

A /belief/ is a logical formula with no free variables.
** Reading-and-writing as /asynchronous/ dialog
Readers come with questions.
Writers give answers.

Readers come with problems.
Writers give solutions.
* The /asymmetry/ between reading and writing
** Writing is harder than reading
Writers write for readers.
Readers read for themselves, not for writers.
Writers are expected to write from the reader's point of view.
Readers are not expected to read from the writer's point of view.

Readers have the money.

Readers expect more from writers than writers expect from readers.
The writer is supposed to be the party that spends more effort in the communication.

Writing is harder than reading because writers /must/ think more than readers do.
Writers cannot /passively/ write;
they must first come up with some /thoughts/ to write before they can write anything at all.
Readers can passively read a text and still suboptimally benefit from it.

Another contributing factor to that asymmetry is the physical constraint
that eyes can move faster than hands,
but perhaps there will be machines to dump our thoughts directly into symbols,
or even to directly transmit our thoughts to others, directly between brains, without eyes and hands.

Speaking is harder than listening for the same reason:
Speaking requires thought, and listening does not.
** Writers have voice and authority
It is easy to copy the writing many times,
and it is hard to change all copies of the writing.
* How do write /efficiently convincing/ text?
Writers try to convince readers, even in narratives.

But readers try to reinforce their beliefs?

Not only arguments, but also narratives, must be convincing.

Psychology.

Avoid triggering the reader's /defense mechanism/.
* Not writer's block, but thinker's block
This is the basic writing method:

1. A thought appears in one's mind.
2. He writes that down.

The problem is not about finding what to write, but finding what to /think/.
A writer's block is actually a /thinker's block/.
It is not about running out of words.
It is about running out of /thoughts/.

Writing begins with /thoughts/, not words.
Writing is converting thoughts to text.
If one has no thoughts, he has nothing to convert to text.
* Iteration
Writers rewrite many times.
Readers reread many times.

Rewriting improves text.
Rereading improves thought.
* Top-down vs bottom-up reader
From "Version control with Subversion"[fn::http://svnbook.red-bean.com/en/1.7/svn.preface.howread.html]:
#+BEGIN_QUOTE
Technical books always face a certain dilemma: whether to cater to /top-down/ or to /bottom-up/ learners.
A top-down learner prefers to read or skim documentation, getting a large overview of how the system works; only then does she actually start using the software.
A bottom-up learner is a "learn by doing" person—someone who just wants to dive into the software and figure it out as she goes, referring to book sections when necessary.
#+END_QUOTE
* Begin with a question
This is the way to fecund writing.
Begin with a question.
Then answer it.

This is the way to productive reading.
Begin with a question.
Then seek the answer.

Can we infer "what is good reading" from this "What is good writing" article[fn::https://writingcooperative.com/what-is-good-writing-6379d77cd0c5]?
* How should we write?
** Writing; topic position and stress position
"A reader will unconsciously focus at the end of the sentence to identify what is important."[fn::https://www.springer.com/gp/authors-editors/authorandreviewertutorials/writinginenglish/stress-position/10252690]

It is more important for the sentences of a paragraph to have /related topics/ than to have active voice \cite{gopen1990science}.
(A sentence's topic is what in its topic position.)
** TODO Writing?
https://medium.com/@write4research/why-do-academics-and-phders-carefully-choose-useless-titles-for-articles-and-chapters-518f02a2ecbb

https://medium.com/@write4research/top-ten-questions-to-ask-about-your-chapter-start-32848d924953

** A writing method?
Writing
- rewrite = read + think + write
- Dont rewrite while writing. Dont edit while writing. Let thoughts out.
- the predicate is more important than the subject.
- avoid long subject
- cluster related ideas together
- a predicate must occur no later than the seventh word in the sentence?

Constrained writing:
- each sentence in the same paragraph has the same subject?
- the first sentence is both a claim and a summary. The first sentence summarizes the paragraph.

Example:
#+BEGIN_QUOTE
X is good. <why x is good>
#+END_QUOTE
** Writer vs editor
Writers vomit their ideas into words;
editors clean up the mess.[fn::https://mshannonhernandez.com/the-writer-vs-the-editor-dont-confuse-the-roles/]
** It is important to motivate the reader
It is counter-productive to begin a mathematical text with a definition.
Such text should begin with /motivation/.

It is counter-productive to begin a textbook in group theory by listing the group axioms.
We are creative humans, not mechanical theorem provers.

Such textbook should begin with /why/ the reader should care about group theory.
At least, it should begin with why the writer thinks that group theory is fascinating.
But it's difficult: How do we convince someone that something as abstract as group theory is interesting?

Don't make the readers think; make them /see/.
Your goal as a writer is to be a giant who enables the readers to stand on your shoulder as fast as possible,
so that they can see farther into the unexplored knowable world.
* On writing for oneself
One can write for himself, to clarify his thoughts, to augment his memory.
* Readings
From http://www.fortell.org/content/exploring-reading-writing-relationship-critical-thinking

#+BEGIN_QUOTE

#+END_QUOTE
* Bibliography
