#+TITLE: Topics in literacy and meta-research
#+DATE: 2019-11-28 00:00:00 +0700
* Literacy research articles
- [[file:literacy.html][On literacy]]
- [[file:dual-read-write.html][On the mathematical duality of reading and writing]]
- [[file:writing.html][On writing]]
- [[file:english-gender.html][A simple solution to the English singular gender-neutral pronoun problem]]
* <2019-08-14> Writing is a non-linear process
From https://macademic.org/2011/03/15/writing-philosophy/:
- "Combining these different pieces of information does not happen in an orderly linear process."
- "Writer’s block often comes from being too closely linked to the linearity of a process and
  the inability to break out small pieces of text to work on and move with ideas."
* On English participles and gerunds
Both a participle and a gerund are formed from a verb,
but a participle is an /adjective/, and a gerund is a /noun/.[fn::<2019-09-29> https://www.cliffsnotes.com/study-guides/english/verb/verbals-gerunds-infinitives-and-participles]

What is the difference between "I don't like the /guy/ wearing the green pants" and "I don't like the /guy's/ wearing green pants"?

"I don't like the /guy/ wearing the green pants" means you don't like /the guy himself/.
You have a personal problem with the guy.

"I don't like the /guy's/ wearing green pants" means you don't like /what he does/: wearing green pants.
You don't have a personal problem with the guy, but you think he shouldn't wear green pants.
However, there is a better way to express this:
Ask him "What's the story behind these green pants?" instead; you get a chance to better understand him.
* On the difference between change, alter, and modify
Ontologically:

A change changes the identity of the changed object.

An alteration or modification changes some properties of the altered/modified object but does not change its identity.

Examples:

Modification: change the color of your car.

Alteration: replace the engine of your car.

Change: buy a new car.

Dictionary?

Source?

To change = to swap, to replace

Example: change clothes, change name, change mood

To alter = to change the form or structure

<2019-10-26> https://www.lexico.com/en/definition/alter

Example: alter a building

To modify = to make a partial or minor change

<2019-10-26> https://www.lexico.com/en/definition/modify
* <2019-10-27> Abortion is a linguistic issue, not a moral issue
Abortion is not a moral issue.
It is a /linguistic/ issue.

The root problem of the abortion issue is the non-existence of the definition of "human".

The question "Should we allow abortion?" actually reads "What is a human?"

It is crazy that people can talk and shout for hours without agreeing on the meaning of the words that they use.
It is exactly like watching someone who understands only Chinese argue with someone who understands only English:
No communication happens, only noise and gestures of frustration.

My suggestion is:
Before everyone agrees on the same definition of "human", avoid wasting time in abortion "debates".
No communication happens when people interpret words differently.

What is a human?
Nobody can satisfactorily define what a "human" is; they only "know it when they see it".
For every "definition" of human you come up with, I can point out a problem with it.
I have tried to define "human" a few times, and failed.

The same goes for "baby" and "fetus".

Where do you draw the line?

This problem has a name: sorites paradox[fn::<2019-10-27> https://en.wikipedia.org/wiki/Sorites_paradox] (that is, paradox of the heap).

Anyone who doesn't know the sorites paradox has no business talking about abortion.

Anyone who thinks that every statement is either false or true has no business talking about abortion.
In reality, every statement can be anywhere between 0 percent true and 100 percent true.

Outlawing abortion now causes increased crime rate 20 years later.

Outlawing abortion is condemning rape victims into living hell.

Outlawing abortion saves some present lives but harms even more future lives.

People reject abortion not because abortion is bad, but because /they believe/ abortion is bad,
and thus rejecting abortion makes them feel noble.
They cannot distinguish between "X is true" and "I believe X is true".
Their reasoning is deficient.

People have been having abortions since time immemorial.
Why does it become a problem only recently?

Just because you don't like it doesn't mean it should be illegal.

But the state should also not always be utilitarian.

I think it is dishonest to call our species /Homo sapiens/, the wise ones.
I think it's more honest to call our species /Homo homicidalis/, that is, the ones who like to kill their own kind.
I think we can admit that we have some people we'd like to kill;
we just don't do it because we're afraid of the cops.

See also: [[file:language.html][Language Research Group]].
* Meta-research
See [[file:meta.html]].
* <2019-07-07> Do not ask Google (or anyone else) questions that only you can answer
Like "If I am my own target audience, what should I write, for myself?"
* On personal knowledge bases
What is the most commonly used free-and-open-source one?
There are too many solutions?

If the graphical user interface cannot be standardized, at least the data format should be standardized.

I'm using Org Mode and Pandoc.

Wordpress?

TiddlyWiki?

I want free-and-open-source software because I want my data to be usable forever.

Evernote is not FOSS.

https://www.ubuntupit.com/13-best-evernote-alternative-note-taking-apps-linux/

https://opensource.com/article/17/12/joplin-open-source-evernote-alternative

One can convert a dynamic website to a static website with a /website downloader/.
You can point a website downloader to localhost.

Should we build it on Pollen[fn::https://docs.racket-lang.org/pollen/]?
It was made for making web-based books.
* On hypertext
Am I writing a non-linear online book?

I think long linear text is not the best form of communication.
Perhaps I should make a mind map, perhaps with graphviz?
Or an entity-relationship diagram?
Here I try hypertext (a graph of short linear-text documents).

* Flat Earth is a social issue, not a scientific issue
Flat-Earthers are merely looking for friends in this extremely power-unbalanced world.
They have trust issues with authorities.
I am also looking for friends who share my beliefs, and I also have trust issues with authorities,
but the difference between a Flat-Earther and me is that
I have trust issues with political authorities,
whereas a Flat-Earther has a trust issue with scientific authorities.
Thus, although I do not believe in Flat Earth,
a Flat-Earther and I have more commonalities than differences.
The same is true with Holocaust deniers and climate change deniers:
it is a trust issue with some authorities.

How did such trust issues arise?
Our parents, for good reason, taught us not to trust strangers.
Thus it is a logical consequence that we don't trust authorities: they are strangers!
We don't know who they are, and yet they suddenly come down telling us what is right and what is wrong.

How can two strangers be friends?
By physical closeness (being at nearby location and time) and by mental closeness (having similar ideas and beliefs).
How do we make sure that the people in power are not strangers?
It is not feasible for one person to meet millions of people.
Thus I have this corollary: /having power over more people always begets more trust issues/, simply because it is harder for the authority to not be strangers with its subjects.
Perhaps it's just that power today is too centralized.
But mass media enables centralization of power;
the authority uses mass media to make its subjects feel that the authority is familiar.
But mass communication is one-way communication.
How does one-way communication build trust?
In the same way an actor builds his fanbase of fans who trust him.
First, the would-be fans have to fall in love with him from afar, be it due to his handsomeness, his charisma, or any aspect of him that resonates with them.
But then this fanbase has to be maintained, and it is physically impossible for an actor with a million fans to be close to all of them.
Therefore what is required to maintain the fanbase is a /mass illusion/ of closeness:
the actor has to behave in such a way that makes his fans /perceive/ that he cares about /all/ of them,
whereas he can only /actually/ care about /few/ of them.
The mass media only has to show the actor's interacting with /a few/ of his fans, in order to make /all/ of his fans feel that they have been interacted with.
This is not because he is evil; he is just constrained by the laws of physics.
This technique is a double-edged sword:
it can be used to maintain political stability,
but it can also be used to lie to millions of people.
We need to teach people epistemology so that they can tell apart what they know and what they think they know.
Mass media does not give any knowledge; it only gives an illusion of knowledge.
Reading the news does not make us know anything; it only makes us think that we know.
How do I know there is a disaster somewhere?
I do not, because I can only know things near me, and it is not feasible for me to verify every claim in the news; I am merely assuming that the news is honest.
Epistemology is more important than ever in this age of falsehood.

There are some simple experiments that we can carry out to determine the curvature of the Earth.
Reality itself has told us through those experiments that the Earth is not flat; it is up to us to listen to reality or ignore it at our own peril.
We will make costly mistakes if we make antennas and satellites with Flat Earth theory.

The theory makes sense and is a fine scientific theory: it is falsifiable.
What does not make sense to me is the refusal to change one's beliefs despite being otherwise told by reality.

My thought is exactly that of George Box and of Isaac Asimov.

George Box: "All models are wrong but some are useful."[fn::https://en.wikipedia.org/wiki/All_models_are_wrong]

Isaac Asimov: "When people thought the Earth was flat, they were wrong. When people thought the Earth was spherical, they were wrong.
But if you think that thinking the Earth is spherical is just as wrong as thinking the Earth is flat,
then your view is wronger than both of them put together."[fn::https://en.wikipedia.org/wiki/Wronger_than_wrong]

Thus, both the Flat Earth theory and the Spherical Earth theory are "wrong", because they are only our descriptions of reality, and not reality itself.
It's just that the Spherical Earth theory is useful in more cases, and Spherical Earth theory is useful in fewer cases.
In software terms, we can think of Flat Earth theory as an "alpha" version of Spherical Earth theory, where the "bugs" are the mismatches with reality.
Updating the "software" fixes some "bugs", but the "software" becomes more complex.

The Flat Earth theory does make testable predictions.
But Round Earth /subsumes/ Flat Earth, in the sense that:
- If Flat Earth predicts something correctly, then Round Earth predicts it correctly.
- There are some things correctly predicted by Round Earth that are not correctly predicted by Flat Earth.

Both Flat Earth and Round Earth are models and are wrong; it's just that Round Earth subsumes Flat Earth, so we use Round Earth.
* Organizing knowledge
** what
- Knowledge should be ordered descending by importance, from the most important?
- Knowledge should be ordered ascending by verifiability, from the easiest to verify?
- Knowledge should be grouped by usefulness?

  - If both Y and Z are useful to X, then Y and Z should be put together.

- Why does someone need to know something?

  - What is all the related things that he also needs to know?

- others

  - [[https://www.e-education.psu.edu/geog882/l3_p3.html][Kant's Three Ways of Ordering Knowledge]]

- In what sequence should we present knowledge for fastest learning?
- Example of primitive life (but not survivalism?)

  - [[https://www.youtube.com/user/laws507/videos][YT:Primitive Life]]

- information organization

  - An information is a sentence, a paragraph, a picture, or anything that helps us accomplish something.

    - Here "information" is a countable noun.

  - Informations should be grouped by the task it helps us accomplish.

    - Every task T requires a set of informations, which should be put together in one place.
    - If doing task T requires informations J and K, then J and K should be grouped together.
    - Duplication problem.

      - Suppose: both task T and task U requires information J.
      - Where should J be put?

  - The value of information J should be measured by the ratio V/E, where V is the value of the task that J helps us accomplish, and E is our effort for obtaining J.
  - Example of combinatorial explosion of categories.

    - Which should a red car be grouped together with: a red hat or a blue car?

      - Which should a big old man be grouped together with: a big old woman, a big young man, or a small old man?

- The information organization of this wiki

  - At first I tried grouping by topic.
  - Then I asked myself, "Why am I collecting this information?"
  - Then I tried grouping by project (goals).
  - I switched from lookup-oriented knowledge organization (organize knowledge for refindability (fast lookup))
    to task-oriented (goal-oriented) knowledge organization (organize knowledge by the tasks that require the knowledge).

- Can machine organize information for us?
  Can machine cluster documents by the task they help accomplish?

  - Internet search "automatic clustering of wiki articles"

    - 2017, article, "Spectral Clustering Wikipedia Keyword-Based Search Results", [[https://www.frontiersin.org/articles/10.3389/frobt.2016.00078/full][html]]
    - 2016, article, "WikiWrite: Generating Wikipedia Articles Automatically", [[https://www.ijcai.org/Proceedings/16/Papers/389.pdf][pdf]]
    - 2014, article, "Text mining in R -- Automatic categorization of Wikipedia articles", [[http://www.rexamine.com/2014/06/text-mining-in-r-automatic-categorization-of-wikipedia-articles/][html]]
    - 2011, article, "Categorization of Wikipedia articles with spectral clustering", [[https://link.springer.com/content/pdf/10.1007/978-3-642-23878-9_14.pdf][pdf]]
    - 2007, article, "Clustering Short Texts using Wikipedia", [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.188.1139&rep=rep1&type=pdf][pdf]]
    - https://www.quora.com/How-should-I-cluster-Wikipedia-articles
    - slightly different topics

      - https://en.wikipedia.org/wiki/Document_clustering
      - 2010, article, "Exploiting Wikipedia Knowledge for Conceptual Hierarchical Clustering of Documents", [[https://www.researchgate.net/publication/221579515_Exploiting_Wikipedia_Knowledge_for_Conceptual_Hierarchical_Clustering_of_Documents][html]]
      - 2008, article, "Clustering Documents with Active Learning Using Wikipedia", [[https://ieeexplore.ieee.org/document/4781188/][abstract]]

  - Machine reading comprehension

    - [[http://www.msmarco.org/][MS MARCO: Microsoft MAchine Reading COmprehension Dataset]]
    - https://www.quora.com/What-is-the-difference-between-machine-comprehension-and-question-answering-in-NLP
    - 2017, slides, "Machine reading comprehension", [[http://tcci.ccf.org.cn/summit/2017/dlinfo/003.pdf][pdf]]
    - https://www.microsoft.com/en-us/research/blog/transfer-learning-machine-reading-comprehension/
    - https://futurism.com/machines-beat-humans-stanford-reading-comprehension-test/
    - 2018, article, "Adversarial reading networks for machine comprehension", [[https://openreview.net/forum?id=Hy3MvSlRW][review]], "Interesting idea, unconvincing results"

- 2002, slides, [[http://mockus.us/papers/exbpresentation.pdf]["Expertise browser: a quantitative approach to identifying expertise"]]

  - http://mockus.org/ExV/index.html

- Undigested

  - [[https://pm.stackexchange.com/questions/2780/how-to-organize-knowledge-within-a-wiki][PMSE 2780: How to organize knowledge within a wiki?]]
  - https://www.quora.com/What-is-the-best-way-to-organize-a-company-wiki

- Knowledge is only as good as what it enables you.

  - 2013, article, [[https://www.k4health.org/blog/post/knowledge-no-longer-power-how-you-use-knowledge-power][Knowledge is no longer power; How you use knowledge is power!]]

- knowledge organization?

  - 2016, article, [[https://medium.com/airbnb-engineering/scaling-knowledge-at-airbnb-875d73eff091][Scaling Knowledge at Airbnb -- Airbnb Engineering & Data Science -- Medium]]
  - 2018, article, [[https://blog.socialcops.com/technology/engineering/airbnb-knowledge-repository-scale-knowledge/][Using Airbnb's Knowledge Repository to Scale Your Organization's Knowledge - SocialCops]]

** The personal knowledge base?
See [[http://www.acuriousmix.com/2014/09/03/designing-a-personal-knowledgebase/][Designing a Personal Knowledgebase -- A Curious Mix]].

See also its HackerNews commend thread [[https://news.ycombinator.com/item?id=8270759][Designing a Personal Knowledgebase | Hacker News]].
** Information architecture
- What does an information architect do?

  - An information architect /plans the disclosure of information/
    so that users can get the information they need with minimum confusion.

- What concern such architect when he/she builds a store?

  - How visitors find things.

- How do visitors find things in such store?

  - Don't make them think.
    Group similar things together.
    Put text banners indicating categories.
    Let them ask anyone with uniform.

- We will confuse users if we dump all information in one page.
- LATCH: Location, Alphabet, Time, Category, or Hierarchy

  - https://uxplanet.org/design-principle-organizing-information-343a7ef936a8
** KWIC (Key Word In Context) indexing?
- There is an example. https://en.wikipedia.org/wiki/Key_Word_in_Context
