#+TITLE: Live forever
#+DATE: 2019-04-22 00:00:00 +0700
#+PERMALINK: /live.html
#+OPTIONS: ^:nil
* Understand the causal chain of death
** Why does a human die?
- Because his brain dies.
  - Because the blood that flows into the brain
    does not satisfy the brain's operating conditions.
    - Because other organs fail.
      - Because of Hayflick limit[fn::https://en.wikipedia.org/wiki/Hayflick_limit]?
        Telomere shortening?
        - Why does the Hayflick limit exist?[fn::1994 https://www.ncbi.nlm.nih.gov/pubmed/7845054]
        - Do stem cells also have Hayflick limit?
      - Because of irreversible cell damage?
      - Homeostatic failure?
- Reading list?
  - https://en.wikipedia.org/wiki/Longevity_escape_velocity
  - https://en.wikipedia.org/wiki/Anti-aging_movement
  - https://en.wikipedia.org/wiki/Gerontology
  - https://en.wikipedia.org/wiki/Indefinite_lifespan
  - https://en.wikipedia.org/wiki/Life_extension
  - https://en.wikipedia.org/wiki/Immortality
** Why and how are immortal organisms immortal?
- https://en.wikipedia.org/wiki/Biological_immortality
** Is it enough to sustain the brain in order to live forever?
* Find promising ways to live forever
What is the most feasible way to live forever?
- Mind upload?
- Cryopreservation?
- Cyborg?
- Biological advances?
- Reverse aging?
- Cure death?

Biohacking?[fn::https://www.theguardian.com/science/2018/sep/21/extreme-biohacking-tech-guru-who-spent-250000-trying-to-live-for-ever-serge-faguet]

Genetics is the biggest factor in how far we can build our body.[fn::https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting]

AI-vs-biology immortality dilemma:

If we want to achieve immortality, which should we prioritize: AI or biology?
- If we understand enough AI, we can make an AI to research immortality faster.
- If we understand enough biology, we can live long enough to research immortality.

Why not both AI and biology?
* Avoid untimely death
Don't swallow slugs.[fn::https://www.dailymail.co.uk/news/article-6352629/amp/Sam-Ballard-dies-eight-years-swallowing-slug.html]

Don't swim in a warm lake.[fn::https://en.wikipedia.org/wiki/Naegleria_fowleri]

Read ingredient labels.
Try to understand what is in the food.
If you don't understand it, you probably shouldn't eat it.

Avoid food that has been processed too much.

Don't eat spoiled food.
Don't eat food that smells off.
* Avoid risky places to live
Avoid places with natural disasters, social disasters, economic disasters, incompetent governments, backward people.

Move if necessary.
* What?
** Thyroid?
"The two major causes of thyroid disorders are nutrient deficiency and autoimmune disease."[fn::https://kresserinstitute.com/underlying-causes-thyroid-disease/]
- Thyroid hormone synthesis requires these metals: iodine, zinc, selenium.
- Raw vegetables may contain goitrogens that prevent the body from using iodine.
- Very low-carb diets can decrease thyroid function.
** What causes gastritis?
- Does skipping a meal cause gastritis?
- Is Helicobacter pylori a normal part of the stomach flora?
- Does empty stomach secrete acid?
- How does the body dispose of excess stomach acid?
  Is it reabsorbed?
  Is it drained down the intestines as diarrhea?
- Why does keto diet cause loss of salts?

My hypothesis of the causal chain:
- gastritis
  - H. pylori /overgrowth/
    - /insufficient mucus/ in the lining of the gastric wall
      - malnutrition
    - insufficient acid
      - reduced acid due to no food passing through
      - hypochloremia due to keto diet
      - kalium is required to transport hydrogen ions in stomach acid production[fn::http://www.pathwaymedicine.org/stomach-acid-secretion]
    - overproduction of stomach acid
      the stomach's inflammatory response to H. pylori overgrowth
    - disturbed stomach acid pathways
      - insufficient materials to create hormones in those pathways

Why?
Because most H. pylori colonization is asymptomatic.
Is it true that half of the population have H. pylori but only some develop gastritis?

Bacteria don't kill the host just by being present.
It's the byproducts, toxins, interactions, infections, and sepses that kill the host.

Thus, my hypothesis is that gastritis happens when the stomach digests itself.

Svestka et al. 2003 \cite{svestka2003effect}:
- "It has been proven that damage to the gastric mucosa is the result of the combined effects of acidopeptic agents
  including infection with Helicobacter pylori and insufficient protective mechanisms of the mucosa.
  Thickness of gastric mucus is very important protective factor."
- "The thickness of gastric mucus is reduced after 24 hours' fasting in laboratory rats."

Unread but related:
- Role of mucus layers in gut infection and inflammation[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3716454/]
- The gastrointestinal mucus system in health and disease[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3758667/]
- Why do we still have Helicobacter Pylori in our Stomachs[fn::https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5295741/]

"Inhibiting Acid Production Could Make Gastritis Worse"[fn::https://www.sciencedaily.com/releases/2002/01/020115074441.htm]:
- '"These animal studies indicate that it is the inflammatory response - triggering the overproduction of hydrochloric acid -
  which is the stomach's primary response to bacterial colonization," says Juanita L. Merchant, M.D., Ph.D.'
- "Merchant cautions that [...] a type of bacteria called Helicobacter pylori, the most common cause of gastritis, was excluded from these studies."
* What is wrong with our education?
How come schools teach kids about sponge reproduction,
but they don't teach them /what to eat/ and /how to eat/?
* Bibliography
