#+TITLE: Defining marriage
#+DATE: 2018-09-20 01:55 +0700
#+PERMALINK: /marry.html
* Legal principle
** Everything consensual is legal.
- Being illegal does not always imply being prosecutable.
- If nobody reports, the police has no case.
* Marriage and public order
- Legal: Marriage exists to maintain public order.
- Biological: Public order exists to maintain survival of the species.
** Why does marriage exist?
- Marriage exists because the average person gets angry when someone (s)he copulated with copulated with someone else,
  and this anger may disturb public order.
  - Do we get angry when our spouses cheat?
    - Why?
    - Is that the same anger that we feel when we lose our belongings?
    - Is that the same anger that we feel when we are betrayed?
    - Is that the same anger that we feel when we are lied to?
** What is copulation?
- To copulate is to link/join/bind/tie/couple / to bring together / to conjoin (the genitals).
  To copulate is to cause the male genital to be inside the female genital.
  The male genital protrudes (goes outward).
  The female genital receives (goes inward).
  - https://en.wiktionary.org/wiki/copulate#Etymology
  - https://en.wiktionary.org/wiki/copulare#Latin
  - https://en.wiktionary.org/wiki/copula#Latin
- The definition seems to require that the sexes be different.
- Is it reasonable to generalize "copulation" into "any sexual act"?
- The average person would be angry if his/her spouse have any sexual acts (including flirting and sexual advances) with someone else.
  It is not only copulation.
  It is all sexual acts.
  It is all acts that may reduce the chance of copulation.
  The average man would be suspicious if his wife begins receiving lavish gifts from another man.
- Therefore it is reasonable to generalize marriages to concern the exclusive rights of everything that may lead into copulation, not only copulation.
- Marriage regulates sexual envy/jealousy?
- The debate of marriages boil down to the definition of copulation, and the relationship between copulation and procreation.

Originally copulation was for procreation/reproduction, but then nervous systems evolved, then pleasure centers evolved,
and thus copulation evolves to be pleasurable (because otherwise the organism will not reproduce).
** What is marriage?
A marriage is a contract between a person X, a person Y, and their society, stating that:
- person X and person Y may copulate with each other,
- person X must not copulate with anyone else other than person Y,
- person Y must not copulate with anyone else other than person X,
- the society will help enforce that restriction.
* Marriage regulates copulation, not procreation.
- Marriage regulates /copulation/ (having sex), not procreation (having offsprings).
- Before we invent marriage, the society assumes that copulation is allowed by default, and must be explicitly forbidden (by complaints, disputes, fights, wars, treaties, etc.).
- After we invent marriage, the society assumes that copulation is forbidden by default, and must be explicitly allowed (by marriage).
- We can see how this change of fundamental assumption improves public order.
** Copulation and procreation are two orthogonal concepts.
- Two concepts are orthogonal if we can have one without the other, in both ways.
- We can have copulation without procreation: inserting the penis into the vagina without ejaculating sperm, even between two married people.
- We can have procreation without copulation: cloning, in-vitro fertilization, synthetic organisms.
- Copulation is sexual intercourse?
- Procreation is the production of offspring.
- Marriage is about exclusive copulation, not about procreation.
** Thought experiments suggest that marriage regulates copulation, not procreation.
*** Do you mind if your spouse copulate with but doesn't procreate with someone else?
- That is, do you mind if your spouse had sex with someone else as long as nobody gets pregnant?
- If you do mind that, then marriage is about regulating copulation, not procreation.
*** Do you mind if you can procreate with but not copulate with your spouse?
Consider an average couple.

Suppose that the husband's penis and the wife's vagina must never touch,
but a third person will, at no cost to the couple, inject the husband's sperm into the wife so that the couple can have a child.

Would the average husband mind?
Would the average wife mind?
If they would mind that, then marriage is about regulating copulation, not procreation.

- https://en.wikipedia.org/wiki/Sexless_marriage
* Generalizing marriage
** Generalizing marriage with graph theory
Marriage can be generalized to any arrangement of exclusive mating rights.
*** Group marriage
- It is straightforward to define a /group marriage/ involving a group G of people P1, ..., Pn as follows:
  - If person X is in G and person Y is in G, then person X and person Y may copulate.
  - Everyone in G must not copulate with anyone outside G.
*** Strictly-heterosexual group marriage
- Each person X in group G may copulate with each person Y if they have different sexes.
- Everything else is forbidden.
*** General marriage
- A marriage is an undirected graph.
- An edge (x,y) means that x may copulate with y.
- The copulate-with relation is symmetric: an edge (x,y) implies the edge (y,x).
- The absence of an edge (x,y) means that x must not copulate with y.
- You can see where this is going: complete-graph marriages, point-to-point marriages, bus marriages, star marriages, ring marriages, mesh marriages, daisy-chain marriages, etc.
  - https://en.wikipedia.org/wiki/Network_topology#Classification
- Relationship between marriage, graph theory, and model theory
  - What is the shortest first-order logic formula that describes a graph that describes a marriage?
- /The law should enable arbitrary graphs in a marriage contract to the furthest practically enforceable extent/.
** Contract law subsumes marriage law.
- Remember that a marriage is a contract.
  Therefore contract law terms apply.
- Cheating is a /breach/ of a marriage.
- Divorce is the /termination/ of a marriage.
- Marriage law is redudant.
  Marriage is just a special case of contract law that happens to be about mating rights.
* Problem
We are still figuring out whether same-sex marriage is philosophically sound.
* Acknowledgements
I would like to thank Alan Keyes for indirectly (and perhaps unintentionally) motivating me to write this.
This is the only time he gets me thinking; I can't find anything else of him to agree with.

I agree with his [[https://www.youtube.com/watch?v=BMYBl2uzXEw][spirit]] of being careful with definitions, but I disagree with his concluding that marriage came into existence in order to regulate procreation.
Marriage regulates /copulation/, not procreation.
* Unrelated?
** Evolutionary benefits of monogamy
- Perhaps most of us we have evolved to prefer monogamy.
*** Monogamy reduces the risk of contracting sexually-transmitted diseases.
- Those diseases may co-evolve with us.
- [[https://www.biorxiv.org/content/early/2017/10/15/203695][Sexual conflict and STDs: coevolution of sexually antagonistic host traits with a sexually transmitted disease | bioRxiv]]
- https://en.wikipedia.org/wiki/Monogamy#Evolutionary_and_historical_development_in_humans
- https://edition.cnn.com/2016/05/17/health/sti-infanticide-human-monogamy/index.html
*** Monogamy improves infant survival.
