#+TITLE: Toward a curriculum for meditation
#+DATE: 2019-09-28 00:00:00 +0700
#+PERMALINK: /meditate.html
* Other curriculums
- I feel that all ancient techings are not prescriptive/explicit/procedural enough: Patanjali, Padmasambhava, Buddha, etc.
* What is meditation?
Nash et al. 2013 \cite{nash2013toward}[fn::<2019-10-30> https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00806/full]
proposed a definition and a taxonomy of meditation.

TODO summarize
\cite{cardoso2004meditation}[fn::<2019-10-30> http://www.academia.edu/download/43943209/Meditation_in_health_An_operational_defi20160321-14420-1crpgc2.pdf]
\cite{awasthi2013issues}[fn::<2019-10-30> https://www.frontiersin.org/articles/10.3389/fpsyg.2012.00613/full]

To meditate on something is to focus on that thing, and that thing only, exclusively, and nothing else?

"However, the actual aim of Meditation is not having a blank mind as popularly believed."
 [fn::<2019-09-28> Sandra Winkler https://www.quora.com/What-will-happen-as-you-focus-on-your-breath-meditation]

The essence of meditation is the singular exclusive focus on the object of meditation.
The stillness and relaxation are there to help us focus, but are not the goal of meditation.

Everybody has their own idea about meditation.
 [fn::https://en.wikipedia.org/wiki/Meditation]
 [fn::https://hackspirit.com/dalai-lama-reveals-practice-meditation-properly/]
 [fn::https://www.osho.com/meditate/meditation-tool-kit/questions-about-meditation/what-is-not-meditation]
 [fn::http://www.meditationiseasy.com/meditation-intro/what-is-not-meditation/]
 [fn::https://yogainternational.com/article/view/the-real-meaning-of-meditation]

Daydreaming is the /opposite/ of meditation.
Daydreaming is mindless; meditation is mindful.
Daydreaming is unfocused; meditation is focused.
 [fn::<2019-09-28> https://moodsmith.com/meditation-and-daydreaming/]
 [fn::<2019-09-28> https://aboutmeditation.com/whats-the-difference-between-daydreaming-and-meditating/]
 [fn::<2019-09-28> https://www.reddit.com/r/Meditation/comments/2553k9/is_daydreaming_a_form_of_meditation/]

Meditation is about focusing, not relaxation.
The relaxation is only to help the focusing.
But focus on what?
Nothing, something, or everything?
* How to meditate?
Is this legit?
Andrew Benington's 42-day instructions[fn::<2019-10-29> https://meditationthehardway.wordpress.com/]
* How do I meditate?
This is how I think one should meditate.
** Beware of the risks of meditation
/Trigger warning: Do not read if you have suicidal tendencies;/
instead, find a suicide hotline near you on the Internet,
and seek help from that suicide hotline.

/Warning: Meditation may harm you,/
especially if you teach yourself,
or get it from an unqualified beginner like me;
I'm not a meditation teacher; I'm just sharing my experiments;
it may not work for you; it may even work /against/ you.
/Proceed at your own risk./

/Beginners should avoid meditating too much/.
Beginners should avoid meditating more than 20 minutes per day?
Use common sense.
I am curious about the possibility of obtaining psychic powers by meditating,
but I approach it with some skepticism.

Meditation may harm you and others, although it happens somewhat rarely.
 [fn::https://www.vice.com/en_us/article/vbaedd/meditation-is-a-powerful-mental-tool-and-for-some-it-goes-terribly-wrong]
 [fn::https://patcarrington.com/about-meditation/meditation-articles/the-misuse-of-meditation/]
 [fn::http://shinzenyoung.blogspot.com/2011_11_01_archive.html]
You may lose enjoyment in things you used to enjoy.
You may no longer love the people you love.
You may change, and this may lead to a divorce if you are married.
You may become uncaring about anything including your friends, kids, and parents.
You may become unable to feel emotions.
The change is not always better, and may be irreversible.
You may be unable to return to your old self.

It may help if you are already an optimistic nihilist before you begin meditating.

I had already been a nihilist before I began meditating in my thirties.

In my teens, when I was in senior high school, I found nihilism on the Internet.

In my mid-twenties, I occasionally thought about suicide, perhaps every a few months, although I never dared to do it.
The thoughts were not too strong and not too frequent, but it was there.

In my late twenties, I bounced back a bit and emerged as a mostly apathetic person able to enjoy a few things.

Suicide is always an option.
I never say "There is nothing I can do" because I /can/ always kill myself,
although I /will not/ always do that,
but /it feels good to always have an option/.
It gives me a feeling of /power/ over the world:
If I don't like the world, I always have the option of killing myself,
besides all the other options I may have.

I rarely feel happy; I am merely content most of the time.

I rarely feel sad; I usually feel angry instead.

I fear death.
No. I fear dying.
No. I fear the /pain/ of dying.
No. I fear the /suffering/ from the pain of dying.
Thus, it is inspiring to see the burning monk
Thích Quảng Đức[fn::<2019-09-29> https://en.wikipedia.org/wiki/Th%C3%ADch_Qu%E1%BA%A3ng_%C4%90%E1%BB%A9c]
/separate/ pain and suffering.
Surely there are less painful ways to die than burning.
If he can have that much pain without suffering, then perhaps we can too;
it should even be easier for us, because we should have less pain.
** Choose one object to meditate on
Choose one object, such as your deity, a problem of yours, a favorite thing of yours, a mantra, etc.
It does not have to be a visual object; it can be a sound, a smell, a taste, etc.
Whatever suits you.
** Minimize distraction
Go to somewhere quiet, cool, comfortable, in a relatively static environment that does not change very much:
An environment with stable noise, no blinking lights, no jarring sounds, no haphazard winds, no unpredictable heat, no mosquitos.

Get into a comfortable position that can be sustained with minimum effort.
Sitting, lying down, hanging, whatever works for you.
Close your eyes.
Stay still.
Do not move your body.
If you are lying down, you can pretend that you have sleep paralysis.
Whatever suits you.
** Focus on the object exclusively
Focus on the object exclusively, only on the object, and nothing else.
Let breathing happen comfortably, regularly, and unconsciously, like when you are sleeping,
but do not try to make the breathing unconscious; just let it be.
If you become aware of your breathing, acknowledge it, and move on.
Do not try to suppress your awareness of anything else such as your breathing or the environment.
Instead, acknowledge those thoughts, let them be, do not respond to them;
be indifferent to them, and focus on the object without trying to regain your attention from those thoughts.
It's like you are ironing your clothes and your kid ask you to play;
you say you'll play with him after you finish ironing, you continue ironing, and your kid goes away,
but make sure you fulfill that promise, or your kid will distrust you.
If you let your thoughts be and not respond to them, they will pass on their own like a gentle breeze blowing past you.

Do not shoo your thoughts; let them get bored and leave on their own.
These thoughts are like your childhood friends calling you from outside the fence to play:
If you pretend you're not home, they'll go away on their own.
(Is this a bad analogy?)

After a few minutes of exclusive focus, you will be unaware of your surroundings and other sensory inputs;
you will be aware of only the object and nothing else.
We call this feeling the state of /oneness/, but in beginners, this happens for a very short duration, only a few seconds,
and then you /will/ be distracted,
your mind will pull you back to your body,
and you will become aware again of your surroundings, and lose the exclusive focus on the object,
but you will remember that for a short time you were fixated on the object and unaware of everything else.
You are aware that your state of mind has changed.
(Perhaps this is what is meant by being aware of awareness itself?
If you can be aware of the shift of your awareness, then you can be aware of your awareness itself?)

After a few distractions, it becomes increasingly difficult to reenter the state of oneness.
You can take a few minutes of break, do something else, and come back to meditation later.

Therefore, meditation has two aims.

First, to /prolong/ the state of oneness above, from a few seconds to forever (as long as desired).

Second, to /shorten/ the transition from normal waking state to the state of oneness, from a few minutes to none (at will, as short as desired, like blinking an eye).

Thus, the aim of meditation is to enable you to get into and out of the state of oneness /whenever/ you want it.
At first it's very hard to get in and it's too easy to get out,
but, with practice, you should be able to get in, stay, and get out, at any time you want.
** Other objects?
What if the object is /nothing/?

What if the object is /everything/?

What if the object is a part of your own body?

What if the object is a part of your own mind?

What if the object is yourself?
* Tart 1971 meditation experience report
Tart 1971 reported that meditation turned alcohol from enjoyable to repulsive.
After getting a habit of meditating, he found that alcohol made it hard for him to focus;
then his head ached; then he gave up the wine he used to like. \cite{tart1971psychologist}[fn::<2019-10-29> http://www.atpweb.org/jtparchive/trps-03-71-01-135.pdf]
* What is known to be real about meditation
After meditating a few minutes, I can feel temporarily increased alertness.
But how do I know that it is not a placebo?
* On the position for meditation
Avoid lie-down meditation.

I tried to meditate lying down.
The result is sexual thoughts and falling asleep.

Many people \cite{tart1971psychologist} advise against lie-down meditation because that tends to make people fall asleep.

Do not meditate lying down, because you will fall asleep?\cite{tart1971psychologist}[fn::<2019-10-29> https://www.expandinglight.org/free/yoga-teacher/advice/lying-down-meditation.php]
But what is yoga nidra?
Is it not meditation?

I sit too much.
Can I meditate standing up?

Why do people meditate sitting?
* On meditation and vibration
What does it mean that "meditation raises vibrational frequency"?
https://www.mindful-messages.com/2018/08/18/psychic-101-seeking-stillness/

Perhaps they call it "vibration" because they feel their bodies vibrate when they are about to get out of their bodies?

What is vibration?

What is vibrating?

What the hell do they mean by "raising your vibration"?
What the hell is that sloppy use of language?
* Untested wild guesses; don't read
It seems that the thing common to the obtainment of superpowers in all cultures is /meditation/, be it Indian or Chinese.

I think meditation done right should eventually induce synesthesia after a few years?

Hypothesis:
If we don't think of anything, the mind will naturally daydream, as a spring is at its resting position when there are no external forces.

When we are daydreaming, we do not remember reality.

We glance at a wooden table, and we see a legged brown thing.
Then, we stare at the wooden table, and we see the grain.
This shows that we can /perceive the same thing in several different ways/.
The light that arrives at our eyes has not changed.
It is our attention that changes.
We can fail to perceive what we sense.
We do not perceive everything that arrives at our senses.

When you are doing something boring but necessary, often your mind wanders somewhere else.
What is this state of mind?
Daydreaming?

Feeling boredom or hatred means you think something is wrong; this implies that you care.
Apathy means you don't feel anything.
Perhaps we don't get apathetic as we age; it's just that our priorities change.

I used to be able to feel bored.
However, as I get older, I find it harder to feel bored.
Apparently my boredom has been replaced by apathy.
** We are still aware in our sleep, only less aware
If a bang can wake me up, then I am aware in my sleep?

Thus one practicing pratyahara is in a state between awake and asleep, but more toward the awake state:
He is awake-like because he is conscious, but he is asleep-like because he disconnects the brain and the mind,
he disconnects his sensors and actuators from the brain,
he does not respond to weak stimuli, in the same way a sleeping person does not respond to weak stimuli.

The brain wakes us up if there is a sudden change of inputs, be it from silent to noisy, or from noisy to silent.
 [fn::https://www.reddit.com/r/NoStupidQuestions/comments/b77yh5/a_loud_noise_will_wake_someone_up_but_will_the/]
** On meditation, subconscious, reality
<2019-09-22>
I have not yet found reality.

When I first tried to relax, I realized that /I didn't know how to relax!/

Why is relaxing so hard?
Why does it take years to learn how to relax?

I am so confused.
Is meditation about relaxing or focusing, or both, or neither?

I think the most important thing in remote viewing is the ability to enter and exit an extremely relaxed-but-focused state at will.

Hypothesis:
Sleep is for the mind, not for the brain/body.
*** The dangers of getting new senses
Imagine a congenitally blind person seeing for the first time.
Perhaps that is also the feeling of getting enlightened or getting a psychic ability for the first time.
If they feel like getting a new sense,
we can treat Joyce Schenkein's 2015 post[fn::<2019-09-21> https://www.quora.com/What-does-it-feel-like-to-see-for-the-first-time] as a cautionary tale:
#+BEGIN_QUOTE
Von Senden studied patients who were born blind (due to congenital cataracts) and who, later in life (like age 40) underwent surgery to have them removed.
He found that they never learned to see normally.
Several were depressed to have this constant, unstoppable input of "static" and at least one person committed suicide.
#+END_QUOTE

Perhaps not all recovering blind people end up like that?
*** The illusion
The Indian concept of "maya"[fn::<2019-09-22> https://en.wikipedia.org/wiki/Maya_(religion)] (illusion) is easy to wit, hard to ken.

It is trivial to realize that our senses are imperfect.
It is hard to know what is real then.
Can we know anything without any senses?

When we think we perceive an object, we actually perceive its reflection.
We do not see a tree.
We see the light reflected by the tree, and not even all of the reflected light, but only a small part of all light reflected by the tree, only the part that reaches our eyes.
Can we directly experience a tree?
What does it feel like to be a tree?

When I think I see a chair, I dont see a chair, but I see a chair as presented to me by my mind.

All perception is illusory.
The perception of the passing of time.
But, then, what is real?

If I live without any emotions at all, then am I not a psychopath?
There is a  difference between being aware of your emotions and not having any emotions at all.

These things enrage me:
interrupted internet connections,
the government's passing laws I disagree with,
food couriers sending something that doesn't match my order,
people getting dogs without knowing how to train them.
By "it enrages me", I mean it drives me to a murderous mood;
I would kill the stupid offending person,
if I didn't fear being caught by cops.
But I don't dwell in such feeling.
I acknowledge my anger, and after a few minutes it subsides,
and my recollecting of the event does not provoke an emotion as great as the first occurrence.
I used to be enraged by traffic jams but now I see them as a chance to meditate.
I am most enraged by things that violate my expectations.

Swann theorizes that the body is the way of communication between the conscious and the subconscious.

Even if I didn't have any language I would still feel emotions and have thoughts.
It would just be that I would not be able to describe my experience.

Naked awareness is easy to wit but hard to ken.
It's easy to say what it is.
But it's hard to actually /experience/ it and ken it first-hand.

It is easy to understand that our perceptions are illusory.
It is hard to turn off those illusions,
especially if those illusions feel so real.
It seems that those illusions are not completely arbitrary;
they seem to have some correspondence with reality.
It is hard to perceive the reality, but it is because the reality cannot be perceived,
but must be directly experienced, because every perception is a representation of reality.
If we quiet /all/ senses, we are left with reality?
But "all senses" is a lot.
If we close our eyes, we can still hear.
If we close our eyes and ears, we can still feel the wind blowing.
Imagine a baby born without /any/ sensors at all?

It is wrong to think that congenitally blind people see blackness everywhere.
They /just don't/ see.
They just don't experience sight.
There is a difference between seeing blackness and not seeing anything at all.
They don't even experience the blackness that non-blind people see with closed eyes.
Meditation is that.
We don't aim to see blackness.
We aim to not experience anything.
It is hard for a sighted person to pretend that he has no sight.

https://en.wikipedia.org/wiki/Recovery_from_blindness

https://www.reddit.com/r/explainlikeimfive/comments/2b0xpx/eli5_do_blind_people_just_see_the_color_black_or/

Open one eye, and try to see with the closed eye.

Even if we destroy our senses, for example by blinding our eyes, we can still perceive and we still have memory and Imagination between us and reality.

Switching from naked awareness to maya is like a congenitally blind person seeing for the first time.
Perhaps that is why naked awareness enables us to see everything afresh.

Is it possible to know something without perceiving it? Must I perceive myself before I know that I exist?

Can i be aware without memory?
If i momentarily have naked awareness, how do i know i have it, and how do i know i had it, if i had to be simply aware without sensing and remembering?
How can i know something without remembering it?
I can.
I can thoughtlessly stare at a chair, and know that there is something there.
Imagine someone without senses, memory, and imagination.

How can we remote-view if we do not perceive?
In other for us to cognize something, we must perceive it?

A mind-silencing/mind-idling/mind-parking experiment?

I tried to silence my mind, or, perhaps more accurately, /idle/ my mind, or, /park/ my mind, by not thinking anything,
or, by focusing on the null thought (nothingness).
It seemed to dislike silence; it fought back by generating random thoughts.

Even as I receive random images, my conscious mind interferes.

I tried to pretend that I did not have any senses.

From[fn::https://www.reddit.com/r/Paranormal/comments/9g3ero/hi_reddit_im_loyd_auerbach_parapsychologist_ask/e61agrg/],
emphasis mine:
#+BEGIN_QUOTE
I've learned from [...]
that the majority of humans seem to walk about oblivious to anything/everything of a psychic nature because
our cultural and other programming has built up our own /psychic shields/, shored up quite by belief (and disbelief).
True disbelievers are rarely, if ever, bothered by or even experience anything psychic. Their shields are strong.

[...]

I know I won't be harmed because a) /ghosts can't physically harm people/ and
b) my "psychic shield" is strong [...] and
c) I have knowledge of the first two which mitigates any negative emotional impact I might feel.
#+END_QUOTE

I tried to silence my mind, with the hope of receiving something, but I received nothing,
as if I were a radio receiver with no nearby radio stations broadcasting any radio waves.

Perhaps at first I should pretend to be dissociative.
Perhaps when I'm eating I should say "/My body/ is putting the food into my body's mouth" and "The thought of saltiness appears in /my mind/"
instead of saying "I'm eating a salty food".
Perhaps I should never use the word "I".
When I see a flower, the light reflected by the flower reaches my body, and the thought of a flower appears in my mind.
When I'm thinking, I should say that a thought appears in /my mind/.
I am not seeing, doing, feeling, or thinking anything; I simply exist.
Perhaps that is how I should think in order to meditate before remote viewing?
*** The subconscious
What is it?
Does it exist?
How does it work?
How do we know it exists?

Buchanan 2009 \cite{buchanan2009seventh} suggests
that the problem is in the communication between the conscious and the subconscious,
not in the variation of psychic talent.
The problem is associating the senses.

Hypothesis:
/Feeling/ is the way the subconscious communicate to the conscious.

Hypothesis:
The mind consists of these parts:
the thinking (the logical/linguistic),
the feeling (the autonomous/subconscious/emotional),
the moving (the motoric),
and the observing (the conscious).

Where does imagination come from?
*** Forgetting dreams?
To lucid-dream, make it a habit to ask yourself every hour, "Am I dreaming?"?
Does that work?
Why?
How?

https://www.livescience.com/62703-why-we-forget-dreams-quickly.html
*** The "cage"?
Dzogchen?

Namkhai Norbu, "The Mirror: Advice on the Presence of Awareness"?
*** On the limits of imagination
Can I imagine a color I has never seen?

Can I imagine a color I /cannot/ see?
For example, what is the color of a gamma ray?
Or, I can see that?

Subconscious is habit?

Does subliminals work?

Are levitating monks real?
*** What is time?
If time is an illusion, what is real?
** Meditation?
The attention wanders in meditation, but we /gently/ bring it back to where we want it to be.
 [fn::<2019-09-17> How to Meditate with Charles T. Tart https://www.youtube.com/watch?v=OWfe3pVYP8o]
The more we try to suppress a thought, the harder it resists.
Acknowledge the thought, and move on?

Is it about relaxation or concentration?
Is it about silence or concentration?
* Other things
Hemi-Sync was mentioned by some authors whose books I read, such as Joe McMoneagle and Eben Alexander.

Wim Hof method vs Tummo meditation?[fn::https://www.wimhofmethod.com/tummo-meditation]
* Meditating while driving, reading, etc.?
When you drive a car, you are one with the car, in the sense that you can feel the spatial extent of the car,
in the sense that you can feel whether a turning road is wide enough for the car.

You can meditate (focus) on the object.
You can meditate on the subject.
You can meditate on the separation between the subject and the object?
* Bibliography
