#+TITLE: Internal Research Group
#+DATE: 2017-05-25 01:00:00 +0700
#+PERMALINK: /meta.html
* Organization of this wiki
** Hierarchy and linking
These rules exist to simplify renaming files.
(But aren't wiki articles supposed to be highly interlinked?)

The hierarchy of this website is 2 levels deep.
Level 1 is the home page.
Level 2 is everything else.

If article X links to article Y, and both X and Y are not generated, then Y should not link to X.
** Article categories
Each article in this wiki belongs to one of these categories:
- survey (What exists? What is the state of...)
- argument (We should...)
- exploration (What if...); borderline ramble
- record/logging/memory/notes (What happened when?)
- rant/complaint/ramble/babble/sketch

A mature exploration should become an argument.

I record the evil and the incompetencies, of people, corporations, and systems.
** Article structure
The title is a goal.

The content is the ongoing journey to achieve it.

Each article in this site is a living document.
* What are some similar websites?
These are some websites similar to this website and their differences.

[[https://kevinbinz.com/][kevinbinz.com]] is more like a blog than a wiki.

[[https://en.wikipedia.org/][en.wikipedia.org]] does not want original content.
(Also, if [[https://www.quora.com/Will-it-be-feasible-to-move-Wikipedia-mediaWiki-from-PHP-to-some-modern-language-like-Golang][Kelly Kinkade's answer]] is true, then it's worrying that so much human knowledge is stored in such unparseable MediaWiki markup language.)

TheBrain: the idea is good, but the app is slower than static web.

[[https://www.brainpickings.org][brainpickings.org]]:
too social, too much content, too little navigation, too little structure;
pop science content is too much pop and too little science.
* Meta-thinking
** When stuck, ask yourself...
When you're stuck, ask yourself "What question do I have to ask myself in order to get me unstuck?"
** When stuck on a question, convert it into a hypothesis
Every question can be turned into a hypothesis.
Therefore, don't ask.
Instead, hypothesize, and find evidences for or against.

What is this:
The value of asking questions
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3596240/
** How to categorize
Suppose we want to categorize T (a set of things) to C (a set of categories).

A good categorization is:
- complete/exhaustive: every item belongs to a category
- disjoint (non-overlapping): every item belongs to exactly one category
- similar-sized: each category contains about the same number of items

https://webdesign.tutsplus.com/articles/the-art-of-structuring-information-effectively--webdesign-6807

* I think I have stopped caring about these
** Fonts
<2018-07-21>
Wikipedia uses 14px (about 10.5pt).

Why is the font so big?
Because I'm myopic.

Why is the font so small?
To fit more information on screen.

To shrink the text, press Control-minus.

To expand the text, press Control-plus.

I read smaller text faster because my eyes move less, until the font size reaches 8pt.
The screen pixels aren't dense enough to render 8pt sans-serif.
** Problem: can't infer last modified date of files in a Git repository?
This affects Google crawl?
- Yes.
  - https://www.sitemaps.org/protocol.html
    - sitemap.xml lastmod is optional but
      "This incremental Sitemap fetching mechanism allows for the rapid discovery of new URLs on very large sites."
- No.
  - https://webmasters.stackexchange.com/questions/25833/does-google-penalize-daily-updated-lastmod-tags-in-sitemaps-if-the-data-is-not
    - "The lastmod tag is optional in sitmaps and in most of the cases it's ignored by search engines,
      because webmasters are doing a horrible job keeping it accurate."

Solution candidates:
- Manually update lastmod every time we edit an md file
- Write a script to update lastmod in each md file
  - all files, or only those in a commit?
  - https://serverfault.com/questions/401437/how-to-retrieve-the-last-modification-date-of-all-files-in-a-git-repository
  - https://stackoverflow.com/questions/14141344/git-status-list-last-modified-date
  - https://hackerific.net/2016/04/30/git-file-age-a-script-to-show-when-files-were-last-modified-in-git/
- Stay in Jekyll, modify sitemap generator
  - https://github.com/gjtorikian/jekyll-last-modified-at
    - not compatible with github pages https://github.com/gjtorikian/jekyll-last-modified-at/issues/32
  - https://stackoverflow.com/questions/14978474/how-to-show-the-modification-date-of-a-file-in-jekyll
  - https://milanaryal.com.np/jekyll-site-last-modified-time/
- Generate sitemap.xml outside Jekyll
- Run Jekyll locally, commit output html to github
* What
** How should we order or group questions in this website?
Why do we group questions?
Because everyone has narrow and different interests.
Everything that does not interest us is noise to us, that we filter out.
We care about some truth, but we do not have time for all truth.
One who cares about a question is likely to also care about related questions.

What properties should the ordering have?
The ordering should be natural and meaningful to the reader.
The ordering should help the reader understand the content.
The ordering should promote the fastest possible learning.

By Bloom's taxonomy: remembering, understanding, transferring, relating, creating, judging?[fn::http://faculty.academyart.edu/faculty/teaching-topics/teaching-curriculum/enhancing-teacher-student-interaction/different-types-questions-blooms-taxonomy.html]
Similar to Fraenkel's taxonomy[fn::https://www.slideshare.net/jrbt2014/fraenkels-taxonomy-of-question]?

By hardship?
By the time I spent looking for answers?

By importance?
From survival questions, to fun questions?

Close-ended vs open-ended?

By number of answers: zero, one, many?

Logical/mental/ideal (whose truth is self-contained, that is, requires only logic and no reality) vs physical/material (whose truth depends on reality)?

By nature: argument, exploration?

By probability of an average person being interested?
By relevance to the general population?

By inspiringness, from the most inspiring?
But this ordering is not timeless?

The information literacy tutorial[fn::http://camellia.shc.edu/literacy/index.html]
** What makes a question hard?
Any combination of these:
- It is unanswerable.
  It is unknowable.
  It is epistemologically impossible to answer.
- Its answer's search space is big.
- It requires much background knowledge to understand, let alone to answer.
** How do we do research?
How do we [[file:research.html][research]]?
How should we?
Who should we know?
Where should we go?
Where should we write?

Good researchers define the topic and formulating a strong and precise thesis statement.
They define which questions need to be explored and answered.
They use terms that work within the structures of the library and its online information systems.
 [fn::http://camellia.shc.edu/literacy/tablesversion/lessons/lesson3/defining.htm]
** How should we organize this website?
By questions that we want to answer?

By goals that we want to achieve (currently-false statements that we want to make true)?
** How should we publish on the Internet?
I am [[file:publish.html][looking for a publishing system]].
I also write
[[file:emacs.html][Using Emacs and Org Mode]],
[[file:emacsvi.html][Emacs for vi users]],
[[file:writing.html][Writing]],
and [[file:markdown.html][Working around Markdown]].
** What is the difference between important and urgent?
Something is important if not doing it is fatal.
Breathing, eating, drinking water.
Having some in-demand high-paying skills.
Being useful.

Something is urgent if it urges you to do it, if you feel an urge (strong desire) to do it.
Eating sugar, fucking, shitting.
* How should we meet?
This is the way we should meet.
Ban small talk.
Impose some but minimal structure.
See Marcel Schwantes article[fn::https://www.inc.com/marcel-schwantes/13-genius-questions-most-interesting-people-ask-to-start-great-conversations.html].
* Should we create our own publishing system?
These may be strong reasons for rolling our own publication system in Prolog:
- (WONTFIX) Org Mode Reader duplicates footnotes https://github.com/jgm/pandoc/issues/5196
- (workaround available) HTML writer does not separate adjacent footnote references https://github.com/jgm/pandoc/issues/5197
- amsthm, theorem/lemma/definition/proof
- we want by default #+OPTIONS: ^:nil
- multi-authorship?
- https://github.com/jgm/pandoc/issues/1608
- LaTeX command argument, hard to fix (practically wontfix) https://github.com/jgm/pandoc/issues/5261 https://github.com/jgm/pandoc/issues/3047

As we age, we learn that a hack/quick-fix/duct-tape only leads to misery, regret, and self-hate.

However, the last time we tried to create our own publishing system was a big XML disaster.
* Self-research
PhD interview questions[fn::https://www.findaphd.com/advice/finding/phd-interview-questions.aspx][fn::https://academia.stackexchange.com/questions/101803/answering-the-why-do-you-want-to-do-a-phd-question]
** What are my strengths?
I try to be rational.
I readily change my beliefs when I find conflicting evidences.
** What are my weaknesses?
I have a bad relationship with time.
I have difficulty sleeping and waking up.
I disregard deadlines.
I'm slow.
I suck at races.

I don't act without reason.
I am prone to overthinking.
I am selfish and stubborn.
I see things from my point of view.
It takes a lot of effort to convince me.
I should not be put in a team that I do not believe in.
I will not do what I don't believe is important for my goal.
You will find me useless when you want me to do something that I don't believe is important for my goal, no matter how important it is to you;
in such situation I will be totally uncooperative.
I don't pretend to care.

I am non-conformist.
I put reason above norms, conventions, and authorities.
I hate ceremonies.
I risk making cultural mistakes.
My candid may offend people.

I'm bad at socializing, but I'm trying to change this.
I suck at caring.
I suck at pretending to care.
I'm learning to be the first to greet.

I hate crowds.
I'm afraid to be in crowds.
I'm paranoid and untrusting.

I am not loyal.

I have strong opinions on everything.
** What am I no longer interested in?
I occasionally played weiqi[fn::Weiqi is also known as go, igo, baduk. https://en.wikipedia.org/wiki/Go_(game)],
but after AlphaGo[fn::https://en.wikipedia.org/wiki/AlphaGo] beat[fn::https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol] Lee Sedol, I abandoned weiqi and never looked back.
I occasionally played chess, before Deep Blue beat Kasparov[fn::https://en.wikipedia.org/wiki/Deep_Blue_versus_Garry_Kasparov].
I occasionally played poker, before machines took over[fn::https://www.theguardian.com/technology/2017/jan/30/libratus-poker-artificial-intelligence-professional-human-players-competition].
Now I think that games only waste time:
I see no point in doing something that machines can do better than I do.
** What musical instruments do I play?
I played piano in the band [[file:nomads.html][The Nomads]] (an Indonesian band, not the Swedish band).
However, I quit being a performer on 2018-12-23, less than a year after joining the band, because I hate inhaling cigarette smoke in venues and I hate carrying pianos to venues.
I am no longer a pianist.
I am now a composer with an asset mindset.
** What things do I find entertaining?
I collect [[file:entertain.html][entertainments found on the Internet]].

Why are lyrebirds entertaining?
Lyrebird can mimic sounds uncannily.
Laser guns, drills, hammers, camera shutters.
* How should wee write?
** Writing; topic position and stress position
"A reader will unconsciously focus at the end of the sentence to identify what is important."[fn::https://www.springer.com/gp/authors-editors/authorandreviewertutorials/writinginenglish/stress-position/10252690]

It is more important for the sentences of a paragraph to have /related topics/ than to have active voice \cite{gopen1990science}.
(A sentence's topic is what in its topic position.)
** TODO Writing?
https://medium.com/@write4research/why-do-academics-and-phders-carefully-choose-useless-titles-for-articles-and-chapters-518f02a2ecbb

https://medium.com/@write4research/top-ten-questions-to-ask-about-your-chapter-start-32848d924953
