#+TITLE: Mind Research Group
#+DATE: 2019-02-06 00:00:00 +0700
#+PERMALINK: /mind.html
#+OPTIONS: ^:nil
* Linguistic analysis
** Mind is what thinks thoughts
<2018-11-04>
Our usage of English suggests that /the mind is what thinks thoughts/:
It feels wrong to substitute "What's in your mind?" with "What's in your brain?".
Thus, it is the mind that thinks, not the brain.

"What's in your mind" implies that a mind can contain thoughts in the way a box can contain things.

The mind thinks.
The brain follows physical laws.
But how does a mind get tied to a brain (or how does a brain give rise to a mind)?

Brain contains brain matter.
Mind contains thoughts.

"Mind contains thoughts" implies that mind has a boundary.
* What
** Nonlocal what?
"Nonlocal Mind: Best Updated Empirical and Theoretical Evidence"
http://www.patriziotressoldi.it/cmssimpled/index.php?page=best-updated-empirical-and-theoretical-evidence
** TODO Tetanus, rabies, electrocution, epilepsy, uncontrollable spasms, and the mind
Tetanus, rabies, electrocution, and epilepsy cause muscle spasms that the suffering body's mind doesn't control.
** TODO questions
Soul is the cause of the changing wants?
** TODO Materialism, ship of Theseus, continuity of identity, what makes us us
Let T be a point in time.

Let /original atoms/ mean all the atoms that make me at time T.

I'm always replacing the atoms that make me.

After some duration, I will have replaced most of the original atoms.

However, I don't feel a gap in my subjective experience.
I still remember the same things.
I still think I'm the same person.

What?

- https://www.quora.com/What-is-the-scientific-evidence-that-every-atom-in-the-brain-of-a-person-gets-replaced-over-time
- https://www.reddit.com/r/askscience/comments/g63l6/are_98_of_the_atoms_in_the_human_body_replaced/
- https://biology.stackexchange.com/questions/24020/are-brain-cells-replaced-over-time

What?
Linguistic (non?)solution to Ship of Theseus?

- http://steve-patterson.com/no-chairs-do-not-exist/
- https://www.reddit.com/r/philosophy/comments/331ni0/no_chairs_do_not_exist/

To tag is to put a name tag for later identification.

We can tag a dolphin. Can we tag an electron?

https://en.wikipedia.org/wiki/One-electron_universe

https://aeon.co/ideas/if-i-teleport-from-mars-does-the-original-me-get-destroyed

** TODO How does subjective experience arise?
Does subjective experience arise from matter?

Why do I happen to be this particular subjective experience among other billions of possible subjective experiences?

A subjective experience is a point of view (from which a being perceives).

Consciousness is not subjective experience.

Being conscious doesn't mean having subjective experience.

Being conscious doesn't mean having a mind.

"Total synthesis" means what is described in the Wikipedia article of the same title. https://en.wikipedia.org/wiki/Total_synthesis

"Molecular assembly"

Suppose that we total-synthesize a fertilized egg, and we place that egg in a womb.
Then that egg will grow.
The egg doesn't care about its history.

Suppose that John is an average 30-year-old man.
We can snapshot his chemical configuration at a point in time.
From that snapshot, we can recreate the chemical configuration that constitutes John at that point in time.
We can total-synthesize a replica of John.
But this replica would have different subjective experience.
The original John also continues to exist.

Existence doesn't require subjective experience.
The virtual people in the game "The Sims" doesn't have subjective experience.
(Do they!?)

By now I would have concluded that brain controls mind, if I hadn't heard of Pim van Lommel's near-death experiments.

I want to believe that the brain control the mind, but there are Pim van Lommel's near-death experiments.

An outlandish explanation attempt: interfering parallel universes.
There is a parallel universe where Pim told his patients.
That universe interferes with our universe.

Scientists have assembled a bacterium.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2836213/#!po=0.263158

A newborn fails the self-awareness test.

A system is self-aware means that a system know its self or itself?

Does a newborn have subjective experience?

How does subjective existence arise?

Don't conflate "consciousness" and "subjective experience". Consciousness is the ability to know. Your subjective experience is your first-person view.

Does an imaginary person have a real subjective experience? (Does this question even make sense?)

Does a sim in the game "The Sims" have a subjective experience?

JTB theory:
Is it possible to believe something true but for the wrong reason?
So what?

https://www.reddit.com/r/philosophy/comments/4sh4bz/man_missing_90_of_brain_poses_challenges_to/
* What is not mind?
** Autonomous nervous system is not part of mind
Consider my ANS (autonomic nervous system).

My brain controls my ANS.
My mind does not control my ANS (I don't know how).

Thus, my ANS is a part of /my brain's/ self, but my ANS is not a part of /my mind's/ self.

However, both my mind and my brain are parts of /my/ self.

My mind has only very small control over my brain.
The involuntary processes are much bigger than the voluntary processes.
*** <2018-11-06> We usually conflate /someone/ and /someone's mind/.
These questions usually mean the same thing:
- What do /you think/?
- What's /in your mind/?

That equivalence implies that your mind is a part of you or belongs to you.

However, when we insult, we say "Use your brain!", not "Use your mind!"
*** TODO Drafts
**** What does it mean to have the same thought?
"Are you thinking what I'm thinking?"
**** Casual English usage
- "It has a mind of its own" means it has its own wants.
***** Expressing objections
- "Mind the gap."
- "Mind the language."
- "Do you mind if I turn on the air conditioner?"
- https://english.stackexchange.com/questions/54867/on-mind-vs-in-mind
**** Dictionary definitions of "mind"
- <2018-11-05> https://en.oxforddictionaries.com/definition/mind
  - "The element of a person that enables them to be aware of the world and their experiences, to think, and to feel; the faculty of consciousness and thought."
  - "A person's ability to think and reason; the intellect."
    - "A person's memory."
    - "A particular way of thinking, influenced by a person's profession or environment."
    - "A person identified with their intellectual faculties."
  - "A person's attention."
    - "A person's will or determination to achieve something."
- <2018-11-05> https://en.wiktionary.org/wiki/mind#Noun
  - "The ability for rational thought."
  - "The ability to be aware of things."
  - "The ability to remember things."
  - "The ability to focus the thoughts."
  - "Somebody that embodies certain mental qualities."
  - "Judgment, opinion, or view."
  - "Desire, inclination, or intention."
  - "A healthy mental state."
  - "(philosophy) The non-material substance or set of processes in which consciousness, perception, affectivity, judgement, thinking, and will are based."
**** <2018-11-06> Is the mind a /sense/?
- A sense connects mind and reality?
- The eye senses light.
- The ear senses sound pressure variations.
- The nose senses chemicals floating in the air.
- The mind senses thought?
**** <2018-11-04> A mind is an /organ/ that thinks?
- What is an organ?
- /Where/ is the mind?
  Does it exist in space?
**** <2018-11-04> A brain /houses/ a mind?
- Hippocrates?
  Brain is seat of mind?
**** What is the relationship between mind, sleep, and consciousness?
Does my mind exist while I'm sleeping?

My busy mind prevents me from sleeping?

Can we know anything if we don't have any senses to interact physically?

Which one sleeps: my mind, my brain, or me?
**** First-person view? Subjective experience? Qualia?
**** Why does subjective experience exist?
We are made of the same kinds of atoms.
Why do our consciousness differ?

Every hydrogen atom has the same property (mass, charge, etc.).

Why does subjective experience exist?
- The same functional area of different brains are located at the same spot. We can predict the effect of damaging certain areas of the brain. Thus there is a common principle that determine how all brains work.
- Everyone seizures when electrical-shocked. This implies that all muscles work the same way.

Binding problem
https://psychology.stackexchange.com/questions/8056/how-does-subjective-experience-arise-from-matter

https://en.wikipedia.org/wiki/Hard_problem_of_consciousness

Search "brain without consciousness" and "consciousness without brain".

Does this make sense?
- https://www.google.co.id/amp/s/qz.com/866352/scientists-say-your-mind-isnt-confined-to-your-brain-or-even-
- https://www.consciouslifestylemag.com/non-local-consciousness-and-the-brain/
- https://www.google.co.id/amp/s/www.psychologytoday.com/us/blog/mind-brain-and-consciousness/201101/mind-brain-and-consciousness%3famp
- http://superconsciousness.com/topics/science/why-consciousness-not-brain
- https://en.m.wikipedia.org/wiki/Consciousness
- Can we memorize something while we are unconscious (sleeping)?
- Attention
- Relate them all
- https://www.explorejournal.com/article/S1550-8307(12)00271-6/fulltext
- Thanatology
- http://www.amitgoswami.org/2016/12/20/the-scientific-evidence-for-god-is-already-here-so-what-are-you-doing-about-it/
- Quantum is suspicious.
- http://superconsciousness.com/topics/science/why-consciousness-not-brain

How are our brains different, and how are our brains the same?

Compare these statements.
Which ones make sense?
- The self is everything that the brain can directly control.
- The self is everything that the brain can consciously directly control with electrical signals.
- The self is everything that the conscious mind can control.

The simplest explanation to why we don't remember our past lives is that past lives don't exist.
But human memory is unreliable.
But there are stories of some people who can corroborate their past lives?
***** Hypothesis: Adult dogs are more conscious than newborn human babies.
**** TODO Fucking around with language: intending to intend, wanting to want, willing to will
***** <2018-11-05> Volition is involuntary.
- Life is involuntary.
  We have life without wanting it.
- Volition is involuntary.
  We have volition without wanting it.
- We did not intend to intend?
***** All these articles are behind fucking paywalls. Who the hell pays $40 to read philosophers fuck around with language?
- 1987 article "Are Intentions Self-Referential?" https://www.jstor.org/stable/4319923?seq=1
- 2000 article "The Self-referentiality of Intentions" https://link.springer.com/article/10.1023%2FA%3A1018336525240

* Mind-brain interaction; comparison of mental phenomena
** Table of comparison by origin and volitionality
Hallucination is when brain confuses input and output?

I have experienced these first-hand:
- sleep paralysis: when going from sleep to wake, can move eyes, can breathe, but can't move other muscles, not even speak
- hypnagogic jerk: the feeling of falling when going from wake to sleep

<2018-11-07>
The difference between imagination and hallucination is /voluntary of existence/.
We can start imagining at will.
We can stop imagining at will.
We cannot start hallucinating at will.
We cannot stop hallucinating at will.
"At will" means "voluntarily", that is, "by volition".

Example.
I can imagine an elephant for three seconds, and then stop imagining it.
But, if I eat a psychedelic mushroom,
I can't stop the hallucination by sheer will,
but eventually my brain chemistry returns to normal and the hallucination ends.

Imagination: mind affects brain.
Hallucination: brain affects mind.

This explains why people can't die /just by wanting/ to die:
because the mind does not fully control the brain.

How do we complete this table?

|                    | can we start it at will? | does it require our will (conscious mental effort) to start? | can we stop it at will? | origin |
| imagination        | yes                      | yes                                                          | yes                     | mind   |
| hallucination      | no                       | no                                                           | no                      | brain  |
| illusion           | no                       | no                                                           | no                      | ?      |
| delusion           | no                       | no                                                           | no                      | ?      |
| intrusive thoughts | no                       | no                                                           | no                      | ?      |
** Mind-brain interaction/experiments; Sperry, Libet, mentalism, and non-materialism
(Are there other scientific experiments?
Search "consciousness experiments" on the Internet.)

We want to infer from these things:
- the relationship between these concepts:
  - volition
  - imagination, hallucination, illusion, delusion
  - wake, sleep, dream
  - intrusive thoughts
  - three kinds of consciousness? https://www.sciencealert.com/artificial-intelligence-three-types-of-consciousness
    - 2017 "What is consciousness, and could machines have it?" http://science.sciencemag.org/content/358/6362/486
    - C0 = the problem solving our brains do without our awareness
    - https://en.wikipedia.org/wiki/Artificial_consciousness
  - https://en.wikipedia.org/wiki/Category:Thought_experiments_in_philosophy_of_mind
- brain experiments
  - Sperry's insightful experiments (paywall) https://www.sciencedirect.com/science/article/abs/pii/0306452280900986
  - [[http://www.informationphilosopher.com/freedom/libet_experiments.html][Libet experiments]]
  - Split-brain (corpus callostomy)
    - [[https://en.wikipedia.org/wiki/Split-brain][WP:Split-brain]]
    - [[https://faculty.washington.edu/chudler/split.html][Neuroscience for kids]]
    - [[https://embryo.asu.edu/pages/roger-sperrys-split-brain-experiments-1959-1968][Roger Sperry's split-brain experiments (1959--1968)]]
    - https://www.nobelprize.org/educational/medicine/split-brain/
    - How did we find out that corpus callostomy reduces epilepsy?

These experiments seem to support physicalism/materialism/reductionism/monism: reconstructing brain input from brain activity?
- 1999, Scientists reconstruct picture from cat brain activity
  - https://www.berkeley.edu/news/media/releases/99legacy/10-15-1999.html
- Scientists reconstruct movie from human brain activity
  - https://gizmodo.com/5843117/scientists-reconstruct-video-clips-from-brain-activity
  - [[https://www.youtube.com/watch?v=nsjDnYxJ0bo][YT:Movie reconstruction from human brain activity]]
  - http://news.berkeley.edu/2011/09/22/brain-movies/

What we may do with those things:
- formal concept analysis https://en.wikipedia.org/wiki/Formal_concept_analysis
- classification / dichotomization

There is an idea "Your brain hallucinates your conscious reality" (your brain hallucinates your subjective experience):
https://www.reddit.com/r/philosophy/comments/6rqq11/your_brain_hallucinates_your_conscious_reality/

TODO Read Liber's "A testable field theory of mind brain interaction"

Relevant phenomenons, experiments, reports, and cases:
- Phineas Gage changed after brain accident
- French civil servant with missing brain https://www.youtube.com/watch?v=_oXoMYJIvJ4
  - "A man in France continues to puzzle scientists nearly a decade after he was found to be living with just 10 percent of a typical human brain."
  - "Despite the reduced brain matter, the man lived a relatively normal life; he was a married civil servant with two kids.
    He also scored an IQ of 75 which is considered low but not disabled."
- Baby born without forebrain

Transcranial magnetic stimulation[fn::https://en.wikipedia.org/wiki/Transcranial_magnetic_stimulation] shows that some physical change on the brain affects subjective experience of the mind.
The question: does the /same/ magnetic stimulation cause the /same/ change in subjective experience?

Brain study, psychedelics, and anesthetics:
We still don't know how psychedelics and anesthetics work.
*** TODO Is intrusive thoughts voluntary?
*** TODO What I think we know?

* What is the relationship between mind and brain?
Our brain is analog, but our mind is digital?
Is our brain analog or digital?
 [fn::https://medium.com/the-spike/brains-as-analog-computers-fa297021f935]
 [fn::https://www.forbes.com/sites/quora/2016/09/27/is-the-human-brain-analog-or-digital/]

Vsauce video "What is consciousness?"[fn::https://www.youtube.com/watch?v=qjfaoe847qQ]
