#+TITLE: On mind-brain interaction
#+DATE: 2018-11-04 00:00:00 +0700
#+PERMALINK: /mind-brain.html
* On the interaction between mind and brain
We know that mental stress can induce somatic illness.

How do I distinguish between these two cases?
- I was conscious before I was born but I have no memory of it
- I was not conscious before I was born

I know that I exist.
I think I existed a few seconds ago because I have a memory of that.
But how do i know that I /existed/ a few hours ago?
My memory is only an extremely simplified representation of what my past self perceived.

Can a conscious being be unaware of itself, its own existence?

Memory is necessary for consciousness?

Hypothesis: A brain /traps/ consciousness.
* On mind-body interaction experiments and case reports
Sperry, Libet, mentalism, and non-materialism

What can we infer from these experiments?
What are they trying to tell us?

(Are there other scientific experiments?
Search "consciousness experiments" on the Internet.)

We want to infer from these things:
- the relationship between these concepts:
  - volition
  - imagination, hallucination, illusion, delusion
  - wake, sleep, dream
  - intrusive thoughts
  - three kinds of consciousness? https://www.sciencealert.com/artificial-intelligence-three-types-of-consciousness
    - 2017 "What is consciousness, and could machines have it?" http://science.sciencemag.org/content/358/6362/486
    - C0 = the problem solving our brains do without our awareness
    - https://en.wikipedia.org/wiki/Artificial_consciousness
  - https://en.wikipedia.org/wiki/Category:Thought_experiments_in_philosophy_of_mind
- brain experiments
  - Sperry's insightful experiments (paywall) https://www.sciencedirect.com/science/article/abs/pii/0306452280900986
  - [[http://www.informationphilosopher.com/freedom/libet_experiments.html][Libet experiments]]
  - Split-brain (corpus callostomy)
    - [[https://en.wikipedia.org/wiki/Split-brain][WP:Split-brain]]
    - [[https://faculty.washington.edu/chudler/split.html][Neuroscience for kids]]
    - [[https://embryo.asu.edu/pages/roger-sperrys-split-brain-experiments-1959-1968][Roger Sperry's split-brain experiments (1959--1968)]]
    - https://www.nobelprize.org/educational/medicine/split-brain/
    - How did we find out that corpus callostomy reduces epilepsy?

These experiments seem to support physicalism/materialism/reductionism/monism: reconstructing brain input from brain activity?
- 1999, Scientists reconstruct picture from cat brain activity[fn::https://www.berkeley.edu/news/media/releases/99legacy/10-15-1999.html]
- Scientists reconstruct movie from human brain activity
  [fn::https://gizmodo.com/5843117/scientists-reconstruct-video-clips-from-brain-activity]
  [fn::YT:Movie reconstruction from human brain activity https://www.youtube.com/watch?v=nsjDnYxJ0bo]
  [fn::http://news.berkeley.edu/2011/09/22/brain-movies/]

What we may do with those things:
- formal concept analysis[fn::https://en.wikipedia.org/wiki/Formal_concept_analysis]
- classification / dichotomization

There is an idea that "Your brain hallucinates your conscious reality" (your brain hallucinates your subjective experience)
 [fn::https://www.reddit.com/r/philosophy/comments/6rqq11/your_brain_hallucinates_your_conscious_reality/].

TODO Read Liber's "A testable field theory of mind brain interaction"

Relevant phenomenons, experiments, reports, and cases:
- Phineas Gage changed after brain accident
- French civil servant with missing brain https://www.youtube.com/watch?v=_oXoMYJIvJ4
  - "A man in France continues to puzzle scientists nearly a decade after he was found to be living with just 10 percent of a typical human brain."
  - "Despite the reduced brain matter, the man lived a relatively normal life; he was a married civil servant with two kids.
    He also scored an IQ of 75 which is considered low but not disabled."
- Baby born without forebrain

Transcranial magnetic stimulation[fn::https://en.wikipedia.org/wiki/Transcranial_magnetic_stimulation] shows that some physical change on the brain affects subjective experience of the mind.
The question: does the /same/ magnetic stimulation cause the /same/ change in subjective experience?

Brain study, psychedelics, and anesthetics:
We still don't know how psychedelics and anesthetics work.

Hogan sisters' "thalamic bridge"[fn::http://www.drhaseltine.com/six-brain-phenomena/]
** TODO Is intrusive thoughts voluntary?
** TODO What I think we know?
* On classifying mind-brain interaction
Here we classify mind-brain interaction by /origin/ and /voluntariness/.

We know that some changes in the brain cause some changes in the mind,
and some changes in the mind cause some changes in the brain.

Hallucination is when brain confuses input and output?

I have experienced these first-hand:
- sleep paralysis: when going from sleep to wake, can move eyes, can breathe, but can't move other muscles, not even speak
- hypnagogic jerk: the feeling of falling when going from wake to sleep

<2018-11-07>
The difference between imagination and hallucination is /voluntary of existence/.
We can start imagining at will.
We can stop imagining at will.
We cannot start hallucinating at will.
We cannot stop hallucinating at will.
"At will" means "voluntarily", that is, "by volition".

Example.
I can imagine an elephant for three seconds, and then stop imagining it.
But, if I eat a psychedelic mushroom,
I can't stop the hallucination by sheer will,
but eventually my brain chemistry returns to normal and the hallucination ends.

Imagination: mind affects brain.
Hallucination: brain affects mind.

This explains why people can't die /just by wanting/ to die:
because the mind does not fully control the brain.

How do we complete this table?

| name               | can we start it at will? | does it require our will (conscious mental effort) to start? | can we stop it at will? | origin |
|--------------------+--------------------------+--------------------------------------------------------------+-------------------------+--------|
| imagination        | yes                      | yes                                                          | yes                     | mind   |
| hallucination      | no                       | no                                                           | no                      | brain  |
| illusion           | no                       | no                                                           | no                      | ?      |
| delusion           | no                       | no                                                           | no                      | ?      |
| intrusive thoughts | no                       | no                                                           | no                      | ?      |
| delirium           | ?                        | ?                                                            | ?                       | ?      |
| confusion          | ?                        | ?                                                            | ?                       | ?      |
| headache           | ?                        | ?                                                            | ?                       | ?      |
* Sleep deprivation causes difficulty focusing; mental muscles, mental exertion, and mental analogs
I find reading philosophical articles harder when I don't sleep enough the night before.
I find it harder to focus.
Sleep deprivation affects my ability to think, but not my ability to lift weights.

Mental analogs?

Key finding: Focus uses glucose?
Cite?

Key fact: Both physical exertion and mental exertion use glucose?
* Most of the brain is not for consciousness
"What Is Consciousness?"
https://www.nature.com/articles/d41586-018-05097-x
* Is brain/mind analog or digital?
Our brain is analog, but our mind is digital?
Is our brain analog or digital?
 [fn::https://medium.com/the-spike/brains-as-analog-computers-fa297021f935]
 [fn::https://www.forbes.com/sites/quora/2016/09/27/is-the-human-brain-analog-or-digital/]
