#+TITLE: Model
#+DATE: 2018-04-11 04:00 +0700
#+PERMALINK: /model.html
#+MATHJAX: yes
* Summary
A /model/ of a thing is a /simplification/ of that thing.

A model always comes with /simplifying assumptions/.

Violating the simplifying assumptions leads to nonsense.

Related concepts: simplification, ignoration, truncation, approximation.
* The meaning of "model"
** History of the English word "model"
In the 15th century, a model is a small woodwork crafted with the same proportions of a building that is going to be built.
Thus a model has the same shape of the building but is much smaller.
For example, if the building has a stone wall, then the model has a wooden card.

The English word "model" comes from Latin "modellus" that is diminutive of "modulus" that is diminutive of "modus".
The Latin "modus" means "measure", and "modulus" is small "modus", and "modellus" is small "modulus";
thus "modellus" should mean "a small small measure".

The "model" in "bone remodeling" and "kitchen remodeling" means reshaping, reformation, renewal, renovation, replacement.

Sources:
- Dictionaries and thesauruses
  - Oxford English Dictionary: "model" comes from "Late 16th century (denoting a set of plans of a building) [...]".
    [[https://en.oxforddictionaries.com/definition/model]]
  - Historical Thesaurus of English (ht.ac.uk):
    The noun "model" was used in 1575 to mean "plans of construction".
    and the verb "model" was used in 1604 to mean "represent".
    [[https://ht.ac.uk/category-selection/?word=model&page=1&categoryMinis=on&categorySort=tier]]
  - The Online Etymology Dictionary traces the noun "model" back to the 1570s "likeness made to scale; architect's set of designs".
    It traces the verb "model" back to a word in 1660s meaning "fashion in clay or wax".
    [[https://www.etymonline.com/word/model]]
  - Princeton WordNet 3.1
    [[http://wordnetweb.princeton.edu/perl/webwn?s=model&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=]]
  - The Free Dictionary [[https://www.thefreedictionary.com/model]]
  - Wiktionary [[https://en.wiktionary.org/wiki/model]]
  - Also, the definition of "model oneself after" in Merriam-Webster dictionary
    [[https://www.merriam-webster.com/dictionary/model%20oneself%20after]]
- Images
  - 15th century wooden architectural model of Florence Cathedral Dome by Filippo Brunelleschi
    [[https://www.architectural-review.com/essays/architects-do-it-with-models-the-history-of-architecture-in-16-models/8658964.article]]
- Essays
  - Wilfrid Hodges's history of the word "model" in "model theory", in the Stanford Encyclopedia of Philosophy
    [[https://plato.stanford.edu/entries/model-theory/#Modelling]]
  - Gene Bellinger's definition: "a simplification of reality intended to promote understanding"
    [[http://www.systems-thinking.org/simulation/model.htm]]
  - 2009 Emily Griffiths article "What is a model?"
    - various types of models: conceptual models, in vivo (in life) models, in vitro (in glass) models, in silico (in silicon, that is, computer) models
    - "Certainly all models are simplifications"
    - "[models] bear some likeness to the real world and are constructed to reflect certain parts that are essential for the job in hand"
    - [[https://sites.google.com/a/ncsu.edu/emily-griffiths/publications/general-articles]]
    - [[https://sites.google.com/a/ncsu.edu/emily-griffiths/whatisamodel.pdf?attredirects=0]]
    - [[https://web.archive.org/web/20120312220527/http://www.emily-griffiths.postgrad.shef.ac.uk/models.pdf]]
- Forums
  - I asked this on History of Science and Mathematics StackOverflow.
    [[https://hsm.stackexchange.com/questions/7948/what-motivated-the-choice-of-the-word-model-in-model-theory/7953#7953]]
- Automated question-answering systems
  - [[https://books.google.com/talktobooks/query?q=What%20is%20a%20model?][What is a model? - Google Talk to Books]]
- Encyclopedias
  - Wikipedia article [[https://en.wikipedia.org/wiki/Model][Model]], and pages linked from there, such as
    [[https://en.wikipedia.org/wiki/Architectural_model][Architectural model]],
    [[https://en.wikipedia.org/wiki/Physical_model][Physical model]],
    Also, by text search: [[https://en.wikipedia.org/wiki/Role_model][Role model]].
  - [[https://www.britannica.com/search?query=model][Encyclopaedia Britannica search result for "model"]]
  - [[https://www.encyclopedia.com/search?keys=model][encyclopedia.com search result for "model"]]
** The meanings of "model" in 2018
How do we show that all these senses of "model" are essentially simplifications?
*** Concretization for transfer learning
For example, we study a /model organism/ to understand other organisms.
This suggests that a model is about /transfer learning/:
knowledge about the model maps to knowledge about the modeled,
as long as the knowledge is about aspects captured by the model.
See also the [[https://en.wikipedia.org/wiki/Model_organism][Wikipedia article about model organism]].
*** Abstraction, picking aspects, ignoring irrelevant details
- A Newton equation system /models/ a real physical system.
- A Newton equation system /is a model of/ a real physical system.
- Quadratic equations /model/ parabolic motions.
- The Lotka-Volterra equations can /model/ the populations of lions and deers in a savanna.

It is confusing that "model" can mean both concretion and abstraction, which are opposites.
*** A resemblance that takes less effort to make than the real thing does
- This /model/ railroad is mostly made of plastic.
- This miniature /models/ the 20-story building.
- This miniature /is a model of/ the 20-story building.
- A stick figure is a /model/ of a person/animal/being.
*** Intentional resemblance
- Some cartoon characters /are modeled after/ real people.
- The Abraham Lincoln statue /was modeled after/ Abraham Lincoln.
  (It means that the statue was intended to look like him.)
*** Fashion model, photo model, actor
- The /model/ sits on the chair so that the painters can begin painting.
- The /model/ wearing a fancy dress walks on the catwalk.
- The /model/ is posing for the camera.
- His dog is /modeling/ for a dog food advertisement.
*** What one strives to imitate
- He is a /role model/.
- He is a /model/ husband. He and his wife are much happier after their marriage.
*** Type, class, kind, variant, product line
- Ford /Model/ T and Tesla /Model/ S are cars.
- This Honda car comes in two /models/: an automatic transmission /model/ and a manual transmission /model/.
- Which /model/ of this Toyota car do you want to buy: the gasoline engine /model/ or the diesel engine /model/?
* Modeling is simplification.
Here we think of some examples where X is a model of Y.
We discuss about (1) how X simplifies Y (the "manner of simplification"), (2) what the simplifying assumptions are,
and (3) what nonsense happens when the assumptions are violated.

The following paragraphs follow this pattern: "X models Y, by /(manner of simplification)/, assuming /(simplifying assumptions)/".

The formula \(q \to r\) models the formula \((p\wedge q) \to r\), by grounding some variables, assuming that \(p\) is true.

The formula \(e^x \approx 1 + x + x^2/2\) models the formula \(e^x = \sum_{k=0}^\infty x^k/k!\), by truncating the series, assuming that \(x\) is near zero.

The statement "if I strike the match then it will burn" is a causal /model/ of how striking matches work in reality, by picking a small part of the modeled,
assuming that all matches are dry (and many other implicit simplifying assumptions we take for granted).

A fashion model models the average person, by hasty generalization, assuming that the average person has similar body measurements.
(Fallacies such as hasty generalization can be useful. Indeed a model is something /wrong but useful/.)
Violating this assumption makes the clothes misfit.

The tuple (john, 30 years old) models the tuple (john, 30 years old, black hair, brown eyes),
by projection (as in the geometric projection of a solid to its shadow),
assuming that the discarded aspects are irrelevant.
Modeling is dimension reduction.
Modeling is projection.

If we violate a simplifying assumption, the model breaks down and gives nonsensical results.
The name-age tuple (john, 10000 years old) models something nonexistent.
We can insert such nonsensical data into the database, but what does such nonsensical data mean?
We can substitute the mass variables in Newton's gravity equation with negative quantities, but what does it mean?

Our perception models reality, assuming that we stay in the environment that evolution and natural selection led us to.
We violate this assumption when we fly an aircraft.
This violation may kill us.
- https://en.wikipedia.org/wiki/Sensory_illusions_in_aviation
- https://www.scientificamerican.com/article/did-humans-evolve-to-see-things-as-they-really-are/
  - "Mimicry works only if there is an objective reality to mimic."
* Modeling by ignoring irrelevant information
"To model X" is to ignore the irrelevant aspects of X.

"X models Y" means "Y is X with some simplifying assumptions".

"X models Y" means "Y is X with some details lost".

Example of how model ignores irrelevant aspects.
Statics.
Real physical systems in rest.
Pick a coordinate system.
Center of mass of car.
Change car color.
The model is the same.
The reality is different.
The model ignores the irrelevant aspect that is the car's color.
* How we model things
We model a thing by making simplifying assumptions on that thing.
We choose which aspects to care about.
We ignore all other aspects.
Thus a model of something is a /simplification/ of that thing.

We judge models by their usefulness, not by their correctness.
** Modeling by partial evaluation (grounding of variables)
An example of how to model is partial evaluation (grounding of variables).
In this case, the model X is obtained from the modeled Y by partially evaluating Y, that is, by assuming the constancy of some variables in Y.
** TODO Capturing function?
We say any of these to mean the same thing:

- "The set X models the set Y with capturing function f."
- "The function f models Y with X."

The meaning is "There are subsets $X' \subseteq X$ and $Y' \subseteq Y$
such that $f : Y' \to X'$ is surjective."

The "capturing function" defines the aspects of reality that we capture in our model.
The function describes how X model Y.

Corollary: Every set models itself.
This is the theoretically correct but practically useless 1:1 map.

Here are some examples of "X models Y" to show the generality of that definition:

In software engineering, we can map Y (an employee) to X (a row in the database), but then we lose some irrelevant information about Y, such as hair color, weight.

In physics, we can map Y (a real physical system) to X (a Newton equation system) by assuming certain things (coordinate systems, point masses, absolute time),
but we can't map X to Y because in reality there are no point masses and time is relative.
By "Newton equation system", we mean a system of equations whose every equation looks like $F_k = m_k \cdot a_k$.

In geometry, we can map Y (a 3D vector) to X (a 2D vector).
Thus geometric projection is modeling.

In analysis, we can map Y (the exponential function) to X (a truncated Taylor series of the exponential function).
Thus approximation is modeling.

In real life, a writing is a model of its author.
What you think about X is your model of X.
Everyone models everyone they have ever encountered.
Our thoughts model reality.
Brain activity models reality.
Our thoughts of ourselves model ourselves.

Consider X = the set of all white cars and Y = the set of all cars.
Obviously X is a subset of Y.
X models Y.
** TODO Modeling (approximation) by truncation
** TODO Modeling by formula truncation
We truncate \( (p \wedge q) \to r \) to \( p \to r \), but not to \( p \), and not to \( r \).
We truncate \( p \wedge q \) to \( p \).
We truncate \( p \vee q \) to \( q \).
- \( M \) models \( M \wedge F \).
- \( M \) models \( M \vee F \).
- If \( M \) models \( R \), then \( M \to C \) models \( R \to C \).
** TODO Modeling by series truncation
This requires that the series converge.

* Fundamental learning by falsifying simplifying assumptions
We learn something fundamental by testing ("torturing") our models at their limits to break them.
We can find out a model's simplifying assumptions by pushing it to failure.
Fundamental learning happens at the boundary of a simplifying assumption,
that is, a situation where a simplifying assumption changes from true to false.
This is what experimental physicists do.

We learn about people when we anger them.
Other people's anger signals us that at least one of our simplifying assumptions about them doesn't hold.

An aircraft crash signals that a simplifying assumption, of someone, somewhere, is wrong.
* Generalizing the "model" in model theory?
Sentence S models sentence T iff S can be derived from T by grounding some variables.
The simplifying assumption is that assignment of variables to ground terms.
The simplifying assumption is an interpretation.

Examples.
"John ate a hamburger" is a model of "X ate Y".
"John ate a hamburger" is a model of "Someone ate something".

To /interpret/ a sentence is to /ground/ all its variables (to substitute all its variables with /ground terms/).

This generalizes model theory?
* We model things because our thought is limited
We /model/ a machine in order to /understand/ what it does:
to /interpret/ what it does, to give /meaning/ to what it does.
Of course what we /think/ it does is not what it /actually/ does.
We think the machine is adding two numbers.
What the machine actually does is shuffling electrons around in a way that we interpret as adding two numbers.
We model something so that we can reason about it.
We can only think about very few things at once.

We ignore hardware problems, such as unreliable power supplies, cosmic rays flipping bits,
cats pissing on the machine, fires burning down the building,
and other infinitely many hardware problems we conveniently ignore.
The simplifying assumption is that the hardware works in the environment it's designed for.
As long as our simplifying assumptions hold, our model is valid.

We need that model.
Without model, irrelevant details would preclude us from understanding anything.
* A model is ...
A model is ... resemblance, replica, downscaling, simplification?
We say "X models Y" iff X resembles Y, iff X behaves like Y, iff X is a simplification of Y, iff X and Y have something in common but X is simpler than Y?
A model of X is a simplified representation of X.
A model is a simplified description of reality?
A description of reality is not reality.
If reality and theory disagree, then reality wins and theory must change.
* Model and reality
- Some models model reality well.
- Some reality is modeled well.
- Some models are unrealistic.
- Some reality are unmodelable.
* Modeling: How does X model Y?
Consider several ways we can model a person:

- as a stick figure
- as a photograph
- as a police sketch
- as a tuple (row in a relational database)
- as a "chemical" that may react with another person ("chemical")

Reading list:

- 1980 Hilary Putnam article "Models and Reality" [[https://www.jstor.org/stable/2273415?seq=1#page_scan_tab_contents][paywall]]
- 2004 Ronald N. Giere article "How Models Are Used to Represent Reality" [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.433.860&rep=rep1&type=pdf][pdf]]
* "Model theory" should be named "structure theory" instead?
Group theory studies groups.
Number theory studies numbers.
Model theory studies structures!
What a surprise!
* Our "model" vs metamathematics model theory "model"
SEP's "Basic notions of model theory" is surprisingly readable. https://plato.stanford.edu/archives/fall2018/entries/model-theory/

Our definition of "model" includes the notion of "model" in model theory?

What is a "model" in model theory?
Here I try to paraphrase
the 2000 David Marker book "Introduction to Model Theory" [[http://library.msri.org/books/Book39/files/marker.pdf][pdf]]
and the 2000 Weiss--D'Mello book "Fundamentals of Model Theory" [[http://www.math.toronto.edu/weiss/model_theory.pdf][pdf]].
I may err.
My paraphrase:

- A /structure/ of a formal language $L$ is a pair $(A,I)$, where $A$ is a set called the /universe/,
  and $I$ is the structure's /interpretation function/.
  Such structure must also satisfy these:

  - Every constant symbol $c \in L$ maps to a universe element $I(c) \in A$.
  - Every relation symbol $R \in L$ maps to a relation $I(R) \subseteq A^n$, with the same arity $n$.
  - Every function symbol in $F \in L$ maps to a function $I(F) : A^n \to A$, with the same arity $n$.
    Note that a function of arity $n$ is a kind of relation with arity $n + 1$.
    See [[https://en.wikipedia.org/wiki/Arity][WP:Arity]].

- Structure $A$ /models/ sentence $\varphi$, written $A \models \varphi$, iff ... ?
- I think I forget something.
  Read Chapter 0 of the book.
  It has examples.

The codomain of the interpretation function $I : L \to J(A)$ is defined as follows.

- Every element of $A$ is also in $J(A)$.
- Every function $F : A^n \to A$ is also in $J(A)$, for every $n$ that makes sense.
- Every relation $R \subseteq A^n$ is also in $J(A)$, for every $n$ that makes sense.
  (This makes the previous bullet point redundant.)
- That's all.

In other words:
$$
J(A) = A + 2^{A^0} + 2^{A^1} + \ldots + 2^{A^n} + \ldots
$$

I think $J(A)$ is related to a Herbrand universe, but how?

The structure $S = (A,I)$ maps the language $L$ to $J(A)$.
* TODO Questions we want to answer
- How does X model Y?
- How do we measure how good a model is?
- How do we formalize all that?
- How does it relate to model theory?
* Measuring model quality: How well does X model Y?
- [[https://en.wikipedia.org/wiki/All_models_are_wrong]["All models are wrong, but some are useful."]], George Edward Pelham Box (1919--2013)
- In [[http://chem.tufts.edu/answersinscience/relativityofwrong.htm][The Relativity of Wrong]], Isaac Asimov writes

  - Asimov's relativity of wrong:

    - Both round earth theory and flat earth theory are wrong,
    - but believing that they are equally wrong is wronger than both of them combined.

- https://en.wikipedia.org/wiki/The_Relativity_of_Wrong
- https://en.wikipedia.org/wiki/Wronger_than_wrong
- 2003 article "Measuring the Quality of Data Models: An Empirical Evaluation of the Use of Quality Metrics in Practice" [[https://pdfs.semanticscholar.org/0536/3b8ddecd695444dc9b341796a0dc73e606be.pdf][pdf]]
- [[http://tdan.com/measuring-the-quality-of-models/4877][Measuring the Quality of Models | TDAN.com]]
* Model of model: multiple-level machine model
A model can model another model.
We can stack simplifying assumptions on top of other simplifying assumptions.

A mechanical machine is modeled by a system of equations derived from Newton's motion laws.

We can model an abacus ...

Suppose that we have a mechanical calculator that adds two 3-digit numbers.
Suppose that we have an electronic calculator that also adds two 3-digit numbers.
Then /the same model/ models both the mechanical calculator and the electronic calculator.

An electrical machine is called a "circuit".

First, we can model a circuit as its /lumped element model/.
This model is a system of equations derived from Kirchhoff's circuit laws.
This model is only valid under the conditions described in [[https://en.wikipedia.org/wiki/Lumped_element_model#Lumped_matter_discipline][WP:Lumped matter discipline]].

A /switch/ S is modeled as a /lumped component/ S1 with one binary state (open/closed) and two terminals (S1A and S1B).

Second, we can model the lumped element model S1 further as Boolean algebra equation.
The switch model S1 is then modeled again as a /Boolean-algebra equation/ S2: S1A = S1B.

An electrical logic /circuit/ is modeled as a /system/ of Boolean-algebra equations.

An electrical logic circuit /component/ is modeled as an /equation/ in Boolean-algebra.

An electrical logic circuit /node/ is modeled as a /variable/ that holds either 0 or 1.

A computing machine is called a "computer".

A computer is modeled by... not a system of equations?

Claude Shannon's 1937 master thesis.
Who retyped this neat version?
https://www.cs.virginia.edu/~evans/greatworks/shannon38.pdf
- About Claude Shannon's 1937 master thesis https://en.wikipedia.org/wiki/Claude_Shannon#Logic_circuits
* Complexity?
Here we try to understand complexity from its etymology.
The following etymology is according to the Wiktionary entries on [[https://en.wiktionary.org/wiki/simple#Etymology][simple]], [[https://en.wiktionary.org/wiki/complex#Etymology][complex]], [[https://en.wiktionary.org/wiki/plico#Etymology_2][plico]], [[https://en.wiktionary.org/wiki/plecto#Etymology_1][plecto]], [[https://en.wiktionary.org/wiki/complicate#Etymology][complicate]], [[https://en.wiktionary.org/wiki/complect#Etymology][complect]].

"Simple" comes from Latin "simplex" (one-fold), from "sim-" (same) and "plicare" (to fold, to bend),
comparable with "multiple" (many-fold), "uniplex" (one-fold), "duplex" (two-fold), "triplex" (three-fold), and so on.
"Complex" comes from Latin "com-" (together) and "plectere" (to weave, to braid, to twist), comparable with "complect", "complicate".
"Plicare" and "plectere" both come from a Proto-Indo-European word meaning "to fold, to weave".
(I omit this PIE word because I don't know how to type it in XeLaTeX; copying doesn't work.)

Thus "simple" means "one-fold" and "complex" means "woven together".

Here we try to understand complexity by an example of paper folding.

Imagine a sheet of paper.
Fold it several times.

The /complexity/ of the resulting shape is the number of folds, that is how many times the original sheet is folded.
The shape with zero complexity is the original sheet of paper before any folding.

A shape's complexity is unique and irreducible.
An \(n\)-fold shape can only be made by folding exactly \(n\) times, no less and no more, if we assume that papers don't crease when folded.

A fold affects all folds after it.
The folding order matters.
The folds usually don't commute.

A fold always adds complexity.
There is no way to unfold a folded paper by folding it.
A combination of folds will never be equal to an unfold.

See also the [[https://en.wikipedia.org/wiki/Origami][Wikipedia entry on origami]] (paper folding).

Folding /complicates/ the shape.
Unfolding /simplifies/ the shape.

We can /simplify/ a shape by removing its last folds.
Suppose that a shape is a folding sequence (a sequence of folds).
Then shape X is a /simplification/ of shape Y iff the folding sequence X begins (is a prefix of) the folding sequence Y.
