#+TITLE: Music Research Group
#+DATE: 2016-03-27 14:14:08 +0700
#+PERMALINK: /music.html
* What
** What do I think about music?
I have a love-hate relationship with music.
Music wastes time, but as I distance myself from it, something always tempts me to come back.

Kids should learn art to stimulate the brain, but they should not grow up to be artists.
They should grow up to be mathematicians/scientists/engineers who know some art.
** How should we compose music?
Begin with form.

If there is lyrics, then begin with lyrics, and pay attention to syllable patterns (their counts and stresses).
** What can be done with what?
See J.S. Bach, Chaconne from Partita no. 2, BWV 1004.
See F. Mendelssohn, Violin Concerto; the ricochets.
See N. Paganini, Caprice no. 24.

What can be done with one cello?
See J.S. Bach, Prelude from Cello Suite no. 1, BWV 1007.

What can be done with chords?
See S. Rachmaninoff, Prelude in C# minor; Prelude in G minor; Piano Concerto no. 3.

What can be done with the black keys of a piano?
See F. Chopin, "Black Keys" Etude.
* Composing for middle school string orchestra festivals
** The composition should have between 5 and 9 instrument sections
A middle school string orchestra is usually divided into 5 sections: violin 1, violin 2, viola, cello, and bass.
But perhaps it should be divided into 9 sections:
violin solo, violin 1, violin 2, viola solo, viola, cello solo, cello, bass solo, and bass.
This addresses the ability differences.
Make the piece fun for the incompetent players and challenging for the competent players.
It's like writing a quadruple concerto.
It's like writing a piece for a great string quintet and a so-so orchestra.
A festival string orchestra is basically a great string quintet accompanied by a so-so orchestra.
** The composition should be at least 4 minute long
I composed a song that lasts below 2 minutes, and I definitely felt that it was too short.

Write the solo parts first.
Then write the bass part.
The write the middle voices.
Unless you are writing a counterpoint.

Stick to fun singable cool pop-ish simple tonal music, but not over-simplified.
These kids get bored super quickly, and they can't even play chords with correct intonation.
** The composition form should be ritornello or sonata
Interesting, memorable, learnable, some repetition but not boring.

Ritornello is A B1 A B2 A B3 ... A Bn ...
That is, the music keeps "returning" to A.

We can put solos/cadenzas in B sections.
** The kids should be taught how to read the conductor
The conductor must learn how to conduct, but the kids must also learn how to read the conductor.

The kid has to be taught about preparatory upbeats.
** Tempo: Fingerboard hand max 300 npm, bowing hand max 480 npm
Cellos are too big for the kids' hands.
Don't write fast runs for middle school cellos.

The fingerboard hand should not have to play faster than 300 notes per minute.
Thus, maximum tempo for the fingerboard hand is 360 bpm if shortest note is 1/4th note,
180 bpm if shortest note is 1/8th note,
90 bpm if shortest note is 1/16th note.

The bowing hand should not have to move faster than 480 notes per minute.
Thus, maximum tempo for the bowing hand is 480 bpm if shortest note is 1/4th note,
240 bpm if shortest note is 1/8th note,
120 bpm if shortest note is 1/16th note.
** What I learn from my mistakes
Don't require violin 2 to be the loudest part.
Teachers seem to have instilled into the kids that they should never play louder than violin 1.

Do not assume that the conductor can conduct big tempo changes.
Do not assume that the conductor can conduct stringendo.
** Middle school string orchestra sounds muddy because the instruments are too big for the kids' hands
Intonation is destroyed.

In a middle school string orchestra, the kids' hands are big enough for violin and viola, but not cello and bass.
The kid cellists and bassists' hands are jumping around the fingerboard.

Middle school cellists.
The left hand can't be too agile.
The right hand should compensate so that the part is not too boring.
That is the key to writing middle school cello and bass part.
* Teaching kids orchestra?
** Segregate the great, good, bad, and shitty kids
A class is only as good as the worst kid in the class.
Fire the shitty kids that cause the unfixable ability difference in your class.
Don't let the shitty kids hold back your class from achieving greatness.

I classify a kid into four classes: great, good, bad, and shitty.

Great kids.
Give them solos.
Let them shine.
Give them challenges.

Good kids.
They are internally motivated.
Good kids can become great kids with correct practice.

Bad kids.
Incompetent but not malicious.
Bad kids can become good kids through practice, discipline, dedication, effort, time, and sacrifices.
Bad kids have good intentions, but they aren't fit yet for festivals.

Shitty kids will never improve.
Lazy, indifferent, unwilling.
Fire them immediately.
If that is impossible, limit the damage done by these shitty kids.
Obviously, these shitty kids should never play at festivals.
These shitty kids should not be in your class in the first place.
Talk to their parents to move those shitty kids to someone else's class that is not a music class.
These kids are not born to play music.
They may shine and be great kids somewhere else.
Don't let them rot in your class.
Don't waste your time and their time.

** The kids should be taught how to synchronize by skipping notes
If you make a mistake or fall behind, then you should immediately synchronize, skip notes.

** The kids should be taught to pretend that they are metronomes
They should have an internal rhythm and internal counter.
They should internally subdivide the beats.

They rush when playing difficult passages.
This can only be solved by building internal metronome and doing slow practice.

** Cellos are tricky
This is about the average kid cellist.

These kid cellists have bad intonation and use vibrato too much.
Vibrato will not fix intonation problem.
If you place your finger at the wrong point, you need to /relocate/ your hand;
/wiggling/ your hand will not fix the intonation.

A cello section with 9 great kids and 1 shitty kid is a shitty cello section.
It will sound muddy.

Bass is even trickier.
** The kids should be taught to strike a note with conviction and commitment
Kids are full of self-doubt and bad habits.
Those must be undone.
** The kids must be taught proper tone production
The contact point must not wander.
** Make kids watch a real violinist, and tell them to pretend that they are that violinist
Hilary Hahn, Mendelssohn's violin concerto

Itzhak Perlman

and other great violinists

Tell the kids to expressively move their body.
The kids should not rigidly stay in a position for too long.
Otherwise they will get muscle pains.

These motions are /not/ for showing off, but for preventing muscle stiffness and pain.
** The kids must be able to change tempo and dynamics independently
Don't get quieter when getting slower, unless the music demands it.

Don't get louder when getting faster, unless the music demands it.

To be able to improve, the kids must realize two things.
First, they are shitty.
Second, they /can/ get out of that shittiness, but it is entirely up to them.
If they get better, it is because they work.

Learning speed = teacher quality * student quality * student effort

If student effort is zero, everything else does not matter.
Zero times anything is zero.
** The kids must be taught how to learn and how to practice
Most kids practice by mindless repetition.
It is just a waste of time.
** The kids must unconsciously do inverse kinematics
Training the kids is asking the kids to internalize inverse kinematics[fn::https://en.wikipedia.org/wiki/Inverse_kinematics].

I don't care how you play.
I want good sound.

These principles may help us achieve a good sound.
- The bow must move straightly, must always form a right angle to the string. The point of contact must not wander.
- You should not hurt yourself. Playing for 2 hours should not cause pain or stiffness.
  If you hurt yourself, you are using the wrong muscles.

Human anatomy + straight-line bowing = the entire body has to move, primarily the arms, shoulders, and hip.

Beginners tend to lock their wrists.
** The kids must be taught fundamental musicianship
The students must be able to sing with correct intonation and clap with correct rhythm, regardless of whatever instrument they play.

The students must first hear it in their heads, and only then try to sing or play it.

The students must never think that fingerboard labels will save them.

The kids must be taught about /music/, not /musical instrument/.
* What?
- Selected music
- [[file:mussoft.html][Music software]]
- [[file:musbus.html][Music business]]
- Problems with music in Indonesia

  - Indoor smoking

    - Still happens in 2018 in Jakarta, despite the ban of smoking in public places

  - Piracy

- Is music a language?

  - People often say "Music is a language." without knowing some linguistics.

    - A language must have /syntax/ and /semantics/.

      - How do you say in music: "I'm writing a wiki."?

  - What is its syntax?

    - [[https://en.wikipedia.org/wiki/Musical_syntax][WP: Musical syntax]]

  - What is its semantics?

- [[https://www.youtube.com/watch?v=wHp9kQdPLuE][How to Write a Theme]]
- [[https://www.youtube.com/watch?v=hPvAqyDd1aI][How to Sound Like Bach (Happy Birthday)]]
- [[https://www.youtube.com/watch?v=RhXnff1daXk][pro vs beginner cellist]]

  - beginner is stiff, pro makes minimal movements

    - distal interphalangal joint of left hand

      - beginner collapses
      - pro doesn't
      - https://en.wikipedia.org/wiki/Phalanx_bone
      - https://en.wikipedia.org/wiki/Interphalangeal_joints_of_the_hand

  - holding the cello

    - pro: the cello doesn't move around
    - beginner: the cello sometimes sways

  - right-hand wrist, bowing

- For writing string chorus effect: [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4196478/][Perception of string quartet synchronization]]
- All Honors Jakarta Orchestra
- IOEF indonesia orchestra ensemble festival
- What kind of music that the students enjoy practicing?
- What is Café del Mar?

  - It seems to be a source of chillout musics and Ibiza Balearic beats and other electronic dance musics?

- [[https://etd.ohiolink.edu/rws_etd/document/get/bgsu1242663220/inline]["A case study of an award winning public school string orchestra program", Wing Man Fu, graduate thesis]]
- http://www.aaronbonneau.com/7-things-japanese-music-does-better/
- [[https://www.youtube.com/watch?v=B5FaG6dgAxc][Where Nokia's Ringtone Originally Came From]]

  - Francisco Tárrega's "Gran Vals"

- [[https://en.wikipedia.org/wiki/Chekhov%27s_gun][WP:Chekhov's gun]] applied to orchestration

  - If you ask for an instrument, you have to use it.

    - If it doesn't contribute meaningfully to the music, it's better left out.

- The more person is in a band, the less everyone works.

  - Also, more scheduling difficulties.
  - The ideal band size is less than 5 people?

- http://www.hopefulcases.org/

  - https://www.reddit.com/r/MadeMeSmile/comments/8fjd1u/on_my_hellish_nyc_commute/

- music composition / sound design method; imitate language tone/contour

  - [[https://www.youtube.com/watch?v=1sqg63imHx0]["How I composed the Windows 10 calendar alert" - YouTube]]
* My musical background, if anybody cares
Erik Dominikus was born in 1989 in Jakarta, Indonesia.

In 2001-2007 he studied classical music under Mr Hans (Han-Sin) Huang B.Mus.

In 2005 he took a Javanese gamelan class in SMA Regina Pacis Jakarta.

In 2006 he passed the ABRSM Grade 8 Piano examination.

In 2007 he passed the ABRSM Grade 6 Theory examination.

In 2011 he obtained his Bachelor of Computer Science degree from the Faculty of Computer Science, Universitas Indonesia.

In 2012 he learned to play some jazz music from a local community (Margo Friday Jazz) and the Internet.

In 2016-2017 he arranged some songs for an orchestra in his parish (Catholic Church of St Andrew, Jakarta), and composed some songs for the theater in that parish.
* Notes for the conductor of "Short karawitan for string orchestra"
** Some background about karawitan and gamelan
*** What is karawitan and gamelan?
Gamelan is a set of instruments.
Karawitan is the activity of playing gamelan.
*** What is the difference between Javanese, Balinese, and Sundanese karawitan?
Balinese karawitan sounds more dynamic, more loud, more fast, more bright, more active, more festive, and more dazzling than Javanese karawitan.
Balinese karawitan has extreme dynamic changes.
Javanese karawitan has extreme tempo changes, but never exceeds Balinese karawitan tempo.
Balinese gamelan has slightly detuned pairs.
Those who don't like karawitan may find Javanese karawitan boring and Balinese karawitan nauseating.
*** I have little karawitan experience
I participated a little in Javanese karawitan.
I saw live Balinese karawitan once in Bali.
I don't know anything about Sundanese karawitan.
Thus I write the piece with mostly Javanese and some Balinese karawitan in mind.

Gamelan has several tunings, but none is 12-tone.
I approximate the tuning with Western pentatonic 1-3-4-5-7, although only in the melody.
** Emulating a metallophone with a string
Accent each note.
No legato, but no staccato.
No vibrato.
Spiccato is OK.

Longer notes have more sustain than higher notes.
However, all notes decay.

The goal is to sound similar to this video[fn::https://www.youtube.com/watch?v=sZZTfu4jWcI].
** Emulating a sindhén (female singer)
Vibrato is OK.

A Javanese sindhén does these /less/ than a Western opera singer does: vowel-rounding and larynx-dropping.
The Javanese karawitan vowels are sharper than the Western opera vowels.
** Tempo
The fast tempo must be about twice of the slow tempo.
The acceptable fast tempo is 108 to 120 bpm; 96 bpm is definitely too slow; 120 bpm is almost too fast; 132 bpm is definitely too fast.
The acceptable slow tempo is 48 to 60 bpm; 60 bpm is a bit too fast.
These tempo changes are extreme in Western music, but normal in Javanese karawitan.

Update <2019-01-22>:
Change tempo from 120/60 to 108/54 bpm.
Kick dynamics up a notch.
* What
** Composing for beginners
Matthew Hindson:
Fast music is easier than slow music
because beginners can't produce good long tone.[fn::http://hindson.com.au/info/writing-for-school-and-amateur-orchestras-2006-toan-conference-presentation/]
** How should we subdivide beats?
Subdivide each beat into 2: TOOK-tuck (TUK-tak).

Subdivide each beat into 4: TOOK-uh-tuck-uh (TUK-ke-tak-ke).
