#+TITLE: Catchment area
#+DATE: 2018-09-10 03:56 +0700
#+PERMALINK: /other0.html
This file is for my capture-refile workflow.
* <2018-09-11> Microeconomics
An economy consists of actors.

- No economic actor has complete view of the economy.
  Every actor can only see his suppliers and consumers.
- Every actor responds only to what immediately affects it: its direct suppliers and consumers.
- Actors need time to respond to change in demand/supply.
- Some actors maintain buffers/inventories.
- Some actors get involved in futures.

Hypotheses:

- Shocks ripple through actors.
- Demand collapse may waste inventory.

Statistics can give us an accurate picture of the economy.
Random sampling of actors.
* TODO <2018-09-15> Fix possible programming error in ~/work/web in Iterables.filter
* TODO <2018-09-15> Modernize operating system
Back up data.
Should not take more than a day.
** TODO <2018-09-15> Install Ubuntu 18.04 after its point release
Ubuntu 14.04 EOL is April 2019.
* TODO <2018-09-15> Make an Emacs Lisp interpreter in Haskell for Yi editor
