#+TITLE: A mess
#+DATE: 2016-03-22 21:44 +0700
#+PERMALINK: /other.html
#+OPTIONS: ^:nil toc:nil
#+TOC: headlines 1
* The purposes of this page
- This page is a holding area for my capture-refile workflow.
- This page is for recycling old content.
* Reorganize this mess
This was moved from research.html.
** Resolving citations?
To resolve citation keys in this website, look up the key in [[https://github.com/edom/edom.github.io/blob/master/bibliography.yaml][bibliography.yaml]].

<2019-01-02>
We are moving back to bib.bib from bibliography.yaml,
so that we can copy-paste bib from Google Scholar.
*** Ramblings and undigested matters
   :PROPERTIES:
   :CUSTOM_ID: ramblings-and-undigested-matters
   :END:

- Linguistics

  - How do we use language?

    - We assume:

      - Every adjective is fuzzy.
      - Truth is a continuum.

- Corruptors and their offsprings have so much money that they don't know what to do with it.
- 2017-07-10

  - Ubuntu crashed without log.

    - Screen turned off suddenly.
    - Keyboard forze.
    - Power button didn't respond even after 4 seconds.
    - The problem turned out to be shitty graphics card connection.

      - Hardware problem, not Ubuntu problem.
      - Probably dust or oxidized connectors.

        - It would be nice if graphics card could be hotswapped though.

          - But do we want to touch a running graphics card?

    - The fix: unplug and plug the card several times.

- How do I find people who care about what I care?
- How do I find people with interests similar to mine?
- How to make money

  - Make hard things easy.

- Should we use holidays to form strategic alliances?
- To form quality relationship, socialize with one person at a time?
- There are only two way of getting rich:

  - create value (make others better)
  - extract value (steal from others, either legally or illegally)

- [[https://stackoverflow.com/questions/9466360/how-to-request-google-to-re-crawl-my-website][SO 9466360: How to request Google to re-crawl my website?]]
- Marketing

  - To market something is to try to sell it.

- [[https://www.youtube.com/watch?v=yzl7oX9FYGE][YT: What I've learned: Everything wrong with the "System" (Educate yourself)]]
- https://id.wikipedia.org/wiki/Ken_Kawan_Soetanto

  - Any English publications? Where?

- http://therumpus.net/2012/11/the-map-of-the-system-of-human-knowledge-by-james-tadd-adcox/
- https://www.theatlantic.com/magazine/archive/2006/08/a-taxonomy-of-knowledge/305189/
- [[https://en.wikipedia.org/wiki/Joy%27s_law_(management)][WP:Joy's law of management]]:
  "no matter who you are, most of the smartest people work for someone else"

** Applying probability theory and statistics to marketing and pricing

- https://medium.com/airbnb-engineering/learning-market-dynamics-for-optimal-pricing-97cffbcc53e3
- https://overflow.buffer.com/2018/08/13/predicting-churn/

** Philosophy

*** First- vs third-person view?

- [[http://consc.net/notes/first-third.html][The First-Person and Third-Person Views]]

*** Ethics, morality
Utilitarianism is questionable.
 [fn::https://rationaloptimist.wordpress.com/2014/05/24/utilitarianism-is-killing-one-to-save-five-moral/]
 [fn::http://blog.practicalethics.ox.ac.uk/2014/11/why-i-am-not-a-utilitarian/]

Jonathan Haidt:
- Blind pursuit of Equal OUTCOME leads to an "Abomination of Justice".[fn::https://www.youtube.com/watch?v=cQNaT52QYYA]
- The moral roots of liberals and conservatives[fn::https://www.youtube.com/watch?v=vs41JrnGaxc]
- ? https://www.yourmorals.org/aboutus.php
- ? https://www.moralfoundations.org/
*** Evolutionary ethics
- https://en.wikipedia.org/wiki/Evolution_of_morality
- https://en.wikipedia.org/wiki/Evolutionary_ethics
- Evolutionary ethics
    - Morality is shaped by evolution.
    - We have difficulties defining what is "good", but there are things that we agree are good.
    - Morality is defined by the majority opinion.
    - Humans evolved morality because morality promotes survival.
        - Nature selects moral behavior. There is evolutionary pressure for moral behavior.
            - Sharing foods promotes survival.
            - Sharing knowledge promotes survival.
            - Cooperation promotes survival.
            - Marriage promotes survival?
            - Monogamy promotes survival?
    - The morality of a species is whatever evolved behavior that promotes its survival.
** TED?
- [[https://www.youtube.com/watch?v=fxbCHn6gE3U][The surprising habits of original thinkers | Adam Grant]]
- [[https://www.youtube.com/watch?v=YM-uykVfq_E][TED-Ed: What is entropy? - Jeff Phillips]]
- [[https://www.youtube.com/watch?v=PRYmx7Lk9F0][This Quantum 'Sixth Sense' Could Allow Birds to Navigate Earth's Magnetic Field]]
- [[https://www.youtube.com/watch?v=YnY0J_Z1TF4][The Earth Is Running Out of Sand and It Could Cause a Global Crisis]]
* Philosophy?
** Pragmatic ontology: how pragmatism can help us answer what something is
(Is this really what others mean by "pragmatic ontology"?)

To the pragmatic ontologist, "exist" means "practically exist".

Someone who subscribes to egocentric pragmatic ontology would take the question "What is X?" to mean "What can I use X for? / How can I use X?"

- I can use it, therefore it exists. (Compare: Descartes's "I think, therefore I exist.")
- It affects me, therefore it exists.
** Gaining information by losing data?
(Do I understand what I'm talking about?)

It is possible to gain information while losing data.
We often gain information when we feed data to an irreversible function.
Example:
- array_length
- statistical summarization and interpretation
- modeling
But is that losing data?

Most interesting mappings are irreversible.
Modeling is irreversible mapping.
** Dying in the 21st century
- Inheriting digital data
  - What to do with your data when you die?
  - https://www.businessinsider.sg/how-to-give-google-account-to-trusted-person-when-you-die-2018-8/
- Do we have to die?
  Can technology save us?
  Will we reach immortality in this century?
** Sloppy synecdoches: Is a "potato" a plant or a tuber?
A bean is a plant.

Let B be an individual, a bean plant.

Every individual of the species Solanum tuberosum is a plant.

Wrong: Potato is a plant => Every potato is a plant => forall x. potato(x) => plant(x)
A potato plant is a plant.
A potato is not a plant; a potato is a tuber.
Potato the whole plant vs potato the edible tuber.

Of course we can dismiss all this and just be sloppy with synecdoches,
but unclear language breeds unclear thinking.
* Hiring
** If you are going to hire me
- No work for hire.
  I own all my work.
  No exceptions.
  Work-for-hire is legal exploitation.
  However, I'm open to licensing negotiations.
- I don't care about deadlines.
  It's done when I think it's done.
  I don't care about the short-term.
  I don't have a good relationship with time.
- I do what I want how I want, unless there is a reason not to.
- I won't use any language less than Prolog.
  I'm not settling for anything less.
  I insist on using the best tool I know.
  If someday I find a better tool than Prolog, I will move again.
- I only make sure that my software runs on a recent Debian release.
  I don't care if my software doesn't run on Windows, Android, or iOS.
- I will not sign any anti-competitive agreements.
  I will not sign non-compete agreements.
  I will not sign non-disclosure agreements.
- I can change my mind at any time.

Perhaps I should hire you, not the other way around?
*** Why work for/with me? How am I from other partners/employers?
- Justice
- Fairness
- Environment
- Reasonable

Really?
Am I still the same person when I wrote that?
*** Why not work for/with me?
- I can't guarantee that you will get rich working for/with me.
- I am opinionated and principled. I do things my way.
- I am a dictator, although I try to be benevolent.
*** Principles?
- Survive.
- Sustain: minimize operation and minimize maintenance.
- Systems, not heroes.
  - But we need heroes?
** My company rules? My business rules?
All compensations must be explicit, rule-based, and justifiable.
Everyone must know the same rules.
Everyone must play by the same rules.
No tipping.

- Employer may terminate an employment at any time without notice.
- Employee may terminate his/her employment at any time without notice.
- Pay with money only.
  No bullshit perks and benefits.
  No insurance.

Refuse and skip exit interview.
Don't say anything incriminating.

"Ask the Headhunter: Why it’s risky to give notice when you quit"
https://www.youtube.com/watch?v=sBFjotmUkjA

https://www.forbes.com/sites/lizryan/2017/07/06/ten-reasons-to-skip-your-exit-interview/#5b51301e20e3

my accounting principles?

- Keep only one book.
  Don't show different books to different people.
- Accounting records historical truth.
  Don't calculate current market price in accounting reports; mark-to-market belongs in financial statements, not accounting books.
- Don't mix currencies.
- A redenominated currency is a different currency.
- Err on the side of safety.
  Don't count your eggs before they hatch.
  Recognize income as late as possible.
  Recognize expenses as early as possible.

A company with no secrets.
A transparent company.

An economic benevolent dictatorship.

Dictatorship doesn't last.
Systems last.
** Job openings and projects
*** Job openings
**** Assistant/clone
Requirements:
- Fluent in written English.
- Enjoys the stress of writing.
- Writes concisely.
- Writes precisely; cares about definitions.
- Writes conservatively; cares about etymologies.
- Reads 800 wpm with 60% comprehension when focused at prime condition.
- Likes to stay at home, and hates traveling.
- Connected to the Internet from home.
- Has an IQ above 135.
- Able and willing to eat pork.
- Uses Debian or a Debian-based distro.
- Can use Google Docs, Git, Markdown, and Org-Mode.
- Watches YouTube videos at 2x speed.

What you will do:
- Organize and clean up this website.
- Arrange my derailed train of thoughts.
- Write about things similar to what is already on this website.
- Find evidences for or against my beliefs.

Salary range:
IDR 0 - IDR 20,000,000.
* Delete?
** "English" names
Scarface, Boaty McBoatface
Sir Lancelot, Sir Chirpsalot (chirps a lot), Sir Changealot (change a lot)
** Things I learned the hard way
*** <2018-10-08> While a person is on a motorcycle (be it driving or not driving), he must secure his chattels, and not place them in shirt pockets, in order to prevent the chattels from falling to the road (therefore being lost or broken).
- Secure the chattels:
  - Put it in a /totally closed compartment/ in a bag, not in a pocket on the bag.
  - Grip the chattels.
- Triggers:
  - Eyeglasses fell from shirt pocket to the road, and were run over by the motorcycle behind.
  - A few months ago, a hairband fell from bag pocket to the road; it was lost.
  - Shit happened. Twice.
** Finding bottleneck?
*** what
Make sure that the bottleneck is not in the kernel
netstat | grep
Check the number of connections
Expected jmeter number of connections

Make sure that jmeter is properly configured

https://stackoverflow.com/questions/42311414/iperf3-windows-bandwidth-is-much-slower-than-linux
iperf
sudo apt-get install iperf
Run this on PHP machine: iperf -s
Let SERVER be the IP address of the PHP machine.
Run this on JMeter machine: iperf -c SERVER

CPU tidak mentok, RAM tidak mentok, berarti ada beberapa kemungkinan:
- bottleneck di network,
- CPU di-throttle oleh docker/cgroup,
- bottleneck di disk seek rate (unnecessary SQL transaction),
- bottleneck di disk transfer rate.

If 1 request takes 1 KB, then 10000 request/second translates to 10 MB/s, which is enough to saturate a 100 Mbps Ethernet interface.

Cari tahu 1 application server sanggup serve berapa banyak.

Check
iftop -i INTERFACE

https://serverfault.com/questions/299093/linux-how-to-find-out-whether-nic-is-causing-a-bottleneck

check disk queue depth dengan top (average load)
iotop

https://serverfault.com/questions/665799/whats-the-technique-to-find-out-bottleneck/665831
- atop for cpu & ram
- iotop for disk
- iftop for network

Disable swap, but be careful to avoid running out of memory.

Pastikan bottleneck bukan di mesin JMeter (terutama di network interface-nya). Apakah mesin JMeter sudah dipisah dari mesin PHP?

Linux kernel limit: number of open files, maximum number of open sockets.

Docker bisa mengurangi performance. Kalau tidak pakai Docker, apa bisa lebih cepat?
Ganti 20 docker instance php-fpm dengan 1 php-fpm dengan 20 children.

Docker performance cost
2015 article "An Updated Performance Comparison of Virtual Machines and Linux Containers" https://domino.research.ibm.com/library/cyberdig.nsf/papers/0929052195DD819C85257D2300681E7B/$File/rc25482.pdf
That link was obtained from https://www.linode.com/docs/applications/containers/when-and-why-to-use-docker/#when-not-to-use-docker

nload is an alternative to iftop?


Use Vegeta instead of ApacheBench?
Locust? JMeter?
https://medium.freecodecamp.org/how-we-fine-tuned-haproxy-to-achieve-2-000-000-concurrent-ssl-connections-d017e61a4d27


select vs poll vs epoll
https://www.ulduzsoft.com/2014/01/select-poll-epoll-practical-difference-for-system-architects/

The C10K (10000 connection) problem
http://www.kegel.com/c10k.html


https://stackoverflow.com/questions/16888429/how-to-make-a-hard-abortive-close-on-a-tcp-connection
In bottleneck/tcp.c
Set linger onoff 1 timeout 0


http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html

https://thehftguy.com/2016/10/03/haproxy-vs-nginx-why-you-should-never-use-nginx-for-load-balancing/
*** Measuring things to find bottlenecks (Linux, TCP, HTTP, network, CPU, disk, etc.)
- How many empty TCP connections per second can a TCP endpoint accept?
  We don't want to measure transfer rate.
  We want to measure kernel bookkeeping overhead.
  - These can't do that:
    - iperf
  - Can these do that?
    - https://txlab.wordpress.com/2016/05/05/tcpkali-tcp-load-generator/
    - http://uperf.org/
    - qperf (ubuntu?)
      - https://www.opsdash.com/blog/network-performance-linux.html
      - https://access.redhat.com/solutions/2122681
- How many HTTP requests can it handle? Use ApacheBench. =sudo apt-get install apache2-utils=.
- How do we reduce the worst-case response time under high load?
- Is the Linux process scheduler fair?
- Is the Linux process scheduler time complexity O(1)?
- https://medium.com/@oscar.eriks/case-study-network-bottlenecks-on-a-linux-server-part-2-the-kernel-88cf614aae70
- Which is better, select or epoll?
**** Linux TCP TIME_WAIT exhaustion on busy server
- What are my options?
  - Assign more IP addresses.
  - Geographically distribute the application.
    Procure edge servers closer to the clients.
    But you can't do this if you are not a CDN or ISP.
  - Reduce the TIME_WAIT MSL (maximum segment lifetime)
    - http://www.lognormal.com/blog/2012/09/27/linux-tcpip-tuning/
    - This makes TCP incorrect, but in the case of a load balancer, the probability of the incorrectness is negligible (unless it's an attack, or it's behind a NAT).
    - =net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait = 1=
  - Non-options
    - =net.ipv4.tcp_tw_recycle= has been removed.
    - =net.ipv4.tcp_tw_reuse= doesn't work.
  - https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux
    - https://news.ycombinator.com/item?id=7684015
    - "The universal solution is to /increase the number of possible quadruplets/ by using, for example, more server ports."
    - "Moreover, when designing protocols, /don’t let clients close first/."
- See the TCP protocol documentation.
  Where are the wait states?
  Who hold the wait states?
  The client?
  The server?
  The one who calls the =close= system call?
** Maximizing lithium-ion battery life
- https://batteryuniversity.com/learn/article/how_to_prolong_lithium_based_batteries
  - "Exposing the battery to high temperature and dwelling in a full state-of-charge for an extended time can be more stressful than cycling."
  - "In terms of longevity, the optimal charge voltage is 3.92V/cell."
  - "Every 70mV drop in charge voltage lowers the usable capacity by about 10%."
  - "Partial charging negates the benefit of Li-ion in terms of high specific energy."
  - "Chalmers University of Technology, Sweden, reports that using a reduced charge level of 50% SOC increases the lifetime expectancy of the vehicle Li-ion battery by 44–130%."
  - "For safety reasons, many lithium-ions cannot exceed 4.20V/cell."
  - "Industrial devices, such as the EV, typically limit the charge to 85% and discharge to 25% to prolong battery life."
    - "Why Mobile Phone Batteries do not last as long as an EV Battery" https://batteryuniversity.com/index.php/learn/article/why_mobile_phone_batteries_do_not_last_as_long_as_an_ev_battery
  - "The question is asked, “Should I disconnect my laptop from the power grid when not in use?”
    Under normal circumstances this should not be necessary because charging stops when the Li-ion battery is full.
    A topping charge is only applied when the battery voltage drops to a certain level.
    Most users do not remove the AC power, and this practice is safe."
    - "Always keep the airflow unobstructed when running electric devices with air-cooling on a bed or pillow."
** Natural sciences
- Physics and engineering
  - Civil engineering
    - [How Do Sinkholes Form?](https://www.youtube.com/watch?v=e-DVIQPqS8E)
      - Internal erosion, piping, etc.
    - [YT:Why Concrete Needs Reinforcement](https://www.youtube.com/watch?v=cZINeaDjisY)
      - three types of stresses: tensile, compressive, shear
    - [What's inside Ikea's "wood"?](https://www.youtube.com/watch?v=24F5JlKkxR4)
    - Architecture
      - [YT:Open office is overrated](https://www.youtube.com/watch?v=-p6WWRarjNs)
    - Softwood vs hardwood
      - Softwood is gymnosperm (monocot) wood.
      - Hardwood is angiosperm (dicot) wood.
      - Softwood isn't always softer than hardwood.
      - https://en.wikipedia.org/wiki/Softwood
      - https://en.wikipedia.org/wiki/Hardwood
      - https://en.wikipedia.org/wiki/Dicotyledon#Comparison_with_monocotyledons
- Science in 21st century is multi-/inter-discipline?
  - All branches of science cross-pollinate?
  - It's no longer useful to categorize science by branches?
  - Where is the boundary between two branches?
    - Where do physics end and chemistry begin?
- Philosophy
  - Does everything fall under philosophy?
    - How do we prevent this category from becoming a kitchen sink?
    - Philosophy is everywhere (a cross-cutting concern), so it shouldn't be a category.
** Ramblings, speculations, fantasies, imaginations, and trivias
*** Acting
- I rarely watch movies.
- I'm sure there are other good actors, actresses, and movies.
- But I'm not watching all the movies in this world.
- Examples of good acting
  - Adewale Akinnuoye-Agbaje in "Faster"
  - Christoph Waltz as Hans Landa in "Inglourious Bastards"
  - Heath Ledger as Joker in which Batman movie?
- Examples of good movies
  - films directed by Christopher Nolan
    - "Interstellar"
    - "Inception"
*** Quantum inertia? Rocket propulsion? What?
- https://www.reddit.com/r/compsci/comments/9kxiiu/what_new_thing_are_you_currently_learning_in_your/
*** Curing cancer?
**** Trading cancer with autoimmune disease?
Trading something bad with something hopefully less bad?
https://arstechnica.com/science/2018/10/treatments-that-cause-the-immune-system-to-attack-cancer-earn-a-nobel/
*** (Why the hell did I bother to find out about these things?)
**** Physics textbook

- [[http://www.lightandmatter.com/area1sn.html][Simple Nature, an online physics textbook]]: for beginner, too wordy for me.

**** Browser plugins (I don't necessarily use)

- Vimium: vim-like shortcuts for navigating the chromium browser
  - [[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en][Install from Chrome Web Store]]
  - [[https://github.com/philc/vimium][Source code on GitHub]]
- Perhaps I should make a browser plugin that copies a link of the page to the clipboard in Markdown format?
  No. A bookmarklet suffices.
  - Which browser has easiest plugin development?
    - The result might be suspicious because I used Google to look for the answer.
    - 2016: Chrome ([[https://www.quora.com/Is-it-easier-to-write-a-plug-in-extension-for-Chrome-or-Firefox][source]])
    - 2011: Chrome ([[https://stackoverflow.com/questions/6438329/which-browser-is-easier-to-develop-plug-ins-for-chrome-or-firefox][source]])

**** Quartz scheduler performance
  - http://airboxlab.github.io/performance/scalability/scheduler/quartz/2017/06/20/perf_tuning_quartz.html
  - https://www.ebayinc.com/stories/blogs/tech/performance-tuning-on-quartz-scheduler/
  - https://stackoverflow.com/questions/11565993/quartz-performance
**** Picking colors
  - theories and principles
    - [[https://usabilla.com/blog/how-to-design-for-color-blindness/][How to Design for Color Blindness]]
    - [[http://www.tigercolor.com/color-lab/color-theory/color-harmonies.htm][Color Harmonies: complementary, analogous, triadic color schemes]]
  - tools
    - [[http://www.hsluv.org/][HSLUV: human-friendly /perceptually uniform/ color picker]]
      - [[https://en.wikipedia.org/wiki/CIELUV][Wikipedia: CIELUV color space]]
      - [[https://arxiv.org/abs/1509.03700][Good colour maps: how to design them]], 2015, Peter Kovesi
    - [[https://leaverou.github.io/contrast-ratio/][Lea Verou's contrast ratio checker tool]]
**** Peterson v Newman on Channel 4 is not journalism

[[https://www.youtube.com/watch?v=aMcjxSThD54][video]]

Newman is putting her words on Peterson's mouth.

Peterson has the patience of a saint.

It is not journalism.
It is a mere entertainment.
Verbal boxing.
Spectacle.
**** Accommodation Ontology Language Reference?
- http://ontologies.sti-innsbruck.at/acco/ns.html
*** Accounting
- I use GnuCash for my personal accounting.
- Accounting terms
  - What is an account?
    - If you deposit money in banks, then you have an account for every bank account you have.
    - If you lend money to people, then you have an account for every people.
  - What is a journal?
    - A journal is optimized for entering transactions by date.
    - What is a transaction?
      - A transaction involves two or more accounts.
        - The sum of all account changes in a transaction is zero.
  - What is a subledger (subsidiary ledger)?
    - A subledger of account C is obtained by selecting only the journal entries that affect the account C.
  - What is a general ledger?
    - A general ledger is the concatenation/combination/summation of several subledgers.
- Are there open source enterprise accounting systems?
*** FOSS alternative to SmartRecruiters?

https://blog.capterra.com/top-8-freeopen-source-applicant-tracking-software-solutions/
*** Learning languages
**** Cantonese
http://wikitravel.org/en/Cantonese_phrasebook

The biggest problem of Cantonese:
it doesn't have /standard/ romanization like Hanyu Pinyin, does it?
Cantonese has three: Jyutping Romanization, Yale Romanization, and Cantonese Pinyin.
It unnecessarily fragments learning resources.

https://en.wikipedia.org/wiki/Cantonese_Pinyin

6 tones.

- 1: high
- 2: low-to-high
- 3: flat mid
- 4: low-to-even-lower
- 5: low-to-mid
- 6:

Which is the romanization, Yale or Jyutping?
Yale vs Jyutping:
https://en.wikipedia.org/wiki/Cantonese#Phonology
https://en.wikipedia.org/wiki/Hong_Kong_Government_Cantonese_Romanisation

https://en.wikipedia.org/wiki/Cantonese_phonology#Cantonese_syllables

http://cantonese.ca/

http://www.cantonese.sheik.co.uk/dictionary/words/42086/#jyutpinginfo

我 ngo5 = I

你 nei5 = you

今日 gam1 jat6 = today

我係 ...
ngo5 hai6 ...
= I am ... (name, occupation)

我係今日返屋企㗎。
ngo5 hai6 gam1 jat6 faan1 uk1 kei5/2 gaa2/3/4

你以為我係邊個呀？
nei5 ji5 wai4 ngo5 hai6 bin1 go3 aa3/4/5/1?
Who do you think I am? / Do you know who I am?

https://www.youtube.com/watch?v=Pg0xsKyA1Uw

ngo5 hai6 yat1 jek maau = I am a cat

yat jek gau = a dog
**** Russian
[[https://ria.ru/][RIA news agency website]]

[[https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0][Заглавная страница]]
(Russian Wikipedia main page)

Словарь
dictionary

проверить
check

Избранная статья
selected articles

Случайная статья
random article

Биография
biography

Окончил Калькуттский окружной колледж.
He graduated from the Calcutta District College.

человек
human

Человек изучает и изменяет себя и окружающий мир, создаёт культуру и собственную историю.
A person studies and changes himself and the surrounding world, creates a culture and own history.

Тело человека имеет ряд отличий от обезьян.
The human body has a number of differences from monkeys

Знаете ли вы?
Did you know?

Текущие события
current events

Новости news

News categories:
главное main
общество society
наука science

Коалиция США нанесла новый удар по проправительственным силам в Сирии

The US coalition struck a new blow against the pro-government forces in Syria
**** German
- teil
  - teilen = divide
  - geteilt = divided
  - unteilbar = indivisible
- bis = to
- Tisch
  - der Tisch = the table
  - die Tische = the tables
  - auf dem Tisch = on the table
  - auf den Tischen = on the tables
- Bitte melden Sie sich an, um zu kommentieren. = Please log in to comment.
  - from https://www.zeit.de/campus/2018-08/altersvorsorge-rente-angst-zukunft-fragen
  - bitte = please
  - melden = log in
  - Sie = you
  - sich = yourself
  - "an" modifies "melden"
  - um zu kommentieren = in order to comment
  - More literal translation: "Please log you yourself in in order to comment."
- langlebig = long-lived
- kurzlebig = short-lived
**** Mandarin
- Where can I learn Mandarin?
- What are the five tones?

  - 1
  - 2
  - 3
  - 4
  - 5

- Set up input method
- Dictionary
- Thesaurus
- Basic grammar
- Set phrases
- [[https://www.fluentu.com/blog/chinese/2015/02/18/simple-mandarin-chinese-sentences-examples/][5 Solid Structures for Building Simple Mandarin Chinese Sentences]]
- Chinese computer terms

  - https://www.writtenchinese.com/stop-being-n00b-learn-computer-words-chinese/
  - https://www.fluentu.com/blog/chinese/2011/10/10/chinese-vocabulary-word-list-computer-internet/
  - https://chinese.stackexchange.com/questions/6375/chinese-computer-vocabulary-and-most-frequently-encountered-common-computer-ter

- Where are example sentences?
- Reading hanzi

  - [[https://www.coscom.co.jp/japanesekanji/kanji02_2001.html][How to learn Kanji Efficiently]]
  - Various orderings

    - by frequency of use

      - https://en.wikipedia.org/wiki/List_of_kanji_radicals_by_frequency
      - [[https://kanjicards.org/kanji-list-by-freq.html][Kanji ordered by frequency of use - Kanjicards.org]]

    - https://en.wikipedia.org/wiki/List_of_kanji_by_concept
    - https://en.wikipedia.org/wiki/List_of_kanji_radicals_by_stroke_count

  - https://en.wikipedia.org/wiki/Radical_(Chinese_characters)
  - Use wiktionary to look up Han character origins (Bronze inscriptions)

- How does Mandarin absorb loanwords, foreign terms, foreign proper names?

  - Examples

    - How does [[https://en.wikipedia.org/wiki/Las_Vegas][WP:Las Vegas]] become [[https://zh.wikipedia.org/wiki/%E6%8B%89%E6%96%AF%E7%BB%B4%E5%8A%A0%E6%96%AF][WP:拉斯维加斯]] (lā sī wéi jiā sī)?
    - How does [[https://en.wikipedia.org/wiki/India][WP:India]] become [[https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%BA%A6][WP:印度]] (yìn dù)?
    - How does [[https://en.wikipedia.org/wiki/Indonesia][WP:Indonesia]] become [[https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%BA%A6%E5%B0%BC%E8%A5%BF%E4%BA%9A][WP:印度尼西亚]] (yìn dù ní xī yà)?
    - How does [[https://en.wikipedia.org/wiki/Saddam_Hussein][WP:Saddam Hussein]] become [[https://zh.wikipedia.org/wiki/%E8%90%A8%E8%BE%BE%E5%A7%86%C2%B7%E4%BE%AF%E8%B5%9B%E5%9B%A0][WP:萨达姆·侯赛因]] (sà dá mǔ hóu sài yīn)?
    - How does [[https://en.wikipedia.org/wiki/George_W._Bush][WP:George Walker Bush]] become [[https://zh.wikipedia.org/wiki/%E4%B9%94%E6%B2%BB%C2%B7%E6%B2%83%E5%85%8B%C2%B7%E5%B8%83%E4%BB%80][WP:乔治·沃克·布什]] (qiáo zhì wò kè bù shí)?

  - If every character has a meaning, how do we specify sound without meaning?
  - https://www.quora.com/How-are-foreign-names-written-in-Chinese
  - [[http://www.cjvlang.com/Writing/fornames.html][How Chinese, Japanese, and Vietnamese handle foreign names]]
  - [[https://www.fluentinmandarin.com/content/how-do-you-write-foreignenglish-names-in-chinese/][How do you write foreign or English names in Chinese?]]
  - [[https://en.wikipedia.org/wiki/Transcription_into_Chinese_characters][WP:Transcription into Chinese characters]]
  - https://chinese.stackexchange.com/questions/2270/why-do-chinese-translations-of-english-names-sound-very-inaccurate

- 2018, [[https://www.youtube.com/watch?v=OA_g2bQgOXY][How KaiOS Is Becoming the 3rd Major Mobile OS - YouTube]]
- What is Chinese equivalent of Twitter, Google, Facebook, Wikipedia, Google Scholar?

  - Google - baidu
  - Wikipedia - baike

- 雅加达 yǎ jiā dá - Jakarta
- 新闻 xīn wén - news
- 好事 hǎo shì - good thing, good deed

  - https://baike.baidu.com/item/%E5%A5%BD%E4%BA%8B

    - Is that an encyclopedia or a dictionary?

      - 词 cí - word
      - "X"一词 X yī cí - the word "X"
      - 通常 - tōng cháng - generally, usually

- [[http://tags.news.sina.com.cn/%E9%9B%85%E5%8A%A0%E8%BE%BE][sina.com Jakarta news in Mandarin]]

  - http://sports.sina.com.cn/others/fencing/2018-08-16/doc-ihhvciiv7596331.shtml

    - 击剑冠军孙伟将任亚运火炬手 fencing champion Sun Wei will assume the post of Asian Games torchbearer

      - 击剑 jí jiàn - fencing - anggar
      - 冠军 guàn jūn - champion - juara
      - 孙伟 sūn wěi - Sun Wei (name)
      - 将 jiāng - will, be going to, soon - akan
      - 任 rèn - to take charge of; to assume the post of
      - 亚运 yà yùn - Asian Games

        - 亚 abbreviation of 亚细亚 yà xì yà - Asia
        - 亚运 abbreviation of 亚洲运动会 yà zhōu yùn dòng huì - Asian Games

      - 火炬手 huǒ jù shǒu - torchbearer (火 fire, 火炬 torch, 手 hand) - pembawa obor

    - 上届斩获两枚奖牌 last time (he) seized two medals

      - 上届 shàng jiè - previous; last
      - 斩获 zhǎn huò - to seize

        - 斩 behead, cut
        - 获 catch, obtain, capture

      - 两枚 奖牌 liǎng méi jiǎng pái - two medals

        - 枚 counter word for small flat objects; similar to Indonesian "keping"

          - https://en.wiktionary.org/wiki/%E6%9E%9A#Chinese

    - 8月18日，第十八届亚运会将在印尼雅加达举行。 (On) August 18th, the 18th Asian Games will take place (be held) in Jakarta, Indonesia.

      - 8月18日 (八月十八日) bā yuè shí bā rì - August 18th
      - 第十八届 dì shí bā jiè - the 18th time
      - 亚运会 yàyùn huì - Asian Games
      - 将 jiàng - will
      - 在 zài - in, at
      - 印尼 yìn ní - abbreviation of Indonesia
      - 雅加达 yǎ jiā dá - Jakarta
      - 举行 jǔ xíng - to hold (a meeting, reception, etc.) - menyelenggarakan
**** Japanese
- Introduction

  - [[https://pomax.github.io/nrGrammar/#section-3-More_grammar][An introduction to Japanese]]
  - [[https://www.tofugu.com/japanese/borrowing-language/][Japanese: The Borrower Language]]

- Japanese grammar

  - [[http://kwhazit.ucoz.net/ranma/g_vaux.html][Japanese Verb Auxiliaries]]
  - [[https://en.wikipedia.org/wiki/Japanese_counter_word#Euphonic_changes][Japanese counter word - Wikipedia]]

- Japanese vocabulary

  - [[http://www.linguanaut.com/english_japanese.htm][Japanese Phrases]]

- Reading kanji

  - See "Reading hanzi" in [[file:%7B%%20link%20mandarin.md%20%%7D][Learning Mandarin]].

- Ubuntu 14.04

  - ibus-anthy for input method
  - gjiten for dictionary
  - What?

    - xelatex

- Newspapers

  - Asahi shimbun
  - Jakarta shimbun

- Communities

  - [[https://www.reddit.com/r/ja/][日本reddit]]
**** Bahasa Indonesia
- Apa beda manjur, mempan, mujarab, dan mustajab?
***** Some Indonesian vernaculars
Spoken Indonesian is wildly different from written Indonesian and news Indonesian.
On the street, nobody speak like news anchors.
****** Dong, kek
"Gitu dong!" (with emphasis on tu)
"Nah, gitu dong!"
"Gitu kek dari tadi!"
That's what I wanted you to do!
If only you had shut up and done that earlier,
we wouldn't have had to fight.

"Iiiih diem dong!"
(Can't you shut up!?)

"Ga bisa gitu dong!"
"Enak aja lu!"
"Apaan!?"
"Dari mana!?"
"Atas dasar apa!?"
(Typical response to outrage-inducing unfairness, injustice, or absurdity.
What the hell?
You can't do that!)
****** Doang, sih, aja
"Gitu doang?"
(Is that all? Is that all you got?)

"Segitu doang kemampuanlu? Cupu banget sih lu!"
(Is that all you got? You piece of shit!)

"Kenapa sih tiap kali gua datang, ada aja masalah..."
(I'm dying to know why there is always a problem every time I come.)

"Gitu doang ngambek"
"Gitu aja marah"
(Why the hell are you angry for such trivial thing?)

"Coba diem dulu deh!!"
Can't you shut up for a while?

"Eh ini enak. Cobain deh..."
This is delicious. Here, try some!

"Iya aja deh"
"Apa katalu dah"
(Whatever you say.)

"Masih aja!"
(Why the hell are you still doing this?
Haven't I told you to stop already?)

"Ini aja?" (Is this everything?)
"Iya ini aja"
"Iya ini doang" (Yes, it's everything.)
****** Deh
"Eh iya deh."
(Oops, I was wrong.)
(Oops, I just remembered.)

"Iya maaf deh."
(Sorry. Whatever. Are you happy now?)
****** Kok
"Kok lu masih idup?"
(Why the hell are you still alive?)

"Kok lu di sini?"
"Kok lu di sini sih?"
(Why are you here? You aren't supposed to be here.)

"Udah dikerjain kok PR-nya Ma."
(What the hell are you accusing me for Mum?
I have done my homework, you know.)

A: "Eh ini kok gini? dapet dari mana?"
(Huh? Why is this? Where does this come from?)
B: "Ya iya dong. Masa gini aja lu ga ngerti?"
(I'm getting impatient.
Isn't it obvious?
You can't understand something this simple?)

"Gitu aja kok repot" (trademark alm. Gus Dur)
"Why so much hassle over such small matter?"
(I think Joker's (as played by Heath Ledger) "Why so serious?" also fits this somewhat.)
****** Lah, lho or loh
"Ya begitulah"
(More or less that's the case.)

"Ya begitulah"
(a vague and rather polite response that does not mean anything;
this avoids making the other party think you are ignoring him/her)

"Ya begitulah"
"Ya begitulah... lu tau sendiri kan"
"Mau gimana lagi?"
仕方ない
(Nothing can be done about it; What else can be done?)

"Lho kok masih di sini?"
(Why the hell are you still here?)

"Lho kok belum dikerjain?"
(Why the hell haven't you done this?)

"Iya lho"
"Bener lho"
(I'm serious. I'm not lying.)

"Lho lho lho"
(Wait, what?)

"Gue gitu loh"
(Of course I can do that. I'm the greatest.)
****** Toh
"Oh gitu toh"
そうですか。
なるほど。
I see.
****** Lain-lain
"Mampus... gw lupa matiin kompor!"
(Shit! I forgot to turn off the stove.)
**** English
***** Present perfect tense, past perfect tense
- https://englishlive.ef.com/blog/language-lab/english-grammar-help-present-perfect-and-past-perfect/
  - I did X = I did X in the past?
  - I has X = I did X, and I finished doing X, but I can still feel its effects now
  - I had X = I did X, and I finished doing X, and I don't feel its effects now
  - past tense vs past perfect tense?
***** will vs be going to
- https://www.perfect-english-grammar.com/will-or-be-going-to.html
***** Favorite shortenings
   :PROPERTIES:
   :CUSTOM_ID: favorite-shortenings
   :END:

- to obviate X = to make X unnecessary

  - similar: replace, supersede, deprecate

- to fudgel = to pretend to work while in reality you are not doing anything ([[https://en.wiktionary.org/wiki/fudgel][Wiktionary]])

  - to procrastinate = to put off; to delay ([[https://en.wiktionary.org/wiki/procrastinate][Wiktionary]])

- to lucubrate = to work diligently by artificial light; to study at night [[https://en.wiktionary.org/wiki/lucubrate][Wiktionary]]
- https://en.wiktionary.org/wiki/Thesaurus:laugh

***** Colorful synonyms of bad
   :PROPERTIES:
   :CUSTOM_ID: colorful-synonyms-of-bad
   :END:

- bad: improper, intolerable, unacceptable, undesirable
- awkward, clunky
- kludge, hack, ugly
- oversentimentally bad: kitsch, corny
- disappointingly bad: suck, hopeless
- almost/borderline bad: mediocre
- very bad: terrible, abysmal, disturbing
- scarily bad: dreadful, horrendous, horrifying, horrible
- ethically/morally bad: shady, sketchy, questionable, scandalous, criminal
- cruelly/violently bad: atrocious, brutal
- disgustingly bad: abominable
- much/excessively bad: shitload, truckload, crapload, boatload
- irritatingly bad: annoying, frustrating, exasperating
- hatefully bad: shitty, half-assed, crummy, crappy, cruddy
- outrageously bad: [goddamn] [worthless] [motherfucking] [truckload of / piece of] [shit / crap]
  (the order of adjectives is important)
- https://en.wiktionary.org/wiki/Thesaurus:bad

***** Synonyms of insane
   :PROPERTIES:
   :CUSTOM_ID: synonyms-of-insane
   :END:

- crank, crackpot, wacko, kook
- lunatic
- deranged
- delusional
- https://en.wiktionary.org/wiki/Thesaurus:insane

***** razmatazz, claptrap, humbug
   :PROPERTIES:
   :CUSTOM_ID: razmatazz-claptrap-humbug
   :END:

***** Researches
   :PROPERTIES:
   :CUSTOM_ID: researches
   :END:

- 2015 article "Vocabulary Learning Strategies",
  [[https://jyx.jyu.fi/handle/123456789/49945][abstract]],
  [[https://jyx.jyu.fi/bitstream/handle/123456789/49945/vls.pdf][pdf]]
***** How does swapping the subject and the predicate changes the meaning of a copular sentence (a sentence whose verb is the copula)? Subject-predicate asymmetry?
We consider sentences of these forms: "X is Y" and "Y is X", where each of X and Y is a noun phrase.

We are interested in how swapping X and Y changes the meaning of the sentence.
****** Example
- John is the culprit.
- The culprit is John.
****** Example
- Mark Twain is Samuel Langhorne Clemens.
- Samuel Langhorne Clemens is Mark Twain.
****** Example
- The dog is a Siberian husky.
- A Siberian husky is the dog.
****** Example
- Dogs are animals.
- Animals are dogs.
****** Example
- The car is red.
- Red is the car.
*** Learning to play mahjong
  :PROPERTIES:
  :CUSTOM_ID: learning-to-play-mahjong
  :END:

The variant discussed here is classic Chinese mahjong.

**** Basic facts
   :PROPERTIES:
   :CUSTOM_ID: basic-facts
   :END:

There are 136 mahjong tiles,
of which 52 are dealed to the players.
The remaining 84 forms the wall.
Thus, in a play, you only get at most 21 chances to change your hand,
that is 84 divided by 4 (the number of players).

If each player takes 15 seconds, then a hand
will take at most 4 x 15 x 21 = 1,260 seconds (21 minutes).

There are 136 tiles (not including 4 flower tiles and 4 season tiles):

There are 3 suits (bams, dots, and chars). Each suit has 9 classes. Each number has 4 instances. Thus each suit has 36 tiles. Thus there are 108 suit tiles.

There are 7 honors (4 winds and 3 dragons). Each honor has 4 instances. Thus there are 28 honor tiles.

There are 27 suit classes and 7 honor classes, giving a total of 34 classes.

Each tile class has 4 instances.

Each tile is equally probable to be drawn.

The probability of picking a tile class is 4/136. The odds of picking a tile class is 4:132.

**** Number of chows, pungs, and kongs
   :PROPERTIES:
   :CUSTOM_ID: number-of-chows-pungs-and-kongs
   :END:

The probability of drawing a pung:
34 * 4/136 * 3/135 * 2/134 = 1/3,015 (odd of 1 : 3,014, approx 1 : 3,000)

Each suit has 7 unique chows: 123, 234, 345, 456, 567, 678, 789.
There are 3 suits, so there are 21 unique chows.
Each tile has 4 instances.
Each chow has 4^3 instances.
The probability of drawing a chow: 21 * 4^3 / (136 * 135 * 134) = 28 / 51,255
(odd of 1 : 51,227, approx 1 : 51,000).

Pung is more likely than chow. Is this a calculation mistake?

The probability of drawing a kong (four identical tiles):
34 * 4/136 * 3/135 * 2/134 * 1/133 = 1/400,995 (odd of 1 : 400,994, approx 1 : 401,000)

The probability of drawing a pair:
34 * 4/136 * 3/135 = 1/45 (odd of 1 : 44)

The probability of drawing two tiles having the same class:
4/136 * 3/135 = 1/1,530 (odd of 1 : 1,529)

The probability of drawing two tiles having the same suit (3 suits):
3 * 36/136 * 35/135 = 7/34 (odd of 7 : 27, approx 1 : 4)

The probability of drawing a chow:
The probability of drawing n, n+1, n+2 unordered of the same suit, for n in 1 to 7:

3! * 3 * 7 * 4/136 * 4/135 * 4/134 = 56/17,085 (odd of 56 : 17,029, about 1 : 304)

The probability of drawing a pair, given that one tile has been drawn by another player:

Let each player draw exactly one tile. The probability of four players drawing the same tile:
34 * 4/136 * 3/135 * 2/134 * 1/133 = the probability of drawing a kong
*** Traffic engineering
  :PROPERTIES:
  :CUSTOM_ID: traffic-engineering
  :END:

- Everyone has different willingness for travel.

  - Some travel is necessary.

    - Travel to work. Travel to make economic transactions.
    - This is ideally as efficient and fast as possible.
    - This forms the inelastic baseline demand.

  - The rest of travel is discretionary.

    - Travel to leisure.
    - This is ideally as enjoyable as possible.
    - This forms the elastic demand.

- Is induced demand theory correct?

  - Disagreements

    - https://www.cato.org/blog/debunking-induced-demand-myth

  - Agreements

    - http://plazaperspective.com/road-widening/
    - "Induced demand means that for every person that switches from driving to an alternative, another driver will take their place."
    - [[https://www.youtube.com/watch?v=N4PW66_g6XA][How to Fix Traffic Forever]]

      - Counterintuitive

        - If road demand already exceeds supply, then widening roads increases traffic and causes more congestion.

          - [[https://en.wikipedia.org/wiki/Induced_demand][WP:Induced demand]]

- [[https://www.youtube.com/watch?v=Akm7ik-H_7U][The high cost of free parking]]
- [[https://helper.ipam.ucla.edu/publications/tratut/tratut_12985.pdf][A Mathematical Introduction to Traffic Flow Theory]]
- Related

  - [[https://en.wikipedia.org/wiki/Traffic_engineering_(transportation)][WP:Traffic engineering (transportation)]]
*** Outdated content that I do not intend to update
**** Android development in 2016
Last time I developed for Android in 2012.
My knowledge is irrelevant now.
- http://blog.teamtreehouse.com/android-libraries-use-every-project
- https://github.com/codepath/android_guides/wiki/Must-Have-Libraries
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instances-and-amis.html
**** Web scraping with Haskell
- Easily manipulate DOM using [scalpel](https://hackage.haskell.org/package/scalpel),
  which uses [tagsoup](https://hackage.haskell.org/package/tagsoup).
  - Consume and produce REST API using
    [a Haskell REST framework](http://engineering.silk.co/post/90354057868/announcing-rest-a-haskell-rest-framework).
  - [A rather low-level approach](https://www.schoolofhaskell.com/school/to-infinity-and-beyond/competition-winners/interfacing-with-restful-json-apis).
  - We need an HTTP REST API.
    There are many ways of passing parameters: query string, http header, multipart.
    Request body can contain bytes, or JSON.
    Needs jsonification and dejsonification.
  - [HXT](https://wiki.haskell.org/HXT): how is this package organized?
  - [Building a concurrent web scraper with Haskell](http://adit.io/posts/2012-03-10-building_a_concurrent_web_scraper_with_haskell.html)
**** btpn
- Update <2020-01-17>: akhirnya bikin BTPN Jenius; orangnya datang ke kantor
- Syarat-syarat saya

  - Apa yang menarik?
    Mengapa harus peduli?

    - Bunga 5% per tahun?
    - Gratis biaya transfer?

      - Internet banking?
      - ATM?
      - Giro?

    - Penting nggak?

      - https://www.jenius.com/basic_question/apa-keuntungan-saya-memakai-jenius/

  - Seaman apa?

    - Apa simpanan dijamin LPS (Lembaga Penjamin Simpanan)?
      2018-08-09: [[https://www.jenius.com/basic_question/apakah-uang-yang-saya-simpan-di-jenius-aman/][Ya.]]

      - Apa BTPN peserta LPS?
        2018-08-09: Ya. Cari "pensiun" di [[http://lps.go.id/bank-peserta-penjaminan][daftar LPS]].

        - BTPN singkatan apa?

          - 2018-08-09:

            - Di [[https://www.btpn.com/][situs resmi]] sendiri malah tidak ada?
            - Menurut daftar LPS: "PT Bank Tabungan Pensiunan Nasional Tbk."

    - Apa bank ini akan bangkrut?
      Apa bank ini too big to fail?
    - BTPN punya siapa?

      - 2018-08-09: menurut [[https://www.btpn.com/id/hubungan-investor/komposisi-pemegang-saham-dan-struktur-organisasi-grup][sumber]]:

        - 39.9% punya Sumitomo Mitsui Banking Corporation (perusahaan Jepang)
        - 20% punya Summit Global Capital Management B.V. (perusahaan Belanda)

          - ujung-ujungnya Sumitomo Corporation

            - "The company operates as a subsidiary of Sumitomo Corporation." [[https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=285795044][sumber]]

        - 40.1% punya publik (people mostly holding very little share)

      - Kok ada "nasional" di namanya?
        Kirain punya negara?

        - Emang arti "nasional" apa?
          Menyebar di suatu negara?
          Dimiliki negara?

          - https://en.wikipedia.org/wiki/National_bank

  - Bagaimana cara buka rekening?

    - https://www.jenius.com/topic/jenius-registration/
    - [[https://www.jenius.com/basic_question/apakah-saya-harus-menjadi-nasabah-btpn-untuk-menikmati-layanan-aplikasi-jenius/][Buka akun Jenius, otomatis jadi "bagian" BTPN.]]

      - [[https://www.jenius.com/basic_question/already-btpn-account-can-change-transfer-account-jenius/][Tidak berlaku sebaliknya.]]

  - Siapa counterparty kontrak saya jika saya membuka rekening Jenius?
  - Apakah data saya akan bocor ke pihak ketiga?

    - Bagaimana saya melarang BTPN membocorkan data saya ke pihak ketiga?

      - Apakah saya harus menerima semua syarat yang dibuat tanpa melibatkan saya?
        Kalau tidak mau ya jangan pakai?

- How much money are you losing by not switching?
**** violin
This is my study notes, observations, and conclusions.
This is a bit disorganized.

I play the violin without chin rest and shoulder rest.
***** The right pinky
The right pinky is for playing softly:
tilt the bow very slightly by pressing down the pinky (with the thumb as the fulcrum).
XXX: Is it by flexing the pinky or by supinating the hand?

Playing softly is harder than playing loudly.
Playing softly also uses more tension than playing loudly.
***** Squeaking
Each bow speed has a range of pressure that will make a good sound.
Less bow speed needs less pressure.
The symptom of too much pressure for a bow speed is squeaking;
increase the bow speed, or decrease the bow pressure, or both.

Decrease the bow pressure by pressing the end of the bow with the right pinky,
with the thumb as the fulcrum.
***** Playing open strings
Open strings, especially the A and E strings,
sound brighter than stopped strings,
so open strings will be perceived as louder
even though the bow speed and pressure stay the same.
In order to play scales with even dynamics,
we can avoid open strings,
or we can bow the open strings more softly
with reduced pressure and speed.

Also, we can play the D string nearer to the bridge to brighten it,
and the A string nearer to the fingerboard to darken it,
to make the change from the D to the A string smoother.
***** Idea for group practice
Learning Kreutzer etudes together?
***** Bouncing bows
The hairs act as a spring.

Vertical component of stick-slip.

Act as torque with the right thumb as the fulcrum.
**** wikia
[[http://dizzy.pestermom.com/][KimikoMuffin]]
has [[http://dizzy.pestermom.com/?p=nowikia][some strong reasons for not using Wikia]].

Wikipedia does not own Wikia, but
[[http://money.cnn.com/magazines/business2/business2_archive/2007/03/01/8401010/][who owns Wikipedia also owns Wikia]]:
Jimmy Wales owns a share of Wikipedia and also a share of Wikia.
Whenever you make a Wikia site,
you're working, unpaid, for him and the other owners.
[[http://shouldiworkforfree.com/][Why would you work for free?]]
(By the way, Wikipedia also has its share of unpleasant stories,
but that's for another post.)

An alternative that will give you more freedom
(and ownership, but also more responsibility)
is hosting on your own domain,
but this needs some technical understanding.

The bad news is that Wikia is the leader for niche wikis
and there doesn't seem to be any meaningful [[http://alternativeto.net/software/wikia/][competition]]:
Google search result for niche gaming queries is typically full of Wikia articles.
In the meantime, you can try [[http://www.shoutwiki.com/wiki/Main_Page][Shoutwiki]]
(there's even a wiki named [[http://awa.shoutwiki.com/wiki/Anti-Wikia_Alliance][Anti-Wikia Alliance]]) or
[[http://www.gamepedia.com/][Gamepedia]].
*** <2016-03-22> The reason for the name spacetimecat.com
In jazz-speak, a /cat/ is a jazz musician, and
I'm a jazz musician traveling through spacetime;
hence the name /spacetime cat/.

However, most importantly, the domain is a dot-com,
and it was available, untouched by rent-seeking domain speculators.

Another reason is that the name isn't tied to shady stuffs
and doesn't have unwanted connotations.
A quick google shows that the worst result
for 'spacetime cat' is cat pictures,
which should be pretty safe for everyone
except perhaps a few extreme cat haters.

It's also nice that the name
isn't too hard to remember or spell,
but it's hard to get it wrong.

Hence I bought spacetimecat.com.
** Ethical design
- [[http://mrmrs.cc/writing/2016/03/23/the-veil-of-ignorance/][Applying John Rawls's "veil of ignorance" argument to web design]]
* Does not belong in this page?
** LSEV (low-speed electric vehicle)
- Big in China: Tiny Electric Cars [[https://www.youtube.com/watch?v=kILXXaqspcI][video]]
  - $1,000 for a car that fits 2 adults and goes up to 60 km/h.
** "Sanity" does not exist
"an experiment conducted to determine the validity of psychiatric diagnosis"
https://en.wikipedia.org/wiki/Rosenhan_experiment
** Antivaccinism is parental negligence.
http://www.thejakartapost.com/news/2018/09/05/rubella-kills-baby-in-jambi-as-vaccination-campaign-meets-resistance.html

What is the difference between killing and letting die?
What is the difference between deliberately killing and deliberately letting die?
* Entertainment
** 21st century news
- [[https://www.liputan6.com/regional/read/3618529/bocah-bocah-terciduk-saat-asyik-dugem-di-diskotek-berkedok-toko-es-krim][Bocah-Bocah Terciduk Saat Asyik Dugem di Diskotek Berkedok Toko Es Krim - Regional Liputan6.com]]
  - from [[https://www.reddit.com/r/indonesia/comments/97s1o2/bocahbocah_terciduk_saat_asyik_dugem_di_diskotek/][reddit]]
- [[https://regional.kompas.com/read/2017/05/10/15213361/tommy.soeharto.dianugerahi.gelar.gus.oleh.ulama.di.jatim][Tommy Soeharto Dianugerahi Gelar "Gus" oleh Ulama di Jatim - Kompas.com]]
  - [[https://nasional.tempo.co/read/10122/kronologi-kasus-tommy-soeharto][Kronologi Kasus Tommy Soeharto - Nasional Tempo.co]]
  - [[https://tirto.id/pembunuhan-hakim-syafiuddin-yang-dirancang-tommy-soeharto-cPVT][Pembunuhan Hakim Syafiuddin yang Dirancang Tommy Soeharto - Tirto.ID]]
  - [[https://seword.com/politik/sadisnya-pembunuhan-hakim-kartasasmita-oleh-tommy-soeharto-ryLUQSUYG][Sadisnya Pembunuhan Hakim Kartasasmita oleh Tommy Soeharto - Seword]]
** Other entertainment
an0nymooose
ooooOOOOOOOOOOOOOOOOH
https://www.youtube.com/watch?v=nSRpbNru5aw&list=PLbZ4aMR4f3Sd_rvr40AYy_spbBu_xZGgA&index=8

[Vinesauce] Vinny - Best of The Choicest Voice
https://www.youtube.com/watch?v=SB9Cpjd7PxI

Treadmill falls apart
https://www.youtube.com/watch?v=XanTpm8dxMU
from 1:24 of "YOU may LAUGH TO DEATH - Funny compilation" https://www.youtube.com/watch?v=j9dLVJgT79M

- How To Get Affordable Healthcare | We the Internet TV https://www.youtube.com/watch?v=JoIXpKUFDtM
- HateF**k Dating App | We The Internet TV https://www.youtube.com/watch?v=z4-qbrvx9f0

What the fuck are these guys wearing?
"Kanye West & Lil Pump ft. Adele Givens - "I Love It" (Official Music Video)"
- https://www.youtube.com/watch?v=cwQgjq0mCdE

Café In Thailand Lets You Play With A Pack Of Huskies
https://www.youtube.com/watch?v=hjrl-G0vySY

a dank meme: Trump, Kim, and "pees are stored in the balls"[fn::https://www.reddit.com/r/dankmemes/comments/8qi1pt/supreme_leader_sees_the_light/]
* Interdisciplinary comments
* Virtual hotel operators
** Who is OYO CTO?
From a 2016 article[fn::https://www.livemint.com/Companies/GfBdOyw5rNidPCkmwc2KSJ/OYO-Rooms-appoints-Anil-Goel-as-chief-technology-officer.html]:
- In 2016, OYO gets new CTO: Anil Goel[fn::https://in.linkedin.com/in/anilgoel1]
- 20 years of experience in technology infrastructure
- past head of technology for customer returns and reverse logistics at Amazon India in Hyderabad for three years
- past chief technology officer of Hike Messenger

Is he more of the practical-type than the researcher-type?
Is he more about business than about research?
One interview question is "What is considered as a good business plan?"
 [fn::https://www.geeksforgeeks.org/oyo-rooms-interview-experience-for-software-engineer/]

"[...] he went to BITS Pilani in 1991"[fn::https://yourstory.com/2018/02/techie-tuesdays-anil-goel].
Thus he was probably 18 years old in 1991, and 46 years old in 2019.

<2018-09-21>
"OYO plans to hire over 2,000 tech experts, engineers by 2020"
 [fn::https://www.thehindubusinessline.com/companies/oyo-plans-to-hire-over-2000-tech-experts-engineers-by-2020/article25005997.ece]:
- OYO is backed by Softbank and Sequoia
- "we will continue to invest in technologies like artificial intelligence, machine learning,
  and IoT that will make curated guest experiences at every price point a reality,
  while ensuring sustainable income for partners and livelihood opportunities for several Indians."
- "we are glad to partner with the government in its goal of creating millions of economic opportunities"

Ajay Shrivastava was the previous CTO?[fn::https://in.linkedin.com/in/ajayshrivastava1]

https://www.linkedin.com/pulse/solver-teams-oyo-hyper-agile-well-oiled-execution-ajay?published=u
** How many VPs does OYO have?
- <2017-04-13> Suvesh Malhotra, VP of engineering[fn::https://www.oyorooms.com/officialoyoblog/2017/04/13/welcoming-suvesh-malhotra-to-the-team]
- <2018-09-21> Priyank Chaudhury, VP of technology[fn::https://twitter.com/oyorooms/status/1043108964542468096]
- Shreerang Godbole, VP of people operations[fn::https://in.linkedin.com/in/shreeranggodbole]
- Ayush Mathur, VP of business development[fn::https://in.linkedin.com/in/ayush-mathur-94004918]
- Closed job: VP/AVP/Director of engineering[fn::https://in.linkedin.com/jobs/view/vp-avp-director-of-engineering-at-oyo-1190146439]
- Job description: VP of engineering[fn::https://oyorooms.taleo.net/careersection/ex/jobdetail.ftl?job=18000562&tz=GMT%2B07%3A00&tzname=Asia%2FJakarta]
** <2019-04-30> What is OYO doing?
Information sources:
- OYO Engineering & Data Science at Medium[fn::https://medium.com/@oyoengineering]
- OYOTech at Medium[fn::https://medium.com/oyotech/tagged/oyo]
- Official Oyo blog[fn::https://www.oyorooms.com/officialoyoblog/]

OYO Now![fn::https://medium.com/@shreyas.v.joshi]

<2019-04-02>
Spend USD 100 million in Indonesia[fn::https://bisnis.tempo.co/read/1191625/incar-100-kota-di-indonesia-oyo-hotel-kucurkan-usd-100-juta/full&view=ok]

<2019-04-02>
From 0 to 500 properties in 5 months.

<2019-04-09>
Oyo Wizard Membership[fn::https://www.oyorooms.com/officialoyoblog/2019/04/09/oyo-wizard-membership] seems to be a customer loyalty program.

<2019-04-30>
"We introduced pioneering technology to the hospitality industry to deliver better and more efficient
/operations, management, service and CRM/. Our app allows a user to book a room in just 3 taps, or within 5 seconds."
 [fn::https://www.oyorooms.com/about?oyocorporate=]
(emphasis mine)
** What is Oyo doing with its engineers?
** OYO tech stack
In 2016, they are using pretty much a standard tech stack:
 [fn::https://in.linkedin.com/jobs/view/senior-software-engineer-at-oyo-1107116583]
 [fn::https://startup.jobs/47930-software-engineer-at-oyorooms]:
- They are using "Java/J2EE, Lamp, GoLang, Python/DJANGO" for their property management system
  ("You will work at an intersection of Finance, Business and Technology - owning end to end development of features that help us cater to our Hotel Partners.")
- Java/Python/Ruby/C++
- SQL
- Amazon Web Services

Spring Framework (Java)[fn::https://www.glassdoor.co.in/Interview/OYO-Full-Stack-Developer-Interview-Questions-EI_IE953789.0,3_KO4,24.htm]

"Easy" competitive programming questions.
(Easy for competitive programmers, somewhat hard for non-competitive programmers.)

From the previous CTO Ajay[fn::https://in.linkedin.com/in/ajayshrivastava1]:
- Website - Ember.js, Node.js, Javascript, Foundation, Bootstrap, HTML, CSS. Mobile - Android, Java, Objective C
- Analytics - Hadoop, Map reduce, Amazon EMR.
- Backend - Ruby on Rails, JRuby, Amazon Web Services, Data stores (Postgres, MongoDB, Redis, Memcache).
- Quality - Java, Selenium

They used Ruby on Rails,
according to one employee.[fn::https://www.quora.com/Which-development-platform-and-technology-are-used-by-OYO-Rooms]

But they are moving from Ruby to Java:
"Almost all teams breaking the current code(Ruby on Rails) into new Micro-services (Java)"[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW22416076.htm]
** OYO tech blog
- https://www.oyorooms.com/officialoyoblog/category/tech
** OYO software engineer interview experience
January 2018 Gurgaon interview questions.
20-30 applicants.
 [fn::https://www.geeksforgeeks.org/oyo-rooms-interview-experience-set-8-software-engineer/]
** OYO software engineer salary
<2019-04-08>
Glassdoor[fn::https://www.glassdoor.co.in/Salary/OYO-Software-Engineer-Salaries-E953789_D_KO4,21.htm]:
INR 900,000 (IDR 183,569,926 nominal, IDR 212,727,600 PPP-adjusted) per year.
About IDR 17,727,300 real per month.
This is before taxes.

INR 1,125,000 according to Hush[fn::https://hush.company/oyo-rooms/salaries/software-engineer/].

<2019-04-12>
Cost of living per month in Mumbai for a bachelor[fn::https://www.numbeo.com/cost-of-living/in/Mumbai]:
- INR 26,000 for expenses without rent
- INR 40,000 for 1-bedroom apartment in city center

Total cost of living in Mumbai for a bachelor: INR 792,000 per year.

Mumbai seems to be the most expensive city.
They are hiring in other cities.
Bangalore living cost is about 1/2 to 2/3 of Mumbai.

<2019-04-12>
2017 purchasing-power-parity adjusted data[fn::https://data.oecd.org/conversion/purchasing-power-parities-ppp.htm]:
- USD 1 = INR 17.729 PPP-adjusted
- USD 1 = IDR 4,190.492 PPP-adjusted
- INR 1 = IDR 236.364 PPP-adjusted
- INR 1 = IDR 203.97 nominal
** Disgruntled ex-OYO employees
There are some disgruntled ex-OYO-bizdevs[fn::https://www.glassdoor.com/Reviews/OYO-new-cto-Reviews-EI_IE953789.0,3_KH4,11.htm].

They probably have non-compete agreements.

Are non-compete agreements legal in India?

Are non-compete agreements legal in Indonesia?

Probably a disgruntled female engineer[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW24717895.htm]

Probably an overworked biz-dev[fn::https://www.glassdoor.com/Reviews/OYO-Software-Engineer-Reviews-EI_IE953789.0,3_KO4,21.htm]

<2018-09-11>
A damning review from "Join OYO only if you are desperate. Honest 2018 review with no bias."
Current Employee - Software Engineer in Gurgaon, Haryana[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW22416076.htm]:
- Politics , politics everywhere.
- Large salary disparity.
  You'll join only to know there are ppl in your team getting much higher than you get and than they deserve.
  CTO has a fetish for hiring people from Hike and Amazon.
He has worked at both places earlier.
So he's pretty much bringing in everyone he knows from these places (I am not saying they are not good), but they will be given important roles than you, without question.
- Almost all old employees have left/asked to leave Here's a red flag.
  The employees who joined during the time of old VP Ajay were now being called non-smart hires.
  The CTO has replaced EACH AND EVERY ONE OF THEM.
  They were the people who gave their blood and sweat to build OYO as it is today.
  OYO has a technique to make you leave the company now.
  They'll hire someone totally new and make them sit over you on higher position, to take away you responsibilities.
  Or they'll just give you no hike.
  So you'll and leave.
  I was hired after the new CTO came but the older guys were so awesome.
  Now there are hardly 5 older guys left.
  Whole tech team replaced.
- There's a flood of freshers.
  They hired more than 200 freshers in one batch from IITs(any branch)/good colleges against 70 devs who were left at one time.
  No one has any idea of the legacy system.
  There's total chaos.
  Much time goes in doing their ramp up if you're an old employee.
  So by the evening you'll feel to do the work yourself instead of teaching them everything.
- In the last 6 months, they made jokingly new teams,to accommodate the new hires, and hired managers from outside for almost all of them.
  most of them total jerks.
- 90% people leave within 1 year of joining.
  So my advice: If you're a fresher or don't have any opportunity from anywhere else.
  OYO will be a good place as you can learn.
  But then again come with no expectations of respect or growth, as you'll watch it getting shattered within 6 months.
  My papers on their way.

But there are other good reviews too.
** OYO job openings
Software development engineer[fn::https://www.glassdoor.com/Job/bengaluru-software-development-engineer-bangalore-jobs-SRCH_IL.0,9_IC2940587_KO10,49.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3002042947&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=102&t=EMPLOYER_SEARCH_RESULTS]

3+ years of strong hands-on development experience including at least 1.5 years of real-world web development experience using JSP, Java Servlets, Java Struts, Spring, & Hibernate

- Good understanding of design patterns, object oriented design, and frameworks
- Good RDBMS skills and experience in DB/SQL
- Experience with multiple technologies - LAMP, Ruby on Rails, Python, Perl, Java, PHP
- Exposure to MVC frameworks such as Rails, Spring, Django, CodeIgniter.
- Experience working with scripting language such as Pearl [sic] - to quickly roll our parsers for analysis and write small modules - is preferred
  [WTF is Pearl? You mean Perl?]
- Exposure to Postgres, Mysql (exposure to NoSQL database related technologies like MongoDB, Redis, Aerospike, Cassandra etc. is a plus)
- Experience with SCRUM methodology or extreme programming is a great plus
- Exposure to app servers like JBoss, WebLogic, WebSphere
- Previous start-up experience or contribution to any open source project
- Experience working on DROOLS or any other rule engine and SOAP/string based API integrations

https://www.glassdoor.com/Job/hyderabad-software-development-engineer-23-jobs-SRCH_IL.0,9_IC2865319_KO10,42.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3130003429&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=104&t=EMPLOYER_SEARCH_RESULTS

IoT engineer:
They don't bother writing the "What will you need to be successful in this role?" section.
It is an exact copy of that of the back-end engineer.
- https://www.glassdoor.com/Job/bengaluru-software-development-engineer-ii-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,46.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3127022842&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=105&t=EMPLOYER_SEARCH_RESULTS
- https://www.glassdoor.com/Job/bengaluru-software-development-i-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,36.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3127023307&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=107&t=EMPLOYER_SEARCH_RESULTS

ACP? What is ACP?
https://www.glassdoor.com/Job/hyderabad-software-development-engineer-ii-iii-acp-jobs-SRCH_IL.0,9_IC2865319_KO10,50.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3187186317&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=106&t=EMPLOYER_SEARCH_RESULTS
** In 2016 it seems that they are focusing on wifi experience
- https://www.oyorooms.com/officialoyoblog/2016/09/02/home-is-where-wifi-is
  - It seems that wifi is important?
    Is wifi important for customers?
    Is bad wifi a deal-breaker?
  - OYO app automatically enters wifi password, but how does that work without intruding into the user's phone?

Firmware engineering manager[fn::https://www.glassdoor.com/Job/bengaluru-firmware-engineering-manager-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,42.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3131744908&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=112&t=EMPLOYER_SEARCH_RESULTS]:
- Deep hands-on technical experience in RTOS, at-least one of these Wireless technologies (BLE 4.2 or 5.0 with Mesh, LoRaWAN, 6LoWPAN, Zigbee, Thread, Sub-GHz RF),
  interfacing with multiple devices on UART, I2C, SPI, object-oriented design, data structures, algorithm design, High-level architecture design and complexity analysis
- Good-to-have: Experience of working on IoT projects at-scale - Smart-lock, Home Automation, Vehicle tracking, etc.

Firmware engineer[fn::https://www.glassdoor.com/Job/bengaluru-firmware-engineer-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,31.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3103540384&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=113&t=EMPLOYER_SEARCH_RESULTS]
- Sound experience of developing firmware on ARM Cortex, MSP430, AVR, DSP, or other embedded platforms for 16/32 bit microcontrollers.
- Background in Systems Programming, Operating Systems, RTOS, IoT Protocols MQTT, CoAP.
- Experience with Wi-Fi, Bluetooth development, and BLE solutions.
- Knowledge of communication protocols: I2C, SPI, UART.
- Excellent programming skills in one or more of the following: C/C++/JAVA/Python with a proven capability of delivering high-quality code.
- Familiar with the use of embedded toolchains, ICE/JTAG debuggers, etc.
- Good to have - understanding of Wifi triangulation, indoor location tracking & mapping techniques.

"Oyo Rooms wants to share digital record of your check-ins with government"
 [fn::https://www.indiatoday.in/technology/news/story/oyo-rooms-wants-to-share-digital-record-of-your-check-ins-with-government-1431439-2019-01-15]
 [fn::https://en.wikipedia.org/wiki/OYO_Rooms]
** OYO glassdoor
Not only software engineers?
https://www.glassdoor.com/Reviews/OYO-new-cto-Reviews-EI_IE953789.0,3_KH4,11.htm
Pros:
- "Good work Environment and many things to learn at a go" (in 48 reviews)
- "Team leaders are well qualified (except some) and you learn a lot from them" (in 18 reviews)
- "Nice work culture of the company" (in 31 reviews)
- "work from home , beer in office , flexible working hours" (in 14 reviews)
- "a lot of opportunities to learn" (in 12 reviews)

Cons:
- "6 days a week is something that the management needs to work to ensure proper work life balance" (in 92 reviews)
- "No work life balance need to handle escalation" (in 32 reviews)
- "Long working hours and work not challenging" (in 29 reviews)
- "No work-life balance, no job-security" (in 13 reviews)
- "Work culture, Hire and fire policy" (in 11 reviews)
** Government
"exemption [of taxes] for hotels that charge Rs 1,000 or lesser, and lower tax rates for those charging less than Rs 2,500"
 [fn::https://yourstory.com/2018/01/oyos-ritesh-agarwal-talks-full-stack-model-expects-budget]

"This government has showcased [its] ability to be [unpredictable]"
** Does OYO have a research team?
Either OYO does not have a research team, or it is secret.
But, the CTO seems to be business-oriented,
so I think they don't have software engineering research.
** Who are some example OYO engineers?
What are their beliefs about software engineering?
** Who are some employees below VP?
- senior engineering manager https://in.linkedin.com/in/shashankjain89 https://in.linkedin.com/in/varunpathak
- senior principal engineer https://in.linkedin.com/in/dksidana
- ex-senior engineer https://in.linkedin.com/in/anshulnigam who "Owned and delivered Leads Management System, Owner Portal, Studio Stays, Meal Plans, OYO Getaways (now called OYO Hotel Packages); and worked on Hotel Agreements, Reconciliations, Owner/Hotels Payments, Payment Gateways integration for consumer payments, CRS(Central Reservation System), Lifeline, integration of SAP with CRS."
** What do OYO recruiters think a VP of engineering do?
https://www.glassdoor.com/Job/vp-avp-director-of-engineering-jobs-SRCH_KO0,30.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3083569104&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=118&t=EMPLOYER_SEARCH_RESULTS
** Dirts
*** September 2018 sexual harassment
In September 2018, a female guest Jordan Taylor reported sexual harassment by some staffs in an OYO-branded property.
- https://www.thenewsminute.com/article/stalked-trapped-hotel-us-travel-blogger-recounts-sexual-harassment-india-88186
  - from https://www.thehindubusinessline.com/companies/oyo-plans-to-hire-over-2000-tech-experts-engineers-by-2020/article25005997.ece

I think this is a culture clash.

From the point of view of the perpetrators, they were teasing the girl.
I don't think those Indian guys really dared to rape her,
because they would surely go to jail if they did.

However, from the point of the Western girl (and also Western people in general),
that interaction is really creepy, abnormal, and outside the bounds of civility.

Nonetheless, it is improper and totally unacceptable for workers in the hospitality industry to behave like that,
because they are in the hospitality industry, and they are expected to be hospitable.

"However OYO maintains that few incidents are insignificant compared to millions of check-ins happening everyday and the company tries to remedy any problem."
 [fn::https://en.wikipedia.org/wiki/OYO_Rooms]
*** <2019-04-16> From Wikipedia
From Wikipedia[fn::https://en.wikipedia.org/wiki/OYO_Rooms].

"OYO has been in news for using predatory pricing using its funding money to unfairly remove competition.
It was also reported that OYO was not following its own agreements and have threatened the hotels to
unilaterally change some of the clauses or suffer the consequences of non-payment."

"Oyo Rooms had sent mass unsolicited job offer emails targeting senior- and mid-level employees of competitor companies."

"It was reported by Business Standard in 2017 that OYO rooms were making massive losses without showing any significant revenues."
