#+TITLE: A mess
#+DATE: 2016-03-22 21:44 +0700
#+PERMALINK: /other.html
#+OPTIONS: ^:nil toc:nil
#+TOC: headlines 1
* The purposes of this page
- This page is a holding area for my capture-refile workflow.
- This page is for recycling old content.
* Reorganize this mess
This was moved from research.html.
** Resolving citations?
To resolve citation keys in this website, look up the key in [[https://github.com/edom/edom.github.io/blob/master/bibliography.yaml][bibliography.yaml]].

<2019-01-02>
We are moving back to bib.bib from bibliography.yaml,
so that we can copy-paste bib from Google Scholar.
*** Ramblings and undigested matters
   :PROPERTIES:
   :CUSTOM_ID: ramblings-and-undigested-matters
   :END:

- Linguistics

  - How do we use language?

    - We assume:

      - Every adjective is fuzzy.
      - Truth is a continuum.

- Corruptors and their offsprings have so much money that they don't know what to do with it.
- 2017-07-10

  - Ubuntu crashed without log.

    - Screen turned off suddenly.
    - Keyboard forze.
    - Power button didn't respond even after 4 seconds.
    - The problem turned out to be shitty graphics card connection.

      - Hardware problem, not Ubuntu problem.
      - Probably dust or oxidized connectors.

        - It would be nice if graphics card could be hotswapped though.

          - But do we want to touch a running graphics card?

    - The fix: unplug and plug the card several times.

- How do I find people who care about what I care?
- How do I find people with interests similar to mine?
- How to make money

  - Make hard things easy.

- Should we use holidays to form strategic alliances?
- To form quality relationship, socialize with one person at a time?
- There are only two way of getting rich:

  - create value (make others better)
  - extract value (steal from others, either legally or illegally)

- [[https://stackoverflow.com/questions/9466360/how-to-request-google-to-re-crawl-my-website][SO 9466360: How to request Google to re-crawl my website?]]
- Marketing

  - To market something is to try to sell it.

- [[https://www.youtube.com/watch?v=yzl7oX9FYGE][YT: What I've learned: Everything wrong with the "System" (Educate yourself)]]
- https://id.wikipedia.org/wiki/Ken_Kawan_Soetanto

  - Any English publications? Where?

- http://therumpus.net/2012/11/the-map-of-the-system-of-human-knowledge-by-james-tadd-adcox/
- https://www.theatlantic.com/magazine/archive/2006/08/a-taxonomy-of-knowledge/305189/
- [[https://en.wikipedia.org/wiki/Joy%27s_law_(management)][WP:Joy's law of management]]:
  "no matter who you are, most of the smartest people work for someone else"

** Mathematical modeling?
  - [[https://en.wikipedia.org/wiki/Mathematical_model][WP:Mathematical model]]
  - [[https://en.wikipedia.org/wiki/Many-body_problem][WP:Many-body problem]]
  - [[https://en.wikipedia.org/wiki/Few-body_systems][WP:Few-body systems]]
  - [[https://en.wikipedia.org/wiki/N-body_problem][WP:N-body problem]]
  - Articles
    - [[https://aip.scitation.org/doi/10.1063/1.533319][The quantum N-body problem]]
  - What is the difference between variable and parameter?
  - How many parameters do we need to model a system?
  - Discrete Newtonian kinematical model
    - A /system at time \( t \)/ is a set of particles ( { 1, \ldots, n } ).
      - Time is a real number: \( t \in \Real \).
      - The number of particle is constant \( n \in \Nat \).
      - For each particle \( k \):
        - It has /position/ \( x_k \in \Real^3 \).
        - Simplifying assumptions
          - particle
            - It is a point.
              - It doesn't occupy any space.
            - Its mass is not modeled.
          - Time is global and absolute (the same everywhere).
  - Discrete Newtonian dynamical model (N-body problem) extends discrete Newtonian kinematical model.
    - A /system at time \( t \)/ is all that above, plus:
      - For each particle \( k \):
        - It has /mass/ \( m_k \in \Real \).
        - It has /resultant force/ \( F_k \) acting on it.
        - Simplifying assumptions about the particle
          - It is rigid.
            - It doesn't deform.
            - It doesn't break.
          - Its mass is constant.
          - It don't interact with other particles.
            - Particles don't merge or collide.
  - [[https://en.wikipedia.org/wiki/Continuum_mechanics][WP:Continuum mechanics]]
  - Skippable philosophical issues?
    - Does "the same particle at different times" make sense?
      - What is "same"?
    - [[https://en.wikipedia.org/wiki/Heraclitus#Panta_rhei,_%22everything_flows%22][WP:"Panta rhei" ("Everything flows"), Heraclitus]]
** Common company wiki fundamental problem
Employees have no reason to read the wiki.
It doesn't help them do their jobs.
Why should they read it then?
** Applying probability theory and statistics to marketing and pricing

- https://medium.com/airbnb-engineering/learning-market-dynamics-for-optimal-pricing-97cffbcc53e3
- https://overflow.buffer.com/2018/08/13/predicting-churn/

** AI/ML?

- https://thegradient.pub/nlp-imagenet/
- https://chrisalbon.com/
- https://createmomo.github.io/2017/09/12/CRF_Layer_on_the_Top_of_BiLSTM_1/

*** Judea Pearl, "book of why", causal inference

- https://twitter.com/yudapearl/status/1016858846034210816
  - 2018, "The Seven Tools of Causal Inference with Reflections on Machine Learning", Judea Pearl, [[http://ftp.cs.ucla.edu/pub/stat_ser/r481.pdf][pdf]]
    - book, "The book of why [...]", Judea Pearl

** Programming language research

*** Self-composable programming?

- [[https://arxiv.org/abs/1612.02547][1612.02547 - Self-composable Programming]]

*** Generate REST API from database

- [[https://github.com/PostgREST/postgrest][PostgREST/postgrest: REST API for any Postgres database]]
  - https://restifydb.com/
  - https://www.progress.com/blogs/restify-databases-expose-your-database-to-rest-web-services
  - http://www.odata.org/getting-started/understand-odata-in-6-steps/

** Philosophy

*** First- vs third-person view?

- [[http://consc.net/notes/first-third.html][The First-Person and Third-Person Views]]

*** Ethics, morality
Utilitarianism is questionable.
 [fn::https://rationaloptimist.wordpress.com/2014/05/24/utilitarianism-is-killing-one-to-save-five-moral/]
 [fn::http://blog.practicalethics.ox.ac.uk/2014/11/why-i-am-not-a-utilitarian/]

Jonathan Haidt:
- Blind pursuit of Equal OUTCOME leads to an "Abomination of Justice".[fn::https://www.youtube.com/watch?v=cQNaT52QYYA]
- The moral roots of liberals and conservatives[fn::https://www.youtube.com/watch?v=vs41JrnGaxc]
- ? https://www.yourmorals.org/aboutus.php
- ? https://www.moralfoundations.org/
*** Evolutionary ethics
- https://en.wikipedia.org/wiki/Evolution_of_morality
- https://en.wikipedia.org/wiki/Evolutionary_ethics
- Evolutionary ethics
    - Morality is shaped by evolution.
    - We have difficulties defining what is "good", but there are things that we agree are good.
    - Morality is defined by the majority opinion.
    - Humans evolved morality because morality promotes survival.
        - Nature selects moral behavior. There is evolutionary pressure for moral behavior.
            - Sharing foods promotes survival.
            - Sharing knowledge promotes survival.
            - Cooperation promotes survival.
            - Marriage promotes survival?
            - Monogamy promotes survival?
    - The morality of a species is whatever evolved behavior that promotes its survival.
** Teaching and learning
  - How to teach history (or anything)
    - Don't memorize things that you can look up on the Internet.
    - Focus on stories, insights, reasons, motivations.
    - Empathize with the subjects.
      Why do they go to war?
  - Learning languages, both human languages and programming languages
    - One learns a language by example sentences.
      One learns a programming language by example programs/snippets.
      - One does not learn a language by memorizing the syntax.
      - One does not learn a language by memorizing the language reference document.
** TED?
- [[https://www.youtube.com/watch?v=fxbCHn6gE3U][The surprising habits of original thinkers | Adam Grant]]
- [[https://www.youtube.com/watch?v=YM-uykVfq_E][TED-Ed: What is entropy? - Jeff Phillips]]
- [[https://www.youtube.com/watch?v=PRYmx7Lk9F0][This Quantum 'Sixth Sense' Could Allow Birds to Navigate Earth's Magnetic Field]]
- [[https://www.youtube.com/watch?v=YnY0J_Z1TF4][The Earth Is Running Out of Sand and It Could Cause a Global Crisis]]
* Psychology?
** goals? systems?
- [[https://jamesclear.com/goals-systems][Forget About Setting Goals. Focus on This Instead.]]: focus on systems/processes instead of goals.
** Emotion hypothesis: Everything is fear
Attractive emotion.
Fear is a repulsive emotion.

Emotion axis: low/high energy, repulsive/attractive toward the cause

Hate is fear of proximity.

Desire is fear of loss.

Love is fear of loss.

Boredom is fear of repetition.

Indecisiveness is fear of regret.

Hunger and thirst are fear of death.

Joy is fear of fear.

* Philosophy?
** Bertrand Russell
Bertrand Russell - Message To Future Generations
https://www.youtube.com/watch?v=ihaB8AFOhZo
** Pragmatic ontology: how pragmatism can help us answer what something is
(Is this really what others mean by "pragmatic ontology"?)

To the pragmatic ontologist, "exist" means "practically exist".

Someone who subscribes to egocentric pragmatic ontology would take the question "What is X?" to mean "What can I use X for? / How can I use X?"

- I can use it, therefore it exists. (Compare: Descartes's "I think, therefore I exist.")
- It affects me, therefore it exists.
** Gaining information by losing data?
(Do I understand what I'm talking about?)

It is possible to gain information while losing data.
We often gain information when we feed data to an irreversible function.
Example:
- array_length
- statistical summarization and interpretation
- modeling
But is that losing data?

Most interesting mappings are irreversible.
Modeling is irreversible mapping.
** Dying in the 21st century
- Inheriting digital data
  - What to do with your data when you die?
  - https://www.businessinsider.sg/how-to-give-google-account-to-trusted-person-when-you-die-2018-8/
- Do we have to die?
  Can technology save us?
  Will we reach immortality in this century?
** Sloppy synecdoches: Is a "potato" a plant or a tuber?
A bean is a plant.

Let B be an individual, a bean plant.

Every individual of the species Solanum tuberosum is a plant.

Wrong: Potato is a plant => Every potato is a plant => forall x. potato(x) => plant(x)
A potato plant is a plant.
A potato is not a plant; a potato is a tuber.
Potato the whole plant vs potato the edible tuber.

Of course we can dismiss all this and just be sloppy with synecdoches,
but unclear language breeds unclear thinking.
* Hiring
** Hiring?
http://www.siop.org/Media/News/science.aspx
http://www.selectinternational.com/blog/hiring-art-or-science
** If you are going to hire me
- No work for hire.
  I own all my work.
  No exceptions.
  Work-for-hire is legal exploitation.
  However, I'm open to licensing negotiations.
- I don't care about deadlines.
  It's done when I think it's done.
  I don't care about the short-term.
  I don't have a good relationship with time.
- I do what I want how I want, unless there is a reason not to.
- I won't use any language less than Prolog.
  I'm not settling for anything less.
  I insist on using the best tool I know.
  If someday I find a better tool than Prolog, I will move again.
- I only make sure that my software runs on a recent Debian release.
  I don't care if my software doesn't run on Windows, Android, or iOS.
- I will not sign any anti-competitive agreements.
  I will not sign non-compete agreements.
  I will not sign non-disclosure agreements.
- I can change my mind at any time.

Perhaps I should hire you, not the other way around?
*** Why work for/with me? How am I from other partners/employers?
- Justice
- Fairness
- Environment
- Reasonable

Really?
Am I still the same person when I wrote that?
*** Why not work for/with me?
- I can't guarantee that you will get rich working for/with me.
- I am opinionated and principled. I do things my way.
- I am a dictator, although I try to be benevolent.
*** Principles?
- Survive.
- Sustain: minimize operation and minimize maintenance.
- Systems, not heroes.
  - But we need heroes?
** My company rules? My business rules?
All compensations must be explicit, rule-based, and justifiable.
Everyone must know the same rules.
Everyone must play by the same rules.
No tipping.

- Employer may terminate an employment at any time without notice.
- Employee may terminate his/her employment at any time without notice.
- Pay with money only.
  No bullshit perks and benefits.
  No insurance.

Refuse and skip exit interview.
Don't say anything incriminating.

"Ask the Headhunter: Why it’s risky to give notice when you quit"
https://www.youtube.com/watch?v=sBFjotmUkjA

https://www.forbes.com/sites/lizryan/2017/07/06/ten-reasons-to-skip-your-exit-interview/#5b51301e20e3

my accounting principles?

- Keep only one book.
  Don't show different books to different people.
- Accounting records historical truth.
  Don't calculate current market price in accounting reports; mark-to-market belongs in financial statements, not accounting books.
- Don't mix currencies.
- A redenominated currency is a different currency.
- Err on the side of safety.
  Don't count your eggs before they hatch.
  Recognize income as late as possible.
  Recognize expenses as early as possible.

A company with no secrets.
A transparent company.

An economic benevolent dictatorship.

Dictatorship doesn't last.
Systems last.
** Job openings and projects
*** Job openings
**** Assistant/clone
Requirements:
- Fluent in written English.
- Enjoys the stress of writing.
- Writes concisely.
- Writes precisely; cares about definitions.
- Writes conservatively; cares about etymologies.
- Reads 800 wpm with 60% comprehension when focused at prime condition.
- Likes to stay at home, and hates traveling.
- Connected to the Internet from home.
- Has an IQ above 135.
- Able and willing to eat pork.
- Uses Debian or a Debian-based distro.
- Can use Google Docs, Git, Markdown, and Org-Mode.
- Watches YouTube videos at 2x speed.

What you will do:
- Organize and clean up this website.
- Arrange my derailed train of thoughts.
- Write about things similar to what is already on this website.
- Find evidences for or against my beliefs.

Salary range:
IDR 0 - IDR 20,000,000.
* Delete?
** Insane stuffs
*** Argument for killing stupid people?
- Premises:
  - People don't change.
    - Stupid is forever.
  - Survival is moral.
    If an action is necessary for survival, then it is moral.
    - Consequence: War for survival is moral.
      If there are only two people left on Earth, and there is only one last drip of water left on Earth,
      then it is moral for those people to go to war (that is, to harm the other) for that last drip of water.
    - Consequence: Retaliation is moral.
      It is moral for X to harm Y if Y harms X first.
  - Stupid people have been harming us.
- Conclusion?
  - It is moral to kill stupid people?
- Weaknesses and problems in the argument:
  - How do we define and determine stupidity?
    We should /not/ define "stupid" as "everyone who doesn't agree with us".
*** Analogy: fixing wrong building, fixing wrong children, fixing wrong people?
- The safest action is preemptive strike:
  - When you realize that you built a house wrong, you tear down the house, and rebuild it the right way.
    - Or, you just wait until a natural disaster destroys it, and then rebuild it.
      - Let's hope that you aren't in the building when disaster strikes.
  - When you realize that you raised your child wrong, you kill it (?), and make another child (?).
    - Or, you just wait for karma to kill your child, and have another child.
      - Let's hope that your child doesn't kill you first.
  - If people don't change, then the only way to fix deluded people / persistently misbehaving people is killing them (?).
    - Or, you just wait for a war or disaster.
      - Let's hope that you're not in the shithole when shit happens.
  - We programmers tear down rotten code all the time.
    We rewrite it from scratch.
    Why don't we tear down rotten societies as well?
** "English" names
Scarface, Boaty McBoatface
Sir Lancelot, Sir Chirpsalot (chirps a lot), Sir Changealot (change a lot)
** Name-calling
A name-calling person is a insecure person who has run out of rational arguments.
** Statistics, smoking, mindfulness
Seeing statistics worries me.
Most researchers don't understand statistics.
For example, I don't need statistics to know that smoking is bad; it's obvious.
It smells bad.
It makes me dizzy.

I guess people smoke because they have peer pressure, they have a weird sense of "cool", and they are too lazy to think for themselves.

Smoking always tastes bad.
Thus it is the rationalization that makes smokers tough it out.

How to stop smoking (Does it work?)

Remember when you first smoke cigarettes.
This is my guess.
It tastes bitter.
You cough.
Your eyes water.
It hurts.
But you tough it out.
You fear that your friends will leave you if you don't smoke.

I want you to taste every cigarette in the same way you tasted your first cigarette.
It's always the first time.
Feel the unpleasant bitter taste.
** Code of conduct
- Don't be an asshole.
- Don't do things that you don't want to be done to you.
- Talk in cyberspace as you talk in meatspace.
  If you won't say it to someone you are talking with, don't write it on the Internet.

People nowadays get offended too easily.
It is possible to disagree without fighting.

What is an asshole?
If many people in the same room hate you, then maybe you are an asshole.

Swearwords show passion.
But if you use swearwords too often, they lose their meaning and impact.

Maybe sprinkle some smilies when you use swearwords.

But swearwords don't add meaning?
** Things I learned the hard way
*** <2018-10-08> While a person is on a motorcycle (be it driving or not driving), he must secure his chattels, and not place them in shirt pockets, in order to prevent the chattels from falling to the road (therefore being lost or broken).
- Secure the chattels:
  - Put it in a /totally closed compartment/ in a bag, not in a pocket on the bag.
  - Grip the chattels.
- Triggers:
  - Eyeglasses fell from shirt pocket to the road, and were run over by the motorcycle behind.
  - A few months ago, a hairband fell from bag pocket to the road; it was lost.
  - Shit happened. Twice.
** Finding bottleneck?
*** what
Make sure that the bottleneck is not in the kernel
netstat | grep
Check the number of connections
Expected jmeter number of connections

Make sure that jmeter is properly configured

https://stackoverflow.com/questions/42311414/iperf3-windows-bandwidth-is-much-slower-than-linux
iperf
sudo apt-get install iperf
Run this on PHP machine: iperf -s
Let SERVER be the IP address of the PHP machine.
Run this on JMeter machine: iperf -c SERVER

CPU tidak mentok, RAM tidak mentok, berarti ada beberapa kemungkinan:
- bottleneck di network,
- CPU di-throttle oleh docker/cgroup,
- bottleneck di disk seek rate (unnecessary SQL transaction),
- bottleneck di disk transfer rate.

If 1 request takes 1 KB, then 10000 request/second translates to 10 MB/s, which is enough to saturate a 100 Mbps Ethernet interface.

Cari tahu 1 application server sanggup serve berapa banyak.

Check
iftop -i INTERFACE

https://serverfault.com/questions/299093/linux-how-to-find-out-whether-nic-is-causing-a-bottleneck

check disk queue depth dengan top (average load)
iotop

https://serverfault.com/questions/665799/whats-the-technique-to-find-out-bottleneck/665831
- atop for cpu & ram
- iotop for disk
- iftop for network

Disable swap, but be careful to avoid running out of memory.

Pastikan bottleneck bukan di mesin JMeter (terutama di network interface-nya). Apakah mesin JMeter sudah dipisah dari mesin PHP?

Linux kernel limit: number of open files, maximum number of open sockets.

Docker bisa mengurangi performance. Kalau tidak pakai Docker, apa bisa lebih cepat?
Ganti 20 docker instance php-fpm dengan 1 php-fpm dengan 20 children.

Docker performance cost
2015 article "An Updated Performance Comparison of Virtual Machines and Linux Containers" https://domino.research.ibm.com/library/cyberdig.nsf/papers/0929052195DD819C85257D2300681E7B/$File/rc25482.pdf
That link was obtained from https://www.linode.com/docs/applications/containers/when-and-why-to-use-docker/#when-not-to-use-docker

nload is an alternative to iftop?


Use Vegeta instead of ApacheBench?
Locust? JMeter?
https://medium.freecodecamp.org/how-we-fine-tuned-haproxy-to-achieve-2-000-000-concurrent-ssl-connections-d017e61a4d27


select vs poll vs epoll
https://www.ulduzsoft.com/2014/01/select-poll-epoll-practical-difference-for-system-architects/

The C10K (10000 connection) problem
http://www.kegel.com/c10k.html


https://stackoverflow.com/questions/16888429/how-to-make-a-hard-abortive-close-on-a-tcp-connection
In bottleneck/tcp.c
Set linger onoff 1 timeout 0


http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html

https://thehftguy.com/2016/10/03/haproxy-vs-nginx-why-you-should-never-use-nginx-for-load-balancing/
*** Measuring things to find bottlenecks (Linux, TCP, HTTP, network, CPU, disk, etc.)
- How many empty TCP connections per second can a TCP endpoint accept?
  We don't want to measure transfer rate.
  We want to measure kernel bookkeeping overhead.
  - These can't do that:
    - iperf
  - Can these do that?
    - https://txlab.wordpress.com/2016/05/05/tcpkali-tcp-load-generator/
    - http://uperf.org/
    - qperf (ubuntu?)
      - https://www.opsdash.com/blog/network-performance-linux.html
      - https://access.redhat.com/solutions/2122681
- How many HTTP requests can it handle? Use ApacheBench. =sudo apt-get install apache2-utils=.
- How do we reduce the worst-case response time under high load?
- Is the Linux process scheduler fair?
- Is the Linux process scheduler time complexity O(1)?
- https://medium.com/@oscar.eriks/case-study-network-bottlenecks-on-a-linux-server-part-2-the-kernel-88cf614aae70
- Which is better, select or epoll?
**** Linux TCP TIME_WAIT exhaustion on busy server
- What are my options?
  - Assign more IP addresses.
  - Geographically distribute the application.
    Procure edge servers closer to the clients.
    But you can't do this if you are not a CDN or ISP.
  - Reduce the TIME_WAIT MSL (maximum segment lifetime)
    - http://www.lognormal.com/blog/2012/09/27/linux-tcpip-tuning/
    - This makes TCP incorrect, but in the case of a load balancer, the probability of the incorrectness is negligible (unless it's an attack, or it's behind a NAT).
    - =net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait = 1=
  - Non-options
    - =net.ipv4.tcp_tw_recycle= has been removed.
    - =net.ipv4.tcp_tw_reuse= doesn't work.
  - https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux
    - https://news.ycombinator.com/item?id=7684015
    - "The universal solution is to /increase the number of possible quadruplets/ by using, for example, more server ports."
    - "Moreover, when designing protocols, /don’t let clients close first/."
- See the TCP protocol documentation.
  Where are the wait states?
  Who hold the wait states?
  The client?
  The server?
  The one who calls the =close= system call?
** Maximizing lithium-ion battery life
- https://batteryuniversity.com/learn/article/how_to_prolong_lithium_based_batteries
  - "Exposing the battery to high temperature and dwelling in a full state-of-charge for an extended time can be more stressful than cycling."
  - "In terms of longevity, the optimal charge voltage is 3.92V/cell."
  - "Every 70mV drop in charge voltage lowers the usable capacity by about 10%."
  - "Partial charging negates the benefit of Li-ion in terms of high specific energy."
  - "Chalmers University of Technology, Sweden, reports that using a reduced charge level of 50% SOC increases the lifetime expectancy of the vehicle Li-ion battery by 44–130%."
  - "For safety reasons, many lithium-ions cannot exceed 4.20V/cell."
  - "Industrial devices, such as the EV, typically limit the charge to 85% and discharge to 25% to prolong battery life."
    - "Why Mobile Phone Batteries do not last as long as an EV Battery" https://batteryuniversity.com/index.php/learn/article/why_mobile_phone_batteries_do_not_last_as_long_as_an_ev_battery
  - "The question is asked, “Should I disconnect my laptop from the power grid when not in use?”
    Under normal circumstances this should not be necessary because charging stops when the Li-ion battery is full.
    A topping charge is only applied when the battery voltage drops to a certain level.
    Most users do not remove the AC power, and this practice is safe."
    - "Always keep the airflow unobstructed when running electric devices with air-cooling on a bed or pillow."
** Natural sciences
- Physics and engineering
  - Civil engineering
    - [How Do Sinkholes Form?](https://www.youtube.com/watch?v=e-DVIQPqS8E)
      - Internal erosion, piping, etc.
    - [YT:Why Concrete Needs Reinforcement](https://www.youtube.com/watch?v=cZINeaDjisY)
      - three types of stresses: tensile, compressive, shear
    - [What's inside Ikea's "wood"?](https://www.youtube.com/watch?v=24F5JlKkxR4)
    - Architecture
      - [YT:Open office is overrated](https://www.youtube.com/watch?v=-p6WWRarjNs)
    - Softwood vs hardwood
      - Softwood is gymnosperm (monocot) wood.
      - Hardwood is angiosperm (dicot) wood.
      - Softwood isn't always softer than hardwood.
      - https://en.wikipedia.org/wiki/Softwood
      - https://en.wikipedia.org/wiki/Hardwood
      - https://en.wikipedia.org/wiki/Dicotyledon#Comparison_with_monocotyledons
- Science in 21st century is multi-/inter-discipline?
  - All branches of science cross-pollinate?
  - It's no longer useful to categorize science by branches?
  - Where is the boundary between two branches?
    - Where do physics end and chemistry begin?
- Philosophy
  - Does everything fall under philosophy?
    - How do we prevent this category from becoming a kitchen sink?
    - Philosophy is everywhere (a cross-cutting concern), so it shouldn't be a category.
** Ramblings, speculations, fantasies, imaginations, and trivias
*** Acting
- I rarely watch movies.
- I'm sure there are other good actors, actresses, and movies.
- But I'm not watching all the movies in this world.
- Examples of good acting
  - Adewale Akinnuoye-Agbaje in "Faster"
  - Christoph Waltz as Hans Landa in "Inglourious Bastards"
  - Heath Ledger as Joker in which Batman movie?
- Examples of good movies
  - films directed by Christopher Nolan
    - "Interstellar"
    - "Inception"
*** Quantum inertia? Rocket propulsion? What?
- https://www.reddit.com/r/compsci/comments/9kxiiu/what_new_thing_are_you_currently_learning_in_your/
*** Curing cancer?
**** Trading cancer with autoimmune disease?
Trading something bad with something hopefully less bad?
https://arstechnica.com/science/2018/10/treatments-that-cause-the-immune-system-to-attack-cancer-earn-a-nobel/
*** Where ethics and design meet
  - [[http://mrmrs.cc/writing/2016/03/23/the-veil-of-ignorance/][Applying John Rawls's "veil of ignorance" argument to web design]]
*** (Why the hell did I bother to find out about these things?)
**** Physics textbook

- [[http://www.lightandmatter.com/area1sn.html][Simple Nature, an online physics textbook]]: for beginner, too wordy for me.

**** Browser plugins (I don't necessarily use)

- Vimium: vim-like shortcuts for navigating the chromium browser
  - [[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en][Install from Chrome Web Store]]
  - [[https://github.com/philc/vimium][Source code on GitHub]]
- Perhaps I should make a browser plugin that copies a link of the page to the clipboard in Markdown format?
  No. A bookmarklet suffices.
  - Which browser has easiest plugin development?
    - The result might be suspicious because I used Google to look for the answer.
    - 2016: Chrome ([[https://www.quora.com/Is-it-easier-to-write-a-plug-in-extension-for-Chrome-or-Firefox][source]])
    - 2011: Chrome ([[https://stackoverflow.com/questions/6438329/which-browser-is-easier-to-develop-plug-ins-for-chrome-or-firefox][source]])

**** Judaism, kareth, gays, and lesbians
   :PROPERTIES:
   :CUSTOM_ID: judaism-kareth-gays-and-lesbians
   :END:

- [[https://en.wikipedia.org/wiki/Kareth][WP:Kareth]]

  - It is interesting that a gay is punishable by kareth, but a lesbian is not punishable by kareth.

    - See item no. 4: "A male having sexual intercourse with another male".
      It doesn't say anything about "a female having sexual intercourse with another female".

  - It doesn't mean that Judaism allows lesbianism.
    There may be other rules somewhere else.
  - [[https://en.wikipedia.org/wiki/Homosexuality_and_Judaism][WP:Homosexuality and Judaism]]
**** Quartz scheduler performance
  - http://airboxlab.github.io/performance/scalability/scheduler/quartz/2017/06/20/perf_tuning_quartz.html
  - https://www.ebayinc.com/stories/blogs/tech/performance-tuning-on-quartz-scheduler/
  - https://stackoverflow.com/questions/11565993/quartz-performance
**** Picking colors
  - theories and principles
    - [[https://usabilla.com/blog/how-to-design-for-color-blindness/][How to Design for Color Blindness]]
    - [[http://www.tigercolor.com/color-lab/color-theory/color-harmonies.htm][Color Harmonies: complementary, analogous, triadic color schemes]]
  - tools
    - [[http://www.hsluv.org/][HSLUV: human-friendly /perceptually uniform/ color picker]]
      - [[https://en.wikipedia.org/wiki/CIELUV][Wikipedia: CIELUV color space]]
      - [[https://arxiv.org/abs/1509.03700][Good colour maps: how to design them]], 2015, Peter Kovesi
    - [[https://leaverou.github.io/contrast-ratio/][Lea Verou's contrast ratio checker tool]]
**** Peterson v Newman on Channel 4 is not journalism

[[https://www.youtube.com/watch?v=aMcjxSThD54][video]]

Newman is putting her words on Peterson's mouth.

Peterson has the patience of a saint.

It is not journalism.
It is a mere entertainment.
Verbal boxing.
Spectacle.
**** Accommodation Ontology Language Reference?
- http://ontologies.sti-innsbruck.at/acco/ns.html
*** Accounting
- I use GnuCash for my personal accounting.
- Accounting terms
  - What is an account?
    - If you deposit money in banks, then you have an account for every bank account you have.
    - If you lend money to people, then you have an account for every people.
  - What is a journal?
    - A journal is optimized for entering transactions by date.
    - What is a transaction?
      - A transaction involves two or more accounts.
        - The sum of all account changes in a transaction is zero.
  - What is a subledger (subsidiary ledger)?
    - A subledger of account C is obtained by selecting only the journal entries that affect the account C.
  - What is a general ledger?
    - A general ledger is the concatenation/combination/summation of several subledgers.
- Are there open source enterprise accounting systems?
*** FOSS alternative to SmartRecruiters?

https://blog.capterra.com/top-8-freeopen-source-applicant-tracking-software-solutions/
*** Learning languages
**** Cantonese
http://wikitravel.org/en/Cantonese_phrasebook

The biggest problem of Cantonese:
it doesn't have /standard/ romanization like Hanyu Pinyin, does it?
Cantonese has three: Jyutping Romanization, Yale Romanization, and Cantonese Pinyin.
It unnecessarily fragments learning resources.

https://en.wikipedia.org/wiki/Cantonese_Pinyin

6 tones.

- 1: high
- 2: low-to-high
- 3: flat mid
- 4: low-to-even-lower
- 5: low-to-mid
- 6:

Which is the romanization, Yale or Jyutping?
Yale vs Jyutping:
https://en.wikipedia.org/wiki/Cantonese#Phonology
https://en.wikipedia.org/wiki/Hong_Kong_Government_Cantonese_Romanisation

https://en.wikipedia.org/wiki/Cantonese_phonology#Cantonese_syllables

http://cantonese.ca/

http://www.cantonese.sheik.co.uk/dictionary/words/42086/#jyutpinginfo

我 ngo5 = I

你 nei5 = you

今日 gam1 jat6 = today

我係 ...
ngo5 hai6 ...
= I am ... (name, occupation)

我係今日返屋企㗎。
ngo5 hai6 gam1 jat6 faan1 uk1 kei5/2 gaa2/3/4

你以為我係邊個呀？
nei5 ji5 wai4 ngo5 hai6 bin1 go3 aa3/4/5/1?
Who do you think I am? / Do you know who I am?

https://www.youtube.com/watch?v=Pg0xsKyA1Uw

ngo5 hai6 yat1 jek maau = I am a cat

yat jek gau = a dog
**** Russian
[[https://ria.ru/][RIA news agency website]]

[[https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0][Заглавная страница]]
(Russian Wikipedia main page)

Словарь
dictionary

проверить
check

Избранная статья
selected articles

Случайная статья
random article

Биография
biography

Окончил Калькуттский окружной колледж.
He graduated from the Calcutta District College.

человек
human

Человек изучает и изменяет себя и окружающий мир, создаёт культуру и собственную историю.
A person studies and changes himself and the surrounding world, creates a culture and own history.

Тело человека имеет ряд отличий от обезьян.
The human body has a number of differences from monkeys

Знаете ли вы?
Did you know?

Текущие события
current events

Новости news

News categories:
главное main
общество society
наука science

Коалиция США нанесла новый удар по проправительственным силам в Сирии

The US coalition struck a new blow against the pro-government forces in Syria
**** German
- teil
  - teilen = divide
  - geteilt = divided
  - unteilbar = indivisible
- bis = to
- Tisch
  - der Tisch = the table
  - die Tische = the tables
  - auf dem Tisch = on the table
  - auf den Tischen = on the tables
- Bitte melden Sie sich an, um zu kommentieren. = Please log in to comment.
  - from https://www.zeit.de/campus/2018-08/altersvorsorge-rente-angst-zukunft-fragen
  - bitte = please
  - melden = log in
  - Sie = you
  - sich = yourself
  - "an" modifies "melden"
  - um zu kommentieren = in order to comment
  - More literal translation: "Please log you yourself in in order to comment."
- langlebig = long-lived
- kurzlebig = short-lived
**** Mandarin
- Where can I learn Mandarin?
- What are the five tones?

  - 1
  - 2
  - 3
  - 4
  - 5

- Set up input method
- Dictionary
- Thesaurus
- Basic grammar
- Set phrases
- [[https://www.fluentu.com/blog/chinese/2015/02/18/simple-mandarin-chinese-sentences-examples/][5 Solid Structures for Building Simple Mandarin Chinese Sentences]]
- Chinese computer terms

  - https://www.writtenchinese.com/stop-being-n00b-learn-computer-words-chinese/
  - https://www.fluentu.com/blog/chinese/2011/10/10/chinese-vocabulary-word-list-computer-internet/
  - https://chinese.stackexchange.com/questions/6375/chinese-computer-vocabulary-and-most-frequently-encountered-common-computer-ter

- Where are example sentences?
- Reading hanzi

  - [[https://www.coscom.co.jp/japanesekanji/kanji02_2001.html][How to learn Kanji Efficiently]]
  - Various orderings

    - by frequency of use

      - https://en.wikipedia.org/wiki/List_of_kanji_radicals_by_frequency
      - [[https://kanjicards.org/kanji-list-by-freq.html][Kanji ordered by frequency of use - Kanjicards.org]]

    - https://en.wikipedia.org/wiki/List_of_kanji_by_concept
    - https://en.wikipedia.org/wiki/List_of_kanji_radicals_by_stroke_count

  - https://en.wikipedia.org/wiki/Radical_(Chinese_characters)
  - Use wiktionary to look up Han character origins (Bronze inscriptions)

- How does Mandarin absorb loanwords, foreign terms, foreign proper names?

  - Examples

    - How does [[https://en.wikipedia.org/wiki/Las_Vegas][WP:Las Vegas]] become [[https://zh.wikipedia.org/wiki/%E6%8B%89%E6%96%AF%E7%BB%B4%E5%8A%A0%E6%96%AF][WP:拉斯维加斯]] (lā sī wéi jiā sī)?
    - How does [[https://en.wikipedia.org/wiki/India][WP:India]] become [[https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%BA%A6][WP:印度]] (yìn dù)?
    - How does [[https://en.wikipedia.org/wiki/Indonesia][WP:Indonesia]] become [[https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%BA%A6%E5%B0%BC%E8%A5%BF%E4%BA%9A][WP:印度尼西亚]] (yìn dù ní xī yà)?
    - How does [[https://en.wikipedia.org/wiki/Saddam_Hussein][WP:Saddam Hussein]] become [[https://zh.wikipedia.org/wiki/%E8%90%A8%E8%BE%BE%E5%A7%86%C2%B7%E4%BE%AF%E8%B5%9B%E5%9B%A0][WP:萨达姆·侯赛因]] (sà dá mǔ hóu sài yīn)?
    - How does [[https://en.wikipedia.org/wiki/George_W._Bush][WP:George Walker Bush]] become [[https://zh.wikipedia.org/wiki/%E4%B9%94%E6%B2%BB%C2%B7%E6%B2%83%E5%85%8B%C2%B7%E5%B8%83%E4%BB%80][WP:乔治·沃克·布什]] (qiáo zhì wò kè bù shí)?

  - If every character has a meaning, how do we specify sound without meaning?
  - https://www.quora.com/How-are-foreign-names-written-in-Chinese
  - [[http://www.cjvlang.com/Writing/fornames.html][How Chinese, Japanese, and Vietnamese handle foreign names]]
  - [[https://www.fluentinmandarin.com/content/how-do-you-write-foreignenglish-names-in-chinese/][How do you write foreign or English names in Chinese?]]
  - [[https://en.wikipedia.org/wiki/Transcription_into_Chinese_characters][WP:Transcription into Chinese characters]]
  - https://chinese.stackexchange.com/questions/2270/why-do-chinese-translations-of-english-names-sound-very-inaccurate

- 2018, [[https://www.youtube.com/watch?v=OA_g2bQgOXY][How KaiOS Is Becoming the 3rd Major Mobile OS - YouTube]]
- What is Chinese equivalent of Twitter, Google, Facebook, Wikipedia, Google Scholar?

  - Google - baidu
  - Wikipedia - baike

- 雅加达 yǎ jiā dá - Jakarta
- 新闻 xīn wén - news
- 好事 hǎo shì - good thing, good deed

  - https://baike.baidu.com/item/%E5%A5%BD%E4%BA%8B

    - Is that an encyclopedia or a dictionary?

      - 词 cí - word
      - "X"一词 X yī cí - the word "X"
      - 通常 - tōng cháng - generally, usually

- [[http://tags.news.sina.com.cn/%E9%9B%85%E5%8A%A0%E8%BE%BE][sina.com Jakarta news in Mandarin]]

  - http://sports.sina.com.cn/others/fencing/2018-08-16/doc-ihhvciiv7596331.shtml

    - 击剑冠军孙伟将任亚运火炬手 fencing champion Sun Wei will assume the post of Asian Games torchbearer

      - 击剑 jí jiàn - fencing - anggar
      - 冠军 guàn jūn - champion - juara
      - 孙伟 sūn wěi - Sun Wei (name)
      - 将 jiāng - will, be going to, soon - akan
      - 任 rèn - to take charge of; to assume the post of
      - 亚运 yà yùn - Asian Games

        - 亚 abbreviation of 亚细亚 yà xì yà - Asia
        - 亚运 abbreviation of 亚洲运动会 yà zhōu yùn dòng huì - Asian Games

      - 火炬手 huǒ jù shǒu - torchbearer (火 fire, 火炬 torch, 手 hand) - pembawa obor

    - 上届斩获两枚奖牌 last time (he) seized two medals

      - 上届 shàng jiè - previous; last
      - 斩获 zhǎn huò - to seize

        - 斩 behead, cut
        - 获 catch, obtain, capture

      - 两枚 奖牌 liǎng méi jiǎng pái - two medals

        - 枚 counter word for small flat objects; similar to Indonesian "keping"

          - https://en.wiktionary.org/wiki/%E6%9E%9A#Chinese

    - 8月18日，第十八届亚运会将在印尼雅加达举行。 (On) August 18th, the 18th Asian Games will take place (be held) in Jakarta, Indonesia.

      - 8月18日 (八月十八日) bā yuè shí bā rì - August 18th
      - 第十八届 dì shí bā jiè - the 18th time
      - 亚运会 yàyùn huì - Asian Games
      - 将 jiàng - will
      - 在 zài - in, at
      - 印尼 yìn ní - abbreviation of Indonesia
      - 雅加达 yǎ jiā dá - Jakarta
      - 举行 jǔ xíng - to hold (a meeting, reception, etc.) - menyelenggarakan
**** Japanese
- Introduction

  - [[https://pomax.github.io/nrGrammar/#section-3-More_grammar][An introduction to Japanese]]
  - [[https://www.tofugu.com/japanese/borrowing-language/][Japanese: The Borrower Language]]

- Japanese grammar

  - [[http://kwhazit.ucoz.net/ranma/g_vaux.html][Japanese Verb Auxiliaries]]
  - [[https://en.wikipedia.org/wiki/Japanese_counter_word#Euphonic_changes][Japanese counter word - Wikipedia]]

- Japanese vocabulary

  - [[http://www.linguanaut.com/english_japanese.htm][Japanese Phrases]]

- Reading kanji

  - See "Reading hanzi" in [[file:%7B%%20link%20mandarin.md%20%%7D][Learning Mandarin]].

- Ubuntu 14.04

  - ibus-anthy for input method
  - gjiten for dictionary
  - What?

    - xelatex

- Newspapers

  - Asahi shimbun
  - Jakarta shimbun

- Communities

  - [[https://www.reddit.com/r/ja/][日本reddit]]
**** Bahasa Indonesia
- Apa beda manjur, mempan, mujarab, dan mustajab?
***** Some Indonesian vernaculars
Spoken Indonesian is wildly different from written Indonesian and news Indonesian.
On the street, nobody speak like news anchors.
****** Dong, kek
"Gitu dong!" (with emphasis on tu)
"Nah, gitu dong!"
"Gitu kek dari tadi!"
That's what I wanted you to do!
If only you had shut up and done that earlier,
we wouldn't have had to fight.

"Iiiih diem dong!"
(Can't you shut up!?)

"Ga bisa gitu dong!"
"Enak aja lu!"
"Apaan!?"
"Dari mana!?"
"Atas dasar apa!?"
(Typical response to outrage-inducing unfairness, injustice, or absurdity.
What the hell?
You can't do that!)
****** Doang, sih, aja
"Gitu doang?"
(Is that all? Is that all you got?)

"Segitu doang kemampuanlu? Cupu banget sih lu!"
(Is that all you got? You piece of shit!)

"Kenapa sih tiap kali gua datang, ada aja masalah..."
(I'm dying to know why there is always a problem every time I come.)

"Gitu doang ngambek"
"Gitu aja marah"
(Why the hell are you angry for such trivial thing?)

"Coba diem dulu deh!!"
Can't you shut up for a while?

"Eh ini enak. Cobain deh..."
This is delicious. Here, try some!

"Iya aja deh"
"Apa katalu dah"
(Whatever you say.)

"Masih aja!"
(Why the hell are you still doing this?
Haven't I told you to stop already?)

"Ini aja?" (Is this everything?)
"Iya ini aja"
"Iya ini doang" (Yes, it's everything.)
****** Deh
"Eh iya deh."
(Oops, I was wrong.)
(Oops, I just remembered.)

"Iya maaf deh."
(Sorry. Whatever. Are you happy now?)
****** Kok
"Kok lu masih idup?"
(Why the hell are you still alive?)

"Kok lu di sini?"
"Kok lu di sini sih?"
(Why are you here? You aren't supposed to be here.)

"Udah dikerjain kok PR-nya Ma."
(What the hell are you accusing me for Mum?
I have done my homework, you know.)

A: "Eh ini kok gini? dapet dari mana?"
(Huh? Why is this? Where does this come from?)
B: "Ya iya dong. Masa gini aja lu ga ngerti?"
(I'm getting impatient.
Isn't it obvious?
You can't understand something this simple?)

"Gitu aja kok repot" (trademark alm. Gus Dur)
"Why so much hassle over such small matter?"
(I think Joker's (as played by Heath Ledger) "Why so serious?" also fits this somewhat.)
****** Lah, lho or loh
"Ya begitulah"
(More or less that's the case.)

"Ya begitulah"
(a vague and rather polite response that does not mean anything;
this avoids making the other party think you are ignoring him/her)

"Ya begitulah"
"Ya begitulah... lu tau sendiri kan"
"Mau gimana lagi?"
仕方ない
(Nothing can be done about it; What else can be done?)

"Lho kok masih di sini?"
(Why the hell are you still here?)

"Lho kok belum dikerjain?"
(Why the hell haven't you done this?)

"Iya lho"
"Bener lho"
(I'm serious. I'm not lying.)

"Lho lho lho"
(Wait, what?)

"Gue gitu loh"
(Of course I can do that. I'm the greatest.)
****** Toh
"Oh gitu toh"
そうですか。
なるほど。
I see.
****** Lain-lain
"Mampus... gw lupa matiin kompor!"
(Shit! I forgot to turn off the stove.)
**** English
***** Present perfect tense, past perfect tense
- https://englishlive.ef.com/blog/language-lab/english-grammar-help-present-perfect-and-past-perfect/
  - I did X = I did X in the past?
  - I has X = I did X, and I finished doing X, but I can still feel its effects now
  - I had X = I did X, and I finished doing X, and I don't feel its effects now
  - past tense vs past perfect tense?
***** will vs be going to
- https://www.perfect-english-grammar.com/will-or-be-going-to.html
***** Favorite shortenings
   :PROPERTIES:
   :CUSTOM_ID: favorite-shortenings
   :END:

- to obviate X = to make X unnecessary

  - similar: replace, supersede, deprecate

- to fudgel = to pretend to work while in reality you are not doing anything ([[https://en.wiktionary.org/wiki/fudgel][Wiktionary]])

  - to procrastinate = to put off; to delay ([[https://en.wiktionary.org/wiki/procrastinate][Wiktionary]])

- to lucubrate = to work diligently by artificial light; to study at night [[https://en.wiktionary.org/wiki/lucubrate][Wiktionary]]
- https://en.wiktionary.org/wiki/Thesaurus:laugh

***** Colorful synonyms of bad
   :PROPERTIES:
   :CUSTOM_ID: colorful-synonyms-of-bad
   :END:

- bad: improper, intolerable, unacceptable, undesirable
- awkward, clunky
- kludge, hack, ugly
- oversentimentally bad: kitsch, corny
- disappointingly bad: suck, hopeless
- almost/borderline bad: mediocre
- very bad: terrible, abysmal, disturbing
- scarily bad: dreadful, horrendous, horrifying, horrible
- ethically/morally bad: shady, sketchy, questionable, scandalous, criminal
- cruelly/violently bad: atrocious, brutal
- disgustingly bad: abominable
- much/excessively bad: shitload, truckload, crapload, boatload
- irritatingly bad: annoying, frustrating, exasperating
- hatefully bad: shitty, half-assed, crummy, crappy, cruddy
- outrageously bad: [goddamn] [worthless] [motherfucking] [truckload of / piece of] [shit / crap]
  (the order of adjectives is important)
- https://en.wiktionary.org/wiki/Thesaurus:bad

***** Synonyms of insane
   :PROPERTIES:
   :CUSTOM_ID: synonyms-of-insane
   :END:

- crank, crackpot, wacko, kook
- lunatic
- deranged
- delusional
- https://en.wiktionary.org/wiki/Thesaurus:insane

***** razmatazz, claptrap, humbug
   :PROPERTIES:
   :CUSTOM_ID: razmatazz-claptrap-humbug
   :END:

***** Researches
   :PROPERTIES:
   :CUSTOM_ID: researches
   :END:

- 2015 article "Vocabulary Learning Strategies",
  [[https://jyx.jyu.fi/handle/123456789/49945][abstract]],
  [[https://jyx.jyu.fi/bitstream/handle/123456789/49945/vls.pdf][pdf]]
***** How does swapping the subject and the predicate changes the meaning of a copular sentence (a sentence whose verb is the copula)? Subject-predicate asymmetry?
We consider sentences of these forms: "X is Y" and "Y is X", where each of X and Y is a noun phrase.

We are interested in how swapping X and Y changes the meaning of the sentence.
****** Example
- John is the culprit.
- The culprit is John.
****** Example
- Mark Twain is Samuel Langhorne Clemens.
- Samuel Langhorne Clemens is Mark Twain.
****** Example
- The dog is a Siberian husky.
- A Siberian husky is the dog.
****** Example
- Dogs are animals.
- Animals are dogs.
****** Example
- The car is red.
- Red is the car.
*** Learning to play mahjong
  :PROPERTIES:
  :CUSTOM_ID: learning-to-play-mahjong
  :END:

The variant discussed here is classic Chinese mahjong.

**** Basic facts
   :PROPERTIES:
   :CUSTOM_ID: basic-facts
   :END:

There are 136 mahjong tiles,
of which 52 are dealed to the players.
The remaining 84 forms the wall.
Thus, in a play, you only get at most 21 chances to change your hand,
that is 84 divided by 4 (the number of players).

If each player takes 15 seconds, then a hand
will take at most 4 x 15 x 21 = 1,260 seconds (21 minutes).

There are 136 tiles (not including 4 flower tiles and 4 season tiles):

There are 3 suits (bams, dots, and chars). Each suit has 9 classes. Each number has 4 instances. Thus each suit has 36 tiles. Thus there are 108 suit tiles.

There are 7 honors (4 winds and 3 dragons). Each honor has 4 instances. Thus there are 28 honor tiles.

There are 27 suit classes and 7 honor classes, giving a total of 34 classes.

Each tile class has 4 instances.

Each tile is equally probable to be drawn.

The probability of picking a tile class is 4/136. The odds of picking a tile class is 4:132.

**** Number of chows, pungs, and kongs
   :PROPERTIES:
   :CUSTOM_ID: number-of-chows-pungs-and-kongs
   :END:

The probability of drawing a pung:
34 * 4/136 * 3/135 * 2/134 = 1/3,015 (odd of 1 : 3,014, approx 1 : 3,000)

Each suit has 7 unique chows: 123, 234, 345, 456, 567, 678, 789.
There are 3 suits, so there are 21 unique chows.
Each tile has 4 instances.
Each chow has 4^3 instances.
The probability of drawing a chow: 21 * 4^3 / (136 * 135 * 134) = 28 / 51,255
(odd of 1 : 51,227, approx 1 : 51,000).

Pung is more likely than chow. Is this a calculation mistake?

The probability of drawing a kong (four identical tiles):
34 * 4/136 * 3/135 * 2/134 * 1/133 = 1/400,995 (odd of 1 : 400,994, approx 1 : 401,000)

The probability of drawing a pair:
34 * 4/136 * 3/135 = 1/45 (odd of 1 : 44)

The probability of drawing two tiles having the same class:
4/136 * 3/135 = 1/1,530 (odd of 1 : 1,529)

The probability of drawing two tiles having the same suit (3 suits):
3 * 36/136 * 35/135 = 7/34 (odd of 7 : 27, approx 1 : 4)

The probability of drawing a chow:
The probability of drawing n, n+1, n+2 unordered of the same suit, for n in 1 to 7:

3! * 3 * 7 * 4/136 * 4/135 * 4/134 = 56/17,085 (odd of 56 : 17,029, about 1 : 304)

The probability of drawing a pair, given that one tile has been drawn by another player:

Let each player draw exactly one tile. The probability of four players drawing the same tile:
34 * 4/136 * 3/135 * 2/134 * 1/133 = the probability of drawing a kong
*** Traffic engineering
  :PROPERTIES:
  :CUSTOM_ID: traffic-engineering
  :END:

- Everyone has different willingness for travel.

  - Some travel is necessary.

    - Travel to work. Travel to make economic transactions.
    - This is ideally as efficient and fast as possible.
    - This forms the inelastic baseline demand.

  - The rest of travel is discretionary.

    - Travel to leisure.
    - This is ideally as enjoyable as possible.
    - This forms the elastic demand.

- Is induced demand theory correct?

  - Disagreements

    - https://www.cato.org/blog/debunking-induced-demand-myth

  - Agreements

    - http://plazaperspective.com/road-widening/
    - "Induced demand means that for every person that switches from driving to an alternative, another driver will take their place."
    - [[https://www.youtube.com/watch?v=N4PW66_g6XA][How to Fix Traffic Forever]]

      - Counterintuitive

        - If road demand already exceeds supply, then widening roads increases traffic and causes more congestion.

          - [[https://en.wikipedia.org/wiki/Induced_demand][WP:Induced demand]]

- [[https://www.youtube.com/watch?v=Akm7ik-H_7U][The high cost of free parking]]
- [[https://helper.ipam.ucla.edu/publications/tratut/tratut_12985.pdf][A Mathematical Introduction to Traffic Flow Theory]]
- Related

  - [[https://en.wikipedia.org/wiki/Traffic_engineering_(transportation)][WP:Traffic engineering (transportation)]]
*** Outdated content that I do not intend to update
**** Android development in 2016
Last time I developed for Android in 2012.
My knowledge is irrelevant now.
- http://blog.teamtreehouse.com/android-libraries-use-every-project
- https://github.com/codepath/android_guides/wiki/Must-Have-Libraries
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instances-and-amis.html
**** Web scraping with Haskell
- Easily manipulate DOM using [scalpel](https://hackage.haskell.org/package/scalpel),
  which uses [tagsoup](https://hackage.haskell.org/package/tagsoup).
  - Consume and produce REST API using
    [a Haskell REST framework](http://engineering.silk.co/post/90354057868/announcing-rest-a-haskell-rest-framework).
  - [A rather low-level approach](https://www.schoolofhaskell.com/school/to-infinity-and-beyond/competition-winners/interfacing-with-restful-json-apis).
  - We need an HTTP REST API.
    There are many ways of passing parameters: query string, http header, multipart.
    Request body can contain bytes, or JSON.
    Needs jsonification and dejsonification.
  - [HXT](https://wiki.haskell.org/HXT): how is this package organized?
  - [Building a concurrent web scraper with Haskell](http://adit.io/posts/2012-03-10-building_a_concurrent_web_scraper_with_haskell.html)
**** btpn
- Syarat-syarat saya

  - Apa yang menarik?
    Mengapa harus peduli?

    - Bunga 5% per tahun?
    - Gratis biaya transfer?

      - Internet banking?
      - ATM?
      - Giro?

    - Penting nggak?

      - https://www.jenius.com/basic_question/apa-keuntungan-saya-memakai-jenius/

  - Seaman apa?

    - Apa simpanan dijamin LPS (Lembaga Penjamin Simpanan)?
      2018-08-09: [[https://www.jenius.com/basic_question/apakah-uang-yang-saya-simpan-di-jenius-aman/][Ya.]]

      - Apa BTPN peserta LPS?
        2018-08-09: Ya. Cari "pensiun" di [[http://lps.go.id/bank-peserta-penjaminan][daftar LPS]].

        - BTPN singkatan apa?

          - 2018-08-09:

            - Di [[https://www.btpn.com/][situs resmi]] sendiri malah tidak ada?
            - Menurut daftar LPS: "PT Bank Tabungan Pensiunan Nasional Tbk."

    - Apa bank ini akan bangkrut?
      Apa bank ini too big to fail?
    - BTPN punya siapa?

      - 2018-08-09: menurut [[https://www.btpn.com/id/hubungan-investor/komposisi-pemegang-saham-dan-struktur-organisasi-grup][sumber]]:

        - 39.9% punya Sumitomo Mitsui Banking Corporation (perusahaan Jepang)
        - 20% punya Summit Global Capital Management B.V. (perusahaan Belanda)

          - ujung-ujungnya Sumitomo Corporation

            - "The company operates as a subsidiary of Sumitomo Corporation." [[https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=285795044][sumber]]

        - 40.1% punya publik (people mostly holding very little share)

      - Kok ada "nasional" di namanya?
        Kirain punya negara?

        - Emang arti "nasional" apa?
          Menyebar di suatu negara?
          Dimiliki negara?

          - https://en.wikipedia.org/wiki/National_bank

  - Bagaimana cara buka rekening?

    - https://www.jenius.com/topic/jenius-registration/
    - [[https://www.jenius.com/basic_question/apakah-saya-harus-menjadi-nasabah-btpn-untuk-menikmati-layanan-aplikasi-jenius/][Buka akun Jenius, otomatis jadi "bagian" BTPN.]]

      - [[https://www.jenius.com/basic_question/already-btpn-account-can-change-transfer-account-jenius/][Tidak berlaku sebaliknya.]]

  - Siapa counterparty kontrak saya jika saya membuka rekening Jenius?
  - Apakah data saya akan bocor ke pihak ketiga?

    - Bagaimana saya melarang BTPN membocorkan data saya ke pihak ketiga?

      - Apakah saya harus menerima semua syarat yang dibuat tanpa melibatkan saya?
        Kalau tidak mau ya jangan pakai?

- How much money are you losing by not switching?
**** violin
This is my study notes, observations, and conclusions.
This is a bit disorganized.

I play the violin without chin rest and shoulder rest.
***** The right pinky
The right pinky is for playing softly:
tilt the bow very slightly by pressing down the pinky (with the thumb as the fulcrum).
XXX: Is it by flexing the pinky or by supinating the hand?

Playing softly is harder than playing loudly.
Playing softly also uses more tension than playing loudly.
***** Squeaking
Each bow speed has a range of pressure that will make a good sound.
Less bow speed needs less pressure.
The symptom of too much pressure for a bow speed is squeaking;
increase the bow speed, or decrease the bow pressure, or both.

Decrease the bow pressure by pressing the end of the bow with the right pinky,
with the thumb as the fulcrum.
***** Playing open strings
Open strings, especially the A and E strings,
sound brighter than stopped strings,
so open strings will be perceived as louder
even though the bow speed and pressure stay the same.
In order to play scales with even dynamics,
we can avoid open strings,
or we can bow the open strings more softly
with reduced pressure and speed.

Also, we can play the D string nearer to the bridge to brighten it,
and the A string nearer to the fingerboard to darken it,
to make the change from the D to the A string smoother.
***** Idea for group practice
Learning Kreutzer etudes together?
***** Bouncing bows
The hairs act as a spring.

Vertical component of stick-slip.

Act as torque with the right thumb as the fulcrum.
**** wikia
[[http://dizzy.pestermom.com/][KimikoMuffin]]
has [[http://dizzy.pestermom.com/?p=nowikia][some strong reasons for not using Wikia]].

Wikipedia does not own Wikia, but
[[http://money.cnn.com/magazines/business2/business2_archive/2007/03/01/8401010/][who owns Wikipedia also owns Wikia]]:
Jimmy Wales owns a share of Wikipedia and also a share of Wikia.
Whenever you make a Wikia site,
you're working, unpaid, for him and the other owners.
[[http://shouldiworkforfree.com/][Why would you work for free?]]
(By the way, Wikipedia also has its share of unpleasant stories,
but that's for another post.)

An alternative that will give you more freedom
(and ownership, but also more responsibility)
is hosting on your own domain,
but this needs some technical understanding.

The bad news is that Wikia is the leader for niche wikis
and there doesn't seem to be any meaningful [[http://alternativeto.net/software/wikia/][competition]]:
Google search result for niche gaming queries is typically full of Wikia articles.
In the meantime, you can try [[http://www.shoutwiki.com/wiki/Main_Page][Shoutwiki]]
(there's even a wiki named [[http://awa.shoutwiki.com/wiki/Anti-Wikia_Alliance][Anti-Wikia Alliance]]) or
[[http://www.gamepedia.com/][Gamepedia]].
*** <2016-03-22> The reason for the name spacetimecat.com
In jazz-speak, a /cat/ is a jazz musician, and
I'm a jazz musician traveling through spacetime;
hence the name /spacetime cat/.

However, most importantly, the domain is a dot-com,
and it was available, untouched by rent-seeking domain speculators.

Another reason is that the name isn't tied to shady stuffs
and doesn't have unwanted connotations.
A quick google shows that the worst result
for 'spacetime cat' is cat pictures,
which should be pretty safe for everyone
except perhaps a few extreme cat haters.

It's also nice that the name
isn't too hard to remember or spell,
but it's hard to get it wrong.

Hence I bought spacetimecat.com.
* Mathematics?
- Writing mathematics
  - 1989, article, "Mathematical writing", Donald E. Knuth, Tracy Larrabee, and Paul M. Roberts, [pdf](http://jmlr.csail.mit.edu/reviewing-papers/knuth_mathematical_writing.pdf)
    - "Many readers will skim over formulas on their first reading of your exposition.
      Therefore, your sentences should flow smoothly when all but the simplest formulas are replaced by 'blah' or some other grunting noise. (p. 3)
- Reference articles
  - Which point of view should we use?
    - We can see a function as a special kind of relation.
    - We can see a relation from \( A \) to \( B \) as a function from \( A \) to \( 2^B \).
      - Every binary relation \((A,B,r)\) is a function \((A,2^B,f)\)
        where \(f(x) = \{ y ~\|~ r(x,y) \}\).
    - Which is more primitive: function or relation?
** Math, learning, and brain?
https://dyske.com/paper/825
"When I was in 7th grade, my math teacher answered an obvious but difficult question:
Why do we have to study advanced math, if we are never going to use it in our adult lives?
He said it’s because the same parts of our brains used for math can be used for many other things in life.
With this short explanation, he utterly convinced me the importance of studying math, and of any other subjects for that matter."
* Everything after this doesn't belong in this page
** <2018-11-19> I changed my mind. Now I think most of this page is a waste of time.
Thanks to John Stossel and Steve Patterson.

If I could solve the libertarian children problem, I would be a libertarian by now.

Is antinatalism against nature?
Yes, if humans have innate drive to breed (to have have an offspring).
No, if humans have innate drive to fuck only (to satisfy the genitals, not including breeding).

I'm more inclined toward survivalism than antinatalism.

Antinatalism is noble but impractical.
The reality is that billions of low-IQ people are going to fuck and breed anyway,
producing low-IQ children who never question anything, repeating the stupidity of their parents, perpetuating the cycle.
But this may be practical in the future:
Inconspicuous forced mass sterilization!
Airborne human-sterilizing nanobots!
Human-sterilizing viruses!
Infertility-causing foods!
http://wiki.c2.com/?HumanSterilizationVirus

Is this just a waste of time?
Is this going to change anything?

Goal:
Establish a benevolent dictatorship with these principles:
- Peace of mind.
  - No overtime.
  - No deadlines.
  - No loans.
  - If growth robs you of peace of mind, don't grow.
** What? Socialism? Communism? Understanding communism before criticizing it?
Marx's stages of society
https://en.wikipedia.org/wiki/Marx%27s_theory_of_history

Ganti upah minimum dengan universal basic income atau negative tax rate

Embedding communism in capitalism

Embedding capitalism in communism

Reconciling capitalism and communism

Communism should not be defined as an opposite to capitalism.
"Abolition" is negative definition.

Communism doesn't require central government.
*** Examples of local communism?
Israel kibbutz? https://en.wikipedia.org/wiki/Kibbutz

Can we have communism without centralization?
It's absurd to have a central authority that decides who to make how much what.

https://en.wikipedia.org/wiki/Primitive_communism
*** Is sharing communism?
Is ridesharing (Gojek, Grab, Uber, Lyft, etc.) communism?
** TODO reorganize; from politics.md
- What is the Government of China afraid of?
  - The Government of China isn't afraid of criticism. It is afraid of collective action. [King2013]
- Why are cannabis and heroin illegal?
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/6h6med/daily_reminder_about_the_true_purpose_of_the_war/][/r/LateStageCapitalism: John Ehrlichman: Nixon illegalized drugs to stigmatize hippies (cannabis) and blacks (heroin) because those people were against him.]]
  - Cannabis overuse permanently damages teen brains.
  - Another theory: cotton farmers vs hemp farmers?
- Reddit: CrazyIdeas
  - procreation license https://www.reddit.com/r/CrazyIdeas/comments/17yniw/you_need_a_license_to_have_children/
    - Are people more likely to be killed by other people (war, genocide, holocaust) or by cars?
  - https://www.reddit.com/r/CrazyIdeas/comments/3x8fr5/seeing_as_the_1_have_nearly_everything_lets_just/
  - https://www.reddit.com/r/CrazyIdeas/comments/6alqe1/make_a_handy_guide_of_democratic_and_republican/
  - impractical
    - https://www.reddit.com/r/CrazyIdeas/comments/6cu2yf/we_all_join_isis_so_there_isnt_anyone_left_for/
    - [[https://www.reddit.com/r/FunnyandSad/comments/7h7p3u/if_everyone_was_given_one_free_totally_legal_kill/][give everyone one free totally legal kill]]
- Who is Donald Trump's greatest opponent?
  - Donald Trump is the person who disagrees most with Donald Trump.
    - [[https://twitter.com/DonTrumpsTrump][Twitter: DonTrumpsTrump]],
      [[https://www.reddit.com/r/TrumpCriticizesTrump/][/r/TrumpCriticizesTrump]]
    - [[https://www.youtube.com/watch?v=kSE-XoVKaXg][YouTube: PlainSight: Trump exposes Trump]]
  - Ignore what politicians /say/.
    See what they /do/.
    See where their money comes from.
    See where their money goes to.
    Talk is easy.
    - But who is going to read through the
      [[https://en.wikipedia.org/wiki/List_of_executive_actions_by_Donald_Trump][list of executive actions by Donald Trump]]
      to find out who he really is?
      Will someone summarize?
- Who else trash-talk like Donald Trump does?
  - Thomas Jefferson, according to [[https://www.youtube.com/watch?v=ZIv7dQ9tt30][Adam Ruins Everything - Other Donald Trumps Throughout History]]
  - and lots of people in the colonial era, according to [[https://www.readex.com/readex-report/slinging-mud-and-talking-trash-gutter-age-american-journalism][Slinging Mud and Talking Trash: The Gutter Age of American Journalism]]
- Syrian war
  - [[https://www.quora.com/Is-Assad-bombing-his-people-If-so-why-do-many-people-support-him][Quora: Is Assad bombing his people? If so, why do many people support him?]]
- How do we fix the justice system?
  - Replace retributive justice with restorative justice.
    - Focus on fixing the damage, not on punishing people.
    - Norway gets the prison system right by "restorative justice" as opposed to American "retributive justice".
  - Society should help people fix their mistakes and reintegrate to society.
    - [[https://www.youtube.com/watch?v=RfU8TUZRtZg][Homeless guy spits some truth.]]
- [[https://www.youtube.com/watch?v=5tu32CCA_Ig][Corruption is legal in America]], 6-minute video
  - https://represent.us/
  - https://anticorruptionact.org/
- Wars are still happening. They just moved from overt to covert.
  - [[https://en.wikipedia.org/wiki/War_Is_a_Racket][WP: War is a racket]], Smedley D. Butler, 1935
- [[https://www.politico.eu/article/12-people-and-things-that-ruined-iran-energy-shah-regime-islamism/][Politico: 12 people and things that ruined Iran]]
  - Iran has a traumatic past. History has shown that it can't trust anyone, even its neighbor Iraq. Thus Iran wants self-sufficiency at all costs.
  - Self-sufficiency is a necessary but not sufficient condition for independence.
    - If you trade with other nations, you depend on them.
    - Trade (and specialization of labor) is beneficial for everybody if everybody is fair.
  - What is the difference between "independence" and "sovereignty"?
- Undigested
  - How can the minority control the majority?
    - https://en.wikipedia.org/wiki/Big_man_(political_science)
  - [[https://www.youtube.com/watch?v=rStL7niR7gs&feature=youtu.be][CGP Grey: The Rules for Rulers]]
    - "The Dictator's Handbook", Bruce Bueno de Mesquita
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/7bd6xm/how_to_bribe_a_lawmaker_101/]["Lobbying" /is/ "bribing"]].
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/8i4y3a/new_un_report_finds_almost_no_industry_profitable/][New UN report finds almost no industry profitable if environmental costs were included]]
  - History, politics, military, war, weapon
    - https://www.reddit.com/r/explainlikeimfive/comments/1fy1na/eli5_why_did_joseph_stalin_kill_so_many_people/
    - [[http://www.historyisaweapon.com/defcon1/zinncol1.html][Native American Holocaust]]
    - Reddit: LateStageCapitalism
      - https://www.reddit.com/r/LateStageCapitalism/comments/6ilw3q/war_who_is_it_good_for/
      - https://www.reddit.com/r/LateStageCapitalism/comments/6cqcm3/if_youre_unemployed_it_is_not_because_there_isnt/
    - Best attack aircraft? https://en.wikipedia.org/wiki/Fairchild_Republic_A-10_Thunderbolt_II
    - What does manifest destiny have to do with American Imperialism?
      - [[https://en.wikipedia.org/wiki/Manifest_destiny][WP:Manifest destiny]]
      - [[https://en.wikipedia.org/wiki/American_imperialism][WP:American imperialism]]
  - [[https://www.ranker.com/list/the-best-way-to-fix-the-american-political-system/desertrat89][The Best Way to Fix The American Political System]]
  - History
    - https://history.stackexchange.com/questions/32480/why-would-some-nations-want-to-force-japan-to-end-their-isolation
  - [[https://www.youtube.com/watch?v=257wV-AbKaE][How does money laundering work? - Delena D. Spann]]
  - Free speech is only possible if people think critically.
  - Democracy is only possible if people think critically. - Democracy assumes that the electors are educated;
    otherwise the candidates will manipulate the electors
    using public media and sensitive issues. - Examples: - US in 2016 (Trump) - Indonesia in 2017 (Anies-Sandi)
    - [[https://www.youtube.com/watch?v=fLJBzhcSWTk][Why Socrates hated democracy]]?
      - Because the average person isn't competent to rule a country.
- YouTube: user: The school of life
  - [[https://www.youtube.com/watch?v=shanIOl7MyE][The Perfect Country]]
  - [[https://www.youtube.com/watch?v=Y9zThcMJzQU][How to Make a Country Rich]]
- Why is the US defense budget so huge?
  - https://www.reddit.com/r/explainlikeimfive/comments/3b5ogu/eli5_why_is_the_united_states_defense_budget_so/
  - https://www.quora.com/Why-does-the-United-States-have-such-a-large-military-budget
  - My guesses
    - The US defense budget is so huge because it's dealing with the entire Earth, not only the US?
    - Also, no competition in the defense sector?
      It's inefficient?
      It has no incentive to be efficient.
      Compare how competition (such as SpaceX)
      could cut down the cost of launching rockets.
- Why is Britain helping Israel?
- [[https://www.youtube.com/watch?v=rStL7niR7gs][The Rules for Rulers]]
- [[https://www.quora.com/Whats-the-story-of-SoftBank-Where-does-it-get-so-much-money-to-invest-from][Quora: What's the story of SoftBank? Where does it get so much money to invest from?]]
  - by investing in Alibaba
- If a law does not prescribe any punishment, will you obey it?
- Should we just die when we cannot pay the hospital bills?
  - If your death would ruin your family, should you have a family?
- Data source for salaries of various positions in the US: Foreign labor certification wage library
  - In the US, salary isn't secret, especially if you're a foreigner.
- No matter how evil or stupid politicians may seem, they do it with a reason?
  - Which makes it worse?
    - They're evil on purpose?
  - How do politicians reason?
    - Keep it simple?
      - If politicians are honest:
        - They represent their voters.
          - They reflect the people who vote for them.
  - Is [[https://en.wikipedia.org/wiki/Hanlon%27s_razor][WP:Hanlon's razor]] applicable?
- [[https://en.wikipedia.org/wiki/Politician][WP:Politician]]
- [[https://en.wikipedia.org/wiki/Politics][WP:Politics]]
- [[https://www.youtube.com/watch?v=3JVR0zAiyw0][YT:Putin on ideology - difference between Americans and Russians]],
  American individualisn, Russian collectivism
- [[https://www.quora.com/Is-there-one-website-to-daily-summarize-everything-that-is-going-on-in-Washington][Quora:Is there one website to daily summarize everything that is going on in Washington?]]
- [[https://en.wikipedia.org/wiki/Public_sphere][WP:Public sphere]]
- I don't always agree with these, but these have some useful things.
  - [[https://stallman.org/][Richard Stallman's personal site]]
    - What's bad about X (company)?
- [[https://www.reuters.com/article/us-usa-rights-un/americas-poor-becoming-more-destitute-under-trump-u-n-expert-idUSKCN1IY0C3][America's poor becoming more destitute under Trump: U.N. expert]]
  - https://www.theschooloflife.com/thebookoflife/countries-for-losers-countries-for-winners/
    - https://www.youtube.com/watch?v=kbpY-2nOYRI
- [[https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences][Why do politicians diverge from their constituents' preferences?]]
  - "the very idea of representative democracy is based on the fact that the preferences of the individual constituents
    do not make for good decisions in complex questions."
  - TODO group this with Socrates's argument
- Political economy
  - https://en.wikipedia.org/wiki/Employer_of_last_resort
    - https://en.wikipedia.org/wiki/Civilian_Conservation_Corps
    - [[http://www.levyinstitute.org/pubs/wp_534.pdf][Argentina: A Case Study on the "Plan Jefes y Jefas de Hogar
      Desocupados", or the Employment Road to Economic Recovery]]
- Justin Trudeau: "Donald Trump was elected on a promise to help the millions of middle-class families who feel left out of the success and progress of the past decades, and, interestingly enough, that is exactly the promise I got elected on, too."
  - https://www.quora.com/How-does-Justin-Trudeau-view-Canadas-relationship-with-the-US-in-light-of-Donald-Trump-winning-the-US-presidential-election/answer/Justin-Trudeau
- [[https://www.youtube.com/watch?v=c_Eutci7ack][How to understand power - Eric Liu]]
- [[https://www.youtube.com/watch?v=Cd0JH1AreDw][Eric Liu: Why ordinary people need to understand power]]
  - civics is the study of power
  - cities can practically bypass national governments
- Stop fluoridating water
  - Gaia: The Actual Truth About Fluoride, [[https://www.youtube.com/watch?v=HAagzF6D-nE][youtube]]
- [[https://www.politicalcompass.org/][Political compass]]: plotting economical-political views in two-dimensional space
- [[https://www.washingtonpost.com/world/asia_pacific/chinas-all-powerful-leader-should-heed-the-lessons-from-history-former-official-says/2017/11/09/22e7987a-c39a-11e7-a441-3a768c8586f1_story.html?noredirect=on&utm_term=.5dcdb36d3ff0][China's all-powerful leader should heed the lessons from history, former official says - The Washington Post]]
- We should limit inheritance.
  - Each child should inherit at most 1 house, 1 car, and cash sufficient for him to reach an age of 30.
- [[https://www.youtube.com/watch?v=o0ONByhAHC4][Why the wars America starts are unwinnable - Danny Sjursen - YouTube]]
- [[https://www.youtube.com/watch?v=U7DdgUAWR-s][What America gets wrong about China and the rest of Asia - David Kang - YouTube]]
  - China isn't a rising power. It has always been big.
  - Big nations have big internal (intra-nation) struggles.
  - Most big nations (such as the old Chinese dynasties) fall due to internal struggles.
- Has Google been artificially diversifying its employees by discriminating against Caucasian and Asian men?
  See James Damore lawsuit.
  - [[https://twitter.com/jamesadamore][James Damore on Twitter]]
- [[https://www.youtube.com/watch?v=IESYMFtLIis][Why societies collapse | Jared Diamond - YouTube]]
  - One possible reason:
    - conflict of interest
      - Elites make self-serving decisions that are good for themselves in the short term but bad for the society in the long term.
      - Those elites don't directly feel the bad consequences of their decisions.
- China
  - http://www.cirosantilli.com/
    - https://github.com/cirosantilli/china-dictatorship/blob/master/FAQ.adoc
- The goal of a career politician is to get reelected.
  - How do we create a system that makes sure that one is reelected if and only if he works according to the people's desires,
    and one is taken down as soon as he strays from the people's desires?
    - How do we create a system that is robust, that depends only minimally on the electees, that works for a wide variety of malicious electees?
      - How do we make government fear the people, and people fear the government?
        How do we make mutual fear?
- [[https://www.youtube.com/watch?v=UyohSu-Ft_U][The Grand Theory of Amazon - YouTube]]
  - Amazon is a scale company.
    It specializes in scaling.
- The solution is to make corruption impossible and irrelevant.
- Work-for-hire (WFH) contracts should be illegal, and be replaced with irrevocable licensing.
  Every man should own his own labor.
  Work-for-hire contributes to social injustice.
- Solution to extremism/radicalism:
  Make it a law that every copy of Quran/Bible/other holy book must be accompanied with historical context.
  The book should prescribe how it should be interpreted.
  People should not invent their own interpretations.
  The interpretation must be justified by historical context.
  - [[http://aboutislam.net/counseling/ask-about-islam/why-does-the-quran-require-context/][Why Does the Quran Require Context? | About Islam]]
  - [[https://www.sbs.com.au/news/why-the-historical-context-of-the-qur-an-and-the-bible-cannot-be-ignored][Why the historical context of the Qur'an and the Bible cannot be ignored]]
  - synonyms: interpretation, exegesis, tafsir
- How much political power do we have?
  - [[https://www.theatlantic.com/magazine/archive/2015/07/power-quiz/395273/][How Much Political Power Do You Have? - The Atlantic]]
  - [[http://www.bbc.co.uk/guides/zpyr4wx][BBC iWonder - Do you know how much political power is in your pocket?]]
- office politics
  - [[http://www.yourofficecoach.com/coaching-resources/office-politics/political-games/how-much-political-power-do-you-have][How Much Political Power Do You Have? - Your Office Coach]]
- [[https://edition.cnn.com/2015/02/16/opinion/schmitt-politics-money/index.html][Money's power in politics: Give everyone a share - CNN]]
- [[https://www.crummy.com/2004/11/01/2][How To Exercise Political Power Part 1]]
** <2018-10-03> It's 2018, but people still believe in flat Earth and trickle-down economics.
According to https://www.forbes.com/sites/teresaghilarducci/2018/09/28/who-benefits-from-the-tax-cut-10-months-later/#3af0b9dc26bb:
- "Buybacks are attractive because most CEO pay is directly linked to stock values and not to productive capital expansion."
** Anarchism?
1995 book "What Is Anarchism? An Introduction"
https://theanarchistlibrary.org/library/donald-rooum-and-freedom-press-ed-what-is-anarchism-an-introduction
*** Letter to anarchists: Say "self-governance" instead of "anarchism"; focus on making what you want, not on avoiding what you hate
Your goal is noble, but, for your message to be acceptable by the people,
you must use the word "self-governance" instead of "anarchy".
No need to change anything else, just replace all occurrences of "anarchy" with "self-governance".
This will make your speeches and writings infinitely more acceptable
to the uneducated people that you need.
No more wasting time explaining what "anarchy" really is.

It does not benefit you to use a word that has been redefined by everyone else.
Your meaning of "anarchy" dates back to Proudhon's 1840 treatise "What is property?"
It's 2018, almost 200 years since Proudhon,
and the topmost Google search result for "anarchy" today
is "a state of disorder due to absence or nonrecognition of authority".
You see, even the dictionaries and the Internet are conspiring against you.
Nobody wins a fight against the Internet.
You need a new word.

The word "anarchy" focuses on the absence of a ruler.
It gives the impression that you are a belligerent forever
plotting a coup d'etat against your nemesis the government.
You don't want that.
You want to maximize everyone's freedom,
and you want people to associate voluntarily,
which is to say that they self-govern.
The word "self-governance" gives the impression that you are
a youthful progressive bunch of people
with positive success mindset brimming with can-do attitude.
It sounds like bullshit, but flowery bullshit sells better than ugly truth.

It's unfortunate that words change meanings, but language changes with the people who speak it.
You won't see any progress until you change the word you use to spread your message.

The word "anarchy" is, in today's context, bad for marketing your cause.

Thus, from now on, say and write "self-governance" instead of "anarchy".
** Privacy
*** Re-identification: Pieces of anonymized information about a subject can be combined to identify the subject.
[[https://arstechnica.com/tech-policy/2009/09/your-secrets-live-online-in-databases-of-ruin/][“Anonymized” data really isn’t—and here’s why not | Ars Technica]]

- Massachusetts Group Insurance Commission
- AOL
- Netflix
- etc.

Browser fingerprinting
*** Is advertising ethical?
- Happiness = Expectation - Reality.
- Advertising increases expectation.
- Therefore advertising reduces happiness.
- But without advertising, how will people know that you even exist?
  How are you going to have customers at all?
- Advertising should be replaced with information.
- https://twitter.com/oxcsh/status/1055953330328010753
** Government/state
*** Deregulation of USA

- [[https://www.youtube.com/watch?v=TuAg-RaZ4Is][Trump Is 'Destroying' Regulations - YouTube]]

Trump needs a cooperative Congress in order for him to be able to repeal more laws.

*** Antonin Scalia: The key to American freedom is the separation of power, not the Bill of Rights.

https://www.youtube.com/watch?v=Ggz_gd--UO0

The USSR Constitution guarantees more freedom than the USA Constitution, but the USSR failed to prevent the centralization of power.

Every dictatorship has bill of rights.

North Korea has elections.

*** Evolution justifies governments

Evolution suggests that cooperation improves survival (in the long run, of the species, not of an individual).

Evolution suggests that morality improves survival.

Evolution suggests that government improves survival.

What is the state for?
Why do we need government?
To promote the survival of the governed species.

**** Government is not to merely maintain public order.

Public order can be undesirable:

- We don't want a government that oppresses people in order to maintain public order.
- The overthrowing of a tyrant may be a desirable public disorder.

To promote survival of the people? As in evolution?

To better the people?
To impose the morality of the people?
A government reflects the morality of its people.

We must impose our morality on others.
The law imposes the lawmakers' morality on everyone.
It is practically impossible to live without imposing your morality on others.
There is a minimum decency that we expect when we interact with others.

The enforcement of law is an imposition of the morality of the lawmakers (and therefore of the people who elected the lawmakers).

https://www.quora.com/Should-the-law-impose-morality

**** Social apoptosis? Programmed human death?

Some cells must die to better the organism.
Some people should die to better the society?
Programmed cell death ~ programmed human death?

A malfunctioning cell kills itself.
It would be nice if a malfunctioning human could kill himself?

A cell infected by a virus kills itself.
It would be nice if a human infected by ideological virus (mind virus) could kill himself?

How do we know we're infected?

**** Why should our survival be desirable at all?

**** Human rights are legal fiction.

What is real is tolerance.
People let other people live.
If I am still alive, it's because others let me live,
because others tolerate me,
not because I have any rights.

**** Justifying freedom
   :PROPERTIES:
   :CUSTOM_ID: justifying-freedom
   :END:

- Hypotheses:

  - People do/produce best (the highest quantity for the lowest price) when they pursue what they want to do/produce.
  - People approach their strengths and leave their weaknesses.
  - Different people have different goals.
  - Higher intrinsic motivation increases willingness to accept lower pay.

*** It is insane that every country makes their own laws.
   :PROPERTIES:
   :CUSTOM_ID: it-is-insane-that-every-country-makes-their-own-laws.
   :END:

Software engineers share as much as possible to avoid repeating work.
They use operating systems, libraries.

Legislators could share more work.

Most software engineers use the same operating system.
Every country has its own constitution.
This is an insane amount of duplication.

There should be a "software library" for laws.
Laws should be reusable.
It should be able to legislate
"law X of country Y also holds in country Z, provided that every occurrence of X is replaced by Z".

- [[https://en.wikipedia.org/wiki/Don%27t_repeat_yourself][WP:Don't repeat yourself]]
- [[https://en.wikipedia.org/wiki/World_government][WP:World government]]
- [[https://www.quora.com/There-is-only-one-country-in-the-world-and-there-are-no-borders-no-need-for-passports-People-can-travel-freely-and-there-is-a-similar-legal-and-economic-system-for-everyone-in-the-world-What-do-you-think-of-this-idea][Quora question about world government]]
*** A government is a cancer that parasitizes its host country?
Government exists because people are too lazy to think.
People want the government to nanny them.
People blame the government for everything.
In reality they cause their own misery.
** Insurance
We should limit health insurance to catastrophic conditions only.
https://www.youtube.com/watch?v=3WnS96NVlMI

2017
"These Doctors Got Fed Up With Insurance. Now They Treat Their Patients Like Valued Customers."
https://www.youtube.com/watch?v=6-Vqjo2S1us

** Leaving Greenpeace
- [[https://www.youtube.com/watch?v=BpBnJq19R60][video]] of Patrick Moore's reasons for leaving Greenpeace
* Does not belong in this page?
** LSEV (low-speed electric vehicle)
- Big in China: Tiny Electric Cars [[https://www.youtube.com/watch?v=kILXXaqspcI][video]]
  - $1,000 for a car that fits 2 adults and goes up to 60 km/h.
** "Sanity" does not exist
"an experiment conducted to determine the validity of psychiatric diagnosis"
https://en.wikipedia.org/wiki/Rosenhan_experiment
** Antivaccinism is parental negligence.
http://www.thejakartapost.com/news/2018/09/05/rubella-kills-baby-in-jambi-as-vaccination-campaign-meets-resistance.html

What is the difference between killing and letting die?
What is the difference between deliberately killing and deliberately letting die?
** Political economics
*** Economic ramblings
How may private interests give rise to integrated intermodal transportation?

Raising minimum wage increases unemployment

Bezos (Amazon) didn't raise minimum wages out of kindness.
He did it to pressure everybody to pressure Wal-Mart (an Amazon competitor).
Enemy of Capitalism: Capitalists
https://www.youtube.com/watch?v=nFe9N0BX8mM

Governments shouldn't guarantee bank deposits.
Governments should not encourage people to save too much money at banks.
Governments should encourage trade.

Employers love immigration.
Immigration makes cheap workers.
Illegal immigrants are even cheaper.

The pro-immigration people hide that desire behind pretend humanitarianism.
They don't care about cultural stability, as they live in their safe enclaves, protected by the government they bribe, far away from where immigrants live.

Better watch John Stossel than watch Bernie Sanders.
https://www.youtube.com/watch?v=YydE0IGKPXw

https://www.quora.com/What-dirt-is-there-on-Bernie-Sanders-Whats-out-there-that-might-spoil-his-chances-in-his-presidential-run
*** Minimum wage hurts the very people it is supposed to protect.
First, pandering politicians raise minimum wage.

Then, companies scramble to avoid bankruptcy.
A company has several options:
- Do nothing; keep the workers, bear the cost. (Do you think the company will happily accept the reduced profit, if it still profits at all?)
- Raise prices, passing costs to buyers. (But then the buyers will buy less. Law of supply and demand.)
- Cut costs by reducing quality. (But will the buyers still buy?)
- Train the workers to make them more productive. (But how far can we train people?)
- Fire the workers, move to somewhere with cheaper workers.
- Fire the workers, buy robots.

https://www.minimumwage.com/

Political propaganda can't change the basic economic law of supply and demand.
This law is more fundamental than the politician-made laws.
Political fantasy can't change economic reality.
Ignore reality at your own peril.

I think workers should negotiate with their employers, and there is no need to involve government.

Disagreements.

Does minimum wage have different consequences in developing countries?
Minimum wage in developing countries may have no effect on employment, because the companies have bigger profit margins?
- 2009 "Minimum wage effects in a developing country" https://www.sciencedirect.com/science/article/abs/pii/S0927537108000547

(Indonesian) https://tirto.id/penghapusan-upah-minimum-bagi-negara-miskin-dinilai-tidak-tepat-cLgW
*** Is the world better without private ownership?
Nobody needs to be rich?
What we really seek is satisfaction.
We should be happy if others find us useful, if others want us to stay, if others want us to exist.

If people's basic needs are met, they will still work, but they will only do what they really want to do.

Personal property is OK.
Is private non-moving property OK?

https://kk.org/thetechnium/better-than-own/

https://www.quora.com/How-would-a-world-without-money-ownership-and-monetary-value-operate
*** Analogy: Marx were a doctor, capitalism were the disease, Marxism was the cure that was worse than the disease.
- Jordan Peterson Vs Marxist Professor Richard Wolff https://www.youtube.com/watch?v=HTj17c4N9vI
  - Marx predicted some bad consequences of capitalism, but the cure he proposed was worse than the disease.
  - However, Jordan Peterson says that inequality is not due to capitalism, but because small successes breeds even bigger successes.
    - When something good happens to you, it increases the probability that something else good also happens to you.
      - That (string of luck) spirals out of control, and we don't know what to do about it.
        - Luck begets more luck.
          Success begets more success.
          Money begets more money.
          (If you know what you're doing.)
** Bible and homosexuality
The Bible clearly prohibits sodomy.
But The Bible clearly does not prohibit other sexual activities between two men, such as kissing, frotting, hugging, sleeping together.

* Entertainment
** 21st century news
- [[https://www.liputan6.com/regional/read/3618529/bocah-bocah-terciduk-saat-asyik-dugem-di-diskotek-berkedok-toko-es-krim][Bocah-Bocah Terciduk Saat Asyik Dugem di Diskotek Berkedok Toko Es Krim - Regional Liputan6.com]]
  - from [[https://www.reddit.com/r/indonesia/comments/97s1o2/bocahbocah_terciduk_saat_asyik_dugem_di_diskotek/][reddit]]
- [[https://regional.kompas.com/read/2017/05/10/15213361/tommy.soeharto.dianugerahi.gelar.gus.oleh.ulama.di.jatim][Tommy Soeharto Dianugerahi Gelar "Gus" oleh Ulama di Jatim - Kompas.com]]
  - [[https://nasional.tempo.co/read/10122/kronologi-kasus-tommy-soeharto][Kronologi Kasus Tommy Soeharto - Nasional Tempo.co]]
  - [[https://tirto.id/pembunuhan-hakim-syafiuddin-yang-dirancang-tommy-soeharto-cPVT][Pembunuhan Hakim Syafiuddin yang Dirancang Tommy Soeharto - Tirto.ID]]
  - [[https://seword.com/politik/sadisnya-pembunuhan-hakim-kartasasmita-oleh-tommy-soeharto-ryLUQSUYG][Sadisnya Pembunuhan Hakim Kartasasmita oleh Tommy Soeharto - Seword]]
** Other entertainment
an0nymooose
ooooOOOOOOOOOOOOOOOOH
https://www.youtube.com/watch?v=nSRpbNru5aw&list=PLbZ4aMR4f3Sd_rvr40AYy_spbBu_xZGgA&index=8

[Vinesauce] Vinny - Best of The Choicest Voice
https://www.youtube.com/watch?v=SB9Cpjd7PxI

Treadmill falls apart
https://www.youtube.com/watch?v=XanTpm8dxMU
from 1:24 of "YOU may LAUGH TO DEATH - Funny compilation" https://www.youtube.com/watch?v=j9dLVJgT79M

- How To Get Affordable Healthcare | We the Internet TV https://www.youtube.com/watch?v=JoIXpKUFDtM
- HateF**k Dating App | We The Internet TV https://www.youtube.com/watch?v=z4-qbrvx9f0

What the fuck are these guys wearing?
"Kanye West & Lil Pump ft. Adele Givens - "I Love It" (Official Music Video)"
- https://www.youtube.com/watch?v=cwQgjq0mCdE

Café In Thailand Lets You Play With A Pack Of Huskies
https://www.youtube.com/watch?v=hjrl-G0vySY

a dank meme: Trump, Kim, and "pees are stored in the balls"[fn::https://www.reddit.com/r/dankmemes/comments/8qi1pt/supreme_leader_sees_the_light/]
* Indonesian stuffs
** Catatan: semua ini baru ide; masih bisa berubah.
*** Ini apa?
Halaman ini berisi campuran beberapa hal:

- cita-cita/rencana untuk Indonesia
- riset/pembelajaran secara umum, terutama yang berkaitan dengan politik, ekonomi, sosial
- urusan yang ada kaitannya dengan pemerintah/negara
*** Apa masalah terbesar Indonesia? Apa akar masalahnya?
- https://www.galena.co.id/q/apa-masalah-terbesar-di-indonesia

Analyze causal chain.

Apa yang tampak (kenyataan di lapangan)?
Apa sebab langsungnya?
Apa sebabnya?
Apa sebabnya lagi?
Dan seterusnya.

- Wealth gap / kesenjangan ekonomi / severe inequality.
  Mana yang lebih penting: mengurangi wealth gap, atau memperbaiki worst case kehidupan?
*** <2018-09-26> Ganti /retributive justice/ dengan /restorative justice/.
**** Ideas and principles
Punishment is replaced with compensation.

The state /mediates/ (facilitates dialog between) the perpetrator and the victim.
The judge, perpetrator, and victim negotiate the compensation.
It can be money, labor, anything.

Imprisonment is reserved only for the unchangeable criminals.
**** Problem: Philosophical issues, definitions
A judge is to establish justice.
What is justice?
What is fairness?

Which do we judge: the person himself, or his deeds?
To judge a person is to opine (to form an opinion) about that person, but on what basis, according to which rules?

What do judges do?
What are judges supposed to do, according to the political systems our ancestors designed?

What is the history of judges?
How did judges come into being?

Jown Rawlins's veil-of-ignorance idea:
We know that a society is /just/, if we don't mind being born in that society
without being able to choose who we are going to be born as.

What is a just society for disabled people?

It is not his fault that he was born disabled.

Justice requires blame (assigning/attributing faults to people).
**** Problem: What do judges do then, if their daily tasks are given to the mediators?
- https://www.sokanu.com/careers/judge/
- https://www.nolo.com/legal-encyclopedia/what-judges-actually.html
- https://en.wikipedia.org/wiki/Judge
**** Kesulitan
- Berapa besar usaha yang diperlukan untuk mengubah sistem hukum yang sekarang?
- Bagaimana rencana transisi?
- Bagaimana memastikan sistem tidak disalahgunakan?
- Bagaimana meminimalkan kerusakan yang mungkin ditimbulkan hakim yang salah?
**** Rencana?
- Siapa yang berwenang mengubah sistem hukum indonesia menjadi restorative justice?
- Bagaimana melobi pihak berwenang?
*** Obtain political power?
**** TODO <2018-09-17> Join a think tank or a political party or both?

- https://onthinktanks.org/articles/what-can-indonesian-research-institutes-learn-from-chinese-think-tanks/
- http://www.ksi-indonesia.org/in/home
- http://www.thejakartapost.com/news/2017/02/03/indonesian-groups-among-worlds-influential-think-tanks-report.html
- https://id.wikipedia.org/wiki/Wadah_pemikir

**** TODO <2018-09-17> Educate the people about critical thinking, religion, history, power, and politics?
**** TODO <2018-09-22> Own a media company, or piggyback existing media?
**** Mungkin tidak perlu jadi anggota legislatif? Mungkin bisa dengan mendirikan ormas (organisasi masyarakat) atau yayasan?
UU no 17 tahun 2013, penjelasan pasal 59 ayat 4:
'Yang dimaksud dengan "ajaran atau paham yang bertentangan dengan Pancasila" adalah ajaran ateisme, komunisme/marxisme-leninisme.'

2016 [[http://rubernews.com/2016/05/14/kapolri-keluarkan-aturan-penindakan-penyebaran-paham-komunisme/][berita]]:
"Kapolri Badrodin Haiti menekankan penindakan hukum juga dilakukan pada mereka yang memakai atribut komunisme,
memposting foto palu arit, pemutaran film yang memuat paham komunisme, termasuk memproduksi dan melakukan penyitaan barang bukti."

https://historia.id/modern/articles/pasal-karet-larangan-penyebaran-komunisme-DbNL9

<2018-10-01>
Komunisme di Indonesia sudah tidak ada sejak tahun 1965-an.
Sekarang tahun 2018.
Sudah 50 tahun berlalu.
Tidak perlu takut.
Seandainya ada yang mencoba membangkitkan komunisme di Indonesia, kemungkinan besar akan ditolak oleh masyarakat.
**** Tidak perlu bikin organisasi secara formal, cukup himpun orang-orang yang bercita-cita sama.
Tunda bikin badan hukum sampai perlu melibatkan uang besar.
**** Using the media in politics
- The role of the media in politics:
    - The media should research/watch/monitor/summarize/audit the government for the public.
    - The media should therefore be owned by the public, and independent of the government. The media should not be funded with tax.
    - The media shapes the public opinion.
    - The media bridges the government and the public.
    - The public doesn't have the time to watch the government.
- The media is the public's opinion of the government.
- The media is whatever the public sees.
    - Shadow/private media: social media, websites, chat groups.
        - "Shadow" in the same sense as "shadow banking".
            - "Shadow" here means unofficial/non-traditional but effective.
        - They may contain hoaxes, fake news, disinformations, and the like.
- How do the public form opinion?
    - Public opinion is country-scale groupthink?
- https://www.thebalancecareers.com/how-politicians-use-media-to-win-elections-2315204
- http://www.ethicssage.com/2016/10/the-role-of-the-media-in-politics.html
- https://study.com/academy/lesson/how-the-media-covers-elections-other-government-activities.html
*** <2018-10-02> Ajar cara berpikir di sekolah
Unfortunately the brain doesn't come with an instruction manual.
**** Interpret human language using probabilistic logic, not classical logic; every adjective is continuous, not binary
Degree of truth is continuous, not binary.
**** Distinguish between facts and opinions
**** Think for yourself
**** Eat healthily
**** Objective reality, wishful thinking
**** Self-awareness of one's own thoughts
**** Justifying actions; requiring reasons for things; asking why; goal-directed behavior
*** Establish low-operational-cost power generation and transportation: solar power plants and sun-powered trucks.

Kita harus lepas dari pengaruh geopolitik minyak bumi supaya kita tidak terpengaruh pertengkaran negara lain.

Komponen termahal biaya operasional transportasi jarak jauh adalah bahan bakar fosil.

- <2018-09-29>
  - https://www.theguardian.com/business/2018/may/17/what-are-the-factors-driving-up-the-price-of-crude-oil
  - https://www.thehindu.com/business/Economy/why-are-crude-oil-prices-going-up/article23937146.ece
  - "Saudi Arabia Promised More Oil. So Why Are Prices Rising?" https://www.nytimes.com/2018/07/04/business/energy-environment/oil-prices-opec.html
  - https://www.thebalance.com/what-makes-oil-prices-so-high-3305654
  - https://now.tufts.edu/articles/why-price-oil-rising
  - https://www.quora.com/Gasoline-How-long-does-it-take-for-the-change-in-crude-oil-price-to-reach-end-consumers
    - My conclusion: Prices are quick to rise and slow to fall.
    - https://www.aol.com/2011/03/18/why-gas-prices-rise-quickly-but-fall-slowly/
    - https://www.telegraph.co.uk/finance/personalfinance/energy-bills/11044279/The-oil-price-puzzle-prices-are-quick-to-rise-but-slow-to-fall.html
  - https://oilprice.com/Energy/Energy-General/Why-Oil-Prices-Are-Surging.html

*** Basmi politik identitas; mulai desegregasi; basmi partisanisme; basmi tribal politics

- How Congress (and America) became so polarized - Jonathan Haidt https://www.youtube.com/watch?v=RhoGx7bTzko
  - Newt Gingrich started tribalism in the Republican party.

*** Sederhanakan hukum
You know your legal system is too complex when people can profit from that complexity.
*** <2018-09-19> Tertibkan pelacuran, narkoba, dan judi?

Kita jangan munafik.
Hal-hal ini sudah ada sejak manusia ada.
Hal-hal ini tidak bisa dihilangkan.

Solusinya adalah mendidik masyarakat, bukan melarang.
Larangan hanya akan membuat black market.

Laws can't go against human nature.

Masalah: NIMBY.
Mau dilokalisasi di mana?
Tentu di tempat yang sudah ada.
Resmikan tempat yang sudah ada.

Jual narkoba di alfamart/warung?
Atur kemasan harus sama semua.
Tidak boleh iklan.

Perlu update [[http://spkonline.bps.go.id/spkonline/help/klasifikasi/2][KBLI]] (Klasifikasi Baku Lapangan Usaha Indonesia).

https://www.straitstimes.com/asia/se-asia/malaysia-in-talks-to-become-first-in-asia-to-allow-medical-pot

*** <2018-09-19> Perbaiki sistem hukum?

**** Prinsip hukum

***** A law must not go against nature.

Banning prostitution does not respect nature.
Banning drugs does not respect nature.

***** A law must be practically enforceable.

Cabut semua aturan yang enforcement-nya tidak praktikal.

***** Regulate; don't ban.

**** <2018-09-19> Perjelas bagian UUD yang tidak jelas.

***** Naskah
   :PROPERTIES:
   :CUSTOM_ID: naskah
   :END:

- 2018-09-01: [[http://www.dpr.go.id/jdih/uu1945][UUD 1945]] (perubahan keberapa?)
- [[https://ngada.org/uud01-1945pjl.htm][Penjelasan UUD 1945 (naskah asli tanpa amandemen)]]
  (itu website apa?)

***** Cara mengubah UUD
   :PROPERTIES:
   :CUSTOM_ID: cara-mengubah-uud
   :END:

- Lihat pasal 37.
  Wewenang MPR.
- Pasal 37 ayat 5: "Khusus mengenai bentuk Negara Kesatuan Republik Indonesia tidak dapat dilakukan perubahan."
- Pasal 1 ayat 3: "Negara Indonesia adalah negara hukum."

***** Pemilu partai vs pemilu langsung?
   :PROPERTIES:
   :CUSTOM_ID: pemilu-partai-vs-pemilu-langsung
   :END:

- Pasal 22E ayat 3: "Peserta pemilihan umum untuk memilih anggota Dewan Perwakilan Rakyat dan anggota Dewan Perwakilan Rakyat Daerah adalah partai politik."

  - Mengapa partai?

    - Menyederhanakan pemilu.
    - Perkumpulan orang-orang setujuan?

  - Keburukan partai

    - Kebutuhan memenangkan suara membuat partai berpolitik praktis dan meninggalkan tujuannya?
    - [[https://tirto.id/corak-ideologi-partai-partai-di-indonesia-cJKc][Corak Ideologi Partai-Partai di Indonesia - Tirto.ID]]

      - Pertai di Indonesia hanya beda pendapat soal agama.
        Sisanya sama semua.
        Kurang variasi.
        Groupthink.

  - Partai berarti "bagian".

***** Pasal-pasal yang perlu dijelaskan
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-perlu-dijelaskan
   :END:

Pasal-pasal ini bertujuan mulia, tetapi kata-katanya tidak jelas secara hukum, sehingga tidak bisa ditegakkan.

- Pasal 27 ayat 1:
  "Segala warga negara bersamaan kedudukannya di dalam hukum dan pemerintahan dan wajib menjunjung hukum dan pemerintahan itu dengan tidak ada kecualinya."

  - Pasal tersebut tidak cocok menjadi hukum.
    Ia bukan definisi ataupun aturan, melainkan harapan.
  - Tidak ada cara untuk menjalankan pasal tersebut.
  - Tidak ada hukuman yang jelas untuk pelanggarannya.
    (Aturan tanpa hukuman sama saja tidak ada.)
  - Aturan yang sulit di-enforce sama saja tidak ada.
  - Diskriminasi adalah bagian manusia dan akan ada selama manusia ada.

- Pasal 27 ayat 3:
  "Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara."

  - Apa beda "berhak dan wajib" dan "wajib"?
  - Apa hukuman untuk pelanggarnya?
  - Apa arti kata "berhak"?
  - Bagaimana cara mengklaim suatu hak?

- Pasal 29 ayat 1: "Negara berdasar atas Ketuhanan Yang Maha Esa."

  - Apa arti kata "esa"?

    - Menurut [[https://kbbi.web.id/esa][KBBI daring]], kata "esa" berarti "satu".
      Tapi sumber ini kurang kuat.
      Bisa saja di-hack.
    - [[https://balebengong.id/kabar/melacak-asal-kata-esa-dalam-pancasila.html?lang=id][Melacak asal Kata Esa dalam Pancasila - BaleBengong]]
    - Pendapat ahli bahasa Indonesia

      - https://twitter.com/eggggsie/status/990073630653476864
      - https://twitter.com/harimbawa/status/989232636274008064
      - [[https://en.wiktionary.org/wiki/wish#Etymology][Wiktionary tidak sependapat soal asal usul kata "wish"]]

    - Perkelahian gara-gara kata "esa"

      - https://twitter.com/Mentimoen/status/946237996327686144
      - [[https://tirto.id/sejarawan-eggi-sudjana-ahistoris-dan-tak-paham-konsep-esa-cxVS][Sejarawan: Eggi Sudjana Ahistoris dan Tak Paham Konsep Esa - Tirto.ID]]

  - Sebaiknya kita ganti pasal tersebut dengan kata-kata yang umum di abad 21.
    Aturan harusnya dibuat supaya mudah dipahami.

- Pasal 31

  - Pasal 31 ayat 2: "Setiap warga negara wajib mengikuti pendidikan dasar dan pemerintah wajib membiayainya."
  - Pasal 31 ayat 4: "Negara memprioritaskan anggaran pendidikan sekurang-kurangnya dua puluh persen dari anggaran pendapatan dan belanja negara serta dari anggaran pendapatan dan belanja daerah untuk memenuhi kebutuhan penyelenggaraan pendidikan nasional."
  - Apa itu artinya sekolah harus digratiskan?
    Seandainya APBN tidak cukup bagaimana?
  - Pasal 31 ayat 3: "Pemerintah mengusahakan dan menyelenggarakan satu sistem pendidikan nasional, yang meningkatkan keimanan dan ketakwaan serta ahlak mulia dalam rangka mencerdaskan kehidupan bangsa, yang diatur dengan undang-undang."

    - Ini mungkin harus diubah supaya mengikutkan "toleransi".

- Pasal 32 ayat 1: "Negara memajukan kebudayaan nasional Indonesia di tengah peradaban dunia dengan menjamin kebebasan masyarakat dalam memelihara dan mengembangkan nilai-nilai budayanya."

  - Apa itu nilai budaya?
    Apakah budaya yang buruk juga harus dipelihara?
    Apa itu "buruk"?
    Sistem moral mana yang harus dipakai pemerintah?

- Pasal 32 ayat 2: "Negara menghormati dan memelihara bahasa daerah sebagai kekayaan budaya nasional."

  - Bagaimana caranya?

- Pasal 28H ayat 4: "Setiap orang berhak mempunyai hak milik pribadi dan hak milik tersebut tidak boleh diambil alih secara sewenang-wenang oleh siapapun."

  - Pasal ini sangat tidak jelas.
  - Pajak adalah pengambilan sebagian hak milik pribadi secara paksa oleh pemerintah.
    Bagaimana hubungan pajak dan ayat ini?

    - Apa yang dimaksud "hak milik"?
      Private property?
    - Hak milik untuk apa saja?
      Semua benda?
    - Tapi kepemilikan bisa dicabut?
      Apa beda kepemilikan dan hak milik?

  - Bertentangan dengan pasal 33 ayat 3?

    - Sepertinya tidak.
      Ayat ini tidak melarang /pembatasan/ jenis benda yang bisa dimiliki pribadi.

***** Pasal-pasal yang tidak perlu?
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-tidak-perlu
   :END:

Pasal-pasal ini mengatur hal-hal yang tidak usah disuruh pun orang akan melakukan.
Cara menegakkannya juga tidak jelas.

****** Tambahan pasal 28, sepertinya karena Pak Harto
    :PROPERTIES:
    :CUSTOM_ID: tambahan-pasal-28-sepertinya-karena-pak-harto
    :END:

Mungkin beberapa tambahan ini dibuat karena penculikan, penghilangan, dan penembakan misterius pada zaman Pak Harto.

- Pasal 28A: "Setiap orang berhak untuk hidup serta berhak mempertahankan hidup dan kehidupannya."
- Pasal 28B ayat 1: "Setiap orang berhak membentuk keluarga dan melanjutkan keturunan melalui perkawinan yang sah."

  - Tanpa dibolehkan pun orang akan kawin.
    Sebelum ada UUD 1945 pun orang sudah kawin.
    Mengapa bisa ada ayat ini di UUD?
    Apa latar belakangnya?
  - Setiap orang?
    Apakah semua orang boleh melanjutkan keturunan?
    Apakah orang yang tidak bisa mengurus anak sebaiknya melanjutkan keturunan?
    Apakah ekstremis sebaiknya melanjutkan keturunan?

- Pasal 28B ayat 2: "Setiap anak berhak atas kelangsungan hidup, tumbuh, dan berkembang serta berhak atas perlindungan dari kekerasan dan diskriminasi."
- Pasal 28C, 28D, 28E, 28F, 28G, 28H, 28I: you don't say. Bagaimana cara menegakannya?

***** Loopholes and undefined situations
   :PROPERTIES:
   :CUSTOM_ID: loopholes-and-undefined-situations
   :END:

- Pasal 24B ayat 3: "Anggota Yudisial diangkat dan diberhentikan oleh Presiden dengan persetujuan Dewan Perwakilan Rakyat."

  - Kalau DPR tidak setuju, lalu apa?

***** Mana lembaga negara tertinggi?
   :PROPERTIES:
   :CUSTOM_ID: mana-lembaga-negara-tertinggi
   :END:

- DPR lebih tinggi daripada Presiden.
  Presiden tidak bisa pecat DPR.

  - Pasal 7: DPR bisa pecat Presiden, tapi ada syaratnya.
  - Pasal 7C: "Presiden tidak dapat membekukan dan/atau membubarkan Dewan Perwakilan Rakyat."

- Tapi Presiden bisa memerintahkan militer untuk menyerang DPR?

  - Pasal 10: "Presiden memegang kekuasaan yang tertinggi atas Angkatan Darat, Angkatan Laut dan Angkatan Udara."

- DPR bisa mengatur sebagian yudikatif?

  - Pasal 24 ayat 3: "Badan-badan lain yang fungsinya berkaitan dengan kekuasaan kehakiman diatur dalam undang-undang."

***** Yang sudah baik
   :PROPERTIES:
   :CUSTOM_ID: yang-sudah-baik
   :END:

****** Sistem ekonomi paham tengah, berimbang antara kapitalisme dan sosialisme
    :PROPERTIES:
    :CUSTOM_ID: sistem-ekonomi-paham-tengah-berimbang-antara-kapitalisme-dan-sosialisme
    :END:

Pasal 27 ayat 2: "Tiap-tiap warga negara berhak atas pekerjaan dan penghidupan yang layak bagi kemanusiaan."

- Bagaimana cara enforcenya?
- Universal basic income?

Pasal 28H ayat 2: "Setiap orang berhak mendapat kemudahan dan perlakuan khusus untuk memperoleh kesempatan dan manfaat yang sama guna mencapai persamaan dan keadilan."

Pasal 33 ayat 1: "Perekonomian disusun sebagai usaha bersama berdasar atas asas kekeluargaan."

- Apa artinya?

Pasal 33 ayat 2: "Cabang-cabang produksi yang penting bagi negara dan yang menguasai hajat hidup orang banyak dikuasai oleh negara."

Apa arti "hajat hidup orang banyak" dan "dikuasai"?
Dikuasai tidak berarti dimiliki?

Apakah Gojek hajat hidup orang banyak?
Apakah transportasi umum (Kopaja, Metromini, Mikrolet, dll.) hajat hidup orang banyak?

Pasal 33 ayat 3: "Bumi dan air dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besar kemakmuran rakyat."

- Apa itu berarti tanah harus dikuasai negara?
  Orang tidak boleh punya tanah?
  Perusahaan air seperti Aqua, Oasis, Cleo, PAM, PDAM, dll. harus dikuasai negara?

Saya lebih suka orang tidak boleh memiliki tanah (hanya boleh menyewa tanah dari pemerintah).
Tapi bagaimana dengan bangunan di atasnya?

Pasal 33 ayat 4: "Perekonomian nasional diselenggarakan berdasar atas demokrasi ekonomi dengan prinsip kebersamaan, efisiensi berkeadilan, berkelanjutan, berwawasan lingkungan, kemandirian, serta dengan menjaga keseimbangan kemajuan dan kesatuan ekonomi nasional."

Apa arti "demokrasi ekonomi"?
Apa arti "efisiensi berkeadilan"?

"Kemandirian" berarti harus mengurangi impor, lalu memproduksi sebanyak mungkin macam barang dalam negeri?

Pasal 34 ayat 2: "Negara mengembangkan sistem jaminan sosial bagi seluruh rakyat dan memberdayakan masyarakat yang lemah dan tidak mampu sesuai dengan martabat kemanusiaan."

Mendasari BPJS, Jamsostek, dll..
Tinggal eksekusi yang baik.

Pasal 34 ayat 3: "Negara bertanggung jawab atas penyediaan fasilitas pelayanan kesehatan dan fasilitas pelayanan umum yang layak."

Mendasari RSUP, RSUD, dll.


**** <2018-09-19> Cabut aturan yang melarang hal-hal yang tidak membahayakan orang banyak.

Cabut aturan yang mengatur urusan pribadi.

**** <2018-09-19> Generalize aturan: Kriminalkan semua orang yang mengganggu ketertiban umum?

Problem: Ini bisa jadi pasal karet.

Tidak perlu ada aturan spesifik.
Aturan tentang ketertiban umum mencakup semua hal berikut:
- Membuat video porno tidak kriminal; menyebarkannya yang kriminal.
- Hubungan intim tidak kriminal; yang kriminal adalah membuat masyarakat resah.
- Menghujat tidak kriminal; yang kriminal adalah membuat masyarakat ribut.

**** <2018-09-19> Buat aturan contempt of court? Sebaiknya benahi hakim dan pengadilan dulu?

Ide Hotman Paris?

Tapi bagaimana kalau ada miscarriage of justice?
Aturan contempt of court akan memperparah miscarriage of justice.


**** Should we repeal blasphemy laws and obscenity laws?
   :PROPERTIES:
   :CUSTOM_ID: should-we-repeal-blasphemy-laws-and-obscenity-laws
   :END:

We already have laws for people causing public disorder.

- If a person commits blasphemy and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for blasphemy.
- If a person distributes obscene materials and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for distributing obscene materials.
- If a person causes public disorder to overthrow a corrupt government,
  then the government will try to vanquish the rebellion,
  but the people shall prevail?
- Blasphemy laws allow angry people to fight in the courtroom.
  Without blasphemy laws, angry people would fight on the road,
  where there are no rules, taking matter into their own hands.

  - However, blasphemy laws also allow religion
    to subvert the justice system.

- http://business-law.binus.ac.id/2018/07/10/bahaya-tafsir-a-historis-terhadap-pasal-156a-kuhp/

*** Buat profesi petani jadi menarik secara ekonomi.
*** <2018-09-19> Net neutrality, un-ban websites, Reddit, Vimeo, dll.

Tapi, apakah website ekstremis juga mau di-unblock?

**** Why is Reddit blocked in Indonesia?

- The official reason
  - Something like "Reddit is a porn site.".
  - http://www.mesinwaktu.id/2017/11/alasan-kenapa-reddit-diblokir.html
  - https://www.quora.com/Why-is-Reddit-blocked-by-the-Indonesian-government
  - Doesn't make sense.
    - There is porn on Reddit, but Reddit is not a porn site.
      There are also porn on Google, Bing, YouTube, Blogspot, but they aren't porn sites.
      Why block only Reddit?
      If you're following the law to the letter,
      why not block all of Internet?
- What I think the reason is
  - Someone in the government might need to be seen working.
    Sepertinya blokir website termasuk tugas kemkominfo dalam undang-undang.

*** Close international tax evasion loopholes

Make it impossible to hide money trail.
Require electronic cash with traceability/accounting/history.
Eliminate hard cash.

**** Rally all countries against the money-laundering countries

Tax havens are money launderers.

** Prinsip
*** My basic assumptions for legislating
- Humans are generally moral and peaceful, if their basic needs are met.
- Some humans are immoral or evil.
**** Hobbes vs Locke?
*** Start from the objective reality.
- Contoh:
  - Objektif: "Beberapa orang Indonesia tidak bisa membaca."
    Ada tes yang jelas untuk mengukur kemampuan membaca.
  - Tidak objektif: "Orang Indonesia malas."
    Apa definisi "malas"?
*** Work as close as possible to the root cause.
Misalnya dengan cara five whys.

Bisa juga dengan bertanya mengapa sampai kita tidak bisa jawab lagi.
Pertanyaan terakhir yang berhasil kita jawab itulah yang mau kita benahi.
*** Bigger changes should be slower
We don't want bloody revolutions (big fast changes).
** Hukum

*** Hapusnya hak atas tanah?
   :PROPERTIES:
   :CUSTOM_ID: hapusnya-hak-atas-tanah
   :END:

Saya punya tetangga yang menelantarkan rumahnya sampai rusak.
Berapa lama sebelum saya bisa main klaim bahwa tanah itu tanah saya?

- https://www.hukumproperti.com/pertanahan/hapusnya-hak-atas-tanah/

  - "karena ditelantarkan" PP 36/1998

    - Apakah bisa digunakan untuk tetangga yang meninggalkan rumahnya dan membiarkannya rusak?

*** Masalah sistem hukum, dan kasus menggantung
   :PROPERTIES:
   :CUSTOM_ID: masalah-sistem-hukum-dan-kasus-menggantung
   :END:

- https://nasional.tempo.co/read/793720/bnn-ada-72-mafia-narkoba-lain-freddy-masih-kelas-ecek-ecek
- http://akakristianto.com/2015/08/14/ungkap-kematian-pekerja-kebersihan-jis/
- http://nasional.republika.co.id/berita/nasional/hukum/15/06/05/npfrim-azwar-tersangka-jis-bukan-mati-bunuh-diri
- https://en.wikipedia.org/wiki/Munir_Said_Thalib
- [[https://news.detik.com/berita/4167913/ganti-rugi-tak-kunjung-cair-korban-salah-tangkap-gugat-menkeu?utm_source=twitter&utm_medium=oa&utm_content=detikcom&utm_campaign=cmssocmed][Ganti Rugi Tak Kunjung Cair, Korban Salah Tangkap Gugat Menkeu]]

  - Aturan 14 hari bayar.
    Itu sudah 2 tahun tidak bayar.
  - Betul kata Hotman Paris, Indonesia perlu aturan contempt of court (penghinaan terhadap lembaga peradilan).
    Selama tidak ada aturan itu, putusan pengadilan tidak dihargai.

*** Keluar masuk pegawai
    :PROPERTIES:
    :CUSTOM_ID: keluar-masuk-pegawai
    :END:

- Polisi bisa? (tapi seharusnya tidak bisa?) https://nasional.kompas.com/read/2018/01/15/16055551/polisi-yang-sudah-masuk-ke-politik-seharusnya-tak-bisa-balik-lagi-ke-polri
- TNI tidak bisa https://news.detik.com/berita/d-3305012/setelah-mundur-agus-tak-bisa-kembali-ke-tni-kodam-jaya-itu-pilihannya

  - PNS TNI tidak bisa

- PNS lain bisa http://www.hukumonline.com/klinik/detail/lt59ae5a5d781fd/bolehkah-melamar-menjadi-pns-lagi-jika-pernah-berhenti-dengan-hormat-atas-permintaan-sendiri

** Agama

Agama adalah urusan pribadi, bukan urusan negara.

(Ini masih sesuai UUD?)

*** <2018-09-19> Akui semua agama, aliran, dan kepercayaan.

Ada sedikitnya 4000 agama/aliran/kepercayaan.

Syiah, Ahmadiyah, Tarekat Naqsabandiyah.

Agama Mesir kuno.
Paganisme.
Animisme.
Dinamisme.

Discordia, Church of the SubGenius, Flying Spaghetti Monster.

**** Aceh

- https://tirto.id/menilik-harta-kekayaan-cagub-cawagub-dki-bPPV
- https://tirto.id/benarkah-syariat-islam-menghambat-investasi-di-aceh-cP3C
- https://tirto.id/dana-otsus-dicabut-aceh-siap-bangkrut-cP54

**** Sejarah agama

- Agama, yang sekarang besar, awalnya dianggap sesat oleh orang-orang di sekitarnya.
- Pengikut Yesus awalnya dianggap sesat oleh pengikut Yahudi pada zamannya.
- Pengikut Muhammad awalnya dianggap sesat oleh pengikut polytheism Arab pada zamannya.
- Bayangkan seandainya seorang di kampung Anda tiba-tiba mengumumkan suatu agama baru.
- Mengapa kita lebih percaya orang 2000 tahun lalu daripada orang sekarang?
  Mengapa kita berpaku pada masa lalu?
  Mengapa kita tidak berusaha membuat masa depan jadi lebih indah?

*** <2018-09-19> Alihkan tugas departemen agama (umrah, naik haji dll.) kepada private sector.

*** <2018-09-19> Serahkan pendidikan agama sepenuhnya kepada keluarga.
- Mengganti pelajaran agama di sekolah dengan pelajaran /sejarah/ agama.

*** <2018-09-19> Kurangi/tiadakan ekstremisme/radikalisme

**** <2018-09-22> Wajibkan pelajaran sejarah agama

History of Islam?
Is Brigitte Gabriel's [[https://www.youtube.com/watch?v=o0m9nEafBE4][history-of-Islam video]] accurate?

**** Setiap ayat sensitif dalam kitab suci harus disertai tafsir/exegesis/interpretasi dan komentar tentang konteks sejarah turunnya ayat tersebut.
- Terutama Quran karena mayoritas penduduk Indonesia Muslim.
- Kitab suci bisa berupa buku kertas, aplikasi komputer, dll.
- Bagaimana cara mencegah [[https://en.wikipedia.org/wiki/Auto-segregation][WP:Auto-segregation]]?
  Asimilasi vs akulturasi vs absorpsi vs integrasi?
- Apakah efektif?
  Quran terjemahan ekstremis akan tetap saja beredar underground.
  Tapi kebijakan ini mungkin mempengaruhi Muslim moderat yang selama ini complicit atau bahkan diam-diam setuju dengan ekstremis.
- Kita sebaiknya tidak memaksakan/mengatur kepercayaan dengan undang-undang.
- Bagaimana seandainya ada orang mengarang kitab suci sendiri?


*** Kerusuhan SARA
   :PROPERTIES:
   :CUSTOM_ID: kerusuhan-sara
   :END:

- Tanjung Balai Sumatra Utara sering rusuh?

  - 2018, [[https://regional.kompas.com/read/2018/08/23/18025471/5-fakta-kasus-meiliana-menangis-di-sidang-hingga-fatwa-mui][5 Fakta Kasus Meiliana, Menangis di Sidang hingga Fatwa MUI - Kompas.com]]

    - [[https://www.facebook.com/ransibar/posts/10216709033187633][Keterangan Ranto Sibarani, anggota tim penasihat hukum tergugat]]
    - Coba tanya MUI Sumatra Utara:

      - Mengapa Jusuf Kalla boleh minta suara azan dikecilkan, tetapi Meiliana tidak boleh?

        - 2018, [[https://news.detik.com/berita/4179062/jk-nilai-kasus-meiliana-bukan-soal-toleransi][JK Nilai Kasus Meiliana Bukan Soal Toleransi]]
        - Karena JK wapres?

          - Seandainya wapresnya Meiliana, apa dia boleh minta suara azan dikecilkan?

            - Seandainya wapresnya Ahok?

      - Mengapa standar ganda?

        - Yang ini hanya kena teguran, tidak dipenjara: [[https://www.liputan6.com/regional/read/3614381/sebut-nabi-muhammad-sesat-ustaz-evie-effendie-kena-teguran-keras][Sebut 'Nabi Muhammad Sesat', Ustaz Evie Effendie Kena Teguran Keras - Regional Liputan6.com]]
        - 2018, [[https://news.detik.com/berita/4178495/pengeluh-volume-azan-dibui-18-bulan-bagaimana-perusak-vihara][Pengeluh Volume Azan Dibui 18 Bulan, Bagaimana Perusak Vihara?]]
          Hanya 1-2 bulan.

      - Mengapa PBNU tidak sepakat dengan MUI?

        - [[https://nasional.tempo.co/read/1119693/pbnu-icjr-dan-setara-kritik-vonis-kasus-penistaan-agama-meiliana][PBNU, ICJR dan Setara Kritik Vonis Kasus Penistaan Agama Meiliana - nasional Tempo.co]]
        - [[https://nasional.tempo.co/read/1119345/pbnu-katakan-suara-adzan-terlalu-keras-bukan-penistaan-agama/full&view=ok][PBNU: Katakan Suara Adzan Terlalu Keras Bukan Penistaan Agama - nasional Tempo.co]]
        - Jadi yang benar siapa?

  - 2018, [[http://medan.tribunnews.com/2018/05/15/ini-kronologis-penangkapan-terduga-teroris-di-tanjungbalai-satu-orang-tewas-di-tempat][Ini Kronologi Penangkapan Terduga Teroris di Tanjungbalai, Satu Orang Tewas di Tempat - Tribun Medan]]
  - 2018, [[https://www.viva.co.id/berita/nasional/1057980-dua-tahun-usai-kerusuhan-sara-toleransi-di-tanjung-balai-kian-kuat][Dua Tahun Usai Kerusuhan SARA, Toleransi di Tanjung Balai Kian Kuat -- VIVA]]

    - Baru dipuji sudah rusuh lagi.

  - 2016, [[https://tirto.id/tujuh-warga-jadi-tersangka-kerusuhan-tanjungbalai-bwtp][Tujuh Warga Jadi Tersangka Kerusuhan Tanjungbalai - Tirto.ID]]
  - 2016, [[http://jarumdetik.blogspot.com/2016/07/fakta-sebenarnya-di-balik-rusuh-tanjung.html][Fakta Sebenarnya di Balik Rusuh Tanjung Balai | Jarum Detik]]

    - Masyarakat setempat sudah dua kali terhasut berita bohong: 2016 dan 2018.

      - [[https://www.motivasi-islami.com/jangan-seperti-keledai-atau-lebih-parah/][Jangan Seperti Keledai Atau Lebih Parah - Motivasi Islami]]: Keledai saja tak jatuh dua kali ke lubang yang sama.

  - A person's beliefs filter all incoming information.
    Therefore people believe hoax that supports their beliefs, and reject facts that counter their beliefs.

    - Riots uncover true beliefs.
    - Kerusuhan adalah bukti bahwa toleransi hanya di permukaan.

  - UU 1/1965 tentang penodaan agama

    - [[https://tirto.id/asal-usul-delik-penistaan-agama-b49e][Asal-Usul Delik Penistaan Agama - Tirto.ID]]

** Teknologi

*** <2018-09-19> Kuasai infrastruktur Internet

Infrastruktur Internet adalah hajat hidup orang banyak, jadi harusnya dikuasai negara, sesuai pasal 33 ayat 3 UUD 1945.

*** <2018-09-21> Benahi keculasan Telkomsel dan korporat lainnya
- Beli paket data di Indonesia Barat; terbang ke Indonesia Tengah; paket data tidak berlaku.
- Simplify pricing.
  Harga paket data harus rata per GB, dan harus sama di semua Indonesia.
  Tidak boleh memahalkan pengguna kecil.
  - Daerah maju mensubsidi daerah tertinggal.
- Cabut iklan sisipan proxy Telkomsel.

Lapor ke LPK (Lembaga Perlindungan Konsumen):
https://www.reddit.com/r/indonesia/comments/9lj478/definisi_unlimited_di_hukum_indonesia_itu_apa_sih/e77cleu/

Di mana tuh LPK?

YLKI: "Bagaimana Menyampaikan Pengaduan Konsumen?"
https://ylki.or.id/2016/12/__trashed/

UU 8/1999 tentang perlindungan konsumen?
** Transportasi, lingkungan, pertanahan, tata kota

- Utamakan pejalan kaki dalam tata kota.

*** Self-driving buses for public transport can drive transport costs down?

- Which are the biggest transport cost component? Is it fuel or the driver?

*** Solusi kemacetan tol Jakarta?

- Solusi:
  - Pemda DKI, Bogor, Depok, Tangerang, dan Bekasi:
    - Pilihan 1: Membeli jalan tol menjadi jalan umum.
      - Lunasi atau cicil ke pemilik tol.
    - Pilihan 2: Menyewa jalan tol pada jam tertentu menjadi jalan umum.
      - Menaikkan pajak jalan untuk mobil.
        - [[https://en.wikipedia.org/wiki/Road_tax][WP:Road tax]]
        - Ditambah (rata-rata biaya tol) * (jumlah hari dalam setahun)
          - Ditambah Rp 7,200,000 per tahun?
      - Membuka semua pintu tol di Jakarta pada jam sibuk.
        - Kalau tidak bisa buka semua, buka yang paling bikin macet.
      - Membayar ganti rugi ke operator tol.
- Menyelesaikan dua masalah sekaligus:
  - Disinsentif untuk pengguna mobil pribadi.
  - Mengurangi kemacetan karena kelambatan gerbang tol.
- Skenario gagal:
  - Pemda tidak punya cukup uang.
  - Manusia egois.
    - Pemda sekitar DKI tidak mau patungan.
    - Pemilik mobil menolak bayar pajak demi kebaikan bersama.
    - Pemilik tol menolak penawaran karena terlalu serakah.



*** TODO <2018-09-17> Gratiskan kendaraan umum bertrayek

- Lebih mudah dan murah daripada integrasi antarmoda?
- Mengurangi trafik dan polusi.

**** <2018-09-19> Biaya yang diperlukan per jam-kendaraan (unit economics)

- Satuan unit economics: 1 jam-kendaraan
- Breakdown
  - Upah
    - 1 kendaraan butuh 2 orang operator (1 supir dan 1 kenek)
    - Upah 1 orang Rp 7 juta/160 jam ~ Rp 50000/jam
  - Bahan bakar
    - Penggunaan bahan bakar (fuel mileage), 5 km/liter, Rp 10000/liter
    - Kecepatan rata-rata 50 km/jam
    - Kendaraan beroperasi 24 jam per hari = 1200 km/hari = 240 liter/hari
  - Biaya perawatan kendaraan Rp ?/bulan
  - Asuransi kesehatan Rp ?/bulan
  - Asuransi kendaraan Rp ?/bulan

**** Potensi masalah dan penolakan

***** Pengemudi ojek, taksi, dan mobil sewa mungkin menolak karena pendapatan mereka mungkin berkurang

- Bantu mereka beralih jadi supir kendaraan umum bertrayek.

**** Negara lain yang sudah berhasil

- [[https://www.youtube.com/watch?v=ccxVYborUcU][Let's Make Mass Transit Free* - YouTube]]
  - Making mass transit free benefits everyone, including those who don't use mass transit.
    Free mass transit reduces traffic.

*** <2018-09-21> Perbaiki jembatan penyeberangan

<2018-09-21>
Jembatan penyeberangan di Jl. S. Parman Jakarta logamnya mencuat dan ukuran anak tangganya terlalu kecil.

*** Pentingnya infrastruktur
    :PROPERTIES:
    :CUSTOM_ID: pentingnya-infrastruktur
    :END:

[[https://www.bloomberg.com/quicktake/indonesias-nationalism][Bloomberg]]:
"A lack of roads and ports means it's cheaper to ship goods to China than across the archipelago."

Kok lebih murah ngirim barang ke Cina daripada ke Papua?
Padahal, menurut peta, jarak Jakarta-Hongkong mirip jarak Jakarta-Jayapura.

- [[https://www.youtube.com/watch?v=MFrLcRhMKnE][Geopolitics of Southeast Asia Part 2: Malay Archipelago - YouTube]]

  - Indonesia is too big to defend itself.

** Politik

Fix the system; berantas perverse incentive, principal-agent problem, dan conflict of interest.

*** Mengapa Indonesia tertinggal?

https://nasional.kontan.co.id/news/dua-alasan-indonesia-tertinggal-dari-negara-lain

Rizal Ramli:

- "Paradigmanya, tebang hutan, lalu ekspor. Sedot tanah di Papua lalu ekspor. Tidak dibangun industri hilir sehingga nilai tambahnya sedikit."
- "Saya minta tolong, perlu perubahan paradigma pengelolaan SDM dari sekadar sedot ekspor, kita kembangkan nilai tambahnya"

Kesimpulannya kita tertinggal karena selalu mencari jalan pintas / menang mudah yang kecil dan tidak matter.

*** Mudahkan pemilu untuk perantau

Pemilu serentak?
Sistem e-ktp nasional?

Pemilu harus ada bukti fisik seperti kertas, tidak boleh sepenuhnya bergantung ke komputer.

*** <2018-09-19> Evidence-based legislation? data-driven legislation?

*** <2018-09-19> Tertibkan kampanye politik

- membatasi kampanye hanya dalam bentuk prospektus (tertulis) berisi rencana program kerja, seperti yang sedang Anda lihat
- mengumpulkan prospektus dalam satu website
- melarang semua bentuk lain

*** <2018-09-19> Larang /lobbying/

Bukannya memang sudah dilarang?

*** <2018-09-17> Larang partai membayar anggota; wajibkan anggota membayar partai?

- Berantas politik karir?
  What's so bad about career politicians?
  A career is not bad in and of itself.
- Pastikan bahwa yang masuk adalah orang yang benar-benar peduli politik.
- Tapi kalau begini, politik jadi sampingan.
  Tidak semua orang mau punya 2 pekerjaan.

A party is a mini-country.
Therefore a party should tax its members, not pay its members.

Politics should not be a career path?

*** Pesimis soal partai baru
   :PROPERTIES:
   :CUSTOM_ID: pesimis-soal-partai-baru
   :END:

2014 ada partai baru: [[https://psi.id/][Partai Solidaritas Indonesia]].
Terus?
Semua partai juga pernah baru.
Semua partai juga didirikan dengan cita-cita mulia.

- Pada tahun 1927 PNI juga partai baru.
- Pada tahun 1964 Golkar juga partai baru.
- Pada tahun 1973 PDI juga partai baru.
- Pada tahun 2001 Partai Demokrat juga partai baru.
- Pada tahun 2002 PKS juga partai baru.
- Pada tahun 2008 Gerindra juga partai baru.
- Semua partai baru itu akhirnya terlibat masalah.

Bagaimana kita menjamin partai baru tidak terjerembab ke lubang korupsi?

Ada siklus:

- Partai baru didirikan karena ketidakpuasan terhadap partai lama.
- Setelah lama, partai baru jadi partai lama, dan terlibat masalah.
- Ulangi.

Kalau semua partai terlibat masalah,
sistem pemerintahan perlu diperbaiki?
Pemisahan perlu diperbaiki?
Insentif perlu dirancang lebih baik?

Umpama anak sekolah:

- Kalau satu anak gagal, mungkin anaknya yang salah.
- Kalau satu kelas banyak yang gagal, mungkin kelasnya yang salah.
- Kalau banyak kelas gagal, mungkin sekolahnya yang salah.
- Kalau banyak sekolah gagal, mungkin sistem pendidikannya yang salah.

Umpama partai:

- Kalau satu orang korup, mungkin orangnya yang salah.
- Kalau satu partai banyak yang korup, mungkin partainya yang salah.
- Kalau banyak partai korup, mungkin hukum negara ini yang salah.

Diskusi:

- [[https://www.quora.com/What-do-Indonesians-know-think-about-the-new-party-PSI-Partai-Solidaritas-Indonesia-And-how-big-is-the-chance-that-the-PSI-will-get-a-place-in-the-parliament][What do Indonesians know/think about the new party PSI (Partai Solidaritas Indonesia)? And how big is the chance that the PSI will get a place in the parliament? - Quora]]

**** Sistem kita mengubah orang muda idealis menjadi orang tua korup?

Orang baik dalam sistem buruk akan jadi orang buruk.

- https://theconversation.com/buasnya-sistem-politik-indonesia-halangi-upaya-reformasi-dari-dalam-oleh-mantan-aktivis-94523

Bagaimana memperbaikinya?

*** Ucapan terima kasih
   :PROPERTIES:
   :CUSTOM_ID: ucapan-terima-kasih
   :END:

**** Terima kasih Gus Dur
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-gus-dur
    :END:

Imlek jadi libur.

Diskriminasi berkurang.

WNI keturunan Cina bisa masuk universitas negeri.

**** Terima kasih Ahok
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-ahok
    :END:

- Rumah saya baru bebas banjir pada zaman BTP (Basuki Tjahaja Purnama a.k.a. Ahok).

  - Tahun 1990-an setiap 5-6 tahun sekali, rumah banjir.
  - Makin lama makin parah. Tiap tahun banjir.
  - Bahkan, pernah suatu ketika, tidak hujan malah banjir.
  - Jalanan dinaikkan 50 cm. Rumah dinaikkan 100 cm. Tetap banjir.
  - Saat BTP menjabat, rumah saya tidak banjir.

Namun, hal yang saya tidak setuju:

- Omongan kurang dijaga, mungkin terbawa emosi.
  Akhirnya kata-katanya dipakai untuk menyerang dia.
- Utilitarianisme.
  [[https://en.wikipedia.org/wiki/Trolley_problem][WP:Trolley problem]] menyiratkan bahwa utilitarianisme tidak cocok jadi prinsip moral.
  Saya hargai kemampuan problem-solving dan kecepatan kerja Ahok, tapi soal prinsip moral ini saya tidak setuju.

  - [[https://news.detik.com/berita/2998358/ham-versi-ahok-untuk-melindungi-rakyat-banyak][HAM Versi Ahok untuk Melindungi Rakyat Banyak]]

*** Peduli rakyat kecil
   :PROPERTIES:
   :CUSTOM_ID: peduli-rakyat-kecil
   :END:

- Student activism

  - [[https://twitter.com/semarui?lang=en][SEMAR UI]]
  - [[https://twitter.com/rakapare?lang=en][Komune Rakapare]]

*** 1998
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

- [[https://www.reddit.com/r/indonesia/comments/61ed2m/what_was_indonesia_like_before_reformasi_and/][What was Indonesia like before Reformasi and after1998? (Long) : indonesia]]
- [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/][Telegram from US Embassy Jakarta to State Department, "Who Is Behind [1998] Disappearances?," : indonesia]]

  - [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/e4a0s02/][Pendapat redditor fourrier01]]: "Every year, just before election, there's always a news to reveal Prabowo stench over and over. 4 years ago there was Allan Nairn. [...] This one isn't so surprising anymore."

*** Pemilihan Presiden 2019
   :PROPERTIES:
   :CUSTOM_ID: pemilihan-presiden-2019
   :END:

- https://www.reddit.com/r/indonesia/comments/9640by/rekam_jejak_sikap_dan_perkataan_maruf_amin/

  - https://www.reddit.com/r/indonesia/comments/9631cu/maruf_amin_dulu_saya_yang_menggerakkan_aksi_212/

- [Pendapat seorang redditor dengan username kurang elok](https://www.reddit.com/r/indonesia/comments/97bncz/mahfud_sebut_maruf_amin_suruh_nu_ancam_jokowi/e472v4s/] tentang Maruf Amin, calon wakil presiden 2019. Pendapat ini terdengar gila, tapi mungkin. Entah.

  - "Sesuai UU kita, ketika presiden gak ada (karena meninggal atau lengser) wapres langsung auto-presiden. Disini ada insentif besar utk kaum mereka bunuh atau lengserkan presiden."

- Belum dibaca

  - [[https://www.reddit.com/r/indonesia/comments/983if1/pros_of_jokowi/][Pros of Jokowi : indonesia]]
  - [[https://www.reddit.com/r/indonesia/comments/982c5x/why_fear_over_islamists_in_prabowos_future/][Why Fear Over Islamists in Prabowo's Future Government is Unfounded : indonesia]]

*** Pendapat-pendapat yang edgy tapi mungkin ada benarnya
   :PROPERTIES:
   :CUSTOM_ID: pendapat-pendapat-yang-edgy-tapi-mungkin-ada-benarnya
   :END:

**** Jalan tol adalah tindak kejahatan.
    :PROPERTIES:
    :CUSTOM_ID: jalan-tol-adalah-tindak-kejahatan.
    :END:

- Jalan tol adalah jalan pribadi (jalan milik perusahaan, bukan jalan umum).
- Jalan S. Parman, Jalan Gatot Subroto, dan Jalan M.T. Haryono adalah jalan umum.
- Dahulukan kepentingan umum sebelum kepentingan pribadi, menurut pendidikan kewarganegaraan yang diajarkan di SD.
- Antrian tol memacetkan jalan umum.
- Sebagian kemacetan di jalan umum tersebut terjadi
  karena pemerintah membiarkan pengelola jalan tol mendahulukan kepentingan pribadi.

  - Jika antrian terlalu panjang, polisi seharusnya berhak mempercepat antrian dengan cara:

    - memaksa mengalihkan mobil dari antrian ke jalan biasa
    - memaksa membuka gerbang tol

- Tugas pemerintah hanya dua:

  - Melakukan hal yang menguntungkan banyak orang.
  - Mencegah hal yang merugikan banyak orang.

- Seandainya Pemda DKI Jakarta hendak membeli sebagian ruas jalan tol untuk dijadikan jalan umum,
  berapa biaya per kilometernya?

*** Pertanyaan-pertanyaan yang belum terjawab
   :PROPERTIES:
   :CUSTOM_ID: pertanyaan-pertanyaan-yang-belum-terjawab
   :END:

- How to combat people who provoke you and then cry foul?
- Undigested

  - Why do Habib Rizieq supporters support him?
  - 2017-06-23 government announces that they will take Rp344 trillion loan. Source?
  - If Sukarno hadn't fallen, would he have been like Gajah Mada, Washington, Castro, Kim, Mao, Stalin, Khan, or someone else?
  - Bagaimana cara impor?
  - Bagaimana cara ekspor?

- Indonesia needs a website like politifact or factcheck.org.
- Is the 21st century is the age of demagogues, or has it always been the case?
  When did candidates begin appealing to emotion using racism and religion?
  Donald Trump?
  Anies Baswedan?

**** Ada Mata Najwa, mengapa tidak ada Tangan Najwa?
    :PROPERTIES:
    :CUSTOM_ID: ada-mata-najwa-mengapa-tidak-ada-tangan-najwa
    :END:

- Apa ada hal seperti acara televisi Mata Najwa tetapi berupa tulisan?
  Tangan Najwa gitu?

**** Mengapa kita tidak minta tolong cenayang panggil arwah Bung Karno dan tanyakan kebenaran G30S PKI dan Supersemar?
    :PROPERTIES:
    :CUSTOM_ID: mengapa-kita-tidak-minta-tolong-cenayang-panggil-arwah-bung-karno-dan-tanyakan-kebenaran-g30s-pki-dan-supersemar
    :END:

Mengapa kita tidak tanya istrinya, anaknya, kerabatnya, teman-temannya?

**** Program 1000 startup ke mana?
    :PROPERTIES:
    :CUSTOM_ID: program-1000-startup-ke-mana
    :END:

- [[https://www.reddit.com/r/indonesia/comments/98afrg/anyone_know_what_happened_to_1000_startup_i_found/][Anyone know what happened to 1000 Startup? I found these three comments in a video about them. : indonesia]]

** Kesehatan

*** Permurah kesehatan?

Mengapa kesehatan mahal?

Mengapa rumah sakit mahal?

*** <2018-09-19> Ban buffets/all-you-can-eat restaurants

- Unhealthy. Induces overeating.
- Dishonest pricing.
  - [[https://www.insideedition.com/athlete-banned-all-you-can-eat-sushi-buffet-eating-too-much-46845][Athlete Banned From All-You-Can-Eat Sushi Buffet for Eating Too Much | Inside Edition]]
    - Why do you ban people?
      You know what you sign up for.
      You know everyone's diet is different.
      The eater does nothing wrong.
      If you don't like people eating too much, open a conventional a la carte restaurant.
      Buffets are food casinos.
      Buffets are insurance.
      They are all actuarial.
      It's unfair if you only want the money but don't want the risk.

*** <2018-09-19> Bantu petani tembakau dan buruh tembakau cari pekerjaan lain

*** <2018-09-22> Legalkan aborsi
Forcing someone to live the life he does not want is more immoral than killing him.
This also implies:

- We should let people kill themselves if they have thought about it well, as long as they are done privately.
  - But https://www.speakingofsuicide.com/2013/05/19/why-stop-someone-from-suicide/ dissents:
    - "The most important reason to prevent suicide is that suicidal crises, though formidable and painful, almost always are temporary.
      Even if the person continues thinking about suicide, the intense suicidal intent usually subsides.
      Consider that 90% of people who survive a suicide attempt do not go on to die by suicide.
      That number is very revealing.
      Even among people who wanted to die so strongly that they tried to end their life, most ultimately chose to live."
      - People don't know what they want.
        We don't know what we want.
- We should not prolong the suffering of dying people by forcing life support.

No baby consents to being killed.
No baby consents to being born either.
** Ekonomi

*** Prinsip ekonomi

- Mandirikan bangsa.
  Maksimalkan produksi dalam negeri.
  Kemandirian adalah syarat perlu tetapi tidak cukup untuk kedaulatan.

*** Kurangi nilai impor.

- Tingkatkan produksi dalam negeri, terutama industri strategis, teknologi.
- Bangun daerah tertinggal, kurangi urbanisasi.

*** Bantuan langsung tunai (BLT) = cash transfers
   :PROPERTIES:
   :CUSTOM_ID: bantuan-langsung-tunai-blt-cash-transfers
   :END:

- [[https://www.livemint.com/Politics/144kmvZXyDiM40UxY66DYJ/Targeted-cash-transfer-schemes-can-do-more-harm-than-good.html][Targeted cash transfer schemes can do more harm than good - Livemint]]
- Giving money to poor people immediately increases their purchasing power, but there are consequences.
- They buy things, increasing demand.
- If there is not enough supply, then prices rise.
- Conclusion:

  - In the short term, cash transfers provides immediate relief to poor people.
  - In the long term, cash transfers hurts the poor people it intends to help.
  - To help the poor, the government should increase the supply of goods to the poor.

    - Ideal permanent strategic solution: increase aggregate efficiency to drive down costs.

      - Localize production.
        Avoid transportation.
        Transportation is waste.
      - Depend on renewable energy.
        The sun is free!
        Wind is free!
        The TCO (total cost of ownership) of solar is approaching that of coal/oil?
      - Good infrastructure to reduce transport time/cost.
      - Integrate transport modes to reduce transport costs?

    - Quick temporary tactical solution: subsidies.

- Basic income is unconditional cash transfers.
** Survei tanah, konflik agraria, sertifikasi tanah?

** Pendidikan
*** Tingkatkan gaji dan mutu guru?

*** <2018-09-22> Perbaiki cara mengajar sejarah

- Tidak perlu menghapal hal-hal yang dicari dalam 1 menit di Internet.
- Yang penting ialah memahami sebab/konteks sesuatu terjadi, terutama perang.

*** 100% literacy rate; budayakan membaca dan menulis

Jordan Peterson: "The best way to teach people critical thinking is to teach them to write." ([[https://www.youtube.com/watch?v=x0vUsxhMczI][source]])

*** Bahasa Inggris (dan Mandarin?)

*** Memberantas kebodohan
   :PROPERTIES:
   :CUSTOM_ID: memberantas-kebodohan
   :END:

**** Benci suku tertentu itu merugikan diri sendiri

WNI keturunan Cina itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Cina?
Pemerintah Cina saja tidak peduli.

WNI keturunan Arab itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Arab?
Pemerintah Arab saja tidak peduli.

WNI keturunan India itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah India?
Pemerintah India saja tidak peduli.

Dan seterusnya.
** Golkar (golongan karya, functional group)

https://historia.id/modern/articles/golkar-sebagai-pengganti-partai-vxmrP:
"Mulanya golongan fungsional atau golongan karya adalah pengganti sistem kepartaian. Sukarno yang menggagasnya."

https://www.tutor2u.net/politics/reference/functional-representation

http://www.oxfordreference.com/view/10.1093/acref/9780199207800.001.0001/acref-9780199207800-e-524
"Functional representation may be contrasted to the more usual form of territorial representation [...]"

https://www.kompasiana.com/faizrahman/54f82194a33311ae608b4bde/urgensi-perwakilan-fungsional-dalam-majelis-permusyawaratan-rakyat

https://id.wikipedia.org/wiki/Utusan_Golongan
** Berinteraksi dengan pemerintah
   :PROPERTIES:
   :CUSTOM_ID: berinteraksi-dengan-pemerintah
   :END:

- [[https://www.reddit.com/r/indonesia/comments/97pzfs/adakah_cara_untuk_browsing_mencari_uu_permen_dll/][Adakah cara untuk browsing / mencari UU, PERMEN, dll berdasarkan topik? : indonesia]]

  - JDIH (Jaringan Dokumentasi dan Informasi Hukum)

Kontak DPR, sampaikan aspirasi
Kenapa ada banyak cara?
Yang mana yang dipakai?

- http://www.adangdaradjatun.com/berita-dpr/1769-cara-mengadu-ke-dpr
- http://satulayanan.id/layanan/index/92/pengaduan-anggota-dpr/dpr-ri
- https://pengaduan.dpr.go.id
- http://www.dpr.go.id/index/kontak
- https://mobile.twitter.com/DPR_RI/status/558192636222132224
- http://rumahaspirasi.dpr.go.id/layanan
- http://m.metrotvnews.com/play/2015/03/22/374732

*** Mengubah sistem hukum dari retributive justice ke restorative justice
    :PROPERTIES:
    :CUSTOM_ID: mengubah-sistem-hukum-dari-retributive-justice-ke-restorative-justice
    :END:

- http://ksp.go.id/pemerintah-luncurkan-portal-aspirasi-dan-pengaduan-nasional/index.html
- Bergabung saja ke ANRKUHP.
  Liaison ANRKUHP dan RJI (Restorative Justice International/Indonesia)?

  - https://m.cnnindonesia.com/nasional/20180612195019-12-305684/icjr-dorong-20-hukuman-alternatif-selain-penjara-di-rkuhp

- ICJR.

Kapan terakhir kali RJI mengirim surat/email ke DPR?
Surat tersebut ditujukan kepada bagian DPR yang mana?

*** Jangan penjarakan koruptor. Cukup sita curiannya.
    :PROPERTIES:
    :CUSTOM_ID: jangan-penjarakan-koruptor.-cukup-sita-curiannya.
    :END:

Koruptor tidak takut dipenjara.
Koruptor takut miskin.

** Deradikalisasi seperti Singapura
   :PROPERTIES:
   :CUSTOM_ID: deradikalisasi-seperti-singapura
   :END:

Contohlah Singapura.
Mereka mencampur penduduk berbeda suku dalam setiap pemukiman.

** Cara memilih anggota DPR dan DPD
   :PROPERTIES:
   :CUSTOM_ID: cara-memilih-anggota-dpr-dan-dpd
   :END:

- Anda memilih partai politik. Anda tidak memilih anggota DPR secara langsung. (UUD 1945 pasal 22E ayat 3.)
- Anda memilih anggota DPD secara langsung. (UUD 1945 pasal 22E ayat 4.)

Cari dan pahami latar belakang, profil, dan cita-cita partai-partai politik.

Pilih partai yang cita-citanya sejalan dengan cita-cita Anda.

Partai tersebut akan menempatkan beberapa anggota mereka di DPR.

Bantu mereka melaksakan tugas dengan memberi saran, melaporkan penyimpangan, dll.

** Mencari partai
   :PROPERTIES:
   :CUSTOM_ID: mencari-partai
   :END:

Saya mencari partai orang yang berpikir mandiri.

** Komputerisasi untuk menidakmungkinkan korupsi?
   :PROPERTIES:
   :CUSTOM_ID: komputerisasi-untuk-menidakmungkinkan-korupsi
   :END:

Karena komputer zakelijk.
Tidak ada kongkalikong.

** Tumpang tindih tugas BPK, KPK, polisi, bareskrim, tim tastipikor, dll.?
   :PROPERTIES:
   :CUSTOM_ID: tumpang-tindih-tugas-bpk-kpk-polisi-bareskrim-tim-tastipikor-dll.
   :END:

Semuanya sama-sama memeriksa keuangan.

** Hancurnya negara ini adalah salah kita yang menolak berpolitik.
   :PROPERTIES:
   :CUSTOM_ID: hancurnya-negara-ini-adalah-salah-kita-yang-menolak-berpolitik.
   :END:

Menolak berpolitik berarti membiarkan negara hancur.

Menolak berpolitik berarti membiarkan pengacau menang.

Membiarkan kesalahan artinya ikut salah.

Membiarkan penindasan artinya ikut menindas.

Membiarkan ekstremis merajalela artinya merestui ekstremisme.

[[https://en.wikipedia.org/wiki/First_they_came_...][WP:First they came...]]

** Legislatif lebih penting daripada eksekutif.
   :PROPERTIES:
   :CUSTOM_ID: legislatif-lebih-penting-daripada-eksekutif.
   :END:

Media harus lebih banyak meliput legislatif daripada eksekutif.

Selama ini media salah.
Yang diliput eksekutif terus.
Legislatif lebih penting.

Legislatif membentuk sistem.

Legislator bagus akan mencegah eksekutor buruk.
Eksekutor bagus tidak bisa mengatasi legislator buruk.

Lebih mudah meliput eksekutif karena ada kegiatan yang tampak.

Meliput legislatif lebih susah karena harus mengerti filsafat hukum.

** Fadli Zon Library
   :PROPERTIES:
   :CUSTOM_ID: fadli-zon-library
   :END:

[[https://id.wikipedia.org/wiki/Fadli_Zon_Library][WP:Fadli Zon Library]]

Ada kajian/diskusi?
Jadwal?

** Mengatasi sesat pikir
   :PROPERTIES:
   :CUSTOM_ID: mengatasi-sesat-pikir
   :END:

- [[http://partaigerindra.or.id/2015/04/28/gerindra-dukung-eksekusi-mati-agar-bandar-narkoba-jera.html][Gerindra Dukung Eksekusi Mati Agar Bandar Narkoba Jera]]

  - Orang mati mana bisa jera (kapok)?
    Kalau mau bikin orang jera, suruh dia ganti rugi.
    Obati semua korbannya.
    Kembalikan masa depan mereka yang hilang.
    Bayar.

** Narasi berbeda antara eksekutif dan legislatif
   :PROPERTIES:
   :CUSTOM_ID: narasi-berbeda-antara-eksekutif-dan-legislatif
   :END:

Eksekutif bilang ekonomi tumbuh.
Legislatif bilang hidup makin sulit.

Dua-duanya betul.
Ekonomi tumbuh.
GDP memang tumbuh.
Tapi apa arti GDP?
** Kewajiban dan hak warga negara
*** BPJS?
- [[https://daftar.bpjs-kesehatan.go.id/bpjs-checking/][Cek saldo BPJS]]
- [[https://sso.bpjsketenagakerjaan.go.id/registrasi.bpjs][Ini registrasi apa?]]
  Kenapa harus registrasi?
*** Pemerintah menyediakan akses ke jurnal berbayar? Di mana? Cara pakainya?
*** Jangan abstain dalam pemilu.
Lihat argumen [[https://www.reddit.com/r/indonesia/comments/968qbs/ajakan_untuk_yang_tidak_cocok_dengan_pasangan/e3yw8bd/][/u/kolormelar]].
*** Bayar pajak
- https://djponline.pajak.go.id/account/login
  - http://www.pajak.go.id/article/jangan-panik-jika-lupa-kode-efin-ikuti-langkah-berikut
** Internet censorship in Indonesia
- <2017-10-06> The ministry spent IDR 211 billion to censor the Internet. https://kominfo.go.id/content/detail/10860/kominfo-umumkan-pemenang-tender-mesin-sensor-internet-rp-211-miliar/0/sorotan_media
- <2018-08-09> The ministry begins censoring Google search results. https://tekno.kompas.com/read/2018/08/09/17183717/mulai-besok-netizen-indonesia-tak-bisa-lagi-googling-gambar-porno
** BPJS?
https://pinterpolitik.com/dokter-goodbye-jokowi/

<2018-11-02>
Dalam praktek, BPJS hanya bagus buat PNS, dan shitty buat non-PNS.
- https://www.reddit.com/r/indonesia/comments/9t2hby/anyone_using_health_insurance/
  - Ada orang yang *lima* kerabatnya *mati* karena *BPJS terlalu lambat*.
  - I can confirm that.
    Orang tua saya nunggu *12 jam* ngantri di rumah sakit pakai BPJS.
    Berangkat pagi, pulang malam.
    Padahal hanya periksa.
    12 jam itu nunggunya doang.
    Orang-orang rumah sakitnya juga ogah-ogahan.
- https://www.reddit.com/r/indonesia/comments/832kmh/dokter_protes_ke_pemerintah_dibayar_seharga/

** Negara tidak perlu mengatur agama.
- https://www.reddit.com/r/indonesia/comments/9r72uj/pgi_keberatan_atas_2_pasal_di_ruu_pesantren_dan/
** Laporan penggunaan pajak oleh negara
- https://www.kemenkeu.go.id/alokasipajakmu
  - https://www.reddit.com/r/indonesia/comments/9qkd3m/as_an_early_adult_who_recently_graduated_from/
** Indonesia market research: effect of sharia label on buying propensity?
Does slapping a sharia label on a hotel increases its sales?
** Twitter
- [[https://twitter.com/Julie_C_Hwang][Julie Chernov Hwang]] "Professor. Author. Why Terrorists Quit: The Disengagement of Indonesian Jihadists @cornellpress. I research entry & exit from terrorism. Islamism. SE Asia"
- https://twitter.com/pscindo
- https://kyotoreview.org/issue-24/twenty-years-after-suharto-dynastic-politics-and-signs-of-subnational-authoritarianism/
  - What is subnational authoritarianism?
  - "In 2013, the Indonesian Ministry of Home Affairs found that at least 60 political dynasties exist throughout Indonesia."
  - "During Suharto’s regime, dynastic politics did not exist at the subnational level, except at the village level."
  - "Dynastic politics is a rational option for politicians who aspire to prolong and strengthen their grip on local politics."
* Interdisciplinary comments
** Software and law
Creating a law without caring about how it will be enforced is like creating a program without caring about how it will be executed.
No wonder the nation feels shitty and the machine feels slow.
* Virtual hotel operators
** Who is OYO CTO?
From a 2016 article[fn::https://www.livemint.com/Companies/GfBdOyw5rNidPCkmwc2KSJ/OYO-Rooms-appoints-Anil-Goel-as-chief-technology-officer.html]:
- In 2016, OYO gets new CTO: Anil Goel[fn::https://in.linkedin.com/in/anilgoel1]
- 20 years of experience in technology infrastructure
- past head of technology for customer returns and reverse logistics at Amazon India in Hyderabad for three years
- past chief technology officer of Hike Messenger

Is he more of the practical-type than the researcher-type?
Is he more about business than about research?
One interview question is "What is considered as a good business plan?"
 [fn::https://www.geeksforgeeks.org/oyo-rooms-interview-experience-for-software-engineer/]

"[...] he went to BITS Pilani in 1991"[fn::https://yourstory.com/2018/02/techie-tuesdays-anil-goel].
Thus he was probably 18 years old in 1991, and 46 years old in 2019.

<2018-09-21>
"OYO plans to hire over 2,000 tech experts, engineers by 2020"
 [fn::https://www.thehindubusinessline.com/companies/oyo-plans-to-hire-over-2000-tech-experts-engineers-by-2020/article25005997.ece]:
- OYO is backed by Softbank and Sequoia
- "we will continue to invest in technologies like artificial intelligence, machine learning,
  and IoT that will make curated guest experiences at every price point a reality,
  while ensuring sustainable income for partners and livelihood opportunities for several Indians."
- "we are glad to partner with the government in its goal of creating millions of economic opportunities"

Ajay Shrivastava was the previous CTO?[fn::https://in.linkedin.com/in/ajayshrivastava1]

https://www.linkedin.com/pulse/solver-teams-oyo-hyper-agile-well-oiled-execution-ajay?published=u
** How many VPs does OYO have?
- <2017-04-13> Suvesh Malhotra, VP of engineering[fn::https://www.oyorooms.com/officialoyoblog/2017/04/13/welcoming-suvesh-malhotra-to-the-team]
- <2018-09-21> Priyank Chaudhury, VP of technology[fn::https://twitter.com/oyorooms/status/1043108964542468096]
- Shreerang Godbole, VP of people operations[fn::https://in.linkedin.com/in/shreeranggodbole]
- Ayush Mathur, VP of business development[fn::https://in.linkedin.com/in/ayush-mathur-94004918]
- Closed job: VP/AVP/Director of engineering[fn::https://in.linkedin.com/jobs/view/vp-avp-director-of-engineering-at-oyo-1190146439]
- Job description: VP of engineering[fn::https://oyorooms.taleo.net/careersection/ex/jobdetail.ftl?job=18000562&tz=GMT%2B07%3A00&tzname=Asia%2FJakarta]
** <2019-04-30> What is OYO doing?
Information sources:
- OYO Engineering & Data Science at Medium[fn::https://medium.com/@oyoengineering]
- OYOTech at Medium[fn::https://medium.com/oyotech/tagged/oyo]
- Official Oyo blog[fn::https://www.oyorooms.com/officialoyoblog/]

OYO Now![fn::https://medium.com/@shreyas.v.joshi]

<2019-04-02>
Spend USD 100 million in Indonesia[fn::https://bisnis.tempo.co/read/1191625/incar-100-kota-di-indonesia-oyo-hotel-kucurkan-usd-100-juta/full&view=ok]

<2019-04-02>
From 0 to 500 properties in 5 months.

<2019-04-09>
Oyo Wizard Membership[fn::https://www.oyorooms.com/officialoyoblog/2019/04/09/oyo-wizard-membership] seems to be a customer loyalty program.

<2019-04-30>
"We introduced pioneering technology to the hospitality industry to deliver better and more efficient
/operations, management, service and CRM/. Our app allows a user to book a room in just 3 taps, or within 5 seconds."
 [fn::https://www.oyorooms.com/about?oyocorporate=]
(emphasis mine)
** What is Oyo doing with its engineers?
** OYO tech stack
In 2016, they are using pretty much a standard tech stack:
 [fn::https://in.linkedin.com/jobs/view/senior-software-engineer-at-oyo-1107116583]
 [fn::https://startup.jobs/47930-software-engineer-at-oyorooms]:
- They are using "Java/J2EE, Lamp, GoLang, Python/DJANGO" for their property management system
  ("You will work at an intersection of Finance, Business and Technology - owning end to end development of features that help us cater to our Hotel Partners.")
- Java/Python/Ruby/C++
- SQL
- Amazon Web Services

Spring Framework (Java)[fn::https://www.glassdoor.co.in/Interview/OYO-Full-Stack-Developer-Interview-Questions-EI_IE953789.0,3_KO4,24.htm]

"Easy" competitive programming questions.
(Easy for competitive programmers, somewhat hard for non-competitive programmers.)

From the previous CTO Ajay[fn::https://in.linkedin.com/in/ajayshrivastava1]:
- Website - Ember.js, Node.js, Javascript, Foundation, Bootstrap, HTML, CSS. Mobile - Android, Java, Objective C
- Analytics - Hadoop, Map reduce, Amazon EMR.
- Backend - Ruby on Rails, JRuby, Amazon Web Services, Data stores (Postgres, MongoDB, Redis, Memcache).
- Quality - Java, Selenium

They used Ruby on Rails,
according to one employee.[fn::https://www.quora.com/Which-development-platform-and-technology-are-used-by-OYO-Rooms]

But they are moving from Ruby to Java:
"Almost all teams breaking the current code(Ruby on Rails) into new Micro-services (Java)"[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW22416076.htm]
** OYO tech blog
- https://www.oyorooms.com/officialoyoblog/category/tech
** OYO software engineer interview experience
January 2018 Gurgaon interview questions.
20-30 applicants.
 [fn::https://www.geeksforgeeks.org/oyo-rooms-interview-experience-set-8-software-engineer/]
** OYO software engineer salary
<2019-04-08>
Glassdoor[fn::https://www.glassdoor.co.in/Salary/OYO-Software-Engineer-Salaries-E953789_D_KO4,21.htm]:
INR 900,000 (IDR 183,569,926 nominal, IDR 212,727,600 PPP-adjusted) per year.
About IDR 17,727,300 real per month.
This is before taxes.

INR 1,125,000 according to Hush[fn::https://hush.company/oyo-rooms/salaries/software-engineer/].

<2019-04-12>
Cost of living per month in Mumbai for a bachelor[fn::https://www.numbeo.com/cost-of-living/in/Mumbai]:
- INR 26,000 for expenses without rent
- INR 40,000 for 1-bedroom apartment in city center

Total cost of living in Mumbai for a bachelor: INR 792,000 per year.

Mumbai seems to be the most expensive city.
They are hiring in other cities.
Bangalore living cost is about 1/2 to 2/3 of Mumbai.

<2019-04-12>
2017 purchasing-power-parity adjusted data[fn::https://data.oecd.org/conversion/purchasing-power-parities-ppp.htm]:
- USD 1 = INR 17.729 PPP-adjusted
- USD 1 = IDR 4,190.492 PPP-adjusted
- INR 1 = IDR 236.364 PPP-adjusted
- INR 1 = IDR 203.97 nominal
** Disgruntled ex-OYO employees
There are some disgruntled ex-OYO-bizdevs[fn::https://www.glassdoor.com/Reviews/OYO-new-cto-Reviews-EI_IE953789.0,3_KH4,11.htm].

They probably have non-compete agreements.

Are non-compete agreements legal in India?

Are non-compete agreements legal in Indonesia?

Probably a disgruntled female engineer[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW24717895.htm]

Probably an overworked biz-dev[fn::https://www.glassdoor.com/Reviews/OYO-Software-Engineer-Reviews-EI_IE953789.0,3_KO4,21.htm]

<2018-09-11>
A damning review from "Join OYO only if you are desperate. Honest 2018 review with no bias."
Current Employee - Software Engineer in Gurgaon, Haryana[fn::https://www.glassdoor.com/Reviews/Employee-Review-OYO-RVW22416076.htm]:
- Politics , politics everywhere.
- Large salary disparity.
  You'll join only to know there are ppl in your team getting much higher than you get and than they deserve.
  CTO has a fetish for hiring people from Hike and Amazon.
He has worked at both places earlier.
So he's pretty much bringing in everyone he knows from these places (I am not saying they are not good), but they will be given important roles than you, without question.
- Almost all old employees have left/asked to leave Here's a red flag.
  The employees who joined during the time of old VP Ajay were now being called non-smart hires.
  The CTO has replaced EACH AND EVERY ONE OF THEM.
  They were the people who gave their blood and sweat to build OYO as it is today.
  OYO has a technique to make you leave the company now.
  They'll hire someone totally new and make them sit over you on higher position, to take away you responsibilities.
  Or they'll just give you no hike.
  So you'll and leave.
  I was hired after the new CTO came but the older guys were so awesome.
  Now there are hardly 5 older guys left.
  Whole tech team replaced.
- There's a flood of freshers.
  They hired more than 200 freshers in one batch from IITs(any branch)/good colleges against 70 devs who were left at one time.
  No one has any idea of the legacy system.
  There's total chaos.
  Much time goes in doing their ramp up if you're an old employee.
  So by the evening you'll feel to do the work yourself instead of teaching them everything.
- In the last 6 months, they made jokingly new teams,to accommodate the new hires, and hired managers from outside for almost all of them.
  most of them total jerks.
- 90% people leave within 1 year of joining.
  So my advice: If you're a fresher or don't have any opportunity from anywhere else.
  OYO will be a good place as you can learn.
  But then again come with no expectations of respect or growth, as you'll watch it getting shattered within 6 months.
  My papers on their way.

But there are other good reviews too.
** OYO job openings
Software development engineer[fn::https://www.glassdoor.com/Job/bengaluru-software-development-engineer-bangalore-jobs-SRCH_IL.0,9_IC2940587_KO10,49.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3002042947&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=102&t=EMPLOYER_SEARCH_RESULTS]

3+ years of strong hands-on development experience including at least 1.5 years of real-world web development experience using JSP, Java Servlets, Java Struts, Spring, & Hibernate

- Good understanding of design patterns, object oriented design, and frameworks
- Good RDBMS skills and experience in DB/SQL
- Experience with multiple technologies - LAMP, Ruby on Rails, Python, Perl, Java, PHP
- Exposure to MVC frameworks such as Rails, Spring, Django, CodeIgniter.
- Experience working with scripting language such as Pearl [sic] - to quickly roll our parsers for analysis and write small modules - is preferred
  [WTF is Pearl? You mean Perl?]
- Exposure to Postgres, Mysql (exposure to NoSQL database related technologies like MongoDB, Redis, Aerospike, Cassandra etc. is a plus)
- Experience with SCRUM methodology or extreme programming is a great plus
- Exposure to app servers like JBoss, WebLogic, WebSphere
- Previous start-up experience or contribution to any open source project
- Experience working on DROOLS or any other rule engine and SOAP/string based API integrations

https://www.glassdoor.com/Job/hyderabad-software-development-engineer-23-jobs-SRCH_IL.0,9_IC2865319_KO10,42.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3130003429&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=104&t=EMPLOYER_SEARCH_RESULTS

IoT engineer:
They don't bother writing the "What will you need to be successful in this role?" section.
It is an exact copy of that of the back-end engineer.
- https://www.glassdoor.com/Job/bengaluru-software-development-engineer-ii-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,46.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3127022842&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=105&t=EMPLOYER_SEARCH_RESULTS
- https://www.glassdoor.com/Job/bengaluru-software-development-i-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,36.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3127023307&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=107&t=EMPLOYER_SEARCH_RESULTS

ACP? What is ACP?
https://www.glassdoor.com/Job/hyderabad-software-development-engineer-ii-iii-acp-jobs-SRCH_IL.0,9_IC2865319_KO10,50.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3187186317&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=106&t=EMPLOYER_SEARCH_RESULTS
** In 2016 it seems that they are focusing on wifi experience
- https://www.oyorooms.com/officialoyoblog/2016/09/02/home-is-where-wifi-is
  - It seems that wifi is important?
    Is wifi important for customers?
    Is bad wifi a deal-breaker?
  - OYO app automatically enters wifi password, but how does that work without intruding into the user's phone?

Firmware engineering manager[fn::https://www.glassdoor.com/Job/bengaluru-firmware-engineering-manager-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,42.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3131744908&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=112&t=EMPLOYER_SEARCH_RESULTS]:
- Deep hands-on technical experience in RTOS, at-least one of these Wireless technologies (BLE 4.2 or 5.0 with Mesh, LoRaWAN, 6LoWPAN, Zigbee, Thread, Sub-GHz RF),
  interfacing with multiple devices on UART, I2C, SPI, object-oriented design, data structures, algorithm design, High-level architecture design and complexity analysis
- Good-to-have: Experience of working on IoT projects at-scale - Smart-lock, Home Automation, Vehicle tracking, etc.

Firmware engineer[fn::https://www.glassdoor.com/Job/bengaluru-firmware-engineer-iot-jobs-SRCH_IL.0,9_IC2940587_KO10,31.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3103540384&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=113&t=EMPLOYER_SEARCH_RESULTS]
- Sound experience of developing firmware on ARM Cortex, MSP430, AVR, DSP, or other embedded platforms for 16/32 bit microcontrollers.
- Background in Systems Programming, Operating Systems, RTOS, IoT Protocols MQTT, CoAP.
- Experience with Wi-Fi, Bluetooth development, and BLE solutions.
- Knowledge of communication protocols: I2C, SPI, UART.
- Excellent programming skills in one or more of the following: C/C++/JAVA/Python with a proven capability of delivering high-quality code.
- Familiar with the use of embedded toolchains, ICE/JTAG debuggers, etc.
- Good to have - understanding of Wifi triangulation, indoor location tracking & mapping techniques.

"Oyo Rooms wants to share digital record of your check-ins with government"
 [fn::https://www.indiatoday.in/technology/news/story/oyo-rooms-wants-to-share-digital-record-of-your-check-ins-with-government-1431439-2019-01-15]
 [fn::https://en.wikipedia.org/wiki/OYO_Rooms]
** OYO glassdoor
Not only software engineers?
https://www.glassdoor.com/Reviews/OYO-new-cto-Reviews-EI_IE953789.0,3_KH4,11.htm
Pros:
- "Good work Environment and many things to learn at a go" (in 48 reviews)
- "Team leaders are well qualified (except some) and you learn a lot from them" (in 18 reviews)
- "Nice work culture of the company" (in 31 reviews)
- "work from home , beer in office , flexible working hours" (in 14 reviews)
- "a lot of opportunities to learn" (in 12 reviews)

Cons:
- "6 days a week is something that the management needs to work to ensure proper work life balance" (in 92 reviews)
- "No work life balance need to handle escalation" (in 32 reviews)
- "Long working hours and work not challenging" (in 29 reviews)
- "No work-life balance, no job-security" (in 13 reviews)
- "Work culture, Hire and fire policy" (in 11 reviews)
** Government
"exemption [of taxes] for hotels that charge Rs 1,000 or lesser, and lower tax rates for those charging less than Rs 2,500"
 [fn::https://yourstory.com/2018/01/oyos-ritesh-agarwal-talks-full-stack-model-expects-budget]

"This government has showcased [its] ability to be [unpredictable]"
** Does OYO have a research team?
Either OYO does not have a research team, or it is secret.
But, the CTO seems to be business-oriented,
so I think they don't have software engineering research.
** Who are some example OYO engineers?
What are their beliefs about software engineering?
** Who are some employees below VP?
- senior engineering manager https://in.linkedin.com/in/shashankjain89 https://in.linkedin.com/in/varunpathak
- senior principal engineer https://in.linkedin.com/in/dksidana
- ex-senior engineer https://in.linkedin.com/in/anshulnigam who "Owned and delivered Leads Management System, Owner Portal, Studio Stays, Meal Plans, OYO Getaways (now called OYO Hotel Packages); and worked on Hotel Agreements, Reconciliations, Owner/Hotels Payments, Payment Gateways integration for consumer payments, CRS(Central Reservation System), Lifeline, integration of SAP with CRS."
** What do OYO recruiters think a VP of engineering do?
https://www.glassdoor.com/Job/vp-avp-director-of-engineering-jobs-SRCH_KO0,30.htm?src=GD_JOB_AD&rdserp=true&srs=EI_JOBS&jl=3083569104&ao=7438&s=21&guid=0000016a11df5d44b1d0113f56610e12&pos=118&t=EMPLOYER_SEARCH_RESULTS
** Dirts
*** September 2018 sexual harassment
In September 2018, a female guest Jordan Taylor reported sexual harassment by some staffs in an OYO-branded property.
- https://www.thenewsminute.com/article/stalked-trapped-hotel-us-travel-blogger-recounts-sexual-harassment-india-88186
  - from https://www.thehindubusinessline.com/companies/oyo-plans-to-hire-over-2000-tech-experts-engineers-by-2020/article25005997.ece

I think this is a culture clash.

From the point of view of the perpetrators, they were teasing the girl.
I don't think those Indian guys really dared to rape her,
because they would surely go to jail if they did.

However, from the point of the Western girl (and also Western people in general),
that interaction is really creepy, abnormal, and outside the bounds of civility.

Nonetheless, it is improper and totally unacceptable for workers in the hospitality industry to behave like that,
because they are in the hospitality industry, and they are expected to be hospitable.

"However OYO maintains that few incidents are insignificant compared to millions of check-ins happening everyday and the company tries to remedy any problem."
 [fn::https://en.wikipedia.org/wiki/OYO_Rooms]
*** <2019-04-16> From Wikipedia
From Wikipedia[fn::https://en.wikipedia.org/wiki/OYO_Rooms].

"OYO has been in news for using predatory pricing using its funding money to unfairly remove competition.
It was also reported that OYO was not following its own agreements and have threatened the hotels to
unilaterally change some of the clauses or suffer the consequences of non-payment."

"Oyo Rooms had sent mass unsolicited job offer emails targeting senior- and mid-level employees of competitor companies."

"It was reported by Business Standard in 2017 that OYO rooms were making massive losses without showing any significant revenues."
* Cooking
** Why preheat pan (heat pan after putting in oil but before putting in food)?
"The oil gives off visual clues telling you just when you need to start adding ingredients."[fn::https://www.reluctantgourmet.com/frying-pan-temperature-video/]
