#+TITLE: Catchment area
#+DATE: 2018-07-22 13:15 +0700
#+PERMALINK: /other.html
#+OPTIONS: ^:nil toc:nil
#+TOC: headlines 1
#+TOC: headlines 3
* The purposes of this page
- This page is a holding area for my capture-refile workflow.
- This page is for recycling old content.
* Research

** Problems

- 2005, article, "Why Most Published Research Findings Are False", John P. A. Ioannidis, [[http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020124][html]]

** Finding research papers?

- [[https://www.deutsche-digitale-bibliothek.de/?lang=en][Deutsche Digitale Bibliothek - Kultur und Wissen online]] (English available)

** Mathematical knowledge management?
- [[https://github.com/planetmath][Planetmath]] is a collection of TeX documents.
  - Can it be made into a mathematical knowledge management system?
- https://wikieducator.org/Main_Page
** Academic writing
  - "How to write a good CVPR submission", [[https://billf.mit.edu/sites/default/files/documents/cvprPapers.pdf][pdf slides]]

** Math PhD?
- 2011, article, "A Very Rough Guide for PhD Students in Mathematics", [[http://www.maths.manchester.ac.uk/media/eps/schoolofmathematics/study/guide_2011.pdf][pdf]]

** Mathematical modeling?
  - [[https://en.wikipedia.org/wiki/Mathematical_model][WP:Mathematical model]]
  - [[https://en.wikipedia.org/wiki/Many-body_problem][WP:Many-body problem]]
  - [[https://en.wikipedia.org/wiki/Few-body_systems][WP:Few-body systems]]
  - [[https://en.wikipedia.org/wiki/N-body_problem][WP:N-body problem]]
  - Articles
    - [[https://aip.scitation.org/doi/10.1063/1.533319][The quantum N-body problem]]
  - What is the difference between variable and parameter?
  - How many parameters do we need to model a system?
  - Discrete Newtonian kinematical model
    - A /system at time \( t \)/ is a set of particles ( { 1, \ldots, n } ).
      - Time is a real number: \( t \in \Real \).
      - The number of particle is constant \( n \in \Nat \).
      - For each particle \( k \):
        - It has /position/ \( x_k \in \Real^3 \).
        - Simplifying assumptions
          - particle
            - It is a point.
              - It doesn't occupy any space.
            - Its mass is not modeled.
          - Time is global and absolute (the same everywhere).
  - Discrete Newtonian dynamical model (N-body problem) extends discrete Newtonian kinematical model.
    - A /system at time \( t \)/ is all that above, plus:
      - For each particle \( k \):
        - It has /mass/ \( m_k \in \Real \).
        - It has /resultant force/ \( F_k \) acting on it.
        - Simplifying assumptions about the particle
          - It is rigid.
            - It doesn't deform.
            - It doesn't break.
          - Its mass is constant.
          - It don't interact with other particles.
            - Particles don't merge or collide.
  - [[https://en.wikipedia.org/wiki/Continuum_mechanics][WP:Continuum mechanics]]
  - Skippable philosophical issues?
    - Does "the same particle at different times" make sense?
      - What is "same"?
    - [[https://en.wikipedia.org/wiki/Heraclitus#Panta_rhei,_%22everything_flows%22][WP:"Panta rhei" ("Everything flows"), Heraclitus]]
** Common company wiki fundamental problem
- Employees have no reason to read the wiki.
- It doesn't help them do their jobs.
  - Why should they read it then?
** Library problems
  - In 2018, a lot of human knowledge is still in libraries and not available on the Internet.
    Digital typesetting was invented relatively recently.
    Papers should be scanned and OCR-ed.
    AI can help.
  - Why are there different libraries?
    There should be only one library in the world.
    All library should be the same.
    All library should have the same content.
** Applying probability theory and statistics to marketing and pricing

- https://medium.com/airbnb-engineering/learning-market-dynamics-for-optimal-pricing-97cffbcc53e3
- https://overflow.buffer.com/2018/08/13/predicting-churn/

** Wikipedia alternatives?
- https://en.wikipedia.org/wiki/Wikipedia:Other_projects_similar_to_Wikipedia
- https://en.wikipedia.org/wiki/Wikipedia:Alternative_outlets
- https://www.quora.com/What-are-the-best-alternatives-to-Wikipedia
- https://everipedia.org/wiki/InterPlanetary_File_System/
  - Everipedia and IPFS?
- https://oedb.org/ilibrarian/top-7-alternatives-to-wikipedia/
** AI/ML?

- https://thegradient.pub/nlp-imagenet/
- https://chrisalbon.com/
- https://createmomo.github.io/2017/09/12/CRF_Layer_on_the_Top_of_BiLSTM_1/

*** Judea Pearl, "book of why", causal inference

- https://twitter.com/yudapearl/status/1016858846034210816
  - 2018, "The Seven Tools of Causal Inference with Reflections on Machine Learning", Judea Pearl, [[http://ftp.cs.ucla.edu/pub/stat_ser/r481.pdf][pdf]]
    - book, "The book of why [...]", Judea Pearl

** Programming language research

*** Self-composable programming?

- [[https://arxiv.org/abs/1612.02547][1612.02547 - Self-composable Programming]]

*** Generate REST API from database

- [[https://github.com/PostgREST/postgrest][PostgREST/postgrest: REST API for any Postgres database]]
  - https://restifydb.com/
  - https://www.progress.com/blogs/restify-databases-expose-your-database-to-rest-web-services
  - http://www.odata.org/getting-started/understand-odata-in-6-steps/

** Philosophy

*** First- vs third-person view?

- [[http://consc.net/notes/first-third.html][The First-Person and Third-Person Views]]

*** Morality

- Blind pursuit of Equal OUTCOME leads to an "Abomination of Justice" - Jonathan Haidt; [[https://www.youtube.com/watch?v=cQNaT52QYYA][video]]
- [[https://www.youtube.com/watch?v=vs41JrnGaxc][Jonathan Haidt: The moral roots of liberals and conservatives - YouTube]]
- https://www.yourmorals.org/aboutus.php
- https://www.moralfoundations.org/

*** Evolutionary ethics

- https://en.wikipedia.org/wiki/Evolution_of_morality
- https://en.wikipedia.org/wiki/Evolutionary_ethics
- Evolutionary ethics
    - Morality is shaped by evolution.
    - We have difficulties defining what is "good", but there are things that we agree are good.
    - Morality is defined by the majority opinion.
    - Humans evolved morality because morality promotes survival.
        - Nature selects moral behavior. There is evolutionary pressure for moral behavior.
            - Sharing foods promotes survival.
            - Sharing knowledge promotes survival.
            - Cooperation promotes survival.
            - Marriage promotes survival?
            - Monogamy promotes survival?
    - The morality of a species is whatever evolved behavior that promotes its survival.
- https://en.wikipedia.org/wiki/Evolutionary_ethics
- https://en.wikipedia.org/wiki/Evolution_of_morality

** Refuting bullshit

- [[https://en.wikipedia.org/wiki/Bullshit#Bullshit_asymmetry_principle][WP:Bullshit asymmetry principle]]
  - "The amount of energy needed to refute bullshit is an order of magnitude bigger than to produce it."
  - Does that mean it's easier to fight a bullshit with another bullshit?
    - Why don't we fight bullshit with bullshit?
    - Why don't we fight false news with false news?
    - Why don't we fight hoaxes with hoaxes?
    - Why don't we fight propagandas with propagandas?
    - If we fight lies with lies, everybody loses?

** Teaching and learning
  - How to teach history (or anything)
    - Don't memorize things that you can look up on the Internet.
    - Focus on stories, insights, reasons, motivations.
    - Empathize with the subjects.
      Why do they go to war?
  - Learning languages, both human languages and programming languages
    - One learns a language by example sentences.
      One learns a programming language by example programs/snippets.
      - One does not learn a language by memorizing the syntax.
      - One does not learn a language by memorizing the language reference document.
** Brain? Biology?
- Does everyone have a fusiform gyrus? A prefrontal cortex?
- [[https://www.youtube.com/watch?v=lyu7v7nWzfo][TED: Your brain hallucinates your conscious reality | Anil Seth]]
- [[https://www.youtube.com/watch?v=SgOTaXhbqPQ][TED: What hallucination reveals about our minds | Oliver Sacks]]
- same video, different narrator
  - [[https://www.youtube.com/watch?v=X_tYrnv_o6A][Veritasium: Your Amazing Molecular Machines]]
  - [[https://www.youtube.com/watch?v=WFCvkkDSfIU][Drew Berry: Animations of unseeable biology]]
** TED?
- [[https://www.youtube.com/watch?v=fxbCHn6gE3U][The surprising habits of original thinkers | Adam Grant]]
- [[https://www.youtube.com/watch?v=YM-uykVfq_E][TED-Ed: What is entropy? - Jeff Phillips]]
- [[https://www.youtube.com/watch?v=PRYmx7Lk9F0][This Quantum 'Sixth Sense' Could Allow Birds to Navigate Earth's Magnetic Field]]
- [[https://www.youtube.com/watch?v=YnY0J_Z1TF4][The Earth Is Running Out of Sand and It Could Cause a Global Crisis]]
** Utilitarianism is questionable.
   :PROPERTIES:
   :CUSTOM_ID: utilitarianism-is-questionable.
   :END:

- https://rationaloptimist.wordpress.com/2014/05/24/utilitarianism-is-killing-one-to-save-five-moral/
- http://blog.practicalethics.ox.ac.uk/2014/11/why-i-am-not-a-utilitarian/

** psychology? goals? systems?

- [[https://jamesclear.com/goals-systems][Forget About Setting Goals. Focus on This Instead.]]: focus on systems/processes instead of goals.

** How to get research grants?
- What are the laws and rules?
- Who makes the decisions?
- How do you improve your chances?
* TODO <2018-09-15> Fix possible programming error in ~/work/web in Iterables.filter
* TODO <2018-09-15> Modernize operating system
Back up data.
Should not take more than a day.
** TODO <2018-09-15> Install +Ubuntu 18.04 after its point release+ Debian
Ubuntu 14.04 EOL is April 2019.

<2018-10-26> I'm using Ubuntu 14.04.

When Ubuntu 14.04 reaches its end of life, I'll move to Debian.
I won't upgrade to Ubuntu 18.04.
- https://micahflee.com/2013/01/why-im-leaving-ubuntu-for-debian/
- https://www.datamation.com/open-source/ubuntu-18.04-review-tough-love.html
* TODO Ask others
** Who should we ask?
- Haskell Cafe mailing list
- #haskell on freenode IRC
- Haskell reddit
- Abdullah
** TODO <2018-09-17> Is there anything like Pandoc but for programming languages instead of markup languages?
Does anyone know of anything like Pandoc but for programming languages?

For example, it would translate Haskell to Java by translating Haskell into an internal representation and then translating that internal representation to Java.

Possible related things:
- LLVM IR
- GHC Core
* <2018-09-22> Derita naik Gojek/Gocar
Saya sempat coba Grab dan Gojek.
Saya tidak pakai Grab karena saya benci kode promo.
Akhirnya berlabuh di Gojek.

- Gojek
  - Kadang pengemudi tidak bisa membaca.
    Tiap minggu ada saja pengemudi yang tidak baca catatan, lalu nyasar.
    Sangat buang waktu.
  - Kadang dapat motor Yamaha Aerox.
    - Motor ini tidak aman; pusat massa tinggi, mengurangi kestabilan.
    - Motor ini tidak nyaman; joknya keras, suspensinya keras, menyiksa pantat.
    - Contoh motor yang enak: Honda Scoopy.
      Tampilannya emang culun, tapi jok lebar dan empuk, dan suspensi juga lembut.
      Enak buat pantat.
    - (Saya tidak punya motor.
      Saya bukan fans Yamaha ataupun Honda.
      Saya cuma benci sakit pantat.)
  - Kadang ban kempes.
  - Pernah, jam 17:00, 30 menit gak ada yang ambil.
- Gocar
  - Kadang pengemudi mengantuk, merem melek.
    Mobil ngegas ngerem.
  - Posisi suka ngaco.
    Minta jemput di S Parman, supir di Mal Pondok Indah lah (12 km), di Pejompongan lah (6 km), di Tomang lah (4 km), di sisi jalan yang salah lah (4 km).
  - Kadang di-cancel 5 kali baru dapat.
  - Kadang mobil bau rokok.
- Grabcar
  - <2018-10-25> Saya ditinggal kabur supir grabcar, padahal saya tinggal 5 langkah dari mobil, dan dia belum ada 5 menit menunggu.
- Aplikasi Gojek vs Grab:
  - Grab lebih reliable.
  - Gojek lebih hemat baterai.
- Perasaan saya.
  - Teknologi keduanya shitty, tapi teknologi Grab less shitty daripada teknologi Gojek;
    Grabcar lebih bisa mencari supir yang dekat (500 m, 1 km); Gocar seringkali dapat supir (2 km, bahkan pernah 6 km).
  - Supir Gocar memperlakukan penumpang lebih baik daripada supir Grabcar memperlakukan penumpang.
    Mungkin karena Gojek lebih kejam ke supir.
* Government/state
** Deregulation of USA

- [[https://www.youtube.com/watch?v=TuAg-RaZ4Is][Trump Is 'Destroying' Regulations - YouTube]]

Trump needs a cooperative Congress in order for him to be able to repeal more laws.

** Antonin Scalia: The key to American freedom is the separation of power, not the Bill of Rights.

https://www.youtube.com/watch?v=Ggz_gd--UO0

The USSR Constitution guarantees more freedom than the USA Constitution, but the USSR failed to prevent the centralization of power.

Every dictatorship has bill of rights.

North Korea has elections.

** Evolution justifies governments

Evolution suggests that cooperation improves survival (in the long run, of the species, not of an individual).

Evolution suggests that morality improves survival.

Evolution suggests that government improves survival.

What is the state for?
Why do we need government?
To promote the survival of the governed species.

*** Government is not to merely maintain public order.

Public order can be undesirable:

- We don't want a government that oppresses people in order to maintain public order.
- The overthrowing of a tyrant may be a desirable public disorder.

To promote survival of the people? As in evolution?

To better the people?
To impose the morality of the people?
A government reflects the morality of its people.

We must impose our morality on others.
The law imposes the lawmakers' morality on everyone.
It is practically impossible to live without imposing your morality on others.
There is a minimum decency that we expect when we interact with others.

The enforcement of law is an imposition of the morality of the lawmakers (and therefore of the people who elected the lawmakers).

https://www.quora.com/Should-the-law-impose-morality

*** Social apoptosis? Programmed human death?

Some cells must die to better the organism.
Some people should die to better the society?
Programmed cell death ~ programmed human death?

A malfunctioning cell kills itself.
It would be nice if a malfunctioning human could kill himself?

A cell infected by a virus kills itself.
It would be nice if a human infected by ideological virus (mind virus) could kill himself?

How do we know we're infected?

*** Why should our survival be desirable at all?

*** Human rights are legal fiction.

What is real is tolerance.
People let other people live.
If I am still alive, it's because others let me live,
because others tolerate me,
not because I have any rights.

*** Justifying freedom
   :PROPERTIES:
   :CUSTOM_ID: justifying-freedom
   :END:

- Hypotheses:

  - People do/produce best (the highest quantity for the lowest price) when they pursue what they want to do/produce.
  - People approach their strengths and leave their weaknesses.
  - Different people have different goals.
  - Higher intrinsic motivation increases willingness to accept lower pay.

** It is insane that every country makes their own laws.
   :PROPERTIES:
   :CUSTOM_ID: it-is-insane-that-every-country-makes-their-own-laws.
   :END:

Software engineers share as much as possible to avoid repeating work.
They use operating systems, libraries.

Legislators could share more work.

Most software engineers use the same operating system.
Every country has its own constitution.
This is an insane amount of duplication.

There should be a "software library" for laws.
Laws should be reusable.
It should be able to legislate
"law X of country Y also holds in country Z, provided that every occurrence of X is replaced by Z".

- [[https://en.wikipedia.org/wiki/Don%27t_repeat_yourself][WP:Don't repeat yourself]]
- [[https://en.wikipedia.org/wiki/World_government][WP:World government]]
- [[https://www.quora.com/There-is-only-one-country-in-the-world-and-there-are-no-borders-no-need-for-passports-People-can-travel-freely-and-there-is-a-similar-legal-and-economic-system-for-everyone-in-the-world-What-do-you-think-of-this-idea][Quora question about world government]]

* Game-changers?
** DoNotPay: automate lawyers

https://www.youtube.com/watch?v=xbXM-aNRNlY

https://www.donotpay.com/

* Pragmatic ontology: how pragmatism can help us answer what something is

(Is this really what others mean by "pragmatic ontology"?)

To the pragmatic ontologist, "exist" means "practically exist".

Someone who subscribes to egocentric pragmatic ontology would take the question "What is X?" to mean "What can I use X for? / How can I use X?"

- I can use it, therefore it exists. (Compare: Descartes's "I think, therefore I exist.")
- It affects me, therefore it exists.

* <2018-09-25> Software is broken and bloated

- [[http://tonsky.me/blog/disenchantment/][Software disenchantment @ tonsky.me]]
- [[https://www.hanselman.com/blog/EverythingsBrokenAndNobodysUpset.aspx][Scott Hanselman: "Software doesn't work. I'm shocked at how often we put up with it."]]

* Automatic differentiation?

Justin Le, [[https://blog.jle.im/entry/purely-functional-typed-models-1.html][A Purely Functional Typed Approach to Trainable Models]]

* About defining consciousness

2009, "How to define consciousness—and how not to define consciousness", [[http://cogprints.org/6453/1/How_to_define_consciousness.pdf][pdf]]

* What is the difference between the $10,000 Indonesian-citizen programmer and the $100,000 American-citizen programmer?

Is it location?
Will a $10,000 Indonesian-citizen programmer suddenly become a $100,000 Indonesian-citizen programmer just by moving to America?
Are American companies simply able/willing to pay more?

Is it skill/ability?
Is the $100,000 American-citizen programmer more capable than the $10,000 Indonesian-citizen programmer?

Inconclusive discussion https://marginalrevolution.com/marginalrevolution/2012/01/why-are-some-programmers-paid-more-than-others.html

* <2018-09-28> Book: "interpretable machine learning"

https://christophm.github.io/interpretable-ml-book/

* The dualistic nature of machines; the machine-program dualism; the hardware-software dualism

The hardware is the body.
The software is the mind.

Are bits software /itself/, or are bits a /representation/ (embodiment) of software?

A running machine embodies the software it is running?

* Machine-learning database indexing; an index is a model of the data

http://deliprao.com/archives/262

https://arxiv.org/abs/1712.01208
* Approximation theory and machine learning
Conference: "Approximation Theory and Machine Learning", at Purdue University, September 29 - 30, 2018
- http://www.math.purdue.edu/calendar/conferences/machinelearning/
- http://www.math.purdue.edu/calendar/conferences/machinelearning/abstracts.php
* Making a programming language
https://www.reddit.com/r/ProgrammingLanguages/comments/9ky7o6/writing_my_own_programming_language/e72qjll/
banzr: 'Racket is taught in universities to be used to write languages. Use "match" and "cases" to build the parser and interpreter. Good luck!'
* Defining investing, trading, gambling, betting, wagering, insurance
** Defining gambling
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/
** How do we know something is not gambling?
*** If it's possible to be skillful, then it's not gambling.
** What
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?" https://www.bbc.com/news/business-38905963
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
* Ramblings, speculations, fantasies, imaginations, and trivias
** Acting
- I rarely watch movies.
- I'm sure there are other good actors, actresses, and movies.
- But I'm not watching all the movies in this world.
- Examples of good acting
  - Adewale Akinnuoye-Agbaje in "Faster"
  - Christoph Waltz as Hans Landa in "Inglourious Bastards"
  - Heath Ledger as Joker in which Batman movie?
- Examples of good movies
  - films directed by Christopher Nolan
    - "Interstellar"
    - "Inception"
** Lyrebird can mimic sounds uncannily.
laser guns, drills, hammers, camera shutters.
** Quantum inertia? Rocket propulsion? What?
- https://www.reddit.com/r/compsci/comments/9kxiiu/what_new_thing_are_you_currently_learning_in_your/
** latency, throughput, and port usage information for instructions on recent intel microarchitectures
http://uops.info/
** Some journalist brutal murder cases
Journalists have been brutally murdered in these areas:
- Malta: Daphne Caruana Galizia was car-bombed in 2017. https://en.wikipedia.org/wiki/Daphne_Caruana_Galizia
- Bulgaria: Viktoria Marinova was raped and murdered in 2018.
** Witness testimony shouldn't count as evidence; there has to be independent corroboration
- How reliable is your memory? | Elizabeth Loftus https://www.youtube.com/watch?v=PB2OegI6wvI
- Steve Titus: victim of false memory https://en.wikipedia.org/wiki/Wrongful_conviction_of_Steve_Titus
** Curing cancer?
*** Trading cancer with autoimmune disease?
Trading something bad with something hopefully less bad?
https://arstechnica.com/science/2018/10/treatments-that-cause-the-immune-system-to-attack-cancer-earn-a-nobel/
** What does an assistant professor do?
According to https://recruit.ucsc.edu/apply/JPF00651:
- develop a research program
- advise graduate students in their research area
- obtain external funding
- develop and teach courses within the undergraduate and graduate curriculum
- perform university, public, and professional service

That's a lot for one person to do.
** <2018-10-03> Brain-to-brain interface
https://www.sciencealert.com/brain-to-brain-mind-connection-lets-three-people-share-thoughts
** <2018-10-02> Twitter is surprisingly good for academic research
Example:
- https://twitter.com/search?q=programming%20language%20research&src=typd
** Where ethics and design meet
  - [[http://mrmrs.cc/writing/2016/03/23/the-veil-of-ignorance/][Applying John Rawls's "veil of ignorance" argument to web design]]
** My tech observations and complaints

*** smartphone politics

- Xiaomi limits hardware profit to 5%? What?
  - [[https://www.reddit.com/r/Android/comments/8k43qo/why_does_xiaomi_limit_its_profits_to_5_youtube/][Why does Xiaomi limit its profits to 5%? - YouTube TechAltar : Android]]
    - Because Xiaomi is a software company, not a hardware company.
- [[https://www.youtube.com/watch?v=OA_g2bQgOXY][How KaiOS Is Becoming the 3rd Major Mobile OS - YouTube]]
  - Much money can be made from selling to poor people (hopefully while also helping them).
    - [[https://hbr.org/2012/06/the-smart-way-to-make-profits][The Smart Way to Make Profits While Serving the Poor]]

*** GIF is video, not image.

- GIF videos must have controls.
- Google should penalize (push down) Pinterest from image search.
  It's littering.

*** Using chat such as IRC/Slack
  - I find that most channels are idle.
  - There are two kinds of channels: temporary and permanent.
    - Temporary channel is functional. It gathers people for a task/project.
    - Permanent channel is structural. It gathers people in the same tribe/department/structure.
** <2018-09-19> Web development woes: lack of a set of font families with same x-height

I need a serif font family, sans-serif font family, a monospaced font family, and a math font family.
I want all of them to have the same x-height.

*** <2018-09-19> Recruiting networks are double-edged swords for employers

Example tools: Linkedin, SmartRecruiters.

You can use it to find new employees.
But your employees can also use it to find new employers.

But the overall economy stands to gain if we can fix the information asymmetry in job market.

*** <2018-09-19> Sturgeon's law, originally for science fiction, also applies to job applicants

"Ninety percent of everything is crap."

Ninety percent of your applicants is crap.

Indeed it applies to /everything/.
Ninety percent of /everything/ is crap.
Software.
Companies.
Goods.

Ninety percent of /everything/ is crap: people, countries, etc.;
and we may be in that 90%.

*** <2018-09-19> GitHub is trying machine learning

- I think GitHub should be like StackOverflow but for open-source codes/libraries/programs instead of questions.
  Prevent people from reinventing the wheel.
  Help people find things that already exist.
  - <2018-09-19>
    Google is doing a better job at what GitHub should be doing:
    finding existing open-source software, that does something we want, that we can reuse.
    It's a hard problem.
- [[https://githubengineering.com/towards-natural-language-semantic-code-search/][Towards Natural Language Semantic Code Search | GitHub Engineering]]
- I think StackOverflow can use machine learning to comprehend user query and recommend related questions/answers/information.
** What is TurnKey GNU/Linux?
[[https://www.turnkeylinux.org/][
TurnKey GNU/Linux: 100+ free ready-to-use system images for virtual machines, the cloud, and bare metal.]]
** Why is Xi Jinping becoming so powerful?

Some answers/opinions on Reddit:
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvmnlo
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvf76g
** Anti-vaxxers are letting babies die

Antivaccinism kills babies.

Antivaccinism should be illegal.
It's parental negligence.

http://www.thejakartapost.com/news/2018/09/05/rubella-kills-baby-in-jambi-as-vaccination-campaign-meets-resistance.html

What is the difference between killing and letting die?
What is the difference between deliberately killing and deliberately letting die?
** (Why the hell did I bother to find out about these things?)
*** Physics textbook

- [[http://www.lightandmatter.com/area1sn.html][Simple Nature, an online physics textbook]]: for beginner, too wordy for me.

*** Browser plugins (I don't necessarily use)

- Vimium: vim-like shortcuts for navigating the chromium browser
  - [[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en][Install from Chrome Web Store]]
  - [[https://github.com/philc/vimium][Source code on GitHub]]
- Perhaps I should make a browser plugin that copies a link of the page to the clipboard in Markdown format?
  No. A bookmarklet suffices.
  - Which browser has easiest plugin development?
    - The result might be suspicious because I used Google to look for the answer.
    - 2016: Chrome ([[https://www.quora.com/Is-it-easier-to-write-a-plug-in-extension-for-Chrome-or-Firefox][source]])
    - 2011: Chrome ([[https://stackoverflow.com/questions/6438329/which-browser-is-easier-to-develop-plug-ins-for-chrome-or-firefox][source]])

*** Judaism, kareth, gays, and lesbians
   :PROPERTIES:
   :CUSTOM_ID: judaism-kareth-gays-and-lesbians
   :END:

- [[https://en.wikipedia.org/wiki/Kareth][WP:Kareth]]

  - It is interesting that a gay is punishable by kareth, but a lesbian is not punishable by kareth.

    - See item no. 4: "A male having sexual intercourse with another male".
      It doesn't say anything about "a female having sexual intercourse with another female".

  - It doesn't mean that Judaism allows lesbianism.
    There may be other rules somewhere else.
  - [[https://en.wikipedia.org/wiki/Homosexuality_and_Judaism][WP:Homosexuality and Judaism]]
*** skin color chart

- https://en.wikipedia.org/wiki/Von_Luschan%27s_chromatic_scale
- https://en.wikipedia.org/wiki/Fitzpatrick_scale
*** Quartz scheduler performance
  - http://airboxlab.github.io/performance/scalability/scheduler/quartz/2017/06/20/perf_tuning_quartz.html
  - https://www.ebayinc.com/stories/blogs/tech/performance-tuning-on-quartz-scheduler/
  - https://stackoverflow.com/questions/11565993/quartz-performance
*** Picking colors
  - theories and principles
    - [[https://usabilla.com/blog/how-to-design-for-color-blindness/][How to Design for Color Blindness]]
    - [[http://www.tigercolor.com/color-lab/color-theory/color-harmonies.htm][Color Harmonies: complementary, analogous, triadic color schemes]]
  - tools
    - [[http://www.hsluv.org/][HSLUV: human-friendly /perceptually uniform/ color picker]]
      - [[https://en.wikipedia.org/wiki/CIELUV][Wikipedia: CIELUV color space]]
      - [[https://arxiv.org/abs/1509.03700][Good colour maps: how to design them]], 2015, Peter Kovesi
    - [[https://leaverou.github.io/contrast-ratio/][Lea Verou's contrast ratio checker tool]]
*** Peterson v Newman on Channel 4 is not journalism

[[https://www.youtube.com/watch?v=aMcjxSThD54][video]]

Newman is putting her words on Peterson's mouth.

Peterson has the patience of a saint.

It is not journalism.
It is a mere entertainment.
Verbal boxing.
Spectacle.
*** Accommodation Ontology Language Reference?
- http://ontologies.sti-innsbruck.at/acco/ns.html
** Re-identification: Pieces of anonymized information about a subject can be combined to identify the subject.

[[https://arstechnica.com/tech-policy/2009/09/your-secrets-live-online-in-databases-of-ruin/][“Anonymized” data really isn’t—and here’s why not | Ars Technica]]

- Massachusetts Group Insurance Commission
- AOL
- Netflix
- etc.

Browser fingerprinting
** <2018-09-28> "Class Struggle" board game

- [[http://www.nyu.edu/projects/ollman/game.php][what it looks like]]
- [[http://www.nyu.edu/projects/ollman/game_rules.php][the rules]]
** Accounting
- I use GnuCash for my personal accounting.
- Accounting terms
  - What is an account?
    - If you deposit money in banks, then you have an account for every bank account you have.
    - If you lend money to people, then you have an account for every people.
  - What is a journal?
    - A journal is optimized for entering transactions by date.
    - What is a transaction?
      - A transaction involves two or more accounts.
        - The sum of all account changes in a transaction is zero.
  - What is a subledger (subsidiary ledger)?
    - A subledger of account C is obtained by selecting only the journal entries that affect the account C.
  - What is a general ledger?
    - A general ledger is the concatenation/combination/summation of several subledgers.
- Are there open source enterprise accounting systems?
** Is advertising ethical?
- Happiness = Expectation - Reality.
- Advertising increases expectation.
- Therefore advertising reduces happiness.
- But without advertising, how will people know that you even exist?
  How are you going to have customers at all?
- Advertising should be replaced with information.
- https://twitter.com/oxcsh/status/1055953330328010753
** <2018-10-28> Systemd programmers are not competent enough for what they are doing.
- https://blog.erratasec.com/2018/10/systemd-is-bad-parsing-and-should-feel.html
  - https://www.reddit.com/r/programming/comments/9rtm1f/systemd_is_bad_parsing_and_should_feel_bad/
** Don't just collect links. Comment them. Opine. Think.
** Analogy: Marx were a doctor, capitalism were the disease, Marxism was the cure that was worse than the disease.
- Jordan Peterson Vs Marxist Professor Richard Wolff https://www.youtube.com/watch?v=HTj17c4N9vI
  - Marx predicted some bad consequences of capitalism, but the cure he proposed was worse than the disease.
  - However, Jordan Peterson says that inequality is not due to capitalism, but because small successes breeds even bigger successes.
    - When something good happens to you, it increases the probability that something else good also happens to you.
      - That (string of luck) spirals out of control, and we don't know what to do about it.
        - Luck begets more luck.
          Success begets more success.
          Money begets more money.
          (If you know what you're doing.)
** Does Wikileaks matter? Who is going to scour all that text for interesting stuffs / incriminating evidence? Most people don't have time to read that.
** You MUST have at least one camera in your car streaming the data to a remote safe location. Cops will trap you.
- https://www.youtube.com/watch?v=UpT-SAunuLk
- Busted! How to Handle the Police Until You Get a Lawyer - by Mary Griego https://www.youtube.com/watch?v=bmtIizXdh88
  - Ordering vs asking.
- We need to make sure that misbehaving cops are punished.
- 5 Rules for Recording Police: Steve Silverman of FlexYourRights.org https://www.youtube.com/watch?v=BHpQtvIxBJ4
** Negara tidak perlu mengatur agama.
- https://www.reddit.com/r/indonesia/comments/9r72uj/pgi_keberatan_atas_2_pasal_di_ruu_pesantren_dan/
** Laporan penggunaan pajak oleh negara
- https://www.kemenkeu.go.id/alokasipajakmu
  - https://www.reddit.com/r/indonesia/comments/9qkd3m/as_an_early_adult_who_recently_graduated_from/
** What is fairness?
- Suppose that we have a running contest, and you beat me.
  How do I know that you beat me /fairly/?
  - Good genetics is an advantage, but is it a fair advantage?
  - If we can't control it, can it be unfair?
  - Is it fair for children to be born in families with different socioeconomic status?
  - If equality of outcome is absurd, then what is fairness?
  - Is equality of opportunity fair?
    - Opportunity to do what?
      Opportunity to become what?
    - Equality of /all/ opportunity?
      - Opportunity to be boss/capitalist/rich?
** Why are we so angry?
- https://www.nhs.uk/conditions/stress-anxiety-depression/about-anger/
  - "being treated unfairly and feeling powerless to do anything about it"
    - Is it really unfairness that bothers me, or do I have the wrong sense of fairness?
      Does fairness even exist?
- https://psychcentral.com/blog/angry-all-the-time-for-no-reason-this-might-be-why/
  - 'Anger also “stems from wanting to control what is outside of us,” said Michelle Farris, LMFT, a psychotherapist in San Jose, Calif.'
** Genetics is the biggest factor in how far we can build our body
- https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting
** Measuring things to find bottlenecks (Linux, TCP, HTTP, network, CPU, disk, etc.)
- How many empty TCP connections per second can a TCP endpoint accept?
  We don't want to measure transfer rate.
  We want to measure kernel bookkeeping overhead.
  - These can't do that:
    - iperf
  - Can these do that?
    - https://txlab.wordpress.com/2016/05/05/tcpkali-tcp-load-generator/
    - http://uperf.org/
    - qperf (ubuntu?)
      - https://www.opsdash.com/blog/network-performance-linux.html
      - https://access.redhat.com/solutions/2122681
- How many HTTP requests can it handle? Use ApacheBench. =sudo apt-get install apache2-utils=.
- How do we reduce the worst-case response time under high load?
- Is the Linux process scheduler fair?
- Is the Linux process scheduler time complexity O(1)?
- https://medium.com/@oscar.eriks/case-study-network-bottlenecks-on-a-linux-server-part-2-the-kernel-88cf614aae70
- Which is better, select or epoll?
*** Linux TCP TIME_WAIT exhaustion on busy server
- What are my options?
  - Assign more IP addresses.
  - Geographically distribute the application.
    Procure edge servers closer to the clients.
    But you can't do this if you are not a CDN or ISP.
  - Reduce the TIME_WAIT MSL (maximum segment lifetime)
    - http://www.lognormal.com/blog/2012/09/27/linux-tcpip-tuning/
    - This makes TCP incorrect, but in the case of a load balancer, the probability of the incorrectness is negligible (unless it's an attack, or it's behind a NAT).
    - =net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait = 1=
  - Non-options
    - =net.ipv4.tcp_tw_recycle= has been removed.
    - =net.ipv4.tcp_tw_reuse= doesn't work.
  - https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux
    - https://news.ycombinator.com/item?id=7684015
    - "The universal solution is to /increase the number of possible quadruplets/ by using, for example, more server ports."
    - "Moreover, when designing protocols, /don’t let clients close first/."
- See the TCP protocol documentation.
  Where are the wait states?
  Who hold the wait states?
  The client?
  The server?
  The one who calls the =close= system call?
** All fierce debates are language problems
Communication consists of input, processing, and output.

In a fierce debate, there is no input; there is only output, and the participants don't even agree about the definitions.
They don't know what they are talking about.
** Why the non-oppressed Chinese must help the oppressed Chinese

Because when the oppressed people revolt, the non-oppressed people will be among the victims.

*** Speculations

These are the possible scenarios:
- The oppressed thinks that they are already dead (their lives are worse than death) anyway,
  musters enough strength, revolts, and overthrows the government.
  The non-oppressed (the middle-class) takes collateral damage.
- The government kills off all oppressed people.
  The non-oppressed people lives in their bubble happily ever after.
- The government slowly releases control while trying to save face.

Xi Jinping cannot release control in 2018, because if he releases control, his opponents will pounce on him, reveal all his crimes, and tarnish his name.
Xi Jinping wants to die in good standing, with good reputation; he wants to be remembered as a good person.

I hope that the next bloodshed gives the Chinese people enough reason to limit government power.

You can live a good comfortable life in China as long as you blind yourself from the truth.

- <2018-09-26> [[https://www.youtube.com/watch?v=eViswN602_k][Exposing China's Digital Dystopian Dictatorship | Foreign Correspondent]]
  - China's Big Brother system favors obedient middle-class people, and limits journalists, minorities, and dissenters.
  - Alibaba helps oppression.
    Alibaba is making AI to help the Chinese government oppress people more efficiently.
    Do they profit from oppression?

Stalin's inner circle was too afraid to tell him the truth.
Nobody dared to challenge Stalin.
Stalin's inner circle told him what he wanted to hear.

https://www.quora.com/Is-is-true-that-top-Soviet-officials-lived-in-constant-fear-under-Stalin-Or-is-that-an-exaggeration

After Stalin died, there was a great purge.

You know your country is led by an authoritarian if:
- You can't say the truth there.
- There is someone whom people are too afraid to disagree with, even politely.

We must respect the truth.
The truth doesn't care about us.
People who ignore the truth do so at their own peril.
Ignoring the truth means ignoring some danger;
such ignorance reduces the chance of survival.

*** Hopeful

[[https://www.youtube.com/watch?v=8XQ1onjXJK0][Are China and the US doomed to conflict? | Kevin Rudd - YouTube]]
** FOSS alternative to SmartRecruiters?

https://blog.capterra.com/top-8-freeopen-source-applicant-tracking-software-solutions/
** Is the world better without private ownership?

Nobody needs to be rich.
What we really seek is satisfaction.
We should be happy if others find us useful, if others want us to stay, if others want us to exist.

If people's basic needs are met, they will still work, but they will only do what they really want to do.

Personal property is OK.
Is private non-moving property OK?

https://kk.org/thetechnium/better-than-own/

https://www.quora.com/How-would-a-world-without-money-ownership-and-monetary-value-operate

** <2018-09-24> Competition is wasteful

Suppose that Company A and Company B both make System S.
They duplicate each other's efforts.
Then Company B loses.
Thus everything B (and all other losers) did is /wasted/.

- If a company doesn't have any competitors, it has little incentive to improve.
  (We assume that companies only improve when they are existentially threatened.)
- How do we make sure that something improves even without competition?
  /Guilds/.
  An organization that /intrinsically/ wants to improve (while still profiting),
  not an organization that intrinsically wants to maximize profit at all costs.

[[https://academic.oup.com/antitrust/article/1/1/162/274807][Is competition always good? | Journal of Antitrust Enforcement | Oxford Academic]]

Duplicated Effort vs. Partnership from Christianity perspective
http://www.lausanneworldpulse.com/perspectives-php/1234/01-2010
** <2018-09-24> Willy & Nigel: Bisnis apa yang modal rendah, tidak perlu hire orang pintar, dan tinggal duduk-duduk aja dapat duit

Semua kelihatan mudah sampai dicoba.

Yang legal (apa benar mudah?):
- rumah duka
- dropshipping

Yang ilegal:
- bos preman
- rumah bordil
** Brain study, psychedelics, and anesthetics

We still don't know how psychedelics and anesthetics work.

** Class treason? Class traitors?
- https://en.wikipedia.org/wiki/Class_traitor
- police?
- human resources?

** Living in a republic
*** If you don't vote, you let the worst guy win.

Your vote prevents greater harm.

*** If you don't speak, you let the worst guy do anything he wants.

You must state your disagreement.
** Distributed systems

*** Why users don't use distributed systems

- [[http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html][highscalability.com: What do you believe now that you didn't five years ago?]]
  - "Decentralized systems will continue to lose to centralized systems until there's a driver requiring decentralization to deliver a clearly superior consumer experience."
    - Users don't care.
      They want software to just work.

*** YaCy-related

- [[https://loklak.org/][Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]]
- [[https://chat.susi.ai/][SUSI.AI Chat - Open Source Artificial Intelligence]]
- https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html

*** Freedom pack?

- We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
  The pack might contain things like yacy.net, matrix.org, riot.im.
  - Why stop there? Why not make free/libre distributed operating system with all those goodies preinstalled?
    - https://en.wikipedia.org/wiki/Distributed_operating_system
** Java

- http://tech.jonathangardner.net/wiki/Why_Java_Sucks#Speaking_of_the_JVM...
- [[http://www.jsweet.org/][JSweet: a transpiler to write JavaScript programs in Java]]
- [[http://sparkjava.com/documentation.html][Spark Framework: An expressive web framework for Kotlin and Java - Documentation]]
- [[https://github.com/webfolderio/ui4j][webfolderio/ui4j: Web Automation for Java]]

*** Compile a Java class to an ELF native binary?

Use DWARF to help reconstruct stack trace.

** CSS
- CSS programming
  - https://css-tricks.com/autoprefixer/
  - [[https://css-tricks.com/snippets/css/a-guide-to-flexbox/][CSS flexbox cheat sheet]]
** Economics
*** Cooperatives?
   :PROPERTIES:
   :CUSTOM_ID: cooperatives
   :END:

What is the difference between cooperative and nonprofit?

Do cooperatives have limited liabilities like limited liability companies?

Cooperative is not a legal form?

How to measure member contribution?
This is hard, if even possible at all.
Thus it's a bad idea to distribute profit according to member contribution.
An alternative way to distribute is
[[https://en.wikipedia.org/wiki/From_each_according_to_his_ability,_to_each_according_to_his_needs][WP:From each according to his ability, to each according to his needs]],
but it only works if there is abundance.

*** Should we assume scarcity or abundance?

- Which assumption is better?
  - Assumption of scarcity: Human always wants more than what exists. There is never enough resources for everybody.
  - Assumption of abundance: There is a point where humans are satisfied. There are enough resources for everybody.

I think the assumption of abundance is saner.
But unfortunately it seems to lead to communism.

*** Converting between goods and services
   :PROPERTIES:
   :CUSTOM_ID: converting-between-goods-and-services
   :END:

SaaS converts goods (software) into services.
If you have goods, and you want to make it a service, then you host a software that controls access to that goods.

Robot converts services into goods.
If you have a service, and you want to make it a goods, then you make a robot that does that service.

*** The law of demand and supply only happens with order-book-like markets?

*** <2018-09-11> Microeconomics
An economy consists of actors.

- No economic actor has complete view of the economy.
  Every actor can only see his suppliers and consumers.
- Every actor responds only to what immediately affects it: its direct suppliers and consumers.
- Actors need time to respond to change in demand/supply.
- Some actors maintain buffers/inventories.
- Some actors get involved in futures.

Hypotheses:

- Shocks ripple through actors.
- Demand collapse may waste inventory.

Statistics can give us an accurate picture of the economy.
Random sampling of actors.
** OS magics

*** Can we make memory a compressible resource?

*** android termux: can have bash, ssh, git, vim, emacs, and more on android

  - 2018-09-08: Too bad there is no clear way for android to charge while OTG (hosting) USB.
    Otherwise phones could kill netbooks.
  - 2018-09-08: a problem: can't close session with android keyboard (requires a physical keyboard plugged in via OTG USB)
** Living in the 21th century? Rejecting reality?
   :PROPERTIES:
   :CUSTOM_ID: rejecting-reality
   :END:

In year 1000 AD who would have thought that 1000 years later we would have AI deepfakes,
human sex change (sex reassignment surgery, hormone therapy),
and what else reality-bending technologies we have.

In 2018 those technologies aren't perfect.
We can see deepfake artifacts.
We can tell apart transsexuals from their hips.
Maybe in the future those technologies will be perfected.
Maybe in the future people can be whoever they want to be.
"You are who you want to be" is getting more literal.

When that time comes, we will have more respect for philosophers.
If everything is easy to fake, then what is real, and how do we know it's real?
If everything is easy to fake, then what can be taken as proof in court?
What really exists?
If a man can easily become a woman, and a woman can easily become a man, then what does it mean to be a man/woman?
Do ID cards still make sense if you are immortal and you change your identity every 6 months?
Technology will force us to deal with ontology and epistemology.

Reality discontents humans.
We work hard to deceive our senses so that we can escape reality.
We try to make imagination real, and make reality irrelevant.
The Matrix is getting real.

*** Data, customers, and reality
- https://www.inc.com/business-insider/amazon-founder-ceo-jeff-bezos-customer-emails-forward-managers-fix-issues.html
  - "If all his [Bezos's] data says one thing and a few customers say something else, he believes the customers."
** Ethics and the workforce

  - [[https://hackernoon.com/where-are-the-programmers-who-give-a-shit-87f859f13f75][Where are the programmers who give a shit? -- Hacker Noon]]

    - [[https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/][What are the 10 most harmful jobs? - 80,000 Hours]]

      - Not everyone agrees. See the comment section.

- [[https://www.econlib.org/library/Enc/MarketforCorporateControl.html][Market for Corporate Control -- Econlib]]

  - "Markets discipline producers by rewarding them with profits when they create value for consumers and punishing them with losses when they fail to create enough value for consumers."

- Find a high-social-impact job suitable for you: [[https://80000hours.org/career-quiz/#/][Get social impact career ideas - 80,000 Hours]]

  - I don't understand the recommendations.

- [[https://80000hours.org/career-guide/most-pressing-problems/][How to find the world's most pressing problems]]
- [[https://80000hours.org/career-guide/personal-fit/][The evidence on how to find the right career for you - 80,000 Hours]]
- [[https://80000hours.org/career-guide/how-to-be-successful/][Evidence-based advice on how to be successful in any job - 80,000 Hours]]

Example of federated/decentralized social networks:

- [[https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc][Kari Nordmann's comment]]:
  "Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo) "
*** Tech giant ethical issues

- Bezos Amazon worker condition?
- Google Dragonfly supports Chinese authoritarianism?

**** Don't buy from Oracle.

- [[https://www.reddit.com/r/programming/comments/5iogug/oracle_finally_targets_java_nonpayers_six_years/][Oracle finally targets Java non-payers -- six years after plucking Sun : programming]]
- [[https://developers.slashdot.org/story/16/12/18/0147216/oracle-begins-aggressively-pursuing-java-licensing-fees][Oracle Begins Aggressively Pursuing Java Licensing Fees - Slashdot]]

*** <2018-08-29> IQ and jobs
  Although I'm happy to be proven wrong,
  I believe that a minimum IQ of 120 is necessary but not sufficient for software engineering (cooperativeness is also required).
  It seems IQ tests are inaccurate for high IQs above 130.
  - [[https://www.reddit.com/r/learnprogramming/comments/2ue71p/what_iq_do_you_need_in_order_to_be_a_programmer/][What IQ do you need in order to be a programmer? : learnprogramming]]
    - The OP doesn't sound like his IQ is 89.
  - Higher IQ means faster learning, and that's all.
  - To each according to their ability.
    Society needs low IQ people.
    Some jobs fit low IQ people.
    These jobs are equally honorable as high IQ jobs are.
    Low IQ isn't an insult.
    Everyone is different.
** <2018-09-17> Open source Heroku/PaaS/dashboard alternative?
We don't even know what such things are called.

Google search "open source heroku clone".

As usual, there are too many open source options.

- From [[https://www.quora.com/What-are-some-open-source-Heroku-alternatives][What are some open source Heroku alternatives? - Quora]]:
  Dokku, Flynn, Convox?, Globo.com Tsuru, Apache Stratos, cloudify-cosmo, lastbackend, CaptainDuckDuck.
** Setting up and running a X.509 certificate authority (for TLS, for example)
Practically everyone uses OpenSSL.

What servers do we have to setup?
OCSP responder?
*** What software are other certificate authorities using?
*** Guides of varying qualities other have written
**** Probably helpful
- [[http://pages.cs.wisc.edu/~zmiller/ca-howto/][How To Setup a CA]], Ian Alderman and Zach Miller
- [[https://www.wikihow.com/Be-Your-Own-Certificate-Authority][How to Be Your Own Certificate Authority (with Pictures) - wikiHow]]
- [[https://ericlemes.com/2018/05/17/ssl-part-3/][SSL – part 3 – How to run your own Certificate Authority – Eric Lemes' Blog]]
- [[https://workaround.org/certificate-authority/][How do I create my own Certificate Authority (CA) – workaround.org]]
- [[https://www.davidpashley.com/articles/becoming-a-x-509-certificate-authority/][Becoming a X.509 Certificate Authority - David Pashley.comDavid Pashley.com]]
- [[https://ssl.comodo.com/support/ssl-validation-faqs/what-standards-do-certification-authorities-have-to-comply-with.php][What standards do certification authorities have to comply with?]]
**** What
- [[https://www.esecurityplanet.com/network-security/how-to-run-your-own-certificate-authority.html][esecurityplanet.com]]
- [[https://fabrictestdocs.readthedocs.io/en/stable/Setup/ca-setup.html][Certificate Authority (CA) Setup — fabrictestdocs stable documentation]]
*** Tools of varying qualities others have made
- https://en.wikipedia.org/wiki/Certificate_authority#Software
- OpenSSL
- [[https://github.com/google/easypki][google/easypki: Creating a certificate authority the easy way]]
- https://github.com/recursecenter/ca-tools, requires ruby
** Hiring, interviewing, recruiting
*** We should use machine learning to hire?
*** Hiring standards, what to test in work sample tests
**** IOT engineer
Must master some of hardware, software, and business.

- Software
  - C++ smart pointers
- Hardware
  - soldering skills
  - basic understanding of electric circuits
  - designing and making PCBs, including local knowledge of where to buy components and services

What the employer may expect the employee to do:

- design and make systems (hardware and software) with constrained production cost and field operation
- maintain existing programs written in C++/Java (or whatever the employer uses), including documenting software
- travel to maintain remote hardware
*** What is the best predictor?
According to [[http://blog.eskill.com/best-worst-predictors/][eskill.com]]:
- past behavior
- conscientiousness (what is this? how do we test this?)
- cognitive ability

Interviews must be structured.
Unstructured interviews waste time.

[[https://resources.workable.com/blog/conduct-structured-interview][How to conduct a structured interview | Workable]]

We can test skill.

How do we test behavior?

Questions are unreliable.
Actions are reliable.

Where is the research paper?

How does Google hire?

What is the best predictor of on-the-job performance?
How do we interview to best predict on-the-job/post-interview performance?
- the reputation of recent employers (2 years?), and how long the employee worked at those employers
- past experience
- work sample test
- education/university
- IQ
- github
- tricky questions
- school grades
- what else?

Is there evidence-based hiring like evidence-based medicine?

Can we use machine learning to hire people?
[[https://www.criteriacorp.com/resources/whitepaper_tests_versus_humans.php][Can Pre-Employment Tests Predict Employee Success Better than a Human?]]
*** Uncertainty in hiring
In hiring, if a candidate leaves good impressions (not exceptional, but decent nonetheless), but you aren't sure about him, should you just reject him?
Does "maybe" mean "no"?
*** To avoid wasting time, begin with the most selective test.
Begin with the test with the highest failure ratio.
End the interview as soon as the candidates fail the test.
Respect their time and your time.
Don't force them to do what they can't do well.
Don't set them up to fail.
If you aren't going to hire them, don't waste their time.
*** Recruitment pipeline
- Review the resume / curriculum vitae.
*** You know your job ad is wrong when...
You know your job ad is wrong when you have to obviously reject a lot of candidates without thinking.

People don't read the job description.
People only read the job title.

To make sure that people read the job description, you can require that the applicant include a secret word that can only be found in the job ad.
Auto-reject people who don't read the job description.
*** Personality-based hiring doesn't work?
What are these trying to say?
- https://www.clomedia.com/2012/03/07/the-problem-with-personality-based-hiring/
** <2018-09-20> Politics
- [[https://www.youtube.com/watch?v=xDsg2sLhnIE][Trump Is Making America Great Again. Just Not the Way He Thinks. | NYT - Opinion - YouTube]]
** Indonesia market research: effect of sharia label on buying propensity?
Does slapping a sharia label on a hotel increases its sales?
** Why do some markets such as job markets don't show prices?
A supermarket shows its prices prominently.

Why doesn't a job market show its prices?

[[https://www.flexjobs.com/blog/post/why-isnt-salary-always-listed-on-a-postin/][Why Isn't Salary Always Listed on a Job Posting? - FlexJobs]]
*** Would it be better if they do?

https://www.elitedaily.com/money/about-sharing-salaries/1171642

*** How much should you be paid?

https://www.forbes.com/sites/jacquelynsmith/2012/11/27/how-to-figure-out-what-you-really-should-be-paid/#333beba75402
** <2018-09-21> Australia fruit sabotage crisis
- Is it done by immature kids?
- Is it done by foreign actors (to destabilize Australia, for example)?
- Is there any other explanation?
** <2018-09-22> Power: control vs identity
"The traditional view—that power means having /control/ over a group of people—is giving way to a new understanding: that power means having other people /identify/ with you." ([[https://insight.kellogg.northwestern.edu/article/four-tips-to-gain-influence-in-your-organization][source]])
** Apple deliberately makes their devices irreparable.
- Genius Bar caught ripping customer off ON CAMERA by CBC News https://www.youtube.com/watch?v=o2_SZ4tfLns
** <2018-10-28> Current definition of life: "self-sustaining chemical system capable of Darwinian evolution"
- from "How to Spot an Alien, According to NASA!" https://www.youtube.com/watch?v=pbZ2MFAbGrk
* Determining when your pants rise is too low
Your pants rise is too low if any of these are true:
- You feel your pants are cleaving your crotch.
- Your buttcrack shows when you bend over.
