#+TITLE: On paranormal evidence
#+DATE: 2019-09-02 00:00:00 +0700
#+PERMALINK: /paranormal-evidence.html
* Overview
I try to begin with first-hand reports of ex-skeptics, especially engineers and scientists, because they speak my language.

There is always the possibility of lying, but people who do not stand to gain from lying are probably not lying.

- Alan Hugenot took a mediumship course? Everyone can? https://makemindpowerful.com/can-develop-psychic-abilities-deep-hypnosis/
- mit.edu domain?
  - https://www.mit.edu/people/rei/spir.html
  - https://www.mit.edu/people/rei/spir-help.html
- this guy is a computer programmer https://www.youtube.com/watch?v=0ntav0LA9Yg
- John Roncz's 2012 "An Engineer's Guide to the Spirit World: My Journey from Skeptic to Psychic Medium"?
- Eben Alexander's "Proof of heaven"
- Russell Targ
- People who were in the military
  - Ben Swett http://www.bswett.com/spirit.html
  - Joe McMoneagle
* "Proof of Heaven [...]", Eben Alexander
"Proof of Heaven: A Neurosurgeon's Journey into the Afterlife"

This book is Eben Alexander's account of his near-death experience.

He considered how some materialistic hypotheses fail to explain the experience he had when his neocortex was not functioning.
* "The Reality of ESP: [...]", Russell Targ
"The Reality of ESP: A Physicist's Proof of Psychic Abilities"
* "Mind Trek [...]", Joseph McMoneagle
"Mind Trek: Exploring Consciousness, Time & Space through Remote Viewing"

Interesting: His out-of-body experience interferes with his remote viewing.
* "Remote Viewing: [...]", Ingo Swann
"Remote Viewing: The Real Story, An Autobiographical Memoir"
