#+TITLE: (Draft) A crash course on 21st-century physics, with emphasis on modeling
#+DATE: 2019-11-05 00:00:00 +0700
* About the book
** My original motivation, advanced hypotheses, and crackpots
Around 2019-11-08, I was reading much literature about remote viewing,
and I found many resources with various agenda, from the most legitimate open-minded people to the most illegitimate crackpots.
My motivation for learning quantum mechanics was to distinguish between legitimate hypotheses and quantum woo.

But all the crackpots I have encountered are so obvious that one immediately suspects crackpottery even without any knowledge of quantum mechanics.
Perhaps it is their very attempt at looking legitimate that gives them away.

But to me there is no practical difference between legitimate advanced hypotheses and illegitimate crackpots;
both are incomprehensible and useless to me, and I shall treat them equally:
give them the benefit of the doubt, and ignore them until I understand them, if ever.
* To understand is to model accurately
To understand something is to create a reasonably accurate model (internal mental model) of it.

I want to write a physics book with emphasis in /modeling/, because that is what physics is.
* Physics and mathematics
Physics is about understanding (and therefore creating a reasonably accurate model of) reality,
and mathematics is its tool for concise precise communication.
* Modeling some simple motions
** Galileo's inclined planes
The bottom of the inclined plane is at the ground.

The height of the top of the inclined plane from the ground is represented by a real number \(h\).

The angle of the inclined plane is represented by a real number \(\theta\).
The number zero represents a horizontal plane (a plane that is parallel to the horizon as seen by someone standing on Earth).

A ball is held still at the top of the plane, and it is released.

The time taken by the ball to move from the top of the plane to the bottom of the plane is represented by a real number \(t\).

Galileo (Was it he or someone else?) dropped two heavy solid things with different masses from the same height,
and he found that both of them reached the ground at the same time, regardless of the height from which they fell.

Galileo found that \( h \) is proportional to \( t^2 \).
* Modeling motion, the classical way
In this section, we consider the motion of a body.

A body is presumed to be rigid, indivisible, to occupy no space.
It is tacitly assumed that bodies do not collide with each other.
** Modeling spacetime as Euclidean space
Here we consider the classical model of spacetime.

Space is represented by a three-dimensional Euclidean space.

Time is represented by a one-dimensional Euclidean space, isomorphic to the real line, the set of real numbers.
(Thus we sometimes say "a point in time").

An /Euclidean space/ is a set of points.

An /Euclidean vector space/ is a set of vectors with Euclidean metric.

The number of dimensions of an Euclidean space is the maximum number of mutually orthogonal lines
you can simultaneously make without making any pair of them parallel.
For example, if we pick three pens, we can arrange them into three vectors which are orthogonal to each other.
But, if we pick four pens, we know no way to arrange them as four mutually orthogonal vectors.
That is why we think that space is three-dimensional.
** Modeling motion as function
An /observer/ is chosen at an arbitrary point O in space.

An arbitrary point in time is chosen, and is designated as the /zero time/.

Addition behaves as follows:
- Vector + Vector = Vector: The addition of a vector AB and a vector BC produces a vector AB + BC = AC.
- Point + Vector = Point: The addition of a point X and a vector XY produces the point X + XY = Y.

The /position/ of an object at position B /as observed by an observer/ at position A is represented by the /vector/ AB.

The /motion/ of an object of interest /as observed by an observer/ at position O is represented by a function \( x \)
whose interpretation is: "At time \(t\), the object of interest is at position \(O + x(t)\)".

In short, a /movement/ is a change in position,
and a /motion/ is a continuous movement.
** Modeling instantaneous velocity with derivatives
If we record that a body was at position \(x(t_0)\) at time \(t_0\) and that it was at position \(x(t_1)\) at time \(t_1\),
then we say that the body moved between time \(t_0\) and \(t_1\) with the /average velocity/ \(\bar{v}(t_0,t_1) = \frac{x(t_1)-x(t_0)}{t_1-t_0}\).

If we endeavor to record the movement more frequently that \(t_1\) approaches \(t_0\),
we approximate the /instantaneous velocity/ of the body at \(t_0\), that is
\( v(t_0) = \lim_{t_1 \to t_0} v(t_0,t_1) = \lim_{t_1 \to t_0} \frac{x(t_1) - x(t_0)}{t_1 - t_0} \).

We define "the /derivative/ of \(f\) at \(x\)" as \( [Df](x) \) where:
\begin{align*}
[Df](x) = \lim_{h \to 0} \frac{f(x+h)-f(x)}{h}
\end{align*}

Note that \(Df\) notates a function, read "derivative of \(f\)", not "\(D\) multiplied by \(f\)".

Note that \([Df](x)\) notates the output produced by function \(Df\) for input \(x\).

The concept of derivative is required for Newton's model of a many-body system.

Exercise: If \(f(x) = x^2\), evaluate \([Df](5)\).
** Euclidean spaces vs real tuple spaces
Euclidean spaces and real tuple spaces are isomorphic, but they are not the same.
An Euclidean space is a set of points.
A real tuple space is a set of tuples of real numbers.
** Modeling motion in Newtonian kinematics
The position of a body at a given time is represented by a vector in the observer's vector space.
** Modeling motion in Lagrangian kinematics?
Let O be the fixed point of the pendulum, that is, the point where the rope is fixed to the frame/stand/fixture.

For example, instead of representing the position of a pendulum bob by three real numbers \((x,y,z)\) relative to the point O,
one may choose to represent the position of that pendulum bob by one real number \(\theta\)
that represents the angle from the normal line (a line that is perpendicular to the floor and passes the point O).

If you are already familiar with Newtonian mechanics, and you want to understand analytical mechanics, perhaps read \cite{lanczos2012variational}.

Lagrangian mechanics exploits the conservation of energy to simplify the mathematical description of a dynamical system?
** Modeling transverse waves or surface waves
A wave is represented by a function

f : Position × Time → Amplitude

The interpretation is: "At time \(t\), the amplitude of the part of the wave at point \(x\) is \(f(x,t)\)".

Amplitude is displacement from resting position.

That is, a wave is often represented as an /amplitude field/.
(In mathematical physics, an "X field" is a function from position to X.)

Example phenomena that can be represented by periodic functions:
the motion of a pendulum,
the surface waves of water in a pond,
the oscillation of a guitar string.

Often, the wave is extrapolated to infinity.
For example, when modeling a pond, we often assume that the pond is infinite, it has no edges, and waves do not reflect off the edges.
We assume that wave propagate freely without hitting any obstacles, without reflection, without diffraction.

If we use the simplifying assumption that a wave repeats infinitely in both space and time,
then we can define wavelength and period:

A wave has /wavelength/ \( |dx| \) iff \( dx \) is a shortest vector (the shortest vector) such that \(f(x+dx,t) = f(x,t)\) for all \( t \).

A wave has /period/ \( dt \) iff \( dt \) is the smallest positive number such that \(f(x,t+dt) = f(x,t)\) for all \( x \).

That is, wavelength is spatial periodicity, and period is temporal periodicity.
* What is the justification for the principle of stationary action?
An example of a variational principle is Fermat's principle:
the path taken by light in free space is such that the time of travel is minimized.

Another example:
If an object moves from \((x_0,t_0)\) to \((x_1,t_1)\) in a conservative force field,
then the motion (the path) is such that energy (the sum of potential energy and kinetic energy) is conserved,
that is, the force does zero work on the object at every point of the object's actual trajectory in spacetime.

Given a hypothetical path, we can compute the work the force /would/ do to the object if the object followed that path.
* Planned contents
- work
- What does it mean that a force does some /work/ on an object?
- conservation of energy
  - Galileo's interrupted pendulum[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conservation_of_energy#History]
- How does one find a conserved quantity?[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conserved_quantity]
- conservation of momentum, Newton's cradle
- conservation of kinetic energy, vis viva, elastic collisions
- ???
- principle of stationary action
- describing curved surfaces
  - How do we describe a sphere? \(x^2+y^2+z^2 = r^2\).
  - How do we describe a curved surface? By its tangent space? By coordinate mapping?
- Derive Einstein field equations from analytical mechanics / principle of stationary action?
  \cite{lanczos2012variational}
- [[file:integral.html][On integrals]]
* Modeling the cause of motion, the classical way
A force is defined as the cause of motion.

If we observe that an object is accelerating, then we take it to mean that a non-zero resultant force is acting on the object.

Newton's second law:
Iff \(F(t)\) is the sum of all forces acting on an object at time \(t\),
and iff \( p(t) \) is the object's momentum at time \(t\),
then \( F = Dp \).
* Modeling the evolution of a many-body system
Consider a system that consists of several tiny bodies in motion.

Newton, Lagrange, Hamilton, Schrödinger, and Einstein are about modeling the evolution of a many-body system.
It is about identifying tacit simplifying assumptions and relaxing them.
Relaxing a tacit simplifying assumption produces a theory that is more complex but more accurate.
** Newton model of a many-body system
The interpretation is: "At time \( t \), the position of body \( k \) is \( x_k(t) \)".

For each body \( k \), its trajectory is represented by a function \(x_k\) : Time → Position,
where time is represented by a real number,
and a body's position is represented by a point in a three-dimensional Euclidean space.

Iff \( x(t) \) is an object's position at time \(t\), and \( p(t) \) is the object's momentum at time \(t\),
and iff the object's mass is constant \(m\), then \( p(t) = m \cdot [D x](t) \), or, \( p = m \cdot D x \),
but note that \(m\) is a scalar and \(Dx\) is a function (which is a vector in a function space, in the generalized mathematical sense),
and thus \(m \cdot Dx\) can be thought of as "\(Dx\) scaled by \(m\)".

\( F_k(t) \) is the sum of forces acting on object \(k\) at time \(t\).

Because acceleration is the second time-derivative of position,
we can substitute \( a_k = D(Dx_k) \) into \( F_k = m_k \cdot a_k \)
to obtain \( F_k = m_k \cdot D(Dx_k) \).

If the bodies are celestial objects,
then the shape of \( F_k \) is determined by Newton's law of universal gravitation.

Thus, in the Newton model, the entire system of \( n \) bodies is represented by \( n \) differential equations,
in which each differential equation has the shape \( F_k(t) = m_k \cdot [D(Dx)](t) \),
where the expression \( F_k \) usually contains \( x_k \).

One should not confuse a function and its expression.
** Lagrange model of a many-body system
You may want to read Lagrange's own words (albeit translated from French into English)[fn::<2019-11-06> https://archive.org/details/springer_10.1007-978-94-015-8903-1],
from page 169.
It has historical context.
It may also describe Lagrange's train of thought.
It can be downloaded as PDF.

If the Newton model of an \(n\)-body system consists of \(n\) differential equations,
the Lagrange model of the same system consists of /one/ equation?

The interpretation is "At time \(t\), the position of body \(k\) is \(x_k(q_k(t),t)\)".

\( x_k \) : GenCoord-k × Time → Position

Each GenCoord-k is a real tuple space and may have a dimension different from other GenCoord-i spaces.
** Hamilton model of a many-body system
** Schrödinger model of a many-body system
In the wave-mechanics model, the position of a body is represented by a parameter of the system's wave function.

In the wave-mechanics model, the entire system of \( n \) bodies is represented by a function
Position-1 × ... × Position-n × Time → Complex.

\( \psi(x_1, \ldots, x_n, t) \).

Key question: What do the parameters of \( \psi \) represent?

In the Schrödinger--Born model, the real number \( |\psi(x_1,\ldots,x_n,t)|^2 \)
represents the density of the probability of finding, at time \(t\), that body 1 is at \(x_1\), ..., and body \(n\) is at \(x_n\).
That is, the positions of the bodies are not as separate as in the Newton model.

Read Turgut 2005 crash course?[fn::<2019-11-05> Turgut 2005, "A Crash Course on Quantum Mechanics" http://www.physics.metu.edu.tr/~sturgut/qm.pdf]

However, people fiercely disagree about the meaning of the wave function.
** Einstein model of a many-body system
All the above models of mechanics, both classical and quantum, make tacit assumptions about spacetime (space and time).
In particular, they presume that spacetime is absolute and the same everywhere.

Einstein models replaces the assumption of absolute spacetime (shared by all bodies) with relative (body-specific) spacetime.

(Here I am using "body" as a synonym of "observer".)

In Einstein models, there is no such thing as "the position of body \( k \) at time \( t \)";
it is replaced with "the position of body \( j \) at time \( t \) /according to body \( i \)/",
that is, /both/ the position and the time are as seen from body \(i\).

Here we write \([i:x_j(t)]\) to mean "the position of body \(j\) at time \(t\) according to body \(i\)".

Newton models tacitly assume \([i:x_j(t)] = -[j:x_i(t)]\).

What does "simultaneous" ("at the same time") mean in this model?

How do we know if two things are simultaneous?

Einstein postulated the constancy of the speed of light in order to make Maxwell's equations to have the same form in all reference frames.

In special relativity, each body has its own time.

A body's time is defined operationally as whatever is measured by a clock attached to the body.

How do we describe curvature?
 [fn::<2019-11-05> https://physics.info/general-relativity/]

(Notes to functional programmers: Types can help elucidate Einstein's field equations.)

At the lowest layer, there are only numbers;
vectors, matrices, and tensors can be thought of as a meaningful way of grouping numbers.
** The next model?
A common problem with /all/ those model is that they tacitly assume that spacetime is infinitely divisible like the set of real numbers.

But what would be the mathematics of non-continuous spaces be like?
And what would it imply about the isotropy of space?
* Electron excitation is not instantaneous
2019 article "To catch and reverse a quantum jump mid-flight"[fn::<2019-11-09> https://www.nature.com/articles/s41586-019-1287-z],
via video "Quantum Leap / Quantum Jump Explained"[fn::<2019-11-09> https://www.youtube.com/watch?v=r8uVbwD-aZM].
* Bibliography
