#+TITLE: (Draft) A crash course on 21st-century physics, with emphasis on modeling
#+DATE: 2019-11-05 00:00:00 +0700
* About the book
** My original motivation, advanced hypotheses, and crackpots
Around 2019-11-08, I was reading much literature about remote viewing,
and I found many resources with various agenda, from the most legitimate open-minded people to the most illegitimate crackpots.
My motivation for learning quantum mechanics was to distinguish between legitimate hypotheses and quantum woo.

But all the crackpots I have encountered are so obvious that one immediately suspects crackpottery even without any knowledge of quantum mechanics.
Perhaps it is their very attempt at looking legitimate that gives them away.

But to me there is no practical difference between legitimate advanced hypotheses and illegitimate crackpots;
both are incomprehensible and useless to me, and I shall treat them equally:
give them the benefit of the doubt, and ignore them until I understand them, if ever.
** What is to understand?
To understand something is to create a reasonably accurate model (internal mental model) of it.

I want to write a physics book with emphasis in /modeling/, because that is what physics is.

Physics is about understanding (and therefore creating a reasonably accurate model of) reality,
and mathematics is its tool for concise precise communication.
* Planned contents
- [[file:physics-motion.html][On motion]]
- [[file:nature.html][A physics book draft]] (should be split into articles instead)
- [[file:chemistry-ontology.html][On the evolution of the ontology of chemistry]]
- work
- What does it mean that a force does some /work/ on an object?
- conservation of energy
  - Galileo's interrupted pendulum[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conservation_of_energy#History]
- How does one find a conserved quantity?[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conserved_quantity]
- conservation of momentum, Newton's cradle
- conservation of kinetic energy, vis viva, elastic collisions
- ???
- principle of stationary action
- describing curved surfaces
  - How do we describe a sphere? \(x^2+y^2+z^2 = r^2\).
  - How do we describe a curved surface? By its tangent space? By coordinate mapping?
- Derive Einstein field equations from analytical mechanics / principle of stationary action?
  \cite{lanczos2012variational}
- [[file:integral.html][On integrals]]
* Electron excitation is not instantaneous
2019 article "To catch and reverse a quantum jump mid-flight"[fn::<2019-11-09> https://www.nature.com/articles/s41586-019-1287-z],
via video "Quantum Leap / Quantum Jump Explained"[fn::<2019-11-09> https://www.youtube.com/watch?v=r8uVbwD-aZM].
* Physics blog
What is the evidence for quantum field theory?
What experiments justify it?
** <2019-08-14> Electromagnetic wave
In Maxwell's theory, an electric charge instantaneously affects all of space,
and an electromagnetic wave is not something emitted by an electric charge.
* Bibliography
