#+TITLE: (Draft) A story of physics
#+DATE: 2019-11-05 00:00:00 +0700
\(
\newcommand\dif{\mathrm{d}}
\newcommand\Dif{\Delta}
\)
* Note: This book is not a history book
Historically, the development of physics and mathematics were intertwined, but, in hindsight,
it is more efficient to develop mathematics first, and then do physics in it,
because modern mathematical notation greatly boosts efficiency.
We thank our ancestors for giving us hindsight.

It is much more efficient to do physics in the language of mathematics (a domain-specific language embedded in English) than doing physics in plain English.

By this book, we hope to come up with an optimal learning sequence for 21st century physics, in narrative form.
* The story and the characters
** The characters and their desires
The /humans/ want to know Nature.
If that is impossible, then they at least want to understand Nature,
to gradually build increasingly accurate models of Nature,
to understand a little bit of quantum mechanics and general relativity.
But the humans often thwart themselves:
pride, egoism, infighting, dogmatism, refusal to change beliefs despite counterevidence.

The /models/ (the mathematical models) help the humans build great things,
but sometimes the humans fall in love with the models and become too dogmatic and this halts progress.

/Nature/ is not hiding its secrets;
otherwise it would answer experiments with lies.
** Which should be the protagonists and which should be the antagonists?
*** Pitting the humans against the humans
We can depend on humans to antagonize themselves.
They are an inexhaustible source of antagonism.

Examples: Bruno/Galileo vs the Roman Catholic church,
prudent people vs the Indiana pi bill, scientists vs cranks,
fringe scientists (e.g. Wegener of plate tectonics) vs old guards,
young scientists vs non-random grants,
honest academicians vs broken academic system.
*** Pitting the humans against the models
The protagonists are the humans, and their undergraduate-level math knowledge.

The antagonists are the mathematical models of Nature,
and all their associated mathematical objects, formalisms, knowledge.

The climax is the "battle" against quantum mechanics and general relativity.

This choice gives rise to the following natural plot.

The models think they are real.
The humans defeat the models by asking philosophical questions and showing experimental evidence against the models.
Perhaps we need to resort to some cheesy personification here; we may personify a model as someone who dogmatically believes the model.

But I don't want to write a [[https://en.wikipedia.org/wiki/Socratic_dialogue][Socratic dialogue]] like this:

#+BEGIN_QUOTE
Alice: "O, Exalted Guy Bob, tell me, what is motion?"

Bob: "O, Wise Girl Alice, motion is ..."

Alice: "But it doesn't make sense; ..."

Bob: "Indeed, but ..."
#+END_QUOTE

I want the book to contain telepathic answers.
I want the book to read the questions that appear in my mind as they arise.
*** Pitting the models against the humans
The protagonists are the mathematical models.

The antagonists is the humans' ignorance.
and all their associated mathematical objects, formalisms, knowledge.

The climax is the "battle" against the humans' ignorance of quantum mechanics and general relativity.

(Problem: Won't making the readers the antagonists antagonize the readers?
They aren't going to read!)
*** Nature is not a character
It does not make sense for Nature to be a protagonist because Nature apparently does not develop its character.

It also does not make sense for Nature to be an antagonist because Nature apparently is unbeatable.
** ? The goal, the purpose
The goal is not to understand all models,
but to build enough habit of /mathematical thinking/
so that we are /able/ to understand models /as necessary/,
in the same way the purpose of learning to punch is not to punch everything all the time,
but to build enough habit so that we are /able/ to punch /as necessary/.

Drill down / flesh out / detail some of [[http://www.goodtheorist.science/][t'Hooft's advice]].
** ? How to read this book?
(Will this still be valid? The book is changing to a narrative.)

Skip everything until you find something you don't understand,
and then begin reading from there.
This should be possible, because the chapters have been ordered ascending by sophistication (both mathematical and physical).
Each chapter builds on all previous chapters.
* --- The plot ---
The plot serves as a plan/draft/sketch for/of the content of this book.

The plot also serves to establish an optimal learning sequence, and as a table of contents for this book.

The plot is /not/ necessarily historical.
* ? Act: Settling down
(Does this go back too far away to the past?)

They invent language.

They count people and animals.

They begin manipulating Nature to simplify their survival.

They settle down.
They change from being nomadic to being sedentary.

They build houses.

They domesticate plants and animals.

They farm, enabling them to build bigger and denser settlements.

They invent writing.
They invent paper.
They build libraries.
This enables knowledge to be preserved and carried over to the far future.
Knowledge no longer dies with the people who have it.

/They solve hunger./
Survival no longer occupies their mind.

They begin doing what they /want/, not what they /must/.

They begin doing mathematics out of /curiosity/, not /necessity/.
* What
They shift their thinking from /how/ to /why/,
from "How do we model this" to "suppose that we have a model; what properties should it satisfy?"

They make up /principles/: reasonable assumptions with some philosophical justification.

They say light travels in a straight line, but they are not content with that.
They say that if we know that light travels from point P to point Q in free space,
then the length of line PQ is the shortest distance between P and Q.

They switch from unprincipled modeling to principled modeling.
They invoke reason and philosophical justification.

They unify their models of motion of matter and motion of light.
They come up with variational principles.
* Act: Classical mechanics
** Turning point: Momentum
They measure the amount of motion.

They collide things, elastic and inelastic.
** ? Turning point: Buoyancy, mass, and weight
They discover /buoyancy/: things are easier to lift in water than on land.
This concept enables them to /distinguish between mass and weight/.
They define that the /mass/ of a thing is the /amount of matter/ in it,
whereas its /weight/ is /what has to be overcome in order to lift/ it.
** Turning point: Levers, pulleys, simple machines?
They exploit string tension to invent pulleys to help weightlifting.
** Turning point: Analytic geometry
They want to name every point in space, because they want to answer where something is.

They introduce /coordinate systems/ to name every point and every vector.
They introduce /vectors/ to describe changes, displacements, movements.

They marry analysis and geometry, begetting /analytic geometry/.

They begin doing geometry with numbers instead of drawings.

They begin describing shapes with algebraic equations instead of drawings.

They invent Cartesian coordinate systems.

They invent non-Cartesian coordinate systems.

They invent coordinate transformations.
** Turning point: Calculus, real analysis, differential equations
They know real numbers, arithmetics, measurements, and algebra (variables).

They model falling objects with a /quadratic equation/.

They use /functions/ to model motion with constant/uniform acceleration.

They model space as a three-dimensional Euclidean space.
They discover Newton's law of universal gravitation and Coulomb's law.

They want not only the end points, but also the trajectory, all points in between.

They introduce /functions/ and /trajectories/.

They model /motion/.
They introduce /time/.

They invent chemistry.
They observe that chemical reactions /conserve/ the mass of its reactants.

They invent steam engines.
They define "work" as "weight lifted through a height" \cite{coriolis1829calcul}[fn::<2019-12-25> https://en.wikipedia.org/wiki/Work_(physics)].
They realize that weight is a force.
They generalize "work" to all forces.

They model spaces and objects.

When is something?

Multi-variable question.
Question with several question words.
"When is something where".
At time t, the position of the object is x.

Time.

Coordinate transform.

Optimization problems.
Fermat's method of adequality.
Variational calculus.

They solve the differential equation in the two-body problem.
They discover that two celestial bodies orbit each other elliptically.
** Turning point: The electrochemical cell
The invention of the electrochemical cell is pivotal.

Galvani animal electricity.
Volta suspected the different metals; he followed his suspicion; it led him to his invention of the electrochemical cell.
He set out to prove Galvani wrong, not to revolutionize the world.

Enables experiments of atomic theory and electromagnetism.

Enables electrochemistry, which enables the isolation of many chemical elements by Humphry Davy and his big battery.

Enables the discovery of subatomic particles, such as the discovery of electron by Crookes.

Enables electrodynamics, Hertz's experiments, Faraday's experiments, and Maxwell's equations.
** Turning point: Force, work, and kinetic energy
They discover that the work done by a force on an object is equal to the change in the object's kinetic energy.
** Thermodynamics?
They measure temperature indirectly by the expansion of the length of a piece of metal.
** Turning point: Lagrange writes "Analytical mechanics"
** Turning point: Principle of stationary action
They come up with the concept of /conservative/ forces and /potential gradients/.

They model /collisions/.

They find out some conserved quantities.
They find out that Galileo's interrupted pendulum conserves energy?
They find out that Newton's cradle conserves momentum.
Galileo's interrupted pendulum[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conservation_of_energy#History].
How does one find a conserved quantity?[fn::<2019-11-06> https://en.wikipedia.org/wiki/Conserved_quantity]
Conservation of kinetic energy, vis viva, elastic collisions.

They shift their thinking from "/what/ is motion" to "/why/ is motion".

They have a lot of models.

They shift their question from "How do we model motion" to "How do we /generate/ these models of motion".

They begin asking the question "What is the minimum amount of information we need to model the dynamics of a system".

"What is the simplest explanation for motion".

They begin divorcing mathematics from physics.

They begin meta-reasoning, that is reasoning about reasoning.
Perhaps this shift is why it is hard to understand the development of physics after this point.

They suspect that there is something more fundamental.

Newton's laws explain /how/ things move (/what/ motion is).
The principle of stationary action explains /why/ things move (/why/ motion is).

They surmise that things move /to stationarize their actions/.

They don't know why; it just gives the right equations of motion.

Euler--Lagrange equation.

They discover, in optics, that the angle of incidence and the angle of reflection are equal.
They state that more fancifully: Light takes the path that requires the least time to traverse.

They generalize/unify the disparate variational principles?

They propose Friston's [[https://en.wikipedia.org/wiki/Free_energy_principle][free energy principle]].
It is a variational principle.

It becomes in vogue to derive physical laws from variational principles.

https://en.wikipedia.org/wiki/History_of_variational_principles_in_physics

Lanczos's "the variational principles of mehanics"?

But how the hell did they arrive at that conclusion?
Of whose ass was the "principle of stationary action" pulled out?
Hamilton's?
What was the justification?

They find out that they are lazy.
They surmise that this laziness pervades Nature:
everything spends minimum effort to get maximum result.
They are eager to overgeneralize.

We can think in reverse:
From Newton's laws, find what gives Newton's laws when optimized.

Optimization problem, variational calculus.

They solve the brachistochrone problem, just because they can.

Then comes Lagrangian mechanics.
The form of "Lagrangian mechanics" we know today was actually invented by Hamilton?
Stigler's law of eponymy.
** Turning point: Unified theory of motion of light and matter
They introduce the [[https://en.wikipedia.org/wiki/Hamilton%E2%80%93Jacobi_equation][Hamilton--Jacobi equation]],
which unifies several variational principles and provides a unified theory of the motion of light and matter.

They seek the most general variational principle.
* Act: 20th century physics
** Turning point: Symmetry, Erlangen program, Noether's theorem
What?

They formalize symmetry using logic?

They formalize the symmetry of functions?

They begin the Erlangen program.
They formalize the symmetries/invariants into groups of transformations.
They hierarchicalize geometries based on their invariants?
** Turning point: Mass-energy equivalence
They discover that mass is congealed energy.[fn::https://www.ted.com/talks/david_christian_big_history/transcript?language=en]
** Turning point: CP-violation / symmetry breaking
** ? Act: quantum mechanics
Then comes quantum mechanics.

How the hell did Schrödinger arrive at (or perhaps "come up with") that strange equation?
** ? Act: geometry, relativity
- describing curved surfaces
  - How do we describe a sphere? \(x^2+y^2+z^2 = r^2\).
  - How do we describe a curved surface? By its tangent space? By coordinate mapping?
- Derive Einstein field equations from analytical mechanics / principle of stationary action?
  \cite{lanczos2012variational}
** Turning point: Hawking radiation
They predict Hawking radiation by thinking about a pair of virtual particles X and Y (quantum mechanics) near a black hole (general relativity).
X falls into the black hole, and Y escapes.
** ? Act: quantum field theory
* Other drafts
- [[file:physics-motion.html][On motion]]
- [[file:nature.html][A physics book draft]] (should be split into articles instead)
- [[file:chemistry-ontology.html][On the evolution of the ontology of chemistry]]
- [[file:integral.html][On integrals]]
* What digressions?
** Digression: Narrative of target audience
<2019-12-25>

My target audience is people like me:
those who want to understand a little bit of 21st century physics in their spare time.

(This book tells a story about reading this book itself. What the hell.)

Enter John, a 30-year-old who aspires to understand recent physics.

John is a 30-year-old man who likes mathematics, physics, and research, but he avoids a job in academia,
because he refuses to rot in the ivory tower infested with perverse incentives and predatory publishers,
so he spent 10 years working as a well-paid engineer.
Now that he has saved enough money to survive for a while,
he rekindles his old dream of being an amateur who discovers fun things.

John wants to learn a little bit of recent physics, especially quantum mechanics and general relativity,
but he doesn't have some billion dollars to spare for building a particle accelerator or a satellite probe, for experimental physics,
and he prefers to work alone or in small groups,
so he gets into theoretical physics, because,
as Vladimir Arnold [[https://www.uni-muenster.de/Physik.TP/~munsteg/arnold.html][wrote]],
"Mathematics is the part of physics where experiments are cheap."

He wants to understand the mathematics, not just pop science.
He wants to distinguish between real spirituality and quantum woo.

John is comfortable with undergraduate-level physics.
** Digression: Where curiosity led us
Numbers got divorced from counting.

We saw that some things happen together.
We began expecting and predicting things.
We understood /correlation/.
We understood /causation/ as a reliable time-ordered correlation.
We had an internal model that enables /counterfactual reasoning/ by simulating the past or the future.
We gained the ability to imagine, both the past and the future.

/Language/, /writing/, and /alphabets/ came along.

/Algebra/.

/Functions/ and /relations/.
Relate effort to harvest.

To maximize the area enclosed by a rope.
What shape has the maximal area-to-circumference ratio?

We frame motion as an /optimization problem/.
We think in reverse: what is optimized by a free-falling body?

Then our desire grows.
We begin modeling things for fun, not because we need to.
Brachistochrone problem.
Soap bubble on two coaxial rings.
Calculus of variations.

We wonder why things move.
Because forces.
But that only shifts the question:
What is a force?

We try to model falling things with numbers.

Galileo found \( h = kt^2 \).

Then vectors.

Newton found \( F = G m_1 m_2 / r^2 \).

We want every point in between.

Then we graph functions and superimpose them on the real world.

Trajectories.

Where does Lagrange come in?

Now that we have a lot of models, we wonder: is there an easier way to do this?
Is there something common to these models?
Which generalizes which?
Which can be derived from which?
We begin meta-modeling: modeling the models, using math to think about math itself.
Then math begins to take a life of its own.

It seems that both linear programming and variational calculus are optimization problems?
** Narrative: What
At first we did something to survive; it was work.
Then we did it for leisure, for fun, for love.
Then we did it for pay, that is, indirectly, to survive; leisure has become work again.
We have come back to where we started from.
Materially we are better off, but spiritually we are worse off.

We see every inconvenience as a problem to be eliminated, while being unaware that the solution creates more problems.
We create technologies without thinking about the problems they create.

** My original motivation, advanced hypotheses, and crackpots
Around 2019-11-08, I was reading much literature about remote viewing,
and I found many resources with various agenda, from the most legitimate open-minded people to the most illegitimate crackpots.
My motivation for learning quantum mechanics was to distinguish between legitimate hypotheses and quantum woo.

But all the crackpots I have encountered are so obvious that one immediately suspects crackpottery even without any knowledge of quantum mechanics.
Perhaps it is their very attempt at looking legitimate that gives them away.

But to me there is no practical difference between legitimate advanced hypotheses and illegitimate crackpots;
both are incomprehensible and useless to me, and I shall treat them equally:
give them the benefit of the doubt, and ignore them until I understand them, if ever.
** What is to understand?
To understand something is to create a reasonably accurate model (internal mental model) of it.

I want to write a physics book with emphasis in /modeling/, because that is what physics is.

Physics is about understanding (and therefore creating a reasonably accurate model of) reality,
and mathematics is its tool for concise precise communication.
* Physics blog?
What is the evidence for quantum field theory?
What experiments justify it?
** <2019-08-14> Electromagnetic wave
In Maxwell's theory, an electric charge instantaneously affects all of space,
and an electromagnetic wave is not something emitted by an electric charge.
** Electron excitation is not instantaneous
2019 article "To catch and reverse a quantum jump mid-flight"[fn::<2019-11-09> https://www.nature.com/articles/s41586-019-1287-z],
via video "Quantum Leap / Quantum Jump Explained"[fn::<2019-11-09> https://www.youtube.com/watch?v=r8uVbwD-aZM].
* Bibliography
