#+TITLE: (Draft) On theoretical physics
#+DATE: 2019-12-28 00:00 +0700
\(
\newcommand\der{\operatorname{der}}
\newcommand\Der{\mathrm{D}}
\newcommand\dd{\operatorname{d}}
\newcommand\ang[1]{#1^\circ}
\newcommand\parenthesize[1]{\left(#1\right)}
\newcommand\dif{\mathrm{d}}
\newcommand\Dif{\Delta}
\)
* Geometry
** Synthetic geometry
A [[https://en.wikipedia.org/wiki/Space_(mathematics)][space]] (a mathematical space) is a set.

A /point/ is an element of a space (a set).

| geometry | set theory |
|----------+------------|
| space    | set        |
| point    | element    |

We write \(d(x,y)\) to mean "the /distance/ between point \(x\) and point \(y\)".
"[[https://en.wikipedia.org/wiki/Metric_(mathematics)][Metric]]" is another term for "distance".

See also [[https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)][a brief history of vectors]].

An /[[https://en.wikipedia.org/wiki/Euclidean_vector][Euclidean vector]]/ is something with magnitude and direction.

A /vector/ is an element of a [[https://en.wikipedia.org/wiki/Vector_space][vector space]].

A /[[https://en.wikipedia.org/wiki/Manifold][manifold]]/ is a "space that locally resembles Euclidean space near each point".

The /[[https://en.wikipedia.org/wiki/Tangent_space][tangent space]]/ of \(S\) at \(p\), written \(T_p S\),
is the vector space of every vector that is tangent to \(S\) at \(p\).

TODO: Relativity

Einstein's summation convention.

Tensors are covariant/contravariant /with respect to what/?
** Motivating stress tensor
See [[https://en.wikipedia.org/wiki/Stress_(mechanics)][Wikipedia]].

Generalize
/uniaxial normal stress/ \( \sigma = F/A \)
and /simple shear stress/ \( \tau = F/A \)
to [[https://en.wikipedia.org/wiki/Cauchy_stress_tensor][Cauchy stress tensor]]
** Invariants
Let \(\phi : D \to C\) be a function.

Let \(T : D \to D\) be a function, usually called a "transformation".

We say
"\(\phi\) is /unaffected/ by \(T\)"
or "\( \phi \) is /\(T\)-invariant/"
or "\( T \) is an /invariant/ (a /symmetry/) of \( \phi \)"
iff, for all \(x \in D\):
\[ \phi(x) = \phi(T(x)) \]

Here are some examples of invariants.

Let \( Tx = x + c \) represent translation.

Example:
If \(\phi(x,o,r)\) means "\(x\) is a point on a circle with center \(o\) and radius \(r\)",
then \(\phi(x,o,r) = \phi(Tx,To,r)\).
(A predicate is a function whose codomain is the set of booleans.)

Example:
If \(V\) is a vector space, then \(\SetBuilder{Tv}{v \in V} = V\).
If we follow the "auto-lifting" convention, we can write the equation more prettily as \( TV = V \).

Example:
Even functions exhibit mirror symmetry.
(A function \( f \) is /even/ iff \( f(x) = f(-x) \) for all applicable \(x\).)

Example:
Periodicity is a special case of translation-invariance.
(A function \(f\) has /period/ \(p\) iff \(p\) is the smallest positive number such that \( f(x+p) = f(x) \) for all applicable \(x\).
A function is /periodic/ iff it has a period.)
** Symmetries
Example: let \(S\) be the set of points of an unlabeled square.

Let \(T\) be a rotation about the square's center by a right angle.

We write \(TS\) to mean "the result of rotating \(S\) about its center by a right angle".

We write \(TS = S\) to mean "rotating \(S\) about its center by a right angle produces \(S\) itself".
** Analytic geometry
See also [[https://en.wikipedia.org/wiki/Analytic_geometry][Wikipedia]].

Let \(S\) be a space.

A /[[https://en.wikipedia.org/wiki/Coordinate_system][coordinate system]]/ for \(S\) is a surjective function \(C \to S\)
where \(C \subseteq \Real^n\).

Let \(s : C \to S\) be a coordinate system.

Let \(s' : C' \to S\) be a coordinate system.

We say that \(x\) /names/ \(s(x)\).

We say that \(x\) /refers to/ \(s(x)\).

We say that \(x\) /references/ \(s(x)\).

We say that \(x\) is an /\(s\)-name/ of \(s(x)\).

We say that \(x\) is a /\(C\)-name/ of \(s(x)\).

We say that \(s(x)\) is the /referent/ of \(x\).

We say that \(s(x)\) is the \(s\)-/referent/ of \(x\).

We say that \(s(x)\) is the \(C\)-/referent/ of \(x\).

A /[[https://en.wikipedia.org/wiki/Coordinate_system#Transformations][coordinate transformation]]/ from \(s\) to \(s'\)
is a function \(T : C \to C'\) such that \(s(x) = s'(x')\) where \(x' = T(x)\) for all \(x \in C\).

A coordinate transformation changes the names but preserves the point.

"Coordinate system transformation" means "coordinate transformation".

A /[[https://en.wikipedia.org/wiki/Atlas_(topology)][chart]]/ (a /coordinate chart/) for \(S\)
is a [[https://en.wikipedia.org/wiki/Homeomorphism][homeomorphism]] between a subspace of \(S\) and a subspace of an Euclidean space.

An /atlas/ is a collection of charts.
** ? Converting polar coordinate tuples to rectangular coordinate tuples
Both the rectangular coordinate $(r\cos\theta, r\sin\theta)$ and the polar coordinate $(r,\theta)$
describe the same point in two-dimensional Euclidean space.
\[
R(r\cos\theta, r\sin\theta) = P(r,\theta)
\]

A point in a space can have different coordinates in different coordinate systems.
* Operators
It amazes me that the formal power series of \((1+\Der)^{-1}\) works.
Penrose 2006 \cite{penrose2006road} attributes it to Oliver Heaviside.

In quantum mechanics, why do bother calling a matrix an "operator"?
* ? Mechanics
** ? Deriving the concept of momentum
To get a taste of a principled approach, let us exercise by deriving "momentum".
(See also [[http://www.cleonis.nl/physics/phys256/quantity_of_motion.php][Teunissen 2017]].)

We define "momentum" as having "amount of motion" and "direction of motion",
so it is a vector.

We expect that the direction of motion coincides with the direction of velocity.

Suppose that \(f(m,v)\) is a vector that is the momentum of a point mass \(m\) with velocity \(v\).

We expect that changing the direction of motion does not change the amount of motion.
Thus, if \(R\) is a rotation, then
\[ f(m,Rv) = Rf(m,v) \]

We observe that a body colliding with an immovable wall changes its direction of motion but not its amount of motion:

\[ f(m,-v) = -f(m,v) \]

???

We assume that two colliding bodies preserve the total amount of motion:

\[ f(m_1,v_1) + f(m_2,v_2) = f(m_1,v_1') + f(m_2,v_2') \]

???

??? We expect that an object's amount of motion is linearly proportional to its mass (its amount of matter).

\begin{align*}
f(cm,v) &= c f(m,v)
\\ f(m_1+m_2,v) &= f(m_1,v) + f(m_2,v)
\end{align*}

One possibility is \( f(m,v) = mv \), but is that the only possibility?

Infer that \( f(m,v) = m v \).

???

Let \([Nx](t) = x(-t)\).

Both \((m_1,x_1,m_2,x_2)\) and \((m_1,Nx_1,m_2,Nx_2)\) describe the same collision.
If we reverse the time, we will see the same collision.

** ? special fields, conservative forces, potential energy
Let \( \hat{x} \) mean \( \vec{x} / \norm{x} \).

A time-invariant vector field \(F\) is [[https://en.wikipedia.org/wiki/Central_force][central]] iff \( F(\vec{x}) = F(x) \cdot \hat{x} \),
where \(\vec{x}\) is the displacement from the /center/ of the field.
The strength of a central field at \(x\) depends only on the distance between \(x\) and the center of the field.

A force is /conservative/ iff it conserves the mechanical energy of the object it acts upon.
What is the importance of the fact that the work done by a conservative force does not depend on path?

Consider a spring and a mass.
Pull the spring, and release it.
Why is the sum of potential energy and kinetic energy conserved?
** ? "F = ma" implies "W = ΔK": Work is equal to the change in kinetic energy
Here we show that \( F = m \vec{a} \) implies \( W = \Dif K \).

(What is the importance of this insight?)

Suppose that a force \( \vec{F} \) is acting on an object of mass \(m\)
at initial position \(\vec{x}\) and initial velocity \(\vec{v}\).
By initial, we mean at time zero.

The object's velocity at time \(t\) is \(\vec{v}' = \vec{v} + \vec{a} t\).

The object's position at time \(t\) is \(\vec{x}' = \vec{x} + \vec{v} t + \vec{a} t^2 / 2\).

Recall that \( \vec{F} = m \vec{a} \) and \( \vec{a} \cdot \vec{a} = a^2 \).

The work done by the force on the object is
\begin{align*}
W &= \vec{F} \cdot (\vec{x}' - \vec{x})
\\ &= m\vec{a} \cdot (\vec{v} t + \vec{a} t^2 / 2)
\\ &= mt \vec{a} \cdot \vec{v} + ma^2t^2/2
\end{align*}

The object's initial kinetic energy is \(K = mv^2/2\).

The object's kinetic energy at time \(t\) is
\begin{align*}
K' &= m \norm{\vec{v} + \vec{a}t}^2/2
\\ &= mv^2/2 + mt \vec{v} \cdot \vec{a} + ma^2t^2/2
\end{align*}

Therefore the change in kinetic energy is
\begin{align*}
\Dif K &= K' - K = mt \vec{v} \cdot \vec{a} + ma^2t^2/2
\end{align*}

Observe that \(W\) and \(\Dif K\) are equal.
Recall that the dot product is commutative: \( \vec{a} \cdot \vec{v} = \vec{v} \cdot \vec{a} \).
\begin{align*}
W &= mt \vec{a} \cdot \vec{v} + ma^2t^2/2
\\ \Dif K &= mt \vec{v} \cdot \vec{a} + ma^2t^2/2
\end{align*}

Therefore, the work done by a force on an object is equal to the change in that object's kinetic energy.
\[ W = \Dif K \]

???

Now suppose that the time elapsed is infinitesimal \( \dif t \).

???

Power \(W'\) is rate of work?

\[
\int_{t_1}^{t_2} W'(t) ~ \dif t = K(t_2) - K(t_1)
\]
** ? The surprising mechanical advantage of movable pulleys
It is surprising that a movable pulley has a [[https://en.wikipedia.org/wiki/Mechanical_advantage][mechanical advantage]] of 2.
The magic is in the string tension.
This is one among [[https://www.reddit.com/r/Physics/comments/3qxnog/what_are_some_of_the_most_counterintuitive/][many]]
cases where habit fails us.

Engineering idea:
We can use \(n\) ropes with a movable pulley attached to a weight \(F\),
and ask \(n\) people to pull the free ends of the ropes,
and each person will only need to exert a force of \(F/(2n)\) to balance the weight.
However, the people exert unequal forces, tilting the weight.
* Variational principles
Prerequisites: line integrals (see [[file:integral.html]]).
** ? Predictions, explanations, how to make principles
Think backwards?

Example:
Newton's laws /predict/: given masses and positions (inputs), Newton's laws give the trajectories.
Principle of stationary action /explains/: given a trajectory (an observed reality), find the properties of the trajectory?
** Variational principles
[[https://en.wikipedia.org/wiki/Variational_principle][Examples]] of variational principles:
[[https://en.wikipedia.org/wiki/Maupertuis%27s_principle][Maupertuis's principle]].

Prediction: Given \(x\) and \(f\), compute \(f(x)\).

Explanation: Given \(x\) and \(f(x)\), compute the properties of \(f\).

? A /variational principle/ is a /constraint/ on trajectories.
** Discrete variational principles?
Example candidates?
- The sequence of actions of a lazy agent is that which minimizes the total effort.
- The sequence of actions of an adaptive agent is that which minimizes the total surprise.
- The sequence of actions of an agent is that which maximizes its utility function.
** ? Example: hills
For example problems, see [[https://en.wikipedia.org/wiki/Calculus_of_variations][Wikipedia]].

Let \( z : \Real^2 \to \Real \) be a height map.

Let P and Q be two known points.

A man wants to go from P to Q, but there are hills between them.

Suppose that he does not care about time, and he wants the least effort,
where the total effort to move from \(x\) to \(y\) is \(h(y) - h(x)\).

Suppose the path is \(p:\Real\to\Real^2\).

The path's total effort is \(E(p(t_k))\).
** ? Other principles
** Trajectory
A /path/ is a one-dimensional geometric object, usually smooth.

A /[[https://en.wikipedia.org/wiki/Path_(topology)][path]] in space \(X\)/ is a function \( [0,1] \to X \).

A /[[https://en.wikipedia.org/wiki/Trajectory][trajectory]]/ (in space \(X\)) is a function \( T \to X \)
whose domain \(T\) is a [[https://en.wikipedia.org/wiki/Interval_(mathematics)][real interval]]
that represents an interval of time and whose codomain represents physical space.

A trajectory can be thought of as a path in spacetime.

A trajectory \(x\) means "At time \(t\), the object of interest is at position \(x(t)\)".
** Minimum
Let \(f:D\to C\) be a function.

The /range/ of \(f\) is the set \(\SetBuilder{f(x)}{x \in D}\).

A /[[https://en.wikipedia.org/wiki/Partially_ordered_set][poset]]/ (partially ordered set) is a set and a partial order.

A /minimum/ of a poset \((S,\le)\) is an \(x\in S\) such that \(x \le y\) for all \(y \in S\).

A /minimum/ of \(f\) is a minimum of the range of \(f\).
** Problem
A /problem/ \(p\) is a question (a logical predicate).

An /answer/ to problem \(p\) is an \(x\) that satisfies \(p(x)\) (such that \(p(x)\) is true).

An /[[https://en.wikipedia.org/wiki/Mathematical_optimization][optimization]] problem/ is the problem of finding a minimum of \(f\) subject to some constraints.
For example: Find an \(x \in \Real\) such that \(x \le 0\) and \(x^2-1\) is minimal.


** Example: pre-variational-calculus: the path traversed by light
Let \(p\) be a path traversed by light.

Let \(v\) be the light's speed field.

The question: How much time does light take to traverse that path?

The time light takes to move from \(q\) to \(q+\dif q\) is \( \dif t(q) \) such that
\[ v(q) ~ \dif t(q) = \dif q \]

The time light takes to move from \(p(q)\) to \(p(q+\dif q)\) is \( \dif t(q) \) such that
\[ v(p(q)) ~ \dif t(q) = p(q+\dif q) - p(q) \]

Divide both sides by \(v(p(q)) ~ \dif q\):
\begin{align*}
\frac{\dif t(q)}{\dif q} &= \frac{1}{v(p(q))} ~ \frac{p(q+\dif q) - p(q)}{\dif q}
\\ \dot{t}(q) &= \frac{1}{v(p(q))} ~ \dot{p}(q)
\end{align*}

Integrate both sides with respect to \(q\):
\begin{align*}
\int_0^1 v(p(q)) ~ \dot{t}(q) ~ \dif q &= \int_0^1 \dot{p}(q) ~ \dif q
\end{align*}

???

In virtual time span \(\dif u\), light has traversed \( v(p(u))~\dif u \).

(Isn't this just arc length?
 [fn::<2019-12-28> https://en.wikipedia.org/wiki/Fermat%27s_principle#Modern_version]
 [fn::<2019-12-28> https://en.wikipedia.org/wiki/Differentiable_curve#arc-length_parametrization])

Divide the path into \(n\) subpaths:
\[ p_k = p(u_{k+1}) - p(u_k) \]

The time light takes to traverse the subpath \(p_k\) is:
\[ t_k = \norm{p_k} / v_k \]

Thus the total time is:
\[ \lim_{n\to\infty} \sum_k t_k \]

Let \(\dif p(k)\) be the infinitesimal subpath \(p(k+\dif k) - p(k)\).

The time light takes to traverse \(\dif p(k)\)
is \(\dif t(k)\) such that
\[
\norm{\dif p(k)} = v(p(k)) ~ \dif t(k)
\]

The time light takes to traverse \(p\) is
\begin{align*}
\int_0^1 \dif t(k) ~ \dif k
&= \int_0^1 \frac{\norm{\dif p(k)}}{v(p(k))} ~ \dif k
\\ &= \int_0^1 \frac{\norm{\dif p(k)}}{v(p(k))} ~ \dif k
\end{align*}
** Fermat's principle
[[https://en.wikipedia.org/wiki/Fermat%27s_principle][Fermat's principle]] (of least time) is:
If light traverses the path AP with velocity v1 and the path PB with velocity v2,
then light traverses APB in the least amount of time;
that is, there is no other P' such that t(AP'B) < t(APB).

Fermat's principle unifies reflection and refraction (Snell's law).[fn::<2019-12-28> http://electron6.phys.utk.edu/optics421/modules/m1/Fermat's%20principle.htm]

To approximate /point source/, /enclose/ an ordinary light source (such as a fire, torch, candle, or lamp)
with a solid opaque container with a small aperture.

? How did Fermat think that light travels with different speeds in different mediums?

In his time (1607--1665),
light was thought to be ...[fn::<2019-12-28> https://en.wikipedia.org/wiki/Light#Historical_theories_about_light,_in_chronological_order],
the speed of light had not been known[fn::<2019-12-28> https://en.wikipedia.org/wiki/Speed_of_light#History],
but the wave theory of light was being invented.

/But how can that principle be used to compute B from A and P?/

How do we test the principle of stationary action?
** Hamilton's principle
Hamilton's principle unifies the motion of light and the motion of matter?
* Continuum mechanics
** ? From Newtonian mechanics to continuum mechanics
The first step is to replace the fictional concept of "point mass" with the less fictional concept of "mass density".

\( \rho : \Real^3 \to \Real \)

\[ m = \int_V \rho(x) ~ \dif x \]

What do Newton's laws of motion become?

What do the variational principles become?
** ? Self-gravitation
(Newtonian) gravitational field of a fluid or a non-point mass?

https://en.wikipedia.org/wiki/Newton%27s_law_of_universal_gravitation#Bodies_with_spatial_extent

Let \( \rho(x,t) \) be the mass density at point \(x\) at time \(t\).

The gravitational field at point \(x\) at time \(t\) is
\begin{align*}
g(x,t) &= \int_{X - \Set{x}} - G ~ \rho(v^*,t) ~ \frac{x-v^*}{\norm{x-v^*}^3} ~ \dif v
\end{align*}

Should we have used Gauss's law instead of Newton's?
Gauss's law for gravity is more general than Newton's, because
"Gauss's law for gravity can be derived from Newton's law of universal gravitation"
but "It is impossible to mathematically prove Newton's law from Gauss's law /alone/"?
 [fn::<2019-12-28> https://en.wikipedia.org/wiki/Gauss%27s_law_for_gravity]

The resultant force acting at point \(x^*\) at time \(t\) is
\begin{align*}
F(x^*,t) &= m(x^*,t) ~ g(x,t)
\end{align*}

TODO: Learn some continuum mechanics first.

https://en.wikipedia.org/wiki/Momentum#In_deformable_bodies_and_fluids

https://en.wikipedia.org/wiki/Cauchy_momentum_equation

? The momentum of a volume \(x\) at time \(t\) is
\[ p(x,t) = \rho(x^*,t) ~ v(x,t) \]

We are interested in the time-evolution of \(\rho\).

What are the criteria for the solution?

We want the solution to conserve the total mass:
\[
\int_X \rho(x^*,t) ~ \dif x = m
\]
where \(m\) is a constant.
Thus the total mass is conserved (does not change over time).
* Waves
The [[https://en.wikipedia.org/wiki/Wave_equation][wave equation]] can be derived from Newton's laws of motion?

The second-order differential equation of an oscillating spring can be derived from Newton's laws of motion.
** Waves in steady state
A /waveform/ \(f\) is a function, usually periodic.

A /wave/ \(w\) is a waveform traveling/propagating with velocity \(v\).

The relationship between a wave and its waveform:

\[ w(x,t) = f(x - vt) \]

A wave has /wavelength/ \( |\lambda| \) iff \( \lambda \) is a shortest vector such that \(f(x+\lambda,t) = f(x,t)\) for all \( t \).

A wave has /period/ \( T \) iff \( T \) is the smallest positive number such that \(f(x,t+T) = f(x,t)\) for all \( x \).

That is, wavelength is spatial periodicity, and period is temporal periodicity.

The wavelength of a wave is the period of its waveform.
** Traveling waveform
Let \( i : \Real^3 \to \Real \) be the shape of the disturbance.

Suppose that the disturbance is traveling with velocity \(v\).

Let \(f(x,t)\) be the displacement/disturbance/amplitude in the propagation medium at point \(x\) at time \(t\).

Initially the impulse is at the origin:
\[ f(x,0) = i(x) \]

After time \(t\) elapses, the impulse has moved in space by \(v t\).
\[ f(x+vt,t) = i(x) \]

Rearrange:
\[ f(x,t) = i(x-vt) \]
** Radially traveling disturbance
Let \( s(t) \) be the amplitude of the source oscillation at time \(t\).

The oscillation happens at the origin.

The disturbance propagates out radially with speed \(v\).

Assume isotropy and homogeneity of medium?

After time h, what was at (x,t) is at (x+hv,t+h)?

Thus f(x,t) = ... ?

Wave propagation velocity?

f(x - v t, t + Dif t) = f(x,t) ?
** Modeling transverse waves or surface waves?
A wave is represented by a function

f : Position × Time → Amplitude

The interpretation is: "At time \(t\), the amplitude at point \(x\) is \(f(x,t)\)".

Amplitude is displacement from resting position.

That is, a wave is often represented as an /amplitude field/.
(In mathematical physics, an "X field" is a function from position to X.)

Example phenomena that can be represented by periodic functions:
the motion of a pendulum,
the surface waves of water in a pond,
the oscillation of a guitar string.

In steady-state modeling, the wave is extrapolated to infinity in both space and time.
For example, when modeling a pond, we often assume that the pond is infinite, it has no edges, and waves do not reflect off the edges.
We assume that wave propagate freely without hitting any obstacles, without reflection, without diffraction.
Thus we can define wavelength and period:
* Digression: An example of a circle in differential geometry?
Curious:

\begin{align*}
x^2 + y^2 &= r^2
\\ (x + \Dif x)^2 + (y + \Dif y)^2 &= r^2
\end{align*}

Subtract both equations, and change \( \Dif \) to \( \dif \), with non-standard analysis.
What do we get?

...

But that is only a circle in a space with /Euclidean metric/.

In synthetic geometry, a circle with center \(c\) and radius \(r\) is
\( \SetBuilder{x}{d(c,x) = r}\), that is, the set of all points \(x\) such that the distance between the center and \(x\) is the radius.

Synthetic geometry is more abstract/general.
For example, a square is a circle in a space with taxicab metric.

Is a circle about the shape, or about the equidistance of points?
* Bibliography
