#+TITLE: Be remembered forever
#+DATE: 2019-04-22 00:00:00 +0700
#+PERMALINK: /plan.h<tml
#+OPTIONS: ^:nil
If we cannot live forever, we can still be immortal by being remembered forever,
leaving our legacy in history, for big impacts, whether good or bad.
* <2019-05-08> Which comes first: wealth or impact?
Both seems possible:
- Impact causes wealth, when you sell highly-demanded things.
- Wealth causes impact, when you are born to rich parents.

However:
- If you are rich but useless, then you will eventually be poor.
- If you are useful but unlucky, then you will still be poor.

Making impact requires /some/ wealth.
Having more wealth enables you to make an even bigger impact which begets even more wealth.

There are several way for someone in the middle class to rise into the upper class:
- unreliable
  - get lucky: win the lottery, marry a rich person, etc.
  - steal: break into houses, etc.
- somewhat reliable
  - extract: go into the financial sector, commit usury, rent, etc.
  - create
    - sell some high-profit things
    - sell a lot of low-profit things

What is the relationship between
the cycle of wealth[fn::http://www.oxfordplace.com/advising-families/cycle-of-wealth/]
and the cycle of poverty[fn::https://en.wikipedia.org/wiki/Cycle_of_poverty]?
* Get the resources required to make some impacts
** Get more power
Power gives us ideas for making impact.
With power, some actions that were unthinkable are now obvious.

If you want to change the world but you don't know how,
the answer is /power/.

[[file:power.html][Understand power]].

Get more physical power: Exercise.
*** [[file:rich.html][Get rich quickly without going to jail]].
<2019-04-22>
I think the most feasible way for me to get power is to get rich,
because I don't like war and I don't like lying.
*** Learn rhetorics, public speaking, and how to convince people
** Increase the efficiency of research and thinking
- [[file:meta.html][Meta-research]]: meta-thinking
  - [[file:language.html][Language Research Group]]
  - [[file:writing.html][Writing]]
- [[file:publish.html][Make a system for publishing this website]]
  - [[file:parse.html][Find an elegant parsing method]]
    - I am looking for the best technique for specifying formal grammars, parsing formal languages, and unparsing formal languages.
      Parsing is the common thing between programming language and publishing system, and I want both.
    - [[file:division.html][Generalizing division]]: Brzozowski quotient and set division
  - Write a Prolog DCG for a declarative subset of LaTeX
  - Write a Prolog DCG for Org Mode
  - Write a Prolog program for generating sitemap.xml
- Speed up human research
  - Kill all people who do not believe in science?
  - Kill all people who are against eugenics?
  - The only necessary ethics for a scientist is to be honest and to avoid harming others.
    All others "ethics" is irrational feelings.
    - "Patients died unnecessarily while we waited for this trial to be approved."[fn::https://www.badscience.net/2011/03/when-ethics-committees-kill/]
  - Make everyone understand English, or eliminate all human languages but English (this is pragmatism, not imperialism)
- [[file:browser.html][Make our own web browser]]
- [[file:usecom.html][Use computers]]
  - Leo Editor[fn::http://leoeditor.com]: personal information manager + integrated development environment;
    via akkartik.name[fn::http://akkartik.name/post/literate-programming]
- [[file:phone.html][Buy a smartphone]], when the old smartphone becomes unusable
* Make some impacts
** Make society more fair and just
Is fairness even definable?
Do we need fairness?
Don't we only need to reduce suffering?

*Do poor people see their poverty as a problem?*
If they didn't, why did we see it as a problem?
Are we just being condescending?

The problem with trying to change the world is that /it resists/.
To overcome that resistance, we need /power/.
But how are we going to distribute power,
if doing so requires us to first accumulate power to wrest power from where they are centralized now?
That means war, that is a great power's challenging a hegemony.
But we don't want war.
It is like "To feel better, we must first feel worse."
But this makes sense.

Thus there is this dilemma:
Power corrupts, but power distribution promotes war;
what about power distribution without government in a global anarcho-syndicalist society?
Why does a great power challenge a hegemony?
Is it like two dogs fighting for territory?
It is the same as dog fights, only with much bigger scale.
Are we territorial?
But all dog fights eventually end,
all wars eventually end,
and peace is eventually reached?

- [[file:social.html][Decentralize political power]]
  - We may not want to decentralize power
    because war is more likely to happen without power imbalance[fn::https://en.wikipedia.org/wiki/Power_transition_theory].
    That is, power imbalance is a necessary evil to keep peace.
    But would we rather live in a mostly peaceful state of subjugation,
    or would we rather live in a free but unfamiliar state of anarchy?
  - [[file:moral.html][Morality]]:
    codify our natural morality, that is,
    the implicit moral system that we have evolved;
    but I doubt that people have the same natural morality,
    in the same way dogs have different aggression tendencies.
  - [[file:tech.html][Techno-Anarchy Research Group]]
  - Replace retributive justice with restorative justice
- Educate refugees and temporarily employ them; change the law
  - But this may incentivize war to increase the number of refugees and cheap labor?
** Create a timeless piece of art
Create music like Bach, Mozart, Beethoven, or what?
** Solve the P vs NP problem?
- [[file:pnptry.html][Solve the P vs NP problem]]: a dream
  - [[file:compute.html][Computing Research Group]]: define computation
    - [[file:logic.html][Logic]]?
      Should we rewrite this article from theory-oriented to programming-oriented?
** Counterproductive countercurrent desires, morbid curiosities, destruction, escapism, boredom avoidance, and the dark side?
*** Avoid getting bored?
- [[file:game.html][Gaming]]: play games, make games
  - [[file:ps1.html][Reverse-engineering PlayStation 1 3D games to control the camera]]
- [[file:art.html][Art Research Group]]
- [[file:music.html][Music Research Group]]
*** Think about insane things
**** Use Prolog for low-level programming
- Write an operating system in Prolog
  - Reuse Linux kernel
  - Reuse the House operating system[fn::https://en.wikipedia.org/wiki/House_(operating_system)]?
  - Write applications in Prolog plus program checking like Singularity OS[fn::https://en.wikipedia.org/wiki/Singularity_(operating_system)]
    that uses software type safety instead of hardware memory protection;
    but there are lots of similar projects already?
  - Dynamic and inspectable like Temple OS Holy C
- Make a C compiler in Prolog
- Make something like LLVM IR in Prolog
- Make an x86-64 assembler in Prolog
- Make an ELF linker in Prolog
**** Giants pet naked humans like humans pet cats
Head stroking, belly tickling, obsessive cuddling, and all the annoyances, abuses, intrusions, and privacy violations.
**** There have been robotic animals; where are the robotic humans?
In 2019 it seems to be a trend for humans to place robotic animals in the middle of real animals.
Robotic spy African wild dog.
Robotic spy tortoise.
Robotic squirrel.
Robotic spy penguin.

What if super-intelligent aliens have been placing robotic humans in the middle of real humans?
Maybe strange people are just philosophical zombies dropped into the middle of us by aliens,
for research, or for shits and giggles, as we sometimes cruelly do to animals.
**** Destroy things; but this urge conflicts with the desire to preserve ourselves?
- Establish global hive mind, monoculture homogenous cooperative anarchist/liberal society in a post-scarcity economy;
  but perhaps we should stop trying to change the world?
  - Kill all humans, or massively reduce world population, quickly
    [fn::https://www.psychologytoday.com/us/blog/the-new-brain/201610/humans-are-genetically-predisposed-kill-each-other]
    - Nanobot, anthrax, ebola, mass sterilization, a mechanical-biological agent
      that passes through the pores or holes in the human body, or viruses delivered by drones
    - Reversibly sterilize every newborn,
      and make them earn their right to procreate when they are adults
    - Require license for procreation;
      establish minimum standard for parents
    - Ban the teaching of religion to minors
  - Gather everyone who agrees; kill everyone who disagrees
  - But wouldn't we be just as barbaric as terrorists like ISIS if we did those?
  - Bring about a catastrophic disaster obliterating unplannedly-grown cities like Jakarta
    so that they can be rebuilt from scratch with proper urban planning
  - [[file:other.html][Unimportant content]]: utter mess
* To-do
I should merge [[file:goal.html][Goals]] into this page.
