#+TITLE: Political goals
#+DATE: 2017-06-26 02:00 +0700
#+PERMALINK: /politics.html

* Catatan: semua ini baru ide; masih bisa berubah.
** Ini apa?
Halaman ini berisi campuran beberapa hal:

- cita-cita/rencana untuk Indonesia
- riset/pembelajaran secara umum, terutama yang berkaitan dengan politik, ekonomi, sosial
- urusan yang ada kaitannya dengan pemerintah/negara
** Apa masalah terbesar Indonesia? Apa akar masalahnya?
- https://www.galena.co.id/q/apa-masalah-terbesar-di-indonesia

Analyze causal chain.

Apa yang tampak (kenyataan di lapangan)?
Apa sebab langsungnya?
Apa sebabnya?
Apa sebabnya lagi?
Dan seterusnya.

- Wealth gap / kesenjangan ekonomi / severe inequality.
  Mana yang lebih penting: mengurangi wealth gap, atau memperbaiki worst case kehidupan?
* Obtain personal/group sovereignty by securing the ability to live by depending only on nature
** Why
Those who can survive on their own have power over those who can't.

Everyone needs food.
Those who control food control the society.

You can always sell food (convert food into money).
The inverse isn't always true: you can't always buy food (convert money into food).

Nature accepts labor as payment.
Nature doesn't accept money.

Nature feeds those who work.
** <2018-09-28> Establish low-operation permaculture.
*** TODO Feasibility study
**** Typical Indonesian mainstream agriculture crop yields in tons per hectare-year
***** TODO OECD-FAO data https://data.oecd.org/agroutput/crop-production.htm
- https://en.wikipedia.org/wiki/Crop_yield
**** TODO Crop yields: permaculture vs mainstream
- https://grist.org/food/do-industrial-agricultural-methods-actually-yield-more-food-per-acre-than-organic-ones/
*** What
- low operational cost
- no pesticide, no manmade chemicals necessary
- ecological engineering https://en.wikipedia.org/wiki/Ecological_engineering
- https://en.wikipedia.org/wiki/Ecosystem_engineer#Humans_as_ecosystem_engineers

Permaculture: weed ecology
Ecology engineering
Ecology vs ecosystem?
https://articles.extension.org/pages/18529/an-ecological-understanding-of-weeds

China reverse desertification video:
[[https://www.youtube.com/watch?v=jkdxObsCVGY][Watch This New Technology in China That Converts Desert Into Productive Land Rich With Crops - YouTube]]

Kemandirian.
Self-reliance.
Independence.
No money, but lots of assets.

- Buy a land.
- Establish permaculture/do-nothing-farming.

[[http://peta.bpn.go.id/][Peta nilai tanah BPN]]

- Permaculture (Do-nothing farming)
    - http://www.backyardabundance.org/AbundantLandscapes/WetherbyEdibleForest.aspx
    - http://tcpermaculture.com/site/2016/03/01/permaculture-basics-edible-forest-gardens/
    - https://www.permaculture.co.uk/articles/permaculture-growing-arctic
- Mouse trap
    - https://www.youtube.com/watch?v=6SIlYiiCGLI cylinder rod, bucket, detergent, mouse trap
    - https://www.youtube.com/watch?v=cNWJIkjOupg water is more humane because otherwise the mice would kill each other
- [[https://www.youtube.com/watch?v=IWChH9MHkHg]] raising chickens with compost instead of grain
*** Shitology (What is the formal name?)
**** What is the nutritional value of our shit?
**** How do we recycle our shit? How do we return our shit to nature, so that plants can take it up, but without contaminating our drinking water?
* <2018-09-26> Ganti /retributive justice/ dengan /restorative justice/.

** Ideas and principles

Punishment is replaced with compensation.

The state /mediates/ (facilitates dialog between) the perpetrator and the victim.
The judge, perpetrator, and victim negotiate the compensation.
It can be money, labor, anything.

Imprisonment is reserved only for the unchangeable criminals.

** Problem: Philosophical issues, definitions

A judge is to establish justice.
What is justice?
What is fairness?

Which do we judge: the person himself, or his deeds?
To judge a person is to opine (to form an opinion) about that person, but on what basis, according to which rules?

What do judges do?
What are judges supposed to do, according to the political systems our ancestors designed?

What is the history of judges?
How did judges come into being?

Jown Rawlins's veil-of-ignorance idea:
We know that a society is /just/, if we don't mind being born in that society
without being able to choose who we are going to be born as.

What is a just society for disabled people?

It is not his fault that he was born disabled.

Justice requires blame (assigning/attributing faults to people).

** Problem: What do judges do then, if their daily tasks are given to the mediators?

- https://www.sokanu.com/careers/judge/
- https://www.nolo.com/legal-encyclopedia/what-judges-actually.html
- https://en.wikipedia.org/wiki/Judge

** Kesulitan

- Berapa besar usaha yang diperlukan untuk mengubah sistem hukum yang sekarang?
- Bagaimana rencana transisi?
- Bagaimana memastikan sistem tidak disalahgunakan?
- Bagaimana meminimalkan kerusakan yang mungkin ditimbulkan hakim yang salah?

** Rencana?

- Siapa yang berwenang mengubah sistem hukum indonesia menjadi restorative justice?
- Bagaimana melobi pihak berwenang?

* <2018-10-02> Ajar cara berpikir di sekolah
Unfortunately the brain doesn't come with an instruction manual.
** Interpret human language using probabilistic logic, not classical logic; every adjective is continuous, not binary
Degree of truth is continuous, not binary.
** Distinguish between facts and opinions
** Think for yourself
** Eat healthily
** Objective reality, wishful thinking
** Self-awareness of one's own thoughts
** Justifying actions; requiring reasons for things; asking why; goal-directed behavior
* Establish low-operational-cost power generation and transportation: solar power plants and sun-powered trucks.

Kita harus lepas dari pengaruh geopolitik minyak bumi supaya kita tidak terpengaruh pertengkaran negara lain.

Komponen termahal biaya operasional transportasi jarak jauh adalah bahan bakar fosil.

- <2018-09-29>
  - https://www.theguardian.com/business/2018/may/17/what-are-the-factors-driving-up-the-price-of-crude-oil
  - https://www.thehindu.com/business/Economy/why-are-crude-oil-prices-going-up/article23937146.ece
  - "Saudi Arabia Promised More Oil. So Why Are Prices Rising?" https://www.nytimes.com/2018/07/04/business/energy-environment/oil-prices-opec.html
  - https://www.thebalance.com/what-makes-oil-prices-so-high-3305654
  - https://now.tufts.edu/articles/why-price-oil-rising
  - https://www.quora.com/Gasoline-How-long-does-it-take-for-the-change-in-crude-oil-price-to-reach-end-consumers
    - My conclusion: Prices are quick to rise and slow to fall.
    - https://www.aol.com/2011/03/18/why-gas-prices-rise-quickly-but-fall-slowly/
    - https://www.telegraph.co.uk/finance/personalfinance/energy-bills/11044279/The-oil-price-puzzle-prices-are-quick-to-rise-but-slow-to-fall.html
  - https://oilprice.com/Energy/Energy-General/Why-Oil-Prices-Are-Surging.html

* Basmi politik identitas; mulai desegregasi; basmi partisanisme; basmi tribal politics

- How Congress (and America) became so polarized - Jonathan Haidt https://www.youtube.com/watch?v=RhoGx7bTzko
  - Newt Gingrich started tribalism in the Republican party.

* Sederhanakan hukum

You know your legal system is too complex when people can profit from that complexity.

* <2018-09-19> Tertibkan pelacuran, narkoba, dan judi?

Kita jangan munafik.
Hal-hal ini sudah ada sejak manusia ada.
Hal-hal ini tidak bisa dihilangkan.

Solusinya adalah mendidik masyarakat, bukan melarang.
Larangan hanya akan membuat black market.

Laws can't go against human nature.

Masalah: NIMBY.
Mau dilokalisasi di mana?
Tentu di tempat yang sudah ada.
Resmikan tempat yang sudah ada.

Jual narkoba di alfamart/warung?
Atur kemasan harus sama semua.
Tidak boleh iklan.

Perlu update [[http://spkonline.bps.go.id/spkonline/help/klasifikasi/2][KBLI]] (Klasifikasi Baku Lapangan Usaha Indonesia).

https://www.straitstimes.com/asia/se-asia/malaysia-in-talks-to-become-first-in-asia-to-allow-medical-pot

* <2018-09-19> Perbaiki sistem hukum

** Prinsip hukum

*** A law must not go against nature.

Banning prostitution does not respect nature.
Banning drugs does not respect nature.

*** A law must be practically enforceable.

Cabut semua aturan yang enforcement-nya tidak praktikal.

*** Regulate; don't ban.

** <2018-09-19> Perjelas bagian UUD yang tidak jelas.

*** Naskah
   :PROPERTIES:
   :CUSTOM_ID: naskah
   :END:

- 2018-09-01: [[http://www.dpr.go.id/jdih/uu1945][UUD 1945]] (perubahan keberapa?)
- [[https://ngada.org/uud01-1945pjl.htm][Penjelasan UUD 1945 (naskah asli tanpa amandemen)]]
  (itu website apa?)

*** Cara mengubah UUD
   :PROPERTIES:
   :CUSTOM_ID: cara-mengubah-uud
   :END:

- Lihat pasal 37.
  Wewenang MPR.
- Pasal 37 ayat 5: "Khusus mengenai bentuk Negara Kesatuan Republik Indonesia tidak dapat dilakukan perubahan."
- Pasal 1 ayat 3: "Negara Indonesia adalah negara hukum."

*** Pemilu partai vs pemilu langsung?
   :PROPERTIES:
   :CUSTOM_ID: pemilu-partai-vs-pemilu-langsung
   :END:

- Pasal 22E ayat 3: "Peserta pemilihan umum untuk memilih anggota Dewan Perwakilan Rakyat dan anggota Dewan Perwakilan Rakyat Daerah adalah partai politik."

  - Mengapa partai?

    - Menyederhanakan pemilu.
    - Perkumpulan orang-orang setujuan?

  - Keburukan partai

    - Kebutuhan memenangkan suara membuat partai berpolitik praktis dan meninggalkan tujuannya?
    - [[https://tirto.id/corak-ideologi-partai-partai-di-indonesia-cJKc][Corak Ideologi Partai-Partai di Indonesia - Tirto.ID]]

      - Pertai di Indonesia hanya beda pendapat soal agama.
        Sisanya sama semua.
        Kurang variasi.
        Groupthink.

  - Partai berarti "bagian".

*** Pasal-pasal yang perlu dijelaskan
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-perlu-dijelaskan
   :END:

Pasal-pasal ini bertujuan mulia, tetapi kata-katanya tidak jelas secara hukum, sehingga tidak bisa ditegakkan.

- Pasal 27 ayat 1:
  "Segala warga negara bersamaan kedudukannya di dalam hukum dan pemerintahan dan wajib menjunjung hukum dan pemerintahan itu dengan tidak ada kecualinya."

  - Pasal tersebut tidak cocok menjadi hukum.
    Ia bukan definisi ataupun aturan, melainkan harapan.
  - Tidak ada cara untuk menjalankan pasal tersebut.
  - Tidak ada hukuman yang jelas untuk pelanggarannya.
    (Aturan tanpa hukuman sama saja tidak ada.)
  - Aturan yang sulit di-enforce sama saja tidak ada.
  - Diskriminasi adalah bagian manusia dan akan ada selama manusia ada.

- Pasal 27 ayat 3:
  "Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara."

  - Apa beda "berhak dan wajib" dan "wajib"?
  - Apa hukuman untuk pelanggarnya?
  - Apa arti kata "berhak"?
  - Bagaimana cara mengklaim suatu hak?

- Pasal 29 ayat 1: "Negara berdasar atas Ketuhanan Yang Maha Esa."

  - Apa arti kata "esa"?

    - Menurut [[https://kbbi.web.id/esa][KBBI daring]], kata "esa" berarti "satu".
      Tapi sumber ini kurang kuat.
      Bisa saja di-hack.
    - [[https://balebengong.id/kabar/melacak-asal-kata-esa-dalam-pancasila.html?lang=id][Melacak asal Kata Esa dalam Pancasila - BaleBengong]]
    - Pendapat ahli bahasa Indonesia

      - https://twitter.com/eggggsie/status/990073630653476864
      - https://twitter.com/harimbawa/status/989232636274008064
      - [[https://en.wiktionary.org/wiki/wish#Etymology][Wiktionary tidak sependapat soal asal usul kata "wish"]]

    - Perkelahian gara-gara kata "esa"

      - https://twitter.com/Mentimoen/status/946237996327686144
      - [[https://tirto.id/sejarawan-eggi-sudjana-ahistoris-dan-tak-paham-konsep-esa-cxVS][Sejarawan: Eggi Sudjana Ahistoris dan Tak Paham Konsep Esa - Tirto.ID]]

  - Sebaiknya kita ganti pasal tersebut dengan kata-kata yang umum di abad 21.
    Aturan harusnya dibuat supaya mudah dipahami.

- Pasal 31

  - Pasal 31 ayat 2: "Setiap warga negara wajib mengikuti pendidikan dasar dan pemerintah wajib membiayainya."
  - Pasal 31 ayat 4: "Negara memprioritaskan anggaran pendidikan sekurang-kurangnya dua puluh persen dari anggaran pendapatan dan belanja negara serta dari anggaran pendapatan dan belanja daerah untuk memenuhi kebutuhan penyelenggaraan pendidikan nasional."
  - Apa itu artinya sekolah harus digratiskan?
    Seandainya APBN tidak cukup bagaimana?
  - Pasal 31 ayat 3: "Pemerintah mengusahakan dan menyelenggarakan satu sistem pendidikan nasional, yang meningkatkan keimanan dan ketakwaan serta ahlak mulia dalam rangka mencerdaskan kehidupan bangsa, yang diatur dengan undang-undang."

    - Ini mungkin harus diubah supaya mengikutkan "toleransi".

- Pasal 32 ayat 1: "Negara memajukan kebudayaan nasional Indonesia di tengah peradaban dunia dengan menjamin kebebasan masyarakat dalam memelihara dan mengembangkan nilai-nilai budayanya."

  - Apa itu nilai budaya?
    Apakah budaya yang buruk juga harus dipelihara?
    Apa itu "buruk"?
    Sistem moral mana yang harus dipakai pemerintah?

- Pasal 32 ayat 2: "Negara menghormati dan memelihara bahasa daerah sebagai kekayaan budaya nasional."

  - Bagaimana caranya?

- Pasal 28H ayat 4: "Setiap orang berhak mempunyai hak milik pribadi dan hak milik tersebut tidak boleh diambil alih secara sewenang-wenang oleh siapapun."

  - Pasal ini sangat tidak jelas.
  - Pajak adalah pengambilan sebagian hak milik pribadi secara paksa oleh pemerintah.
    Bagaimana hubungan pajak dan ayat ini?

    - Apa yang dimaksud "hak milik"?
      Private property?
    - Hak milik untuk apa saja?
      Semua benda?
    - Tapi kepemilikan bisa dicabut?
      Apa beda kepemilikan dan hak milik?

  - Bertentangan dengan pasal 33 ayat 3?

    - Sepertinya tidak.
      Ayat ini tidak melarang /pembatasan/ jenis benda yang bisa dimiliki pribadi.

*** Pasal-pasal yang tidak perlu?
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-tidak-perlu
   :END:

Pasal-pasal ini mengatur hal-hal yang tidak usah disuruh pun orang akan melakukan.
Cara menegakkannya juga tidak jelas.

**** Tambahan pasal 28, sepertinya karena Pak Harto
    :PROPERTIES:
    :CUSTOM_ID: tambahan-pasal-28-sepertinya-karena-pak-harto
    :END:

Mungkin beberapa tambahan ini dibuat karena penculikan, penghilangan, dan penembakan misterius pada zaman Pak Harto.

- Pasal 28A: "Setiap orang berhak untuk hidup serta berhak mempertahankan hidup dan kehidupannya."
- Pasal 28B ayat 1: "Setiap orang berhak membentuk keluarga dan melanjutkan keturunan melalui perkawinan yang sah."

  - Tanpa dibolehkan pun orang akan kawin.
    Sebelum ada UUD 1945 pun orang sudah kawin.
    Mengapa bisa ada ayat ini di UUD?
    Apa latar belakangnya?
  - Setiap orang?
    Apakah semua orang boleh melanjutkan keturunan?
    Apakah orang yang tidak bisa mengurus anak sebaiknya melanjutkan keturunan?
    Apakah ekstremis sebaiknya melanjutkan keturunan?

- Pasal 28B ayat 2: "Setiap anak berhak atas kelangsungan hidup, tumbuh, dan berkembang serta berhak atas perlindungan dari kekerasan dan diskriminasi."
- Pasal 28C, 28D, 28E, 28F, 28G, 28H, 28I: you don't say. Bagaimana cara menegakannya?

*** Loopholes and undefined situations
   :PROPERTIES:
   :CUSTOM_ID: loopholes-and-undefined-situations
   :END:

- Pasal 24B ayat 3: "Anggota Yudisial diangkat dan diberhentikan oleh Presiden dengan persetujuan Dewan Perwakilan Rakyat."

  - Kalau DPR tidak setuju, lalu apa?

*** Mana lembaga negara tertinggi?
   :PROPERTIES:
   :CUSTOM_ID: mana-lembaga-negara-tertinggi
   :END:

- DPR lebih tinggi daripada Presiden.
  Presiden tidak bisa pecat DPR.

  - Pasal 7: DPR bisa pecat Presiden, tapi ada syaratnya.
  - Pasal 7C: "Presiden tidak dapat membekukan dan/atau membubarkan Dewan Perwakilan Rakyat."

- Tapi Presiden bisa memerintahkan militer untuk menyerang DPR?

  - Pasal 10: "Presiden memegang kekuasaan yang tertinggi atas Angkatan Darat, Angkatan Laut dan Angkatan Udara."

- DPR bisa mengatur sebagian yudikatif?

  - Pasal 24 ayat 3: "Badan-badan lain yang fungsinya berkaitan dengan kekuasaan kehakiman diatur dalam undang-undang."

*** Yang sudah baik
   :PROPERTIES:
   :CUSTOM_ID: yang-sudah-baik
   :END:

**** Sistem ekonomi paham tengah, berimbang antara kapitalisme dan sosialisme
    :PROPERTIES:
    :CUSTOM_ID: sistem-ekonomi-paham-tengah-berimbang-antara-kapitalisme-dan-sosialisme
    :END:

Pasal 27 ayat 2: "Tiap-tiap warga negara berhak atas pekerjaan dan penghidupan yang layak bagi kemanusiaan."

- Bagaimana cara enforcenya?
- Universal basic income?

Pasal 28H ayat 2: "Setiap orang berhak mendapat kemudahan dan perlakuan khusus untuk memperoleh kesempatan dan manfaat yang sama guna mencapai persamaan dan keadilan."

Pasal 33 ayat 1: "Perekonomian disusun sebagai usaha bersama berdasar atas asas kekeluargaan."

- Apa artinya?

Pasal 33 ayat 2: "Cabang-cabang produksi yang penting bagi negara dan yang menguasai hajat hidup orang banyak dikuasai oleh negara."

Apa arti "hajat hidup orang banyak" dan "dikuasai"?
Dikuasai tidak berarti dimiliki?

Apakah Gojek hajat hidup orang banyak?
Apakah transportasi umum (Kopaja, Metromini, Mikrolet, dll.) hajat hidup orang banyak?

Pasal 33 ayat 3: "Bumi dan air dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besar kemakmuran rakyat."

- Apa itu berarti tanah harus dikuasai negara?
  Orang tidak boleh punya tanah?
  Perusahaan air seperti Aqua, Oasis, Cleo, PAM, PDAM, dll. harus dikuasai negara?

Saya lebih suka orang tidak boleh memiliki tanah (hanya boleh menyewa tanah dari pemerintah).
Tapi bagaimana dengan bangunan di atasnya?

Pasal 33 ayat 4: "Perekonomian nasional diselenggarakan berdasar atas demokrasi ekonomi dengan prinsip kebersamaan, efisiensi berkeadilan, berkelanjutan, berwawasan lingkungan, kemandirian, serta dengan menjaga keseimbangan kemajuan dan kesatuan ekonomi nasional."

Apa arti "demokrasi ekonomi"?
Apa arti "efisiensi berkeadilan"?

"Kemandirian" berarti harus mengurangi impor, lalu memproduksi sebanyak mungkin macam barang dalam negeri?

Pasal 34 ayat 2: "Negara mengembangkan sistem jaminan sosial bagi seluruh rakyat dan memberdayakan masyarakat yang lemah dan tidak mampu sesuai dengan martabat kemanusiaan."

Mendasari BPJS, Jamsostek, dll..
Tinggal eksekusi yang baik.

Pasal 34 ayat 3: "Negara bertanggung jawab atas penyediaan fasilitas pelayanan kesehatan dan fasilitas pelayanan umum yang layak."

Mendasari RSUP, RSUD, dll.


** <2018-09-19> Cabut aturan yang melarang hal-hal yang tidak membahayakan orang banyak.

Cabut aturan yang mengatur urusan pribadi.

** <2018-09-19> Generalize aturan: Kriminalkan semua orang yang mengganggu ketertiban umum?

Problem: Ini bisa jadi pasal karet.

Tidak perlu ada aturan spesifik.
Aturan tentang ketertiban umum mencakup semua hal berikut:
- Membuat video porno tidak kriminal; menyebarkannya yang kriminal.
- Hubungan intim tidak kriminal; yang kriminal adalah membuat masyarakat resah.
- Menghujat tidak kriminal; yang kriminal adalah membuat masyarakat ribut.

** <2018-09-19> Buat aturan contempt of court? Sebaiknya benahi hakim dan pengadilan dulu?

Ide Hotman Paris?

Tapi bagaimana kalau ada miscarriage of justice?
Aturan contempt of court akan memperparah miscarriage of justice.


** Should we repeal blasphemy laws and obscenity laws?
   :PROPERTIES:
   :CUSTOM_ID: should-we-repeal-blasphemy-laws-and-obscenity-laws
   :END:

We already have laws for people causing public disorder.

- If a person commits blasphemy and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for blasphemy.
- If a person distributes obscene materials and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for distributing obscene materials.
- If a person causes public disorder to overthrow a corrupt government,
  then the government will try to vanquish the rebellion,
  but the people shall prevail?
- Blasphemy laws allow angry people to fight in the courtroom.
  Without blasphemy laws, angry people would fight on the road,
  where there are no rules, taking matter into their own hands.

  - However, blasphemy laws also allow religion
    to subvert the justice system.

- http://business-law.binus.ac.id/2018/07/10/bahaya-tafsir-a-historis-terhadap-pasal-156a-kuhp/

* Buat profesi petani jadi menarik secara ekonomi.

* Obtain political power?

** TODO <2018-09-17> Join a think tank or a political party or both?

- https://onthinktanks.org/articles/what-can-indonesian-research-institutes-learn-from-chinese-think-tanks/
- http://www.ksi-indonesia.org/in/home
- http://www.thejakartapost.com/news/2017/02/03/indonesian-groups-among-worlds-influential-think-tanks-report.html
- https://id.wikipedia.org/wiki/Wadah_pemikir

** TODO <2018-09-17> Educate the people about critical thinking, religion, history, power, and politics?

** TODO <2018-09-22> Own a media company, or piggyback existing media?
** Mungkin tidak perlu jadi anggota legislatif? Mungkin bisa dengan mendirikan ormas (organisasi masyarakat) atau yayasan?

UU no 17 tahun 2013, penjelasan pasal 59 ayat 4:
'Yang dimaksud dengan "ajaran atau paham yang bertentangan dengan Pancasila" adalah ajaran ateisme, komunisme/marxisme-leninisme.'

2016 [[http://rubernews.com/2016/05/14/kapolri-keluarkan-aturan-penindakan-penyebaran-paham-komunisme/][berita]]:
"Kapolri Badrodin Haiti menekankan penindakan hukum juga dilakukan pada mereka yang memakai atribut komunisme,
memposting foto palu arit, pemutaran film yang memuat paham komunisme, termasuk memproduksi dan melakukan penyitaan barang bukti."

https://historia.id/modern/articles/pasal-karet-larangan-penyebaran-komunisme-DbNL9

<2018-10-01>
Komunisme di Indonesia sudah tidak ada sejak tahun 1965-an.
Sekarang tahun 2018.
Sudah 50 tahun berlalu.
Tidak perlu takut.
Seandainya ada yang mencoba membangkitkan komunisme di Indonesia, kemungkinan besar akan ditolak oleh masyarakat.

** Tidak perlu bikin organisasi secara formal, cukup himpun orang-orang yang bercita-cita sama.
Tunda bikin badan hukum sampai perlu melibatkan uang besar.
** Using the media in politics
- The role of the media in politics:
    - The media should research/watch/monitor/summarize/audit the government for the public.
    - The media should therefore be owned by the public, and independent of the government. The media should not be funded with tax.
    - The media shapes the public opinion.
    - The media bridges the government and the public.
    - The public doesn't have the time to watch the government.
- The media is the public's opinion of the government.
- The media is whatever the public sees.
    - Shadow/private media: social media, websites, chat groups.
        - "Shadow" in the same sense as "shadow banking".
            - "Shadow" here means unofficial/non-traditional but effective.
        - They may contain hoaxes, fake news, disinformations, and the like.
- How do the public form opinion?
    - Public opinion is country-scale groupthink?
- https://www.thebalancecareers.com/how-politicians-use-media-to-win-elections-2315204
- http://www.ethicssage.com/2016/10/the-role-of-the-media-in-politics.html
- https://study.com/academy/lesson/how-the-media-covers-elections-other-government-activities.html
* <2018-09-19> Net neutrality, un-ban websites, Reddit, Vimeo, dll.

Tapi, apakah website ekstremis juga mau di-unblock?

** Why is Reddit blocked in Indonesia?

- The official reason
  - Something like "Reddit is a porn site.".
  - http://www.mesinwaktu.id/2017/11/alasan-kenapa-reddit-diblokir.html
  - https://www.quora.com/Why-is-Reddit-blocked-by-the-Indonesian-government
  - Doesn't make sense.
    - There is porn on Reddit, but Reddit is not a porn site.
      There are also porn on Google, Bing, YouTube, Blogspot, but they aren't porn sites.
      Why block only Reddit?
      If you're following the law to the letter,
      why not block all of Internet?
- What I think the reason is
  - Someone in the government might need to be seen working.
    Sepertinya blokir website termasuk tugas kemkominfo dalam undang-undang.

* <2018-10-02> Beware of China's debt-trap diplomacy?

Beware of every other nation that seems helpful.

What is this [[https://www.youtube.com/watch?v=lVYdqoVJIeI][video]] trying to say?

The system forces politicians to be myopic (think short-term); they only see at most 5 years ahead.

* Close international tax evasion loopholes

Make it impossible to hide money trail.
Require electronic cash with traceability/accounting/history.
Eliminate hard cash.

** Rally all countries against the money-laundering countries

Tax havens are money launderers.

* Permudah pembuatan badan usaha?

Bikin lebih mudah daripada Singapura, Hong Kong, USA, Estonia.

Tahun 2018, bikin PT di Indonesia masih terlalu sulit.
Mungkin harus tunggu sampai tahun 2025.

Cabut batasan nama PT tiga suku kata tanpa mengandung bahasa atau serapan asing.

Cabut batasan PT harus punya alamat.
Cukup alamat email.

- Indonesia
  - https://easybiz.id/prosedur-dan-syarat-pendirian-pt-terbaru-yang-wajib-anda-ketahui/
  - https://prolegal.id/2018/04/11/prosedur-syarat-pendirian-pt-2018/
- https://www.quora.com/Which-country-has-the-easiest-procedure-for-a-foreigner-to-start-a-business
- ga jelas, agak shady
  - https://flagtheory.com/the-best-place-for-an-internet-entrepreneur-to-incorporate/
  - http://nomadcapitalist.com/2016/05/25/best-country-online-company-incorporation/

Prosedur yang ideal?

- Applicant obtains approval of target neighborhood if necessary (if company operation is disturbing).
- Applicant registers company data.
- Government issues a legal certificate and a tax subject number.
- Done.

[[https://www.bps.go.id/website/fileMenu/Perka-KBLI-2015.pdf][KBLI 2015]] untuk PT yang bergerak di bidang software engineering dan programming language research:

- J.62, hlm. 402
- M.72, hlm. 439

* Prinsip

** Start from the objective reality.

- Contoh:
  - Objektif: "Beberapa orang Indonesia tidak bisa membaca."
    Ada tes yang jelas untuk mengukur kemampuan membaca.
  - Tidak objektif: "Orang Indonesia malas."
    Apa definisi "malas"?

** Work as close as possible to the root cause.

Misalnya dengan cara five whys.

Bisa juga dengan bertanya mengapa sampai kita tidak bisa jawab lagi.
Pertanyaan terakhir yang berhasil kita jawab itulah yang mau kita benahi.


** Bigger changes should be slower

We don't want bloody revolutions (big fast changes).

* Building the ideal society

** Maximize individual freedom while minimizing harm to others

Every man, when left alone, does something he does best.
One person plants trees.
Another person murders people.
It follows that unlimited freedom is bad;
murderers should not be free to murder.

How much individual freedom is desirable?

** Presumption of innocence

- https://en.wikipedia.org/wiki/Presumption_of_innocence
- https://en.wikipedia.org/wiki/Blackstone%27s_formulation

* Hukum

** Hapusnya hak atas tanah?
   :PROPERTIES:
   :CUSTOM_ID: hapusnya-hak-atas-tanah
   :END:

Saya punya tetangga yang menelantarkan rumahnya sampai rusak.
Berapa lama sebelum saya bisa main klaim bahwa tanah itu tanah saya?

- https://www.hukumproperti.com/pertanahan/hapusnya-hak-atas-tanah/

  - "karena ditelantarkan" PP 36/1998

    - Apakah bisa digunakan untuk tetangga yang meninggalkan rumahnya dan membiarkannya rusak?

** Masalah sistem hukum, dan kasus menggantung
   :PROPERTIES:
   :CUSTOM_ID: masalah-sistem-hukum-dan-kasus-menggantung
   :END:

- https://nasional.tempo.co/read/793720/bnn-ada-72-mafia-narkoba-lain-freddy-masih-kelas-ecek-ecek
- http://akakristianto.com/2015/08/14/ungkap-kematian-pekerja-kebersihan-jis/
- http://nasional.republika.co.id/berita/nasional/hukum/15/06/05/npfrim-azwar-tersangka-jis-bukan-mati-bunuh-diri
- https://en.wikipedia.org/wiki/Munir_Said_Thalib
- [[https://news.detik.com/berita/4167913/ganti-rugi-tak-kunjung-cair-korban-salah-tangkap-gugat-menkeu?utm_source=twitter&utm_medium=oa&utm_content=detikcom&utm_campaign=cmssocmed][Ganti Rugi Tak Kunjung Cair, Korban Salah Tangkap Gugat Menkeu]]

  - Aturan 14 hari bayar.
    Itu sudah 2 tahun tidak bayar.
  - Betul kata Hotman Paris, Indonesia perlu aturan contempt of court (penghinaan terhadap lembaga peradilan).
    Selama tidak ada aturan itu, putusan pengadilan tidak dihargai.

** Keluar masuk pegawai
    :PROPERTIES:
    :CUSTOM_ID: keluar-masuk-pegawai
    :END:

- Polisi bisa? (tapi seharusnya tidak bisa?) https://nasional.kompas.com/read/2018/01/15/16055551/polisi-yang-sudah-masuk-ke-politik-seharusnya-tak-bisa-balik-lagi-ke-polri
- TNI tidak bisa https://news.detik.com/berita/d-3305012/setelah-mundur-agus-tak-bisa-kembali-ke-tni-kodam-jaya-itu-pilihannya

  - PNS TNI tidak bisa

- PNS lain bisa http://www.hukumonline.com/klinik/detail/lt59ae5a5d781fd/bolehkah-melamar-menjadi-pns-lagi-jika-pernah-berhenti-dengan-hormat-atas-permintaan-sendiri

* Agama

Agama adalah urusan pribadi, bukan urusan negara.

(Ini masih sesuai UUD?)

** <2018-09-19> Akui semua agama, aliran, dan kepercayaan.

Ada sedikitnya 4000 agama/aliran/kepercayaan.

Syiah, Ahmadiyah, Tarekat Naqsabandiyah.

Agama Mesir kuno.
Paganisme.
Animisme.
Dinamisme.

Discordia, Church of the SubGenius, Flying Spaghetti Monster.

*** Aceh

- https://tirto.id/menilik-harta-kekayaan-cagub-cawagub-dki-bPPV
- https://tirto.id/benarkah-syariat-islam-menghambat-investasi-di-aceh-cP3C
- https://tirto.id/dana-otsus-dicabut-aceh-siap-bangkrut-cP54

*** Sejarah agama

- Agama, yang sekarang besar, awalnya dianggap sesat oleh orang-orang di sekitarnya.
- Pengikut Yesus awalnya dianggap sesat oleh pengikut Yahudi pada zamannya.
- Pengikut Muhammad awalnya dianggap sesat oleh pengikut polytheism Arab pada zamannya.
- Bayangkan seandainya seorang di kampung Anda tiba-tiba mengumumkan suatu agama baru.
- Mengapa kita lebih percaya orang 2000 tahun lalu daripada orang sekarang?
  Mengapa kita berpaku pada masa lalu?
  Mengapa kita tidak berusaha membuat masa depan jadi lebih indah?

** <2018-09-19> Alihkan tugas departemen agama (umrah, naik haji dll.) kepada private sector.

** <2018-09-19> Serahkan pendidikan agama sepenuhnya kepada keluarga.
- Mengganti pelajaran agama di sekolah dengan pelajaran /sejarah/ agama.

** <2018-09-19> Kurangi/tiadakan ekstremisme/radikalisme

*** <2018-09-22> Wajibkan pelajaran sejarah agama

History of Islam?
Is Brigitte Gabriel's [[https://www.youtube.com/watch?v=o0m9nEafBE4][history-of-Islam video]] accurate?

*** Setiap ayat sensitif dalam kitab suci harus disertai tafsir/exegesis/interpretasi dan komentar tentang konteks sejarah turunnya ayat tersebut.
- Terutama Quran karena mayoritas penduduk Indonesia Muslim.
- Kitab suci bisa berupa buku kertas, aplikasi komputer, dll.
- Bagaimana cara mencegah [[https://en.wikipedia.org/wiki/Auto-segregation][WP:Auto-segregation]]?
  Asimilasi vs akulturasi vs absorpsi vs integrasi?
- Apakah efektif?
  Quran terjemahan ekstremis akan tetap saja beredar underground.
  Tapi kebijakan ini mungkin mempengaruhi Muslim moderat yang selama ini complicit atau bahkan diam-diam setuju dengan ekstremis.
- Kita sebaiknya tidak memaksakan/mengatur kepercayaan dengan undang-undang.
- Bagaimana seandainya ada orang mengarang kitab suci sendiri?


** Kerusuhan SARA
   :PROPERTIES:
   :CUSTOM_ID: kerusuhan-sara
   :END:

- Tanjung Balai Sumatra Utara sering rusuh?

  - 2018, [[https://regional.kompas.com/read/2018/08/23/18025471/5-fakta-kasus-meiliana-menangis-di-sidang-hingga-fatwa-mui][5 Fakta Kasus Meiliana, Menangis di Sidang hingga Fatwa MUI - Kompas.com]]

    - [[https://www.facebook.com/ransibar/posts/10216709033187633][Keterangan Ranto Sibarani, anggota tim penasihat hukum tergugat]]
    - Coba tanya MUI Sumatra Utara:

      - Mengapa Jusuf Kalla boleh minta suara azan dikecilkan, tetapi Meiliana tidak boleh?

        - 2018, [[https://news.detik.com/berita/4179062/jk-nilai-kasus-meiliana-bukan-soal-toleransi][JK Nilai Kasus Meiliana Bukan Soal Toleransi]]
        - Karena JK wapres?

          - Seandainya wapresnya Meiliana, apa dia boleh minta suara azan dikecilkan?

            - Seandainya wapresnya Ahok?

      - Mengapa standar ganda?

        - Yang ini hanya kena teguran, tidak dipenjara: [[https://www.liputan6.com/regional/read/3614381/sebut-nabi-muhammad-sesat-ustaz-evie-effendie-kena-teguran-keras][Sebut 'Nabi Muhammad Sesat', Ustaz Evie Effendie Kena Teguran Keras - Regional Liputan6.com]]
        - 2018, [[https://news.detik.com/berita/4178495/pengeluh-volume-azan-dibui-18-bulan-bagaimana-perusak-vihara][Pengeluh Volume Azan Dibui 18 Bulan, Bagaimana Perusak Vihara?]]
          Hanya 1-2 bulan.

      - Mengapa PBNU tidak sepakat dengan MUI?

        - [[https://nasional.tempo.co/read/1119693/pbnu-icjr-dan-setara-kritik-vonis-kasus-penistaan-agama-meiliana][PBNU, ICJR dan Setara Kritik Vonis Kasus Penistaan Agama Meiliana - nasional Tempo.co]]
        - [[https://nasional.tempo.co/read/1119345/pbnu-katakan-suara-adzan-terlalu-keras-bukan-penistaan-agama/full&view=ok][PBNU: Katakan Suara Adzan Terlalu Keras Bukan Penistaan Agama - nasional Tempo.co]]
        - Jadi yang benar siapa?

  - 2018, [[http://medan.tribunnews.com/2018/05/15/ini-kronologis-penangkapan-terduga-teroris-di-tanjungbalai-satu-orang-tewas-di-tempat][Ini Kronologi Penangkapan Terduga Teroris di Tanjungbalai, Satu Orang Tewas di Tempat - Tribun Medan]]
  - 2018, [[https://www.viva.co.id/berita/nasional/1057980-dua-tahun-usai-kerusuhan-sara-toleransi-di-tanjung-balai-kian-kuat][Dua Tahun Usai Kerusuhan SARA, Toleransi di Tanjung Balai Kian Kuat -- VIVA]]

    - Baru dipuji sudah rusuh lagi.

  - 2016, [[https://tirto.id/tujuh-warga-jadi-tersangka-kerusuhan-tanjungbalai-bwtp][Tujuh Warga Jadi Tersangka Kerusuhan Tanjungbalai - Tirto.ID]]
  - 2016, [[http://jarumdetik.blogspot.com/2016/07/fakta-sebenarnya-di-balik-rusuh-tanjung.html][Fakta Sebenarnya di Balik Rusuh Tanjung Balai | Jarum Detik]]

    - Masyarakat setempat sudah dua kali terhasut berita bohong: 2016 dan 2018.

      - [[https://www.motivasi-islami.com/jangan-seperti-keledai-atau-lebih-parah/][Jangan Seperti Keledai Atau Lebih Parah - Motivasi Islami]]: Keledai saja tak jatuh dua kali ke lubang yang sama.

  - A person's beliefs filter all incoming information.
    Therefore people believe hoax that supports their beliefs, and reject facts that counter their beliefs.

    - Riots uncover true beliefs.
    - Kerusuhan adalah bukti bahwa toleransi hanya di permukaan.

  - UU 1/1965 tentang penodaan agama

    - [[https://tirto.id/asal-usul-delik-penistaan-agama-b49e][Asal-Usul Delik Penistaan Agama - Tirto.ID]]

* Teknologi

** <2018-09-19> Kuasai infrastruktur Internet

Infrastruktur Internet adalah hajat hidup orang banyak, jadi harusnya dikuasai negara, sesuai pasal 33 ayat 3 UUD 1945.

** <2018-09-21> Benahi keculasan Telkomsel

- Beli paket data di Indonesia Barat; terbang ke Indonesia Tengah; paket data tidak berlaku.
- Simplify pricing.
  Harga paket data harus rata per GB, dan harus sama di semua Indonesia.
  Tidak boleh memahalkan pengguna kecil.
  - Daerah maju mensubsidi daerah tertinggal.
- Cabut iklan sisipan proxy Telkomsel.

* Transportasi, lingkungan, pertanahan, tata kota

- Utamakan pejalan kaki dalam tata kota.

** Self-driving buses for public transport can drive transport costs down?

- Which are the biggest transport cost component? Is it fuel or the driver?

** Solusi kemacetan tol Jakarta?

- Solusi:
  - Pemda DKI, Bogor, Depok, Tangerang, dan Bekasi:
    - Pilihan 1: Membeli jalan tol menjadi jalan umum.
      - Lunasi atau cicil ke pemilik tol.
    - Pilihan 2: Menyewa jalan tol pada jam tertentu menjadi jalan umum.
      - Menaikkan pajak jalan untuk mobil.
        - [[https://en.wikipedia.org/wiki/Road_tax][WP:Road tax]]
        - Ditambah (rata-rata biaya tol) * (jumlah hari dalam setahun)
          - Ditambah Rp 7,200,000 per tahun?
      - Membuka semua pintu tol di Jakarta pada jam sibuk.
        - Kalau tidak bisa buka semua, buka yang paling bikin macet.
      - Membayar ganti rugi ke operator tol.
- Menyelesaikan dua masalah sekaligus:
  - Disinsentif untuk pengguna mobil pribadi.
  - Mengurangi kemacetan karena kelambatan gerbang tol.
- Skenario gagal:
  - Pemda tidak punya cukup uang.
  - Manusia egois.
    - Pemda sekitar DKI tidak mau patungan.
    - Pemilik mobil menolak bayar pajak demi kebaikan bersama.
    - Pemilik tol menolak penawaran karena terlalu serakah.



** TODO <2018-09-17> Gratiskan kendaraan umum bertrayek

- Lebih mudah dan murah daripada integrasi antarmoda?
- Mengurangi trafik dan polusi.

*** <2018-09-19> Biaya yang diperlukan per jam-kendaraan (unit economics)

- Satuan unit economics: 1 jam-kendaraan
- Breakdown
  - Upah
    - 1 kendaraan butuh 2 orang operator (1 supir dan 1 kenek)
    - Upah 1 orang Rp 7 juta/160 jam ~ Rp 50000/jam
  - Bahan bakar
    - Penggunaan bahan bakar (fuel mileage), 5 km/liter, Rp 10000/liter
    - Kecepatan rata-rata 50 km/jam
    - Kendaraan beroperasi 24 jam per hari = 1200 km/hari = 240 liter/hari
  - Biaya perawatan kendaraan Rp ?/bulan
  - Asuransi kesehatan Rp ?/bulan
  - Asuransi kendaraan Rp ?/bulan

*** Potensi masalah dan penolakan

**** Pengemudi ojek, taksi, dan mobil sewa mungkin menolak karena pendapatan mereka mungkin berkurang

- Bantu mereka beralih jadi supir kendaraan umum bertrayek.

*** Negara lain yang sudah berhasil

- [[https://www.youtube.com/watch?v=ccxVYborUcU][Let's Make Mass Transit Free* - YouTube]]
  - Making mass transit free benefits everyone, including those who don't use mass transit.
    Free mass transit reduces traffic.

** <2018-09-22> Jakarta is sinking, unless we stop draining the aquifer below it.

The animation at 1:55 in this [[https://www.youtube.com/watch?v=dNE5aptbGyY][video]] explains why.

- People pump the aquifers out.
- Rain can't replenish the aquifers because Jakarta is wrapped in concrete.
- There is no more underground water to press the land up.
- The land sinks.

North Jakarta is sinking by up to 20 cm per year.

** <2018-09-21> Perbaiki jembatan penyeberangan

<2018-09-21>
Jembatan penyeberangan di Jl. S. Parman Jakarta logamnya mencuat dan ukuran anak tangganya terlalu kecil.

** Pentingnya infrastruktur
    :PROPERTIES:
    :CUSTOM_ID: pentingnya-infrastruktur
    :END:

[[https://www.bloomberg.com/quicktake/indonesias-nationalism][Bloomberg]]:
"A lack of roads and ports means it's cheaper to ship goods to China than across the archipelago."

Kok lebih murah ngirim barang ke Cina daripada ke Papua?
Padahal, menurut peta, jarak Jakarta-Hongkong mirip jarak Jakarta-Jayapura.

- [[https://www.youtube.com/watch?v=MFrLcRhMKnE][Geopolitics of Southeast Asia Part 2: Malay Archipelago - YouTube]]

  - Indonesia is too big to defend itself.

* Politik

Fix the system; berantas perverse incentive, principal-agent problem, dan conflict of interest.

** Mengapa Indonesia tertinggal?

https://nasional.kontan.co.id/news/dua-alasan-indonesia-tertinggal-dari-negara-lain

Rizal Ramli:

- "Paradigmanya, tebang hutan, lalu ekspor. Sedot tanah di Papua lalu ekspor. Tidak dibangun industri hilir sehingga nilai tambahnya sedikit."
- "Saya minta tolong, perlu perubahan paradigma pengelolaan SDM dari sekadar sedot ekspor, kita kembangkan nilai tambahnya"

Kesimpulannya kita tertinggal karena selalu mencari jalan pintas / menang mudah yang kecil dan tidak matter.

** Mudahkan pemilu untuk perantau

Pemilu serentak?
Sistem e-ktp nasional?

Pemilu harus ada bukti fisik seperti kertas, tidak boleh sepenuhnya bergantung ke komputer.

** <2018-09-19> Evidence-based legislation? data-driven legislation?

** <2018-09-19> Tertibkan kampanye politik

- membatasi kampanye hanya dalam bentuk prospektus (tertulis) berisi rencana program kerja, seperti yang sedang Anda lihat
- mengumpulkan prospektus dalam satu website
- melarang semua bentuk lain

** <2018-09-19> Larang /lobbying/

Bukannya memang sudah dilarang?

** <2018-09-17> Larang partai membayar anggota; wajibkan anggota membayar partai?

- Berantas politik karir?
  What's so bad about career politicians?
  A career is not bad in and of itself.
- Pastikan bahwa yang masuk adalah orang yang benar-benar peduli politik.
- Tapi kalau begini, politik jadi sampingan.
  Tidak semua orang mau punya 2 pekerjaan.

A party is a mini-country.
Therefore a party should tax its members, not pay its members.

Politics should not be a career path?

** Pesimis soal partai baru
   :PROPERTIES:
   :CUSTOM_ID: pesimis-soal-partai-baru
   :END:

2014 ada partai baru: [[https://psi.id/][Partai Solidaritas Indonesia]].
Terus?
Semua partai juga pernah baru.
Semua partai juga didirikan dengan cita-cita mulia.

- Pada tahun 1927 PNI juga partai baru.
- Pada tahun 1964 Golkar juga partai baru.
- Pada tahun 1973 PDI juga partai baru.
- Pada tahun 2001 Partai Demokrat juga partai baru.
- Pada tahun 2002 PKS juga partai baru.
- Pada tahun 2008 Gerindra juga partai baru.
- Semua partai baru itu akhirnya terlibat masalah.

Bagaimana kita menjamin partai baru tidak terjerembab ke lubang korupsi?

Ada siklus:

- Partai baru didirikan karena ketidakpuasan terhadap partai lama.
- Setelah lama, partai baru jadi partai lama, dan terlibat masalah.
- Ulangi.

Kalau semua partai terlibat masalah,
sistem pemerintahan perlu diperbaiki?
Pemisahan perlu diperbaiki?
Insentif perlu dirancang lebih baik?

Umpama anak sekolah:

- Kalau satu anak gagal, mungkin anaknya yang salah.
- Kalau satu kelas banyak yang gagal, mungkin kelasnya yang salah.
- Kalau banyak kelas gagal, mungkin sekolahnya yang salah.
- Kalau banyak sekolah gagal, mungkin sistem pendidikannya yang salah.

Umpama partai:

- Kalau satu orang korup, mungkin orangnya yang salah.
- Kalau satu partai banyak yang korup, mungkin partainya yang salah.
- Kalau banyak partai korup, mungkin hukum negara ini yang salah.

Diskusi:

- [[https://www.quora.com/What-do-Indonesians-know-think-about-the-new-party-PSI-Partai-Solidaritas-Indonesia-And-how-big-is-the-chance-that-the-PSI-will-get-a-place-in-the-parliament][What do Indonesians know/think about the new party PSI (Partai Solidaritas Indonesia)? And how big is the chance that the PSI will get a place in the parliament? - Quora]]

*** Sistem kita mengubah orang muda idealis menjadi orang tua korup?

Orang baik dalam sistem buruk akan jadi orang buruk.

- https://theconversation.com/buasnya-sistem-politik-indonesia-halangi-upaya-reformasi-dari-dalam-oleh-mantan-aktivis-94523

Bagaimana memperbaikinya?

** Ucapan terima kasih
   :PROPERTIES:
   :CUSTOM_ID: ucapan-terima-kasih
   :END:

*** Terima kasih Gus Dur
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-gus-dur
    :END:

Imlek jadi libur.

Diskriminasi berkurang.

WNI keturunan Cina bisa masuk universitas negeri.

*** Terima kasih Ahok
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-ahok
    :END:

- Rumah saya baru bebas banjir pada zaman BTP (Basuki Tjahaja Purnama a.k.a. Ahok).

  - Tahun 1990-an setiap 5-6 tahun sekali, rumah banjir.
  - Makin lama makin parah. Tiap tahun banjir.
  - Bahkan, pernah suatu ketika, tidak hujan malah banjir.
  - Jalanan dinaikkan 50 cm. Rumah dinaikkan 100 cm. Tetap banjir.
  - Saat BTP menjabat, rumah saya tidak banjir.

Namun, hal yang saya tidak setuju:

- Omongan kurang dijaga, mungkin terbawa emosi.
  Akhirnya kata-katanya dipakai untuk menyerang dia.
- Utilitarianisme.
  [[https://en.wikipedia.org/wiki/Trolley_problem][WP:Trolley problem]] menyiratkan bahwa utilitarianisme tidak cocok jadi prinsip moral.
  Saya hargai kemampuan problem-solving dan kecepatan kerja Ahok, tapi soal prinsip moral ini saya tidak setuju.

  - [[https://news.detik.com/berita/2998358/ham-versi-ahok-untuk-melindungi-rakyat-banyak][HAM Versi Ahok untuk Melindungi Rakyat Banyak]]

** Peduli rakyat kecil
   :PROPERTIES:
   :CUSTOM_ID: peduli-rakyat-kecil
   :END:

- Student activism

  - [[https://twitter.com/semarui?lang=en][SEMAR UI]]
  - [[https://twitter.com/rakapare?lang=en][Komune Rakapare]]

** 1998
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

- [[https://www.reddit.com/r/indonesia/comments/61ed2m/what_was_indonesia_like_before_reformasi_and/][What was Indonesia like before Reformasi and after1998? (Long) : indonesia]]
- [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/][Telegram from US Embassy Jakarta to State Department, "Who Is Behind [1998] Disappearances?," : indonesia]]

  - [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/e4a0s02/][Pendapat redditor fourrier01]]: "Every year, just before election, there's always a news to reveal Prabowo stench over and over. 4 years ago there was Allan Nairn. [...] This one isn't so surprising anymore."

** Pemilihan Presiden 2019
   :PROPERTIES:
   :CUSTOM_ID: pemilihan-presiden-2019
   :END:

- https://www.reddit.com/r/indonesia/comments/9640by/rekam_jejak_sikap_dan_perkataan_maruf_amin/

  - https://www.reddit.com/r/indonesia/comments/9631cu/maruf_amin_dulu_saya_yang_menggerakkan_aksi_212/

- [Pendapat seorang redditor dengan username kurang elok](https://www.reddit.com/r/indonesia/comments/97bncz/mahfud_sebut_maruf_amin_suruh_nu_ancam_jokowi/e472v4s/] tentang Maruf Amin, calon wakil presiden 2019. Pendapat ini terdengar gila, tapi mungkin. Entah.

  - "Sesuai UU kita, ketika presiden gak ada (karena meninggal atau lengser) wapres langsung auto-presiden. Disini ada insentif besar utk kaum mereka bunuh atau lengserkan presiden."

- Belum dibaca

  - [[https://www.reddit.com/r/indonesia/comments/983if1/pros_of_jokowi/][Pros of Jokowi : indonesia]]
  - [[https://www.reddit.com/r/indonesia/comments/982c5x/why_fear_over_islamists_in_prabowos_future/][Why Fear Over Islamists in Prabowo's Future Government is Unfounded : indonesia]]

** Pendapat-pendapat yang edgy tapi mungkin ada benarnya
   :PROPERTIES:
   :CUSTOM_ID: pendapat-pendapat-yang-edgy-tapi-mungkin-ada-benarnya
   :END:

*** Jalan tol adalah tindak kejahatan.
    :PROPERTIES:
    :CUSTOM_ID: jalan-tol-adalah-tindak-kejahatan.
    :END:

- Jalan tol adalah jalan pribadi (jalan milik perusahaan, bukan jalan umum).
- Jalan S. Parman, Jalan Gatot Subroto, dan Jalan M.T. Haryono adalah jalan umum.
- Dahulukan kepentingan umum sebelum kepentingan pribadi, menurut pendidikan kewarganegaraan yang diajarkan di SD.
- Antrian tol memacetkan jalan umum.
- Sebagian kemacetan di jalan umum tersebut terjadi
  karena pemerintah membiarkan pengelola jalan tol mendahulukan kepentingan pribadi.

  - Jika antrian terlalu panjang, polisi seharusnya berhak mempercepat antrian dengan cara:

    - memaksa mengalihkan mobil dari antrian ke jalan biasa
    - memaksa membuka gerbang tol

- Tugas pemerintah hanya dua:

  - Melakukan hal yang menguntungkan banyak orang.
  - Mencegah hal yang merugikan banyak orang.

- Seandainya Pemda DKI Jakarta hendak membeli sebagian ruas jalan tol untuk dijadikan jalan umum,
  berapa biaya per kilometernya?

** Pertanyaan-pertanyaan yang belum terjawab
   :PROPERTIES:
   :CUSTOM_ID: pertanyaan-pertanyaan-yang-belum-terjawab
   :END:

- How to combat people who provoke you and then cry foul?
- Undigested

  - Why do Habib Rizieq supporters support him?
  - 2017-06-23 government announces that they will take Rp344 trillion loan. Source?
  - If Sukarno hadn't fallen, would he have been like Gajah Mada, Washington, Castro, Kim, Mao, Stalin, Khan, or someone else?
  - Bagaimana cara impor?
  - Bagaimana cara ekspor?

- Indonesia needs a website like politifact or factcheck.org.
- Is the 21st century is the age of demagogues, or has it always been the case?
  When did candidates begin appealing to emotion using racism and religion?
  Donald Trump?
  Anies Baswedan?

*** Ada Mata Najwa, mengapa tidak ada Tangan Najwa?
    :PROPERTIES:
    :CUSTOM_ID: ada-mata-najwa-mengapa-tidak-ada-tangan-najwa
    :END:

- Apa ada hal seperti acara televisi Mata Najwa tetapi berupa tulisan?
  Tangan Najwa gitu?

*** Mengapa kita tidak minta tolong cenayang panggil arwah Bung Karno dan tanyakan kebenaran G30S PKI dan Supersemar?
    :PROPERTIES:
    :CUSTOM_ID: mengapa-kita-tidak-minta-tolong-cenayang-panggil-arwah-bung-karno-dan-tanyakan-kebenaran-g30s-pki-dan-supersemar
    :END:

Mengapa kita tidak tanya istrinya, anaknya, kerabatnya, teman-temannya?

*** Program 1000 startup ke mana?
    :PROPERTIES:
    :CUSTOM_ID: program-1000-startup-ke-mana
    :END:

- [[https://www.reddit.com/r/indonesia/comments/98afrg/anyone_know_what_happened_to_1000_startup_i_found/][Anyone know what happened to 1000 Startup? I found these three comments in a video about them. : indonesia]]

* Kesehatan

** Permurah kesehatan?

Mengapa kesehatan mahal?

Mengapa rumah sakit mahal?

** <2018-09-19> Ban buffets/all-you-can-eat restaurants

- Unhealthy. Induces overeating.
- Dishonest pricing.
  - [[https://www.insideedition.com/athlete-banned-all-you-can-eat-sushi-buffet-eating-too-much-46845][Athlete Banned From All-You-Can-Eat Sushi Buffet for Eating Too Much | Inside Edition]]
    - Why do you ban people?
      You know what you sign up for.
      You know everyone's diet is different.
      The eater does nothing wrong.
      If you don't like people eating too much, open a conventional a la carte restaurant.
      Buffets are food casinos.
      Buffets are insurance.
      They are all actuarial.
      It's unfair if you only want the money but don't want the risk.

** <2018-09-19> Bantu petani tembakau dan buruh tembakau cari pekerjaan lain

** <2018-09-22> Legalkan aborsi
Forcing someone to live the life he does not want is more immoral than killing him.
This also implies:

- We should let people kill themselves if they have thought about it well, as long as they are done privately.
  - But https://www.speakingofsuicide.com/2013/05/19/why-stop-someone-from-suicide/ dissents:
    - "The most important reason to prevent suicide is that suicidal crises, though formidable and painful, almost always are temporary.
      Even if the person continues thinking about suicide, the intense suicidal intent usually subsides.
      Consider that 90% of people who survive a suicide attempt do not go on to die by suicide.
      That number is very revealing.
      Even among people who wanted to die so strongly that they tried to end their life, most ultimately chose to live."
      - People don't know what they want.
        We don't know what we want.
- We should not prolong the suffering of dying people by forcing life support.

No baby consents to being killed.
No baby consents to being born either.
* Ekonomi

** Prinsip ekonomi

- Mandirikan bangsa.
  Maksimalkan produksi dalam negeri.
  Kemandirian adalah syarat perlu tetapi tidak cukup untuk kedaulatan.

** Kurangi nilai impor.

- Tingkatkan produksi dalam negeri, terutama industri strategis, teknologi.
- Bangun daerah tertinggal, kurangi urbanisasi.

** Bantuan langsung tunai (BLT) = cash transfers
   :PROPERTIES:
   :CUSTOM_ID: bantuan-langsung-tunai-blt-cash-transfers
   :END:

- [[https://www.livemint.com/Politics/144kmvZXyDiM40UxY66DYJ/Targeted-cash-transfer-schemes-can-do-more-harm-than-good.html][Targeted cash transfer schemes can do more harm than good - Livemint]]
- Giving money to poor people immediately increases their purchasing power, but there are consequences.
- They buy things, increasing demand.
- If there is not enough supply, then prices rise.
- Conclusion:

  - In the short term, cash transfers provides immediate relief to poor people.
  - In the long term, cash transfers hurts the poor people it intends to help.
  - To help the poor, the government should increase the supply of goods to the poor.

    - Ideal permanent strategic solution: increase aggregate efficiency to drive down costs.

      - Localize production.
        Avoid transportation.
        Transportation is waste.
      - Depend on renewable energy.
        The sun is free!
        Wind is free!
        The TCO (total cost of ownership) of solar is approaching that of coal/oil?
      - Good infrastructure to reduce transport time/cost.
      - Integrate transport modes to reduce transport costs?

    - Quick temporary tactical solution: subsidies.

- Basic income is unconditional cash transfers.
* Survei tanah, konflik agraria, sertifikasi tanah?

* Pendidikan

** Tingkatkan gaji dan mutu guru?

** <2018-09-22> Perbaiki cara mengajar sejarah

- Tidak perlu menghapal hal-hal yang dicari dalam 1 menit di Internet.
- Yang penting ialah memahami sebab/konteks sesuatu terjadi, terutama perang.

** 100% literacy rate; budayakan membaca dan menulis

Jordan Peterson: "The best way to teach people critical thinking is to teach them to write." ([[https://www.youtube.com/watch?v=x0vUsxhMczI][source]])

** Bahasa Inggris (dan Mandarin?)

** Memberantas kebodohan
   :PROPERTIES:
   :CUSTOM_ID: memberantas-kebodohan
   :END:

*** Benci suku tertentu itu merugikan diri sendiri

WNI keturunan Cina itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Cina?
Pemerintah Cina saja tidak peduli.

WNI keturunan Arab itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Arab?
Pemerintah Arab saja tidak peduli.

WNI keturunan India itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah India?
Pemerintah India saja tidak peduli.

Dan seterusnya.

* Pertanian

* Shocking news. Are these real?
   :PROPERTIES:
   :CUSTOM_ID: shocking-news.-are-these-real
   :END:

- [[https://www.liputan6.com/regional/read/3618529/bocah-bocah-terciduk-saat-asyik-dugem-di-diskotek-berkedok-toko-es-krim][Bocah-Bocah Terciduk Saat Asyik Dugem di Diskotek Berkedok Toko Es Krim - Regional Liputan6.com]]

  - from [[https://www.reddit.com/r/indonesia/comments/97s1o2/bocahbocah_terciduk_saat_asyik_dugem_di_diskotek/][reddit]]

- [[https://regional.kompas.com/read/2017/05/10/15213361/tommy.soeharto.dianugerahi.gelar.gus.oleh.ulama.di.jatim][Tommy Soeharto Dianugerahi Gelar "Gus" oleh Ulama di Jatim - Kompas.com]]

  - [[https://nasional.tempo.co/read/10122/kronologi-kasus-tommy-soeharto][Kronologi Kasus Tommy Soeharto - Nasional Tempo.co]]
  - [[https://tirto.id/pembunuhan-hakim-syafiuddin-yang-dirancang-tommy-soeharto-cPVT][Pembunuhan Hakim Syafiuddin yang Dirancang Tommy Soeharto - Tirto.ID]]
  - [[https://seword.com/politik/sadisnya-pembunuhan-hakim-kartasasmita-oleh-tommy-soeharto-ryLUQSUYG][Sadisnya Pembunuhan Hakim Kartasasmita oleh Tommy Soeharto - Seword]]

* Bayar pajak
   :PROPERTIES:
   :CUSTOM_ID: bayar-pajak
   :END:

- https://djponline.pajak.go.id/account/login

  - http://www.pajak.go.id/article/jangan-panik-jika-lupa-kode-efin-ikuti-langkah-berikut
* Ethics
** Abortion debates are futile communication failures
<2018-09-15>

TLDR: Before you debate abortion, make sure everyone has the same definition of the words you're going to use.
*** The problem with abortion debates
Abortion debate is all emotion and no thinking.
Nothing will ever come out of it.
There is no real discussion.
The participants don't even agree on the meaning of the words they use (human, fetus, life, species, murder).
It is communication failure.
It is religious debate.

Everyone gives different meanings to the same word.
Everyone assumes everyone else has the same definitions.
There is only an illusion of communication.
There is no real progress.

New York Times has some [[https://opinionator.blogs.nytimes.com/2011/11/30/on-abortion-and-defining-a-person/][opinion]] about language in abortion debates.
*** Abortion debate is battle between thinkers and feelers
After seeing [[https://abortion.procon.org/][Abortion ProCon.org]], I realize that the debate is just a battle between thinkers and feelers.
Generally, thinkers are pro-abortion and feelers are anti-abortion.

After browsing around, I realize that gun control, euthanasia, death penalty, and other moral issues are just a giant battle between thinkers and feelers.
*** Ubiquitous problem: not defining what a human is
What is a human?
We think we know what a human is, but when we want to say it, we find out we can't.
Why?
Is our language limited?
Is "human" an ill-defined concept?

We don't know what a human is, we don't know what life is, but we dare to debate the sanctity of the life of a human?

People who debate abortion but can't define human are wasting time.
They don't know what they're talking about.
*** Ubiquitous fallacy: binarizing the continuum
Concepts such as hot, tall, big are not binary.
They are continuums.

Life is not binary.
It is a continuum.
We are more alive when we wake up.
We are less alive when we sleep.
We are even less alive when we die.

Being human is a continuum.

Truth is a continuum.
We reason probabilistically.
*** Why do we care what others do?
We care about what others do only as far as how they may harm us.

We don't care when someone harms himself.

We care when someone harms others, but only if he may harm us.

We care when someone kills people because we fear he may kill us next, not because we care about the people he killed.

We care when someone kills his children because we fear he may kill our children next, not because we care about the children he killed.

Why do we care when a pregnant woman aborts her fetus?

We care when a woman aborts her fetus because we want to impose our morality on others, not because we care about the fetus.
If we cared about the fetus, we would help the mother raise the fetus, help her give birth, and then adopt the baby.
*** Nature-defying El Salvador abortion law
[[https://www.bbc.co.uk/news/magazine-24532694][El Salvador abortion law ignores nature]].
It imprisons people unnecessarily.
*** Catching fallacies in action
**** Dennis Prager
Dennis Prager has a [[https://www.youtube.com/watch?v=AMwkQVpy98A][video about abortion]].

What he gets right:

- Right: "When challenged with this argument, people usually change the subject to the rights of the mother."
  - The right response is to ask the claimant to define the words human, species, life, fetus, etc.
    There is no need to digress to mother rights in order to point out the problems with the argument.

What he gets wrong:

- Mixing unrelated concepts in a loaded question: "Does the human fetus have any value and any rights?"
  - "Value" is a moral concept.
    "Rights" is a legal concept.
    The two don't always coincide.
    Also, he hadn't defined what a "human" is.
- Misuse of language: "A living being doesn't have to be a person in order to have intrinsic moral value and rights."
  - The term "intrinsic rights" is an oxymoron.
    Your rights are the things laws give you.
    They don't come with you.
- Wrong: "Either a human fetus has worth or it doesn't."
  - This is the fallacy of binarizing the continuum.
- Loaded question:
  "Why does one person, a mother, get to determine whether that being has any right to live?"
  - The question should have been: "Why does /anyone/ at all get to determine whether any being has any right to live?"
    - That question suggests antinatalism.
      Why do we force babies to come into being?
** Moral particularism
https://philosophynow.org/issues/60/Why_You_Shouldnt_Be_A_Person_Of_Principle

Is there a universal moral principle that coincides with the majority intuition about these issues?

- It is moral to kill fewer people to save more people?
- Is it moral to kill a serial killer to prevent 100 murders?
- Is it moral to kill a healthy innocent person and distribute his organs to save 5 people in need?
- Is it moral to annex a mismanaged country and improve it?
** Does intention matter?
How do we know others' intentions?
** Improbability of equality of outcome in doomsday spaceship scenario
Consider this "doomsday spaceship" scenario:
- A huge asteroid will hit the Earth 1 week from now. That will kill all 7 billion people.
- But we have one spaceship that can save 1000 people. That is the only way out of Earth.
Which people should we save?
Why?
There is no satisfactory answer to this; we should just use a truly random lottery.
But if we pick people randomly, the ship will be full of poor people, because the majority of the Earth is poor.
Should pregnant women be prioritized before non-pregnant women?
Should older women be prioritized before younger women?
Should women be prioritized before men?
Should children be prioritized before women?
Nobody should be prioritized.
If we don't pick people randomly, then we don't practice what we preach about equality.

With a lottery, all 7 billion people have a chance to board the spaceship,
but it is physically impossible for all 7 billion people to actually board the spaceship.
No amount of political correctness will change the laws of nature.

Of course, when the spaceship is big enough for 7 billion people, we can have equality of outcome.
The question is how we make a spaceship that big.
** Leaving Greenpeace
- [[https://www.youtube.com/watch?v=BpBnJq19R60][video]] of Patrick Moore's reasons for leaving Greenpeace

** Contextual/circumstantial morality/ethics

Does context change the goodness?
Is context relevant to morality?
Do circumstances affect judgment?
Example:
Stealing is wrong.
Is stealing in distress to survive less wrong?
Self-defense can justify killing. Why can't self-defense justify stealing?
Should intentional killing be more wrong than unintentional killing?
Rioting is wrong. But is rooting to overthrow a tyrant wrong?

https://english.stackexchange.com/questions/360411/whats-the-difference-between-dictator-tyrant-and-despot-in-terms-of-a-r

Is killing a terrorist good?

** Natural morality? Survival?

http://atheistnexus.org/m/discussion?id=2182797%3ATopic%3A131131
"Morality is a consideration among the living about that which affects survival." Clarence Dember

[[https://en.wikipedia.org/wiki/Natural_morality]]

* What

Marx's stages of society
https://en.wikipedia.org/wiki/Marx%27s_theory_of_history

Ganti upah minimum dengan universal basic income atau negative tax rate

Embedding communism in capitalism

Embedding capitalism in communism

Reconciling capitalism and communism

Communism should not be defined as an opposite to capitalism.
"Abolition" is negative definition.

Communism doesn't require central government.

* Examples of local communism?

Israel kibbutz? https://en.wikipedia.org/wiki/Kibbutz

Can we have communism without centralization?
It's absurd to have a central authority that decides who to make how much what.

https://en.wikipedia.org/wiki/Primitive_communism

* Is sharing communism?

Is ridesharing (Gojek, Grab, Uber, Lyft, etc.) communism?

* Can employer-employee relations be replaced with buyer-seller relations?

Can a factory worker be allowed to work at any time he wants, at any duration he wants, and be paid by the amount of things he sold to his direct buyer?

Combine animal husbandry / ranching and permaculture to make low-operation organic chicken farm?

* Why are the Norwegians so sensible? Why are their governments so good?

[[https://www.youtube.com/watch?v=b_l3eLhYbVo][Why The UK Lost Its Oil Wealth (And Why Norway Didn't) - YouTube]]

Every country has smart people.
Smart people are everywhere.
Why do countries fare differently?

* from government.md

These are important and urgent things for most (if not all) countries on Earth to do as soon as possible.

** Fixing the political system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-political-system
   :END:

- Restrict the form of all political campaigns to text containing the list of things the candidate wants to do.

  - Avoid pandering and toxic campaigns.

- Replace parliaments with sortition (randomly choosing people)?

  - TED: "What if we replaced politicians with randomly selected people? | Brett Hennig", [[https://www.youtube.com/watch?v=cUee1I69nFs][youtube]]
  - [[https://en.wikipedia.org/wiki/Sortition][WP:Sortition]]
  - Will sortition work in a homogeneous country?
    Won't it just promote groupthink?
  - How does sortition affect the minority?
    How should the population be sampled?
    Stratified sampling?

** Fixing the justice system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-justice-system
   :END:

- Change the justice system from retributive justice to restorative justice for the non-violent criminals.

  - Instead of locking up prisoners, let them repair the harm they did, and help them reintegrate into society.
  - Millions of people are being incarcerated.
    Their ability is being wasted.
    They are deprived of future.
    They will have difficulties reintegrating into society.
    Stigmatized.
    Like the homeless.
    This stigma makes it impossible for them to get financial stability and get out of the vicious circle of crime.

    - Also, prison initiation rituals are terrible.

  - There are two kinds of criminals:

    - /Perforce criminals/ commit crime to defend themselves from immediate bodily harm that threatens their existence.
      Examples are hungry moneyless people who steal food, and cornered people who kill.
      The solution is restorative justice, and giving work to the criminal for financial stability, helping them reintegrate into society.

      - If the threat is removed, perforce criminals no longer commit crime.

    - /Non-perforce criminals/ commit crime for anything else.
      Examples are psychopaths (people with physical inability to weigh bad consequences because their brains are wired differently).
      The solution is unbreeding: modify them by gene therapy or psychological therapy or whatever technology, or kill them if they can't change,
      but only after we have proven that they can't change.

      - See also [[https://www.theatlantic.com/magazine/archive/2017/06/when-your-child-is-a-psychopath/524502/][theatlantic.com: When your child is a psychopath]].

  - Prisons should not exist.
    There should exist only two kinds of punishment:

    - Forced labor, for perforce criminals, to repair the harm they did.
      The state must also help them reintegrate into society.
    - Death penalty, for non-perforce criminals.

  - In any case, nobody should be locked up for so long.
    Locking up people wastes resource.

** Should we limit inheritance?
   :PROPERTIES:
   :CUSTOM_ID: should-we-limit-inheritance
   :END:

https://taxfoundation.org/estate-and-inheritance-taxes-around-world/

Should we have any tax at all?

Should government funding be voluntary?

** A government is to maximize the well-being of its people
   :PROPERTIES:
   :CUSTOM_ID: a-government-is-to-maximize-the-well-being-of-its-people
   :END:

- A government is to:

  - do things that benefit many but do not benefit a few, such as building roads;
  - prevent things that benefit few but do not benefit many, such as committing crime.

- A government is to minimize negative [[https://en.wikipedia.org/wiki/Externality][externality]]
  and [[https://en.wikipedia.org/wiki/Rent-seeking][rent-seeking]].
- A government is to prevent the [[https://en.wikipedia.org/wiki/Tragedy_of_the_commons][tragedy of the commons]].

** Ungrouped content
   :PROPERTIES:
   :CUSTOM_ID: ungrouped-content
   :END:

A modern government is designed to minimize the damage if a bad person rises to the top,
not to maximize the benefit if a good person rises to the top.
That is why a republic has checks and balances.
The most efficient government is a benevolent competent dictator,
but does such person exist?

The government is a monopoly, and it should seek profit for its stakeholders: all its people.
Government official corruption, similar to corporate management corruption,
is a [[https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem][principal-agent problem]].
Everything that solves the principal-agent problem also solves corruption.

** Deciding what governments should do
   :PROPERTIES:
   :CUSTOM_ID: deciding-what-governments-should-do
   :END:

Use this quadrant:

- Axis 1: Does it benefit many people?
- Axis 2: Does it benefit a few people?

Things that benefit many and benefit few are best left to the private sector
with as little regulation as needed to keep the market healthy.

Things that benefit many but disadvantage few should be done by the public sector,
because the private sector will not do them because they don't get money doing that.
Example: building road.

Things that disadvantage many but benefit few should be prevented by the government.
Example: rent-seeking (bribing, lobbying,
speculation of non-fungible goods such as land parcels and Internet domain names),
crime, terrorism.

Things that disadvantage many and disadvantage few should also be discouraged by the government.
Example: road rage, human stupidity.

** Tips from our ancestors
   :PROPERTIES:
   :CUSTOM_ID: tips-from-our-ancestors
   :END:

I do not always agree with Lenin, but I agree with this sentence of his:

#+BEGIN_QUOTE
  When it is not immediately apparent which political or social groups,
  forces or alignments advocate certain proposals, measures, etc.,
  one should always ask: "Who stands to gain?"

  Vladimir Ilyich Ulyanov a.k.a. Lenin (1870--1924)
  ([[https://www.marxists.org/archive/lenin/works/1913/apr/11.htm][source]])
#+END_QUOTE

That was 1913.
In 1976 that could be more simply put as [[https://en.wikipedia.org/wiki/Follow_the_money][follow the money]].

** Ramble
   :PROPERTIES:
   :CUSTOM_ID: ramble
   :END:

- A government should only do things that better its people.

  - How do we know if something will make people better off?

- Is Chinese government dominated by scientists and engineers?

  - https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers

- https://www.quora.com/What-would-a-government-designed-by-engineers-and-not-politicians-look-like?share=1

  - https://tomgrego.blogspot.com/2010/12/a-government-you-can-love.html
  - https://www.quora.com/Concretely-what-can-we-do-to-get-US-politics-working-What's-gone-wrong-and-why-are-things-worse-than-20-years-ago-How-could-US-politics-improve-in-10-years-What-short-term-tactics-could-advance-the-long-term-goal?share=1

- The public sector is inefficient, but the private sector might be too efficient (extracting too much profit? but how much profit is too much?)?
  Is there a mixture between the two?
  Regulated private sector?
- https://en.wikipedia.org/wiki/Monopoly_on_violence

  - https://en.wikipedia.org/wiki/Justification_for_the_state

- https://www.bbc.com/news/uk-politics-42570823
- https://www.quora.com/Are-there-any-countries-without-government
- If healthcare were affordable, would we still need insurance?
- We don't need insurance.
  We need affordable healthcare.
- http://time.com/4937691/americans-cheap-healthcare-instantly/
- https://www.bloomberg.com/news/articles/2018-05-15/doctors-who-hate-insurance-so-much-they-go-without-it-themselves
- https://www.quora.com/What-do-doctors-think-about-insurance-companies
- What makes healthcare so expensive?

  - Definitely not the general practitioners (non-specialist doctors).
    They charge the patient only about $20 per visit.
  - Hospitals?
  - Drugs?
  - Insurances?

- argument for government, the necessity of government

  - https://www.quora.com/Why-have-so-few-humans-realized-that-governments-are-unnecessary

- https://en.wikipedia.org/wiki/Night-watchman_state
- If taxes were voluntary, would people pay tax?
- https://en.wikipedia.org/wiki/Voluntary_taxation

** The world should have only one country, one government, one law.
   :PROPERTIES:
   :CUSTOM_ID: the-world-should-have-only-one-country-one-government-one-law.
   :END:

Having many countries causes legal loopholes.

If there is only one country, there will be no tax tricks, tax havens.

There would be no illegal immigrants.
Everyone would be a world citizen.

- https://www.quora.com/Why-cant-all-the-earth-countries-unite-to-make-a-single-federation
* Golkar (golongan karya, functional group)

https://historia.id/modern/articles/golkar-sebagai-pengganti-partai-vxmrP:
"Mulanya golongan fungsional atau golongan karya adalah pengganti sistem kepartaian. Sukarno yang menggagasnya."

https://www.tutor2u.net/politics/reference/functional-representation

http://www.oxfordreference.com/view/10.1093/acref/9780199207800.001.0001/acref-9780199207800-e-524
"Functional representation may be contrasted to the more usual form of territorial representation [...]"

https://www.kompasiana.com/faizrahman/54f82194a33311ae608b4bde/urgensi-perwakilan-fungsional-dalam-majelis-permusyawaratan-rakyat

https://id.wikipedia.org/wiki/Utusan_Golongan

* <2018-10-02> We don't want completely free-and-global trade because we don't want to depend too much to others.
** Independence is necessary but not sufficient for sovereignty.
By depending on someone, you give him power over.
You weaken your bargaining power.
You worsen your negotiating position.
You reduce your sovereignty.

We must start strategic domestic industries, no matter how shitty it will be.
We can always improve it later.

<2018-10-03>

* Use nitrogen asphyxiation for capital punishment
Nitrogen asphyxiation is humane, cheap, and fast.
- https://www.quora.com/What-would-be-the-fastest-and-most-efficient-way-to-kill-someone
- https://www.quora.com/Why-is-nitrogen-asphyxiation-not-used-in-capital-punishment
- https://en.wikipedia.org/wiki/Inert_gas_asphyxiation
- https://www.washingtonpost.com/news/post-nation/wp/2018/03/14/oklahoma-says-it-will-begin-using-nitrogen-for-all-executions-in-an-unprecedented-move/?noredirect=on&utm_term=.f342a31e16e9
* Blacklisted untrustworthy news sources
According to https://www.vox.com/platform/amp/policy-and-politics/2018/10/1/17923178/washington-times-seth-rich-aaron-rich-trump-fox-news:
- Washington Times
- FOX News
* Measuring trust between countries
** The power of a country's passport tells how great that country is
https://www.passportindex.org/byRank.php

Your passport's power is proportional to how much the world trusts your country.
* Cipolla's laws of stupidity
- https://en.wikipedia.org/wiki/Carlo_M._Cipolla
- Cipolla's definition of "stupid":
  "A stupid person is a person who causes losses to another person or to a group of persons while himself deriving no gain and even possibly incurring losses."
* TODO reorganize; from politics.md
- What is the Government of China afraid of?

  - The Government of China isn't afraid of criticism. It is afraid of collective action. [King2013]

- Why are cannabis and heroin illegal?

  - [[https://www.reddit.com/r/LateStageCapitalism/comments/6h6med/daily_reminder_about_the_true_purpose_of_the_war/][/r/LateStageCapitalism: John Ehrlichman: Nixon illegalized drugs to stigmatize hippies (cannabis) and blacks (heroin) because those people were against him.]]
  - Cannabis overuse permanently damages teen brains.
  - Another theory: cotton farmers vs hemp farmers?

- Reddit: CrazyIdeas

  - https://www.reddit.com/r/CrazyIdeas/comments/17yniw/you_need_a_license_to_have_children/

    - Are people more likely to be killed by other people (war, genocide, holocaust) or by cars?

  - https://www.reddit.com/r/CrazyIdeas/comments/3x8fr5/seeing_as_the_1_have_nearly_everything_lets_just/
  - https://www.reddit.com/r/CrazyIdeas/comments/6alqe1/make_a_handy_guide_of_democratic_and_republican/
  - impractical

    - https://www.reddit.com/r/CrazyIdeas/comments/6cu2yf/we_all_join_isis_so_there_isnt_anyone_left_for/
    - [[https://www.reddit.com/r/FunnyandSad/comments/7h7p3u/if_everyone_was_given_one_free_totally_legal_kill/][give everyone one free totally legal kill]]

- Who is Donald Trump's greatest opponent?

  - Donald Trump is the person who disagrees most with Donald Trump.

    - [[https://twitter.com/DonTrumpsTrump][Twitter: DonTrumpsTrump]],
      [[https://www.reddit.com/r/TrumpCriticizesTrump/][/r/TrumpCriticizesTrump]]
    - [[https://www.youtube.com/watch?v=kSE-XoVKaXg][YouTube: PlainSight: Trump exposes Trump]]

  - Ignore what politicians /say/.
    See what they /do/.
    See where their money comes from.
    See where their money goes to.
    Talk is easy.

    - But who is going to read through the
      [[https://en.wikipedia.org/wiki/List_of_executive_actions_by_Donald_Trump][list of executive actions by Donald Trump]]
      to find out who he really is?
      Will someone summarize?

- Who else trash-talk like Donald Trump does?

  - Thomas Jefferson, according to [[https://www.youtube.com/watch?v=ZIv7dQ9tt30][Adam Ruins Everything - Other Donald Trumps Throughout History]]
  - and lots of people in the colonial era, according to [[https://www.readex.com/readex-report/slinging-mud-and-talking-trash-gutter-age-american-journalism][Slinging Mud and Talking Trash: The Gutter Age of American Journalism]]

- Syrian war

  - [[https://www.quora.com/Is-Assad-bombing-his-people-If-so-why-do-many-people-support-him][Quora: Is Assad bombing his people? If so, why do many people support him?]]

- How do we fix the justice system?

  - Replace retributive justice with restorative justice.

    - Focus on fixing the damage, not on punishing people.
    - Norway gets the prison system right by "restorative justice" as opposed to American "retributive justice".

  - Society should help people fix their mistakes and reintegrate to society.

    - [[https://www.youtube.com/watch?v=RfU8TUZRtZg][Homeless guy spits some truth.]]

- [[https://www.youtube.com/watch?v=5tu32CCA_Ig][Corruption is legal in America]], 6-minute video

  - https://represent.us/
  - https://anticorruptionact.org/

- Wars are still happening. They just moved from overt to covert.

  - [[https://en.wikipedia.org/wiki/War_Is_a_Racket][WP: War is a racket]], Smedley D. Butler, 1935

- [[https://www.politico.eu/article/12-people-and-things-that-ruined-iran-energy-shah-regime-islamism/][Politico: 12 people and things that ruined Iran]]

  - Iran has a traumatic past. History has shown that it can't trust anyone, even its neighbor Iraq. Thus Iran wants self-sufficiency at all costs.
  - Self-sufficiency is a necessary but not sufficient condition for independence.

    - If you trade with other nations, you depend on them.
    - Trade (and specialization of labor) is beneficial for everybody if everybody is fair.

  - What is the difference between "independence" and "sovereignty"?

- Undigested

  - How can the minority control the majority?

    - https://en.wikipedia.org/wiki/Big_man_(political_science)

  - [[https://www.youtube.com/watch?v=rStL7niR7gs&feature=youtu.be][CGP Grey: The Rules for Rulers]]

    - "The Dictator's Handbook", Bruce Bueno de Mesquita

  - [[https://www.reddit.com/r/LateStageCapitalism/comments/7bd6xm/how_to_bribe_a_lawmaker_101/]["Lobbying" /is/ "bribing"]].
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/8i4y3a/new_un_report_finds_almost_no_industry_profitable/][New UN report finds almost no industry profitable if environmental costs were included]]
  - History, politics, military, war, weapon

    - https://www.reddit.com/r/explainlikeimfive/comments/1fy1na/eli5_why_did_joseph_stalin_kill_so_many_people/
    - [[http://www.historyisaweapon.com/defcon1/zinncol1.html][Native American Holocaust]]
    - Reddit: LateStageCapitalism

      - https://www.reddit.com/r/LateStageCapitalism/comments/6ilw3q/war_who_is_it_good_for/
      - https://www.reddit.com/r/LateStageCapitalism/comments/6cqcm3/if_youre_unemployed_it_is_not_because_there_isnt/

    - Best attack aircraft? https://en.wikipedia.org/wiki/Fairchild_Republic_A-10_Thunderbolt_II
    - What does manifest destiny have to do with American Imperialism?

      - [[https://en.wikipedia.org/wiki/Manifest_destiny][WP:Manifest destiny]]
      - [[https://en.wikipedia.org/wiki/American_imperialism][WP:American imperialism]]

  - [[https://www.ranker.com/list/the-best-way-to-fix-the-american-political-system/desertrat89][The Best Way to Fix The American Political System]]
  - History

    - https://history.stackexchange.com/questions/32480/why-would-some-nations-want-to-force-japan-to-end-their-isolation

  - [[https://www.youtube.com/watch?v=257wV-AbKaE][How does money laundering work? - Delena D. Spann]]
  - Free speech is only possible if people think critically.
  - Democracy is only possible if people think critically. - Democracy assumes that the electors are educated;
    otherwise the candidates will manipulate the electors
    using public media and sensitive issues. - Examples: - US in 2016 (Trump) - Indonesia in 2017 (Anies-Sandi)

    - [[https://www.youtube.com/watch?v=fLJBzhcSWTk][Why Socrates hated democracy]]?

      - Because the average person isn't competent to rule a country.

- YouTube: user: The school of life

  - [[https://www.youtube.com/watch?v=shanIOl7MyE][The Perfect Country]]
  - [[https://www.youtube.com/watch?v=Y9zThcMJzQU][How to Make a Country Rich]]

- Why is the US defense budget so huge?

  - https://www.reddit.com/r/explainlikeimfive/comments/3b5ogu/eli5_why_is_the_united_states_defense_budget_so/
  - https://www.quora.com/Why-does-the-United-States-have-such-a-large-military-budget
  - My guesses

    - The US defense budget is so huge because it's dealing with the entire Earth, not only the US?
    - Also, no competition in the defense sector?
      It's inefficient?
      It has no incentive to be efficient.
      Compare how competition (such as SpaceX)
      could cut down the cost of launching rockets.

- Why is Britain helping Israel?
- [[https://www.youtube.com/watch?v=rStL7niR7gs][The Rules for Rulers]]
- [[https://www.quora.com/Whats-the-story-of-SoftBank-Where-does-it-get-so-much-money-to-invest-from][Quora: What's the story of SoftBank? Where does it get so much money to invest from?]]

  - by investing in Alibaba

- If a law does not prescribe any punishment, will you obey it?
- Should we just die when we cannot pay the hospital bills?

  - If your death would ruin your family, should you have a family?

- Data source for salaries of various positions in the US: Foreign labor certification wage library

  - In the US, salary isn't secret, especially if you're a foreigner.

- No matter how evil or stupid politicians may seem, they do it with a reason?

  - Which makes it worse?

    - They're evil on purpose?

  - How do politicians reason?

    - Keep it simple?

      - If politicians are honest:

        - They represent their voters.

          - They reflect the people who vote for them.

  - Is [[https://en.wikipedia.org/wiki/Hanlon%27s_razor][WP:Hanlon's razor]] applicable?

- [[https://en.wikipedia.org/wiki/Politician][WP:Politician]]
- [[https://en.wikipedia.org/wiki/Politics][WP:Politics]]
- [[https://www.youtube.com/watch?v=3JVR0zAiyw0][YT:Putin on ideology - difference between Americans and Russians]],
  American individualisn, Russian collectivism
- [[https://www.quora.com/Is-there-one-website-to-daily-summarize-everything-that-is-going-on-in-Washington][Quora:Is there one website to daily summarize everything that is going on in Washington?]]
- [[https://en.wikipedia.org/wiki/Public_sphere][WP:Public sphere]]
- I don't always agree with these, but these have some useful things.

  - [[https://stallman.org/][Richard Stallman's personal site]]

    - What's bad about X (company)?

- [[https://www.reuters.com/article/us-usa-rights-un/americas-poor-becoming-more-destitute-under-trump-u-n-expert-idUSKCN1IY0C3][America's poor becoming more destitute under Trump: U.N. expert]]

  - https://www.theschooloflife.com/thebookoflife/countries-for-losers-countries-for-winners/

    - https://www.youtube.com/watch?v=kbpY-2nOYRI

- [[https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences][Why do politicians diverge from their constituents' preferences?]]

  - "the very idea of representative democracy is based on the fact that the preferences of the individual constituents
    do not make for good decisions in complex questions."
  - TODO group this with Socrates's argument

- Political economy

  - https://en.wikipedia.org/wiki/Employer_of_last_resort

    - https://en.wikipedia.org/wiki/Civilian_Conservation_Corps
    - [[http://www.levyinstitute.org/pubs/wp_534.pdf][Argentina: A Case Study on the "Plan Jefes y Jefas de Hogar
      Desocupados", or the Employment Road to Economic Recovery]]

- Justin Trudeau: "Donald Trump was elected on a promise to help the millions of middle-class families who feel left out of the success and progress of the past decades, and, interestingly enough, that is exactly the promise I got elected on, too."

  - https://www.quora.com/How-does-Justin-Trudeau-view-Canadas-relationship-with-the-US-in-light-of-Donald-Trump-winning-the-US-presidential-election/answer/Justin-Trudeau

- [[https://www.youtube.com/watch?v=c_Eutci7ack][How to understand power - Eric Liu]]
- [[https://www.youtube.com/watch?v=Cd0JH1AreDw][Eric Liu: Why ordinary people need to understand power]]

  - civics is the study of power
  - cities can practically bypass national governments

- Stop fluoridating water

  - Gaia: The Actual Truth About Fluoride, [[https://www.youtube.com/watch?v=HAagzF6D-nE][youtube]]

- [[https://www.politicalcompass.org/][Political compass]]: plotting economical-political views in two-dimensional space
- [[https://www.washingtonpost.com/world/asia_pacific/chinas-all-powerful-leader-should-heed-the-lessons-from-history-former-official-says/2017/11/09/22e7987a-c39a-11e7-a441-3a768c8586f1_story.html?noredirect=on&utm_term=.5dcdb36d3ff0][China's all-powerful leader should heed the lessons from history, former official says - The Washington Post]]
- We should limit inheritance.

  - Each child should inherit at most 1 house, 1 car, and cash sufficient for him to reach an age of 30.

- [[https://www.youtube.com/watch?v=o0ONByhAHC4][Why the wars America starts are unwinnable - Danny Sjursen - YouTube]]
- [[https://www.youtube.com/watch?v=U7DdgUAWR-s][What America gets wrong about China and the rest of Asia - David Kang - YouTube]]

  - China isn't a rising power. It has always been big.
  - Big nations have big internal (intra-nation) struggles.
  - Most big nations (such as the old Chinese dynasties) fall due to internal struggles.

- [[https://www.youtube.com/watch?v=pe4feBH0ABk][Richard Dawkins: No, Not All Opinions Are Equal---Elitism, Lies, and the Limits of Democracy - YouTube]]

  - Not all opinions are equal.

    - This goes back to Socrates.

  - If you have a surgery, you want an expert surgeon.
  - If you have a concert, you want an expert musicians.
  - Why then, when it comes to Brexit, do people suddently think they are expert politicians?

    - The people voting for Brexit might not even understand what the European Union is.

- Has Google been artificially diversifying its employees by discriminating against Caucasian and Asian men?
  See James Damore lawsuit.

  - [[https://twitter.com/jamesadamore][James Damore on Twitter]]

- [[https://www.youtube.com/watch?v=IESYMFtLIis][Why societies collapse | Jared Diamond - YouTube]]

  - One possible reason:

    - conflict of interest

      - Elites make self-serving decisions that are good for themselves in the short term but bad for the society in the long term.
      - Those elites don't directly feel the bad consequences of their decisions.

- China

  - http://www.cirosantilli.com/

    - https://github.com/cirosantilli/china-dictatorship/blob/master/FAQ.adoc

- The goal of a career politician is to get reelected.

  - How do we create a system that makes sure that one is reelected if and only if he works according to the people's desires,
    and one is taken down as soon as he strays from the people's desires?

    - How do we create a system that is robust, that depends only minimally on the electees, that works for a wide variety of malicious electees?

      - How do we make government fear the people, and people fear the government?
        How do we make mutual fear?

- [[https://www.youtube.com/watch?v=UyohSu-Ft_U][The Grand Theory of Amazon - YouTube]]

  - Amazon is a scale company.
    It specializes in scaling.

- The solution is to make corruption impossible and irrelevant.
- Work-for-hire (WFH) contracts should be illegal, and be replaced with irrevocable licensing.
  Every man should own his own labor.
  Work-for-hire contributes to social injustice.
- Solution to extremism/radicalism:
  Make it a law that every copy of Quran/Bible/other holy book must be accompanied with historical context.
  The book should prescribe how it should be interpreted.
  People should not invent their own interpretations.
  The interpretation must be justified by historical context.

  - [[http://aboutislam.net/counseling/ask-about-islam/why-does-the-quran-require-context/][Why Does the Quran Require Context? | About Islam]]
  - [[https://www.sbs.com.au/news/why-the-historical-context-of-the-qur-an-and-the-bible-cannot-be-ignored][Why the historical context of the Qur'an and the Bible cannot be ignored]]
  - synonyms: interpretation, exegesis, tafsir

- How much political power do we have?

  - [[https://www.theatlantic.com/magazine/archive/2015/07/power-quiz/395273/][How Much Political Power Do You Have? - The Atlantic]]
  - [[http://www.bbc.co.uk/guides/zpyr4wx][BBC iWonder - Do you know how much political power is in your pocket?]]

- office politics

  - [[http://www.yourofficecoach.com/coaching-resources/office-politics/political-games/how-much-political-power-do-you-have][How Much Political Power Do You Have? - Your Office Coach]]

- [[https://edition.cnn.com/2015/02/16/opinion/schmitt-politics-money/index.html][Money's power in politics: Give everyone a share - CNN]]
- [[https://www.crummy.com/2004/11/01/2][How To Exercise Political Power Part 1]]
* TODO reorganize; from indonesia.md
** Berinteraksi dengan pemerintah
   :PROPERTIES:
   :CUSTOM_ID: berinteraksi-dengan-pemerintah
   :END:

- [[https://www.reddit.com/r/indonesia/comments/97pzfs/adakah_cara_untuk_browsing_mencari_uu_permen_dll/][Adakah cara untuk browsing / mencari UU, PERMEN, dll berdasarkan topik? : indonesia]]

  - JDIH (Jaringan Dokumentasi dan Informasi Hukum)

Kontak DPR, sampaikan aspirasi
Kenapa ada banyak cara?
Yang mana yang dipakai?

- http://www.adangdaradjatun.com/berita-dpr/1769-cara-mengadu-ke-dpr
- http://satulayanan.id/layanan/index/92/pengaduan-anggota-dpr/dpr-ri
- https://pengaduan.dpr.go.id
- http://www.dpr.go.id/index/kontak
- https://mobile.twitter.com/DPR_RI/status/558192636222132224
- http://rumahaspirasi.dpr.go.id/layanan
- http://m.metrotvnews.com/play/2015/03/22/374732

*** Mengubah sistem hukum dari retributive justice ke restorative justice
    :PROPERTIES:
    :CUSTOM_ID: mengubah-sistem-hukum-dari-retributive-justice-ke-restorative-justice
    :END:

- http://ksp.go.id/pemerintah-luncurkan-portal-aspirasi-dan-pengaduan-nasional/index.html
- Bergabung saja ke ANRKUHP.
  Liaison ANRKUHP dan RJI (Restorative Justice International/Indonesia)?

  - https://m.cnnindonesia.com/nasional/20180612195019-12-305684/icjr-dorong-20-hukuman-alternatif-selain-penjara-di-rkuhp

- ICJR.

Kapan terakhir kali RJI mengirim surat/email ke DPR?
Surat tersebut ditujukan kepada bagian DPR yang mana?

*** Jangan penjarakan koruptor. Cukup sita curiannya.
    :PROPERTIES:
    :CUSTOM_ID: jangan-penjarakan-koruptor.-cukup-sita-curiannya.
    :END:

Koruptor tidak takut dipenjara.
Koruptor takut miskin.

** Deradikalisasi seperti Singapura
   :PROPERTIES:
   :CUSTOM_ID: deradikalisasi-seperti-singapura
   :END:

Contohlah Singapura.
Mereka mencampur penduduk berbeda suku dalam setiap pemukiman.

** Cara memilih anggota DPR dan DPD
   :PROPERTIES:
   :CUSTOM_ID: cara-memilih-anggota-dpr-dan-dpd
   :END:

- Anda memilih partai politik. Anda tidak memilih anggota DPR secara langsung. (UUD 1945 pasal 22E ayat 3.)
- Anda memilih anggota DPD secara langsung. (UUD 1945 pasal 22E ayat 4.)

Cari dan pahami latar belakang, profil, dan cita-cita partai-partai politik.

Pilih partai yang cita-citanya sejalan dengan cita-cita Anda.

Partai tersebut akan menempatkan beberapa anggota mereka di DPR.

Bantu mereka melaksakan tugas dengan memberi saran, melaporkan penyimpangan, dll.

** Mencari partai
   :PROPERTIES:
   :CUSTOM_ID: mencari-partai
   :END:

Saya mencari partai orang yang berpikir mandiri.

** Komputerisasi untuk menidakmungkinkan korupsi?
   :PROPERTIES:
   :CUSTOM_ID: komputerisasi-untuk-menidakmungkinkan-korupsi
   :END:

Karena komputer zakelijk.
Tidak ada kongkalikong.

** Tumpang tindih tugas BPK, KPK, polisi, bareskrim, tim tastipikor, dll.?
   :PROPERTIES:
   :CUSTOM_ID: tumpang-tindih-tugas-bpk-kpk-polisi-bareskrim-tim-tastipikor-dll.
   :END:

Semuanya sama-sama memeriksa keuangan.

** Hancurnya negara ini adalah salah kita yang menolak berpolitik.
   :PROPERTIES:
   :CUSTOM_ID: hancurnya-negara-ini-adalah-salah-kita-yang-menolak-berpolitik.
   :END:

Menolak berpolitik berarti membiarkan negara hancur.

Menolak berpolitik berarti membiarkan pengacau menang.

Membiarkan kesalahan artinya ikut salah.

Membiarkan penindasan artinya ikut menindas.

Membiarkan ekstremis merajalela artinya merestui ekstremisme.

[[https://en.wikipedia.org/wiki/First_they_came_...][WP:First they came...]]

** Legislatif lebih penting daripada eksekutif.
   :PROPERTIES:
   :CUSTOM_ID: legislatif-lebih-penting-daripada-eksekutif.
   :END:

Media harus lebih banyak meliput legislatif daripada eksekutif.

Selama ini media salah.
Yang diliput eksekutif terus.
Legislatif lebih penting.

Legislatif membentuk sistem.

Legislator bagus akan mencegah eksekutor buruk.
Eksekutor bagus tidak bisa mengatasi legislator buruk.

Lebih mudah meliput eksekutif karena ada kegiatan yang tampak.

Meliput legislatif lebih susah karena harus mengerti filsafat hukum.

** Fadli Zon Library
   :PROPERTIES:
   :CUSTOM_ID: fadli-zon-library
   :END:

[[https://id.wikipedia.org/wiki/Fadli_Zon_Library][WP:Fadli Zon Library]]

Ada kajian/diskusi?
Jadwal?

** Mengatasi sesat pikir
   :PROPERTIES:
   :CUSTOM_ID: mengatasi-sesat-pikir
   :END:

- [[http://partaigerindra.or.id/2015/04/28/gerindra-dukung-eksekusi-mati-agar-bandar-narkoba-jera.html][Gerindra Dukung Eksekusi Mati Agar Bandar Narkoba Jera]]

  - Orang mati mana bisa jera (kapok)?
    Kalau mau bikin orang jera, suruh dia ganti rugi.
    Obati semua korbannya.
    Kembalikan masa depan mereka yang hilang.
    Bayar.

** Narasi berbeda antara eksekutif dan legislatif
   :PROPERTIES:
   :CUSTOM_ID: narasi-berbeda-antara-eksekutif-dan-legislatif
   :END:

Eksekutif bilang ekonomi tumbuh.
Legislatif bilang hidup makin sulit.

Dua-duanya betul.
Ekonomi tumbuh.
GDP memang tumbuh.
Tapi apa arti GDP?
* Memakai hak warga negara?
** BPJS?
- [[https://daftar.bpjs-kesehatan.go.id/bpjs-checking/][Cek saldo BPJS]]
- [[https://sso.bpjsketenagakerjaan.go.id/registrasi.bpjs][Ini registrasi apa?]]
  Kenapa harus registrasi?
** Mendirikan perusahaan?
- Bagaimana?
- Bayar berapa?
- Berapa lama?
- Apa keuntungan pajak?
** Pemerintah menyediakan akses ke jurnal berbayar? Di mana? Cara pakainya?
** Jangan abstain dalam pemilu.
Lihat argumen [[https://www.reddit.com/r/indonesia/comments/968qbs/ajakan_untuk_yang_tidak_cocok_dengan_pasangan/e3yw8bd/][/u/kolormelar]].
* How do we scale democracy?
** How do we make elections cheap, easy, trustworthy (independently verifiable), and scalable?
Paper ballots can be independently verified.
Machines can't.

Trustworthiness requires that the system can be independently verified (by a third party, by a non-government organization, by local people, by anyone who cares).

How can we ensure verifiability while maintaining secrecy?

Every citizen has a private key?

Rachel Tobac:
"At @defcon hacking conference and just learned how easy it is to physically gain admin access on a voting machine that is used in 18 states.
Requires no tools and takes under 2 minutes.
Im concerned for our upcoming elections."
https://twitter.com/RachelTobac/status/1028437783050776576

https://arstechnica.com/information-technology/2018/09/e-voting-researchers-warn-of-hack-that-could-flip-the-electoral-college/
* <2018-10-03> It's 2018, but people still believe in flat Earth and trickle-down economics.
According to https://www.forbes.com/sites/teresaghilarducci/2018/09/28/who-benefits-from-the-tax-cut-10-months-later/#3af0b9dc26bb:
- "Buybacks are attractive because most CEO pay is directly linked to stock values and not to productive capital expansion."
