#+TITLE: Topics in politics
#+DATE: 2019-11-28 00:00:00 +0700
* <2020-01-19> My view have changed again
I will no longer write about politics.

Abundance and spirituality obviate politics.

Politics, like materialism, was useful, but they have overstayed their welcome.
* <2018-11-19> I changed my mind. Now I think most of this page is a waste of time.
Thanks to John Stossel and Steve Patterson.

If I could solve the libertarian children problem, I would be a libertarian by now.

Is antinatalism against nature?
Yes, if humans have innate drive to breed (to have have an offspring).
No, if humans have innate drive to fuck only (to satisfy the genitals, not including breeding).

I'm more inclined toward survivalism than antinatalism.

Antinatalism is noble but impractical.
The reality is that billions of low-IQ people are going to fuck and breed anyway,
producing low-IQ children who never question anything, repeating the stupidity of their parents, perpetuating the cycle.
But this may be practical in the future:
Inconspicuous forced mass sterilization!
Airborne human-sterilizing nanobots!
Human-sterilizing viruses!
Infertility-causing foods!
http://wiki.c2.com/?HumanSterilizationVirus

Is this just a waste of time?
Is this going to change anything?
- Establish a benevolent dictatorship with these principles:
  - Peace of mind.
    - No overtime.
    - No deadlines.
    - No loans.
    - If growth robs you of peace of mind, don't grow.
* Power uncovers, not corrupts
<2019-11-27>

"In sum, the study found, power doesn’t corrupt; it heightens pre-existing ethical tendencies."
https://www.smithsonianmag.com/science-nature/why-power-corrupts-37165345/
* Using child psychology to make politicians behave
<2019-11-28>

Some people have been suggesting that we operant-condition the politicians.
I think that's a brilliant idea.
The premise is: somehow politics make people childish,
so we apply child psychology to make politicians behave.
We praise them whenever they say the truth, and we ignore them whenever they lie.

Perhaps politicians are even simpler than children;
perhaps they are like animals, like dogs, which is why operant conditioning works on them.

If politicans are childish, then the people have to be the parents; otherwise the country is all whim.

https://www.politico.com/magazine/story/2019/10/22/how-to-trick-trump-into-telling-the-truth-229874

https://medium.com/@JessicaLexicus/operant-conditioning-for-presidents-4fc8cd5d6c74
* On ethical consumption
<2019-11-17>
** <2019-11-27> Dissenting opinions
Wicker 2017[fn::<2019-11-27> https://qz.com/920561/conscious-consumerism-is-a-lie-heres-a-better-way-to-help-save-the-world/]
argues that ethical consumerism is not enough to save the world.

If everyone know what truly matters for them, we won't have an environmental crisis.

Not only do you need to pick what you consume, you need to consume less.

Either we change the system, or we use mindfulness to immunize the people against the broken system.

Ethical consumption is not enough; we need everyone to live mindfully; we need a global spiritual revolution.
** The immorality of companies reflects the immorality of consumers
Consumers are the masters of companies, because companies need money from consumers to live.
Consumers are even more powerful than shareholders, because shareholders get their money from consumers too.

For example, Amazon's mission is "to be Earth's most customer-centric company"[fn::<2019-11-18> https://www.amazon.jobs/en/working/working-amazon].
If consumers want cheap things fast, then so be it, workers be damned.

Profit is a feedback signal that indicates that the company is doing what consumers want.
Thus, if we buy from Amazon because it is cheaper,
we are voting for getting workers to do maximum work with minimum pay;
otherwise our things wouldn't be as cheap and fast as they are today.

If consumers want food to be delivered to their houses, then so be it, environment be damned.

If consumers want new stuff every year, then so be it, environment be damned.

Companies are not the only ones to blame; all of us are to blame for having endless desires.

Everytime we buy something, we make a moral judgement, even if we don't realize it.

Companies are simply doing what the consumers want.
If the consumers want cheap things, then so be it, workers and environment be damned.
Thus, the immorality of companies reflects the immorality of consumers.

We often buy something without caring about how it is made.
We turn a blind eye to the immorality of producing that thing.

The consumer's beliefs determine the company's behavior.

Buying from immoral companies means /voting for immoral behavior/.
** How can we care?
It seems impractical for one person to check every building, every mine, and every employee of all companies.

We establish an organization that summarizes the immorality of companies
so concisely that consumers can easily act on that report.
We must establish a moral police for policing the morality of companies.

Consumers must unite, prefer, and demand moral companies.

In 2019, I define the adjective "moral" to mean "not detrimental to the survival of the human race"
(my moral system in 2019 is natural morality),
but you can define "moral" to mean anything that suits your moral system.
For example, if you follow Jesus,
then you may define "moral" to mean "that would not be disapproved by Jesus".

To survive, we have to both think and feel.

To change the world, we must first change ourselves.
** What if we need something that is produced by only one company?
How are foods going to be delivered to our houses if not with plastic packaging?
The only alternative is to move the people instead of moving the food,
but aren't we all too lazy to walk to the restaurant?

How are we going to get electricity?

What if we need something that is produced by a monopoly with high barrier to entry?

Boycott the company, and put our lifestyle down a notch?

We can always choose to not buy (and perhaps suffer or die).

We can always kill ourselves, although we usually won't.

The crisis is a question to us: Which do we prefer:
much convenience but much environmental destruction,
or some inconvenience but slight environmental destruction?
** Other resources
- <2019-11-17> https://en.wikipedia.org/wiki/Ethical_consumerism
- <2019-11-17> https://en.wikipedia.org/wiki/Dollar_voting
- <2019-11-18> https://en.wikipedia.org/wiki/Consumer_activism

* English
- [[file:boeing.html][The root cause of Boeing 737 MAX fiasco: existentially-threatening competitions?]]
* Bahasa Indonesia
- [[file:cara-memilih-pejabat.html][Cara memilih pejabat dalam sebuah demokrasi]]
** <2019-08-20> Pengguna narkoba adalah korban, bukan penjahat
Pengguna narkoba harusnya ditolong, bukan dipenjara.

Korban memakai narkoba karena terisolasi secara sosial (merasa kesepian).

Penjara tidak menyelesaikan apapun.

Penjara adalah masalah, bukan solusi.

Untuk mengatasi narkoba, contohlah Portugis yang berhasil, dan jangan contoh Amerika yang gagal.
* <2019-08-21> Politics rule no 1: Avoid angering the majority
Avoid angering the majority.

If the majority are idiots, it is even more important to avoid angering them.

Even if you know the truth, avoid angering the majority.

(Isn't this common sense?)
* Unfortunately auto-segregation is rational
Every man thinks that it's much easier to move to where the "smart" people are than to fix the "idiots" around him.

For example, non-Muslim people would not want to live near mosques because mosques are noisy,
but Muslims would want to live near mosques because they go there very often.
Thus, those two groups have just automatically segregated themselves without anyone's help.
* Seeking the truth?
** Gun rights is now about selling guns for profit, no longer about fighting tyrannical governments
<2019-08-15>

In 2019, anyone who thinks that guns can protect them from tyrannical governments is deluded.
Governments have better guns, soldiers, cops, bombs, planes, drones, tanks, nukes, and a monopoly on violence bigger than ever in history.
Nevertheless, guns can be used to terrorize government employees to discourage people from working for the government,
 [fn::https://www.bbc.com/news/amp/world-us-canada-49339903]
but I don't recommend that,
and I don't plan to discuss asymmetric warfare[fn::https://en.wikipedia.org/wiki/Asymmetric_warfare] and militant anarchism here.

Thus the only reason left for gun rights is to let people sell guns for profit.
** Constitutions are not holy books
<2019-08-16>

Changing constitutions is almost as hard as changing bibles.
Constitutions have become holy books, and political ideologies have become religions.
Blind beliefs are bad for progress.

Constitutions should be hard to change,
because it is the foundation of all other laws in a country.
A constitution that changes often will confuse everyone.
Unfortunately, this also means that a bad constitution will stay bad forever.
** <2019-07-06> Borders are lawless places
*** <2019-07-06> Use a new clean phone that is not logged into anything, when you go abroad
Customs are lawless.
Borders are lawless places.
Laws are not enforceable at borders.
Rights do not exist at borders.
China forces travelers to install malware.[fn::https://www.slashgear.com/china-forces-malware-on-tourist-phones-at-border-heres-what-they-want-02582568/]
USA customs harass.[fn::https://www.schneier.com/blog/archives/2019/04/former_mozilla_.html]

Border Patrol had a secret Facebook group.[fn::https://theintercept.com/2019/07/05/border-patrol-facebook-group/]

Customs officials can make their own laws because they face no consequences:
There is no practical way to hold them accountable for their actions.
Also, people don't care.

Before we blame border patrol, we should try to empathize.
Are they underpaid?
Are they at risk?
Is their job dehumanizing or demoralizing?
Have we allocated them enough resources necessary for their job?
Is the system broken?
** Platforms and antitrust laws are inherently incompatible
A platform is only useful if everybody uses it, but if that is the case, then it has become a monopoly.
But monopolies are illegal?
Thus, are platforms illegal?

One can mitigate monopolies by requiring interoperability?
** <2019-08-17> British imperialism?
Opium wars?[fn::https://amp.cnn.com/cnn/2019/05/26/opinions/china-is-not-the-enemy-sachs/index.html]
** <2019-08-17> Entrepreneurial employee is exploitation
Work as hard as entrepreneurs, get paid as low as employees.
** <2019-08-20> On the false assumptions of deterrence theory
What is the point of making a weapon so powerful that you would rather not use it?
What is the point of living under constant fear?

https://www.theguardian.com/world/2018/jan/14/nuclear-deterrence-myth-lethal-david-barash
** <2019-08-20> What is natural economic growth?
As fast as /lives/ can grow: plants, bacteria, etc.
If you grow faster than natural, you are extracting some wealth?
** Can inventors profit without patents?
How?

Sell the invention as a service?

Are trade secrets protected?

Patents pros:
- incentivize innovation

Patents cons:
- encourage patent trolling and gaming the legal system for personal financial gain at the expense of others

https://en.wikipedia.org/wiki/Economics_and_patents
** <2019-07-06> Is freedom of speech important?
Examples of degrees of freedom of speech:
- In USA and Canada, you can talk shit about the government, as long as you don't make death threats, or the cops will get you.
- In Indonesia, you can disagree with the government, but you have to do it very politely, or you will be jailed.
- In China, if you disagree with the government, your will be encumbered, if not killed.
- In Saudi Arabia, if you disagree with the government, you will be killed.

But all government is more similar than different:
There is always centralization of power, and therefore abuse of power.

Without freedom of speech, life goes on pretty much normally in Indonesia.
Meanwhile, the USA, for all its free speech, still has problems like crony capitalism
and highest gun-related murder which is totally preventable
as shown by the Australians.

Why do you insist on owning a gun?
It does not protect you from a tyrannical government.
They have bombs, armies, nukes, soldiers, cops, gunboats, aircrafts, hackers, money, what else.
If you think your teeny-pistol militia can beat them, you're as deluded as Don Quixote;
but actually he has better chances than you do,
because windmills don't fight back, whereas governments do.
The freedom to bear arms is just a ceremonial distraction
from more important issues such as imperialism, privacy, and borders.
** <2019-07-06> Gerrymandering
Gerrymandering is a self-inflicted pain with a simple solution:
proportional representation[fn::https://www.fairvote.org/how_proportional_representation_would_finally]
 [fn::https://www.sightline.org/2019/05/03/the-secret-to-ending-gerrymandering-isnt-a-secret/].
Drawing district lines is like punching yourself in the face and wondering why it hurts.
The fix is simple: Just don't do it.

How does Alabama have a government that does not represent its constituents
 [fn::https://qz.com/1628427/saudi-arabias-abortion-laws-are-more-forgiving-than-alabamas/]
 [fn::https://www.motherjones.com/politics/2019/05/previously-unreleased-poll-shows-alabama-voters-disapprove-of-extreme-abortion-ban/]
 [fn::https://www.vox.com/policy-and-politics/2019/5/18/18630562/alabama-abortion-ban-voters-exemption-for-rape-incest]?
Gerrymandering?
** On the firehose of lies
“Don't try to fight the firehose of falsehood with the squirtgun of truth,” Paul said. “Try to put 'raincoats' on those who will be hit with the firehose.”
 [fn::https://www.rand.org/blog/2016/12/beyond-the-headlines-rands-christopher-paul-discusses.html]
 [fn::https://www.youtube.com/watch?v=i1pA1kpJosk]
** Bush's Iraq War
Bush attacked Iraq to reaffirm American hegemony.[fn::https://www.aljazeera.com/amp/indepth/opinion/bush-war-iraq-190318150236739.html]
That is, he did it just because he could.
** What is the problem with West Java?
Jawa Barat: sudah berpenduduk terbanyak[fn::https://ilmupengetahuanumum.com/jumlah-penduduk-indonesia/],
sarang ekstremis pula.[fn::https://www.jpnn.com/news/mms-sebut-jawa-barat-sarang-ekstrimis]
Tapi yang sering ada bom masuk berita bukannya Jawa Timur?
Sama-sama teroris tapi beda cabang?
** Sejarah Islam Indonesia
https://www.nu.or.id/post/read/71691/awal-mula-masuknya-islam-di-indonesia-menurut-mbah-maimoen-
** There is no such thing as "straight", "gay", or "lesbian"
Men have been putting their dicks wherever they want to since humans existed:
in their own hands, in other women, in other men, in goats, in horses, you name it, someone has tried to put their dick in it.

Perhaps women also have the same problem: you name it, someone has tried to put it in their vagina.

Perhaps humans just like sex.
** Examples of costly cost-cutting when management overrides engineers
I used to argue for nuclear fission power.
Now I argue against nuclear fission power, not because it is harmful, but because companies cannot be trusted.
I feel that companies are inherently incompatible with humanity; they centralize power to shareholders.

I trust engineers and scientists, but I don't trust companies.
If a nuclear power plant is run by a company, it is just a matter of time
before someone in management cuts costs for short-term profit,
skimps on something, dismisses the engineers, and causes an accident.
It has happened with airplanes (such as Boeing 737 MAX, they cut corners because they were competing with Airbus),
nuclear fission power plants (such as TEPCO Fukushima, they ignored an engineer's concern about the backup pump's vulnerability to giant tsunami).

When you ignore an engineer, a disaster will happen,
and you will bear a much higher cost than what would cost you if you just did what the engineer told you to do.
Disrespecting engineers and scientists is disrespecting Nature, and /Nature does not care about your profits./
** An insightful clustering of America into 11 nations
https://www.npr.org/2013/11/11/244527860/forget-the-50-states-u-s-is-really-11-nations-says-author
** South Korea quits Windows cold turkey?
https://betanews.com/2019/05/18/korea-linux/

What about "Indonesia goes open source"?
** FairTube, and renaming "advertising"
I hope FairTube wins, but the root cause of the problem is that today's "advertising" is about /making people buy/,
by psychological manipulation, by all means, at all costs;
whereas the original 15th century meaning of "to advertise" is to "give notice to others"[fn::https://www.etymonline.com/search?q=advertise].
There was no sense of persuasion in the 15th-century advertising.

In 2019, "advertising" is about manipulating people into buying things, by all means not forbidden by law.
Thus what we call "advertising" now, we should call "for-profit psychological manipulation".
** I'd rather have police not work than have them incentivized to catch people
Incentivizing police to catch people is extremely dangerous;
I'd rather have police not work than have them eagerly incriminate people.

Police should not be rewarded for making arrests.
Police should not be rewarded for successful trials.
** On modern monetary theory, taxes, incentives, behaviors
We should think of /taxes/ as a way for /incentivizing/ behaviors, /not/ for /funding/ government programs.
The government can just create money out of nothing, as long as the money creation rate does not exceed the real economic growth rate.
Indeed, right now, banks are creating money out of nothing, in the form of loans,
and these virtual numbers can have real effects on prices:
If, at the same time, one million people get loans and buy cars,
then there will be a short-term shortage of cars (demand surge),
and producers may decide to increase production or raise prices or both if the surge persists.

But what if the real economy is shrinking?
* Crazy ideas?
** <2019-08-14> Elections should have an entrance fee
The amount is not important, but should be low, but not zero.
What is important is that an entrance fee /exists/.

When a surgeon fails, he injures one people.
When a car driver fails, he injures ten people.
When a lawmaker fails, he injures millions of people.
Then why do we insist on lower standards for our lawmakers than for our surgeons?
Why do we elect clueless clowns and self-enriching thiefs into the government?
/Because we pay for a surgery but not for an election/.
Paying for something increases our expectation.
We don't pay for an election, so we expect nothing.

But companies do pay for elections, through contributions and lobbyings.
Thus companies expect to gain from elections, while people don't.
** <2019-08-14> We need a World Government
These entities may have done things that would be considered atrocities by 2019 standards:
Muhammad
 [fn::https://wikiislam.net/wiki/List_of_Killings_Ordered_or_Supported_by_Muhammad]
 [fn::Why Did Carl Jung Compare Hitler To Muhammad? https://www.youtube.com/watch?v=BzlESr-2cZ4],
Suharto[fn::https://indonesiaatmelbourne.unimelb.edu.au/theres-now-clear-proof-that-soeharto-orchestrated-the-1965-killings/],
the United States of America[fn::https://en.wikipedia.org/wiki/United_States_war_crimes],
the British Empire[fn::https://www.independent.co.uk/news/uk/home-news/worst-atrocities-british-empire-amritsar-boer-war-concentration-camp-mau-mau-a6821756.html],
many imperialist European countries,
Mao[fn::https://en.wikipedia.org/wiki/Mass_killings_of_landlords_under_Mao_Zedong],
Stalin[fn::https://en.wikipedia.org/wiki/Excess_mortality_in_the_Soviet_Union_under_Joseph_Stalin],
Hitler[fn::https://en.wikipedia.org/wiki/The_Holocaust],
Genghis Khan,
and many more[fn::https://www.hawaii.edu/powerkills/NOTE1.HTM][fn::https://en.wikipedia.org/wiki/Democide],
if not everyone.

/But only Hitler lost the war./

Thus now Hitler is condemned, whereas the others are venerated.

It is a crime to murder one person.
It is not a crime to wage an unjust war /and win the war/
because the winner gets to define what "crime" is, and then he gets to write the history.
This is just human nature.
Even I myself suffer from that:
I often find myself imagining the killing of billions of people,
be it by my own hands or by a natural catastrophe,
and I imagine the peace that follows, the problems that disappear,
the overcrowding gone, the pollution gone, the noise-makers gone, the exorbitant land prices fall.

There is no government for countries,
and thus countries go to war against other countries.
At the level of citizens, there is a rule of law,
but at the level of countries, it is anarchy.
Thus it seems that there has to be a government for governments,
but this suffers from infinite regress:
second-level governments may go to war with each other,
and so on.
Thus, the only way to global peace is /to have exactly one government for all people/, one World Government,
because it is impossible to have a war if there is nobody else to wage a war against,
that is, if you are the only government in the world.
This is the only way to prevent wars.

This World Government should be filled with scientists and engineers
because they do politics better than politicians do;
see China[fn::https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers],
but it's changing in 2017.[fn::https://www.scmp.com/news/china/policies-politics/article/2117169/out-technocrats-chinas-new-breed-politicians]

But people are too chauvinistic, too egoistic, and too proud for a World Government.
All nationalism is chauvinism, because we are all citizens of the Earth.
As technology is heading toward a singularity,
human culture is also heading toward a singularity.

Having different governments also enables tax avoidance, money laundering, and wage slavery,
by enabling one to arbitrage different regulations in different countries.
** <2019-08-14> People, not beliefs, deserve respect
We can respectfully treat people who believe unjustifiable things such as religions, superstitions, but we should not respect their beliefs.
If we facilitate some people with stupid beliefs, it is not because we respect their beliefs, but because we respect their feelings.

But this is impractical.
People interpret attacks on their beliefs as attacks on their selves.

Not all opinions are equal:
- [[https://www.youtube.com/watch?v=pe4feBH0ABk][Richard Dawkins: No, Not All Opinions Are Equal---Elitism, Lies, and the Limits of Democracy - YouTube]]
  - If you have a surgery, you want an expert surgeon.
  - If you have a concert, you want an expert musicians.
  - Why then, when it comes to Brexit, do people suddently think they are expert politicians?
    - The people voting for Brexit might not even understand what the European Union is.
** <2019-08-20> Common law is more agile than civil law
Civil law is always late, because we suck at foretelling.
In civil law, everything is legal until legislators make a law against it.

But common law requires higher standards for judges, whereas judges are fallible humans too, just like the rest of us.

Humans are not computers.
Humans excel at following the /spirit/ of the law.
Computers excel at following the /letter/ of the law.
Indeed humans who strictly follow the letter of the law may be malicious.

Lawmakers should make principles, not rules.
Lawmakers should explicitly state the spirit and intention of the law,
not just the letter of the law.
** Growing food is the best solution to poverty
Growing food is the only sane way to lift many people out of poverty, because /Nature pays everyone who works/.

It reduces unemployment, poverty, homelessness, crime.

Example[fn::https://www.bbc.com/indonesia/majalah-47052996]

A scalable solution to poverty?

1. Relocate poor people to fertile land that is unused but not too far from civilization; give each family 100 square meters.
2. Help them grow food; educate and train them. Pay attention to ecology, and close the nutrient cycle.
3. Help them sell their production.

This simultaneously solves hunger, poverty, homelessness, overcrowding, and crime.

This reduces agricultural failure risk:
More small farms distributed geographically means we have more backups to a regional catastrophe.

Indonesia will lose 20% corn production by 2050 due to climate change?
 [fn::https://medium.com/@jeremyerdman/we-produce-enough-food-to-feed-10-billion-people-so-why-does-hunger-still-exist-8086d2657539]
* Capitalism exploits individual selfishness to benefit everyone?
Capitalism assumes that humans are bad and selfish.
Communism assumes that humans are good and altruistic.
In reality, most humans are between those two extremes.

In capitalism, X helps Y because X wants Y's money.
Capitalism assumes that there is only unconditional selfishness and no unconditional love.
Capitalism is about making the desire to gain money coincide with the desire to better humankind.

In communism, X helps Y because X has unconditional love for everything.

There are no pure capitalism and no pure communism.
Humans are somewhere between totally selfish and totally altruistic.

Everyone wants to maximize their own profit.
Everyone only cares about themselves.
Therefore, a system must be created, such that selfish people can only profit by benefiting others.

What does a system incentivize?
* Unions?
Who does a union benefit?
The incumbent workers?

Do laborers have less bargaining power than capitalists?

https://www.quora.com/Why-do-some-people-hate-labor-unions

https://en.wikipedia.org/wiki/Opposition_to_trade_unions
* <2019-08-14> Groups diffuse blame
A perverse situation may arise, in which the individual is praised for success, but the group is blamed for faults,
perhaps due to our desire to feel good and avoid conflicts.
An example of such perverse situation is the belief "If this country advances, it's due to the president; if this country regresses, it's due to the government",
or "If this company profits, it's due to the director; if the company loses, it's due to everyone".
* <2019-08-14> Why are corporations legal people?
Corporations are legal people so that they can be sued and brought into court.
 [fn::https://www.forbes.com/sites/timworstall/2012/11/17/ill-believe-corporations-are-people-when-texas-executes-one-what-is-this-foolishness-from-robert-reich/#78f1f29633f2]
* Core beliefs
If a belief conflicts with reality, then the belief must change.

We define "good" as "promoting the survival of the human species".

/Nationalism is collective egoism./
There should be only one government on Earth, and it should be The Only World Government,
because otherwise governments will fight each other due to national egoism.

We prefer to be /sober/ and savor every moment of our lives.
The only time we use consciousness-altering drugs is in great pain, such as in surgeries or in terminal illnesses.
We do not drink alcohol to the point of intoxication.

/We hate smoke/: cigarettes, vapes, you name it, we hate it.
We do not smoke.

/We hate perfumes./
We prefer no odor at all.
We prefer slight natural body odor to perfumes.

We think a little dandruff and a little body odor is normal.

We treat most bacteria as essential, not as things to be eradicated.
We only use antibiotics if it is the only way to save us from death.

We do not want to change the status quo for the sake of change without reason.
Disruption is not something to be proud of.
Every change has unintended consequences.

We prefer /sustainability/ to growth.

/Leisure/ is noble and there is nothing shameful about wanting leisure, seeking sustainability, and shunning gratuitous growth.

/Pension is robbing the young to pay the old./
It assumes that the population pyramid will always have a certain shape.
It is not sustainable.
* <2019-08-21> Hiring from trading point of view: buy low sell high
Everything is trading: Buy low, sell high.

Hiring is trading too.
Buy labor cheap, sell products high.

Labor has maintenance costs, just like machines.
Skimp on machine maintenance, they break down.
Skimp on labor maintenance, they resign, or worse, they riot, or even worse, they unionize.
* <2019-08-21> Capitalism and morality?
From https://evonomics.com/role-of-morality-in-a-capitalist-economy/
#+BEGIN_QUOTE
Now, what do you mean social good? In economics and evolution we have a well-defined concept of public goods.
Production of public goods is individually costly, while benefits are shared among all.
I think you see where I am going.
As we all know, selfish agents will never cooperate to produce costly public goods.
I think this mathematical result should have the status of “the fundamental theorem of social sciences.”
#+END_QUOTE
* Seek wealth, not money
If one wants to be rich, then one should seek wealth, not money.
One should always know that money is only a proxy of wealth, and the conversion of money to wealth always depends on who is willing to accept that money.
* <2019-10-28> Anarchy, selfishness, institutions
Humanity should not try anarchy before humanity can overcome its own selfishness.

Anarchy cannot work with selfish people.

Capitalism is the system for making selfish people help others.

Capitalism assumes the least of humans.
Capitalism does not assume that people are good.

If humans were not selfish, anarchy would work much better than capitalism did.

Often we do not have the luxury of assuming that people are good.

But the total wealth in the 21st century is much higher than the total wealth in the 20th century.

/Can humanity accomplish great things without institutions?/

Even without formal institutions, there will be de-facto makeshift institutions headed by experts who know what to do, established by people who have power.

Institution is one way of doing something that takes more than the lifespan of one human.

Institutions suck, but perhaps they are better than the natural state of man that is anarchy,
but anarchy would be the best if humans were able to overcome their selfishness.
Anarchy would only work if most people were very altruistic.
* <2019-07-06> Blinking Morse code as covert communication channel
Jeremiah Denton signals "torture" by blinking on TV while he was a war prisoner in Vietnam.
 [fn::https://qz.com/1625459/learning-morse-code-is-a-valuable-skill-even-in-the-21st-century/]

* <2019-08-20> Atomic Shrimp's fun way to deal with scammers: "Reply all"
"Bringing Scammers Together (Not Harmonious!) - Scambaiting By Reply-All"[fn::<2019-10-27> https://www.youtube.com/watch?v=py-cQ5PscsU]

That is fun but perhaps unsuitable for average people;
perhaps it would be better for average people to not reply at all.

* <2019-07-07> Using government data?
Marc Dacosta: Adventures in the Dark Web of Government Data[fn::https://www.youtube.com/watch?v=SzkyuGeNDf8]:
joining multiple disparate data sources.

* Junk?
** Suspicious things; things to keep track; things to recheck next year
*** <2018-10-04> Amazon raises its warehouse worker wage (hourly pay) from about $8 (?) to $15 (minimum wage).
- https://news.vice.com/en_us/article/yw4n7j/jeff-bezos-just-caved-to-activists-and-bernie-sanders-and-raised-amazons-minimum-wage-to-dollar15
**** Find out 1 years later: Compare the number of blue-collar workers.
*** <2018-10-06> Swiss banking is no longer secret. Does this reduce international crimes / money laundering?
- "Era of bank secrecy ends as Swiss start sharing account data"
  https://www.reuters.com/article/us-swiss-secrecy/era-of-bank-secrecy-ends-as-swiss-start-sharing-account-data-idUSKCN1MF13O
*** <2018-09-26> Why is Nikkei Asian Review sponsoring Mochtar Riady stories?
** The other side of Trump
The non-media's opinion of Trump:
"Actions Speak Louder Than Words: The Real Donald Trump"
https://www.youtube.com/watch?v=zRogXTFtpUc

Publishers scramble to cash-grab, slaps "Trump" on anything, crap literature
https://www.youtube.com/watch?v=wB8bJyjr_Ao

Trump is sometimes right.
https://www.youtube.com/watch?v=jymNk_YgcpE

Trump attacks Guantanamo 1 million dollar soccer field.
This is an argument defending the 1 million dollar soccer field.
https://www.reuters.com/article/nsa-Guantanamo-soccer-idUSL2E8E1CC520120301
** <2018-11-19> Who is honest nowadays?
I don't know who is honest anymore.
Everybody seems to be making their own reality bubble.
Mass delusion.
** Why is Xi Jinping becoming so powerful?
Some answers/opinions on Reddit:
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvmnlo
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvf76g
** This may be biased; speculations about China
*** Speculations
These are the possible scenarios:
- The oppressed thinks that they are already dead (their lives are worse than death) anyway,
  musters enough strength, revolts, and overthrows the government.
  The non-oppressed (the middle-class) takes collateral damage.
- The government kills off all oppressed people.
  The non-oppressed people lives in their bubble happily ever after.
- The government slowly releases control while trying to save face.

Xi Jinping cannot release control in 2018, because if he releases control, his opponents will pounce on him, reveal all his crimes, and tarnish his name.
Xi Jinping wants to die in good standing, with good reputation; he wants to be remembered as a good person.

I hope that the next bloodshed gives the Chinese people enough reason to limit government power.

You can live a good comfortable life in China as long as you blind yourself from the truth.

- <2018-09-26> [[https://www.youtube.com/watch?v=eViswN602_k][Exposing China's Digital Dystopian Dictatorship | Foreign Correspondent]]
  - China's Big Brother system favors obedient middle-class people, and limits journalists, minorities, and dissenters.
  - Alibaba helps oppression.
    Alibaba is making AI to help the Chinese government oppress people more efficiently.
    Do they profit from oppression?

Stalin's inner circle was too afraid to tell him the truth.
Nobody dared to challenge Stalin.
Stalin's inner circle told him what he wanted to hear.

https://www.quora.com/Is-is-true-that-top-Soviet-officials-lived-in-constant-fear-under-Stalin-Or-is-that-an-exaggeration

After Stalin died, there was a great purge.

You know your country is led by an authoritarian if:
- You can't say the truth there.
- There is someone whom people are too afraid to disagree with, even politely.

We must respect the truth.
The truth doesn't care about us.
People who ignore the truth do so at their own peril.
Ignoring the truth means ignoring some danger;
such ignorance reduces the chance of survival.
*** Hopeful
[[https://www.youtube.com/watch?v=8XQ1onjXJK0][Are China and the US doomed to conflict? | Kevin Rudd - YouTube]]
** Living in a republic
*** If you don't vote, you let the worst guy win.
Your vote prevents greater harm.
*** If you vote some people, and they win, then, you are, in some way, responsible for the bad things that they
George Carlin doesn't vote https://www.youtube.com/watch?v=xIraCchPDhk
*** If you don't speak, you let the worst guy do anything he wants.
You must state your disagreement.
** <2018-09-20> Politics
- [[https://www.youtube.com/watch?v=xDsg2sLhnIE][Trump Is Making America Great Again. Just Not the Way He Thinks. | NYT - Opinion - YouTube]]
** Why the non-oppressed people must help the oppressed people
Because when the oppressed people revolt, the non-oppressed people will be among the victims.
** <2018-09-21> Australia fruit sabotage crisis
- Is it done by immature kids?
- Is it done by foreign actors (to destabilize Australia, for example)?
- Is there any other explanation?
** <2018-09-22> Power: control vs identity
"The traditional view—that power means having /control/ over a group of people—is giving way to a new understanding: that power means having other people /identify/ with you." ([[https://insight.kellogg.northwestern.edu/article/four-tips-to-gain-influence-in-your-organization][source]])
** Donald Trump, media firehose of lies, psychology
*** Everybody wants their own reality.
The media lie.
Newspaper lie.
Politicians lie.
*** https://www.reddit.com/r/The_Donald/ is a firehose of lies.
- That subreddit uses derogatory/bully language.
  The same technique used by school bullies: calling names.
- https://www.reddit.com/r/The_Donald/wiki/index
  - rule no. 6: "Trump Supporters ONLY - This sub is for supporters of Donald J. Trump ONLY.
    This is not a place for you to debate with us about Donald Trump, or to ask us to convince you to like Donald Trump.
    This is not a neutral place - we are 100% in support of Donald J. Trump. Moderators reserve the right to ban non-supporters as we see fit."
    - Read: This subreddit exists to perpetuate lies.
      We are lying, but we don't want people to think that we are lying.
      We will ban everyone who points out that we are lying.
- That subreddit bans fellow Trump supporters who don't lie.
  - https://www.reddit.com/r/BannedFromThe_Donald/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/64kduy/trump_supporter_gets_banished/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/6thnoa/banned_for_linking_a_t_d_post_on_t_d/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/7klmhy/the_lovely_messages_you_get_from_the_moderators/
- https://www.reddit.com/r/AgainstHateSubreddits/comments/851rgd/i_compiled_a_list_showcasing_the_donalds_50_worst/
*** Mass bullying, mobbing
- https://en.wikipedia.org/wiki/Mobbing
*** Psychology
- https://www.psychologytoday.com/us/blog/mind-in-the-machine/201609/the-psychology-behind-donald-trumps-unwavering-support
  - "There may be nothing we can do" means "the only way to fix it is by killing those deluded people but, unfortunately, doing so is illegal".
*** Nobody should be able to spread lies and go unpunished.
*** Do Trump's bankruptcies imply that he is incompetent?
*** What is the history of the Republicans? What is the history of the Democrats?
*** When humanity is divided, only a catastrophe can reunite us.
- alien invasion
- catastrophic natural disaster
- supervolcanic supereruption
- nuclear plant meltdown
- famine
- any existential threat; a threat to the existence of all of us
** The truth about the truth
- It is impractical to know the truth.
  - We can only perceive things near us (about a few meters).
  - It is impractical to visit every corner of the world and see everything with our own eyes.
  - It is impractical to verify every sentence a person has ever uttered.
- What then?
- Can we tell apart the liars from the honest people?
- If everyone were humble enough to admit that they don't know the truth, extremists wouldn't exist.
*** Learn to ride the media for free and win like Trump
- How Trump Manipulates The Media https://www.youtube.com/watch?v=IctC0Quf8zc
  - If you're wrong, don't apologize.
    Apologizing requires you to restate the charge and what gets repeated gets remembered.

As long as media optimizes themselves for maximum traffic (for advertising), people like Trump are going to win.
Sensationalism gets traffic.

Think of the headline that you want, and repeat it.
Headlines have to be short.
Keep your message simple.
Repeat the message.

Keep your calm, no matter what others say.
Repeat the headline.

** Game-changer? DoNotPay: automate lawyers?
- https://www.youtube.com/watch?v=xbXM-aNRNlY
- https://www.donotpay.com/
** Does Wikileaks matter? Who is going to scour all that text for interesting stuffs / incriminating evidence? Most people don't have time to read that.
But the point is that everybody who wants to verify it can verify it, not that everybody should read it.
** All fierce debates are language problems
Communication consists of input, processing, and output.

In a fierce debate, there is no input; there is only output, and the participants don't even agree about the definitions.
They don't know what they are talking about.
** News?
*** <2018-10-05> Global information technology hardware supply chain serious security disaster
- https://www.bloomberg.com/news/features/2018-10-04/the-big-hack-how-china-used-a-tiny-chip-to-infiltrate-america-s-top-companies
- https://www.schneier.com/blog/archives/2018/10/chinese_supply_.html
*** <2018-10-02> Beware of China's debt-trap diplomacy?
Beware of every other nation that seems helpful.

What is this [[https://www.youtube.com/watch?v=lVYdqoVJIeI][video]] trying to say?

The system forces politicians to be myopic (think short-term); they only see at most 5 years ahead.
** Witness testimony shouldn't count as /sole/ evidence; there has to be independent corroboration
- How reliable is your memory? | Elizabeth Loftus https://www.youtube.com/watch?v=PB2OegI6wvI
- Steve Titus: victim of false memory https://en.wikipedia.org/wiki/Wrongful_conviction_of_Steve_Titus
** Politics?
*** Law
- Law should be principle-based instead of rule-based.
- A judge should facilitate restoration, not determine punishment.
*** Cops, government, and you
Cops don't work for you. They work for the government.

The government doesn't work for you. They work for themselves.
Only people with entitlement mentality thinks the government works for them.
*** What is this? Politics?
"Hans J. Morgenthau, /Politics Among Nations: The Struggle for Power and Peace/, Fifth Edition, Revised, New York: Alfred A. Knopf, 1978, pp. 4-15"
"Six principles of political realism"
https://www.mtholyoke.edu/acad/intrel/morg6.htm
*** Rights
Right is given by one person to others.
To give person P the right to do D is to let P do D
** Improving society?
- Preventing social isolation
  - Social isolation causes violence and extremism.
    Bullying is part of the social isolation vicious circle.
    [[https://www.youtube.com/watch?v=azRl1dI-Cts][YT:I Was Almost A School Shooter | Aaron Stark | TEDxBoulder]]
    - [[https://www.youtube.com/watch?v=DmWrx0ntATU][YT:Cohousing communities help prevent social isolation]]
- Achieving independence
  - Demonopolizing the ability to do violence?
    - People who care (and thus readily mobilize) are less oppressable than people who don't.
      - How do we get people to care about and participate in politics?
    - Online campaigns/petitions.
      - [[https://www.newscientist.com/article/mg22630182-800-technology-can-give-political-power-back-to-the-people/][Technology can give political power back to the people - New Scientist]]
    - Using the Internet (social media, messaging, forum, etc.) to incite people?
    - Teach people how to participate democracy?
      - If shit gets to the top, people have only themselves to blame.
        - Democracy means they could have prevented that shit.
          - But they were apathetic.
            They didn't care.
            They gave up before even trying.
            So that shit rose without any obstacles.
  - Automating politics/governments/law?
  - Empowering people with distributed local technology?
    - Take power away from governments and elites, and give it back to the masses?
      - Isn't that mobocracy/ochlocracy?
        Anarchy?
        Do we want?
        - [[https://rationalwiki.org/wiki/Anarchy#Contrast_with_mobocracy][RationalWiki: Difference between anarchy and mobocracy]]
** Evil automobile industry
https://www.reddit.com/r/todayilearned/comments/9mv3oi/til_that_the_term_and_concept_of_jaywalking_was/

Given enough time, all industry eventually becomes corrupt.
Even something as mundane as the window industry is corrupt.
** Tech problems
*** Bloomberg spy chip report? Untrustworthy hardware manufacturers?
https://techcrunch.com/2018/10/07/homeland-security-denies-bloomberg-spy-chip-report/amp/
https://techcrunch.com/2018/10/04/bloomberg-spy-chip-murky-world-national-security-reporting/

Is Bloomberg fake news?
https://techbeacon.com/security/bloomberg-spy-chip-story-will-not-die

It does not make sense for Huawei/Supermicro/Lenovo to plant spy chips,
because someone else will find out,
and it will hurt the company's reputation a lot,
unless they are so sophisticated or powerful that can do it undetected or get away with it.
Ren Zhengfei of Huawei has denied planting spy chips, for that reason, which makes sense.
https://www.youtube.com/watch?v=Nl2jCWDwE8w

Are Supermicro and Lenovo untrustworthy?
Jamie Schnaitter:
"It's already been a touchy topic, especially since major players in HPC, such as SuperMicro and Lenovo have been caught with malware in their firmware and on their websites."

Could the Lenovo SuperFish[fn::https://en.wikipedia.org/wiki/Superfish] scandal be accidental?
It could be the case that Lenovo was just bundling/preinstalling third-party apps
(which seems to be a common practice among OEMs)
and did not know that SuperFish installed a certificate.

Sony BMG also had a DRM rootkit scandal.
 [fn::https://en.wikipedia.org/wiki/Sony_BMG_copy_protection_rootkit_scandal]

https://arstechnica.com/information-technology/2018/12/supermicro-refutes-report-of-malicious-implants-with-audit/
*** Facebook is rotten to the core?
"If you still have a Facebook account, delete it and stop using Facebook"
https://www.youtube.com/watch?v=vEDGJWocYd8

Facebook is corrupting WhatsApp?
Should we leave WhatsApp?
https://www.forbes.com/sites/parmyolson/2018/09/26/exclusive-whatsapp-cofounder-brian-acton-gives-the-inside-story-on-deletefacebook-and-why-he-left-850-million-behind/amp/
*** Redundant people don't simply disappear.
Neo-Luddites fights tech with tech.

The Luddites aren't stupid.
They are frustrated because quick landscape changes cause mass layoff of the Luddites,
but everybody else wishes that the Luddites just disappear.

The problem with introducing technology:
the replaced people are now jobless, but they don't simply disappear.

It is simple to DDoS Facebook.
Create an Android app that slowlorises the servers.
Tell people to download the app to better mankind.
*** Slack anticompetitive?
https://www.theverge.com/platform/amp/2018/9/24/17897658/slack-astro-acquisition-email-app-shut-down-integration
*** Google
The Google Cemetery: List of dead Google products
https://gcemetery.co/
*** 2018 article "How the Internet went wrong in 15 steps"
How the Internet went wrong in 15 steps
http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html
- "Step 1: Start With Hippie Good Intentions"
- "Step 4: [...] we paid a high price for keeping [the Internet] free"
  - "To avoid charging for the internet — while becoming fabulously rich at the same time — Silicon Valley turned to digital advertising."
  - Click maximization breeds sensationalism and extremism: /anything goes/, for a click.
    - Growth at all costs.
      Growth for the sake of growth.
      Idolization of growth.
      Growth is overrated.
      Growth isn't always desirable.
  - Tristan Harris: "We cannot afford the advertising business model. The price of free is actually too high.
    It is literally destroying our society, because it incentivizes automated systems that have these inherent flaws.
    Cambridge Analytica is the easiest way of explaining why that’s true.
    Because that wasn’t an abuse by a bad actor — that was the inherent platform.
    The problem with Facebook is Facebook."
- "Step 5: Everything was designed to be really, really addictive.
 The social-media giants became 'attention merchants', bent on hooking users no matter the consequences.
 'Engagement' was the euphemism for the metric, but in practice it evolved into an unprecedented machine for behavior modification."
  - Guillaume Chaslot: "The way AI is designed will have a huge impact on the type of content you see.
    For instance, if the AI favors engagement, like on Facebook and YouTube, it will incentivize divisive content, because divisive content is very efficient to keep people online."
- Internet business model that is not advertising
  - "Step 12: To fix it, we’ll need a new business model. Maybe [...] like charging users for goods and services"
  - I think Facebook/Twitter/Reddit/YouTube can make country-level subscription that countries pay using taxpayer money.
- "Step 14: Maybe nothing will change."
- What people say
  - Tim Berners-Lee: "The fact that power is concentrated among so few companies has made it possible to weaponize the web at scale."
  - Tim Cook: "I don’t have a kid, but I have a nephew that I put some boundaries on. There are some things that I won’t allow; I don’t want them on a social network."
  - Chamath Palihapitiya: "The short-term, dopamine-driven feedback loops that we have created are destroying how society works. No civil discourse, no cooperation; misinformation, mistruth. This is not about Russians’ ads. This is a global problem."
*** Privacy problem
https://gizmodo.com/apps-you-use-every-day-are-tracking-your-every-move-ac-1830980646/amp

** Aircraft crashes
Causal chain:
- Boeing 737 MAX crashes two times in less than a year.
  - MCAS (Manuvering Characteristic Augmentation System) fights the pilot.
    - MCAS is a software workaround for a hardware flaw (the aircraft's tendency to pitch up and stall when engine power is increased).
      - The hardware flaw is an economic workaround for a strategic flaw?
        - Boeing wants to avoid retraining costs.
        - Boeing sticked to the 737 design for too long?
          - Boeing is averse to giant-leap innovations?
          - Economic competition too aggressive?

<2018-10-29>
Lion Air JT 610 jatuh menghantam air laut di dekat Karawang.
Wait for black box analysis result.

Boeing 737 MAX Lion Air JT 610 crash

The safety system, designed to protect the people, killed them instead.

<2018-11-15> Lion Air crash: Boeing sued by victim's family over aircraft design
https://www.bbc.com/news/amp/world-asia-46230496

https://arstechnica.com/information-technology/2018/11/indonesia-737-crash-caused-by-safety-feature-change-pilots-werent-told-of/

Sensor error is more likely than actual stall?
The designers trust themselves more than they trust the pilots?
The pilots didn't read the manual?
Boeing didn't disseminate information fast enough?
Hardware fault?

https://en.wikipedia.org/wiki/Stick_pusher

https://philip.greenspun.com/blog/2018/11/11/boeing-737-crash-is-first-mass-killing-by-software/

** Terror, fear, power?
Engels:
"Terror consists mostly of useless cruelties perpetrated by frightened people in order to reassure themselves."
** Climate change
Climate change (increasing temperature and carbon dioxide) is real, but we don't agree about whether it's harmful
https://www.youtube.com/watch?v=m3hHi4sylxE
** <2018-09-19> Recruiting networks are double-edged swords for employers
Example tools: Linkedin, SmartRecruiters.

You can use it to find new employees.
But your employees can also use it to find new employers.

But the overall economy stands to gain if we can fix the information asymmetry in job market.
** <2018-09-19> Sturgeon's law, originally for science fiction, also applies to job applicants
"Ninety percent of everything is crap."

Ninety percent of your applicants is crap.

Indeed it applies to /everything/.
Ninety percent of /everything/ is crap.
Software.
Companies.
Goods.

Ninety percent of /everything/ is crap: people, countries, etc.;
and we may be in that 90%.
** <2018-09-28> "Class Struggle" board game

- [[http://www.nyu.edu/projects/ollman/game.php][what it looks like]]
- [[http://www.nyu.edu/projects/ollman/game_rules.php][the rules]]
** Ethics and the workforce
- [[https://www.econlib.org/library/Enc/MarketforCorporateControl.html][Market for Corporate Control -- Econlib]]

  - "Markets discipline producers by rewarding them with profits when they create value for consumers and punishing them with losses when they fail to create enough value for consumers."
*** Tech giant ethical issues

- Bezos Amazon worker condition?
- Google Dragonfly supports Chinese authoritarianism?

**** Don't buy from Oracle.

- [[https://www.reddit.com/r/programming/comments/5iogug/oracle_finally_targets_java_nonpayers_six_years/][Oracle finally targets Java non-payers -- six years after plucking Sun : programming]]
- [[https://developers.slashdot.org/story/16/12/18/0147216/oracle-begins-aggressively-pursuing-java-licensing-fees][Oracle Begins Aggressively Pursuing Java Licensing Fees - Slashdot]]

*** <2018-08-29> IQ and jobs
  Although I'm happy to be proven wrong,
  I believe that a minimum IQ of 120 is necessary but not sufficient for software engineering (cooperativeness is also required).
  It seems IQ tests are inaccurate for high IQs above 130.
  - [[https://www.reddit.com/r/learnprogramming/comments/2ue71p/what_iq_do_you_need_in_order_to_be_a_programmer/][What IQ do you need in order to be a programmer? : learnprogramming]]
    - The OP doesn't sound like his IQ is 89.
  - Higher IQ means faster learning, and that's all.
  - To each according to their ability.
    Society needs low IQ people.
    Some jobs fit low IQ people.
    These jobs are equally honorable as high IQ jobs are.
    Low IQ isn't an insult.
    Everyone is different.
** Data, customers, and reality
- https://www.inc.com/business-insider/amazon-founder-ceo-jeff-bezos-customer-emails-forward-managers-fix-issues.html
  - "If all his [Bezos's] data says one thing and a few customers say something else, he believes the customers."
** Solving the Israel-Palestine problem
- I propose this for the Israel-Palestine problem:

  - Country

    - Establish a new country (say "Ispal"), merging Israel and Palestine.

  - Government

    - Everyone in the Israeli government is in the Ispalian government.
    - Everyone in the Palestinian government is in the Ispalian government.

  - Land

    - The land of Ispal is the land of Israel plus the land of Palestine.

  - Citizen

    - Every Israeli is an Ispalian.
    - Every Palestinian is an Ispalian.

  - Law

    - Every Ispalian is equal before the law.

  - Why this might not be accepted

    - Idealism, fanaticism, narrow-mindedness, intolerance, ignorance of history, mixing religion and politics
** Performance review?
*** Why do companies have performance reviews?
   :PROPERTIES:
   :CUSTOM_ID: why-do-companies-have-performance-reviews
   :END:

Meritocracy?

To weed out bad apples?

Governance?
Minimize risk, not maximize reward?

*** Does it do what we intend it to do?
   :PROPERTIES:
   :CUSTOM_ID: does-it-do-what-we-intend-it-to-do
   :END:

Problem: People tend to talk only about the good things of other people.

Problem: Retaliation.
If A say bad things about B, B will retaliate.

https://en.wikipedia.org/wiki/Machiavellianism_in_the_workplace
https://en.wikipedia.org/wiki/Workplace_deviance
https://en.wikipedia.org/wiki/Live_and_let_live_(World_War_I)

Does performance review make employees think short term and seek quick small wins?

*** Why does the Internet think that performance reviews don't work?
   :PROPERTIES:
   :CUSTOM_ID: why-does-the-internet-think-that-performance-reviews-dont-work
   :END:

- http://www.growthengineering.co.uk/annual-performance-reviews-dont-work/
- https://www.thebalancecareers.com/performance-appraisals-dont-work-1918846
- https://www.forbes.com/sites/lizryan/2018/01/14/performance-reviews-are-pointless-and-insulting-so-why-do-they-still-exist/#615c36c672d1
- https://www.inc.com/thomas-koulopoulos/performance-reviews-are-dead-heres-what-you-should-do-instead.html
** <2016-03-22> Don't use Wikia
[[http://dizzy.pestermom.com/][KimikoMuffin]]
has [[http://dizzy.pestermom.com/?p=nowikia][some strong reasons for not using Wikia]].

Wikipedia does not own Wikia, but
[[http://money.cnn.com/magazines/business2/business2_archive/2007/03/01/8401010/][who owns Wikipedia also owns Wikia]]:
Jimmy Wales owns a share of Wikipedia and also a share of Wikia.
Whenever you make a Wikia site,
you're working, unpaid, for him and the other owners.
[[http://shouldiworkforfree.com/][Why would you work for free?]]
(By the way, Wikipedia also has its share of unpleasant stories,
but that's for another post.)

An alternative that will give you more freedom
(and ownership, but also more responsibility)
is hosting on your own domain,
but this needs some technical understanding.

The bad news is that Wikia is the leader for niche wikis
and there doesn't seem to be any meaningful [[http://alternativeto.net/software/wikia/][competition]]:
Google search result for niche gaming queries is typically full of Wikia articles.
In the meantime, you can try [[http://www.shoutwiki.com/wiki/Main_Page][Shoutwiki]]
(there's even a wiki named [[http://awa.shoutwiki.com/wiki/Anti-Wikia_Alliance][Anti-Wikia Alliance]]) or
[[http://www.gamepedia.com/][Gamepedia]].
** My tech observations and complaints
*** smartphone politics
- Xiaomi limits hardware profit to 5%? What?
  - [[https://www.reddit.com/r/Android/comments/8k43qo/why_does_xiaomi_limit_its_profits_to_5_youtube/][Why does Xiaomi limit its profits to 5%? - YouTube TechAltar : Android]]
    - Because Xiaomi is a software company, not a hardware company.
- [[https://www.youtube.com/watch?v=OA_g2bQgOXY][How KaiOS Is Becoming the 3rd Major Mobile OS - YouTube]]
  - Much money can be made from selling to poor people (hopefully while also helping them).
    - [[https://hbr.org/2012/06/the-smart-way-to-make-profits][The Smart Way to Make Profits While Serving the Poor]]
*** GIF is video, not image.
- GIF videos must have controls.
- Google should penalize (push down) Pinterest from image search.
  It's littering.
*** Using chat such as IRC/Slack
- I find that most channels are idle.
- There are two kinds of channels: temporary and permanent.
  - Temporary channel is functional. It gathers people for a task/project.
  - Permanent channel is structural. It gathers people in the same tribe/department/structure.
* What? Socialism? Communism? Understanding communism before criticizing it?
Marx's stages of society
https://en.wikipedia.org/wiki/Marx%27s_theory_of_history

Ganti upah minimum dengan universal basic income atau negative tax rate

Embedding communism in capitalism

Embedding capitalism in communism

Reconciling capitalism and communism

Communism should not be defined as an opposite to capitalism.
"Abolition" is negative definition.

Communism doesn't require central government.
** Examples of local communism?
Israel kibbutz? https://en.wikipedia.org/wiki/Kibbutz

Can we have communism without centralization?
It's absurd to have a central authority that decides who to make how much what.

https://en.wikipedia.org/wiki/Primitive_communism
** Is sharing communism?
Is ridesharing (Gojek, Grab, Uber, Lyft, etc.) communism?
* TODO reorganize; from politics.md
- What is the Government of China afraid of?
  - The Government of China isn't afraid of criticism. It is afraid of collective action. [King2013]
- Why are cannabis and heroin illegal?
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/6h6med/daily_reminder_about_the_true_purpose_of_the_war/][/r/LateStageCapitalism: John Ehrlichman: Nixon illegalized drugs to stigmatize hippies (cannabis) and blacks (heroin) because those people were against him.]]
  - Cannabis overuse permanently damages teen brains.
  - Another theory: cotton farmers vs hemp farmers?
- Reddit: CrazyIdeas
  - procreation license https://www.reddit.com/r/CrazyIdeas/comments/17yniw/you_need_a_license_to_have_children/
    - Are people more likely to be killed by other people (war, genocide, holocaust) or by cars?
  - https://www.reddit.com/r/CrazyIdeas/comments/3x8fr5/seeing_as_the_1_have_nearly_everything_lets_just/
  - https://www.reddit.com/r/CrazyIdeas/comments/6alqe1/make_a_handy_guide_of_democratic_and_republican/
  - impractical
    - https://www.reddit.com/r/CrazyIdeas/comments/6cu2yf/we_all_join_isis_so_there_isnt_anyone_left_for/
    - [[https://www.reddit.com/r/FunnyandSad/comments/7h7p3u/if_everyone_was_given_one_free_totally_legal_kill/][give everyone one free totally legal kill]]
- Who is Donald Trump's greatest opponent?
  - Donald Trump is the person who disagrees most with Donald Trump.
    - [[https://twitter.com/DonTrumpsTrump][Twitter: DonTrumpsTrump]],
      [[https://www.reddit.com/r/TrumpCriticizesTrump/][/r/TrumpCriticizesTrump]]
    - [[https://www.youtube.com/watch?v=kSE-XoVKaXg][YouTube: PlainSight: Trump exposes Trump]]
  - Ignore what politicians /say/.
    See what they /do/.
    See where their money comes from.
    See where their money goes to.
    Talk is easy.
    - But who is going to read through the
      [[https://en.wikipedia.org/wiki/List_of_executive_actions_by_Donald_Trump][list of executive actions by Donald Trump]]
      to find out who he really is?
      Will someone summarize?
- Who else trash-talk like Donald Trump does?
  - Thomas Jefferson, according to [[https://www.youtube.com/watch?v=ZIv7dQ9tt30][Adam Ruins Everything - Other Donald Trumps Throughout History]]
  - and lots of people in the colonial era, according to [[https://www.readex.com/readex-report/slinging-mud-and-talking-trash-gutter-age-american-journalism][Slinging Mud and Talking Trash: The Gutter Age of American Journalism]]
- Syrian war
  - [[https://www.quora.com/Is-Assad-bombing-his-people-If-so-why-do-many-people-support-him][Quora: Is Assad bombing his people? If so, why do many people support him?]]
- How do we fix the justice system?
  - Replace retributive justice with restorative justice.
    - Focus on fixing the damage, not on punishing people.
    - Norway gets the prison system right by "restorative justice" as opposed to American "retributive justice".
  - Society should help people fix their mistakes and reintegrate to society.
    - [[https://www.youtube.com/watch?v=RfU8TUZRtZg][Homeless guy spits some truth.]]
- [[https://www.youtube.com/watch?v=5tu32CCA_Ig][Corruption is legal in America]], 6-minute video
  - https://represent.us/
  - https://anticorruptionact.org/
- Wars are still happening. They just moved from overt to covert.
  - [[https://en.wikipedia.org/wiki/War_Is_a_Racket][WP: War is a racket]], Smedley D. Butler, 1935
- [[https://www.politico.eu/article/12-people-and-things-that-ruined-iran-energy-shah-regime-islamism/][Politico: 12 people and things that ruined Iran]]
  - Iran has a traumatic past. History has shown that it can't trust anyone, even its neighbor Iraq. Thus Iran wants self-sufficiency at all costs.
  - Self-sufficiency is a necessary but not sufficient condition for independence.
    - If you trade with other nations, you depend on them.
    - Trade (and specialization of labor) is beneficial for everybody if everybody is fair.
  - What is the difference between "independence" and "sovereignty"?
- Undigested
  - How can the minority control the majority?
    - https://en.wikipedia.org/wiki/Big_man_(political_science)
  - [[https://www.youtube.com/watch?v=rStL7niR7gs&feature=youtu.be][CGP Grey: The Rules for Rulers]]
    - "The Dictator's Handbook", Bruce Bueno de Mesquita
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/7bd6xm/how_to_bribe_a_lawmaker_101/]["Lobbying" /is/ "bribing"]].
  - [[https://www.reddit.com/r/LateStageCapitalism/comments/8i4y3a/new_un_report_finds_almost_no_industry_profitable/][New UN report finds almost no industry profitable if environmental costs were included]]
  - History, politics, military, war, weapon
    - https://www.reddit.com/r/explainlikeimfive/comments/1fy1na/eli5_why_did_joseph_stalin_kill_so_many_people/
    - [[http://www.historyisaweapon.com/defcon1/zinncol1.html][Native American Holocaust]]
    - Reddit: LateStageCapitalism
      - https://www.reddit.com/r/LateStageCapitalism/comments/6ilw3q/war_who_is_it_good_for/
      - https://www.reddit.com/r/LateStageCapitalism/comments/6cqcm3/if_youre_unemployed_it_is_not_because_there_isnt/
    - Best attack aircraft? https://en.wikipedia.org/wiki/Fairchild_Republic_A-10_Thunderbolt_II
    - What does manifest destiny have to do with American Imperialism?
      - [[https://en.wikipedia.org/wiki/Manifest_destiny][WP:Manifest destiny]]
      - [[https://en.wikipedia.org/wiki/American_imperialism][WP:American imperialism]]
  - [[https://www.ranker.com/list/the-best-way-to-fix-the-american-political-system/desertrat89][The Best Way to Fix The American Political System]]
  - History
    - https://history.stackexchange.com/questions/32480/why-would-some-nations-want-to-force-japan-to-end-their-isolation
  - [[https://www.youtube.com/watch?v=257wV-AbKaE][How does money laundering work? - Delena D. Spann]]
  - Free speech is only possible if people think critically.
  - Democracy is only possible if people think critically. - Democracy assumes that the electors are educated;
    otherwise the candidates will manipulate the electors
    using public media and sensitive issues. - Examples: - US in 2016 (Trump) - Indonesia in 2017 (Anies-Sandi)
    - [[https://www.youtube.com/watch?v=fLJBzhcSWTk][Why Socrates hated democracy]]?
      - Because the average person isn't competent to rule a country.
- YouTube: user: The school of life
  - [[https://www.youtube.com/watch?v=shanIOl7MyE][The Perfect Country]]
  - [[https://www.youtube.com/watch?v=Y9zThcMJzQU][How to Make a Country Rich]]
- Why is the US defense budget so huge?
  - https://www.reddit.com/r/explainlikeimfive/comments/3b5ogu/eli5_why_is_the_united_states_defense_budget_so/
  - https://www.quora.com/Why-does-the-United-States-have-such-a-large-military-budget
  - My guesses
    - The US defense budget is so huge because it's dealing with the entire Earth, not only the US?
    - Also, no competition in the defense sector?
      It's inefficient?
      It has no incentive to be efficient.
      Compare how competition (such as SpaceX)
      could cut down the cost of launching rockets.
- Why is Britain helping Israel?
- [[https://www.youtube.com/watch?v=rStL7niR7gs][The Rules for Rulers]]
- [[https://www.quora.com/Whats-the-story-of-SoftBank-Where-does-it-get-so-much-money-to-invest-from][Quora: What's the story of SoftBank? Where does it get so much money to invest from?]]
  - by investing in Alibaba
- If a law does not prescribe any punishment, will you obey it?
- Should we just die when we cannot pay the hospital bills?
  - If your death would ruin your family, should you have a family?
- Data source for salaries of various positions in the US: Foreign labor certification wage library
  - In the US, salary isn't secret, especially if you're a foreigner.
- No matter how evil or stupid politicians may seem, they do it with a reason?
  - Which makes it worse?
    - They're evil on purpose?
  - How do politicians reason?
    - Keep it simple?
      - If politicians are honest:
        - They represent their voters.
          - They reflect the people who vote for them.
  - Is [[https://en.wikipedia.org/wiki/Hanlon%27s_razor][WP:Hanlon's razor]] applicable?
- [[https://en.wikipedia.org/wiki/Politician][WP:Politician]]
- [[https://en.wikipedia.org/wiki/Politics][WP:Politics]]
- [[https://www.youtube.com/watch?v=3JVR0zAiyw0][YT:Putin on ideology - difference between Americans and Russians]],
  American individualisn, Russian collectivism
- [[https://www.quora.com/Is-there-one-website-to-daily-summarize-everything-that-is-going-on-in-Washington][Quora:Is there one website to daily summarize everything that is going on in Washington?]]
- [[https://en.wikipedia.org/wiki/Public_sphere][WP:Public sphere]]
- I don't always agree with these, but these have some useful things.
  - [[https://stallman.org/][Richard Stallman's personal site]]
    - What's bad about X (company)?
- [[https://www.reuters.com/article/us-usa-rights-un/americas-poor-becoming-more-destitute-under-trump-u-n-expert-idUSKCN1IY0C3][America's poor becoming more destitute under Trump: U.N. expert]]
  - https://www.theschooloflife.com/thebookoflife/countries-for-losers-countries-for-winners/
    - https://www.youtube.com/watch?v=kbpY-2nOYRI
- [[https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences][Why do politicians diverge from their constituents' preferences?]]
  - "the very idea of representative democracy is based on the fact that the preferences of the individual constituents
    do not make for good decisions in complex questions."
  - TODO group this with Socrates's argument
- Political economy
  - https://en.wikipedia.org/wiki/Employer_of_last_resort
    - https://en.wikipedia.org/wiki/Civilian_Conservation_Corps
    - [[http://www.levyinstitute.org/pubs/wp_534.pdf][Argentina: A Case Study on the "Plan Jefes y Jefas de Hogar
      Desocupados", or the Employment Road to Economic Recovery]]
- Justin Trudeau: "Donald Trump was elected on a promise to help the millions of middle-class families who feel left out of the success and progress of the past decades, and, interestingly enough, that is exactly the promise I got elected on, too."
  - https://www.quora.com/How-does-Justin-Trudeau-view-Canadas-relationship-with-the-US-in-light-of-Donald-Trump-winning-the-US-presidential-election/answer/Justin-Trudeau
- [[https://www.youtube.com/watch?v=c_Eutci7ack][How to understand power - Eric Liu]]
- [[https://www.youtube.com/watch?v=Cd0JH1AreDw][Eric Liu: Why ordinary people need to understand power]]
  - civics is the study of power
  - cities can practically bypass national governments
- Stop fluoridating water
  - Gaia: The Actual Truth About Fluoride, [[https://www.youtube.com/watch?v=HAagzF6D-nE][youtube]]
- [[https://www.politicalcompass.org/][Political compass]]: plotting economical-political views in two-dimensional space
- [[https://www.washingtonpost.com/world/asia_pacific/chinas-all-powerful-leader-should-heed-the-lessons-from-history-former-official-says/2017/11/09/22e7987a-c39a-11e7-a441-3a768c8586f1_story.html?noredirect=on&utm_term=.5dcdb36d3ff0][China's all-powerful leader should heed the lessons from history, former official says - The Washington Post]]
- We should limit inheritance.
  - Each child should inherit at most 1 house, 1 car, and cash sufficient for him to reach an age of 30.
- [[https://www.youtube.com/watch?v=o0ONByhAHC4][Why the wars America starts are unwinnable - Danny Sjursen - YouTube]]
- [[https://www.youtube.com/watch?v=U7DdgUAWR-s][What America gets wrong about China and the rest of Asia - David Kang - YouTube]]
  - China isn't a rising power. It has always been big.
  - Big nations have big internal (intra-nation) struggles.
  - Most big nations (such as the old Chinese dynasties) fall due to internal struggles.
- Has Google been artificially diversifying its employees by discriminating against Caucasian and Asian men?
  See James Damore lawsuit.
  - [[https://twitter.com/jamesadamore][James Damore on Twitter]]
- [[https://www.youtube.com/watch?v=IESYMFtLIis][Why societies collapse | Jared Diamond - YouTube]]
  - One possible reason:
    - conflict of interest
      - Elites make self-serving decisions that are good for themselves in the short term but bad for the society in the long term.
      - Those elites don't directly feel the bad consequences of their decisions.
- China
  - http://www.cirosantilli.com/
    - https://github.com/cirosantilli/china-dictatorship/blob/master/FAQ.adoc
- The goal of a career politician is to get reelected.
  - How do we create a system that makes sure that one is reelected if and only if he works according to the people's desires,
    and one is taken down as soon as he strays from the people's desires?
    - How do we create a system that is robust, that depends only minimally on the electees, that works for a wide variety of malicious electees?
      - How do we make government fear the people, and people fear the government?
        How do we make mutual fear?
- [[https://www.youtube.com/watch?v=UyohSu-Ft_U][The Grand Theory of Amazon - YouTube]]
  - Amazon is a scale company.
    It specializes in scaling.
- The solution is to make corruption impossible and irrelevant.
- Work-for-hire (WFH) contracts should be illegal, and be replaced with irrevocable licensing.
  Every man should own his own labor.
  Work-for-hire contributes to social injustice.
- Solution to extremism/radicalism:
  Make it a law that every copy of Quran/Bible/other holy book must be accompanied with historical context.
  The book should prescribe how it should be interpreted.
  People should not invent their own interpretations.
  The interpretation must be justified by historical context.
  - [[http://aboutislam.net/counseling/ask-about-islam/why-does-the-quran-require-context/][Why Does the Quran Require Context? | About Islam]]
  - [[https://www.sbs.com.au/news/why-the-historical-context-of-the-qur-an-and-the-bible-cannot-be-ignored][Why the historical context of the Qur'an and the Bible cannot be ignored]]
  - synonyms: interpretation, exegesis, tafsir
- How much political power do we have?
  - [[https://www.theatlantic.com/magazine/archive/2015/07/power-quiz/395273/][How Much Political Power Do You Have? - The Atlantic]]
  - [[http://www.bbc.co.uk/guides/zpyr4wx][BBC iWonder - Do you know how much political power is in your pocket?]]
- office politics
  - [[http://www.yourofficecoach.com/coaching-resources/office-politics/political-games/how-much-political-power-do-you-have][How Much Political Power Do You Have? - Your Office Coach]]
- [[https://edition.cnn.com/2015/02/16/opinion/schmitt-politics-money/index.html][Money's power in politics: Give everyone a share - CNN]]
- [[https://www.crummy.com/2004/11/01/2][How To Exercise Political Power Part 1]]
* <2018-10-03> It's 2018, but people still believe in flat Earth and trickle-down economics.
According to https://www.forbes.com/sites/teresaghilarducci/2018/09/28/who-benefits-from-the-tax-cut-10-months-later/#3af0b9dc26bb:
- "Buybacks are attractive because most CEO pay is directly linked to stock values and not to productive capital expansion."
* Anarchism?
1995 book "What Is Anarchism? An Introduction"
https://theanarchistlibrary.org/library/donald-rooum-and-freedom-press-ed-what-is-anarchism-an-introduction
** Letter to anarchists: Say "self-governance" instead of "anarchism"; focus on making what you want, not on avoiding what you hate
Your goal is noble, but, for your message to be acceptable by the people,
you must use the word "self-governance" instead of "anarchy".
No need to change anything else, just replace all occurrences of "anarchy" with "self-governance".
This will make your speeches and writings infinitely more acceptable
to the uneducated people that you need.
No more wasting time explaining what "anarchy" really is.

It does not benefit you to use a word that has been redefined by everyone else.
Your meaning of "anarchy" dates back to Proudhon's 1840 treatise "What is property?"
It's 2018, almost 200 years since Proudhon,
and the topmost Google search result for "anarchy" today
is "a state of disorder due to absence or nonrecognition of authority".
You see, even the dictionaries and the Internet are conspiring against you.
Nobody wins a fight against the Internet.
You need a new word.

The word "anarchy" focuses on the absence of a ruler.
It gives the impression that you are a belligerent forever
plotting a coup d'etat against your nemesis the government.
You don't want that.
You want to maximize everyone's freedom,
and you want people to associate voluntarily,
which is to say that they self-govern.
The word "self-governance" gives the impression that you are
a youthful progressive bunch of people
with positive success mindset brimming with can-do attitude.
It sounds like bullshit, but flowery bullshit sells better than ugly truth.

It's unfortunate that words change meanings, but language changes with the people who speak it.
You won't see any progress until you change the word you use to spread your message.

The word "anarchy" is, in today's context, bad for marketing your cause.

Thus, from now on, say and write "self-governance" instead of "anarchy".
* Privacy
** Re-identification: Pieces of anonymized information about a subject can be combined to identify the subject.
[[https://arstechnica.com/tech-policy/2009/09/your-secrets-live-online-in-databases-of-ruin/][“Anonymized” data really isn’t—and here’s why not | Ars Technica]]

- Massachusetts Group Insurance Commission
- AOL
- Netflix
- etc.

Browser fingerprinting
** Is advertising ethical?
- Happiness = Expectation - Reality.
- Advertising increases expectation.
- Therefore advertising reduces happiness.
- But without advertising, how will people know that you even exist?
  How are you going to have customers at all?
- Advertising should be replaced with information.
- https://twitter.com/oxcsh/status/1055953330328010753
* Government/state
** Deregulation of USA

- [[https://www.youtube.com/watch?v=TuAg-RaZ4Is][Trump Is 'Destroying' Regulations - YouTube]]

Trump needs a cooperative Congress in order for him to be able to repeal more laws.

** Antonin Scalia: The key to American freedom is the separation of power, not the Bill of Rights.

https://www.youtube.com/watch?v=Ggz_gd--UO0

The USSR Constitution guarantees more freedom than the USA Constitution, but the USSR failed to prevent the centralization of power.

Every dictatorship has bill of rights.

North Korea has elections.

** Evolution justifies governments

Evolution suggests that cooperation improves survival (in the long run, of the species, not of an individual).

Evolution suggests that morality improves survival.

Evolution suggests that government improves survival.

What is the state for?
Why do we need government?
To promote the survival of the governed species.

*** Government is not to merely maintain public order.

Public order can be undesirable:

- We don't want a government that oppresses people in order to maintain public order.
- The overthrowing of a tyrant may be a desirable public disorder.

To promote survival of the people? As in evolution?

To better the people?
To impose the morality of the people?
A government reflects the morality of its people.

We must impose our morality on others.
The law imposes the lawmakers' morality on everyone.
It is practically impossible to live without imposing your morality on others.
There is a minimum decency that we expect when we interact with others.

The enforcement of law is an imposition of the morality of the lawmakers (and therefore of the people who elected the lawmakers).

https://www.quora.com/Should-the-law-impose-morality

*** Social apoptosis? Programmed human death?

Some cells must die to better the organism.
Some people should die to better the society?
Programmed cell death ~ programmed human death?

A malfunctioning cell kills itself.
It would be nice if a malfunctioning human could kill himself?

A cell infected by a virus kills itself.
It would be nice if a human infected by ideological virus (mind virus) could kill himself?

How do we know we're infected?

*** Why should our survival be desirable at all?

*** Human rights are legal fiction.

What is real is tolerance.
People let other people live.
If I am still alive, it's because others let me live,
because others tolerate me,
not because I have any rights.

*** Justifying freedom
   :PROPERTIES:
   :CUSTOM_ID: justifying-freedom
   :END:

- Hypotheses:

  - People do/produce best (the highest quantity for the lowest price) when they pursue what they want to do/produce.
  - People approach their strengths and leave their weaknesses.
  - Different people have different goals.
  - Higher intrinsic motivation increases willingness to accept lower pay.

** It is insane that every country makes their own laws.
   :PROPERTIES:
   :CUSTOM_ID: it-is-insane-that-every-country-makes-their-own-laws.
   :END:

Software engineers share as much as possible to avoid repeating work.
They use operating systems, libraries.

Legislators could share more work.

Most software engineers use the same operating system.
Every country has its own constitution.
This is an insane amount of duplication.

There should be a "software library" for laws.
Laws should be reusable.
It should be able to legislate
"law X of country Y also holds in country Z, provided that every occurrence of X is replaced by Z".

- [[https://en.wikipedia.org/wiki/Don%27t_repeat_yourself][WP:Don't repeat yourself]]
- [[https://en.wikipedia.org/wiki/World_government][WP:World government]]
- [[https://www.quora.com/There-is-only-one-country-in-the-world-and-there-are-no-borders-no-need-for-passports-People-can-travel-freely-and-there-is-a-similar-legal-and-economic-system-for-everyone-in-the-world-What-do-you-think-of-this-idea][Quora question about world government]]
** A government is a cancer that parasitizes its host country?
Government exists because people are too lazy to think.
People want the government to nanny them.
People blame the government for everything.
In reality they cause their own misery.
* Insurance
We should limit health insurance to catastrophic conditions only.
https://www.youtube.com/watch?v=3WnS96NVlMI

2017
"These Doctors Got Fed Up With Insurance. Now They Treat Their Patients Like Valued Customers."
https://www.youtube.com/watch?v=6-Vqjo2S1us

* Leaving Greenpeace
- [[https://www.youtube.com/watch?v=BpBnJq19R60][video]] of Patrick Moore's reasons for leaving Greenpeace
* Political economics
** Economic ramblings
How may private interests give rise to integrated intermodal transportation?

Raising minimum wage increases unemployment

Bezos (Amazon) didn't raise minimum wages out of kindness.
He did it to pressure everybody to pressure Wal-Mart (an Amazon competitor).
Enemy of Capitalism: Capitalists
https://www.youtube.com/watch?v=nFe9N0BX8mM

Governments shouldn't guarantee bank deposits.
Governments should not encourage people to save too much money at banks.
Governments should encourage trade.

Employers love immigration.
Immigration makes cheap workers.
Illegal immigrants are even cheaper.

The pro-immigration people hide that desire behind pretend humanitarianism.
They don't care about cultural stability, as they live in their safe enclaves, protected by the government they bribe, far away from where immigrants live.

Better watch John Stossel than watch Bernie Sanders.
https://www.youtube.com/watch?v=YydE0IGKPXw

https://www.quora.com/What-dirt-is-there-on-Bernie-Sanders-Whats-out-there-that-might-spoil-his-chances-in-his-presidential-run
** Minimum wage hurts the very people it is supposed to protect.
First, pandering politicians raise minimum wage.

Then, companies scramble to avoid bankruptcy.
A company has several options:
- Do nothing; keep the workers, bear the cost. (Do you think the company will happily accept the reduced profit, if it still profits at all?)
- Raise prices, passing costs to buyers. (But then the buyers will buy less. Law of supply and demand.)
- Cut costs by reducing quality. (But will the buyers still buy?)
- Train the workers to make them more productive. (But how far can we train people?)
- Fire the workers, move to somewhere with cheaper workers.
- Fire the workers, buy robots.

https://www.minimumwage.com/

Political propaganda can't change the basic economic law of supply and demand.
This law is more fundamental than the politician-made laws.
Political fantasy can't change economic reality.
Ignore reality at your own peril.

I think workers should negotiate with their employers, and there is no need to involve government.

Disagreements.

Does minimum wage have different consequences in developing countries?
Minimum wage in developing countries may have no effect on employment, because the companies have bigger profit margins?
- 2009 "Minimum wage effects in a developing country" https://www.sciencedirect.com/science/article/abs/pii/S0927537108000547

(Indonesian) https://tirto.id/penghapusan-upah-minimum-bagi-negara-miskin-dinilai-tidak-tepat-cLgW
** Is the world better without private ownership?
Nobody needs to be rich?
What we really seek is satisfaction.
We should be happy if others find us useful, if others want us to stay, if others want us to exist.

If people's basic needs are met, they will still work, but they will only do what they really want to do.

Personal property is OK.
Is private non-moving property OK?

https://kk.org/thetechnium/better-than-own/

https://www.quora.com/How-would-a-world-without-money-ownership-and-monetary-value-operate
** Analogy: Marx were a doctor, capitalism were the disease, Marxism was the cure that was worse than the disease.
- Jordan Peterson Vs Marxist Professor Richard Wolff https://www.youtube.com/watch?v=HTj17c4N9vI
  - Marx predicted some bad consequences of capitalism, but the cure he proposed was worse than the disease.
  - However, Jordan Peterson says that inequality is not due to capitalism, but because small successes breeds even bigger successes.
    - When something good happens to you, it increases the probability that something else good also happens to you.
      - That (string of luck) spirals out of control, and we don't know what to do about it.
        - Luck begets more luck.
          Success begets more success.
          Money begets more money.
          (If you know what you're doing.)
* Insane stuffs
** Argument for killing stupid people?
- Premises:
  - People don't change.
    - Stupid is forever.
  - Survival is moral.
    If an action is necessary for survival, then it is moral.
    - Consequence: War for survival is moral.
      If there are only two people left on Earth, and there is only one last drip of water left on Earth,
      then it is moral for those people to go to war (that is, to harm the other) for that last drip of water.
    - Consequence: Retaliation is moral.
      It is moral for X to harm Y if Y harms X first.
  - Stupid people have been harming us.
- Conclusion?
  - It is moral to kill stupid people?
- Weaknesses and problems in the argument:
  - How do we define and determine stupidity?
    We should /not/ define "stupid" as "everyone who doesn't agree with us".
** Analogy: fixing wrong building, fixing wrong children, fixing wrong people?
- The safest action is preemptive strike:
  - When you realize that you built a house wrong, you tear down the house, and rebuild it the right way.
    - Or, you just wait until a natural disaster destroys it, and then rebuild it.
      - Let's hope that you aren't in the building when disaster strikes.
  - When you realize that you raised your child wrong, you kill it (?), and make another child (?).
    - Or, you just wait for karma to kill your child, and have another child.
      - Let's hope that your child doesn't kill you first.
  - If people don't change, then the only way to fix deluded people / persistently misbehaving people is killing them (?).
    - Or, you just wait for a war or disaster.
      - Let's hope that you're not in the shithole when shit happens.
  - We programmers tear down rotten code all the time.
    We rewrite it from scratch.
    Why don't we tear down rotten societies as well?
* Statistics, smoking, mindfulness
Seeing statistics worries me.
Most researchers don't understand statistics.
For example, I don't need statistics to know that smoking is bad; it's obvious.
It smells bad.
It makes me dizzy.

I guess people smoke because they have peer pressure, they have a weird sense of "cool", and they are too lazy to think for themselves.

Smoking always tastes bad.
Thus it is the rationalization that makes smokers tough it out.

How to stop smoking (Does it work?)

Remember when you first smoke cigarettes.
This is my guess.
It tastes bitter.
You cough.
Your eyes water.
It hurts.
But you tough it out.
You fear that your friends will leave you if you don't smoke.

I want you to taste every cigarette in the same way you tasted your first cigarette.
It's always the first time.
Feel the unpleasant bitter taste.

* Indonesian stuffs
** Catatan: semua ini baru ide; masih bisa berubah.
*** Ini apa?
Halaman ini berisi campuran beberapa hal:

- cita-cita/rencana untuk Indonesia
- riset/pembelajaran secara umum, terutama yang berkaitan dengan politik, ekonomi, sosial
- urusan yang ada kaitannya dengan pemerintah/negara
*** Apa masalah terbesar Indonesia? Apa akar masalahnya?
- https://www.galena.co.id/q/apa-masalah-terbesar-di-indonesia

Analyze causal chain.

Apa yang tampak (kenyataan di lapangan)?
Apa sebab langsungnya?
Apa sebabnya?
Apa sebabnya lagi?
Dan seterusnya.

- Wealth gap / kesenjangan ekonomi / severe inequality.
  Mana yang lebih penting: mengurangi wealth gap, atau memperbaiki worst case kehidupan?
*** <2018-09-26> Ganti /retributive justice/ dengan /restorative justice/.
**** Ideas and principles
Punishment is replaced with compensation.

The state /mediates/ (facilitates dialog between) the perpetrator and the victim.
The judge, perpetrator, and victim negotiate the compensation.
It can be money, labor, anything.

Imprisonment is reserved only for the unchangeable criminals.
**** Problem: Philosophical issues, definitions
A judge is to establish justice.
What is justice?
What is fairness?

Which do we judge: the person himself, or his deeds?
To judge a person is to opine (to form an opinion) about that person, but on what basis, according to which rules?

What do judges do?
What are judges supposed to do, according to the political systems our ancestors designed?

What is the history of judges?
How did judges come into being?

Jown Rawlins's veil-of-ignorance idea:
We know that a society is /just/, if we don't mind being born in that society
without being able to choose who we are going to be born as.

What is a just society for disabled people?

It is not his fault that he was born disabled.

Justice requires blame (assigning/attributing faults to people).
**** Problem: What do judges do then, if their daily tasks are given to the mediators?
- https://www.sokanu.com/careers/judge/
- https://www.nolo.com/legal-encyclopedia/what-judges-actually.html
- https://en.wikipedia.org/wiki/Judge
**** Kesulitan
- Berapa besar usaha yang diperlukan untuk mengubah sistem hukum yang sekarang?
- Bagaimana rencana transisi?
- Bagaimana memastikan sistem tidak disalahgunakan?
- Bagaimana meminimalkan kerusakan yang mungkin ditimbulkan hakim yang salah?
**** Rencana?
- Siapa yang berwenang mengubah sistem hukum indonesia menjadi restorative justice?
- Bagaimana melobi pihak berwenang?
*** Obtain political power?
**** TODO <2018-09-17> Join a think tank or a political party or both?

- https://onthinktanks.org/articles/what-can-indonesian-research-institutes-learn-from-chinese-think-tanks/
- http://www.ksi-indonesia.org/in/home
- http://www.thejakartapost.com/news/2017/02/03/indonesian-groups-among-worlds-influential-think-tanks-report.html
- https://id.wikipedia.org/wiki/Wadah_pemikir

**** TODO <2018-09-17> Educate the people about critical thinking, religion, history, power, and politics?
**** TODO <2018-09-22> Own a media company, or piggyback existing media?
**** Mungkin tidak perlu jadi anggota legislatif? Mungkin bisa dengan mendirikan ormas (organisasi masyarakat) atau yayasan?
UU no 17 tahun 2013, penjelasan pasal 59 ayat 4:
'Yang dimaksud dengan "ajaran atau paham yang bertentangan dengan Pancasila" adalah ajaran ateisme, komunisme/marxisme-leninisme.'

2016 [[http://rubernews.com/2016/05/14/kapolri-keluarkan-aturan-penindakan-penyebaran-paham-komunisme/][berita]]:
"Kapolri Badrodin Haiti menekankan penindakan hukum juga dilakukan pada mereka yang memakai atribut komunisme,
memposting foto palu arit, pemutaran film yang memuat paham komunisme, termasuk memproduksi dan melakukan penyitaan barang bukti."

https://historia.id/modern/articles/pasal-karet-larangan-penyebaran-komunisme-DbNL9

<2018-10-01>
Komunisme di Indonesia sudah tidak ada sejak tahun 1965-an.
Sekarang tahun 2018.
Sudah 50 tahun berlalu.
Tidak perlu takut.
Seandainya ada yang mencoba membangkitkan komunisme di Indonesia, kemungkinan besar akan ditolak oleh masyarakat.
**** Tidak perlu bikin organisasi secara formal, cukup himpun orang-orang yang bercita-cita sama.
Tunda bikin badan hukum sampai perlu melibatkan uang besar.
**** Using the media in politics
- The role of the media in politics:
    - The media should research/watch/monitor/summarize/audit the government for the public.
    - The media should therefore be owned by the public, and independent of the government. The media should not be funded with tax.
    - The media shapes the public opinion.
    - The media bridges the government and the public.
    - The public doesn't have the time to watch the government.
- The media is the public's opinion of the government.
- The media is whatever the public sees.
    - Shadow/private media: social media, websites, chat groups.
        - "Shadow" in the same sense as "shadow banking".
            - "Shadow" here means unofficial/non-traditional but effective.
        - They may contain hoaxes, fake news, disinformations, and the like.
- How do the public form opinion?
    - Public opinion is country-scale groupthink?
- https://www.thebalancecareers.com/how-politicians-use-media-to-win-elections-2315204
- http://www.ethicssage.com/2016/10/the-role-of-the-media-in-politics.html
- https://study.com/academy/lesson/how-the-media-covers-elections-other-government-activities.html
*** <2018-10-02> Ajar cara berpikir di sekolah
Unfortunately the brain doesn't come with an instruction manual.
**** Interpret human language using probabilistic logic, not classical logic; every adjective is continuous, not binary
Degree of truth is continuous, not binary.
**** Distinguish between facts and opinions
**** Think for yourself
**** Eat healthily
**** Objective reality, wishful thinking
**** Self-awareness of one's own thoughts
**** Justifying actions; requiring reasons for things; asking why; goal-directed behavior
*** Establish low-operational-cost power generation and transportation: solar power plants and sun-powered trucks.

Kita harus lepas dari pengaruh geopolitik minyak bumi supaya kita tidak terpengaruh pertengkaran negara lain.

Komponen termahal biaya operasional transportasi jarak jauh adalah bahan bakar fosil.

- <2018-09-29>
  - https://www.theguardian.com/business/2018/may/17/what-are-the-factors-driving-up-the-price-of-crude-oil
  - https://www.thehindu.com/business/Economy/why-are-crude-oil-prices-going-up/article23937146.ece
  - "Saudi Arabia Promised More Oil. So Why Are Prices Rising?" https://www.nytimes.com/2018/07/04/business/energy-environment/oil-prices-opec.html
  - https://www.thebalance.com/what-makes-oil-prices-so-high-3305654
  - https://now.tufts.edu/articles/why-price-oil-rising
  - https://www.quora.com/Gasoline-How-long-does-it-take-for-the-change-in-crude-oil-price-to-reach-end-consumers
    - My conclusion: Prices are quick to rise and slow to fall.
    - https://www.aol.com/2011/03/18/why-gas-prices-rise-quickly-but-fall-slowly/
    - https://www.telegraph.co.uk/finance/personalfinance/energy-bills/11044279/The-oil-price-puzzle-prices-are-quick-to-rise-but-slow-to-fall.html
  - https://oilprice.com/Energy/Energy-General/Why-Oil-Prices-Are-Surging.html

*** Basmi politik identitas; mulai desegregasi; basmi partisanisme; basmi tribal politics

- How Congress (and America) became so polarized - Jonathan Haidt https://www.youtube.com/watch?v=RhoGx7bTzko
  - Newt Gingrich started tribalism in the Republican party.

*** Sederhanakan hukum
You know your legal system is too complex when people can profit from that complexity.
*** <2018-09-19> Tertibkan pelacuran, narkoba, dan judi?

Kita jangan munafik.
Hal-hal ini sudah ada sejak manusia ada.
Hal-hal ini tidak bisa dihilangkan.

Solusinya adalah mendidik masyarakat, bukan melarang.
Larangan hanya akan membuat black market.

Laws can't go against human nature.

Masalah: NIMBY.
Mau dilokalisasi di mana?
Tentu di tempat yang sudah ada.
Resmikan tempat yang sudah ada.

Jual narkoba di alfamart/warung?
Atur kemasan harus sama semua.
Tidak boleh iklan.

Perlu update [[http://spkonline.bps.go.id/spkonline/help/klasifikasi/2][KBLI]] (Klasifikasi Baku Lapangan Usaha Indonesia).

https://www.straitstimes.com/asia/se-asia/malaysia-in-talks-to-become-first-in-asia-to-allow-medical-pot

*** <2018-09-19> Perbaiki sistem hukum?

**** Prinsip hukum

***** A law must not go against nature.

Banning prostitution does not respect nature.
Banning drugs does not respect nature.

***** A law must be practically enforceable.

Cabut semua aturan yang enforcement-nya tidak praktikal.

***** Regulate; don't ban.

**** <2018-09-19> Perjelas bagian UUD yang tidak jelas.

***** Naskah
   :PROPERTIES:
   :CUSTOM_ID: naskah
   :END:

- 2018-09-01: [[http://www.dpr.go.id/jdih/uu1945][UUD 1945]] (perubahan keberapa?)
- [[https://ngada.org/uud01-1945pjl.htm][Penjelasan UUD 1945 (naskah asli tanpa amandemen)]]
  (itu website apa?)

***** Cara mengubah UUD
   :PROPERTIES:
   :CUSTOM_ID: cara-mengubah-uud
   :END:

- Lihat pasal 37.
  Wewenang MPR.
- Pasal 37 ayat 5: "Khusus mengenai bentuk Negara Kesatuan Republik Indonesia tidak dapat dilakukan perubahan."
- Pasal 1 ayat 3: "Negara Indonesia adalah negara hukum."

***** Pemilu partai vs pemilu langsung?
   :PROPERTIES:
   :CUSTOM_ID: pemilu-partai-vs-pemilu-langsung
   :END:

- Pasal 22E ayat 3: "Peserta pemilihan umum untuk memilih anggota Dewan Perwakilan Rakyat dan anggota Dewan Perwakilan Rakyat Daerah adalah partai politik."

  - Mengapa partai?

    - Menyederhanakan pemilu.
    - Perkumpulan orang-orang setujuan?

  - Keburukan partai

    - Kebutuhan memenangkan suara membuat partai berpolitik praktis dan meninggalkan tujuannya?
    - [[https://tirto.id/corak-ideologi-partai-partai-di-indonesia-cJKc][Corak Ideologi Partai-Partai di Indonesia - Tirto.ID]]

      - Pertai di Indonesia hanya beda pendapat soal agama.
        Sisanya sama semua.
        Kurang variasi.
        Groupthink.

  - Partai berarti "bagian".

***** Pasal-pasal yang perlu dijelaskan
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-perlu-dijelaskan
   :END:

Pasal-pasal ini bertujuan mulia, tetapi kata-katanya tidak jelas secara hukum, sehingga tidak bisa ditegakkan.

- Pasal 27 ayat 1:
  "Segala warga negara bersamaan kedudukannya di dalam hukum dan pemerintahan dan wajib menjunjung hukum dan pemerintahan itu dengan tidak ada kecualinya."

  - Pasal tersebut tidak cocok menjadi hukum.
    Ia bukan definisi ataupun aturan, melainkan harapan.
  - Tidak ada cara untuk menjalankan pasal tersebut.
  - Tidak ada hukuman yang jelas untuk pelanggarannya.
    (Aturan tanpa hukuman sama saja tidak ada.)
  - Aturan yang sulit di-enforce sama saja tidak ada.
  - Diskriminasi adalah bagian manusia dan akan ada selama manusia ada.

- Pasal 27 ayat 3:
  "Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara."

  - Apa beda "berhak dan wajib" dan "wajib"?
  - Apa hukuman untuk pelanggarnya?
  - Apa arti kata "berhak"?
  - Bagaimana cara mengklaim suatu hak?

- Pasal 29 ayat 1: "Negara berdasar atas Ketuhanan Yang Maha Esa."

  - Apa arti kata "esa"?

    - Menurut [[https://kbbi.web.id/esa][KBBI daring]], kata "esa" berarti "satu".
      Tapi sumber ini kurang kuat.
      Bisa saja di-hack.
    - [[https://balebengong.id/kabar/melacak-asal-kata-esa-dalam-pancasila.html?lang=id][Melacak asal Kata Esa dalam Pancasila - BaleBengong]]
    - Pendapat ahli bahasa Indonesia

      - https://twitter.com/eggggsie/status/990073630653476864
      - https://twitter.com/harimbawa/status/989232636274008064
      - [[https://en.wiktionary.org/wiki/wish#Etymology][Wiktionary tidak sependapat soal asal usul kata "wish"]]

    - Perkelahian gara-gara kata "esa"

      - https://twitter.com/Mentimoen/status/946237996327686144
      - [[https://tirto.id/sejarawan-eggi-sudjana-ahistoris-dan-tak-paham-konsep-esa-cxVS][Sejarawan: Eggi Sudjana Ahistoris dan Tak Paham Konsep Esa - Tirto.ID]]

  - Sebaiknya kita ganti pasal tersebut dengan kata-kata yang umum di abad 21.
    Aturan harusnya dibuat supaya mudah dipahami.

- Pasal 31

  - Pasal 31 ayat 2: "Setiap warga negara wajib mengikuti pendidikan dasar dan pemerintah wajib membiayainya."
  - Pasal 31 ayat 4: "Negara memprioritaskan anggaran pendidikan sekurang-kurangnya dua puluh persen dari anggaran pendapatan dan belanja negara serta dari anggaran pendapatan dan belanja daerah untuk memenuhi kebutuhan penyelenggaraan pendidikan nasional."
  - Apa itu artinya sekolah harus digratiskan?
    Seandainya APBN tidak cukup bagaimana?
  - Pasal 31 ayat 3: "Pemerintah mengusahakan dan menyelenggarakan satu sistem pendidikan nasional, yang meningkatkan keimanan dan ketakwaan serta ahlak mulia dalam rangka mencerdaskan kehidupan bangsa, yang diatur dengan undang-undang."

    - Ini mungkin harus diubah supaya mengikutkan "toleransi".

- Pasal 32 ayat 1: "Negara memajukan kebudayaan nasional Indonesia di tengah peradaban dunia dengan menjamin kebebasan masyarakat dalam memelihara dan mengembangkan nilai-nilai budayanya."

  - Apa itu nilai budaya?
    Apakah budaya yang buruk juga harus dipelihara?
    Apa itu "buruk"?
    Sistem moral mana yang harus dipakai pemerintah?

- Pasal 32 ayat 2: "Negara menghormati dan memelihara bahasa daerah sebagai kekayaan budaya nasional."

  - Bagaimana caranya?

- Pasal 28H ayat 4: "Setiap orang berhak mempunyai hak milik pribadi dan hak milik tersebut tidak boleh diambil alih secara sewenang-wenang oleh siapapun."

  - Pasal ini sangat tidak jelas.
  - Pajak adalah pengambilan sebagian hak milik pribadi secara paksa oleh pemerintah.
    Bagaimana hubungan pajak dan ayat ini?

    - Apa yang dimaksud "hak milik"?
      Private property?
    - Hak milik untuk apa saja?
      Semua benda?
    - Tapi kepemilikan bisa dicabut?
      Apa beda kepemilikan dan hak milik?

  - Bertentangan dengan pasal 33 ayat 3?

    - Sepertinya tidak.
      Ayat ini tidak melarang /pembatasan/ jenis benda yang bisa dimiliki pribadi.

***** Pasal-pasal yang tidak perlu?
   :PROPERTIES:
   :CUSTOM_ID: pasal-pasal-yang-tidak-perlu
   :END:

Pasal-pasal ini mengatur hal-hal yang tidak usah disuruh pun orang akan melakukan.
Cara menegakkannya juga tidak jelas.

****** Tambahan pasal 28, sepertinya karena Pak Harto
    :PROPERTIES:
    :CUSTOM_ID: tambahan-pasal-28-sepertinya-karena-pak-harto
    :END:

Mungkin beberapa tambahan ini dibuat karena penculikan, penghilangan, dan penembakan misterius pada zaman Pak Harto.

- Pasal 28A: "Setiap orang berhak untuk hidup serta berhak mempertahankan hidup dan kehidupannya."
- Pasal 28B ayat 1: "Setiap orang berhak membentuk keluarga dan melanjutkan keturunan melalui perkawinan yang sah."

  - Tanpa dibolehkan pun orang akan kawin.
    Sebelum ada UUD 1945 pun orang sudah kawin.
    Mengapa bisa ada ayat ini di UUD?
    Apa latar belakangnya?
  - Setiap orang?
    Apakah semua orang boleh melanjutkan keturunan?
    Apakah orang yang tidak bisa mengurus anak sebaiknya melanjutkan keturunan?
    Apakah ekstremis sebaiknya melanjutkan keturunan?

- Pasal 28B ayat 2: "Setiap anak berhak atas kelangsungan hidup, tumbuh, dan berkembang serta berhak atas perlindungan dari kekerasan dan diskriminasi."
- Pasal 28C, 28D, 28E, 28F, 28G, 28H, 28I: you don't say. Bagaimana cara menegakannya?

***** Loopholes and undefined situations
   :PROPERTIES:
   :CUSTOM_ID: loopholes-and-undefined-situations
   :END:

- Pasal 24B ayat 3: "Anggota Yudisial diangkat dan diberhentikan oleh Presiden dengan persetujuan Dewan Perwakilan Rakyat."

  - Kalau DPR tidak setuju, lalu apa?

***** Mana lembaga negara tertinggi?
   :PROPERTIES:
   :CUSTOM_ID: mana-lembaga-negara-tertinggi
   :END:

- DPR lebih tinggi daripada Presiden.
  Presiden tidak bisa pecat DPR.

  - Pasal 7: DPR bisa pecat Presiden, tapi ada syaratnya.
  - Pasal 7C: "Presiden tidak dapat membekukan dan/atau membubarkan Dewan Perwakilan Rakyat."

- Tapi Presiden bisa memerintahkan militer untuk menyerang DPR?

  - Pasal 10: "Presiden memegang kekuasaan yang tertinggi atas Angkatan Darat, Angkatan Laut dan Angkatan Udara."

- DPR bisa mengatur sebagian yudikatif?

  - Pasal 24 ayat 3: "Badan-badan lain yang fungsinya berkaitan dengan kekuasaan kehakiman diatur dalam undang-undang."

***** Yang sudah baik
   :PROPERTIES:
   :CUSTOM_ID: yang-sudah-baik
   :END:

****** Sistem ekonomi paham tengah, berimbang antara kapitalisme dan sosialisme
    :PROPERTIES:
    :CUSTOM_ID: sistem-ekonomi-paham-tengah-berimbang-antara-kapitalisme-dan-sosialisme
    :END:

Pasal 27 ayat 2: "Tiap-tiap warga negara berhak atas pekerjaan dan penghidupan yang layak bagi kemanusiaan."

- Bagaimana cara enforcenya?
- Universal basic income?

Pasal 28H ayat 2: "Setiap orang berhak mendapat kemudahan dan perlakuan khusus untuk memperoleh kesempatan dan manfaat yang sama guna mencapai persamaan dan keadilan."

Pasal 33 ayat 1: "Perekonomian disusun sebagai usaha bersama berdasar atas asas kekeluargaan."

- Apa artinya?

Pasal 33 ayat 2: "Cabang-cabang produksi yang penting bagi negara dan yang menguasai hajat hidup orang banyak dikuasai oleh negara."

Apa arti "hajat hidup orang banyak" dan "dikuasai"?
Dikuasai tidak berarti dimiliki?

Apakah Gojek hajat hidup orang banyak?
Apakah transportasi umum (Kopaja, Metromini, Mikrolet, dll.) hajat hidup orang banyak?

Pasal 33 ayat 3: "Bumi dan air dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besar kemakmuran rakyat."

- Apa itu berarti tanah harus dikuasai negara?
  Orang tidak boleh punya tanah?
  Perusahaan air seperti Aqua, Oasis, Cleo, PAM, PDAM, dll. harus dikuasai negara?

Saya lebih suka orang tidak boleh memiliki tanah (hanya boleh menyewa tanah dari pemerintah).
Tapi bagaimana dengan bangunan di atasnya?

Pasal 33 ayat 4: "Perekonomian nasional diselenggarakan berdasar atas demokrasi ekonomi dengan prinsip kebersamaan, efisiensi berkeadilan, berkelanjutan, berwawasan lingkungan, kemandirian, serta dengan menjaga keseimbangan kemajuan dan kesatuan ekonomi nasional."

Apa arti "demokrasi ekonomi"?
Apa arti "efisiensi berkeadilan"?

"Kemandirian" berarti harus mengurangi impor, lalu memproduksi sebanyak mungkin macam barang dalam negeri?

Pasal 34 ayat 2: "Negara mengembangkan sistem jaminan sosial bagi seluruh rakyat dan memberdayakan masyarakat yang lemah dan tidak mampu sesuai dengan martabat kemanusiaan."

Mendasari BPJS, Jamsostek, dll..
Tinggal eksekusi yang baik.

Pasal 34 ayat 3: "Negara bertanggung jawab atas penyediaan fasilitas pelayanan kesehatan dan fasilitas pelayanan umum yang layak."

Mendasari RSUP, RSUD, dll.


**** <2018-09-19> Cabut aturan yang melarang hal-hal yang tidak membahayakan orang banyak.

Cabut aturan yang mengatur urusan pribadi.

**** <2018-09-19> Generalize aturan: Kriminalkan semua orang yang mengganggu ketertiban umum?

Problem: Ini bisa jadi pasal karet.

Tidak perlu ada aturan spesifik.
Aturan tentang ketertiban umum mencakup semua hal berikut:
- Membuat video porno tidak kriminal; menyebarkannya yang kriminal.
- Hubungan intim tidak kriminal; yang kriminal adalah membuat masyarakat resah.
- Menghujat tidak kriminal; yang kriminal adalah membuat masyarakat ribut.

**** <2018-09-19> Buat aturan contempt of court? Sebaiknya benahi hakim dan pengadilan dulu?

Ide Hotman Paris?

Tapi bagaimana kalau ada miscarriage of justice?
Aturan contempt of court akan memperparah miscarriage of justice.


**** Should we repeal blasphemy laws and obscenity laws?
   :PROPERTIES:
   :CUSTOM_ID: should-we-repeal-blasphemy-laws-and-obscenity-laws
   :END:

We already have laws for people causing public disorder.

- If a person commits blasphemy and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for blasphemy.
- If a person distributes obscene materials and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for distributing obscene materials.
- If a person causes public disorder to overthrow a corrupt government,
  then the government will try to vanquish the rebellion,
  but the people shall prevail?
- Blasphemy laws allow angry people to fight in the courtroom.
  Without blasphemy laws, angry people would fight on the road,
  where there are no rules, taking matter into their own hands.

  - However, blasphemy laws also allow religion
    to subvert the justice system.

- http://business-law.binus.ac.id/2018/07/10/bahaya-tafsir-a-historis-terhadap-pasal-156a-kuhp/

*** Buat profesi petani jadi menarik secara ekonomi.
*** <2018-09-19> Net neutrality, un-ban websites, Reddit, Vimeo, dll.

Tapi, apakah website ekstremis juga mau di-unblock?

**** Why is Reddit blocked in Indonesia?

- The official reason
  - Something like "Reddit is a porn site.".
  - http://www.mesinwaktu.id/2017/11/alasan-kenapa-reddit-diblokir.html
  - https://www.quora.com/Why-is-Reddit-blocked-by-the-Indonesian-government
  - Doesn't make sense.
    - There is porn on Reddit, but Reddit is not a porn site.
      There are also porn on Google, Bing, YouTube, Blogspot, but they aren't porn sites.
      Why block only Reddit?
      If you're following the law to the letter,
      why not block all of Internet?
- What I think the reason is
  - Someone in the government might need to be seen working.
    Sepertinya blokir website termasuk tugas kemkominfo dalam undang-undang.

*** Close international tax evasion loopholes

Make it impossible to hide money trail.
Require electronic cash with traceability/accounting/history.
Eliminate hard cash.

**** Rally all countries against the money-laundering countries

Tax havens are money launderers.

** Prinsip
*** My basic assumptions for legislating
- Humans are generally moral and peaceful, if their basic needs are met.
- Some humans are immoral or evil.
**** Hobbes vs Locke?
*** Start from the objective reality.
- Contoh:
  - Objektif: "Beberapa orang Indonesia tidak bisa membaca."
    Ada tes yang jelas untuk mengukur kemampuan membaca.
  - Tidak objektif: "Orang Indonesia malas."
    Apa definisi "malas"?
*** Work as close as possible to the root cause.
Misalnya dengan cara five whys.

Bisa juga dengan bertanya mengapa sampai kita tidak bisa jawab lagi.
Pertanyaan terakhir yang berhasil kita jawab itulah yang mau kita benahi.
*** Bigger changes should be slower
We don't want bloody revolutions (big fast changes).
** Hukum
*** Hapusnya hak atas tanah?
Saya punya tetangga yang menelantarkan rumahnya sampai rusak.
Berapa lama sebelum saya bisa main klaim bahwa tanah itu tanah saya?
- https://www.hukumproperti.com/pertanahan/hapusnya-hak-atas-tanah/
  - "karena ditelantarkan" PP 36/1998
    - Apakah bisa digunakan untuk tetangga yang meninggalkan rumahnya dan membiarkannya rusak?
*** Masalah sistem hukum, dan kasus menggantung
- https://nasional.tempo.co/read/793720/bnn-ada-72-mafia-narkoba-lain-freddy-masih-kelas-ecek-ecek
- http://akakristianto.com/2015/08/14/ungkap-kematian-pekerja-kebersihan-jis/
- http://nasional.republika.co.id/berita/nasional/hukum/15/06/05/npfrim-azwar-tersangka-jis-bukan-mati-bunuh-diri
- https://en.wikipedia.org/wiki/Munir_Said_Thalib
- [[https://news.detik.com/berita/4167913/ganti-rugi-tak-kunjung-cair-korban-salah-tangkap-gugat-menkeu?utm_source=twitter&utm_medium=oa&utm_content=detikcom&utm_campaign=cmssocmed][Ganti Rugi Tak Kunjung Cair, Korban Salah Tangkap Gugat Menkeu]]
  - Aturan 14 hari bayar.
    Itu sudah 2 tahun tidak bayar.
  - Betul kata Hotman Paris, Indonesia perlu aturan contempt of court (penghinaan terhadap lembaga peradilan).
    Selama tidak ada aturan itu, putusan pengadilan tidak dihargai.
*** Keluar masuk pegawai
- Polisi bisa? (tapi seharusnya tidak bisa?) https://nasional.kompas.com/read/2018/01/15/16055551/polisi-yang-sudah-masuk-ke-politik-seharusnya-tak-bisa-balik-lagi-ke-polri
- TNI tidak bisa https://news.detik.com/berita/d-3305012/setelah-mundur-agus-tak-bisa-kembali-ke-tni-kodam-jaya-itu-pilihannya
  - PNS TNI tidak bisa
- PNS lain bisa http://www.hukumonline.com/klinik/detail/lt59ae5a5d781fd/bolehkah-melamar-menjadi-pns-lagi-jika-pernah-berhenti-dengan-hormat-atas-permintaan-sendiri
** Agama
Agama adalah urusan pribadi, bukan urusan negara.

(Ini masih sesuai UUD?)
*** <2018-09-19> Akui semua agama, aliran, dan kepercayaan.
Ada sedikitnya 4000 agama/aliran/kepercayaan.

Syiah, Ahmadiyah, Tarekat Naqsabandiyah.

Agama Mesir kuno.
Paganisme.
Animisme.
Dinamisme.

Discordia, Church of the SubGenius, Flying Spaghetti Monster.
**** Aceh
- https://tirto.id/menilik-harta-kekayaan-cagub-cawagub-dki-bPPV
- https://tirto.id/benarkah-syariat-islam-menghambat-investasi-di-aceh-cP3C
- https://tirto.id/dana-otsus-dicabut-aceh-siap-bangkrut-cP54
**** Sejarah agama
- Agama, yang sekarang besar, awalnya dianggap sesat oleh orang-orang di sekitarnya.
- Pengikut Yesus awalnya dianggap sesat oleh pengikut Yahudi pada zamannya.
- Pengikut Muhammad awalnya dianggap sesat oleh pengikut polytheism Arab pada zamannya.
- Bayangkan seandainya seorang di kampung Anda tiba-tiba mengumumkan suatu agama baru.
- Mengapa kita lebih percaya orang 2000 tahun lalu daripada orang sekarang?
  Mengapa kita berpaku pada masa lalu?
  Mengapa kita tidak berusaha membuat masa depan jadi lebih indah?
*** <2018-09-19> Alihkan tugas departemen agama (umrah, naik haji dll.) kepada private sector.
*** <2018-09-19> Serahkan pendidikan agama sepenuhnya kepada keluarga.
- Mengganti pelajaran agama di sekolah dengan pelajaran /sejarah/ agama.
*** <2018-09-19> Kurangi/tiadakan ekstremisme/radikalisme
**** <2018-09-22> Wajibkan pelajaran sejarah agama
History of Islam?
Is Brigitte Gabriel's [[https://www.youtube.com/watch?v=o0m9nEafBE4][history-of-Islam video]] accurate?
**** Setiap ayat sensitif dalam kitab suci harus disertai tafsir/exegesis/interpretasi dan komentar tentang konteks sejarah turunnya ayat tersebut.
- Terutama Quran karena mayoritas penduduk Indonesia Muslim.
- Kitab suci bisa berupa buku kertas, aplikasi komputer, dll.
- Bagaimana cara mencegah [[https://en.wikipedia.org/wiki/Auto-segregation][WP:Auto-segregation]]?
  Asimilasi vs akulturasi vs absorpsi vs integrasi?
- Apakah efektif?
  Quran terjemahan ekstremis akan tetap saja beredar underground.
  Tapi kebijakan ini mungkin mempengaruhi Muslim moderat yang selama ini complicit atau bahkan diam-diam setuju dengan ekstremis.
- Kita sebaiknya tidak memaksakan/mengatur kepercayaan dengan undang-undang.
- Bagaimana seandainya ada orang mengarang kitab suci sendiri?
*** Kerusuhan SARA
- Tanjung Balai Sumatra Utara sering rusuh?

  - 2018, [[https://regional.kompas.com/read/2018/08/23/18025471/5-fakta-kasus-meiliana-menangis-di-sidang-hingga-fatwa-mui][5 Fakta Kasus Meiliana, Menangis di Sidang hingga Fatwa MUI - Kompas.com]]

    - [[https://www.facebook.com/ransibar/posts/10216709033187633][Keterangan Ranto Sibarani, anggota tim penasihat hukum tergugat]]
    - Coba tanya MUI Sumatra Utara:

      - Mengapa Jusuf Kalla boleh minta suara azan dikecilkan, tetapi Meiliana tidak boleh?

        - 2018, [[https://news.detik.com/berita/4179062/jk-nilai-kasus-meiliana-bukan-soal-toleransi][JK Nilai Kasus Meiliana Bukan Soal Toleransi]]
        - Karena JK wapres?

          - Seandainya wapresnya Meiliana, apa dia boleh minta suara azan dikecilkan?

            - Seandainya wapresnya Ahok?

      - Mengapa standar ganda?

        - Yang ini hanya kena teguran, tidak dipenjara: [[https://www.liputan6.com/regional/read/3614381/sebut-nabi-muhammad-sesat-ustaz-evie-effendie-kena-teguran-keras][Sebut 'Nabi Muhammad Sesat', Ustaz Evie Effendie Kena Teguran Keras - Regional Liputan6.com]]
        - 2018, [[https://news.detik.com/berita/4178495/pengeluh-volume-azan-dibui-18-bulan-bagaimana-perusak-vihara][Pengeluh Volume Azan Dibui 18 Bulan, Bagaimana Perusak Vihara?]]
          Hanya 1-2 bulan.

      - Mengapa PBNU tidak sepakat dengan MUI?

        - [[https://nasional.tempo.co/read/1119693/pbnu-icjr-dan-setara-kritik-vonis-kasus-penistaan-agama-meiliana][PBNU, ICJR dan Setara Kritik Vonis Kasus Penistaan Agama Meiliana - nasional Tempo.co]]
        - [[https://nasional.tempo.co/read/1119345/pbnu-katakan-suara-adzan-terlalu-keras-bukan-penistaan-agama/full&view=ok][PBNU: Katakan Suara Adzan Terlalu Keras Bukan Penistaan Agama - nasional Tempo.co]]
        - Jadi yang benar siapa?

  - 2018, [[http://medan.tribunnews.com/2018/05/15/ini-kronologis-penangkapan-terduga-teroris-di-tanjungbalai-satu-orang-tewas-di-tempat][Ini Kronologi Penangkapan Terduga Teroris di Tanjungbalai, Satu Orang Tewas di Tempat - Tribun Medan]]
  - 2018, [[https://www.viva.co.id/berita/nasional/1057980-dua-tahun-usai-kerusuhan-sara-toleransi-di-tanjung-balai-kian-kuat][Dua Tahun Usai Kerusuhan SARA, Toleransi di Tanjung Balai Kian Kuat -- VIVA]]

    - Baru dipuji sudah rusuh lagi.

  - 2016, [[https://tirto.id/tujuh-warga-jadi-tersangka-kerusuhan-tanjungbalai-bwtp][Tujuh Warga Jadi Tersangka Kerusuhan Tanjungbalai - Tirto.ID]]
  - 2016, [[http://jarumdetik.blogspot.com/2016/07/fakta-sebenarnya-di-balik-rusuh-tanjung.html][Fakta Sebenarnya di Balik Rusuh Tanjung Balai | Jarum Detik]]

    - Masyarakat setempat sudah dua kali terhasut berita bohong: 2016 dan 2018.

      - [[https://www.motivasi-islami.com/jangan-seperti-keledai-atau-lebih-parah/][Jangan Seperti Keledai Atau Lebih Parah - Motivasi Islami]]: Keledai saja tak jatuh dua kali ke lubang yang sama.

  - A person's beliefs filter all incoming information.
    Therefore people believe hoax that supports their beliefs, and reject facts that counter their beliefs.

    - Riots uncover true beliefs.
    - Kerusuhan adalah bukti bahwa toleransi hanya di permukaan.

  - UU 1/1965 tentang penodaan agama

    - [[https://tirto.id/asal-usul-delik-penistaan-agama-b49e][Asal-Usul Delik Penistaan Agama - Tirto.ID]]

** Teknologi

*** <2018-09-19> Kuasai infrastruktur Internet

Infrastruktur Internet adalah hajat hidup orang banyak, jadi harusnya dikuasai negara, sesuai pasal 33 ayat 3 UUD 1945.

*** <2018-09-21> Benahi keculasan Telkomsel dan korporat lainnya
- Beli paket data di Indonesia Barat; terbang ke Indonesia Tengah; paket data tidak berlaku.
- Simplify pricing.
  Harga paket data harus rata per GB, dan harus sama di semua Indonesia.
  Tidak boleh memahalkan pengguna kecil.
  - Daerah maju mensubsidi daerah tertinggal.
- Cabut iklan sisipan proxy Telkomsel.

Lapor ke LPK (Lembaga Perlindungan Konsumen):
https://www.reddit.com/r/indonesia/comments/9lj478/definisi_unlimited_di_hukum_indonesia_itu_apa_sih/e77cleu/

Di mana tuh LPK?

YLKI: "Bagaimana Menyampaikan Pengaduan Konsumen?"
https://ylki.or.id/2016/12/__trashed/

UU 8/1999 tentang perlindungan konsumen?
** Transportasi, lingkungan, pertanahan, tata kota

- Utamakan pejalan kaki dalam tata kota.

*** Self-driving buses for public transport can drive transport costs down?

- Which are the biggest transport cost component? Is it fuel or the driver?

*** Solusi kemacetan tol Jakarta?

- Solusi:
  - Pemda DKI, Bogor, Depok, Tangerang, dan Bekasi:
    - Pilihan 1: Membeli jalan tol menjadi jalan umum.
      - Lunasi atau cicil ke pemilik tol.
    - Pilihan 2: Menyewa jalan tol pada jam tertentu menjadi jalan umum.
      - Menaikkan pajak jalan untuk mobil.
        - [[https://en.wikipedia.org/wiki/Road_tax][WP:Road tax]]
        - Ditambah (rata-rata biaya tol) * (jumlah hari dalam setahun)
          - Ditambah Rp 7,200,000 per tahun?
      - Membuka semua pintu tol di Jakarta pada jam sibuk.
        - Kalau tidak bisa buka semua, buka yang paling bikin macet.
      - Membayar ganti rugi ke operator tol.
- Menyelesaikan dua masalah sekaligus:
  - Disinsentif untuk pengguna mobil pribadi.
  - Mengurangi kemacetan karena kelambatan gerbang tol.
- Skenario gagal:
  - Pemda tidak punya cukup uang.
  - Manusia egois.
    - Pemda sekitar DKI tidak mau patungan.
    - Pemilik mobil menolak bayar pajak demi kebaikan bersama.
    - Pemilik tol menolak penawaran karena terlalu serakah.



*** TODO <2018-09-17> Gratiskan kendaraan umum bertrayek

- Lebih mudah dan murah daripada integrasi antarmoda?
- Mengurangi trafik dan polusi.

**** <2018-09-19> Biaya yang diperlukan per jam-kendaraan (unit economics)

- Satuan unit economics: 1 jam-kendaraan
- Breakdown
  - Upah
    - 1 kendaraan butuh 2 orang operator (1 supir dan 1 kenek)
    - Upah 1 orang Rp 7 juta/160 jam ~ Rp 50000/jam
  - Bahan bakar
    - Penggunaan bahan bakar (fuel mileage), 5 km/liter, Rp 10000/liter
    - Kecepatan rata-rata 50 km/jam
    - Kendaraan beroperasi 24 jam per hari = 1200 km/hari = 240 liter/hari
  - Biaya perawatan kendaraan Rp ?/bulan
  - Asuransi kesehatan Rp ?/bulan
  - Asuransi kendaraan Rp ?/bulan

**** Potensi masalah dan penolakan

***** Pengemudi ojek, taksi, dan mobil sewa mungkin menolak karena pendapatan mereka mungkin berkurang

- Bantu mereka beralih jadi supir kendaraan umum bertrayek.

**** Negara lain yang sudah berhasil

- [[https://www.youtube.com/watch?v=ccxVYborUcU][Let's Make Mass Transit Free* - YouTube]]
  - Making mass transit free benefits everyone, including those who don't use mass transit.
    Free mass transit reduces traffic.

*** <2018-09-21> Perbaiki jembatan penyeberangan

<2018-09-21>
Jembatan penyeberangan di Jl. S. Parman Jakarta logamnya mencuat dan ukuran anak tangganya terlalu kecil.

*** Pentingnya infrastruktur
    :PROPERTIES:
    :CUSTOM_ID: pentingnya-infrastruktur
    :END:

[[https://www.bloomberg.com/quicktake/indonesias-nationalism][Bloomberg]]:
"A lack of roads and ports means it's cheaper to ship goods to China than across the archipelago."

Kok lebih murah ngirim barang ke Cina daripada ke Papua?
Padahal, menurut peta, jarak Jakarta-Hongkong mirip jarak Jakarta-Jayapura.

- [[https://www.youtube.com/watch?v=MFrLcRhMKnE][Geopolitics of Southeast Asia Part 2: Malay Archipelago - YouTube]]

  - Indonesia is too big to defend itself.

** Politik

Fix the system; berantas perverse incentive, principal-agent problem, dan conflict of interest.

*** Mengapa Indonesia tertinggal?

https://nasional.kontan.co.id/news/dua-alasan-indonesia-tertinggal-dari-negara-lain

Rizal Ramli:

- "Paradigmanya, tebang hutan, lalu ekspor. Sedot tanah di Papua lalu ekspor. Tidak dibangun industri hilir sehingga nilai tambahnya sedikit."
- "Saya minta tolong, perlu perubahan paradigma pengelolaan SDM dari sekadar sedot ekspor, kita kembangkan nilai tambahnya"

Kesimpulannya kita tertinggal karena selalu mencari jalan pintas / menang mudah yang kecil dan tidak matter.

*** Mudahkan pemilu untuk perantau

Pemilu serentak?
Sistem e-ktp nasional?

Pemilu harus ada bukti fisik seperti kertas, tidak boleh sepenuhnya bergantung ke komputer.

*** <2018-09-19> Evidence-based legislation? data-driven legislation?

*** <2018-09-19> Tertibkan kampanye politik

- membatasi kampanye hanya dalam bentuk prospektus (tertulis) berisi rencana program kerja, seperti yang sedang Anda lihat
- mengumpulkan prospektus dalam satu website
- melarang semua bentuk lain

*** <2018-09-19> Larang /lobbying/

Bukannya memang sudah dilarang?

*** <2018-09-17> Larang partai membayar anggota; wajibkan anggota membayar partai?

- Berantas politik karir?
  What's so bad about career politicians?
  A career is not bad in and of itself.
- Pastikan bahwa yang masuk adalah orang yang benar-benar peduli politik.
- Tapi kalau begini, politik jadi sampingan.
  Tidak semua orang mau punya 2 pekerjaan.

A party is a mini-country.
Therefore a party should tax its members, not pay its members.

Politics should not be a career path?

*** Pesimis soal partai baru
   :PROPERTIES:
   :CUSTOM_ID: pesimis-soal-partai-baru
   :END:

2014 ada partai baru: [[https://psi.id/][Partai Solidaritas Indonesia]].
Terus?
Semua partai juga pernah baru.
Semua partai juga didirikan dengan cita-cita mulia.

- Pada tahun 1927 PNI juga partai baru.
- Pada tahun 1964 Golkar juga partai baru.
- Pada tahun 1973 PDI juga partai baru.
- Pada tahun 2001 Partai Demokrat juga partai baru.
- Pada tahun 2002 PKS juga partai baru.
- Pada tahun 2008 Gerindra juga partai baru.
- Semua partai baru itu akhirnya terlibat masalah.

Bagaimana kita menjamin partai baru tidak terjerembab ke lubang korupsi?

Ada siklus:

- Partai baru didirikan karena ketidakpuasan terhadap partai lama.
- Setelah lama, partai baru jadi partai lama, dan terlibat masalah.
- Ulangi.

Kalau semua partai terlibat masalah,
sistem pemerintahan perlu diperbaiki?
Pemisahan perlu diperbaiki?
Insentif perlu dirancang lebih baik?

Umpama anak sekolah:

- Kalau satu anak gagal, mungkin anaknya yang salah.
- Kalau satu kelas banyak yang gagal, mungkin kelasnya yang salah.
- Kalau banyak kelas gagal, mungkin sekolahnya yang salah.
- Kalau banyak sekolah gagal, mungkin sistem pendidikannya yang salah.

Umpama partai:

- Kalau satu orang korup, mungkin orangnya yang salah.
- Kalau satu partai banyak yang korup, mungkin partainya yang salah.
- Kalau banyak partai korup, mungkin hukum negara ini yang salah.

Diskusi:

- [[https://www.quora.com/What-do-Indonesians-know-think-about-the-new-party-PSI-Partai-Solidaritas-Indonesia-And-how-big-is-the-chance-that-the-PSI-will-get-a-place-in-the-parliament][What do Indonesians know/think about the new party PSI (Partai Solidaritas Indonesia)? And how big is the chance that the PSI will get a place in the parliament? - Quora]]

**** Sistem kita mengubah orang muda idealis menjadi orang tua korup?

Orang baik dalam sistem buruk akan jadi orang buruk.

- https://theconversation.com/buasnya-sistem-politik-indonesia-halangi-upaya-reformasi-dari-dalam-oleh-mantan-aktivis-94523

Bagaimana memperbaikinya?

*** Ucapan terima kasih
   :PROPERTIES:
   :CUSTOM_ID: ucapan-terima-kasih
   :END:

**** Terima kasih Gus Dur
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-gus-dur
    :END:

Imlek jadi libur.

Diskriminasi berkurang.

WNI keturunan Cina bisa masuk universitas negeri.

**** Terima kasih Ahok
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-ahok
    :END:

- Rumah saya baru bebas banjir pada zaman BTP (Basuki Tjahaja Purnama a.k.a. Ahok).

  - Tahun 1990-an setiap 5-6 tahun sekali, rumah banjir.
  - Makin lama makin parah. Tiap tahun banjir.
  - Bahkan, pernah suatu ketika, tidak hujan malah banjir.
  - Jalanan dinaikkan 50 cm. Rumah dinaikkan 100 cm. Tetap banjir.
  - Saat BTP menjabat, rumah saya tidak banjir.

Namun, hal yang saya tidak setuju:

- Omongan kurang dijaga, mungkin terbawa emosi.
  Akhirnya kata-katanya dipakai untuk menyerang dia.
- Utilitarianisme.
  [[https://en.wikipedia.org/wiki/Trolley_problem][WP:Trolley problem]] menyiratkan bahwa utilitarianisme tidak cocok jadi prinsip moral.
  Saya hargai kemampuan problem-solving dan kecepatan kerja Ahok, tapi soal prinsip moral ini saya tidak setuju.

  - [[https://news.detik.com/berita/2998358/ham-versi-ahok-untuk-melindungi-rakyat-banyak][HAM Versi Ahok untuk Melindungi Rakyat Banyak]]

*** Peduli rakyat kecil
   :PROPERTIES:
   :CUSTOM_ID: peduli-rakyat-kecil
   :END:

- Student activism

  - [[https://twitter.com/semarui?lang=en][SEMAR UI]]
  - [[https://twitter.com/rakapare?lang=en][Komune Rakapare]]

*** 1998
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

- [[https://www.reddit.com/r/indonesia/comments/61ed2m/what_was_indonesia_like_before_reformasi_and/][What was Indonesia like before Reformasi and after1998? (Long) : indonesia]]
- [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/][Telegram from US Embassy Jakarta to State Department, "Who Is Behind [1998] Disappearances?," : indonesia]]

  - [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/e4a0s02/][Pendapat redditor fourrier01]]: "Every year, just before election, there's always a news to reveal Prabowo stench over and over. 4 years ago there was Allan Nairn. [...] This one isn't so surprising anymore."

*** Pemilihan Presiden 2019
   :PROPERTIES:
   :CUSTOM_ID: pemilihan-presiden-2019
   :END:

- https://www.reddit.com/r/indonesia/comments/9640by/rekam_jejak_sikap_dan_perkataan_maruf_amin/

  - https://www.reddit.com/r/indonesia/comments/9631cu/maruf_amin_dulu_saya_yang_menggerakkan_aksi_212/

- [Pendapat seorang redditor dengan username kurang elok](https://www.reddit.com/r/indonesia/comments/97bncz/mahfud_sebut_maruf_amin_suruh_nu_ancam_jokowi/e472v4s/] tentang Maruf Amin, calon wakil presiden 2019. Pendapat ini terdengar gila, tapi mungkin. Entah.

  - "Sesuai UU kita, ketika presiden gak ada (karena meninggal atau lengser) wapres langsung auto-presiden. Disini ada insentif besar utk kaum mereka bunuh atau lengserkan presiden."

- Belum dibaca

  - [[https://www.reddit.com/r/indonesia/comments/983if1/pros_of_jokowi/][Pros of Jokowi : indonesia]]
  - [[https://www.reddit.com/r/indonesia/comments/982c5x/why_fear_over_islamists_in_prabowos_future/][Why Fear Over Islamists in Prabowo's Future Government is Unfounded : indonesia]]

*** Pendapat-pendapat yang edgy tapi mungkin ada benarnya
   :PROPERTIES:
   :CUSTOM_ID: pendapat-pendapat-yang-edgy-tapi-mungkin-ada-benarnya
   :END:

**** Jalan tol adalah tindak kejahatan.
    :PROPERTIES:
    :CUSTOM_ID: jalan-tol-adalah-tindak-kejahatan.
    :END:

- Jalan tol adalah jalan pribadi (jalan milik perusahaan, bukan jalan umum).
- Jalan S. Parman, Jalan Gatot Subroto, dan Jalan M.T. Haryono adalah jalan umum.
- Dahulukan kepentingan umum sebelum kepentingan pribadi, menurut pendidikan kewarganegaraan yang diajarkan di SD.
- Antrian tol memacetkan jalan umum.
- Sebagian kemacetan di jalan umum tersebut terjadi
  karena pemerintah membiarkan pengelola jalan tol mendahulukan kepentingan pribadi.

  - Jika antrian terlalu panjang, polisi seharusnya berhak mempercepat antrian dengan cara:

    - memaksa mengalihkan mobil dari antrian ke jalan biasa
    - memaksa membuka gerbang tol

- Tugas pemerintah hanya dua:

  - Melakukan hal yang menguntungkan banyak orang.
  - Mencegah hal yang merugikan banyak orang.

- Seandainya Pemda DKI Jakarta hendak membeli sebagian ruas jalan tol untuk dijadikan jalan umum,
  berapa biaya per kilometernya?

*** Pertanyaan-pertanyaan yang belum terjawab
   :PROPERTIES:
   :CUSTOM_ID: pertanyaan-pertanyaan-yang-belum-terjawab
   :END:

- How to combat people who provoke you and then cry foul?
- Undigested

  - Why do Habib Rizieq supporters support him?
  - 2017-06-23 government announces that they will take Rp344 trillion loan. Source?
  - If Sukarno hadn't fallen, would he have been like Gajah Mada, Washington, Castro, Kim, Mao, Stalin, Khan, or someone else?
  - Bagaimana cara impor?
  - Bagaimana cara ekspor?

- Indonesia needs a website like politifact or factcheck.org.
- Is the 21st century is the age of demagogues, or has it always been the case?
  When did candidates begin appealing to emotion using racism and religion?
  Donald Trump?
  Anies Baswedan?

**** Ada Mata Najwa, mengapa tidak ada Tangan Najwa?
    :PROPERTIES:
    :CUSTOM_ID: ada-mata-najwa-mengapa-tidak-ada-tangan-najwa
    :END:

- Apa ada hal seperti acara televisi Mata Najwa tetapi berupa tulisan?
  Tangan Najwa gitu?

**** Mengapa kita tidak minta tolong cenayang panggil arwah Bung Karno dan tanyakan kebenaran G30S PKI dan Supersemar?
    :PROPERTIES:
    :CUSTOM_ID: mengapa-kita-tidak-minta-tolong-cenayang-panggil-arwah-bung-karno-dan-tanyakan-kebenaran-g30s-pki-dan-supersemar
    :END:

Mengapa kita tidak tanya istrinya, anaknya, kerabatnya, teman-temannya?

**** Program 1000 startup ke mana?
    :PROPERTIES:
    :CUSTOM_ID: program-1000-startup-ke-mana
    :END:

- [[https://www.reddit.com/r/indonesia/comments/98afrg/anyone_know_what_happened_to_1000_startup_i_found/][Anyone know what happened to 1000 Startup? I found these three comments in a video about them. : indonesia]]

** Kesehatan

*** Permurah kesehatan?

Mengapa kesehatan mahal?

Mengapa rumah sakit mahal?

*** <2018-09-19> Ban buffets/all-you-can-eat restaurants

- Unhealthy. Induces overeating.
- Dishonest pricing.
  - [[https://www.insideedition.com/athlete-banned-all-you-can-eat-sushi-buffet-eating-too-much-46845][Athlete Banned From All-You-Can-Eat Sushi Buffet for Eating Too Much | Inside Edition]]
    - Why do you ban people?
      You know what you sign up for.
      You know everyone's diet is different.
      The eater does nothing wrong.
      If you don't like people eating too much, open a conventional a la carte restaurant.
      Buffets are food casinos.
      Buffets are insurance.
      They are all actuarial.
      It's unfair if you only want the money but don't want the risk.

*** <2018-09-19> Bantu petani tembakau dan buruh tembakau cari pekerjaan lain

*** <2018-09-22> Legalkan aborsi
Forcing someone to live the life he does not want is more immoral than killing him.
This also implies:

- We should let people kill themselves if they have thought about it well, as long as they are done privately.
  - But https://www.speakingofsuicide.com/2013/05/19/why-stop-someone-from-suicide/ dissents:
    - "The most important reason to prevent suicide is that suicidal crises, though formidable and painful, almost always are temporary.
      Even if the person continues thinking about suicide, the intense suicidal intent usually subsides.
      Consider that 90% of people who survive a suicide attempt do not go on to die by suicide.
      That number is very revealing.
      Even among people who wanted to die so strongly that they tried to end their life, most ultimately chose to live."
      - People don't know what they want.
        We don't know what we want.
- We should not prolong the suffering of dying people by forcing life support.

No baby consents to being killed.
No baby consents to being born either.
** Ekonomi

*** Prinsip ekonomi

- Mandirikan bangsa.
  Maksimalkan produksi dalam negeri.
  Kemandirian adalah syarat perlu tetapi tidak cukup untuk kedaulatan.

*** Kurangi nilai impor.

- Tingkatkan produksi dalam negeri, terutama industri strategis, teknologi.
- Bangun daerah tertinggal, kurangi urbanisasi.

*** Bantuan langsung tunai (BLT) = cash transfers
   :PROPERTIES:
   :CUSTOM_ID: bantuan-langsung-tunai-blt-cash-transfers
   :END:

- [[https://www.livemint.com/Politics/144kmvZXyDiM40UxY66DYJ/Targeted-cash-transfer-schemes-can-do-more-harm-than-good.html][Targeted cash transfer schemes can do more harm than good - Livemint]]
- Giving money to poor people immediately increases their purchasing power, but there are consequences.
- They buy things, increasing demand.
- If there is not enough supply, then prices rise.
- Conclusion:

  - In the short term, cash transfers provides immediate relief to poor people.
  - In the long term, cash transfers hurts the poor people it intends to help.
  - To help the poor, the government should increase the supply of goods to the poor.

    - Ideal permanent strategic solution: increase aggregate efficiency to drive down costs.

      - Localize production.
        Avoid transportation.
        Transportation is waste.
      - Depend on renewable energy.
        The sun is free!
        Wind is free!
        The TCO (total cost of ownership) of solar is approaching that of coal/oil?
      - Good infrastructure to reduce transport time/cost.
      - Integrate transport modes to reduce transport costs?

    - Quick temporary tactical solution: subsidies.

- Basic income is unconditional cash transfers.
** Survei tanah, konflik agraria, sertifikasi tanah?

** Pendidikan
*** Tingkatkan gaji dan mutu guru?

*** <2018-09-22> Perbaiki cara mengajar sejarah

- Tidak perlu menghapal hal-hal yang dicari dalam 1 menit di Internet.
- Yang penting ialah memahami sebab/konteks sesuatu terjadi, terutama perang.

*** 100% literacy rate; budayakan membaca dan menulis

Jordan Peterson: "The best way to teach people critical thinking is to teach them to write." ([[https://www.youtube.com/watch?v=x0vUsxhMczI][source]])

*** Bahasa Inggris (dan Mandarin?)

*** Memberantas kebodohan
   :PROPERTIES:
   :CUSTOM_ID: memberantas-kebodohan
   :END:

**** Benci suku tertentu itu merugikan diri sendiri

WNI keturunan Cina itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Cina?
Pemerintah Cina saja tidak peduli.

WNI keturunan Arab itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Arab?
Pemerintah Arab saja tidak peduli.

WNI keturunan India itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah India?
Pemerintah India saja tidak peduli.

Dan seterusnya.
** Golkar (golongan karya, functional group)

https://historia.id/modern/articles/golkar-sebagai-pengganti-partai-vxmrP:
"Mulanya golongan fungsional atau golongan karya adalah pengganti sistem kepartaian. Sukarno yang menggagasnya."

https://www.tutor2u.net/politics/reference/functional-representation

http://www.oxfordreference.com/view/10.1093/acref/9780199207800.001.0001/acref-9780199207800-e-524
"Functional representation may be contrasted to the more usual form of territorial representation [...]"

https://www.kompasiana.com/faizrahman/54f82194a33311ae608b4bde/urgensi-perwakilan-fungsional-dalam-majelis-permusyawaratan-rakyat

https://id.wikipedia.org/wiki/Utusan_Golongan
** Berinteraksi dengan pemerintah
   :PROPERTIES:
   :CUSTOM_ID: berinteraksi-dengan-pemerintah
   :END:

- [[https://www.reddit.com/r/indonesia/comments/97pzfs/adakah_cara_untuk_browsing_mencari_uu_permen_dll/][Adakah cara untuk browsing / mencari UU, PERMEN, dll berdasarkan topik? : indonesia]]

  - JDIH (Jaringan Dokumentasi dan Informasi Hukum)

Kontak DPR, sampaikan aspirasi
Kenapa ada banyak cara?
Yang mana yang dipakai?

- http://www.adangdaradjatun.com/berita-dpr/1769-cara-mengadu-ke-dpr
- http://satulayanan.id/layanan/index/92/pengaduan-anggota-dpr/dpr-ri
- https://pengaduan.dpr.go.id
- http://www.dpr.go.id/index/kontak
- https://mobile.twitter.com/DPR_RI/status/558192636222132224
- http://rumahaspirasi.dpr.go.id/layanan
- http://m.metrotvnews.com/play/2015/03/22/374732

*** Mengubah sistem hukum dari retributive justice ke restorative justice
    :PROPERTIES:
    :CUSTOM_ID: mengubah-sistem-hukum-dari-retributive-justice-ke-restorative-justice
    :END:

- http://ksp.go.id/pemerintah-luncurkan-portal-aspirasi-dan-pengaduan-nasional/index.html
- Bergabung saja ke ANRKUHP.
  Liaison ANRKUHP dan RJI (Restorative Justice International/Indonesia)?

  - https://m.cnnindonesia.com/nasional/20180612195019-12-305684/icjr-dorong-20-hukuman-alternatif-selain-penjara-di-rkuhp

- ICJR.

Kapan terakhir kali RJI mengirim surat/email ke DPR?
Surat tersebut ditujukan kepada bagian DPR yang mana?

*** Jangan penjarakan koruptor. Cukup sita curiannya.
    :PROPERTIES:
    :CUSTOM_ID: jangan-penjarakan-koruptor.-cukup-sita-curiannya.
    :END:

Koruptor tidak takut dipenjara.
Koruptor takut miskin.

** Deradikalisasi seperti Singapura
   :PROPERTIES:
   :CUSTOM_ID: deradikalisasi-seperti-singapura
   :END:

Contohlah Singapura.
Mereka mencampur penduduk berbeda suku dalam setiap pemukiman.

** Cara memilih anggota DPR dan DPD
   :PROPERTIES:
   :CUSTOM_ID: cara-memilih-anggota-dpr-dan-dpd
   :END:

- Anda memilih partai politik. Anda tidak memilih anggota DPR secara langsung. (UUD 1945 pasal 22E ayat 3.)
- Anda memilih anggota DPD secara langsung. (UUD 1945 pasal 22E ayat 4.)

Cari dan pahami latar belakang, profil, dan cita-cita partai-partai politik.

Pilih partai yang cita-citanya sejalan dengan cita-cita Anda.

Partai tersebut akan menempatkan beberapa anggota mereka di DPR.

Bantu mereka melaksakan tugas dengan memberi saran, melaporkan penyimpangan, dll.

** Mencari partai
   :PROPERTIES:
   :CUSTOM_ID: mencari-partai
   :END:

Saya mencari partai orang yang berpikir mandiri.

** Komputerisasi untuk menidakmungkinkan korupsi?
   :PROPERTIES:
   :CUSTOM_ID: komputerisasi-untuk-menidakmungkinkan-korupsi
   :END:

Karena komputer zakelijk.
Tidak ada kongkalikong.

** Tumpang tindih tugas BPK, KPK, polisi, bareskrim, tim tastipikor, dll.?
   :PROPERTIES:
   :CUSTOM_ID: tumpang-tindih-tugas-bpk-kpk-polisi-bareskrim-tim-tastipikor-dll.
   :END:

Semuanya sama-sama memeriksa keuangan.

** Hancurnya negara ini adalah salah kita yang menolak berpolitik.
   :PROPERTIES:
   :CUSTOM_ID: hancurnya-negara-ini-adalah-salah-kita-yang-menolak-berpolitik.
   :END:

Menolak berpolitik berarti membiarkan negara hancur.

Menolak berpolitik berarti membiarkan pengacau menang.

Membiarkan kesalahan artinya ikut salah.

Membiarkan penindasan artinya ikut menindas.

Membiarkan ekstremis merajalela artinya merestui ekstremisme.

[[https://en.wikipedia.org/wiki/First_they_came_...][WP:First they came...]]

** Legislatif lebih penting daripada eksekutif.
   :PROPERTIES:
   :CUSTOM_ID: legislatif-lebih-penting-daripada-eksekutif.
   :END:

Media harus lebih banyak meliput legislatif daripada eksekutif.

Selama ini media salah.
Yang diliput eksekutif terus.
Legislatif lebih penting.

Legislatif membentuk sistem.

Legislator bagus akan mencegah eksekutor buruk.
Eksekutor bagus tidak bisa mengatasi legislator buruk.

Lebih mudah meliput eksekutif karena ada kegiatan yang tampak.

Meliput legislatif lebih susah karena harus mengerti filsafat hukum.

** Fadli Zon Library
   :PROPERTIES:
   :CUSTOM_ID: fadli-zon-library
   :END:

[[https://id.wikipedia.org/wiki/Fadli_Zon_Library][WP:Fadli Zon Library]]

Ada kajian/diskusi?
Jadwal?

** Mengatasi sesat pikir
   :PROPERTIES:
   :CUSTOM_ID: mengatasi-sesat-pikir
   :END:

- [[http://partaigerindra.or.id/2015/04/28/gerindra-dukung-eksekusi-mati-agar-bandar-narkoba-jera.html][Gerindra Dukung Eksekusi Mati Agar Bandar Narkoba Jera]]

  - Orang mati mana bisa jera (kapok)?
    Kalau mau bikin orang jera, suruh dia ganti rugi.
    Obati semua korbannya.
    Kembalikan masa depan mereka yang hilang.
    Bayar.

** Narasi berbeda antara eksekutif dan legislatif
   :PROPERTIES:
   :CUSTOM_ID: narasi-berbeda-antara-eksekutif-dan-legislatif
   :END:

Eksekutif bilang ekonomi tumbuh.
Legislatif bilang hidup makin sulit.

Dua-duanya betul.
Ekonomi tumbuh.
GDP memang tumbuh.
Tapi apa arti GDP?
** Kewajiban dan hak warga negara
*** BPJS?
- [[https://daftar.bpjs-kesehatan.go.id/bpjs-checking/][Cek saldo BPJS]]
- [[https://sso.bpjsketenagakerjaan.go.id/registrasi.bpjs][Ini registrasi apa?]]
  Kenapa harus registrasi?
*** Pemerintah menyediakan akses ke jurnal berbayar? Di mana? Cara pakainya?
*** Jangan abstain dalam pemilu.
Lihat argumen [[https://www.reddit.com/r/indonesia/comments/968qbs/ajakan_untuk_yang_tidak_cocok_dengan_pasangan/e3yw8bd/][/u/kolormelar]].
*** Bayar pajak
- https://djponline.pajak.go.id/account/login
  - http://www.pajak.go.id/article/jangan-panik-jika-lupa-kode-efin-ikuti-langkah-berikut
** Internet censorship in Indonesia
- <2017-10-06> The ministry spent IDR 211 billion to censor the Internet. https://kominfo.go.id/content/detail/10860/kominfo-umumkan-pemenang-tender-mesin-sensor-internet-rp-211-miliar/0/sorotan_media
- <2018-08-09> The ministry begins censoring Google search results. https://tekno.kompas.com/read/2018/08/09/17183717/mulai-besok-netizen-indonesia-tak-bisa-lagi-googling-gambar-porno
** BPJS?
https://pinterpolitik.com/dokter-goodbye-jokowi/

<2018-11-02>
Dalam praktek, BPJS hanya bagus buat PNS, dan shitty buat non-PNS.
- https://www.reddit.com/r/indonesia/comments/9t2hby/anyone_using_health_insurance/
  - Ada orang yang *lima* kerabatnya *mati* karena *BPJS terlalu lambat*.
  - I can confirm that.
    Orang tua saya nunggu *12 jam* ngantri di rumah sakit pakai BPJS.
    Berangkat pagi, pulang malam.
    Padahal hanya periksa.
    12 jam itu nunggunya doang.
    Orang-orang rumah sakitnya juga ogah-ogahan.
- https://www.reddit.com/r/indonesia/comments/832kmh/dokter_protes_ke_pemerintah_dibayar_seharga/

** Negara tidak perlu mengatur agama.
- https://www.reddit.com/r/indonesia/comments/9r72uj/pgi_keberatan_atas_2_pasal_di_ruu_pesantren_dan/
** Laporan penggunaan pajak oleh negara
- https://www.kemenkeu.go.id/alokasipajakmu
  - https://www.reddit.com/r/indonesia/comments/9qkd3m/as_an_early_adult_who_recently_graduated_from/
** Indonesia market research: effect of sharia label on buying propensity?
Does slapping a sharia label on a hotel increases its sales?
** Twitter
- [[https://twitter.com/Julie_C_Hwang][Julie Chernov Hwang]] "Professor. Author. Why Terrorists Quit: The Disengagement of Indonesian Jihadists @cornellpress. I research entry & exit from terrorism. Islamism. SE Asia"
- https://twitter.com/pscindo
- https://kyotoreview.org/issue-24/twenty-years-after-suharto-dynastic-politics-and-signs-of-subnational-authoritarianism/
  - What is subnational authoritarianism?
  - "In 2013, the Indonesian Ministry of Home Affairs found that at least 60 political dynasties exist throughout Indonesia."
  - "During Suharto’s regime, dynastic politics did not exist at the subnational level, except at the village level."
  - "Dynastic politics is a rational option for politicians who aspire to prolong and strengthen their grip on local politics."
