#+TITLE: Cita-cita politik
#+DATE: 2018-04-15 00:00 +0700
#+PERMALINK: /politik.html

* Catatan: semua ini baru ide; masih bisa berubah.

* Prinsip

** Start from the objective reality.

- Contoh:
  - Objektif: "Beberapa orang Indonesia tidak bisa membaca."
    Ada tes yang jelas untuk mengukur kemampuan membaca.
  - Tidak objektif: "Orang Indonesia malas."
    Apa definisi "malas"?

** Work as close as possible to the root cause.

Misalnya dengan cara five whys.

Bisa juga dengan bertanya mengapa sampai kita tidak bisa jawab lagi.
Pertanyaan terakhir yang berhasil kita jawab itulah yang mau kita benahi.


* Cita-cita diurutkan mulai dari yang terpenting?

** <2018-09-26> (hukum) Ganti /retributive justice/ dengan /restorative justice/.

- Siapa yang berwenang mengubah sistem hukum indonesia menjadi restorative justice?
- Bagaimana melobi pihak berwenang?
- Berapa besar usaha yang diperlukan untuk mengubah sistem hukum yang sekarang?
- Bagaimana rencana transisi?
- Bagaimana memastikan sistem tidak disalahgunakan?
- Bagaimana meminimalkan kerusakan yang mungkin ditimbulkan hakim yang salah?

** <2018-09-28> Establish zero-operation permaculture

- zero operational cost
- ecological engineering https://en.wikipedia.org/wiki/Ecological_engineering
- https://en.wikipedia.org/wiki/Ecosystem_engineer#Humans_as_ecosystem_engineers

** <2018-09-19> Tertibkan pelacuran, narkoba, dan judi?

Kita jangan munafik.
Hal-hal ini sudah ada sejak manusia ada.
Hal-hal ini tidak bisa dihilangkan.

Solusinya adalah mendidik masyarakat, bukan melarang.
Larangan hanya akan membuat black market.

Laws can't go against human nature.

Masalah: NIMBY.
Mau dilokalisasi di mana?
Tentu di tempat yang sudah ada.
Resmikan tempat yang sudah ada.

Jual narkoba di alfamart/warung?
Atur kemasan harus sama semua.
Tidak boleh iklan.


** <2018-09-19> Perbaiki sistem hukum

*** Prinsip hukum

**** A law must not go against nature.

Banning prostitution does not respect nature.
Banning drugs does not respect nature.

**** A law must be practically enforceable.

Cabut semua aturan yang enforcement-nya tidak praktikal.

**** Regulate; don't ban.

*** <2018-09-19> Perjelas bagian UUD yang tidak jelas.

*** <2018-09-19> Cabut aturan yang melarang hal-hal yang tidak membahayakan orang banyak.

Cabut aturan yang mengatur urusan pribadi.

*** <2018-09-19> Generalize aturan: Kriminalkan semua orang yang mengganggu ketertiban umum?

Problem: Ini bisa jadi pasal karet.

Tidak perlu ada aturan spesifik.
Aturan tentang ketertiban umum mencakup semua hal berikut:
- Membuat video porno tidak kriminal; menyebarkannya yang kriminal.
- Hubungan intim tidak kriminal; yang kriminal adalah membuat masyarakat resah.
- Menghujat tidak kriminal; yang kriminal adalah membuat masyarakat ribut.

*** <2018-09-19> Buat aturan contempt of court? Sebaiknya benahi hakim dan pengadilan dulu?

Ide Hotman Paris?

Tapi bagaimana kalau ada miscarriage of justice?
Aturan contempt of court akan memperparah miscarriage of justice.


*** Should we repeal blasphemy laws and obscenity laws?
   :PROPERTIES:
   :CUSTOM_ID: should-we-repeal-blasphemy-laws-and-obscenity-laws
   :END:

We already have laws for people causing public disorder.

- If a person commits blasphemy and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for blasphemy.
- If a person distributes obscene materials and causes public disorder,
  then that perpetrator should be arrested for causing public disorder,
  not for distributing obscene materials.
- If a person causes public disorder to overthrow a corrupt government,
  then the government will try to vanquish the rebellion,
  but the people shall prevail?
- Blasphemy laws allow angry people to fight in the courtroom.
  Without blasphemy laws, angry people would fight on the road,
  where there are no rules, taking matter into their own hands.

  - However, blasphemy laws also allow religion
    to subvert the justice system.

- http://business-law.binus.ac.id/2018/07/10/bahaya-tafsir-a-historis-terhadap-pasal-156a-kuhp/


** Buat profesi petani jadi menarik secara ekonomi.



* Hukum

** Hapusnya hak atas tanah?
   :PROPERTIES:
   :CUSTOM_ID: hapusnya-hak-atas-tanah
   :END:

Saya punya tetangga yang menelantarkan rumahnya sampai rusak.
Berapa lama sebelum saya bisa main klaim bahwa tanah itu tanah saya?

- https://www.hukumproperti.com/pertanahan/hapusnya-hak-atas-tanah/

  - "karena ditelantarkan" PP 36/1998

    - Apakah bisa digunakan untuk tetangga yang meninggalkan rumahnya dan membiarkannya rusak?

** Masalah sistem hukum, dan kasus menggantung
   :PROPERTIES:
   :CUSTOM_ID: masalah-sistem-hukum-dan-kasus-menggantung
   :END:

- https://nasional.tempo.co/read/793720/bnn-ada-72-mafia-narkoba-lain-freddy-masih-kelas-ecek-ecek
- http://akakristianto.com/2015/08/14/ungkap-kematian-pekerja-kebersihan-jis/
- http://nasional.republika.co.id/berita/nasional/hukum/15/06/05/npfrim-azwar-tersangka-jis-bukan-mati-bunuh-diri
- https://en.wikipedia.org/wiki/Munir_Said_Thalib
- [[https://news.detik.com/berita/4167913/ganti-rugi-tak-kunjung-cair-korban-salah-tangkap-gugat-menkeu?utm_source=twitter&utm_medium=oa&utm_content=detikcom&utm_campaign=cmssocmed][Ganti Rugi Tak Kunjung Cair, Korban Salah Tangkap Gugat Menkeu]]

  - Aturan 14 hari bayar.
    Itu sudah 2 tahun tidak bayar.
  - Betul kata Hotman Paris, Indonesia perlu aturan contempt of court (penghinaan terhadap lembaga peradilan).
    Selama tidak ada aturan itu, putusan pengadilan tidak dihargai.

** Keluar masuk pegawai
    :PROPERTIES:
    :CUSTOM_ID: keluar-masuk-pegawai
    :END:

- Polisi bisa? (tapi seharusnya tidak bisa?) https://nasional.kompas.com/read/2018/01/15/16055551/polisi-yang-sudah-masuk-ke-politik-seharusnya-tak-bisa-balik-lagi-ke-polri
- TNI tidak bisa https://news.detik.com/berita/d-3305012/setelah-mundur-agus-tak-bisa-kembali-ke-tni-kodam-jaya-itu-pilihannya

  - PNS TNI tidak bisa

- PNS lain bisa http://www.hukumonline.com/klinik/detail/lt59ae5a5d781fd/bolehkah-melamar-menjadi-pns-lagi-jika-pernah-berhenti-dengan-hormat-atas-permintaan-sendiri
* Agama

Agama adalah urusan pribadi, bukan urusan negara.

(Ini masih sesuai UUD?)

** <2018-09-19> Akui semua agama, aliran, dan kepercayaan.
Ada sedikitnya 4000 agama/aliran/kepercayaan.

Syiah, Ahmadiyah, Tarekat Naqsabandiyah.

Agama Mesir kuno.
Paganisme.
Animisme.
Dinamisme.

Discordia, Church of the SubGenius, Flying Spaghetti Monster.

*** Aceh

- https://tirto.id/menilik-harta-kekayaan-cagub-cawagub-dki-bPPV
- https://tirto.id/benarkah-syariat-islam-menghambat-investasi-di-aceh-cP3C
- https://tirto.id/dana-otsus-dicabut-aceh-siap-bangkrut-cP54

*** Sejarah agama
- Agama, yang sekarang besar, awalnya dianggap sesat oleh orang-orang di sekitarnya.
- Pengikut Yesus awalnya dianggap sesat oleh pengikut Yahudi pada zamannya.
- Pengikut Muhammad awalnya dianggap sesat oleh pengikut polytheism Arab pada zamannya.
- Bayangkan seandainya seorang di kampung Anda tiba-tiba mengumumkan suatu agama baru.
- Mengapa kita lebih percaya orang 2000 tahun lalu daripada orang sekarang?
  Mengapa kita berpaku pada masa lalu?
  Mengapa kita tidak berusaha membuat masa depan jadi lebih indah?

** <2018-09-19> Alihkan tugas departemen agama (umrah, naik haji dll.) kepada private sector.

** <2018-09-19> Serahkan pendidikan agama sepenuhnya kepada keluarga.
- Mengganti pelajaran agama di sekolah dengan pelajaran /sejarah/ agama.

** <2018-09-19> Kurangi/tiadakan ekstremisme/radikalisme

*** <2018-09-22> Wajibkan pelajaran sejarah agama

History of Islam?
Is Brigitte Gabriel's [[https://www.youtube.com/watch?v=o0m9nEafBE4][history-of-Islam video]] accurate?

*** Setiap ayat sensitif dalam kitab suci harus disertai tafsir/exegesis/interpretasi dan komentar tentang konteks sejarah turunnya ayat tersebut.
- Terutama Quran karena mayoritas penduduk Indonesia Muslim.
- Kitab suci bisa berupa buku kertas, aplikasi komputer, dll.
- Bagaimana cara mencegah [[https://en.wikipedia.org/wiki/Auto-segregation][WP:Auto-segregation]]?
  Asimilasi vs akulturasi vs absorpsi vs integrasi?
- Apakah efektif?
  Quran terjemahan ekstremis akan tetap saja beredar underground.
  Tapi kebijakan ini mungkin mempengaruhi Muslim moderat yang selama ini complicit atau bahkan diam-diam setuju dengan ekstremis.
- Kita sebaiknya tidak memaksakan/mengatur kepercayaan dengan undang-undang.
- Bagaimana seandainya ada orang mengarang kitab suci sendiri?


** Kerusuhan SARA
   :PROPERTIES:
   :CUSTOM_ID: kerusuhan-sara
   :END:

- Tanjung Balai Sumatra Utara sering rusuh?

  - 2018, [[https://regional.kompas.com/read/2018/08/23/18025471/5-fakta-kasus-meiliana-menangis-di-sidang-hingga-fatwa-mui][5 Fakta Kasus Meiliana, Menangis di Sidang hingga Fatwa MUI - Kompas.com]]

    - [[https://www.facebook.com/ransibar/posts/10216709033187633][Keterangan Ranto Sibarani, anggota tim penasihat hukum tergugat]]
    - Coba tanya MUI Sumatra Utara:

      - Mengapa Jusuf Kalla boleh minta suara azan dikecilkan, tetapi Meiliana tidak boleh?

        - 2018, [[https://news.detik.com/berita/4179062/jk-nilai-kasus-meiliana-bukan-soal-toleransi][JK Nilai Kasus Meiliana Bukan Soal Toleransi]]
        - Karena JK wapres?

          - Seandainya wapresnya Meiliana, apa dia boleh minta suara azan dikecilkan?

            - Seandainya wapresnya Ahok?

      - Mengapa standar ganda?

        - Yang ini hanya kena teguran, tidak dipenjara: [[https://www.liputan6.com/regional/read/3614381/sebut-nabi-muhammad-sesat-ustaz-evie-effendie-kena-teguran-keras][Sebut 'Nabi Muhammad Sesat', Ustaz Evie Effendie Kena Teguran Keras - Regional Liputan6.com]]
        - 2018, [[https://news.detik.com/berita/4178495/pengeluh-volume-azan-dibui-18-bulan-bagaimana-perusak-vihara][Pengeluh Volume Azan Dibui 18 Bulan, Bagaimana Perusak Vihara?]]
          Hanya 1-2 bulan.

      - Mengapa PBNU tidak sepakat dengan MUI?

        - [[https://nasional.tempo.co/read/1119693/pbnu-icjr-dan-setara-kritik-vonis-kasus-penistaan-agama-meiliana][PBNU, ICJR dan Setara Kritik Vonis Kasus Penistaan Agama Meiliana - nasional Tempo.co]]
        - [[https://nasional.tempo.co/read/1119345/pbnu-katakan-suara-adzan-terlalu-keras-bukan-penistaan-agama/full&view=ok][PBNU: Katakan Suara Adzan Terlalu Keras Bukan Penistaan Agama - nasional Tempo.co]]
        - Jadi yang benar siapa?

  - 2018, [[http://medan.tribunnews.com/2018/05/15/ini-kronologis-penangkapan-terduga-teroris-di-tanjungbalai-satu-orang-tewas-di-tempat][Ini Kronologi Penangkapan Terduga Teroris di Tanjungbalai, Satu Orang Tewas di Tempat - Tribun Medan]]
  - 2018, [[https://www.viva.co.id/berita/nasional/1057980-dua-tahun-usai-kerusuhan-sara-toleransi-di-tanjung-balai-kian-kuat][Dua Tahun Usai Kerusuhan SARA, Toleransi di Tanjung Balai Kian Kuat -- VIVA]]

    - Baru dipuji sudah rusuh lagi.

  - 2016, [[https://tirto.id/tujuh-warga-jadi-tersangka-kerusuhan-tanjungbalai-bwtp][Tujuh Warga Jadi Tersangka Kerusuhan Tanjungbalai - Tirto.ID]]
  - 2016, [[http://jarumdetik.blogspot.com/2016/07/fakta-sebenarnya-di-balik-rusuh-tanjung.html][Fakta Sebenarnya di Balik Rusuh Tanjung Balai | Jarum Detik]]

    - Masyarakat setempat sudah dua kali terhasut berita bohong: 2016 dan 2018.

      - [[https://www.motivasi-islami.com/jangan-seperti-keledai-atau-lebih-parah/][Jangan Seperti Keledai Atau Lebih Parah - Motivasi Islami]]: Keledai saja tak jatuh dua kali ke lubang yang sama.

  - A person's beliefs filter all incoming information.
    Therefore people believe hoax that supports their beliefs, and reject facts that counter their beliefs.

    - Riots uncover true beliefs.
    - Kerusuhan adalah bukti bahwa toleransi hanya di permukaan.

  - UU 1/1965 tentang penodaan agama

    - [[https://tirto.id/asal-usul-delik-penistaan-agama-b49e][Asal-Usul Delik Penistaan Agama - Tirto.ID]]



* Teknologi

** <2018-09-19> Net neutrality, un-ban websites, Reddit, Vimeo, dll.
Apakah website ekstremis juga mau dibolehkan?

** <2018-09-19> Kuasai infrastruktur Internet

Infrastruktur Internet adalah hajat hidup orang banyak, jadi harusnya dikuasai negara, sesuai pasal 33 ayat 3 UUD 1945.

** <2018-09-21> Benahi keculasan Telkomsel

- Beli paket data di Indonesia Barat; terbang ke Indonesia Tengah; paket data tidak berlaku.
- Simplify pricing.
  Harga paket data harus rata per GB, dan harus sama di semua Indonesia.
  Tidak boleh memahalkan pengguna kecil.
  - Daerah maju mensubsidi daerah tertinggal.
- Cabut iklan sisipan proxy Telkomsel.

** Why is Reddit blocked in Indonesia?
   :PROPERTIES:
   :CUSTOM_ID: why-is-reddit-blocked-in-indonesia
   :END:

- The official reason

  - Something like "Reddit is a porn site.".
  - http://www.mesinwaktu.id/2017/11/alasan-kenapa-reddit-diblokir.html
  - https://www.quora.com/Why-is-Reddit-blocked-by-the-Indonesian-government
  - Doesn't make sense.

    - There is porn on Reddit, but Reddit is not a porn site.
      There are also porn on Google, Bing, YouTube, Blogspot, but they aren't porn sites.
      Why block only Reddit?
      If you're following the law to the letter,
      why not block all of Internet?

- What I think the reason is

  - Someone in the government might need to be seen working.

* Transportasi, lingkungan, pertanahan, tata kota

- Utamakan pejalan kaki dalam tata kota.

** Self-driving buses for public transport can drive transport costs down?

- Which are the biggest transport cost component? Is it fuel or the driver?

** Solusi kemacetan tol Jakarta?

- Solusi:
  - Pemda DKI, Bogor, Depok, Tangerang, dan Bekasi:
    - Pilihan 1: Membeli jalan tol menjadi jalan umum.
      - Lunasi atau cicil ke pemilik tol.
    - Pilihan 2: Menyewa jalan tol pada jam tertentu menjadi jalan umum.
      - Menaikkan pajak jalan untuk mobil.
        - [[https://en.wikipedia.org/wiki/Road_tax][WP:Road tax]]
        - Ditambah (rata-rata biaya tol) * (jumlah hari dalam setahun)
          - Ditambah Rp 7,200,000 per tahun?
      - Membuka semua pintu tol di Jakarta pada jam sibuk.
        - Kalau tidak bisa buka semua, buka yang paling bikin macet.
      - Membayar ganti rugi ke operator tol.
- Menyelesaikan dua masalah sekaligus:
  - Disinsentif untuk pengguna mobil pribadi.
  - Mengurangi kemacetan karena kelambatan gerbang tol.
- Skenario gagal:
  - Pemda tidak punya cukup uang.
  - Manusia egois.
    - Pemda sekitar DKI tidak mau patungan.
    - Pemilik mobil menolak bayar pajak demi kebaikan bersama.
    - Pemilik tol menolak penawaran karena terlalu serakah.



** TODO <2018-09-17> Gratiskan kendaraan umum bertrayek

- Lebih mudah dan murah daripada integrasi antarmoda?
- Mengurangi trafik dan polusi.

*** <2018-09-19> Biaya yang diperlukan per jam-kendaraan (unit economics)

- Satuan unit economics: 1 jam-kendaraan
- Breakdown
  - Upah
    - 1 kendaraan butuh 2 orang operator (1 supir dan 1 kenek)
    - Upah 1 orang Rp 7 juta/160 jam ~ Rp 50000/jam
  - Bahan bakar
    - Penggunaan bahan bakar (fuel mileage), 5 km/liter, Rp 10000/liter
    - Kecepatan rata-rata 50 km/jam
    - Kendaraan beroperasi 24 jam per hari = 1200 km/hari = 240 liter/hari
  - Biaya perawatan kendaraan Rp ?/bulan
  - Asuransi kesehatan Rp ?/bulan
  - Asuransi kendaraan Rp ?/bulan

*** Potensi masalah dan penolakan

**** Pengemudi ojek, taksi, dan mobil sewa mungkin menolak karena pendapatan mereka mungkin berkurang

- Bantu mereka beralih jadi supir kendaraan umum bertrayek.

*** Negara lain yang sudah berhasil

- [[https://www.youtube.com/watch?v=ccxVYborUcU][Let's Make Mass Transit Free* - YouTube]]
  - Making mass transit free benefits everyone, including those who don't use mass transit.
    Free mass transit reduces traffic.

** <2018-09-22> Jakarta is sinking, unless we stop draining the aquifer below it.

The animation at 1:55 in this [[https://www.youtube.com/watch?v=dNE5aptbGyY][video]] explains why.

- People pump the aquifers out.
- Rain can't replenish the aquifers because Jakarta is wrapped in concrete.
- There is no more underground water to press the land up.
- The land sinks.

North Jakarta is sinking by up to 20 cm per year.

** <2018-09-21> Perbaiki jembatan penyeberangan

<2018-09-21>
Jembatan penyeberangan di Jl. S. Parman Jakarta logamnya mencuat dan ukuran anak tangganya terlalu kecil.

** Pentingnya infrastruktur
    :PROPERTIES:
    :CUSTOM_ID: pentingnya-infrastruktur
    :END:

[[https://www.bloomberg.com/quicktake/indonesias-nationalism][Bloomberg]]:
"A lack of roads and ports means it's cheaper to ship goods to China than across the archipelago."

Kok lebih murah ngirim barang ke Cina daripada ke Papua?
Padahal, menurut peta, jarak Jakarta-Hongkong mirip jarak Jakarta-Jayapura.

- [[https://www.youtube.com/watch?v=MFrLcRhMKnE][Geopolitics of Southeast Asia Part 2: Malay Archipelago - YouTube]]

  - Indonesia is too big to defend itself.

* Politik

Fix the system; berantas perverse incentive, principal-agent problem, dan conflict of interest.

** Mengapa Indonesia tertinggal?

https://nasional.kontan.co.id/news/dua-alasan-indonesia-tertinggal-dari-negara-lain

Rizal Ramli:

- "Paradigmanya, tebang hutan, lalu ekspor. Sedot tanah di Papua lalu ekspor. Tidak dibangun industri hilir sehingga nilai tambahnya sedikit."
- "Saya minta tolong, perlu perubahan paradigma pengelolaan SDM dari sekadar sedot ekspor, kita kembangkan nilai tambahnya"

Kesimpulannya kita tertinggal karena selalu mencari jalan pintas / menang mudah yang kecil dan tidak matter.

** Mudahkan pemilu untuk perantau

Pemilu serentak?
Sistem e-ktp nasional?

Pemilu harus ada bukti fisik seperti kertas, tidak boleh sepenuhnya bergantung ke komputer.

** <2018-09-19> Evidence-based legislation? data-driven legislation?

** <2018-09-19> Tertibkan kampanye politik

- membatasi kampanye hanya dalam bentuk prospektus (tertulis) berisi rencana program kerja, seperti yang sedang Anda lihat
- mengumpulkan prospektus dalam satu website
- melarang semua bentuk lain

** <2018-09-19> Larang /lobbying/

Bukannya memang sudah dilarang?

** <2018-09-17> Larang partai membayar anggota; wajibkan anggota membayar partai?

- Berantas politik karir.
- Pastikan bahwa yang masuk adalah orang yang benar-benar peduli politik.
- Tapi kalau begini, politik jadi sampingan.
  Tidak semua orang mau punya 2 pekerjaan.

A party is a mini-country.
Therefore a party should tax its members, not pay its members.

Politics should not be a career path.

** Pesimis soal partai baru
   :PROPERTIES:
   :CUSTOM_ID: pesimis-soal-partai-baru
   :END:

2014 ada partai baru: [[https://psi.id/][Partai Solidaritas Indonesia]].
Terus?
Semua partai juga pernah baru.
Semua partai juga didirikan dengan cita-cita mulia.

- Pada tahun 1927 PNI juga partai baru.
- Pada tahun 1964 Golkar juga partai baru.
- Pada tahun 1973 PDI juga partai baru.
- Pada tahun 2001 Partai Demokrat juga partai baru.
- Pada tahun 2002 PKS juga partai baru.
- Pada tahun 2008 Gerindra juga partai baru.
- Semua partai baru itu akhirnya terlibat masalah.

Bagaimana kita menjamin partai baru tidak terjerembab ke lubang korupsi?

Ada siklus:

- Partai baru didirikan karena ketidakpuasan terhadap partai lama.
- Setelah lama, partai baru jadi partai lama, dan terlibat masalah.
- Ulangi.

Kalau semua partai terlibat masalah,
sistem pemerintahan perlu diperbaiki?
Pemisahan perlu diperbaiki?
Insentif perlu dirancang lebih baik?

Perumpamaan anak sekolah:

- Kalau satu anak tidak naik kelas, mungkin anaknya yang salah.
- Kalau satu kelas banyak yang gagal, mungkin kelasnya yang salah.
- Kalau banyak kelas gagal, mungkin sekolahnya yang salah.
- Kalau banyak sekolah gagal, mungkin sistem pendidikannya yang salah.

Perumpamaan partai:

- Kalau satu orang korup, mungkin orangnya yang salah.
- Kalau satu partai korup, mungkin partainya yang salah.
- Kalau banyak partai korup, mungkin hukum negara ini yang salah.

Sistem kita mengubah orang muda idealis menjadi orang tua korup?
Orang baik dalam sistem buruk akan jadi orang buruk.

- https://theconversation.com/buasnya-sistem-politik-indonesia-halangi-upaya-reformasi-dari-dalam-oleh-mantan-aktivis-94523
- [[https://www.quora.com/What-do-Indonesians-know-think-about-the-new-party-PSI-Partai-Solidaritas-Indonesia-And-how-big-is-the-chance-that-the-PSI-will-get-a-place-in-the-parliament][What do Indonesians know/think about the new party PSI (Partai Solidaritas Indonesia)? And how big is the chance that the PSI will get a place in the parliament? - Quora]]

** Ucapan terima kasih
   :PROPERTIES:
   :CUSTOM_ID: ucapan-terima-kasih
   :END:

*** Terima kasih Gus Dur
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-gus-dur
    :END:

Imlek jadi libur.

Diskriminasi berkurang.

WNI keturunan Cina bisa masuk universitas negeri.

*** Terima kasih Ahok
    :PROPERTIES:
    :CUSTOM_ID: terima-kasih-ahok
    :END:

- Rumah saya baru bebas banjir pada zaman BTP (Basuki Tjahaja Purnama a.k.a. Ahok).

  - Tahun 1990-an setiap 5-6 tahun sekali, rumah banjir.
  - Makin lama makin parah. Tiap tahun banjir.
  - Bahkan, pernah suatu ketika, tidak hujan malah banjir.
  - Jalanan dinaikkan 50 cm. Rumah dinaikkan 100 cm. Tetap banjir.
  - Saat BTP menjabat, rumah saya tidak banjir.

Namun, hal yang saya tidak setuju:

- Omongan kurang dijaga, mungkin terbawa emosi.
  Akhirnya kata-katanya dipakai untuk menyerang dia.
- Utilitarianisme.
  [[https://en.wikipedia.org/wiki/Trolley_problem][WP:Trolley problem]] menyiratkan bahwa utilitarianisme tidak cocok jadi prinsip moral.
  Saya hargai kemampuan problem-solving dan kecepatan kerja Ahok, tapi soal prinsip moral ini saya tidak setuju.

  - [[https://news.detik.com/berita/2998358/ham-versi-ahok-untuk-melindungi-rakyat-banyak][HAM Versi Ahok untuk Melindungi Rakyat Banyak]]

** Peduli rakyat kecil
   :PROPERTIES:
   :CUSTOM_ID: peduli-rakyat-kecil
   :END:

- Student activism

  - [[https://twitter.com/semarui?lang=en][SEMAR UI]]
  - [[https://twitter.com/rakapare?lang=en][Komune Rakapare]]

** 1998
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

- [[https://www.reddit.com/r/indonesia/comments/61ed2m/what_was_indonesia_like_before_reformasi_and/][What was Indonesia like before Reformasi and after1998? (Long) : indonesia]]
- [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/][Telegram from US Embassy Jakarta to State Department, "Who Is Behind [1998] Disappearances?," : indonesia]]

  - [[https://www.reddit.com/r/indonesia/comments/97iz5m/telegram_from_us_embassy_jakarta_to_state/e4a0s02/][Pendapat redditor fourrier01]]: "Every year, just before election, there's always a news to reveal Prabowo stench over and over. 4 years ago there was Allan Nairn. [...] This one isn't so surprising anymore."

** Pemilihan Presiden 2019
   :PROPERTIES:
   :CUSTOM_ID: pemilihan-presiden-2019
   :END:

- https://www.reddit.com/r/indonesia/comments/9640by/rekam_jejak_sikap_dan_perkataan_maruf_amin/

  - https://www.reddit.com/r/indonesia/comments/9631cu/maruf_amin_dulu_saya_yang_menggerakkan_aksi_212/

- [Pendapat seorang redditor dengan username kurang elok](https://www.reddit.com/r/indonesia/comments/97bncz/mahfud_sebut_maruf_amin_suruh_nu_ancam_jokowi/e472v4s/] tentang Maruf Amin, calon wakil presiden 2019. Pendapat ini terdengar gila, tapi mungkin. Entah.

  - "Sesuai UU kita, ketika presiden gak ada (karena meninggal atau lengser) wapres langsung auto-presiden. Disini ada insentif besar utk kaum mereka bunuh atau lengserkan presiden."

- Belum dibaca

  - [[https://www.reddit.com/r/indonesia/comments/983if1/pros_of_jokowi/][Pros of Jokowi : indonesia]]
  - [[https://www.reddit.com/r/indonesia/comments/982c5x/why_fear_over_islamists_in_prabowos_future/][Why Fear Over Islamists in Prabowo's Future Government is Unfounded : indonesia]]

** Pendapat-pendapat yang edgy tapi mungkin ada benarnya
   :PROPERTIES:
   :CUSTOM_ID: pendapat-pendapat-yang-edgy-tapi-mungkin-ada-benarnya
   :END:

*** Jalan tol adalah tindak kejahatan.
    :PROPERTIES:
    :CUSTOM_ID: jalan-tol-adalah-tindak-kejahatan.
    :END:

- Jalan tol adalah jalan pribadi (jalan milik perusahaan, bukan jalan umum).
- Jalan S. Parman, Jalan Gatot Subroto, dan Jalan M.T. Haryono adalah jalan umum.
- Dahulukan kepentingan umum sebelum kepentingan pribadi, menurut pendidikan kewarganegaraan yang diajarkan di SD.
- Antrian tol memacetkan jalan umum.
- Sebagian kemacetan di jalan umum tersebut terjadi
  karena pemerintah membiarkan pengelola jalan tol mendahulukan kepentingan pribadi.

  - Jika antrian terlalu panjang, polisi seharusnya berhak mempercepat antrian dengan cara:

    - memaksa mengalihkan mobil dari antrian ke jalan biasa
    - memaksa membuka gerbang tol

- Tugas pemerintah hanya dua:

  - Melakukan hal yang menguntungkan banyak orang.
  - Mencegah hal yang merugikan banyak orang.

- Seandainya Pemda DKI Jakarta hendak membeli sebagian ruas jalan tol untuk dijadikan jalan umum,
  berapa biaya per kilometernya?

** Pertanyaan-pertanyaan yang belum terjawab
   :PROPERTIES:
   :CUSTOM_ID: pertanyaan-pertanyaan-yang-belum-terjawab
   :END:

- How to combat people who provoke you and then cry foul?
- Undigested

  - Why do Habib Rizieq supporters support him?
  - 2017-06-23 government announces that they will take Rp344 trillion loan. Source?
  - If Sukarno hadn't fallen, would he have been like Gajah Mada, Washington, Castro, Kim, Mao, Stalin, Khan, or someone else?
  - Bagaimana cara impor?
  - Bagaimana cara ekspor?

- Indonesia needs a website like politifact or factcheck.org.
- Is the 21st century is the age of demagogues, or has it always been the case?
  When did candidates begin appealing to emotion using racism and religion?
  Donald Trump?
  Anies Baswedan?

*** Ada Mata Najwa, mengapa tidak ada Tangan Najwa?
    :PROPERTIES:
    :CUSTOM_ID: ada-mata-najwa-mengapa-tidak-ada-tangan-najwa
    :END:

- Apa ada hal seperti acara televisi Mata Najwa tetapi berupa tulisan?
  Tangan Najwa gitu?

*** Mengapa kita tidak minta tolong cenayang panggil arwah Bung Karno dan tanyakan kebenaran G30S PKI dan Supersemar?
    :PROPERTIES:
    :CUSTOM_ID: mengapa-kita-tidak-minta-tolong-cenayang-panggil-arwah-bung-karno-dan-tanyakan-kebenaran-g30s-pki-dan-supersemar
    :END:

Mengapa kita tidak tanya istrinya, anaknya, kerabatnya, teman-temannya?

*** Program 1000 startup ke mana?
    :PROPERTIES:
    :CUSTOM_ID: program-1000-startup-ke-mana
    :END:

- [[https://www.reddit.com/r/indonesia/comments/98afrg/anyone_know_what_happened_to_1000_startup_i_found/][Anyone know what happened to 1000 Startup? I found these three comments in a video about them. : indonesia]]

* Kesehatan

** Permurah kesehatan?

Mengapa kesehatan mahal?

Mengapa rumah sakit mahal?

** <2018-09-19> Ban buffets/all-you-can-eat restaurants

- Unhealthy. Induces overeating.
- Dishonest pricing.
  - [[https://www.insideedition.com/athlete-banned-all-you-can-eat-sushi-buffet-eating-too-much-46845][Athlete Banned From All-You-Can-Eat Sushi Buffet for Eating Too Much | Inside Edition]]
    - Why do you ban people?
      You know what you sign up for.
      You know everyone's diet is different.
      The eater does nothing wrong.
      If you don't like people eating too much, open a conventional a la carte restaurant.
      Buffets are food casinos.
      Buffets are insurance.
      They are all actuarial.
      It's unfair if you only want the money but don't want the risk.

** <2018-09-19> Bantu petani tembakau dan buruh tembakau cari pekerjaan lain

** <2018-09-22> Legalkan aborsi
Forcing someone to live the life he does not want is more immoral than killing him.
This also implies:

- We should let people kill themselves if they have thought about it well, as long as they are done privately.
  - But https://www.speakingofsuicide.com/2013/05/19/why-stop-someone-from-suicide/ dissents:
    - "The most important reason to prevent suicide is that suicidal crises, though formidable and painful, almost always are temporary.
      Even if the person continues thinking about suicide, the intense suicidal intent usually subsides.
      Consider that 90% of people who survive a suicide attempt do not go on to die by suicide.
      That number is very revealing.
      Even among people who wanted to die so strongly that they tried to end their life, most ultimately chose to live."
      - People don't know what they want.
        We don't know what we want.
- We should not prolong the suffering of dying people by forcing life support.

No baby consents to being killed.
No baby consents to being born either.
* Ekonomi

** Prinsip ekonomi

- Mandirikan bangsa.
  Maksimalkan produksi dalam negeri.
  Kemandirian adalah syarat perlu tetapi tidak cukup untuk kedaulatan.

** Kurangi nilai impor.

- Tingkatkan produksi dalam negeri, terutama industri strategis, teknologi.
- Bangun daerah tertinggal, kurangi urbanisasi.

** Bantuan langsung tunai (BLT) = cash transfers
   :PROPERTIES:
   :CUSTOM_ID: bantuan-langsung-tunai-blt-cash-transfers
   :END:

- [[https://www.livemint.com/Politics/144kmvZXyDiM40UxY66DYJ/Targeted-cash-transfer-schemes-can-do-more-harm-than-good.html][Targeted cash transfer schemes can do more harm than good - Livemint]]
- Giving money to poor people immediately increases their purchasing power, but there are consequences.
- They buy things, increasing demand.
- If there is not enough supply, then prices rise.
- Conclusion:

  - In the short term, cash transfers provides immediate relief to poor people.
  - In the long term, cash transfers hurts the poor people it intends to help.
  - To help the poor, the government should increase the supply of goods to the poor.

    - Ideal permanent strategic solution: increase aggregate efficiency to drive down costs.

      - Localize production.
        Avoid transportation.
        Transportation is waste.
      - Depend on renewable energy.
        The sun is free!
        Wind is free!
        The TCO (total cost of ownership) of solar is approaching that of coal/oil?
      - Good infrastructure to reduce transport time/cost.
      - Integrate transport modes to reduce transport costs?

    - Quick temporary tactical solution: subsidies.

- Basic income is unconditional cash transfers.
* Survei tanah, konflik agraria, sertifikasi tanah?

* Pendidikan

** Tingkatkan gaji dan mutu guru?

** <2018-09-22> Perbaiki cara mengajar sejarah

- Tidak perlu menghapal hal-hal yang dicari dalam 1 menit di Internet.
- Yang penting ialah memahami sebab/konteks sesuatu terjadi, terutama perang.

** 100% literacy rate; budayakan membaca dan menulis

Jordan Peterson: "The best way to teach people critical thinking is to teach them to write." ([[https://www.youtube.com/watch?v=x0vUsxhMczI][source]])

** Bahasa Inggris (dan Mandarin?)

** Memberantas kebodohan
   :PROPERTIES:
   :CUSTOM_ID: memberantas-kebodohan
   :END:

*** Benci suku tertentu itu merugikan diri sendiri

WNI keturunan Cina itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Cina?
Pemerintah Cina saja tidak peduli.

WNI keturunan Arab itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah Arab?
Pemerintah Arab saja tidak peduli.

WNI keturunan India itu WNI.
Bayar pajak ke pemerintah Indonesia.
Berobat pakai BPJS Indonesia.
Untuk apa mereka pro pemerintah India?
Pemerintah India saja tidak peduli.

Dan seterusnya.

* Pertanian

* Obtain political power?

** TODO <2018-09-17> Join a think tank or a political party or both?

** TODO <2018-09-17> Educate the people about critical thinking, religion, history, power, and politics?

** TODO <2018-09-22> Own a media company, or piggyback existing media?

* Shocking news. Are these real?
   :PROPERTIES:
   :CUSTOM_ID: shocking-news.-are-these-real
   :END:

- [[https://www.liputan6.com/regional/read/3618529/bocah-bocah-terciduk-saat-asyik-dugem-di-diskotek-berkedok-toko-es-krim][Bocah-Bocah Terciduk Saat Asyik Dugem di Diskotek Berkedok Toko Es Krim - Regional Liputan6.com]]

  - from [[https://www.reddit.com/r/indonesia/comments/97s1o2/bocahbocah_terciduk_saat_asyik_dugem_di_diskotek/][reddit]]

- [[https://regional.kompas.com/read/2017/05/10/15213361/tommy.soeharto.dianugerahi.gelar.gus.oleh.ulama.di.jatim][Tommy Soeharto Dianugerahi Gelar "Gus" oleh Ulama di Jatim - Kompas.com]]

  - [[https://nasional.tempo.co/read/10122/kronologi-kasus-tommy-soeharto][Kronologi Kasus Tommy Soeharto - Nasional Tempo.co]]
  - [[https://tirto.id/pembunuhan-hakim-syafiuddin-yang-dirancang-tommy-soeharto-cPVT][Pembunuhan Hakim Syafiuddin yang Dirancang Tommy Soeharto - Tirto.ID]]
  - [[https://seword.com/politik/sadisnya-pembunuhan-hakim-kartasasmita-oleh-tommy-soeharto-ryLUQSUYG][Sadisnya Pembunuhan Hakim Kartasasmita oleh Tommy Soeharto - Seword]]

* Bayar pajak
   :PROPERTIES:
   :CUSTOM_ID: bayar-pajak
   :END:

- https://djponline.pajak.go.id/account/login

  - http://www.pajak.go.id/article/jangan-panik-jika-lupa-kode-efin-ikuti-langkah-berikut
* Ethics
** Abortion debates are futile communication failures
<2018-09-15>

TLDR: Before you debate abortion, make sure everyone has the same definition of the words you're going to use.
*** The problem with abortion debates
Abortion debate is all emotion and no thinking.
Nothing will ever come out of it.
There is no real discussion.
The participants don't even agree on the meaning of the words they use (human, fetus, life, species, murder).
It is communication failure.
It is religious debate.

Everyone gives different meanings to the same word.
Everyone assumes everyone else has the same definitions.
There is only an illusion of communication.
There is no real progress.

New York Times has some [[https://opinionator.blogs.nytimes.com/2011/11/30/on-abortion-and-defining-a-person/][opinion]] about language in abortion debates.
*** Abortion debate is battle between thinkers and feelers
After seeing [[https://abortion.procon.org/][Abortion ProCon.org]], I realize that the debate is just a battle between thinkers and feelers.
Generally, thinkers are pro-abortion and feelers are anti-abortion.

After browsing around, I realize that gun control, euthanasia, death penalty, and other moral issues are just a giant battle between thinkers and feelers.
*** Ubiquitous problem: not defining what a human is
What is a human?
We think we know what a human is, but when we want to say it, we find out we can't.
Why?
Is our language limited?
Is "human" an ill-defined concept?

We don't know what a human is, we don't know what life is, but we dare to debate the sanctity of the life of a human?

People who debate abortion but can't define human are wasting time.
They don't know what they're talking about.
*** Ubiquitous fallacy: binarizing the continuum
Concepts such as hot, tall, big are not binary.
They are continuums.

Life is not binary.
It is a continuum.
We are more alive when we wake up.
We are less alive when we sleep.
We are even less alive when we die.

Being human is a continuum.

Truth is a continuum.
We reason probabilistically.
*** Why do we care what others do?
We care about what others do only as far as how they may harm us.

We don't care when someone harms himself.

We care when someone harms others, but only if he may harm us.

We care when someone kills people because we fear he may kill us next, not because we care about the people he killed.

We care when someone kills his children because we fear he may kill our children next, not because we care about the children he killed.

Why do we care when a pregnant woman aborts her fetus?

We care when a woman aborts her fetus because we want to impose our morality on others, not because we care about the fetus.
If we cared about the fetus, we would help the mother raise the fetus, help her give birth, and then adopt the baby.
*** Nature-defying El Salvador abortion law
[[https://www.bbc.co.uk/news/magazine-24532694][El Salvador abortion law ignores nature]].
It imprisons people unnecessarily.
*** Catching fallacies in action
**** Dennis Prager
Dennis Prager has a [[https://www.youtube.com/watch?v=AMwkQVpy98A][video about abortion]].

What he gets right:

- Right: "When challenged with this argument, people usually change the subject to the rights of the mother."
  - The right response is to ask the claimant to define the words human, species, life, fetus, etc.
    There is no need to digress to mother rights in order to point out the problems with the argument.

What he gets wrong:

- Mixing unrelated concepts in a loaded question: "Does the human fetus have any value and any rights?"
  - "Value" is a moral concept.
    "Rights" is a legal concept.
    The two don't always coincide.
    Also, he hadn't defined what a "human" is.
- Misuse of language: "A living being doesn't have to be a person in order to have intrinsic moral value and rights."
  - The term "intrinsic rights" is an oxymoron.
    Your rights are the things laws give you.
    They don't come with you.
- Wrong: "Either a human fetus has worth or it doesn't."
  - This is the fallacy of binarizing the continuum.
- Loaded question:
  "Why does one person, a mother, get to determine whether that being has any right to live?"
  - The question should have been: "Why does /anyone/ at all get to determine whether any being has any right to live?"
    - That question suggests antinatalism.
      Why do we force babies to come into being?
** Moral particularism
https://philosophynow.org/issues/60/Why_You_Shouldnt_Be_A_Person_Of_Principle

Is there a universal moral principle that coincides with the majority intuition about these issues?

- It is moral to kill fewer people to save more people?
- Is it moral to kill a serial killer to prevent 100 murders?
- Is it moral to kill a healthy innocent person and distribute his organs to save 5 people in need?
- Is it moral to annex a mismanaged country and improve it?
** Does intention matter?
How do we know others' intentions?
** Improbability of equality of outcome in doomsday spaceship scenario
Consider this "doomsday spaceship" scenario:
- A huge asteroid will hit the Earth 1 week from now. That will kill all 7 billion people.
- But we have one spaceship that can save 1000 people. That is the only way out of Earth.
Which people should we save?
Why?
There is no satisfactory answer to this; we should just use a truly random lottery.
But if we pick people randomly, the ship will be full of poor people, because the majority of the Earth is poor.
Should pregnant women be prioritized before non-pregnant women?
Should older women be prioritized before younger women?
Should women be prioritized before men?
Should children be prioritized before women?
Nobody should be prioritized.
If we don't pick people randomly, then we don't practice what we preach about equality.

With a lottery, all 7 billion people have a chance to board the spaceship,
but it is physically impossible for all 7 billion people to actually board the spaceship.
No amount of political correctness will change the laws of nature.

Of course, when the spaceship is big enough for 7 billion people, we can have equality of outcome.
The question is how we make a spaceship that big.
** Leaving Greenpeace
- [[https://www.youtube.com/watch?v=BpBnJq19R60][video]] of Patrick Moore's reasons for leaving Greenpeace

* Think tanks

https://onthinktanks.org/articles/what-can-indonesian-research-institutes-learn-from-chinese-think-tanks/

http://www.ksi-indonesia.org/in/home

http://www.thejakartapost.com/news/2017/02/03/indonesian-groups-among-worlds-influential-think-tanks-report.html

https://id.wikipedia.org/wiki/Wadah_pemikir
