#+TITLE: Topics in politics
#+DATE: 2019-11-28 00:00:00 +0700
* Power uncovers, not corrupts
<2019-11-27>

"In sum, the study found, power doesn’t corrupt; it heightens pre-existing ethical tendencies."
https://www.smithsonianmag.com/science-nature/why-power-corrupts-37165345/
* Using child psychology to make politicians behave
<2019-11-28>

Some people have been suggesting that we operant-condition the politicians.
I think that's a brilliant idea.
The premise is: somehow politics make people childish,
so we apply child psychology to make politicians behave.
We praise them whenever they say the truth, and we ignore them whenever they lie.

Perhaps politicians are even simpler than children;
perhaps they are like animals, like dogs, which is why operant conditioning works on them.

If politicans are childish, then the people have to be the parents; otherwise the country is all whim.

https://www.politico.com/magazine/story/2019/10/22/how-to-trick-trump-into-telling-the-truth-229874

https://medium.com/@JessicaLexicus/operant-conditioning-for-presidents-4fc8cd5d6c74
* On ethical consumption
<2019-11-17>
** <2019-11-27> Dissenting opinions
Wicker 2017[fn::<2019-11-27> https://qz.com/920561/conscious-consumerism-is-a-lie-heres-a-better-way-to-help-save-the-world/]
argues that ethical consumerism is not enough to save the world.

If everyone know what truly matters for them, we won't have an environmental crisis.

Not only do you need to pick what you consume, you need to consume less.

Either we change the system, or we use mindfulness to immunize the people against the broken system.

Ethical consumption is not enough; we need everyone to live mindfully; we need a global spiritual revolution.
** The immorality of companies reflects the immorality of consumers
Consumers are the masters of companies, because companies need money from consumers to live.
Consumers are even more powerful than shareholders, because shareholders get their money from consumers too.

For example, Amazon's mission is "to be Earth's most customer-centric company"[fn::<2019-11-18> https://www.amazon.jobs/en/working/working-amazon].
If consumers want cheap things fast, then so be it, workers be damned.

Profit is a feedback signal that indicates that the company is doing what consumers want.
Thus, if we buy from Amazon because it is cheaper,
we are voting for getting workers to do maximum work with minimum pay;
otherwise our things wouldn't be as cheap and fast as they are today.

If consumers want food to be delivered to their houses, then so be it, environment be damned.

If consumers want new stuff every year, then so be it, environment be damned.

Companies are not the only ones to blame; all of us are to blame for having endless desires.

Everytime we buy something, we make a moral judgement, even if we don't realize it.

Companies are simply doing what the consumers want.
If the consumers want cheap things, then so be it, workers and environment be damned.
Thus, the immorality of companies reflects the immorality of consumers.

We often buy something without caring about how it is made.
We turn a blind eye to the immorality of producing that thing.

The consumer's beliefs determine the company's behavior.

Buying from immoral companies means /voting for immoral behavior/.
** How can we care?
It seems impractical for one person to check every building, every mine, and every employee of all companies.

We establish an organization that summarizes the immorality of companies
so concisely that consumers can easily act on that report.
We must establish a moral police for policing the morality of companies.

Consumers must unite, prefer, and demand moral companies.

In 2019, I define the adjective "moral" to mean "not detrimental to the survival of the human race"
(my moral system in 2019 is natural morality),
but you can define "moral" to mean anything that suits your moral system.
For example, if you follow Jesus,
then you may define "moral" to mean "that would not be disapproved by Jesus".

To survive, we have to both think and feel.

To change the world, we must first change ourselves.
** What if we need something that is produced by only one company?
How are foods going to be delivered to our houses if not with plastic packaging?
The only alternative is to move the people instead of moving the food,
but aren't we all too lazy to walk to the restaurant?

How are we going to get electricity?

What if we need something that is produced by a monopoly with high barrier to entry?

Boycott the company, and put our lifestyle down a notch?

We can always choose to not buy (and perhaps suffer or die).

We can always kill ourselves, although we usually won't.

The crisis is a question to us: Which do we prefer:
much convenience but much environmental destruction,
or some inconvenience but slight environmental destruction?
** Other resources
- <2019-11-17> https://en.wikipedia.org/wiki/Ethical_consumerism
- <2019-11-17> https://en.wikipedia.org/wiki/Dollar_voting
- <2019-11-18> https://en.wikipedia.org/wiki/Consumer_activism

* English
- [[file:boeing.html][The root cause of Boeing 737 MAX fiasco: existentially-threatening competitions?]]
* Bahasa Indonesia
- [[file:cara-memilih-pejabat.html][Cara memilih pejabat dalam sebuah demokrasi]]
** <2019-08-20> Pengguna narkoba adalah korban, bukan penjahat
Pengguna narkoba harusnya ditolong, bukan dipenjara.

Korban memakai narkoba karena terisolasi secara sosial (merasa kesepian).

Penjara tidak menyelesaikan apapun.

Penjara adalah masalah, bukan solusi.

Untuk mengatasi narkoba, contohlah Portugis yang berhasil, dan jangan contoh Amerika yang gagal.
* <2019-08-21> Politics rule no 1: Avoid angering the majority
Avoid angering the majority.

If the majority are idiots, it is even more important to avoid angering them.

Even if you know the truth, avoid angering the majority.

(Isn't this common sense?)
* Unfortunately auto-segregation is rational
Every man thinks that it's much easier to move to where the "smart" people are than to fix the "idiots" around him.

For example, non-Muslim people would not want to live near mosques because mosques are noisy,
but Muslims would want to live near mosques because they go there very often.
Thus, those two groups have just automatically segregated themselves without anyone's help.
* Seeking the truth?
** Gun rights is now about selling guns for profit, no longer about fighting tyrannical governments
<2019-08-15>

In 2019, anyone who thinks that guns can protect them from tyrannical governments is deluded.
Governments have better guns, soldiers, cops, bombs, planes, drones, tanks, nukes, and a monopoly on violence bigger than ever in history.
Nevertheless, guns can be used to terrorize government employees to discourage people from working for the government,
 [fn::https://www.bbc.com/news/amp/world-us-canada-49339903]
but I don't recommend that,
and I don't plan to discuss asymmetric warfare[fn::https://en.wikipedia.org/wiki/Asymmetric_warfare] and militant anarchism here.

Thus the only reason left for gun rights is to let people sell guns for profit.
** Constitutions are not holy books
<2019-08-16>

Changing constitutions is almost as hard as changing bibles.
Constitutions have become holy books, and political ideologies have become religions.
Blind beliefs are bad for progress.

Constitutions should be hard to change,
because it is the foundation of all other laws in a country.
A constitution that changes often will confuse everyone.
Unfortunately, this also means that a bad constitution will stay bad forever.
** <2019-07-06> Borders are lawless places
*** <2019-07-06> Use a new clean phone that is not logged into anything, when you go abroad
Customs are lawless.
Borders are lawless places.
Laws are not enforceable at borders.
Rights do not exist at borders.
China forces travelers to install malware.[fn::https://www.slashgear.com/china-forces-malware-on-tourist-phones-at-border-heres-what-they-want-02582568/]
USA customs harass.[fn::https://www.schneier.com/blog/archives/2019/04/former_mozilla_.html]

Border Patrol had a secret Facebook group.[fn::https://theintercept.com/2019/07/05/border-patrol-facebook-group/]

Customs officials can make their own laws because they face no consequences:
There is no practical way to hold them accountable for their actions.
Also, people don't care.

Before we blame border patrol, we should try to empathize.
Are they underpaid?
Are they at risk?
Is their job dehumanizing or demoralizing?
Have we allocated them enough resources necessary for their job?
Is the system broken?
** Platforms and antitrust laws are inherently incompatible
A platform is only useful if everybody uses it, but if that is the case, then it has become a monopoly.
But monopolies are illegal?
Thus, are platforms illegal?

One can mitigate monopolies by requiring interoperability?
** <2019-08-17> British imperialism?
Opium wars?[fn::https://amp.cnn.com/cnn/2019/05/26/opinions/china-is-not-the-enemy-sachs/index.html]
** <2019-08-17> Entrepreneurial employee is exploitation
Work as hard as entrepreneurs, get paid as low as employees.
** <2019-08-20> On the false assumptions of deterrence theory
What is the point of making a weapon so powerful that you would rather not use it?
What is the point of living under constant fear?

https://www.theguardian.com/world/2018/jan/14/nuclear-deterrence-myth-lethal-david-barash
** <2019-08-20> What is natural economic growth?
As fast as /lives/ can grow: plants, bacteria, etc.
If you grow faster than natural, you are extracting some wealth?
** Can inventors profit without patents?
How?

Sell the invention as a service?

Are trade secrets protected?

Patents pros:
- incentivize innovation

Patents cons:
- encourage patent trolling and gaming the legal system for personal financial gain at the expense of others

https://en.wikipedia.org/wiki/Economics_and_patents
** <2019-07-06> Is freedom of speech important?
Examples of degrees of freedom of speech:
- In USA and Canada, you can talk shit about the government, as long as you don't make death threats, or the cops will get you.
- In Indonesia, you can disagree with the government, but you have to do it very politely, or you will be jailed.
- In China, if you disagree with the government, your will be encumbered, if not killed.
- In Saudi Arabia, if you disagree with the government, you will be killed.

But all government is more similar than different:
There is always centralization of power, and therefore abuse of power.

Without freedom of speech, life goes on pretty much normally in Indonesia.
Meanwhile, the USA, for all its free speech, still has problems like crony capitalism
and highest gun-related murder which is totally preventable
as shown by the Australians.

Why do you insist on owning a gun?
It does not protect you from a tyrannical government.
They have bombs, armies, nukes, soldiers, cops, gunboats, aircrafts, hackers, money, what else.
If you think your teeny-pistol militia can beat them, you're as deluded as Don Quixote;
but actually he has better chances than you do,
because windmills don't fight back, whereas governments do.
The freedom to bear arms is just a ceremonial distraction
from more important issues such as imperialism, privacy, and borders.
** <2019-07-06> Gerrymandering
Gerrymandering is a self-inflicted pain with a simple solution:
proportional representation[fn::https://www.fairvote.org/how_proportional_representation_would_finally]
 [fn::https://www.sightline.org/2019/05/03/the-secret-to-ending-gerrymandering-isnt-a-secret/].
Drawing district lines is like punching yourself in the face and wondering why it hurts.
The fix is simple: Just don't do it.

How does Alabama have a government that does not represent its constituents
 [fn::https://qz.com/1628427/saudi-arabias-abortion-laws-are-more-forgiving-than-alabamas/]
 [fn::https://www.motherjones.com/politics/2019/05/previously-unreleased-poll-shows-alabama-voters-disapprove-of-extreme-abortion-ban/]
 [fn::https://www.vox.com/policy-and-politics/2019/5/18/18630562/alabama-abortion-ban-voters-exemption-for-rape-incest]?
Gerrymandering?
** On the firehose of lies
“Don't try to fight the firehose of falsehood with the squirtgun of truth,” Paul said. “Try to put 'raincoats' on those who will be hit with the firehose.”
 [fn::https://www.rand.org/blog/2016/12/beyond-the-headlines-rands-christopher-paul-discusses.html]
 [fn::https://www.youtube.com/watch?v=i1pA1kpJosk]
** Bush's Iraq War
Bush attacked Iraq to reaffirm American hegemony.[fn::https://www.aljazeera.com/amp/indepth/opinion/bush-war-iraq-190318150236739.html]
That is, he did it just because he could.
** What is the problem with West Java?
Jawa Barat: sudah berpenduduk terbanyak[fn::https://ilmupengetahuanumum.com/jumlah-penduduk-indonesia/],
sarang ekstremis pula.[fn::https://www.jpnn.com/news/mms-sebut-jawa-barat-sarang-ekstrimis]
Tapi yang sering ada bom masuk berita bukannya Jawa Timur?
Sama-sama teroris tapi beda cabang?
** Sejarah Islam Indonesia
https://www.nu.or.id/post/read/71691/awal-mula-masuknya-islam-di-indonesia-menurut-mbah-maimoen-
** There is no such thing as "straight", "gay", or "lesbian"
Men have been putting their dicks wherever they want to since humans existed:
in their own hands, in other women, in other men, in goats, in horses, you name it, someone has tried to put their dick in it.

Perhaps women also have the same problem: you name it, someone has tried to put it in their vagina.

Perhaps humans just like sex.
** Examples of costly cost-cutting when management overrides engineers
I used to argue for nuclear fission power.
Now I argue against nuclear fission power, not because it is harmful, but because companies cannot be trusted.
I feel that companies are inherently incompatible with humanity; they centralize power to shareholders.

I trust engineers and scientists, but I don't trust companies.
If a nuclear power plant is run by a company, it is just a matter of time
before someone in management cuts costs for short-term profit,
skimps on something, dismisses the engineers, and causes an accident.
It has happened with airplanes (such as Boeing 737 MAX, they cut corners because they were competing with Airbus),
nuclear fission power plants (such as TEPCO Fukushima, they ignored an engineer's concern about the backup pump's vulnerability to giant tsunami).

When you ignore an engineer, a disaster will happen,
and you will bear a much higher cost than what would cost you if you just did what the engineer told you to do.
Disrespecting engineers and scientists is disrespecting Nature, and /Nature does not care about your profits./
** An insightful clustering of America into 11 nations
https://www.npr.org/2013/11/11/244527860/forget-the-50-states-u-s-is-really-11-nations-says-author
** South Korea quits Windows cold turkey?
https://betanews.com/2019/05/18/korea-linux/

What about "Indonesia goes open source"?
** FairTube, and renaming "advertising"
I hope FairTube wins, but the root cause of the problem is that today's "advertising" is about /making people buy/,
by psychological manipulation, by all means, at all costs;
whereas the original 15th century meaning of "to advertise" is to "give notice to others"[fn::https://www.etymonline.com/search?q=advertise].
There was no sense of persuasion in the 15th-century advertising.

In 2019, "advertising" is about manipulating people into buying things, by all means not forbidden by law.
Thus what we call "advertising" now, we should call "for-profit psychological manipulation".
** I'd rather have police not work than have them incentivized to catch people
Incentivizing police to catch people is extremely dangerous;
I'd rather have police not work than have them eagerly incriminate people.

Police should not be rewarded for making arrests.
Police should not be rewarded for successful trials.
** On modern monetary theory, taxes, incentives, behaviors
We should think of /taxes/ as a way for /incentivizing/ behaviors, /not/ for /funding/ government programs.
The government can just create money out of nothing, as long as the money creation rate does not exceed the real economic growth rate.
Indeed, right now, banks are creating money out of nothing, in the form of loans,
and these virtual numbers can have real effects on prices:
If, at the same time, one million people get loans and buy cars,
then there will be a short-term shortage of cars (demand surge),
and producers may decide to increase production or raise prices or both if the surge persists.

But what if the real economy is shrinking?
* Crazy ideas?
** <2019-08-14> Elections should have an entrance fee
The amount is not important, but should be low, but not zero.
What is important is that an entrance fee /exists/.

When a surgeon fails, he injures one people.
When a car driver fails, he injures ten people.
When a lawmaker fails, he injures millions of people.
Then why do we insist on lower standards for our lawmakers than for our surgeons?
Why do we elect clueless clowns and self-enriching thiefs into the government?
/Because we pay for a surgery but not for an election/.
Paying for something increases our expectation.
We don't pay for an election, so we expect nothing.

But companies do pay for elections, through contributions and lobbyings.
Thus companies expect to gain from elections, while people don't.
** <2019-08-14> We need a World Government
These entities may have done things that would be considered atrocities by 2019 standards:
Muhammad
 [fn::https://wikiislam.net/wiki/List_of_Killings_Ordered_or_Supported_by_Muhammad]
 [fn::Why Did Carl Jung Compare Hitler To Muhammad? https://www.youtube.com/watch?v=BzlESr-2cZ4],
Suharto[fn::https://indonesiaatmelbourne.unimelb.edu.au/theres-now-clear-proof-that-soeharto-orchestrated-the-1965-killings/],
the United States of America[fn::https://en.wikipedia.org/wiki/United_States_war_crimes],
the British Empire[fn::https://www.independent.co.uk/news/uk/home-news/worst-atrocities-british-empire-amritsar-boer-war-concentration-camp-mau-mau-a6821756.html],
many imperialist European countries,
Mao[fn::https://en.wikipedia.org/wiki/Mass_killings_of_landlords_under_Mao_Zedong],
Stalin[fn::https://en.wikipedia.org/wiki/Excess_mortality_in_the_Soviet_Union_under_Joseph_Stalin],
Hitler[fn::https://en.wikipedia.org/wiki/The_Holocaust],
Genghis Khan,
and many more[fn::https://www.hawaii.edu/powerkills/NOTE1.HTM][fn::https://en.wikipedia.org/wiki/Democide],
if not everyone.

/But only Hitler lost the war./

Thus now Hitler is condemned, whereas the others are venerated.

It is a crime to murder one person.
It is not a crime to wage an unjust war /and win the war/
because the winner gets to define what "crime" is, and then he gets to write the history.
This is just human nature.
Even I myself suffer from that:
I often find myself imagining the killing of billions of people,
be it by my own hands or by a natural catastrophe,
and I imagine the peace that follows, the problems that disappear,
the overcrowding gone, the pollution gone, the noise-makers gone, the exorbitant land prices fall.

There is no government for countries,
and thus countries go to war against other countries.
At the level of citizens, there is a rule of law,
but at the level of countries, it is anarchy.
Thus it seems that there has to be a government for governments,
but this suffers from infinite regress:
second-level governments may go to war with each other,
and so on.
Thus, the only way to global peace is /to have exactly one government for all people/, one World Government,
because it is impossible to have a war if there is nobody else to wage a war against,
that is, if you are the only government in the world.
This is the only way to prevent wars.

This World Government should be filled with scientists and engineers
because they do politics better than politicians do;
see China[fn::https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers],
but it's changing in 2017.[fn::https://www.scmp.com/news/china/policies-politics/article/2117169/out-technocrats-chinas-new-breed-politicians]

But people are too chauvinistic, too egoistic, and too proud for a World Government.
All nationalism is chauvinism, because we are all citizens of the Earth.
As technology is heading toward a singularity,
human culture is also heading toward a singularity.

Having different governments also enables tax avoidance, money laundering, and wage slavery,
by enabling one to arbitrage different regulations in different countries.
** <2019-08-14> People, not beliefs, deserve respect
We can respectfully treat people who believe unjustifiable things such as religions, superstitions, but we should not respect their beliefs.
If we facilitate some people with stupid beliefs, it is not because we respect their beliefs, but because we respect their feelings.

But this is impractical.
People interpret attacks on their beliefs as attacks on their selves.

Not all opinions are equal:
- [[https://www.youtube.com/watch?v=pe4feBH0ABk][Richard Dawkins: No, Not All Opinions Are Equal---Elitism, Lies, and the Limits of Democracy - YouTube]]
  - If you have a surgery, you want an expert surgeon.
  - If you have a concert, you want an expert musicians.
  - Why then, when it comes to Brexit, do people suddently think they are expert politicians?
    - The people voting for Brexit might not even understand what the European Union is.
** <2019-08-20> Common law is more agile than civil law
Civil law is always late, because we suck at foretelling.
In civil law, everything is legal until legislators make a law against it.

But common law requires higher standards for judges, whereas judges are fallible humans too, just like the rest of us.

Humans are not computers.
Humans excel at following the /spirit/ of the law.
Computers excel at following the /letter/ of the law.
Indeed humans who strictly follow the letter of the law may be malicious.

Lawmakers should make principles, not rules.
Lawmakers should explicitly state the spirit and intention of the law,
not just the letter of the law.
** Growing food is the best solution to poverty
Growing food is the only sane way to lift many people out of poverty, because /Nature pays everyone who works/.

It reduces unemployment, poverty, homelessness, crime.

Example[fn::https://www.bbc.com/indonesia/majalah-47052996]

A scalable solution to poverty?

1. Relocate poor people to fertile land that is unused but not too far from civilization; give each family 100 square meters.
2. Help them grow food; educate and train them. Pay attention to ecology, and close the nutrient cycle.
3. Help them sell their production.

This simultaneously solves hunger, poverty, homelessness, overcrowding, and crime.

This reduces agricultural failure risk:
More small farms distributed geographically means we have more backups to a regional catastrophe.

Indonesia will lose 20% corn production by 2050 due to climate change?
 [fn::https://medium.com/@jeremyerdman/we-produce-enough-food-to-feed-10-billion-people-so-why-does-hunger-still-exist-8086d2657539]
* Capitalism exploits individual selfishness to benefit everyone?
Capitalism assumes that humans are bad and selfish.
Communism assumes that humans are good and altruistic.
In reality, most humans are between those two extremes.

In capitalism, X helps Y because X wants Y's money.
Capitalism assumes that there is only unconditional selfishness and no unconditional love.
Capitalism is about making the desire to gain money coincide with the desire to better humankind.

In communism, X helps Y because X has unconditional love for everything.

There are no pure capitalism and no pure communism.
Humans are somewhere between totally selfish and totally altruistic.

Everyone wants to maximize their own profit.
Everyone only cares about themselves.
Therefore, a system must be created, such that selfish people can only profit by benefiting others.

What does a system incentivize?
* Unions?
Who does a union benefit?
The incumbent workers?

Do laborers have less bargaining power than capitalists?

https://www.quora.com/Why-do-some-people-hate-labor-unions

https://en.wikipedia.org/wiki/Opposition_to_trade_unions
* <2019-08-14> Groups diffuse blame
A perverse situation may arise, in which the individual is praised for success, but the group is blamed for faults,
perhaps due to our desire to feel good and avoid conflicts.
An example of such perverse situation is the belief "If this country advances, it's due to the president; if this country regresses, it's due to the government",
or "If this company profits, it's due to the director; if the company loses, it's due to everyone".
* <2019-08-14> Why are corporations legal people?
Corporations are legal people so that they can be sued and brought into court.
 [fn::https://www.forbes.com/sites/timworstall/2012/11/17/ill-believe-corporations-are-people-when-texas-executes-one-what-is-this-foolishness-from-robert-reich/#78f1f29633f2]
* Core beliefs
If a belief conflicts with reality, then the belief must change.

We define "good" as "promoting the survival of the human species".

/Nationalism is collective egoism./
There should be only one government on Earth, and it should be The Only World Government,
because otherwise governments will fight each other due to national egoism.

We prefer to be /sober/ and savor every moment of our lives.
The only time we use consciousness-altering drugs is in great pain, such as in surgeries or in terminal illnesses.
We do not drink alcohol to the point of intoxication.

/We hate smoke/: cigarettes, vapes, you name it, we hate it.
We do not smoke.

/We hate perfumes./
We prefer no odor at all.
We prefer slight natural body odor to perfumes.

We think a little dandruff and a little body odor is normal.

We treat most bacteria as essential, not as things to be eradicated.
We only use antibiotics if it is the only way to save us from death.

We do not want to change the status quo for the sake of change without reason.
Disruption is not something to be proud of.
Every change has unintended consequences.

We prefer /sustainability/ to growth.

/Leisure/ is noble and there is nothing shameful about wanting leisure, seeking sustainability, and shunning gratuitous growth.

/Pension is robbing the young to pay the old./
It assumes that the population pyramid will always have a certain shape.
It is not sustainable.
* <2019-08-21> Hiring from trading point of view: buy low sell high
Everything is trading: Buy low, sell high.

Hiring is trading too.
Buy labor cheap, sell products high.

Labor has maintenance costs, just like machines.
Skimp on machine maintenance, they break down.
Skimp on labor maintenance, they resign, or worse, they riot, or even worse, they unionize.
* <2019-08-21> Capitalism and morality?
From https://evonomics.com/role-of-morality-in-a-capitalist-economy/
#+BEGIN_QUOTE
Now, what do you mean social good? In economics and evolution we have a well-defined concept of public goods.
Production of public goods is individually costly, while benefits are shared among all.
I think you see where I am going.
As we all know, selfish agents will never cooperate to produce costly public goods.
I think this mathematical result should have the status of “the fundamental theorem of social sciences.”
#+END_QUOTE
* Seek wealth, not money
If one wants to be rich, then one should seek wealth, not money.
One should always know that money is only a proxy of wealth, and the conversion of money to wealth always depends on who is willing to accept that money.
* <2019-10-28> Anarchy, selfishness, institutions
Humanity should not try anarchy before humanity can overcome its own selfishness.

Anarchy cannot work with selfish people.

Capitalism is the system for making selfish people help others.

Capitalism assumes the least of humans.
Capitalism does not assume that people are good.

If humans were not selfish, anarchy would work much better than capitalism did.

Often we do not have the luxury of assuming that people are good.

But the total wealth in the 21st century is much higher than the total wealth in the 20th century.

/Can humanity accomplish great things without institutions?/

Even without formal institutions, there will be de-facto makeshift institutions headed by experts who know what to do, established by people who have power.

Institution is one way of doing something that takes more than the lifespan of one human.

Institutions suck, but perhaps they are better than the natural state of man that is anarchy,
but anarchy would be the best if humans were able to overcome their selfishness.
Anarchy would only work if most people were very altruistic.
* <2019-07-06> Blinking Morse code as covert communication channel
Jeremiah Denton signals "torture" by blinking on TV while he was a war prisoner in Vietnam.
 [fn::https://qz.com/1625459/learning-morse-code-is-a-valuable-skill-even-in-the-21st-century/]

* <2019-08-20> Atomic Shrimp's fun way to deal with scammers: "Reply all"
"Bringing Scammers Together (Not Harmonious!) - Scambaiting By Reply-All"[fn::<2019-10-27> https://www.youtube.com/watch?v=py-cQ5PscsU]

That is fun but perhaps unsuitable for average people;
perhaps it would be better for average people to not reply at all.

* <2019-07-07> Using government data?
Marc Dacosta: Adventures in the Dark Web of Government Data[fn::https://www.youtube.com/watch?v=SzkyuGeNDf8]:
joining multiple disparate data sources.

* Junk?
** Suspicious things; things to keep track; things to recheck next year
*** <2018-10-04> Amazon raises its warehouse worker wage (hourly pay) from about $8 (?) to $15 (minimum wage).
- https://news.vice.com/en_us/article/yw4n7j/jeff-bezos-just-caved-to-activists-and-bernie-sanders-and-raised-amazons-minimum-wage-to-dollar15
**** Find out 1 years later: Compare the number of blue-collar workers.
*** <2018-10-06> Swiss banking is no longer secret. Does this reduce international crimes / money laundering?
- "Era of bank secrecy ends as Swiss start sharing account data"
  https://www.reuters.com/article/us-swiss-secrecy/era-of-bank-secrecy-ends-as-swiss-start-sharing-account-data-idUSKCN1MF13O
*** <2018-09-26> Why is Nikkei Asian Review sponsoring Mochtar Riady stories?
** The other side of Trump
The non-media's opinion of Trump:
"Actions Speak Louder Than Words: The Real Donald Trump"
https://www.youtube.com/watch?v=zRogXTFtpUc

Publishers scramble to cash-grab, slaps "Trump" on anything, crap literature
https://www.youtube.com/watch?v=wB8bJyjr_Ao

Trump is sometimes right.
https://www.youtube.com/watch?v=jymNk_YgcpE

Trump attacks Guantanamo 1 million dollar soccer field.
This is an argument defending the 1 million dollar soccer field.
https://www.reuters.com/article/nsa-Guantanamo-soccer-idUSL2E8E1CC520120301
** <2018-11-19> Who is honest nowadays?
I don't know who is honest anymore.
Everybody seems to be making their own reality bubble.
Mass delusion.
** Why is Xi Jinping becoming so powerful?
Some answers/opinions on Reddit:
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvmnlo
- https://www.reddit.com/r/China/comments/80fqlr/why_is_xi_jinping_becoming_so_powerful_why_is_the/duvf76g
** This may be biased; speculations about China
*** Speculations
These are the possible scenarios:
- The oppressed thinks that they are already dead (their lives are worse than death) anyway,
  musters enough strength, revolts, and overthrows the government.
  The non-oppressed (the middle-class) takes collateral damage.
- The government kills off all oppressed people.
  The non-oppressed people lives in their bubble happily ever after.
- The government slowly releases control while trying to save face.

Xi Jinping cannot release control in 2018, because if he releases control, his opponents will pounce on him, reveal all his crimes, and tarnish his name.
Xi Jinping wants to die in good standing, with good reputation; he wants to be remembered as a good person.

I hope that the next bloodshed gives the Chinese people enough reason to limit government power.

You can live a good comfortable life in China as long as you blind yourself from the truth.

- <2018-09-26> [[https://www.youtube.com/watch?v=eViswN602_k][Exposing China's Digital Dystopian Dictatorship | Foreign Correspondent]]
  - China's Big Brother system favors obedient middle-class people, and limits journalists, minorities, and dissenters.
  - Alibaba helps oppression.
    Alibaba is making AI to help the Chinese government oppress people more efficiently.
    Do they profit from oppression?

Stalin's inner circle was too afraid to tell him the truth.
Nobody dared to challenge Stalin.
Stalin's inner circle told him what he wanted to hear.

https://www.quora.com/Is-is-true-that-top-Soviet-officials-lived-in-constant-fear-under-Stalin-Or-is-that-an-exaggeration

After Stalin died, there was a great purge.

You know your country is led by an authoritarian if:
- You can't say the truth there.
- There is someone whom people are too afraid to disagree with, even politely.

We must respect the truth.
The truth doesn't care about us.
People who ignore the truth do so at their own peril.
Ignoring the truth means ignoring some danger;
such ignorance reduces the chance of survival.
*** Hopeful
[[https://www.youtube.com/watch?v=8XQ1onjXJK0][Are China and the US doomed to conflict? | Kevin Rudd - YouTube]]
** Living in a republic
*** If you don't vote, you let the worst guy win.
Your vote prevents greater harm.
*** If you vote some people, and they win, then, you are, in some way, responsible for the bad things that they
George Carlin doesn't vote https://www.youtube.com/watch?v=xIraCchPDhk
*** If you don't speak, you let the worst guy do anything he wants.
You must state your disagreement.
** <2018-09-20> Politics
- [[https://www.youtube.com/watch?v=xDsg2sLhnIE][Trump Is Making America Great Again. Just Not the Way He Thinks. | NYT - Opinion - YouTube]]
** Why the non-oppressed people must help the oppressed people
Because when the oppressed people revolt, the non-oppressed people will be among the victims.
** <2018-09-21> Australia fruit sabotage crisis
- Is it done by immature kids?
- Is it done by foreign actors (to destabilize Australia, for example)?
- Is there any other explanation?
** <2018-09-22> Power: control vs identity
"The traditional view—that power means having /control/ over a group of people—is giving way to a new understanding: that power means having other people /identify/ with you." ([[https://insight.kellogg.northwestern.edu/article/four-tips-to-gain-influence-in-your-organization][source]])
** Donald Trump, media firehose of lies, psychology
*** Everybody wants their own reality.
The media lie.
Newspaper lie.
Politicians lie.
*** https://www.reddit.com/r/The_Donald/ is a firehose of lies.
- That subreddit uses derogatory/bully language.
  The same technique used by school bullies: calling names.
- https://www.reddit.com/r/The_Donald/wiki/index
  - rule no. 6: "Trump Supporters ONLY - This sub is for supporters of Donald J. Trump ONLY.
    This is not a place for you to debate with us about Donald Trump, or to ask us to convince you to like Donald Trump.
    This is not a neutral place - we are 100% in support of Donald J. Trump. Moderators reserve the right to ban non-supporters as we see fit."
    - Read: This subreddit exists to perpetuate lies.
      We are lying, but we don't want people to think that we are lying.
      We will ban everyone who points out that we are lying.
- That subreddit bans fellow Trump supporters who don't lie.
  - https://www.reddit.com/r/BannedFromThe_Donald/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/64kduy/trump_supporter_gets_banished/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/6thnoa/banned_for_linking_a_t_d_post_on_t_d/
    - https://www.reddit.com/r/BannedFromThe_Donald/comments/7klmhy/the_lovely_messages_you_get_from_the_moderators/
- https://www.reddit.com/r/AgainstHateSubreddits/comments/851rgd/i_compiled_a_list_showcasing_the_donalds_50_worst/
*** Mass bullying, mobbing
- https://en.wikipedia.org/wiki/Mobbing
*** Psychology
- https://www.psychologytoday.com/us/blog/mind-in-the-machine/201609/the-psychology-behind-donald-trumps-unwavering-support
  - "There may be nothing we can do" means "the only way to fix it is by killing those deluded people but, unfortunately, doing so is illegal".
*** Nobody should be able to spread lies and go unpunished.
*** Do Trump's bankruptcies imply that he is incompetent?
*** What is the history of the Republicans? What is the history of the Democrats?
*** When humanity is divided, only a catastrophe can reunite us.
- alien invasion
- catastrophic natural disaster
- supervolcanic supereruption
- nuclear plant meltdown
- famine
- any existential threat; a threat to the existence of all of us
** The truth about the truth
- It is impractical to know the truth.
  - We can only perceive things near us (about a few meters).
  - It is impractical to visit every corner of the world and see everything with our own eyes.
  - It is impractical to verify every sentence a person has ever uttered.
- What then?
- Can we tell apart the liars from the honest people?
- If everyone were humble enough to admit that they don't know the truth, extremists wouldn't exist.
*** Learn to ride the media for free and win like Trump
- How Trump Manipulates The Media https://www.youtube.com/watch?v=IctC0Quf8zc
  - If you're wrong, don't apologize.
    Apologizing requires you to restate the charge and what gets repeated gets remembered.

As long as media optimizes themselves for maximum traffic (for advertising), people like Trump are going to win.
Sensationalism gets traffic.

Think of the headline that you want, and repeat it.
Headlines have to be short.
Keep your message simple.
Repeat the message.

Keep your calm, no matter what others say.
Repeat the headline.

** Game-changer? DoNotPay: automate lawyers?
- https://www.youtube.com/watch?v=xbXM-aNRNlY
- https://www.donotpay.com/
** Does Wikileaks matter? Who is going to scour all that text for interesting stuffs / incriminating evidence? Most people don't have time to read that.
But the point is that everybody who wants to verify it can verify it, not that everybody should read it.
** All fierce debates are language problems
Communication consists of input, processing, and output.

In a fierce debate, there is no input; there is only output, and the participants don't even agree about the definitions.
They don't know what they are talking about.
** News?
*** <2018-10-05> Global information technology hardware supply chain serious security disaster
- https://www.bloomberg.com/news/features/2018-10-04/the-big-hack-how-china-used-a-tiny-chip-to-infiltrate-america-s-top-companies
- https://www.schneier.com/blog/archives/2018/10/chinese_supply_.html
*** <2018-10-02> Beware of China's debt-trap diplomacy?
Beware of every other nation that seems helpful.

What is this [[https://www.youtube.com/watch?v=lVYdqoVJIeI][video]] trying to say?

The system forces politicians to be myopic (think short-term); they only see at most 5 years ahead.
** Witness testimony shouldn't count as /sole/ evidence; there has to be independent corroboration
- How reliable is your memory? | Elizabeth Loftus https://www.youtube.com/watch?v=PB2OegI6wvI
- Steve Titus: victim of false memory https://en.wikipedia.org/wiki/Wrongful_conviction_of_Steve_Titus
** Politics?
*** Law
- Law should be principle-based instead of rule-based.
- A judge should facilitate restoration, not determine punishment.
*** Cops, government, and you
Cops don't work for you. They work for the government.

The government doesn't work for you. They work for themselves.
Only people with entitlement mentality thinks the government works for them.
*** What is this? Politics?
"Hans J. Morgenthau, /Politics Among Nations: The Struggle for Power and Peace/, Fifth Edition, Revised, New York: Alfred A. Knopf, 1978, pp. 4-15"
"Six principles of political realism"
https://www.mtholyoke.edu/acad/intrel/morg6.htm
*** Rights
Right is given by one person to others.
To give person P the right to do D is to let P do D
** Improving society?
- Preventing social isolation
  - Social isolation causes violence and extremism.
    Bullying is part of the social isolation vicious circle.
    [[https://www.youtube.com/watch?v=azRl1dI-Cts][YT:I Was Almost A School Shooter | Aaron Stark | TEDxBoulder]]
    - [[https://www.youtube.com/watch?v=DmWrx0ntATU][YT:Cohousing communities help prevent social isolation]]
- Achieving independence
  - Demonopolizing the ability to do violence?
    - People who care (and thus readily mobilize) are less oppressable than people who don't.
      - How do we get people to care about and participate in politics?
    - Online campaigns/petitions.
      - [[https://www.newscientist.com/article/mg22630182-800-technology-can-give-political-power-back-to-the-people/][Technology can give political power back to the people - New Scientist]]
    - Using the Internet (social media, messaging, forum, etc.) to incite people?
    - Teach people how to participate democracy?
      - If shit gets to the top, people have only themselves to blame.
        - Democracy means they could have prevented that shit.
          - But they were apathetic.
            They didn't care.
            They gave up before even trying.
            So that shit rose without any obstacles.
  - Automating politics/governments/law?
  - Empowering people with distributed local technology?
    - Take power away from governments and elites, and give it back to the masses?
      - Isn't that mobocracy/ochlocracy?
        Anarchy?
        Do we want?
        - [[https://rationalwiki.org/wiki/Anarchy#Contrast_with_mobocracy][RationalWiki: Difference between anarchy and mobocracy]]
** Evil automobile industry
https://www.reddit.com/r/todayilearned/comments/9mv3oi/til_that_the_term_and_concept_of_jaywalking_was/

Given enough time, all industry eventually becomes corrupt.
Even something as mundane as the window industry is corrupt.
** Tech problems
*** Bloomberg spy chip report? Untrustworthy hardware manufacturers?
https://techcrunch.com/2018/10/07/homeland-security-denies-bloomberg-spy-chip-report/amp/
https://techcrunch.com/2018/10/04/bloomberg-spy-chip-murky-world-national-security-reporting/

Is Bloomberg fake news?
https://techbeacon.com/security/bloomberg-spy-chip-story-will-not-die

It does not make sense for Huawei/Supermicro/Lenovo to plant spy chips,
because someone else will find out,
and it will hurt the company's reputation a lot,
unless they are so sophisticated or powerful that can do it undetected or get away with it.
Ren Zhengfei of Huawei has denied planting spy chips, for that reason, which makes sense.
https://www.youtube.com/watch?v=Nl2jCWDwE8w

Are Supermicro and Lenovo untrustworthy?
Jamie Schnaitter:
"It's already been a touchy topic, especially since major players in HPC, such as SuperMicro and Lenovo have been caught with malware in their firmware and on their websites."

Could the Lenovo SuperFish[fn::https://en.wikipedia.org/wiki/Superfish] scandal be accidental?
It could be the case that Lenovo was just bundling/preinstalling third-party apps
(which seems to be a common practice among OEMs)
and did not know that SuperFish installed a certificate.

Sony BMG also had a DRM rootkit scandal.
 [fn::https://en.wikipedia.org/wiki/Sony_BMG_copy_protection_rootkit_scandal]

https://arstechnica.com/information-technology/2018/12/supermicro-refutes-report-of-malicious-implants-with-audit/
*** Facebook is rotten to the core?
"If you still have a Facebook account, delete it and stop using Facebook"
https://www.youtube.com/watch?v=vEDGJWocYd8

Facebook is corrupting WhatsApp?
Should we leave WhatsApp?
https://www.forbes.com/sites/parmyolson/2018/09/26/exclusive-whatsapp-cofounder-brian-acton-gives-the-inside-story-on-deletefacebook-and-why-he-left-850-million-behind/amp/
*** Redundant people don't simply disappear.
Neo-Luddites fights tech with tech.

The Luddites aren't stupid.
They are frustrated because quick landscape changes cause mass layoff of the Luddites,
but everybody else wishes that the Luddites just disappear.

The problem with introducing technology:
the replaced people are now jobless, but they don't simply disappear.

It is simple to DDoS Facebook.
Create an Android app that slowlorises the servers.
Tell people to download the app to better mankind.
*** Slack anticompetitive?
https://www.theverge.com/platform/amp/2018/9/24/17897658/slack-astro-acquisition-email-app-shut-down-integration
*** Google
The Google Cemetery: List of dead Google products
https://gcemetery.co/
*** 2018 article "How the Internet went wrong in 15 steps"
How the Internet went wrong in 15 steps
http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html
- "Step 1: Start With Hippie Good Intentions"
- "Step 4: [...] we paid a high price for keeping [the Internet] free"
  - "To avoid charging for the internet — while becoming fabulously rich at the same time — Silicon Valley turned to digital advertising."
  - Click maximization breeds sensationalism and extremism: /anything goes/, for a click.
    - Growth at all costs.
      Growth for the sake of growth.
      Idolization of growth.
      Growth is overrated.
      Growth isn't always desirable.
  - Tristan Harris: "We cannot afford the advertising business model. The price of free is actually too high.
    It is literally destroying our society, because it incentivizes automated systems that have these inherent flaws.
    Cambridge Analytica is the easiest way of explaining why that’s true.
    Because that wasn’t an abuse by a bad actor — that was the inherent platform.
    The problem with Facebook is Facebook."
- "Step 5: Everything was designed to be really, really addictive.
 The social-media giants became 'attention merchants', bent on hooking users no matter the consequences.
 'Engagement' was the euphemism for the metric, but in practice it evolved into an unprecedented machine for behavior modification."
  - Guillaume Chaslot: "The way AI is designed will have a huge impact on the type of content you see.
    For instance, if the AI favors engagement, like on Facebook and YouTube, it will incentivize divisive content, because divisive content is very efficient to keep people online."
- Internet business model that is not advertising
  - "Step 12: To fix it, we’ll need a new business model. Maybe [...] like charging users for goods and services"
  - I think Facebook/Twitter/Reddit/YouTube can make country-level subscription that countries pay using taxpayer money.
- "Step 14: Maybe nothing will change."
- What people say
  - Tim Berners-Lee: "The fact that power is concentrated among so few companies has made it possible to weaponize the web at scale."
  - Tim Cook: "I don’t have a kid, but I have a nephew that I put some boundaries on. There are some things that I won’t allow; I don’t want them on a social network."
  - Chamath Palihapitiya: "The short-term, dopamine-driven feedback loops that we have created are destroying how society works. No civil discourse, no cooperation; misinformation, mistruth. This is not about Russians’ ads. This is a global problem."
*** Privacy problem
https://gizmodo.com/apps-you-use-every-day-are-tracking-your-every-move-ac-1830980646/amp

** Aircraft crashes
Causal chain:
- Boeing 737 MAX crashes two times in less than a year.
  - MCAS (Manuvering Characteristic Augmentation System) fights the pilot.
    - MCAS is a software workaround for a hardware flaw (the aircraft's tendency to pitch up and stall when engine power is increased).
      - The hardware flaw is an economic workaround for a strategic flaw?
        - Boeing wants to avoid retraining costs.
        - Boeing sticked to the 737 design for too long?
          - Boeing is averse to giant-leap innovations?
          - Economic competition too aggressive?

<2018-10-29>
Lion Air JT 610 jatuh menghantam air laut di dekat Karawang.
Wait for black box analysis result.

Boeing 737 MAX Lion Air JT 610 crash

The safety system, designed to protect the people, killed them instead.

<2018-11-15> Lion Air crash: Boeing sued by victim's family over aircraft design
https://www.bbc.com/news/amp/world-asia-46230496

https://arstechnica.com/information-technology/2018/11/indonesia-737-crash-caused-by-safety-feature-change-pilots-werent-told-of/

Sensor error is more likely than actual stall?
The designers trust themselves more than they trust the pilots?
The pilots didn't read the manual?
Boeing didn't disseminate information fast enough?
Hardware fault?

https://en.wikipedia.org/wiki/Stick_pusher

https://philip.greenspun.com/blog/2018/11/11/boeing-737-crash-is-first-mass-killing-by-software/

** Terror, fear, power?
Engels:
"Terror consists mostly of useless cruelties perpetrated by frightened people in order to reassure themselves."
** Climate change
Climate change (increasing temperature and carbon dioxide) is real, but we don't agree about whether it's harmful
https://www.youtube.com/watch?v=m3hHi4sylxE
** <2018-09-19> Recruiting networks are double-edged swords for employers
Example tools: Linkedin, SmartRecruiters.

You can use it to find new employees.
But your employees can also use it to find new employers.

But the overall economy stands to gain if we can fix the information asymmetry in job market.
** <2018-09-19> Sturgeon's law, originally for science fiction, also applies to job applicants
"Ninety percent of everything is crap."

Ninety percent of your applicants is crap.

Indeed it applies to /everything/.
Ninety percent of /everything/ is crap.
Software.
Companies.
Goods.

Ninety percent of /everything/ is crap: people, countries, etc.;
and we may be in that 90%.
** <2018-09-28> "Class Struggle" board game

- [[http://www.nyu.edu/projects/ollman/game.php][what it looks like]]
- [[http://www.nyu.edu/projects/ollman/game_rules.php][the rules]]
** Ethics and the workforce
- [[https://www.econlib.org/library/Enc/MarketforCorporateControl.html][Market for Corporate Control -- Econlib]]

  - "Markets discipline producers by rewarding them with profits when they create value for consumers and punishing them with losses when they fail to create enough value for consumers."
*** Tech giant ethical issues

- Bezos Amazon worker condition?
- Google Dragonfly supports Chinese authoritarianism?

**** Don't buy from Oracle.

- [[https://www.reddit.com/r/programming/comments/5iogug/oracle_finally_targets_java_nonpayers_six_years/][Oracle finally targets Java non-payers -- six years after plucking Sun : programming]]
- [[https://developers.slashdot.org/story/16/12/18/0147216/oracle-begins-aggressively-pursuing-java-licensing-fees][Oracle Begins Aggressively Pursuing Java Licensing Fees - Slashdot]]

*** <2018-08-29> IQ and jobs
  Although I'm happy to be proven wrong,
  I believe that a minimum IQ of 120 is necessary but not sufficient for software engineering (cooperativeness is also required).
  It seems IQ tests are inaccurate for high IQs above 130.
  - [[https://www.reddit.com/r/learnprogramming/comments/2ue71p/what_iq_do_you_need_in_order_to_be_a_programmer/][What IQ do you need in order to be a programmer? : learnprogramming]]
    - The OP doesn't sound like his IQ is 89.
  - Higher IQ means faster learning, and that's all.
  - To each according to their ability.
    Society needs low IQ people.
    Some jobs fit low IQ people.
    These jobs are equally honorable as high IQ jobs are.
    Low IQ isn't an insult.
    Everyone is different.
** Data, customers, and reality
- https://www.inc.com/business-insider/amazon-founder-ceo-jeff-bezos-customer-emails-forward-managers-fix-issues.html
  - "If all his [Bezos's] data says one thing and a few customers say something else, he believes the customers."
** Solving the Israel-Palestine problem
- I propose this for the Israel-Palestine problem:

  - Country

    - Establish a new country (say "Ispal"), merging Israel and Palestine.

  - Government

    - Everyone in the Israeli government is in the Ispalian government.
    - Everyone in the Palestinian government is in the Ispalian government.

  - Land

    - The land of Ispal is the land of Israel plus the land of Palestine.

  - Citizen

    - Every Israeli is an Ispalian.
    - Every Palestinian is an Ispalian.

  - Law

    - Every Ispalian is equal before the law.

  - Why this might not be accepted

    - Idealism, fanaticism, narrow-mindedness, intolerance, ignorance of history, mixing religion and politics
** Performance review?
*** Why do companies have performance reviews?
   :PROPERTIES:
   :CUSTOM_ID: why-do-companies-have-performance-reviews
   :END:

Meritocracy?

To weed out bad apples?

Governance?
Minimize risk, not maximize reward?

*** Does it do what we intend it to do?
   :PROPERTIES:
   :CUSTOM_ID: does-it-do-what-we-intend-it-to-do
   :END:

Problem: People tend to talk only about the good things of other people.

Problem: Retaliation.
If A say bad things about B, B will retaliate.

https://en.wikipedia.org/wiki/Machiavellianism_in_the_workplace
https://en.wikipedia.org/wiki/Workplace_deviance
https://en.wikipedia.org/wiki/Live_and_let_live_(World_War_I)

Does performance review make employees think short term and seek quick small wins?

*** Why does the Internet think that performance reviews don't work?
   :PROPERTIES:
   :CUSTOM_ID: why-does-the-internet-think-that-performance-reviews-dont-work
   :END:

- http://www.growthengineering.co.uk/annual-performance-reviews-dont-work/
- https://www.thebalancecareers.com/performance-appraisals-dont-work-1918846
- https://www.forbes.com/sites/lizryan/2018/01/14/performance-reviews-are-pointless-and-insulting-so-why-do-they-still-exist/#615c36c672d1
- https://www.inc.com/thomas-koulopoulos/performance-reviews-are-dead-heres-what-you-should-do-instead.html
** <2016-03-22> Don't use Wikia
[[http://dizzy.pestermom.com/][KimikoMuffin]]
has [[http://dizzy.pestermom.com/?p=nowikia][some strong reasons for not using Wikia]].

Wikipedia does not own Wikia, but
[[http://money.cnn.com/magazines/business2/business2_archive/2007/03/01/8401010/][who owns Wikipedia also owns Wikia]]:
Jimmy Wales owns a share of Wikipedia and also a share of Wikia.
Whenever you make a Wikia site,
you're working, unpaid, for him and the other owners.
[[http://shouldiworkforfree.com/][Why would you work for free?]]
(By the way, Wikipedia also has its share of unpleasant stories,
but that's for another post.)

An alternative that will give you more freedom
(and ownership, but also more responsibility)
is hosting on your own domain,
but this needs some technical understanding.

The bad news is that Wikia is the leader for niche wikis
and there doesn't seem to be any meaningful [[http://alternativeto.net/software/wikia/][competition]]:
Google search result for niche gaming queries is typically full of Wikia articles.
In the meantime, you can try [[http://www.shoutwiki.com/wiki/Main_Page][Shoutwiki]]
(there's even a wiki named [[http://awa.shoutwiki.com/wiki/Anti-Wikia_Alliance][Anti-Wikia Alliance]]) or
[[http://www.gamepedia.com/][Gamepedia]].
** My tech observations and complaints
*** smartphone politics
- Xiaomi limits hardware profit to 5%? What?
  - [[https://www.reddit.com/r/Android/comments/8k43qo/why_does_xiaomi_limit_its_profits_to_5_youtube/][Why does Xiaomi limit its profits to 5%? - YouTube TechAltar : Android]]
    - Because Xiaomi is a software company, not a hardware company.
- [[https://www.youtube.com/watch?v=OA_g2bQgOXY][How KaiOS Is Becoming the 3rd Major Mobile OS - YouTube]]
  - Much money can be made from selling to poor people (hopefully while also helping them).
    - [[https://hbr.org/2012/06/the-smart-way-to-make-profits][The Smart Way to Make Profits While Serving the Poor]]
*** GIF is video, not image.
- GIF videos must have controls.
- Google should penalize (push down) Pinterest from image search.
  It's littering.
*** Using chat such as IRC/Slack
- I find that most channels are idle.
- There are two kinds of channels: temporary and permanent.
  - Temporary channel is functional. It gathers people for a task/project.
  - Permanent channel is structural. It gathers people in the same tribe/department/structure.
