#+TITLE: Cita-cita politik
#+DATE: 2018-05-18 00:00 +0700
#+PERMALINK: /poliprog.html

* Catatan: semua ini baru ide; masih bisa berubah.

* Hukum

** Prinsip hukum

*** A law must not go against nature.

Banning prostitution does not respect nature.
Banning drugs does not respect nature.

*** A law must be practically enforceable.

Cabut semua aturan yang enforcement-nya tidak praktikal.

*** Regulate; don't ban.

** <2018-09-19> Ganti /retributive justice/ dengan /restorative justice/.

- Siapa yang berwenang mengubah sistem hukum indonesia menjadi restorative justice?
- Bagaimana melobi pihak berwenang?
- Berapa besar usaha yang diperlukan untuk mengubah sistem hukum yang sekarang?
- Bagaimana rencana transisi?

** <2018-09-19> Perjelas bagian UUD yang tidak jelas.

** <2018-09-19> Cabut aturan yang melarang hal-hal yang tidak membahayakan orang banyak.

Cabut aturan yang mengatur urusan pribadi.

** <2018-09-19> Generalize aturan: Kriminalkan semua orang yang mengganggu ketertiban umum?

Problem: Ini bisa jadi pasal karet.

Tidak perlu ada aturan spesifik.
Aturan tentang ketertiban umum mencakup semua hal berikut:
- Membuat video porno tidak kriminal; menyebarkannya yang kriminal.
- Hubungan intim tidak kriminal; yang kriminal adalah membuat masyarakat resah.
- Menghujat tidak kriminal; yang kriminal adalah membuat masyarakat ribut.

** <2018-09-19> Buat aturan contempt of court? Sebaiknya benahi hakim dan pengadilan dulu?

Ide Hotman Paris?

Tapi bagaimana kalau ada miscarriage of justice?
Aturan contempt of court akan memperparah miscarriage of justice.

* Agama

Agama adalah urusan pribadi, bukan urusan negara.

(Ini masih sesuai UUD?)

** <2018-09-19> Akui semua agama, aliran, dan kepercayaan.
Ada sedikitnya 4000 agama/aliran/kepercayaan.

Syiah, Ahmadiyah, Tarekat Naqsabandiyah.

Discordia, Church of the SubGenius, Flying Spaghetti Monster.
*** Sejarah agama
- Agama, yang sekarang besar, awalnya dianggap sesat oleh orang-orang di sekitarnya.
- Pengikut Yesus awalnya dianggap sesat oleh pengikut Yahudi pada zamannya.
- Pengikut Muhammad awalnya dianggap sesat oleh pengikut polytheism Arab pada zamannya.
- Bayangkan seandainya seorang di kampung Anda tiba-tiba mengumumkan suatu agama baru.
- Mengapa kita lebih percaya orang 2000 tahun lalu daripada orang sekarang?
  Mengapa kita berpaku pada masa lalu?
  Mengapa kita tidak berusaha membuat masa depan jadi lebih indah?

** <2018-09-19> Alihkan tugas departemen agama (umrah, naik haji dll.) kepada private sector.

** <2018-09-19> Serahkan pendidikan agama sepenuhnya kepada keluarga.
- Mengganti pelajaran agama di sekolah dengan pelajaran /sejarah/ agama.

** <2018-09-19> Kurangi/tiadakan ekstremisme/radikalisme

*** <2018-09-22> Wajibkan pelajaran sejarah agama

History of Islam?
Is Brigitte Gabriel's [[https://www.youtube.com/watch?v=o0m9nEafBE4][history-of-Islam video]] accurate?

*** Setiap ayat sensitif dalam kitab suci harus disertai tafsir/exegesis/interpretasi dan komentar tentang konteks sejarah turunnya ayat tersebut.
- Terutama Quran karena mayoritas penduduk Indonesia Muslim.
- Kitab suci bisa berupa buku kertas, aplikasi komputer, dll.
- Bagaimana cara mencegah [[https://en.wikipedia.org/wiki/Auto-segregation][WP:Auto-segregation]]?
  Asimilasi vs akulturasi vs absorpsi vs integrasi?
- Apakah efektif?
  Quran terjemahan ekstremis akan tetap saja beredar underground.
  Tapi kebijakan ini mungkin mempengaruhi Muslim moderat yang selama ini complicit atau bahkan diam-diam setuju dengan ekstremis.
- Kita sebaiknya tidak memaksakan/mengatur kepercayaan dengan undang-undang.
- Bagaimana seandainya ada orang mengarang kitab suci sendiri?


* Teknologi

** <2018-09-19> Net neutrality, un-ban websites, Reddit, Vimeo, dll.
Apakah website ekstremis juga mau dibolehkan?

** <2018-09-19> Kuasai infrastruktur Internet

Infrastruktur Internet adalah hajat hidup orang banyak, jadi harusnya dikuasai negara, sesuai pasal 33 ayat 3 UUD 1945.

** <2018-09-21> Benahi keculasan Telkomsel

- Beli paket data di Indonesia Barat; terbang ke Indonesia Tengah; paket data tidak berlaku.
- Simplify pricing.
  Harga paket data harus rata per GB, dan harus sama di semua Indonesia.
  Tidak boleh memahalkan pengguna kecil.
  - Daerah maju mensubsidi daerah tertinggal.
- Cabut iklan sisipan proxy Telkomsel.

* Transportasi, lingkungan, pertanahan, tata kota

- Utamakan pejalan kaki dalam tata kota.

** Solusi kemacetan tol Jakarta?

- Solusi:
  - Pemda DKI, Bogor, Depok, Tangerang, dan Bekasi:
    - Pilihan 1: Membeli jalan tol menjadi jalan umum.
      - Lunasi atau cicil ke pemilik tol.
    - Pilihan 2: Menyewa jalan tol pada jam tertentu menjadi jalan umum.
      - Menaikkan pajak jalan untuk mobil.
        - [[https://en.wikipedia.org/wiki/Road_tax][WP:Road tax]]
        - Ditambah (rata-rata biaya tol) * (jumlah hari dalam setahun)
          - Ditambah Rp 7,200,000 per tahun?
      - Membuka semua pintu tol di Jakarta pada jam sibuk.
        - Kalau tidak bisa buka semua, buka yang paling bikin macet.
      - Membayar ganti rugi ke operator tol.
- Menyelesaikan dua masalah sekaligus:
  - Disinsentif untuk pengguna mobil pribadi.
  - Mengurangi kemacetan karena kelambatan gerbang tol.
- Skenario gagal:
  - Pemda tidak punya cukup uang.
  - Manusia egois.
    - Pemda sekitar DKI tidak mau patungan.
    - Pemilik mobil menolak bayar pajak demi kebaikan bersama.
    - Pemilik tol menolak penawaran karena terlalu serakah.



** TODO <2018-09-17> Gratiskan kendaraan umum bertrayek

- Lebih mudah dan murah daripada integrasi antarmoda?
- Mengurangi trafik dan polusi.

*** <2018-09-19> Biaya yang diperlukan per jam-kendaraan (unit economics)

- Satuan unit economics: 1 jam-kendaraan
- Breakdown
  - Upah
    - 1 kendaraan butuh 2 orang operator (1 supir dan 1 kenek)
    - Upah 1 orang Rp 7 juta/160 jam ~ Rp 50000/jam
  - Bahan bakar
    - Penggunaan bahan bakar (fuel mileage), 5 km/liter, Rp 10000/liter
    - Kecepatan rata-rata 50 km/jam
    - Kendaraan beroperasi 24 jam per hari = 1200 km/hari = 240 liter/hari
  - Biaya perawatan kendaraan Rp ?/bulan
  - Asuransi kesehatan Rp ?/bulan
  - Asuransi kendaraan Rp ?/bulan

*** Potensi masalah dan penolakan

**** Pengemudi ojek, taksi, dan mobil sewa mungkin menolak karena pendapatan mereka mungkin berkurang

- Bantu mereka beralih jadi supir kendaraan umum bertrayek.

*** Negara lain yang sudah berhasil

- [[https://www.youtube.com/watch?v=ccxVYborUcU][Let's Make Mass Transit Free* - YouTube]]
  - Making mass transit free benefits everyone, including those who don't use mass transit.
    Free mass transit reduces traffic.

** <2018-09-22> Jakarta is sinking, unless we stop draining the aquifer below it.

The animation at 1:55 in this [[https://www.youtube.com/watch?v=dNE5aptbGyY][video]] explains why.

- People pump the aquifers out.
- Rain can't replenish the aquifers because Jakarta is wrapped in concrete.
- There is no more underground water to press the land up.
- The land sinks.

North Jakarta is sinking by up to 20 cm per year.

** <2018-09-21> Perbaiki jembatan penyeberangan

<2018-09-21>
Jembatan penyeberangan di Jl. S. Parman Jakarta logamnya mencuat dan ukuran anak tangganya terlalu kecil.

** <2018-09-19> Tertibkan pelacuran, narkoba, dan judi?

Kita jangan munafik.
Hal-hal ini sudah ada sejak manusia ada.
Hal-hal ini tidak bisa dihilangkan.

Solusinya adalah mendidik masyarakat, bukan melarang.
Larangan hanya akan membuat black market.

Laws can't go against human nature.

Masalah: NIMBY.
Mau dilokalisasi di mana?
Tentu di tempat yang sudah ada.
Resmikan tempat yang sudah ada.

Jual narkoba di alfamart/warung?
Atur kemasan harus sama semua.
Tidak boleh iklan.

* Politik

Fix the system; berantas perverse incentive, principal-agent problem, dan conflict of interest.

** Mudahkan pemilu untuk perantau

Pemilu serentak?
Sistem e-ktp nasional?

Pemilu harus ada bukti fisik seperti kertas, tidak boleh sepenuhnya bergantung ke komputer.

** <2018-09-19> Evidence-based legislation? data-driven legislation?

** <2018-09-19> Tertibkan kampanye politik

- membatasi kampanye hanya dalam bentuk prospektus (tertulis) berisi rencana program kerja, seperti yang sedang Anda lihat
- mengumpulkan prospektus dalam satu website
- melarang semua bentuk lain

** <2018-09-19> Larang /lobbying/

Bukannya memang sudah dilarang?

** <2018-09-17> Larang partai membayar anggota; wajibkan anggota membayar partai?

- Berantas politik karir.
- Pastikan bahwa yang masuk adalah orang yang benar-benar peduli politik.
- Tapi kalau begini, politik jadi sampingan.
  Tidak semua orang mau punya 2 pekerjaan.

A party is a mini-country.
Therefore a party should tax its members, not pay its members.

Politics should not be a career path.

* Kesehatan

** Permurah kesehatan?

Mengapa kesehatan mahal?

Mengapa rumah sakit mahal?

** <2018-09-19> Ban buffets/all-you-can-eat restaurants

- Unhealthy. Induces overeating.
- Dishonest pricing.
  - [[https://www.insideedition.com/athlete-banned-all-you-can-eat-sushi-buffet-eating-too-much-46845][Athlete Banned From All-You-Can-Eat Sushi Buffet for Eating Too Much | Inside Edition]]
    - Why do you ban people?
      You know what you sign up for.
      You know everyone's diet is different.
      The eater does nothing wrong.
      If you don't like people eating too much, open a conventional a la carte restaurant.
      Buffets are food casinos.
      Buffets are insurance.
      They are all actuarial.
      It's unfair if you only want the money but don't want the risk.

** <2018-09-19> Bantu petani tembakau dan buruh tembakau cari pekerjaan lain

* Ekonomi

** Prinsip ekonomi

- Mandirikan bangsa.
  Maksimalkan produksi dalam negeri.
  Kemandirian adalah syarat perlu tetapi tidak cukup untuk kedaulatan.

** Kurangi nilai impor.

- Tingkatkan produksi dalam negeri, terutama industri strategis, teknologi.
- Bangun daerah tertinggal, kurangi urbanisasi.

* Survei tanah, konflik agraria, sertifikasi tanah?

* Pendidikan

- Tingkatkan gaji dan mutu guru?

** <2018-09-22> Perbaiki cara mengajar sejarah

- Tidak perlu menghapal hal-hal yang dicari dalam 1 menit di Internet.
- Yang penting ialah memahami sebab/konteks sesuatu terjadi, terutama perang.

** 100% literacy rate; budayakan membaca dan menulis

Jordan Peterson: "The best way to teach people critical thinking is to teach them to write." ([[https://www.youtube.com/watch?v=x0vUsxhMczI][source]])

* Pertanian

** Buat profesi petani jadi menarik secara ekonomi.

* Obtain political power?

** TODO <2018-09-17> Join a think tank or a political party or both?

** TODO <2018-09-17> Educate the people about critical thinking, religion, history, power, and politics?

** TODO <2018-09-22> Own a media company, or piggyback existing media?
