#+TITLE: Understand power
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /power.html
#+OPTIONS: ^:nil toc:nil
* What is power, security, trust, risk, and vulnerability?
Power may be seen as goal, influence, security, capability, status.
 [fn::<2019-04-23> https://en.wikipedia.org/wiki/Power_(international_relations)]
Power is "the capacity of an individual to influence the conduct (behaviour) of others"
 [fn::<2019-04-23> https://en.wikipedia.org/wiki/Power_(social_and_political)].

Nietzsche:
"What is happiness? The feeling that power increases—that a resistance is overcome."
 [fn::https://en.wikipedia.org/wiki/Paradox_of_hedonism]

"To exploit someone is to take unfair advantage of them."\cite{sep-exploitation}
** What is security?
** What is vulnerability?
Trust is the assumption that others will not exploit our vulnerabilities.

Everything is vulnerable.
Vulnerabilities differ in their probability and the severity, and thus their expected damages.
We protect our houses with gates to deter thieves.
But we don't protect our houses against meteors.
Meteors do more damage than thieves, but meteors are so rare that the expected damage of thieves exceeds the expected damage of meteors.
We probabilistically reason that thieves are more risky than meteors.
** Power
We assume these primitive concepts: harm, violence.
*** How do we design a power literacy course?
If I ask you to wave your hand, will you do that?
By following what I tell you, you have given me some power over you.
Why do you give me power?
Why do you let me control?

If I ask you to bark like a dog for $10, will you do that?

If I ask you to dig coal for $50,000 a year, will you do that?
If I ask you to drill the Earth for oil for $50,000 a year, will you do that?
What if I give you more money?

If I ask you to cut down a forest for $50,000 a year, will you do that?
Somebody out there will do that.

You see, there is a common theme:
you /let/ others tell you what to do.

Rich people can only give you money.
They don't cut down the trees themselves.

Why do we let others tell us what to do?
Because they pay?

Why do we let money bend our will?
*** What is power?
Power is control.

The amount of power X has over Y is the amount of control X has over Y.

Power is the ability to harm.

Power is the potential to do violence.

To have power is to control.
We say that /X has power over Y/ to mean /X controls Y/.
*** Why distribute power?
Keltner's paradox of power is a strong scientific reason for distributing power.
 [fn::Dacher Keltner, Ph.D. - "The Power Paradox: How We Gain and Lose Influence" (05/19/16) https://www.youtube.com/watch?v=HS9VHBlYklc]

Feeling powerful reduces morality and inhibition.

Feeling powerless causes chronic stress.
*** Power and control?
*** Power is the flip side of trust?
*** How does one gain power?
By gaining trust.

X can have power over Y if and only if Y /lets/ X have power over Y.

Employers control employees because employees /let/ employers.

Government controls the governed because the governed /let/ the government.

Gain power by sharing it?[fn::"How do humans gain power? By sharing it" https://www.youtube.com/watch?v=j2XpiVrUWog]

Now we understand where power comes from.
Evil people have power because we /let/ them.
How do we let them?

By being employed by them to perpetuate their evil.
Rich people are not destroying the environment.
/We/, their employees, are destroying the environment, by doing what they want us to do.
We, the coal miners.
We, the power plant operators.
We, the car sellers.
/We are complicit/.
We /let/ them control us.
It is our hands, the workers' hands, not the rich people's hands, who murder the kids, who launches the missiles.

/All rich people can do is give us money./
If we accept that money and we do evil, then we ourselves are at fault.

Companies and rich people are not to blame.
We the complicit majority are to be blame.
We are sleepwalking.
We are not aware of our own power.
We have power but we are afraid to use it.

But even if we are not complicit, those rich people will just buy machines and destroy the environment anyway?
Therefore they are truly immoral?
Why do they take pride in short-term profit maximization?
Who taught them?

Government must come from the people.
US government is for the rich only, not for the people.
The candidates are rich people.
The government listens only to rich people.
The government does what is good for rich people.
There is never a grassroot candidate.

But we have to feed our families.
Where do we get money?
This is the wrong question.
The question is: How do we feed our families?
/We/ can farm ourselves.
We feed them directly from our own labor.
Nature always gives to those who work, to those who hunt, gather, or farm.
Nature does not discriminate.
Only in nature, those who do not work do not eat.
A seed does not care about the color of the hand that sows it.
*** Where does one get power?
From nature.
Some of us grow to be strong and healthy people, by virtue of good genetics, good habit, and good nourishment.
*** How does one lose power?
By losing trust.
** Risk
Related words: danger, hazard, chance, gamble, probability, uncertainty, contingency.

(We are resisting the temptation of digressing to probability theory and statistics.)
*** What is risk?
Did Warren Buffett say that risk comes from not understanding what we are doing?

Risk comes from Italian "riscare" which means "to run into danger".[fn::https://www.etymonline.com/word/risk]

Risk is danger.

Danger is something that may harm.

Risk has negative connotation.
*** What is hazard?
"Hazard" was the name of a game of chance played with dice[fn::https://www.etymonline.com/word/hazard].
In 2019, "hazard" means danger.
*** What is chance?
*** Is it absurd to buy or build things that we hope to never have to use?
Insurance buyers hope to never have to use it, because having to use it means shit has happened.
We hope that shit doesn't happen.
When you buy a scissor, you expect to use it.
Insurance is the only thing that you buy but hope to never have to use it.

If I buy a gun, I hope to never have to use it.

If I buy a fire extinguisher, I hope to never have to use it.
Is it absurd for me to buy a fire extinguisher?

We hope that we never have to use atomic bombs.

Having to use an insurance or a gun means that something bad has happened.
We don't want bad things to happen.

https://www.reddit.com/r/AskReddit/comments/3uc06v/what_is_something_youd_buy_but_hope_to_never_use/
** Trust
*** Measuring trust between countries
**** The power of a country's passport tells how great that country is
https://www.passportindex.org/byRank.php

Your passport's power is proportional to how much the world trusts your country.
*** What is trust?
*** How little trust can we live with?
When I walk around the town, I tacitly assume that nobody will suddenly stab me with a knife.

** Contract is trust/distrust?
Signing a contract that obliges you is trusting.

Signing a contract that gives you a right is distrusting.

We make a contract because we want the state to help us when the other party breaches the contract.
Thus we make a contract because we distrust the other party.

Contracts reduces the amount of trust required for trade.

If the state did not exist, would we still make contracts?
We would rely on honor, and not the state.

But underlying every contract is the assumption that the state is honorable.

Contract assumes a third-party enforcer that is powerful and honorable (just, fair, neutral, reliable).

* How does power get centralized?
** Weapons and oppression
- Weapons enhance our ability to kill.
  - Weapons enhance our ability to scare.
  - Thus weapons enables better-armed people to oppress worse-armed people.
- Order of magnitude of weapon effectiveness
  - With a blade, one person can subdue 1 unarmed person.
  - With a pistol, one person can subdue 10 unarmed people.
  - With a machine gun, one person can subdue 100 unarmed people.
  - With a bomb such as that in Oklahoma city bombing, one person can subdue 1,000 unarmed people.
  - With a nuclear bomb such as those dropped by the USA on Hiroshima and Nagasaki during World War 2, one person can subdue 1,000,000 unarmed people.
- Order of magnitude of media deception effectiveness?
  - This is totally baseless.
    How do we estimate this?
  - With hearsay, one person can deceive ten people?
  - With paper, one person can deceive a hundred people?
  - With newspaper or WhatsApp, one person can deceive a million people?
  - With television or Facebook or Google, one person can deceive a hundred million people?
- The only way for the oppressed to fight back is:
  - total guerrilla warfare
  - living near to the oppressor (so that he can't nuke)
  - terrorism
    - Is there really no other way?
      Dialogs?
      Referendums?

What prevents violence is the ability to retaliate with comparable violence.
What prevents oppression is the ability to retaliate for that oppression.

NUKEMAP: nuclear explosion damage calculator
https://nuclearsecrecy.com/nukemap/
** Ownership, property
*** Why do people give up their power so easily?
*** How do we live in a society whose morality goes against ours?
How do we live in a society whose morality clashes with our morality,
without demeaning the people that we think are immoral?
How do we live morally but without self-righteousness?
*** If we need to be evil to change something evil, should we be evil?
*** Should we do the necessary evil?
If we believe that power should be distributed,
but we need power to change the world,
should we temporarily (~ 100 years) centralize power on us?
Can we trust ourselves, as power tends to corrupt?
*** Legal fictions?
Philosophically-unsound legal fictions such as corporate personhood create unnecessary misery.

Litigation is part of the problem, not part of the solution.
Justice should at least be restorative.

Problem:
"That’s why if your toaster explodes, you have to sue the company that makes the toaster.
You can’t sue the company’s shareholders.
The company and its shareholders are distinct legal persons, with different legal rights and duties."[fn::https://www.sfchronicle.com/opinion/article/Corporate-personhood-actually-limits-12721448.php]

How would the combination of restorative justice and no-corporation handle exploding toasters?
What is the anarchist approach to litigating one who makes an exploding toaster that hurts someone else?

"If Corporations Are People, They Should Act Like It"[fn::https://www.theatlantic.com/politics/archive/2015/02/if-corporations-are-people-they-should-act-like-it/385034/]

Both governments and corporations are part of the problem.

Anarchy is a /privilege/.
Freedom is expensive.
*** Capitalism does not benefit us; free trade does?
*** Legal system is part of the problem.
Nobody knows all laws that are in effect.
Not the legislators.
Not the judges.
*** Parallels between master-slave and lessor-lessee
"Slaves could not own property, but their masters often let them save up to purchase their freedom,[97] and records survive of slaves operating businesses by themselves,
making only a fixed tax-payment to their masters."[fn::https://en.wikipedia.org/w/index.php?title=Slavery_in_ancient_Greece&oldid=881609681]

That sounds very much like the relationship between a lessee (tenant/renter) and a lessor (landlord).
A lessee practically will never have enough money to buy the lessor's property;
the economic system guarantees that.
For example, in 2019, my neighbor is asking IDR 3 billion for his 72-m2 land and house on it.
A typical frugal man who saves IDR 3 million monthly salary will need to save for 83 years, assuming over-optimistically zero inflation.
He would have died 20 years before he had saved enough to buy the house!

In principle slavery has been abolished, but in practice the economic system guarantees that most people will forever live mediocre lives,
although in much better condition than that of ancient Roman slaves.
But we can do better.
*** What is ownership?
*** What is property?
*** What is slavery?
Slavery is the treatment of human as non-human property.
Slavery is humans' owning humans.

Slavery violates the silver rule (do not do unto others what you do not want to be done unto yourself).
*** If everybody needs to eat, why aren't farmers the richest people on Earth?
Food has been the best-selling thing for 40,000 years,
but why aren't farmers the richest people on Earth?

Here's a thought experiment that leads me to that question.

Imagine an economy that consists of 1 extremely frugal farmer and 1 doctor.
After some time, money accumulates at the farmer,
because the doctor always needs to eat, but the farmer doesn't always have a health problem.

A government has these options, from the least coercive to the most coercive:
- Do nothing, and hope that the farmer donates his money to the doctor.
- Create more money and give it to the doctor.
  But the farmer may think that this is unfair.
- Tax the farmer and give that tax money to the doctor.
- Force the farmer to spend his money on the doctor.

The current economic system suffers from money accumulation.

Is accumulation of money bad?
Is inequality bad?
*** What is ownership?
What does owning something mean?
*** What is property?
Is property theft?
*** If everyone owned a piece of fertile land, poverty should not exist?
** Work, employment
*** We should not conflate work and employment
Work gives life meaning.

Employment is subjugation.
X employs Y because X has a better idea about what Y should do with Y's time in order to make more profits for X.

Some people are lucky enough to have their work coincide with their employment.
They are lucky enough to be enslaved to do what they want to do anyway.
*** Dangerous freedom vs comfortable slavery?
Would we rather live free but hard,
or would we rather be comfortable in an enslavement by a good master who can give us more than we could get in a free life?
/But how could this master have so much money to pay everybody in the first place?/
*** What is work without employment?
Work without subjugation.
Work without power asymmetry.

Work gives life meaning.
We like work and dislike employment.
We want a world in which we work because we want to, not because we have to.

What is work?
Work is purposeful deed/action.
The difference between work and leisure is teleological.
What is employment?

Life /is/ work.
Your work defines you.
You are only as good as your contribution to the world.
Your work defines the meaning of your life.

Don't confuse working with employment.
Work is everything that creates value.
Employment is subjugation.

- How does employment and slavery compare?

  - Slavery is the ownership of humans.
  - Employment is the rental of humans.
  - How has slavery changed?

    - Humans used to buy humans. Now humans rent other humans.

      - 2018: we can even rent a friend.

    - [[https://www.reddit.com/r/LateStageCapitalism/comments/68fkek/in_slavery_you_are_boughtin_capitalism_you_are/][r/LateStageCapitalism: In slavery, you are bought--in capitalism, you are rented]]
    - "Hiring" /is/ "renting".

      - You rent a car. The contract includes an insurance. You use the car for anything; just don't break it.
      - You hire an employee. The contract includes an insurance. You use the employee for anything; just don't break it.

    - [[http://www.differencebetween.net/business/difference-between-labor-and-human-capital/][differencebetween.net: labor and human capital]]
*** Work
**** Work vs employment
Work is purposeful deed.

Employment is subjugation.
**** Raising kids while working?
It is impractical to raise kids while working, but not while being employed.

My guess of division of labor in stone age:
Able men and childless women find food.
Women and old men raise children.

In stone age there are no 8-hour work days.
Men work only as much as needed to live that day.
The rest is free time: sleep, play, art, sex, rough-and-tumble, musing, thinking
*** Labor without hiring?
By hiring I mean employment/wage/salary.

I'm thinking about anarchistic labor, a form of voluntary labor that is not subject to labor laws.
Get paid by result not by time.
Work anywhere.
Resign anytime.
No non-competes, no non-disclosures, no grace periods.
Work on something ethical and meaningful.
** How did we get into this unholy combination of statism and capitalism, and what is so bad about it?
*** States make wars somewhat less often but much more severe
A war between two tribes kills about 100 people.
A war between two 11th-century kingdoms[fn::https://en.wikipedia.org/wiki/List_of_countries_by_population_in_1000] kills about 100,000 people.
A war between two 20th-century states kills about 1,000,000 people.
A war between two 20th-century state-alliances kills about 70,000,000 people.
A war between two planetary governments may kill billions of people.
This does not yet count the people hurt but not killed by the war.

Hypothesis: the expected damage of wars is constant.
A war between two kingdoms is 1,000 times less likely but 1,000 times more destructive than a war between two tribes.
For example, if a tribe went to war every day, then a kingdom would go to war every 3 years.
But Harrison and Wolf 2012 \cite{harrison2012frequency} falsifies that hypothesis.

States enable long-term peace with the risk of occasional catastrophic wars.

A catastrophe is too high a price to pay.

https://en.wikipedia.org/wiki/List_of_wars_by_death_toll

The frequency reduction is not because have become more peace-loving,
but because each war destroys more, so we take more time to recover for the next war.
*** A society with too many rights cannot progress
Copyright, patent, intellectual property.

We don't need copyright, patent, etc.
Inventors will still invent without patents.
They are intrinsically motivated.

* Weapon
There are several points of view:
- weapon as deterrent
- weapon as power multiplier
* Law
** The ideal law enforcement
- Describe the case to a computer (such as a Prolog program).
- The computer suggests relevant laws.
  The judge still makes the final decision though.
  The judge uses restorative justice.
** what
- There is something above the law: violence, that is, power, that is, human nature.
  - Law is whatever people fear.
  - Power is the ability to do violence (bodily harm).
  - Weapon is power multiplier.
    Weapon multiplies the ability to do violence.
  - People who are above the law are above the law because they have more power than the police.
    Example of those people are extremely rich people, including big corruptors.
    Such powerful people have enough money to do more violence than the police can do.
  - Religious demonstrators are above the law because they can do more violence than the police can do.
    - The police must develop non-lethal crowd-control weapons.
- Law requires the ability to do violence.
- Law isn't about truth.
  Law has never been about truth.
  Philosophy is about truth.
- Modern law is about /provability/.
  - Since when? Since "habeas corpus"?
    - [[https://en.wikipedia.org/wiki/Habeas_corpus][WP:Habeas corpus]]
  - Is law a formal system that can do arithmetic?
    - What are the consequences of Gödel's incompleteness theorems to law?
      - There are true but unprovable things?
  - Is testimony acceptable?
  - [[https://en.wikipedia.org/wiki/Prima_facie][WP:Prima facie]]
  - [[https://en.wikipedia.org/wiki/Burden_of_proof_(law)][WP:Legal burden of proof]], onus probandi
    - "In a legal dispute, one party is initially presumed to be correct and gets the benefit of the doubt,
      while the other side bears the burden of proof."
    - "When a party bearing the burden of proof meets its burden, the burden of proof switches to the other side."
  - It is better to wrongly acquit than to wrongly convict?
    - [[https://www.independent.co.uk/news/uk/home-news/its-better-that-10-guilty-men-go-free-than-one-innocent-man-be-wrongly-convicted-944059.html][It's better that 10 guilty men go free than one innocent man be wrongly convicted]]
  - [[https://en.wikipedia.org/wiki/Truth][WP:Truth]]
  - [[https://en.wikipedia.org/wiki/Proof_theory][WP:Proof theory]]
  - [[https://en.wikipedia.org/wiki/Provability_logic][WP:Provability logic]]
- Enforceability is important.
  An unenforceable law practically doesn't exist.
  - This is why government requires the employer to withhold employee income tax.
    This is why the employee doesn't pay the income tax directly.
    - There are much fewer employees than employees.
    - It's easier to arrest employers than employees.
- Ontology
  - complain, complainant, plaintiff
  - defend, defendant, suspect, convict, felon, recidivist
  - litigation, litigant, legal battle
  - injunction
  - advocate, attorney, barrister, lawyer
  - judge, jury
  - precedent
  - penalty
  - crime
  - justice
    - retributive vs restorative justice
    - [[https://assets.justice.vic.gov.au/njc/resources/c4518c8a-c200-4623-afd1-42e255b62cf9/01+an+overview+of+restorative+justice.pdf][2005, Daniel W. Van Ness, "An overview of restorative justice around the world"]]
  - witness, testimony
  - slightly meta-legal concepts
    - obstruction of justice
    - contempt of court
- Computerization of law
  - Law is first-order logic? It should be computerizable?
  - Legal ontology?
  - Legal information system?
  - Legal search engine?
  - [[https://en.wikipedia.org/wiki/Computer-assisted_legal_research][WP:Computer-assisted legal research]]
  - [[https://www.legalrobot.com/blog/2016/05/25/Ontologies/][How Legal Robot works: Legal Ontologies]], 3-minute reading
    - LKIF (Legal Knowledge Interchange Format)
- Overview
  - [[https://en.wikipedia.org/wiki/Law][WP:Law]]
  - [[https://en.wikipedia.org/wiki/Crime][WP:Crime]]
- [[https://en.wikipedia.org/wiki/Counterclaim][WP:Counterclaim]]
- Legal abuse
  - [[https://en.wikipedia.org/wiki/Legal_abuse][WP:Legal abuse]]
  - [[https://en.wikipedia.org/wiki/Frivolous_litigation][WP:Frivolous litigation]]
  - [[https://en.wikipedia.org/wiki/Vexatious_litigation][WP:Vexatious litigation]]
    - [[https://en.wikipedia.org/wiki/Patent_troll][WP:Patent troll]]
  - [[https://en.wikipedia.org/wiki/Strategic_lawsuit_against_public_participation][WP:Strategic lawsuit against public participation]]
  - [[https://en.wikipedia.org/wiki/Chilling_effect][WP:Chilling effect]]
- [[http://www.tht.org.uk/myhiv/Telling-people/Law/How-do-you-prove-it_qm_][How do you prove HIV transmission?]]
  - "Sometimes, the person who complains to the police after recently testing as HIV positive turns out to have infected the person they are accusing."
- Who pay the cost of litigation?
- classifications
  - criminal acts
    - offense, wrongdoing
    - misdemeanor
    - felony
  - legal systems
    - common law system, case law
    - civil law system, statutory law
  - parts of law
    - civil law
    - criminal law
  - crimes
    - assault
    - battery
    - perjury
    - theft
    - murder
    - rape
    - etc.
- Can the defendant also be a witness?
- Can't we simply ask the defendant "Did you do it?"?
- [[https://en.wikipedia.org/wiki/Hitchens%27s_razor][WP:Hitchens's razor]]
  - "What can be asserted without evidence can be dismissed without evidence"
- Maritime law
  - [[https://en.wikipedia.org/wiki/General_average][WP:General average]]
- legal loopholes, programming errors
  - [[https://mentalfloss.com/article/83439/perfect-crime-may-be-possible-yellowstone-park][The Perfect Crime May Be Possible in Yellowstone Park | Mental Floss]]
** Handling lawyers
If you don't know, don't act like you know.

Watch out for baits.
Don't be greedy.

- Risky stuffs
  - [[https://www.reddit.com/r/IAmA/comments/ajsih/i_am_the_guy_who_owned_mikerowesoftcom_ama/c0hy3d8/][I am the guy who owned MikeRoweSoft.com. AMA : IAmA]]
** Making good laws
Good laws satisfactorily answers:

- How are we going to enforce it?
- What is the worst that haters can do?
- What questions might arise?
- What undefined cases?

Good laws:

- Can be enforced practically (sane effort and cost)
- Addresses the root cause of the problem
- Minimizes unintended effects (is well-targeted)
- Is complete (handle all cases) and Leaves no questions
- Is timeless/future-proof (doesn't depend on time) (is this even possible?)

People are creative.
They will find ways around laws.

Questionable example: even-odd car license plate rule.
If cars are cheap, then people will just buy two cars.
The root cause of the problem is bad/expensive/unintegrated public transport.

Bad example: legislating morality.
Are you going to visit each of the 100 million homes and install a camera?
* Bibliography
