#+TITLE: Get more power
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /power.html
#+OPTIONS: ^:nil toc:nil
* Understand power
- https://en.wikipedia.org/wiki/Power_(international_relations)
- https://en.wikipedia.org/wiki/Power_(social_and_political)

Nietzsche:
"What is happiness? The feeling that power increases—that a resistance is overcome."
 [fn::https://en.wikipedia.org/wiki/Paradox_of_hedonism]
** Understand money
We can think of money as seed and human as soil.
Some humans are fertile soils for money to grow.
A poor person who wins a lottery soon loses all of it.
A rich person who wins a lottery keeps getting richer.
A fool and his money are soon parted.
However, this way of thinking puts money first and human second.

We can think of how fast money flows through a person.
** What is power, security, trust, risk, and vulnerability?
"To exploit someone is to take unfair advantage of them."\cite{sep-exploitation}
*** What is security?
*** What is vulnerability?
Trust is the assumption that others will not exploit our vulnerabilities.

Everything is vulnerable.
Vulnerabilities differ in their probability and the severity, and thus their expected damages.
We protect our houses with gates to deter thieves.
But we don't protect our houses against meteors.
Meteors do more damage than thieves, but meteors are so rare that the expected damage of thieves exceeds the expected damage of meteors.
We probabilistically reason that thieves are more risky than meteors.
*** Power
We assume these primitive concepts: harm, violence.
**** How do we design a power literacy course?
If I ask you to wave your hand, will you do that?
By following what I tell you, you have given me some power over you.
Why do you give me power?
Why do you let me control?

If I ask you to bark like a dog for $10, will you do that?

If I ask you to dig coal for $50,000 a year, will you do that?
If I ask you to drill the Earth for oil for $50,000 a year, will you do that?
What if I give you more money?

If I ask you to cut down a forest for $50,000 a year, will you do that?
Somebody out there will do that.

You see, there is a common theme:
you /let/ others tell you what to do.

Rich people can only give you money.
They don't cut down the trees themselves.

Why do we let others tell us what to do?
Because they pay?

Why do we let money bend our will?
**** What is power?
Power is control.

The amount of power X has over Y is the amount of control X has over Y.

Power is the ability to harm.

Power is the potential to do violence.

To have power is to control.
We say that /X has power over Y/ to mean /X controls Y/.
**** Why distribute power?
Keltner's paradox of power is a strong scientific reason for distributing power.
 [fn::Dacher Keltner, Ph.D. - "The Power Paradox: How We Gain and Lose Influence" (05/19/16) https://www.youtube.com/watch?v=HS9VHBlYklc]

Feeling powerful reduces morality and inhibition.

Feeling powerless causes chronic stress.
**** Power and control?
**** Power is the flip side of trust?
**** How does one gain power?
By gaining trust.

X can have power over Y if and only if Y /lets/ X have power over Y.

Employers control employees because employees /let/ employers.

Government controls the governed because the governed /let/ the government.

Gain power by sharing it?[fn::"How do humans gain power? By sharing it" https://www.youtube.com/watch?v=j2XpiVrUWog]

Now we understand where power comes from.
Evil people have power because we /let/ them.
How do we let them?

By being employed by them to perpetuate their evil.
Rich people are not destroying the environment.
/We/, their employees, are destroying the environment, by doing what they want us to do.
We, the coal miners.
We, the power plant operators.
We, the car sellers.
/We are complicit/.
We /let/ them control us.
It is our hands, the workers' hands, not the rich people's hands, who murder the kids, who launches the missiles.

/All rich people can do is give us money./
If we accept that money and we do evil, then we ourselves are at fault.

Companies and rich people are not to blame.
We the complicit majority are to be blame.
We are sleepwalking.
We are not aware of our own power.
We have power but we are afraid to use it.

But even if we are not complicit, those rich people will just buy machines and destroy the environment anyway?
Therefore they are truly immoral?
Why do they take pride in short-term profit maximization?
Who taught them?

Government must come from the people.
US government is for the rich only, not for the people.
The candidates are rich people.
The government listens only to rich people.
The government does what is good for rich people.
There is never a grassroot candidate.

But we have to feed our families.
Where do we get money?
This is the wrong question.
The question is: How do we feed our families?
/We/ can farm ourselves.
We feed them directly from our own labor.
Nature always gives to those who work, to those who hunt, gather, or farm.
Nature does not discriminate.
Only in nature, those who do not work do not eat.
A seed does not care about the color of the hand that sows it.
**** Where does one get power?
From nature.
Some of us grow to be strong and healthy people, by virtue of good genetics, good habit, and good nourishment.
**** How does one lose power?
By losing trust.
*** Risk
Related words: danger, hazard, chance, gamble, probability, uncertainty, contingency.

(We are resisting the temptation of digressing to probability theory and statistics.)
**** What is risk?
Did Warren Buffett say that risk comes from not understanding what we are doing?

Risk comes from Italian "riscare" which means "to run into danger".[fn::https://www.etymonline.com/word/risk]

Risk is danger.

Danger is something that may harm.

Risk has negative connotation.
**** What is hazard?
"Hazard" was the name of a game of chance played with dice[fn::https://www.etymonline.com/word/hazard].
In 2019, "hazard" means danger.
**** What is chance?
**** Is it absurd to buy or build things that we hope to never have to use?
Insurance buyers hope to never have to use it, because having to use it means shit has happened.
We hope that shit doesn't happen.
When you buy a scissor, you expect to use it.
Insurance is the only thing that you buy but hope to never have to use it.

If I buy a gun, I hope to never have to use it.

If I buy a fire extinguisher, I hope to never have to use it.
Is it absurd for me to buy a fire extinguisher?

We hope that we never have to use atomic bombs.

Having to use an insurance or a gun means that something bad has happened.
We don't want bad things to happen.

https://www.reddit.com/r/AskReddit/comments/3uc06v/what_is_something_youd_buy_but_hope_to_never_use/
*** Trust
**** Measuring trust between countries
***** The power of a country's passport tells how great that country is
https://www.passportindex.org/byRank.php

Your passport's power is proportional to how much the world trusts your country.
**** What is trust?
**** How little trust can we live with?
When I walk around the town, I tacitly assume that nobody will suddenly stab me with a knife.

*** Contract is trust/distrust?
Signing a contract that obliges you is trusting.

Signing a contract that gives you a right is distrusting.

We make a contract because we want the state to help us when the other party breaches the contract.
Thus we make a contract because we distrust the other party.

Contracts reduces the amount of trust required for trade.

If the state did not exist, would we still make contracts?
We would rely on honor, and not the state.

But underlying every contract is the assumption that the state is honorable.

Contract assumes a third-party enforcer that is powerful and honorable (just, fair, neutral, reliable).

** How does power get centralized?
*** Weapons and oppression
- Weapons enhance our ability to kill.
  - Weapons enhance our ability to scare.
  - Thus weapons enables better-armed people to oppress worse-armed people.
- Order of magnitude of weapon effectiveness
  - With a blade, one person can subdue 1 unarmed person.
  - With a pistol, one person can subdue 10 unarmed people.
  - With a machine gun, one person can subdue 100 unarmed people.
  - With a bomb such as that in Oklahoma city bombing, one person can subdue 1,000 unarmed people.
  - With a nuclear bomb such as those dropped by the USA on Hiroshima and Nagasaki during World War 2, one person can subdue 1,000,000 unarmed people.
- Order of magnitude of media deception effectiveness?
  - This is totally baseless.
    How do we estimate this?
  - With hearsay, one person can deceive ten people?
  - With paper, one person can deceive a hundred people?
  - With newspaper or WhatsApp, one person can deceive a million people?
  - With television or Facebook or Google, one person can deceive a hundred million people?
- The only way for the oppressed to fight back is:
  - total guerrilla warfare
  - living near to the oppressor (so that he can't nuke)
  - terrorism
    - Is there really no other way?
      Dialogs?
      Referendums?

What prevents violence is the ability to retaliate with comparable violence.
What prevents oppression is the ability to retaliate for that oppression.

NUKEMAP: nuclear explosion damage calculator
https://nuclearsecrecy.com/nukemap/
*** Ownership, property
**** Why do people give up their power so easily?
**** How do we live in a society whose morality goes against ours?
How do we live in a society whose morality clashes with our morality,
without demeaning the people that we think are immoral?
How do we live morally but without self-righteousness?
**** If we need to be evil to change something evil, should we be evil?
**** Should we do the necessary evil?
If we believe that power should be distributed,
but we need power to change the world,
should we temporarily (~ 100 years) centralize power on us?
Can we trust ourselves, as power tends to corrupt?
**** Legal fictions?
Philosophically-unsound legal fictions such as corporate personhood create unnecessary misery.

Litigation is part of the problem, not part of the solution.
Justice should at least be restorative.

Problem:
"That’s why if your toaster explodes, you have to sue the company that makes the toaster.
You can’t sue the company’s shareholders.
The company and its shareholders are distinct legal persons, with different legal rights and duties."[fn::https://www.sfchronicle.com/opinion/article/Corporate-personhood-actually-limits-12721448.php]

How would the combination of restorative justice and no-corporation handle exploding toasters?
What is the anarchist approach to litigating one who makes an exploding toaster that hurts someone else?

"If Corporations Are People, They Should Act Like It"[fn::https://www.theatlantic.com/politics/archive/2015/02/if-corporations-are-people-they-should-act-like-it/385034/]

Both governments and corporations are part of the problem.

Anarchy is a /privilege/.
Freedom is expensive.
**** Capitalism does not benefit us; free trade does?
**** Legal system is part of the problem.
Nobody knows all laws that are in effect.
Not the legislators.
Not the judges.
**** Parallels between master-slave and lessor-lessee
"Slaves could not own property, but their masters often let them save up to purchase their freedom,[97] and records survive of slaves operating businesses by themselves,
making only a fixed tax-payment to their masters."[fn::https://en.wikipedia.org/w/index.php?title=Slavery_in_ancient_Greece&oldid=881609681]

That sounds very much like the relationship between a lessee (tenant/renter) and a lessor (landlord).
A lessee practically will never have enough money to buy the lessor's property;
the economic system guarantees that.
For example, in 2019, my neighbor is asking IDR 3 billion for his 72-m2 land and house on it.
A typical frugal man who saves IDR 3 million monthly salary will need to save for 83 years, assuming over-optimistically zero inflation.
He would have died 20 years before he had saved enough to buy the house!

In principle slavery has been abolished, but in practice the economic system guarantees that most people will forever live mediocre lives,
although in much better condition than that of ancient Roman slaves.
But we can do better.
**** What is ownership?
**** What is property?
**** What is slavery?
Slavery is the treatment of human as non-human property.
Slavery is humans' owning humans.

Slavery violates the silver rule (do not do unto others what you do not want to be done unto yourself).
**** If everybody needs to eat, why aren't farmers the richest people on Earth?
Food has been the best-selling thing for 40,000 years,
but why aren't farmers the richest people on Earth?

Here's a thought experiment that leads me to that question.

Imagine an economy that consists of 1 extremely frugal farmer and 1 doctor.
After some time, money accumulates at the farmer,
because the doctor always needs to eat, but the farmer doesn't always have a health problem.

A government has these options, from the least coercive to the most coercive:
- Do nothing, and hope that the farmer donates his money to the doctor.
- Create more money and give it to the doctor.
  But the farmer may think that this is unfair.
- Tax the farmer and give that tax money to the doctor.
- Force the farmer to spend his money on the doctor.

The current economic system suffers from money accumulation.

Is accumulation of money bad?
Is inequality bad?
**** What is ownership?
What does owning something mean?
**** What is property?
Is property theft?
**** If everyone owned a piece of fertile land, poverty should not exist?
*** Work, employment
**** We should not conflate work and employment
Work gives life meaning.

Employment is subjugation.
X employs Y because X has a better idea about what Y should do with Y's time in order to make more profits for X.

Some people are lucky enough to have their work coincide with their employment.
They are lucky enough to be enslaved to do what they want to do anyway.
**** Dangerous freedom vs comfortable slavery?
Would we rather live free but hard,
or would we rather be comfortable in an enslavement by a good master who can give us more than we could get in a free life?
/But how could this master have so much money to pay everybody in the first place?/
**** What is work without employment?
Work without subjugation.
Work without power asymmetry.

Work gives life meaning.
We like work and dislike employment.
We want a world in which we work because we want to, not because we have to.

What is work?
Work is purposeful deed/action.
The difference between work and leisure is teleological.
What is employment?

Life /is/ work.
Your work defines you.
You are only as good as your contribution to the world.
Your work defines the meaning of your life.

Don't confuse working with employment.
Work is everything that creates value.
Employment is subjugation.

- How does employment and slavery compare?

  - Slavery is the ownership of humans.
  - Employment is the rental of humans.
  - How has slavery changed?

    - Humans used to buy humans. Now humans rent other humans.

      - 2018: we can even rent a friend.

    - [[https://www.reddit.com/r/LateStageCapitalism/comments/68fkek/in_slavery_you_are_boughtin_capitalism_you_are/][r/LateStageCapitalism: In slavery, you are bought--in capitalism, you are rented]]
    - "Hiring" /is/ "renting".

      - You rent a car. The contract includes an insurance. You use the car for anything; just don't break it.
      - You hire an employee. The contract includes an insurance. You use the employee for anything; just don't break it.

    - [[http://www.differencebetween.net/business/difference-between-labor-and-human-capital/][differencebetween.net: labor and human capital]]
**** Work
***** Work vs employment
Work is purposeful deed.

Employment is subjugation.
***** Raising kids while working?
It is impractical to raise kids while working, but not while being employed.

My guess of division of labor in stone age:
Able men and childless women find food.
Women and old men raise children.

In stone age there are no 8-hour work days.
Men work only as much as needed to live that day.
The rest is free time: sleep, play, art, sex, rough-and-tumble, musing, thinking
**** Labor without hiring?
By hiring I mean employment/wage/salary.

I'm thinking about anarchistic labor, a form of voluntary labor that is not subject to labor laws.
Get paid by result not by time.
Work anywhere.
Resign anytime.
No non-competes, no non-disclosures, no grace periods.
Work on something ethical and meaningful.
*** How did we get into this unholy combination of statism and capitalism, and what is so bad about it?
**** States make wars somewhat less often but much more severe
A war between two tribes kills about 100 people.
A war between two 11th-century kingdoms[fn::https://en.wikipedia.org/wiki/List_of_countries_by_population_in_1000] kills about 100,000 people.
A war between two 20th-century states kills about 1,000,000 people.
A war between two 20th-century state-alliances kills about 70,000,000 people.
A war between two planetary governments may kill billions of people.
This does not yet count the people hurt but not killed by the war.

Hypothesis: the expected damage of wars is constant.
A war between two kingdoms is 1,000 times less likely but 1,000 times more destructive than a war between two tribes.
For example, if a tribe went to war every day, then a kingdom would go to war every 3 years.
But Harrison and Wolf 2012 \cite{harrison2012frequency} falsifies that hypothesis.

States enable long-term peace with the risk of occasional catastrophic wars.

A catastrophe is too high a price to pay.

https://en.wikipedia.org/wiki/List_of_wars_by_death_toll

The frequency reduction is not because have become more peace-loving,
but because each war destroys more, so we take more time to recover for the next war.
**** A society with too many rights cannot progress
Copyright, patent, intellectual property.

We don't need copyright, patent, etc.
Inventors will still invent without patents.
They are intrinsically motivated.

** Weapon
There are several points of view:
- weapon as deterrent
- weapon as power multiplier
** Law
*** The ideal law enforcement
- Describe the case to a computer (such as a Prolog program).
- The computer suggests relevant laws.
  The judge still makes the final decision though.
  The judge uses restorative justice.
*** what
- There is something above the law: violence, that is, power, that is, human nature.
  - Law is whatever people fear.
  - Power is the ability to do violence (bodily harm).
  - Weapon is power multiplier.
    Weapon multiplies the ability to do violence.
  - People who are above the law are above the law because they have more power than the police.
    Example of those people are extremely rich people, including big corruptors.
    Such powerful people have enough money to do more violence than the police can do.
  - Religious demonstrators are above the law because they can do more violence than the police can do.
    - The police must develop non-lethal crowd-control weapons.
- Law requires the ability to do violence.
- Law isn't about truth.
  Law has never been about truth.
  Philosophy is about truth.
- Modern law is about /provability/.
  - Since when? Since "habeas corpus"?
    - [[https://en.wikipedia.org/wiki/Habeas_corpus][WP:Habeas corpus]]
  - Is law a formal system that can do arithmetic?
    - What are the consequences of Gödel's incompleteness theorems to law?
      - There are true but unprovable things?
  - Is testimony acceptable?
  - [[https://en.wikipedia.org/wiki/Prima_facie][WP:Prima facie]]
  - [[https://en.wikipedia.org/wiki/Burden_of_proof_(law)][WP:Legal burden of proof]], onus probandi
    - "In a legal dispute, one party is initially presumed to be correct and gets the benefit of the doubt,
      while the other side bears the burden of proof."
    - "When a party bearing the burden of proof meets its burden, the burden of proof switches to the other side."
  - It is better to wrongly acquit than to wrongly convict?
    - [[https://www.independent.co.uk/news/uk/home-news/its-better-that-10-guilty-men-go-free-than-one-innocent-man-be-wrongly-convicted-944059.html][It's better that 10 guilty men go free than one innocent man be wrongly convicted]]
  - [[https://en.wikipedia.org/wiki/Truth][WP:Truth]]
  - [[https://en.wikipedia.org/wiki/Proof_theory][WP:Proof theory]]
  - [[https://en.wikipedia.org/wiki/Provability_logic][WP:Provability logic]]
- Enforceability is important.
  An unenforceable law practically doesn't exist.
  - This is why government requires the employer to withhold employee income tax.
    This is why the employee doesn't pay the income tax directly.
    - There are much fewer employees than employees.
    - It's easier to arrest employers than employees.
- Ontology
  - complain, complainant, plaintiff
  - defend, defendant, suspect, convict, felon, recidivist
  - litigation, litigant, legal battle
  - injunction
  - advocate, attorney, barrister, lawyer
  - judge, jury
  - precedent
  - penalty
  - crime
  - justice
    - retributive vs restorative justice
    - [[https://assets.justice.vic.gov.au/njc/resources/c4518c8a-c200-4623-afd1-42e255b62cf9/01+an+overview+of+restorative+justice.pdf][2005, Daniel W. Van Ness, "An overview of restorative justice around the world"]]
  - witness, testimony
  - slightly meta-legal concepts
    - obstruction of justice
    - contempt of court
- Computerization of law
  - Law is first-order logic? It should be computerizable?
  - Legal ontology?
  - Legal information system?
  - Legal search engine?
  - [[https://en.wikipedia.org/wiki/Computer-assisted_legal_research][WP:Computer-assisted legal research]]
  - [[https://www.legalrobot.com/blog/2016/05/25/Ontologies/][How Legal Robot works: Legal Ontologies]], 3-minute reading
    - LKIF (Legal Knowledge Interchange Format)
- Overview
  - [[https://en.wikipedia.org/wiki/Law][WP:Law]]
  - [[https://en.wikipedia.org/wiki/Crime][WP:Crime]]
- [[https://en.wikipedia.org/wiki/Counterclaim][WP:Counterclaim]]
- Legal abuse
  - [[https://en.wikipedia.org/wiki/Legal_abuse][WP:Legal abuse]]
  - [[https://en.wikipedia.org/wiki/Frivolous_litigation][WP:Frivolous litigation]]
  - [[https://en.wikipedia.org/wiki/Vexatious_litigation][WP:Vexatious litigation]]
    - [[https://en.wikipedia.org/wiki/Patent_troll][WP:Patent troll]]
  - [[https://en.wikipedia.org/wiki/Strategic_lawsuit_against_public_participation][WP:Strategic lawsuit against public participation]]
  - [[https://en.wikipedia.org/wiki/Chilling_effect][WP:Chilling effect]]
- [[http://www.tht.org.uk/myhiv/Telling-people/Law/How-do-you-prove-it_qm_][How do you prove HIV transmission?]]
  - "Sometimes, the person who complains to the police after recently testing as HIV positive turns out to have infected the person they are accusing."
- Who pay the cost of litigation?
- classifications
  - criminal acts
    - offense, wrongdoing
    - misdemeanor
    - felony
  - legal systems
    - common law system, case law
    - civil law system, statutory law
  - parts of law
    - civil law
    - criminal law
  - crimes
    - assault
    - battery
    - perjury
    - theft
    - murder
    - rape
    - etc.
- Can the defendant also be a witness?
- Can't we simply ask the defendant "Did you do it?"?
- [[https://en.wikipedia.org/wiki/Hitchens%27s_razor][WP:Hitchens's razor]]
  - "What can be asserted without evidence can be dismissed without evidence"
- Maritime law
  - [[https://en.wikipedia.org/wiki/General_average][WP:General average]]
- legal loopholes, programming errors
  - [[https://mentalfloss.com/article/83439/perfect-crime-may-be-possible-yellowstone-park][The Perfect Crime May Be Possible in Yellowstone Park | Mental Floss]]
*** Handling lawyers
If you don't know, don't act like you know.

Watch out for baits.
Don't be greedy.

- Risky stuffs
  - [[https://www.reddit.com/r/IAmA/comments/ajsih/i_am_the_guy_who_owned_mikerowesoftcom_ama/c0hy3d8/][I am the guy who owned MikeRoweSoft.com. AMA : IAmA]]
*** Making good laws
Good laws satisfactorily answers:

- How are we going to enforce it?
- What is the worst that haters can do?
- What questions might arise?
- What undefined cases?

Good laws:

- Can be enforced practically (sane effort and cost)
- Addresses the root cause of the problem
- Minimizes unintended effects (is well-targeted)
- Is complete (handle all cases) and Leaves no questions
- Is timeless/future-proof (doesn't depend on time) (is this even possible?)

People are creative.
They will find ways around laws.

Questionable example: even-odd car license plate rule.
If cars are cheap, then people will just buy two cars.
The root cause of the problem is bad/expensive/unintegrated public transport.

Bad example: legislating morality.
Are you going to visit each of the 100 million homes and install a camera?
* Get rich quickly without going to jail
- Make capitalism work for us instead of making us work for capitalism
- Is evil a necessity or a consequence?[fn::https://tvtropes.org/pmwiki/pmwiki.php/Main/SlowlySlippingIntoEvil]
- Power corrupts, but with more power we can do more good?

Maximize long-term profit: maximize income, minimize expenses.

I am already very frugal by nature, so I have to combat my tendency to be fixated at minimizing expenses.
** Maximize income
*** Find better use for the idly deposited moneys
*** Establish a monarchy, a corporation, start a business
Because:
socialism for the rich and capitalism for the poor[fn::https://en.wikipedia.org/wiki/Socialism_for_the_rich_and_capitalism_for_the_poor].
**** Other people's business ideas
- Tech company that sells to engineers; companies like JetBrains (Mufid)
- Machine transcription of interviews in Bahasa Indonesia using speech-to-text (Mufid)
  - <2019-04-22>
    He tried GCP text-to-speech for Bahasa Indonesia but he found the result unacceptable.
- <2018-09-24> Undertaker, mortician, funeral home, mortuary (Willy)
- <2018-09-24> Dropshipping, buying from someone in Tokopedia and selling to someone else also in Tokopedia (Nigel)
- <2019-04-22> Catering at Karawang (Mr. Handoko)[fn::https://www.facebook.com/Dapur-Rempah-267685393886789/]
- Dyson: 6-billion-dollar 7000-employee company owned by one person[fn::https://www.quora.com/What-is-the-largest-company-owned-entirely-by-one-person]
  - These people have one seemingly simple business and they can reach billion-dollar net-worth.
**** Flip companies; active investing
- Buy a company that is in shambles, fix it, refurbish it, clean it up, and sell it, hopefully for a profit.
- Help dying companies in exchange for partial ownership.
*** Extract wealth from society by seeking rent
Seek rent[fn::https://en.wikipedia.org/wiki/Rent-seeking];
use the law to get paid for simply owning something and doing nothing.
**** Own a property
- Buy a property, contract a management agency, and lease the property
  - Find good properties; determine what is good
    - Why do people stay at hotels? Attending events. Meetings. Inspections. A combination of closeness to the actual location of interest and the hotel's reputation. People stay at a hotel not because they admire the hotel building, but because they care about the location.
    - Unmarried white-collar workers choose the cheaper between renting and commuting.
    - Nomads who change work location every a few years, and people without enough money to buy houses
- Determine why people pay
  - The only reason people pay you is that they believe you will give them what they want.
- Start a gambling or insurance company
  - Kelly criterion
- Start a hype-laden "startup" and sell it to "investors"
- Get rich quickly from financial markets
  - Practice usury, lend money with interest
  - vestifarm
  - Trade financial assets: stocks, derivatives, currencies
    - For a beginner, merely not losing money is already a splendid start!
    - Calculate the fair price of a financial asset
    - [[file:reveng.html][Reverse software engineering]]
      - [[file:rejava.html][Reverse engineering the network protocol used by a Java desktop application]]
** Make more things doable without going to jail
*** Reduce the ability of government to jail people
- Piggyback, weaken, dismantle governments
  - Plant anti-government people in the government;
    laissez-faire liberals;
    anarcho-capitalists;
    unwitting opinionated idealistic hard-liners;
    "confused and misguided sympathizers"[fn::https://en.wikipedia.org/wiki/Useful_idiot]
** Get rich quickly by creating wealth?
** Minimize expenses
*** Minimize operational/administrative/bureaucratic/red-tape hassle
- Avoid dealing with labor laws; use contractors, freelancers, etc.
*** Minimize tax
**** Maximize non-taxable income
**** Minimize taxable income
- Maximize asset without mark-to-market
- Minimize profit
**** Maximize tax deductions
**** Plant anti-taxation people in the government
*** Write an enterprise operation system in Prolog
- Write an accountant in Prolog
*** Make machine work more
**** Improve machine intelligence
- [[file:intelligence.html][Making intelligence]]
- [[file:endo.html][The endofunction model of worlds and agents, and its philosophical implications]]
- Find how to make machine understand causation, in principle; find the theory
  - How do we make a machine that understands causation?
    - "Causal Cognition in Human and Nonhuman Animals: A Comparative, Critical Review", 2007[fn::http://derekcpenn.com/Penn_2007-Causal_Cognition_in_Human_and_Nonhuman_Animals.pdf]
    - "Causal Reasoning in Rats", 2006[fn::https://www.psych.uni-goettingen.de/de/cognition/publikationen-dateien-waldmann/2006_science.pdf]
    - "Causal knowledge in animals", 1995
    - Understand reality, the world, the Universe
      - [[file:philo.html][Philosophy]]: armchair philosophy; should be rewritten to focus on causation
        - [[file:mind.html][Mind]]: philosophy of mind
      - [[file:nature.html][Nature Research Group]]: physics and its philosophy
- Demonstrate that a machine understands causation
  - How do we know whether X understands causation?
**** Multiply software engineer productivity by 20?
- [[file:softeng.html][Software engineering]]: come up with a science to underlie software engineering
  - Measure programmer productivity
- [[file:prolog.html][Use the Prolog programming language]]
  - Make Prolog more suitable for programming in the large
    - Make a module system for Prolog
  - [[file:enterprise.html][Use Prolog for model-driven software engineering]]
  - Make an untyped Haskell/ML-like language in Prolog
  - Seamlessly interoperate programming languages
    [fn::I desire more than Will Crichton; I do not want to add annotations to the original code http://willcrichton.net/notes/the-coming-age-of-the-polyglot-programmer/]
    - 1996 \cite{barrett1996automated}
    - [[file:program.html][Programming Research Group]]: these should be merged?
      - [[file:proglang.html][programming language design]]
      - [[file:program-sketch.html][sketching a declarative programming language]]
      - [[file:semantics.html][Semantics Research Group]] (of programming languages)
- [[file:opensrc.html][Making contributable open-source projects]]
  - [[file:community.html][Building online communities]]
** Build human resource
- Educate software engineers to a comparable quality but faster than the 16 years of formal education
  - Make all Indonesian people understand English,
    because most relevant resources on the Internet are in English
* Getting rich (old content, to be reorganized)
** How do we get rich?
There are only two ways to get rich: /earn/ wealth or /steal/ wealth.

Earn wealth: convince people to give you money, by selling them things that improve their lives.
Use the money to develop your wealth even more.

Or steal wealth: An investor steals a little wealth from each person who does not invest.

After you obtain enough wealth, develop it, but don't lose all of them.
** What?
- Which is more fundamental, economics or finance?
  Which is built on which?

- Why get rich?

  - Get more power.
  - Change the world.
    Bend the world to your will.
    Impose your ideals onto the world.
  - Actualize your dreams.

- The problem with opening a business is too many choices.

  - Almost all businesses make money.
  - Every obvious business idea is already taken.

- 2017, 1 hour, [[https://www.youtube.com/watch?v=vsMydMDi3rI][Frank Abagnale: "Catch Me If You Can" - Talks at Google]]

  - Use credit card, not debit card.

    - Use credit card, but don't fall into debt.
      Treat credit card as means of payment, not loan.
    - Never use debit card outside trusted ATMs.
    - But what about cash withdrawals from ATMs?
      Credit cards have higher fees.
    - https://www.nerdwallet.com/blog/credit-cards/credit-card-vs-debit-card-safer-online-purchases/
    - https://www.quora.com/Are-credit-cards-safer-than-debit-cards
    - FUD (fear, uncertainty, and doubt)

      - https://www.chimebank.com/2017/08/08/are-credit-cards-really-safer-than-debit-cards/

        - Of course banks want you to use the debit card. It reduces their liability.

  - Passwordless authentication

    - Authentication with a phone, without username, without password: [[https://www.trusona.com/][Trusona]], from the Frank Abagnale 2017 Google talk above.
    - https://hacks.mozilla.org/2014/10/passwordless-authentication-secure-simple-and-fast-to-deploy/
    - 2014, Justin Balthrop, "The basic idea is that instead of using a password to authenticate each user, a temporary secret code is sent to them over a secure channel."
      ([[https://medium.com/@ninjudd/passwords-are-obsolete-9ed56d483eb][source]])

- What is money?

  - Money is a way for people to decide what is important (vote for what is important).

    - People vote with their money.

- The job of a company (a company director?) is to find what to do and find who should do it.

  - Everyone has different tendencies, strengths, weaknesses, desires, preferences, habits, upbringings, backgrounds.
  - Some people are more suited for some jobs.

    - Some jobs require high IQ; otherwise the employee will take too long to learn.
    - Some jobs require low IQ; otherwise the employee will get bored too soon.

      - Yes, low IQ can be a strength.

  - The company has goals.
  - The director breaks down the goals into jobs.
  - The director matches employees and jobs.
  - Which comes first: the job or the employee?

    - Do you formulate a job description first, and then find people to do that?
    - Do you hire people first, and then formulate jobs suitable for them?

  - A good company accomplishes more than each employee can accomplish individually.

- [[https://www.youtube.com/watch?v=cWVk8Cdvmgs][Who controls the world? - James B. Glattfelder]]

  - physical modeling/explanation of financial inequality

- [[https://www.youtube.com/watch?v=QX3M8Ka9vUA][The Third Industrial Revolution: A Radical New Sharing Economy]]

  - Jeremy Rifkin, Third Industrial Revolution, sharing economy, Germany, Digital Europe, China Internet Plus, aggregate efficiency, distributed system

    - The Second Industrial Revolution peaked at 20% aggregate efficiency.
    - Difference between post-Westphalian worldview and Millenial worldview.

      - The 21st century way of living is radically different.
        Different ideas of freedom.

        - In the post-Westphalian worldview, freedom means sovereignty, being autonomous, being an island.

    - Second Industrial Revolution teaches kids to be factory workers. Obedient. Unquestioning. Hardworking.

  - [[https://www.youtube.com/watch?v=3xOK2aJ-0Js][Jeremy Rifkin on the Fall of Capitalism and the Internet of Things - YouTube]]

- [[https://www.youtube.com/watch?v=mAOyOULWKUo][Corporate Greed Isn't New. The Internet Is Just the New Playing Field, says Douglas Rushkoff - YouTube]]

  - Corporates were invented by aristocrats to make sure peasants stay peasants?
  - [[https://bigthink.com/videos/douglas-rushkoff-on-the-internet-and-the-future-of-business][transcript]]

    - We should verify and distill these texts.
      These are some bold claims.

      - "As the peasants became wealthy the aristocracy got scared, who are these people?
        They're not going to be dependent on us any more.
        So they came up with two main financial innovations to prevent the rise of this peer to peer economy.
        The first one was the chartered monopoly, really the parent to the modern corporation.
        All the chartered monopoly was was a way to say all of you small businesses are now illegal.
        If you want to be in the shoe business you have to work for his majesty's royal shoe company.
        You want to be in the grain business you have to work for his majesty's royal grain company.
        So people who were small business people now became employees.
        Instead of selling the value they created, now they sold their time as servants, as wage laborers."
      - "The second invention they came up with was central currency.
        Not such a terrible thing in itself.
        It's great to have a long distance currency that lots of people can use and value, but the problem was they made all of the local currencies illegal.
        So the only way people could trade with each other, the candlestick maker could trade with the chicken farmer was by borrowing central currency from the treasury.
        So now you had to borrow money at interest just in order to transact.
        And that set in motion really a growth cascade.
        If you have a currency that has to be paid back with interest, in order to just make end meet you need an economy that's growing.
        You need more money next year than there was this year."
      - "So that worked well for colonial powers, as long as we could extend into Africa and South America and North America, find slaves, find new resources, we could grow.
        But what happens when you reach the end of the planet's growth as we did really at the end of World War II?"

- [[https://www.youtube.com/watch?v=6_n1Dro0Uec][Online Companies Like Facebook Have Created a Meaningless Economy, says Douglas Rushkoff - YouTube]]
- Work-life balance?

  - Don't confuse being busy and working.

    - Work should create value.
    - You can feel busy while not producing anything.
    - Work has goals. Being busy doesn't have goals.

  - People don't care about processes.
    They only care about results.
  - If you are not working in all your waking hours, then it's not the work you want.
  - If I could work in my sleep, I would!

- Transport is waste.
  Hence travel is waste.
- Why can't people stay at home on holidays?

  - If you don't like staying at home on holidays, that means something is wrong with your home.
    Fix it.
    Make it the best place on Earth.
    Face reality.
    Don't escape.

- https://www.quora.com/What-are-possible-warning-signs-of-an-imminent-economic-collapse
- Communism

  - The USSR was beyond communism; it was Stalinism.
  - Stalinism failed because it overcentralizes power.

    - Power corrupts.
    - Oppression isn't a good long-term strategy.
    - People are like gas.

      - Increasing pressure (oppression, stress, overcrowding) increases temperature (collisions, friction, conflicts, clashes).

  - People would still work even if they couldn't get rich.

    - People work to give their life meaning, not to get rich.

      - Getting rich is a side-effect.

    - Would they work better if they could get rich?

- If you buy land and let it idle, only to sell it higher in the future, then you're /seeking rent/.

  - You are not creating any value.
    You burden society.
    You get rich by burdening others, making them poorer.
    The world is better without you.
    You contribute to city sprawl, which causes winding roads, more fuel consumption, more traffic, more pollution, and more heat.
    You should be heavily taxed for the huge negative externality you cause.

- Is all speculation rent-seeking?
** Capitalism
- What is capitalism?

  - Capitalism is:

    1. the /private ownership/ of means of production,
    2. the operation of such means /for profit/.

  - [[https://en.wikipedia.org/wiki/Capitalism][WP: Capitalism]].

- How is it good?

  - Capitalism enables selfish people to better everyone else.
  - Voluntary exchange betters everyone.

    - People don't agree to a deal they think bad for them.

- How is it bad?

  - Wealth gap? Social gap?
  - Capitalism places capital above labor?
  - Short-term profit-seeking and rent-seeking destroys environment and humanity?

- How can it be improved?

  - Regulation

    - [[https://www.youtube.com/watch?v=YOaJe68C-bU][How to Improve Capitalism]]

  - Capitalism can be environmentally friendly if the polluters pay the environmental costs.

    - 2018: other people are still paying the cost. (Negative externality)

      - Can sustainability be made profitable?

        - Pessimistic sources

          - https://grist.org/business-technology/none-of-the-worlds-top-industries-would-be-profitable-if-they-paid-for-the-natural-capital-they-use/
          - https://www.theguardian.com/sustainable-business/blog/sustainability-business-sense-profit-purpose
          - https://www.theguardian.com/environment/2010/feb/18/worlds-top-firms-environmental-damage

- Ramble

  - Companies must extract value to survive.

    - A profitable company must extract more value
      from its employees than it pays its employees.

      - People create value. People in a company create value. Human labor creates value.
        Companies aren't human. Companies can't work. It's the employees who work.
      - But if the employees weren't in the company, they might create less value.
        The company might be a place where the employees can create more value for society.

- http://www.visualcapitalist.com/
- Capital is everything that is not labor?
- Capitalism is capital above labor? Communism is labor above capital?
- Example of low-capital high-labor:

  - small and medium enterprises (SMEs)

    - food stalls
    - home bakeries
    - art freelancing

  - research in pure mathematics

- [[https://en.wikipedia.org/wiki/Criticism_of_capitalism][WP:Criticism of capitalism]]

** Investing
  :PROPERTIES:
  :CUSTOM_ID: investing
  :END:

- Wealth Extraction Efficiency = Dividend / Equity

  - Dividend is shareholder's dividend
  - Equity is book value
  - If reading consolidated report, use the one attributable to parent entity

- Time to buy? Mungkin beberapa bulan setelah lebaran.

  - 2018, https://www.reddit.com/r/indonesia/comments/8l9yc7/indonesias_stock_rout_claims_another_victim_the/
  - https://www.reddit.com/r/indonesia/comments/8l4ykk/why_an_emerging_market_rout_has_hit_indonesia_so/

    - https://www.bloomberg.com/news/articles/2018-05-09/why-an-emerging-market-rout-has-hit-indonesia-so-hard-quicktake
    - Why do they disapprove of Sri Mulyani?

- Everyday there are stocks that rise by 20% and there are stocks that fall by 20%.

  - If we can predict which will rise, we can get rich quickly.
  - Why do prices rise?
    Because buyers concede to sellers.

    - Because there is more buying pressure than selling pressure.
    - Because there is more buy orders than sell orders.
    - Because more people buy.
    - Because less people sell.
    - Because more people buy.

  - Why do people buy a stock?

    - Because they believe it will rise.

      - Why do they believe so?

        - Fallacious reasoning.
          Psychological bias.
          Appeal to authority.
          Hearsay.
          Fear of missing out.
          Irrational exuberance?

    - Because they believe it will give them dividends.
    - https://money.stackexchange.com/questions/82057/what-factors-make-someone-buy-or-sell-a-stock

  - How do we persuade/encourage people to buy a stock?
    How do you market a stock?

    - This is gray area.
      Is it even legal?

  - How do we prevent sellers from selling?

- Hypothesis: Some companies' financial statements predict economic/financial crises.

  - How are economic crises even possible if there is enough money for everybody?

    - Uneven distribution of money?
    - Hypothesis: The solution to an economic crisis is a forced redistribution of money, an economic reboot/restart, however unpleasant.

      - In an economic crisis, tax the wealthy and pay the poor.
      - I think that is an optimal solution (if not the only solution), but that is politically incorrect, so we'll never see that.

    - If ignored, economic crisis will escalate to sociopolitical crisis.

- Banks lend money with interest.
  Thus, paying back the loans reduce circulating money.
- https://iextrading.com/

  - the only independent stock exchange in the USA
  - http://hackage.haskell.org/package/stocks

- daftar (list) reksadana https://www.indopremier.com/ipotfund/listreksadana.php
- 2018-10-10: GarudaFood mau IPO!

  - http://investasi.kontan.co.id/news/bersiap-masuk-bursa-garudafood-akan-melepas-10-saham
  - https://investasi.kontan.co.id/news/menanti-ipo-jumbo-dari-garudafood

- Read Benjamin Graham value investing?
- Mana yang mujarab? Belum ada yang saya coba.

  - Teguh Hidayat

    - [[https://www.teguhhidayat.com/p/ebook-analisis-kuartal-i-2014.html][Indonesia Value Investing: Ebook Analisis Kuartal II 2018]]
    - [[https://www.thpartner.com/][Indonesia Value Investing]]

  - [[http://galerisaham.com/][galerisaham.com]]: rekomendasi saham harian; GS Pro

- [[https://deep-throat-ipo.blogspot.com/][deep-throat-ipo.blogspot.com]]
- http://www.sahamok.com/tentang/
- https://www.kemenkeu.go.id/single-page/savings-bond-ritel/
- https://sbn.investree.id/
- List of traded things

  - [[http://www.idx.co.id/id-id/beranda/informasipasar/saham/ringkasansaham.aspx][Stocks]] sortable by price, "value" (I thought it was market capitalization), volume, frequency
  - [[http://www.idx.co.id/id-id/beranda/informasipasar/daftarefek/saham.aspx][Stocks]] sortable by category ("board"), IPO date, number of shares
  - [[https://id.wikipedia.org/wiki/Daftar_perusahaan_yang_tercatat_di_Bursa_Efek_Indonesia][Stocks]], from Wikipedia Indonesia, linking to IDX pages
  - [[http://www.idx.co.id/id-id/beranda/informasipasar/daftarefek/etf.aspx][ETFs]]
  - [[http://www.idx.co.id/id-id/beranda/perusahaantercatat/aktivitaspencatatan.aspx][IPOs, delistings, and relistings]]
  - forex = foreign exchange
  - CFD = contract for difference
  - IndoCDS? credit default swap? apa ini? apakah traded?

- Announcements about the securities being traded

  - In practice, you get these news from your broker's application, not from IDX website.
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/pengumuman.aspx][Announcements]] (delistings, mergers, shareholder meeting invitations, etc.)
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/unusualmarketactivity.aspx][Unusual market activities]]
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/suspensi.aspx][Temporary trading suspensions]]

- Brokers

  - [[http://www.idx.co.id/id-id/beranda/anggotabursaamppartisipan/anggotabursadikotaanda.aspx][Find a broker near you]]

- Regulations

  - [[http://www.idx.co.id/id-id/beranda/tentangbei/mekanismeperdagangan/jamperdagangan.aspx][Trading hours]]:

    - practically 09:00--11:30 and 14:00--15:50 UTC+7, except Fridays

  - [[http://www.idx.co.id/id-id/beranda/tentangbei/mekanismeperdagangan/saham.aspx][Settlement]]:

    - practically T+3, where T+0 is the transaction date

  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/jadwalliburbursa.aspx][Holiday schedule]]
  - [[http://www.idx.co.id/id-id/beranda/tentangbei/strukturpasarmodalindonesia.aspx][Struktur pasar modal Indonesia menurut UU 8/1995]]

- [[https://en.wikipedia.org/wiki/Industry_classification][Industry classification]]
- Indonesia company types

  - [[https://id.wikipedia.org/wiki/Badan_usaha#Persero][What is BUMN/BUMD Persero?]] (Wikipedia Indonesia)

- Financial reports

  - [[https://www.abdainsurance.co.id/index.php?option=com_content&view=category&layout=blog&id=41&Itemid=136&lang=id][ABDA]] (PT Asuransi Bina Dana Arta Tbk)
  - [[http://www.bca.co.id/Tentang-BCA/Hubungan-Investor/Laporan-Keuangan/Laporan-Finansial-Per-Kuartal][BBCA]] (PT Bank Central Asia Tbk)
  - [[http://phx.corporate-ir.net/phoenix.zhtml?c=148820&p=irol-reportsOther][BBRI]] (PT Bank Rakyat Indonesia (Persero) Tbk)
  - [[http://ir.bankmandiri.co.id/phoenix.zhtml?c=146157&p=irol-finStatement][BMRI]] (PT Bank Mandiri (Persero) Tbk)
  - [[http://ir.matahari.co.id/phoenix.zhtml?c=171562&p=irol-reportsother][LPPF]] (PT Matahari Department Store Tbk)
  - [[http://corporate.ramayana.co.id/index.php/en/investor-relation-2/financial-information/financialreports][RALS]] (PT Ramayana Lestari Sentosa Tbk)

- Banks

  - [[http://media.corporate-ir.net/media_files/IROL/14/148820/BRI_ENG_31%20Dec_2016_Released_Password_Removed.pdf][BBRI 2016]]
  - [[http://media.corporate-ir.net/media_files/IROL/14/146157/Bank-Mandiri-Tbk_Ind_31_Desember_2016_Released-.pdf][BMRI 2016]]

- Insurance

  - [[https://www.allianz.co.id/tentang-kami/finansial#keuangan][Allianz ID]] (PT Asuransi Allianz Life Indonesia)
  - [[https://www.prudential.co.id/corp/prudential_in_id/header/aboutus/financialstatement/index.html][Prudential Indonesia]]
  - 2016 annual reports:

    - [[https://www.abdainsurance.co.id/abdanew/lap_keu_thn/Final%20Report%20ABDA%2031%20Des%202016%20with%20opini.pdf][ABDA]]
    - [[https://www.prudential.co.id/export/sites/default/prudential_in_id/resources/downloads/financialstatement/2017/FS_Audited_2016.PDF][Pru]]

- Things that make me sad

  - Back button doesn't work on the IDX website.

- Thanks but no thanks. I'll stick to stocks for now.

  - http://www.brokerforexindo.com/
  - http://www.nfa.futures.org/basicnet/SearchResults.aspx?type=firm&firm=FXCM
  - national futures association http://www.nfa.futures.org/
  - http://www.bappebti.go.id/id/api/pialang_dicabut.html
  - http://www.e-bursa.com/
  - http://www.bloomberg.com/quote/LMAS:IJ
  - http://topbrokerforex.blog.com/2012/08/02/daftar-badan-regulasi-untuk-broker-forex/

- https://en.wikipedia.org/wiki/Outline_of_finance#Post-modern_portfolio_theory
- Measuring investment performance

  - https://en.wikipedia.org/wiki/Sharpe_ratio
  - https://en.wikipedia.org/wiki/Sortino_ratio
** Justifying my value
  :PROPERTIES:
  :CUSTOM_ID: justifying-my-value
  :END:

- 2018-08-18

  - Today, in an hour, I advised my friend.
    My advice, if implemented, would save him Rp 450 million / year.
    His cost is Rp 3000 million / year.
    He makes 300 sales per year.

    - Talking with me for an hour could cut your business unit economic costs by 15%.
    - Should I be a SME (Small and Medium Enterprises) consultant?
    - Is Rp 450 million / year big?
    - Is 15% unit economics improvement big?

  - Inefficiency kills a company.
    A competitor finds a more efficient way to do the same thing.
    Either slowly/incrementally from an ordinary competitor, or radically/disruptively by an unexpected competitor.
** Economics
  :PROPERTIES:
  :CUSTOM_ID: economics
  :END:

- ontology

  - wealth

    - /Wealth/ is the sum of satisfied wants.

  - price, pay, ownership, exchange, transaction

    - To /own/ something is to have exclusive access to that thing.
    - /Exchange/ and /transaction/ are synonyms.
    - An /exchange/ is an agreement

      - between two parties A and B where

        - A gives X to B,
        - B gives Y to A.

    - If X is money and Y is not money, then:

      - X is the price.

        - /Price/ is the amount agreed for exchange.
        - /Price/ is something sacrificed to get something else.

      - A is the buyer.
      - B is the seller.
      - The buyer /pays/ the price to the seller.

  - negotiation, price-taker, price-maker

    - Negotiating parties often have asymmetrical bargaining power.
    - The price-taker is the weaker one.
    - The price-maker is the stronger one.

  - money and currency

    - Money has /currency/ and /amount/ (/magnitude/).
    - Money can be /exchanged/ with many other things.

  - debt, interest, and price

    - The price of debt is the /interest/
      (the amount of money that will be exchanged for obtaining the loan now).

      - An X market is a market where X is traded.

        - A money market is a market where money is traded.

          - How do you buy money with money?

- Assumptions

  - Every human:

    - Has wants.
    - Has priorities? Utility function?

      - Non-constructive? It exists, but we don't know what it is?

    - Acts to satisfy those wants.

- Counterexamples? Where the theory breaks down?

  - Thiefs want something more than freedom?

    - But both of the stolen thing and the freedom will be taken away?

  - Smokers and junk food eaters don't want health?

    - Everybody wants health?

      - But doesn't behave consistent with wants?

        - Cognitive dissonance?

          - Want health later or health now?
          - Addiction?

            - Physical changes to the brain?

- Fundamentals of economics

  - Everybody wants something.
  - How do we satisfy more people using less resources?

- decision theory?

  - [[https://en.wikipedia.org/wiki/Von_Neumann%E2%80%93Morgenstern_utility_theorem][WP:von Neumann--Morgenstern utility theorem]]

- Higher-order belief

  - [[https://en.wikipedia.org/wiki/Keynesian_beauty_contest][WP:Keynesian beauty contest]]
  - Examples of higher-order beliefs:

    - People believe that money is valuable because they believe
      that others also believe that money is valuable.

- How do we give more than we take?

  - How do we produce more than we consume?

- Land > Labor > Capital

  - The [[https://en.wikipedia.org/wiki/Factors_of_production][factors of production]]
    in classical economics are:

    - land (all other things that exist in nature),
    - labor (human),
    - capital (tools).

  - Land creates labor.
  - Labor creates capital.
  - If capital is destroyed, labor can rebuild it.
  - If labor is destroyed, capital cannot rebuild it.
  - Labor without capital is inefficient.
  - Capital without labor is /nothing/.
  - However, without land, nothing would exist at all.
  - Therefore, land is more important than labor, and labor is more important than capital,

    - but it seems here that capital is revered, labor is disdained, and land is forgotten.

  - Money is not capital, but it can be used to buy capital, but this quote is related:
    > When the last tree is cut, the last fish is caught, and the last river is polluted;
    > when to breathe the air is sickening, you will realize, too late,
    > that wealth is not in bank accounts and that you can't eat money.
    >
    > Alanis Obomsawin (b. 1932) ([[http://quoteinvestigator.com/2011/10/20/last-tree-cut/][source]])

- Is Indonesia basic income feasible?

  - [[https://en.wikipedia.org/wiki/Basic_income][WP:Basic income]]
  - [[https://www.kemenkeu.go.id/apbn2016][APBN 2016]] income Rp 1,822.5 trillion (in one year).
  - 2016 population 258 million people. (source?)
  - Thus about Rp 7 million per man-year.

    - This isn't even enough to buy food for one man-year.

- https://www.numbeo.com/cost-of-living/
- Undigested

  - https://www.opendemocracy.net/transformation/andrew-sayer/is-unearned-income-acceptable
  - http://www.resilience.org/stories/2016-03-15/money-is-not-a-store-of-value/
  - Write about inflation

    - Supply-caused inflation
    - Demand-caused inflation

  - https://www.washingtonpost.com/news/wonk/wp/2013/09/09/how-the-cult-of-shareholder-value-wrecked-american-business/

- philosophy

  - Increasing the wealth of the human race conflicts with antinatalism?
  - Increasing the minimum/average wealth of the human race doesn't conflict with antinatalism?

- Some economists

  - David Ricardo
  - Henry George
  - Adam Smith
  - John Maynard Keynes

- Initial money supply

  - How is money distributed for the first time (when there is not yet any money)?
  - How do we transition from barter to cash?

    - How do we set prices?

- [[https://en.wikipedia.org/wiki/Modern_Monetary_Theory][WP:Modern monetary theory]]?
- Tax

  - Tax enables government to redistribute money (and therefore some wealth).
  - Tax enables government to discourage the consumption of certain goods.
  - Taxation is legalized robbery.

    - The government forcibly takes some of the people's money.
    - The people doesn't get to decide what the tax money is used for.

      - The government is assumed to use that money for the people's good.

- [[https://en.wikipedia.org/wiki/Trickle-down_economics][WP:Trickle-down economics]]

  - How does one arrive at this? How does one think? What is the argument?

- If the total amount of money is constant,
  then the only way for you to have more money
  is to make someone else has less money.

  - [[https://en.wikipedia.org/wiki/Mercantilism][WP:Mercantilism]] assumes that the total wealth in the world is constant?

    - "Mercantilists viewed the economic system as a zero-sum game, in which any gain by one party required a loss by another.[16]"

- Questions I haven't been able to answer

  - If everybody needs to buy food, then why aren't farmers the richest people on Earth?

    - What if the farmers don't spend?

      - Will money collect at the farmers?
      - Will they be the richest people on Earth?

- Money circulation

  - Circulating money amount should be proportional to amount of goods/services exchanged?
  - The amount of money in circulation can be reduced by tax or destruction.
  - Why do governments sell bonds?

    - To reduce the amount of money in circulation now?

      - At the cost of increasing a bigger amount of money circulating in the future?

  - Money moves faster in certain areas?
  - How does the government increases the amount of money in circulation?

    - How I think it might be done:

      - Create new money.
      - Spend that money by buying things from a few elites,

        - with the hope that the elites will quickly spend that money to the lesser elites.

          - Thus that money will circulate to more people.

            - But isn't this trickle-down economics?

    - But does it even do this? Isn't it the banks?

  - What is the effect of people's borrowing from banks?

    - Increase circulating money now (boom part of boom-bust cycle).
    - Reduce /more/ circulating money later (bust part of boom-bust cycle, when the loan is paid back with interest).

      - Principal plus interest (money retired) is greater than principal (money created),
        so the net effect of lending money now
        is a delayed reduction of a greater amount of money in circulation.

        - Where does the money to pay the interest come from?

          - If left alone, eventually the money collects at the banks?

            - But banks have expenses too.

              - Banks need to pay taxes, pay their utility bills,
                pay their staffs.

            - But shouldn't the money collect at the farmers?

  - The ideal inflation rate is zero?

    - [[https://en.wikipedia.org/wiki/Nominal_rigidity][WP:Nominal rigidity]] a.k.a. price-stickiness or wage-stickiness

- [[https://makewealthhistory.org/2018/01/31/wealth-creation-and-wealth-extraction/][The difference between wealth creation and wealth extraction]]
- [[https://medium.com/@joe_brewer/the-global-architecture-of-wealth-extraction-4c0a6b954a14][The Global Architecture of Wealth Extraction]]
- [[https://www.aljazeera.com/indepth/opinion/2017/05/africa-poor-stealing-wealth-170524063731884.html][Africa is not poor, we are stealing its wealth]]
- rent seeking, wealth extraction

  - unread

    - [[https://boffyblog.blogspot.com/2017/04/general-election-who-are-wealth.html][Who are the wealth extractors?]]
    - [[http://www.rossgittins.com/2018/01/whos-doing-best-in-rent-seeking-business.html][Who's doing best in the rent-seeking business]]

- Infer: People buy something because they want it.

  - False assumption: People buy something because it makes them better off.
  - False assumption: People buy something because /they believe/ it makes them better off.
  - False assumption: Voluntary exchange makes both parties better off.
  - Counterexample: Cigarette smoking, addictive substances.
  - Why do people want things? Some possible reasons:

    - To sustain life.
    - To avoid pain.
    - To increase happiness.
    - To satisfy curiosity.
    - ...
    - Their brains are hijacked.

      - Isn't it generally immoral to harm people?
      - Is it moral to make people harm themselves (e.g. selling them cigarettes)?

  - Murphy's law applied to capitalism?

    - If something is profitable, someone will do it.
    - Some evil is profitable.
    - Therefore someone will do some evil and get rich from doing that evil.

- Unread

  - False assumptions

    - [[https://caspertk.wordpress.com/2012/12/08/top-ten-false-assumptions-taught-in-my-economics-classroom/]["Top Ten False Assumptions Taught In My Economics Classroom"]]
    - [[http://www.binaryeconomics.net/wordpress/fifty-nine-false-assumptions-of-mainstream-neo-classical-economics/][Fifty Nine False Assumptions of Mainstream Neo-classical Economics]]

      - questionable source

- economics-biology analogy

  - pioneer species?

    - https://en.wikipedia.org/wiki/Pioneer_species
    - pioneer species in biology ~ pioneer species in economics ?
    - ecosystem recovery after wildfire ~ economy recovery after war/disaster ?
    - fire ecology ~ war/disaster ecology ?
    - How does a community rebuild itself?

- Company theory

  - Avoiding personification of companies

    - A company is a group of people.
    - Group is concept. Person is reality.
    - Groups can't think. People think.
    - Groups can't react. People react.
    - Groups can't live. People live.
    - Groups can't work. People work.
    - Groups can't create value. People create value.
    - Groups can't decide. People decide.
    - Groups can't be responsible. People are responsible.
    - Groups can't commit crime. People commit crime.
    - Groups can't damage environment. People damage environment.
    - Groups can't exploit. People exploit.
    - What do we mean when we say "a group of people are walking"?
      We mean "those people are walking".
      A group is a concept.
      We invent it in our language.
      A group can't walk.

  - The whole is greater than the parts?

    - The value that someone produce alone is less than the value he produces with his coworkers?
    - But social loafing? Bigger team mean less work per person?
    - Companies exist.

      - It shows that owning a company can be profitable.

  - Define: To /employ/ someone is to find/give him things to do.
  - A profitable-company owner employs its employees better than those employees employ themselves.
  - If employees could find great things to do, they will own a company, not work for a company.
  - To employ is to exploit.

    - A company owner who doesn't exploit his employees enough will run out of money.
    - A company owner who exploits his employees too much will run out of employees.
    - "Exploit" there is the same "exploit" in "exploiting natural resources".

      - [[https://en.wiktionary.org/wiki/exploit#Verb][Wiktionary:exploit]]: "to use for one's own advantage"

- Does Patreon work?

  - For investors?
  - For creators?
  - For patrons?
  - https://theoutline.com/post/2571/no-one-makes-a-living-on-patreon

- https://en.wikipedia.org/wiki/Laffer_curve

** Finance
  :PROPERTIES:
  :CUSTOM_ID: finance
  :END:

- What is finance?

  - [[https://en.wiktionary.org/wiki/finance][Wiktionary: finance]]
  - [[https://en.wikipedia.org/wiki/Finance][WP: Finance]]

    - "Finance is a field that deals with the study of investments."

- Loan-related jargon

  - A lender lends (gives) a loan to a borrower.
  - A borrower borrows (takes) a loan from a lender.
  - Loan is the amount.
  - Borrower (one who borrows) is the debtor (one who has debt).
  - Lender (one who lends) is the creditor (one who gives credit).
  - Lease vs rent?

    - Lease is more formal and long-term than rent.

      - [[http://www.businessdictionary.com/article/1063/lease-vs-rent-d1412/][businessdictionary.com]]
      - [[https://www.nolo.com/legal-encyclopedia/leases-rental-agreements-faq.html][nolo.com]]

- Currency-related jargon

  - The /price/ is the amount paid by the buyer to the seller.
  - What is currency?
  - What is money?
  - What is the difference between currency and money?

    - https://www.weusecoins.com/hidden-secrets-of-money-currency-versus-money/

      - "Currency is a medium of exchange, a unit of account."
      - "Money is [currency] plus a store of value over a long period of time."

  - What is legal tender?
  - What is cryptocurrency?
  - Is there such thing as "cryptomoney"?

- Securities

  - A [[https://en.wikipedia.org/wiki/Security_(finance)][security]] is a /claim/ to something.
  - An /exchange/ was a place (is a computer system) where things are traded (bought and sold).

    - The exchange requires /brokers/ because it was invented before computers.

      - Impractical: 1 million people on the trading floor shouting for a match.

        - But a computer can match 1 million trades in a second.

      - Nobody bothers making a new stock exchange.

        - Because of [[https://en.wikipedia.org/wiki/Network_effect#Financial_exchanges][network effect]].
        - But [[https://robinhood.com/][Robinhood]] is doing that,

          - but it's a broker, not a stock exchange,

            - but I hope they make buying stock as easy as ordering pizza online,

              - because if everyone uses the same broker,
                then the broker /is/ the exchange.

          - [[https://support.robinhood.com/hc/en-us/articles/202853769-How-Robinhood-Makes-Money][How Robinhood makes money]]

            - No trading fee.
            - $6 per month per person who uses Robinhood Gold; otherwise none.
            - In 2017, Robinhood had 2 million users ([[https://techcrunch.com/2017/04/26/robincorn/][techcrunch.com]]).

              - How many of them use Robinhood Gold?

                - How many people have margin account compared to regular account?

                  - I guess 1:100.

              - How many employees do Robinhood have?

                - 30 ([[https://www.owler.com/company/robinhood][owler.com]])

              - Does that make sense?

                - My estimate:

                  - Their revenue:

                    - $60,000 per month = $720,000 per year.

                  - Their expenses:

                    - $300,000 per year for employees.
                    - ? for stock exchange chairs.
                    - ? for building leases.

                - Yes, it makes sense.
                - Are customers "mercy-buying" because they think Robinhood is too cheap (compared to old-school brokerages)?

                  - [[https://www.stockbrokers.com/guides/features-fees][stockbrokers.com: 21 Most Common Online Broker Features & Fees]]
                  - Comparison: In Indonesia, stock trading cost is about 0.02% of trade value.

    - A stock exchange starts out trading stocks,
      but after some time it begins trading other securities,
      but the name has stuck.

  - A /bond/ is a securitized loan?
  - Every asset can be securitized?
  - Stock

    - /Stock/ is company ownership.
    - A /share/ is a fraction of stock.
    - Buying share means buying partial company ownership.

- Undigested information

  - [[http://noahpinionblog.blogspot.co.id/2013/01/how-much-value-does-finance-industry.html][Noahpinion: How much value does the finance industry create?]]
  - Investing, speculating, or gambling?

    - Slap some "math" on gambling masquerading as "investing", and suddenly it looks legit.
    - "Modern investing: gambling in disguise", David Schneider

** Defining investing, trading, gambling, betting, wagering, insurance
*** Defining gambling
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/
*** How do we know something is not gambling?
**** If it's possible to be skillful, then it's not gambling.
*** What
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?" https://www.bbc.com/news/business-38905963
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
** If you win a lottery
Don't tell anyone.
Even families, friends, and lovers.
** "Investing"
What Bitcoin "investing" is:
- You buy a certificate of environmental destruction from someone, probably a "miner".
- You expect a greater fool to buy that certificate from you at a higher price.
  There are millions of other people who are looking for someone else more stupid than them.

Bitcoin is massive wealth transfer from late buyers to early buyers.
All financial investing is massive "realistic-return" Ponzi scheme.
Exactly fits the definition.
Newcomers pay oldtimers.
Late buyers pay early buyers.

Bitcoin is not necessary at all. It is pure want.
Inflation target disincentivizes currency hoarding.
A deflating currency encourages currency hoarding and discourages real spending.
https://www.cmegroup.com/education/featured-reports/an-in-depth-look-at-the-economics-of-bitcoin.html

https://www.theguardian.com/technology/2018/nov/05/energy-cost-of-mining-bitcoin-more-than-twice-that-of-copper-or-gold
** Economics, price, quality
Price is not important in itself.
It is the quality-price trade-off that is important.
People don't buy shit even if it's cheap, even if you pay them to buy it.

For an increment of quality, people are willing to pay an increment of price.
But there is a "good enough" point where people are satisfied and they just look at the lowest price.

Negative price means willingness to pay to get rid of something.
Example: rotten vegetables has negative price to most people, but positive price to farmers.
** Economics?
We should measure debt-to-income ratio instead of debt-to-GDP ratio?

Consumptive debt sacrifices future for the present.

Productive debt is good.

Example of productive debt:

Suppose that you want to buy a land to farm on it. These are the scenarios:
- You work for 20 years. Then you buy the land with cash. But the land price has risen.
- You take a loan, buy the land now, and repay the loan over 10 years. In the second year, your land starts producing.

If a person takes too much consumptive debt, he goes bankrupt.

If a government takes too much consumptive debt nominated in its own currency, it can print money to repay the debt, but such printing devalues the currency.

If the US continues to take loans mindlessly, it will have to choose:
- Default (refuse to repay).
- Suffer severe inflation (rising prices), if the creditors spend the printed money.

Does the USA think it can get away by refusing to repay its debts? It will trigger a huge power shift, maybe to China. Will China sacrifice itself to clean up America's mess? Will China buy up all US debts, and use the default as a reason to start a war?

https://deviantinvestor.com/9778/sacrificing-future-spending/

https://en.wikipedia.org/wiki/Unearned_income

Everything comes from nature.
We are not creating or destroying anything.
We are merely transforming things.
At least as seen from physics.

The number of atoms in Earth doesn't change.
(But what about solar wind? It does change a bit?)

Urban toilet harms humans and the Earth.
- We should poo squatting, not sitting.
- Urine and feces should be composted, not flushed down the drain.
- Compost bins should replace septic tanks.

https://www.vice.com/amp/en_us/article/zm95ka/republicans-are-outraged-about-the-deficit-they-caused

https://en.wikipedia.org/wiki/Unrestricted_Warfare
** Dan Lok
3 Types Of Employees (grunt, mercenary, and patriot) - How To Hire
https://www.youtube.com/watch?v=kILJN6eu1P8

How To Build Systems In Your Business - Systemize Your Business Ep. 7
https://www.youtube.com/watch?v=2g6sTH8FiFY

Kingpin strategy: Sell to the person who matters, who can bestow you authority, everyone else follows;
"The One Thing You Can Do To Grow Your Business And Sales Faster"
https://www.youtube.com/watch?v=M33aMYxuY60

How To Get What You Want - 3 Proven Persuasion Tactics
https://www.youtube.com/watch?v=nLA_T1AXd6o

* Get more physical power
- Exercise
* Make our own Web browser that gives us full programmable control of what we see
- Fix the Internet from the user side
  - Block cookies from Medium, New York Times, Harvard Business Review, etc.
  - Fix Pinterest and Quora
  - Block all third-party ads
  - Try HTTPS first when the user enters a URL without a protocol scheme
** Designing a web browser
*** Why stop at web browser?
What we want is not a web browser.
What we want is a user interface for the Internet.

We should dream more about the browser.
We should have an Information Agent instead of a browser.
But this risks scope creep; we'll end up making an operating system.
Indeed Firefox and Chrome has already done that with Firefox OS and Chrome OS.[fn::https://www.quora.com/Why-did-the-Chrome-OS-succeed-but-the-Firefox-OS-failed]

The browser should also be a crowd-sourced search engine and a peer-to-peer web hosting?

Opennic
https://mastodon.ar.al/@aral/101714998469668580

Rethinking the web browser

https://refresh.study
*** What is the most important thing of a web browser?
The user is in full control of everything, including the content displayed to him.
The user can program the browser to transform badly-designed websites.
The user should not need to install a plugin such as Greasemonkey, Tampermonkey,
or any other "user script manager" to have full control of what is displayed.
*** Why do browsers have history?
What is the chance that the user asks one of these:
- What did I just browse?
- What did I browse yesterday?

What is the chance that the user wants to revisit something?

I myself often need that.

https://www.computerhope.com/issues/ch001871.htm
*** How hard is it to secure a browser?
Very hard.

We may think that API A is secure and API B is secure,
but when we use them together, A+B may not be secure.
 [fn::https://www.ghacks.net/2018/11/04/browser-history-sniffing-is-still-a-thing/]

How do we make systems whose security is composable?

How do we prove that a system is secure?
How should we model security?

\cite{barthe2017provably} is a possibility.
But what if new unforeseen side-channel attacks appear in the future?

We must model the time and energy usage of each CPU instruction.
But the CPU is not open source?
*** Parts of a browser
- cache and history
- HTTP
- HTML parsing
- rendering HTML DOM to GUI widgets

What we choose /not/ to do:
- plug-ins, extensions
- themes, customizations

Who are going to maintain the plugins?

Should we just embed WebKit?

https://www.paulirish.com/2013/webkit-for-developers/
*** Search engine?
Is AntRank[fn::http://www.ijettcs.org/Volume3Issue2/IJETTCS-2014-04-23-113.pdf] usable?

I find YaCy[fn::https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html] unusable:
its search result relevance is too far behind Google.
YaCy-related things
 [fn::https://loklak.org/ Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]
 [fn::https://chat.susi.ai/ SUSI.AI Chat - Open Source Artificial Intelligence]
seem to also suffer from usability issues.

Unfortunately, it's 2019, NAT is still common, and I don't see IPv6 anywhere near my computer.

Perhaps it is a bad idea to allow /every/ device to be connected to the Internet.
Weakly-passworded IP cameras were hijacked and put into a botnet.
*** Why don't users use distributed systems?
Users don't care; they want software to just work.[fn::"Decentralized systems will continue to lose to centralized systems until
there's a driver requiring decentralization to deliver a clearly superior consumer experience."
http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html]

We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
The pack might contain things like matrix.org, riot.im.
But why stop there?
Why not make free/libre distributed operating system[fn::https://en.wikipedia.org/wiki/Distributed_operating_system] with all those goodies preinstalled?

Example of federated/decentralized social networks:
Kari Nordmann's comment[fn::https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc]:
"Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo)"
