#+TITLE: Understand productivity
#+DATE: 2019-05-14 00:00 +0700
#+OPTIONS: ^:nil toc:nil
#+PERMALINK: /produce.html
* Productivity, output, morality
** What is productivity?
Productivity is /output per input/.

Thus productivity is like /efficiency/.

Dividing two quantities is easy.
Measuring input is also easy.

Defining /output/ is hard.
We ascribe anthropocentric purposes to things.
What should output be?
What moral system should we use to define output?

For example, a machine produces goods, but it also produces heat, pollution, losses, and waste.

Output should be a function of /quantity/ and /quality/,
but perhaps not a simple multiplication.
If quality is too low, quantity does not matter, because no buyer wants it.
If quality is too high, it does not matter, because no buyer can perceive the quality difference.

What is /quality/?

The ability to produce, or the ability to /satisfy consumers/?
Producers don't produce for the sake of production.
Producers keeps producing because there is unsatisfied demand.

Aren't we putting too much emphasis on consumption?

Quality is an arbitrary number?
Subjective?

100 oranges at quality 20 vs 50 oranges at quality 40?

100 room-cleaning at quality 50 vs 50 room-cleaning at quality 100?

The output of a machine is defined by the machine's designer.

The output of a system is defined by the system's designer.
** Where does the word "productivity" come from?
- productivity[fn::https://en.wiktionary.org/wiki/productivity] ← productive + -ity[fn::https://en.wiktionary.org/wiki/-ity]
- productive[fn::https://en.wiktionary.org/wiki/productive] ← prōductīvus
- prōductīvus[fn::https://en.wiktionary.org/wiki/productivus] ← prōdūcō + -īvus[fn::https://en.wiktionary.org/wiki/-ivus]
- prōdūcō[fn::https://en.wiktionary.org/wiki/produco] ← prō-[fn::https://en.wiktionary.org/wiki/pro-] + dūcō[fn::https://en.wiktionary.org/wiki/duco]

In 2019, "to produce"[fn::https://en.wiktionary.org/wiki/produce][fn::https://www.etymonline.com/word/produce]
means "to make".

"Productive" means:
- /related/ to producing
- /tending/ (having a tendency) to produce[fn::https://en.wiktionary.org/wiki/-ive]

"Productivity" means:
- the /state/ of being productive[fn::https://en.wiktionary.org/wiki/-ity]
- a /measure/ of someone's ability to produce
  (this definition parallels the definition of
  conductivity[fn::<2019-05-07> "Measure of a material's ability to conduct an electric current"
  https://en.wikipedia.org/wiki/List_of_physical_quantities] in physics)
- http://www.thefreedictionary.com/words-that-end-in-ivity
- https://en.wikipedia.org/wiki/Sensitivity_and_specificity
- In economics, productivity is output per unit of labor.
  [fn::http://www.thefreedictionary.com/productivity]
- "Productivity describes various measures of the efficiency of production.
  A productivity measure is expressed as the /ratio of output to inputs/ used in a production process, i.e. output per unit of input."
  [fn::<2019-05-07> https://en.wikipedia.org/wiki/Productivity]
  (emphasis mine)

What are the inputs of software production process?
- man-hour
- machine-hour
- electricity
* Why should we care about productivity and not only profit?
Productivity increases /wealth/.
Profit increases /richness/.

Productivity is /real/.
Profit is /nominal/.

Productivity is about /value/.
Profit is about /price/.

Productivity does not always mean profitability.

For example, a farmer may produce a lot of oranges, but when the demand for oranges is low,
he may not be able to sell his excess production for profit.
* Consumption and satisfaction
People consume to satisfy themselves.

Consumption is the dual of production.

Satisfaction is the dual of quality.
** Consumption is everywhere
Production is not exactly the opposite of consumption.
Production itself consumes some input to produce some output.
* What should be produced?
We should produce /goods/.
What is /good/ depends on which /moral system/ we subscribe to.

If we subscribe to /utilitarian/ ethics,
we should produce what maximizes the /total satisfaction of the population/.
However, an utilitarian is okay with killing 1,000 people to save 1,000,000 people.

Profit maximization is utilitarian?

If we subscribe to /hedonist/ ethics,
we should produce what brings us the most joy when we produce it.
** Why do we want productivity?
** Examples of false or unwanted productivity
Examples of false productivity that feels good but only wastes time:
- Checking off lots of unimportant things from a to-do list.
- Sorting files and folders that we rarely use.

Productivity is about long-term profit.
Forced labor is productive only in the very short term.

Examples of unwanted productivity:
- Manufacturing as much hardware as possible with unacceptable defect rate.
- Writing as much software as possible with unacceptable unmaintainability.
** Is productivity increase good or desirable?
** Is sustainability more important than productivity?
* Where does software operation and maintenance fit in the big picture of productivity?
Once created, software has to be operated.
Software operation has costs.
* How does technology improve productivity?
Technology enables a person to control more things.
With bare hands, a person can control 10 kg.
With power tools, a person can control 100 kg.

- https://en.wikipedia.org/wiki/Productivity_improving_technologies
* Measure productivity?
** Is it possible? Is it practical?
What does it mean to measure productivity?

It is impractical to trace all the causal chains.

It is easy to compare factory worker productivity between such workers because:
- The causal chain is very simple and short.
- The interaction between factory workers do not affect each worker's productivity.
- The environmental factors (machines, lighting, etc.) are constant and identical for all workers.

A knowledge worker's productivity is affected by peer interaction.

In order to measure a programmer's productivity, he must first be isolated from everyone else.
But is this isolation enough?

If both A and B are necessary causes of C,
then A or B alone is not sufficient to cause C.
Each of A and B is a causal factor (necessary but not sufficient).
The cause of C cannot be reduced to either A or B.
Both of them are necessary to cause C.
For example, in the fire triangle, all of fuel, oxygen, and heat are necessary to cause fire.
The cause of fire cannot be reduced to any strict sub-combination of those three factors.

Measuring producitivity requires understanding causality.

It is not as simple as blaming the proximate (the nearest) cause.
For example, suppose a smoker in a gas station causes an explosion.
The blame is /largely/, but not /entirely/ on the smoker,
because the smoker alone is not enough to cause the explosion:
the explosion requires gasoline vapor,
which is caused by the existence of the gas station,
which is caused by the demand for gas,
which is caused by other car owners,
and so on.
In the end, all of humanity shares a little blame, although negligible.
** When is line of code a valid measure?
Line of code (LOC) can be a valid measure if they are /normalized/ first,
like purchasing-power-parity adjustment in currency exchange rates.

One atomic statement per line.

LOC is valid for the same language with the same coding style.

1 LOC of C cannot be equated with 1 LOC of Java, in the same way we cannot equate 1 kilogram and 1 pound.
** Complexity points? Story points? Function points?
- What the hell are we trying to measure?
- What should we care about?
  We only care about /how long it takes to make/.
** What does a software engineer do?
- Find out what the user really wants.
- Formalize user requirements.
** How do we compare programmers/code?
- correctness of the system
- maintainability of the system
- efficiency of the system
- time taken to implement the system
** How do we measure developer productivity?
- 2004 article "Defining and measuring the productivity of programming languages" [[https://pdfs.semanticscholar.org/1852/9ff58460b6238f5095af073d8505d79d3264.pdf][pdf]]:
  - It defines these metrics:
    - "the time and effort required to write, debug, and tune the code"
    - "the performance of the code that results"
  - power-efficiency graph (human efficiency and machine efficiency)
  - what else?
- 2008 https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/Web/Planning/productivity.html
  - https://ifs.host.cs.st-andrews.ac.uk/Books/SE9/
- 1992 article https://www.andrews.edu/~vyhmeisr/papers/progprod.html
- 2012 article http://www.drdobbs.com/jvm/the-comparative-productivity-of-programm/240005881
  - "A database comparing 6,000 projects shows that the choice of programming language has a significant impact on project schedule."

State of the art[fn::https://en.wikipedia.org/wiki/Programming_productivity]?

\cite{karimi2016links}
** What?
- 2015, PhD thesis, Bergersen, "Measuring Programming Skill: Construction and Validation of an Instrument for Evaluating Java Developers"
  - [[http://folk.uio.no/gunnab/publications/Bergersen2015_PhD_thesis.pdf][pdf]]
  - It's a collection of 4 articles.
  - https://www.duo.uio.no/handle/10852/48583
** Ideas?
** How do we measure the productivity of services producers?
The same way we measure the productivity of goods producers?
