#+TITLE: On developing psychic abilities
#+DATE: 2019-10-01 00:00:00 +0700
#+PERMALINK: /psychic.html
* Examples of psychic abilities
<2019-10-28> https://en.wikipedia.org/wiki/List_of_psychic_abilities

That article looks balanced, which is an exception in the pseudoskeptic-infested Wikipedia.
However, apparently that page got vandalized quite often, so beware.

This website[fn::<2019-10-29> https://paranormal.lovetoknow.com/List_of_Psychic_Abilities] has a partial list but it does not look convincing.
* Driving questions
** How do I alter my state of consciousness without drugs?
** If psychic healing is possible, what about psychic body-building?
If psychic healing is possible, then perhaps these things are also possible:
psychic body-building,
psychic penis-lengthening,
psychic wrist-enlargement, and
psychic selective-fat-burning?
** What do I need to awaken psychic powers?
I think I only need two things: myself and time.
** Claims to test
#+BEGIN_QUOTE
Having accumulated enough jing, you no longer think of sex;
having accumulated enough qi, you no longer feel hungry;
having accumulated enough shen, you no longer need to sleep.
<2019-10-03> https://www.thedaobums.com/topic/28199-taoist-proof-that-we-cant-ignore/
#+END_QUOTE
** My questions and hypotheses
Is fasting necessary for psychic?

Does myopia interfere with astral travel?
If you have poor vision, are you doomed to have poor psychic vision?
How does psychic vision even work?
What are the eyes for when we are out-of-body?
Do congenitally blind people see when they astral-travel?

If everybody is supposed to be psychic, but in reality few people are psychic, then, what is preventing most people from being psychic?

Is it possible for mediums to contact a soul from the /future/?

If remote viewing and reincarnation are possible, then perhaps there should exist souls /in the future/ or /from the future/.

Robert Bruce's advice[fn::<2019-10-29> "NEVER Make These Mistakes On The Astral Plane" https://www.youtube.com/watch?v=bRYHmniQnA8] for astral travel beginners:
As one is about to leave the body, one must stay calm and focused, and not get excited.
* On beginner resources for psychic power, spiritual journey, etc.
Understanding Hypnosis with Stanley Krippner[fn::<2019-10-03> https://www.youtube.com/watch?v=-P23o32pHwQ]
** <2019-09-30> International Academy of Consciousness?
IAC claims that someone can obtain some very basic psychic abilities in /three hours/ with the /right technique/.
  [fn::<2019-09-30> https://uk.iacworld.org/how-long-does-it-take-to-develop-psychic-abilities/]
But what is the right technique?

It assumes you're in England or Spain.

I have an unpleasant experience with the website.
I tried to download their ebook, but it requires me to subscribe, so I did that, and then the website experiences an internal error, after asking for my personal data.

It seems mostly legitimate with some questionable things and yellow flags.
It sells courses.

The only free thing there is a semi-marketing introduction video behind a login wall.

It gives me a bad first impression.
