#+TITLE: The truth about psychics
#+DATE: 2019-09-02 00:00:00 +0700
#+PERMALINK: /psychic.html
Welcome, fellow truth-seekers.

We have a problem: Google's search result for psychic-related queries is full of disinformation that hampers our research.
I hope this article can change that.
I also hope to change the majority opinion and hasten the scientific research on psychic abilities.
* Definitions
** Psychics
A /psychic/ is a person with [[https://en.wikipedia.org/w/index.php?title=List_of_psychic_abilities&oldid=928270792][psychic abilities]].

A /psychic claimant/ is a person who /claims/ to have psychic abilities.
The truth of the claim is unknown, so we give the benefit of the doubt.

A /pseudopsychic/ (a fake psychic) is a psychic claimant whose claims are known to be totally or mostly false.

A /cold reader/ is one who does [[https://en.wikipedia.org/wiki/Cold_reading][cold reading]],
which is fine until a cold reader claims to be a psychic
whereas he/she is in fact a pseudopsychic.
The problem is not cold reading.
The problem is that many people claim to be what they are not.

How do we know someone is psychic?

Psychics give mostly true and /highly improbable/ statements that we think they cannot know,
whereas cold readers guess highly probable statements that everyone can know from collecting statistics.
Psychics may not be 100% accurate, but they should be more accurate than guessers.
Cold reading is totally explained by probability and psychology,
such as [[https://en.wikipedia.org/wiki/Barnum_effect][Barnum/Forer effect]],
[[https://en.wikipedia.org/wiki/Subjective_validation][subjective validation]],
and [[https://en.wikipedia.org/wiki/Confirmation_bias][confirmation bias]].
** Skeptics
A /skeptic/ is a doubter (in a good sense), someone who is looking for the truth,
someone who does not know, but would like to know.
Skeptics change their beliefs according to evidence,
after exhausting simpler explanations, including mistakes.

A /debunker/ is someone who exposes false claims.
The problem is: they only look for false claims and not true claims.

A /scientist/ is a skeptic who uses [[https://en.wikipedia.org/wiki/Scientific_method][the scientific method]].

A /pseudoskeptic/ (a fake skeptic) is a person who claims to be a skeptic but is not.
There are several kinds of pseudoskeptics:
- /[[https://en.wikipedia.org/wiki/Cover_your_ass][Ass-covering]] pseudoskeptics/ cave in to peer pressure.
  They fear being ostracized by their peers.
  They fear for their careers.
  They are reluctantly complicit in oppressing the truth.
  They are powerless.
  They mostly stay silent, but they occasionally affirm their allegiance when they are suspected of heresy.
- /Narcissistic pseudoskeptics/ doubt other people's beliefs but never doubt their own beliefs.
  They only accept evidence that is compatible with their beliefs.
  They have become the very thing they sought to destroy.
  Skeptics would instead rejoice when evidence falsifies their beliefs,
  because it means that they are inching toward the truth.
- /Science despots/ have built their careers, found comfort in their position,
  and settled to refuse any changes, the truth be damned.
  They can be found in all fields, not only in psychic research.
  They don't care about the truth; they only care about their comfort.

It is useless to try to change pseudoskeptics.
Instead, ignore them, and shout louder: write more about the truth, and muster fellow truth-seekers.

Science is not the truth, but is the search for the truth.

The problem of science despots is summarized by [[https://en.wikiquote.org/wiki/Max_Planck][Planck 1949]]:
#+BEGIN_QUOTE
A new scientific truth does not generally triumph by persuading its opponents and getting them to admit their errors,
but rather by its opponents gradually dying out and giving way to a new generation that is raised on it.
#+END_QUOTE
We see again the pattern: The biggest problem is that many people from all camps (psychics and skeptics)
claim to be what they are not.

There is [[https://en.wikipedia.org/w/index.php?title=Fringe_science&oldid=927262305][evidence]] that science is despotic.
* Overview of psychic research
What are people researching today, related to psychic functioning / paranormal phenomena / non-locality?

What experiments?

What devices?
How do they work?
What is the underlying theory?

There are two approaches / classes:
- inside-out (mind-first, subjective, introspectionist, esoteric),
- outside-in (body-first, objective, extrospectionist, exoteric).

Both may use the scientific method.
Both are equally legitimate if they are done with careful language and scientific method.
Both camps should collaborate to form a more complete science.
* Overview of evidence
** Experiments
(To do: Find others' experiments, or do it ourselves. We need more of this.)

The oldest reported remote viewing experiment seems to be
[[https://en.wikipedia.org/wiki/Croesus#Croesus'_votive_offerings_to_Delphi][Herodotus's account of Croesus's experiment on the oracles]],
some time in the 6th century BC.
It is double blind!

May, Spottiswoode, et al. researched how several physical phenomena (geomagnetic activity, sidereal time, entropy) affect psychic functioning.
** Reports, stories
I claim nothing about the strength of these pieces of evidence for psychic functioning.
It may be less satisfactory that they are subjective first-person experience reports.
However, if the reporters do not stand to gain by lying,
we should not dismiss them only because their reports seem improbable.

Kieruff & Krippner 2004 book "Becoming psychic: Spiritual lessons for focusing your hidden abilities"
is Kieruff's personal experience plus Krippner's academic commentary.
It combines reports, stories, guides, academic commentary, and a short list of psychics and organizations.

[[https://www.near-death.com/paranormal/ghosts.html][Ghosts of Flight 401]].
There are many independent witnesses, sometimes with corroboration, so they are unlikely to be hallucinating.

Russell Targ wrote his experience in his book "The Reality of ESP: A Physicist's Proof of Psychic Abilities".
It is his account of the remote viewing research in the CIA Stargate program.

Eben Alexander wrote his near-death experience in his book "Proof of Heaven: A Neurosurgeon's Journey into the Afterlife".
Bacteria [[https://www.cdc.gov/meningitis/bacterial.html][feasted]] on his brain.
He tried to tough out the early signs which felt like ordinary headache, so he got hospitalized a bit too late when it was already too severe.
When doctors scanned his brain, they saw no hope:
he would die or, at best, be disabled.
He fell into coma.
But, [[https://en.wikipedia.org/wiki/Spontaneous_remission][against all odds]], he survived and recovered to tell his experience.
He considered how some materialistic hypotheses fail to explain the experience he had when his neocortex was not functioning.

John Roncz's 2012 "An Engineer's Guide to the Spirit World: My Journey from Skeptic to Psychic Medium"?
Some [[https://www.amazon.com/product-reviews/B008S4YYWA/?filterByStar=three_star][bad reviews]].

- mit.edu domain?
  - https://www.mit.edu/people/rei/spir.html
  - https://www.mit.edu/people/rei/spir-help.html

People who were in the military:
Joseph McMoneagle,
[[http://www.bswett.com/spirit.html][Ben Swett]].

Braude 2003 \cite{braude2003immortal}?

Joseph McMoneagle's book: "Mind Trek: Exploring Consciousness, Time & Space through Remote Viewing".
Interestingly, his out-of-body experience interferes with his remote viewing.

Ingo Swann's book "Remote Viewing: The Real Story, An Autobiographical Memoir"

Are [[https://www.alienlady.com/][Mary Rodwell]]'s [[https://www.youtube.com/watch?v=E3MQ3-CAV4Y]["super psychic kids"]] evidence for aliens?
Nancy du Tertre's 2015 book "How to Talk to an Alien" has some [[https://www.amazon.com/product-reviews/1632650215/?filterByStar=two_star][bad reviews]]?
Is [[talkalien.com]] real?
** Circumstantial evidence for remote viewing
(Perhaps "remote viewing" should be renamed to "non-local perception" to be more accurate?
"Remote viewing" is more like "remote sensing".)

If remote viewing had not worked, I think the USA government would have terminated it before they had spent /twenty million dollars/ in /twenty years/.
(Source?)

But instead their research resulted in protocols.

Everyone can strictly follow a protocol and judge for themselves.

Remote viewing merits scientific investigation because it can be replicated by strictly following a protocol.

Daz Smith has a history of remote viewing in the USA:
[[http://www.remoteviewed.com/remote_viewing_history_military.htm][Stargate archive]]
and [[http://www.remoteviewed.com/rvhistorymap.html][remote viewing visual history]].

See also Ingo Swann's book, and Russell Targ's book.
** Things that can be explained away as normal
Some seemingly paranormal phenomena turn out to have normal explanations.

Vic Tandy found that infrasound around 19 Hz may induce fear, shivering, and visual artifacts due to eyeball resonance.
(via [[https://www.reddit.com/r/todayilearned/comments/d2oebj/til_about_vic_tandy_an_engineer_who_established_a/][Reddit]] and [[https://en.wikipedia.org/wiki/Vic_Tandy#Work_with_infrasound][Wikipedia]])
* Rectified Google search results
Around 2019-11-28,
I searched Google for these queries:
[[https://www.google.com/?q=psychic][psychic]],
[[https://www.google.com/?q=psychic+evidence][psychic evidence]].
The results are full of disinformation.

Here I clean up the results.
Beware that you may get [[https://en.wikipedia.org/wiki/Filter_bubble][different]] results.
** Dictionaries, definitions, and lists
There are some dictionary definitions of "psychic".
Those in [[https://dictionary.cambridge.org/dictionary/english/psychic][Cambridge]] and [[https://www.ldoceonline.com/dictionary/psychic][Longman]] are correct and unbiased.
Those in [[https://www.merriam-webster.com/dictionary/psychic][Merriam-Webster]] and [[https://www.dictionary.com/browse/psychic][Dictionary.com]] are biased with words like "apparent" or "alleged".
Those in [[https://en.wiktionary.org/wiki/psychic][Wiktionary]] are cowardly imprecise ("A person who possesses, or appears to possess [...]").

There is Wikipedia's [[https://en.wikipedia.org/wiki/List_of_psychic_abilities][list of psychic abilities]],
which is surprisingly neutral, although that page sometimes gets vandalized.
** Devices
Gary Schwartz is making SoulSwitch, [[https://www.thesoulphonefoundation.org/][SoulPhone]], etc. for people to communicate with their discarnate relatives.
I have not yet looked at his research, but I hope he is moving toward the truth.
(via [[https://www.soulproof.com/soulphone-want-call/][soulproof.com]] on 2019-12-02)
** Organizations
http://opensciences.org/
** Other things that may be relevant to my research
There is a [[https://www.insidehighered.com/news/2016/11/17/science-journal-withdraws-paper-suggested-evidence-some-people-are-psychic][news article about a retraction]]
of an article that has insufficient evidence.

There is a quite damning [[https://www.reddit.com/r/AskReddit/comments/29041r/serious_psychics_of_reddit_do_you_knowingly_scam/][inside story of the pseudopsychic industry]].
(Remember to mentally replace "psychic" with "pseudopsychic".)

Russell Targ's book is more relevant but Google ranks it lower.
** Detrimental Wikipedia articles
There is a [[https://en.wikipedia.org/wiki/Psychic][mistitled Wikipedia article]]
which is about psychic claimants, not psychics.
A [[https://en.wikipedia.org/w/index.php?title=Talk:Psychic&oldid=921672968#%22A_psychic_is_a_person_who_claims...%22][complaint]] was raised in 2015,
but four years later there was still no progress.
Such idiosyncratic redefinition prevents people from thinking about psychics.

Wikipedia [[https://en.wikipedia.org/wiki/Wikipedia:Verifiability,_not_truth][reflects the majority opinion]],
and while they are mostly true, they are not the truth.
The job of Wikipedia admins is to [[https://en.wikipedia.org/wiki/Thought_Police][enforce policy]] according to majority opinion, not to find out the truth.
As a result, some editors [[https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Editor_Retention/Discovered_reasons_given_for_leaving_Wikipedia][quit]].

/Thus, to change Wikipedia, change the majority opinion./

Majority does not mean right; it simply means having power to decide which discourses are taboo;
but truth respects no feelings or taboos.

Wikipedia itself says that it is [[https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_is_not_a_reliable_source][unreliable]],
so why do we insist on trusting it so much?
Perhaps because the website looks authoritative at a glance.
** Other things of no use to my research
There is someone's [[https://www.theguardian.com/society/2019/apr/22/psychics-how-a-sceptic-found-solace-in-clairvoyance][venting]].
Her beliefs blind her from seeing things as they are.
However, at least she is open to new experiences.
** Advertisement-laden pages of no use to my research
These websites earn money mostly or solely from ads.
More traffic means more money;
hence [[https://en.wikipedia.org/wiki/Sensationalism][sensationalism]]
and [[https://en.wikipedia.org/wiki/Clickbait][clickbait]] titles.

There is a [[https://blogs.scientificamerican.com/illusion-chasers/two-neuroscientists-walk-into-a-psychic-fair/][low-information field report with clickbait title]].
It does not matter whether they are neuroscientists
if they are not using any neuroscience in the article.
The premise also doesn't make sense.
If I were looking for psychics, I would first visit my friends who have psychic experiences, not a psychic-claimant fair.
However, at least they are open to new experiences.

This [[https://www.thecut.com/2018/07/so-are-psychics-real-or-what.html][shallow inconclusive misrepresentative article]] is overly [[https://en.wikipedia.org/wiki/Search_engine_optimization][SEO]]-ed:
three ads in the page, an image that does not add any information,
many links to high-authority websites, but no original insight, just a rehash of the linked articles.
Also, the crystal ball image is highly insulting to psychics.

There is a [[https://www.nytimes.com/2019/03/19/style/wellness-mediums.html][mistitled cynical news on medium claimants]], although there may be some truth to it.

There is a [[https://www.buzzfeednews.com/article/ingridrojascontreras/life-lessons-from-my-mom-the-psychic][novel chapter writing exercise]],
if you enjoy short stories.
** Advertisements of no use to my research
There is an ad about "Kasamba psychic chat", of which an ex-pseudopsychic
[[https://www.reddit.com/r/IAmA/comments/gzww4/iaman_internet_psychic_ama/c1rjl1y/][wrote]] in 2011:
"Think of it like an ebay for bullshit."
I visited the website, and I can see why.

There is an ad about a $649 "Shiva god helmet", but perhaps we can meditate for $0 to get a similar profound experience.
To me, it is at best an expensive crutch.
* You can help: speak, write, and think correctly
** No need to assume conspiracy
Our problems are mostly due to intellectual laziness and sloppy language.

An example of intellectual laziness is to blindly trust claims, be it from scientists or others.

An example of sloppy language is to conflate "psychic" and "psychic claimant".
** Use language precisely
Stop calling pseudopsychics "psychics".

Use "psychics" only for psychics.

Use "psychic claimant" for someone you would like to give the benefit of the doubt.

Use the definitions in the "Definitions" section of this document.

Call people what they are, not what they claim to be.
** Think non-binarily
The next step after linguistic precision is /non-binary thinking/.

The question is not: /Are/ you psychic?

The question is: /How psychic/ are you?

Ten percent? Fifty percent?
** Insist that others also speak, write, and think correctly
Always agree on the definitions before talking.

Gently expose incorrect thinking by raising questions that will make the offender realize the incorrect thinking without losing face.

No need for public debates.

Stay civil and polite.
* People who research psychic phenomena
* People in STEM researching psychic phenomena
** A list of some people
(To do: Integrate a summary of their works into this article. Do not just list them.)

I do not know whether these people actually have STEM background.
I do not personally know these people.
When I write "X is Y", you should interpret it as "The author thinks that X claims to be Y", unless I provide evidence;
otherwise my writing would be unreadably verbose.

(Note: I include psychology in STEM.)

[[http://www.psychicengineer.com/PE_am.htm][Richard King]] is a chartered engineer, a healer, and a psychic.

[[https://thedynamicstate.wordpress.com/][Brian Slartsani]] ([[https://www.youtube.com/watch?v=0ntav0LA9Yg][video]])
is a computer programmer experimenting in altered states of consciousness.
He tries to come up with a theory for his astral projection research.

[[https://psi-encyclopedia.spr.ac.uk/articles/ingo-swann][Ingo Swann]], and the people he met:
Russell Targ, Hal Puthoff, Karlis Osis, Cleve Backster, Edwin May, Gertrude Schmeidler, Carole Silfen, Charles Tart, etc.

Edgar Mitchell, Andrija Puharich, etc.
See also [[https://www.bibliotecapleyades.net/sociopolitica/hambone_info/index1.htm#People_menu][Doc Hambone's people and places]].
** <2019-11-27> Calling all STEM people with personal psychic experiences
STEM = Science, Technology, Engineering, Mathematics

Who are STEM people who have personal psychic experiences?
 [fn::<2019-11-27> https://noetic.org/blog/engineers-scientists-report-psychic-experiences/]
Some of them are
Russell Targ (he has witnessed some psychic phenomena;
his website[fn::<2019-09-17> http://www.espresearch.com/] has some links[fn::<2019-09-17> http://www.espresearch.com/links.shtml])
and Alan Hugenot (where did he learn mediumship?).

Among those STEM people, who have theories and experiments?

Gathering the STEM people may speed up the next scientific revolution.

The theory does not have to be stated in terms of mainstream physics.
The theory simply has to explain/predict some psychic aspects of reality,
and we can marry the theory and mainstream physics later.

Consciousness research is long overdue, but I think it is at least speeding up.

[[https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0208384][Sauermann et al. 2019]]: Crowdfunding scientific research: Descriptive insights and correlates of funding success

[[experiment.com]] is a science crowdfunding website, but as of 2019 it has no psychic research.

[[crowd.science]] is another science crowdfunding website.

[[a list of 5 science crowdfunding websites][https://www.thebalancesmb.com/top-sites-for-crowdfunding-scientific-research-985238]]
** <2019-11-27> On funding psychic research, and on working around the brokenness of how we do science
While we wait for the old guards to die,
we can ask the crowd to fund our psychic/paranormal research.
It would be even better if we could force those old guards to retire early
as they have become the very thing they sought to destroy in their youth.
It seems that the way we do science in the 21st century
corrupts open-minded youths into close-minded old guards.
There is something wrong with the system.
"Publish or perish" make people game citations.
Proposals take too much effort to write and, even worse,
the grants are awarded to "safe-bet" researches that have slim chance of discovering anything important.

Our way of doing science is systematically broken:
old guards have too much power,
grants are not allocated to enough varieties,
people are too attached to theories,
and the majority is too risk-averse.
For faster progress, science should be anarchistic.

[[https://en.wikiquote.org/wiki/Shut_up_and_calculate]["Shut up and calculate"]] leads to a massive short-term gain but long-term dead end.
Theoretical physicists should also identify and relax the simplifying assumptions, not just tinker with mathematics.
Theoretical physics is not a branch of mathematics.
Theoretical physics is a combination of philosophy and mathematics.
* Things I highly doubt
I'm not saying that these are false; I just highly doubt them.
** International Academy of Consciousness
<2019-09-30>

IAC [[https://uk.iacworld.org/how-long-does-it-take-to-develop-psychic-abilities/][claims]]
that someone can obtain some very basic psychic abilities in /three hours/ with the /right technique/.
But what is the right technique?

It assumes you're in England or Spain.

I have an unpleasant experience with the website.
I tried to download their ebook, but it requires me to subscribe, so I did that, and then the website experiences an internal error, after asking for my personal data.

It seems mostly legitimate with some questionable things and yellow flags.
It sells courses.

The only free thing there is a semi-marketing introduction video behind a login wall.

It gives me a bad first impression.
** Spiritual Science Research Foundation
<2019-11-28>

I feel that [[https://www.spiritualresearchfoundation.org/][SSRF]] is a bit off.
Despite its name, I don't see any science in its website; no theories, no explanations, no experiments, only instructions and claims.
Some people even
[[https://www.quora.com/Is-Spiritual-Science-Research-Foundation-SSRF-brainwashing-people-with-their-so-called-spiritual-research][think]]
that SSRF is brainwashing.
** Farsight Institute
<2019-11-28>

Farsight Institute claims to have remote-viewed [[https://farsight.org/FarsightPress/Moses_Beyond_Exodus_Farsight_Project_main_page.html][Moses]]
and [[http://farsightpresentations.com/RV_Projects/CrucifixionRuse.html][Jesus]].
Those are some big claims.
* On poorly chosen words
ESP (Extra-Sensory Perception) is an oxymoron:
If you can perceive it, you have a sensor for it; you just don't know what the sensor is.
Perhaps ESP should be renamed to EOP ("/Extra-Ordinary/ Perception").
Alas, the term has stuck, but words mean whatever we choose them to mean anyway, so let's stick with ESP.

The word "supernatural" is absurd:
If it exists, then it is natural, because Nature is defined to be everything that exists.
We should replace "supernatural" with "extraordinary", "unusual", "unexplained", or "anomalous".
* Bibliography
