#+TITLE: On developing psychic abilities
#+DATE: 2019-10-01 00:00:00 +0700
#+PERMALINK: /psychic.html
* Examples of psychic abilities
<2019-10-28> https://en.wikipedia.org/wiki/List_of_psychic_abilities

That article looks balanced, which is an exception in the pseudoskeptic-infested Wikipedia.
However, apparently that page got vandalized quite often, so beware.

This website[fn::<2019-10-29> https://paranormal.lovetoknow.com/List_of_Psychic_Abilities] has a partial list but it does not look convincing.
* On beginner resources for psychic power, spiritual journey, etc.
Robert Bruce's advice[fn::<2019-10-29> "NEVER Make These Mistakes On The Astral Plane" https://www.youtube.com/watch?v=bRYHmniQnA8] for astral travel beginners:
As one is about to leave the body, one must stay calm and focused, and not get excited.

Understanding Hypnosis with Stanley Krippner[fn::<2019-10-03> https://www.youtube.com/watch?v=-P23o32pHwQ]
** <2019-09-30> International Academy of Consciousness?
IAC claims that someone can obtain some very basic psychic abilities in /three hours/ with the /right technique/.
  [fn::<2019-09-30> https://uk.iacworld.org/how-long-does-it-take-to-develop-psychic-abilities/]
But what is the right technique?

It assumes you're in England or Spain.

I have an unpleasant experience with the website.
I tried to download their ebook, but it requires me to subscribe, so I did that, and then the website experiences an internal error, after asking for my personal data.

It seems mostly legitimate with some questionable things and yellow flags.
It sells courses.

The only free thing there is a semi-marketing introduction video behind a login wall.

It gives me a bad first impression.
