#+TITLE: Looking for a publishing system
#+DATE: 2018-01-01 03:08:00 +0700
#+AUTHOR: erik
#+PERMALINK: /publish.html
* Current system
The page you are looking at is written in Org Mode, and then converted to HTML with Pandoc and a Pandoc Lua filter.
My only reason for using Org Mode is its Outline Mode.
* What I have tried
I tried Org Exporter; it was too slow.
On <2019-01-01>, I tried [[https://github.com/pandoc-scholar/pandoc-scholar][pandoc-scholar]], but it was too slow for my needs; I need to routinely convert my website.
Thus I wrote a Pandoc Lua filter to translate org mode to jekyll html.
It is still somewhat slow, but its output is acceptable.
The alternative is to switch from Org to Markdown, but find a Markdown editor that can fold sections[fn::https://vi.stackexchange.com/questions/9543/how-to-fold-markdown-using-the-built-in-markdown-mode].
Set up vim markdown folding, or get a markdown editor that can fold sections, maybe vscode.
I prefer vim to emacs because I can move around much faster in vim.
Vim is designed for motion.
Emacs is designed for extensibility.
I could also use regex to replace org =***= with markdown =###= as a preprocessing step before calling Pandoc,
but I would rather have a non-hacky long-term solution.
I think I will need to reimplement some of Jekyll + Pandoc + Org in Prolog.
* Write a Prolog static site generator to translate Org-Mode and Markdown to HTML
I need a publishing system, preferably written in Prolog.
** Features, goals, and constraints
This basically reimplements some of Pandoc in Prolog.

I need this big yak shaving because:
- I need citations in my file:proglang.org.
- I don't trust Emacs.
- I don't trust org-ref.
- I don't trust the interaction between org, pandoc, and pandoc-citeproc.
- I feel Emacs is too slow.
- I hate editing and compiling Pandoc; GHC is slow.
- Markdown is not enough.

Problem:
- pandoc can't read org metadata/directives?

The constraints:
- The user edits the file using unmodified Emacs Org-Mode.

Work breakdown:
- citeproc? bibtex? biblatex? bibliography management?
- Citing from website.
- The program exports the Org files to HTML for web publishing without using the slow Emacs Org Exporter.
- Parse LaTeX begin end environment.
- YAML metadata preamble.
- Generate local table of contents for each section that has more one or more child.
- word count, to replace page numbers as navigation aid
- Why bibtex?
  Because Google Scholar exports bibtex.
  We can then just copy the bibtex fragment from Google Scholar.
- Parse Org Mode.
  - Inline: bold, italic, underline, code, at-at-html.
  - Heading.
  - Block: EXAMPLE, SRC, HTML
  - Syntax highlighting in code blocks?
    We skip this because this is not essential.

VERY IMPORTANT: the ability to handle citations without slowing down everything

We can use http://www.swi-prolog.org/pack/list?p=bibtex

We are going to use LMX instead of https://github.com/SWI-Prolog/packages-ltx2htm
** ?7d: Implement LMX (LaTeX-Markdown-XML) markup language
LMX is a LaTeX-like surface syntax for XML;
this enables you to replace the closing tag with a closing brace.

LMX is a combination of Org-Mode.

#+BEGIN_EXAMPLE
This is a paragraph.
Separate a paragraph with a blank line.

This is another paragraph.

- This is a list.

\passthru{
WHAT.
}

\cite{foo}

\bibliography

LMX \Tag[Attr1=Val1,Attr2=Val2]{Content} translates to XML <Tag Attr1=Val1 Attr2=Val2>Content</Tag>
\ul{
  \li{This is the first item.}
  \li{This is the second item.}
}

\div[class=foo]{
  \div[class=bar]{
  }
}

Curly braces quote/escape attribute values.
\Tag[Attr={,}]
\Tag[Attr={[}]
\div[data-foo=4123]{}
\h1{bar}
\img[src=foo.png]


Escape a curly brace by prepending a backslash.
\Tag[Beg=\{,End=\}]{}

\table{
  \tr{\td{Foo}\td{Bar}}
}

inline math \( 1 + 2 \)

environments
\begin{align}
1 + 2 &= 3
\\
4 + 5 &\neq 6
\end{align}

\strong{\em{strong emphasized text}}

\p{This is an example paragraph. It may contain \em{emphasis}.}
\p{ Leading and trailing whitespaces are stripped away. }
\p{\ Backslash-space escapes a space that would otherwise be ignored.}

HTML entities:

\nbsp expands to &nbsp;
#+END_EXAMPLE

Difference from TeX/LaTeX:
- In TeX, "\a b" inserts no space.
  We insert a space.
  If you don't want a space, write "\a{}b" or "{\a}b".
- In LaTeX, you use "\bibliography{FILE}".
  In LMX, you use "\bibliography",
  and specify the FILE from the command line or from Prolog code.

Similar but not the same
1999 "TEXML: Typesetting XML with TEX"
https://www.tug.org/TUG99-web/pdf/lovell.pdf

"SXML: an XML document as an S-expression"
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.729.3639&rep=rep1&type=pdf

R markdown
https://bookdown.org/

LaTeX syntax for XML.
#+BEGIN_EXAMPLE
\tag[attr1=val1,attr2=val2]{content} = <tag attr1="val1" attr2="val2">content</tag>
\amp = &amp;
\e{amp} = &amp;
#+END_EXAMPLE
Make a semantic-LaTeX parser/interpreter in Prolog.
Treat LaTeX as declarative markup language and not imperative command language.
- escaping comma https://tex.stackexchange.com/questions/70986/comma-in-macro-parameters
- escaping square brackets https://tex.stackexchange.com/questions/6683/escaping-square-braces
- escaping curly braces https://tex.stackexchange.com/questions/181118/how-to-escape-curly-braces-within-texttt
