#+TITLE: Questions at my knowledge frontier
#+DATE: 2019-11-04 00:00:00 +0700
* On remote viewing, psychic/spiritual development/unfolding, and meditation
** <2019-11-04> How does remote viewing work?
Puthoff 1996 \cite{puthoff1996cia}
 [fn::<2019-11-04> https://pdfs.semanticscholar.org/5326/d58231f3d0080249d82d830061c116bf7931.pdf]
 [fn::<2019-11-04> backup link https://peshakoffstudio.com/storage/2016/06/CIA-Initiated-Remote-Viewing-program-at-Stanford-Research-institute..pdf]

See the 2003 book "Psi Wars: Getting to Grips with the Paranormal"?
*** <2019-11-03> On a book of Tim Rifat
I read the book "Remote Viewing" (or whatever the title is) by Tim Rifat
 [fn::<2019-11-03> https://www.bibliotecapleyades.net/vision_remota/esp_visionremota_9.htm]
 [fn::<2019-11-02> backup link http://www.pauladaunt.com/books/Banned%20books%20and%20conspiracy%20theories/Remote%20Viewing%20By%20Tim%20Rifat.pdf]
 [fn::<2019-11-02> backup link http://fliphtml5.com/yfsq/knbz].

Here are some of his hypotheses:
- Remote viewing may require that the brain be in the "theta state"
- Stress levels may "have to be lowered for paranormal abilities to show themselves"
- Stress may interfere "with the mechanism of remote viewing"
- "Autovisualization of the brain" may induce "the states needed for remote viewing"
- Tesla coils tuned to 7.8 Hz[fn::<2019-11-03> https://en.wikipedia.org/wiki/Schumann_resonances] may induce "a theta state in the remote viewer"

He also proposes some procedures and experiments:
- a relaxation technique[fn::<2019-11-03> https://www.bibliotecapleyades.net/vision_remota/esp_visionremota_9e.htm]
- "a specialized technique [...] to enter the theta state without electronic biofeedback"[fn::<2019-11-03> https://www.bibliotecapleyades.net/vision_remota/esp_visionremota_9f.htm]
- a meditation technique he calls "the cinema method"[fn::<2019-11-03> https://www.bibliotecapleyades.net/vision_remota/esp_visionremota_9g.htm]
  - "The cinema method is such a powerful technique because it uses the potent meme of watching television to eradicate the internal-chatter meme.
    Since both memes are very powerful, they cancel each other out"
- "Try to stop thinking to yourself for ten seconds. You will find that internal mental silence is extremely difficult to achieve."

He also has hypotheses about brains and quantum stuff but I skipped them because I lack the necessary background knowledge.

Unfortunately the Google search result for "theta wave" is full of snake-oil sellers.
*** <2019-11-04> On a 2007 book of Morehouse
Morehouse 2007 \cite{morehouse2007remote}

I did not understand Chapter 4.
It seems as if he needed to use math but he were afraid that math would scare readers,
so he dumbed it down, but it seems that he overdid it.

Begin reading at Chapter 5.

He hypothesizes that reality has eight dimensions.
Where is the details of that hypothesis?
Did he know Garrett Lisi's E8 hypothesis?
** <2019-11-04> How can one learn mediumship?
Where did Alan Hugenot learn mediumship?
** <2019-11-02> How do we induce theta waves in the brain?
Meditation?
Hypnosis?

Can we induce theta waves without drugs?
*** <2019-11-04> Experiment in rapid periodic shifting of attention
If brain theta wave frequency is 4 Hz[fn::<2019-11-02> https://en.wikipedia.org/wiki/Theta_wave],
then, can we induce theta waves in the brain by repeatedly-and-rapidly shifting our attention (a few times per second)?
For example, we pick two spots in our head, say X and Y, and we focus on X for T seconds (let T = 0.25 or 0.5 perhaps?),
then we focus on Y for T seconds, and then we focus back on X for T seconds, and so on.

Can we induce theta waves by imagining 4 Hz beat frequency?
Visual beat frequency?
Aural beat frequency?
** <2019-09-28> How do we alter consciousness without drugs? With meditation?
Tart 1975[fn::<2019-10-29> http://www.psychedelic-library.org/soccont.htm]

I think, if the consensus reality of adults are fixed,
then the only hope for adults with clashing consensus realities
is either mass-segregation or mass-murder.
** <2019-10-01> If psychic healing is possible, what about psychic body-building?
If psychic healing is possible, then perhaps these things are also possible:
psychic body-building,
psychic penis-lengthening,
psychic wrist-enlargement, and
psychic selective-fat-burning?
** <2019-10-01> What hampers psychic functioning?
If everybody is supposed to be psychic, but in reality few people are psychic, then, what is preventing most people from being psychic?

Some blame memes (mind viruses, upbringings).
** <2019-10-01> Are there souls from the future?
Is it possible for mediums to contact a soul from the /future/?

If remote viewing and reincarnation are possible, and if time is non-linear, then perhaps there should exist souls /in the future/ or /from the future/.
** <2019-09-28> Is meditation effective for entering alpha state in noisy environment?
Is there an EEG of a meditator in noisy environment?
* <2019-11-04> On psi research around the world
How advanced was Soviet psi research compared to American psi research, in the Cold War era?

<2019-11-04> https://www.lfr.org/subtle-energies

Is the Soviet LIDA machine real?[fn::<2019-11-04> http://www.cheniere.org/books/aids/newviewmind.htm]
Does it work?
Was the Soviet really that advanced?

<2019-11-04> https://psi-encyclopedia.spr.ac.uk/articles/psi-research-russia

See the 2015 book "ESP Wars: East & West"?

<2019-11-04> https://www.newdawnmagazine.com/articles/the-changing-face-of-russian-psi-research

Which is real, and which is disinformation?

The USA and the USSR try to play mind tricks on each other with disinformation.

Chinese psi research?
https://psi-encyclopedia.spr.ac.uk/articles/psi-research-china

Japan?
https://www.encyclopedia.com/science/encyclopedias-almanacs-transcripts-and-maps/japanese-society-parapsychology

https://www.mind-energy.net/archives/1388-parapsychology-research-in-china-is-on-the-rise.html
* On the requirements of psychic functioning
I think the key is an altered state of consciousness;
I think meditation, hypnosis, drugs, and others are crutches for achieving an altered state of consciousness.

The question:
- How many states of consciousness are there?
- What is an altered state of consciousness?
- Which altered state of consciousness do we want for psychic functioning?

Develop psychic abilities with hypnosis?[fn::<2019-11-04> https://makemindpowerful.com/can-develop-psychic-abilities-deep-hypnosis/]
** <2019-11-04> Does psychic functioning require meditation?
I think psychic functioning requires an altered state of consciousness, not meditation,
and meditation is just one way of achieving an altered state of consciousness without material crutches.

- It seems that the consensus is that developing psychic abilities requires [[file:meditate.html][meditation]] (having a still-and-focused mind).
  Why is that? "To raise vibrational frequencies"?
  Do people with poltergeists meditate inadvertently?
- Are psychic abilities just energy works?
  - Robert Bruce's "N.E.W. Energy Ways"?[fn::<2019-10-29> http://www.innerworlddesigns.com/circle/book12/pdf/Robert%20Bruce%20-%20New%20Energy%20Ways.pdf]
  - Nathaniel's writings?
  - secret to magick: anchor and link?[fn::https://robjo.files.wordpress.com/2007/10/stam.pdf]
** <2019-10-01> Is fasting necessary for psychic?
** <2019-10-01> What do I need to awaken psychic powers?
I think I only need two things: myself and time.
** <2019-10-01> Does myopia interfere with astral travel?
If you have poor vision, are you doomed to have poor psychic vision?
How does psychic vision even work?
What are the eyes for when we are out-of-body?
Do congenitally blind people see when they astral-travel?
* On consciousness
** <2019-11-04> What is the problem with Kastrup's idea (individual consciousness dissociates from cosmic/universal consciousness)?
I got that idea from somewhere.
I need to find the citations.

If I am the only thing that exists, why can't I make the world do what I want?
Two possibilities:
- I am not the only thing that exists, or
- I am not who I think I am; perhaps it is just my linguistic mind, which is only a part of me, and not I, that wants it, and thus it does not happen.

Perhaps solipsism is right but our concept of "I" is wrong.

Bernardo Kastrup proposes a solution to the mind-body problem.
He proposes an ontology that is "more parsimonious and empirically rigorous" than mainstream ontologies are.
 [fn::<2019-09-13> https://www.freewiki.eu/en/index.php?title=Bernardo_Kastrup]
 [fn::<2019-09-13> What Can We Learn From Bizarre Phenomena? with Bernardo Kastrup https://www.youtube.com/watch?v=tWpKB7n4dRs]
 [fn::<2019-09-13> https://www.bernardokastrup.com/p/papers.html]
The key is the brain activity of people with /dissociative identity disorder/.
 [fn::<2019-09-13> https://blogs.scientificamerican.com/observations/could-multiple-personality-disorder-explain-life-the-universe-and-everything/]

Its simplicity is genius?

It has deep implications.
If it becomes mainstream, we will witness a paradigm shift.

It explains all paranormal phenomenons: reincarnation, anomalous cognition, psychokinesis, and so on.

Perhaps it also answers Brian D. Josephson[fn::http://www.tcm.phy.cam.ac.uk/~bdj10/]'s "mind-matter unification project".

The difference between Kastrup and other philosophers is that his theory is based on /empirical evidence/,
whereas other theories are based on thought experiments.
Thus, I think we can just read Kastrup directly, skip Chalmers 2018 \cite{chalmers2018meta},
and skip the Part IV of a 2001 thick book \cite{moreira2011exploring}.
Or perhaps I'm just in a honeymoon with a shiny new thing.

What is it like, the subjective experience of the cosmic consciousness?
** <2019-10-31> What are the problems with Thomas Metzinger's transparent self-model?
<2019-10-31> https://www.edge.org/response-detail/10461

Metzinger 2004 \cite{metzinger2004being}:

#+BEGIN_QUOTE
[...] Its main thesis [...] Nobody ever /was/ or /had/ a self. [...] (p. 1)
#+END_QUOTE

Materialist?
** <2019-11-04> Why do brains have functional areas?
Why do all human brains follow the same layout/architecture/blueprint?

Because we share a common genetic code?

For example, does everyone have a fusiform gyrus?

Does each fusiform gyrus have the same relative location in each brain
and have the same relative function (i.e. facial recognition) in each brain?

Does everyone have a prefrontal cortex?

Because they are programmed to do so?
The genes are the program?

Perhaps the question should have been:
Why do brains have functional areas?
Why is processing not spread evenly throughout the brain?

Can evolution answer that?

Perhaps to answer that, we have to understand how the brain evolved.

Does dividing/compartmentalizing/specializing the brain into functional areas promote survival?

\cite{kanwisher2010functional}[fn::<2019-11-04> https://www.pnas.org/content/107/25/11163]
** <2019-11-04> How does the brain work?
Practopoiesis?
Cybernetics?
Adaptive systems?

Friston free-energy hypothesis?
** <2019-11-04> How did the brain evolve?
** <2018-11-04> How do we measure consciousness (ability to know)?
How do we measure whether X has more consciousness than Y?

/Degree of consciousness is a continuum./

I was conscious when I wrote this.
There was a time after I was born but before I became conscious.
There isn't any point in time when I suddenly become conscious.

- [[https://www.quora.com/Do-babies-have-consciousness][Quora: Do babies have consciousness?]]
  - [[https://en.wikipedia.org/wiki/Mirror_test][WP:Mirror test]] tests visual self-awareness.
  - [[https://www.youtube.com/watch?v=k-_Lgg2D4kM][YT:Self-recognition test, aka the 'Rouge Test': Johnny and Eden at 15 months]]
    - 15-month-old babies might fail the test.
- Glasgow coma scale, operational definition of consciousness
- /ConsScale/ is a biologically-inspired scale for measuring cognitive development in natural and artificial creatures. http://www.conscious-robots.com/consscale/
- what? https://resonance.is/quantum-experiment-test-human-consciousness-beyond-physical-world/
- How do we measure consciousness?
  - Extensional measurement
    - [[https://en.wikipedia.org/wiki/Glasgow_Coma_Scale][WP:Glasgow Coma Scale]]?
    - [[http://www.abiroh.com/en/what-science-has-forgotten/196.html][abiroh.com]]:
      detect consciousness by anomaly in the output of a hardware random number generator
    - Extensional measurement is unsatisfactory. It doesn't explain how consciousness works.
  - Intensional measurement?
    - [[https://en.wikipedia.org/wiki/Integrated_information_theory][WP:Integrated information theory]], 2004
*** Glasgow coma scale?
*** Tononi et al. zap-and-zip method
** <2019-11-04> Is there a neural correlate for poltergeist or telekinesis?
Poltergeist is due to the person, ghost is due to the place.

Poltergeist is unconscious telekinesis.

Is there a brain area or a pattern of brain activity responsible for poltergeists or telekinesis?
** <2019-11-04> Functional imaging of brain on telepathy?
What journal is this?
Who are these people?
2008 article "Investigating paranormal phenomena: Functional brain imaging of telepathy"\cite{venkatasubramanian2008investigating}.
** <2019-11-05> What are the implications of mediumship and disembodied consciousness?
* On traditions
** <2019-10-30> Are these legitimate: Daoism, Qigong, Neigong, Chinese stuff?
The pinyin spelling is "dao".

If Daodejing were a military manual, how on Earth did it become a bible?
 [fn::<2019-10-30> https://taoism101.wordpress.com/2013/02/12/tao-te-ching-bullshit/]
Or is it never a bible?

On fapping and jing

When ejaculating, does eating sperm preserve jing?

Are there psychics who have sex/fap a lot?
There are married psychics and they probably have sex?

Real stuff, ancient fiction, or modern misinterpretation?

Minimum jing requirement?
http://projectavalon.net/forum4/showthread.php?87212-Living-Nei-Kung-schools--the-story-of-John-Chang-

Evidence for jing, qi, shen, daoism?
How do we test it?

What?

https://www.aetherius.org/shop/unlock-your-psychic-powers/

https://flowingzen.com/17310/how-to-feel-qi-energy-without-waiting-years/

Claims to test:

#+BEGIN_QUOTE
Having accumulated enough jing, you no longer think of sex;
having accumulated enough qi, you no longer feel hungry;
having accumulated enough shen, you no longer need to sleep.
<2019-10-03> https://www.thedaobums.com/topic/28199-taoist-proof-that-we-cant-ignore/
#+END_QUOTE

What about the book \cite{danaos2000magus}?

It is Kosta Danaos's account of John Chang.

John was a level-4-of-72 neigong master at the time that book was written.

Kosta and John did some experiments and had some hypotheses about yin and yang.
** <2019-11-04> Is there scientific spiritualism?
How do we extract the scientifically testable parts of Daoism, Hinduism, Sufism, and other spiritual/mystical traditions?
Is Theosophy free from kooky stuff?
* <2019-11-04> Which IONS experiments are relevant to my research?
The Institute of Noetic Sciences (IONS) has /lots/ of experiments and plans.
 [fn::https://noetic.org/science/experiments/]
Quantum what.
 [fn::https://noetic.org/research/next-generation-double-slit/]
 [fn::https://noetic.org/research/multiple-entangled-photons/]
 [fn::https://noetic.org/research/missing-photon-experiment/]
 [fn::https://noetic.org/research/double-slit-experiment/]
 [fn::https://noetic.org/research/does-consciousness-interact-with-the-quantum-wavefunction/]
 [fn::https://noetic.org/research/quantum-observer-test/]
 [fn::https://noetic.org/research/entangled-photons/]
Healing what.
 [fn::https://noetic.org/research/consciousness-and-breast-cancer/]
Statistics what.
 [fn::https://noetic.org/research/implicit-beliefs-in-the-study-of-experimenter-effects-in-the-replication-of-psi-experiments-a-global-initiative/]
 [fn::https://noetic.org/research/analysis-of-gotpsi-data/]
Psychophysiology what.
 [fn::https://noetic.org/research/psi-performance-meditation-retreats/]
 [fn::https://noetic.org/research/extraordinary-experiences-and-performance-on-psi-tasks-during-and-after-meditation-classes-and-retreats/]
 [fn::https://noetic.org/research/accuracy-and-neural-correlates-of-blinded-mediumship-compared-to-controls/]
 [fn::https://noetic.org/research/psychophysiological-correlates-of-nondual-states-of-awareness/]
 [fn::https://noetic.org/research/psychophysiology-spiritual-transmission-preliminary-investigation/]
 [fn::https://noetic.org/research/unconditional-love-in-silicon-valley/]
 [fn::https://noetic.org/research/reproductive-hormonal-status-as-a-predictor-of-precognition/]
Global what.
 [fn::https://noetic.org/research/collective-consciousness/]
 [fn::https://noetic.org/research/global-consciousness-project/]
What.
 [fn::https://noetic.org/research/effects-virtual-reality-awe/]
 [fn::https://noetic.org/research/ions-channeling-research-program/]
 [fn::https://noetic.org/research/compassionate-intention-prayer-distant-healing/]
 [fn::https://noetic.org/research/meeting-of-the-minds/]
 [fn::https://noetic.org/research/markov-chain/]
 [fn::https://noetic.org/research/psi-arcade/]
 [fn::https://noetic.org/research/gaias-dreams/]
 [fn::https://noetic.org/research/fred/]
 [fn::https://noetic.org/research/effects-of-distant-intention-on-water-crystal-formation/]
 [fn::https://noetic.org/research/psiq/]
 [fn::https://noetic.org/research/seeing-the-future/]
* <2019-11-05> If consciousness does not require brain, how do we explain the memory of spirits of dead people?
* <2019-11-05> How do we know whether the medium is really contacting the dead person or is merely accessing the Akashic records of/about the dead person?
* <2019-11-05> If elephants have more than neurons than humans, why, apparently, do humans make more variety of tools than elephants do?
* <2019-11-05> Are memory problems recall problems or storage problems?
We must distinguish between a problem /recalling/ memory and a problem /storing/ memory.
* <2019-11-05> Hypothesis: Temporal ordering enhances recall
I have hardship mentioning one hundred distinct words, although I know more than one hundred words.

But I can easily mention the names of most stores at the roads that I pass in my daily trip from my home to my office.

Hypothesis: It is easier to recall a /temporally ordered/ sequence (a sequence of events) than other kinds of sequences.

Or is that just a peculiarity of my way of thinking?

The next question:
How/why does temporal ordering enhance recall?

Story enhances recall?

I can easily mention most things in my home, if I am to mention them in the order that I see them when I walk around in my home,
because, to recall those things, I imagine myself walking around in my home.

I can hardly mention those things, if I have to order them by their names alphabetically, even though I think I know the things in my home.

Thus, it is possible to know something but unable to /recall/ it.

It is also possible to recall false memory.

We perceive time as an ordering of events near us.

How can I know how fast I am flying in the vast void of outer space, if there is nothing near me to compare my motion against?
* Bibliography
