#+TITLE: On religion
#+DATE: 2019-05-18 00:00:00 +0700
#+PERMALINK: /religion.html
#+OPTIONS: ^:nil
* What is religion?
Religion is a technology for communicating with God?
But we should not conflate religion and spiritualism?

Religion is a technology for controlling the mind?

Religion is a mental illness?
It can help people establish order and find peace.
It can help people do the contrary too.

If religions are technologies for communicating with God, then we need a better religion.

People should use religion to find God, not to be slaves to religion.
* The problem with the big religions
The big five religions share one fatal problem:
They do not provide a procedure for communicating with God.

Perhaps God is supposed to reply.

Perhaps God is transmitting, but we are not receiving.

From sociological/evolutionary/survival perspective,
religion promotes cooperation, promotes procreation,
and subdues the natural order of man as described by Hobbes.
Those outcomes are expected to increase the chance of survival,
and perhaps our ancestors evolved to be religious because it enhanced their survival.

But the evolutionary context of humanity has changed,
in the sense that, in the 21st century, the most probable threat to our extinction is ourselves.
However, religions have not keeped up with the change in the evolutionary context of humanity.
Indeed, most of the big religions are designed to resist changes.

Organized religions have to die.
If any good comes out of organized religions,
it is only because the good humans refuse to absolutely follow the organized religions
that have been corrupted by the centralization of power.

Religion has to be personalized (tailored to each person),
in the same way medicine has to be personalized,
because no two people respond equally to the same treatment.
* Some faith in one's own perception is necessary for living
It is impossible to live without any faith:
at least one has to believe that the reality in a few seconds yet to come
will be similar to the reality in the few seconds that have just passed;
at least one has to believe that his senses are reliable enough for survival;
at least one has to believe that what he perceives mostly corresponds to reality.

When I walk on a busy road, I do not know what I see or why I see,
but I have faith in myself that I will see whatever I need to see to avoid dying on the road.
* Science is a verifiable religion
It is simple to verify natural science; just run the experiments.
All scientists will find the same facts about Nature.

On the other hand, until we find a way to rewind time, we cannot verify religion and history;
we can only corroborate sources and reason by counterfactuals as to which explanation is most likely, given what we know.
If we don't know all the relevant facts, we will draw the wrong conclusion about the past.
* Plans?
- Understand religions historically and sociologically
  - Write a short article and share it on social media?
  - Give a lecture/seminar?
  - Answer these questions:
    - Who threw the first stone in the war between Israel and Palestine?
    - Why did the Crusades happen?
    - Who threw the first stone in the first Crusade?
    - How do Catholics rationalize their cognitive dissonance between papal infallibility and the unexemplary 10th century popes?
      - Protestantism as a reaction to corrupt 10th century Catholicism
- Understand the psychology of terrorism
  - Why does someone become a terrorist?
  - Why does someone become an ex-terrorist?
  - Are there non-religious terrorists?
- Measure religious fanaticism
- Eliminate religious extremism, fanaticism, and narrow-mindedness
* Religiosity causal chain?
- A child has a religion because its parents teach it that religion.
  - Parents may revolt if we forbid them from teaching religion to their children.
- A person leaves religion because he disagrees with the religion or how others practice it.
- A person wants to apply religion because he sees it as an ideal.
- Can we send subliminal messages on TV to make religions look bad?
- People are more religious in bad times because religion numbs the pain somewhat. Religion is a psychological painkiller. Religion is addictive.
  - If we give them real-pain killing drugs, will they replace their addiction?
- People are religious because they are afraid to think for themselves. They are afraid of the unknown?
- People are religious because they fear becoming irreligious.
- How do we passivate religious people?

Poor people are more religious?

But what about the middle-class/upper-class bombers, such as in 2019 Sri Lanka bombing, 2018 JAD Surabaya church bombing?
* Religion from evolution perspective
Why did we evolve to be religious?
What are the evolutionary advantages of religion?

Religion might have helped humans survive.

Religion, superstition, and folk tales had evolutionary benefit.

Before science, religion was humankind's best attempt at understanding reality.

Understanding reality helps survival.

The paranoid is more likely to survive.

Religion can be thought of as proto-science[fn::https://en.wikipedia.org/wiki/Protoscience].
 [fn::https://www.quora.com/To-what-extent-is-religion-proto-science-and-science-neo-religion]

Hypothesis about the origin of religions and the evolutionary benefit of religions?
- Religion evolved from folk tales.
- Religion evolved from our ability to personify things.
- Religion, superstition, and folk tales were the best tool for survival before modern healthcare.
- Superstition and religion helped people survive.
  Superstitious people are more paranoid and less likely to die for stupid reasons.
- Religion is learned paranoia and culturally-spread paranoia.
- https://en.wikipedia.org/wiki/Hundredth_monkey_effect
  - "The *hundredth monkey effect* is a hypothetical phenomenon in which a new behaviour or idea
    is claimed to spread rapidly by unexplained means from one group to all related groups
    once a critical number of members of one group exhibit the new behaviour or acknowledge the new idea."
* Hard websites
- Websites
  - [[https://www.biblegateway.com/][biblegateway.com: online Christian bible]]
    - [[http://www.evilbible.com/][Evil Bible .com -- Fighting Against Immorality in Religion]]
  - [[https://quran.com/][quran.com: online Islamic bible]]
    - [[http://wikiislam.net/wiki/Main_Page][wikiislam.net]]
  - [[http://whywontgodhealamputees.com/][Why Won't God Heal Amputees?]]
- Concepts
  - [[https://en.wikipedia.org/wiki/Supersessionism][WP:Supersessionism]]
  - [[https://en.wikipedia.org/wiki/Manifest_destiny][WP:Manifest destiny]]
  - [[https://en.wikipedia.org/wiki/Crusades][WP:Crusades]]
  - [[https://en.wikipedia.org/wiki/Simony][WP:Simony]]
  - [[https://en.wikipedia.org/wiki/Parody_religion][WP:Parody religion]]
- Lists
  - [[https://en.wikipedia.org/wiki/The_Bad_Popes][WP:The bad popes]]
  - [[https://www.quora.com/Who-was-the-most-corrupt-pope-in-the-history-of-Catholicism][Quora: Who was the most corrupt pope in the history of Catholicism?]]
  - [[https://en.wikipedia.org/wiki/Historicity_of_Jesus][WP:Historicity of Jesus]]
** About this post
    :PROPERTIES:
    :CUSTOM_ID: about-this-post
    :END:

This post contains serious questions but no answers.
The questions were made with complete respect to all religions.

*** How to benefit from the questions
     :PROPERTIES:
     :CUSTOM_ID: how-to-benefit-from-the-questions
     :END:

Answer them honestly in your mind.
You can choose to keep your answers to yourself,
so please be completely honest to yourself.

Please do not feel stupid.
Honesty is not stupidity.
Not being able to answer a question does not imply stupidity.

If you are a religious person and you answer the questions seriously,
then these are some possible outcomes:

1. You ignore these questions or refuse to answer them.
   If you think I'm just trying to confuse you,
   please know that I respect your time,
   and I'm trying to help you.
   The questions are hard because they are serious questions, not riddles.
   I'm sorry if what I thought would be good turns out to be bad for you.
2. You invent new rationalizations
   (
   e.g. the author is committing a logical fallacy,
   all good people can go to heaven regardless of their religion,
   all religions basically teach good things,
   my religion might not be the best but it's the one I'm most familiar with,
   etc.).

** The questions
*** Conversion
     :PROPERTIES:
     :CUSTOM_ID: conversion
     :END:

If a person leaves Islam and joins Christianity,
then Allah will punish him, but Jesus will save him,
so what will happen?

*** Correctness
     :PROPERTIES:
     :CUSTOM_ID: correctness
     :END:

- Is your religion /the/ correct religion?

  - If yes, are people with other religions unable to go to heaven?

    - If no, why don't you try their religions?
      Aren't you going to heaven regardless of which one yours is?

  - If no, why do you still believe in something you know is wrong
    instead of looking for the correct one?

    - If you think all religions are correct, why don't you try other religions?
      Aren't you going to heaven regardless of which one yours is?
    - If you think there's no such thing as /the/ correct religion,
      why do you have any religion at all?
      Why would you believe in something you know is not correct?
      Why would you gamble your afterlife?

If all people with religion can go to heaven,
why not choose the religion that requires
the least effort to go to heaven?

*** Experiments
     :PROPERTIES:
     :CUSTOM_ID: experiments
     :END:

If parents did not teach their children any religion,
what would the religion of those children be?

** Closing
    :PROPERTIES:
    :CUSTOM_ID: closing
    :END:

Thank you for answering the questions.
I wish you all the best.

** Undigested
    :PROPERTIES:
    :CUSTOM_ID: undigested
    :END:

- How do we measure religion?

  - By number of believers over time?

- How do religion spread?
- Why do family members tend to have the same religion?

  - If children choose their own religions, will they believe it more?

- Classification of people by religiosity

  - internal (can't be seen by others)

    - by degree of belief

      - non-believer
      - believer

  - external (can be seen by others)

    - by level of practice

      - non-practicing
      - practicing

    - by spreading

      - non-spreading
      - spreading

        - by forcing their children to the same religion
        - by proselytizing

- [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5602559/][Measuring Five Dimensions of Religiosity across Adolescence]]
- Attacking people's beliefs will activate their amygdala,
  resulting in fight-or-flight response?
- Every religion started out as something good.
  It civilized its community.
  However, after 1000 years, people got too attached to religion, and religion loses its benefits.

- To everyone, especially religious people:

  - Why do you let someone else decide what/how you should think?
** History of Islam?
Sayyid Ali Ashgar Razwy has written a free online book[fn::https://www.al-islam.org/restatement-history-islam-and-muslims-sayyid-ali-ashgar-razwy/]
about the history of Islam.
I need not write another one.
Some examples of his contents:
- "Contrary to popular notions, Arabia is not all a wilderness of sand."
- "One moment [the desert] may be deceptively benign and tranquil but the very next moment, it may become vicious, temperamental, menacing and treacherous like a turbulent ocean. "
- "Then came oil and everything changed.
  Saudi Arabia sold her first concession in 1923, and the first producing well was drilled in 1938.
  Within a few years, annual revenues from petroleum exceeded $1 million.
  The kingdom passed the $1 billion mark in 1970; the $100 billion mark in 1980."
- "Economically, the Jews were the leaders of Arabia.
  They were the owners of the best arable lands in Hijaz, and they were the best farmers in the country.
  They were also the entrepreneurs of such industries as existed in Arabia in those days, and they enjoyed a monopoly of the armaments industry."

/Islam civilized Arabia./
Before Islam, Arabia was a dangerous place to live.

- [[https://www.youtube.com/watch?v=BvkBlpfbFJM][Islam destroyed its own "Golden Age" - Neil deGrasse Tyson & Steven Weinberg - YouTube]]
  - There was Islamic Golden Age, but it ended tragically.
    - Are the Gulf Nations allergic to science?
    - What is the Muslim Brotherhood's idea of education?
  - [[https://en.wikipedia.org/wiki/Al-Ghazali][WP:Al-Ghazali]] has a role in the downfall.
  - [[https://en.wikipedia.org/wiki/Islamic_Golden_Age][Islamic Golden Age - Wikipedia]]
- [[https://www.meforum.org/articles/other/why-does-the-muslim-world-lag-in-science][Why Does the Muslim World Lag in Science? | Middle East Forum]], too long
** A fiction of Ali and Bob
  :PROPERTIES:
  :CUSTOM_ID: a-fiction-of-ali-and-bob
  :END:

Ali is a good Muslim.
Bob is a good Christian.
They are good friends.

But then Ali reads [[http://quran.com/74/42-47][Quran 74:42-47]],
and Bob reads [[https://www.biblegateway.com/passage/?search=John+3%3A16-20&version=NIV][John 3:16-20]].

Each of them wants to go to their respective heaven,
and as good friends, each of them also wants the best for the other,
which is for the other to go to heaven,
but they aren't sure whose heaven:
Ali's holy book implies that Bob is going to the Islamic hell,
and Bob's holy book implies that Ali is going to the Christian hell.

They can't bear the dissonance, but don't want to live as enemies either,
and they don't want to assume that their friend is wrong,
for such assumption would justify their converting their friend,
and they think the other won't like any proselytizing,
because they don't like being proselytized themselves,
and they won't do unto others what they don't want others to do unto them.
They don't want to reduce their friendship into mere tolerance;
thus they throw away their holy books and religions,
and they stay good friends until their death,
while still believing in a higher power.

*** Postscript
   :PROPERTIES:
   :CUSTOM_ID: postscript
   :END:

This is not the
argument from inconsistent revelations
(also known as the aptly named 'the problem of avoiding the wrong hell').
This story is about humanity, not gods.
** Religions in 2018
- https://www.theverge.com/2018/10/24/18018446/follow-jc-go-pokemon-go-clone-vatican
** Is there an advanced Islamic country?
https://www.google.co.id/amp/s/www.forbes.com/sites/quora/2013/01/08/why-have-the-islamic-countries-failed-to-develop-even-with-resources-like-oil-while-countries-with-no-resources-like-switzerland-have-flourished/amp/

Iran has nukes.
Nukes are advanced.
Is Iran not an advanced Islamic country?

TLDR: I don't have an answer.

What is an Islamic country?

We can classify countries into four categories:
- non-Islamic non-advanced country
- Islamic non-advanced country
- non-Islamic advanced country
- Islamic advanced country

What is an advanced country?

The problem is:
If there are enough religious extremists in a country,
then the whole country goes down.
The smart people die or move out, leaving only stupid people behind.
Stupid people beget more stupid people, deteriorating the country even faster.
People segregate themselves.

Forced democratization of a developing country only creates corrupt government.
For a government to be beneficial, the governed people must think critically.
The people of a developing country does not think critically.

Example of a developing country corrupted by forced democratization: Indonesia (and pretty much all developing countries).

Anyone who criticizes Islam risks death.
But one who rejects criticism is condemned to eternal backwardness.
If you are backward, you reject criticism.
If you reject criticism, you stay backward.
It's a vicious circle.
The only way out is waiting for backward people to die and be replaced with their children,
hopefully more open-minded and capable of critical thinking and introspection.
But the apple doesn't fall far from the tree.
The situation is extremely bleak.
We have billions of such people.

Immigrants tend to create parallel societies and don't integrate.

https://moralarc.org/why-islam-of-the-three-great-monotheistic-religions-one-did-not-go-through-enlightenment/
* Which religion has the best benefit-to-cost ratio?
I do not have the answer.

- There are 4200 religions.

  - [[https://en.wikipedia.org/wiki/List_of_religions_and_spiritual_traditions][WP:List]]

- 2018-05-26

  - We should choose the one with the highest return of investment.

    - The one with the least obligations but the most rewards.
    - Thus we should also make afterlife easier.
    - We should seek the one with the minimal rules, beliefs, rituals, commitments.
    - We have always been making life easier (by technology).

      - We should make afterlife easier too.

- [[https://www.quora.com/How-do-I-decide-which-religion-to-follow][Quora: How do I decide which religion to follow?]]

Here are some religions, ordered by personal benefit-obligation ratio, from the highest?

(Part of this was posted on https://www.reddit.com/r/indonesia/comments/6y5yvc/atheistagnostic_komodos_whatwhen_was_your/dmlscxr/)

For every pair of religions R1 and R2, there is always a sentence S such that S is true in R1 but S is not true in R2.
Therefore, it cannot be the case that both R1 and R2 are true.
Sometimes a religion is not even consistent.
A religion R is inconsistent iff there is a sentence S such that both S and the negation of S is in R.
[[https://www.google.com/search?source=hp&q=how+many+religions][There are 4200 religions.]]
They cannot all be true.
At most only one of them can be true.
It can also be the case that all of them are not true.

- (Feel free to contribute other religions.)
- Discordianism
- Zoroastrianism?
- [[https://en.wikipedia.org/wiki/Bah%C3%A1%27%C3%AD_Faith][WP: Bahá'í Faith]]
- Hinduism
- Buddhism (is Buddhism a religion?)
- Christianity:
  - believe in Jesus
  - Protestantism:
  - Lutheranism:
    - sola scriptura
    - sola fide
    - sola gratia
  - Catholicism:
    - believe in the Holy Trinity (Father, Son, and Holy Spirit)
    - Roman Catholicism:
    - Orthodox Catholicism:
- Islam (Sunni)
  - believe in Allah
  - believe in Muhammad
  - 5 prayers a day, with specific gestures
  - on Friday, the 2nd prayer is in a congregation in a mosque
  - dietary laws
    - can't eat pork
    - can't drink alcohol
- Judaism
  - dietary laws
    - can't eat pork
    - can't drink alcohol
    - can't eat meat and dairy in one meal
- Scientology
  - costs a lot of money?
- [[https://en.wikipedia.org/wiki/Heaven][WP: Heaven]]
- [[https://en.wikipedia.org/wiki/Religion][WP: Religion]]
- [[https://en.wikipedia.org/wiki/Comparative_religion][WP: Comparative religion]]
- [[https://en.wikipedia.org/wiki/Major_religious_groups][WP: Major religious groups]]
- [[https://sites.fas.harvard.edu/~pluralsm/affiliates/jainism/workshop/Worldrlgn.PDF][Pravin K. Shah: Comparison of Religions, Eastern and Western]]

Tal Peretz's "A Cost/Benefit Analysis of Religion's Effects in Society"[fn::https://www.academia.edu/31439019/A_Cost_Benefit_Analysis_of_Religions_Effects_in_Society]

Quora has an unanswered question.[fn::https://www.quora.com/If-all-religions-allow-us-to-reach-heaven-what-is-the-easiest-religion-to-practice-to-get-into-heaven]
* Does it matter when a religion was created?
Christianity was created in the 1st century.
Islam was created in the 7th century.
Discordianism was created in the 20th century.
Does it matter when a religion was created?
Does a religion take time to be a religion?
Why must a religion's founder die before the religion becomes widespread?

The second generation does not directly experience the creation of the religion.
They only have the stories told by the first generation.
The third generation is even further removed.
* <2019-11-03> On a mind trick for ignoring barking dogs; also on pain and suffering, cigarettes, self-sabotage, Buddhism, nihilism, calmness, love, and apathy
<2019-11-03>
Background:
A neighbor of mine has three dogs, but apparently she doesn't train them, so,
one of them, a light-brown Labrador retriever, routinely barks through the night, from 10pm to 3am.

Then it dawned on me:
Perhaps the Universe sent me such an incompetent neighbor to teach me a life lesson.

I learned a mind trick:
I pretend that the barking is something like wind and rain,
common natural phenomena that we often ignore.
Now, whenever that dog barks, I automatically think, "Oh, it's raining,"
and continue doing whatever I have been doing.

I still suffer the barking, but I no longer suffer /from/ the barking.

Buddha teaches that pain does not always necessarily cause suffering.

The following equation is attributed to Shinzen Young,
but I believe that it also has been and will be independently rediscovered by many other thinkers as well:

Suffering = Pain × Resistance (our desire to eliminate the pain)

Here is an example of two polar opposites:

The burning monk feels much pain but little suffering.

An insatiable person feels little pain but much suffering.

However, it's hard for me to use this mind trick for cigarette smoke,
because I hate the smell of cigarette smoke so much that it's hard for me to ignore it, because,
for me, it is the smell of smokers' hurting themselves,
smokers' hurting others, and companies' profiting from hurting people.

Cigarette smoke is the smell of humanity's self-sabotaging itself.

But why stop the mind trick at barking dogs and cigarette smokes?

Why not pretend that /my entire life/ is something like wind and rain too?

There is a danger of taking this too far.
For example, it does not seem right to me that
one may witness a crime and ignore it because one sees it as something like wind and rain.
It does not seem right to me to always let everything just be.

If one takes this too far, one becomes a passive observer, a zombie.

Is Buddhism just nihilism with some bells and whistles?

How do we distinguish between calmness and apathy?

One way to prevent calmness from turning into apathy is love?
* <2019-11-03> On Jesus, fruits, Christianity, reincarnation, and imperialism
I think a follower of Jesus can go a long way with these things from the bible:

To judge prophets by their fruits[fn::<2019-11-03> https://en.wikipedia.org/wiki/The_Tree_and_its_Fruits].
I think this means to judge them by what they do, not by what they say.
I think "prophets" includes Jesus himself, so I think we should judge Jesus by this same standard:
What are his fruits?

Are these his fruits?

<2019-11-03> https://en.wikipedia.org/wiki/Fruit_of_the_Holy_Spirit

Did Jesus ever claim that he was God?
If not, who invented the divinity of Jesus, and when?
Long after Jesus died?
 [fn::<2019-11-08> https://www.npr.org/2014/04/07/300246095/if-jesus-never-called-himself-god-how-did-he-become-one]

Swett 1968 has the idea that Jesus can free us from reincarnation.[fn::<2019-11-03> http://www.bswett.com/1968-04Reincarnation101.html]

<2019-11-03> https://en.wikipedia.org/wiki/Criticism_of_Jesus

Christianity bears both good fruits and bad fruits,
although we can argue that Christianity is not Jesusism.
For example, some of the unsavory fruits of Christianity
are in the Middle Ages: European imperialism and corrupt popes.

I think it is plausible that, in the Middle Ages,
Christianity was used to justify for colonization.

This cannot be generalized to all Christians,
but I can imagine the Middle-Ages train of thought went like this:
"We must 'save' the savages from eternal damnation, by making them believe in Jesus.
Oh, while we're at it, why don't we take home some spices with us?
Oh, there's some gold there, let's take it home too!
Oh, those men look strong, we can use some of them to row our boats home!
Wait, we can make money from this!
Don't worry about the savages; they owe us their lives for our saving them from eternal damnation!"

<2019-11-03> https://en.wikipedia.org/wiki/Christianity_and_colonialism

Some colonizers were even brazen enough to demand reparation money from the victims!

<2019-11-03> https://en.wikipedia.org/wiki/External_debt_of_Haiti

<2019-11-03> https://historibersama.com/colonial-reparations/

It is as if your neighbor occupies your house, uninvited;
and then you ask him to leave, and he asks you to pay!

It is as if you steal someone's belonging and sells it back to him!
* <2019-11-08> After seeing the history of Christianity ...
After seeing the history of Christianity, I can still have faith in Jesus, but I cannot have any faith in Christianity;
there are so many possibilities that Jesus's teachings may have been corrupted.

How much of Christianity is Jesus's teachings,
and how much is other people's inferences (about the bible, Jesus, etc.)?

I hypothesize that the ecumenical councils might have been about compromises, not about seeking the truth.

I hypothesize that Roman Catholicism could grow so big because it piggybacked the power of the Roman Empire,
not because it was particularly good or true or sensical or virtuous or anything.

Jesus in the Gospel said that prophets may be judged by their fruits.
You can see and judge for yourself the fruits of Christianity.

Are inquisitions, colonialism, and imperialism some fruits of Christianity?
* <2019-10-31> On mathematics, God, and fixed points
Perhaps God is a fixed point, an \( x \) such that \( f(x) = x \), for some \( f \).
But what should such \( f \) be?

What if \( f = x \)?

One example function \( f \) that satisfies \( f(f) = f \) is
an identity function whose domain is the set of all functions,
because \( id_F(id_F) = id_F \).
But is \( id_F \) the only solution?
