#+TITLE: Understand religion
#+DATE: 2019-05-18 00:00:00 +0700
#+PERMALINK: /religion.html
#+OPTIONS: ^:nil
* Plans?
- Understand religions historically and sociologically
  - Write a short article and share it on social media?
  - Give a lecture/seminar?
  - Answer these questions:
    - Who threw the first stone in the war between Israel and Palestine?
    - Why did the Crusades happen?
    - Who threw the first stone in the first Crusade?
    - How do Catholics rationalize their cognitive dissonance between papal infallibility and the unexemplary 10th century popes?
      - Protestantism as a reaction to corrupt 10th century Catholicism
- Understand the psychology of terrorism
  - Why does someone become a terrorist?
  - Why does someone become an ex-terrorist?
  - Are there non-religious terrorists?
- Measure religious fanaticism
- Eliminate religious extremism, fanaticism, and narrow-mindedness
* Religiosity causal chain?
- A child has a religion because its parents teach it that religion.
  - Parents may revolt if we forbid them from teaching religion to their children.
- A person leaves religion because he disagrees with the religion or how others practice it.
- A person wants to apply religion because he sees it as an ideal.
- Can we send subliminal messages on TV to make religions look bad?
- People are more religious in bad times because religion numbs the pain somewhat. Religion is a psychological painkiller. Religion is addictive.
  - If we give them real-pain killing drugs, will they replace their addiction?
- People are religious because they are afraid to think for themselves. They are afraid of the unknown?
- People are religious because they fear becoming irreligious.
- How do we passivate religious people?

Poor people are more religious?

But what about the middle-class/upper-class bombers, such as in 2019 Sri Lanka bombing, 2018 JAD Surabaya church bombing?
* Religion from evolution perspective
Why did we evolve to be religious?
What are the evolutionary advantages of religion?

Religion might have helped humans survive.

Religion, superstition, and folk tales had evolutionary benefit.

Before science, religion was humankind's best attempt at understanding reality.

Understanding reality helps survival.

The paranoid is more likely to survive.

Religion can be thought of as proto-science[fn::https://en.wikipedia.org/wiki/Protoscience].
 [fn::https://www.quora.com/To-what-extent-is-religion-proto-science-and-science-neo-religion]

Hypothesis about the origin of religions and the evolutionary benefit of religions?
- Religion evolved from folk tales.
- Religion evolved from our ability to personify things.
- Religion, superstition, and folk tales were the best tool for survival before modern healthcare.
- Superstition and religion helped people survive.
  Superstitious people are more paranoid and less likely to die for stupid reasons.
- Religion is learned paranoia and culturally-spread paranoia.
- https://en.wikipedia.org/wiki/Hundredth_monkey_effect
  - "The *hundredth monkey effect* is a hypothetical phenomenon in which a new behaviour or idea
    is claimed to spread rapidly by unexplained means from one group to all related groups
    once a critical number of members of one group exhibit the new behaviour or acknowledge the new idea."
* Hard websites
- Websites
  - [[https://www.biblegateway.com/][biblegateway.com: online Christian bible]]
    - [[http://www.evilbible.com/][Evil Bible .com -- Fighting Against Immorality in Religion]]
  - [[https://quran.com/][quran.com: online Islamic bible]]
    - [[http://wikiislam.net/wiki/Main_Page][wikiislam.net]]
  - [[http://whywontgodhealamputees.com/][Why Won't God Heal Amputees?]]
- Concepts
  - [[https://en.wikipedia.org/wiki/Supersessionism][WP:Supersessionism]]
  - [[https://en.wikipedia.org/wiki/Manifest_destiny][WP:Manifest destiny]]
  - [[https://en.wikipedia.org/wiki/Crusades][WP:Crusades]]
  - [[https://en.wikipedia.org/wiki/Simony][WP:Simony]]
  - [[https://en.wikipedia.org/wiki/Parody_religion][WP:Parody religion]]
- Lists
  - [[https://en.wikipedia.org/wiki/The_Bad_Popes][WP:The bad popes]]
  - [[https://www.quora.com/Who-was-the-most-corrupt-pope-in-the-history-of-Catholicism][Quora: Who was the most corrupt pope in the history of Catholicism?]]
  - [[https://en.wikipedia.org/wiki/Historicity_of_Jesus][WP:Historicity of Jesus]]
** About this post
    :PROPERTIES:
    :CUSTOM_ID: about-this-post
    :END:

This post contains serious questions but no answers.
The questions were made with complete respect to all religions.

*** How to benefit from the questions
     :PROPERTIES:
     :CUSTOM_ID: how-to-benefit-from-the-questions
     :END:

Answer them honestly in your mind.
You can choose to keep your answers to yourself,
so please be completely honest to yourself.

Please do not feel stupid.
Honesty is not stupidity.
Not being able to answer a question does not imply stupidity.

If you are a religious person and you answer the questions seriously,
then these are some possible outcomes:

1. You ignore these questions or refuse to answer them.
   If you think I'm just trying to confuse you,
   please know that I respect your time,
   and I'm trying to help you.
   The questions are hard because they are serious questions, not riddles.
   I'm sorry if what I thought would be good turns out to be bad for you.
2. You invent new rationalizations
   (
   e.g. the author is committing a logical fallacy,
   all good people can go to heaven regardless of their religion,
   all religions basically teach good things,
   my religion might not be the best but it's the one I'm most familiar with,
   etc.).

** The questions
*** Conversion
     :PROPERTIES:
     :CUSTOM_ID: conversion
     :END:

If a person leaves Islam and joins Christianity,
then Allah will punish him, but Jesus will save him,
so what will happen?

*** Correctness
     :PROPERTIES:
     :CUSTOM_ID: correctness
     :END:

- Is your religion /the/ correct religion?

  - If yes, are people with other religions unable to go to heaven?

    - If no, why don't you try their religions?
      Aren't you going to heaven regardless of which one yours is?

  - If no, why do you still believe in something you know is wrong
    instead of looking for the correct one?

    - If you think all religions are correct, why don't you try other religions?
      Aren't you going to heaven regardless of which one yours is?
    - If you think there's no such thing as /the/ correct religion,
      why do you have any religion at all?
      Why would you believe in something you know is not correct?
      Why would you gamble your afterlife?

If all people with religion can go to heaven,
why not choose the religion that requires
the least effort to go to heaven?

*** Experiments
     :PROPERTIES:
     :CUSTOM_ID: experiments
     :END:

If parents did not teach their children any religion,
what would the religion of those children be?

** Closing
    :PROPERTIES:
    :CUSTOM_ID: closing
    :END:

Thank you for answering the questions.
I wish you all the best.

** Undigested
    :PROPERTIES:
    :CUSTOM_ID: undigested
    :END:

- How do we measure religion?

  - By number of believers over time?

- How do religion spread?
- Why do family members tend to have the same religion?

  - If children choose their own religions, will they believe it more?

- Classification of people by religiosity

  - internal (can't be seen by others)

    - by degree of belief

      - non-believer
      - believer

  - external (can be seen by others)

    - by level of practice

      - non-practicing
      - practicing

    - by spreading

      - non-spreading
      - spreading

        - by forcing their children to the same religion
        - by proselytizing

- [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5602559/][Measuring Five Dimensions of Religiosity across Adolescence]]
- Attacking people's beliefs will activate their amygdala,
  resulting in fight-or-flight response?
- Every religion started out as something good.
  It civilized its community.
  However, after 1000 years, people got too attached to religion, and religion loses its benefits.

- To everyone, especially religious people:

  - Why do you let someone else decide what/how you should think?
** History of Islam?
Sayyid Ali Ashgar Razwy has written a free online book[fn::https://www.al-islam.org/restatement-history-islam-and-muslims-sayyid-ali-ashgar-razwy/]
about the history of Islam.
I need not write another one.
Some examples of his contents:
- "Contrary to popular notions, Arabia is not all a wilderness of sand."
- "One moment [the desert] may be deceptively benign and tranquil but the very next moment, it may become vicious, temperamental, menacing and treacherous like a turbulent ocean. "
- "Then came oil and everything changed.
  Saudi Arabia sold her first concession in 1923, and the first producing well was drilled in 1938.
  Within a few years, annual revenues from petroleum exceeded $1 million.
  The kingdom passed the $1 billion mark in 1970; the $100 billion mark in 1980."
- "Economically, the Jews were the leaders of Arabia.
  They were the owners of the best arable lands in Hijaz, and they were the best farmers in the country.
  They were also the entrepreneurs of such industries as existed in Arabia in those days, and they enjoyed a monopoly of the armaments industry."

/Islam civilized Arabia./
Before Islam, Arabia was a dangerous place to live.

- [[https://www.youtube.com/watch?v=BvkBlpfbFJM][Islam destroyed its own "Golden Age" - Neil deGrasse Tyson & Steven Weinberg - YouTube]]
  - There was Islamic Golden Age, but it ended tragically.
    - Are the Gulf Nations allergic to science?
    - What is the Muslim Brotherhood's idea of education?
  - [[https://en.wikipedia.org/wiki/Al-Ghazali][WP:Al-Ghazali]] has a role in the downfall.
  - [[https://en.wikipedia.org/wiki/Islamic_Golden_Age][Islamic Golden Age - Wikipedia]]
- [[https://www.meforum.org/articles/other/why-does-the-muslim-world-lag-in-science][Why Does the Muslim World Lag in Science? | Middle East Forum]], too long
** A fiction of Ali and Bob
  :PROPERTIES:
  :CUSTOM_ID: a-fiction-of-ali-and-bob
  :END:

Ali is a good Muslim.
Bob is a good Christian.
They are good friends.

But then Ali reads [[http://quran.com/74/42-47][Quran 74:42-47]],
and Bob reads [[https://www.biblegateway.com/passage/?search=John+3%3A16-20&version=NIV][John 3:16-20]].

Each of them wants to go to their respective heaven,
and as good friends, each of them also wants the best for the other,
which is for the other to go to heaven,
but they aren't sure whose heaven:
Ali's holy book implies that Bob is going to the Islamic hell,
and Bob's holy book implies that Ali is going to the Christian hell.

They can't bear the dissonance, but don't want to live as enemies either,
and they don't want to assume that their friend is wrong,
for such assumption would justify their converting their friend,
and they think the other won't like any proselytizing,
because they don't like being proselytized themselves,
and they won't do unto others what they don't want others to do unto them.
They don't want to reduce their friendship into mere tolerance;
thus they throw away their holy books and religions,
and they stay good friends until their death,
while still believing in a higher power.

*** Postscript
   :PROPERTIES:
   :CUSTOM_ID: postscript
   :END:

This is not the
argument from inconsistent revelations
(also known as the aptly named 'the problem of avoiding the wrong hell').
This story is about humanity, not gods.
** Religions in 2018
- https://www.theverge.com/2018/10/24/18018446/follow-jc-go-pokemon-go-clone-vatican
** Is there an advanced Islamic country?
https://www.google.co.id/amp/s/www.forbes.com/sites/quora/2013/01/08/why-have-the-islamic-countries-failed-to-develop-even-with-resources-like-oil-while-countries-with-no-resources-like-switzerland-have-flourished/amp/

Iran has nukes.
Nukes are advanced.
Is Iran not an advanced Islamic country?

TLDR: I don't have an answer.

What is an Islamic country?

We can classify countries into four categories:
- non-Islamic non-advanced country
- Islamic non-advanced country
- non-Islamic advanced country
- Islamic advanced country

What is an advanced country?

The problem is:
If there are enough religious extremists in a country,
then the whole country goes down.
The smart people die or move out, leaving only stupid people behind.
Stupid people beget more stupid people, deteriorating the country even faster.
People segregate themselves.

Forced democratization of a developing country only creates corrupt government.
For a government to be beneficial, the governed people must think critically.
The people of a developing country does not think critically.

Example of a developing country corrupted by forced democratization: Indonesia (and pretty much all developing countries).

Anyone who criticizes Islam risks death.
But one who rejects criticism is condemned to eternal backwardness.
If you are backward, you reject criticism.
If you reject criticism, you stay backward.
It's a vicious circle.
The only way out is waiting for backward people to die and be replaced with their children,
hopefully more open-minded and capable of critical thinking and introspection.
But the apple doesn't fall far from the tree.
The situation is extremely bleak.
We have billions of such people.

Immigrants tend to create parallel societies and don't integrate.

https://moralarc.org/why-islam-of-the-three-great-monotheistic-religions-one-did-not-go-through-enlightenment/
* Which religion has the best benefit-to-cost ratio?
I do not have the answer.

- There are 4200 religions.

  - [[https://en.wikipedia.org/wiki/List_of_religions_and_spiritual_traditions][WP:List]]

- 2018-05-26

  - We should choose the one with the highest return of investment.

    - The one with the least obligations but the most rewards.
    - Thus we should also make afterlife easier.
    - We should seek the one with the minimal rules, beliefs, rituals, commitments.
    - We have always been making life easier (by technology).

      - We should make afterlife easier too.

- [[https://www.quora.com/How-do-I-decide-which-religion-to-follow][Quora: How do I decide which religion to follow?]]

Here are some religions, ordered by personal benefit-obligation ratio, from the highest?

(Part of this was posted on https://www.reddit.com/r/indonesia/comments/6y5yvc/atheistagnostic_komodos_whatwhen_was_your/dmlscxr/)

For every pair of religions R1 and R2, there is always a sentence S such that S is true in R1 but S is not true in R2.
Therefore, it cannot be the case that both R1 and R2 are true.
Sometimes a religion is not even consistent.
A religion R is inconsistent iff there is a sentence S such that both S and the negation of S is in R.
[[https://www.google.com/search?source=hp&q=how+many+religions][There are 4200 religions.]]
They cannot all be true.
At most only one of them can be true.
It can also be the case that all of them are not true.

- (Feel free to contribute other religions.)
- Discordianism
- Zoroastrianism?
- [[https://en.wikipedia.org/wiki/Bah%C3%A1%27%C3%AD_Faith][WP: Bahá'í Faith]]
- Hinduism
- Buddhism (is Buddhism a religion?)
- Christianity:
  - believe in Jesus
  - Protestantism:
  - Lutheranism:
    - sola scriptura
    - sola fide
    - sola gratia
  - Catholicism:
    - believe in the Holy Trinity (Father, Son, and Holy Spirit)
    - Roman Catholicism:
    - Orthodox Catholicism:
- Islam (Sunni)
  - believe in Allah
  - believe in Muhammad
  - 5 prayers a day, with specific gestures
  - on Friday, the 2nd prayer is in a congregation in a mosque
  - dietary laws
    - can't eat pork
    - can't drink alcohol
- Judaism
  - dietary laws
    - can't eat pork
    - can't drink alcohol
    - can't eat meat and dairy in one meal
- Scientology
  - costs a lot of money?
- [[https://en.wikipedia.org/wiki/Heaven][WP: Heaven]]
- [[https://en.wikipedia.org/wiki/Religion][WP: Religion]]
- [[https://en.wikipedia.org/wiki/Comparative_religion][WP: Comparative religion]]
- [[https://en.wikipedia.org/wiki/Major_religious_groups][WP: Major religious groups]]
- [[https://sites.fas.harvard.edu/~pluralsm/affiliates/jainism/workshop/Worldrlgn.PDF][Pravin K. Shah: Comparison of Religions, Eastern and Western]]

Tal Peretz's "A Cost/Benefit Analysis of Religion's Effects in Society"[fn::https://www.academia.edu/31439019/A_Cost_Benefit_Analysis_of_Religions_Effects_in_Society]

Quora has an unanswered question.[fn::https://www.quora.com/If-all-religions-allow-us-to-reach-heaven-what-is-the-easiest-religion-to-practice-to-get-into-heaven]
* Does it matter when a religion was created?
Christianity was created in the 1st century.
Islam was created in the 7th century.
Discordianism was created in the 20th century.
Does it matter when a religion was created?
Does a religion take time to be a religion?
Why must a religion's founder die before the religion becomes widespread?

The second generation does not directly experience the creation of the religion.
They only have the stories told by the first generation.
The third generation is even further removed.
