#+TITLE: Research
#+DATE: 2017-07-22 00:00 +0700
#+PERMALINK: /research.html
* Overview
** What is research?
"To research" is to search closely,
and "to search" is to seek or wander.[fn::https://www.etymonline.com/word/research][fn::https://www.etymonline.com/word/search][fn::https://en.wikipedia.org/wiki/Research]

To research is to accumulate knowledge.

To research is to answer a research question or solve a research problem.

Meta-research is research about research.[fn::https://en.wikipedia.org/wiki/Meta-research]

Scientists and academics are researchers, but not always the other way around.

In practice, a theoretical research is mainly trying to answer focused (deep and narrow) questions.
** How do we research?
This is how we do research:
1. Think about an idea we are interested in.
1. Find related publications.
1. Summarize how those publications are related to our idea.
1. Write our article.

Ask "What questions should we ask?"

Advice?[fn::https://cstheory.stackexchange.com/questions/2953/advice-on-good-research-practices]

What is an ideal research process, in BPMN (Business Process Model Notation)?

Researchers need something like a global version of a combination of Wikipedia and
AirBnb's Knowledge Repo[fn::https://medium.com/airbnb-engineering/scaling-knowledge-at-airbnb-875d73eff091].

Ask research questions, answer them, and collect them into living documents.
** What is the best place to do research?
Find the leading researcher, and go there?
* Finding related publications
** How do we find related publications?
There are some disparate systems.
I wish there were /one/ system for /all/ scientific publications.

To find papers and citations, use
Semantic Scholar[fn::https://www.semanticscholar.org]
or Google Scholar[fn::https://scholar.google.com].
Semantic Scholar is much richer than Google Scholar.
Semantic Scholar enables us to find out who influences who, what cites what, and which papers are similar, and much more.
It is the closest thing to my dream of having an artificial-intelligence that assists my research.
It makes Google Scholar look like a dumb pile of data.
A weakness of Semantic Scholar is that, as of 2019, its notion of "the same author" is somewhat lacking:
sometimes it thinks "John Smith" and "J. Smith" are two different authors.

What is Iris AI[fn::https://iris.ai]?

Libraries?[fn::https://medium.com/a-wikipedia-librarian/youre-a-researcher-without-a-library-what-do-you-do-6811a30373cd]

What is IGDORE?[fn::https://medium.com/@IGDORE/new-academia-a-safe-harbour-for-researchers-who-love-science-c4baa87c1ebe]

Sometimes telephones may be necessary.[fn::https://academia.stackexchange.com/questions/73236/how-to-find-people-who-do-similar-research]

Use Google to find papers.
We may also add =filetype:pdf= to your query.

These are disparate systems.
To find theses and dissertations, use OATD[fn::https://oatd.org/] (open-access theses and dissertations).
To find a UK PhD thesis, use EThOS[fn::http://ethos.bl.uk/Home.do] (e-theses online service).
Deutsche Digitale Bibliothek - Kultur und Wissen online (English available)[fn::https://www.deutsche-digitale-bibliothek.de/?lang=en]

How do we know what others have done?
I think, today, in a research group,
there has to be a "lead researcher" dedicated to finding resources (papers, books)
that might be related to the group's research,
because this job is huge,
given today's flood of information.

Suppose we have found a related article.
Which should we zoom into: the /author/ who writes it, or the /venue/ where it is published?

Both an author and a venue have /stable narrow interests/.
But only authors can /ask questions/ or /solve problems/.
Therefore, the author is more important than the venue, and we should check the author's publication list before we check the venue's publication list.
Therefore, when we come to a conference, we should aim to /make friends/ with people with similar interests.
Do not attend a conference that has a /topic/ you may be interested in,
but do attend a conference that may be attended by /people/ who share your interests.
The source of an idea is the author, not the venue.
The thought lives in an author, not in a venue.

Why do people have stable interests?
Adults have stable interests because adults rarely change beliefs.

People do what they think are important for them.
It is wonderful to find another person who also thinks that what we think is important.

There are too many journals for authors to compare.
Authors publish to where their friends publish.
Thus it is important that people with similar interests know each other.

<2018-10-02>
Twitter is surprisingly good for computer science research?[fn::https://twitter.com/search?q=programming%20language%20research]

Finding recent publications using academic search engines?

I tested Google Scholar[fn::https://scholar.google.com/],
Microsoft Academic[fn::https://academic.microsoft.com/],
and Bielefeld Academic Search Engine (BASE)[fn::https://www.base-search.net/],
using these queries: "partial evaluation", "optimal lambda".

BASE can boost open-access documents.

Are there academic metasearch engines / search aggregators?
- https://www.llrx.com/2017/01/academic-and-scholar-search-engines-and-sources-2017/

Why do different fields have different search engines?
What is the difference between biology literature study, computer science literature study, and physics literature study?
** The problem of multiple authors
Usually the last author is a supervisor, a professor, a research director, or something like that.
Thus the true interest of the last author is /masked/.

A publication only truly reflects the interest of the first author.

The first author contributes the most to the publication.
** How do we traverse citations?
*** What is a citation?
In the 15th century, "to cite" means "to summon".[fn::https://www.etymonline.com/word/cite]
In 2018, "to cite" means, roughly, to hyperlink.

In 2018, a citation is a /printable hyperlink/[fn::https://en.wikipedia.org/wiki/Hyperlink].
Citations and hyperlinks serve the same purpose: /to link information/.
We cite for the same reason we hyperlink.

A citation is a reference to /external content/.

A citation is a reference that is /too distracting to inline/.

CiteSeer[fn::http://citeseerx.ist.psu.edu/index] is an automatic citation indexing system\cite{Giles1998CiteSeerAA}.
*** Why do we cite?
A citation indicates that the citing author thinks that the citee is somehow /related/ to the citer.

Why do we cite?
What is the relationship between a citer and a citee?
One answer is that the citer cites the citee because the citee is interesting\cite{liu2013interestingness}.
Another answer is implied by the Citation Typing Ontology (CiTO)\cite{shotton2010cito}, which was designed for biomedical research, but should also be applicable to other fields.
Another answer is implied by a taxonomy of the motives of citing\cite{erikson2014taxonomy}.

Citations may be fraudulent.
Researchers are humans.
*** Other points of view
There are three points of view: the citer, the citee, and the reader.

Most ideas are a sentence in first-order logic.
Two sentences \(p\) and \(q\) are /compatible/ iff they don't contradict each other.
They are compatible iff their conjunction is not false.

How come there can be a case where we don't know the truth of \(p\) and we don't know the truth of \(q\) but we know that \(p \wedge q\) is false?

The strength of a claim is determined by the /difference/ between the strongest /supporting/ argument and the strongest /opposing/ argument.
** How do we know the current sum of human knowledge?
This is hard.
I don't know.

Finding other information sources: Finding other wikis[fn::https://en.wikipedia.org/wiki/List_of_wikis].

Science 2.0[fn::https://en.wikipedia.org/wiki/Science_2.0],
Open Research[fn::https://en.wikipedia.org/wiki/Open_research],
Open Science[fn::https://en.wikipedia.org/wiki/Open_science].
Minimize the duplication of work.
** Which conference should we attend?
The goal of attending a conference is to find people who share similar goals with us.
Thus, we should not see what the conference is about, but /who/ attends the conference.
** Where are expository works?
[[https://mathoverflow.net/questions/15366/which-journals-publish-expository-work][MO 15366: Which journals publish expository work?]]

These journals[fn::Expositiones mathematicae https://www.journals.elsevier.com/expositiones-mathematicae/]
 [fn::Computer science review https://www.journals.elsevier.com/computer-science-review]
contain expository works.
Unfortunately they are Elsevier journals.

Arxiv math history and overview[fn::https://arxiv.org/archive/math.HO]
** How do we use journals?

  - What are the journal article types?
    What kinds of articles do journals publish?

    - [[http://www.editage.com/insights/6-article-types-that-journals-publish-a-guide-for-early-career-researchers][Editage's six journal article types]]: original research; review article; clinical case study; clinical trial; perspective, opinion, and commentary; book review
    - There are also letters, monographs, surveys, and retractions.

* Summarizing publications
** How do we read a research article?
Read the title, the abstract, and then the conclusion.
** How do we read a book?
Do not read the entire book.

Get an idea or a problem before touching the book.
Find relevant parts in the table of contents.
** How do we catch up quickly?
An article is a diff.
It is a patch.
To understand the article, you need background knowledge.
We are weak in bootstrapping new people quickly.

If you are in a lab, you can ask your professor to bootstrap you.

If you are an independent researcher?

Only read papers or books after you know what you are looking for.
Don't read without reason.


** How do we onboard newcomers faster?
Write /living documents/ that summarize papers and provide directions.
Let newcomers improve them.
Living documents are perfect for expository works.

Every research paper is a "delta" of knowledge, a "nugget", a "diff".
 We need living documents that are the sum of those deltas.

A possible problem: who are the authors of a collaborative living document?
** How fast can we speed-read?

  - [[https://www.scotthyoung.com/blog/2015/01/19/speed-reading-redo/][I Was Wrong About Speed Reading: Here are the Facts]]:
    "anything above 500-600 words per minute is improbable without losing comprehension".

* Writing
** What computer document format should I write my research in?
Write your content in Pandoc Markdown / Org Mode.
Let Pandoc convert whatever format to HTML or LaTeX.

Use MathJax if you need to typeset math on the Web.

Stick to standard Web technology.
For the reader, reading HTML pages has less friction than reading a PDF document.

Use CSS to style the HTML.

Why should we not follow my advice?
Your institution probably incentivizes you to publish on famous journals, not on the Internet.
This incentive scheme has to change for better science.
Unfortunately you are not in the position to change it.
It's frustrating.
** How do researchers collaborate?
[[https://gowers.wordpress.com/2009/01/27/is-massively-collaborative-mathematics-possible/][Timothy Gowers: Is massively collaborative mathematics possible?]]
** How should we write?
Slides, Simon Peyton-Jones, "How to write a great research paper: seven simple suggestions"[fn::https://www.cis.upenn.edu/~sweirich/icfp-plmw15/slides/peyton-jones.pdf].
Another copy of those slides is at Microsoft[fn::https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/].
** What writing medium should we use?
Researchers should collaborate writing living documents instead of writing isolated papers.
We need something like Wikipedia but for research.
We need a goal-oriented/task-oriented Wikipedia.
Wikiversity might be close to that.
* Entering academia
The most important thing when entering academia is to find a professor whose research interests match ours.

If we want to enroll in higher formal education, then we must find a professor whose research interests match ours,
and we must prove that we are worthy of the research position.
/The right professor is the most important factor./[fn::https://www.quora.com/What-are-the-good-complexity-theory-research-groups-around-the-world]
The professor is more important than the institution (university or company).
We must be prepared to /relocate/ to somewhere near the professor.

https://www.quora.com/How-do-professors-view-cold-emails-asking-for-research-opportunities
* Academic journal publishing reform
** What
- Where can I find more information?

  - [[https://en.m.wikipedia.org/wiki/Academic_journal_publishing_reform][Wikipedia: Academic journal publishing reform]]
  - Where can I find more information about the current state and recent progress?

    - [[https://gowers.wordpress.com/category/elsevier/][Timothy Gowers's blog, "Elsevier" category]]

      - 2017: [[https://gowers.wordpress.com/2017/07/27/another-journal-flips/][Another journal flips]]
      - 2016: [[https://gowers.wordpress.com/2016/11/29/time-for-elsexit/][Time for Elsexit?]]
      - 2012: [[https://gowers.wordpress.com/2012/01/21/elsevier-my-part-in-its-downfall/][Elsevier -- my part in its downfall]]

- What is it?

  - a battle between many oppressed academics and some questionable publishing companies

- Who are the heros?

  - Aaron Swartz, who is a hero to the researchers in poor countries, and a criminal to the prosecutors
  - Timothy Gowers, who began a boycott against Elsevier
  - and other tens of thousands of academics who care, probably more
  - I don't know. There have to be other people. They don't work alone.

- Who are the villains?

  - mainly Elsevier, because of two reasons:

    - It's the biggest academic publisher.
    - It does [[https://en.wikipedia.org/wiki/Elsevier#Criticism_and_controversies][lots of questionable things]].
    - [[https://www.talyarkoni.org/blog/2016/12/12/why-i-still-wont-review-for-or-publish-with-elsevier-and-think-you-shouldnt-either/][Tal Yarkoni's comprehensive argument against Elsevier]]

  - and some other predatory publishers

- What are the problems?

  - Price gouging, done rationally by a profit-seeking monopoly.
    See also the list of questionable things in the link above.

- What is the outcome of the battle?

  - How much has it impacted Elsevier's bottom line?
  - How much has it saved universities?
  - I don't know.
  - It seems that more new papers published open-access. But what about old papers? We need them too.
  - [[https://en.wikipedia.org/wiki/The_Cost_of_Knowledge][Wikipedia: The cost of knowledge]]
  - [[https://en.wikisource.org/wiki/Guerilla_Open_Access_Manifesto][Wikipedia: Guerilla open access manifesto]]
  - The battle might also have sparked the creation of these websites?
    Actions against these websites might have sparked the battle?

    - Library Genesis, see [[https://en.wikipedia.org/wiki/Library_Genesis][Wikipedia]]
    - Sci-Hub, see [[https://en.wikipedia.org/wiki/Sci-Hub][Wikipedia]]
    - ICanHazPDF, see [[https://en.wikipedia.org/wiki/ICanHazPDF][Wikipedia]]
    - Library.nu, see [[https://en.wikipedia.org/wiki/Library.nu][Wikipedia]]

- What can you do to help solve that?

  - I have a proposal below that I hope is useful, but I'm not sure.

- https://www.quora.com/Why-do-researchers-have-to-pay-to-read-research-papers-Shouldnt-papers-be-free-for-those-who-need-them-How-are-publishers-able-to-charge-so-much
- [[https://en.wikipedia.org/wiki/Academic_publishing][WP: Academic publishing]]
- [[https://en.wikipedia.org/wiki/Scientometrics][WP: Scientometrics]]

  - What are some metrics used to measure an academic resource?

    - Impact factor, "a measure reflecting the yearly average number of citations to recent articles published in that journal" ([[https://en.wikipedia.org/wiki/Impact_factor][Wikipedia: Impact factor]])
    - h-index, https://en.wikipedia.org/wiki/H-index#Calculation

  - Are those metrics good? Do they create perverse incentive? Are people gaming the system?

    - I know someone who coauthors more papers than everyone in my university /combined/.

      - Is it possible to coauthor that many papers?
      - Is he efficient?
      - Is he cheating?

        - Perhaps he should be thanked, but he is not an author?

          - What is an author?

            - If you suggest an idea, but don't write the paper, are you an author?
            - https://www.theguardian.com/higher-education-network/2015/jun/05/my-professor-demand-to-be-listed-author-on-research-paper

          - How many papers can you author in a year?

      - Is my university incompetent?

- Why are there so many academic journals?
- [[https://www.theguardian.com/higher-education-network/2017/jun/06/why-we-cant-trust-academic-journals-to-tell-the-scientific-truth][Why we can't trust academic journals to tell the scientific truth]]
- Undigested

  - Academic publishing is broken

    - https://sbseminar.wordpress.com/2017/04/09/and-elsevier-taketh-away/
    - https://fairoa.org/

  - https://academia.stackexchange.com/questions/19333/how-much-do-springer-verlag-authors-make-per-book-sold

Springer makes no fucking sense:
personally spending $39,000[fn::5 paper/work-day * $30/paper * 260 work-day/year = $39,000] per year just to read papers is just too fucking much for an average researcher.

Publishers may be evil.[fn::https://www.theguardian.com/higher-education-network/2015/sep/04/academics-are-being-hoodwinked-into-writing-books-nobody-can-buy]
** Proposal for academic publishing reform: Separate peer review and physical dissemination
   :PROPERTIES:
   :CUSTOM_ID: proposal-for-academic-publishing-reform-separate-peer-review-and-physical-dissemination
   :END:

/Attach reputation to reviewers, not journals./
To humans, not institutions.
What is important is not where an article is published,
but /who reviews the article/.
There are no important journals.
There are only important reviewers.

Alternatively, /make the reviewers own the journals/.
Profit-seeking is not evil on its own.
Neither is monopoly.
But together they screw buyers.

Incentivize academics to publish openly on the Internet instead on closed journals.

Make a website for peer-reviewing articles.

2018-04-25: It exists. See Wikipedia:
[[https://en.wikipedia.org/wiki/Publons][Publons]],
[[https://en.wikipedia.org/wiki/PubPeer][PubPeer]],
[[https://en.wikipedia.org/wiki/JournalReview.org][JournalReview.org]].

** Other content
   :PROPERTIES:
   :CUSTOM_ID: other-content
   :END:

- Science progresses much faster if we exchange data/knowledge/information freely.

  - You have something I need.
  - I have something you need.

- We need content curation for science/academics.

  - https://medium.com/content-curation-official-guide/why-to-curate-information-73ecb47b98a5
  - https://en.wikipedia.org/wiki/Content_curation
  - https://en.wikipedia.org/wiki/Digital_curation
  - 2016, article, [[https://medium.com/content-curation-official-guide/why-to-curate-information-73ecb47b98a5][Why To Curate Information -- Content Curation Official Guide]]
  - 2017, article, [[https://medium.com/content-curation-official-guide/how-to-monetize-curated-content-465cc44725bd][How To Monetize Curated Content -- Content Curation Official Guide]]
  - 2008, article, [[https://www.missiontolearn.com/content-curator/][Who are your content curators - and what skill should they have?]]
  - Is there a curated wiki?
    Can we crowdsource curation?

    - 2017, article, [[https://bigthink.com/Picture-This/mob-rule-curating-via-crowdsourcing][Mob Rule: Curating via Crowdsourcing - Big Think]]
    - 2016, article, [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4976298/][Crowdsourcing and curation: perspectives from biology and natural language processing]]
    - 2016, article, [[https://yeti.co/blog/crowdsourcing-spotifys-secret-weapon-for-curation-at-scale/][Crowdsourcing: Spotify's Secret Weapon for Curation at Scale - Yeti]]
    - 2016, article, [[http://analytics-magazine.org/crowdsourcing-using-the-crowd-curated-vs-unknown/][Crowdsourcing -- Using the crowd: curated vs. unknown - Analytics Magazine]]
    - 2013, article, "A Theoretical Analysis of Crowdsourced Content Curation", [[http://users.eecs.northwestern.edu/~gar627/crowdsource.pdf][pdf]]

  - [[https://medium.com/machine-learning-in-practice/my-curated-list-of-ai-and-machine-learning-resources-from-around-the-web-9a97823b8524]["My Curated List of AI and Machine Learning Resources from Around the Web"]]

- [[https://en.wikipedia.org/wiki/Least_publishable_unit][Least publishable unit - Wikipedia]]
- [[http://www.vegapublish.info/][Vega Academic Publishing System -- Blog]]: "Vega is laying a new foundation for online open access publishing."
** Academic grant funding is broken
Researchers waste time adorning grant proposals in the proposal arms race.
We should use some randomness.[fn::"Researchers spend much of their time writing grant applications, which adds up to a lot of wasted resources.
Is there a better way to fund science?" https://www.youtube.com/watch?v=JkMvm_rsTvI]
* Unorganized related things
** Reading academic publications

  - The input is the publication and some effort.
  - What is the output?
  - What is the best way of reading?

    - An attempt to answer that

      - Begin with a goal.
      - Every time you read a sentence, compare it to your goal.

        - If the sentence helps you reach your goal, process the sentence.
        - Otherwise, skip it.

  - A publication can be thought of as a set of first-order logic statements.
  - What is knowledge?

    - A piece of knowledge is a sentence: a first-order logic statement with no free variables.

- In order to do something new, you must make sure that nobody else has done it.
  In 2018, there are 7 billion people.
- Which country values science the most?
  Where is scientist most demanded?

  - [[https://en.wikipedia.org/wiki/Inglehart%E2%80%93Welzel_cultural_map_of_the_world][WP: Inglehart--Welzel cultural map of the world]]
  - [[https://www.phdstudies.com/article/What-Are-The-Best-Countries-For-Scientists/][phdstudies.com: What are the best countries for scientists?]]
  - [[https://en.wikipedia.org/wiki/OECD_Better_Life_Index][OECD better life index]]

** How should I structure my research?

  - Structure your research as a hierarchy of questions and answers.
    Every question may spawn child questions and answers.
    I call this format the HQA (Hierarchical Questions and Answers) or QAT (Question-Answer Tree).

    - We should group paragraphs into trees.

      - Every child explains, augments, supports, or elaborates its parent.
      - We have been grouping sentences into paragraphs.

  - Why do we need questions or problems?

    - Questions drive research.

** How should we organize information?

  - It depends on how the information is going to be retrieved.
  - [[http://thevisualcommunicationguy.com/2013/07/20/the-five-and-only-five-ways-to-orgaize-information/][The only five ways to organize information]]:
    location, alphabet, time, category, hierarchy
  - [[https://en.wikipedia.org/wiki/Personal_knowledge_management][Wikipedia: Personal knowledge management]]
  - [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.164.320&rep=rep1&type=pdf][Better to organize personal information by folders or by tags?]]

** Journals

  - https://mathoverflow.net/questions/42/which-are-the-best-mathematics-journals-and-what-are-the-differences-between-th
  - What is [[https://en.wikipedia.org/wiki/Impact_factor][impact factor]]?
  - Is citation a strong signal of quality?
  - [[https://en.wikipedia.org/wiki/Sturgeon%27s_law][Sturgeon's law]]: 90% of everything is crap

    - How do we find the 10% that is not crap?
    - [[https://math.stackexchange.com/questions/1071384/effective-research-notes][How to make effective research notes]]

** Exploration

  - https://ibmathsresources.com/maths-ia-maths-exploration-topics/
  - http://www.dpcdsb.org/NR/rdonlyres/FE43C622-9FA0-4385-8E19-0C539513295E/133918/ListofPotentialTopicsfortheExploration1.pdf

** How do I keep myself up-to-date? How do I keep myself in the loop?

  - Which mailing lists should I join?
  - Which blogs, websites, or people should I follow?
  - [[https://mobile.twitter.com/amermathsoc][Twitter of AMS (American Mathematical Society)]]

** How do we know if something is legitimate or bullshit?

  - See [[http://callingbullshit.org/][callingbullshit.org]]
  - [[http://callingbullshit.org/tools/tools_legit.html][How do you know a paper is legit?]]

** What tools might help my research?

  - [[https://learn-anything.xyz/][learn-anything.xyz]] is a community-curated mind map.
  - Google's [[https://books.google.com/talktobooks/][talk to books]].
  - http://www.arxiv-sanity.com/
  - http://connectedresearchers.com/online-tools-for-researchers/
  - https://digitalresearchtools.pbworks.com/w/page/17801693/Organize%20Research%20Materials
  - https://www.zotero.org/
  - Preprint servers. Beware: anyone can put anything.
    Browsing a preprint server directly is a bad idea that will waste your time.

    - arxiv.org
    - vixra.org
** Open access journals
   :PROPERTIES:
   :CUSTOM_ID: open-access-journals
   :END:

How do we know if an open-access journal is legitimate?

http://www.mdpi.com/journal/universe

https://benthamopen.com/PHY/home/

** How do we work with proofs?

  - Understanding and simplifying existing proofs
  - Proving unproved conjectures, lemmas, and theorems
  - [[https://proofwiki.org/wiki/Main_Page][ProofWiki: compendium of mathematical proofs]]
  - https://www.reddit.com/r/math/comments/4uelmr/a_theorem_and_proof_a_week_the_50_most/
  - https://math.stackexchange.com/questions/178940/proofs-that-every-mathematician-should-know

    - https://en.wikipedia.org/wiki/Brouwer_fixed-point_theorem

      - https://en.wikipedia.org/wiki/Sperner%27s_lemma

        - https://en.wikipedia.org/wiki/Monsky%27s_theorem

          - https://en.wikipedia.org/wiki/Proofs_from_THE_BOOK

  - The most important theorems?

    - http://pirate.shu.edu/~kahlnath/Top100.html
    - https://www.quora.com/What-are-the-most-important-mathematical-theorems
    - Theorems allow you to stand on the shoulder of giants
    - https://en.wikipedia.org/wiki/Newton's_theorem_of_revolving_orbits
    - Pythagoras's theorem about right triangles
    - Löwenheim--Skolem theorems
    - Gödel's incompleteness theorems
    - Gödel's completeness theorems

** Can we crowdsource/outsource master-level or doctorate-level research to Fiverr or Amazon Mechanical Turk?
I think no.
Thinking doesn't scale.
Some data collection may scale.

Trying to scale the thinking may invite crackpots?

** Can we transform or break a doctorate-level research problem into pieces that amateurs can work on?
Is the difficulty in mathematics essential or accidental?
For example, accidental complexity is due to bad notation, bad presentation, bad writing.

** What are the different kinds of academic meetings?
Which is the most common type?
Which one should I attend?

"Conference" comes from Latin "con-" ("together") and "ferō" ("I bear")[fn::https://en.wiktionary.org/wiki/conference]

"Colloquium" comes Latin "co-" ("together") and "loquor" ("to talk")[fn::https://en.wiktionary.org/wiki/colloquium]

seminar

congress;
[[https://en.wikipedia.org/wiki/International_Congress_of_Mathematicians][Wikipedia: International Congress of Mathematicians]]

See also [[https://english.stackexchange.com/questions/20924/whats-the-difference-between-colloquium-seminar-and-possibly-other-such-w][English SE 20924]].

"Symposium" comes from a Greek word meaning "to drink together".[fn::https://en.wikipedia.org/wiki/Symposium]

What is the difference between conference, congregation, symposium, seminar?
Why can't we just use the word "meeting" for all of them?
** Why is literature study important?

  - It saves time.

    - Skip things that are already done.
    - Skip dead ends.
    - Build on other people's work.

** How should we structure human knowledge?
- [[https://thepantologist.com/classifying-all-human-knowledge/][Classifying all human knowledge]]
- [[https://en.wikipedia.org/wiki/Figurative_system_of_human_knowledge][WP:Figurative system of human knowledge]]
- [[https://www.theatlantic.com/technology/archive/2013/10/-wikipediaproblems-how-do-you-classify-everything/280178/][#WikipediaProblems: How Do You Classify Everything?]]
  - SUMO (Suggested Upper Merged Ontology)
** Undigested

  - [[https://books.google.com/talktobooks/][Google talk to books]]
  - SQ3R method https://academia.stackexchange.com/questions/631/how-to-efficiently-read-mathematically-and-theoretically-dense-books-in-stem-fie
  - http://tex.stackexchange.com/questions/5635/how-to-cite-a-university-lecture-or-its-slides-or-script
  - https://www.timeshighereducation.com/features/these-are-20-most-popular-academic-papers-2016
  - https://www.quora.com/Is-doing-a-PhD-worth-it-these-days
  - http://connectedresearchers.com/online-tools-for-researchers/

** Scientific method?

  - Scientific method is a combination of Ask, Observe, Guess, Test.
  - [[https://en.wikipedia.org/wiki/Scientific_method][WP:Scientific method]]

- [[https://en.wikipedia.org/wiki/Lists_of_unsolved_problems][WP:List of unsolved problems]]
** Failures?
Publishers that fail the SCIGen test?

Lupine Publishers[fn::https://www.sciencealert.com/how-kim-kardashian-inventor-bitcoin-teamed-up-write-scientific-paper-satoshi-nakamoto-predatory-journals]

Other failures?

"Peer review fails to prevent publication of paper with unsupported claims about peer review"[fn::https://scholarlykitchen.sspnet.org/2018/03/15/a-comment-on-klein-et-als-comparing-articles-to-preprints/]

I read somewhere I forgot, that that is not the point of peer review.
What is peer review meant to accomplish then?
** How to study everything?
Begin with ontology.
What exists?
How do they relate?
** Open-access journals?
- [[https://en.wikipedia.org/wiki/List_of_open_access_journals][WP:List of open-access journals]]
- [[https://en.wikipedia.org/wiki/Body_of_knowledge][WP:Body of knowledge]]
* Unorganized not-too-related things?
** How do we get research grants?
What are the laws and rules?

Who makes the decisions?

How do you improve your chances?

2014 book "Writing Successful Grant Proposals from the Top Down and Bottom Up"[fn::https://us.sagepub.com/en-us/nam/writing-successful-grant-proposals-from-the-top-down-and-bottom-up/book236652]
** What does an assistant professor do?
According to https://recruit.ucsc.edu/apply/JPF00651:
- develop a research program
- advise graduate students in their research area
- obtain external funding
- develop and teach courses within the undergraduate and graduate curriculum
- perform university, public, and professional service

That's a lot for one person to do.
** Problems
- 2005, article, "Why Most Published Research Findings Are False", John P. A. Ioannidis, [[http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020124][html]]
** Academics is broken. Science is broken. Research is broken.
- https://www.statnews.com/2018/10/29/alzheimers-research-outsider-bucked-prevailing-theory/
  - Alzheimer research went slowly.
    30 years and still no cure.
    Because grants are decided by narrow-minded old high guards.
    Perverse incentives.
    Too narrow.
    Too incremental.
    Too risk averse.
    Too tribal.
    Groupthink.
    Science has become a religious monoculture.
    - Science requires diverse thoughts in order to progress.
- Theoretical physics is also broken.
  It's hard to get a grant if you don't do string theory.
  See Lee Smolin's commentary.
** Academic writing
  - "How to write a good CVPR submission", [[https://billf.mit.edu/sites/default/files/documents/cvprPapers.pdf][pdf slides]]

** Math PhD?
- 2011, article, "A Very Rough Guide for PhD Students in Mathematics", [[http://www.maths.manchester.ac.uk/media/eps/schoolofmathematics/study/guide_2011.pdf][pdf]]
** Mathematical knowledge management?
- [[https://github.com/planetmath][Planetmath]] is a collection of TeX documents.
  - Can it be made into a mathematical knowledge management system?
- https://wikieducator.org/Main_Page
** Library problems
In 2018, a lot of human knowledge is still in libraries and not available on the Internet.
Digital typesetting was invented relatively recently.
Papers should be scanned and OCR-ed.
AI can help.

Why are there different libraries?
There should be only one library in the world.
All library should be the same.
All library should have the same content.
** Wikipedia alternatives?
- https://en.wikipedia.org/wiki/Wikipedia:Other_projects_similar_to_Wikipedia
- https://en.wikipedia.org/wiki/Wikipedia:Alternative_outlets
- https://www.quora.com/What-are-the-best-alternatives-to-Wikipedia
- https://everipedia.org/wiki/InterPlanetary_File_System/
  - Everipedia and IPFS?
- https://oedb.org/ilibrarian/top-7-alternatives-to-wikipedia/
** Refuting bullshit
- [[https://en.wikipedia.org/wiki/Bullshit#Bullshit_asymmetry_principle][WP:Bullshit asymmetry principle]]
  - "The amount of energy needed to refute bullshit is an order of magnitude bigger than to produce it."
  - Does that mean it's easier to fight a bullshit with another bullshit?
    - Why don't we fight bullshit with bullshit?
    - Why don't we fight false news with false news?
    - Why don't we fight hoaxes with hoaxes?
    - Why don't we fight propagandas with propagandas?
    - If we fight lies with lies, everybody loses?
* Living their dreams doing research?
The Max Planck Society
http://elevanth.org/blog/2018/09/02/golden_eggs/
* Bibliography
