#+TITLE: Get rich quickly without going to jail
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /rich.html
#+OPTIONS: ^:nil toc:nil
* How quickly?
About 10 years?

If we know a way to get rich, then we can always speed it up by financial leverage (debt, credit).
But leverage also multiplies the risk.
* Use the economic/financial system to centralize power
Sam Altman puts it concisely: "You get rich by owning things."[fn::http://blog.samaltman.com/how-to-be-successful]

Why do we get rich by owning things?

Because ownership piggybacks on the power of the jurisdiction that we are in
(unless we are in a communist state that denies private ownership).

Because we can ask the police to violate whomever violates our ownership
(unless the perpetrator is the government itself).

Understand how to make the system works for us instead of making us work for the system.

Respecting private property enables the accumulation of wealth and the ensuing economic inequality.

Inequality is not poverty.[fn::https://fee.org/articles/stop-conflating-inequality-with-poverty/]

We have several choices to reduce inequality:
- Embrace capitalism:
  Make everyone own properties and educate everyone to spend money wisely.
- Oppose capitalism:
  Steal from the rich, give to the poor, although this incentivizes poverty.
  Abolish private ownership.
  But isn't this envy-based politics?

But why should we reduce inequality?
It is poverty that we should reduce, not inequality.

Of course some poverty is due to bad luck,
and we should help people who fall into poverty due to bad luck.
But too many entitlement programs are trapping people in poverty.

It is up to us whether we want to find ways to own properties.

Patrick Anderson has an interesting idea:
"the origin of profit is the consumer's lack of ownership in the means of production"
 [fn::http://postgrowth.org/how-on-earth-flourishing-in-a-not-for-profit-economy-by-2050/].
** Understand money
*** Money as seed and human as soil
We can think of money as seed and human as soil.
Some humans are fertile soils for money to grow.
A poor person who wins a lottery soon loses all of it.
A rich person who wins a lottery keeps getting richer.
A fool and his money are soon parted.
However, this way of thinking puts money first and human second.

We can think of how fast money flows through a person.
*** Money as people's way of voting for what they want
Money is a way for people to vote for what they want.
People vote with their money.
*** Money as fluid
*** Money as blood
Economic actors are the organs, and money is the blood.
** Understand how capitalism centralizes power
Capitalism is:[fn::https://en.wikipedia.org/wiki/Capitalism]
1. the /private ownership/ of means of production,
2. the operation of such means /for profit/.

What?
- http://www.visualcapitalist.com/
- Capital is everything that is not labor?
- Capitalism is capital above labor? Communism is labor above capital?
- Example of low-capital high-labor:
  - small and medium enterprises (SMEs)
    - food stalls
    - home bakeries
    - art freelancing
  - research in pure mathematics
** Understand value
"Create value"?

Value does not exist.
What exists is /want/.

To "create value" is to satisfy desire, to satisfy want.
** Companies must extract value to survive
- A profitable company must extract more value
  from its employees than it pays its employees.
  - People create value. People in a company create value. Human labor creates value.
    Companies aren't human. Companies can't work. It's the employees who work.
  - But if the employees weren't in the company, they might create less value.
    The company might be a place where the employees can create more value for society.
** Economics
- ontology

  - wealth

    - /Wealth/ is the sum of satisfied wants.

  - price, pay, ownership, exchange, transaction

    - To /own/ something is to have exclusive access to that thing.
    - /Exchange/ and /transaction/ are synonyms.
    - An /exchange/ is an agreement

      - between two parties A and B where

        - A gives X to B,
        - B gives Y to A.

    - If X is money and Y is not money, then:

      - X is the price.

        - /Price/ is the amount agreed for exchange.
        - /Price/ is something sacrificed to get something else.

      - A is the buyer.
      - B is the seller.
      - The buyer /pays/ the price to the seller.

  - negotiation, price-taker, price-maker

    - Negotiating parties often have asymmetrical bargaining power.
    - The price-taker is the weaker one.
    - The price-maker is the stronger one.

  - money and currency

    - Money has /currency/ and /amount/ (/magnitude/).
    - Money can be /exchanged/ with many other things.

  - debt, interest, and price

    - The price of debt is the /interest/
      (the amount of money that will be exchanged for obtaining the loan now).

      - An X market is a market where X is traded.

        - A money market is a market where money is traded.

          - How do you buy money with money?

- Assumptions

  - Every human:

    - Has wants.
    - Has priorities? Utility function?

      - Non-constructive? It exists, but we don't know what it is?

    - Acts to satisfy those wants.

- Counterexamples? Where the theory breaks down?

  - Thiefs want something more than freedom?

    - But both of the stolen thing and the freedom will be taken away?

  - Smokers and junk food eaters don't want health?

    - Everybody wants health?

      - But doesn't behave consistent with wants?

        - Cognitive dissonance?

          - Want health later or health now?
          - Addiction?

            - Physical changes to the brain?

- Fundamentals of economics

  - Everybody wants something.
  - How do we satisfy more people using less resources?

- decision theory?

  - [[https://en.wikipedia.org/wiki/Von_Neumann%E2%80%93Morgenstern_utility_theorem][WP:von Neumann--Morgenstern utility theorem]]

- Higher-order belief

  - [[https://en.wikipedia.org/wiki/Keynesian_beauty_contest][WP:Keynesian beauty contest]]
  - Examples of higher-order beliefs:

    - People believe that money is valuable because they believe
      that others also believe that money is valuable.

- How do we give more than we take?

  - How do we produce more than we consume?

- Land > Labor > Capital

  - The [[https://en.wikipedia.org/wiki/Factors_of_production][factors of production]]
    in classical economics are:

    - land (all other things that exist in nature),
    - labor (human),
    - capital (tools).

  - Land creates labor.
  - Labor creates capital.
  - If capital is destroyed, labor can rebuild it.
  - If labor is destroyed, capital cannot rebuild it.
  - Labor without capital is inefficient.
  - Capital without labor is /nothing/.
  - However, without land, nothing would exist at all.
  - Therefore, land is more important than labor, and labor is more important than capital,

    - but it seems here that capital is revered, labor is disdained, and land is forgotten.

  - Money is not capital, but it can be used to buy capital, but this quote is related:
    > When the last tree is cut, the last fish is caught, and the last river is polluted;
    > when to breathe the air is sickening, you will realize, too late,
    > that wealth is not in bank accounts and that you can't eat money.
    >
    > Alanis Obomsawin (b. 1932) ([[http://quoteinvestigator.com/2011/10/20/last-tree-cut/][source]])

- Is Indonesia basic income feasible?

  - [[https://en.wikipedia.org/wiki/Basic_income][WP:Basic income]]
  - [[https://www.kemenkeu.go.id/apbn2016][APBN 2016]] income Rp 1,822.5 trillion (in one year).
  - 2016 population 258 million people. (source?)
  - Thus about Rp 7 million per man-year.

    - This isn't even enough to buy food for one man-year.

- https://www.numbeo.com/cost-of-living/
- Undigested

  - https://www.opendemocracy.net/transformation/andrew-sayer/is-unearned-income-acceptable
  - http://www.resilience.org/stories/2016-03-15/money-is-not-a-store-of-value/
  - Write about inflation

    - Supply-caused inflation
    - Demand-caused inflation

  - https://www.washingtonpost.com/news/wonk/wp/2013/09/09/how-the-cult-of-shareholder-value-wrecked-american-business/

- philosophy

  - Increasing the wealth of the human race conflicts with antinatalism?
  - Increasing the minimum/average wealth of the human race doesn't conflict with antinatalism?

- Some economists

  - David Ricardo
  - Henry George
  - Adam Smith
  - John Maynard Keynes

- Initial money supply

  - How is money distributed for the first time (when there is not yet any money)?
  - How do we transition from barter to cash?

    - How do we set prices?

- [[https://en.wikipedia.org/wiki/Modern_Monetary_Theory][WP:Modern monetary theory]]?
- Tax

  - Tax enables government to redistribute money (and therefore some wealth).
  - Tax enables government to discourage the consumption of certain goods.
  - Taxation is legalized robbery.

    - The government forcibly takes some of the people's money.
    - The people doesn't get to decide what the tax money is used for.

      - The government is assumed to use that money for the people's good.

- [[https://en.wikipedia.org/wiki/Trickle-down_economics][WP:Trickle-down economics]]

  - How does one arrive at this? How does one think? What is the argument?

- If the total amount of money is constant,
  then the only way for you to have more money
  is to make someone else has less money.

  - [[https://en.wikipedia.org/wiki/Mercantilism][WP:Mercantilism]] assumes that the total wealth in the world is constant?

    - "Mercantilists viewed the economic system as a zero-sum game, in which any gain by one party required a loss by another.[16]"

- Questions I haven't been able to answer

  - If everybody needs to buy food, then why aren't farmers the richest people on Earth?

    - What if the farmers don't spend?

      - Will money collect at the farmers?
      - Will they be the richest people on Earth?

- Money circulation

  - Circulating money amount should be proportional to amount of goods/services exchanged?
  - The amount of money in circulation can be reduced by tax or destruction.
  - Why do governments sell bonds?

    - To reduce the amount of money in circulation now?

      - At the cost of increasing a bigger amount of money circulating in the future?

  - Money moves faster in certain areas?
  - How does the government increases the amount of money in circulation?

    - How I think it might be done:

      - Create new money.
      - Spend that money by buying things from a few elites,

        - with the hope that the elites will quickly spend that money to the lesser elites.

          - Thus that money will circulate to more people.

            - But isn't this trickle-down economics?

    - But does it even do this? Isn't it the banks?

  - What is the effect of people's borrowing from banks?

    - Increase circulating money now (boom part of boom-bust cycle).
    - Reduce /more/ circulating money later (bust part of boom-bust cycle, when the loan is paid back with interest).

      - Principal plus interest (money retired) is greater than principal (money created),
        so the net effect of lending money now
        is a delayed reduction of a greater amount of money in circulation.

        - Where does the money to pay the interest come from?

          - If left alone, eventually the money collects at the banks?

            - But banks have expenses too.

              - Banks need to pay taxes, pay their utility bills,
                pay their staffs.

            - But shouldn't the money collect at the farmers?

  - The ideal inflation rate is zero?

    - [[https://en.wikipedia.org/wiki/Nominal_rigidity][WP:Nominal rigidity]] a.k.a. price-stickiness or wage-stickiness

- [[https://makewealthhistory.org/2018/01/31/wealth-creation-and-wealth-extraction/][The difference between wealth creation and wealth extraction]]
- [[https://medium.com/@joe_brewer/the-global-architecture-of-wealth-extraction-4c0a6b954a14][The Global Architecture of Wealth Extraction]]
- [[https://www.aljazeera.com/indepth/opinion/2017/05/africa-poor-stealing-wealth-170524063731884.html][Africa is not poor, we are stealing its wealth]]
- rent seeking, wealth extraction

  - unread

    - [[https://boffyblog.blogspot.com/2017/04/general-election-who-are-wealth.html][Who are the wealth extractors?]]
    - [[http://www.rossgittins.com/2018/01/whos-doing-best-in-rent-seeking-business.html][Who's doing best in the rent-seeking business]]

- Infer: People buy something because they want it.

  - False assumption: People buy something because it makes them better off.
  - False assumption: People buy something because /they believe/ it makes them better off.
  - False assumption: Voluntary exchange makes both parties better off.
  - Counterexample: Cigarette smoking, addictive substances.
  - Why do people want things? Some possible reasons:

    - To sustain life.
    - To avoid pain.
    - To increase happiness.
    - To satisfy curiosity.
    - ...
    - Their brains are hijacked.

      - Isn't it generally immoral to harm people?
      - Is it moral to make people harm themselves (e.g. selling them cigarettes)?

  - Murphy's law applied to capitalism?

    - If something is profitable, someone will do it.
    - Some evil is profitable.
    - Therefore someone will do some evil and get rich from doing that evil.

- Unread

  - False assumptions

    - [[https://caspertk.wordpress.com/2012/12/08/top-ten-false-assumptions-taught-in-my-economics-classroom/]["Top Ten False Assumptions Taught In My Economics Classroom"]]
    - [[http://www.binaryeconomics.net/wordpress/fifty-nine-false-assumptions-of-mainstream-neo-classical-economics/][Fifty Nine False Assumptions of Mainstream Neo-classical Economics]]

      - questionable source

- economics-biology analogy

  - pioneer species?

    - https://en.wikipedia.org/wiki/Pioneer_species
    - pioneer species in biology ~ pioneer species in economics ?
    - ecosystem recovery after wildfire ~ economy recovery after war/disaster ?
    - fire ecology ~ war/disaster ecology ?
    - How does a community rebuild itself?

- Company theory

  - Avoiding personification of companies

    - A company is a group of people.
    - Group is concept. Person is reality.
    - Groups can't think. People think.
    - Groups can't react. People react.
    - Groups can't live. People live.
    - Groups can't work. People work.
    - Groups can't create value. People create value.
    - Groups can't decide. People decide.
    - Groups can't be responsible. People are responsible.
    - Groups can't commit crime. People commit crime.
    - Groups can't damage environment. People damage environment.
    - Groups can't exploit. People exploit.
    - What do we mean when we say "a group of people are walking"?
      We mean "those people are walking".
      A group is a concept.
      We invent it in our language.
      A group can't walk.

  - The whole is greater than the parts?

    - The value that someone produce alone is less than the value he produces with his coworkers?
    - But social loafing? Bigger team mean less work per person?
    - Companies exist.

      - It shows that owning a company can be profitable.

  - Define: To /employ/ someone is to find/give him things to do.
  - A profitable-company owner employs its employees better than those employees employ themselves.
  - If employees could find great things to do, they will own a company, not work for a company.
  - To employ is to exploit.

    - A company owner who doesn't exploit his employees enough will run out of money.
    - A company owner who exploits his employees too much will run out of employees.
    - "Exploit" there is the same "exploit" in "exploiting natural resources".

      - [[https://en.wiktionary.org/wiki/exploit#Verb][Wiktionary:exploit]]: "to use for one's own advantage"

- Does Patreon work?

  - For investors?
  - For creators?
  - For patrons?
  - https://theoutline.com/post/2571/no-one-makes-a-living-on-patreon

- https://en.wikipedia.org/wiki/Laffer_curve

** Finance
  :PROPERTIES:
  :CUSTOM_ID: finance
  :END:

- What is finance?

  - [[https://en.wiktionary.org/wiki/finance][Wiktionary: finance]]
  - [[https://en.wikipedia.org/wiki/Finance][WP: Finance]]

    - "Finance is a field that deals with the study of investments."

- Loan-related jargon

  - A lender lends (gives) a loan to a borrower.
  - A borrower borrows (takes) a loan from a lender.
  - Loan is the amount.
  - Borrower (one who borrows) is the debtor (one who has debt).
  - Lender (one who lends) is the creditor (one who gives credit).
  - Lease vs rent?

    - Lease is more formal and long-term than rent.

      - [[http://www.businessdictionary.com/article/1063/lease-vs-rent-d1412/][businessdictionary.com]]
      - [[https://www.nolo.com/legal-encyclopedia/leases-rental-agreements-faq.html][nolo.com]]

- Currency-related jargon

  - The /price/ is the amount paid by the buyer to the seller.
  - What is currency?
  - What is money?
  - What is the difference between currency and money?

    - https://www.weusecoins.com/hidden-secrets-of-money-currency-versus-money/

      - "Currency is a medium of exchange, a unit of account."
      - "Money is [currency] plus a store of value over a long period of time."

  - What is legal tender?
  - What is cryptocurrency?
  - Is there such thing as "cryptomoney"?

- Securities

  - A [[https://en.wikipedia.org/wiki/Security_(finance)][security]] is a /claim/ to something.
  - An /exchange/ was a place (is a computer system) where things are traded (bought and sold).

    - The exchange requires /brokers/ because it was invented before computers.

      - Impractical: 1 million people on the trading floor shouting for a match.

        - But a computer can match 1 million trades in a second.

      - Nobody bothers making a new stock exchange.

        - Because of [[https://en.wikipedia.org/wiki/Network_effect#Financial_exchanges][network effect]].
        - But [[https://robinhood.com/][Robinhood]] is doing that,

          - but it's a broker, not a stock exchange,

            - but I hope they make buying stock as easy as ordering pizza online,

              - because if everyone uses the same broker,
                then the broker /is/ the exchange.

          - [[https://support.robinhood.com/hc/en-us/articles/202853769-How-Robinhood-Makes-Money][How Robinhood makes money]]

            - No trading fee.
            - $6 per month per person who uses Robinhood Gold; otherwise none.
            - In 2017, Robinhood had 2 million users ([[https://techcrunch.com/2017/04/26/robincorn/][techcrunch.com]]).

              - How many of them use Robinhood Gold?

                - How many people have margin account compared to regular account?

                  - I guess 1:100.

              - How many employees do Robinhood have?

                - 30 ([[https://www.owler.com/company/robinhood][owler.com]])

              - Does that make sense?

                - My estimate:

                  - Their revenue:

                    - $60,000 per month = $720,000 per year.

                  - Their expenses:

                    - $300,000 per year for employees.
                    - ? for stock exchange chairs.
                    - ? for building leases.

                - Yes, it makes sense.
                - Are customers "mercy-buying" because they think Robinhood is too cheap (compared to old-school brokerages)?

                  - [[https://www.stockbrokers.com/guides/features-fees][stockbrokers.com: 21 Most Common Online Broker Features & Fees]]
                  - Comparison: In Indonesia, stock trading cost is about 0.02% of trade value.

    - A stock exchange starts out trading stocks,
      but after some time it begins trading other securities,
      but the name has stuck.

  - A /bond/ is a securitized loan?
  - Every asset can be securitized?
  - Stock

    - /Stock/ is company ownership.
    - A /share/ is a fraction of stock.
    - Buying share means buying partial company ownership.

- Undigested information

  - [[http://noahpinionblog.blogspot.co.id/2013/01/how-much-value-does-finance-industry.html][Noahpinion: How much value does the finance industry create?]]
  - Investing, speculating, or gambling?

    - Slap some "math" on gambling masquerading as "investing", and suddenly it looks legit.
    - "Modern investing: gambling in disguise", David Schneider

** Defining investing, trading, gambling, betting, wagering, insurance
*** Defining gambling
We say that a person /gambles/ iff he bets on an outcome that he doesn't know how to control at all.

Thus, there are two necessary conditions for something to be a gamble:
- There exists a bet.
- There does not exist control.

Other definitions of gambling:
- https://en.wikipedia.org/wiki/Gambling
- US legal definition https://definitions.uslegal.com/g/gambling/
*** How do we know something is not gambling?
**** If it's possible to be skillful, then it's not gambling.
*** What
- Investing
- Trading
- Betting
- Random/uncontrollable
- Individual outcome is unpredictable

Can two unskilled people playing chess control the outcome?

Wager and bet are synonyms.

The gambler doesn't have /any/ control over the outcome of a gamble.
How do we know if someone has some control? The ability to affect outcome. By how much? By physical explanation?
Too hard to predict?

The gamblers are gambling, but the casino isn't.
The casino can control the outcome.

Although the individual outcomes are unpredictable, the trend is predictable.

Insurance is reverse gambling, which is also gambling.
It is absurd to buy something that you avoid using.

- "What makes gambling wrong but insurance right?" https://www.bbc.com/news/business-38905963
- https://seekingalpha.com/article/4080260-insurance-gambling-seriously
  - "Insurance is a very specific type of gambling."
  - "Two parties agree on the consideration (by calling that wager a premium instead),
    the type of chance (by using expectations of when the insured might die, for example),
    and a prize (by referring to the winnings as a death benefit)."

Can you insure yourself against loss at the casino?

Is professional poker gambling?
If a skilled player can consistently beat an unskilled player, than the skilled player can control the outcome, and thus the skilled player is not gambling.

If skill (improvement) is possible, then it isn't gambling.

Can you be skilled in throwing dice so that you can consistently beat unskilled people?
Slot machines?
Guessing computer-generated numbers?
What is a possible physical explanation?

How do we argue that binary option is gambling?

I saw binary options marketed with fake Facebook comments.
I know those Facebook comments are fake because all of them have perfect grammar, capitalization, and punctuation.
Real Facebook comment threads are full of shit.
** "Investing"
What Bitcoin "investing" is:
- You buy a certificate of environmental destruction from someone, probably a "miner".
- You expect a greater fool to buy that certificate from you at a higher price.
  There are millions of other people who are looking for someone else more stupid than them.

Bitcoin is massive wealth transfer from late buyers to early buyers.
All financial investing is massive "realistic-return" Ponzi scheme.
Exactly fits the definition.
Newcomers pay oldtimers.
Late buyers pay early buyers.

Bitcoin is not necessary at all. It is pure want.
Inflation target disincentivizes currency hoarding.
A deflating currency encourages currency hoarding and discourages real spending.
https://www.cmegroup.com/education/featured-reports/an-in-depth-look-at-the-economics-of-bitcoin.html

https://www.theguardian.com/technology/2018/nov/05/energy-cost-of-mining-bitcoin-more-than-twice-that-of-copper-or-gold
** Economics, price, quality
Price is not important in itself.
It is the quality-price trade-off that is important.
People don't buy shit even if it's cheap, even if you pay them to buy it.

For an increment of quality, people are willing to pay an increment of price.
But there is a "good enough" point where people are satisfied and they just look at the lowest price.

Negative price means willingness to pay to get rid of something.
Example: rotten vegetables has negative price to most people, but positive price to farmers.
** Economics?
We should measure debt-to-income ratio instead of debt-to-GDP ratio?

Consumptive debt sacrifices future for the present.

Productive debt is good.

Example of productive debt:

Suppose that you want to buy a land to farm on it. These are the scenarios:
- You work for 20 years. Then you buy the land with cash. But the land price has risen.
- You take a loan, buy the land now, and repay the loan over 10 years. In the second year, your land starts producing.

If a person takes too much consumptive debt, he goes bankrupt.

If a government takes too much consumptive debt nominated in its own currency, it can print money to repay the debt, but such printing devalues the currency.

If the US continues to take loans mindlessly, it will have to choose:
- Default (refuse to repay).
- Suffer severe inflation (rising prices), if the creditors spend the printed money.

Does the USA think it can get away by refusing to repay its debts? It will trigger a huge power shift, maybe to China. Will China sacrifice itself to clean up America's mess? Will China buy up all US debts, and use the default as a reason to start a war?

https://deviantinvestor.com/9778/sacrificing-future-spending/

https://en.wikipedia.org/wiki/Unearned_income

Everything comes from nature.
We are not creating or destroying anything.
We are merely transforming things.
At least as seen from physics.

The number of atoms in Earth doesn't change.
(But what about solar wind? It does change a bit?)

Urban toilet harms humans and the Earth.
- We should poo squatting, not sitting.
- Urine and feces should be composted, not flushed down the drain.
- Compost bins should replace septic tanks.

https://www.vice.com/amp/en_us/article/zm95ka/republicans-are-outraged-about-the-deficit-they-caused

https://en.wikipedia.org/wiki/Unrestricted_Warfare
** There are only two ways to get rich: earn or steal
There are only two ways to get rich: /earn/ wealth or /steal/ wealth.

Earn wealth: convince people to give you money, by selling them things that improve their lives.
Use the money to develop your wealth even more.

Or steal wealth: An investor steals a little wealth from each person who does not invest.

After you obtain enough wealth, develop it, but don't lose all of them.
* Increase income without increasing maintenance burden
** Overview
We want to own systems that can run without ourselves.

Get rich quickly without going to jail.

Make capitalism work for us instead of making us work for capitalism.

Maximize long-term profit: maximize income, minimize expenses.

I am already very frugal by nature, so I have to combat my tendency to be fixated at minimizing expenses.

Business without employees[fn::https://www.entrepreneur.com/article/249868]

Find better use for the idly deposited moneys at the banks.
** Establish an empire
Establish a monarchy, a corporation, a business, because:
- Socialism for the rich and capitalism for the poor[fn::https://en.wikipedia.org/wiki/Socialism_for_the_rich_and_capitalism_for_the_poor]
- "The wealthy 'make mistakes', the poor go to jail"[fn::https://www.theguardian.com/commentisfree/2013/sep/08/wall-street-versus-poor-in-america]

There are 26.71 million non-agricultural businesses in Indonesia,
but most are small businesses.[fn::https://tirto.id/indonesia-kini-punya-2671-juta-perusahaan-cnz4]

Establish an Indonesian limited company (perseroan terbatas).

Forget IPOs.
Skip all the red-tape.
We want to keep our companies to ourselves.
We want 100% ownership.
*** Other people's business ideas
- Tech company that sells to engineers; companies like JetBrains (Mufid)
- Machine transcription of interviews in Bahasa Indonesia using speech-to-text (Mufid)
  - <2019-04-22>
    He tried GCP text-to-speech for Bahasa Indonesia but he found the result unacceptable.
- <2018-09-24> Undertaker, mortician, funeral home, mortuary (Willy)
- <2018-09-24> Dropshipping, buying from someone in Tokopedia and selling to someone else also in Tokopedia (Nigel)
- <2019-04-22> Catering at Karawang (Mr. Handoko)[fn::https://www.facebook.com/Dapur-Rempah-267685393886789/]
- Dyson: 6-billion-dollar 7000-employee company owned by one person[fn::https://www.quora.com/What-is-the-largest-company-owned-entirely-by-one-person]
  - These people have one seemingly simple business and they can reach billion-dollar net-worth.
- Patrick Bet-David's "10 Industries Facing Massive Disruption"[fn::https://www.youtube.com/watch?v=HuymeBMFe5I]
*** Flip companies; active investing
- Buy a company that is in shambles, fix it, refurbish it, clean it up, and sell it, hopefully for a profit.
- Help dying companies in exchange for partial ownership.
*** Basic definitions
Company
Enterprise
Business
Corporation
*** Memahami dasar hukum
**** Peraturan yang berkaitan
- UUPT adalah UU 40/2007 tentang perseroan terbatas ([[http://peraturan.go.id/uu/nomor-40-tahun-2007.html][html]]).
- UUTK adalah UU 13/2003 tentang ketenagakerjaan.
  - <2018-01-24> https://www.hukumonline.com/berita/baca/hol7529/uu-ketenagakerjaan-baru Beberapa pasal ada yang dicabut.
- UUHC adalah UU 28/2014 tentang hak cipta ([[http://www.dgip.go.id/images/ki-images/pdf-files/hak_cipta/uu_pp/uu_hc_%2028_2014.pdf][pdf]]).
- KUHPer adalah Kitab Undang-undang Hukum Perdata.
***** Notasi singkatan untuk rujukan
"UU 40/2007" berarti UU no 40 tahun 2007.

"UUPT 3:2" berarti UUPT pasal 3 ayat 2.
**** Badan hukum dan badan usaha
- https://id.wikipedia.org/wiki/Badan_hukum
- https://id.wikipedia.org/wiki/Badan_usaha#BUMS
- https://id.wikipedia.org/wiki/Perseroan_terbatas
- http://www.gresnews.com/berita/tips/82855-peraturan-badan-hukum-usaha-perseorangan/
***** A company is a virtual person. Can it be imprisoned?
https://slate.com/news-and-politics/2002/04/can-a-company-be-charged-with-a-crime.html
***** The corporate veil can be lifted according to UUPT 3:2.
**** Mendirikan perusahaan?
- Bagaimana?
- Bayar berapa?
- Berapa lama?
- Apa keuntungan pajak?
***** Permudah pembuatan badan usaha?
Bikin lebih mudah daripada Singapura, Hong Kong, USA, Estonia.

Tahun 2018, bikin PT di Indonesia masih terlalu sulit.
Mungkin harus tunggu sampai tahun 2025.

Cabut batasan nama PT tiga suku kata tanpa mengandung bahasa atau serapan asing.

- Cabut batasan PT harus punya alamat? Cukup alamat email?
  - Tidak bisa. PT harus punya alamat karena ada kebutuhan birokrasi surat menyurat.
- Indonesia
  - https://easybiz.id/prosedur-dan-syarat-pendirian-pt-terbaru-yang-wajib-anda-ketahui/
  - https://prolegal.id/2018/04/11/prosedur-syarat-pendirian-pt-2018/
- https://www.quora.com/Which-country-has-the-easiest-procedure-for-a-foreigner-to-start-a-business
- ga jelas, agak shady
  - https://flagtheory.com/the-best-place-for-an-internet-entrepreneur-to-incorporate/
  - http://nomadcapitalist.com/2016/05/25/best-country-online-company-incorporation/

Prosedur yang ideal?

- Applicant obtains approval of target neighborhood if necessary (if company operation is disturbing).
- Applicant registers company data.
- Government issues a legal certificate and a tax subject number.
- Done.

[[https://www.bps.go.id/website/fileMenu/Perka-KBLI-2015.pdf][KBLI 2015]] untuk PT yang bergerak di bidang software engineering dan programming language research:

- J.62, hlm. 402
- M.72, hlm. 439
****** <2018-10-05> Birokrasi Jakarta tidak bagus-bagus amat, tapi di luar Jakarta lebih parah lagi?
- https://medium.com/asepbagja/pengalaman-mengagumkan-mendaftarkan-perusahaan-di-estonia-33e2c10d7028:
  - 'Waktu itu notaris saya cuma bilang, "kalau mengurus di Tangerang akan sedikit lebih lama loh birokrasinya, Mas, dibanding Jakarta. Bisa beda sekitar 2 bulan."
    Saya pun setuju. Perkiraan saya paling juga Mei 2017 udah beres. Ternyata meleset hingga 6 bulan!'
  - "Update terbaru: Akhirnya beres setelah *9 bulan*!"
*** Mendirikan PT
**** Modal Disetor disetor ke mana?
**** Anggaran Dasar
Di sini "anggaran" berarti "aturan".
**** Mengangkat Direksi dan Dewan Komisaris
Direksi minimal 1 orang.

Dewan Komisaris minimal 1 orang.

Satu orang tidak boleh sekaligus menjabat sebagai Direksi dan Komisaris.
**** System for operating companies/enterprises: accounting, payroll, legal, tax, reporting, ERP, SCM, recruiting, ATS, etc.
openbravo, odoo
https://blog.capterra.com/top-8-freeopen-source-applicant-tracking-software-solutions/

Accounting system

Rekening bank pt

<2018-10-08> experimental:
- AISCO "Adaptive Information System for Charity Organization"
  from 2017 article "Feature Model-to-Ontology for SPL Application Realisation"
  https://arxiv.org/pdf/1707.02511.pdf
  http://www.aiscoweb.org/
**** Virtual office Jakarta? Barat? Selatan?
*** Laporan tahunan
*** Perencanaan pajak: bentuk usaha paling efisien pajak?
- [[http://ortax.org/ortax/?mod=issue&page=show&id=85&list=1&q=&hlm=2][ortax.org: Memilih Bentuk Usaha Yang Tepat Bagi Perencanaan Pajak]]
*** Tanggung jawab sosial dan lingkungan (TJSL) / corporate social responsibility (CSR)
- https://kliklegal.com/mengenal-sejumlah-regulasi-yang-mengatur-csr-di-indonesia/
*** Mempekerjakan orang lain
**** partnership vs employment: Bagaimana membedakan kontrak kerja sama dan kontrak ketenagakerjaan? Kontrak kemitraan vs kontrak kerja? Kontrak biasa vs kontrak kerja?
- https://www.hukumonline.com/berita/baca/hol20668/saat-hubungan-kemitraan-menjadi-hubungan-kerja
- https://www.hukum-hukum.com/2017/06/modus-menjadikan-pekerja-sebagai-mitra.html

To simplify operations, always partner, never employ.
Employment is heavily regulated because employment breeds inequality.

How do you partner with an accountant?
How do you partner with a supervisor?
How do you partner with a customer service officer?
How do you partner with operational staffs?

Is partnership always possible?

https://gajimu.com/pekerjaan-yanglayak/kompensasi/jam-kerja

**** Hak cipta, work-for-hire, IP (intellectual property) rights, HAKI/HKI (hak kekayaan intelektual)
***** TODO Cek UUHC: apa bisa lisensi: hak bebas royalti non-eksklusif yang tidak bisa ditarik kembali
***** Employee IP (intellectual property) assignment is unfair
Employee IP assignment is the practice where a company owns whatever its employees make.

Employee IP assignment is unfair and should be replaced with, at most, an irrevocable non-exclusive royalty-free license.

Employee IP assignment gives the company too much power over its employees.

Employee IP assignment contributes to inequality / social gap / wealth gap.
***** <2018-10-04> Tentang UUHC.
/Berikut interpretasi saya, bukan teks resmi. Saya mungkin salah. Ini bukan pendapat hukum yang sah./

Pasal 18: Hak Cipta tidak bisa dialihkan selamanya; ada batas waktu 25 tahun.
(Bagaimana jika Pemegang Hak Cipta meninggal sebelum 25 tahun berlalu sejak pengalihan?)

Pasal 36: "Kecuali diperjanjikan lain, Pencipta dan Pemegang Hak Cipta atas Ciptaan yang dibuat dalam hubungan kerja atau berdasarkan pesanan yaitu pihak yang membuat Ciptaan."
Ini berarti "Pencipta" dan "Pemegang Hak Cipta" bisa didefinisikan ulang oleh perjanjian kerja.

Bagian ketiga ("Hasil Karya yang Tidak Dilindungi Hak Cipta")

Pasal 41: "Hasil karya yang tidak dilindungi Hak Cipta meliputi: [...]
b. setiap ide, prosedur, sistem, metode, konsep, prinsip,
temuan atau data walaupun telah diungkapkan,
dinyatakan, digambarkan, dijelaskan, atau digabungkan
dalam sebuah Ciptaan; dan [...]"

Pasal 41 huruf b sangat rancu.
Penjelasannya berkata "cukup jelas".

Pasal 50:
"Orang dilarang melakukan Pengumuman,
Pendistribusian, atau Komunikasi Ciptaan yang bertentangan
dengan moral, agama, kesusilaan, ketertiban umum, atau
pertahanan dan keamanan negara."
Bahaya.
Pasal karet.
Bagaimana menentukan sesuatu itu bertentangan dengan moral/agama atau tidak?

Pasal 57: Beberapa hak moral berlaku selamanya.

Pasal 58 ayat 3:
"Pelindungan Hak Cipta atas Ciptaan sebagaimana dimaksud pada ayat (1) dan ayat (2) yang dimiliki atau dipegang oleh badan hukum berlaku selama 50 (lima puluh) tahun sejak pertama kali dilakukan Pengumuman."
**** Can employer-employee relations be replaced with buyer-seller relations?
Can a factory worker be allowed to work at any time he wants, at any duration he wants, and be paid by the amount of things he sold to his direct buyer?
*** Memperluas bidang usaha
**** Diversifikasi: Buat PT baru vs ubah akta pendirian
**** Ownership graph must be acyclic

*** Understand Indonesian incorporation laws
*** Indonesian company laws
UU pasar modal

UUPT 36:1: Ownership graph must be acyclic.

http://m.hukumonline.com/index.php/klinik/detail/lt4ee1cdcb3b9fc/status-direksi-perusahaan--pengusaha-atau-pekerja-revisi

https://www.hukumonline.com/klinik/detail/lt51b0380e6b9f8/bolehkah-menggeser-hari-libur-karyawan-tanpa-memberi-upah-lembur
Tidak boleh.

http://www.hukumperseroanterbatas.com/anggaran-dasar/anggaran-dasar-perseroan-terbatas/

https://www.hukumonline.com/klinik/detail/lt4cd0bd0284a71/perbedaan-modal-dasar--modal-ditempatkan--dan-modal-disetor-pt

https://media.neliti.com/media/publications/14073-ID-aspek-hukum-kelalaian-menyetorkan-modal-dalam-prosespendirian-perseroan-terbatas.pdf

https://www.hukumonline.com/klinik/detail/lt51426f0a4f0ee/fungsi-meterai-
**** Direktur bukan karyawan
Bolehkah direktur bekerja tanpa digaji? Boleh asal direkturnya bukan karyawan/pekerja/employee (hubungan kerja).
http://strategihukum.net/strategi-hukum-mengangkat-karyawan-menjadi-direktur
**** What
UUY Yayasan
https://www.putra-putri-indonesia.com/undang-undang-yayasan.html
- UU 16/2001
- diubah dengan UU 28/2004
- PP 63/2008

UU Pajak
https://id.wikipedia.org/wiki/Perpajakan_di_Indonesia
Susunan dalam satu naskah undang-undang perpajakan 2011 http://www.pajak.go.id/sites/default/files/PersandinganUUPerpajakan.pdf
UUPPh tentang pajak penghasilan
UUDP adalah UU 11/1992 tentang dana pensiun.

UUPPh 4:3L Beberapa beasiswa bukan objek pajak?
*** Anggaran Dasar
**** Definisi
Perusahaan adalah PT ... yang beralamat di ...
**** Maksud dan tujuan
1. Bertahan hidup.
**** Jangka waktu
1. Perusahaan mulai berdiri pada tanggal ...
**** Modal
1. Modal Dasar Perusahaan berjumlah Rp 100.000.000 (seratus juta rupiah).
*** Aturan Tambahan
**** Tentang Aturan Tambahan
1. Direksi berwenang mengubah Aturan Tambahan.
2. Aturan Tambahan bukan bagian Anggaran Dasar.
**** Saham
1. Perusahaan tidak mengeluarkan surat saham.
2. Bukti kepemilikan adalah Anggaran Dasar.
**** Direksi
1. Direksi tidak membuat rencana kerja tahunan.
2. Direksi menentukan atau mengubah cita-cita perusahaan.
**** Daftar Hitam
1. Perusahaan menyimpan Daftar Hitam.
2. Direksi berwenang mengubah isi Daftar Hitam.
3. Daftar Hitam berisi orang-orang yang pernah merugikan, menipu, atau mengkhianati Perusahaan.
4. Daftar Hitam mengandung nomor KTP, nama, alamat, foto KTP, deskripsi kerugian.
5. Daftar Hitam dipublikasikan di Internet.
6. Perusahaan secepatnya memutuskan semua perjanjian dengan orang dalam Daftar Hitam.
7. Perusahaan tidak membuat perjanjian dengan orang dalam Daftar Hitam.
**** Principles
1. There should be at most one way to do something.
*** Network?
** Meterai
- Meterai adalah syarat supaya pengadilan menerima suatu dokumen sebagai alat bukti.
- Ketiadaan meterai tidak mengubah keabsahan suatu perjanjian, tapi surat perjanjian tanpa meterai tidak bisa dijadikan alat bukti di pengadilan.
- Surat perjanjian tanpa meterai dapat dijadikan alat bukti di pengadilan dengan pemeteraian kemudian,
  tapi tata caranya tidak jelas, jadi lebih baik /setiap surat yang mungkin dijadikan alat bukti di pengadilan dimeteraikan sejak awal/.
- Apa gunanya surat perjanjian kalau tidak bisa digunakan sebagai alat bukti oleh pengadilan?
- http://www.hukum123.com/mengapa-kita-harus-menggunakan-materai-2/

** Benefiting from the state, for Indonesians
lelang barang sitaan KPK, BRI, dll. (tanah murah, mobil murah)
https://lelang.go.id/
** Extract wealth from society by seeking rent
There are still rooms for rent seekers.

If everyone seeks rent, nobody works, and everyone dies.

If some people seek rent, then those people will be disproportionately enriched.

Seek rent[fn::https://en.wikipedia.org/wiki/Rent-seeking];
use the law to get paid for simply owning something and doing nothing.
*** Own a property
- Buy a property, contract a management agency, and lease the property
  - Find good properties; determine what is good
    - Why do people stay at hotels? Attending events. Meetings. Inspections. A combination of closeness to the actual location of interest and the hotel's reputation. People stay at a hotel not because they admire the hotel building, but because they care about the location.
    - Unmarried white-collar workers choose the cheaper between renting and commuting.
    - Nomads who change work location every a few years, and people without enough money to buy houses
- Determine why people pay
  - The only reason people pay you is that they believe you will give them what they want.
- Start a hype-laden "startup" and sell it to "investors"
*** Get rich quickly from financial markets
**** Practice usury, lend money with interest, crowd-lending
Vestifarm[fn::https://vestifarm.com/] is a platform for crowd-lending to micro-agribusinesses,
with a return of up to 18% per 4 month (as advertised on <2019-04-22>).

Akseleran[fn::https://www.akseleran.com/].
***** Own a bank with zero employees, without physical presence, without customer support
So that we can make our own money,
charge interests, take some wealth from borrowers, with little hassle.
 [fn::https://www.youtube.com/watch?v=ZzCegQVljdY]

**** Invest
What?
- Wealth Extraction Efficiency = Dividend / Equity
  - Dividend is shareholder's dividend
  - Equity is book value
  - If reading consolidated report, use the one attributable to parent entity
- Time to buy? Mungkin beberapa bulan setelah lebaran.
  - 2018, https://www.reddit.com/r/indonesia/comments/8l9yc7/indonesias_stock_rout_claims_another_victim_the/
  - https://www.reddit.com/r/indonesia/comments/8l4ykk/why_an_emerging_market_rout_has_hit_indonesia_so/
    - https://www.bloomberg.com/news/articles/2018-05-09/why-an-emerging-market-rout-has-hit-indonesia-so-hard-quicktake
    - Why do they disapprove of Sri Mulyani?
- Everyday there are stocks that rise by 20% and there are stocks that fall by 20%.
  - If we can predict which will rise, we can get rich quickly.
  - Why do prices rise?
    Because buyers concede to sellers.
    - Because there is more buying pressure than selling pressure.
    - Because there is more buy orders than sell orders.
    - Because more people buy.
    - Because less people sell.
    - Because more people buy.
  - Why do people buy a stock?
    - Because they believe it will rise.
      - Why do they believe so?
        - Fallacious reasoning.
          Psychological bias.
          Appeal to authority.
          Hearsay.
          Fear of missing out.
          Irrational exuberance?
    - Because they believe it will give them dividends.
    - https://money.stackexchange.com/questions/82057/what-factors-make-someone-buy-or-sell-a-stock
  - How do we persuade/encourage people to buy a stock?
    How do you market a stock?
    - This is gray area.
      Is it even legal?
  - How do we prevent sellers from selling?
- Hypothesis: Some companies' financial statements predict economic/financial crises.
  - How are economic crises even possible if there is enough money for everybody?
    - Uneven distribution of money?
    - Hypothesis: The solution to an economic crisis is a forced redistribution of money, an economic reboot/restart, however unpleasant.
      - In an economic crisis, tax the wealthy and pay the poor.
      - I think that is an optimal solution (if not the only solution), but that is politically incorrect, so we'll never see that.
    - If ignored, economic crisis will escalate to sociopolitical crisis.
- Banks lend money with interest.
  Thus, paying back the loans reduce circulating money.
- https://iextrading.com/
  - the only independent stock exchange in the USA
  - http://hackage.haskell.org/package/stocks
- daftar (list) reksadana https://www.indopremier.com/ipotfund/listreksadana.php
- 2018-10-10: GarudaFood mau IPO!
  - http://investasi.kontan.co.id/news/bersiap-masuk-bursa-garudafood-akan-melepas-10-saham
  - https://investasi.kontan.co.id/news/menanti-ipo-jumbo-dari-garudafood
- Read Benjamin Graham value investing?
- Mana yang mujarab? Belum ada yang saya coba.
  - Teguh Hidayat
    - [[https://www.teguhhidayat.com/p/ebook-analisis-kuartal-i-2014.html][Indonesia Value Investing: Ebook Analisis Kuartal II 2018]]
    - [[https://www.thpartner.com/][Indonesia Value Investing]]
  - [[http://galerisaham.com/][galerisaham.com]]: rekomendasi saham harian; GS Pro
- [[https://deep-throat-ipo.blogspot.com/][deep-throat-ipo.blogspot.com]]
- http://www.sahamok.com/tentang/
- https://www.kemenkeu.go.id/single-page/savings-bond-ritel/
- https://sbn.investree.id/
- List of traded things
  - [[http://www.idx.co.id/id-id/beranda/informasipasar/saham/ringkasansaham.aspx][Stocks]] sortable by price, "value" (I thought it was market capitalization), volume, frequency
  - [[http://www.idx.co.id/id-id/beranda/informasipasar/daftarefek/saham.aspx][Stocks]] sortable by category ("board"), IPO date, number of shares
  - [[https://id.wikipedia.org/wiki/Daftar_perusahaan_yang_tercatat_di_Bursa_Efek_Indonesia][Stocks]], from Wikipedia Indonesia, linking to IDX pages
  - [[http://www.idx.co.id/id-id/beranda/informasipasar/daftarefek/etf.aspx][ETFs]]
  - [[http://www.idx.co.id/id-id/beranda/perusahaantercatat/aktivitaspencatatan.aspx][IPOs, delistings, and relistings]]
  - forex = foreign exchange
  - CFD = contract for difference
  - IndoCDS? credit default swap? apa ini? apakah traded?
- Announcements about the securities being traded
  - In practice, you get these news from your broker's application, not from IDX website.
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/pengumuman.aspx][Announcements]] (delistings, mergers, shareholder meeting invitations, etc.)
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/unusualmarketactivity.aspx][Unusual market activities]]
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/suspensi.aspx][Temporary trading suspensions]]
- Brokers
  - [[http://www.idx.co.id/id-id/beranda/anggotabursaamppartisipan/anggotabursadikotaanda.aspx][Find a broker near you]]
- Regulations
  - [[http://www.idx.co.id/id-id/beranda/tentangbei/mekanismeperdagangan/jamperdagangan.aspx][Trading hours]]:
    - practically 09:00--11:30 and 14:00--15:50 UTC+7, except Fridays
  - [[http://www.idx.co.id/id-id/beranda/tentangbei/mekanismeperdagangan/saham.aspx][Settlement]]:
    - practically T+3, where T+0 is the transaction date
  - [[http://www.idx.co.id/id-id/beranda/beritadanpengumuman/jadwalliburbursa.aspx][Holiday schedule]]
  - [[http://www.idx.co.id/id-id/beranda/tentangbei/strukturpasarmodalindonesia.aspx][Struktur pasar modal Indonesia menurut UU 8/1995]]
- [[https://en.wikipedia.org/wiki/Industry_classification][Industry classification]]
- Indonesia company types
  - [[https://id.wikipedia.org/wiki/Badan_usaha#Persero][What is BUMN/BUMD Persero?]] (Wikipedia Indonesia)
- Financial reports
  - [[https://www.abdainsurance.co.id/index.php?option=com_content&view=category&layout=blog&id=41&Itemid=136&lang=id][ABDA]] (PT Asuransi Bina Dana Arta Tbk)
  - [[http://www.bca.co.id/Tentang-BCA/Hubungan-Investor/Laporan-Keuangan/Laporan-Finansial-Per-Kuartal][BBCA]] (PT Bank Central Asia Tbk)
  - [[http://phx.corporate-ir.net/phoenix.zhtml?c=148820&p=irol-reportsOther][BBRI]] (PT Bank Rakyat Indonesia (Persero) Tbk)
  - [[http://ir.bankmandiri.co.id/phoenix.zhtml?c=146157&p=irol-finStatement][BMRI]] (PT Bank Mandiri (Persero) Tbk)
  - [[http://ir.matahari.co.id/phoenix.zhtml?c=171562&p=irol-reportsother][LPPF]] (PT Matahari Department Store Tbk)
  - [[http://corporate.ramayana.co.id/index.php/en/investor-relation-2/financial-information/financialreports][RALS]] (PT Ramayana Lestari Sentosa Tbk)
- Banks
  - [[http://media.corporate-ir.net/media_files/IROL/14/148820/BRI_ENG_31%20Dec_2016_Released_Password_Removed.pdf][BBRI 2016]]
  - [[http://media.corporate-ir.net/media_files/IROL/14/146157/Bank-Mandiri-Tbk_Ind_31_Desember_2016_Released-.pdf][BMRI 2016]]
- Insurance
  - [[https://www.allianz.co.id/tentang-kami/finansial#keuangan][Allianz ID]] (PT Asuransi Allianz Life Indonesia)
  - [[https://www.prudential.co.id/corp/prudential_in_id/header/aboutus/financialstatement/index.html][Prudential Indonesia]]
  - 2016 annual reports:
    - [[https://www.abdainsurance.co.id/abdanew/lap_keu_thn/Final%20Report%20ABDA%2031%20Des%202016%20with%20opini.pdf][ABDA]]
    - [[https://www.prudential.co.id/export/sites/default/prudential_in_id/resources/downloads/financialstatement/2017/FS_Audited_2016.PDF][Pru]]
- Things that make me sad
  - Back button doesn't work on the IDX website.
- Thanks but no thanks. I'll stick to stocks for now.
  - http://www.brokerforexindo.com/
  - http://www.nfa.futures.org/basicnet/SearchResults.aspx?type=firm&firm=FXCM
  - national futures association http://www.nfa.futures.org/
  - http://www.bappebti.go.id/id/api/pialang_dicabut.html
  - http://www.e-bursa.com/
  - http://www.bloomberg.com/quote/LMAS:IJ
  - http://topbrokerforex.blog.com/2012/08/02/daftar-badan-regulasi-untuk-broker-forex/
- https://en.wikipedia.org/wiki/Outline_of_finance#Post-modern_portfolio_theory
- Measuring investment performance
  - https://en.wikipedia.org/wiki/Sharpe_ratio
  - https://en.wikipedia.org/wiki/Sortino_ratio
**** Trade financial assets: stocks, derivatives, currencies
- For a beginner, merely not losing money is already a splendid start!
- Calculate the fair price of a financial asset
- [[file:reveng.html][Reverse software engineering]]
  - [[file:rejava.html][Reverse engineering the network protocol used by a Java desktop application]]
- How much should we bet?
  - Kelly criterion
**** Start a gambling or insurance company
**** Open a do-it-yourself brokerage with no employees and no customer support
Having more participants means having more wealth to extract from.
** Create wealth?
** Move?
Move to Scandinavia?[fn::Does this article make sense? http://evonomics.com/where-in-the-world-is-it-easiest-to-get-rich/]
But the climate is harsh?

Move outside Jakarta?
But what opportunities?
** Have a high-income skill
Examples:
thinking, planning, and software engineering.
* Reduce expenses
** Minimize operational/administrative/bureaucratic/red-tape hassle
Avoid dealing with labor laws; use contractors, freelancers, etc.

Can we operate a company with no employees?
 [fn::https://www.quora.com/Could-you-operate-a-company-with-no-employees-only-contractors]
 [fn::https://www.quora.com/How-do-you-build-a-company-without-employees-but-still-create-a-profitable-organization]
 [fn::https://www.forbes.com/sites/allbusiness/2018/07/26/build-million-dollar-business-with-no-employees/#c4079af270f6]

Contractors do not mean fire-at-will.
Ideally a business relationship improves as time goes by.
** Minimize tax
*** Maximize non-taxable income
*** Minimize taxable income
- Maximize asset without mark-to-market
- Minimize profit
*** Maximize tax deductions
*** Plant anti-taxation people in the government
** Write an enterprise operation system in Prolog
- Write an accountant in Prolog
** Make machine work more
*** Improve machine intelligence
- [[file:intelligence.html][Making intelligence]]
- [[file:endo.html][The endofunction model of worlds and agents, and its philosophical implications]]
- Find how to make machine understand causation, in principle; find the theory
  - How do we make a machine that understands causation?
    - "Causal Cognition in Human and Nonhuman Animals: A Comparative, Critical Review", 2007[fn::http://derekcpenn.com/Penn_2007-Causal_Cognition_in_Human_and_Nonhuman_Animals.pdf]
    - "Causal Reasoning in Rats", 2006[fn::https://www.psych.uni-goettingen.de/de/cognition/publikationen-dateien-waldmann/2006_science.pdf]
    - "Causal knowledge in animals", 1995
    - Understand reality, the world, the Universe
      - [[file:philo.html][Philosophy]]: armchair philosophy; should be rewritten to focus on causation
        - [[file:mind.html][Mind]]: philosophy of mind
      - [[file:nature.html][Nature Research Group]]: physics and its philosophy
- Demonstrate that a machine understands causation
  - How do we know whether X understands causation?
*** Multiply software engineer productivity by 20?
- [[file:softeng.html][Software engineering]]: come up with a science to underlie software engineering
  - Measure programmer productivity
- [[file:prolog.html][Use the Prolog programming language]]
  - Make Prolog more suitable for programming in the large
    - Make a module system for Prolog
  - [[file:enterprise.html][Use Prolog for model-driven software engineering]]
  - Make an untyped Haskell/ML-like language in Prolog
  - Seamlessly interoperate programming languages
    [fn::I desire more than Will Crichton; I do not want to add annotations to the original code http://willcrichton.net/notes/the-coming-age-of-the-polyglot-programmer/]
    - 1996 \cite{barrett1996automated}
    - [[file:program.html][Programming Research Group]]: these should be merged?
      - [[file:proglang.html][programming language design]]
      - [[file:program-sketch.html][sketching a declarative programming language]]
      - [[file:semantics.html][Semantics Research Group]] (of programming languages)
- [[file:opensrc.html][Making contributable open-source projects]]
  - [[file:community.html][Building online communities]]
* Build human resource
- Educate software engineers to a comparable quality but faster than the 16 years of formal education
  - Make all Indonesian people understand English,
    because most relevant resources on the Internet are in English
** Have as many powerful descendants as possible
We can think of our family as cheap loyal labor.

In 2019 it costs Rp 150,000/day to decently feed a person in Jakarta.

What is the ROI (return-on-investment) of a child?

In agricultural societies, more children means more labor, and more labor means more wealth.

This is not true in knowledge societies such as cities.
*** Impregnate as many women with good genetics as possible
Without going to jail, of course.

How many women did Genghis Khan impregnate?
 [fn::https://www.dailymail.co.uk/news/article-456789/Genghis-Khan-The-daddy-lovers.html]
 [fn::https://thetyee.ca/Books/2010/07/26/GenghisFeminist/]

Who are the men who have the most children?
 [fn::https://www.quora.com/Who-is-the-man-who-impregnated-the-highest-number-of-women-in-modern-history]
 [fn::https://en.wikipedia.org/wiki/List_of_people_with_the_most_children]

With sperm bank, artificial insemination, in-vitro fertilization,
and other reproductive technologies, we can be even more prolific than Genghis Khan.

We may want to do such thing in the 21st century
without the 13rd century plunder, rampage, and rape.
 [fn::https://en.wikipedia.org/wiki/Genghis_Khan]
 [fn::https://en.wikipedia.org/wiki/Mongol_invasions_and_conquests]
 [fn::https://en.wikipedia.org/wiki/Destruction_under_the_Mongol_Empire]
* Make more things doable without going to jail
** Reduce the ability of government to jail people
*** Downsize the government, relax the laws
Put anti-regulation people in the government;
laissez-faire liberals;
anarcho-capitalists;
unwitting opinionated idealistic hard-liners;
"confused and misguided sympathizers"[fn::https://en.wikipedia.org/wiki/Useful_idiot].
* What?
** Economics vs finance
- Which is more fundamental, economics or finance?
  Which is built on which?
** Establish company
- The problem with opening a business is too many choices.
  - Almost all businesses make money.
  - Every obvious business idea is already taken.
** Frank Abagnale tips
- 2017, 1 hour, [[https://www.youtube.com/watch?v=vsMydMDi3rI][Frank Abagnale: "Catch Me If You Can" - Talks at Google]]
  - Use credit card, not debit card.
    - Use credit card, but don't fall into debt.
      Treat credit card as means of payment, not loan.
    - Never use debit card outside trusted ATMs.
    - But what about cash withdrawals from ATMs?
      Credit cards have higher fees.
    - https://www.nerdwallet.com/blog/credit-cards/credit-card-vs-debit-card-safer-online-purchases/
    - https://www.quora.com/Are-credit-cards-safer-than-debit-cards
    - Banks want you to use the debit card because it reduces their liability?[fn::https://www.chimebank.com/2017/08/08/are-credit-cards-really-safer-than-debit-cards/]
  - Passwordless authentication
    - Authentication with a phone, without username, without password: [[https://www.trusona.com/][Trusona]], from the Frank Abagnale 2017 Google talk above.
    - https://hacks.mozilla.org/2014/10/passwordless-authentication-secure-simple-and-fast-to-deploy/
    - 2014, Justin Balthrop, "The basic idea is that instead of using a password to authenticate each user, a temporary secret code is sent to them over a secure channel."
      ([[https://medium.com/@ninjudd/passwords-are-obsolete-9ed56d483eb][source]])
- The job of a company (a company director?) is to find what to do and find who should do it.
  - Everyone has different tendencies, strengths, weaknesses, desires, preferences, habits, upbringings, backgrounds.
  - Some people are more suited for some jobs.
    - Some jobs require high IQ; otherwise the employee will take too long to learn.
    - Some jobs require low IQ; otherwise the employee will get bored too soon.
  - The company has goals.
  - The director breaks down the goals into jobs.
  - The director matches employees and jobs.
  - Which comes first: the job or the employee?
    - Do you formulate a job description first, and then find people to do that?
    - Do you hire people first, and then formulate jobs suitable for them?
  - A good company accomplishes more than each employee can accomplish individually.
- [[https://www.youtube.com/watch?v=cWVk8Cdvmgs][Who controls the world? - James B. Glattfelder]]
  - physical modeling/explanation of financial inequality
- [[https://www.youtube.com/watch?v=QX3M8Ka9vUA][The Third Industrial Revolution: A Radical New Sharing Economy]]
  - Jeremy Rifkin, Third Industrial Revolution, sharing economy, Germany, Digital Europe, China Internet Plus, aggregate efficiency, distributed system
    - The Second Industrial Revolution peaked at 20% aggregate efficiency.
    - Difference between post-Westphalian worldview and Millenial worldview.
      - The 21st century way of living is radically different.
        Different ideas of freedom.
        - In the post-Westphalian worldview, freedom means sovereignty, being autonomous, being an island.
    - Second Industrial Revolution teaches kids to be factory workers. Obedient. Unquestioning. Hardworking.
  - [[https://www.youtube.com/watch?v=3xOK2aJ-0Js][Jeremy Rifkin on the Fall of Capitalism and the Internet of Things - YouTube]]
- [[https://www.youtube.com/watch?v=mAOyOULWKUo][Corporate Greed Isn't New. The Internet Is Just the New Playing Field, says Douglas Rushkoff - YouTube]]
  - Corporates were invented by aristocrats to make sure peasants stay peasants?
  - [[https://bigthink.com/videos/douglas-rushkoff-on-the-internet-and-the-future-of-business][transcript]]
    - We should verify and distill these texts.
      These are some bold claims.
      - "As the peasants became wealthy the aristocracy got scared, who are these people?
        They're not going to be dependent on us any more.
        So they came up with two main financial innovations to prevent the rise of this peer to peer economy.
        The first one was the chartered monopoly, really the parent to the modern corporation.
        All the chartered monopoly was was a way to say all of you small businesses are now illegal.
        If you want to be in the shoe business you have to work for his majesty's royal shoe company.
        You want to be in the grain business you have to work for his majesty's royal grain company.
        So people who were small business people now became employees.
        Instead of selling the value they created, now they sold their time as servants, as wage laborers."
      - "The second invention they came up with was central currency.
        Not such a terrible thing in itself.
        It's great to have a long distance currency that lots of people can use and value, but the problem was they made all of the local currencies illegal.
        So the only way people could trade with each other, the candlestick maker could trade with the chicken farmer was by borrowing central currency from the treasury.
        So now you had to borrow money at interest just in order to transact.
        And that set in motion really a growth cascade.
        If you have a currency that has to be paid back with interest, in order to just make end meet you need an economy that's growing.
        You need more money next year than there was this year."
      - "So that worked well for colonial powers, as long as we could extend into Africa and South America and North America, find slaves, find new resources, we could grow.
        But what happens when you reach the end of the planet's growth as we did really at the end of World War II?"
- [[https://www.youtube.com/watch?v=6_n1Dro0Uec][Online Companies Like Facebook Have Created a Meaningless Economy, says Douglas Rushkoff - YouTube]]
- Work-life balance?
  - Don't confuse being busy and working.
    - Work should create value.
    - You can feel busy while not producing anything.
    - Work has goals. Being busy doesn't have goals.
  - People don't care about processes.
    They only care about results.
  - If you are not working in all your waking hours, then it's not the work you want.
  - If I could work in my sleep, I would!
- Transport is waste.
  Hence travel is waste.
- Why can't people stay at home on holidays?
  - If you don't like staying at home on holidays, that means something is wrong with your home.
    Fix it.
    Make it the best place on Earth.
    Face reality.
    Don't escape.
- https://www.quora.com/What-are-possible-warning-signs-of-an-imminent-economic-collapse
- Communism
  - The USSR was beyond communism; it was Stalinism.
  - Stalinism failed because it overcentralizes power.
    - Power corrupts.
    - Oppression isn't a good long-term strategy.
    - People are like gas.
      - Increasing pressure (oppression, stress, overcrowding) increases temperature (collisions, friction, conflicts, clashes).
  - People would still work even if they couldn't get rich.
    - People work to give their life meaning, not to get rich.
      - Getting rich is a side-effect.
    - Would they work better if they could get rich?
- If you buy land and let it idle, only to sell it higher in the future, then you're /seeking rent/.
  - You are not creating any value.
    You burden society.
    You get rich by burdening others, making them poorer.
    The world is better without you.
    You contribute to city sprawl, which causes winding roads, more fuel consumption, more traffic, more pollution, and more heat.
    You should be heavily taxed for the huge negative externality you cause.
- Is all speculation rent-seeking?
** Dan Lok
3 Types Of Employees (grunt, mercenary, and patriot) - How To Hire
https://www.youtube.com/watch?v=kILJN6eu1P8

How To Build Systems In Your Business - Systemize Your Business Ep. 7
https://www.youtube.com/watch?v=2g6sTH8FiFY

Kingpin strategy: Sell to the person who matters, who can bestow you authority, everyone else follows;
"The One Thing You Can Do To Grow Your Business And Sales Faster"
https://www.youtube.com/watch?v=M33aMYxuY60

How To Get What You Want - 3 Proven Persuasion Tactics
https://www.youtube.com/watch?v=nLA_T1AXd6o
** If you win a lottery
Don't tell anyone.
Even families, friends, and lovers.
** Justify my value
- <2018-08-18>
  - Today, in an hour, I advised my friend.
    My advice, if implemented, would save him Rp 450 million / year.
    His cost is Rp 3000 million / year.
    He makes 300 sales per year.
    - Talking with me for an hour could cut your business unit economic costs by 15%.
    - Should I be a SME (Small and Medium Enterprises) consultant?
    - Is Rp 450 million / year big?
    - Is 15% unit economics improvement big?
  - Inefficiency kills a company.
    A competitor finds a more efficient way to do the same thing.
    Either slowly/incrementally from an ordinary competitor, or radically/disruptively by an unexpected competitor.
** Morality of power?
- Is evil a necessity or a consequence?[fn::https://tvtropes.org/pmwiki/pmwiki.php/Main/SlowlySlippingIntoEvil]
- Power corrupts, but with more power we can do more good?
** Morality of capitalism
- How is it good?
  - Capitalism enables selfish people to better everyone else.
  - Voluntary exchange betters everyone.
    - People don't agree to a deal they think bad for them.
- How is it bad?[fn::https://en.wikipedia.org/wiki/Criticism_of_capitalism]
  - Wealth gap? Social gap?
  - Capitalism places capital above labor?
  - Short-term profit-seeking and rent-seeking destroys environment and humanity?
- How can it be improved?
  - Regulation
    - [[https://www.youtube.com/watch?v=YOaJe68C-bU][How to Improve Capitalism]]
  - Capitalism can be environmentally friendly if the polluters pay the environmental costs.
    - 2018: other people are still paying the cost. (Negative externality)
      - Can sustainability be made profitable?
        - Pessimistic sources
          - https://grist.org/business-technology/none-of-the-worlds-top-industries-would-be-profitable-if-they-paid-for-the-natural-capital-they-use/
          - https://www.theguardian.com/sustainable-business/blog/sustainability-business-sense-profit-purpose
          - https://www.theguardian.com/environment/2010/feb/18/worlds-top-firms-environmental-damage
