#+TITLE: On my plan to save myself and perhaps some people
#+DATE: 2019-08-30 00:00:00 +0700
#+PERMALINK: /save.html
* Background
I saw the news: Jakarta is going to sink by 2050.

I can only depend on my present self to save my future self.
No company is going to solve the climate crisis,
because no company is going to profit from solving it.
Also, we are bad at predicting long-term consequences;
we are doomed;
we are regressing to anarchy.

But fortunately I live in Indonesia
that has natural advantage in food growing.
It has tropical climate.
The sun shines all year.
The rainfall is abundant.
The soil is fertile.
Rivers, volcanoes, seas, and fish abound.
Plants grow without even trying.
In satellite photos, Indonesia looks green everywhere.

I have to feed myself and move to higher ground.
Then perhaps later I can help lift others out of poverty,
because Nature pays everyone who works.
Indeed all wealth, even our Labor, comes from Nature:
Everything in our body, and the food we eat to work, all come from Nature.
** <2019-07-06> Digression: Jakarta the doomed city
Jakarta is sinking into the sea.
 [fn::Jakarta Is The World's Fastest-Sinking City (HBO) https://www.youtube.com/watch?v=dNE5aptbGyY]
 [fn::Jakarta is sinking! - Equator from the Air - BBC https://www.youtube.com/watch?v=qOSwBIstZUs]
At the same time, the sea is rising due to melting polar ice due to climate change.
Also recently there was an all-time-high level of air pollution.
The future is grim.
Only a natural disaster can fix this sinking polluted overcrowded city.

Jakarta is barely livable.
Atrocious traffic.
Severe dust.

Why aren't there more buses?
Why aren't there more routes?
How hard is it to start a bus company?
Why, in the last 30 years, has there never been a bus route through my area?

<2018-09-22>
Jakarta is sinking, unless we stop draining the aquifer below it.

An animation[fn::1:55 in https://www.youtube.com/watch?v=dNE5aptbGyY] explains why:

- People pump the aquifers out.
- Rain can't replenish the aquifers because Jakarta is wrapped in concrete.
- There is no more underground water to press the land up.
- The land sinks.

North Jakarta is sinking by up to 20 cm per year.

Meanwhile, the government is planning to move the capital from Jakarta to somewhere in Kalimantan.

Is there anything safe to eat?
Is it safer to eat hormones-and-antibiotics-laden chicken or pesticide-laden plants?
Are city-dwellers doomed to eat shit?

Cheap meat can be bought online from PD Dharma Jaya[fn::http://dharmajaya.co.id/][fn::http://smartcity.jakarta.go.id/blog/198/beli-daging-online-dari-perusahaan-daerah-dharma-jaya]'s
DJMeatshop[fn::https://www.instagram.com/djmeatshop/] at Jl. Raya Penggilingan no. 25, Jakarta Timur.
I found these while browsing the Internet, but I never tried these.
I don't know how cheap.[fn::http://m.warungdaging.com/#features]

Somewhat useful government websites:
- Commodity price list[fn::http://infopangan.jakarta.go.id/]
- PD Pasar Jaya commodity price list[fn::http://www.pasarjaya.co.id/komoditas]

Jakarta Barat traffic hotspots:
- Pom bensin di Kemanggisan bikin macet tiap jam makan siang.
  Mobil yang ngantri banyak, stasiun yang buka cuma satu.
- Tempat makan di Tanjung Duren bikin macet, terutama Pisang Goreng Bu Nanik.
  Bikin tempat makan tapi tidak bikin tempat parkir.
  Parkir di jalan.
  Mengganggu kepentingan umum.
  Negative externality.
  Seperti buang limbah ke sungai.
- Green Ville terlalu banyak tempat makan.
  Setiap Sabtu macetnya sampai Jalan Panjang.
* Level 1: Hobbyist backyard small-plant planter
Which plant should I plant?
The criteria:
- nutritious, should contain essential nutrients
- delicious for me
- thrives in my surroundings, suitable habitat
- small, not much taller than I am

I like to eat these plants, so I want to plant them in my backyard:
- garlic, bawang
- Etlingera elatior, kecombrang
- rebung/bambu
- ginger, jahe
- sesame, wijen
- broccoli
- green bean, kacang hijau, buncis
- soybean, kedelai

How do I get started?
Where do I buy the pots, soil, and seeds?

/A little basic knowledge/ suffices in order to begin planting some seeds.
Don't worry about getting an undergraduate degree;
we're just starting a personal garden to feed ourselves for fun.

Buy a bucket and a shovel.
Shit and piss in the bucket.
Dig some hole with the shovel, pour the bucket's contents,
and bury the shit and piss with some dead plant parts and leftover vegetables.
Beware that the more nutritious the compost pile is (such as due to meat or fruit), the more it invites rats.
I left a small cut of a thumb-sized pineapple pulp, and, a few hours later, a rat came.

As your harvest increases, you may improvise with plastic bags to reduce the number of round-trips you make to move the harvest to your storage.
As your harvest outgrows the plastic bags, you may buy a /wheelbarrow/.

It is more expensive but less effort to buy a farm from a retiring farmer than to transform a pristine patch of land.
You get what you pay for, assuming that you do due diligence?
** How to choose pots
It suffices to answer two questions:
1. Will the pot fit the plants?
2. Will I be able to hold and lift the filled pot when the plants mature?

First, it has to fit the /plants/:
The pot has to be large enough for the roots when the plants mature, but not too large that space is wasted.

Second, it has to "fit" /you/:
The dimension and weight of the filled pot is such that you can comfortably /hold and lift/ it and all its contents (the soil and the plants when they /mature/).
** Tools
*** Conventional tools
Hoe, spade, knife, scissors, etc.

For protection against the sun: hats, long-armed white loose thin cotton shirts, long white loose thin cotton pants.

For protection against things in the soil: long gloves and high boots.
*** Plant identification tools
Does PlantSnap[fn::https://www.plantsnap.com/] work with Indonesian plants?
** Plants in my yard
Scadoxus multiflorus[fn::https://en.wikipedia.org/wiki/Scadoxus_multiflorus]
("Bunga November", "Bunga Desember", apalah, di tempat saya berbunganya bulan Agustus.)

Murraya paniculata[fn::https://en.wikipedia.org/wiki/Murraya_paniculata] (kemuning)
** What plant?
dragon fruit cultivation
https://www.botanical-online.com/en/cultivation/dragon-fruit-how-to-grow
Evolutionarily natural habitat
- "In nature, these plants grow under the canopy of trees."
- "Annual rainfall: 800mm to 1,500mm"
- "Temperature: 18 to 26 deg C"
- "Drought resistant and sensitive to cold"
- "Deep and well drained soils"
- seed or vegetative reproduction (cactus)
"Plants can take up to five years to come into full commercial production"
What is the natural seed dispersal method of

Jual tanaman hias lebih untung?
Roses? Orchids?
Mawar? Anggrek?
** Growing medium
Plants do not need soil; they need a /growing medium/ (a medium for growing, not a medium that is growing).
The purpose of the growing medium is to hold water and nutrients such that plant roots can absorb them.
It has to be slightly /porous/ and it has to have the right granularity.
If the grain is too small, the medium will dissolve in water.
If the grain is too big, the medium will not hold water.
** Humanure composting
Rob Greenfield[fn::I Compost my Own Poop! Humanure https://www.youtube.com/watch?v=h1c7voDyIGc].
** Backyard permaculture
* Level 2: 100-square-meter medium-tree planter
Now it's time to move out to somewhere less crowded,
because we are going to deal with smelly things such as compost piles,
animals, and manure, and our urban neighbors would complain.

Buy a patch of land with a reliable water source.

Limit to 100 square meters, or you'll be overwhelmed.

Raise chickens?

In 2019, there is still /a lot/ of untouched land, even in the island of Java alone.
Not everyone has to live in cities.

- Moringa oleifera[fn::https://en.wikipedia.org/wiki/Moringa_oleifera], kelor[fn::https://id.wikipedia.org/wiki/Kelor], drumstick tree;
  Wikipedia says that this tree is a fast-growing, long-living, heat-tolerant, 7-to-11-meters-tall, aggressive invasive species;
  I think the tree must absorb /a lot/ of nutrients from the soil in order to do that.
- cacao fruit
** Get a car?
For moving between home and farm, and to move the harvest to the market.
*** Get a driver's license?
SIM B2?

What is the penalty for getting caught driving without license?
Pidana kurungan paling lama 4 bulan atau denda paling banyak Rp 1.000.000?[fn::https://id.wikipedia.org/wiki/Surat_Izin_Mengemudi#Ketentuan_Pidana]

Majority of Indonesian truck drivers do not have driving license.
** Find a market
** Get a patch of land, 100 square meters or bigger
Should we just buy a land somewhere in Bogor or borrow a land somewhere in Bandung, or should we start with Jakarta backyard pots first?

Considerations, from the most important:
- Distance to market.
- Soil health. If there are grass and trees on it, then it should be healthy enough.
- Air pollution from forest fires and factories?
- River pollution from upstream.
- Disasters such as earthquake, landslide, flood.
- Diseases, animals, and parasites such as mosquitos.
*** On permaculture, homesteading, and finding a place to live
On permaculture and homesteading, especially in Indonesia

What is the easiest place?

My initial guess is next to a river, preferably upstream, because it is less likely to be polluted.

Water, nutrient, transport, electricity, infrastructure, internet, access, roads, civilization, hospitals, characters/beliefs of local people.

Government zone plan?
Bureaucracy?

(Jakarta...)

Kalimantan risk: Pembakaran hutan untuk lahan kelapa sawit.
<2019-08-19> Yudi said it was not too severe in Sanggau.

Masker rekomendasi Yudi https://www.tokopedia.com/untungteknik/o-po-masker-n95-1502-particulate-respirator-masker-kertas-with-valve/review

Rekomendasi Mufid:
Tanah di Bogor beberapa hektar cuma beberapa ratus juta rupiah.

Jakarta is sinking, polluted, and jammed, and
the news does not give me the impression that the 2019 Jakarta governor Anies is competent enough to solve these problems.

I doubt Jakarta government, but I doubt government outside Jakarta even more.
*** Finding a place to live
- Internet access that is affordable and not shitty

Permaculture, sustainability, ecological engineering, personal

Natural-habitat database?[fn::https://www.researchgate.net/post/Is_there_a_database_describing_the_various_habitat_characteristics_of_plant_species_worldwide]

Ecological engineering curriculum?

Plant doctor = plant scientist = plant pathologist

Botanist?
*** Deprecated
(This section is impractical and deprecated.
To simplify my search, I have constrained the target location to be at most 100 km from Jakarta.)
**** Where should we live?
Where is the best place to live?
Where on Earth should we live?

According to "The Economist"[fn::"Where is the world's most liveable city?", The Economist https://www.youtube.com/watch?v=ylR21fezN7E],
in 2018, Vienna is the most livable city, and it was Melbourne.

The United States of America seems to be the most powerful country on Earth.
I thought America was liberal; it turns out to be socialist.
Also, America has too much frivolous lawsuits[fn::https://www.legalzoom.com/articles/top-ten-frivolous-lawsuits].

How do we measure, perhaps indirectly, the /rationality/ a country?
That is, how do we measure how likely its people think critically?
How do we know which people use their brains?

I am thinking about metrics that may correlate with the quality of life in a country.
Among those metrics are immigration hardness,
passport strength[fn::https://www.passportindex.org/byRank.php],
tax rate[fn::https://en.wikipedia.org/wiki/List_of_countries_by_tax_rates],
press freedom index[fn::https://en.wikipedia.org/wiki/Press_Freedom_Index] (journalist imprisonment rate?),
human freedom index (HFI)[fn::https://www.cato.org/human-freedom-index-new],
most liberal country ranking[fn::https://www.worldatlas.com/articles/the-10-most-liberal-countries-of-the-world.html].
I think tax rate correlates with government size, and smaller government is better,
but some high-tax-rate countries have good HFI.

New Zealand sounds promising.
It has good HFI.

It seems that America has never killed or imprisoned journalists for criticizing people in power.

I think that the country that is the hardest to immigrate into[fn::https://www.investopedia.com/articles/personal-finance/121114/5-hardest-countries-getting-citizenship.asp] may be the best country on Earth.
But I think those developed countries have their own problems.

A strong passport means that other countries believe that the issuer will not export bad people.

I think the solution to the refugee problem is not to take refugees, but to /fix the source country/,
which must have become so messy that millions of people would rather die at sea than stay at home.

Switzerland?[fn::https://getpocket.com/explore/item/living-in-switzerland-ruined-me-for-america-and-its-lousy-work-culture]

Making a house[fn::https://en.wikipedia.org/wiki/List_of_human_habitation_forms]
**** Which places on Earth should we avoid?
Big groups to avoid:
- natural disasters: hurricanes, earthquakes, heat wave, flood, etc.
- social disasters: dictatorship, Marxism, religious extremism, intolerance, unreliable law,
  questionable worldview, questionable government, police atrocity, oppression of the weak, etc.

It's wise to avoid places with known disaster risks:
- US risky areas:
  - Florida, North Carolina: hurricanes
  - San Francisco, California: earthquakes and soil liquefaction
  - Tornado alley (where?)
  - North Carolina: missing nuclear bomb[fn::Vsauce: "Cruel Bombs" https://www.youtube.com/watch?v=SHZAaGidUbg]
- Japan, South Korea, Philippines: 2018 super typhoon Jebi and Mangkhut
- areas in the Ring of Fire[fn::https://en.wikipedia.org/wiki/Ring_of_Fire]
  [fn::South East Asia earthquake map https://cilisos.my/what-protects-malaysia-from-all-these-earthquakes-that-is-happening-in-indonesia/]

USA: foods full of additives, broken expensive higher education, broken expensive healthcare,
intolerance (especially political), entitlement mentality, Internet surveillance.
 [fn::https://www.quora.com/Is-USA-a-good-place-to-live-in]
 [fn::https://www.vice.com/en_us/article/ev4aww/american-ex-pats-explain-why-they-quit-america]
Mass shooting.
Bad work-life balance.
Regulatory capture.
Despite all that, USA is still much better than the other countries in the not-to-live list.
It casts doubt upon me: I am thinking about moving to America, but the Americans themselves are thinking about leaving America.
The grass is always greener on the other side of the fence?

Australia: heat wave[fn::https://www.theguardian.com/australia-news/2018/dec/24/christmas-day-heatwave-weather-records-temperatures-forecast-heat-wave-australia-sydney-melbourne-adelaide].

French: police atrocity[fn::https://en.wikipedia.org/wiki/Rémi_Fraisse].

Indonesia: police atrocity, miscarriage of justice, justices lacking integrity, JIS case, unreliable law,
 [fn::Perkap hanya kertas. Fix the system. Jangan bikin lomba menyelesaikan kasus. https://tirto.id/polisi-kami-akui-ada-kasus-salah-tangkap-cKi8]
 [fn::Enak sekali jadi hakim: salah tidak perlu tanggung jawab? https://www.hukumonline.com/berita/baca/hol5949/kesalahan-hakim-tanggung-jawab-siapa],
unnecessary regulation and bureaucracy, Internet censorship.
Imprisonment of drug users (who are victims and should be helped, not imprisoned).
Muslim extremists.
Bali: annual Nyepi days.
Palu: earthquake and liquefaction.
Aceh: tsunami, sharia, subductions, and Muslim extremists.
Selat Sunda: Krakatau, subductions.

Philippines: Muslim extremists, 2019 church bombing
 [fn::https://www.theguardian.com/world/2019/jan/27/two-bombs-explode-at-philippines-cathedral-killing-people]
 [fn::https://www.aljazeera.com/news/2019/01/southern-philippines-mosque-hit-deadly-grenade-attack-190130004852265.html]

Thailand: toxic smog[fn::https://www.theguardian.com/world/2019/jan/30/toxic-smog-forces-bangkok-to-close-hundreds-of-schools]

China: air pollution (but I heard it was improving)

North Korea: for obvious reasons; also Otto Warmbier case

Latin America: interference from the USA?

France, inequality, gilets jaunes

Egypt: Muslim extremists, strange laws, imprisoning Laura Plummer for bringing painkillers to her ailing boyfriend.

Brazil: 2019 dam collapse, anti-LGBT, and now Trumpian president in 2019.

India: bombing, terrorism[fn::https://en.wikipedia.org/wiki/List_of_terrorist_incidents_in_India],
Muslim extremists, Hindu extremists, castes (social segregation),
stray cattle problems[fn::https://www.odditycentral.com/animals/indias-sacred-strays-millions-of-urban-cows-living-alongside-humans.html],
superbugs,
heat wave,
extreme poverty,
2019 Aadhaar (national identity database) data leak[fn::https://techcrunch.com/2019/01/31/aadhaar-data-leak/] (not the first time),
2019 SBI data leak[fn::https://techcrunch.com/2019/01/30/state-bank-india-data-leak/],
and God knows what else.

Pakistan: Muslim extremists, Asia Bibi case.

Arabic countries, Muslim countries, and refugee origin countries.
UAE: wrongful conviction and imprisonment of Matthew Hedges[fn::https://www.theguardian.com/world/2018/nov/21/british-academic-matthew-hedges-accused-of-spying-jailed-for-life-in-uae][fn::https://www.theguardian.com/world/2018/nov/26/matthew-hedges-jailed-british-academic-pardoned-by-uae].
Saudi Arabia: dictatorship,
arbitrary detention[fn::https://en.wikipedia.org/wiki/2017_Saudi_Arabian_purge][fn::https://www.hrw.org/news/2018/05/06/saudi-arabia-thousands-held-arbitrarily],
assassination of Jamal Khashoggi[fn::https://en.wikipedia.org/wiki/Assassination_of_Jamal_Khashoggi],
Yemen bombings[fn::https://en.wikipedia.org/wiki/Saudi_Arabian-led_intervention_in_Yemen].
Iraq and Iran: the war between them.
Afghanistan: The Afghan refugees would rather flee Afghanistan.
Syrian: The Syrian refugees would rather flee Syria.
ISIS/ISIL, Muslim extremists.

Israel: surrounded by neighboring countries who want to kill you.

China, surveillance, Big Brother government, dictatorships.
But I do agree with some of their policies and stances; I'm torn.

What can you do if you are an average person born who is born in a shitty place but wants to move to a better place?
You don't have "a post-secondary education, a job offer in Canada, close relatives in the northern nation,
a business to bring north or 'a high net worth or significant financial resources'"[fn::https://www.usatoday.com/story/tech/news/2016/11/10/100000-americans-crashed-canadian-immigration-site/93587034/].
You are not an oppressed minority either.
* Level 3: Botanist, permaculturist, ecological engineer
Close the nutrient cycle.
** How does a plant know that it is the time to fruit (to reproduce)?
Abundance of properly balanced nutrition.
Reproduction is costly.
In principle, a plant begins fruiting if the circumstances at the /maturation/ of the fruit maximize the chance of survival of the offspring.
 [fn::https://www.wonderopolis.org/wonder/how-do-plants-know-when-to-flower]
* Level 4: People builder who lifts people out of poverty
We have to fix the mindset.

Seek wealth, not money.

What is wealth?
I define it as the sum of satisfied wants.

We must distinguish between /wealthy/ and /moneyful/.
An example of a moneyful-but-poor person is one who has a lot of money but hardly uses it.
An example of a moneyless-but-wealthy person a farmer without money but can eat whatever he wants to, anytime he wants to, from his fertile productive land.

Nature pays everyone who works.
Nature pays workers directly with wealth, not indirectly with money.

I dream that everyone sufficiently feeds themself from their own patch of land.
Bill Gates wanted a personal computer at every home;
I want a food garden at every home, and I want every neighborhood to close their nutrient cycle.
** <2019-08-24> Fellow people tired of modern life and its associated rat race
https://www.reddit.com/r/TrueOffMyChest/comments/b0rgq4/modern_life_is_complete_garbage/

I'm tired as well.

Nature has given us everything we need to survive.
There is no reason to work beyond the minimum necessary for survival.

People can have a nice job and /still/ hate it.
* Level 5: Mining, smelting, manufacturing, toolmaking
** Geology
Why only some mountains erupt?
Why are some mountains active and some inactive?

How do we predict the locations of chemical elements?
Which chemical elements are found where?

What?
https://en.wikipedia.org/wiki/Geologic_map
* Level 50: Fuel?
* Level 60: Carmaking
* Level 70: Computer-making
* Level 80: Weapon and defense
We can outsource this to the government of Indonesia.
We can depend on the government of Indonesia to protect us.
In exchange, we create real economic growth.
* Level 90: Establish a society
* Level 100: Aquanauts? Seafaring? Deep ocean diving?
* Level 200: Spacefaring?
