#+TITLE: Political power decentralization
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /social.html
#+OPTIONS: ^:nil toc:nil
Title was "Social research group".
* Goals
To educate people about political power.

To prescribe how humanity should proceed in order to survive the 21st century.

If power corrupts, and corruption is undesirable,
then the only way to prevent corruption is to prevent someone from having too much power.
* What is wrong with 21st-century societies?
** Focusing on growth instead of sustainability
Economic growth is not a worthy goal.
** Is financial investing moral?
Financial investing is getting more money without doing anything.
It is immoral, because it means indirectly stealing a little from everyone else.
We should not glorify rentiers, freeloaders, and thiefs.

But does that mean that passive income, rent, interest, tax, pension fund, and royalty are immoral?

Both inflation and deflation are immoral,
because it betrays everyone who trusts the currency.
Inflation hurts buyers.
Deflation hurts sellers.

But inflation prevents currency hoarding.
** Taxation + capitalism = stealing from the thieves
Taxing the capitalists is stealing from the thieves.
Both taxation and capitalism are immoral.
Their combination is unnecessarily convoluted.
The correct solution is to not have any theft in the first place.

The solution is not taxing the rich.
The solution is to remove the law that enables the creation of power-centralizing entities.
People must unite but they must not form a formal union.

Examples of power-centralizing entities are
formal institutions, formal organizations, companies, formal labor unions, legal fictions, virtual people.
** Why do we still care about constitutions?
Why should people in the 21st century agree with people in the 18th century?
Why should we agree with people born 300 years ago?
We don't even agree with our parents born 30 years ago!

What is a constitution?

USSR 1936 under Stalin[fn::https://en.wikipedia.org/wiki/1936_Soviet_Constitution]
had the most beautiful-sounding constitution, but it was only a lip service;
the practice was nowhere near that.
The most important thing a constitution must have is /limitation and decentralization/ of power.
** Inequality is a symptom, not the disease
Life is never fair.
Nobody chooses to be born.

Freedom is more desirable than equality.
We cannot have both total freedom and total equality.

Inequality is a symptom, not the disease.
All these people calling for equality are misguided.
They should be calling for freedom and power distribution.

The disease is power centralization.
** Competition is wasteful; engineers should be a hive mind and not enclaves
Global engineering hive mind is more efficient for humanity than engineering enclaves.

Engineers in competing companies duplicate each other's work all the time.

This is a massive planet-scale waste of human mind power.

Companies and organizations must be abolished and replaced with
global anarcho-syndicalistic hive mind in which no one person has too much power.
* What are some example problems due to power centralization?
** What are humankind-destroying businesses that depend on addicting people?
Businesses that profit by making people addicted:
- Juul, vaping:
  Juul helps people start smoking more than it helps people stop smoking?[fn::https://techcrunch.com/2018/12/22/juul-me-twice-shame-on-you/]
- cigarette, tobacco
- gaming, advertising, drugs
- porn? (but we like porn? Is my porn your cigarette?)
** Abuses of power; reasons for anarchism (or even anti-statism)?
** Custom officers will seize your devices and breach your privacy.
Don't bring your devices in international travel
https://www.theguardian.com/world/2018/aug/25/sydney-airport-seizure-of-phone-and-laptop-alarming-say-privacy-groups
** You MUST have at least one camera in your car streaming the data to a remote safe location. Cops will trap you.
- https://www.youtube.com/watch?v=UpT-SAunuLk
- Busted! How to Handle the Police Until You Get a Lawyer - by Mary Griego https://www.youtube.com/watch?v=bmtIizXdh88
  - Ordering vs asking.
- We need to make sure that misbehaving cops are punished.
- 5 Rules for Recording Police: Steve Silverman of FlexYourRights.org https://www.youtube.com/watch?v=BHpQtvIxBJ4
** Class treason? Class traitors?
- https://en.wikipedia.org/wiki/Class_traitor
- police?
- human resources?
- every computer programmer working for government
** USA, Australia, imperialism, recent (19th-20th century) imperialism
Too bad there is no one fighting for the USA-oppressed island nations.

USA annexed (militarily occupied) Hawai'i from the locals.
https://www.youtube.com/watch?v=MfAiB2ZoRhM

USA annexed Puerto Rico from Spain who annexed it from the locals.
https://www.youtube.com/watch?v=g-GYqakwHdg

USA is not the only imperialist country though.

Australian imperialism

Honest Government Ad | Visit Timor-Leste! https://www.youtube.com/watch?time_continue=4&v=xqegTsi6SiE
- from https://www.reddit.com/r/indonesia/comments/9sbnyk/honest_government_ad_visit_timorleste/
** Political system is broken.
*** How Republicans and Democrats are different, and how they are the same.
**** How they differ
- Republicans scare you with dangers that don't exist, such as migrant invasions.
- Democrats excite you with benefits that don't exist, such as ever-increasing pensions.
**** How they are the same
- Both are liars.
- Both don't keep their promises.
- Both make the country worse off.

It's amazing that the USA can become the strongest nation in the world, despite the USA's dysfunctional political system.

Imagine what the USA could have been with a functional political system.
**** Why they behave that way: because they think short-term. Why do they think short-term? Because there are term limits.
**** Lying politicians should be sentenced to death. At least we should immediately vote them out of office.
**** The same thing happens in Indonesia. All parties are the same. The only difference is their religious stance.
***** TODO link that tirto.id article about party political spectrum
*** As long as we have political term limits, we will have popular-but-bad programs.
**** Politicians should not be time-limited. People should both elect politicans into office and elect politicians /out/ of office.
If politicians are time-limited, they will pander to the people and prioritize short-term gains.
**** We can vote people into office. Why can't we vote them /out/ of office?
** Intel Management Engine
CPU backdoors are fundamental breach of trust.

It is unacceptable that one company can make most computers on Earth insecure.
* Why is power centralization the root cause of all woes of society?
The problem is not capitalism vs Stalinism.
The problem is /centralization of power/.
Both USA and USSR are corrupt.
USA gives too much power to companies.
USSR gives too much power to Stalin.

Both a state and a company are legal fictions for centralizing powers.

Stanford prison experiment[fn::https://en.wikipedia.org/wiki/Stanford_prison_experiment]
shows that /power corrupts/[fn::https://www.smithsonianmag.com/science-nature/why-power-corrupts-37165345/] good people.

Dacher Keltner has done some research on the effects of power on nice people.
Power "has a disinhibiting effect regarding the social consequences of exercising it"[fn::https://en.wikipedia.org/wiki/Dacher_Keltner#Theory_of_Power].

Power centralization is a logical consequence of our systems.
It means that the systems are working as designed.

Our systems have a tendency to centralize power.
Property.
Capitalism.
These tend to centralize power.
** What is a state?
A state is essentially a massive principal-agent problem[fn::https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem] involving millions of people.

The people give up their monopoly of violence to the state, and the state promises to do good to the people.
The problem is principal-agent problem.
The state cannot be trusted.
** How can workers empower themselves?
Labor laws and unions are the wrong solution.
The correct solution is that the workers must unite and think for themselves, but they must not form a union.
Once a union is formed (as a legal entity), it has a life of its own, and the principal-agent problem begins.
There is always room and incentive for union bosses to collude with the original enemy, enrich themselves, and betray the original electors.
The anarcho-syndicalists get this mostly right (what they get wrong is "revolution").[fn::https://en.wikipedia.org/wiki/Opposition_to_trade_unions#Left_critiques_of_trade_unionism][fn::https://en.wikipedia.org/wiki/File:Anti-union_ASF_flyer.jpg]
Direct action.
** What benefits us is trade, not capitalism
Capitalism contains free trade.
Free trade benefits everybody, but the for-profit private ownership of property doesn't always benefit everybody.
By free trade, we mean voluntary exchanges/transactions.

It is possible to have free trade without capitalism.
Anarchy is an example.

The issue is centralization of power.
Companies centralize economic power.
States centralize political power.
Institutions/organizations centralize power.
People must unite, but they must not form unions.
Principal-agent problem.
Unions have lives of their own.
** Capitalism has nothing to do with free trade?
Capitalism is simply the private ownership of the means of production.

Capitalism places capital above labor.
Nature places labor above capital:
Someone somewhere eventually has to /actually do/ something in order to produce something.
/Labor is more important than capital./
Capitalism goes against nature?
Capital without labor will not produce anything.
Labor without capital is merely inefficiently allocated.

Capitalism (market?) is a voting about what we should use labor for?
* How do we prevent or preclude power centralization?
The "An Anarchist FAQ" series[fn::https://theanarchistlibrary.org/category/author/the-anarchist-faq-editorial-collective] is too long.
** Unite but don't unionize?
I asked[fn::https://twitter.com/ErikDominikus/status/1093175961867169793]:
Does collective bargaining require involving the government?
Why not direct action?
Can't people unite without unionizing, and gain power without principal-agent problem?

The slogan: /unite but don't unionize/; unity but not union.

What is the difference: unite, unify, unionize?
** Fixing the political system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-political-system
   :END:

- Restrict the form of all political campaigns to text containing the list of things the candidate wants to do.

  - Avoid pandering and toxic campaigns.

- Replace parliaments with sortition (randomly choosing people)?

  - TED: "What if we replaced politicians with randomly selected people? | Brett Hennig", [[https://www.youtube.com/watch?v=cUee1I69nFs][youtube]]
  - [[https://en.wikipedia.org/wiki/Sortition][WP:Sortition]]
  - Will sortition work in a homogeneous country?
    Won't it just promote groupthink?
  - How does sortition affect the minority?
    How should the population be sampled?
    Stratified sampling?

** Fixing the justice system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-justice-system
   :END:

- Change the justice system from retributive justice to restorative justice for the non-violent criminals.

  - Instead of locking up prisoners, let them repair the harm they did, and help them reintegrate into society.
  - Millions of people are being incarcerated.
    Their ability is being wasted.
    They are deprived of future.
    They will have difficulties reintegrating into society.
    Stigmatized.
    Like the homeless.
    This stigma makes it impossible for them to get financial stability and get out of the vicious circle of crime.

    - Also, prison initiation rituals are terrible.

  - There are two kinds of criminals:

    - /Perforce criminals/ commit crime to defend themselves from immediate bodily harm that threatens their existence.
      Examples are hungry moneyless people who steal food, and cornered people who kill.
      The solution is restorative justice, and giving work to the criminal for financial stability, helping them reintegrate into society.

      - If the threat is removed, perforce criminals no longer commit crime.

    - /Non-perforce criminals/ commit crime for anything else.
      Examples are psychopaths (people with physical inability to weigh bad consequences because their brains are wired differently).
      The solution is unbreeding: modify them by gene therapy or psychological therapy or whatever technology, or kill them if they can't change,
      but only after we have proven that they can't change.

      - See also [[https://www.theatlantic.com/magazine/archive/2017/06/when-your-child-is-a-psychopath/524502/][theatlantic.com: When your child is a psychopath]].

  - Prisons should not exist.
    There should exist only two kinds of punishment:

    - Forced labor, for perforce criminals, to repair the harm they did.
      The state must also help them reintegrate into society.
    - Death penalty, for non-perforce criminals.

  - In any case, nobody should be locked up for so long.
    Locking up people wastes resource.

** Should we limit inheritance?
   :PROPERTIES:
   :CUSTOM_ID: should-we-limit-inheritance
   :END:

https://taxfoundation.org/estate-and-inheritance-taxes-around-world/

Should we have any tax at all?

Should government funding be voluntary?

** A government is to maximize the well-being of its people
   :PROPERTIES:
   :CUSTOM_ID: a-government-is-to-maximize-the-well-being-of-its-people
   :END:

- A government is to:

  - do things that benefit many but do not benefit a few, such as building roads;
  - prevent things that benefit few but do not benefit many, such as committing crime.

- A government is to minimize negative [[https://en.wikipedia.org/wiki/Externality][externality]]
  and [[https://en.wikipedia.org/wiki/Rent-seeking][rent-seeking]].
- A government is to prevent the [[https://en.wikipedia.org/wiki/Tragedy_of_the_commons][tragedy of the commons]].

** Ungrouped content
   :PROPERTIES:
   :CUSTOM_ID: ungrouped-content
   :END:

A modern government is designed to minimize the damage if a bad person rises to the top,
not to maximize the benefit if a good person rises to the top.
That is why a republic has checks and balances.
The most efficient government is a benevolent competent dictator,
but does such person exist?

The government is a monopoly, and it should seek profit for its stakeholders: all its people.
Government official corruption, similar to corporate management corruption,
is a [[https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem][principal-agent problem]].
Everything that solves the principal-agent problem also solves corruption.

** Deciding what governments should do
   :PROPERTIES:
   :CUSTOM_ID: deciding-what-governments-should-do
   :END:

Use this quadrant:

- Axis 1: Does it benefit many people?
- Axis 2: Does it benefit a few people?

Things that benefit many and benefit few are best left to the private sector
with as little regulation as needed to keep the market healthy.

Things that benefit many but disadvantage few should be done by the public sector,
because the private sector will not do them because they don't get money doing that.
Example: building road.

Things that disadvantage many but benefit few should be prevented by the government.
Example: rent-seeking (bribing, lobbying,
speculation of non-fungible goods such as land parcels and Internet domain names),
crime, terrorism.

Things that disadvantage many and disadvantage few should also be discouraged by the government.
Example: road rage, human stupidity.

** Tips from our ancestors
   :PROPERTIES:
   :CUSTOM_ID: tips-from-our-ancestors
   :END:

I do not always agree with Lenin, but I agree with this sentence of his:

#+BEGIN_QUOTE
  When it is not immediately apparent which political or social groups,
  forces or alignments advocate certain proposals, measures, etc.,
  one should always ask: "Who stands to gain?"

  Vladimir Ilyich Ulyanov a.k.a. Lenin (1870--1924)
  ([[https://www.marxists.org/archive/lenin/works/1913/apr/11.htm][source]])
#+END_QUOTE

That was 1913.
In 1976 that could be more simply put as [[https://en.wikipedia.org/wiki/Follow_the_money][follow the money]].

** Ramble
   :PROPERTIES:
   :CUSTOM_ID: ramble
   :END:

- A government should only do things that better its people.

  - How do we know if something will make people better off?

- Is Chinese government dominated by scientists and engineers?

  - https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers

- https://www.quora.com/What-would-a-government-designed-by-engineers-and-not-politicians-look-like?share=1

  - https://tomgrego.blogspot.com/2010/12/a-government-you-can-love.html
  - https://www.quora.com/Concretely-what-can-we-do-to-get-US-politics-working-What's-gone-wrong-and-why-are-things-worse-than-20-years-ago-How-could-US-politics-improve-in-10-years-What-short-term-tactics-could-advance-the-long-term-goal?share=1

- The public sector is inefficient, but the private sector might be too efficient (extracting too much profit? but how much profit is too much?)?
  Is there a mixture between the two?
  Regulated private sector?
- https://en.wikipedia.org/wiki/Monopoly_on_violence

  - https://en.wikipedia.org/wiki/Justification_for_the_state

- https://www.bbc.com/news/uk-politics-42570823
- https://www.quora.com/Are-there-any-countries-without-government
- If healthcare were affordable, would we still need insurance?
- We don't need insurance.
  We need affordable healthcare.
- http://time.com/4937691/americans-cheap-healthcare-instantly/
- https://www.bloomberg.com/news/articles/2018-05-15/doctors-who-hate-insurance-so-much-they-go-without-it-themselves
- https://www.quora.com/What-do-doctors-think-about-insurance-companies
- What makes healthcare so expensive?

  - Definitely not the general practitioners (non-specialist doctors).
    They charge the patient only about $20 per visit.
  - Hospitals?
  - Drugs?
  - Insurances?

- argument for government, the necessity of government

  - https://www.quora.com/Why-have-so-few-humans-realized-that-governments-are-unnecessary

- https://en.wikipedia.org/wiki/Night-watchman_state
- If taxes were voluntary, would people pay tax?
- https://en.wikipedia.org/wiki/Voluntary_taxation

** The world should have only one country, one government, one law.
   :PROPERTIES:
   :CUSTOM_ID: the-world-should-have-only-one-country-one-government-one-law.
   :END:

Having many countries causes legal loopholes.

If there is only one country, there will be no tax tricks, tax havens.

There would be no illegal immigrants.
Everyone would be a world citizen.

- https://www.quora.com/Why-cant-all-the-earth-countries-unite-to-make-a-single-federation
** Design the world order
*** Develop non-shitty FOSS distributed/P2P alternatives to most vital services
Works behind NAT?
How can A and B connect to each other if A is behind NAT gateway G1 and B is behind NAT gateway G2?

Google search: no replacement yet!
YaCy is not good enough.
Can we make it in Prolog?

Distribute the result of manual curation?
Bundle a curation tool with a browser?
Privacy issues?

Facebook: Mastodon?

YouTube: DTube, BitChute
https://www.ghacks.net/2018/03/02/dtube-is-more-than-a-youtube-alternative/

Heroku?

"An Open Source, Self-Hosted Heroku"
https://news.ycombinator.com/item?id=12703121
https://www.bitmatica.com/blog/an-open-source-self-hosted-heroku/
"Internals of OpenRuko PaaS, an open source Heroku clone implementation"
https://www.slideshare.net/rogerleite14/paa-s-26212382
https://github.com/dokku/dokku
https://github.com/openruko
https://flynn.io/
https://www.quora.com/What-are-some-open-source-Heroku-alternatives

https://www.quora.com/What-are-some-open-source-Heroku-alternatives
*** Develop power-distributing technologies
*** Write a user-first browser in Prolog
**** 1h: Specify desired features and differences from mainstream browsers
Principle: the user should have maximum control.

It is not only a browser.
It is a tool for controlling your web experience.

- The browser is distributed/P2P.
- The browser comes with a search engine that searches your public history or your peers' public history, and distribute indexes to peers.
- Block all ads because advertising depends on making people addicted.
- Block all popups, no exception, no clickjacking.
- Block all "soft-popups" (displays).
- Run user script for certain websites.
- Block all cookies by default.
- Don't load JavaScript by default.
- Don't load images by default.
- Apply default CSS. Don't load CSS by default.
- Enable user-agent spoofing.
- For advanced users. No GUI to configure. Write Prolog code to configure the browser.
- Default to HTTPS when protocol is not given.
- No download manager. Tell the user to use wget, curl, or whatever.
- Like emacs but:
  - browser instead of text editor
  - prolog instead of emacs lisp
- Browser must limit memory usage.
  See entity explosion problem.
- Browser should refuse to load HTML documents larger than 1 MB.
- User can easily change user agent. WhatsApp wrong browser detection.
- combine with caching, peer-to-peer caching, distributed (and social?) searching and ranking and sharing, but what about privacy and the people who try to game the system?
- Don't remember tabs when closed.
Limit open tabs to 10. Discourage context-switching. I'm a pathological tab hoarder. Always open a configurable set of tabs on start. If you need to open more tabs, then open a google docs or a note-taking app instead.

- Write a fast, private, and secure web browser in Prolog.
  - Features:
    - Selectively enable JavaScript from some websites with Prolog rules.
    - Disable clipboard hook.
**** 1h: Skim existing browsers
Is this legit?
https://vivaldi.com

https://en.wikipedia.org/wiki/Comparison_of_web_browsers

https://www.quora.com/How-should-a-programmer-think-about-solving-problems-in-Prolog

Entity explosion problem:
#+BEGIN_EXAMPLE
<!ENTITY a "&a;">
<!ENTITY a <16 times a>
<!ENTITY b "&a;" <16 times>
<!ENTITY c "&b;" <16 times>
etc.
after 10 times we have 2^40 = 1 TB!
#+END_EXAMPLE

Example rendering rules: nag.html:
if website is pinterest then remove DOM element blah blah after load.

Popular open-source browsers are highly scrutinized.

not too related:
"prolog on the browser"
https://github.com/SWI-Prolog/roadmap/issues/43
**** Gui, logical/relational reactive programming, a layer on top of plgi (Prolog Gtk bindings).

exists W: window(W)
exists A: textbox(A)
value(A, yes) :- is_down(B), !.
value(A, no).
children(W,Cs) :- current_document(D), document_controls(D,Cs).
"The value of the textbox is yes whenever the button is down."
current_document/1 is a dynamic predicate.

name_widget(main,W) :- window(W), widget_width_height(W,640,480).

window(W) is true iff W is a window representation.
name_widget(N,W) is true iff N refers to widget representation W.


Example of some queries that we want a GUI knowledge base to answer:
- What is the width and height of the "main" window?
- What happens when button b1 is clicked?
- What has to be done to make this text box shows "yes"?

Example time-dependent facts that we want to state:
- After button b1 is pressed, then checkbox c1 is checked.
- If user clicks on a link, then navigate to the target of that link.
- latching?



gui(Root)


Layout algorithm
layout_one_line(Font, String, MaxWidth, Line, RemString)



Temporal logic for GUI
is_up(B) -> green(W)
is_down(B) -> red(W)


:- dynamic object_time_property_value/4
At every event, increment current_time

binding(W1, K1, V1, W2, K2, V2) :- ...


widget_value :- current_time, widget_version_value
force(widget_property_value(W,V)) :-
retractall(wtpv :- T >= Curtim, _), asserta((time_widget_value(T,W,V) :- T >= Curtim, !)).

Problem: slow gui update; recheck all widgets unnecessarily

http://www.swi-prolog.org/pldoc/man?predicate=initialization/2

array_array_concat(A, B, C) :-
    array_length(A, NA), ...
    NC is NA + NB,
   subarray_subarray_match(A, 0-NA, C, 0-NA),
    subarray_subarray_match(B, 0-NB, C, NA-NC).

Replace equal with match

*** Liberalism is the only way people can live together.
The only way to live together is to let people do everything they want as long as they don't harm other people.

Why do we care about consent?
Science advances faster without consent?

Why does the silver rule work?
The silver rule is "don't do unto others what you don't want to be done unto yourself".
*** Do we need government? Why do we need government?
https://en.wikipedia.org/wiki/Justification_for_the_state
"There is no single, universally accepted justification of the state."

*** Liberalism vs libertarianism
https://politics.stackexchange.com/questions/353/what-is-the-difference-between-liberalism-and-libertarianism

Dan (Steve's friend)'s question: "if I want to opt out of government services, should I be able to?"
"Even if his decision to opt out was poor – if he’d be better off by using the services – I couldn’t justify /forcing/ him to pay for something he didn’t want"
http://steve-patterson.com/conservative-anarchist/
*** The problem with libertarianism: the libertarian children problem: why do we prevent children from harming themselves?
Thesis: We should let someone do whatever he/she wants to do as long as he/she doesn't harm others, even if it makes him/her personally worse off.

Now the problem.

Why shouldn't parents let children do what children want as long as children don't harm others?
Why do we let an adult smoke cigarette, but we don't let a child smoke cigarette?
Why should we prevent children from touching wall sockets, drinking bleaches, and doing other dangerous things?
Why should we prevent children from harming themselves?
Libertarians are forced to conclude that children aren't people.
This conclusion is not inherently bad.
We can also define peopleness as a continuum (children are 50% people, for example).

Why should we vaccinate children?

https://www.quora.com/Libertarianism-When-do-children-own-themselves-if-at-all

However, an antinatalist libertarian wouldn't have this problem, because having children would be immoral in the first place.

https://www.reddit.com/r/antinatalism/comments/6356ym/shouldnt_libertarians_be_anti_natalist/

Our language implies that children aren't people.
- We use the pronoun "it" to refer to a child.
- Casualty count (death toll) is categorized into "men", "women", and "children".
- We sometimes use the phrase "men, women, and children".

The problem is in the language.
"Person" is not a binary concept; it's a continuum.
A child may be 20% personlike.
The more personlike something is, the more we should treat it as a person.
*** Some problems with free market
- What prevent environment destruction?
  System for internalizing the negative externalities back into the companies, such as carbon credit.
- What prevents private military company from being corrupt or being bought by someone with lots of money but nefarious intents?

*** Maximize individual freedom while minimizing harm to others

Every man, when left alone, does something he does best.
One person plants trees.
Another person murders people.
It follows that unlimited freedom is bad;
murderers should not be free to murder.

How much individual freedom is desirable?

*** Presumption of innocence

- https://en.wikipedia.org/wiki/Presumption_of_innocence
- https://en.wikipedia.org/wiki/Blackstone%27s_formulation

*** Sex and gender
Stop political correctness
https://www.yegor256.com/2018/11/13/bigotry.html

Political correctness kills

Women Can Now Join The SAS : UK Promptly Collapses
https://www.youtube.com/watch?v=piZRqOCOwP4

You can get as angry as you want, but it will not change the fact that sexual differences exist.

https://en.wikipedia.org/wiki/Gender-equality_paradox

John Stossel - Gender Confusion
https://www.youtube.com/watch?v=pTEPr4n_skI

On average, do men drive cars faster than women do?
**** What is a male? What is a female? What really makes a male a male and a female a female?
Is it the sex organ?
Is it the hormones?
It is the appearance?

Male and female are objective sexual classifications.
Man and woman are subjective gender classifications.
If sex and gender are orthogonal, then what is a "male woman"!?

- https://en.wikipedia.org/wiki/Trans_woman
  - A trans woman "is a woman who was assigned male at birth".
    The keywords are /assigned/ and /at birth/.

People in Stone Age may assume that someone's sex is determined at birth and doesn't change.
Back then, there were no sex reassignment surgeries.

Social-culture-language aspects:
Why is "girly man" an insult?

*** How do we scale democracy?
**** How do we make elections cheap, easy, trustworthy (independently verifiable), and scalable?
Paper ballots can be independently verified.
Machines can't.

Trustworthiness requires that the system can be independently verified (by a third party, by a non-government organization, by local people, by anyone who cares).

How can we ensure verifiability while maintaining secrecy?

Every citizen has a private key?

Rachel Tobac:
"At @defcon hacking conference and just learned how easy it is to physically gain admin access on a voting machine that is used in 18 states.
Requires no tools and takes under 2 minutes.
I’m concerned for our upcoming elections."
https://twitter.com/RachelTobac/status/1028437783050776576

https://arstechnica.com/information-technology/2018/09/e-voting-researchers-warn-of-hack-that-could-flip-the-electoral-college/

*** My fundamental assumptions when designing a social system
- Everyone wants to survive.
- Good people (people who enjoy helping others) exist.
- Evil people (people who enjoy harming others) exist.
- There are people who don't care about others.
- People do what they do best when left alone. Inventors gonna invent. Murderers gonna kill. Rapists gonna rape.

But privatization has its dangers too.
BP's strings of accidents after its privatization.

Basic negotiation theory: more need means lower bargaining power.
Buyers fare better if sellers compete.
Sellers fare better if buyers compete.

John Stossel - Privatize Everything (2013)
https://www.youtube.com/watch?v=toYoXf7EHwc

John Stossel - The Parasite Economy
https://www.youtube.com/watch?v=f2vt8e5RjQ0

#+BEGIN_QUOTE
While in government hands, British Petroleum paid too little attention to profitability,
constrained by its need to please elected officials who often cared more about keeping energy cheap and employment high.
But in private hands, it may have cared about profits far too much, at the expense of other objectives.
“BP veered from being a company that made sure nothing blew up to one focusing on cost-cutting at all costs,” Professor Fisman said.
https://www.nytimes.com/2013/01/16/business/when-privatization-works-and-why-it-doesnt-always.html
#+END_QUOTE
*** Industries whose profit is proportional to the destruction of the human race
- advertising, drugs, gaming, every business that profits from making humans addicted
- finance, investing, land speculation, and every business that does not create value

The advertising industry and the game industry are evil because they addict people in order to profit.

The advertising business model also causes recent extremisms.
http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html
*** How do we create an economy with zero rent?
*** Ethics, morality, politics, fairness?
Ethics vs morality: what is the difference?

ethical vs moral

unethical vs immoral

amoral vs immoral

fair vs just; fairness vs justice

"Fair" means "beautiful", not "just".
https://en.wiktionary.org/wiki/fair

Fairness is absence of resentment.

We can't fairly divide one indivisible thing for two people who want it.

Resentment is "bitter indignation at having been treated unfairly".
https://en.oxforddictionaries.com/definition/resentment

How does perception of unfairness arise?

Fairness does not exist objectively.

- Suppose that we have a running contest, and you beat me.
  How do I know that you beat me /fairly/?
  - Good genetics is an advantage, but is it a fair advantage?
  - If we can't control it, can it be unfair?
  - Is it fair for children to be born in families with different socioeconomic status?
  - If equality of outcome is absurd, then what is fairness?
  - Is equality of opportunity fair?
    - Opportunity to do what?
      Opportunity to become what?
    - Equality of /all/ opportunity?
      - Opportunity to be boss/capitalist/rich?
** The economic system
*** What economic system is desirable?
Characteristics:
- Distributed.
  Cannot centralize power.
  Cannot be controlled by government.
- Cooperative.
  Competition is a massive waste of human labor.
  Competitors reinvent each other's wheels all the time.
  The solution to competition is not competition laws.
  The solution is cooperation.
- Productive instead of consumptive.
- Antifragile (Taleb).

Is it possible to create an economic system that does not incentivize cheating?

What is the relationship between liberalism, competition, and cooperation?

Economic that is not focused on consumption?

Economic growth usually means consumption growth.

The easiest way to increase GDP is to increase consumption, environment be damned.

Why would we produce anything that nobody will consume?
*** What?
Deposits should not be guaranteed.
Banks should not lend.
Banks can take fees.
The job of banks is to clear transactions.
Banks exist so that people can transact without physically bringing large amount of cash to the place of transaction.
Banks should strive to minimize transaction cost.
The job of banks is not to lend.
That is the job of credit unions.
Banks should not double as creditors.

What is a bank, in anarchy?
*** Abolish corporations?
Limiting liability creates moral hazard.
But what is the alternative?

Corporation is a legal fiction.

Corporation (and insurance) enables people to act with impunity.

People would be more ethical if they have more skin in the game.

Before we abolish corporations, we must abolish frivolous lawsuits:
- "I'm not a fan of corporations, but the amount of frivolous lawsuits in the us make it desirable."
  https://www.reddit.com/r/CapitalismVSocialism/comments/46ljlf/capitalism_without_corporations/
** What is the ideal society?
*** Principles?
The best thing for a person to do is what he/she /voluntarily/ does?

But:
- Most people don't know what they want?
- Most people don't think for themselves?
- Do most people even think?
*** Institutions?
What is an institution?
Government bodies?
Governing bodies?

Do we need institutions?

Why do we lose trust in institutions?

Institutions enable people to hide.
Institutions enable people to abuse power without being held responsible.
Institutions deflect blame from people to an abstract entity.
Institutions separate the powerful from the coerced.
People should be responsible.
Instutitions cannot be responsible.

Bureaucrats cannot see reality from their desks alone.
*** What seems to be the most ideal society so far?
The most ideal society so far seems to be John Rawls's ideal society (based on his theory of social justice and veil of ignorance)
 [fn::https://en.wikipedia.org/wiki/A_Theory_of_Justice].
What are the problems?

Other people's ideas
https://www.quora.com/What-is-an-ideal-society-like

Practical utopia book?

Protopia is "incremental progress in steps toward /improvement/".
https://aeon.co/ideas/utopia-is-a-dangerous-ideal-we-should-aim-for-protopia

Every man has his own wants.

A voluntary trade betters all parties.
But why stop at trade?
A voluntary life betters the person.

The ideal society maximizes individual freedom while minimizing harm to the species.
Maximizes volition, the will to live.
Everyone fearlessly does what they love most.
Nobody slaves away at the office.

Occasional inconsequential broken small promises are okay.
People change.
People are sometimes too optimistic.

Things that don't belong in an ideal society?
- politicians
- lawsuits
- wars, refugees
- megacorporations, offices, employment
- religions
** Anarchy is the only way to delay our extinction?
It is absurd to centralize power to a few people who are prone to the same mistakes that we are prone to.
** Avoiding extinction
There are two ways for humans to avoid extinction: a political way and a biological way.
The political way is to create a political system that does not depend on human benevolence.
The biological way is to technologically alter the nature of humans.
The political way is much simpler.
** Preventing subversion with religion, and maintaining social cohesion
Yuri Bezmenov: Psychological Warfare Subversion & Control of Western Society (Complete)[fn::https://www.youtube.com/watch?v=5gnpCqsXE8g]:
- four stages of subversion: demoralization, destabilization, crisis, normalization
- Workers must negotiate directly, not through trade unions.
- It is much cheaper to prevent subversion than to fix it.
- Beware of non-elected committees.
- Religion keeps social cohesion.
* Human nature is communistic for kin and capitalistic for non-kin
We reckon more with non-kin and less with kin.
We share many things in our home with our families.
But we rarely share with strangers.
** Families are communists
We share resources with our family.
Every family is a communist micro-society.
** Argument for more communism?
Highlights of "The Role of Luck in Life Success Is Far Greater Than We Realized"
 [fn::https://blogs.scientificamerican.com/beautiful-minds/the-role-of-luck-in-life-success-is-far-greater-than-we-realized/]:
- "They defined /talent/ as whatever set of personal characteristics allow a person to /exploit lucky opportunities/" (emphasis mine)
- "1.7 million dollars to properly /determine the extent of serendipity in science/." (emphasis mine)
- 'This last finding is intriguing because it is consistent with other research suggesting that
  /in complex social and economic contexts where chance is likely to play a role,
  strategies that incorporate randomness can perform better than strategies based on the "naively meritocratic" approach/.' (emphasis mine)
- "With that said, the /best/ funding strategy of them all was one where an equal number of funding was distributed to everyone."
* Basic politics
** Hobbes?
Hobbes[fn::https://www.iep.utm.edu/hobmoral/],
political philosophy[fn::https://www.iep.utm.edu/polphil/]

Hobbes vs Locke?

There is some good in humans.
For example, I believe that most people will not kill people for fun out of boredom.
Or am I wrong?
Does the existence of gladiators disprove my belief?
** What is human nature?
If we did not have to do anything, what would we rather do?

https://www.humansandnature.org/humans-nature-and-ethics

Every human has wants.

Freedom?

Avoidance of boredom?
Pain?
Schopenhauer?
 [fn::https://www.iep.utm.edu/boredom/#SH3a]
 [fn::https://biblioklept.org/2014/01/04/pain-and-boredom-schopenhauer/]

A life is a thing that has different wants.

The essence of life is to have changing wants.
Fickleness is the essence of life.
*** Greed, envy
Greed is endless wanting.
Greed is feeling insufficient.

Envy is wanting what others have.

Why do we envy?
Why do we want what others have?

Why do we want things that do not make us happy?
*** Why do we want?
To sustain life.
Example: we want to breathe, eat, drink, excrete, etc.
** Political theory/research
*** Why do politicians diverge from their constituents' preferences?
https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences
*** <2018-10-02> We don't want completely free-and-global trade because we don't want to depend too much to others.
**** Independence is necessary but not sufficient for sovereignty.
By depending on someone, you give him power over.
You weaken your bargaining power.
You worsen your negotiating position.
You reduce your sovereignty.

We must start strategic domestic industries, no matter how shitty it will be.
We can always improve it later.

<2018-10-03>
*** Cipolla's laws of stupidity
- https://en.wikipedia.org/wiki/Carlo_M._Cipolla
- Cipolla's definition of "stupid":
  "A stupid person is a person who causes losses to another person or to a group of persons while himself deriving no gain and even possibly incurring losses."
*** Why are the Norwegians so sensible? Why are their governments so good?
[[https://www.youtube.com/watch?v=b_l3eLhYbVo][Why The UK Lost Its Oil Wealth (And Why Norway Didn't) - YouTube]]

Every country has smart people.
Smart people are everywhere.
Why do countries fare differently?
** State, nation, country
*** Politics basics: What is the difference between nation, state, country?
https://tamayaosbc.wordpress.com/2010/11/19/basic-concepts-in-politics/
*** What is a state?
States are abstract.
People are concrete.
*** How does a state comes into existence and stays in existence?
The founders of a state understand power dynamics.
Their children do not.

A state comes into existence by the deliberation of its founders and persists through time by the ignorance of their citizens.
** Natural state?
If people do not have to do anything, they do what they want to do.
Some think; some sing; some exercise; some kill.

Hobbes?

Stable anarchy requires social contract: no one shall be the first to aggress.
Peace treaty
Honor code
Families have stronger bonds than tribes.

Government vs state

Hobbes argues ...
State of nature
government is necessary

Read hobbes leviathan directly

We must not assume that everyone is good.

Axiom: bad people always beat good people.

Suppose that a society consists of 1,000,000 good people and 1 bad person.
How do we design the society so that the bad people do not harm others?
How differently would we design our society if there were more bad people than good people?

An animal kills only when it is hungry or threatened.
A lion with full stomach does not kill a deer.
An animal does not kill more than it eats.
A lion does not kill two deers if eating one deer suffices to fill up its stomach.
The surviving deers do not hold grudges against the lions.
The deers do not plot a retaliatory genocide of the lions.

But the more intelligent animals do hold grudges.

A human may kill for fun out of boredom, or out of envy, or other excuses.

It seems that animals are more moral than humans.

Intelligence breeds immorality?

Hobbes makes a strong argument against anarchy.

Hobbes is right about the natural state of humans.
People, even some Westerners, did join ISIS.
** Clashes of power
Clash of power; two mafias fight: ICC vs USA
 [fn::https://www.npr.org/2019/04/05/710324238/u-s-strips-visa-from-intl-criminal-court-prosecutor-pursuing-war-crime-inquiry]
 [fn::https://amp.theguardian.com/law/2019/apr/05/us-revokes-visa-of-international-criminal-courts-top-prosecutor].
* Unanswered questions
** How should we live in the 21st century?
We dream of a self-sufficient global sustainable anarchistic society where people freely do what they really want without harming others, where power is distributed.
But this dream may change.
We are trying to understand what anarchy is, and we disagree with some anarchists.
A state has good and bad things.
The question is: What is the price of having states, and is it too high a price to pay?
** What is the moral system that we have evolved?
What is our natural morality (the moral system built into us by evolution)?
Avoid harm?
** What is the difference between unethical and immoral?
What
 [fn::https://www.quora.com/What-makes-something-immoral-but-not-unethical]
 [fn::https://en.wikipedia.org/wiki/Heinz_dilemma]
 [fn::https://en.wiktionary.org/wiki/ethics#Usage_notes]
** What is the relationship between cooperatives and anarcho-syndicalism?
** Senior, lead, manager, director
Etymology clears up the differences.

Senior = older.[fn::https://www.etymonline.com/word/senior]

Lead = to show the way.[fn::https://www.etymonline.com/word/lead#etymonline_v_6615]

Manage = handle or train a horse.[fn::https://www.etymonline.com/search?q=manage]

Handle = "touch with the hands, hold in the hands, fondle, pet"[fn::https://www.etymonline.com/word/handle]

A director /directs/.
Directors knows what they want.
** Why should everyone know some basic epistemology?
If people know some basic epistemology (that is, if they can tell apart what they know from what /they think/ they know), then there will be no wars.
Some epistemology should be taught in primary school.
We often assume a lot of things about others.
Most conflicts happen because we assume something wrong about someone else.
** What does "X deserves Y" mean?
Does anyone deserve to be rich?
Does anyone deserve to be poor?
Does anyone deserve kindness?
Does anyone deserve inheritance?
** How should we be altruists?
If you want to be an altruist, pick activities with high impact-to-effort ratio[fn::https://www.effectivealtruism.org/articles/introduction-to-effective-altruism/].
Find a high-social-impact job suitable for you.[fn::https://80000hours.org/career-quiz/#/]
 [fn::How to find the world's most pressing problems https://80000hours.org/career-guide/most-pressing-problems/]
 [fn::The evidence on how to find the right career for you https://80000hours.org/career-guide/personal-fit/]
 [fn::Evidence-based advice on how to be successful in any job https://80000hours.org/career-guide/how-to-be-successful/]
 [fn::What are the 10 most harmful jobs? https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/]
 [fn::https://hackernoon.com/where-are-the-programmers-who-give-a-shit-87f859f13f75]
** Will we survive the 21st century?
I am [[file:world.html][somewhat pessimistic about the 21st century]].
** What is competent and dangerous?
Jordan Peterson: responsibility gives life meaning[fn::be competent and dangerous https://www.youtube.com/watch?v=ONK8pGAGT28].
** Procreation is not survival?
To survive is to keep/continue living.

Survival of the individual vs survival of the species?

Survivalism is compatible with antinatalism.

** What is fairness? How to divide a thing fairly?
https://en.wikipedia.org/wiki/Fair_division

From Wikipedia "Divide and choose"[fn::https://en.wikipedia.org/w/index.php?title=Divide_and_choose&oldid=853199297]
- "envy-free cake-cutting"
- "To an external viewer, the division might seem unfair, but to the two involved partners, the division is fair - no partner envies the other."

Thus, is fairness the absence of envy?
** What
Even if we didn't have states, we would still have laws.

Laws should be principles, not rules.
** Arguments against anarchy?
*** But how do we launch rockets without power centralization, without states and companies?
Or build nuclear power plants, or do trillion-dollar engineering projects?

How do we build particle accelerators in an anarchy?

How do we build global space defense to protect the Earth against catastrophic space-object impacts?

How can millions of people cooperate in an anarchy?
*** Problems with anarchy?
**** Without ownership, who will build buildings?
** Voting dilemma
Voting means being complicit in oppression.
Not voting means letting the bigger oppressor win.
** How do we turn 7 billion people from passive sheep to self-determining anarchists?
One at a time?
If we can make robots to do all the toils we would rather not do, we can have anarchy.

There should be a media company dedicated to finding out the bad side of authorities.
Like this Fox News article[fn::https://www.foxnews.com/us/the-dark-silent-history-of-nuns-sexually-abusing-minors-set-to-become-the-next-church-scandal.amp].
** How far should we respect others?
Example: how should a liberal treat an anti-vaxxer?

Liberals try to respect people, accept people as they are, be as non-judgmental as possible, as long as they don't harm others.

However, should stupidity be respected?
Should people who refuse strong evidence be respected?

How much we respect a belief should depend on only two things:
- how true that belief is, and
- how useful that belief is.
** The consumer shares some fault for global warming
Business are simple.
Profit is their strongest driver.
We consumers incentivize global warming.

We consumers must stop making global warming profitable.
We must not buy products that damage the Earth.
We must not buy products whose production damages the Earth.
* Does not belong here
** Is there an Indonesian etymology dictionary?
I am looking for an Indonesian etymology dictionary, which I think is necessary for philosophical analysis of Indonesian laws.
** Lying
*** Statistics makes bullshit appear legitimate
In 2019, by refuting a bullshit in Gamal Albinsaid's Twitter account,
Ainun Najib demonstrates[fn::https://twitter.com/ainunnajib/status/1082185571559124992][fn::https://www.facebook.com/joko.trikukuh/posts/10161376605960541]
Brandolini's bullshit asymmetry principle[fn::https://twitter.com/ziobrando/status/289635060758507521]:
"the amount of energy needed to refute bullshit is an order of magnitude bigger than to produce it".

One does not have to understand statistics in order to be able to bullshit with statistics.

Most people (including myself) don't understand statistics.

Every time I see an article with statistics,
I suspect that the author has not done sufficient philosophical analysis.

We do not have to refute the entire bullshit.
We only have to point out a fatal flaw, such as a truncated graph,
and cause readers to doubt the writer's intention.

A bullshit contains the necessary ingredient to refute itself.
A bullshit has an inherent flaw that we can point out without referring to anything outside the bullshit.
We just have to point it out.
"This is a truncated graph. You are lying."
*** Levels of lying?
Level 0: obvious lie, obviously nonsensical, takes no effort to refute.
Example: a child who broke a vase.

Level 1: sophisticated story, but no data.

Level 2: using true data, but selecting only the data that matches your agenda.

Level 3: level 2 plus fancy graphics, numbers, tables, statistics, truncated graphs[fn::https://en.wikipedia.org/wiki/Misleading_graph],
and damn lies[fn::https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics].

Level 4: level 3 plus creating your own pseudo-philosophy.

Level 5: post-truth politics: inventing your own facts.

** Designing a lovable government?
*** Purpose

The highest law is the will of the people.
The people can change the constitution.

|                         | benefits few    | does not benefit few      |
| benefits many           | good business   | road-building             |
| does not benefit many   | crime           | self-defeating behavior   |
#+CAPTION: Examples of actions according to beneficiaries

Economically, government is to maximize positive externality,
and minimize negative externality.

Example negative externality:
road congestion due to residential space transforming to commercial space.

*** Policy

Do the simplest intervention with the least effort,
the greatest effect, the least gameability,
the least unintended consequences.
But those are conflicting requirements.

Example: even-odd license plate based on day of month.
People will game this by buying two license plates or buying two vehicles.

Avoid wasting resources on policies that
do not attack the root cause of the problem.

*** Murder

Why is something illegal?
Perpetrators are going to perpetrate anyway,
and non-perpetrators are not going to perpetrate,
regardless of its illegality.

Some people commit crime unwillingly because they
want to continue living but they no see other way.
Some people are wired differently and commit crime like a pastime.

If something is illegal, why does a perpetrator still do it?
Is it futile to make anything illegal?
If it were not illegal, will it still be done?

Law cannot change human nature.
If you want to change human nature, study biology, not law.
Lawmaking must defer to human nature.

It is impossible to enforce a law if millions of people violate it at the same time.
If a law is against human nature, of course people will violate it.

Is it moral to force someone who enjoy murder not to murder?

*** Morality

Government should not interfere in private matter
such as religion, insurance, and consensual sex.

If something does not harm anyone else other than the doer,
it should not be illegal.

We should help others,
but we should to the greatest extent avoid forcing
others to do anything against their will
even though doing that would be good for them.
Consequence: procreation is immoral because
it forces people to exist without their consent.

We can persuade, but we should not force, unless we are in war.

Consumption should be taxed, not income.

Alternative to taxation: donation, state-owned enterprise.

Stability.

In a republic, in an election, you don't pick the best candidate;
you pick the one that will do the least damage.

Holding a government position should not be profitable.
How do we prevent abuse of power?
By not giving power in the first place?
The people must have the final say.

*** Banning

Banning something does not eliminate it.
Worse, banning it may also create a black market for it.

Regulate, don't ban.

*** Sex

Blocking access to Internet porn sites does not work.

Banning prostitution creates black market.

Banning sex makes more people more curious.

It's part of human nature.

Family education.

*** Drugs

Some people are curious.

*** Patents

Alternative to patents:
Prize system:
People collect money for a problem,
and the sum is awarded to the inventors who solve the problem.

Another alternative: People can donate to inventors.

Another alternative: Assume that inventors do things
because they love to do that, and they want money, but don't want to get filthy rich.

How was the first people who invented spears rewarded,
if they were rewarded at all?

*** Prevention of mass destruction

How does a government prevent
nuclear briefcase detonation,
water source poisoning,
asteroids hitting Earth,
and so on?

The amount of security is inversely proportional to the amount of trust.
If you could trust everybody, security would be unnecessary.
Republics are complicated because you can't trust the ruler.
Republics are designed to minimize the damage done by an evil ruler,
not to maximize the benefit done by a competent ruler.

The most efficient government is
benevolent competent kind laissez-faire minimalist absolute monarch,
but it is also the most risky.
Anything can happen if the ruler dies.

*** Differences

Conventional government assumes that most humans are fundamentally evil.
New government assumes that most humans are fundamentally non-evil.

*** Office

If you tell people to do something they don't want,
they will do their best to avoid it.
If they want to do it,
they will do it anyway without your telling them.
Thus, you don't tell people.
You simply let them do things,
help them do things,
get out of their way.

If you hire the people who don't want to do the things you want,
no amount of salary will fix it.
When you hire people, there is an intersection between what they want,
what you want, and what your organization wants.

In the office, there are so many things happening that it is too much
for one person to keep track what everyone else is doing.
You are the only person who knows what you really do.
Your supervisor, if any, is the second person to know what you do.
Others have even vaguer ideas about what you do.
But people can instinctively see whether you're doing well or not,
so if you're not doing well,
you must pretend that you were doing well,
and then suddenly you will do well.
If you think you're not doing well, if you doubt yourself,
then it will be a self-fulfilling prophecy.
Even if you are absolutely sure that your job is unimportant,
even if you keep stumbling,
you must unquestioningly believe that you are doing well.

In the office, what you do is less important
than what others think you do.

If you don't know what to do, walk around, and talk to people.

If you don't fit in one company,
maybe that's the company's fault.
But if you have tried three much-different companies
and still can't fit, maybe it's your fault.

Make friends.
People first.
Jobs second.

The number of processes is inversely proportional to the amount of trust.

How much trust are you convenient with?

There are people you naturally gravitate towards,
and people you naturally gravitate away from.
** Evil automobile industry?
https://www.reddit.com/r/todayilearned/comments/9mv3oi/til_that_the_term_and_concept_of_jaywalking_was/
** Government is a trillion-dollar Ponzi scheme?
"John Stossel - Government's Ponzi Scheme"[fn::https://www.youtube.com/watch?v=iNVXaeX4JK8]
** Insurance is gambling; the proof is in the house advantage
Both insurance companies and casinos have /house advantage/; otherwise they go bankrupt.
The bets are tilted in their favor.
** Let's slim down the morbidly obese government
*** What
Medicaid insanity
https://www.reddit.com/r/MaliciousCompliance/comments/90q9m3/i_dont_work_here_anymorehey_boss_got_an_opening/

"I recommend seeing which movie best predicts */future/* scenes."
https://blog.dilbert.com/2018/06/10/why-democrats-hear-a-secret-racist-dog-whistle-and-republicans-dont/

Is this related?
https://blog.dilbert.com/2018/05/04/why-president-trump-deserves-credit-for-progress-in-north-korea/

Blackwater and Erik Prince do mostly GOOD
https://www.youtube.com/watch?v=GOeFKiTP9A0

It's true.
PMCs can be corrupt in the same way that governments can be corrupt.
But a corrupt PMC of 100 people is much less dangerous than a corrupt government of 100,000 people?

"Leaving the Left"
https://www.youtube.com/watch?v=kl0-n0zWVJk

The Left's War on Science
https://www.youtube.com/watch?v=OX8kEjSUr04

Gray Grumbler: "As a retired scientist, both extremes are problematic to science.
The right doesn't stop science but often ignores good science.
The left stifles science they are against and often puts forward junk as science.
And this junk discredits the good science.
I am completely displeased with both sides.﻿"

Admit it. Republicans have broken politics.
https://www.youtube.com/watch?v=mICxKmCjF-4

2004 article "Government: Unnecessary but Inevitable"
http://www.independent.org/publications/tir/article.asp?id=15

The only thing we need from government is protection from physical harm.
But only you can protect yourself?

We have to prevent concentration of power.
Government is concentration of power.
But would we rather arm all people, and have a tribal war, instead of oppression?
But would we have a tribal war?
Haven't we evolved to cooperate?

Even right people avoid the cops.

America’s Parasite Lawyers Deprive Us of Good Things
https://www.youtube.com/watch?v=gTQtVsggZXY

Freeloaders: The Wealthy
https://www.youtube.com/watch?v=DsTKAqHwj0s
We can always depend on the government to make bad rules. How do we profit from bad rules?

The Cayman Islands is not a tax haven. We need less rules, not more rules.
https://www.youtube.com/watch?v=bI7W65k-LPM

Fox News is fake news.
https://amp.cnn.com/cnn/2018/10/29/media/pittsburgh-suspect-invasion/index.html

"Leftist Protesters Get Perfectly Checkmated"
play the victim forever
https://www.youtube.com/watch?v=2NAKH8jdgm8

Dinesh D'Souza?
"it's not Trump that created the division, the division created him"?
https://www.youtube.com/watch?v=jhu7ZjeEO2s
I don't want to be associated with this guy, but does he speak the truth? https://en.wikipedia.org/wiki/Dinesh_D%27Souza

Cigarette smoking

I first got this from Judea Pearl's book of why.
https://tobaccocontrol.bmj.com/content/11/suppl_1/i110

Government problems:
- Wastefulness
- Perverse incentive
#+BEGIN_QUOTE
In two 1954 speeches made by Philip Morris vice president George Weissman, he promised: “[I]f we had any thought or knowledge that in any way we were selling a product harmful to consumers, we would stop business tomorrow.”
#+END_QUOTE
- https://truthinitiative.org/news/philip-morris-announcement-spend-nearly-1-billion-end-smoking-sounds-fake-news
- https://www.unfairtobacco.org/en/pressrelease-quitpmi/

The Inconvenient Truth About the Republican Party
https://www.youtube.com/watch?v=OURy5WFp0zk
Historically it is the Democrats that is sexist and racist. It still is.

Minimum wage hurts the very people it is supposed to protect. The proof is clear. The reason is clear.

The $15 Minimum Wage Is Turning Hard Workers Into Black Market Lawbreakers
https://www.youtube.com/watch?v=0fsVI3EmUnQ
Everyone loses. Workers lose. Business owners lose. Customers lose; reduced competition. Government actively harms everybody. Government is unethical.

Government is a preventable disease?

Who Are the Most Powerful People in America?
bureaucrats, unelected and unaccountable little kings
https://www.youtube.com/watch?v=ZwmUH5AGydQ

Fucking stupid harmful racist Marxist government.
"South Africa 2019: Beginning of the END".
South Africa is the next Zimbabwe.
https://www.youtube.com/watch?v=nURta8-zu4E

Infiltrate 1 million people with nanobots, and kill all those people simultaneously.
*** How do we know what law is in effect? Bagaimana cara kita tahu hukum yang berlaku?
- http://m.hukumonline.com/berita/baca/hol19115/fiksi-hukum-harus-didukung-sosialisasi-hukum-
- Perpres 1/2007
- JDIH lembaga yang bersangkutan
*** Bush crime family
https://twitter.com/JoshClarkDavis/status/1068889697999568897
"This is a major part of Bush’s legacy. It’s what his War on Drugs did to just one person. But it shows the human costs of that war in miniature detail. A high schooler was lured to the WH to sell crack and spent 7+ years in prison, so that the President could make a point on TV."

*** Abolish patents
"Company [Google] Tried to Patent My Work After a Job Interview"
https://patentpandas.org/stories/company-patented-my-idea
That's not the first time for Google.
https://twitter.com/matthewstoller/status/1068542058175098882
*** Minimum wage hurts the very people it is supposed to protect.
Government should abolish minimum wage law.
Everyone should know everyone else's salary.
Worker union is about collective bargaining power, not about formal organization.
The moment a worker union is made a formal organization, it gets its own life, and it starts to benefit itself; it stops to benefit the workers.

Organized Labor Hurts Us
https://www.youtube.com/watch?v=IDA8AyrtTN8
*** Indonesia
What?
- https://www.zenius.net/blog/13453/apa-itu-demokrasi-liberal-kapitalis-komunis-sosialis-fasis-anarkis-konservatif
- ? http://www.berdikarionline.com/kisah-buruk-soeharto-di-mata-soebandrio/

SIM?
UU 22/2009 tentang lalu lintas dan angkutan jalan raya
https://www.bantuanhukum.or.id/web/implementasi-undang-undang-nomor-22-tahun-2009-tentang-lalu-lintas-dan-angkutan-jalan-raya/
*** Don't visit the UAE.
https://amp.theguardian.com/commentisfree/2018/nov/23/justice-uae-dubai-british-academic-matthew-hedges
*** How can Bhutan be unlike others?
"This country isn't just carbon neutral — it's carbon negative | Tshering Tobgay"
https://www.youtube.com/watch?v=7Lc_dlVrg5M

<2018-12-11>
Bhutan has a wise king.
But will the democratization give rise to political panderers and crippling bureaucrats in year 2100?
But is that worth to avoid the risk of a later evil king?
*** Government did not solve food/drug poisoning problem. Tamper-resistant packaging technology solved it.
Government doesn't need to intervene in Tylenol scare.
Free market can handle that.
If the producers don't find a better packaging, people simply won't buy.
Consumers simply have to tell what they want to the producers.

Technology always solves problems and creates new problems, but governments only create problems.
Governments are part of the problem, not of the solution.
** Keeping track
*** Who murdered these journalists?
Journalists have been brutally murdered in these areas:
- Malta: Daphne Caruana Galizia was car-bombed in 2017. https://en.wikipedia.org/wiki/Daphne_Caruana_Galizia
- Bulgaria: Viktoria Marinova was raped and murdered in 2018.
- https://www.theguardian.com/media/2019/feb/03/marie-colvin-murder-verdict--risks-journalists-lindsey-hilsum
*** Which news sources are untrustworthy?
No news source is trustworthy.
Think for yourself.
Learn some epistemology.
Don't read the news.

Vox [fn::https://www.vox.com/platform/amp/policy-and-politics/2018/10/1/17923178/washington-times-seth-rich-aaron-rich-trump-fox-news] says that these are untrustworthy:
Washington Times,
FOX News.
But Vox isn't trustworthy either.

VICE might have violated Naomi Wu's privacy?[fn::https://www.reddit.com/r/KotakuInAction/comments/898na9/vice_gets_patreon_to_remove_naomi_wu_who_blasted/]

Gizmodo and BuzzFeed are somewhat OK when reporting tech, but I find them very biased about social issues.

If it uses clickbait titles, it isn't readworthy; it's just another advertising whore.
If you think DailyMail is shitty, wait until you see Indonesian news sites like Detik.com, Kompas Online, VivaNews, and their ilk.
Pop-up ads.
Ads everywhere.
These Indonesian news sites are total whores that gladly let advertisers rape their spaces.
<2019-02-02>

Wikipedia maintains a blacklist of untrustworthy news sources
 [fn::perennial sources with varying trustworthiness https://en.wikipedia.org/wiki/Wikipedia:Identifying_reliable_sources/Perennial_sources]
 [fn::https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2018-12-24/Discussion_report]

Is BBC also untrustworthy?[fn::https://twitter.com/briankrebs/status/1092621689224085504]

** Fragments
*** Nitrogen asphyxiation for capital punishment
Nitrogen asphyxiation is humane, cheap, and fast.
- https://www.quora.com/What-would-be-the-fastest-and-most-efficient-way-to-kill-someone
- https://www.quora.com/Why-is-nitrogen-asphyxiation-not-used-in-capital-punishment
- https://en.wikipedia.org/wiki/Inert_gas_asphyxiation
- https://www.washingtonpost.com/news/post-nation/wp/2018/03/14/oklahoma-says-it-will-begin-using-nitrogen-for-all-executions-in-an-unprecedented-move/?noredirect=on&utm_term=.f342a31e16e9
*** Trust conserves resource
Trust enables us to use less resources.
Without trust, we have to defend.
Defense uses resources.

Without trust:
we have to bring weapons everywhere;
we can't trade;
we can't collaborate;
groups can't form.

A group cannot exist if its member kills each other.

In order for a group of men to be greater than the sum of its members,
every man must give more than he takes, and therefore every man has to be altruistic/self-sacrificial.

"Without trust, all contingent possibilities should be always considered, leading to a paralysis of inaction."[fn::https://en.wikipedia.org/wiki/Trust_(emotion)]
*** Practical morality
https://theconversation.com/the-greatest-moral-challenge-of-our-time-its-how-we-think-about-morality-itself-92101
- "[M]orality is the set of rules we live by that seek to reduce harm and help us live together effectively."
- "the problems that morality is trying to solve vary from one place to the next."
- "There are ways to judge the usefulness of a particular moral norm, namely: does it actually help solve the problems of social living for the people using it?"
*** What was morality?
Does a law requiring S imply that, before it existed, people would routinely violate S?

Does the Ten Commandments imply that, before it existed, people routinely murder each other?
*** Other resources?
What is this?
https://oll.libertyfund.org/pages/ideas
*** Liberalism, inheritance, and inequality
Dilemma:
- If we cap inheritances, we are thieves.
  We don't want thieves in the ideal society.
- If we don't cap inheritances, we breed inequality.

Inequality is not a problem in and of itself.
The problem is ensuring that the poorest people are not too bad.

People should be free to give whatever thay want to whomever they want, including their kids.

[[https://givingpledge.org/][The Giving Pledge]] tries to solve the big-inheritance problem, but we can't always depend on voluntariness.
Also, that pledge lacks concreteness and is not [[https://en.wikipedia.org/wiki/SMART_criteria][SMART]], so it practically does not exist.
According to [[https://en.wikipedia.org/wiki/The_Giving_Pledge][Wikipedia]]:
- "As of 2018, [...] their pledges total over $365 billion."
- "It does not actually dictate that the money will be spent in any certain way or towards any particular charity or cause, and there is no obligation to actually donate any money. "

Then what the fuck is it for?
Public relations spin?
How do we verify that those people have actually donated?
Is such verification even practical?
** General average?
Is general average socialism?
Is it moral?
Is it moral to handicap fortunate people?
Is it moral to help unfortunate people?
** Principal-agent problems, and conflicts of interests
** 2018 Jewish synagogue shooting: Resentment, despair, impatience, care, fascism, and extremism
https://www.theguardian.com/us-news/2018/nov/04/pittsburgh-shooting-robert-bowers-jewish-nurse

How one becomes a fascist:
He feels that democracy goes nowhere.
He realizes that people don't change.
People don't care.
Politicians are corrupt.
Government doesn't help him.
Cities are unwalkable.
He feels the system is rigged against him.
He begins isolating himself.
He continues to think.
As he thinks, he becomes more extreme.
He reinforces his beliefs.
He confirms his own biases.
He goes online.
He meets people who feel the same.
He is young and impatient.
He wants to see changes right now.

A person needs a justification for his existence.
If he thinks that the system is corrupt and is rigged against him, he will think that his violence is justified.

https://www.jacobinmag.com/2015/07/french-revolution-bastille-day-guide-jacobins-terror-bonaparte/

Oppressed majority will revolt.

Power ultimately comes from the ability to kill.

<2018-11-03>
Watch what Brazil will be under Bolsonaro after 1 year.
** Media
We need a neutral, non-profit media.
We need a bunch of united non-unionized independent journalists.

Every person should be able to report what he/she sees around him.

But what about lying peoples?
** Surprise
/Surprise/ is the discrepancy between belief and reality.

An event /surprises/ us iff we believe it is unlikely but it happens.

Myron Tribus surprisal[fn::https://en.wikipedia.org/wiki/Information_content].
Surprisal 0 means not surprising at all: it is bound to happen.
A-priori truth is unsurprising.
That a bachelor is unmarried is unsurprising, because that is the definition.
But the Immerman–Szelepcsényi theorem[fn::https://en.wikipedia.org/wiki/Immerman%E2%80%93Szelepcs%C3%A9nyi_theorem] was very surprising when it was first proved.
An a-priori truth is surprising if it is hard to compute (hard to know) and its result goes against our guess.
How can mathematics be surprising
 [fn::https://mathoverflow.net/questions/18100/theorems-with-unexpected-conclusions]
 [fn::https://math.stackexchange.com/questions/2949/which-one-result-in-mathematics-has-surprised-you-the-most]
if everything that we prove has always been true, only that we don't know it?
The Pythagorean theorem is true, but we did not know that it is true until we were taught about it in school.
A mathematical statement may be true, but we did not know that is true until someone proves it.
Surprisal \( \infty \) means infinitely surprising: the impossible happened.
** Marriage is just a contract
Key idea:
Contract law subsumes marriage law.
Marriage is an exclusive non-transferable license for sexual activities.
Marriage generalizes to any graph-theoretic arrangement of exclusive sexual rights.
*** Marriage regulates copulation, not procreation
Marriage regulates /copulation/ (having sex), not procreation (having offsprings).

/Before/ marriage has been invented, the society assumes that copulation is allowed by default unless explicitly forbidden (by complaints, disputes, fights, wars, treaties, etc.).
/After/ marriage has been invented, the society assumes that copulation is forbidden by default unless explicitly allowed (by marriage).
This change of fundamental assumption improves public order.

Copulation and procreation are two /orthogonal/ concepts.
Two concepts are orthogonal if we can have one without the other, in both ways.

To /copulate/ is to link / join / bind / tie / couple / bring together / conjoin (the genitals).
To copulate is to cause the male genital to be inside the female genital.
The male genital protrudes (goes outward).
The female genital receives (goes inward).
- https://en.wiktionary.org/wiki/copulate#Etymology
- https://en.wiktionary.org/wiki/copulare#Latin
- https://en.wiktionary.org/wiki/copula#Latin

Copulation is sexual intercourse.
Procreation is the production of offspring.

We can have /copulation without procreation/: inserting the penis into the vagina without ejaculating sperm, even between two married people.

We can have /procreation without copulation/: cloning, in-vitro fertilization, synthetic organisms.

Marriage is about exclusive copulation, not about procreation.
*** Arguments for and against generalizing marriage
**** Pro: Marriage regulates copulation, not procreation
Do you mind if your spouse copulate with but doesn't procreate with someone else?
That is, do you mind if your spouse had sex with someone else as long as nobody gets pregnant?
If you do mind that, then marriage is about regulating copulation, not procreation.

Do you mind if you can procreate with but not copulate with your spouse?
Consider an average couple.
Suppose that the husband's penis and the wife's vagina must never touch,
but a third person will, at no cost to the couple, inject the husband's sperm into the wife so that the couple can have a child.
Do the average husband and wife mind such [[https://en.wikipedia.org/wiki/Sexless_marriage][sexless marriage]]?
If they do, then marriage is about regulating copulation, not procreation.

Marriage, public order, and justification of marriage?

Legally, marriage exists to maintain public order.
Biologically, public order exists to maintain survival of the species.

Why does marriage exist?

Marriage exists because the average person gets angry when someone (s)he copulated with copulated with someone else,
and this anger may disturb public order.
Problem:
The definition seems to require that the sexes be different.
Is it reasonable to generalize "copulation" into "any sexual act"?

The average person would be angry if his/her spouse have any sexual acts (including flirting and sexual advances) with someone else.
It is not only copulation.
It is all sexual acts.
It is all acts that may reduce the chance of copulation.
The average man would be suspicious if his wife begins receiving lavish gifts from another man.

Therefore it is reasonable to generalize marriages to concern the exclusive rights of everything that may lead into copulation, not only copulation.

The debate of marriages boil down to the definition of copulation, and the relationship between copulation and procreation.

Originally copulation was for procreation/reproduction, but then nervous systems evolved, then pleasure centers evolved,
and thus copulation evolves to be pleasurable, because otherwise the organism will not reproduce.
**** Con: Monogamy has evolutionary benefits
Perhaps most of us we have evolved to prefer monogamy.

Monogamy reduces the risk of contracting sexually-transmitted diseases.
- Those diseases may co-evolve with us.
- [[https://www.biorxiv.org/content/early/2017/10/15/203695][Sexual conflict and STDs: coevolution of sexually antagonistic host traits with a sexually transmitted disease | bioRxiv]]
- https://en.wikipedia.org/wiki/Monogamy#Evolutionary_and_historical_development_in_humans
- https://edition.cnn.com/2016/05/17/health/sti-infanticide-human-monogamy/index.html

Monogamy improves infant survival.
*** General marriage
Contract law subsumes marriage law.
The law does not need to define marriages, because ordinary contract law suffices.
We can restate marriage terms in /contract law terms/:
cheating is /breach/, divorce is /termination/, and alimony is /damages/.

Usually we think that a marriage is a /contract/ between a person X, a person Y, and their society, stating that:
- person X and person Y may copulate with each other,
- person X must not copulate with anyone else other than person Y,
- person Y must not copulate with anyone else other than person X,
- the society will help enforce that restriction.

But that thinking is too narrow.
We can generalize that definition to any arrangement of sexual rights.
Two aspects of marriage generalize readily:
the /number/, from only two to any number;
and the /kinds/ of allowed sexual activities, from only copulation to any kind of sexual activities.
For example, group marriage generalizes the number, and gay marriage generalizes the kind of sexual activities.

Some examples of generalized marriages:
- Group marriage involving a group G of people P1, ..., Pn:
  - If person X is in G and person Y is in G, then person X and person Y may copulate.
  - Everyone in G must not copulate with anyone outside G.
- Strictly-heterosexual group marriage:
  - Each person X in group G may copulate with each person Y in G if X and Y have different sexes.
  - Everything else is forbidden.
- General marriage:
  - A marriage is an undirected graph.
  - An edge (x,y) means that x may copulate with y.
  - The absence of an edge (x,y) means that x must not copulate with y.
  - You can see where this is going: complete-graph marriage,
    point-to-point marriage, bus marriage, star marriage, ring marriage, mesh marriage, daisy-chain marriage,
    and [[https://en.wikipedia.org/wiki/Network_topology#Classification][other topologies]] of marriage.

We can even have directed graphs.
For example, X may penetrate Y, but Y must not penetrate X.

We can even have multigraphs.
We can explicitly list the permitted sexual activities in the contract.

Marriage law is redundant.

Marriage is just a contract that happens to be about sexual rights.

Marriage is about regulating the genitals, not about regulating procreation.
When people fuck, they don't think about the next 20 years.
They just want to enjoy the moment.

Relationship between marriage, graph theory, and model theory:
What is the shortest first-order logic formula that describes a graph that describes a marriage?
*** Half-baked contents
**** Legislating marriage, copulation, procreation, parenting, and family?
Marriage regulates consent?
But there are marital rape and arranged marriages.

Marrying someone does not mean being able to do anything to him/her.
He/she is your spouse, not your slave.
** Potential, actualization, waste
Potential is what may be.

/Waste/ is failure to actualize potential.
Failure is final and irreversible.

The goal of a state is to ensure freedom for each person to actualize his/her potential, pursue greatness

Why do we feel bad wasting?
** Anti-natalists are the true liberals
A liberal is a person who avoids forcing other people.

Anti-natalism is a logical consequence of liberalism.
It is the ultimate respect for life.
It is the maximum amount of respect we can give to sentient beings:
We let them freely choose which one they want: existence or non-existence.

Natalists force other people to exist.
This goes against liberal morality.

(Not the American "Liberal".)
** Why is land so expensive?
Why is land so expensive?

Because sellers are asking for a high price.

How much did they buy it for?

Multiply the price by 70%-90%, for each year they own that land.

Why are buyers willing to pay such high price?

Because they can still squeeze some profit from the next people despite such high rent.

Land owners squeeze the land buyers who then squeeze the property users who then squeeze the customers.

Why does land price keep increasing?
Wrong question.
Why does /some/ land price keep increasing?
A land in the middle of nowhere does not change price much.
** Liberalism and child-rearing are incompatible
Why don't we let children do anything they want as long as they do not harm others?
Aren't children humans?
* Poverty
** What is the most efficient way to help people at the bottom of the social ladder?
Which?
- direct cash transfer
- education
- food
- grooming (haircut, clothing)

A combination of those?
** Why are poor people poor?
Combination of personal and systemic factors.[fn::https://www.cato.org/publications/commentary/why-are-people-poor]

Are poor people unfortunate?
Then we should help them.

Are poor people born by poor parents into poverty?
Then we should find a way to prevent them from procreating.
The problem is that condoms reduce the nice feeling of having sex.
Poor people may also have self-defeating beliefs such as religions that prevent them from using condoms.

We should not assume that poor people are rational.
* Creating a defendable society
How to be more powerful than governments?
People, machines, and weapons.

Each country is a chauvinist enclave.
** Persuading people to do immoral things
Seemingly immoral things are often moral when they are done /for defense/.

Thus we can justify killing people by /framing it as defense/.
If they are the first to try to kill us, then it is moral to defend ourselves by killing them.

People who believe that they are being attacked will feel fine killing their attackers.
Thus the trick to make people attack X is to make them believe that they are being attacked by X.

When convincing people, the truth is not important, because nobody knows the truth.
What is important is believability.
Some people are predisposed to have certain beliefs.
Also, beliefs are contagious.
Stupidity is contagious.

Anger tempts us to act.
Whether we actually act depends on whether our anger exceeds our fear.
* What turns curious children into apathetic adults?
Children are inquisitive.

"Education" turns those curious children into apathetic adults?
* Democracy does not work, and not everyone should be allowed to vote
It is an insult that these people
 [fn::https://harianmerdeka.com/lihat-sandi-emak-emak-ternyata-ganteng-sekali-pilih-nomor-2-aah/]
 [fn::https://www.jpnn.com/news/di-pintu-tps-emak-emak-berdebat-pilih-si-ganteng-atau-yang-pulang-umrah]
were allowed to vote.

Democracy incentivizes politicians to be stupid, substanceless, and pandering.
The system is broken.

Democracy is impractical.

Unfortunately, people who don't know they don't know outnumber people who know they don't know.
* Bibliography
