#+TITLE: Social Research Group
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /social.html
#+OPTIONS: ^:nil toc:nil
* Goals
To educate people about political power.

To prescribe how humanity should proceed in order to survive the 21st century.
* What is wrong with 21st-century societies?
** Focusing on growth instead of sustainability
Economic growth is not a worthy goal.
** Is financial investing moral?
Financial investing is getting more money without doing anything.
It is immoral, because it means indirectly stealing a little from everyone else.
We should not glorify rentiers, freeloaders, and thiefs.

But does that mean that passive income, rent, interest, tax, pension fund, and royalty are immoral?

Both inflation and deflation are immoral,
because it betrays everyone who trusts the currency.
Inflation hurts buyers.
Deflation hurts sellers.

But inflation prevents currency hoarding.
** Taxation + capitalism = stealing from the thieves
Taxing the capitalists is stealing from the thieves.
Both taxation and capitalism are immoral.
Their combination is unnecessarily convoluted.
The correct solution is to not have any theft in the first place.

The solution is not taxing the rich.
The solution is to remove the law that enables the creation of power-centralizing entities.
People must unite but they must not form a formal union.

Examples of power-centralizing entities are
formal institutions, formal organizations, companies, formal labor unions, legal fictions, virtual people.
** Why do we still care about constitutions?
Why should people in the 21st century agree with people in the 18th century?
Why should we agree with people born 300 years ago?
We don't even agree with our parents born 30 years ago!

What is a constitution?

USSR 1936 under Stalin[fn::https://en.wikipedia.org/wiki/1936_Soviet_Constitution]
had the most beautiful-sounding constitution, but it was only a lip service;
the practice was nowhere near that.
The most important thing a constitution must have is /limitation and decentralization/ of power.
* What are some example problems due to power centralization?
** What are humankind-destroying businesses that depend on addicting people?
Businesses that profit by making people addicted:
- Juul, vaping:
  Juul helps people start smoking more than it helps people stop smoking?[fn::https://techcrunch.com/2018/12/22/juul-me-twice-shame-on-you/]
- cigarette, tobacco
- gaming, advertising, drugs
- porn? (but we like porn? Is my porn your cigarette?)
** Abuses of power; reasons for anarchism (or even anti-statism)?
** Custom officers will seize your devices and breach your privacy.
Don't bring your devices in international travel
https://www.theguardian.com/world/2018/aug/25/sydney-airport-seizure-of-phone-and-laptop-alarming-say-privacy-groups
** You MUST have at least one camera in your car streaming the data to a remote safe location. Cops will trap you.
- https://www.youtube.com/watch?v=UpT-SAunuLk
- Busted! How to Handle the Police Until You Get a Lawyer - by Mary Griego https://www.youtube.com/watch?v=bmtIizXdh88
  - Ordering vs asking.
- We need to make sure that misbehaving cops are punished.
- 5 Rules for Recording Police: Steve Silverman of FlexYourRights.org https://www.youtube.com/watch?v=BHpQtvIxBJ4
** Class treason? Class traitors?
- https://en.wikipedia.org/wiki/Class_traitor
- police?
- human resources?
- every computer programmer working for government
** USA, Australia, imperialism, recent (19th-20th century) imperialism
Too bad there is no one fighting for the USA-oppressed island nations.

USA annexed (militarily occupied) Hawai'i from the locals.
https://www.youtube.com/watch?v=MfAiB2ZoRhM

USA annexed Puerto Rico from Spain who annexed it from the locals.
https://www.youtube.com/watch?v=g-GYqakwHdg

USA is not the only imperialist country though.

Australian imperialism

Honest Government Ad | Visit Timor-Leste! https://www.youtube.com/watch?time_continue=4&v=xqegTsi6SiE
- from https://www.reddit.com/r/indonesia/comments/9sbnyk/honest_government_ad_visit_timorleste/
** Political system is broken.
*** How Republicans and Democrats are different, and how they are the same.
**** How they differ
- Republicans scare you with dangers that don't exist, such as migrant invasions.
- Democrats excite you with benefits that don't exist, such as ever-increasing pensions.
**** How they are the same
- Both are liars.
- Both don't keep their promises.
- Both make the country worse off.

It's amazing that the USA can become the strongest nation in the world, despite the USA's dysfunctional political system.

Imagine what the USA could have been with a functional political system.
**** Why they behave that way: because they think short-term. Why do they think short-term? Because there are term limits.
**** Lying politicians should be sentenced to death. At least we should immediately vote them out of office.
**** The same thing happens in Indonesia. All parties are the same. The only difference is their religious stance.
***** TODO link that tirto.id article about party political spectrum
*** As long as we have political term limits, we will have popular-but-bad programs.
**** Politicians should not be time-limited. People should both elect politicans into office and elect politicians /out/ of office.
If politicians are time-limited, they will pander to the people and prioritize short-term gains.
**** We can vote people into office. Why can't we vote them /out/ of office?
* Why is power centralization the root cause of all woes of society?
The problem is not capitalism vs Stalinism.
The problem is /centralization of power/.
Both USA and USSR are corrupt.
USA gives too much power to companies.
USSR gives too much power to Stalin.

Both a state and a company are legal fictions for centralizing powers.

Stanford prison experiment[fn::https://en.wikipedia.org/wiki/Stanford_prison_experiment]
shows that /power corrupts/[fn::https://www.smithsonianmag.com/science-nature/why-power-corrupts-37165345/] good people.

Dacher Keltner has done some research on the effects of power on nice people.
Power "has a disinhibiting effect regarding the social consequences of exercising it"[fn::https://en.wikipedia.org/wiki/Dacher_Keltner#Theory_of_Power].

Power centralization is a logical consequence of our systems.
It means that the systems are working as designed.

Our systems have a tendency to centralize power.
Property.
Capitalism.
These tend to centralize power.
** What is a state?
A state is essentially a massive principal-agent problem[fn::https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem] involving millions of people.

The people give up their monopoly of violence to the state, and the state promises to do good to the people.
The problem is principal-agent problem.
The state cannot be trusted.
** How can workers empower themselves?
Labor laws and unions are the wrong solution.
The correct solution is that the workers must unite and think for themselves, but they must not form a union.
Once a union is formed (as a legal entity), it has a life of its own, and the principal-agent problem begins.
There is always room and incentive for union bosses to collude with the original enemy, enrich themselves, and betray the original electors.
The anarcho-syndicalists get this mostly right (what they get wrong is "revolution").[fn::https://en.wikipedia.org/wiki/Opposition_to_trade_unions#Left_critiques_of_trade_unionism][fn::https://en.wikipedia.org/wiki/File:Anti-union_ASF_flyer.jpg]
Direct action.
** What benefits us is trade, not capitalism
Capitalism contains free trade.
Free trade benefits everybody, but the for-profit private ownership of property doesn't always benefit everybody.
By free trade, we mean voluntary exchanges/transactions.

It is possible to have free trade without capitalism.
Anarchy is an example.

The issue is centralization of power.
Companies centralize economic power.
States centralize political power.
Institutions/organizations centralize power.
People must unite, but they must not form unions.
Principal-agent problem.
Unions have lives of their own.
** What is a company?
It is a physically impossible to build or hurt a company.
A company cannot do anything.
People do things.
A company is a legal fiction for concentrating wealth (economic power) to its shareholders.
Such economic power often translates to other forms of power such as political power.
A company is rife with principal-agent problems and conflicts of interest.
There is one principal-agent problem between the shareholders and the directors.
There is another principal-agent problem between the directors and the employees.
There is one principal-agent problem for each layer of management.
It is amazing that such fiction lasts despite providing ample rooms for corruption.
* What is power, security, trust, risk, and vulnerability?
"To exploit someone is to take unfair advantage of them."\cite{sep-exploitation}
** What is security?
** What is vulnerability?
Trust is the assumption that others will not exploit our vulnerabilities.

Everything is vulnerable.
Vulnerabilities differ in their probability and the severity, and thus their expected damages.
We protect our houses with gates to deter thieves.
But we don't protect our houses against meteors.
Meteors do more damage than thieves, but meteors are so rare that the expected damage of thieves exceeds the expected damage of meteors.
We probabilistically reason that thieves are more risky than meteors.
** Power
We assume these primitive concepts: harm, violence.
*** How do we design a power literacy course?
If I ask you to wave your hand, will you do that?
By following what I tell you, you have given me some power over you.
Why do you give me power?
Why do you let me control?

If I ask you to bark like a dog for $10, will you do that?

If I ask you to dig coal for $50,000 a year, will you do that?
If I ask you to drill the Earth for oil for $50,000 a year, will you do that?
What if I give you more money?

If I ask you to cut down a forest for $50,000 a year, will you do that?
Somebody out there will do that.

You see, there is a common theme:
you /let/ others tell you what to do.

Rich people can only give you money.
They don't cut down the trees themselves.

Why do we let others tell us what to do?
Because they pay?

Why do we let money bend our will?
*** What is power?
Power is control.

The amount of power X has over Y is the amount of control X has over Y.

Power is the ability to harm.

Power is the potential to do violence.

To have power is to control.
We say that /X has power over Y/ to mean /X controls Y/.
*** Why distribute power?
Keltner's paradox of power is a strong scientific reason for distributing power.
 [fn::Dacher Keltner, Ph.D. - "The Power Paradox: How We Gain and Lose Influence" (05/19/16) https://www.youtube.com/watch?v=HS9VHBlYklc]

Feeling powerful reduces morality and inhibition.

Feeling powerless causes chronic stress.
*** Power and control?
*** Power is the flip side of trust?
*** How does one gain power?
By gaining trust.

X can have power over Y if and only if Y /lets/ X have power over Y.

Employers control employees because employees /let/ employers.

Government controls the governed because the governed /let/ the government.

Gain power by sharing it?[fn::"How do humans gain power? By sharing it" https://www.youtube.com/watch?v=j2XpiVrUWog]

Now we understand where power comes from.
Evil people have power because we /let/ them.
How do we let them?

By being employed by them to perpetuate their evil.
Rich people are not destroying the environment.
/We/, their employees, are destroying the environment, by doing what they want us to do.
We, the coal miners.
We, the power plant operators.
We, the car sellers.
/We are complicit/.
We /let/ them control us.
It is our hands, the workers' hands, not the rich people's hands, who murder the kids, who launches the missiles.

/All rich people can do is give us money./
If we accept that money and we do evil, then we ourselves are at fault.

Companies and rich people are not to blame.
We the complicit majority are to be blame.
We are sleepwalking.
We are not aware of our own power.
We have power but we are afraid to use it.

But even if we are not complicit, those rich people will just buy machines and destroy the environment anyway?
Therefore they are truly immoral?
Why do they take pride in short-term profit maximization?
Who taught them?

Government must come from the people.
US government is for the rich only, not for the people.
The candidates are rich people.
The government listens only to rich people.
The government does what is good for rich people.
There is never a grassroot candidate.

But we have to feed our families.
Where do we get money?
This is the wrong question.
The question is: How do we feed our families?
/We/ can farm ourselves.
We feed them directly from our own labor.
Nature always gives to those who work, to those who hunt, gather, or farm.
Nature does not discriminate.
Only in nature, those who do not work do not eat.
A seed does not care about the color of the hand that sows it.
*** Where does one get power?
From nature.
Some of us grow to be strong and healthy people, by virtue of good genetics, good habit, and good nourishment.
*** How does one lose power?
By losing trust.
** Risk
Related words: danger, hazard, chance, gamble, probability, uncertainty, contingency.

(We are resisting the temptation of digressing to probability theory and statistics.)
*** What is risk?
Did Warren Buffett say that risk comes from not understanding what we are doing?

Risk comes from Italian "riscare" which means "to run into danger".[fn::https://www.etymonline.com/word/risk]

Risk is danger.

Danger is something that may harm.

Risk has negative connotation.
*** What is hazard?
"Hazard" was the name of a game of chance played with dice[fn::https://www.etymonline.com/word/hazard].
In 2019, "hazard" means danger.
*** What is chance?
*** Is it absurd to buy or build things that we hope to never have to use?
Insurance buyers hope to never have to use it, because having to use it means shit has happened.
We hope that shit doesn't happen.
When you buy a scissor, you expect to use it.
Insurance is the only thing that you buy but hope to never have to use it.

If I buy a gun, I hope to never have to use it.

If I buy a fire extinguisher, I hope to never have to use it.
Is it absurd for me to buy a fire extinguisher?

We hope that we never have to use atomic bombs.

Having to use an insurance or a gun means that something bad has happened.
We don't want bad things to happen.

https://www.reddit.com/r/AskReddit/comments/3uc06v/what_is_something_youd_buy_but_hope_to_never_use/
** Trust
*** Measuring trust between countries
**** The power of a country's passport tells how great that country is
https://www.passportindex.org/byRank.php

Your passport's power is proportional to how much the world trusts your country.
*** What is trust?
*** How little trust can we live with?
When I walk around the town, I tacitly assume that nobody will suddenly stab me with a knife.

** Contract is trust/distrust?
Signing a contract that obliges you is trusting.

Signing a contract that gives you a right is distrusting.

We make a contract because we want the state to help us when the other party breaches the contract.
Thus we make a contract because we distrust the other party.

Contracts reduces the amount of trust required for trade.

If the state did not exist, would we still make contracts?
We would rely on honor, and not the state.

But underlying every contract is the assumption that the state is honorable.

Contract assumes a third-party enforcer that is powerful and honorable (just, fair, neutral, reliable).
* How does power get centralized?
** Weapons and oppression
- Weapons enhance our ability to kill.
  - Weapons enhance our ability to scare.
  - Thus weapons enables better-armed people to oppress worse-armed people.
- Order of magnitude of weapon effectiveness
  - With a blade, one person can subdue 1 unarmed person.
  - With a pistol, one person can subdue 10 unarmed people.
  - With a machine gun, one person can subdue 100 unarmed people.
  - With a bomb such as that in Oklahoma city bombing, one person can subdue 1,000 unarmed people.
  - With a nuclear bomb such as those dropped by the USA on Hiroshima and Nagasaki during World War 2, one person can subdue 1,000,000 unarmed people.
- Order of magnitude of media deception effectiveness?
  - This is totally baseless.
    How do we estimate this?
  - With hearsay, one person can deceive ten people?
  - With paper, one person can deceive a hundred people?
  - With newspaper or WhatsApp, one person can deceive a million people?
  - With television or Facebook or Google, one person can deceive a hundred million people?
- The only way for the oppressed to fight back is:
  - total guerrilla warfare
  - living near to the oppressor (so that he can't nuke)
  - terrorism
    - Is there really no other way?
      Dialogs?
      Referendums?

What prevents violence is the ability to retaliate with comparable violence.
What prevents oppression is the ability to retaliate for that oppression.

NUKEMAP: nuclear explosion damage calculator
https://nuclearsecrecy.com/nukemap/
** Ownership, property
*** Why do people give up their power so easily?
*** How do we live in a society whose morality goes against ours?
How do we live in a society whose morality clashes with our morality,
without demeaning the people that we think are immoral?
How do we live morally but without self-righteousness?
*** If we need to be evil to change something evil, should we be evil?
*** Should we do the necessary evil?
If we believe that power should be distributed,
but we need power to change the world,
should we temporarily (~ 100 years) centralize power on us?
Can we trust ourselves, as power tends to corrupt?
*** Legal fictions?
Philosophically-unsound legal fictions such as corporate personhood create unnecessary misery.

Litigation is part of the problem, not part of the solution.
Justice should at least be restorative.

Problem:
"That’s why if your toaster explodes, you have to sue the company that makes the toaster.
You can’t sue the company’s shareholders.
The company and its shareholders are distinct legal persons, with different legal rights and duties."[fn::https://www.sfchronicle.com/opinion/article/Corporate-personhood-actually-limits-12721448.php]

How would the combination of restorative justice and no-corporation handle exploding toasters?
What is the anarchist approach to litigating one who makes an exploding toaster that hurts someone else?

"If Corporations Are People, They Should Act Like It"[fn::https://www.theatlantic.com/politics/archive/2015/02/if-corporations-are-people-they-should-act-like-it/385034/]

Both governments and corporations are part of the problem.

Anarchy is a /privilege/.
Freedom is expensive.
*** Capitalism does not benefit us; free trade does?
*** Legal system is part of the problem.
Nobody knows all laws that are in effect.
Not the legislators.
Not the judges.
*** Parallels between master-slave and lessor-lessee
"Slaves could not own property, but their masters often let them save up to purchase their freedom,[97] and records survive of slaves operating businesses by themselves,
making only a fixed tax-payment to their masters."[fn::https://en.wikipedia.org/w/index.php?title=Slavery_in_ancient_Greece&oldid=881609681]

That sounds very much like the relationship between a lessee (tenant/renter) and a lessor (landlord).
A lessee practically will never have enough money to buy the lessor's property;
the economic system guarantees that.
For example, in 2019, my neighbor is asking IDR 3 billion for his 72-m2 land and house on it.
A typical frugal man who saves IDR 3 million monthly salary will need to save for 83 years, assuming over-optimistically zero inflation.
He would have died 20 years before he had saved enough to buy the house!

In principle slavery has been abolished, but in practice the economic system guarantees that most people will forever live mediocre lives,
although in much better condition than that of ancient Roman slaves.
But we can do better.
*** What is ownership?
*** What is property?
*** What is slavery?
Slavery is the treatment of human as non-human property.
Slavery is humans' owning humans.

Slavery violates the silver rule (do not do unto others what you do not want to be done unto yourself).
*** If everybody needs to eat, why aren't farmers the richest people on Earth?
Food has been the best-selling thing for 40,000 years,
but why aren't farmers the richest people on Earth?

Here's a thought experiment that leads me to that question.

Imagine an economy that consists of 1 extremely frugal farmer and 1 doctor.
After some time, money accumulates at the farmer,
because the doctor always needs to eat, but the farmer doesn't always have a health problem.

A government has these options, from the least coercive to the most coercive:
- Do nothing, and hope that the farmer donates his money to the doctor.
- Create more money and give it to the doctor.
  But the farmer may think that this is unfair.
- Tax the farmer and give that tax money to the doctor.
- Force the farmer to spend his money on the doctor.

The current economic system suffers from money accumulation.

Is accumulation of money bad?
Is inequality bad?
*** What is ownership?
What does owning something mean?
*** What is property?
Is property theft?
*** If everyone owned a piece of fertile land, poverty should not exist?
** Work, employment
*** We should not conflate work and employment
Work gives life meaning.

Employment is subjugation.
X employs Y because X has a better idea about what Y should do with Y's time in order to make more profits for X.

Some people are lucky enough to have their work coincide with their employment.
They are lucky enough to be enslaved to do what they want to do anyway.
*** Dangerous freedom vs comfortable slavery?
Would we rather live free but hard,
or would we rather be comfortable in an enslavement by a good master who can give us more than we could get in a free life?
/But how could this master have so much money to pay everybody in the first place?/
*** What is work without employment?
Work without subjugation.
Work without power asymmetry.

Work gives life meaning.
We like work and dislike employment.
We want a world in which we work because we want to, not because we have to.

What is work?
Work is purposeful deed/action.
The difference between work and leisure is teleological.
What is employment?

Life /is/ work.
Your work defines you.
You are only as good as your contribution to the world.
Your work defines the meaning of your life.

Don't confuse working with employment.
Work is everything that creates value.
Employment is subjugation.

- How does employment and slavery compare?

  - Slavery is the ownership of humans.
  - Employment is the rental of humans.
  - How has slavery changed?

    - Humans used to buy humans. Now humans rent other humans.

      - 2018: we can even rent a friend.

    - [[https://www.reddit.com/r/LateStageCapitalism/comments/68fkek/in_slavery_you_are_boughtin_capitalism_you_are/][r/LateStageCapitalism: In slavery, you are bought--in capitalism, you are rented]]
    - "Hiring" /is/ "renting".

      - You rent a car. The contract includes an insurance. You use the car for anything; just don't break it.
      - You hire an employee. The contract includes an insurance. You use the employee for anything; just don't break it.

    - [[http://www.differencebetween.net/business/difference-between-labor-and-human-capital/][differencebetween.net: labor and human capital]]
*** Work
**** Work vs employment
Work is purposeful deed.

Employment is subjugation.
**** Raising kids while working?
It is impractical to raise kids while working, but not while being employed.

My guess of division of labor in stone age:
Able men and childless women find food.
Women and old men raise children.

In stone age there are no 8-hour work days.
Men work only as much as needed to live that day.
The rest is free time: sleep, play, art, sex, rough-and-tumble, musing, thinking
*** Labor without hiring?
By hiring I mean employment/wage/salary.

I'm thinking about anarchistic labor, a form of voluntary labor that is not subject to labor laws.
Get paid by result not by time.
Work anywhere.
Resign anytime.
No non-competes, no non-disclosures, no grace periods.
Work on something ethical and meaningful.
** How did we get into this unholy combination of statism and capitalism, and what is so bad about it?
*** States make wars somewhat less often but much more severe
A war between two tribes kills about 100 people.
A war between two 11th-century kingdoms[fn::https://en.wikipedia.org/wiki/List_of_countries_by_population_in_1000] kills about 100,000 people.
A war between two 20th-century states kills about 1,000,000 people.
A war between two 20th-century state-alliances kills about 70,000,000 people.
A war between two planetary governments may kill billions of people.
This does not yet count the people hurt but not killed by the war.

Hypothesis: the expected damage of wars is constant.
A war between two kingdoms is 1,000 times less likely but 1,000 times more destructive than a war between two tribes.
For example, if a tribe went to war every day, then a kingdom would go to war every 3 years.
But Harrison and Wolf 2012 \cite{harrison2012frequency} falsifies that hypothesis.

States enable long-term peace with the risk of occasional catastrophic wars.

A catastrophe is too high a price to pay.

https://en.wikipedia.org/wiki/List_of_wars_by_death_toll

The frequency reduction is not because have become more peace-loving,
but because each war destroys more, so we take more time to recover for the next war.
*** A society with too many rights cannot progress
Copyright, patent, intellectual property.

We don't need copyright, patent, etc.
Inventors will still invent without patents.
They are intrinsically motivated.
* How do we prevent or preclude power centralization?
** Unite but don't unionize?
I asked[fn::https://twitter.com/ErikDominikus/status/1093175961867169793]:
Does collective bargaining require involving the government?
Why not direct action?
Can't people unite without unionizing, and gain power without principal-agent problem?

The slogan: /unite but don't unionize/; unity but not union.

What is the difference: unite, unify, unionize?
** Fixing the political system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-political-system
   :END:

- Restrict the form of all political campaigns to text containing the list of things the candidate wants to do.

  - Avoid pandering and toxic campaigns.

- Replace parliaments with sortition (randomly choosing people)?

  - TED: "What if we replaced politicians with randomly selected people? | Brett Hennig", [[https://www.youtube.com/watch?v=cUee1I69nFs][youtube]]
  - [[https://en.wikipedia.org/wiki/Sortition][WP:Sortition]]
  - Will sortition work in a homogeneous country?
    Won't it just promote groupthink?
  - How does sortition affect the minority?
    How should the population be sampled?
    Stratified sampling?

** Fixing the justice system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-justice-system
   :END:

- Change the justice system from retributive justice to restorative justice for the non-violent criminals.

  - Instead of locking up prisoners, let them repair the harm they did, and help them reintegrate into society.
  - Millions of people are being incarcerated.
    Their ability is being wasted.
    They are deprived of future.
    They will have difficulties reintegrating into society.
    Stigmatized.
    Like the homeless.
    This stigma makes it impossible for them to get financial stability and get out of the vicious circle of crime.

    - Also, prison initiation rituals are terrible.

  - There are two kinds of criminals:

    - /Perforce criminals/ commit crime to defend themselves from immediate bodily harm that threatens their existence.
      Examples are hungry moneyless people who steal food, and cornered people who kill.
      The solution is restorative justice, and giving work to the criminal for financial stability, helping them reintegrate into society.

      - If the threat is removed, perforce criminals no longer commit crime.

    - /Non-perforce criminals/ commit crime for anything else.
      Examples are psychopaths (people with physical inability to weigh bad consequences because their brains are wired differently).
      The solution is unbreeding: modify them by gene therapy or psychological therapy or whatever technology, or kill them if they can't change,
      but only after we have proven that they can't change.

      - See also [[https://www.theatlantic.com/magazine/archive/2017/06/when-your-child-is-a-psychopath/524502/][theatlantic.com: When your child is a psychopath]].

  - Prisons should not exist.
    There should exist only two kinds of punishment:

    - Forced labor, for perforce criminals, to repair the harm they did.
      The state must also help them reintegrate into society.
    - Death penalty, for non-perforce criminals.

  - In any case, nobody should be locked up for so long.
    Locking up people wastes resource.

** Should we limit inheritance?
   :PROPERTIES:
   :CUSTOM_ID: should-we-limit-inheritance
   :END:

https://taxfoundation.org/estate-and-inheritance-taxes-around-world/

Should we have any tax at all?

Should government funding be voluntary?

** A government is to maximize the well-being of its people
   :PROPERTIES:
   :CUSTOM_ID: a-government-is-to-maximize-the-well-being-of-its-people
   :END:

- A government is to:

  - do things that benefit many but do not benefit a few, such as building roads;
  - prevent things that benefit few but do not benefit many, such as committing crime.

- A government is to minimize negative [[https://en.wikipedia.org/wiki/Externality][externality]]
  and [[https://en.wikipedia.org/wiki/Rent-seeking][rent-seeking]].
- A government is to prevent the [[https://en.wikipedia.org/wiki/Tragedy_of_the_commons][tragedy of the commons]].

** Ungrouped content
   :PROPERTIES:
   :CUSTOM_ID: ungrouped-content
   :END:

A modern government is designed to minimize the damage if a bad person rises to the top,
not to maximize the benefit if a good person rises to the top.
That is why a republic has checks and balances.
The most efficient government is a benevolent competent dictator,
but does such person exist?

The government is a monopoly, and it should seek profit for its stakeholders: all its people.
Government official corruption, similar to corporate management corruption,
is a [[https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem][principal-agent problem]].
Everything that solves the principal-agent problem also solves corruption.

** Deciding what governments should do
   :PROPERTIES:
   :CUSTOM_ID: deciding-what-governments-should-do
   :END:

Use this quadrant:

- Axis 1: Does it benefit many people?
- Axis 2: Does it benefit a few people?

Things that benefit many and benefit few are best left to the private sector
with as little regulation as needed to keep the market healthy.

Things that benefit many but disadvantage few should be done by the public sector,
because the private sector will not do them because they don't get money doing that.
Example: building road.

Things that disadvantage many but benefit few should be prevented by the government.
Example: rent-seeking (bribing, lobbying,
speculation of non-fungible goods such as land parcels and Internet domain names),
crime, terrorism.

Things that disadvantage many and disadvantage few should also be discouraged by the government.
Example: road rage, human stupidity.

** Tips from our ancestors
   :PROPERTIES:
   :CUSTOM_ID: tips-from-our-ancestors
   :END:

I do not always agree with Lenin, but I agree with this sentence of his:

#+BEGIN_QUOTE
  When it is not immediately apparent which political or social groups,
  forces or alignments advocate certain proposals, measures, etc.,
  one should always ask: "Who stands to gain?"

  Vladimir Ilyich Ulyanov a.k.a. Lenin (1870--1924)
  ([[https://www.marxists.org/archive/lenin/works/1913/apr/11.htm][source]])
#+END_QUOTE

That was 1913.
In 1976 that could be more simply put as [[https://en.wikipedia.org/wiki/Follow_the_money][follow the money]].

** Ramble
   :PROPERTIES:
   :CUSTOM_ID: ramble
   :END:

- A government should only do things that better its people.

  - How do we know if something will make people better off?

- Is Chinese government dominated by scientists and engineers?

  - https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers

- https://www.quora.com/What-would-a-government-designed-by-engineers-and-not-politicians-look-like?share=1

  - https://tomgrego.blogspot.com/2010/12/a-government-you-can-love.html
  - https://www.quora.com/Concretely-what-can-we-do-to-get-US-politics-working-What's-gone-wrong-and-why-are-things-worse-than-20-years-ago-How-could-US-politics-improve-in-10-years-What-short-term-tactics-could-advance-the-long-term-goal?share=1

- The public sector is inefficient, but the private sector might be too efficient (extracting too much profit? but how much profit is too much?)?
  Is there a mixture between the two?
  Regulated private sector?
- https://en.wikipedia.org/wiki/Monopoly_on_violence

  - https://en.wikipedia.org/wiki/Justification_for_the_state

- https://www.bbc.com/news/uk-politics-42570823
- https://www.quora.com/Are-there-any-countries-without-government
- If healthcare were affordable, would we still need insurance?
- We don't need insurance.
  We need affordable healthcare.
- http://time.com/4937691/americans-cheap-healthcare-instantly/
- https://www.bloomberg.com/news/articles/2018-05-15/doctors-who-hate-insurance-so-much-they-go-without-it-themselves
- https://www.quora.com/What-do-doctors-think-about-insurance-companies
- What makes healthcare so expensive?

  - Definitely not the general practitioners (non-specialist doctors).
    They charge the patient only about $20 per visit.
  - Hospitals?
  - Drugs?
  - Insurances?

- argument for government, the necessity of government

  - https://www.quora.com/Why-have-so-few-humans-realized-that-governments-are-unnecessary

- https://en.wikipedia.org/wiki/Night-watchman_state
- If taxes were voluntary, would people pay tax?
- https://en.wikipedia.org/wiki/Voluntary_taxation

** The world should have only one country, one government, one law.
   :PROPERTIES:
   :CUSTOM_ID: the-world-should-have-only-one-country-one-government-one-law.
   :END:

Having many countries causes legal loopholes.

If there is only one country, there will be no tax tricks, tax havens.

There would be no illegal immigrants.
Everyone would be a world citizen.

- https://www.quora.com/Why-cant-all-the-earth-countries-unite-to-make-a-single-federation
** Design the world order
*** Develop non-shitty FOSS distributed/P2P alternatives to most vital services
Works behind NAT?
How can A and B connect to each other if A is behind NAT gateway G1 and B is behind NAT gateway G2?

Google search: no replacement yet!
YaCy is not good enough.
Can we make it in Prolog?

Distribute the result of manual curation?
Bundle a curation tool with a browser?
Privacy issues?

Facebook: Mastodon?

YouTube: DTube, BitChute
https://www.ghacks.net/2018/03/02/dtube-is-more-than-a-youtube-alternative/

Heroku?

"An Open Source, Self-Hosted Heroku"
https://news.ycombinator.com/item?id=12703121
https://www.bitmatica.com/blog/an-open-source-self-hosted-heroku/
"Internals of OpenRuko PaaS, an open source Heroku clone implementation"
https://www.slideshare.net/rogerleite14/paa-s-26212382
https://github.com/dokku/dokku
https://github.com/openruko
https://flynn.io/
https://www.quora.com/What-are-some-open-source-Heroku-alternatives

https://www.quora.com/What-are-some-open-source-Heroku-alternatives
*** Develop power-distributing technologies
*** Write a user-first browser in Prolog
**** 1h: Specify desired features and differences from mainstream browsers
Principle: the user should have maximum control.

It is not only a browser.
It is a tool for controlling your web experience.

- The browser is distributed/P2P.
- The browser comes with a search engine that searches your public history or your peers' public history, and distribute indexes to peers.
- Block all ads because advertising depends on making people addicted.
- Block all popups, no exception, no clickjacking.
- Block all "soft-popups" (displays).
- Run user script for certain websites.
- Block all cookies by default.
- Don't load JavaScript by default.
- Don't load images by default.
- Apply default CSS. Don't load CSS by default.
- Enable user-agent spoofing.
- For advanced users. No GUI to configure. Write Prolog code to configure the browser.
- Default to HTTPS when protocol is not given.
- No download manager. Tell the user to use wget, curl, or whatever.
- Like emacs but:
  - browser instead of text editor
  - prolog instead of emacs lisp
- Browser must limit memory usage.
  See entity explosion problem.
- Browser should refuse to load HTML documents larger than 1 MB.
- User can easily change user agent. WhatsApp wrong browser detection.
- combine with caching, peer-to-peer caching, distributed (and social?) searching and ranking and sharing, but what about privacy and the people who try to game the system?
- Don't remember tabs when closed.
Limit open tabs to 10. Discourage context-switching. I'm a pathological tab hoarder. Always open a configurable set of tabs on start. If you need to open more tabs, then open a google docs or a note-taking app instead.

- Write a fast, private, and secure web browser in Prolog.
  - Features:
    - Selectively enable JavaScript from some websites with Prolog rules.
    - Disable clipboard hook.
**** 1h: Skim existing browsers
Is this legit?
https://vivaldi.com

https://en.wikipedia.org/wiki/Comparison_of_web_browsers

https://www.quora.com/How-should-a-programmer-think-about-solving-problems-in-Prolog

Entity explosion problem:
#+BEGIN_EXAMPLE
<!ENTITY a "&a;">
<!ENTITY a <16 times a>
<!ENTITY b "&a;" <16 times>
<!ENTITY c "&b;" <16 times>
etc.
after 10 times we have 2^40 = 1 TB!
#+END_EXAMPLE

Example rendering rules: nag.html:
if website is pinterest then remove DOM element blah blah after load.

Popular open-source browsers are highly scrutinized.

not too related:
"prolog on the browser"
https://github.com/SWI-Prolog/roadmap/issues/43
**** Gui, logical/relational reactive programming, a layer on top of plgi (Prolog Gtk bindings).

exists W: window(W)
exists A: textbox(A)
value(A, yes) :- is_down(B), !.
value(A, no).
children(W,Cs) :- current_document(D), document_controls(D,Cs).
"The value of the textbox is yes whenever the button is down."
current_document/1 is a dynamic predicate.

name_widget(main,W) :- window(W), widget_width_height(W,640,480).

window(W) is true iff W is a window representation.
name_widget(N,W) is true iff N refers to widget representation W.


Example of some queries that we want a GUI knowledge base to answer:
- What is the width and height of the "main" window?
- What happens when button b1 is clicked?
- What has to be done to make this text box shows "yes"?

Example time-dependent facts that we want to state:
- After button b1 is pressed, then checkbox c1 is checked.
- If user clicks on a link, then navigate to the target of that link.
- latching?



gui(Root)


Layout algorithm
layout_one_line(Font, String, MaxWidth, Line, RemString)



Temporal logic for GUI
is_up(B) -> green(W)
is_down(B) -> red(W)


:- dynamic object_time_property_value/4
At every event, increment current_time

binding(W1, K1, V1, W2, K2, V2) :- ...


widget_value :- current_time, widget_version_value
force(widget_property_value(W,V)) :-
retractall(wtpv :- T >= Curtim, _), asserta((time_widget_value(T,W,V) :- T >= Curtim, !)).

Problem: slow gui update; recheck all widgets unnecessarily

http://www.swi-prolog.org/pldoc/man?predicate=initialization/2

array_array_concat(A, B, C) :-
    array_length(A, NA), ...
    NC is NA + NB,
   subarray_subarray_match(A, 0-NA, C, 0-NA),
    subarray_subarray_match(B, 0-NB, C, NA-NC).

Replace equal with match

*** Liberalism is the only way people can live together.
The only way to live together is to let people do everything they want as long as they don't harm other people.

Why do we care about consent?
Science advances faster without consent?

Why does the silver rule work?
The silver rule is "don't do unto others what you don't want to be done unto yourself".
*** Do we need government? Why do we need government?
https://en.wikipedia.org/wiki/Justification_for_the_state
"There is no single, universally accepted justification of the state."

*** Liberalism vs libertarianism
https://politics.stackexchange.com/questions/353/what-is-the-difference-between-liberalism-and-libertarianism

Dan (Steve's friend)'s question: "if I want to opt out of government services, should I be able to?"
"Even if his decision to opt out was poor – if he’d be better off by using the services – I couldn’t justify /forcing/ him to pay for something he didn’t want"
http://steve-patterson.com/conservative-anarchist/
*** The problem with libertarianism: the libertarian children problem: why do we prevent children from harming themselves?
Thesis: We should let someone do whatever he/she wants to do as long as he/she doesn't harm others, even if it makes him/her personally worse off.

Now the problem.

Why shouldn't parents let children do what children want as long as children don't harm others?
Why do we let an adult smoke cigarette, but we don't let a child smoke cigarette?
Why should we prevent children from touching wall sockets, drinking bleaches, and doing other dangerous things?
Why should we prevent children from harming themselves?
Libertarians are forced to conclude that children aren't people.
This conclusion is not inherently bad.
We can also define peopleness as a continuum (children are 50% people, for example).

Why should we vaccinate children?

https://www.quora.com/Libertarianism-When-do-children-own-themselves-if-at-all

However, an antinatalist libertarian wouldn't have this problem, because having children would be immoral in the first place.

https://www.reddit.com/r/antinatalism/comments/6356ym/shouldnt_libertarians_be_anti_natalist/

Our language implies that children aren't people.
- We use the pronoun "it" to refer to a child.
- Casualty count (death toll) is categorized into "men", "women", and "children".
- We sometimes use the phrase "men, women, and children".

The problem is in the language.
"Person" is not a binary concept; it's a continuum.
A child may be 20% personlike.
The more personlike something is, the more we should treat it as a person.
*** Some problems with free market
- What prevent environment destruction?
  System for internalizing the negative externalities back into the companies, such as carbon credit.
- What prevents private military company from being corrupt or being bought by someone with lots of money but nefarious intents?

*** Maximize individual freedom while minimizing harm to others

Every man, when left alone, does something he does best.
One person plants trees.
Another person murders people.
It follows that unlimited freedom is bad;
murderers should not be free to murder.

How much individual freedom is desirable?

*** Presumption of innocence

- https://en.wikipedia.org/wiki/Presumption_of_innocence
- https://en.wikipedia.org/wiki/Blackstone%27s_formulation

*** Sex and gender
Stop political correctness
https://www.yegor256.com/2018/11/13/bigotry.html

Political correctness kills

Women Can Now Join The SAS : UK Promptly Collapses
https://www.youtube.com/watch?v=piZRqOCOwP4

You can get as angry as you want, but it will not change the fact that sexual differences exist.

https://en.wikipedia.org/wiki/Gender-equality_paradox

John Stossel - Gender Confusion
https://www.youtube.com/watch?v=pTEPr4n_skI

On average, do men drive cars faster than women do?
**** What is a male? What is a female? What really makes a male a male and a female a female?
Is it the sex organ?
Is it the hormones?
It is the appearance?

Male and female are objective sexual classifications.
Man and woman are subjective gender classifications.
If sex and gender are orthogonal, then what is a "male woman"!?

- https://en.wikipedia.org/wiki/Trans_woman
  - A trans woman "is a woman who was assigned male at birth".
    The keywords are /assigned/ and /at birth/.

People in Stone Age may assume that someone's sex is determined at birth and doesn't change.
Back then, there were no sex reassignment surgeries.

Social-culture-language aspects:
Why is "girly man" an insult?

*** How do we scale democracy?
**** How do we make elections cheap, easy, trustworthy (independently verifiable), and scalable?
Paper ballots can be independently verified.
Machines can't.

Trustworthiness requires that the system can be independently verified (by a third party, by a non-government organization, by local people, by anyone who cares).

How can we ensure verifiability while maintaining secrecy?

Every citizen has a private key?

Rachel Tobac:
"At @defcon hacking conference and just learned how easy it is to physically gain admin access on a voting machine that is used in 18 states.
Requires no tools and takes under 2 minutes.
I’m concerned for our upcoming elections."
https://twitter.com/RachelTobac/status/1028437783050776576

https://arstechnica.com/information-technology/2018/09/e-voting-researchers-warn-of-hack-that-could-flip-the-electoral-college/

*** My fundamental assumptions when designing a social system
- Everyone wants to survive.
- Good people (people who enjoy helping others) exist.
- Evil people (people who enjoy harming others) exist.
- There are people who don't care about others.
- People do what they do best when left alone. Inventors gonna invent. Murderers gonna kill. Rapists gonna rape.

But privatization has its dangers too.
BP's strings of accidents after its privatization.

Basic negotiation theory: more need means lower bargaining power.
Buyers fare better if sellers compete.
Sellers fare better if buyers compete.

John Stossel - Privatize Everything (2013)
https://www.youtube.com/watch?v=toYoXf7EHwc

John Stossel - The Parasite Economy
https://www.youtube.com/watch?v=f2vt8e5RjQ0

#+BEGIN_QUOTE
While in government hands, British Petroleum paid too little attention to profitability,
constrained by its need to please elected officials who often cared more about keeping energy cheap and employment high.
But in private hands, it may have cared about profits far too much, at the expense of other objectives.
“BP veered from being a company that made sure nothing blew up to one focusing on cost-cutting at all costs,” Professor Fisman said.
https://www.nytimes.com/2013/01/16/business/when-privatization-works-and-why-it-doesnt-always.html
#+END_QUOTE
*** Industries whose profit is proportional to the destruction of the human race
- advertising, drugs, gaming, every business that profits from making humans addicted
- finance, investing, land speculation, and every business that does not create value

The advertising industry and the game industry are evil because they addict people in order to profit.

The advertising business model also causes recent extremisms.
http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html
*** How do we create an economy with zero rent?
*** Ethics, morality, politics, fairness?
Ethics vs morality: what is the difference?

ethical vs moral

unethical vs immoral

amoral vs immoral

fair vs just; fairness vs justice

"Fair" means "beautiful", not "just".
https://en.wiktionary.org/wiki/fair

Fairness is absence of resentment.

We can't fairly divide one indivisible thing for two people who want it.

Resentment is "bitter indignation at having been treated unfairly".
https://en.oxforddictionaries.com/definition/resentment

How does perception of unfairness arise?

Fairness does not exist objectively.

- Suppose that we have a running contest, and you beat me.
  How do I know that you beat me /fairly/?
  - Good genetics is an advantage, but is it a fair advantage?
  - If we can't control it, can it be unfair?
  - Is it fair for children to be born in families with different socioeconomic status?
  - If equality of outcome is absurd, then what is fairness?
  - Is equality of opportunity fair?
    - Opportunity to do what?
      Opportunity to become what?
    - Equality of /all/ opportunity?
      - Opportunity to be boss/capitalist/rich?
** The economic system
*** What is "economy"?
What is "economy"?
What is "economy" in "economic meltdown"?

Exchange?
Trade?

Satisfy maximum wants using minimum resources.
There are two solutions:
- Reduce wants.
- Use more resources.

Economics is easy to explain but hard to predict.
Economics is too interconnected.

Demand/consumption is easy; supply/production is hard.

/Demand is easy./
We can want anything.
Changing our minds is free.

/Supply is hard./
We have to work to satisfy our demands.

Consumption is easy.
Production is hard.
Destruction is easy.
Creation is hard.
Second law of thermodynamics: The entropy of the Universe never decreases.
In nature, entropy never decreases.
Disorder arises naturally.
The second law of thermodynamics explains why consumption is easier than production.

The nature of economics is that demand is free, but supply is costly..
Changing demand is cheap: you just change your mind.
Changing supply is costly: all the infrastructure that has been built won't simply turn back into cash.

Demand first or supply first?
Human nature is the root cause of economic demands.
There will always be demand for food and shelter.
There is always demand to make life easier and less boring.

However, in the case of iPhone, we have two views:
- Steve Jobs's presentation causes people to want iPhones. Supply creates demand.
- People always want an easier way to live. Steve Jobs's iPhone just happens to make people's lives easier.

For example:
We want an easier way to live.
People don't want iPhones for iPhones's sake.
People want iPhones because people believe iPhones make people's lives easier.

If demand surges, it will collapse later.
Example: tulip mania.
*** What economic system is desirable?
Characteristics:
- Distributed.
  Cannot centralize power.
  Cannot be controlled by government.
- Cooperative.
  Competition is a massive waste of human labor.
  Competitors reinvent each other's wheels all the time.
  The solution to competition is not competition laws.
  The solution is cooperation.
- Productive instead of consumptive.
- Antifragile (Taleb).

Is it possible to create an economic system that does not incentivize cheating?

What is the relationship between liberalism, competition, and cooperation?

Economic that is not focused on consumption?

Economic growth usually means consumption growth.

The easiest way to increase GDP is to increase consumption, environment be damned.

Why would we produce anything that nobody will consume?
*** Economic recession
Economic recession is the reduction of money flow velocity.

How do we predict recession?
How do we measure and monitor money flow velocity?
- people savings balance
- mass layoffs
- mass price hikes for vital goods (oil?)
- company profit/loss statements
- money accumulates at few economic actors

Technology introduction, demand shift among substitute goods:

A demand shift is a demand collapse and a demand surge.

Cheaper robotic workers (or increasing minimum wages) causes demand for human workers to collapse and demand for robotic workers to surge.

Demand shifts among substitute goods.
*** Fluid dynamics explains economic recessions
Economic recession happens because money flow slows down.

Money is a fluid.
A fluid flows.
Fluid flow velocity depends on pressure at the source and resistances in the path.

If we want to maintain flow velocity despite increasing resistance, we have to increase pressure at the source of the fluid flow.
But do we want this?

Money flow slows down because people spend less.

People spend less because they have less discretionary income.

People have less discretionary income because they are fired, or governments raise taxes, or important things get more expensive, etc.

Assumption:
A person's behavior changes slowly, if it changes at all.
A person who has never cared about the environment will not suddenly care about the environment.

A recession has two possible direct causes: /demand collapse/ or /supply collapse/.

Examples of supply collapse:
- Mine collapse, oil rig explosion, etc.
- Disasters: fire, earthquake, tsunami, flood, volcanic eruption, etc..
- Lots of people going out of workforce at once (into pension, dying in war, etc.).
- Lots of people suddenly becoming conscious (Google workers demonstrating for transparency, etc.).

Examples of demand collapse:
- Bitcoin ran out of fools (greater fool theory).
- Renewable energy sources reduce oil demand.
- Young people adopt a minimalist lifestyle after realizing that consumerism is unsustainable.
- Government increases minimum wage big enough to make switching to robots looks cheap.
  Lots of companies introduce robot workers at the same time, making human workers redundant.

Supply collapse is caused by physical destruction.
Demand collapse is self-inflicted human condition.

Consumers supply demands to producers.
Consumers demand supplies from producers.
Take and give.
To demand is to take, to consume, to destroy.
To supply is to give, to produce, to create.

What does inverted yield curve has to do with recession?
What does time preference have to do with economic recession?
What is an economic recession?

CAGR = compound annualized growth rate.

What is the yield of a bond?
A bond's yield is the CAGR of the bond price.

What is the yield curve?
The yield curve is the curve in a plot with two axes: the horizontal axis is tenor (duration to maturity), and the vertical axis is yield.

An inverted yield curve indicates that buyers are pessimistic about the bond's future?
*** Currency? Free banking? Digital fiat currencies?
Piggyback nascent fintech/e-cash/e-money startups?
BTPN Jenius?

https://openbazaar.org/blog/trust-is-risk-a-decentralized-trust-system/
Currency requires trust.
Debt requires trust.
Transaction requires trust.
Business requires trust.
What is trust?

A trustworthy person refrains from exploiting vulnerabilities.
Trust is the assumption that the other party refrains from exploitation.
Trust is the assumption of the absence of betrayal.
Betrayal is the exploitation of trust.
(Problem: Circular definition.)

*** Economic crisis is discontent due to reduction of purchasing power.
A /crisis/ is a mass discontent.

An /economic crisis/ is a mass discontent due to mass reduction of purchasing power.

"A financial crisis is any of a broad variety of situations in which some financial assets suddenly lose a large part of their nominal value."
https://en.wikipedia.org/wiki/Financial_crisis

- High firing rate, high unemployment, unemployed people having genuine difficulty finding jobs, employers not willing to employ
- Greatly reduced demand (discretionary spending)
- Reduced purchasing power

Deposits should not be guaranteed.
Banks should not lend.
Banks can take fees.
The job of banks is to clear transactions.
Banks exist so that people can transact without physically bringing large amount of cash to the place of transaction.
Banks should strive to minimize transaction cost.
The job of banks is not to lend.
That is the job of credit unions.
Banks should not double as creditors.

What is a bank, in anarchy?
*** Economics of open-source
https://en.wikipedia.org/wiki/Open-source_economics

Where do we draw the line between open core and crippleware?
- https://en.wikipedia.org/wiki/Open-core_model
- https://en.wikipedia.org/wiki/Crippleware

Is "open core" just an euphemism of "crippleware"?

If the open core is actually useful, then it isn't crippleware.
http://blogs.collab.net/subversion/enough-of-this-open-core-confusion

Marginal cost is the change in opportunity cost due to increasing production quantity by one.
https://en.wikipedia.org/wiki/Marginal_cost
*** Abolish corporations?
Limiting liability creates moral hazard.
But what is the alternative?

Corporation is a legal fiction.

Corporation (and insurance) enables people to act with impunity.

People would be more ethical if they have more skin in the game.

Before we abolish corporations, we must abolish frivolous lawsuits:
- "I'm not a fan of corporations, but the amount of frivolous lawsuits in the us make it desirable."
  https://www.reddit.com/r/CapitalismVSocialism/comments/46ljlf/capitalism_without_corporations/
** What is the ideal society?
*** Principles?
The best thing for a person to do is what he/she /voluntarily/ does?

But:
- Most people don't know what they want?
- Most people don't think for themselves?
- Do most people even think?
*** Institutions?
What is an institution?
Government bodies?
Governing bodies?

Do we need institutions?

Why do we lose trust in institutions?

Institutions enable people to hide.
Institutions enable people to abuse power without being held responsible.
Institutions deflect blame from people to an abstract entity.
Institutions separate the powerful from the coerced.
People should be responsible.
Instutitions cannot be responsible.

Bureaucrats cannot see reality from their desks alone.
*** Capitalism has nothing to do with free trade?
Capitalism is simply the private ownership of the means of production.

Capitalism places capital above labor.
Nature places labor above capital:
Someone somewhere eventually has to /actually do/ something in order to produce something.
/Labor is more important than capital./
Capitalism goes against nature?
Capital without labor will not produce anything.
Labor without capital is merely inefficiently allocated.

Capitalism (market?) is a voting about what we should use labor for?
*** What seems to be the most ideal society so far?
The most ideal society so far seems to be John Rawls's ideal society (based on his theory of social justice and veil of ignorance)
 [fn::https://en.wikipedia.org/wiki/A_Theory_of_Justice].
What are the problems?

Other people's ideas
https://www.quora.com/What-is-an-ideal-society-like

Practical utopia book?

Protopia is "incremental progress in steps toward /improvement/".
https://aeon.co/ideas/utopia-is-a-dangerous-ideal-we-should-aim-for-protopia

Every man has his own wants.

A voluntary trade betters all parties.
But why stop at trade?
A voluntary life betters the person.

The ideal society maximizes individual freedom while minimizing harm to the species.
Maximizes volition, the will to live.
Everyone fearlessly does what they love most.
Nobody slaves away at the office.

Occasional inconsequential broken small promises are okay.
People change.
People are sometimes too optimistic.

Things that don't belong in an ideal society?
- politicians
- lawsuits
- wars, refugees
- megacorporations, offices, employment
- religions
** Arguments for anarchy
The "An Anarchist FAQ" series[fn::https://theanarchistlibrary.org/category/author/the-anarchist-faq-editorial-collective] is too long.
*** Families are communists
We share resources with our family.
Every family is a communist micro-society.
*** Argument for more communism?
Highlights of "The Role of Luck in Life Success Is Far Greater Than We Realized"
 [fn::https://blogs.scientificamerican.com/beautiful-minds/the-role-of-luck-in-life-success-is-far-greater-than-we-realized/]:
- "They defined /talent/ as whatever set of personal characteristics allow a person to /exploit lucky opportunities/" (emphasis mine)
- "1.7 million dollars to properly /determine the extent of serendipity in science/." (emphasis mine)
- 'This last finding is intriguing because it is consistent with other research suggesting that
  /in complex social and economic contexts where chance is likely to play a role,
  strategies that incorporate randomness can perform better than strategies based on the "naively meritocratic" approach/.' (emphasis mine)
- "With that said, the /best/ funding strategy of them all was one where an equal number of funding was distributed to everyone."
*** Anarchy is the only way to delay our extinction?
It is absurd to centralize power to a few people who are prone to the same mistakes that we are prone to.
** Arguments against anarchy
*** But how do we launch rockets without power centralization, without states and companies?
Or build nuclear power plants, or do trillion-dollar engineering projects?
*** Problems with anarchy?
**** Without ownership, who will build buildings?
** Avoiding extinction
There are two ways for humans to avoid extinction: a political way and a biological way.
The political way is to create a political system that does not depend on human benevolence.
The biological way is to technologically alter the nature of humans.
The political way is much simpler.
** Preventing subversion with religion, and maintaining social cohesion
Yuri Bezmenov: Psychological Warfare Subversion & Control of Western Society (Complete)[fn::https://www.youtube.com/watch?v=5gnpCqsXE8g]:
- four stages of subversion: demoralization, destabilization, crisis, normalization
- Workers must negotiate directly, not through trade unions.
- It is much cheaper to prevent subversion than to fix it.
- Beware of non-elected committees.
- Religion keeps social cohesion.
* Basic politics
** Hobbes?
Hobbes[fn::https://www.iep.utm.edu/hobmoral/],
political philosophy[fn::https://www.iep.utm.edu/polphil/]

Hobbes vs Locke?

There is some good in humans.
For example, I believe that most people will not kill people for fun out of boredom.
Or am I wrong?
Does the existence of gladiators disprove my belief?
** What is human nature?
If we did not have to do anything, what would we rather do?

https://www.humansandnature.org/humans-nature-and-ethics

Every human has wants.

Freedom?

Avoidance of boredom?
Pain?
Schopenhauer?
 [fn::https://www.iep.utm.edu/boredom/#SH3a]
 [fn::https://biblioklept.org/2014/01/04/pain-and-boredom-schopenhauer/]

A life is a thing that has different wants.

The essence of life is to have changing wants.
Fickleness is the essence of life.
*** Greed, envy
Greed is endless wanting.
Greed is feeling insufficient.

Envy is wanting what others have.

Why do we envy?
Why do we want what others have?

Why do we want things that do not make us happy?
*** Why do we want?
To sustain life.
Example: we want to breathe, eat, drink, excrete, etc.
** Political theory/research
*** Why do politicians diverge from their constituents' preferences?
https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences
*** <2018-10-02> We don't want completely free-and-global trade because we don't want to depend too much to others.
**** Independence is necessary but not sufficient for sovereignty.
By depending on someone, you give him power over.
You weaken your bargaining power.
You worsen your negotiating position.
You reduce your sovereignty.

We must start strategic domestic industries, no matter how shitty it will be.
We can always improve it later.

<2018-10-03>
*** Cipolla's laws of stupidity
- https://en.wikipedia.org/wiki/Carlo_M._Cipolla
- Cipolla's definition of "stupid":
  "A stupid person is a person who causes losses to another person or to a group of persons while himself deriving no gain and even possibly incurring losses."
*** Why are the Norwegians so sensible? Why are their governments so good?
[[https://www.youtube.com/watch?v=b_l3eLhYbVo][Why The UK Lost Its Oil Wealth (And Why Norway Didn't) - YouTube]]

Every country has smart people.
Smart people are everywhere.
Why do countries fare differently?
** State, nation, country
*** Politics basics: What is the difference between nation, state, country?
https://tamayaosbc.wordpress.com/2010/11/19/basic-concepts-in-politics/
*** What is a state?
States are abstract.
People are concrete.
*** How does a state comes into existence and stays in existence?
The founders of a state understand power dynamics.
Their children do not.

A state comes into existence by the deliberation of its founders and persists through time by the ignorance of their citizens.
** Natural state?
If people do not have to do anything, they do what they want to do.
Some think; some sing; some exercise; some kill.

Hobbes?

Stable anarchy requires social contract: no one shall be the first to aggress.
Peace treaty
Honor code
Families have stronger bonds than tribes.

Government vs state

Hobbes argues ...
State of nature
government is necessary

Read hobbes leviathan directly

We must not assume that everyone is good.

Axiom: bad people always beat good people.

Suppose that a society consists of 1,000,000 good people and 1 bad person.
How do we design the society so that the bad people do not harm others?
How differently would we design our society if there were more bad people than good people?

An animal kills only when it is hungry or threatened.
A lion with full stomach does not kill a deer.
An animal does not kill more than it eats.
A lion does not kill two deers if eating one deer suffices to fill up its stomach.
The surviving deers do not hold grudges against the lions.
The deers do not plot a retaliatory genocide of the lions.

But the more intelligent animals do hold grudges.

A human may kill for fun out of boredom, or out of envy, or other excuses.

It seems that animals are more moral than humans.

Intelligence breeds immorality?

Hobbes makes a strong argument against anarchy.

Hobbes is right about the natural state of humans.
People, even some Westerners, did join ISIS.
* Unanswered questions
** How should we live in the 21st century?
We dream of a self-sufficient global sustainable anarchistic society where people freely do what they really want without harming others, where power is distributed.
But this dream may change.
We are trying to understand what anarchy is, and we disagree with some anarchists.
A state has good and bad things.
The question is: What is the price of having states, and is it too high a price to pay?
** What is the moral system that we have evolved?
I am trying to codify (that is, to express in English) our implicit morality, that is, the implicit moral system that we have evolved.
Thus I write [[file:social.html][Designing the ideal society]].

What is our natural morality (the moral system built into us by evolution)?
Avoid harm?
** What is the difference between unethical and immoral?
What
 [fn::https://www.quora.com/What-makes-something-immoral-but-not-unethical]
 [fn::https://en.wikipedia.org/wiki/Heinz_dilemma]
 [fn::https://en.wiktionary.org/wiki/ethics#Usage_notes]
** What is the relationship between cooperatives and anarcho-syndicalism?
** Senior, lead, manager, director
Etymology clears up the differences.

Senior = older.[fn::https://www.etymonline.com/word/senior]

Lead = to show the way.[fn::https://www.etymonline.com/word/lead#etymonline_v_6615]

Manage = handle or train a horse.[fn::https://www.etymonline.com/search?q=manage]

Handle = "touch with the hands, hold in the hands, fondle, pet"[fn::https://www.etymonline.com/word/handle]

A director /directs/.
Directors knows what they want.
** Why should everyone know some basic epistemology?
If people know some basic epistemology (that is, if they can tell apart what they know from what /they think/ they know), then there will be no wars.
Some epistemology should be taught in primary school.
We often assume a lot of things about others.
Most conflicts happen because we assume something wrong about someone else.
** What does "X deserves Y" mean?
Does anyone deserve to be rich?
Does anyone deserve to be poor?
Does anyone deserve kindness?
Does anyone deserve inheritance?
** How should we be altruists?
If you want to be an altruist, pick activities with high impact-to-effort ratio[fn::https://www.effectivealtruism.org/articles/introduction-to-effective-altruism/].
Find a high-social-impact job suitable for you.[fn::https://80000hours.org/career-quiz/#/]
 [fn::How to find the world's most pressing problems https://80000hours.org/career-guide/most-pressing-problems/]
 [fn::The evidence on how to find the right career for you https://80000hours.org/career-guide/personal-fit/]
 [fn::Evidence-based advice on how to be successful in any job https://80000hours.org/career-guide/how-to-be-successful/]
 [fn::What are the 10 most harmful jobs? https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/]
 [fn::https://hackernoon.com/where-are-the-programmers-who-give-a-shit-87f859f13f75]
** Will we survive the 21st century?
I am [[file:world.html][somewhat pessimistic about the 21st century]].
** What is competent and dangerous?
Jordan Peterson: responsibility gives life meaning[fn::be competent and dangerous https://www.youtube.com/watch?v=ONK8pGAGT28].
** Procreation is not survival?
To survive is to keep/continue living.

Survival of the individual vs survival of the species?

Survivalism is compatible with antinatalism.

** What is fairness? How to divide a thing fairly?
https://en.wikipedia.org/wiki/Fair_division

From Wikipedia "Divide and choose"[fn::https://en.wikipedia.org/w/index.php?title=Divide_and_choose&oldid=853199297]
- "envy-free cake-cutting"
- "To an external viewer, the division might seem unfair, but to the two involved partners, the division is fair - no partner envies the other."

Thus, is fairness the absence of envy?
** What
Even if we didn't have states, we would still have laws.

Laws should be principles, not rules.
* Does not belong here
** Is there an Indonesian etymology dictionary?
I am looking for an Indonesian etymology dictionary, which I think is necessary for philosophical analysis of Indonesian laws.
** Lying
*** Statistics makes bullshit appear legitimate
In 2019, by refuting a bullshit in Gamal Albinsaid's Twitter account,
Ainun Najib demonstrates[fn::https://twitter.com/ainunnajib/status/1082185571559124992][fn::https://www.facebook.com/joko.trikukuh/posts/10161376605960541]
Brandolini's bullshit asymmetry principle[fn::https://twitter.com/ziobrando/status/289635060758507521]:
"the amount of energy needed to refute bullshit is an order of magnitude bigger than to produce it".

One does not have to understand statistics in order to be able to bullshit with statistics.

Most people (including myself) don't understand statistics.

Every time I see an article with statistics,
I suspect that the author has not done sufficient philosophical analysis.

We do not have to refute the entire bullshit.
We only have to point out a fatal flaw, such as a truncated graph,
and cause readers to doubt the writer's intention.

A bullshit contains the necessary ingredient to refute itself.
A bullshit has an inherent flaw that we can point out without referring to anything outside the bullshit.
We just have to point it out.
"This is a truncated graph. You are lying."
*** Levels of lying?
Level 0: obvious lie, obviously nonsensical, takes no effort to refute.
Example: a child who broke a vase.

Level 1: sophisticated story, but no data.

Level 2: using true data, but selecting only the data that matches your agenda.

Level 3: level 2 plus fancy graphics, numbers, tables, statistics, truncated graphs[fn::https://en.wikipedia.org/wiki/Misleading_graph],
and damn lies[fn::https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics].

Level 4: level 3 plus creating your own pseudo-philosophy.

Level 5: post-truth politics: inventing your own facts.

** Designing a lovable government?
*** Purpose

The highest law is the will of the people.
The people can change the constitution.

|                         | benefits few    | does not benefit few      |
| benefits many           | good business   | road-building             |
| does not benefit many   | crime           | self-defeating behavior   |
#+CAPTION: Examples of actions according to beneficiaries

Economically, government is to maximize positive externality,
and minimize negative externality.

Example negative externality:
road congestion due to residential space transforming to commercial space.

*** Policy

Do the simplest intervention with the least effort,
the greatest effect, the least gameability,
the least unintended consequences.
But those are conflicting requirements.

Example: even-odd license plate based on day of month.
People will game this by buying two license plates or buying two vehicles.

Avoid wasting resources on policies that
do not attack the root cause of the problem.

*** Murder

Why is something illegal?
Perpetrators are going to perpetrate anyway,
and non-perpetrators are not going to perpetrate,
regardless of its illegality.

Some people commit crime unwillingly because they
want to continue living but they no see other way.
Some people are wired differently and commit crime like a pastime.

If something is illegal, why does a perpetrator still do it?
Is it futile to make anything illegal?
If it were not illegal, will it still be done?

Law cannot change human nature.
If you want to change human nature, study biology, not law.
Lawmaking must defer to human nature.

It is impossible to enforce a law if millions of people violate it at the same time.
If a law is against human nature, of course people will violate it.

Is it moral to force someone who enjoy murder not to murder?

*** Morality

Government should not interfere in private matter
such as religion, insurance, and consensual sex.

If something does not harm anyone else other than the doer,
it should not be illegal.

We should help others,
but we should to the greatest extent avoid forcing
others to do anything against their will
even though doing that would be good for them.
Consequence: procreation is immoral because
it forces people to exist without their consent.

We can persuade, but we should not force, unless we are in war.

Consumption should be taxed, not income.

Alternative to taxation: donation, state-owned enterprise.

Stability.

In a republic, in an election, you don't pick the best candidate;
you pick the one that will do the least damage.

Holding a government position should not be profitable.
How do we prevent abuse of power?
By not giving power in the first place?
The people must have the final say.

*** Banning

Banning something does not eliminate it.
Worse, banning it may also create a black market for it.

Regulate, don't ban.

*** Sex

Blocking access to Internet porn sites does not work.

Banning prostitution creates black market.

Banning sex makes more people more curious.

It's part of human nature.

Family education.

*** Drugs

Some people are curious.

*** Patents

Alternative to patents:
Prize system:
People collect money for a problem,
and the sum is awarded to the inventors who solve the problem.

Another alternative: People can donate to inventors.

Another alternative: Assume that inventors do things
because they love to do that, and they want money, but don't want to get filthy rich.

How was the first people who invented spears rewarded,
if they were rewarded at all?

*** Prevention of mass destruction

How does a government prevent
nuclear briefcase detonation,
water source poisoning,
asteroids hitting Earth,
and so on?

The amount of security is inversely proportional to the amount of trust.
If you could trust everybody, security would be unnecessary.
Republics are complicated because you can't trust the ruler.
Republics are designed to minimize the damage done by an evil ruler,
not to maximize the benefit done by a competent ruler.

The most efficient government is
benevolent competent kind laissez-faire minimalist absolute monarch,
but it is also the most risky.
Anything can happen if the ruler dies.

*** Differences

Conventional government assumes that most humans are fundamentally evil.
New government assumes that most humans are fundamentally non-evil.

*** Office

If you tell people to do something they don't want,
they will do their best to avoid it.
If they want to do it,
they will do it anyway without your telling them.
Thus, you don't tell people.
You simply let them do things,
help them do things,
get out of their way.

If you hire the people who don't want to do the things you want,
no amount of salary will fix it.
When you hire people, there is an intersection between what they want,
what you want, and what your organization wants.

In the office, there are so many things happening that it is too much
for one person to keep track what everyone else is doing.
You are the only person who knows what you really do.
Your supervisor, if any, is the second person to know what you do.
Others have even vaguer ideas about what you do.
But people can instinctively see whether you're doing well or not,
so if you're not doing well,
you must pretend that you were doing well,
and then suddenly you will do well.
If you think you're not doing well, if you doubt yourself,
then it will be a self-fulfilling prophecy.
Even if you are absolutely sure that your job is unimportant,
even if you keep stumbling,
you must unquestioningly believe that you are doing well.

In the office, what you do is less important
than what others think you do.

If you don't know what to do, walk around, and talk to people.

If you don't fit in one company,
maybe that's the company's fault.
But if you have tried three much-different companies
and still can't fit, maybe it's your fault.

Make friends.
People first.
Jobs second.

The number of processes is inversely proportional to the amount of trust.

How much trust are you convenient with?

There are people you naturally gravitate towards,
and people you naturally gravitate away from.
** Evil automobile industry?
https://www.reddit.com/r/todayilearned/comments/9mv3oi/til_that_the_term_and_concept_of_jaywalking_was/
** Government is a trillion-dollar Ponzi scheme?
"John Stossel - Government's Ponzi Scheme"[fn::https://www.youtube.com/watch?v=iNVXaeX4JK8]
** Insurance is gambling; the proof is in the house advantage
Both insurance companies and casinos have /house advantage/; otherwise they go bankrupt.
The bets are tilted in their favor.
** Let's slim down the morbidly obese government
*** What
Medicaid insanity
https://www.reddit.com/r/MaliciousCompliance/comments/90q9m3/i_dont_work_here_anymorehey_boss_got_an_opening/

"I recommend seeing which movie best predicts */future/* scenes."
https://blog.dilbert.com/2018/06/10/why-democrats-hear-a-secret-racist-dog-whistle-and-republicans-dont/

Is this related?
https://blog.dilbert.com/2018/05/04/why-president-trump-deserves-credit-for-progress-in-north-korea/

Blackwater and Erik Prince do mostly GOOD
https://www.youtube.com/watch?v=GOeFKiTP9A0

It's true.
PMCs can be corrupt in the same way that governments can be corrupt.
But a corrupt PMC of 100 people is much less dangerous than a corrupt government of 100,000 people?

"Leaving the Left"
https://www.youtube.com/watch?v=kl0-n0zWVJk

The Left's War on Science
https://www.youtube.com/watch?v=OX8kEjSUr04

Gray Grumbler: "As a retired scientist, both extremes are problematic to science.
The right doesn't stop science but often ignores good science.
The left stifles science they are against and often puts forward junk as science.
And this junk discredits the good science.
I am completely displeased with both sides.﻿"

Admit it. Republicans have broken politics.
https://www.youtube.com/watch?v=mICxKmCjF-4

2004 article "Government: Unnecessary but Inevitable"
http://www.independent.org/publications/tir/article.asp?id=15

The only thing we need from government is protection from physical harm.
But only you can protect yourself?

We have to prevent concentration of power.
Government is concentration of power.
But would we rather arm all people, and have a tribal war, instead of oppression?
But would we have a tribal war?
Haven't we evolved to cooperate?

Even right people avoid the cops.

America’s Parasite Lawyers Deprive Us of Good Things
https://www.youtube.com/watch?v=gTQtVsggZXY

Freeloaders: The Wealthy
https://www.youtube.com/watch?v=DsTKAqHwj0s
We can always depend on the government to make bad rules. How do we profit from bad rules?

The Cayman Islands is not a tax haven. We need less rules, not more rules.
https://www.youtube.com/watch?v=bI7W65k-LPM

Fox News is fake news.
https://amp.cnn.com/cnn/2018/10/29/media/pittsburgh-suspect-invasion/index.html

"Leftist Protesters Get Perfectly Checkmated"
play the victim forever
https://www.youtube.com/watch?v=2NAKH8jdgm8

Dinesh D'Souza?
"it's not Trump that created the division, the division created him"?
https://www.youtube.com/watch?v=jhu7ZjeEO2s
I don't want to be associated with this guy, but does he speak the truth? https://en.wikipedia.org/wiki/Dinesh_D%27Souza

Cigarette smoking

I first got this from Judea Pearl's book of why.
https://tobaccocontrol.bmj.com/content/11/suppl_1/i110

Government problems:
- Wastefulness
- Perverse incentive
#+BEGIN_QUOTE
In two 1954 speeches made by Philip Morris vice president George Weissman, he promised: “[I]f we had any thought or knowledge that in any way we were selling a product harmful to consumers, we would stop business tomorrow.”
#+END_QUOTE
- https://truthinitiative.org/news/philip-morris-announcement-spend-nearly-1-billion-end-smoking-sounds-fake-news
- https://www.unfairtobacco.org/en/pressrelease-quitpmi/

The Inconvenient Truth About the Republican Party
https://www.youtube.com/watch?v=OURy5WFp0zk
Historically it is the Democrats that is sexist and racist. It still is.

Minimum wage hurts the very people it is supposed to protect. The proof is clear. The reason is clear.

The $15 Minimum Wage Is Turning Hard Workers Into Black Market Lawbreakers
https://www.youtube.com/watch?v=0fsVI3EmUnQ
Everyone loses. Workers lose. Business owners lose. Customers lose; reduced competition. Government actively harms everybody. Government is unethical.

Government is a preventable disease?

Who Are the Most Powerful People in America?
bureaucrats, unelected and unaccountable little kings
https://www.youtube.com/watch?v=ZwmUH5AGydQ

Fucking stupid harmful racist Marxist government.
"South Africa 2019: Beginning of the END".
South Africa is the next Zimbabwe.
https://www.youtube.com/watch?v=nURta8-zu4E

Infiltrate 1 million people with nanobots, and kill all those people simultaneously.
*** How do we know what law is in effect? Bagaimana cara kita tahu hukum yang berlaku?
- http://m.hukumonline.com/berita/baca/hol19115/fiksi-hukum-harus-didukung-sosialisasi-hukum-
- Perpres 1/2007
- JDIH lembaga yang bersangkutan
*** Bush crime family
https://twitter.com/JoshClarkDavis/status/1068889697999568897
"This is a major part of Bush’s legacy. It’s what his War on Drugs did to just one person. But it shows the human costs of that war in miniature detail. A high schooler was lured to the WH to sell crack and spent 7+ years in prison, so that the President could make a point on TV."

*** Abolish patents
"Company [Google] Tried to Patent My Work After a Job Interview"
https://patentpandas.org/stories/company-patented-my-idea
That's not the first time for Google.
https://twitter.com/matthewstoller/status/1068542058175098882
*** Minimum wage hurts the very people it is supposed to protect.
Government should abolish minimum wage law.
Everyone should know everyone else's salary.
Worker union is about collective bargaining power, not about formal organization.
The moment a worker union is made a formal organization, it gets its own life, and it starts to benefit itself; it stops to benefit the workers.

Organized Labor Hurts Us
https://www.youtube.com/watch?v=IDA8AyrtTN8
*** Indonesian
**** What
- https://www.zenius.net/blog/13453/apa-itu-demokrasi-liberal-kapitalis-komunis-sosialis-fasis-anarkis-konservatif
- ? http://www.berdikarionline.com/kisah-buruk-soeharto-di-mata-soebandrio/

UU pasar modal

UUPT 36:1: Ownership graph must be acyclic.

http://m.hukumonline.com/index.php/klinik/detail/lt4ee1cdcb3b9fc/status-direksi-perusahaan--pengusaha-atau-pekerja-revisi

https://www.hukumonline.com/klinik/detail/lt51b0380e6b9f8/bolehkah-menggeser-hari-libur-karyawan-tanpa-memberi-upah-lembur
Tidak boleh.

http://www.hukumperseroanterbatas.com/anggaran-dasar/anggaran-dasar-perseroan-terbatas/

https://www.hukumonline.com/klinik/detail/lt4cd0bd0284a71/perbedaan-modal-dasar--modal-ditempatkan--dan-modal-disetor-pt

https://media.neliti.com/media/publications/14073-ID-aspek-hukum-kelalaian-menyetorkan-modal-dalam-prosespendirian-perseroan-terbatas.pdf

https://www.hukumonline.com/klinik/detail/lt51426f0a4f0ee/fungsi-meterai-
**** Direktur bukan karyawan
Bolehkah direktur bekerja tanpa digaji? Boleh asal direkturnya bukan karyawan/pekerja/employee (hubungan kerja).
http://strategihukum.net/strategi-hukum-mengangkat-karyawan-menjadi-direktur
**** What
UUY Yayasan
https://www.putra-putri-indonesia.com/undang-undang-yayasan.html
- UU 16/2001
- diubah dengan UU 28/2004
- PP 63/2008

UU Pajak
https://id.wikipedia.org/wiki/Perpajakan_di_Indonesia
Susunan dalam satu naskah undang-undang perpajakan 2011 http://www.pajak.go.id/sites/default/files/PersandinganUUPerpajakan.pdf
UUPPh tentang pajak penghasilan
UUDP adalah UU 11/1992 tentang dana pensiun.

UUPPh 4:3L Beberapa beasiswa bukan objek pajak?
**** SIM
UU 22/2009 tentang lalu lintas dan angkutan jalan raya
https://www.bantuanhukum.or.id/web/implementasi-undang-undang-nomor-22-tahun-2009-tentang-lalu-lintas-dan-angkutan-jalan-raya/

*** Economics, finance, real economy vs financial economy?
Richard A. Werner
"Shifting from Central Planning to a Decentralised Economy"
https://professorwerner.org/blog/

Important:
"two-loop economy": real economy and financial economy
https://realcurrencies.wordpress.com/2013/04/01/is-there-enough-money-to-pay-off-debt-plus-interest-a-closer-look/

Interest can be repaid if the lender spends that interest back into the real economy.

Prof. Werner brilliantly explains how the banking system and financial sector really work.
https://www.youtube.com/watch?v=EC0G7pY4wRE
debunked: City of London a sovereign state
https://www.metabunk.org/debunked-city-of-london-a-sovereign-state.t587/

He asked an important question:
What is the value-added of financial economy?
*** Don't visit the UAE.
https://amp.theguardian.com/commentisfree/2018/nov/23/justice-uae-dubai-british-academic-matthew-hedges
*** How can Bhutan be unlike others?
"This country isn't just carbon neutral — it's carbon negative | Tshering Tobgay"
https://www.youtube.com/watch?v=7Lc_dlVrg5M

<2018-12-11>
Bhutan has a wise king.
But will the democratization give rise to political panderers and crippling bureaucrats in year 2100?
But is that worth to avoid the risk of a later evil king?
*** Government did not solve food/drug poisoning problem. Tamper-resistant packaging technology solved it.
Government doesn't need to intervene in Tylenol scare.
Free market can handle that.
If the producers don't find a better packaging, people simply won't buy.
Consumers simply have to tell what they want to the producers.

Technology always solves problems and creates new problems, but governments only create problems.
Governments are part of the problem, not of the solution.
** Keeping track
*** Who murdered these journalists?
Journalists have been brutally murdered in these areas:
- Malta: Daphne Caruana Galizia was car-bombed in 2017. https://en.wikipedia.org/wiki/Daphne_Caruana_Galizia
- Bulgaria: Viktoria Marinova was raped and murdered in 2018.
- https://www.theguardian.com/media/2019/feb/03/marie-colvin-murder-verdict--risks-journalists-lindsey-hilsum
*** Which news sources are untrustworthy?
No news source is trustworthy.
Think for yourself.
Learn some epistemology.
Don't read the news.

Vox [fn::https://www.vox.com/platform/amp/policy-and-politics/2018/10/1/17923178/washington-times-seth-rich-aaron-rich-trump-fox-news] says that these are untrustworthy:
Washington Times,
FOX News.
But Vox isn't trustworthy either.

VICE might have violated Naomi Wu's privacy?[fn::https://www.reddit.com/r/KotakuInAction/comments/898na9/vice_gets_patreon_to_remove_naomi_wu_who_blasted/]

Gizmodo and BuzzFeed are somewhat OK when reporting tech, but I find them very biased about social issues.

If it uses clickbait titles, it isn't readworthy; it's just another advertising whore.
If you think DailyMail is shitty, wait until you see Indonesian news sites like Detik.com, Kompas Online, VivaNews, and their ilk.
Pop-up ads.
Ads everywhere.
These Indonesian news sites are total whores that gladly let advertisers rape their spaces.
<2019-02-02>

Wikipedia maintains a blacklist of untrustworthy news sources
 [fn::perennial sources with varying trustworthiness https://en.wikipedia.org/wiki/Wikipedia:Identifying_reliable_sources/Perennial_sources]
 [fn::https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2018-12-24/Discussion_report]

Is BBC also untrustworthy?[fn::https://twitter.com/briankrebs/status/1092621689224085504]

** Fragments
*** Nitrogen asphyxiation for capital punishment
Nitrogen asphyxiation is humane, cheap, and fast.
- https://www.quora.com/What-would-be-the-fastest-and-most-efficient-way-to-kill-someone
- https://www.quora.com/Why-is-nitrogen-asphyxiation-not-used-in-capital-punishment
- https://en.wikipedia.org/wiki/Inert_gas_asphyxiation
- https://www.washingtonpost.com/news/post-nation/wp/2018/03/14/oklahoma-says-it-will-begin-using-nitrogen-for-all-executions-in-an-unprecedented-move/?noredirect=on&utm_term=.f342a31e16e9
*** Trust conserves resource
Trust enables us to use less resources.
Without trust, we have to defend.
Defense uses resources.

Without trust:
we have to bring weapons everywhere;
we can't trade;
we can't collaborate;
groups can't form.

A group cannot exist if its member kills each other.

In order for a group of men to be greater than the sum of its members,
every man must give more than he takes, and therefore every man has to be altruistic/self-sacrificial.

"Without trust, all contingent possibilities should be always considered, leading to a paralysis of inaction."[fn::https://en.wikipedia.org/wiki/Trust_(emotion)]
*** Practical morality
https://theconversation.com/the-greatest-moral-challenge-of-our-time-its-how-we-think-about-morality-itself-92101
- "[M]orality is the set of rules we live by that seek to reduce harm and help us live together effectively."
- "the problems that morality is trying to solve vary from one place to the next."
- "There are ways to judge the usefulness of a particular moral norm, namely: does it actually help solve the problems of social living for the people using it?"
*** What was morality?
Does a law requiring S imply that, before it existed, people would routinely violate S?

Does the Ten Commandments imply that, before it existed, people routinely murder each other?
*** Other resources?
What is this?
https://oll.libertyfund.org/pages/ideas
*** Liberalism, inheritance, and inequality
Dilemma:
- If we cap inheritances, we are thieves.
  We don't want thieves in the ideal society.
- If we don't cap inheritances, we breed inequality.

Inequality is not a problem in and of itself.
The problem is ensuring that the poorest people are not too bad.

People should be free to give whatever thay want to whomever they want, including their kids.

[[https://givingpledge.org/][The Giving Pledge]] tries to solve the big-inheritance problem, but we can't always depend on voluntariness.
Also, that pledge lacks concreteness and is not [[https://en.wikipedia.org/wiki/SMART_criteria][SMART]], so it practically does not exist.
According to [[https://en.wikipedia.org/wiki/The_Giving_Pledge][Wikipedia]]:
- "As of 2018, [...] their pledges total over $365 billion."
- "It does not actually dictate that the money will be spent in any certain way or towards any particular charity or cause, and there is no obligation to actually donate any money. "

Then what the fuck is it for?
Public relations spin?
How do we verify that those people have actually donated?
Is such verification even practical?
** General average?
Is general average socialism?
Is it moral?
Is it moral to handicap fortunate people?
Is it moral to help unfortunate people?
** Principal-agent problems, and conflicts of interests
** 2018 Jewish synagogue shooting: Resentment, despair, impatience, care, fascism, and extremism
https://www.theguardian.com/us-news/2018/nov/04/pittsburgh-shooting-robert-bowers-jewish-nurse

How one becomes a fascist:
He feels that democracy goes nowhere.
He realizes that people don't change.
People don't care.
Politicians are corrupt.
Government doesn't help him.
Cities are unwalkable.
He feels the system is rigged against him.
He begins isolating himself.
He continues to think.
As he thinks, he becomes more extreme.
He reinforces his beliefs.
He confirms his own biases.
He goes online.
He meets people who feel the same.
He is young and impatient.
He wants to see changes right now.

A person needs a justification for his existence.
If he thinks that the system is corrupt and is rigged against him, he will think that his violence is justified.

https://www.jacobinmag.com/2015/07/french-revolution-bastille-day-guide-jacobins-terror-bonaparte/

Oppressed majority will revolt.

Power ultimately comes from the ability to kill.

<2018-11-03>
Watch what Brazil will be under Bolsonaro after 1 year.
** Media
We need a neutral, non-profit media.
We need a bunch of united non-unionized independent journalists.

Every person should be able to report what he/she sees around him.

But what about lying peoples?
** Surprise
/Surprise/ is the discrepancy between belief and reality.

An event /surprises/ us iff we believe it is unlikely but it happens.

Myron Tribus surprisal[fn::https://en.wikipedia.org/wiki/Information_content].
Surprisal 0 means not surprising at all: it is bound to happen.
A-priori truth is unsurprising.
That a bachelor is unmarried is unsurprising, because that is the definition.
But the Immerman–Szelepcsényi theorem[fn::https://en.wikipedia.org/wiki/Immerman%E2%80%93Szelepcs%C3%A9nyi_theorem] was very surprising when it was first proved.
An a-priori truth is surprising if it is hard to compute (hard to know) and its result goes against our guess.
How can mathematics be surprising
 [fn::https://mathoverflow.net/questions/18100/theorems-with-unexpected-conclusions]
 [fn::https://math.stackexchange.com/questions/2949/which-one-result-in-mathematics-has-surprised-you-the-most]
if everything that we prove has always been true, only that we don't know it?
The Pythagorean theorem is true, but we did not know that it is true until we were taught about it in school.
A mathematical statement may be true, but we did not know that is true until someone proves it.
Surprisal \( \infty \) means infinitely surprising: the impossible happened.
** Marriage is just a contract
Key idea:
Contract law subsumes marriage law.
Marriage is an exclusive non-transferable license for sexual activities.
Marriage generalizes to any graph-theoretic arrangement of exclusive sexual rights.
*** Marriage regulates copulation, not procreation
Marriage regulates /copulation/ (having sex), not procreation (having offsprings).

/Before/ marriage has been invented, the society assumes that copulation is allowed by default unless explicitly forbidden (by complaints, disputes, fights, wars, treaties, etc.).
/After/ marriage has been invented, the society assumes that copulation is forbidden by default unless explicitly allowed (by marriage).
This change of fundamental assumption improves public order.

Copulation and procreation are two /orthogonal/ concepts.
Two concepts are orthogonal if we can have one without the other, in both ways.

To /copulate/ is to link / join / bind / tie / couple / bring together / conjoin (the genitals).
To copulate is to cause the male genital to be inside the female genital.
The male genital protrudes (goes outward).
The female genital receives (goes inward).
- https://en.wiktionary.org/wiki/copulate#Etymology
- https://en.wiktionary.org/wiki/copulare#Latin
- https://en.wiktionary.org/wiki/copula#Latin

Copulation is sexual intercourse.
Procreation is the production of offspring.

We can have /copulation without procreation/: inserting the penis into the vagina without ejaculating sperm, even between two married people.

We can have /procreation without copulation/: cloning, in-vitro fertilization, synthetic organisms.

Marriage is about exclusive copulation, not about procreation.
*** Arguments for and against generalizing marriage
**** Pro: Marriage regulates copulation, not procreation
Do you mind if your spouse copulate with but doesn't procreate with someone else?
That is, do you mind if your spouse had sex with someone else as long as nobody gets pregnant?
If you do mind that, then marriage is about regulating copulation, not procreation.

Do you mind if you can procreate with but not copulate with your spouse?
Consider an average couple.
Suppose that the husband's penis and the wife's vagina must never touch,
but a third person will, at no cost to the couple, inject the husband's sperm into the wife so that the couple can have a child.
Do the average husband and wife mind such [[https://en.wikipedia.org/wiki/Sexless_marriage][sexless marriage]]?
If they do, then marriage is about regulating copulation, not procreation.

Marriage, public order, and justification of marriage?

Legally, marriage exists to maintain public order.
Biologically, public order exists to maintain survival of the species.

Why does marriage exist?

Marriage exists because the average person gets angry when someone (s)he copulated with copulated with someone else,
and this anger may disturb public order.
Problem:
The definition seems to require that the sexes be different.
Is it reasonable to generalize "copulation" into "any sexual act"?

The average person would be angry if his/her spouse have any sexual acts (including flirting and sexual advances) with someone else.
It is not only copulation.
It is all sexual acts.
It is all acts that may reduce the chance of copulation.
The average man would be suspicious if his wife begins receiving lavish gifts from another man.

Therefore it is reasonable to generalize marriages to concern the exclusive rights of everything that may lead into copulation, not only copulation.

The debate of marriages boil down to the definition of copulation, and the relationship between copulation and procreation.

Originally copulation was for procreation/reproduction, but then nervous systems evolved, then pleasure centers evolved,
and thus copulation evolves to be pleasurable, because otherwise the organism will not reproduce.
**** Con: Monogamy has evolutionary benefits
Perhaps most of us we have evolved to prefer monogamy.

Monogamy reduces the risk of contracting sexually-transmitted diseases.
- Those diseases may co-evolve with us.
- [[https://www.biorxiv.org/content/early/2017/10/15/203695][Sexual conflict and STDs: coevolution of sexually antagonistic host traits with a sexually transmitted disease | bioRxiv]]
- https://en.wikipedia.org/wiki/Monogamy#Evolutionary_and_historical_development_in_humans
- https://edition.cnn.com/2016/05/17/health/sti-infanticide-human-monogamy/index.html

Monogamy improves infant survival.
*** General marriage
Contract law subsumes marriage law.
The law does not need to define marriages, because ordinary contract law suffices.
We can restate marriage terms in /contract law terms/:
cheating is /breach/, divorce is /termination/, and alimony is /damages/.

Usually we think that a marriage is a /contract/ between a person X, a person Y, and their society, stating that:
- person X and person Y may copulate with each other,
- person X must not copulate with anyone else other than person Y,
- person Y must not copulate with anyone else other than person X,
- the society will help enforce that restriction.

But that thinking is too narrow.
We can generalize that definition to any arrangement of sexual rights.
Two aspects of marriage generalize readily:
the /number/, from only two to any number;
and the /kinds/ of allowed sexual activities, from only copulation to any kind of sexual activities.
For example, group marriage generalizes the number, and gay marriage generalizes the kind of sexual activities.

Some examples of generalized marriages:
- Group marriage involving a group G of people P1, ..., Pn:
  - If person X is in G and person Y is in G, then person X and person Y may copulate.
  - Everyone in G must not copulate with anyone outside G.
- Strictly-heterosexual group marriage:
  - Each person X in group G may copulate with each person Y in G if X and Y have different sexes.
  - Everything else is forbidden.
- General marriage:
  - A marriage is an undirected graph.
  - An edge (x,y) means that x may copulate with y.
  - The absence of an edge (x,y) means that x must not copulate with y.
  - You can see where this is going: complete-graph marriage,
    point-to-point marriage, bus marriage, star marriage, ring marriage, mesh marriage, daisy-chain marriage,
    and [[https://en.wikipedia.org/wiki/Network_topology#Classification][other topologies]] of marriage.

We can even have directed graphs.
For example, X may penetrate Y, but Y must not penetrate X.

We can even have multigraphs.
We can explicitly list the permitted sexual activities in the contract.

Marriage law is redundant.

Marriage is just a contract that happens to be about sexual rights.

Marriage is about regulating the genitals, not about regulating procreation.
When people fuck, they don't think about the next 20 years.
They just want to enjoy the moment.

Relationship between marriage, graph theory, and model theory:
What is the shortest first-order logic formula that describes a graph that describes a marriage?
*** Half-baked contents
**** Legislating marriage, copulation, procreation, parenting, and family?
Marriage regulates consent?
But there are marital rape and arranged marriages.

Marrying someone does not mean being able to do anything to him/her.
He/she is your spouse, not your slave.
** Potential, actualization, waste
Potential is what may be.

/Waste/ is failure to actualize potential.
Failure is final and irreversible.

The goal of a state is to ensure freedom for each person to actualize his/her potential, pursue greatness

Why do we feel bad wasting?
* Bibliography
