#+TITLE: Social Research Group
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /social.html
#+OPTIONS: ^:nil toc:nil
#+TOC: headlines 1
#+TOC: headlines 2
#+TOC: headlines 3
* What?
** How should we live in the 21st century?
How should we care for ourselves?
See [[file:groom.html]].
** What is the moral system that we have evolved?
I am trying to codify (that is, to express in English) our implicit morality, that is, the implicit moral system that we have evolved.
Thus I write [[file:social.html][Designing the ideal society]].

What is our natural morality (the moral system built into us by evolution)?
Avoid harm?
** What is the difference between unethical and immoral?
What
 [fn::https://www.quora.com/What-makes-something-immoral-but-not-unethical]
 [fn::https://en.wikipedia.org/wiki/Heinz_dilemma]
 [fn::https://en.wiktionary.org/wiki/ethics#Usage_notes]
** What is wrong with 21st century societies?
*** Too focused on economic growth
Economic growth is not a worthy goal.
*** The root issue: power centralization?
Both a state and a company are legal fictions for centralizing powers.
**** What is a state?
A state is essentially a massive principal-agent problem[fn::https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem] involving millions of people.

The people give up their monopoly of violence to the state, and the state promises to do good to the people.
The problem is principal-agent problem.
The state cannot be trusted.
**** How can workers empower themselves?
Labor laws and unions are the wrong solution.
The correct solution is that the workers must unite and think for themselves, but they must not form a union.
Once a union is formed (as a legal entity), it has a life of its own, and the principal-agent problem begins.
There is always room and incentive for union bosses to collude with the original enemy, enrich themselves, and betray the original electors.
The anarcho-syndicalists get this mostly right (what they get wrong is "revolution").[fn::https://en.wikipedia.org/wiki/Opposition_to_trade_unions#Left_critiques_of_trade_unionism][fn::https://en.wikipedia.org/wiki/File:Anti-union_ASF_flyer.jpg]
Direct action.
**** What benefits us is trade, not capitalism
Capitalism contains free trade.
Free trade benefits everybody, but the for-profit private ownership of property doesn't always benefit everybody.
By free trade, we mean voluntary exchanges/transactions.

It is possible to have free trade without capitalism.
Anarchy is an example.

The issue is centralization of power.
Companies centralize economic power.
States centralize political power.
Institutions/organizations centralize power.
People must unite, but they must not form unions.
Principal-agent problem.
Unions have lives of their own.
**** What is a company?
It is a physically impossible to build or hurt a company.
A company cannot do anything.
People do things.
A company is a legal fiction for concentrating wealth (economic power) to its shareholders.
Such economic power often translates to other forms of power such as political power.
A company is rife with principal-agent problems and conflicts of interest.
There is one principal-agent problem between the shareholders and the directors.
There is another principal-agent problem between the directors and the employees.
There is one principal-agent problem for each layer of management.
It is amazing that such fiction lasts despite providing ample rooms for corruption.
**** But how do we launch rockets without power centralization, without states and companies?
Or build nuclear power plants, or do trillion-dollar engineering projects?
*** Is financial investing moral?
Financial investing is getting more money without doing anything.
It is immoral, because it means indirectly stealing a little from everyone else.
We should not glorify rentiers, freeloaders, and thiefs.

But does that mean that passive income, rent, interest, tax, pension fund, and royalty are immoral?

Inflationary monetary policy is immoral, because it steals a little from everyone who trusts the currency.
*** Taxation + capitalism = stealing from the thieves
Taxing the capitalists is stealing from the thieves.
Both taxation and capitalism are immoral.
Their combination is unnecessarily convoluted.
The correct solution is to not have any theft in the first place.

The solution is not taxing the rich.
The solution is to remove the law that enables the creation of
formal institutions, formal organizations, companies, legal fictions, virtual people, and other power-centralizing entities.
People must unite but they must not form a formal union.
*** Why do we care about constitutions?
Why should people in the 21st century agree with people in the 18th century?
Why should we agree with people born 300 years ago?
We don't even agree with our parents born 30 years ago!

What is a constitution?

USSR 1936 under Stalin[fn::https://en.wikipedia.org/wiki/1936_Soviet_Constitution]
had the most beautiful-sounding constitution, but it was only a lip service;
the practice was nowhere near that.
The most important thing a constitution must have is /limitation and decentralization/ of power.
** What is work without employment?
Work without subjugation.
Work without power asymmetry.

Work gives life meaning.
We like work and dislike employment.
We want a world in which we work because we want to, not because we have to.

What is work?
Work is purposeful deed/action.
The difference between work and leisure is teleological.
What is employment?
** What is the relationship between cooperatives and anarcho-syndicalism?
** What is ownership?
What does owning something mean?
** What is property?
Is property theft?
** Journalism
*** Who murdered these journalists?
Journalists have been brutally murdered in these areas:
- Malta: Daphne Caruana Galizia was car-bombed in 2017. https://en.wikipedia.org/wiki/Daphne_Caruana_Galizia
- Bulgaria: Viktoria Marinova was raped and murdered in 2018.
*** Which news sources are untrustworthy?
No news source is trustworthy.
Think for yourself.
Learn some epistemology.
Don't read the news.

Vox [fn::https://www.vox.com/platform/amp/policy-and-politics/2018/10/1/17923178/washington-times-seth-rich-aaron-rich-trump-fox-news] says that these are untrustworthy:
Washington Times,
FOX News.
But Vox isn't trustworthy either.

VICE might have violated Naomi Wu's privacy?[fn::https://www.reddit.com/r/KotakuInAction/comments/898na9/vice_gets_patreon_to_remove_naomi_wu_who_blasted/]

Gizmodo and BuzzFeed are somewhat OK when reporting tech, but I find them very biased about social issues.

If it uses clickbait titles, it isn't readworthy; it's just another advertising whore.
If you think DailyMail is shitty, wait until you see Indonesian news sites like Detik.com, Kompas Online, VivaNews, and their ilk.
Pop-up ads.
Ads everywhere.
These Indonesian news sites are total whores that gladly let advertisers rape their spaces.
<2019-02-02>

Wikipedia maintains a blacklist of untrustworthy news sources
 [fn::perennial sources with varying trustworthiness https://en.wikipedia.org/wiki/Wikipedia:Identifying_reliable_sources/Perennial_sources]
 [fn::https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2018-12-24/Discussion_report]
** Senior, lead, manager, director
Etymology clears up the differences.

Senior = older.[fn::https://www.etymonline.com/word/senior]

Lead = to show the way.[fn::https://www.etymonline.com/word/lead#etymonline_v_6615]

Manage = handle or train a horse.[fn::https://www.etymonline.com/search?q=manage]

Handle = "touch with the hands, hold in the hands, fondle, pet"[fn::https://www.etymonline.com/word/handle]

A director /directs/.
Directors knows what they want.
** Lying
*** Statistics makes bullshit appear legitimate
In 2019, by refuting a bullshit in Gamal Albinsaid's Twitter account,
Ainun Najib demonstrates[fn::https://twitter.com/ainunnajib/status/1082185571559124992][fn::https://www.facebook.com/joko.trikukuh/posts/10161376605960541]
Brandolini's bullshit asymmetry principle[fn::https://twitter.com/ziobrando/status/289635060758507521]:
"the amount of energy needed to refute bullshit is an order of magnitude bigger than to produce it".

One does not have to understand statistics in order to be able to bullshit with statistics.

Most people (including myself) don't understand statistics.

Every time I see an article with statistics,
I suspect that the author has not done sufficient philosophical analysis.

We do not have to refute the entire bullshit.
We only have to point out a fatal flaw, such as a truncated graph,
and cause readers to doubt the writer's intention.

A bullshit contains the necessary ingredient to refute itself.
A bullshit has an inherent flaw that we can point out without referring to anything outside the bullshit.
We just have to point it out.
"This is a truncated graph. You are lying."
*** Levels of lying?
Level 0: obvious lie, obviously nonsensical, takes no effort to refute.
Example: a child who broke a vase.

Level 1: sophisticated story, but no data.

Level 2: using true data, but selecting only the data that matches your agenda.

Level 3: level 2 plus fancy graphics, numbers, tables, statistics, truncated graphs[fn::https://en.wikipedia.org/wiki/Misleading_graph],
and damn lies[fn::https://en.wikipedia.org/wiki/Lies,_damned_lies,_and_statistics].

Level 4: level 3 plus creating your own pseudo-philosophy.

Level 5: post-truth politics: inventing your own facts.
** Why should everyone know some basic epistemology?
If people know some basic epistemology (that is, if they can tell apart what they know from what /they think/ they know), then there will be no wars.
Some epistemology should be taught in primary school.
We often assume a lot of things about others.
Most conflicts happen because we assume something wrong about someone else.
** What does "X deserves Y" mean?
Does anyone deserve to be rich?
Does anyone deserve to be poor?
Does anyone deserve kindness?
Does anyone deserve inheritance?
** Is there an Indonesian etymology dictionary?
I am looking for an Indonesian etymology dictionary, which I think is necessary for philosophical analysis of Indonesian laws.
** How should we be altruists?
If you want to be an altruist, pick activities with high impact-to-effort ratio[fn::https://www.effectivealtruism.org/articles/introduction-to-effective-altruism/].
Find a high-social-impact job suitable for you.[fn::https://80000hours.org/career-quiz/#/]
 [fn::How to find the world's most pressing problems https://80000hours.org/career-guide/most-pressing-problems/]
 [fn::The evidence on how to find the right career for you https://80000hours.org/career-guide/personal-fit/]
 [fn::Evidence-based advice on how to be successful in any job https://80000hours.org/career-guide/how-to-be-successful/]
 [fn::What are the 10 most harmful jobs? https://80000hours.org/2015/08/what-are-the-10-most-harmful-jobs/]
 [fn::https://hackernoon.com/where-are-the-programmers-who-give-a-shit-87f859f13f75]
** Will we survive the 21st century?
I am [[file:world.html][somewhat pessimistic about the 21st century]].
** What is competent and dangerous?
Jordan Peterson: responsibility gives life meaning[fn::be competent and dangerous https://www.youtube.com/watch?v=ONK8pGAGT28].
** Procreation is not survival?
To survive is to keep/continue living.

Survival of the individual vs survival of the species?

Survivalism is compatible with antinatalism.

* What is the ideal society?
** Principles?
The best thing for a person to do is what he/she /voluntarily/ does?

But:
- Most people don't know what they want?
- Most people don't think for themselves?
- Do most people even think?
** Institutions?
What is an institution?
Government bodies?
Governing bodies?

Do we need institutions?

Why do we lose trust in institutions?

Institutions enable people to hide.
Institutions enable people to abuse power without being held responsible.
Institutions deflect blame from people to an abstract entity.
Institutions separate the powerful from the coerced.
People should be responsible.
Instutitions cannot be responsible.

Bureaucrats cannot see reality from their desks alone.
** Capitalism has nothing to do with free trade?
Capitalism is simply the private ownership of the means of production.

Capitalism places capital above labor.
Nature places labor above capital:
Someone somewhere eventually has to /actually do/ something in order to produce something.
/Labor is more important than capital./
Capitalism goes against nature?
Capital without labor will not produce anything.
Labor without capital is merely inefficiently allocated.

Capitalism (market?) is a voting about what we should use labor for?
** What seems to be the most ideal society so far?
The most ideal society so far seems to be John Rawls's ideal society (based on his theory of social justice and veil of ignorance)
 [fn::https://en.wikipedia.org/wiki/A_Theory_of_Justice].
What are the problems?

Other people's ideas
https://www.quora.com/What-is-an-ideal-society-like

Practical utopia book?

Protopia is "incremental progress in steps toward /improvement/".
https://aeon.co/ideas/utopia-is-a-dangerous-ideal-we-should-aim-for-protopia

Every man has his own wants.

A voluntary trade betters all parties.
But why stop at trade?
A voluntary life betters the person.

The ideal society maximizes individual freedom while minimizing harm to the species.
Maximizes volition, the will to live.
Everyone fearlessly does what they love most.
Nobody slaves away at the office.

Occasional inconsequential broken small promises are okay.
People change.
People are sometimes too optimistic.

Things that don't belong in an ideal society?
- politicians
- lawsuits
- wars, refugees
- megacorporations, offices, employment
- religions
* Ethics
** Key idea: Morality, intention, and causality are inseparable
Morality cannot be determined by merely looking at the outcomes.
Determining morality requires knowing intention and understanding the chain of causes.

Why does intention matter?
How do we know others' intentions?
** Inaction can be a contributing factor, but not a cause
Key idea:
Inaction cannot be a cause, but inaction can be a contributing factor.
A contributing factor shares some blame.

About the [[https://en.wikipedia.org/wiki/Trolley_problem][trolley problem]], utilitarianism suggests killing the lowest number of people,
but our innate morality suggests /unconditional inaction/.
We refuse to interfere with the natural course of events.

Guilt, harm, blame, and causality:

This suggests that our moral principle may be "do not /cause/ harm".
This suggests that we feel /guilt/ when we cause harm.
Blaming requires understanding causality.

If I don't do anything, then I have /less/ responsibility if the runaway tram crashes into people.
If I switch, I have /more/ responsibility.

The solution to the trolley problem:
Inaction cannot be a cause, but can be a contributing factor.
If you do not act, then your existence does not affect the natural course of events.

The runaway tram problem differs from the crashing airliner problem.
The airliner pilot has a third option: killing everyone on the plane.
The tram driver doesn't have that option.

What do we evolve morality for?

Morality improves species survival, but does not maximize species survival.
Here's a proof by contradiction.
Suppose that it is moral to do everything that promotes survival of the species.
Quandary: the utilitarian surgeon kills 1 patient to save 5 patients.
But we feel that this is immoral.
Why don't doctors kill people to save more people?
Why do we prefer letting people die to making people die?
https://plato.stanford.edu/entries/doing-allowing/

Suppose that two men are starving.
It is moral for a man to sacrifice himself to be eaten by the other man, but it is immoral for a man to sacrifice-and-eat the other man.
Why is this asymmetry?
There are four possible actions:
- X kills X. Y eats X's carcass.
- X kills Y. X eats Y's carcass.
- ...
The outcome is the same: one of them will die anyway.
Why is self-sacrifice moral?
Why is Jesus the most moral person?

We are willing to sacrifice ourselves in an impending doom, in a hopeless situation; but we refuse to sacrifice ourselves so that the utilitarian doctor may save 5 other people.
If we are going to die 5 hours from now, then dying an hour earlier doesn't make a difference.
We are willing to sacrifice one day of life expectancy, but not 60 years of life expectancy.
Why does our willingness to sacrifice depend on how long we expect to live?
Why does our willingness to sacrifice depend on how far we look into the future?
A young suicidal man readily sacrifices himself while knowing that he would expect himself to live for 60 more years if he didn't kill himself?
Does a suicidal person know that a human, on average, lives for 80 years?
What does a suicidal person think about life expectancy?
How long do you expect to live?
I want to live forever.

The opposite of a suicidal person is a person who wants to live forever?


One thing is clear in our evolved morality:
It is moral to harm oneself, but it is immoral to harm others.
Did we evolve altruism?

Suppose two groups.
Actively harms others.
Avoids harming others.

Which is true?
We evolve morality so that we may form groups.
Or.
We form groups so that we may evolve morality.

Morality is what is required to form a group.
A group can only exist if most of its members are moral.
Morality is whatever prevents the collapse of the group.
???

How do we balance the individual's will to live and the group's survival?

Morality evolved to minimize feeling guilty?

Morality evolves to minimize the harm that a group inflicts to its members?

Why do we feel guilty?

Feeling guilty requires knowing causality.
We feel guilty because we think we cause harm.

Imagining evil vs doing evil

Relationship between morality, agency, cause, guilt?

What is the relationship between intention and morality?
Is it moral: an action with good intention but bad outcome?
** Counterproductive fragments?
*** Ethics is the study of moral quandaries?
The goal of ethics is to create a moral system free of moral quandaries?
*** Nature is amoral. Why should we be moral?
What difference is between dying today and dying tomorrow?
Aren't we all dead in the long run anyway?
*** Default-allow of default-forbid?
There are two rules of conduct:
- Everything is allowed unless forbidden.
  Fast, loose, and entrepreneurial.
  Liberal.
- Everything is forbidden unless allowed.
  Safe, slow, bureaucratic.
  This makes sense for computer security, but does it make sense for human?
** Ethics and language
*** Abortion debates are futile communication failures
<2018-09-15>

TLDR: Before you debate abortion, make sure everyone has the same definition of the words you're going to use.
**** The problem with abortion debates
Abortion debate is all emotion and no thinking.
Nothing will ever come out of it.
There is no real discussion.
The participants don't even agree on the meaning of the words they use (human, fetus, life, species, murder).
It is communication failure.
It is religious debate.

Everyone gives different meanings to the same word.
Everyone assumes everyone else has the same definitions.
There is only an illusion of communication.
There is no real progress.

New York Times has some [[https://opinionator.blogs.nytimes.com/2011/11/30/on-abortion-and-defining-a-person/][opinion]] about language in abortion debates.
**** Abortion debate is battle between thinkers and feelers
After seeing [[https://abortion.procon.org/][Abortion ProCon.org]], I realize that the debate is just a battle between thinkers and feelers.
Generally, thinkers are pro-abortion and feelers are anti-abortion.

After browsing around, I realize that gun control, euthanasia, death penalty, and other moral issues are just a giant battle between thinkers and feelers.
**** Ubiquitous problem: not defining what a human is
What is a human?
We think we know what a human is, but when we want to say it, we find out we can't.
Why?
Is our language limited?
Is "human" an ill-defined concept?

We don't know what a human is, we don't know what life is, but we dare to debate the sanctity of the life of a human?

People who debate abortion but can't define human are wasting time.
They don't know what they're talking about.
**** Ubiquitous fallacy: binarizing the continuum
Concepts such as hot, tall, big are not binary.
They are continuums.

Life is not binary.
It is a continuum.
We are more alive when we wake up.
We are less alive when we sleep.
We are even less alive when we die.

Being human is a continuum.

Truth is a continuum.
We reason probabilistically.
**** Why do we care what others do?
We care about what others do only as far as how they may harm us.

We don't care when someone harms himself.

We care when someone harms others, but only if he may harm us.

We care when someone kills people because we fear he may kill us next, not because we care about the people he killed.

We care when someone kills his children because we fear he may kill our children next, not because we care about the children he killed.

Why do we care when a pregnant woman aborts her fetus?

We care when a woman aborts her fetus because we want to impose our morality on others, not because we care about the fetus.
If we cared about the fetus, we would help the mother raise the fetus, help her give birth, and then adopt the baby.
**** Nature-defying El Salvador abortion law
[[https://www.bbc.co.uk/news/magazine-24532694][El Salvador abortion law ignores nature]].
It imprisons people unnecessarily.
**** Catching fallacies in action
***** Dennis Prager
Dennis Prager has a [[https://www.youtube.com/watch?v=AMwkQVpy98A][video about abortion]].

What he gets right:

- Right: "When challenged with this argument, people usually change the subject to the rights of the mother."
  - The right response is to ask the claimant to define the words human, species, life, fetus, etc.
    There is no need to digress to mother rights in order to point out the problems with the argument.

What he gets wrong:

- Mixing unrelated concepts in a loaded question: "Does the human fetus have any value and any rights?"
  - "Value" is a moral concept.
    "Rights" is a legal concept.
    The two don't always coincide.
    Also, he hadn't defined what a "human" is.
- Misuse of language: "A living being doesn't have to be a person in order to have intrinsic moral value and rights."
  - The term "intrinsic rights" is an oxymoron.
    Your rights are the things laws give you.
    They don't come with you.
- Wrong: "Either a human fetus has worth or it doesn't."
  - This is the fallacy of binarizing the continuum.
- Loaded question:
  "Why does one person, a mother, get to determine whether that being has any right to live?"
  - The question should have been: "Why does /anyone/ at all get to determine whether any being has any right to live?"
    - That question suggests antinatalism.
      Why do we force babies to come into being?

* Is universal morality possible or desirable?
** What?
There are always problems with moral systems?
Ethical dilemmas: no universal morality?
https://philosophynow.org/issues/60/Why_You_Shouldnt_Be_A_Person_Of_Principle

If every moral system is problematic, why should we have any moral system?

Egocentric survivalism's answer to trolley problem is "It doesn't matter what you do, because it doesn't have anything to do with your survival."

Chance-survivalism's answer to trolley problem is "You should act in the way that maximizes the human race's chance of survival."
But you don't know who to save for the best survival of the human race.

Problem: If the 5 people are all homosexual, and the 1 person is heterosexual,
then chance-survivalism implies that you should direct the train to the 5 homosexual people?
What if those 5 homosexuals found a cure to cancer, and that heterosexual became a war criminal?
What if the other way around?
** The problem with prioritizing individual survival over species survival
Survivalism suffers this problem.
Consider this dilemma:
A superpowered alien abducts you, starves you, and offers you two options:
- If you eat the food, then he destroys the Earth, killing all humans on Earth.
- If you don't eat the food, then he leaves the Earth alone.
The problem: survivalism prescribes that you eat the food, and let everyone else go to hell.

But it makes sense.
Even Utilitarianism suggests that you get into
** Is there an ultimate moral quandary?
Is there a situation in which no morality has any solutions?

How do we generate moral quandaries?

Given a moral system, can we always generate a moral quandary?
** Moral particularism
https://philosophynow.org/issues/60/Why_You_Shouldnt_Be_A_Person_Of_Principle

Is there a universal moral principle that coincides with the majority intuition about these issues?

- It is moral to kill fewer people to save more people?
- Is it moral to kill a serial killer to prevent 100 murders?
- Is it moral to kill a healthy innocent person and distribute his organs to save 5 people in need?
- Is it moral to annex a mismanaged country and improve it?
** Improbability of equality of outcome in doomsday spaceship scenario
Consider this "doomsday spaceship" scenario:
- A huge asteroid will hit the Earth 1 week from now. That will kill all 7 billion people.
- But we have one spaceship that can save 1000 people. That is the only way out of Earth.
Which people should we save?
Why?
There is no satisfactory answer to this; we should just use a truly random lottery.
But if we pick people randomly, the ship will be full of poor people, because the majority of the Earth is poor.
Should pregnant women be prioritized before non-pregnant women?
Should older women be prioritized before younger women?
Should women be prioritized before men?
Should children be prioritized before women?
Nobody should be prioritized.
If we don't pick people randomly, then we don't practice what we preach about equality.

With a lottery, all 7 billion people have a chance to board the spaceship,
but it is physically impossible for all 7 billion people to actually board the spaceship.
No amount of political correctness will change the laws of nature.

Of course, when the spaceship is big enough for 7 billion people, we can have equality of outcome.
The question is how we make a spaceship that big.
** Contextual/circumstantial morality/ethics

Does context change the goodness?
Is context relevant to morality?
Do circumstances affect judgment?
Example:
Stealing is wrong.
Is stealing in distress to survive less wrong?
Self-defense can justify killing. Why can't self-defense justify stealing?
Should intentional killing be more wrong than unintentional killing?
Rioting is wrong. But is rooting to overthrow a tyrant wrong?

https://english.stackexchange.com/questions/360411/whats-the-difference-between-dictator-tyrant-and-despot-in-terms-of-a-r

Is killing a terrorist good?

** Natural morality? Survival?

http://atheistnexus.org/m/discussion?id=2182797%3ATopic%3A131131
"Morality is a consideration among the living about that which affects survival." Clarence Dember

[[https://en.wikipedia.org/wiki/Natural_morality]]

** Survivalism moral quandary: two people on a sinking ship, in which only one person can be saved
Consider this scenario:
- Two people X and Y are on a sinking ship in the middle of the ocean.
- There is only one way to safety: by a lifeboat.
- But the lifeboat can only carry one person.

Remember that survivalism is about the /species/, not the /individual/.

Survivalism implies that we should prefer the one most fit to continue the survival of the species.
Survivalism implies survival of the fittest.
- It is moral to sacrifice oneself to let the other live.
- It is moral for one to kill the other.
- It is not moral to die together.

Survivalism seems to suggest that they should fight until one dies, but without hurting the other too much that both can't survive.

Here survivalism is ambivalent about egoism and altruism.
* Explicating our innate moral system
Here we are going to do these:
- Assume that we evolved an innate moral system.
- Formally define "moral system" and "quandary".
- Use quandaries arising from universal moral principles, to pinpoint our innate moral system.
  We want to come up with a statement such as "don't harm people".
- Construct a moral system without quandaries.
** Innate morality, natural morality
See these:
- https://en.wikipedia.org/wiki/Natural_morality
- https://en.wikipedia.org/wiki/Evolution_of_morality
- https://www.nytimes.com/2006/10/31/health/psychology/31book.html

We have morality, but we can't say what it is.

Why do most people agree that the utilitarian surgeon is wrong?
** Formalizing quandary-free moral systems
Key ideas:
- A moral system is a formal system that contains modal logic.
- A quandary is a formula with the shape "(must S) and (must not S)".
- Conjecture:
  If a moral system only requires or only forbids but never both requires and forbids, then it won't have quandaries.

A moral system is a /formal system/ that contains modal logic.
A formal system has a formal language, a set of axioms, and a set of inference rules.
A formal language has an alphabet and a grammar (a set of formation rules).

"Moral system" is sometimes also called "morality".

Two kinds of moral statements are /requirement/ and /forbiddance/.
Synonyms for "requirement" are necessity, obligation, duty.
Synonyms for "forbiddance" are prohibition, restriction.

A /quandary/ is a formula with the shape "(must S) and (must not S)".

A quandary is almost a contradiction.
A contradiction is both true and false;
likewise, a quandary both requires and forbids.
Compare the difference in where the "not" is:
- A quandary has the shape "(must S) and (must /not/ S)".
- A contradiction has the shape "(must S) and /not/ (must S)".

A note about language:
in this discussion, we never write "you must /avoid harming/ others"; we always write "you must /not harm/ others".
We don't use negative verbs such as "avoid" in a formal moral system;
we use only positive verbs in this discussion.
** Explicating our innate moral system
Here we are going to repeat these until we arrive at a quandary-free moral system:
- Propose a universal moral principle that at first seems good.
- Find that it raises a quandary.
- Revise the moral principle to immunize it against the quandary.

Here we try to state our innate moral system in English.

Given an action, most people agree on whether that action is good or bad,
but most people cannot satisfactorily define what good is and what bad is.

What I think we believe is moral:
- Retaliating.
- Forcing children to do things for their own good.
* If everybody needs to eat, why aren't farmers the richest people on Earth?
Food has been the best-selling thing for 40,000 years,
but why aren't farmers the richest people on Earth?

Here's a thought experiment that leads me to that question.

Imagine an economy that consists of 1 extremely frugal farmer and 1 doctor.
After some time, money accumulates at the farmer,
because the doctor always needs to eat, but the farmer doesn't always have a health problem.

A government has these options, from the least coercive to the most coercive:
- Do nothing, and hope that the farmer donates his money to the doctor.
- Create more money and give it to the doctor.
  But the farmer may think that this is unfair.
- Tax the farmer and give that tax money to the doctor.
- Force the farmer to spend his money on the doctor.

The current economic system suffers from money accumulation.

Is accumulation of money bad?
Is inequality bad?
* Fragments
** Nitrogen asphyxiation for capital punishment
Nitrogen asphyxiation is humane, cheap, and fast.
- https://www.quora.com/What-would-be-the-fastest-and-most-efficient-way-to-kill-someone
- https://www.quora.com/Why-is-nitrogen-asphyxiation-not-used-in-capital-punishment
- https://en.wikipedia.org/wiki/Inert_gas_asphyxiation
- https://www.washingtonpost.com/news/post-nation/wp/2018/03/14/oklahoma-says-it-will-begin-using-nitrogen-for-all-executions-in-an-unprecedented-move/?noredirect=on&utm_term=.f342a31e16e9
** Weapons and oppression
- Weapons enhance our ability to kill.
  - Weapons enhance our ability to scare.
  - Thus weapons enables better-armed people to oppress worse-armed people.
- Order of magnitude of weapon effectiveness
  - With a blade, one person can subdue 1 unarmed person.
  - With a pistol, one person can subdue 10 unarmed people.
  - With a machine gun, one person can subdue 100 unarmed people.
  - With a bomb such as that in Oklahoma city bombing, one person can subdue 1,000 unarmed people.
  - With a nuclear bomb such as those dropped by the USA on Hiroshima and Nagasaki during World War 2, one person can subdue 1,000,000 unarmed people.
- Order of magnitude of media deception effectiveness?
  - This is totally baseless.
    How do we estimate this?
  - With hearsay, one person can deceive ten people?
  - With paper, one person can deceive a hundred people?
  - With newspaper or WhatsApp, one person can deceive a million people?
  - With television or Facebook or Google, one person can deceive a hundred million people?
- The only way for the oppressed to fight back is:
  - total guerrilla warfare
  - living near to the oppressor (so that he can't nuke)
  - terrorism
    - Is there really no other way?
      Dialogs?
      Referendums?

What prevents violence is the ability to retaliate with comparable violence.
What prevents oppression is the ability to retaliate for that oppression.

NUKEMAP: nuclear explosion damage calculator
https://nuclearsecrecy.com/nukemap/
** Trust conserves resource
Trust enables us to use less resources.
Without trust, we have to defend.
Defense uses resources.

Without trust:
we have to bring weapons everywhere;
we can't trade;
we can't collaborate;
groups can't form.

A group cannot exist if its member kills each other.

In order for a group of men to be greater than the sum of its members,
every man must give more than he takes, and therefore every man has to be altruistic/self-sacrificial.

"Without trust, all contingent possibilities should be always considered, leading to a paralysis of inaction."[fn::https://en.wikipedia.org/wiki/Trust_(emotion)]
** Practical morality
https://theconversation.com/the-greatest-moral-challenge-of-our-time-its-how-we-think-about-morality-itself-92101
- "[M]orality is the set of rules we live by that seek to reduce harm and help us live together effectively."
- "the problems that morality is trying to solve vary from one place to the next."
- "There are ways to judge the usefulness of a particular moral norm, namely: does it actually help solve the problems of social living for the people using it?"
** What was morality?
Does a law requiring S imply that, before it existed, people would routinely violate S?

Does the Ten Commandments imply that, before it existed, people routinely murder each other?
** Other resources?
What is this?
https://oll.libertyfund.org/pages/ideas
** Liberalism, inheritance, and inequality
Dilemma:
- If we cap inheritances, we are thieves.
  We don't want thieves in the ideal society.
- If we don't cap inheritances, we breed inequality.

Inequality is not a problem in and of itself.
The problem is ensuring that the poorest people are not too bad.

People should be free to give whatever thay want to whomever they want, including their kids.

[[https://givingpledge.org/][The Giving Pledge]] tries to solve the big-inheritance problem, but we can't always depend on voluntariness.
Also, that pledge lacks concreteness and is not [[https://en.wikipedia.org/wiki/SMART_criteria][SMART]], so it practically does not exist.
According to [[https://en.wikipedia.org/wiki/The_Giving_Pledge][Wikipedia]]:
- "As of 2018, [...] their pledges total over $365 billion."
- "It does not actually dictate that the money will be spent in any certain way or towards any particular charity or cause, and there is no obligation to actually donate any money. "

Then what the fuck is it for?
Public relations spin?
How do we verify that those people have actually donated?
Is such verification even practical?
* The economic system
** What is "economy"?
What is "economy"?
What is "economy" in "economic meltdown"?

Exchange?
Trade?

Satisfy maximum wants using minimum resources.
There are two solutions:
- Reduce wants.
- Use more resources.

Economics is easy to explain but hard to predict.
Economics is too interconnected.

Demand/consumption is easy; supply/production is hard.

/Demand is easy./
We can want anything.
Changing our minds is free.

/Supply is hard./
We have to work to satisfy our demands.

Consumption is easy.
Production is hard.
Destruction is easy.
Creation is hard.
Second law of thermodynamics: The entropy of the Universe never decreases.
In nature, entropy never decreases.
Disorder arises naturally.
The second law of thermodynamics explains why consumption is easier than production.

The nature of economics is that demand is free, but supply is costly..
Changing demand is cheap: you just change your mind.
Changing supply is costly: all the infrastructure that has been built won't simply turn back into cash.

Demand first or supply first?
Human nature is the root cause of economic demands.
There will always be demand for food and shelter.
There is always demand to make life easier and less boring.

However, in the case of iPhone, we have two views:
- Steve Jobs's presentation causes people to want iPhones. Supply creates demand.
- People always want an easier way to live. Steve Jobs's iPhone just happens to make people's lives easier.

For example:
We want an easier way to live.
People don't want iPhones for iPhones's sake.
People want iPhones because people believe iPhones make people's lives easier.

If demand surges, it will collapse later.
Example: tulip mania.
** What economic system is desirable?
Characteristics:
- Distributed.
  Cannot centralize power.
  Cannot be controlled by government.
- Cooperative.
  Competition is a massive waste of human labor.
  Competitors reinvent each other's wheels all the time.
  The solution to competition is not competition laws.
  The solution is cooperation.
- Productive instead of consumptive.
- Antifragile (Taleb).

Is it possible to create an economic system that does not incentivize cheating?

What is the relationship between liberalism, competition, and cooperation?

Economic that is not focused on consumption?

Economic growth usually means consumption growth.

The easiest way to increase GDP is to increase consumption, environment be damned.

Why would we produce anything that nobody will consume?
** Economic recession
Economic recession is the reduction of money flow velocity.

How do we predict recession?
How do we measure and monitor money flow velocity?
- people savings balance
- mass layoffs
- mass price hikes for vital goods (oil?)
- company profit/loss statements
- money accumulates at few economic actors

Technology introduction, demand shift among substitute goods:

A demand shift is a demand collapse and a demand surge.

Cheaper robotic workers (or increasing minimum wages) causes demand for human workers to collapse and demand for robotic workers to surge.

Demand shifts among substitute goods.
** Fluid dynamics explains economic recessions
Economic recession happens because money flow slows down.

Money is a fluid.
A fluid flows.
Fluid flow velocity depends on pressure at the source and resistances in the path.

If we want to maintain flow velocity despite increasing resistance, we have to increase pressure at the source of the fluid flow.
But do we want this?

Money flow slows down because people spend less.

People spend less because they have less discretionary income.

People have less discretionary income because they are fired, or governments raise taxes, or important things get more expensive, etc.

Assumption:
A person's behavior changes slowly, if it changes at all.
A person who has never cared about the environment will not suddenly care about the environment.

A recession has two possible direct causes: /demand collapse/ or /supply collapse/.

Examples of supply collapse:
- Mine collapse, oil rig explosion, etc.
- Disasters: fire, earthquake, tsunami, flood, volcanic eruption, etc..
- Lots of people going out of workforce at once (into pension, dying in war, etc.).
- Lots of people suddenly becoming conscious (Google workers demonstrating for transparency, etc.).

Examples of demand collapse:
- Bitcoin ran out of fools (greater fool theory).
- Renewable energy sources reduce oil demand.
- Young people adopt a minimalist lifestyle after realizing that consumerism is unsustainable.
- Government increases minimum wage big enough to make switching to robots looks cheap.
  Lots of companies introduce robot workers at the same time, making human workers redundant.

Supply collapse is caused by physical destruction.
Demand collapse is self-inflicted human condition.

Consumers supply demands to producers.
Consumers demand supplies from producers.
Take and give.
To demand is to take, to consume, to destroy.
To supply is to give, to produce, to create.

What does inverted yield curve has to do with recession?
What does time preference have to do with economic recession?
What is an economic recession?

CAGR = compound annualized growth rate.

What is the yield of a bond?
A bond's yield is the CAGR of the bond price.

What is the yield curve?
The yield curve is the curve in a plot with two axes: the horizontal axis is tenor (duration to maturity), and the vertical axis is yield.

An inverted yield curve indicates that buyers are pessimistic about the bond's future?
** Currency? Free banking? Digital fiat currencies?
Piggyback nascent fintech/e-cash/e-money startups?
BTPN Jenius?

https://openbazaar.org/blog/trust-is-risk-a-decentralized-trust-system/
Currency requires trust.
Debt requires trust.
Transaction requires trust.
Business requires trust.
What is trust?

A trustworthy person refrains from exploiting vulnerabilities.
Trust is the assumption that the other party refrains from exploitation.
Trust is the assumption of the absence of betrayal.
Betrayal is the exploitation of trust.
(Problem: Circular definition.)

** Economic crisis is discontent due to reduction of purchasing power.
A /crisis/ is a mass discontent.

An /economic crisis/ is a mass discontent due to mass reduction of purchasing power.

"A financial crisis is any of a broad variety of situations in which some financial assets suddenly lose a large part of their nominal value."
https://en.wikipedia.org/wiki/Financial_crisis

- High firing rate, high unemployment, unemployed people having genuine difficulty finding jobs, employers not willing to employ
- Greatly reduced demand (discretionary spending)
- Reduced purchasing power

Deposits should not be guaranteed.
Banks should not lend.
Banks can take fees.
The job of banks is to clear transactions.
Banks exist so that people can transact without physically bringing large amount of cash to the place of transaction.
Banks should strive to minimize transaction cost.
The job of banks is not to lend.
That is the job of credit unions.
Banks should not double as creditors.

What is a bank, in anarchy?
** Economics of open-source
https://en.wikipedia.org/wiki/Open-source_economics

Where do we draw the line between open core and crippleware?
- https://en.wikipedia.org/wiki/Open-core_model
- https://en.wikipedia.org/wiki/Crippleware

Is "open core" just an euphemism of "crippleware"?

If the open core is actually useful, then it isn't crippleware.
http://blogs.collab.net/subversion/enough-of-this-open-core-confusion

Marginal cost is the change in opportunity cost due to increasing production quantity by one.
https://en.wikipedia.org/wiki/Marginal_cost
** Abolish corporations?
Limiting liability creates moral hazard.
But what is the alternative?

Corporation is a legal fiction.

Corporation (and insurance) enables people to act with impunity.

People would be more ethical if they have more skin in the game.

Before we abolish corporations, we must abolish frivolous lawsuits:
- "I'm not a fan of corporations, but the amount of frivolous lawsuits in the us make it desirable."
  https://www.reddit.com/r/CapitalismVSocialism/comments/46ljlf/capitalism_without_corporations/
* Design the world order
** Develop non-shitty FOSS distributed/P2P alternatives to most vital services
Works behind NAT?
How can A and B connect to each other if A is behind NAT gateway G1 and B is behind NAT gateway G2?

Google search: no replacement yet!
YaCy is not good enough.
Can we make it in Prolog?

Distribute the result of manual curation?
Bundle a curation tool with a browser?
Privacy issues?

Facebook: Mastodon?

YouTube: DTube, BitChute
https://www.ghacks.net/2018/03/02/dtube-is-more-than-a-youtube-alternative/

Heroku?

"An Open Source, Self-Hosted Heroku"
https://news.ycombinator.com/item?id=12703121
https://www.bitmatica.com/blog/an-open-source-self-hosted-heroku/
"Internals of OpenRuko PaaS, an open source Heroku clone implementation"
https://www.slideshare.net/rogerleite14/paa-s-26212382
https://github.com/dokku/dokku
https://github.com/openruko
https://flynn.io/
https://www.quora.com/What-are-some-open-source-Heroku-alternatives

https://www.quora.com/What-are-some-open-source-Heroku-alternatives
** Develop power-distributing technologies
** Write a user-first browser in Prolog
*** 1h: Specify desired features and differences from mainstream browsers
Principle: the user should have maximum control.

It is not only a browser.
It is a tool for controlling your web experience.

- The browser is distributed/P2P.
- The browser comes with a search engine that searches your public history or your peers' public history, and distribute indexes to peers.
- Block all ads because advertising depends on making people addicted.
- Block all popups, no exception, no clickjacking.
- Block all "soft-popups" (displays).
- Run user script for certain websites.
- Block all cookies by default.
- Don't load JavaScript by default.
- Don't load images by default.
- Apply default CSS. Don't load CSS by default.
- Enable user-agent spoofing.
- For advanced users. No GUI to configure. Write Prolog code to configure the browser.
- Default to HTTPS when protocol is not given.
- No download manager. Tell the user to use wget, curl, or whatever.
- Like emacs but:
  - browser instead of text editor
  - prolog instead of emacs lisp
- Browser must limit memory usage.
  See entity explosion problem.
- Browser should refuse to load HTML documents larger than 1 MB.
- User can easily change user agent. WhatsApp wrong browser detection.
- combine with caching, peer-to-peer caching, distributed (and social?) searching and ranking and sharing, but what about privacy and the people who try to game the system?
- Don't remember tabs when closed.
Limit open tabs to 10. Discourage context-switching. I'm a pathological tab hoarder. Always open a configurable set of tabs on start. If you need to open more tabs, then open a google docs or a note-taking app instead.

- Write a fast, private, and secure web browser in Prolog.
  - Features:
    - Selectively enable JavaScript from some websites with Prolog rules.
    - Disable clipboard hook.
*** 1h: Skim existing browsers
Is this legit?
https://vivaldi.com

https://en.wikipedia.org/wiki/Comparison_of_web_browsers

https://www.quora.com/How-should-a-programmer-think-about-solving-problems-in-Prolog

Entity explosion problem:
#+BEGIN_EXAMPLE
<!ENTITY a "&a;">
<!ENTITY a <16 times a>
<!ENTITY b "&a;" <16 times>
<!ENTITY c "&b;" <16 times>
etc.
after 10 times we have 2^40 = 1 TB!
#+END_EXAMPLE

Example rendering rules: nag.html:
if website is pinterest then remove DOM element blah blah after load.

Popular open-source browsers are highly scrutinized.

not too related:
"prolog on the browser"
https://github.com/SWI-Prolog/roadmap/issues/43
*** Gui, logical/relational reactive programming, a layer on top of plgi (Prolog Gtk bindings).

exists W: window(W)
exists A: textbox(A)
value(A, yes) :- is_down(B), !.
value(A, no).
children(W,Cs) :- current_document(D), document_controls(D,Cs).
"The value of the textbox is yes whenever the button is down."
current_document/1 is a dynamic predicate.

name_widget(main,W) :- window(W), widget_width_height(W,640,480).

window(W) is true iff W is a window representation.
name_widget(N,W) is true iff N refers to widget representation W.


Example of some queries that we want a GUI knowledge base to answer:
- What is the width and height of the "main" window?
- What happens when button b1 is clicked?
- What has to be done to make this text box shows "yes"?

Example time-dependent facts that we want to state:
- After button b1 is pressed, then checkbox c1 is checked.
- If user clicks on a link, then navigate to the target of that link.
- latching?



gui(Root)


Layout algorithm
layout_one_line(Font, String, MaxWidth, Line, RemString)



Temporal logic for GUI
is_up(B) -> green(W)
is_down(B) -> red(W)


:- dynamic object_time_property_value/4
At every event, increment current_time

binding(W1, K1, V1, W2, K2, V2) :- ...


widget_value :- current_time, widget_version_value
force(widget_property_value(W,V)) :-
retractall(wtpv :- T >= Curtim, _), asserta((time_widget_value(T,W,V) :- T >= Curtim, !)).

Problem: slow gui update; recheck all widgets unnecessarily

http://www.swi-prolog.org/pldoc/man?predicate=initialization/2

array_array_concat(A, B, C) :-
    array_length(A, NA), ...
    NC is NA + NB,
   subarray_subarray_match(A, 0-NA, C, 0-NA),
    subarray_subarray_match(B, 0-NB, C, NA-NC).

Replace equal with match

** Liberalism is the only way people can live together.
The only way to live together is to let people do everything they want as long as they don't harm other people.

Why do we care about consent?
Science advances faster without consent?

Why does the silver rule work?
The silver rule is "don't do unto others what you don't want to be done unto yourself".
** Do we need government? Why do we need government?
https://en.wikipedia.org/wiki/Justification_for_the_state
"There is no single, universally accepted justification of the state."

** Liberalism vs libertarianism
https://politics.stackexchange.com/questions/353/what-is-the-difference-between-liberalism-and-libertarianism

Dan (Steve's friend)'s question: "if I want to opt out of government services, should I be able to?"
"Even if his decision to opt out was poor  if hed be better off by using the services  I couldnt justify /forcing/ him to pay for something he didnt want"
http://steve-patterson.com/conservative-anarchist/
** The problem with libertarianism: the libertarian children problem: why do we prevent children from harming themselves?
Thesis: We should let someone do whatever he/she wants to do as long as he/she doesn't harm others, even if it makes him/her personally worse off.

Now the problem.

Why shouldn't parents let children do what children want as long as children don't harm others?
Why do we let an adult smoke cigarette, but we don't let a child smoke cigarette?
Why should we prevent children from touching wall sockets, drinking bleaches, and doing other dangerous things?
Why should we prevent children from harming themselves?
Libertarians are forced to conclude that children aren't people.
This conclusion is not inherently bad.
We can also define peopleness as a continuum (children are 50% people, for example).

Why should we vaccinate children?

https://www.quora.com/Libertarianism-When-do-children-own-themselves-if-at-all

However, an antinatalist libertarian wouldn't have this problem, because having children would be immoral in the first place.

https://www.reddit.com/r/antinatalism/comments/6356ym/shouldnt_libertarians_be_anti_natalist/

Our language implies that children aren't people.
- We use the pronoun "it" to refer to a child.
- Casualty count (death toll) is categorized into "men", "women", and "children".
- We sometimes use the phrase "men, women, and children".

The problem is in the language.
"Person" is not a binary concept; it's a continuum.
A child may be 20% personlike.
The more personlike something is, the more we should treat it as a person.
** Some problems with free market
- What prevent environment destruction?
  System for internalizing the negative externalities back into the companies, such as carbon credit.
- What prevents private military company from being corrupt or being bought by someone with lots of money but nefarious intents?

** Maximize individual freedom while minimizing harm to others

Every man, when left alone, does something he does best.
One person plants trees.
Another person murders people.
It follows that unlimited freedom is bad;
murderers should not be free to murder.

How much individual freedom is desirable?

** Presumption of innocence

- https://en.wikipedia.org/wiki/Presumption_of_innocence
- https://en.wikipedia.org/wiki/Blackstone%27s_formulation

** Sex and gender
Stop political correctness
https://www.yegor256.com/2018/11/13/bigotry.html

Political correctness kills

Women Can Now Join The SAS : UK Promptly Collapses
https://www.youtube.com/watch?v=piZRqOCOwP4

You can get as angry as you want, but it will not change the fact that sexual differences exist.

https://en.wikipedia.org/wiki/Gender-equality_paradox

John Stossel - Gender Confusion
https://www.youtube.com/watch?v=pTEPr4n_skI

On average, do men drive cars faster than women do?
*** What is a male? What is a female? What really makes a male a male and a female a female?
Is it the sex organ?
Is it the hormones?
It is the appearance?

Male and female are objective sexual classifications.
Man and woman are subjective gender classifications.
If sex and gender are orthogonal, then what is a "male woman"!?

- https://en.wikipedia.org/wiki/Trans_woman
  - A trans woman "is a woman who was assigned male at birth".
    The keywords are /assigned/ and /at birth/.

People in Stone Age may assume that someone's sex is determined at birth and doesn't change.
Back then, there were no sex reassignment surgeries.

Social-culture-language aspects:
Why is "girly man" an insult?

** How do we scale democracy?
*** How do we make elections cheap, easy, trustworthy (independently verifiable), and scalable?
Paper ballots can be independently verified.
Machines can't.

Trustworthiness requires that the system can be independently verified (by a third party, by a non-government organization, by local people, by anyone who cares).

How can we ensure verifiability while maintaining secrecy?

Every citizen has a private key?

Rachel Tobac:
"At @defcon hacking conference and just learned how easy it is to physically gain admin access on a voting machine that is used in 18 states.
Requires no tools and takes under 2 minutes.
Im concerned for our upcoming elections."
https://twitter.com/RachelTobac/status/1028437783050776576

https://arstechnica.com/information-technology/2018/09/e-voting-researchers-warn-of-hack-that-could-flip-the-electoral-college/

** My fundamental assumptions when designing a social system
- Everyone wants to survive.
- Good people (people who enjoy helping others) exist.
- Evil people (people who enjoy harming others) exist.
- There are people who don't care about others.
- People do what they do best when left alone. Inventors gonna invent. Murderers gonna kill. Rapists gonna rape.

But privatization has its dangers too.
BP's strings of accidents after its privatization.

Basic negotiation theory: more need means lower bargaining power.
Buyers fare better if sellers compete.
Sellers fare better if buyers compete.

John Stossel - Privatize Everything (2013)
https://www.youtube.com/watch?v=toYoXf7EHwc

John Stossel - The Parasite Economy
https://www.youtube.com/watch?v=f2vt8e5RjQ0

#+BEGIN_QUOTE
While in government hands, British Petroleum paid too little attention to profitability,
constrained by its need to please elected officials who often cared more about keeping energy cheap and employment high.
But in private hands, it may have cared about profits far too much, at the expense of other objectives.
BP veered from being a company that made sure nothing blew up to one focusing on cost-cutting at all costs, Professor Fisman said.
https://www.nytimes.com/2013/01/16/business/when-privatization-works-and-why-it-doesnt-always.html
#+END_QUOTE
** Industries whose profit is proportional to the destruction of the human race
- advertising, drugs, gaming, every business that profits from making humans addicted
- finance, investing, land speculation, and every business that does not create value

The advertising industry and the game industry are evil because they addict people in order to profit.

The advertising business model also causes recent extremisms.
http://nymag.com/intelligencer/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html
** How do we create an economy with zero rent?
** Ethics, morality, politics, fairness?
Ethics vs morality: what is the difference?

ethical vs moral

unethical vs immoral

amoral vs immoral

fair vs just; fairness vs justice

"Fair" means "beautiful", not "just".
https://en.wiktionary.org/wiki/fair

Fairness is absence of resentment.

We can't fairly divide one indivisible thing for two people who want it.

Resentment is "bitter indignation at having been treated unfairly".
https://en.oxforddictionaries.com/definition/resentment

How does perception of unfairness arise?

Fairness does not exist objectively.

- Suppose that we have a running contest, and you beat me.
  How do I know that you beat me /fairly/?
  - Good genetics is an advantage, but is it a fair advantage?
  - If we can't control it, can it be unfair?
  - Is it fair for children to be born in families with different socioeconomic status?
  - If equality of outcome is absurd, then what is fairness?
  - Is equality of opportunity fair?
    - Opportunity to do what?
      Opportunity to become what?
    - Equality of /all/ opportunity?
      - Opportunity to be boss/capitalist/rich?
* Marriage is just a contract
Key idea:
Contract law subsumes marriage law.
Marriage is an exclusive non-transferable license for sexual activities.
Marriage generalizes to any graph-theoretic arrangement of exclusive sexual rights.
** Marriage regulates copulation, not procreation
Marriage regulates /copulation/ (having sex), not procreation (having offsprings).

/Before/ marriage has been invented, the society assumes that copulation is allowed by default unless explicitly forbidden (by complaints, disputes, fights, wars, treaties, etc.).
/After/ marriage has been invented, the society assumes that copulation is forbidden by default unless explicitly allowed (by marriage).
This change of fundamental assumption improves public order.

Copulation and procreation are two /orthogonal/ concepts.
Two concepts are orthogonal if we can have one without the other, in both ways.

To /copulate/ is to link / join / bind / tie / couple / bring together / conjoin (the genitals).
To copulate is to cause the male genital to be inside the female genital.
The male genital protrudes (goes outward).
The female genital receives (goes inward).
- https://en.wiktionary.org/wiki/copulate#Etymology
- https://en.wiktionary.org/wiki/copulare#Latin
- https://en.wiktionary.org/wiki/copula#Latin

Copulation is sexual intercourse.
Procreation is the production of offspring.

We can have /copulation without procreation/: inserting the penis into the vagina without ejaculating sperm, even between two married people.

We can have /procreation without copulation/: cloning, in-vitro fertilization, synthetic organisms.

Marriage is about exclusive copulation, not about procreation.
** Arguments for and against generalizing marriage
*** Pro: Marriage regulates copulation, not procreation
Do you mind if your spouse copulate with but doesn't procreate with someone else?
That is, do you mind if your spouse had sex with someone else as long as nobody gets pregnant?
If you do mind that, then marriage is about regulating copulation, not procreation.

Do you mind if you can procreate with but not copulate with your spouse?
Consider an average couple.
Suppose that the husband's penis and the wife's vagina must never touch,
but a third person will, at no cost to the couple, inject the husband's sperm into the wife so that the couple can have a child.
Do the average husband and wife mind such [[https://en.wikipedia.org/wiki/Sexless_marriage][sexless marriage]]?
If they do, then marriage is about regulating copulation, not procreation.

Marriage, public order, and justification of marriage?

Legally, marriage exists to maintain public order.
Biologically, public order exists to maintain survival of the species.

Why does marriage exist?

Marriage exists because the average person gets angry when someone (s)he copulated with copulated with someone else,
and this anger may disturb public order.
Problem:
The definition seems to require that the sexes be different.
Is it reasonable to generalize "copulation" into "any sexual act"?

The average person would be angry if his/her spouse have any sexual acts (including flirting and sexual advances) with someone else.
It is not only copulation.
It is all sexual acts.
It is all acts that may reduce the chance of copulation.
The average man would be suspicious if his wife begins receiving lavish gifts from another man.

Therefore it is reasonable to generalize marriages to concern the exclusive rights of everything that may lead into copulation, not only copulation.

The debate of marriages boil down to the definition of copulation, and the relationship between copulation and procreation.

Originally copulation was for procreation/reproduction, but then nervous systems evolved, then pleasure centers evolved,
and thus copulation evolves to be pleasurable, because otherwise the organism will not reproduce.
*** Con: Monogamy has evolutionary benefits
Perhaps most of us we have evolved to prefer monogamy.

Monogamy reduces the risk of contracting sexually-transmitted diseases.
- Those diseases may co-evolve with us.
- [[https://www.biorxiv.org/content/early/2017/10/15/203695][Sexual conflict and STDs: coevolution of sexually antagonistic host traits with a sexually transmitted disease | bioRxiv]]
- https://en.wikipedia.org/wiki/Monogamy#Evolutionary_and_historical_development_in_humans
- https://edition.cnn.com/2016/05/17/health/sti-infanticide-human-monogamy/index.html

Monogamy improves infant survival.
** General marriage
Contract law subsumes marriage law.
The law does not need to define marriages, because ordinary contract law suffices.
We can restate marriage terms in /contract law terms/:
cheating is /breach/, divorce is /termination/, and alimony is /damages/.

Usually we think that a marriage is a /contract/ between a person X, a person Y, and their society, stating that:
- person X and person Y may copulate with each other,
- person X must not copulate with anyone else other than person Y,
- person Y must not copulate with anyone else other than person X,
- the society will help enforce that restriction.

But that thinking is too narrow.
We can generalize that definition to any arrangement of sexual rights.
Two aspects of marriage generalize readily:
the /number/, from only two to any number;
and the /kinds/ of allowed sexual activities, from only copulation to any kind of sexual activities.
For example, group marriage generalizes the number, and gay marriage generalizes the kind of sexual activities.

Some examples of generalized marriages:
- Group marriage involving a group G of people P1, ..., Pn:
  - If person X is in G and person Y is in G, then person X and person Y may copulate.
  - Everyone in G must not copulate with anyone outside G.
- Strictly-heterosexual group marriage:
  - Each person X in group G may copulate with each person Y in G if X and Y have different sexes.
  - Everything else is forbidden.
- General marriage:
  - A marriage is an undirected graph.
  - An edge (x,y) means that x may copulate with y.
  - The absence of an edge (x,y) means that x must not copulate with y.
  - You can see where this is going: complete-graph marriage,
    point-to-point marriage, bus marriage, star marriage, ring marriage, mesh marriage, daisy-chain marriage,
    and [[https://en.wikipedia.org/wiki/Network_topology#Classification][other topologies]] of marriage.

We can even have directed graphs.
For example, X may penetrate Y, but Y must not penetrate X.

We can even have multigraphs.
We can explicitly list the permitted sexual activities in the contract.

Marriage law is redundant.

Marriage is just a contract that happens to be about sexual rights.

Marriage is about regulating the genitals, not about regulating procreation.
When people fuck, they don't think about the next 20 years.
They just want to enjoy the moment.

Relationship between marriage, graph theory, and model theory:
What is the shortest first-order logic formula that describes a graph that describes a marriage?
** Half-baked contents
*** Legislating marriage, copulation, procreation, parenting, and family?
Marriage regulates consent?
But there are marital rape and arranged marriages.

Marrying someone does not mean being able to do anything to him/her.
He/she is your spouse, not your slave.
* Contract is distrust
We make a contract because we want the state to help us when the other party breaches the contract.
Thus we make a contract because we distrust the other party.

Contracts reduces the amount of trust required for trade.

If the state did not exist, would we still make contracts?
We would rely on honor, and not the state.

But underlying every contract is the assumption that the state is honorable.

Contract assumes a third-party enforcer that is powerful and honorable (just, fair, neutral, reliable).
* How little trust can we live with?
When I walk around the town, I tacitly assume that nobody will suddenly stab me with a knife.
* Let's slim down the morbidly obese government
** What
Medicaid insanity
https://www.reddit.com/r/MaliciousCompliance/comments/90q9m3/i_dont_work_here_anymorehey_boss_got_an_opening/

"I recommend seeing which movie best predicts */future/* scenes."
https://blog.dilbert.com/2018/06/10/why-democrats-hear-a-secret-racist-dog-whistle-and-republicans-dont/

Is this related?
https://blog.dilbert.com/2018/05/04/why-president-trump-deserves-credit-for-progress-in-north-korea/

Blackwater and Erik Prince do mostly GOOD
https://www.youtube.com/watch?v=GOeFKiTP9A0

It's true.
PMCs can be corrupt in the same way that governments can be corrupt.
But a corrupt PMC of 100 people is much less dangerous than a corrupt government of 100,000 people?

"Leaving the Left"
https://www.youtube.com/watch?v=kl0-n0zWVJk

The Left's War on Science
https://www.youtube.com/watch?v=OX8kEjSUr04

Gray Grumbler: "As a retired scientist, both extremes are problematic to science.
The right doesn't stop science but often ignores good science.
The left stifles science they are against and often puts forward junk as science.
And this junk discredits the good science.
I am completely displeased with both sides."

Admit it. Republicans have broken politics.
https://www.youtube.com/watch?v=mICxKmCjF-4

2004 article "Government: Unnecessary but Inevitable"
http://www.independent.org/publications/tir/article.asp?id=15

The only thing we need from government is protection from physical harm.
But only you can protect yourself?

We have to prevent concentration of power.
Government is concentration of power.
But would we rather arm all people, and have a tribal war, instead of oppression?
But would we have a tribal war?
Haven't we evolved to cooperate?

Even right people avoid the cops.

Americas Parasite Lawyers Deprive Us of Good Things
https://www.youtube.com/watch?v=gTQtVsggZXY

Freeloaders: The Wealthy
https://www.youtube.com/watch?v=DsTKAqHwj0s
We can always depend on the government to make bad rules. How do we profit from bad rules?

The Cayman Islands is not a tax haven. We need less rules, not more rules.
https://www.youtube.com/watch?v=bI7W65k-LPM

Fox News is fake news.
https://amp.cnn.com/cnn/2018/10/29/media/pittsburgh-suspect-invasion/index.html

"Leftist Protesters Get Perfectly Checkmated"
play the victim forever
https://www.youtube.com/watch?v=2NAKH8jdgm8

Dinesh D'Souza?
"it's not Trump that created the division, the division created him"?
https://www.youtube.com/watch?v=jhu7ZjeEO2s
I don't want to be associated with this guy, but does he speak the truth? https://en.wikipedia.org/wiki/Dinesh_D%27Souza

Cigarette smoking

I first got this from Judea Pearl's book of why.
https://tobaccocontrol.bmj.com/content/11/suppl_1/i110

Government problems:
- Wastefulness
- Perverse incentive
#+BEGIN_QUOTE
In two 1954 speeches made by Philip Morris vice president George Weissman, he promised: [I]f we had any thought or knowledge that in any way we were selling a product harmful to consumers, we would stop business tomorrow.
#+END_QUOTE
- https://truthinitiative.org/news/philip-morris-announcement-spend-nearly-1-billion-end-smoking-sounds-fake-news
- https://www.unfairtobacco.org/en/pressrelease-quitpmi/

The Inconvenient Truth About the Republican Party
https://www.youtube.com/watch?v=OURy5WFp0zk
Historically it is the Democrats that is sexist and racist. It still is.

Minimum wage hurts the very people it is supposed to protect. The proof is clear. The reason is clear.

The $15 Minimum Wage Is Turning Hard Workers Into Black Market Lawbreakers
https://www.youtube.com/watch?v=0fsVI3EmUnQ
Everyone loses. Workers lose. Business owners lose. Customers lose; reduced competition. Government actively harms everybody. Government is unethical.

Government is a preventable disease?

Who Are the Most Powerful People in America?
bureaucrats, unelected and unaccountable little kings
https://www.youtube.com/watch?v=ZwmUH5AGydQ

Fucking stupid harmful racist Marxist government.
"South Africa 2019: Beginning of the END".
South Africa is the next Zimbabwe.
https://www.youtube.com/watch?v=nURta8-zu4E

Infiltrate 1 million people with nanobots, and kill all those people simultaneously.
** How do we know what law is in effect? Bagaimana cara kita tahu hukum yang berlaku?
- http://m.hukumonline.com/berita/baca/hol19115/fiksi-hukum-harus-didukung-sosialisasi-hukum-
- Perpres 1/2007
- JDIH lembaga yang bersangkutan
** Bush crime family
https://twitter.com/JoshClarkDavis/status/1068889697999568897
"This is a major part of Bushs legacy. Its what his War on Drugs did to just one person. But it shows the human costs of that war in miniature detail. A high schooler was lured to the WH to sell crack and spent 7+ years in prison, so that the President could make a point on TV."

** Abolish patents
"Company [Google] Tried to Patent My Work After a Job Interview"
https://patentpandas.org/stories/company-patented-my-idea
That's not the first time for Google.
https://twitter.com/matthewstoller/status/1068542058175098882
** Minimum wage hurts the very people it is supposed to protect.
Government should abolish minimum wage law.
Everyone should know everyone else's salary.
Worker union is about collective bargaining power, not about formal organization.
The moment a worker union is made a formal organization, it gets its own life, and it starts to benefit itself; it stops to benefit the workers.

Organized Labor Hurts Us
https://www.youtube.com/watch?v=IDA8AyrtTN8
** Indonesian
*** What
- https://www.zenius.net/blog/13453/apa-itu-demokrasi-liberal-kapitalis-komunis-sosialis-fasis-anarkis-konservatif
- ? http://www.berdikarionline.com/kisah-buruk-soeharto-di-mata-soebandrio/

UU pasar modal

UUPT 36:1: Ownership graph must be acyclic.

http://m.hukumonline.com/index.php/klinik/detail/lt4ee1cdcb3b9fc/status-direksi-perusahaan--pengusaha-atau-pekerja-revisi

https://www.hukumonline.com/klinik/detail/lt51b0380e6b9f8/bolehkah-menggeser-hari-libur-karyawan-tanpa-memberi-upah-lembur
Tidak boleh.

http://www.hukumperseroanterbatas.com/anggaran-dasar/anggaran-dasar-perseroan-terbatas/

https://www.hukumonline.com/klinik/detail/lt4cd0bd0284a71/perbedaan-modal-dasar--modal-ditempatkan--dan-modal-disetor-pt

https://media.neliti.com/media/publications/14073-ID-aspek-hukum-kelalaian-menyetorkan-modal-dalam-prosespendirian-perseroan-terbatas.pdf

https://www.hukumonline.com/klinik/detail/lt51426f0a4f0ee/fungsi-meterai-
*** Direktur bukan karyawan
Bolehkah direktur bekerja tanpa digaji? Boleh asal direkturnya bukan karyawan/pekerja/employee (hubungan kerja).
http://strategihukum.net/strategi-hukum-mengangkat-karyawan-menjadi-direktur
*** What
UUY Yayasan
https://www.putra-putri-indonesia.com/undang-undang-yayasan.html
- UU 16/2001
- diubah dengan UU 28/2004
- PP 63/2008

UU Pajak
https://id.wikipedia.org/wiki/Perpajakan_di_Indonesia
Susunan dalam satu naskah undang-undang perpajakan 2011 http://www.pajak.go.id/sites/default/files/PersandinganUUPerpajakan.pdf
UUPPh tentang pajak penghasilan
UUDP adalah UU 11/1992 tentang dana pensiun.

UUPPh 4:3L Beberapa beasiswa bukan objek pajak?
*** SIM
UU 22/2009 tentang lalu lintas dan angkutan jalan raya
https://www.bantuanhukum.or.id/web/implementasi-undang-undang-nomor-22-tahun-2009-tentang-lalu-lintas-dan-angkutan-jalan-raya/

** Economics, finance, real economy vs financial economy?
Richard A. Werner
"Shifting from Central Planning to a Decentralised Economy"
https://professorwerner.org/blog/

Important:
"two-loop economy": real economy and financial economy
https://realcurrencies.wordpress.com/2013/04/01/is-there-enough-money-to-pay-off-debt-plus-interest-a-closer-look/

Interest can be repaid if the lender spends that interest back into the real economy.

Prof. Werner brilliantly explains how the banking system and financial sector really work.
https://www.youtube.com/watch?v=EC0G7pY4wRE
debunked: City of London a sovereign state
https://www.metabunk.org/debunked-city-of-london-a-sovereign-state.t587/

He asked an important question:
What is the value-added of financial economy?
** Don't visit the UAE.
https://amp.theguardian.com/commentisfree/2018/nov/23/justice-uae-dubai-british-academic-matthew-hedges
** How can Bhutan be unlike others?
"This country isn't just carbon neutral  it's carbon negative | Tshering Tobgay"
https://www.youtube.com/watch?v=7Lc_dlVrg5M

<2018-12-11>
Bhutan has a wise king.
But will the democratization give rise to political panderers and crippling bureaucrats in year 2100?
But is that worth to avoid the risk of a later evil king?
** Government did not solve food/drug poisoning problem. Tamper-resistant packaging technology solved it.
Government doesn't need to intervene in Tylenol scare.
Free market can handle that.
If the producers don't find a better packaging, people simply won't buy.
Consumers simply have to tell what they want to the producers.

Technology always solves problems and creates new problems, but governments only create problems.
Governments are part of the problem, not of the solution.

* Technology that liberates
Our goal is to create a technology that:
- distributes power to the people,
- keeps it distributed; prevents centralization

We need these technologies:
- a system that unrestrictably disseminates information
- a single global digital food-backed currency ($1 means the right to one meal)
- distributed electricity generation
- distributed web browser, hosting, and operating system

Physical laws is our only chance of defeating man-made laws.

Prosecutability/enforceability is more important than legality.
Being illegal does not always imply being prosecutable.
If nobody reports, the police has no case.
If there are too many criminals, the police can't do much.

Principles:
- You should not reap what you don't sow.
  Your wealth should be proportional to your contribution to society.
  You should not be entitled what you don't earn.
  If you don't work, you should not be paid.
  Abolish inheritance.
** Technology for anarchy: redistributing power back from government to the people
*** Anarchy
You should not be liable for what is not your fault.
If you are born disabled, it's not your fault.

But how can you work if you are disabled?
*** Technology for anarchy?
How do you host something without being liable for it?
For example, someone uploads porn to your distributed network.

Encryption-at-rest, and in transit, with tamper-resistant private key that self-destructs readily?

Even simpler.
Split the file into several parts, and host each part in different host.
Sorites paradox.
At how many bytes does a file contain porn?
If everyone is a criminal, then nobody is a criminal.

Currency tied to food price.
A meal should be nutritious and nourishing and healthy.
$1 = 1 meal.
Labor that enables the meal.
$1 = cooking 5 meals.
The cook creates a value of $5 but gets paid only $1.
Let everything be market.
$? = Creating a technology that enables us to make more meals.
$1 = protection for 8 hours.
How should we value art, programming, etc.? Let the market decide!
How does software enable us to create more meals?

If everyone takes more value than they create, the system collapses.

Cloud hosting is not a solution.
It's still centralized.
Your cloud provider decides what to host.
Government can crack cloud providers down.
*** Distributed-web browser?
Let's write a web browser library in Prolog.

2018-12-17 Tumblr bans all adult content.

Gnuzilla and IceCat has noble goals but does not solve the root cause of the problem: the centralization of power.
https://www.gnu.org/software/gnuzilla/

https://beakerbrowser.com/

We need to own our data.
We need to host our content ourselves.

We urgently need distributed web.

Distributed web is the only way for mankind and anarchy to flourish.

We need a web that cannot be controlled.

- Apple heavy-handed Tumblr into banning adult content.
- Google filter bubble

We need a currency whose value is tied to the value of food.

https://betanews.com/2018/12/04/duckduckgo-study-google-search-personalization/
*** Distributed (peer-to-peer) web, no central hosting
Prerequisites of success:
- infrastructure, search engine, directory, wiki, encyclopedia
- browsers installed in user machine

"Whoever controls the contents location controls the content"
https://medium.com/textileio/enabling-the-distributed-web-abf7ab33b638

https://stackoverflow.com/questions/737560/why-is-p2p-web-hosting-not-widely-used
*** What
We need distributed web now
https://techcrunch.com/2018/12/05/australia-rushes-its-dangerous-anti-encryption-bill-into-parliament/amp/

We don't want blockchain. We don't want permanence.
The creator may delete a resource that he created.
The host may delete a resource that he is hosting.
Everyone generates a key pair.

Imagine that there is a chemical reaction A + B -> cocaine, and both A and B are legal.
I sell John 1 ton of A.
You sell John 1 ton of B.
John makes 2 tons of cocaine at his home.

It is illegal to sell cocaine, but is it illegal to sell cocaine-making machine and cocaine precursors?
It should be as legal as selling frying pan and salt!
A knife can harm people, but is it not illegal to sell a knife!
Drugs shouldn't be illegal in the first place!

AI deepfakes, fusion power, and nuclear transmutation will destroy inefficient courts and parasite lawyers.
If everything is easy to fake, then nothing stands as evidence.

Imagine that X is a 1 MB JPG file containing porn.
Divide the file into 1000 pieces.
Store each piece at a different host.

https://en.wikipedia.org/wiki/Crypto-anarchism

Every block must have a unique identifier.

Identifier
Hash
Length
Content
Duration
Lease
Does it have to be anonymous?

Hide in plain sight?

Index files.

Identifier can be used to identify the origin.

Generate random block identifier
Assert to network
If there is no objection after some time, assume that the data is valid

Encrypted in transit, encrypted at rest, with asymmetric cipher

Something that will not incriminate you even if FBI blaze into your house unannounced.

A machine that self destructs readily.

A CCTV around your property to see if there is any FBI raid going on your property.

An alert system.

What if the cops raid you while you are sleeping?

How can one safely distribute something illegal without being anonymous?

https://en.wikipedia.org/wiki/Drug_precursors

"Porn precursors"?

Protocol
Take identifier space
Distributed secured DNS

Assume I contribute 1 CPU core, 1 GB RAM, and 100 GB disk to the network.
We don't want remote code execution yet. Let's focus on distributed storage first, to simplify things.
** Ethical engineering?
#TechWontBuildIt

If someone won't build it, will the company just find someone else who will?
Is there such person?

https://spectrum.ieee.org/view-from-the-valley/at-work/tech-careers/engineers-say-no-thanks-to-silicon-valley-recruiters-citing-ethical-concerns

https://arstechnica.com/gadgets/2018/12/the-web-now-belongs-to-google-and-that-should-worry-us-all/
** Technology for the people?
We need decent distributed systems.
Strategy:
- Mirror youtube, but don't steal from youtube.
- upload original content not in youtube.

Distributed email.

Distributed naming.

Routing authority problem.
Global addressing problem.
How do we give everyone a permanent internet address? RSA 2048-bit public key? Should we accept a nonzero minuscule probability of collision?
Everyone issues his own banknotes, like banks before Federal Reserve existed.
I issue a note "I owe John 5 meals".
Everyone issues his own notes, and let the market exchange works it out.
A note is a certificate of debt.
X did something for Y.
Y did something for Z.
https://en.m.wikipedia.org/wiki/Private_currency
Free banking
Private digital fiat complementary currency
Trusted third party guarantees notes?
A guarantor ensures that private notes are convertible to meals, for example by ensuring convertibility to USD.
A guarantor is responsible for checking that the issuer has the assets to back the issued notes, because a note is a certificate of debt.
A guarantor should personally know the issuer.
A guarantor limits the amount of currency an issuer can issue.
Credit US dollar:
If I give you C$1, it means I owe you $1.

Food sellers issue their own currencies.
For example, I can produce 100 meals, and I sell each meal for $1.

Big Mac credit
A McDonalds outlet takes 1 BMC and gives 1 Big Mac.
A McDonalds outlet issues 1 BMC for each Big Mac it can produce immediately.
** Liberating software?
- We wanted to liberate software.
  We end up at distributed systems.
- What are alternatives to Google?
  Are these real alternatives?
  Which are usable?
  - https://restoreprivacy.com/google-alternatives/
  - https://degooglisons-internet.org/en/
    - https://news.ycombinator.com/item?id=13140389
  - Google alternatives?
    - [[https://www.makeuseof.com/tag/5-google-search-alternatives-that-you-could-experiment-with/][The Top 5 Google Alternatives and Why You Should Use Them]]
- 2016, article, "The Fathers of the Internet Revolution Urge Today's Software Engineers to Reinvent the Web", Tekla S. Perry, [[https://spectrum.ieee.org/view-from-the-valley/telecom/internet/the-fathers-of-the-internet-revolution-urge-todays-pioneers-to-reinvent-the-web][html]].
  See the bulleted lists.
- Privacy violations
  - Android
    - Samsung Galaxy S8
      - Why does changing the theme require email address?
        This feature doesn't require email.
** Cryptocurrency?
- Blockchain, cryptocurrency, distributed ledger

  - What is blockchain?
  - What is cryptocurrency?
  - What is distributed ledger?
  - How are they related?
  - Is a Git repository a Merkel tree?

    - ??? Merkelization of a data structure is adding a cryptographic hash to every node?

- A possible cryptocurrency design?

  - A cryptocurrency that proves that W work has been done by A for B, anonymously. Is it possible?
  - Every principal has a keypair
  - Every principal creates a debt certificate and signs it with his private key
  - Every spending of a debt certificate distributes a revocation of that certificate
  - If a token is in the distributed database, it is assumed to be spent
  - Unforgeable digital token? Copy-once?
  - Record that A has paid N dollars to B
  - Blockchain

    - [[https://en.wikipedia.org/wiki/Blockchain][WP: Blockchain]]
    - "Once recorded, the data in any given block cannot be altered retroactively without the alteration of all subsequent blocks, which requires collusion of the network majority."

  - [[https://en.wikipedia.org/wiki/Homomorphic_encryption][https://en.wikipedia.org/wiki/Homomorphic_encryption]]
  - Blockchains are pseudonymous, not anonymous.

    - Is this legit? [[https://securingtomorrow.mcafee.com/mcafee-labs/staying-anonymous-on-the-blockchain-concerns-and-techniques/][https://securingtomorrow.mcafee.com/mcafee-labs/staying-anonymous-on-the-blockchain-concerns-and-techniques/]]

  - Cardano

    - [[https://en.wikipedia.org/wiki/Recursive_InterNetwork_Architecture_(RINA)][WP: Recursive InterNetwork Architecture (RINA)]]
    - formal verification?
    - Haskell programming language

  - [[http://theconversation.com/the-blockchain-does-not-eliminate-the-need-for-trust-86481][theconversation.com: The blockchain does not eliminate the need for trust]]

    - "The blockchain does not create or eliminate trust. It merely converts trust from one form to another.
      While we previously had to trust financial institutions to verify transactions, with the blockchain we have to trust the technology itself."
    - [[https://hackernoon.com/bitcoin-is-not-trustless-350ba0060fc9][hackernoon.com: Bitcoin is not trustless]]

  - Security is trust management.

    - Security is minimizing the required trust.

- Gold vs data: move vs copy

  - Gold doesn't need witness to be valuable.
  - Gold can be moved, but not copied.
    Data can't be moved, but can be copied.
    "Moving" data means copying it and deleting the original.
  - Unforgeable and anonymous

    - Gold is unforgeable and anonymous

      - Yes, you can forge gold with nuclear transmutation, but it's not cost-effective

        - so it's practically unforgeable

    - Private key is unforgeable and anonymous

      - Yes, you can forge private key with brute force, but it's not cost-effective

        - so it's practically unforgeable

  - Payment

    - Payment is made by moving the gold
    - Payment is made by moving the private key? But it's duplicated. Data can be copied, but not moved.

  - Double-spending is possible due to the easy-to-copy nature of digital data.
  - What is double-spending?

- Currency is a way of moving debt

  - Bitcoin white paper: [[https://bitcoin.org/bitcoin.pdf][Satoshi Nakamoto, "Bitcoin: A Peer-to-Peer Electronic Cash System"]]
  - Did SatoNak consider human greed, stupidity, and selfishness?

- Proof of ...

  - proof of work
  - proof of capacity
  - memory-bound functions / memory-hard challenges for spam filtering

- [[https://www.youtube.com/watch?v=6q5mUNEEn2c][YouTube: Real Engineering: Why Bitcoin Is Not Working]]
- [[https://blockchain-nus.github.io/][NUS blockchain research group]]
- What is Bitcoin?

  - Need review

    - Bitcoin is rare (and hard to fake) like gold,
      but it's digital in the sense that you can send it quickly over the Internet,
      so bitcoin is digital gold.
    - Bitcoin is not money, but a bitcoin exchange will accept it
      and give you an amount of money they think it's worth.
      You can exchange it with others' cash, goods, or services,
      but only if they accept bitcoin.
    - All the ruckus about bitcoin arises from mixing up
      the concept of
      [[https://en.wikipedia.org/wiki/Medium_of_exchange][medium of exchange]]
      and
      [[https://en.wikipedia.org/wiki/Unit_of_account][unit of account]]
      those are two of the
      [[https://en.wikipedia.org/wiki/Money#Functions][functions of money]].
    - Using bitcoin for payment is comparable to a [[https://en.wikipedia.org/wiki/Hawala][hawala]].
    - Bitcoin is only useful if people will exchange it with something else.

- [[https://bitcoinmagazine.com/articles/op-ed-how-tokenization-putting-real-world-assets-blockchains/][Op Ed: How Tokenization Is Putting Real-World Assets on Blockchains]]
* Political theory/research
** Politics basics: What is the difference between nation, state, country?
- https://tamayaosbc.wordpress.com/2010/11/19/basic-concepts-in-politics/
** Why do politicians diverge from their constituents' preferences?
https://www.researchgate.net/post/Why_do_politicians_diverge_from_their_constituents_preferences
** <2018-10-02> We don't want completely free-and-global trade because we don't want to depend too much to others.
*** Independence is necessary but not sufficient for sovereignty.
By depending on someone, you give him power over.
You weaken your bargaining power.
You worsen your negotiating position.
You reduce your sovereignty.

We must start strategic domestic industries, no matter how shitty it will be.
We can always improve it later.

<2018-10-03>
** Measuring trust between countries
*** The power of a country's passport tells how great that country is
https://www.passportindex.org/byRank.php

Your passport's power is proportional to how much the world trusts your country.
** Cipolla's laws of stupidity
- https://en.wikipedia.org/wiki/Carlo_M._Cipolla
- Cipolla's definition of "stupid":
  "A stupid person is a person who causes losses to another person or to a group of persons while himself deriving no gain and even possibly incurring losses."
** Why are the Norwegians so sensible? Why are their governments so good?
[[https://www.youtube.com/watch?v=b_l3eLhYbVo][Why The UK Lost Its Oil Wealth (And Why Norway Didn't) - YouTube]]

Every country has smart people.
Smart people are everywhere.
Why do countries fare differently?

* Abuses of power; reasons for anarchism (or even anti-statism)?
** Custom officers will seize your devices and breach your privacy.
Don't bring your devices in international travel
https://www.theguardian.com/world/2018/aug/25/sydney-airport-seizure-of-phone-and-laptop-alarming-say-privacy-groups

** You MUST have at least one camera in your car streaming the data to a remote safe location. Cops will trap you.
- https://www.youtube.com/watch?v=UpT-SAunuLk
- Busted! How to Handle the Police Until You Get a Lawyer - by Mary Griego https://www.youtube.com/watch?v=bmtIizXdh88
  - Ordering vs asking.
- We need to make sure that misbehaving cops are punished.
- 5 Rules for Recording Police: Steve Silverman of FlexYourRights.org https://www.youtube.com/watch?v=BHpQtvIxBJ4

** Class treason? Class traitors?
- https://en.wikipedia.org/wiki/Class_traitor
- police?
- human resources?
- every computer programmer working for government
** USA, Australia, imperialism, recent (19th-20th century) imperialism
Too bad there is no one fighting for the USA-oppressed island nations.

USA annexed (militarily occupied) Hawai'i from the locals.
https://www.youtube.com/watch?v=MfAiB2ZoRhM

USA annexed Puerto Rico from Spain who annexed it from the locals.
https://www.youtube.com/watch?v=g-GYqakwHdg

USA is not the only imperialist country though.

Australian imperialism

Honest Government Ad | Visit Timor-Leste! https://www.youtube.com/watch?time_continue=4&v=xqegTsi6SiE
- from https://www.reddit.com/r/indonesia/comments/9sbnyk/honest_government_ad_visit_timorleste/

** Political system is broken.
*** How Republicans and Democrats are different, and how they are the same.
**** How they differ
- Republicans scare you with dangers that don't exist, such as migrant invasions.
- Democrats excite you with benefits that don't exist, such as ever-increasing pensions.
**** How they are the same
- Both are liars.
- Both don't keep their promises.
- Both make the country worse off.

It's amazing that the USA can become the strongest nation in the world, despite the USA's dysfunctional political system.

Imagine what the USA could have been with a functional political system.
**** Why they behave that way: because they think short-term. Why do they think short-term? Because there are term limits.
**** Lying politicians should be sentenced to death. At least we should immediately vote them out of office.
**** The same thing happens in Indonesia. All parties are the same. The only difference is their religious stance.
***** TODO link that tirto.id article about party political spectrum
*** As long as we have political term limits, we will have popular-but-bad programs.
**** Politicians should not be time-limited. People should both elect politicans into office and elect politicians /out/ of office.
If politicians are time-limited, they will pander to the people and prioritize short-term gains.
**** We can vote people into office. Why can't we vote them /out/ of office?
* Important and urgent things for most (if not all) countries on Earth to do as soon as possible?
** Fixing the political system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-political-system
   :END:

- Restrict the form of all political campaigns to text containing the list of things the candidate wants to do.

  - Avoid pandering and toxic campaigns.

- Replace parliaments with sortition (randomly choosing people)?

  - TED: "What if we replaced politicians with randomly selected people? | Brett Hennig", [[https://www.youtube.com/watch?v=cUee1I69nFs][youtube]]
  - [[https://en.wikipedia.org/wiki/Sortition][WP:Sortition]]
  - Will sortition work in a homogeneous country?
    Won't it just promote groupthink?
  - How does sortition affect the minority?
    How should the population be sampled?
    Stratified sampling?

** Fixing the justice system
   :PROPERTIES:
   :CUSTOM_ID: fixing-the-justice-system
   :END:

- Change the justice system from retributive justice to restorative justice for the non-violent criminals.

  - Instead of locking up prisoners, let them repair the harm they did, and help them reintegrate into society.
  - Millions of people are being incarcerated.
    Their ability is being wasted.
    They are deprived of future.
    They will have difficulties reintegrating into society.
    Stigmatized.
    Like the homeless.
    This stigma makes it impossible for them to get financial stability and get out of the vicious circle of crime.

    - Also, prison initiation rituals are terrible.

  - There are two kinds of criminals:

    - /Perforce criminals/ commit crime to defend themselves from immediate bodily harm that threatens their existence.
      Examples are hungry moneyless people who steal food, and cornered people who kill.
      The solution is restorative justice, and giving work to the criminal for financial stability, helping them reintegrate into society.

      - If the threat is removed, perforce criminals no longer commit crime.

    - /Non-perforce criminals/ commit crime for anything else.
      Examples are psychopaths (people with physical inability to weigh bad consequences because their brains are wired differently).
      The solution is unbreeding: modify them by gene therapy or psychological therapy or whatever technology, or kill them if they can't change,
      but only after we have proven that they can't change.

      - See also [[https://www.theatlantic.com/magazine/archive/2017/06/when-your-child-is-a-psychopath/524502/][theatlantic.com: When your child is a psychopath]].

  - Prisons should not exist.
    There should exist only two kinds of punishment:

    - Forced labor, for perforce criminals, to repair the harm they did.
      The state must also help them reintegrate into society.
    - Death penalty, for non-perforce criminals.

  - In any case, nobody should be locked up for so long.
    Locking up people wastes resource.

** Should we limit inheritance?
   :PROPERTIES:
   :CUSTOM_ID: should-we-limit-inheritance
   :END:

https://taxfoundation.org/estate-and-inheritance-taxes-around-world/

Should we have any tax at all?

Should government funding be voluntary?

** A government is to maximize the well-being of its people
   :PROPERTIES:
   :CUSTOM_ID: a-government-is-to-maximize-the-well-being-of-its-people
   :END:

- A government is to:

  - do things that benefit many but do not benefit a few, such as building roads;
  - prevent things that benefit few but do not benefit many, such as committing crime.

- A government is to minimize negative [[https://en.wikipedia.org/wiki/Externality][externality]]
  and [[https://en.wikipedia.org/wiki/Rent-seeking][rent-seeking]].
- A government is to prevent the [[https://en.wikipedia.org/wiki/Tragedy_of_the_commons][tragedy of the commons]].

** Ungrouped content
   :PROPERTIES:
   :CUSTOM_ID: ungrouped-content
   :END:

A modern government is designed to minimize the damage if a bad person rises to the top,
not to maximize the benefit if a good person rises to the top.
That is why a republic has checks and balances.
The most efficient government is a benevolent competent dictator,
but does such person exist?

The government is a monopoly, and it should seek profit for its stakeholders: all its people.
Government official corruption, similar to corporate management corruption,
is a [[https://en.wikipedia.org/wiki/Principal%E2%80%93agent_problem][principal-agent problem]].
Everything that solves the principal-agent problem also solves corruption.

** Deciding what governments should do
   :PROPERTIES:
   :CUSTOM_ID: deciding-what-governments-should-do
   :END:

Use this quadrant:

- Axis 1: Does it benefit many people?
- Axis 2: Does it benefit a few people?

Things that benefit many and benefit few are best left to the private sector
with as little regulation as needed to keep the market healthy.

Things that benefit many but disadvantage few should be done by the public sector,
because the private sector will not do them because they don't get money doing that.
Example: building road.

Things that disadvantage many but benefit few should be prevented by the government.
Example: rent-seeking (bribing, lobbying,
speculation of non-fungible goods such as land parcels and Internet domain names),
crime, terrorism.

Things that disadvantage many and disadvantage few should also be discouraged by the government.
Example: road rage, human stupidity.

** Tips from our ancestors
   :PROPERTIES:
   :CUSTOM_ID: tips-from-our-ancestors
   :END:

I do not always agree with Lenin, but I agree with this sentence of his:

#+BEGIN_QUOTE
  When it is not immediately apparent which political or social groups,
  forces or alignments advocate certain proposals, measures, etc.,
  one should always ask: "Who stands to gain?"

  Vladimir Ilyich Ulyanov a.k.a. Lenin (1870--1924)
  ([[https://www.marxists.org/archive/lenin/works/1913/apr/11.htm][source]])
#+END_QUOTE

That was 1913.
In 1976 that could be more simply put as [[https://en.wikipedia.org/wiki/Follow_the_money][follow the money]].

** Ramble
   :PROPERTIES:
   :CUSTOM_ID: ramble
   :END:

- A government should only do things that better its people.

  - How do we know if something will make people better off?

- Is Chinese government dominated by scientists and engineers?

  - https://gineersnow.com/leadership/chinese-government-dominated-scientists-engineers

- https://www.quora.com/What-would-a-government-designed-by-engineers-and-not-politicians-look-like?share=1

  - https://tomgrego.blogspot.com/2010/12/a-government-you-can-love.html
  - https://www.quora.com/Concretely-what-can-we-do-to-get-US-politics-working-What's-gone-wrong-and-why-are-things-worse-than-20-years-ago-How-could-US-politics-improve-in-10-years-What-short-term-tactics-could-advance-the-long-term-goal?share=1

- The public sector is inefficient, but the private sector might be too efficient (extracting too much profit? but how much profit is too much?)?
  Is there a mixture between the two?
  Regulated private sector?
- https://en.wikipedia.org/wiki/Monopoly_on_violence

  - https://en.wikipedia.org/wiki/Justification_for_the_state

- https://www.bbc.com/news/uk-politics-42570823
- https://www.quora.com/Are-there-any-countries-without-government
- If healthcare were affordable, would we still need insurance?
- We don't need insurance.
  We need affordable healthcare.
- http://time.com/4937691/americans-cheap-healthcare-instantly/
- https://www.bloomberg.com/news/articles/2018-05-15/doctors-who-hate-insurance-so-much-they-go-without-it-themselves
- https://www.quora.com/What-do-doctors-think-about-insurance-companies
- What makes healthcare so expensive?

  - Definitely not the general practitioners (non-specialist doctors).
    They charge the patient only about $20 per visit.
  - Hospitals?
  - Drugs?
  - Insurances?

- argument for government, the necessity of government

  - https://www.quora.com/Why-have-so-few-humans-realized-that-governments-are-unnecessary

- https://en.wikipedia.org/wiki/Night-watchman_state
- If taxes were voluntary, would people pay tax?
- https://en.wikipedia.org/wiki/Voluntary_taxation

** The world should have only one country, one government, one law.
   :PROPERTIES:
   :CUSTOM_ID: the-world-should-have-only-one-country-one-government-one-law.
   :END:

Having many countries causes legal loopholes.

If there is only one country, there will be no tax tricks, tax havens.

There would be no illegal immigrants.
Everyone would be a world citizen.

- https://www.quora.com/Why-cant-all-the-earth-countries-unite-to-make-a-single-federation
* Designing a lovable government?

** Purpose

The highest law is the will of the people.
The people can change the constitution.

|                         | benefits few    | does not benefit few      |
| benefits many           | good business   | road-building             |
| does not benefit many   | crime           | self-defeating behavior   |
#+CAPTION: Examples of actions according to beneficiaries

Economically, government is to maximize positive externality,
and minimize negative externality.

Example negative externality:
road congestion due to residential space transforming to commercial space.

** Policy

Do the simplest intervention with the least effort,
the greatest effect, the least gameability,
the least unintended consequences.
But those are conflicting requirements.

Example: even-odd license plate based on day of month.
People will game this by buying two license plates or buying two vehicles.

Avoid wasting resources on policies that
do not attack the root cause of the problem.

** Murder

Why is something illegal?
Perpetrators are going to perpetrate anyway,
and non-perpetrators are not going to perpetrate,
regardless of its illegality.

Some people commit crime unwillingly because they
want to continue living but they no see other way.
Some people are wired differently and commit crime like a pastime.

If something is illegal, why does a perpetrator still do it?
Is it futile to make anything illegal?
If it were not illegal, will it still be done?

Law cannot change human nature.
If you want to change human nature, study biology, not law.
Lawmaking must defer to human nature.

It is impossible to enforce a law if millions of people violate it at the same time.
If a law is against human nature, of course people will violate it.

Is it moral to force someone who enjoy murder not to murder?

** Morality

Government should not interfere in private matter
such as religion, insurance, and consensual sex.

If something does not harm anyone else other than the doer,
it should not be illegal.

We should help others,
but we should to the greatest extent avoid forcing
others to do anything against their will
even though doing that would be good for them.
Consequence: procreation is immoral because
it forces people to exist without their consent.

We can persuade, but we should not force, unless we are in war.

Consumption should be taxed, not income.

Alternative to taxation: donation, state-owned enterprise.

Stability.

In a republic, in an election, you don't pick the best candidate;
you pick the one that will do the least damage.

Holding a government position should not be profitable.
How do we prevent abuse of power?
By not giving power in the first place?
The people must have the final say.

** Banning

Banning something does not eliminate it.
Worse, banning it may also create a black market for it.

Regulate, don't ban.

** Sex

Blocking access to Internet porn sites does not work.

Banning prostitution creates black market.

Banning sex makes more people more curious.

It's part of human nature.

Family education.

** Drugs

Some people are curious.

** Patents

Alternative to patents:
Prize system:
People collect money for a problem,
and the sum is awarded to the inventors who solve the problem.

Another alternative: People can donate to inventors.

Another alternative: Assume that inventors do things
because they love to do that, and they want money, but don't want to get filthy rich.

How was the first people who invented spears rewarded,
if they were rewarded at all?

** Prevention of mass destruction

How does a government prevent
nuclear briefcase detonation,
water source poisoning,
asteroids hitting Earth,
and so on?

The amount of security is inversely proportional to the amount of trust.
If you could trust everybody, security would be unnecessary.
Republics are complicated because you can't trust the ruler.
Republics are designed to minimize the damage done by an evil ruler,
not to maximize the benefit done by a competent ruler.

The most efficient government is
benevolent competent kind laissez-faire minimalist absolute monarch,
but it is also the most risky.
Anything can happen if the ruler dies.

** Differences

Conventional government assumes that most humans are fundamentally evil.
New government assumes that most humans are fundamentally non-evil.

** Office

If you tell people to do something they don't want,
they will do their best to avoid it.
If they want to do it,
they will do it anyway without your telling them.
Thus, you don't tell people.
You simply let them do things,
help them do things,
get out of their way.

If you hire the people who don't want to do the things you want,
no amount of salary will fix it.
When you hire people, there is an intersection between what they want,
what you want, and what your organization wants.

In the office, there are so many things happening that it is too much
for one person to keep track what everyone else is doing.
You are the only person who knows what you really do.
Your supervisor, if any, is the second person to know what you do.
Others have even vaguer ideas about what you do.
But people can instinctively see whether you're doing well or not,
so if you're not doing well,
you must pretend that you were doing well,
and then suddenly you will do well.
If you think you're not doing well, if you doubt yourself,
then it will be a self-fulfilling prophecy.
Even if you are absolutely sure that your job is unimportant,
even if you keep stumbling,
you must unquestioningly believe that you are doing well.

In the office, what you do is less important
than what others think you do.

If you don't know what to do, walk around, and talk to people.

If you don't fit in one company,
maybe that's the company's fault.
But if you have tried three much-different companies
and still can't fit, maybe it's your fault.

Make friends.
People first.
Jobs second.

The number of processes is inversely proportional to the amount of trust.

How much trust are you convenient with?

There are people you naturally gravitate towards,
and people you naturally gravitate away from.
