#+TITLE: Techno-Anarchy Research Group
#+DATE: 2019-02-06 00:00:00 +0700
#+PERMALINK: /tech.html
#+OPTIONS: ^:nil
* How do we liberate people with technology?
I am looking for a technology that empowers people and liberates people, a technology that makes power centralization impractical.
I thought I could change the world with politics, but now I think politics only wastes time,
and now I think technology is the only hope for making something in the physical-law layer to bypass the convoluted human-made-law layer.
I think law should be principle-based, and justice should be restorative.
I think the world needs only one law: Try not to harm others.
Nobody bothers to fix the broken political systems.
Nobody even bothers to think.
Political systems are too expensive to fix; it is much cheaper to scrap them.
* What?
I [[file:usecom.html][use computers]].
I [[file:phone.html][buy a smartphone]] when my old smartphone becomes unusable.
I usually watch YouTube at 2x-3x speed; we can speed it up to 16x[fn::https://www.quora.com/Is-there-a-way-of-watching-YouTube-videos-at-higher-than-2x-speed].
* Why don't users use distributed systems?
Users don't care; they want software to just work.[fn::"Decentralized systems will continue to lose to centralized systems until
there's a driver requiring decentralization to deliver a clearly superior consumer experience."
http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html]

I find YaCy[fn::https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html] unusable:
its search result relevance is too far behind Google.
YaCy-related things
 [fn::https://loklak.org/ Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]
 [fn::https://chat.susi.ai/ SUSI.AI Chat - Open Source Artificial Intelligence]
seem to also suffer from usability issues.

We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
The pack might contain things like matrix.org, riot.im.
But why stop there?
Why not make free/libre distributed operating system[fn::https://en.wikipedia.org/wiki/Distributed_operating_system] with all those goodies preinstalled?

Example of federated/decentralized social networks:
Kari Nordmann's comment[fn::https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc]:
"Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo)"
* What are WhatsApp alternative?
<2019-01-31>
Facebook is merging WhatsApp?
We need an alternative with better privacy?
* How do we increase homemadeability?
Why do we want homemadeability?
Because homemadeability promotes equality, liberty, and anarchism.
/Everything/ should be homemadeable, including nuclear bombs.
Only when everyone can produce everything will we have equality and liberty.

Why is not everything homemadeable?

Does it make sense to use solar power (1000 W/m2) for nuclear transmutation?
#+BEGIN_EXAMPLE
E = mc2
9e16 J = 1 kg
1 J = 1.11e-17 kg
#+END_EXAMPLE

No.

How do we make nuclear transmutation homemadeable?
What prevents energy from turning into matter?
What prevents matter from turning into energy?
What prevents matter from breaking down?
Why is matter stable?
What is matter?
What is energy?
A mathematical quantity?
* How should we farm in cities?
I thought about [[file:subsist.html][starting a farm in the middle of Jakarta]],
but I put it on hold because I felt that the opportunity cost was too high.

The key to farming is to understand ecology, some botany (plant physiology and pathology), and nutrient cycle.

We should care more about phosphate run-off.
Phosphates are vital and non-renewable, like fossil fuel.
The bad news is that there is no cycle bringing back the phosphates from the sea to the land, unlike water with its hydrologic cycle.
* Biohacking?
Biohacking?[fn::https://www.theguardian.com/science/2018/sep/21/extreme-biohacking-tech-guru-who-spent-250000-trying-to-live-for-ever-serge-faguet]

Genetics is the biggest factor in how far we can build our body.[fn::https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting]
* Theoretical physics, philosophy of physics
I am [[file:nature.html][trying to understand physics]].

Why is it hard to convert between matter and energy?
What does QFT say?
(Related: Why isn't everything homemadeable?)
* Why does Bitcoin not work?
It's too slow.

It uses too much energy.

Satoshi assumes that the users are ideal anarchists.
Alas, the actual users are mostly mindless greedy humans who want to get money without working.
