#+TITLE: Techno-Anarchy Research Group
#+DATE: 2019-02-06 00:00:00 +0700
#+PERMALINK: /tech.html
#+OPTIONS: ^:nil
* How do we liberate people with technology?
I am looking for a technology that empowers people and liberates people, a technology that makes power centralization impractical.
I thought I could change the world with politics, but now I think politics only wastes time,
and now I think technology is the only hope for making something in the physical-law layer to bypass the convoluted human-made-law layer.
I think law should be principle-based, and justice should be restorative.
I think the world needs only one law: Try not to harm others.
Nobody bothers to fix the broken political systems.
Nobody even bothers to think.
Political systems are too expensive to fix; it is much cheaper to scrap them.

The system must assume the worst of humans:
they are lazy, greedy, stupid, clever at gaming the system, willing to cheat,
and short-sighted (bad at thinking about long chains of causes and long-term causes).

What do we mean by "physically undefeatable"?
We mean this.
For example, government officials are not going to nuke 7 billion disobedient people, because they would kill themselves if they did that.
For example, no legislator can make properly-used one-time pads breakable, because such breaking is a mathematical/physical impossibility.
Human law is not the supreme law.
Natural law is the supreme law.

Which is more practical:
crypto-anarchy, or inventing a biological agent that enables us to control other humans?

We prefer peaceful means.
We dislike revolutions.
We don't want to be in a revolution.
We want to convince people by reason, not by force.
* What?
I [[file:usecom.html][use computers]].
I [[file:phone.html][buy a smartphone]] when my old smartphone becomes unusable.
I usually watch YouTube at 2x-3x speed; we can speed it up to 16x[fn::https://www.quora.com/Is-there-a-way-of-watching-YouTube-videos-at-higher-than-2x-speed].

We don't do drugs.
We need the full capacity of our minds.
Drugs would impair us.

We aim to peacefully, rationally, technologically, and undefeatably actualize an anarchy where no person has too much power over others.
We dream of precluding power centralization, or, at least, preventing or impeding it,
in a physical way such that natural laws go against human-made laws.
We research science and technology, mostly physics, cryptography, and distributed computing, but only insofar as they concern techno-anarchy.
* What are WhatsApp alternative?
<2019-01-31>
Facebook is merging WhatsApp?
We need an alternative with better privacy?
* How do we increase homemadeability?
Why do we want homemadeability?
Because homemadeability promotes equality, liberty, and anarchism.
/Everything/ should be homemadeable, including nuclear bombs.
Only when everyone can produce everything will we have equality and liberty.

Why is not everything homemadeable?

Does it make sense to use solar power (1000 W/m2) for nuclear transmutation?
#+BEGIN_EXAMPLE
E = mc2
9e16 J = 1 kg
1 J = 1.11e-17 kg
#+END_EXAMPLE

No.

How do we make nuclear transmutation homemadeable?
What prevents energy from turning into matter?
What prevents matter from turning into energy?
What prevents matter from breaking down?
Why is matter stable?
What is matter?
What is energy?
A mathematical quantity?
* How should we farm in cities?
I thought about [[file:subsist.html][starting a farm in the middle of Jakarta]],
but I put it on hold because I felt that the opportunity cost was too high.

The key to farming is to understand ecology, some botany (plant physiology and pathology), and nutrient cycle.

We should care more about phosphate run-off.
Phosphates are vital and non-renewable, like fossil fuel.
The bad news is that there is no cycle bringing back the phosphates from the sea to the land, unlike water with its hydrologic cycle.
* Biohacking?
Biohacking?[fn::https://www.theguardian.com/science/2018/sep/21/extreme-biohacking-tech-guru-who-spent-250000-trying-to-live-for-ever-serge-faguet]

Genetics is the biggest factor in how far we can build our body.[fn::https://www.quora.com/Is-it-possible-for-a-skinny-guy-who-eats-trains-and-does-everything-right-to-get-Chris-Evans%E2%80%99-large-pecs-and-overall-muscular-look-If-so-how-long-Im-just-starting]
* Why does Bitcoin not work?
It's too slow.

It uses too much energy.

Satoshi assumes that the users are ideal anarchists.
Alas, the actual users are mostly mindless greedy humans who want to get money without working.
* Technology that liberates
Our goal is to create a technology that:
- distributes power to the people,
- keeps it distributed; prevents centralization

We need these technologies:
- a system that unrestrictably disseminates information
- a single global digital food-backed currency ($1 means the right to one meal)
- distributed electricity generation
- distributed web browser, hosting, and operating system

Physical laws is our only chance of defeating man-made laws.

Prosecutability/enforceability is more important than legality.
Being illegal does not always imply being prosecutable.
If nobody reports, the police has no case.
If there are too many criminals, the police can't do much.

Principles:
- You should not reap what you don't sow.
  Your wealth should be proportional to your contribution to society.
  You should not be entitled what you don't earn.
  If you don't work, you should not be paid.
  Abolish inheritance.
** Technology for anarchy: redistributing power back from government to the people
*** Anarchy
You should not be liable for what is not your fault.
If you are born disabled, it's not your fault.

But how can you work if you are disabled?
*** Technology for anarchy?
How do you host something without being liable for it?
For example, someone uploads porn to your distributed network.

Encryption-at-rest, and in transit, with tamper-resistant private key that self-destructs readily?

Even simpler.
Split the file into several parts, and host each part in different host.
Sorites paradox.
At how many bytes does a file contain porn?
If everyone is a criminal, then nobody is a criminal.

Currency tied to food price.
A meal should be nutritious and nourishing and healthy.
$1 = 1 meal.
Labor that enables the meal.
$1 = cooking 5 meals.
The cook creates a value of $5 but gets paid only $1.
Let everything be market.
$? = Creating a technology that enables us to make more meals.
$1 = protection for 8 hours.
How should we value art, programming, etc.? Let the market decide!
How does software enable us to create more meals?

If everyone takes more value than they create, the system collapses.

Cloud hosting is not a solution.
It's still centralized.
Your cloud provider decides what to host.
Government can crack cloud providers down.
*** Distributed-web browser?
Let's write a web browser library in Prolog.

2018-12-17 Tumblr bans all adult content.

Gnuzilla and IceCat has noble goals but does not solve the root cause of the problem: the centralization of power.
https://www.gnu.org/software/gnuzilla/

https://beakerbrowser.com/

We need to own our data.
We need to host our content ourselves.

We urgently need distributed web.

Distributed web is the only way for mankind and anarchy to flourish.

We need a web that cannot be controlled.

- Apple heavy-handed Tumblr into banning adult content.
- Google filter bubble

We need a currency whose value is tied to the value of food.

https://betanews.com/2018/12/04/duckduckgo-study-google-search-personalization/
*** Distributed (peer-to-peer) web, no central hosting
Prerequisites of success:
- infrastructure, search engine, directory, wiki, encyclopedia
- browsers installed in user machine

"Whoever controls the content’s location controls the content"
https://medium.com/textileio/enabling-the-distributed-web-abf7ab33b638

https://stackoverflow.com/questions/737560/why-is-p2p-web-hosting-not-widely-used
*** What
We need distributed web now
https://techcrunch.com/2018/12/05/australia-rushes-its-dangerous-anti-encryption-bill-into-parliament/amp/

We don't want blockchain. We don't want permanence.
The creator may delete a resource that he created.
The host may delete a resource that he is hosting.
Everyone generates a key pair.

Imagine that there is a chemical reaction A + B -> cocaine, and both A and B are legal.
I sell John 1 ton of A.
You sell John 1 ton of B.
John makes 2 tons of cocaine at his home.

It is illegal to sell cocaine, but is it illegal to sell cocaine-making machine and cocaine precursors?
It should be as legal as selling frying pan and salt!
A knife can harm people, but is it not illegal to sell a knife!
Drugs shouldn't be illegal in the first place!

AI deepfakes, fusion power, and nuclear transmutation will destroy inefficient courts and parasite lawyers.
If everything is easy to fake, then nothing stands as evidence.

Imagine that X is a 1 MB JPG file containing porn.
Divide the file into 1000 pieces.
Store each piece at a different host.

https://en.wikipedia.org/wiki/Crypto-anarchism

Every block must have a unique identifier.

Identifier
Hash
Length
Content
Duration
Lease
Does it have to be anonymous?

Hide in plain sight?

Index files.

Identifier can be used to identify the origin.

Generate random block identifier
Assert to network
If there is no objection after some time, assume that the data is valid

Encrypted in transit, encrypted at rest, with asymmetric cipher

Something that will not incriminate you even if FBI blaze into your house unannounced.

A machine that self destructs readily.

A CCTV around your property to see if there is any FBI raid going on your property.

An alert system.

What if the cops raid you while you are sleeping?

How can one safely distribute something illegal without being anonymous?

https://en.wikipedia.org/wiki/Drug_precursors

"Porn precursors"?

Protocol
Take identifier space
Distributed secured DNS

Assume I contribute 1 CPU core, 1 GB RAM, and 100 GB disk to the network.
We don't want remote code execution yet. Let's focus on distributed storage first, to simplify things.
** Ethical engineering?
#TechWontBuildIt

If someone won't build it, will the company just find someone else who will?
Is there such person?

https://spectrum.ieee.org/view-from-the-valley/at-work/tech-careers/engineers-say-no-thanks-to-silicon-valley-recruiters-citing-ethical-concerns

https://arstechnica.com/gadgets/2018/12/the-web-now-belongs-to-google-and-that-should-worry-us-all/
** Technology for the people?
We need decent distributed systems.
Strategy:
- Mirror youtube, but don't steal from youtube.
- upload original content not in youtube.

Distributed email.

Distributed naming.

Routing authority problem.
Global addressing problem.
How do we give everyone a permanent internet address? RSA 2048-bit public key? Should we accept a nonzero minuscule probability of collision?
Everyone issues his own banknotes, like banks before Federal Reserve existed.
I issue a note "I owe John 5 meals".
Everyone issues his own notes, and let the market exchange works it out.
A note is a certificate of debt.
X did something for Y.
Y did something for Z.
https://en.m.wikipedia.org/wiki/Private_currency
Free banking
Private digital fiat complementary currency
Trusted third party guarantees notes?
A guarantor ensures that private notes are convertible to meals, for example by ensuring convertibility to USD.
A guarantor is responsible for checking that the issuer has the assets to back the issued notes, because a note is a certificate of debt.
A guarantor should personally know the issuer.
A guarantor limits the amount of currency an issuer can issue.
Credit US dollar:
If I give you C$1, it means I owe you $1.

Food sellers issue their own currencies.
For example, I can produce 100 meals, and I sell each meal for $1.

Big Mac credit
A McDonalds outlet takes 1 BMC and gives 1 Big Mac.
A McDonalds outlet issues 1 BMC for each Big Mac it can produce immediately.
** Liberating software?
- We wanted to liberate software.
  We end up at distributed systems.
- What are alternatives to Google?
  Are these real alternatives?
  Which are usable?
  - https://restoreprivacy.com/google-alternatives/
  - https://degooglisons-internet.org/en/
    - https://news.ycombinator.com/item?id=13140389
  - Google alternatives?
    - [[https://www.makeuseof.com/tag/5-google-search-alternatives-that-you-could-experiment-with/][The Top 5 Google Alternatives and Why You Should Use Them]]
- 2016, article, "The Fathers of the Internet Revolution Urge Today's Software Engineers to Reinvent the Web", Tekla S. Perry, [[https://spectrum.ieee.org/view-from-the-valley/telecom/internet/the-fathers-of-the-internet-revolution-urge-todays-pioneers-to-reinvent-the-web][html]].
  See the bulleted lists.
- Privacy violations
  - Android
    - Samsung Galaxy S8
      - Why does changing the theme require email address?
        This feature doesn't require email.
** Cryptocurrency?
- Blockchain, cryptocurrency, distributed ledger

  - What is blockchain?
  - What is cryptocurrency?
  - What is distributed ledger?
  - How are they related?
  - Is a Git repository a Merkel tree?

    - ??? Merkelization of a data structure is adding a cryptographic hash to every node?

- A possible cryptocurrency design?

  - A cryptocurrency that proves that W work has been done by A for B, anonymously. Is it possible?
  - Every principal has a keypair
  - Every principal creates a debt certificate and signs it with his private key
  - Every spending of a debt certificate distributes a revocation of that certificate
  - If a token is in the distributed database, it is assumed to be spent
  - Unforgeable digital token? Copy-once?
  - Record that A has paid N dollars to B
  - Blockchain

    - [[https://en.wikipedia.org/wiki/Blockchain][WP: Blockchain]]
    - "Once recorded, the data in any given block cannot be altered retroactively without the alteration of all subsequent blocks, which requires collusion of the network majority."

  - [[https://en.wikipedia.org/wiki/Homomorphic_encryption][https://en.wikipedia.org/wiki/Homomorphic_encryption]]
  - Blockchains are pseudonymous, not anonymous.

    - Is this legit? [[https://securingtomorrow.mcafee.com/mcafee-labs/staying-anonymous-on-the-blockchain-concerns-and-techniques/][https://securingtomorrow.mcafee.com/mcafee-labs/staying-anonymous-on-the-blockchain-concerns-and-techniques/]]

  - Cardano

    - [[https://en.wikipedia.org/wiki/Recursive_InterNetwork_Architecture_(RINA)][WP: Recursive InterNetwork Architecture (RINA)]]
    - formal verification?
    - Haskell programming language

  - [[http://theconversation.com/the-blockchain-does-not-eliminate-the-need-for-trust-86481][theconversation.com: The blockchain does not eliminate the need for trust]]

    - "The blockchain does not create or eliminate trust. It merely converts trust from one form to another.
      While we previously had to trust financial institutions to verify transactions, with the blockchain we have to trust the technology itself."
    - [[https://hackernoon.com/bitcoin-is-not-trustless-350ba0060fc9][hackernoon.com: Bitcoin is not trustless]]

  - Security is trust management.

    - Security is minimizing the required trust.

- Gold vs data: move vs copy

  - Gold doesn't need witness to be valuable.
  - Gold can be moved, but not copied.
    Data can't be moved, but can be copied.
    "Moving" data means copying it and deleting the original.
  - Unforgeable and anonymous

    - Gold is unforgeable and anonymous

      - Yes, you can forge gold with nuclear transmutation, but it's not cost-effective

        - so it's practically unforgeable

    - Private key is unforgeable and anonymous

      - Yes, you can forge private key with brute force, but it's not cost-effective

        - so it's practically unforgeable

  - Payment

    - Payment is made by moving the gold
    - Payment is made by moving the private key? But it's duplicated. Data can be copied, but not moved.

  - Double-spending is possible due to the easy-to-copy nature of digital data.
  - What is double-spending?

- Currency is a way of moving debt

  - Bitcoin white paper: [[https://bitcoin.org/bitcoin.pdf][Satoshi Nakamoto, "Bitcoin: A Peer-to-Peer Electronic Cash System"]]
  - Did SatoNak consider human greed, stupidity, and selfishness?

- Proof of ...

  - proof of work
  - proof of capacity
  - memory-bound functions / memory-hard challenges for spam filtering

- [[https://www.youtube.com/watch?v=6q5mUNEEn2c][YouTube: Real Engineering: Why Bitcoin Is Not Working]]
- [[https://blockchain-nus.github.io/][NUS blockchain research group]]
- What is Bitcoin?

  - Need review

    - Bitcoin is rare (and hard to fake) like gold,
      but it's digital in the sense that you can send it quickly over the Internet,
      so bitcoin is digital gold.
    - Bitcoin is not money, but a bitcoin exchange will accept it
      and give you an amount of money they think it's worth.
      You can exchange it with others' cash, goods, or services,
      but only if they accept bitcoin.
    - All the ruckus about bitcoin arises from mixing up
      the concept of
      [[https://en.wikipedia.org/wiki/Medium_of_exchange][medium of exchange]]
      and
      [[https://en.wikipedia.org/wiki/Unit_of_account][unit of account]]
      those are two of the
      [[https://en.wikipedia.org/wiki/Money#Functions][functions of money]].
    - Using bitcoin for payment is comparable to a [[https://en.wikipedia.org/wiki/Hawala][hawala]].
    - Bitcoin is only useful if people will exchange it with something else.

- [[https://bitcoinmagazine.com/articles/op-ed-how-tokenization-putting-real-world-assets-blockchains/][Op Ed: How Tokenization Is Putting Real-World Assets on Blockchains]]
* What?
Broadcasting a packet is like shouting as loud as you can and hoping that someone hears you.

TODO make new page tech.pro: technology that liberates, distributed system, techno-anarchistic/good/anti-government/anti-state/anti-oppression/pro-individual technology,

Technologies that maximize individual freedom without destroying society

How can each person feed thonself?
What technology?

3D-printable guns
https://www.dailywire.com/news/22283/diy-untraceable-handguns-crypto-anarchist-cody-amanda-prestigiacomo

global meshnet
https://www.newsbtc.com/2017/01/17/the-inevitable-march-of-techno-anarchy/

Radio network for spreading data with no possible government control?
Unjammable?

https://www.cse.wustl.edu/~jain/cse574-16/ftp/dist_rdo/index.html
Distributed wireless?

DNS gives rise to domain rent seekers.
But how do we globally agree upon names without DNS?

Why do we need ISPs?
Why can't each family be its own ISP?
https://superuser.com/questions/900021/how-to-internet-without-isp

ISP-less internet
Internet without ISP
http://www.neuralmap.com/archives/an-isp-less-internet/

https://www.reddit.com/r/AskTechnology/comments/14ekah/a_couple_years_ago_i_read_about_this_project_to/
* Naming?
** How do we name every network node?
Should we name network nodes in the way humans name humans?

Is everything truly solvable by one more indirection?
Does this global naming problem respect David Wheeler's aphorism "All problems in computer science can be solved by another level of indirection"[fn::https://en.wikipedia.org/wiki/Indirection]?

Should every node decide its own name?
If every node decide its own name, then names may clash.

How do parents name their children?
How do humans name humans?
Who picks a name for the child?
A parent?
The family?
The community?
** What is a name?
A name is a reference.

"John" refers to that blob of matter over there?

https://www.reddit.com/r/askscience/comments/fiew1/when_did_humans_start_to_use_names_to_refer_to/
** How do humans name humans?
If many people with the exact same name are in the same group, then they decide their /local names/.

Imagine that there are 5 people named the exact same "John Smith" in the same group.
There must be differences: one may have white hair, one may be fat, one may be tall, etc.
They may name themselves "John White", "White John", "Fat John" or "John Smith the Fat" or "John 'Fat' Smith", "Tall John", "Texas John", "Old John", "Wise John", "Mark", etc.

"John" means "Jehovah has favored"[fn::https://www.etymonline.com/word/John].
"Matthew" means "gift of Jehovah"[fn::https://www.etymonline.com/word/Matthew].

"Sitting Bull" is English translation of his native Lakota name[fn::https://en.wikipedia.org/wiki/Sitting_Bull].
"Mississippi" means "big river"[fn::https://www.etymonline.com/word/Mississippi].
"Ontario" means "beautiful lake"[fn::https://www.etymonline.com/word/Ontario].

Names do not have to be meaningful.
For example, in principle, nothing prevents a father from regrettably naming his child "Tralala" or "Hmph".

Every word is indeed a name of a concept.

https://plato.stanford.edu/entries/names/


https://spectrum.ieee.org/tech-talk/telecom/internet/could-russia-really-build-its-own-alternate-internet

Trade-offs of naming-system designs.
https://www.afnic.fr/en/resources/publications/issue-papers/alternative-naming-systems-to-the-dns-2.html

How do we have Internet without central authority/registry?

https://en.wikipedia.org/wiki/Mesh_networking
* Questions that we have to answer before we may subscribe to anarchism
** How would an anarcho-syndicalist society build roads, rockets, and other big projects that require massive coordination?
** Do we really want anarchy?
Have we read and understood Hobbes's state of nature of humans?
* Designing a web browser
** Why stop at web browser?
What we want is not a web browser.
What we want is a user interface for the Internet.

We should dream more about the browser.
We should have an Information Agent instead of a browser.
But this risks scope creep; we'll end up making an operating system.
Indeed Firefox and Chrome has already done that with Firefox OS and Chrome OS.[fn::https://www.quora.com/Why-did-the-Chrome-OS-succeed-but-the-Firefox-OS-failed]

The browser should also be a crowd-sourced search engine and a peer-to-peer web hosting?

Opennic
https://mastodon.ar.al/@aral/101714998469668580

Rethinking the web browser

https://refresh.study
** What is the most important thing of a web browser?
The user is in full control of everything, including the content displayed to him.
The user can program the browser to transform badly-designed websites.
The user should not need to install a plugin such as Greasemonkey, Tampermonkey,
or any other "user script manager" to have full control of what is displayed.
** Why do browsers have history?
What is the chance that the user asks one of these:
- What did I just browse?
- What did I browse yesterday?

What is the chance that the user wants to revisit something?

I myself often need that.

https://www.computerhope.com/issues/ch001871.htm
** How hard is it to secure a browser?
Very hard.

We may think that API A is secure and API B is secure,
but when we use them together, A+B may not be secure.
 [fn::https://www.ghacks.net/2018/11/04/browser-history-sniffing-is-still-a-thing/]

How do we make systems whose security is composable?

How do we prove that a system is secure?
How should we model security?

\cite{barthe2017provably} is a possibility.
But what if new unforeseen side-channel attacks appear in the future?

We must model the time and energy usage of each CPU instruction.
But the CPU is not open source?
** Parts of a browser
- cache and history
- HTTP
- HTML parsing
- rendering HTML DOM to GUI widgets

What we choose /not/ to do:
- plug-ins, extensions
- themes, customizations

Who are going to maintain the plugins?

Should we just embed WebKit?

https://www.paulirish.com/2013/webkit-for-developers/
** Search engine?
Is AntRank[fn::http://www.ijettcs.org/Volume3Issue2/IJETTCS-2014-04-23-113.pdf] usable?

I find YaCy[fn::https://www.pcworld.com/article/245414/yacy_its_about_freedom_not_beating_google.html] unusable:
its search result relevance is too far behind Google.
YaCy-related things
 [fn::https://loklak.org/ Loklak Search - Distributed Open Source Search for Twitter and Social Media with Peer to Peer Technology]
 [fn::https://chat.susi.ai/ SUSI.AI Chat - Open Source Artificial Intelligence]
seem to also suffer from usability issues.

Unfortunately, it's 2019, NAT is still common, and I don't see IPv6 anywhere near my computer.

Perhaps it is a bad idea to allow /every/ device to be connected to the Internet.
Weakly-passworded IP cameras were hijacked and put into a botnet.
** Why don't users use distributed systems?
Users don't care; they want software to just work.[fn::"Decentralized systems will continue to lose to centralized systems until
there's a driver requiring decentralization to deliver a clearly superior consumer experience."
http://highscalability.com/blog/2018/8/13/what-do-you-believe-now-that-you-didnt-five-years-ago.html]

We should make a "freedom pack": an installer of essential free/libre open-source distributed-web applications.
The pack might contain things like matrix.org, riot.im.
But why stop there?
Why not make free/libre distributed operating system[fn::https://en.wikipedia.org/wiki/Distributed_operating_system] with all those goodies preinstalled?

Example of federated/decentralized social networks:
Kari Nordmann's comment[fn::https://medium.com/@rxpvh2000/where-are-the-programmers-who-give-a-shit-d27ad2ef24fc]:
"Explore federated (decentralized) social networks (Mastodon, diaspora*, Friendica, Hubzilla, GNU Social, Socialhome, Pleroma, GangGo)"
* How do we make CPUs?
How do we make machines that makes smaller machines?

How are the first CPUs made?

Nanotechnology?[fn::http://trynano.org/about/history-nanotechnology]
