#+TITLE: Jalankan usaha
#+DATE: 2016-01-01 00:00 +0700
#+PERMALINK: /usaha.html
#+OPTIONS: ^:nil toc:nil
* Memahami dasar hukum
** Peraturan yang berkaitan
- UUPT adalah UU 40/2007 tentang perseroan terbatas ([[http://peraturan.go.id/uu/nomor-40-tahun-2007.html][html]]).
- UUTK adalah UU 13/2003 tentang ketenagakerjaan.
  - <2018-01-24> https://www.hukumonline.com/berita/baca/hol7529/uu-ketenagakerjaan-baru Beberapa pasal ada yang dicabut.
- UUHC adalah UU 28/2014 tentang hak cipta ([[http://www.dgip.go.id/images/ki-images/pdf-files/hak_cipta/uu_pp/uu_hc_%2028_2014.pdf][pdf]]).
- KUHPer adalah Kitab Undang-undang Hukum Perdata.
*** Notasi singkatan untuk rujukan
"UU 40/2007" berarti UU no 40 tahun 2007.

"UUPT 3:2" berarti UUPT pasal 3 ayat 2.
*** Lain-lain?
UU pasar modal

UUPT 36:1: Ownership graph must be acyclic.

http://m.hukumonline.com/index.php/klinik/detail/lt4ee1cdcb3b9fc/status-direksi-perusahaan--pengusaha-atau-pekerja-revisi

https://www.hukumonline.com/klinik/detail/lt51b0380e6b9f8/bolehkah-menggeser-hari-libur-karyawan-tanpa-memberi-upah-lembur
Tidak boleh.

http://www.hukumperseroanterbatas.com/anggaran-dasar/anggaran-dasar-perseroan-terbatas/

https://www.hukumonline.com/klinik/detail/lt4cd0bd0284a71/perbedaan-modal-dasar--modal-ditempatkan--dan-modal-disetor-pt

https://media.neliti.com/media/publications/14073-ID-aspek-hukum-kelalaian-menyetorkan-modal-dalam-prosespendirian-perseroan-terbatas.pdf

UU Yayasan[fn::https://www.putra-putri-indonesia.com/undang-undang-yayasan.html]
- UU 16/2001
- diubah dengan UU 28/2004
- PP 63/2008

UU Pajak[fn::https://id.wikipedia.org/wiki/Perpajakan_di_Indonesia]
- Susunan dalam satu naskah undang-undang perpajakan 2011[fn::http://www.pajak.go.id/sites/default/files/PersandinganUUPerpajakan.pdf]
- UUPPh tentang pajak penghasilan
- UUDP adalah UU 11/1992 tentang dana pensiun.

UUPPh 4:3L Beberapa beasiswa bukan objek pajak?
** Badan hukum dan badan usaha
- https://id.wikipedia.org/wiki/Badan_hukum
- https://id.wikipedia.org/wiki/Badan_usaha#BUMS
- https://id.wikipedia.org/wiki/Perseroan_terbatas
- http://www.gresnews.com/berita/tips/82855-peraturan-badan-hukum-usaha-perseorangan/
*** A company is a virtual person. Can it be imprisoned?
https://slate.com/news-and-politics/2002/04/can-a-company-be-charged-with-a-crime.html
*** The corporate veil can be lifted according to UUPT 3:2.
** Mendirikan perusahaan?
- Bagaimana?
- Bayar berapa?
- Berapa lama?
- Apa keuntungan pajak?
*** Permudah pembuatan badan usaha?
Bikin lebih mudah daripada Singapura, Hong Kong, USA, Estonia.

Tahun 2018, bikin PT di Indonesia masih terlalu sulit.
Mungkin harus tunggu sampai tahun 2025.

Cabut batasan nama PT tiga suku kata tanpa mengandung bahasa atau serapan asing.

- Cabut batasan PT harus punya alamat? Cukup alamat email?
  - Tidak bisa. PT harus punya alamat karena ada kebutuhan birokrasi surat menyurat.
- Indonesia
  - https://easybiz.id/prosedur-dan-syarat-pendirian-pt-terbaru-yang-wajib-anda-ketahui/
  - https://prolegal.id/2018/04/11/prosedur-syarat-pendirian-pt-2018/
- https://www.quora.com/Which-country-has-the-easiest-procedure-for-a-foreigner-to-start-a-business
- ga jelas, agak shady
  - https://flagtheory.com/the-best-place-for-an-internet-entrepreneur-to-incorporate/
  - http://nomadcapitalist.com/2016/05/25/best-country-online-company-incorporation/

Prosedur yang ideal?

- Applicant obtains approval of target neighborhood if necessary (if company operation is disturbing).
- Applicant registers company data.
- Government issues a legal certificate and a tax subject number.
- Done.

[[https://www.bps.go.id/website/fileMenu/Perka-KBLI-2015.pdf][KBLI 2015]] untuk PT yang bergerak di bidang software engineering dan programming language research:

- J.62, hlm. 402
- M.72, hlm. 439
**** <2018-10-05> Birokrasi Jakarta tidak bagus-bagus amat, tapi di luar Jakarta lebih parah lagi?
- https://medium.com/asepbagja/pengalaman-mengagumkan-mendaftarkan-perusahaan-di-estonia-33e2c10d7028:
  - 'Waktu itu notaris saya cuma bilang, "kalau mengurus di Tangerang akan sedikit lebih lama loh birokrasinya, Mas, dibanding Jakarta. Bisa beda sekitar 2 bulan."
    Saya pun setuju. Perkiraan saya paling juga Mei 2017 udah beres. Ternyata meleset hingga 6 bulan!'
  - "Update terbaru: Akhirnya beres setelah *9 bulan*!"
* Mendirikan PT
** Modal Disetor disetor ke mana?
** Anggaran Dasar
Di sini "anggaran" berarti "aturan".
** Mengangkat Direksi dan Dewan Komisaris
Direksi minimal 1 orang.

Dewan Komisaris minimal 1 orang.

Satu orang tidak boleh sekaligus menjabat sebagai Direksi dan Komisaris.
** System for operating companies/enterprises: accounting, payroll, legal, tax, reporting, ERP, SCM, recruiting, ATS, etc.
openbravo, odoo
https://blog.capterra.com/top-8-freeopen-source-applicant-tracking-software-solutions/

Accounting system

Rekening bank pt

<2018-10-08> experimental:
- AISCO "Adaptive Information System for Charity Organization"
  from 2017 article "Feature Model-to-Ontology for SPL Application Realisation"
  https://arxiv.org/pdf/1707.02511.pdf
  http://www.aiscoweb.org/
** Virtual office Jakarta? Barat? Selatan?
* Kewajiban rutin
** Laporan tahunan
** Laporan pajak tiap bulan?
* Perencanaan pajak: bentuk usaha paling efisien pajak?
- [[http://ortax.org/ortax/?mod=issue&page=show&id=85&list=1&q=&hlm=2][ortax.org: Memilih Bentuk Usaha Yang Tepat Bagi Perencanaan Pajak]]
* Tanggung jawab sosial dan lingkungan (TJSL) / corporate social responsibility (CSR)
- https://kliklegal.com/mengenal-sejumlah-regulasi-yang-mengatur-csr-di-indonesia/
* Mempekerjakan orang lain
** partnership vs employment: Bagaimana membedakan kontrak kerja sama dan kontrak ketenagakerjaan? Kontrak kemitraan vs kontrak kerja? Kontrak biasa vs kontrak kerja?
- https://www.hukumonline.com/berita/baca/hol20668/saat-hubungan-kemitraan-menjadi-hubungan-kerja
- https://www.hukum-hukum.com/2017/06/modus-menjadikan-pekerja-sebagai-mitra.html

To simplify operations, always partner, never employ.
Employment is heavily regulated because employment breeds inequality.

How do you partner with an accountant?
How do you partner with a supervisor?
How do you partner with a customer service officer?
How do you partner with operational staffs?

Is partnership always possible?

https://gajimu.com/pekerjaan-yanglayak/kompensasi/jam-kerja

** Hak cipta, work-for-hire, IP (intellectual property) rights, HAKI/HKI (hak kekayaan intelektual)
*** TODO Cek UUHC: apa bisa lisensi: hak bebas royalti non-eksklusif yang tidak bisa ditarik kembali
*** Employee IP (intellectual property) assignment is unfair
Employee IP assignment is the practice where a company owns whatever its employees make.

Employee IP assignment is unfair and should be replaced with, at most, an irrevocable non-exclusive royalty-free license.

Employee IP assignment gives the company too much power over its employees.

Employee IP assignment contributes to inequality / social gap / wealth gap.
*** <2018-10-04> Tentang UUHC.
/Berikut interpretasi saya, bukan teks resmi. Saya mungkin salah. Ini bukan pendapat hukum yang sah./

Pasal 18: Hak Cipta tidak bisa dialihkan selamanya; ada batas waktu 25 tahun.
(Bagaimana jika Pemegang Hak Cipta meninggal sebelum 25 tahun berlalu sejak pengalihan?)

Pasal 36: "Kecuali diperjanjikan lain, Pencipta dan Pemegang Hak Cipta atas Ciptaan yang dibuat dalam hubungan kerja atau berdasarkan pesanan yaitu pihak yang membuat Ciptaan."
Ini berarti "Pencipta" dan "Pemegang Hak Cipta" bisa didefinisikan ulang oleh perjanjian kerja.

Bagian ketiga ("Hasil Karya yang Tidak Dilindungi Hak Cipta")

Pasal 41: "Hasil karya yang tidak dilindungi Hak Cipta meliputi: [...]
b. setiap ide, prosedur, sistem, metode, konsep, prinsip,
temuan atau data walaupun telah diungkapkan,
dinyatakan, digambarkan, dijelaskan, atau digabungkan
dalam sebuah Ciptaan; dan [...]"

Pasal 41 huruf b sangat rancu.
Penjelasannya berkata "cukup jelas".

Pasal 50:
"Orang dilarang melakukan Pengumuman,
Pendistribusian, atau Komunikasi Ciptaan yang bertentangan
dengan moral, agama, kesusilaan, ketertiban umum, atau
pertahanan dan keamanan negara."
Bahaya.
Pasal karet.
Bagaimana menentukan sesuatu itu bertentangan dengan moral/agama atau tidak?

Pasal 57: Beberapa hak moral berlaku selamanya.

Pasal 58 ayat 3:
"Pelindungan Hak Cipta atas Ciptaan sebagaimana dimaksud pada ayat (1) dan ayat (2) yang dimiliki atau dipegang oleh badan hukum berlaku selama 50 (lima puluh) tahun sejak pertama kali dilakukan Pengumuman."
** Can employer-employee relations be replaced with buyer-seller relations?
Can a factory worker be allowed to work at any time he wants, at any duration he wants, and be paid by the amount of things he sold to his direct buyer?
** Direktur bukan karyawan, kecuali memang sebelumnya sudah karyawan
Bolehkah direktur bekerja tanpa digaji?
Boleh asal direkturnya bukan karyawan/pekerja/employee (hubungan kerja).
http://strategihukum.net/strategi-hukum-mengangkat-karyawan-menjadi-direktur
* Perluas bidang usaha
There are 26.71 million non-agricultural businesses in Indonesia,
but most are small businesses.[fn::https://tirto.id/indonesia-kini-punya-2671-juta-perusahaan-cnz4]
** Diversifikasi: Buat PT baru vs ubah akta pendirian
** Ownership graph must be acyclic
* Hukum acara
** Meterai
- Meterai adalah syarat supaya pengadilan menerima suatu dokumen sebagai alat bukti.
- Ketiadaan meterai tidak mengubah keabsahan suatu perjanjian, tapi surat perjanjian tanpa meterai tidak bisa dijadikan alat bukti di pengadilan.
- Surat perjanjian tanpa meterai dapat dijadikan alat bukti di pengadilan dengan pemeteraian kemudian,
  tapi tata caranya tidak jelas, jadi lebih baik /setiap surat yang mungkin dijadikan alat bukti di pengadilan dimeteraikan sejak awal/.
- Apa gunanya surat perjanjian kalau tidak bisa digunakan sebagai alat bukti oleh pengadilan?
- Lihat juga
  [fn::http://www.hukum123.com/mengapa-kita-harus-menggunakan-materai-2/]
  [fn::https://www.hukumonline.com/klinik/detail/lt51426f0a4f0ee/fungsi-meterai-]
* Anggaran Dasar
** Definisi
Perusahaan adalah PT ... yang beralamat di ...
** Maksud dan tujuan
1. Bertahan hidup.
** Jangka waktu
1. Perusahaan mulai berdiri pada tanggal ...
** Modal
1. Modal Dasar Perusahaan berjumlah Rp 100.000.000 (seratus juta rupiah).
* Aturan Tambahan
** Tentang Aturan Tambahan
1. Direksi berwenang mengubah Aturan Tambahan.
2. Aturan Tambahan bukan bagian Anggaran Dasar.
** Saham
1. Perusahaan tidak mengeluarkan surat saham.
2. Bukti kepemilikan adalah Anggaran Dasar.
** Direksi
1. Direksi tidak membuat rencana kerja tahunan.
2. Direksi menentukan atau mengubah cita-cita perusahaan.
** Daftar Hitam
1. Perusahaan menyimpan Daftar Hitam.
2. Direksi berwenang mengubah isi Daftar Hitam.
3. Daftar Hitam berisi orang-orang yang pernah merugikan, menipu, atau mengkhianati Perusahaan.
4. Daftar Hitam mengandung nomor KTP, nama, alamat, foto KTP, deskripsi kerugian.
5. Daftar Hitam dipublikasikan di Internet.
6. Perusahaan secepatnya memutuskan semua perjanjian dengan orang dalam Daftar Hitam.
7. Perusahaan tidak membuat perjanjian dengan orang dalam Daftar Hitam.
** Principles
1. There should be at most one way to do something.
* Benefiting from the state, for Indonesians
lelang barang sitaan KPK, BRI, dll. (tanah murah, mobil murah)
https://lelang.go.id/
