#+TITLE: What kind of world are we living in?
#+DATE: 2018-05-29 02:37 +0700
#+PERMALINK: /world.html
* Overview of the 21st century
   :PROPERTIES:
   :CUSTOM_ID: overview-of-the-21st-century
   :END:

- [[https://en.wikipedia.org/wiki/21st_century][WP:21st century]]
- [[https://en.wikipedia.org/wiki/21st_century_skills][WP:21st century skills]]

Our descendants will think we are insane, as we 21st century people think our
[[https://en.wikipedia.org/wiki/Dark_Ages_(historiography)][WP:Dark Ages]]
ancestors are insane.

* Discouraging things
   :PROPERTIES:
   :CUSTOM_ID: discouraging-things
   :END:

** The average person is worth more dead than alive.
    :PROPERTIES:
    :CUSTOM_ID: the-average-person-is-worth-more-dead-than-alive.
    :END:

The organs of an average person are worth more than that person living.

** Healthcare is expensive.
    :PROPERTIES:
    :CUSTOM_ID: healthcare-is-expensive.
    :END:

[[https://arstechnica.com/tech-policy/2018/04/curing-disease-not-a-sustainable-business-model-goldman-sachs-analysts-say/][Curing disease is not a sustainable business model]]

** Distrust is the norm.
    :PROPERTIES:
    :CUSTOM_ID: distrust-is-the-norm.
    :END:

The 21st century is full of hoaxes, fake news, and disinformation spreading via the Internet,
especially social media and chats.

** Slavery is alive and kicking.
    :PROPERTIES:
    :CUSTOM_ID: slavery-is-alive-and-kicking.
    :END:

K-pop is slavery.

- [[https://en.wikipedia.org/wiki/Slave_Contract][WP:Slave contract]]
- [[https://www.youtube.com/watch?v=J8LxORztUWY][YT:The Late Capitalism of K-Pop]]
- [[https://www.youtube.com/watch?v=ClVqqJ3Peuc][YT:The Dark Side Of Being A K-Pop Star]]
- [[https://www.youtube.com/watch?v=8NcTeIVUXyE][YT:Inside The Lives Of The World's Most Famous K-Pop Stars]]

** Big cyber crimes
    :PROPERTIES:
    :CUSTOM_ID: big-cyber-crimes
    :END:

- 2016

  - [[https://www.youtube.com/watch?v=Usu9z0feHug][The $1,000,000,000 North Korean Bank Heist - YouTube]]

    - [[https://en.wikipedia.org/wiki/Bangladesh_Bank_robbery][Bangladesh Bank robbery - Wikipedia]]

* Encouraging things
   :PROPERTIES:
   :CUSTOM_ID: encouraging-things
   :END:

- [[https://www.youtube.com/watch?v=gysKE3POUv0][YT:China is beyond cashless]]
* Rejecting reality?
In year 1000 AD who would have thought that 1000 years later we would have AI deepfakes,
human sex change (sex reassignment surgery, hormone therapy),
and what else reality-bending technologies we have.

In 2018 those technologies aren't perfect.
We can see deepfake artifacts.
We can tell apart transsexuals from their hips.
Maybe in the future those technologies will be perfected.
Maybe in the future people can be whoever they want to be.
"You are who you want to be" is getting more literal.

When that time comes, we will have more respect for philosophers.
If everything is easy to fake, then what is real, and how do we know it's real?
If everything is easy to fake, then what can be taken as proof in court?
What really exists?
If a man can easily become a woman, and a woman can easily become a man, then what does it mean to be a man/woman?
Do ID cards still make sense if you are immortal and you change your identity every 6 months?
Technology will force us to deal with ontology and epistemology.

Reality discontents humans.
We work hard to deceive our senses so that we can escape reality.
We try to make imagination real, and make reality irrelevant.
The Matrix is getting real.
