#!/bin/bash
# why does xelatex produce thicker glyphs on okular?
# https://tex.stackexchange.com/questions/305258/xelatex-font-rendering-tend-to-be-slightly-bolder-compared-to-pdflatex
latex=pdflatex
#latex=xelatex
name="$1"
set -e
$latex -output-directory out "$name"
if [ -z "$quick" ]; then
    (cd out && BIBINPUTS=.. bibtex "$name")
    (cd out && makeindex "$name")
    $latex -output-directory out "$name"
    $latex -output-directory out "$name"
fi
