#!/bin/bash

# Usage:
# ./lookup STRING
# where STRING is a Japanese word or phrase.

# Example:
# STRING can be a character in the CJK Unified Ideograph Unicode block.

# Environment variables:
# v=1 show only verbs
# u=1 show non-P

# For the documentation of EDICT Japanese dictionary, see:
# http://www.edrdg.org/jmdict/edict_doc.html

# Example:
# v=1 ./lookup 愛

filter_verb ()
{
    if [ "$v" = 1 ]; then
        grep '(v'
    else
        cat
    fi
}

filter_common ()
{
    if [ "$u" != 1 ]; then
        grep '(P)'
    else
        cat
    fi
}

grep "$1" /usr/share/gjiten/dics/edict | filter_common | filter_verb
echo '======================================================================'
grep "$1" /usr/share/gjiten/dics/kanjidic
